### ISSUE TITLE
Regression: aws-sdk s3.upload broken starting with RELEASE.2019-02-06T21-16-36Z

### ISSUE THREAD

**Issue by mramato** [minio/minio#7289]
This is the first issue I've submitted, so please let me know if I missed any critical info.  Thanks for the great project!

## Expected Behavior

Using `aws-sdk-js`, calls to `s3.upload` inside of a browser should succeed and perform a multi-part upload.

## Current Behavior

Starting with RELEASE.2019-02-06T21-16-36Z, calls to `s3.upload` have stopped working with the following error:

> ETagMissing: No access to ETag property on response. Check CORS configuration to expose ETag header.

Everything works fine with RELEASE.2019-01-31T00-31-19Z and older. Nothing in the release notes pointed me to what the problem could be.

## Steps to Reproduce (for bugs)

1. Run a basic minio server (We use Docker)
2. Use s3.upload to upload a large file (anything over 5MB should trigger multi-part)
3. The upload will fail with the above error

## Context

Minio has always maintain `aws-sdk-js` compatibility, which is important to us since we use minio as a local dev server for s3-based production environments.

## Regression

Yes, this is a regression, RELEASE.2019-02-06T21-16-36Z fails, RELEASE.2019-01-31T00-31-19Z passes

## Your Environment

* Version used (`minio version`):  RELEASE.2019-02-20T22-44-29Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): Linux 2e487f95993a 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Most probably related to 

```
commit df418a2783269e81b19e35ab77cfa3691758003a
Author: kannappanr <30541348+kannappanr@users.noreply.github.com>
Date:   Tue Feb 5 14:06:52 2019 -0800

    Create Cors handler with permissive configuration (#7186)
    
    Create new Cors handler allowing all origins with all standard
    methods with any header and credentials.
    
    Fixes #7181
```

**Comment by mramato** [comment]
Thanks for the quick reply.  Please let me know if there's anything else I can do to help.

**Comment by kannappanr** [comment]
@mramato  I ran minio in fs mode and tried reproducing this inside a browser and was unable to do so. What mode are you running minio in?

**Comment by kannappanr** [comment]
@mramato Can you please provide us with a sample code to reproduce your issue?

**Comment by mramato** [comment]
Looking into it, I'm was a bit under the weather so I apologize for not replying sooner.

**Comment by kannappanr** [comment]
@mramato Did you get a chance to create a sample code? Will really appreciate if you can create one to reproduce the issue.

**Comment by kanagarajkm** [comment]
@kannappanr i could reproduce this issue. https://jsbin.com/danoqokuwe/edit?html,js,output . Try uploading a bigger file (40MB). You can see `ERROR: No access to ETag property on response. Check CORS configuration to expose ETag header.` printed on the browser console.

**Comment by nguyengiavu** [comment]
Notice, if partSize >= fileSize (upload file) => Successful upload.

**Comment by neben** [comment]
The problem boils down to the `ETAG` header not being exposed via `access-control-allow-headers` anymore, which is a regression.  You can see that with any `GET` request, no matter the size.

<img width="362" alt="image" src="https://user-images.githubusercontent.com/1236695/53797712-06b83f00-3f37-11e9-990a-3bf9f833a153.png">

**Comment by neben** [comment]
I downgraded our container to `RELEASE.2019-01-31T00-31-19Z` and it works again as expected.

<img width="490" alt="image" src="https://user-images.githubusercontent.com/1236695/53799393-91e70400-3f3a-11e9-94a5-6f9d8dcab6fb.png">

**Comment by neben** [comment]
On a slightly different note, `access-control-allow-origin` used to echo the correct origin (`RELEASE.2019-01-31T00-31-19Z`), now (current release) it only returns `*`. Not sure if this was changed on purpose.

**Comment by mramato** [comment]
Sorry again for the delay, here's a full simplified reproduction: [7289.zip](https://github.com/minio/minio/files/2931317/7289.zip)

I used Docker for the minio image and a simple HTML app for the test code (it relies on aws-sdk).

1. Unpack zip
2. Run `docker-compose up -d` to start minio at `http://localhost:9000` with credentials `aws_key`/`aws_secret`.
3. Create a test bucket using the following command:
```
AWS_ACCESS_KEY_ID=aws_key AWS_SECRET_ACCESS_KEY=aws_secret aws s3 mb s3://test.bucket --endpoint http://localhost:9000
```
4. Run `npm install` to download the AWS SDK being used by the app.
5. Open `index.html` and drag and drop any file over 5MB (the one I used was ~60)

It will write to page as it's uploading and then fail.  Switch back to RELEASE.2019-01-31T00-31-19Z  and it will work.

**Comment by bagr001** [comment]
Exposing ETag is necessary for multipart uploads. We are using multipart uploads directly from the browser which is currently blocking you from reading unexposed headers.

**Comment by mramato** [comment]
Thanks again for the quick turnaround!  I'll give it a spin next release.

**Comment by neben** [comment]
This does solve the issue in Chrome, however, it still breaks Firefox. Firefox does not support wildcard values for `access-control-expose-headers`, and thus does not give access to the `ETAG` value of the response (Firefox [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1309358)). It would be great if you could revert to the old behaviour and list allowed headers explicitly instead of the wildcard.

**Comment by YannicEl** [comment]
adding this line to the CORS Rules of my bucket fixed it for me.
`<ExposeHeader>ETag</ExposeHeader>`

complete file:
 `<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <ExposeHeader>ETag</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>`

**Comment by ijajmulani** [comment]
> This does solve the issue in Chrome, however, it still breaks Firefox. Firefox does not support wildcard values for `access-control-expose-headers`, and thus does not give access to the `ETAG` value of the response (Firefox [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1309358)). It would be great if you could revert to the old behaviour and list allowed headers explicitly instead of the wildcard.

Is this solve I am also facing same issue. 
I can't read response etag in firefox.

**Comment by ijajmulani** [comment]
> adding this line to the CORS Rules of my bucket fixed it for me.
> `<ExposeHeader>ETag</ExposeHeader>`
> 
> complete file:
> `<?xml version="1.0" encoding="UTF-8"?> <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"> <CORSRule> <AllowedOrigin>*</AllowedOrigin> <AllowedMethod>POST</AllowedMethod> <AllowedMethod>GET</AllowedMethod> <AllowedMethod>PUT</AllowedMethod> <AllowedMethod>DELETE</AllowedMethod> <AllowedMethod>HEAD</AllowedMethod> <ExposeHeader>ETag</ExposeHeader> <AllowedHeader>*</AllowedHeader> </CORSRule> </CORSConfiguration>`

it did not work in firefox. when I upload large file.

**Comment by harshavardhana** [comment]
Please open a new issue, this issue is resolved and old.
