### ISSUE TITLE
Wrong returncode for GetObject-Request with If-Match and Range-Header

### ISSUE THREAD

**Issue by WolfgangVogl** [minio/minio#7292]
If you specify a GetObject-Request with the Range- and  the If-Match-Header set but a "wrong" ETAG and a range value that is out of range then the server returns a http 416 status code (range not satisfiable) instead of a http 412 status code (precondition failed).

## Expected Behavior

I expect  to get a http returncode 412 due to https://tools.ietf.org/html/rfc7232#section-3.1 that states that the server must return precondition failed OR one of the 2xx (Successful) status codes.

## Current Behavior

I'm getting the status code 418 (range not satisfiable).

## Steps to Reproduce (for bugs)

1. Getting the first 5 KB of a file with a GetObject-Request and the RANGE Header set
2. Getting n parts of the same object by using more GetObject-Requests with the RANGE- and the IF-Match-Header set
3. Change the file on the Server (PutObject-Request) with a smaller one
4. Try to get another part of  the origin file by a GetObject-Request with a Range higher than the size of the new file and the IF-Match Header with the ETAG of the initial version.

## Context
I tried to download parts of an object by using multiple GetObject-Requests with the
Range- and  the IF-Match-header set. To ensure to get the correct version (or an proper error code) I send the IF-Match header with the ETAG of the initial response.
For the first parts my ETAG ist correct but while downloading it happened that the file on the server was replaced. Now my ETAG is wrong but instead of getting a 412 I receive a 416 since my requested range value is higher than the size of the new file.

## Your Environment

* Version used (`minio version`): 2019-02-14T00:21:45Z
* Environment name and version (e.g. nginx 1.9.1): windows commandline
* Operating System and version (`uname -a`): Windows 10

**Comment by nitisht** [comment]
@WolfgangVogl can you pls help us a reproducer for this issue

**Comment by harshavardhana** [comment]
have you tested this with AWS S3 @WolfgangVogl ? - The server behavior is rejecting Range request first than If-Match. 

I do not see that being stated in HTTP RFC can you clarify?

**Comment by WolfgangVogl** [comment]
Hello @harshavardhana, I've tested with AWS S3 and got the expected http 412.

In rfc7232 section 3.1 the text states:
"The "If-Match" header field makes the request method conditional..."
"... since **the client intends this precondition to prevent the method from being applied** if there have been any changes to the representation data."
"An origin server that receives an If-Match header field **MUST evaluate the condition prior to performing the method** (Section 5)."
(emphasis mine)
I think as if-match is a **pre**condition the evalution is before the evaluation of the method and with this in mind it is before the evaluation of the range.

@nitisht - I'll try - Is there a tutorial or some help how to create a test or something like that for this project?

**Comment by nitisht** [comment]
> I'll try - Is there a tutorial or some help how to create a test or something like that for this project?

You can use the same test code / tool that you're using with S3

**Comment by WolfgangVogl** [comment]
I don't think this helps that much but here's the code:
```
TEST_CASE("S3Filesystem - Download file while overwritting it", "[.VerySlow][.integration][s3]")
{
   auto conf = getConf();
   S3Filesystem s3(conf);

   std::string filenameOrg = "just/a/file/that/gets/overwritten.bin";
   auto fileSize = service::MegaBytes(11);

   auto filepathOrg = buildPathWithBucket(conf, filenameOrg);

   REQUIRE_NOTHROW(s3.remove(filepathOrg));
   REQUIRE_FALSE(s3.exists(filepathOrg));

   service::uploadFile(s3, filepathOrg, fileSize);
   REQUIRE(s3.exists(filepathOrg));
   REQUIRE(s3.fileSize(filepathOrg) == fileSize.get() * 1024 * 1024);

   auto fileSource = s3.openFileForRead(filepathOrg);
   auto readBufferSize = service::Bytes{service::KiloBytes{500}}.get();
   std::vector<char> buffer(readBufferSize);

   size_t readTotal{0};
   auto& dataStream = fileSource->stream();
   auto overwritten{false};
   auto readUntilEnd = [&dataStream, &buffer, readBufferSize]() {
      while (dataStream.good())
      {
         dataStream.read(buffer.data(), readBufferSize);
      }
   };

   while (dataStream.good())
   {
      if (!overwritten && readTotal > service::Bytes{service::MegaBytes{3}}.get())
      {
         service::FileContentGenerator gen;
         auto newFileSink = s3.openForCreateOrOverwrite(filepathOrg);
         for (auto partNr{0}; partNr < 10; partNr++)
            newFileSink->stream() << gen.generate(service::KiloBytes{30});
         overwritten = true;
      }

      if (!overwritten)
         dataStream.read(buffer.data(), readBufferSize);
      else
         REQUIRE_THROWS(readUntilEnd());

      auto bytesRead = static_cast<size_t>(dataStream.gcount());
      readTotal += bytesRead;
   }
   REQUIRE_NOTHROW(s3.remove(filepathOrg));
}
```

**Comment by sinhaashish** [comment]
@WolfgangVogl : I tried the below mentioned steps
1. Ran the code 
```
s3Client, err := minio.New("localhost:9000", "minio", "minio123", false)
	if err != nil {
		log.Fatalln(err)
	}
	opts := minio.GetObjectOptions{}
	opts.SetMatchETag("c3e7f310e9c29c860ff4c6e1c64fdf32")
	opts.SetRange(70, 80)

	s3Client.TraceOn(os.Stderr)

	if err := s3Client.FGetObject("<<bucket>>", "sample.txt", "/my-test.txt", opts); err != nil {
		log.Fatalln(err)
	}
	log.Println("Successfully saved my-filename.csv")
```
2. Replaced the object with a smaller size and ran the same code ..i.e. without changing the `etag` . 
3. Got the response as 
```
---------START-HTTP---------
HEAD /sinha/sample.txt HTTP/1.1
Host: localhost:9000
User-Agent: Minio (linux; amd64) minio-go/v6.0.19
Authorization: AWS4-HMAC-SHA256 Credential=minio/20190301/us-east-1/s3/aws4_request, SignedHeaders=host;if-match;range;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
If-Match: "c3e7f310e9c29c860ff4c6e1c64fdf32"
Range: bytes=70-80
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190301T093156Z

HTTP/1.1 412 Precondition Failed
Connection: close
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 01 Mar 2019 09:31:56 GMT
Etag: "eeb9bd89fad52e37525d9ad21858bf5d"
Last-Modified: Fri, 01 Mar 2019 09:31:48 GMT
Server: Minio/DEVELOPMENT.GOGET
Vary: Origin
X-Amz-Request-Id: 1587CBD5F806008D
X-Minio-Deployment-Id: fa56fe1d-7341-4e45-b25b-fa2f277112bb
X-Xss-Protection: 1; mode=block
---------END-HTTP---------
2019/03/01 15:01:56 At least one of the pre-conditions you specified did not hold
exit status 1

```
For this example its returning `412` as the error code. Can you explain the steps so that i can replicate it.

**Comment by WolfgangVogl** [comment]
I think the replacement file must be smaller than the range you request...Am 01.03.2019 10:41 vorm. schrieb Ashish Kumar Sinha <notifications@github.com>:@WolfgangVogl : I tried the below mentioned steps
Ran the code
	if err != nil {
		log.Fatalln(err)
	}
	opts := minio.GetObjectOptions{}
	opts.SetMatchETag("c3e7f310e9c29c860ff4c6e1c64fdf32")
	opts.SetRange(70, 80)

	s3Client.TraceOn(os.Stderr)

	if err := s3Client.FGetObject("<<bucket>>", "sample.txt", "/my-test.txt", opts); err != nil {
		log.Fatalln(err)
	}
	log.Println("Successfully saved my-filename.csv")

Replaced the object with a smaller size and ran the same code ..i.e. without changing the etag .Got the response as
HEAD /sinha/sample.txt HTTP/1.1
Host: localhost:9000
User-Agent: Minio (linux; amd64) minio-go/v6.0.19
Authorization: AWS4-HMAC-SHA256 Credential=minio/20190301/us-east-1/s3/aws4_request, SignedHeaders=host;if-match;range;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
If-Match: "c3e7f310e9c29c860ff4c6e1c64fdf32"
Range: bytes=70-80
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190301T093156Z

HTTP/1.1 412 Precondition Failed
Connection: close
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 01 Mar 2019 09:31:56 GMT
Etag: "eeb9bd89fad52e37525d9ad21858bf5d"
Last-Modified: Fri, 01 Mar 2019 09:31:48 GMT
Server: Minio/DEVELOPMENT.GOGET
Vary: Origin
X-Amz-Request-Id: 1587CBD5F806008D
X-Minio-Deployment-Id: fa56fe1d-7341-4e45-b25b-fa2f277112bb
X-Xss-Protection: 1; mode=block
---------END-HTTP---------
2019/03/01 15:01:56 At least one of the pre-conditions you specified did not hold
exit status 1


For this example its returning 412 as the error code. Can you explain the steps so that i can replicate it.

**Comment by sinhaashish** [comment]
@WolfgangVogl  The new file used is of smaller size than the range request. You can connect on slack to help us reproduce the issue.

**Comment by donatello** [comment]
> HEAD /sinha/sample.txt HTTP/1.1

@sinhaashish The library is doing a HEAD before the GET and the precondition error is coming from that.

We get InvalidRange error instead of Precondition failed on a direct get (for e.g. with aws cli).

**Comment by donatello** [comment]
The bug is that the range is validated on the server, before the pre-conditions.

**Comment by harshavardhana** [comment]
@sinhaashish are you planning to send a fix?
