### ISSUE TITLE
recover access and secret keys from erasure encoded config.json 

### ISSUE THREAD

**Issue by timhughes** [minio/minio#7297]
When creating servers from a script I cannot get the access and secret keys. They dont appear in the logs and dont appear on screen.

## Expected Behavior
I expected them info to be redirected in to the logs in the following script. 

## Current Behavior
I don't know how to get the login access and secret keys. If this was a non erasure encoded file I know I can get it from `config.json` but when that is a binary blob split over multiple places it is hard to reconstruct. 

## Possible Solution

The simplest solution would be to put something in the docs on how to recover it or how to get it in the first place under these circumstances.

## Steps to Reproduce (for bugs)

```
#!/usr/bin/env bash

DISKS=4
mkdir -p ./minio_root/logs/
for i in 1 2 3; do
    disks=''
    for d in `seq 1 ${DISKS}`; do 
        disks="$disks ./minio_root/disk${d}/data/tenant${i}"
    done
    minio server --address :900${i} $disks 2>&1 >> ./minio_root/logs/tenant${i}.log &
done
```

## Context

The context here could just be me not reading the correct documentations 

## Your Environment

```
hughest@argon [0] $ minio version 
Version: 2019-02-26T19:51:46Z
Release-Tag: RELEASE.2019-02-26T19-51-46Z
Commit-ID: 78d116c487278350406e8957d7d35e47caa963d6
```
```
hughest@argon [0] $ mc version
Version: 2019-02-20T22:21:50Z
Release-tag: RELEASE.2019-02-20T22-21-50Z
Commit-id: e538599e2ffa4ee8d8040d5cd14475b380da531a
```

**Comment by harshavardhana** [comment]
Distributed mode can never be started without access and secret in environment variables. 

So it is on purpose that it's not visible anymore on the console.

**Comment by kannappanr** [comment]
@timhughes Closing this issue as answered. Please feel free to reach to us if you have further questions.

**Comment by timhughes** [comment]
@kannappanr thanks. I think what confused me is the text on this page which calls my style of deployment "standalone" and doesn't mention needing the environment variables. Further down it say that you need the keys in environment variables for distributed. Perhaps some mention in the standalone section will stop you getting this question again. 

https://docs.minio.io/docs/multi-tenant-minio-deployment-guide.html#standalone-deployment

**Comment by kannappanr** [comment]
@timhughes Sorry, did not look at your setup properly. Yours is not a distributed setup, but a multi-tenant local erasure coded setup. The issue here is that we do not print `access key` and `secret key` information, if the output is redirected to a log. 

So, you have two options

1. Set an environment variable. Then you know what your access and secret keys are.
2. Use the following script to see the credentials printed on your screen. If you see it once, then you can note it down and then go back to using your originial script.

```
#!/usr/bin/env bash

DISKS=4
mkdir -p ./minio_root/logs/
for i in 1 2 3; do
    disks=''
    for d in `seq 1 ${DISKS}`; do 
        disks="$disks ./minio_root/disk${d}/data/tenant${i}"
    done
    minio server --address :900${i} $disks &
done

```

**Comment by timhughes** [comment]
Cool much appreciated 👍
