### ISSUE TITLE
How can I read Minio data from Streamsets using Amazon S3?

### ISSUE THREAD

**Issue by bellship** [minio/minio#7303]
I couldn't run from Amazon S3(Origin) to mongoDB(Destination) at the Streamsets Pipline.

## Expected Behavior

my specific MongoDB's collection will be updated(insert) from data that is in minio storage.
and It's executed by Streamsets running.
JSON file that fitted my mongoDB collection uploaded at Minio
A streamsets pipline flow is approximately that Origin is Amazon S3 (for minio's s3 protocol) and Destination is MongoDB.

## Current Behavior

I did alter almost every parameter I can do to Streamsets' configuration.
I cannot make narrow Issue .. :-(

## Possible Solution

First, alter Streamsets's configuration
Second, alter minio's s3cmd or etc configuration

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`): Version: 2019-02-20T22:44:29Z Release-Tag: RELEASE.2019-02-20T22-44-29Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: linux amd74 
* Operating System and version (`uname -a`):centos7.4
* Link to your project:
![image 1](https://user-images.githubusercontent.com/37265872/53478656-4383c200-3a6f-11e9-9137-327013d9ce5a.png)
![image](https://user-images.githubusercontent.com/37265872/53478666-48e10c80-3a6f-11e9-839c-47db28b24b6d.png)

**Comment by bellship** [comment]
![imge3](https://user-images.githubusercontent.com/37265872/53484226-3b318400-3a7b-11e9-97b1-af22a978dadf.PNG)

In this picture, there is success log when Streamsets ran pipline from mongoDB(Origin) to AmazonS3(Destination).

I hope it supports you :-)

**Comment by nitisht** [comment]
thanks @bellship we'll take a look soon

**Comment by nitisht** [comment]
Based on Slack discussion, the `marker` and `prefix` should be in order. 

quoting from @harshavardhana here

> When `prefix=US/` then marker either can be `US/test-user1.json` or `US/someotherdir/file.json` otherwise we reject such operations as they are frivolous and always point to application bug.

**Comment by harshavardhana** [comment]
Closing this as issue is a bug in the application.
