### ISSUE TITLE
codebase imports an old repository github.com/coreos/etcd

### ISSUE THREAD

**Issue by chrischdi** [minio/minio#7304]
## Expected Behavior
* `import _ "github.com/minio/minio"`
* `import _ "go.etcd.io/etcd"`
* `go test ./...`

## Current Behavior
Running go tests outputs the following:
```
$ go test ./...                                                                                                                                                                
2019/02/27 14:02:13 proto: duplicate proto type registered: authpb.User
2019/02/27 14:02:13 proto: duplicate proto type registered: authpb.Permission
2019/02/27 14:02:13 proto: duplicate proto type registered: authpb.Role
panic: proto: duplicate enum registered: authpb.Permission_Type

goroutine 1 [running]:
github.com/golang/protobuf/proto.RegisterEnum(...)
        /home/vagrant/go/pkg/mod/github.com/golang/protobuf@v1.2.0/proto/properties.go:458
go.etcd.io/etcd/auth/authpb.init.0()
        /home/vagrant/go/pkg/mod/go.etcd.io/etcd@v0.0.0-20180904210406-1df1ddff4361/auth/authpb/auth.pb.go:103 +0x1d7
FAIL    stash.detss.corpintra.net/dhc/t1        0.009s
```

## Possible Solution
Migrate etcd dependency from `github.com/coreos/etcd` to `go.etcd.io/etcd`.
This is what the etcd team has done due to repository migration: https://github.com/etcd-io/etcd/issues/9965

## Steps to Reproduce (for bugs)
use [gist](https://gist.github.com/chrischdi/b632cfae6bb3dac06790ae50f933101b)
`go test ./...`

## Context
We fixed it by on the following fork: If it is ok I would create a PR for it:
https://github.com/c445/minio/tree/revendor-etcd

## Your Environment
```
$ uname -a
Linux archlinux 4.20.12-arch1-1-ARCH #1 SMP PREEMPT Sat Feb 23 15:11:34 UTC 2019 x86_64 GNU/Linux
$ go version
go version go1.11.5 linux/amd64
```

**Comment by kannappanr** [comment]
@chrischdi Please go ahead and create a PR.

**Comment by kannappanr** [comment]
Closing this issue as `minio` currently uses the latest repo

**Comment by chrischdi** [comment]
@kannappanr : the current master still imports and uses the deprecated `github.com/coreos/etcd` which is fine as long as you v3.3.12 is used . 
Just like mentioned in https://github.com/etcd-io/etcd/issues/10398#issuecomment-469439257 : beginning with v3.4 the dependency should be changed to go.etcd.io/etcd :-)

**Comment by harshavardhana** [comment]
> @kannappanr : the current master still imports and uses the deprecated `github.com/coreos/etcd` which is fine as long as you v3.3.12 is used .
> Just like mentioned in [etcd-io/etcd#10398 (comment)](https://github.com/etcd-io/etcd/issues/10398#issuecomment-469439257) : beginning with v3.4 the dependency should be changed to go.etcd.io/etcd :-)

We are not planning to change that, we tried we saw many of our existing deps haven't moved. So we won't move either - we will come to that when we do @chrischdi

**Comment by keirafadams** [comment]
I'm not 100% sure this is related to the same issue, but if I try to fully install from source (e.g. clone the git repo, but also get the relevant dependent modules) I can't install my modified version of minio, and get bombarded with errors of the form.

`cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc...`

I can potentially hack around this by updating the imports manually, but as is, this breaks things when we try to keep our forks up to date.

**Comment by harshavardhana** [comment]
We use go mod, if you are modifying the code you need to make sure to stick to go mod behavior otherwise you will see issues.

**Comment by keirafadams** [comment]
Understood, thanks.
