### ISSUE TITLE
Hang when recursive delete of large bucket on a cluster

### ISSUE THREAD

**Issue by nneul** [minio/minio#7319]
When doing a recursive rm of a large bucket (few thousand small files), the operation frequently hangs after 1000 objects are processed.

Report sounds just like #6166 - I am running a version a little older than that one, but also reproduced with a fresh download today. (RELEASE.2019-02-26T19-51-46Z on ubuntu 16 x64)

Disk IO and cpu are near zero on the servers, no resource constraints that I can see at all. 

Test scenario was just to create:  bucket/{0-20}/{0-20}/{0-20}.txt with small files (few bytes each), and then do a recursive rm. 

On _some_ invocations it seems like it would hang for a bit, and then start working again, on others it would hang for multiple minutes before terminating the request. 

I'm not seeing any hangs (other than momentary in each batch) when doing a mc find. 

The setup is a 2 machine cluster, each with two drives, backing store SSD. Delete being requested from a third system. All on same network. 

My workaround right now is going to try to not use the mc rm recursive to do the deletes, but would be nice to get this fixed.

**Comment by nneul** [comment]
Changing my code to stream a find to rm calls in batches no longer shows the hang that is present with a rm recursive.

**Comment by harshavardhana** [comment]
Thanks for the report @nneul we will take a look

**Comment by nneul** [comment]
I got another report of problems from one of my coworkers after I put workaround in place - the user said it looked like it hung completely, even doing the small batch deletes. 

What I was able to determine from the new report was - it was not fully hanging, but it was running insanely slow. (20 minutes to delete 250 objects!)

What I found out from the user is that there is a directory in their cluster with 1.5 million files in it. Now, your immediate reaction would be "yeah, that's going to make any filesystem horribly slow". BUT - I'm not seeing that. Operations against the directory directly on the backend (temporary/other files - not touching minio's content) - all were very fast with no delays. 

A very inefficient shell loop create of 10000 new dirs, each with a file in them took about 24 seconds. Deletion of that same tree took 12 seconds. I've seen large-dir performance degradation in the past with old filesystems where single deletes took seconds - but clearly not seeing that here.  

Is there anything inherent in minio that degrades when deleting large directories or might result in running out of resources causing any sort of lock/coordination issues when synchronizing the clusterwide delete? What external resources (shm, locks, fd's, etc.) would you expect to spike during that sort of operation?

**Comment by nneul** [comment]
I think I see the issue - running an strace against minio - it appears to be doing repeated reads of the entire directory during file removals. If this is occurring on every object removal, this is essentially an exponential operation.

Is there something that is designed to do this, or something that is unintentionally reloading directory contents (say due to some sort of lazy loading and expiration due to the size of the dir and time it takes to load it's entries?)

**Comment by nneul** [comment]
In a particular strace that I ran for about 20-30 seconds - saw 55 unlink operations, and 1590 getdents64 system calls.

**Comment by nneul** [comment]
Note - this IS with an older build from mid last year... it's a pain in our product release cycle to update at this point, but if you are highly confident that something like this has already been fixed, I will see what we can do about updating and trying the test scenario again.

**Comment by poornas** [comment]
mc rm lists 1000 objects at a time and batch deletes them, which explains the repeated dir reads - it isn't expected to hang. What is your version of minio server?

**Comment by tholu** [comment]
I can confirm a very high IO load with Minio deployed via docker, when removing a prefix containing some ten thousand files via the Webinterface. The files are organized hash-based 5 subfolders deep (like `a/1/2/b/d`) below the prefix, so there is no directory containing lots of images.

Latest version: `2019-02-26T19:51:46Z`

**Comment by nneul** [comment]
So in my workaround - I was doing a 'mc find' in one process, and then submitting individual 'mc rm' calls with 250 files each listed without --recursive. That was to work around the (apparent) hang doing the recursive deletes. 

I'm not seeing high IO load at all... I think the getdents64() is probably coming straight out of kernel memory, so it's never touching the disk. If it were a high disk IO load, that would make more sense. 

I would not expect a file based 'rm' call to be doing a directory list operation unless I asked it to do the recursive delete - which this workaround is not doing. 

Current build the server is running RELEASE.2018-06-22T23-48-46Z

When I was testing the workaround (two process list+chunked deletes) with a smaller (20*20*20) tree of files and saw the hangs with mc rm recursive, I re-tested and saw the same hang with both that version and with a current download of minio + mc.

**Comment by poornas** [comment]
@nneul, I tested with a 4 node minio setup and did a recursive delete on a deeply nested dir (~ 10 level tree) of ~400000 files 26 bytes each and wasn't able to repro any hang on mc (running on the same machine). Is it possible to get the server side trace when it hangs? (You can set  MINIO_HTTP_TRACE=/tmp/outfile env variable, then start minio server). How good is your network (seems like the mc client is on a different machine)?
```
➜  mc git:(master) ✗ mc ls --r myminio-ssl/bucket1 | wc -l      
406411
➜  mc git:(master) ✗ mc rm --r --force myminio-ssl/bucket1/  23.40s user 2.44s system 5% cpu 7:55.53 total
tee ../output.file  0.14s user 1.72s system 0% cpu 7:55.53 total
```

**Comment by nneul** [comment]
All three VMs involved (srv + srv + client) were on the same vmware host, so it never even hit the physical network. 

I'll see what I can do on that http trace option.

**Comment by nneul** [comment]
Here's a filtered snippet of the trace - note the time stamps between each delete. If you can send me (nneul@neulinger.org) a contact email, I'll share the actual file with you, but would rather not post full contents. 

```
[REQUEST (objectAPIHandlers).ListBucketsHandler-fm] [155190566.578487] [2019-03-06 20:54:25 +0000]
[RESPONSE] [155190566.578487] [2019-03-06 20:54:25 +0000]
[REQUEST (objectAPIHandlers).ListObjectsV1Handler-fm] [155190562.832065] [2019-03-06 20:53:48 +0000]
[RESPONSE] [155190562.832065] [2019-03-06 20:54:38 +0000]
[REQUEST (objectAPIHandlers).ListObjectsV1Handler-fm] [155190566.578609] [2019-03-06 20:54:25 +0000]
[RESPONSE] [155190566.578609] [2019-03-06 20:54:44 +0000]
[REQUEST (objectAPIHandlers).GetBucketLocationHandler-fm] [155190568.446454] [2019-03-06 20:54:44 +0000]
[RESPONSE] [155190568.446454] [2019-03-06 20:54:44 +0000]
[REQUEST (objectAPIHandlers).ListObjectsV1Handler-fm] [155190568.446930] [2019-03-06 20:54:44 +0000]
[RESPONSE] [155190568.446930] [2019-03-06 20:54:55 +0000]
[REQUEST (objectAPIHandlers).ListObjectsV1Handler-fm] [155190569.554447] [2019-03-06 20:54:55 +0000]
[RESPONSE] [155190569.554447] [2019-03-06 20:55:06 +0000]
[REQUEST (objectAPIHandlers).HeadObjectHandler-fm] [155190570.655026] [2019-03-06 20:55:06 +0000]
[RESPONSE] [155190570.655026] [2019-03-06 20:55:06 +0000]
[REQUEST (objectAPIHandlers).DeleteMultipleObjectsHandler-fm] [155190570.655445] [2019-03-06 20:55:06 +0000]
[RESPONSE] [155190570.655445] [2019-03-06 20:55:08 +0000]
[REQUEST (objectAPIHandlers).ListObjectsV1Handler-fm] [155190570.867157] [2019-03-06 20:55:08 +0000]
[RESPONSE] [155190570.867157] [2019-03-06 20:55:20 +0000]
[REQUEST (objectAPIHandlers).HeadObjectHandler-fm] [155190572.004295] [2019-03-06 20:55:20 +0000]
[RESPONSE] [155190572.004295] [2019-03-06 20:55:20 +0000]
[REQUEST (objectAPIHandlers).DeleteMultipleObjectsHandler-fm] [155190572.004667] [2019-03-06 20:55:20 +0000]
[RESPONSE] [155190572.004667] [2019-03-06 20:55:20 +0000]
[REQUEST (objectAPIHandlers).ListObjectsV1Handler-fm] [155190572.005356] [2019-03-06 20:55:20 +0000]
[RESPONSE] [155190572.005356] [2019-03-06 20:55:31 +0000]
[REQUEST (objectAPIHandlers).HeadObjectHandler-fm] [155190573.135156] [2019-03-06 20:55:31 +0000]
[RESPONSE] [155190573.135156] [2019-03-06 20:55:31 +0000]
[REQUEST (objectAPIHandlers).DeleteMultipleObjectsHandler-fm] [155190573.135549] [2019-03-06 20:55:31 +0000]
[RESPONSE] [155190573.135549] [2019-03-06 20:55:31 +0000]
[REQUEST (objectAPIHandlers).ListObjectsV1Handler-fm] [155190573.136304] [2019-03-06 20:55:31 +0000]
[RESPONSE] [155190573.136304] [2019-03-06 20:55:42 +0000]
[REQUEST (objectAPIHandlers).HeadObjectHandler-fm] [155190574.297779] [2019-03-06 20:55:42 +0000]
[RESPONSE] [155190574.297779] [2019-03-06 20:55:42 +0000]
[REQUEST (objectAPIHandlers).DeleteMultipleObjectsHandler-fm] [155190574.298158] [2019-03-06 20:55:42 +0000]
[RESPONSE] [155190574.298158] [2019-03-06 20:55:42 +0000]
[REQUEST (objectAPIHandlers).ListObjectsV1Handler-fm] [155190574.298889] [2019-03-06 20:55:42 +0000]
[RESPONSE] [155190574.298889] [2019-03-06 20:55:53 +0000]
[REQUEST (objectAPIHandlers).HeadObjectHandler-fm] [155190575.346540] [2019-03-06 20:55:53 +0000]
[RESPONSE] [155190575.346540] [2019-03-06 20:55:53 +0000]
[REQUEST (objectAPIHandlers).DeleteMultipleObjectsHandler-fm] [155190575.346887] [2019-03-06 20:55:53 +0000]
[RESPONSE] [155190575.346887] [2019-03-06 20:55:53 +0000]
[REQUEST (objectAPIHandlers).ListObjectsV1Handler-fm] [155190575.347640] [2019-03-06 20:55:53 +0000]
[RESPONSE] [155190575.347640] [2019-03-06 20:56:04 +0000]
[REQUEST (objectAPIHandlers).HeadObjectHandler-fm] [155190576.482555] [2019-03-06 20:56:04 +0000]
[RESPONSE] [155190576.482555] [2019-03-06 20:56:04 +0000]
[REQUEST (objectAPIHandlers).DeleteMultipleObjectsHandler-fm] [155190576.482900] [2019-03-06 20:56:04 +0000]
[RESPONSE] [155190576.482900] [2019-03-06 20:56:04 +0000]
[REQUEST (objectAPIHandlers).ListObjectsV1Handler-fm] [155190576.483563] [2019-03-06 20:56:04 +0000]
[RESPONSE] [155190576.483563] [2019-03-06 20:56:15 +0000]
[REQUEST (objectAPIHandlers).HeadObjectHandler-fm] [155190577.599386] [2019-03-06 20:56:15 +0000]
[RESPONSE] [155190577.599386] [2019-03-06 20:56:15 +0000]
[REQUEST (objectAPIHandlers).DeleteMultipleObjectsHandler-fm] [155190577.599732] [2019-03-06 20:56:15 +0000]
[RESPONSE] [155190577.599732] [2019-03-06 20:56:16 +0000]
[REQUEST (objectAPIHandlers).ListObjectsV1Handler-fm] [155190577.600459] [2019-03-06 20:56:16 +0000]
[RESPONSE] [155190577.600459] [2019-03-06 20:56:27 +0000]
[REQUEST (objectAPIHandlers).HeadObjectHandler-fm] [155190578.727246] [2019-03-06 20:56:27 +0000]
[RESPONSE] [155190578.727246] [2019-03-06 20:56:27 +0000]
[REQUEST (objectAPIHandlers).DeleteMultipleObjectsHandler-fm] [155190578.727635] [2019-03-06 20:56:27 +0000]
[RESPONSE] [155190578.727635] [2019-03-06 20:56:27 +0000]
[REQUEST (objectAPIHandlers).ListObjectsV1Handler-fm] [155190578.728335] [2019-03-06 20:56:27 +0000]
[RESPONSE] [155190578.728335] [2019-03-06 20:56:38 +0000]
[REQUEST (objectAPIHandlers).HeadObjectHandler-fm] [155190579.856822] [2019-03-06 20:56:38 +0000]
[RESPONSE] [155190579.856822] [2019-03-06 20:56:38 +0000]
[REQUEST (objectAPIHandlers).DeleteMultipleObjectsHandler-fm] [155190579.857210] [2019-03-06 20:56:38 +0000]
[RESPONSE] [155190579.857210] [2019-03-06 20:56:38 +0000]
[REQUEST (objectAPIHandlers).ListObjectsV1Handler-fm] [155190579.857892] [2019-03-06 20:56:38 +0000]
[RESPONSE] [155190579.857892] [2019-03-06 20:56:49 +0000]
[REQUEST (objectAPIHandlers).HeadObjectHandler-fm] [155190580.971318] [2019-03-06 20:56:49 +0000]
[RESPONSE] [155190580.971318] [2019-03-06 20:56:49 +0000]
[REQUEST (objectAPIHandlers).DeleteMultipleObjectsHandler-fm] [155190580.971655] [2019-03-06 20:56:49 +0000]
[RESPONSE] [155190580.971655] [2019-03-06 20:56:49 +0000]
[REQUEST (objectAPIHandlers).ListObjectsV1Handler-fm] [155190580.972264] [2019-03-06 20:56:49 +0000]
[RESPONSE] [155190580.972264] [2019-03-06 20:57:01 +0000]
[REQUEST (objectAPIHandlers).HeadObjectHandler-fm] [155190582.131019] [2019-03-06 20:57:01 +0000]
[RESPONSE] [155190582.131019] [2019-03-06 20:57:01 +0000]
[REQUEST (objectAPIHandlers).DeleteMultipleObjectsHandler-fm] [155190582.131388] [2019-03-06 20:57:01 +0000]
[RESPONSE] [155190582.131388] [2019-03-06 20:57:01 +0000]
```

**Comment by nneul** [comment]
It looks like it may be doing a ListObjectsV1Handler-fm doing a GET of the bucket on every delete, with a prefix=<objectname> - and that operation is taking about 11 seconds. 

`GET /bucket-net/?delimiter=%2F&max-keys=1000&prefix=reporting%2F00981183-0b59-4c44-b861-42746ca78117_0B0B0D4187220BC123551927419FD90E_response-details.json`

with a response:

```
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>bucket-name</Name><Prefix>reporting/00981183-0b59-4c44-b861-42746ca78117_0B0B0D4187220BC123551927419FD90E_response-details.json</Prefix><Marker></Marker><NextMarker>reporting/00981183-0b59-4c44-b861-42746ca78117_0B0B0D4187220BC123551927419FD90E_response-details.json</NextMarker><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><Contents><Key>reporting/00981183-0b59-4c44-b861-42746ca78117_0B0B0D4187220BC123551927419FD90E_response-details.json</Key><LastModified>2019-03-05T19:49:29.144Z</LastModified><ETag>&#34;1f10c1213561d0664c4fa39227f24538&#34;</ETag><Size>785</Size><Owner><ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4</ID><DisplayName></DisplayName></Owner><StorageClass>STANDARD</StorageClass></Contents></ListBucketResult>

```

**Comment by nneul** [comment]
I think I need to hold on this until after I can upgrade the server and client versions...

**Comment by poornas** [comment]
thanks, let us know @nneul

**Comment by poornas** [comment]
@nneul, were you able to upgrade yet? If not, we could close this issue and reopen if you face the problem with upgraded setup.

**Comment by nneul** [comment]
Yeah, we can close... it's getting strung along internally. Thank you for your assistance!
