### ISSUE TITLE
[distributed] Putobject return "The specified bucket does not exist." sometimes

### ISSUE THREAD

**Issue by CloudWarGit** [minio/minio#7320]
In distributed mode,  PutObject() method sometimes（rate） return "The specified bucket does not exist." or "The specified key does not exist.", but the bucket is indeed exist, and object can be upload succeed if put again. minio-go version is 6.0.11.
## Expected Behavior

Should upload object with no error.
## Current Behavior

Return "The specified bucket does not exist." or "The specified key does not exist." sometimes.

## Possible Solution

This issue doesn't appear on Standalone mode, may be caused by distributed server didn't sync each other.
## Steps to Reproduce (for bugs)

1. Use Minio helm chart to install a distributed mode Minio cluster on k8s
2. create a bucket named "mybucket"
3. Concurrence upload some files, by code `PutObject(Bucket, metaFile, buf, int64(len(ctentByte)), minio.PutObjectOptions{})`,  
4. Try step 3 many times, the error will appear.

## Context

One of the Minio Server in the distributed cluster once lost its disk, this issue was happened after the server recovered serval days. 

## Your Environment

* Version used (`minio version`): Minio 2018-10-06T00:15:16Z and Minio-go 6.0.11
* Environment name and version (e.g. nginx 1.9.1): 
* Server type and version: kubernetes 1.9
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
Can you upgrade to latest version and test again ?

**Comment by CloudWarGit** [comment]
Sorry, this may be caused by  environment. I close this PR, if encounter again will re-open. Thanks.
