### ISSUE TITLE
ERROR Unable to initialize backend: value too large for defined data type.

### ISSUE THREAD

**Issue by eleaner** [minio/minio#7323]
Hi,

when I try to run minio:latest container over volume mounted with my own volume plugin I am getting message:

`ERROR Unable to initialize backend: value too large for defined data type.`

I am running out of ideas on what might be going wrong
**Is there a way t omake minio talk to a little more verbose?**

The problem must be with the plugin I try to write because in every other scenario I tested the minio container works perfectly.
The plugin gives me access to the filesystem within the containers so I am not sure what's wrong
please help.
I also tried instaling minio in alpine and debian containers. Always the same issue

**Comment by harshavardhana** [comment]
> `ERROR Unable to initialize backend: value too large for defined data type.`

This is because your volume plugin is not implementing some form of POSIX API can you debug this from your volume end? @eleaner 

Doesn't seem like Minio is the problem here..

**Comment by eleaner** [comment]
@harshavardhana I don't think it is minio problem either
but the message does not say much to me :(

**Comment by harshavardhana** [comment]
> @harshavardhana I don't think it is minio problem either
> but the message does not say much to me :(

You may need to debug the volume plugin here. Minio is simply pasting the error reported by the underlying volume. If this volume is an open source project we can take a look.

**Comment by eleaner** [comment]
@harshavardhana thank you for the offer.
the project is opensource but currently only on my machine
I have to learn how to make it public first :(

**Comment by harshavardhana** [comment]
Closing this as non-Minio issue @eleaner - feel free to re-open if needed.
