### ISSUE TITLE
ERROR Unable to initialize gateway backend: The specified bucket does not exist..

### ISSUE THREAD

**Issue by nikitadm** [minio/minio#7324]
What are different permissions that user require to initialize minio gateway?

Currently I am providing following permissions to user and getting above error.
1. s3:ListAllMyBuckets
2. s3:ListBucket

**Comment by harshavardhana** [comment]
you need `s3:HeadBucket` as well @nikitadm

**Comment by nikitadm** [comment]
I am using S3 compliant object store like StorageGrid and I couldn't find `s3:HeadBucket` permission for it. 
Is this specific to minio only? What permission should I provide for any other S3 object store?

**Comment by harshavardhana** [comment]
You can search for s3:HeadBucket its a valid  policy  action according to S3. But nevertheless s3:ListBucket action is allowed means head is implicit..

Most probably the error response returned is not what is expected by minio-go library. Would it be possible to get a tcpdump for the http traffic from storagegrid?

**Comment by kannappanr** [comment]
ping @nikitadm

**Comment by kannappanr** [comment]
@nikitadm Closing this issue now. Please feel free to reach out to us when you have information requested by @harshavardhana

**Comment by nikitadm** [comment]
@kannappanr, with the latest minio version the gateway works with following permissions,
1. s3:ListAllMyBuckets
2. s3:ListBucket

Thanks for the update!
