### ISSUE TITLE
Questions on healthcheck endpoints and http target log

### ISSUE THREAD

**Issue by thomaslange24** [minio/minio#7337]
I have Problems with the healthcheck endpoints and enabling the http logging and need some more information. I started minio in distributed mode with 4 nodes.

1) According to https://github.com/minio/minio/blob/master/docs/metrics/healthcheck/README.md i should be able to access the endpoints /minio/health/live and /minio/health/ready, right? But when i try e.g. "curl http://endpoint:port/minio/health/live" (changing the placeholder to the endpoint of one of the nodes) or open the same in the browser i don't get any response. What am i missing?

2) I would like to enable the http target logging. Therefore i followed the instructions on https://github.com/minio/minio/tree/master/docs/logging. But still i don't get any response when opening the "http://endpoint:port/path" i specified for one of the nodes. I tried both, starting the server with the http target logging environment variable and changing the configuration file, restarting the server according to the description.

Sorry if those questions seem stupid. But i am pretty new to this.

**Comment by kannappanr** [comment]
@thomaslange24 can you please try `curl -I https://play.minio.io:9000/minio/health/ready` or `curl -I https://play.minio.io:9000/minio/health/live` ? This will give you the status code. If you see the status code of `200` that means everything is good.

**Comment by thomaslange24** [comment]
Yes, with curl -I I can see the status code 200. Also when I try it for my distributed minio setup. Thanks

And what about the http target logging?

**Comment by harshavardhana** [comment]
> Yes, with curl -I I can see the status code 200. Also when I try it for my distributed minio setup. Thanks
> 
> And what about the http target logging?

We don't log anything if it's not an error @thomaslange24 - we only log errors which we cannot handle. are you expecting like Apache/ Nginx like behavior here?

**Comment by thomaslange24** [comment]
Yes, I thought it would be a bit more verbose. But if it is only about the errors that cannot be handled my confusion has resolved. Thanks again.

**Comment by kannappanr** [comment]
@thomaslange24 Closing this issue as answered. Please feel free to reach out to us if you have further questions. We are also available on slack at https://slack.min.io .
