### ISSUE TITLE
Object deletion is not logged

### ISSUE THREAD

**Issue by MikiTesi** [minio/minio#7338]
## Expected Behavior

I am expecting the logs to report:
1) When an object is created.
2) When an object is deleted.

## Current Behavior

No logs are produced when an object is deleted.

## Suggestions

Right now, when an object is created, this information is logged:  
 _**PUT /minio/upload/test-bucket/test-file.txt**_

So when an object is deleted, it should also log something similar, possibly like this: 
_**DELETE /minio/upload/test-bucket/test-file.txt**_

## Steps to Reproduce (for bugs)

1. Start a Minio container in Docker (make sure to enable logging by using -e "MINIO_HTTP_TRACE=/var/log/minio.log")
2. Access  http://127.0.0.1:9000 on the browser.
3. Create a bucket.
4. Create an object in the bucket.
5. Delete the object.
6. Open a shell into the Minio container.
7. Read the logs in /var/log/minio.log to check whether both the creation and the deletion of the object were logged.

## Context

-Given a Minio master-server where a certain dataset is stored, I want to replicate this dataset on other Minio slave-servers.
-The dataset needs to be filtered and transformed before it is sent to some of the slave-servers.
-This is why I need to monitor all the events (object creation and object deletion) that occur on my master-server, so that I can decide which events I want to filter out.
-I cannot use the notification system provided by Minio Client (_mc watch_ and _mc event_) because they can only report the events that occur on a specific bucket (whereas I need to monitor all of the buckets). 

## Your Environment

* Version used (`Docker minio version`): minio/minio:RELEASE.2019-03-06T22-47-10Z

**Comment by harshavardhana** [comment]
If you want audit logs you need to set https://github.com/minio/minio/blob/master/docs/logging/README.md#audit-targets

HTTP_TRACE is meant for debugging and browser requests are not traced in the same manner as S3 API requests.

**Comment by MikiTesi** [comment]
Thank you for your reply.

As you suggested, I started my Minio container by including this variable:
 **_-e "MINIO_AUDIT_LOGGER_HTTP_ENDPOINT=http://localhost:9000/minio/logs/audit"_**

How do I access those logs now though?

**Comment by harshavardhana** [comment]
You need to setup a webhook server which can receive those events .. http://localhost:9000/minio/logs/audit this URL doesn't look like you have setup webhook and you are simply passed an arbitrary value?

**Comment by harshavardhana** [comment]
Note audit log doesn't point to Minio itself

**Comment by harshavardhana** [comment]
Additionally you can also do `mc watch` on client to look for lambda events on a bucket..

**Comment by MikiTesi** [comment]
> You need to setup a webhook server which can receive those events .. http://localhost:9000/minio/logs/audit this URL doesn't look like you have setup webhook and you are simply passed an arbitrary value?

Indeed, I simply copied and pasted it from the example here: https://github.com/minio/minio/blob/master/docs/logging/README.md#audit-targets

**Comment by MikiTesi** [comment]
> Note audit log doesn't point to Minio itself

Ok so I need to create a webhook server on a certain port on my localhost. Then I'll need to use its URL as the argument of **MINIO_AUDIT_LOGGER_HTTP_ENDPOINT**. 

Did I understand correctly?

**Comment by harshavardhana** [comment]
Well the copy paste should say 8080 port, to indicate marginally that it's not Minio but another service. Renaming it to 9000 means you are thinking that it's pointing to Minio

**Comment by harshavardhana** [comment]
Yes that is correct, or you can use bucket notifications too - such as `mc watch` as previously mentioned.

**Comment by MikiTesi** [comment]
> Additionally you can also do `mc watch` on client to look for lambda events on a bucket..

Unfortunately, I cannot do this, because I need to watch for the events on ALL buckets (and I don't know how many or which buckets will be created, so I don't want to have to use _mc watch_ on every single bucket).

**Comment by MikiTesi** [comment]
> Well the copy paste should say 8080 port, to indicate marginally that it's not Minio but another service. Renaming it to 9000 means you are thinking that it's pointing to Minio

I had not caught this subtlety, thanks for making it clear :)

**Comment by MikiTesi** [comment]
I think it would be useful to extend the functionality of the _mc watch_ utility, so as to be able to watch all the existing buckets, instead of a specific one. I hope you will consider this in the future.

**Comment by kannappanr** [comment]
@MikiTesi I think there is support only for `bucket level notification` in S3. Not sure if we can add this support, but will definitely check internally and see if it can be done

**Comment by MikiTesi** [comment]
> @MikiTesi I think there is support only for `bucket level notification` in S3. Not sure if we can add this support, but will definitely check internally and see if it can be done

Thank you. Hopefully I'll have found another solution by the time you deliver the Next Release. Anyway, I hope the feature can come in handy to other people as well.

**Comment by MikiTesi** [comment]
I eventually managed to enable audit logging, as suggested by @harshavardhana . 

Though, making something out of the logs is turning out to be more complicated than expected.

For example, I was expecting a single log to be produced when an object is removed, but it actually produces four different logs (which only contain partial information and don't seem to be linked together by some sort of ID).

**Command executed on the client:**
$ mc rm mycloud/mybucket/test.txt

**The four logs produced on the server (filtered and formatted by me):**
1. First log
NAME OF THE API: ListObjectsV1
NAME OF THE BUCKET: mybucket
NAME OF THE OBJECT: undefined
REQUEST ID: 158A0C4B4EAB0A09

2. Second log
NAME OF THE API: ListObjectsV1
NAME OF THE BUCKET: mybucket
NAME OF THE OBJECT: undefined
REQUEST ID: 158A0C4B4EF9EED0

3. Third log
NAME OF THE API: HeadObject
NAME OF THE BUCKET: mybucket
NAME OF THE OBJECT: test.txt
REQUEST ID: 158A0C4B4F3A023B

4. Fourth log
NAME OF THE API: DeleteMultipleObjects
NAME OF THE BUCKET: mybucket
NAME OF THE OBJECT: undefined
REQUEST ID: 158A0C4B51A44058

I wished the fourth log (which has a very explicit name such as DeleteMultipleObjects) also contained the name of the deleted object. 

The only log which contains the name of the deleted object is the third one (that of api HeadObject)...but I couldn't possibly infer that this log was reporting the deletion of an object, since its api is just called HeadObject.

Do you guys have any other suggestions on how I could log the deletion of an object? As a recap, I need three pieces of information: the action (DELETE), the name of the bucket (mybucket), and the name of the deleted object (test.txt).

**Comment by harshavardhana** [comment]
@MikiTesi you are seeing all the API operations being performed that is what Audit would look like. If you are only interested in seeing DELETE then it should be through bucket notifications.

**Comment by MikiTesi** [comment]
But then I'd have to manually create a new notification for every bucket that is ever created, since it's not possible to monitor all buckets with a single command. That sounds kind of impractical :/

I'll have to think this through and see what to do next. 

I guess you can close the issue by now. Thanks for all the support though, I really appreciate it :)

**Comment by kannappanr** [comment]
closing this issue based on the above comments. Please feel free to reach out to us if you have further questions.
