### ISSUE TITLE
Unable to delete buckets with a dot(.) in their name through GUI in federated setups

### ISSUE THREAD

**Issue by adiospeds** [minio/minio#7340]
I was able to create a bucket named `he.man` from minio GUI interface. And was also able to delete the bucket from the GUI interface. However, If I refresh the page before deleting the bucket, the bucket name changes to `man/he`. Once this happens we cannot delete the bucket ever from GUI interface and it can only be deleted from the cli.

After page refresh:
![image](https://user-images.githubusercontent.com/8983446/53994355-24b0ba00-4158-11e9-88d6-4784f745dc5d.png)

## Expected Behavior

Either users should not be allowed to create buckets with a dot in the bucket name or there should be a way to delete these buckets from the GUI interface.

There should be a way to delete these buckets from the GUI interface.

## Steps to Reproduce (for bugs)

1. Create a bucket called abc.xyz through minio GUI interface
2.  Refresh the browser page. Now the bucket name changes to xyz/abc
3. Try to delete the bucket through GUI interface. (Throws an error: Bucket name contains invalid characters )

## Your Environment

* Version used (`minio version`): 2019-01-31T00:31:19Z
* Environment name and version (e.g. nginx 1.9.1): NA
* Server type and version: NA
* Operating System and version (`uname -a`): Linux <hostname> 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project: NA

**Comment by kannappanr** [comment]
@adiospeds i tried to reproduce with the steps that you provided, but was unable to reproduce the issue. i tried both the latest master and minio version `2019-01-31T00:31:19Z`.

**Comment by ebozduman** [comment]
I also couldn't reproduce the issue on my system and the only difference I see between yours and mine is in the Ubuntu/OS version.
Mine is:
```
$ uname -a
Linux ersanscomputer 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
OS is quite unlikely the reason why this issue happened in your case, but just wanted to let you know.

**Comment by donatello** [comment]
This is actually on a federated setup with etcd and coredns.

**Comment by harshavardhana** [comment]
We shouldn't allow bucket creates with `.` in them perhaps its a bug in federated setups.

**Comment by adiospeds** [comment]
> We shouldn't allow bucket creates with `.` in them perhaps its a bug in federated setups.

But aws s3 protocol allows creation of such buckets. I think the minio GUI needs a fix as a long term solution

**Comment by harshavardhana** [comment]
> But aws s3 protocol allows creation of such buckets. I think the minio GUI needs a fix as a long term solution

That I am aware but it can get tricky for DNS record updates when used with etcd and coreDNS. So a bucket with `.` or without wouldn't really add much benefit unless its a specific use case.

The problem is the conversion of sub-sub-domains but was able to fix it anyways...
