### ISSUE TITLE
Trying to create a user-policy per bucket through a backend java client?  Currently I am able to create a user-policy like giving a particular user read/write access and create policy file for a specified bucket and was successfully able to test it through minio-server, and I was performing all my action through cmd!I wanted to do this through a Java-Client I looked into the Minio repository for the Java, but it didnot exactly help me a lot? can anyone provide me the sample code to create policy per user- per bucket  through a backend JAVA-Client

### ISSUE THREAD

**Issue by maniker** [minio/minio#7344]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
Can you open a proper issue, there is no reason to type everything in the title? 

We will close this issue for now.. so that you resubmit properly.
