### ISSUE TITLE
Unable to heal when distributed minio volumes are on root partitions

### ISSUE THREAD

**Issue by jinzinna** [minio/minio#7346]
I have a distributed cluster with 4 nodes.  After a node was taken out of service and had its volume wiped, I am unable to heal once the node is available again.

## Expected Behavior
"mc admin heal {cluster}" should re-establish the .minio.sys directory on the node that was wiped, make the disk available, and bring the cluster back to full operation.

## Current Behavior
After the node is replaced and minio started, the new node's disk is offline, and the volume on that node does not contain a .minio.sys directory.  Attempts to heal do not change this.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1.  $ ./mc admin info devcluster/bucket
●  10.2.11.65:9000
   Uptime : online since 1 minute ago
  Version : 2019-01-31T00:31:19Z
   Region : 
 SQS ARNs : <none>
    Stats : Incoming 0B, Outgoing 0B
  Storage : Used 61MiB
    Disks : 3, 1

●  10.2.11.66:9000
   Uptime : online since 1 minute ago
  Version : 2019-01-31T00:31:19Z
   Region : 
 SQS ARNs : <none>
    Stats : Incoming 0B, Outgoing 0B
  Storage : Used 61MiB
    Disks : 3, 1

●  10.2.11.68:9000
   Uptime : online since 1 minute ago
  Version : 2019-01-31T00:31:19Z
   Region : 
 SQS ARNs : <none>
    Stats : Incoming 0B, Outgoing 0B
  Storage : Used 61MiB
    Disks : 3, 1

●  10.2.11.67:9000
   Uptime : online since 1 minute ago
  Version : 2019-01-31T00:31:19Z
   Region : 
 SQS ARNs : <none>
    Stats : Incoming 0B, Outgoing 0B
  Storage : Used 61MiB
    Disks : 3, 1

2.  All of my heal attempts do not return failure, but do not change the above:
$ ./mc admin heal -r devcluster
 ◓  bucket/directory/file.txt
    0/65 objects; 40 MiB in 1s
    ┌────────┬────┬─────────────────────┐
    │ Green  │  0 │   0.0%              │
    │ Yellow │ 67 │  97.1% ████████████ │
    │ Red    │  1 │   1.4% █            │
    │ Grey   │  1 │   1.4% █            │
    └────────┴────┴─────────────────────┘

3. admin info still shows 1 disk offline, the node volume directory still has no .minio.sys directory

## Context
Dev environment disaster recover preparation

## Regression
Not that I am aware of

## Your Environment
* Version used (`minio version`): 2019-01-31T00:31:19Z
* Environment name and version (e.g. nginx 1.9.1): haproxy 1.8.17
* Server type and version: Citrix VMs
* Operating System and version (`uname -a`): CentOS Linux release 7.5.1804 (Core), kernel 3.10.0-862.el7.x86_64
* Link to your project:

**Comment by kannappanr** [comment]
@jinzinna Can you please provide the parameters you used to start `minio` on all the nodes? Also, can you provide the parameters before and after replace disks on the node that is not healing now?

**Comment by jinzinna** [comment]
@kannappanr I started minio on all 4 servers with this command:
minio server http://10.2.11.65:9000/data http://10.2.11.66:9000/data http://10.2.11.67:9000/data http://10.2.11.68:9000/data

Earlier I had been starting minio on all servers with this command:
minio server http://10.2.11.65/data http://10.2.11.66/data http://10.2.11.67/data http://10.2.11.68/data

After wiping the /data directory on 10.2.11.68, I then restarted minio on all servers with the first command above (i.e., that was when I started specifying port 9000).

**Comment by eco-minio** [comment]
@jinzinna I tested this, it is working fine in my environment, the only major difference is I am not running haproxy.  Can you provide two things?

1) Your haproxy config
2) The output of `mc admin heal -r --json devcluster`

Aside from that, can you make sure that SElinux is allowing access to the port and that no firewall rule exists on the reconfigured node? (If I understood properly you just wiped the disk but doesn't hurt to check).

**Comment by jinzinna** [comment]
@eco-minio I verified the following:
selinuxenabled returns 1, so no SELinux rules
From another server, I can open port 9000 to each node in the cluster (good call, the server was reimaged)

Attached below are the haproxy.cfg as well as the output of the heal command.

[haproxy.txt](https://github.com/minio/minio/files/2954180/haproxy.txt)

[output_json.txt](https://github.com/minio/minio/files/2954124/output_json.txt)

**Comment by eco-minio** [comment]
@jinzinna This looks like a bug that affects heal when a policy is applied to a bucket (https://github.com/minio/minio/pull/7208). After applying a policy I was able to reproduce the issue with the version you are using, upgrading to latest (RELEASE.2019-03-06T22-47-10Z) fixed the issue on my side, can you update an try running a recursive heal again?

**Comment by jinzinna** [comment]
@eco-minio I stopped minio on all 4 nodes, upgraded all 4 nodes to 2019-03-06T22:47:10Z, and restarted minio.  I still see the same behavior of the replaced node's disk not coming online, and not getting a .minio.sys directory after running a heal.

heal output is substantially the same, but attached below.

[output_json.txt](https://github.com/minio/minio/files/2956893/output_json.txt)

**Comment by jinzinna** [comment]
@eco-minio, in case this detail helps, the 3 unaffected servers at start time all report an error regarding the disk of the replaced node being unformatted:

Error: unformatted disk found
endpoint=http://10.2.11.68:9000/data
1: cmd/prepare-storage.go:47:cmd.glob..func16.1()
2: cmd/xl-sets.go:211:cmd.(*xlSets).connectDisks()
3: cmd/xl-sets.go:242:cmd.(*xlSets).monitorAndConnectEndpoints()

**Comment by krishnasrinivas** [comment]
@jinzinna can you give output of the following commands on the affected server:
stat /
stat /data

**Comment by jinzinna** [comment]
[root@minio-srvr-68 minio]# stat /
  File: ‘/’
  Size: 236       	Blocks: 0          IO Block: 4096   directory
Device: fd00h/64768d	Inode: 64          Links: 18
Access: (0555/dr-xr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-03-11 16:47:15.860000000 -0400
Modify: 2019-03-08 14:37:07.135275230 -0500
Change: 2019-03-08 14:37:07.135275230 -0500
 Birth: -

[root@minio-srvr-68 minio]# stat /data
  File: ‘/data’
  Size: 6         	Blocks: 0          IO Block: 4096   directory
Device: fd00h/64768d	Inode: 1207        Links: 2
Access: (0755/drwxr-xr-x)  Uid: (  996/minio-user)   Gid: (  994/minio-user)
Access: 2019-03-12 15:14:37.289770574 -0400
Modify: 2019-03-12 15:14:36.201753607 -0400
Change: 2019-03-12 15:14:36.201753607 -0400
 Birth: -

**Comment by kannappanr** [comment]
@jinzinna I have a PR to fix this issue. We have code to not heal `format.json` if it exists on the `root` disk. This is to stop data from being created on root disks, even if the actual disks are not mounted at that mount point. 

The PR will check if all the disks used here are root disks, then it will assume that this is a test setup and allow you to heal.

We have tried it out locally and made sure that it works. Can you try this PR out and let us know if this works?

**Comment by jinzinna** [comment]
@kannappanr yes I'd be happy to test it out.

**Comment by kannappanr** [comment]
@jinzinna Just in case you want to use a pre-built binary, I have it on play. You can download it using the following command

```
wget https://play.minio.io:9000/test/minio
```

**Comment by jinzinna** [comment]
Problem solved.

FWIW, while I can understand the reasoning for not sending a bunch of data to a root partition, it is worth noting in the quick-start that distributed heal won't work if some of the volumes are on root.

Thank you everyone who contributes to this very cool product!

**Comment by kannappanr** [comment]
@jinzinna Thanks for verifying the fix. Will add the information about root partition and root disk to our documentation. This issue will be closed when we merge the PR.
