### ISSUE TITLE
STS Policy

### ISSUE THREAD

**Issue by timbuchwaldt** [minio/minio#7349]
The STS API is a great addition and gets Minio really close to what I need. It sadly lacks the support for attaching a temporary policy to a temporary STS credential. We use this heavily on S3 to provide endusers S3 access to a big bucket and would love to replace that with minio.

## Expected Behavior
STS AssumeRole allows specifying a policy that allows access to certain "folders" in a bucket.

## Context
Shared secure storage in one bucket.

## Regression

No

**Comment by harshavardhana** [comment]
Currently STS inherits the policy for the user which you are trying to provide access, so you can add such a policy and create a user. 

Then generate temp credentials, the policy is automatically attached to those creds. 

Extra policy is needed only if you want to further restrict the temp creds. Is this what you are looking for ?

**Comment by kannappanr** [comment]
@timbuchwaldt Can you please respond to the question from @harshavardhana

**Comment by kannappanr** [comment]
@timbuchwaldt Closing this issue now. Will re-open when we have more information from you.

**Comment by jcharlytown** [comment]
@harshavardhana, I having a similar request as @timbuchwaldt . I am using the "AssumeRoleWithClientGrants" endpoint in order to acquire a short lived access key/secret.

> Currently STS inherits the policy for the user which you are trying to provide access

Does this also apply to "AssumeRoleWithClientGrants"? I don't see how I "provide" a minio user in this case as there is only the JWT of the external user from the identity provider. In https://github.com/minio/minio/blob/master/docs/sts/wso2.md there is a discussion of the "policy" claim. Is it correct that this is the mechanism to "pass" in the role the credentials will inherit?

**Comment by harshavardhana** [comment]
Your JWT auth token should have an additional claim with key `policy` which points to an existing IAM policy on MinIO created by `mc admin policy` 

Your STS tokens inherit this policy.

**Comment by jcharlytown** [comment]
Thx for the quick response! I think I managed to successfully do this. Is it some kind of error that the credential I acquired this way don't work in the webinterface? Won't bother you any further :)

Edit: I get credentials back, but they work neither for the webinterface, nor using `mc`.

**Comment by harshavardhana** [comment]
Web interface is not extended to allow STS to work, it's a bit cumbersome and also we are planning to reduce the scope of Minio Browser in general.

**Comment by harshavardhana** [comment]
mc requires additional support which is not finished yet, it's a work in progress.

**Comment by jcharlytown** [comment]
Hi, thanks for letting me know. I didn't realize that in order for the STS credentials to work one also needs to provide the original JWT along with the request. The Amazon S3 documentation clearly states that, so my fault. However, I think it would be helpful to many people to include a short note in the Minio STS doc that this won't work with neither the Minio Browser nor the CLI client. It is very tempting to just input the newly acquired credentials into the Browser interface :)
