### ISSUE TITLE
Use execve for restart or disallow Minio restart admin command per deployment

### ISSUE THREAD

**Issue by MOZGIII** [minio/minio#7350]
I'd like to have an option to disable the ability to restart Minio via the admin API, or make the restart use `execve` directly without doing a `fork` (currently it uses `exec.Start`, which does a usual `fork+exec` under the hood).

Rationale is when Minio is deployed under systemd with `Type=simple` and auto-restart enabled at the systemd level, when minio restarts itself the system can end up with two `minio` processes after the restart - one started by the old `minio` process as a part of processing the restart command issued by admin, and one by systemd as a reaction to the old `minio` process termination. In this scenario, it is preferred to only have `minio` process started by systemd, as it is managed by the system, while the other process - the one that was started by `minio` itself as a restart routine - is not managed by anything.

There are two possible solutions for this problem:

1. Use [syscall.Exec](https://golang.org/pkg/syscall/#Exec) to issue `execve` directly. It solves this and a few other problems - like changed pid of the process, which is an issue if you're using pid lockfiles for process management.
2. Add the ability to disallow invoking `restart` service command (i.e. `mc admin service restart`) for a particular Minio deployment, preferably via an env var.

**Comment by harshavardhana** [comment]
Thanks this makes sense, we will do it using the execve style instead.

**Comment by vadmeste** [comment]
A similar issue is with Docker. Currently, `mc admin restart` a Minio docker instance will kill the instance and not restart it, because it looks like Docker monitors the pid.

**Comment by MOZGIII** [comment]
Docker is slightly different: it has a root - aka "init" - process that, if terminated, causes the whole container to be removes - which will cause force termination of all other processes in the said container. This could be solved by using an dedicated in-container init (something like `tini`) - and that would even be a valid/proper soplution to that docker-specific problem. But `execve` should work fine with docker use case too, so implementing that is even better.
