### ISSUE TITLE
Heal not working on nginx endpoint in federated clusters

### ISSUE THREAD

**Issue by adiospeds** [minio/minio#7352]
I have my nginx server_name directive named as testing.s3.xyz.com

I used the command 
`mc config host add test3 http://testing.s3.xyz.com miniokey miniosecret --api S3v2`
to add a target to `mc` command.

`mc admin info test3` gives me the status output for all servers which confirms the working of target.
However, running heal on the TARGET `test3` gives me this following error.

```mc admin heal test3
mc: <ERROR> Unable to display heal status. No such heal process is running on the server```

**Comment by harshavardhana** [comment]
This is expected you need to reach out to a specific endpoint to keep the healing status from missing the token. This is being fixed as I write this.

**Comment by harshavardhana** [comment]
Since we have auto heal now, which runs every 24hrs. Closing this issue.
