### ISSUE TITLE
TLS: no cipher suite supported by both client and server.

### ISSUE THREAD

**Issue by Coder-212** [minio/minio#7357]
I installed a minio server with https in windows server 2012 R2, via my post windows 10 I can use the GUI and the dotnet client to upload documents.
On the other hand, when I go on a windows server 2012 R2 I cannot connect to the minio server and I receive the following exception on my DotNet application:

[ Error occurred when uploading file: Unsuccessful response from server without XML error: The request was aborted: Could not create SSL/TLS secure channel.: 
Minio.Exceptions.InternalClientException: Minio API responded with message=Unsuccessful response from server without XML error: The request was aborted: Could not create SSL/TLS secure channel. ]

On the minio server console I receive the following message:

[ 2019-03-12 10:39:58.926677 I | http: TLS handshake error from [IPAdress]:61032 : tls: no cipher suite supported by both client and server. ] 

## Your Environment

* Version used (`minio version`):
Version: 2019-03-06T22:47:10Z
Release-Tag: RELEASE.2019-03-06T22-47-10Z
Commit-ID: b05825ffe825646dc075996d33c583f6cf456837

**Comment by kannappanr** [comment]
@Coder-212 Can you please take a look at https://github.com/minio/minio/issues/6611

**Comment by harshavardhana** [comment]
@Coder-212 you should use ECDSA certs instead of RSA which are not supported due to TLS vulnerabilities.

**Comment by kannappanr** [comment]
@Coder-212 Closing this issue now. Feel free to re-open this issue or reach us at https://slack.min.io if you have further information.
