### ISSUE TITLE
Event notification payload for Redis in access format

### ISSUE THREAD

**Issue by panzerdev** [minio/minio#7362]
https://github.com/minio/minio/blob/13c3b8afe236eaf04c2797b2cd23cc0ab37af03a/pkg/event/target/redis.go#L101

This is the current type the json payload is right now. This is being put into an array into Redis. IMO this is not very nice to parse and handle. 
```
[
  "2019-03-13T18:44: 03Z",
  [
    {
      "eventVersion": "2.0",
      "eventSource": "minio: s3",
....
  ]
]
```

After parsing that back into `[]interface{}` one has to iterate over the array and do type checks with reflection to find out if it's the timestamp or the one event in an array.

Are there reasons why the payload looks like it looks now?

My proposal would be to either write just the `event.Event` as `json` or have a wrapper that contains the timestamp like

```
type EventWrapper struct{
    event          event.Event
    eventTime   time.Time
```

I'd also be happy to do a PR for that :blush:

**Comment by harshavardhana** [comment]
Definitely we would love to see a PR @panzerdev

**Comment by panzerdev** [comment]
@harshavardhana Great to hear. What version would you prefer?

a) just `event.Event`
b) the `EventWrapper`

**Comment by harshavardhana** [comment]
> @harshavardhana Great to hear. What version would you prefer?
> 
> a) just `event.Event`
> b) the `EventWrapper`

To avoid breakage we can keep EventWrapper, we can keep this an anonymous struct{}

**Comment by kannappanr** [comment]
@panzerdev did you get a chance to work on sending a PR?

**Comment by kannappanr** [comment]
Closing this as stale. please feel free to let us know, when you have time to work on this and we can re-open this issue.

**Comment by hamid-elaosta** [comment]
Any change of this being looked at? Trying to parse the output of the Redis events in access mode is impossible to do cleanly in Golang.
