### ISSUE TITLE
[feature] [logging] add support for multiple targets

### ISSUE THREAD

**Issue by JetChars** [minio/minio#7365]
## Context

I've noticed that logger provided `Target` interface to support more logger targets other than `console` or `http`; but when I dig into it, only `LogIf()` method iterating over all targets to send messages. So, do we have a plan to enable more logger methods to utilize multiple targets? eg: `FatalIf()`, `Info()`, and so on; Also, do we have a plan to support self-defined logging format, to record fields like time, level, req_id, line_in_file and so on?

**Comment by kannappanr** [comment]
@JetChars Will check internally and get back to you, if we plan to support logging to multiple targets in these methods.

**Comment by JetChars** [comment]
nice!

**Comment by kannappanr** [comment]
@JetChars We will log to remote targets in the case of `FatalIf` once the logging subsystem has boot strapped. If `FatalIf` is called before the loggin subsystem bootstraps, then we cannot send that over to the remote targets.
```
Also, do we have a plan to support self-defined logging format, to record fields like time, level, req_id, line_in_file and so on?
```
We do not plan to support custom logging format as of now.

**Comment by JetChars** [comment]
Got it, appreciated. Or can I submit some PR related?

**Comment by kannappanr** [comment]
@JetChars Please feel free to submit a PR for this feature.

**Comment by harshavardhana** [comment]
There is no reason to add multiple targets, in-fact single target can in-turn write to multiple targets if needed. We will close this issue for now and re-open if it becomes a hard requirement in the future.
