### ISSUE TITLE
heal: Fail to heal part.1 when corrupted and empty

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#7366]
## Expected Behavior
Whatever the content of part.1, healing should be able to fix the object if it can be recovered.

## Current Behavior
Unable to heal the object, yellow object in mc admin heal output

## Possible Solution
Do not know yet

## Steps to Reproduce (for bugs)
```
1. dd if=/dev/urandom of=file bs=1024 count=1024
2. mc mb myminio/testbucket/
3. mc cp file myminio/testbucket/
4. rm -rf /path/to/backend/disk-1/testbucket/file/part.1 && touch /path/to/backend/disk-1/testbucket/file/part.1
5. mc admin heal -r myminio/testbucket/ 
```

## Context
Fixing a found bug

## Regression
Do not know

## Your Environment
All

**Comment by harshavardhana** [comment]
Is this still true @vadmeste ?
