### ISSUE TITLE
Official Arm Support & Binaries

### ISSUE THREAD

**Issue by Mark84** [minio/minio#7368]
Happy Pi Day! I have a cluster of Pi zeros on a ClusterHAT and PI3b+ host, I wished to deploy a distributed Minio setup with Docker.

## Expected Behavior
The current Docker file isn't compatible with ARM architecture, but is relatively simple to change to use the arm32v6/alpine:3.X and arm32v6/golang:1.11.4-alpine3.X images instead, which will work in exactly the same way.

However your binary ARM builds are long out of date and don't work inside the docker overlay network, so the Dockerfile could build minio from source too to save you cross-compiling (with a potential trade-off for larger images and longer build times).

## Current Behavior
ARM is currently unsupported, with only out of date pre-built binaries available which error when run in a Docker swarm cluster.

## Possible Solution
I've verified that the arm32v6 golang and alpine images build a successful Docker image when also combined with a minio binary built from source with the same arm32v6 golang alpine image. The cluster runs successfully in distributed mode on 4x Pi Zero 1.3s

Compiling mc binary on a Raspberry Pi is less simple, as (running Raspian Stretch) it requires compiling a newer golang version than ships in the package manager. Currently I have not successfully built go 1.11.4 as the Pi runs out of memory during one of the tests. So further tweaks would be necessary for mc to build on a native Pi, or cross-compilation required to provide a viable mc binary.

## Steps to Reproduce (for bugs)
N/A

## Context
I'm running a Pi cluster of 1x Pi 3b+ and 4x Pi Zeros. Docker swarm is setup and running and I've verified ARMv6 images run on all the hosts. I intend to use Minio as local (mini!) S3 style storage. Both for learning and initially to store images taken from a Pi camera running Motion (motion detection software). Minio will enable simple storage of pictures once motion is detected and web-hook trigger off to the next project stage -> image processing & recognition using machine learning, also running on the Pi cluster.

## Regression
N/A

## Your Environment
As above. 
Raspian Stretch. ARMv6 hardware and backwards compatible versions. Docker 18.0.6-3ce

**Comment by harshavardhana** [comment]
We won't be building binaries officially for ARM platform, this was decided because we don't have any ARM hardware to test and validate. Testing on each of these architectures and making sure you don't hit bugs is beyond our capabilities right now.

Our master branch can be compiled by source. We will fix bugs if any reported on these platforms.

**Comment by nitisht** [comment]
Closing this as there no further action needed

**Comment by treksler** [comment]
> We won't be building binaries officially for ARM platform, this was decided because we don't have any ARM hardware to test and validate. 

AWS has many ARM based instances available for pennies an hour, FYI.

**Comment by harshavardhana** [comment]
> AWS has many ARM based instances available for pennies an hour, FYI.

@treksler the point is our time is more expensive here not just the hardware. Feel free to build them yourself we do support them as source compiled targets.

**Comment by muktiarip** [comment]
@harshavardhana thanks for your hard work. We use minio on Raspberry Pi SBC. We put pre-built binary of latest minio release here: https://github.com/muktiarip/minio-binary-for-rpi/releases

**Comment by stephenstubbs** [comment]
> @harshavardhana thanks for your hard work. We use minio on Raspberry Pi SBC. We put pre-built binary of latest minio release here: https://github.com/muktiarip/minio-binary-for-rpi/releases

This is awesome thank you.

**Comment by inieves** [comment]
Is there any change to Minio's official roadmap for ARM support given Apple's transition to ARM on the desktop and Docker's support for that transition?

I have been able to build the official Minio Docker container using the ARM64 and ARMv7 instruction sets, but have been unable to build for the ARMv6 instruction set.  Any recommendations on how to do that build?

**Comment by harshavardhana** [comment]
> I have been able to build the official Minio Docker container using the ARM64 and ARMv7 instruction sets, but have been unable to build for the ARMv6 instruction set. Any recommendations on how to do that build?

ARMv6 is deprecated by Go and will be removed so you better move away from ARMv6 - Apple will natively support aarch64 we don't support darwin-arm64 yet because Go doesn't support it yet. 

It will be supported in Go 1.16 the new toolchain will arrive to support Darwin aarch64

**Comment by inieves** [comment]
Thanks so much for clarifying that!  Very much appreciated.  I will step away from ARMv6
