### ISSUE TITLE
Unexpeted Error Report to minio

### ISSUE THREAD

**Issue by vipindoshi** [minio/minio#7371]
API: SYSTEM()
Time: 15:00:36 AEDT 03/15/2019
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd\web-handlers.go:1904:cmd.toWebAPIError()
       2: cmd\web-handlers.go:1914:cmd.writeWebErrorResponse()
       3: cmd\web-handlers.go:1280:cmd.(*webAPIHandlers).DownloadZip.func1()
       4: cmd\web-handlers.go:1376:cmd.(*webAPIHandlers).DownloadZip()

**Comment by harshavardhana** [comment]
Thanks for filling the issue.

Can you provide more information? Will close this issue for now, since the issue template was removed and lacks information such as Minio version etc.

Please reopen with relevant information, we will be happy to take a look.
