### ISSUE TITLE
Request for feature: Minio plugin for Container storage interface (CSI)

### ISSUE THREAD

**Issue by akhilputhiry** [minio/minio#7379]
It would be great if minio can have a plugin created for CSI

https://github.com/container-storage-interface/spec
https://github.com/container-storage-interface/spec/blob/master/spec.md

**Comment by kannappanr** [comment]
@akhilputhiry would something like https://github.com/ctrox/csi-s3 work?

**Comment by akhilputhiry** [comment]
@kannappanr  Let me try this out..

Looks like they use `fuse` internally. I have tried fuse earlier but performance wise fuse is very slow compared to normal `aws-cli` commands. I was hoping to use boto apis internally along with the pyfilesystem to create the mount point. Any way let me dig deep on this.

**Comment by akhilputhiry** [comment]
Many people uses blob storage as the storage medium for large machine learning datasets. Minio gateways are great for such use cases. Most of the guys spawn some jupyter notebook in some cloud or cluster to run their trainings. One of the problem here is the the storage. The current available options like s3fs-fuse and all is very slow at the same time native aws apis are faster. I am looking for some solution which will give better throughputs than s3fs-fuse. If we could bridge this gap effectively that can be one of the USP's for minio.

**Comment by akhilputhiry** [comment]
If mounting as file system is going to affect the performance, we can also think about sinking the bucket and mountpoints. May be something like [wormhole](https://github.com/warner/magic-wormhole)  or `aws s3 sync`can help.

I am just starting with `go`, other wise I could have tried out something

**Comment by kannappanr** [comment]
@akhilputhiry Can you elaborate on your use case ? We want to understand why you need to talk to Minio/S3 using a CSI instead of directly talking to minio using S3 APIs/SDKs.

`aws s3 sync can help`, There is an issue here. If you use use `FUSE`, then, the data is still on minio. If you use `aws s3 sync` or `mc mirror`, it will be on local storage. Is this what you want?

**Comment by akhilputhiry** [comment]
@kannappanr here is my use case

I am using [Jupyter hub](https://jupyter.org/hub) to spin off containers dynamically in a kubernetes cluster for running my machine learning notebooks.

All the datasets which I am using for my machine learning purposes sits in some blob storage (S3, Azure blobe, Google coud bucket etc)

Now while running the notebook, I will have to
* Write code explicitly to download the dataset first to my container
* I need to write code explicitly to save data back to the blob storage

The problem here is,
* The container may not be having enough space to download the dataset
* There is no storage attached to the container yet, everything is in memory
* I need to mount a storage to solve this problem (sometime it is S3, sometime it is Azure blob, sometime it is Google cloud bucket)
* To make this generic I want to use minio gateway, so that underlying data can be in any blob store

Now to get this done, I need an CSI interface for minio so that it can be mounted as a volume to my K8 cluster

**Comment by harshavardhana** [comment]
Currently, this is not in our interest - we will happily accept community work. Our main focus is to provide MinIO operator instead of CSI for now. 

Closing this for now and perhaps re-open in future if CSI becomes a requirement.

**Comment by lorinliu** [comment]
Hi @harshavardhana, I think it is a very useful feature for minio users. With this feature, many applications running in k8s can use minio as file-system backend without code modification. For now, minio users have to 1) modify codes by using minio API or 2) use sidecar container in k8s.

**Comment by harshavardhana** [comment]
> Hi @harshavardhana, I think it is a very useful feature for minio users. With this feature, many applications running in k8s can use minio as file-system backend without code modification. For now, minio users have to 1) modify codes by using minio API or 2) use sidecar container in k8s.

@lorinliu https://github.com/kubernetes/enhancements/pull/1383 please follow the discussion here

**Comment by chazapis** [comment]
@akhilputhiry, if the container does not have space to download the data you need, using fuse might not be a bad option. Check out [Datashim](https://github.com/datashim-io/datashim). It works with S3 providers, like Minio, and will help you manage all your different data locations/protocols and easily select which containers access which providers.
