### ISSUE TITLE
Cases in switch are equal

### ISSUE THREAD

**Issue by sosiska** [minio/minio#7380]
## Expected Behavior
I found duplicated case in `toAPIErrorCode` function here: https://github.com/minio/minio/blob/master/cmd/api-errors.go#L1478

## Current Behavior
`case crypto.ErrInvalidCustomerKey` is duplicated here:
https://github.com/minio/minio/blob/master/cmd/api-errors.go#L1510
and here:
https://github.com/minio/minio/blob/master/cmd/api-errors.go#L1524

## Possible Solution
Understand and remove the unnecessary case.

**Comment by kannappanr** [comment]
@sosiska Thanks for filing this issue. Hope to merge the PR soon.
