### ISSUE TITLE
invalid bucket name not conform with AWS terminology

### ISSUE THREAD

**Issue by zorino** [minio/minio#7389]
Bucket name can only contains a-z 0-9 and '-'.

## Expected Behavior

Bucket name with safe characters from https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html
should be supported.

## Current Behavior

Bucket name with characters other than a-z 0-9 and '-' are not supported.

https://github.com/minio/minio/blob/b05825ffe825646dc075996d33c583f6cf456837/cmd/object-api-utils.go#L100-L110

## Possible Solution

Add more valid characters here : 

https://github.com/minio/minio/blob/b05825ffe825646dc075996d33c583f6cf456837/cmd/object-api-utils.go#L100-L110

## Steps to Reproduce (for bugs)

1. launch minio with a bucket name with an underscore
2. mount the bucket with s3fs
3. try to read a file
4. get invalid bucket name

## Your Environment

* Version used (`minio version`): 
* Server type and version: debian 7.11 (Linux app1 3.2.0-4-amd64 #1 SMP Debian 3.2.78-1 x86_64 GNU/Linux)
* Operating System and version (`uname -a`):  client for s3fs mount debian 9 (Linux emarketing-front 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux)

**Comment by kannappanr** [comment]
@zorino Please look at https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html for bucketnaming restrictions. `_` is not an allowed character.

**Comment by zorino** [comment]
You're right I was looking at the object name instead of bucket name my bad.
