### ISSUE TITLE
Public URL access not working

### ISSUE THREAD

**Issue by eteubert** [minio/minio#7393]
## Expected Behavior

Accessing a file url on a public bucket downloads the file.

## Current Behavior

403 Forbidden

## Steps to Reproduce (for bugs)

```
$> mc mb mybucket
Bucket created successfully `mybucket`.

$> mc policy public mybucket
Access permission for `mybucket` is set to `public`

$> mc cp /local/path/example.mp3 mybucket/example.mp3:  77.69 MB / 77.69 MB  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100.00% 807.83 MB/s 0s

$> curl -IL "http://127.0.0.1:9000/mybucket/example.mp3"
HTTP/1.1 403 Forbidden
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Server: Minio/RELEASE.2019-03-13T21-59-47Z
Vary: Origin
X-Amz-Request-Id: 158D503B97663E90
X-Minio-Deployment-Id: e7c41f40-57e8-463a-b36a-c57e95d7a369
X-Xss-Protection: 1; mode=block
Date: Tue, 19 Mar 2019 08:54:23 GMT
```

## Your Environment

* Version used (`minio version`): ```Version: 2019-03-13T21:59:47Z
Release-Tag: RELEASE.2019-03-13T21-59-47Z
Commit-ID: 285c09fe6b012583ce4fe07e3f9221fcbad4df2c```
* Environment name and version (e.g. nginx 1.9.1):
* Operating System and version (`uname -a`): Darwin MBP.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

**Comment by nitisht** [comment]
@eteubert looks like you're missing the alias. It should be 

```
$> mc mb myminio/mybucket
$> mc policy public myminio/mybucket
```

Can you try this and let us know

**Comment by eteubert** [comment]
That solves it, thanks for the quick response!
