### ISSUE TITLE
 How to integrate minio‘s frontend with keycloak?

### ISSUE THREAD

**Issue by west789** [minio/minio#7394]
I want to integrate minio with keycloak, but 400 bad request erro occurs
## Steps to Reproduce (for bugs)

Personal practice: After configuring the relevant parameters using web-identity.go, I can redirect to keycloak and log in, but when I redirect to the minio server again, a 400 bad request error occurs.
1.modify minio config.json

![image](https://user-images.githubusercontent.com/30501870/54595239-32761180-4a6d-11e9-8200-ab2630b7b934.png)

2. modify web-identity.go for keycloak's information
![image](https://user-images.githubusercontent.com/30501870/54594615-faba9a00-4a6b-11e9-987c-5878eee9e642.png)

3. go run [web-identity.go](https://github.com/minio/minio/blob/master/docs/sts/web-identity.go#L148) ,when I Visit http://localhost:8080, login will direct to the keycloak, 
![image](https://user-images.githubusercontent.com/30501870/54595401-808b1500-4a6d-11e9-84c9-ee687269921b.png)
then, 
![image](https://user-images.githubusercontent.com/30501870/54595479-aca69600-4a6d-11e9-88b9-29ba7ed9e0db.png)
4. Through debugging the web-identity.go  code, when POST to the stsEndpoint , error occurs, 
[Error code line](https://github.com/minio/minio/blob/master/docs/sts/web-identity.go#L148)

                  req, err := http.NewRequest("POST", u.String(), nil)
			if err != nil {
				http.Error(w, err.Error(), http.StatusInternalServerError)
				return
			}
			resp, err := http.DefaultClient.Do(req)
			if err != nil {
				http.Error(w, err.Error(), http.StatusInternalServerError)
				return

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by poornas** [comment]
Can you run minio server with http trace enabled and paste the output? 
i.e. MINIO_HTTP_TRACE=/dev/stdout minio server /tmp/data

**Comment by west789** [comment]
> MINIO_HTTP_TRACE=/dev/stdout
As follows :minio server with http trace output 
![image](https://user-images.githubusercontent.com/30501870/54748217-fa590500-4c0b-11e9-8694-27198a4ef6fd.png)

**Comment by eco-minio** [comment]
@west789 Minimum duration is 900 seconds - https://github.com/minio/minio/blob/master/docs/sts/web-identity.md, can you set the value higher and try again?

**Comment by west789** [comment]
> @west789 Minimum duration is 900 seconds - https://github.com/minio/minio/blob/master/docs/sts/web-identity.md, can you set the value higher and try again?

Thanks for your help, now ,I have credentials
![image](https://user-images.githubusercontent.com/30501870/54804570-f16d3f80-4cae-11e9-88cb-49c4892cf929.png)
but， I use accesskey and serectkey to log in the minio server, error occurs as follows:
![image](https://user-images.githubusercontent.com/30501870/54804530-cb479f80-4cae-11e9-96e6-47cf76ace33d.png)
and I put the token into request headers, also response error
![image](https://user-images.githubusercontent.com/30501870/54804739-8b34ec80-4caf-11e9-82d5-a7da8e73dfc3.png)
![image](https://user-images.githubusercontent.com/30501870/54804828-e535b200-4caf-11e9-98e1-e197c966366a.png)

I can't find how to do after getting the credentials from docs?

**Comment by poornas** [comment]
@west789 , you can't send empty Authorization header in this manner. You could use minio-go SDK's NewWithCredentials() to pass the temp access key/secret key and session token to connect to minio endpoint.

**Comment by harshavardhana** [comment]
There are no current plans in allowing MinIO browser to support WebIdentity based temporary credentials,  it's only supported for S3 API.

**Comment by west789** [comment]
> @west789 , you can't send empty Authorization header in this manner. You could use minio-go SDK's NewWithCredentials() to pass the temp access key/secret key and session token to connect to minio endpoint.
I use NewWithCredentials(), but also Access Denied，how can I do?

![image](https://user-images.githubusercontent.com/30501870/54914465-fab90f00-4f2f-11e9-8e12-7928ba96d8c5.png)
![image](https://user-images.githubusercontent.com/30501870/54914515-1ae8ce00-4f30-11e9-8184-f76868aac556.png)
![image](https://user-images.githubusercontent.com/30501870/54914600-48357c00-4f30-11e9-9d8f-0ed926b51ccb.png)

**Comment by poornas** [comment]
@west789, it should work - perhaps the session token expired? It might be good to run the minio server with http trace enabled `MINIO_HTTP_TRACE=/tmp/log minio server /tmp/data` and attach the request/response trace. 
you can enable trace on minio-go client as well with `minioclient.TraceOn(os.Stdout)`

**Comment by west789** [comment]
for temporary credentials, I get this error
![image](https://user-images.githubusercontent.com/30501870/54968989-88b6e900-4f74-11e9-8f14-8db7e09467f2.png)

and I don't know why this duration doesn's work , the session token still expired a few minutes?
![image](https://user-images.githubusercontent.com/30501870/54969421-f4e61c80-4f75-11e9-866d-5c832e3b3a55.png)

**Comment by poornas** [comment]
@west789, DurationSeconds needs to come from the token expiry, so that is not the issue. The reason you are still getting AccessDenied is because you are missing policy claim as part of JWT token. You will need to configure KeyCloak with policy claim - pls check notes in PR https://github.com/minio/minio/pull/6985 on adding policy claims for WSO2. You will need to do something similar for Keycloak.

**Comment by west789** [comment]
thanks for your help, now ,I have access to get object from minio , I will close issue.
This is how to add policy attribute in keycloak, hope to help others !
1. add user Attribute
![image](https://user-images.githubusercontent.com/30501870/54987329-60200500-4fef-11e9-83b0-94f401ca6f96.png)

2. select client=>choose your client ID=>choose Mapper and create
![image](https://user-images.githubusercontent.com/30501870/54987547-c0af4200-4fef-11e9-935c-5ec91c2bbb36.png)
3. fill the blank

![image](https://user-images.githubusercontent.com/30501870/54987956-75e1fa00-4ff0-11e9-8445-8edce0081a8d.png)


Thanks Again!

**Comment by artb1sh** [comment]
@west789 , what get value user Attribute policy?

**Comment by artb1sh** [comment]
```
[REQUEST (*stsAPIHandlers).AssumeRoleWithWebIdentity-fm] [156266024.818667] [2019-07-09 11:17:28 +0300]
POST /?Action=AssumeRoleWithWebIdentity&DurationSeconds=299&Version=2011-06-15&WebIdentityToken=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJpUG1XdmFucTZWdGtGUFg0Q0YtdFVLb05ONV8yWXJWVERjVUdfbUp4ZnhNIn0.eyJqdGkiOiJkNDk0NjA2Ny0xNGZlLTQ2ZjctYTQ3Yy05MDE3MDg5MWRjYWYiLCJleHAiOjE1NjI2NjA1NDgsIm5iZiI6MCwiaWF0IjoxNTYyNjYwMjQ4LCJpc3MiOiJodHRwOi8vZmwtbWluaW8uZGV2Lnplbml0LnJ1OjgwODAvYXV0aC9yZWFsbXMvbmdpbngiLCJhdWQiOiJuZ2lueCIsInN1YiI6IjAwOThiMmVhLTdlNjMtNDMxNC05YjZjLTQxMDEzMzJkODNlNCIsInR5cCI6IklEIiwiYXpwIjoibmdpbngiLCJhdXRoX3RpbWUiOjE1NjI2NjAyNDcsInNlc3Npb25fc3RhdGUiOiIxYTk5ZTE5Mi05YmMyLTRlY2MtYjQ4Ny1kYjFjYjkwYTBkNTkiLCJhY3IiOiIwIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoidGVzdCB0ZXN0IiwicHJlZmVycmVkX3VzZXJuYW1lIjoidGVzdCIsImdpdmVuX25hbWUiOiJ0ZXN0IiwiZmFtaWx5X25hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QHRlc3QucnUiLCJwb2xpY3kiOlsiNTRhZGJiZTUxM2ZhMDk1M2E5NGYyNjBjM2E1NGNkZmUzMTc3ZTllODhkMzM1ZjA4MWRiZWEyMDZlY2VmMGVkOF9wb2xpY3kiXX0.d6j4dBifhLIWaDxOGMdCImgGU_wWvtt0dYhO3fv-lNdnDl1wiPAj9p3T_xqGcqjktP7FeHiq9aGsuBdOcuJcjo-uBbqI8_NTqZa7d8Ow4sbv-0eHE43SnUfG8hXf2kUdlRQpSJx9z27U1E8gtSsqAChXM55tZELkQr3OiBGrxCy9PkY28NbBV076Hf0KIsv3nNtAh2UsZdPuOPKjB1RUMPsOIb_4SWwpvdFSzFGm0Npod6iRJuCCWetp88w3eY5pzEeVHQ-fJy2Id072suvUyJDutADZzgjA5DIlNz_ze2MZbwTGQn2trw5ZelWBfdymX_VsSg3RQ4xJloy7g7dAYw
Host: localhost:9001
User-Agent: Go-http-client/1.1
Content-Length: 0
Accept-Encoding: gzip


[RESPONSE] [156266024.818667] [2019-07-09 11:17:28 +0300]
400 Bad Request
Vary: Origin
X-Xss-Protection: 1; mode=block
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 15AFAF3765C6BB63
X-Minio-Deployment-Id: b61e0975-7ff3-4e1c-b10c-585282385b10
Server: Minio/RELEASE.2019-02-26T19-51-46Z
Accept-Ranges: bytes
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"><Error><Type></Type><Code>InvalidParameterValue</Code><Message>An invalid or out-of-range value was supplied for the input parameter.</Message></Error><RequestId>15AFAF3765C6BB63</RequestId></ErrorResponse>

```

**Comment by poornas** [comment]
@artb1sh, duration needs to be a minimum of 15 mins (900 seconds)

**Comment by artb1sh** [comment]
@poornas , i set duration 900 ther other error. what fix policy? user in create



```
[REQUEST (*storageRESTServer).ReadAllHandler-fm] [156267019.102659] [2019-07-09 14:03:11 +0300]
POST /minio/storage/v4/opt/storage4/readall?file-path=config%2Fiam%2Fsts%2FZ06MARHV4M6YPFF5RX4F%2Fpolicy.json%2Fxl.json&instance-id=b3041c73-e73b-4694-ba56-963d2abed87b&volume=.minio.sys
Host: fl-minio.dev.zenit.ru:9004
X-Minio-Time: 2019-07-09T11:03:11Z
User-Agent: Go-http-client/1.1
Content-Length: 0
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ3MTYyNzAxOTEsInN1YiI6IkFJTFAyODVDVFFCMTI5VFJVUk5RIn0.gbkV8KmHzVt0DX8I-sC2qWOppkqPDlaSl8dmHZrI7wH5D-xiZcYTv5TNowwIADJR4qepQg0YVCxkUJtDFekb-A

<BODY>

[RESPONSE] [156267019.102659] [2019-07-09 14:03:11 +0300]
403 Forbidden
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 15AFB842653AD565
X-Minio-Deployment-Id: b61e0975-7ff3-4e1c-b10c-585282385b10
Vary: Origin
X-Xss-Protection: 1; mode=block

file not found
```

**Comment by harshavardhana** [comment]
@artb1sh let's open a new issue, we shouldn't be conversating on old unrelated issues.

**Comment by artb1sh** [comment]
how get this policy value?
@harshavardhana @poornas  @west789 
![image](https://user-images.githubusercontent.com/4118703/61169130-1dfcde00-a562-11e9-8b9e-ff4d506f016e.png)

**Comment by poornas** [comment]
@artb1sh, policy value is the policy name defined on iam - follow [this](https://docs.min.io/docs/minio-multi-user-quickstart-guide.html) to set up a custom policy on minio or you can test by changing the policy Value in Keycloak to a canned policy such as readwrite, writeonly or readonly

**Comment by harshavardhana** [comment]
Locking the conversation here, let's open a new issue to discuss @artb1sh
