### ISSUE TITLE
Distributed Minio uses more than 2 times disk storage

### ISSUE THREAD

**Issue by dbjv19** [minio/minio#7395]
The Problem is as the headline said, Distributed Minio uses more than 2 times disk storage. 
The Objects are uploaded into the bucket by using the MinioClient (mc) with the 
cp --recursive 

## Expected Behavior
Normally instead it should just be 2 times initial size

## Current Behavior
I uploaded a folderstructure (folder with files and other folders in it) with 15.12 GB capacity into a distributed minio bucket and then check the drive capacity which is used by each minio disk on all nodes and the result is that 36.6 GB are being used in total, which means 6.1GB per disk. 

## Steps to Reproduce (for bugs)

1. Setup a distributed minio system and the mc (minioclient)
2. Create a bucket
3. Upload a folder with subfolders and files by using cp --recursive
4. check the local file user of the minio mounts with du -sbh and compare 

## Your Environment
* Version used (`2019-03-13T21-59-47Z`):
* Operating System and version (`4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`):

**Comment by kannappanr** [comment]
@dbjv19 As far as data is concerned, it will only be twice the amount of actual data.  Minio also stores incomplete uploads for about two weeks in it's data directories. There is also, metadata about your objects that is stored. They are generally few KB. If you store objects of smaller sizes, then the disk space used might be greater than twice the data uploaded.

**Comment by harshavardhana** [comment]
> Normally instead it should just be 2 times initial size

It cannot be just 2x exact - it is 2x + some metadata values which are in around 2KiB or less.  This is as per design as already explained by @kannappanr

**Comment by dbjv19** [comment]
So it's as intended even though the folder and its files use a total of 2.3 GB on DiskStorage and then its becomes 137.4 GB on the Minio-Storage because of the metainformation ?

**Comment by harshavardhana** [comment]
> So it's as intended even though the folder and its files use a total of 2.3 GB on DiskStorage and then its becomes 137.4 GB on the Minio-Storage because of the metainformation ?

This is perhaps odd @dbjv19 so a question did you upload only 2.3G worth of 1KiB files? what was the size of the individual objects?

**Comment by dbjv19** [comment]
The filesize ranges from around 20KiB to 40KiB. The result is quite different, for one file which has 10KiB it shows on the Minio-Server that 10KIB is used for one of the 6 Drives and in some cases the size is even the double on one minio disk

**Comment by harshavardhana** [comment]
> The filesize ranges from around 20KiB to 40KiB. The result is quite different, for one file which has 10KiB it shows on the Minio-Server that 10KIB is used for one of the 6 Drives and in some cases the size is even the double on one minio disk

We also write bit-rot information along with the data which adds more information as well along with your 10KiB 

For example a 262B file on a 4 disk setup will effectively become    

```
~ 
~ ls /tm\ls -l /tmp/{1..4}/testbucket/hosts/
/tmp/1/testbucket/hosts/:
total 8
-rw-r--r-- 1 harsha harsha  179 Mar 21 02:19 part.1
-rw-r--r-- 1 harsha harsha 1121 Mar 21 02:19 xl.json

/tmp/2/testbucket/hosts/:
total 8
-rw-r--r-- 1 harsha harsha  179 Mar 21 02:19 part.1
-rw-r--r-- 1 harsha harsha 1121 Mar 21 02:19 xl.json

/tmp/3/testbucket/hosts/:
total 8
-rw-r--r-- 1 harsha harsha  179 Mar 21 02:19 part.1
-rw-r--r-- 1 harsha harsha 1121 Mar 21 02:19 xl.json

/tmp/4/testbucket/hosts/:
total 8
-rw-r--r-- 1 harsha harsha  179 Mar 21 02:19 part.1
-rw-r--r-- 1 harsha harsha 1121 Mar 21 02:19 xl.json
```

So you can see for small files such as 262B the final object size is `5200` which is 5KiB so the factor is pretty high which is basically 20x the original file size. 

Whereas when you upload a 1MiB file.
```
~ \ls -l /tmp/{1..4}/testbucket/1MiB
/tmp/1/testbucket/1MiB:
total 520
-rw-r--r-- 1 harsha harsha 524576 Mar 21 02:24 part.1
-rw-r--r-- 1 harsha harsha   1133 Mar 21 02:24 xl.json

/tmp/2/testbucket/1MiB:
total 520
-rw-r--r-- 1 harsha harsha 524576 Mar 21 02:24 part.1
-rw-r--r-- 1 harsha harsha   1133 Mar 21 02:24 xl.json

/tmp/3/testbucket/1MiB:
total 520
-rw-r--r-- 1 harsha harsha 524576 Mar 21 02:24 part.1
-rw-r--r-- 1 harsha harsha   1133 Mar 21 02:24 xl.json

/tmp/4/testbucket/1MiB:
total 520
-rw-r--r-- 1 harsha harsha 524576 Mar 21 02:24 part.1
-rw-r--r-- 1 harsha harsha   1133 Mar 21 02:24 xl.json
```

Here your final size used on disk is `2102836` , now when you divide this by 1MiB file your effective usage factor is 
```
2102836/1048576

2.00542068481445312500
```

which is basically 2x 

As @kannappanr already explained for file sizes smaller than let's say 32KiB overheads are visible, whereas for file sizes beyond 256KiB they get closer and closer to 2x and disappear into fractions for higher file sizes.

**Comment by dbjv19** [comment]
Is the amount of storage the bit-rot information uses a fixed value or does it change depending on the size of the files ? If so is it possible to disable the bit-rot information, so that we can reduce the factor ?

**Comment by harshavardhana** [comment]
> Is the amount of storage the bit-rot information uses a fixed value or does it change depending on the size of the files ? If so is it possible to disable the bit-rot information, so that we can reduce the factor ?

These are all integral part of the data format so they cannot be disabled, small files use more effective storage as shown previously. `xl.json` adds up quite a few KiBs when your object sizes are closer to the `xl.json` size.  There is no way to optimize this right now and it is not our focus at the moment to optimize for small object workloads. Most of our workloads are above 256KiB range so few KiBs extra is harmless at best.
