### ISSUE TITLE
Two basic object operations are incorrect.

### ISSUE THREAD

**Issue by igsol** [minio/minio#7397]
# Environment
* Minio version: 2019-03-13T21:59:47Z
* Minio is installed in simplest standalone configuration.
* `uname -a`: `Linux thehost 4.20.15-200.fc29.x86_64 #1 SMP Mon Mar 11 16:01:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

-----
# Minio behavior

## `List objects` results after the 3 ___empty directories___ were created.

```
$ s3cmd ls s3://svelig
                       DIR   s3://svelig/dir_000000/
                       DIR   s3://svelig/dir_000001/
                       DIR   s3://svelig/dir_000002/
```

## Put one empty file under the `dir_000000` ___directory___

```
$ s3cmd put zero s3://svelig/dir_000000/
upload: 'zero' -> 's3://svelig/dir_000000/zero'  [1 of 1]
 0 of 0     0% in    0s     0.00 B/s  done
```

## 1st bug. `List all objects` results after one file was added

```
$ s3cmd ls --recursive s3://svelig
2019-03-19 16:43         0   s3://svelig/dir_000000/zero
2019-03-19 16:42         0   s3://svelig/dir_000001/
2019-03-19 16:42         0   s3://svelig/dir_000002/
```
Note, Minio missed **directory** object: **_dir_000000_/**.

It's the ___1st bug___.

## Deletion of the object

```
$ s3cmd rm s3://svelig/dir_000000/zero
delete: 's3://svelig/dir_000000/zero'
```

## The 2nd bug. `List all objects` shows that ___dir_000000/___ disappeared

```
$ s3cmd ls --recursive s3://svelig
2019-03-19 16:42         0   s3://svelig/dir_000001/
2019-03-19 16:42         0   s3://svelig/dir_000002/
```

## `List objects` confirms absence of ___dir_000000/___

```
$ s3cmd ls s3://svelig
                       DIR   s3://svelig/dir_000001/
                       DIR   s3://svelig/dir_000002/
```

Despite the two objects ___dir_000000/___ and ___dir_000000/zero___ were created, after the only one second object was removed the ___empty directory___ object was indirectly removed.

IMHO it's a 2nd bug.

-----

# AWS behavior

Let's look behavior of real AWS S3.

## List object

Initially we have three ___empty directory___ objects:

```
$ s3cmd ls s3://svelig
                       DIR   s3://svelig/dir_000000/
                       DIR   s3://svelig/dir_000001/
                       DIR   s3://svelig/dir_000002/
```

## The file is added

```
$ s3cmd put zero s3://svelig/dir_000000/
upload: 'zero' -> 's3://svelig/dir_000000/zero'  [1 of 1]
 0 of 0     0% in    0s     0.00 B/s  done
```

## `List all objects` shows all 4 added objects

Note, that AWS S3 returns all 4 created objects: 3 ___directories___ and one file. Minio behaves differently.

```
$ s3cmd ls --recursive s3://svelig
2019-03-19 17:21         0   s3://svelig/dir_000000/
2019-03-19 17:22         0   s3://svelig/dir_000000/zero
2019-03-19 17:21         0   s3://svelig/dir_000001/
2019-03-19 17:21         0   s3://svelig/dir_000002/
```

## File object deletion

```
$ s3cmd rm s3://svelig/dir_000000/zero
delete: 's3://svelig/dir_000000/zero'
```

## `List all objects` shows all 3 initial empty ___directories___

Note ___Empty directory___ object ___dir_000000/___ survives after deletion underlying ___file___ object.

```
$ s3cmd ls --recursive s3://svelig
2019-03-19 17:21         0   s3://svelig/dir_000000/
2019-03-19 17:21         0   s3://svelig/dir_000001/
2019-03-19 17:21         0   s3://svelig/dir_000002/
```

## `List objects` confirms

All 3 initial empty ___directories___ are present.

```
$ s3cmd ls s3://svelig
                       DIR   s3://svelig/dir_000000/
                       DIR   s3://svelig/dir_000001/
                       DIR   s3://svelig/dir_000002/
```

# The expected behavior

S3 is a plain ___key-value___ object storage. The file system tree hierarchy is emulated just by naming conventions.

The object ___dir_000000/___ and the object ___dir_000000/zero___ are a two different objects.

Thus `list object` operation should list all existing objects.

Deletion of one ___leaf file___ object should not lead unexpected removing of other ___upper directory___ object.

**Comment by harshavardhana** [comment]
This is expected @igsol and as per design we cannot support this - it is laboriously explained why  

https://github.com/minio/minio/issues/7335#issuecomment-470683398

**Comment by igsol** [comment]
@harshavardhana 
Thank you for explanation.

Sorry, I can't agree with your reasons. E.g. if for directory we want to store ACLs, xattrs etc. in a custom (x-amz-meta-) metadata, with your solution we have to implement a workarounds.

Minio [documentation](https://docs.minio.io/docs/minio-quickstart-guide.html) states:

> Minio is an object storage server... It is __compatible__ with __Amazon S3__ cloud storage service.

But if even such basic operations are too diverse from original S3 API behaviour, then I think above statement is not correct.

And permitting to create empty directory, but remove it silently after last leaf file is removed is very inconsistent solution IMHO.

**Comment by harshavardhana** [comment]
@igsol it doesn't really matter if we agree on not, it is a design choice for us and we are going to live with it into the near future. In our opinion, S3's behavior is unexpected and leads to bad application behavior. 

> But if even such basic operations are too diverse from original S3 API behaviour, the I think above statement is not correct.

If this is a strict requirement for you then Minio is perhaps not the right solution for you.  Our compatibility exists to an extent which makes logical sense, features such as these which encourage bad application behavior we reject such operations and behave in accordance which helps our users.

ACLs are legacy and incorrectly implemented on AWS S3 - inheritance of permissions etc are inconsistent.  You should be using bucket policies instead @igsol which don't require the existence of such prefixes and bucket policies are the right approach for more granular control. 

> And permitting to create empty directory, but remove it silently after last leaf file is removed is very inconsistent solution IMHO.

This is one point we agree, but we had to do this for some odd requirement by legacy application behavior. We are not planning to extend this style beyond this behavior. We agree that it's inconsistent.

**Comment by igsol** [comment]
> ACLs are legacy and incorrectly implemented on AWS S3

Sorry, I wasn't clear. I mean FS ACLs, like POSIX ACLs, also standard Unix permissions, ownerships, xattr, so on.

If we need to copy our files to S3-like based cloud preserving FS attributes for directory the custom metadata looks as quite natural place.

> This is one point we agree, 

Great :)

> but we had to do this for some odd requirement by legacy application behavior.

The most applications count on standard de facto AWS S3 behavior despite its oddity. 
Once upon a time some application needs to scale up to real AWS S3, then the troubles are unavoidable.
I think compatibility is important thing in the not ideal world :)

**Comment by harshavardhana** [comment]
> The most applications count on standard de facto AWS S3 behavior despite its oddity.


> Sorry, I wasn't clear. I mean FS ACLs, like POSIX ACLs, also standard Unix permissions, ownerships, xattr, so on.
> 
> If we need to copy our files to S3-like based cloud preserving FS attributes for directory the custom metadata looks as quite natural place.

You can still do that for each object will have the right values stored in object metadata. But again relying on POSIX permissions itself is quite a bit of backpedaling, I don't know how that would scale for modern data centers. 

MinIO already implements SSO support with OpenID connect with IAM policies by providing STS and restricting permissions per temporary credential. This is done without the use of any ACLs by externalizing identity, while also providing rich granular functionality.

> The most applications count on standard de facto AWS S3 behavior despite its oddity.
> Once upon a time some application need to scale up to real AWS S3, then they get a trouble.
> I think compatibility is an important thing in the not ideal world :)

In the wild, we have found 2 enterprise applications which want this behavior one is 

- hadoop S3A filesystem (used by spark etc) - we will fix this upstream eventually.
- other applications like file browsers which try to mimic POSIX behavior

No other application which we have found requires this behavior, be it a mobile application of a large enterprise to CI/CD applications, Backup tools which capture permissions per object (save them in metadata) etc.  

So we haven't found any application which cannot be modified to suit a more modern behavior in-fact when an application is modified with such appropriate behavior, the application has become more performant and more scalable - for example, Hadoop S3A has s3 magic committer which exactly does this avoid using "directories". 

So we would love to keep it this way and let applications move to more appropriate behavior. 

AWS S3 is a defacto standard no doubt about that, you may even call it the new POSIX. But it doesn't mean that we will not make design decisions to deprecate legacy behavior which they carry forward.

**Comment by igsol** [comment]
> If this is a strict requirement for you then Minio is perhaps not the right solution for you. 

At this moment Minio is the best application for our developers needs except a few incompatibilities mentioned in this issue.

> Our compatibility exists to an extent which makes logical sense, features such as these which encourage bad application behavior we reject such operations and behave in accordance which helps our users.

I don't see how these 2 bugs fixing could encourage bad application behavior, at least our application :)

We do need to "backup" all files and directories (including empty) from the POSIX FS to the S3 cloud storage. Our application can backup all files and directories attributes (POSIX ACK, xattr, permissions, ownership). Also our application should restore from S3 the files and directories back on POSIX FS ideally with all original attributes. Skipping "directory/" keys in `List Objects` makes a few annoyances for us. 

Fortunately Minio is open source application and we are really grateful for that.
Thus my colleague made already an optional (i.e. configurable) "fix" to perform fully compatible with **real** AWS S3 `List Objects` behavior.

**Comment by nitisht** [comment]
Based on comments above, closing the issue as there is no further action needed.
