### ISSUE TITLE
Long delays when using Distributed Minio when one node is offline

### ISSUE THREAD

**Issue by ShaunMaher** [minio/minio#7400]
I have a three node distributed Minio cluster.  Each node has two disks.  If I shut down one node, to simulate a node failure, the remaining nodes take a long time to service requests.

## Expected Behavior
Since more than 50% of the nodes are available, I expected some performance degradation but that the platform would generally continue to function as it does normally.

Making a request to http://127.0.0.1:9000/minio/prometheus/metrics should return in a timely manner, even if parts of the cluster are offline.  Ideally, the output should reflect that parts of the cluster are failing.

## Current Behavior
For the first request of a file from the cluster there is a delay of approximately 150 seconds.  Generally, the next request for the same file will be nearly instantaneous.  Making a request for a different file however incurs the 150 second delay.

Making a request to http://127.0.0.1:9000/minio/prometheus/metrics takes about 121 seconds.

## Possible Solution
More aggressive timeout settings for inter-node communication?

## Steps to Reproduce (for bugs)
1. Setup three node cluster in FreeBSD jails.  All nodes are in the same DC connected with either Gbit to 10Gbit networking.
2. Populate cluster with a bucket containing some test data
3. Configure the bucket to allow public downloads
4. With all nodes of the cluster available, use a command line tool to download a test file and report to total time taken: `/usr/bin/time fetch -T 300 -q -o - http://127.0.0.1:9000/minio-packages/minio-DEVELOPMENT.GOGET-20190319-0707 | pv >/dev/null`
5.  Take one node offline by gracefully shutting down the FreeBSD jail (I'm not sure which signal is sent to daemon processes when this occurs).
6.  Run the same test command and notice the vast difference in the amount of time taken

## Context
We are using Minio to host the media (mostly images) for a large website.  Contributions happen via the S3 API to a bucket that has public download permissions.  Consumers read the media using normal HTTP GET requests.

Ideally, an outage of a single node would only have a minimal effect on consumers.  At the moment though, if a single node fails a 150 second delay occurs before each GET request is serviced.

Is there a way to tell Minio that one node is down and that it should stop trying to use it?  Something that could be used before maintenance of a single node or could be used by an administrator during an unexpected outage when they know the failed node is going to be offline for a while?

## Regression
Is this issue a regression? No

## Your Environment

* Version used (`minio version`): Commit 73be3ed0ca93119a18e650909ab8f13635966b89 (Mar 19, 7:07am) and 2019-03-13T21:59:47Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: FreeNAS (FreeBSD).  Minio runs in a FreeBSD Jail.
* Operating System and version (`uname -a`): `FreeBSD miniodata5.atw.cust.mach.net.au 11.1-STABLE FreeBSD 11.1-STABLE #0 r321665+6bdfda58b62(HEAD): Thu Dec 20 14:27:36 EST 2018     root@mp19.lab.ixsystems.com:/freenas-releng-final/freenas/_BE/objs/freenas-releng-final/freenas/_BE/os/sys/FreeNAS.amd64  amd64
`

**Comment by harshavardhana** [comment]
To be fixed in #7398

**Comment by kannappanr** [comment]
Closing this issue as #7398 has been merged. Please re-open the issue if you can still repro the issue with the latest release.

**Comment by ShaunMaher** [comment]
Hi.

I'm not entirely sure that this issue is resolved yet.  I have just submitted the following in the Slack channel, which I'll copy here for reference.

>I'm (still) having some issues with a distributed Minio cluster.  I have three nodes, each with two drives.

>My intention for using the distributed mode was to increase availability but I don't seem to have achieved that goal.  I upgraded my test cluster to "2019.03.27.22.35.21" this morning hoping to see that the issue I reported here: https://github.com/minio/minio/issues/7400 was resolved.  It still seems to be the case however that one node being taken offline renders the cluster unable to serve any content in a timely fashion.

>For testing I was downloading a file from a bucket.  The file has been in the bucket for a couple of weeks.  With all three nodes operating, I can download the file in 0.14 of a second.  With one of the three nodes offline, I can't download the file at all:
```
# /usr/bin/time minio-client cat localhost/minio-packages/minio-2019.03.13.21.59.47.txz |pv >/dev/null
minio-client: <ERROR> Unable to read from `localhost/minio-packages/minio-2019.03.13.21.59.47.txz`. Multiple disk failures, unable to reconstruct data.
      273.10 real         0.02 user         0.01 sys
```
>So, it takes nearly 5 minutes and then fails.

>Have I messed up by having two disks per node?  Have I somehow ended up in a situation where enough data exists only on one of the nodes that the remaining majority cannot reconstruct the file to serve it?

>Thanks again for your support.
>Shaun.

**Comment by kannappanr** [comment]
@ShaunMaher It could be that the data is not written on all disks. Can you try 
```
minio-client admin heal --dry-run --json -r  localhost/minio-packages

```

This will tell you how many disks and what all disks have data for that object

**Comment by ShaunMaher** [comment]
Thanks for the followup and re-opening the bug.

For just the file in question:
```
{
  "status": "success",
  "type": "object",
  "name": "minio-packages/minio-2019.03.13.21.59.47.txz",
  "before": {
    "color": "red",
    "offline": 0,
    "online": 4,
    "missing": 0,
    "corrupted": 2,
    "drives": [
      {
        "uuid": "",
        "endpoint": "/mnt/miniodata_1",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "http://miniodata6.atw.cust.mach.net.au:9000/mnt/miniodata_1",
        "state": "corrupt"
      },
      {
        "uuid": "",
        "endpoint": "http://miniodata7.atw.cust.mach.net.au:9000/mnt/miniodata_1",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "/mnt/miniodata_2",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "http://miniodata6.atw.cust.mach.net.au:9000/mnt/miniodata_2",
        "state": "corrupt"
      },
      {
        "uuid": "",
        "endpoint": "http://miniodata7.atw.cust.mach.net.au:9000/mnt/miniodata_2",
        "state": "ok"
      }
    ]
  },
  "after": {
    "color": "red",
    "offline": 0,
    "online": 4,
    "missing": 0,
    "corrupted": 2,
    "drives": [
      {
        "uuid": "",
        "endpoint": "/mnt/miniodata_1",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "http://miniodata6.atw.cust.mach.net.au:9000/mnt/miniodata_1",
        "state": "corrupt"
      },
      {
        "uuid": "",
        "endpoint": "http://miniodata7.atw.cust.mach.net.au:9000/mnt/miniodata_1",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "/mnt/miniodata_2",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "http://miniodata6.atw.cust.mach.net.au:9000/mnt/miniodata_2",
        "state": "corrupt"
      },
      {
        "uuid": "",
        "endpoint": "http://miniodata7.atw.cust.mach.net.au:9000/mnt/miniodata_2",
        "state": "ok"
      }
    ]
  },
  "size": 9555224
}
```

So, it has come corrupt parts.  I'll repeat my testing with another file in the bucket and get back to you shortly.

Cheers.
Shaun.

**Comment by kannappanr** [comment]
@ShaunMaher If `miniodata6` is down, you should be able to read the data. If either `miniodata7` or `localhost` is down, then there isn't enough quorum, so you will not be able to read the data. Will have to check why it is taking so long to respond when one of the nodes is down. Can you validate if the read is fast if `miniodata6` is down when you try to read this object?

**Comment by ShaunMaher** [comment]
OK! this is more like what I expected!

With all 3 nodes (6 disks) running:
```
[mach@miniodata6 ~]$ /usr/bin/time minio-client cat localhost/minio-packages/minio-2019.03.27.22.35.21.txz |pv >/dev/null
        0.17 real         0.01 user         0.01 sys
```
Super fast, super happy.

Shut down one node and then immediately make a request:
```
[mach@miniodata6 ~]$ /usr/bin/time minio-client cat localhost/minio-packages/minio-2019.03.27.22.35.21.txz |pv >/dev/null
      104.12 real         0.01 user         0.01 sys                                                                              ]
```
104s.  That sucks but if it takes ~120s for the cluster to notice there's an issue, fine.

Next request for the same file:
```
[mach@miniodata6 ~]$ /usr/bin/time minio-client cat localhost/minio-packages/minio-2019.03.27.22.35.21.txz |pv >/dev/null
        5.10 real         0.01 user         0.01 sys                                                                              ]
```
5s.  Slow but operational.  The cluster is serving content in a reasonable time.  Users get a sluggish experience but the service is defiantly still operating.  Good result.

Request a different file that hasn't been requested since one node was removed:
```
[mach@miniodata6 ~]$ /usr/bin/time minio-client cat localhost/minio-packages/sudo-1.8.27_1.txz |pv >/dev/null
        0.11 real         0.01 user         0.00 sys
```
Back to super fast.  This file is smaller than the previous test but still, very good result.

Another file that hasn't been requested before:
```
[mach@miniodata6 ~]$ /usr/bin/time minio-client cat localhost/minio-packages/minio-DEVELOPMENT.GOGET-20190319-0707 |pv >/dev/null
        5.56 real         0.03 user         0.06 sys                                                                              ]
```
Back to the ~5s point.  Slow but operational.  Very happy.

So, apart from my initial testing with a broken file, I'm happy to agree that this bug is resolved.

Thank you so much.  I hope I didn't waste too much of your time.

Cheers.
Shaun.

**Comment by harshavardhana** [comment]
Thanks @ShaunMaher closing
