### ISSUE TITLE
minio server not reading bucket

### ISSUE THREAD

**Issue by GvandeSteeg** [minio/minio#7401]
I'm running Minio server on several of our Windows machines so I can collect all their logs from my computer for parsing.
The windows machines have a folder setup like so: `C:\Program Files\HEAD\logfiles`, but HEAD contains multiple other folders. I only want the `logfiles` to be loaded as a bucket. This used to work before when I pointed minio server at HEAD, as it would only pick up lowercase folders. Now it picks up everything when pointed at HEAD, and nothing when pointed at HEAD\logfiles.

## Expected Behavior
`minio.exe gateway nas "C:\Program Files\HEAD\logfiles"`
Minio Browser shows all files within HEAD\logfiles

## Current Behavior
`minio.exe gateway nas "C:\Program Files\HEAD\logfiles"`
Minio Browser shows no data
`minio.exe gateway nas "C:\Program Files\HEAD"`
Minio Browser shows all files within all folders on HEAD, where only logfiles is wanted.

## Context
HEAD contains too much data to store publish on minio, so we're not interested in using an "all over nothing" approach. It would be great to point minio at a folder and it loads that folder as a bucket

## Your Environment
* Version used (`minio version`): Version: 2019-03-13T21:59:47Z
Release-Tag: RELEASE.2019-03-13T21-59-47Z
Commit-ID: 285c09fe6b012583ce4fe07e3f9221fcbad4df2c
* Operating System and version (`uname -a`): Windows 7 Professional

**Comment by kannappanr** [comment]
@GvandeSteeg We added support to show buckets with capital letters in `fs` mode to fix issue #6938. Can you create a user who has only permissions to the `logfiles` bucket and login to the browser with that credential?

**Comment by GvandeSteeg** [comment]
@kannappanr I'm afraid that wouldn't be acceptable, as the logged-in user is an automation credential that needs the attached machine to be able to write to all folders. Restricting access to the other folders would stop the machine from running properly.

**Comment by kannappanr** [comment]
@GvandeSteeg When I said `create a user`. I meant create a user in minio that will only have permissions to this bucket alone.

**Comment by GvandeSteeg** [comment]
@kannappanr Sorry for the misunderstanding, but I can't figure out how to create a user in minio with limited access to buckets. I'm following the [minio admin guide](https://docs.minio.io/docs/minio-admin-complete-guide.html) and I'm able to add users with readonly access, but can't limit the buckets.

And as a hypothetical question, since #6938 resolved capital letter buckets, what would happen if I renamed the folder back to `LogFiles` and starting minio server? With the Python SDK I'm unable to use `LogFiles` as a bucketname, but will it still find the folder/bucket if I use the following?

```python
from minio import Minio

minio = Minio(**config)
minio.list_objects('logfiles') # Does this return data inside LogFiles?
```

I've got python-minio `minio-4.0.12` installed

**Comment by kannappanr** [comment]
@GvandeSteeg Will send in a fix to support bucket names with capital letters in minio-py. Bucket names are case sensitive, so your example will not work. 

Here is a sample policy json file

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Stmt1553675347197",
      "Action": [
        "s3:GetBucketLocation",
        "s3:GetObject",
        "s3:HeadBucket",
        "s3:ListBucket"
      ],
      "Effect": "Allow",
      "Resource": "arn:aws:s3:::logfiles/*"
    }
  ]
}
```

```
$ mc admin policy add myminio testpol ~/Desktop/policy.json
Added policy `testpol` successfully.
```
```
mc admin user add myminio foo foobar123 testpol
Added user `foo` successfully.
```
```
$ mc config host add myfoo http://127.0.0.1:9000 foo foobar123 --api "s3v4"
Added `myfoo` successfully.
```
```
$ mc ls myfoo/logfiles
[2019-03-21 15:14:31 PDT]    20B issue
```

**Comment by GvandeSteeg** [comment]
```bash
➜ mc admin policy add haem_test testpol policy.json
Added policy `testpol` successfully.

➜ mc admin user add haem_test foo bar testpol
Added user `foo` successfully.

➜ mc ls haem_test/logfiles
[2019-03-28 14:32:46 GMT] 7.0KiB passing_example.trc

➜ mc admin user list haem_test
enabled    foo                   testpol
disabled   guus                  readwrite

➜ mc ls haem_test/logfiles
[2019-03-28 14:32:46 GMT] 7.0KiB passing_example.trc

➜ mc ls haem_test
[2019-03-28 14:32:46 GMT]     0B logfiles/

➜ mc cp ~/PycharmProjects/environment/haem/test_haem/resources/passing_example.trc haem_test/notlogfiles
...aem/test_haem/resources/passing_example.trc:  6.98 KB / 6.98 KB  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100.00% 1.12 MB/s 0s
~
➜ mc ls haem_test
[2019-03-28 14:32:46 GMT]     0B logfiles/
[2019-03-28 14:36:39 GMT]     0B notlogfiles/

~
➜ mc ls haem_test/notlogfiles
[2019-03-28 14:36:39 GMT] 7.0KiB passing_example.trc
```

I figured disabling myself (an admin) would remove access to the `notlogfiles` bucket, but I still have access to everything. what's the user policy supposed to do?

**Comment by kannappanr** [comment]
You should do something similar to 
```
$ mc config host add myfoo http://127.0.0.1:9000 foo foobar123 --api "s3v4"
Added `myfoo` successfully.
```
```
$ mc ls myfoo/logfiles
[2019-03-21 15:14:31 PDT]    20B issue
```

Once you create the user `foo`, you should add an entry in `mc` to access your `s3 server` using the credentials of the user `foo`.

**Comment by GvandeSteeg** [comment]
Is `user foo` the same as `accessKey=foo`? I'm getting a bit confused by the arbitrary examples that we're throwing around

**Comment by kannappanr** [comment]
@GvandeSteeg `foo` is the user created who would only have access to the `logfiles` bucket.

**Comment by GvandeSteeg** [comment]
I've got the `mc config host add` part done before, and I have the user `foo`; how do I link one to the other? I can do
```
➜ mc admin user list haem_test
enabled    foo                   testpol
disabled   guus                  readwrite
```
Which shows that foo is enabled for `haem_test`, but still has access to `notlogfiles`

**Comment by kannappanr** [comment]
@GvandeSteeg 

Can you print the output of

```
mc admin policy list haem_test testpol

```

**Comment by GvandeSteeg** [comment]
Not sure what's going on, but suddenly I'm getting an error:
```
mc admin user list haem_test
mc: <ERROR> Cannot list user. The specified method is not allowed against this resource.

mc admin policy list haem_test testpol
mc: <ERROR> Cannot list policy. The specified method is not allowed against this resource.
```


I've tried restarting the minio server, and removed and recreated the host in `mc config host add`, but to no avail.
Is this caused by disabling my own user earlier?

**Comment by kannappanr** [comment]
@GvandeSteeg Can you do `mc config host list haem_test` and make sure that it has the admin user credentials and you have not overwritten that?

**Comment by GvandeSteeg** [comment]
I think I might have:
```
mc config host list haem_test
haem_test:  http://127.0.0.1:9000  haem_admin  haem_admin  s3v4  auto
```

**Comment by kannappanr** [comment]
@GvandeSteeg `Is this caused by disabling my own user earlier?` How did you do this? I do not see this.

**Comment by GvandeSteeg** [comment]
```
➜ mc admin user list haem_test
enabled    foo                   testpol
disabled   guus                  readwrite
```
I disabled myself and enabled foo in an attempt to mock a single user with specific access rights

**Comment by GvandeSteeg** [comment]
But I've removed and re-added haem_test in the meantime, so that should've been reset, shouldn't it?

**Comment by kannappanr** [comment]
@GvandeSteeg Sorry, somehow missed this issue. Are you still seeing this issue?

**Comment by GvandeSteeg** [comment]
@kannappanr Unfortunately yes, I can't even enable myself any longer. Perhaps I should just reinstall mc entirely:
```
mc admin user enable haem_test guus
mc: <ERROR> Cannot enable user. The specified method is not allowed against this resource.
```

**Comment by kannappanr** [comment]
@GvandeSteeg Yes, we can start with reinstalling `mc`. You will have to remove `/.mc/config.json`

**Comment by kannappanr** [comment]
Closing this issue as stale. Please feel free to reach out to us if you have more information.
