### ISSUE TITLE
How to migrate minio data

### ISSUE THREAD

**Issue by Danbuth** [minio/minio#7403]
about minio
I want to know how to export data from minio or migrate data from minio.
Sometimes data needs to be migrated.

**Comment by nitisht** [comment]
You can use https://docs.minio.io/docs/minio-client-complete-guide.html#mirror

Closing this issue, feel free to reach out on slack for more such questions. [https://slack.minio.io]

**Comment by Danbuth** [comment]
minio client can use 'mirror' to upload local files to minio bucket, this is backup local files.
but how to backup minio buckets, such as download the whole bucket files, and Retain buckets structure.

**Comment by kannappanr** [comment]
It is not just for `local files` to `minio bucket`, it can also be used to replicate `minio bucket` to `local files`

**Comment by BabyBoat** [comment]
> minio client can use 'mirror' to upload local files to minio bucket, this is backup local files.
> but how to backup minio buckets, such as download the whole bucket files, and Retain buckets structure.

Have you found the way to migrate 1 online minio to another online-minio ? The doc is not very easy to understand for beginners like me

**Comment by harshavardhana** [comment]
> Have you found the way to migrate 1 online minio to another online-minio ? The doc is not very easy to understand for beginners like me

@BabyBoat please join us on slack https://slack.min.io  for more real-time questions
