### ISSUE TITLE
Unable to run the Minio-server on https.

### ISSUE THREAD

**Issue by maniker** [minio/minio#7405]
Unable to access the Minio-server on https using a CA cert

I have installed my CA cert in [testwassys376l]/home/was/.minio/certs> directory  i followed the document and did the same  but i am unable to run the minio on https.

[testwassys376l]/home/was/.minio/certs> ls
CAs  dev.com.crt  dev.com.key 

Is there any anything else I have to do?? and please let me know if you need any further information I can give you all.

I tried to look into the closed issues previously, but i did not find the right result. Not sure if have doing wrong though.
```
Minio Version
Version: 2019-01-31T00:31:19Z
Release-Tag: RELEASE.2019-01-31T00-31-19Z
Commit-ID: b18c0478e72bf46b2dbe80ef51c6859bddeee2c0

Operating System :- Linux
```
The command used to start my minio-server is    `./minio server /home/was`
```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ You are running an older version of Minio released 1 month ago ┃
┃ Update: Run `minio update`                                     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

Endpoint:  http://10.162.91.136:9000  http://127.0.0.1:9000
AccessKey: BZM8PZFX7H91Y4GULSFV
SecretKey: 7RrXmKZ3XkwEFsVno8fRlJpq0QyUbzYc3WGZol7I

Browser Access:
   http://10.162.91.136:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://10.162.91.136:9000 BZM8PZFX7H91Y4GULSFV 7RrXmKZ3XkwEFsVno8fRlJpq0QyUbzYc3WGZol7I

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
```
 I am not sure in what mode it is running in we have just installed in on one of our test linux servers and trying to play around with it, still did not use all the features minio has. I apologize for not using the template, will surely use it the next time.

**Comment by kannappanr** [comment]
@maniker can you please use the template to file issues going forward. It has questions like minio version, your OS, etc. 

Can you provide `minio version`, `OS`, What mode minio is running in. Command you used to start minio, console output on startup etc

**Comment by kannappanr** [comment]
@maniker 
```
[testwassys376l]/home/was/.minio/certs> ls
CAs dev.com.crt dev.com.key
```
The names should be `public.crt` and `private.key`

**Comment by maniker** [comment]
@kannappanr  Ok gotcha, I have changed it I'll try it and update you thanks :-)

**Comment by maniker** [comment]
I have done changing the names of those files, and when 
i start my minio server with the command   ./minio server /home/was , it says

ERROR Unable to load the TLS configuration: The private key contains additional data.
      > Please check your certificate.
So do you think something is wrong with my private key chain or it has to do something with the way i start it??

**Comment by harshavardhana** [comment]
Your private key is perhaps corrupted @maniker

**Comment by kannappanr** [comment]
[public.crt.txt](https://github.com/minio/minio/files/2994640/public.crt.txt)
[private.key.txt](https://github.com/minio/minio/files/2994641/private.key.txt)
I have copied sample files that should work on your setup. Try it out and let us know. Like @harshavardhana said it is most probably something wrong with the way the certificates and keys were generated. Please also remove `.txt` at the end of the filenames

**Comment by kannappanr** [comment]
ping @maniker Did you get to try the cert files attached?

**Comment by kannappanr** [comment]
@maniker closing this issue now. Please feel free to re-open this issue if you have more information.

**Comment by maniker** [comment]
@kannappanr sorry for the late reply i was able to run the minio on https with the file patterns  you have sent me.

Thanks a lot, you guys are doing a great job
