### ISSUE TITLE
No unit test for ../cmd/crypto/vault.go

### ISSUE THREAD

**Issue by ebozduman** [minio/minio#7409]
Missing unit test, `cmd/crypto/vault_test.go` needs to be added as part of the `Unit Test Refactoring` effort.

**Comment by harshavardhana** [comment]
We should be a bit more descriptive perhaps in the issue, one advantage is it ensures that our community also follows it and we don't have to proactively tell them. When not using the template we should indicate why we are not using the template.

Here we know that unit test should be added but we don't know which pathway is most affected, we can elaborate that by looking at coverage provided by `go test -coverprofile=cover.out`, subsequently perhaps output of  

```go tool cover -html``` can be attached.

**Comment by ebozduman** [comment]
This is a `Unit Test Refactoring` task/issue and I'll be filing bunch of them, all about missing unit tests to increase our coverage.

While filing this very first missing unit test issue, Deepa and I discussed and decided not to use the template since almost all fields/sections of the template are not applicable.

I'll check the coverage outputs and add any relevant information into these issues, I'll be filing going forward as part of `Unit Test Refactoring` task.

**Comment by poornas** [comment]
@ebozduman, the only unit testable function in this file would be config initialization. The remaining functions can only be tested as functional tests because they require a vault server up and running.
