### ISSUE TITLE
no node join feature?

### ISSUE THREAD

**Issue by chinglinwen** [minio/minio#7411]
There seems no node expanding feature, join a new node etc.

## Expected Behavior

Can join new node, to expand the storage capacity.
Also make the endpoint no need of manual specify,  no need to pre-known all the nodes (no restart of existing nodes ).

## Current Behavior

`ERROR Unable to initialize backend: 1st disk is already being used in another erasure deployment. (Number of disks specified: 6 but the number of disks found in the 1st disk's format.json: 4).`

## Steps to Reproduce (for bugs)

```
export MINIO_ACCESS_KEY=Q25H18HEK2D0HLSQJJEK
export MINIO_SECRET_KEY=9Uyocw8z8PiVusl3jC8nI9jnZCfSf2bC7xBGQ1yA

./minio server --address :9001 http://localhost:9001/data/disk1/tenant1 http://localhost:9002/data/disk2/tenant1 http://localhost:9003/data/disk3/tenant1 http://localhost:9004/data/disk4/tenant1

./minio server --address :9002 http://localhost:9001/data/disk1/tenant1 http://localhost:9002/data/disk2/tenant1 http://localhost:9003/data/disk3/tenant1 http://localhost:9004/data/disk4/tenant1

./minio server --address :9003 http://localhost:9001/data/disk1/tenant1 http://localhost:9002/data/disk2/tenant1 http://localhost:9003/data/disk3/tenant1 http://localhost:9004/data/disk4/tenant1

./minio server --address :9004 http://localhost:9001/data/disk1/tenant1 http://localhost:9002/data/disk2/tenant1 http://localhost:9003/data/disk3/tenant1 http://localhost:9004/data/disk4/tenant1

./minio server --address :9005 http://localhost:9001/data/disk1/tenant1 http://localhost:9002/data/disk2/tenant1 http://localhost:9005/data/disk5/tenant1 http://localhost:9006/data/disk6/tenant1
  //why 9005 offline

# try restart one? ( I don't find any doc relate to join )
./minio server --address :9001 http://localhost:9001/data/disk1/tenant1 http://localhost:9002/data/disk2/tenant1 http://localhost:9003/data/disk3/tenant1 http://localhost:9004/data/disk4/tenant1 http://localhost:9005/data/disk5/tenant1 http://localhost:9006/data/disk6/tenant1

#ERROR Unable to initialize backend: 1st disk is already being used in another erasure deployment. (Number of disks specified: 6 but the number of disks found in the 1st disk's format.json: 4).
```
## Your Environment

* Version used (`minio version`): 
  ./minio version
Version: 2019-03-20T22:38:47Z
Release-Tag: RELEASE.2019-03-20T22-38-47Z
Commit-ID: a9032b52b86d9d8a2b89ebbf47a50bc233565f3f
* Environment name and version (e.g. nginx 1.9.1): 
* Server type and version: centos7.3.1611
* Operating System and version (`uname -a`):
  Linux kube-test-10-237 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by nitisht** [comment]
@chinglinwen this is expected and part of design. Instead of adding nodes to existing cluster and risk destabilization of whole cluster - we recommend adding new clusters as and when needed. 

If required you can combine old and new clusters using federation as explained here https://docs.minio.io/docs/minio-federation-quickstart-guide.html

**Comment by chinglinwen** [comment]
sounds good to me.

**Comment by chinglinwen** [comment]
my boss seems worry about this, no expand of storage, it then may someday not able to handle business requirements

we think the dns federation is a little complicated

so we may decide to separate it according to the business unit ( it's still may some day out of space, then  we may need manual migration?  we don't want things that need move around (what if it so big, and move around need stop the service) )

what's the best practice? @nitisht

**Comment by harshavardhana** [comment]
> my boss seems worry about this, no expand of storage, it then may someday not able to handle business requirements

This is not part of the plan for any foreseeable future @chinglinwen - the DNS federation is the right way to scale for large scale data centers. Most modern data applications remember URLs if it comes from cluster1 or cluster2 it doesn't matter. From an application point of view, you are not writing to the cluster1 anymore since it ran out of disk space.

**Comment by chinglinwen** [comment]
thanks for the explanation, it makes me feel more confident with dns federation approach. @harshavardhana
