### ISSUE TITLE
Minio as GW to EMC S3

### ISSUE THREAD

**Issue by erland64** [minio/minio#7418]
My intension is to use Minio S3 as a gateway against EMC S3 bucket storage.
 
If I use AWS CLI against Minio server It works perfect but if I use Minio MC client it hangs.
 
Any Idea why?
 
 
AWS – WORKS PERFECT
aws --endpoint-url http://127.0.0.1:9000 s3 ls s3://aplog_prd/
Server: Minio/RELEASE.2019-03-20T22-38-47Z
Accept-Ranges: bytes
 
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>aplog_prd</Name><Prefix></Prefix><KeyCount>1</KeyCount><MaxKeys>1000</MaxKeys><Delimiter>%2F</Delimiter><IsTruncated>false</IsTruncated><CommonPrefixes><Prefix>snapshots%2F</Prefix></CommonPrefixes><EncodingType>url</EncodingType></ListBucketResult>
 
[REQUEST objectAPIHandlers.ListObjectsV2Handler-fm] [155326869.416263] [2019-03-22 16:31:34 +0100]
GET /aplog_prd?list-type=2&encoding-type=url&delimiter=%2F&prefix=
Host: 127.0.0.1:9000
X-Amz-Date: 20190322T153134Z
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=aplog_prd/20190322/"ece-region"/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=d92bbaea5f387a96d2c967f2540f0ae21906bc718ae169ce4cdded473cc2647c
User-Agent: aws-cli/1.16.125 Python/3.4.9 Linux/3.10.0-957.1.3.el7.x86_64 botocore/1.12.115
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 
MINIO MC CLIENT HANGS
minio/mc --debug ls s3/aplog_prd/
 
[RESPONSE] [155326869.416263] [2019-03-22 16:31:34 +0100]
200 OK
X-Amz-Request-Id: 158E51A5D448AB39
Server: Minio/RELEASE.2019-03-20T22-38-47Z
Accept-Ranges: bytes
Content-Type: application/xml
Vary: Origin
X-Xss-Protection: 1; mode=block
Content-Security-Policy: block-all-mixed-content
 
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>aplog_prd</Name><Prefix></Prefix><KeyCount>1</KeyCount><MaxKeys>1000</MaxKeys><Delimiter>%2F</Delimiter><IsTruncated>false</IsTruncated><CommonPrefixes><Prefix>snapshots%2F</Prefix></CommonPrefixes><EncodingType>url</EncodingType></ListBucketResult>
 
[REQUEST objectAPIHandlers.GetBucketLocationHandler-fm] [155326869.883605] [2019-03-22 16:31:38 +0100]
GET /aplog_prd/?location=
Host: 127.0.0.1:9000
User-Agent: Minio (linux; amd64) minio-go/v6.0.20 mc/2019-03-20T21:29:03Z

**Comment by kannappanr** [comment]
@erland64 Are you saying that `mc` hangs in `GetBucketLocation` s3API call?

**Comment by erland64** [comment]
Hi. Yes.

Thanks

**Comment by kannappanr** [comment]
@erland64 Can you try calling `GetBucketLocation` command in `aws-cli`?

**Comment by erland64** [comment]
It works.

aws s3api get-bucket-location  --bucket aplog_prd --endpoint-url http://127.0.0.1:9000
{
    "LocationConstraint": null
}

From Log:

[REQUEST objectAPIHandlers.GetBucketLocationHandler-fm] [155349942.441883] [2019-03-25 08:37:04 +0100]
GET /aplog_prd?location
Host: 127.0.0.1:9000
X-Amz-Date: 20190325T073704Z
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Authorization: AWS4-HMAC-SHA256 Credential=aplog_prd/20190325/"ece-region"/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=61725930c3f4023d5c025602515e06357359b8312ffc2552db5e86890dbca08c
Accept-Encoding: identity
User-Agent: aws-cli/1.16.125 Python/3.4.9 Linux/3.10.0-957.1.3.el7.x86_64 botocore/1.12.115

**Comment by kannappanr** [comment]
@erland64 One of the commands that `mc` requires is hanging in the case of `EMC S3 gateway`.

Here is an output when I run `mc ls` against `play`

```
mc: <DEBUG> GET /test/?location= HTTP/1.1
Host: play.minio.io:9000
User-Agent: Minio (linux; amd64) minio-go/v6.0.20 mc/2019-03-25T19:31:23Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20190326/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20190326T202349Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/2.0 200 OK
Connection: close
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 26 Mar 2019 20:23:49 GMT
Server: Minio/DEVELOPMENT.2019-03-25T22-50-53Z
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 158F9BEAED8ADDDB
X-Minio-Deployment-Id: c3725876-4560-4ded-aba3-d360b31e6e12
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  388.839066ms

mc: <DEBUG> HEAD /test/ HTTP/1.1
Host: play.minio.io:9000
User-Agent: Minio (linux; amd64) minio-go/v6.0.20 mc/2019-03-25T19:31:23Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20190326/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190326T202349Z

mc: <DEBUG> HTTP/2.0 200 OK
Connection: close
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Tue, 26 Mar 2019 20:23:49 GMT
Server: Minio/DEVELOPMENT.2019-03-25T22-50-53Z
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 158F9BEAEEA6D2B9
X-Minio-Deployment-Id: c3725876-4560-4ded-aba3-d360b31e6e12
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  16.091667ms

mc: <DEBUG> HEAD /test/ HTTP/1.1
Host: play.minio.io:9000
User-Agent: Minio (linux; amd64) minio-go/v6.0.20 mc/2019-03-25T19:31:23Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20190326/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190326T202349Z

mc: <DEBUG> HTTP/2.0 200 OK
Connection: close
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Tue, 26 Mar 2019 20:23:49 GMT
Server: Minio/DEVELOPMENT.2019-03-25T22-50-53Z
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 158F9BEAEF847BCD
X-Minio-Deployment-Id: c3725876-4560-4ded-aba3-d360b31e6e12
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  19.133082ms

mc: <DEBUG> GET /test/?delimiter=%2F&max-keys=1000&prefix= HTTP/1.1
Host: play.minio.io:9000
User-Agent: Minio (linux; amd64) minio-go/v6.0.20 mc/2019-03-25T19:31:23Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20190326/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190326T202349Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/2.0 200 OK
Connection: close
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 26 Mar 2019 20:23:49 GMT
Server: Minio/DEVELOPMENT.2019-03-25T22-50-53Z
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 158F9BEAF0C51514
X-Minio-Deployment-Id: c3725876-4560-4ded-aba3-d360b31e6e12
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  23.393308ms
```

Are you not seeing any of this when you run `mc` against `EMC S3` gateway. Is the behavior same when you connect `mc` to `EMC S3` directly?

**Comment by erland64** [comment]
Below works

minio/mc --debug ls s3/aplog_prd/
mc: <DEBUG> GET /aplog_prd/?location= HTTP/1.1
Host: 172.17.36.142
User-Agent: Minio (linux; amd64) minio-go/v6.0.20 mc/2019-03-20T21:29:03Z
Authorization: AWS **REDACTED**:**REDACTED**
Date: Wed, 27 Mar 2019 07:19:01 GMT
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 144
Content-Type: application/xml
Date: Wed, 27 Mar 2019 07:19:01 GMT
Server: ViPR/1.0
X-Amz-Id-2: 4c91a172f1b165a18b5a9403656a649220e848f5fe55ceaa949c96a638e92914
X-Amz-Request-Id: 0a13f10d:1688bd99d44:43131:e5

mc: <DEBUG> Response Time:  19.688908ms

mc: <DEBUG> HEAD / HTTP/1.1
Host: aplog_prd.172.17.36.142
User-Agent: Minio (linux; amd64) minio-go/v6.0.20 mc/2019-03-20T21:29:03Z
Authorization: AWS **REDACTED**:**REDACTED**
Date: Wed, 27 Mar 2019 07:19:01 GMT

mc: <DEBUG> HTTP/1.1 403 Forbidden
Content-Type: application/xml
Date: Wed, 27 Mar 2019 07:19:01 GMT
Server: ViPR/1.0
X-Amz-Id-2:
X-Amz-Request-Id: 0a13f10e:1688bdf779d:42ded:4f
Content-Length: 0

mc: <DEBUG> Response Time:  6.413466ms

mc: <DEBUG> GET /?delimiter=%2F&max-keys=1000&prefix= HTTP/1.1
Host: aplog_prd.172.17.36.142
User-Agent: Minio (linux; amd64) minio-go/v6.0.20 mc/2019-03-20T21:29:03Z
Authorization: AWS **REDACTED**:**REDACTED**
Date: Wed, 27 Mar 2019 07:19:01 GMT
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 403 Forbidden
Content-Length: 330
Content-Type: application/xml
Date: Wed, 27 Mar 2019 07:19:01 GMT
Server: ViPR/1.0
X-Amz-Id-2:
X-Amz-Request-Id: 0a13f10e:1688bdf779d:42ded:51

<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your Secret Access Key and signing method. For more information, see REST Authentication and SOAP Authentication for details.</Message><RequestId>0a13f10e:1688bdf779d:42ded:51</RequestId></Error>mc: <DEBUG> Response Time:  11.351388ms

mc: <ERROR> Unable to stat `s3/aplog_prd/`. Access Denied.
 (3) ls-main.go:102 cmd.checkListSyntax(..) Tags: [s3/aplog_prd/]
 (2) client-url.go:184 cmd.url2Stat(..) Tags: [s3/aplog_prd/]
 (1) client-s3.go:1136 cmd.(*s3Client).Stat(..) Tags: [aplog_prd]
 (0) client-s3.go:1678 cmd.(*s3Client).bucketStat(..)
 Release-Tag:RELEASE.2019-03-20T21-29-03Z | Commit:3ea090fe18dd | OS:linux | Arch:amd64 | Lang:go1.11.4 | Mem:2.0MB/72MB | Heap:2.0MB/66MB. minio/mc --debug ls s3
mc: <DEBUG> GET / HTTP/1.1
Host: 172.17.36.142
User-Agent: Minio (linux; amd64) minio-go/v6.0.20 mc/2019-03-20T21:29:03Z
Authorization: AWS **REDACTED**:**REDACTED**
Date: Wed, 27 Mar 2019 07:25:14 GMT
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 427
Content-Type: application/xml
Date: Wed, 27 Mar 2019 07:25:14 GMT
Server: ViPR/1.0
X-Amz-Id-2:
X-Amz-Request-Id: 0a13f10f:1688be490dd:40f04:1c5

mc: <DEBUG> Response Time:  40.934361ms

mc: <DEBUG> GET / HTTP/1.1
Host: 172.17.36.142
User-Agent: Minio (linux; amd64) minio-go/v6.0.20 mc/2019-03-20T21:29:03Z
Authorization: AWS **REDACTED**:**REDACTED**
Date: Wed, 27 Mar 2019 07:25:14 GMT
Accept-Encoding: gzip

Below works:
minio/mc --debug ls s3
mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 427
Content-Type: application/xml
Date: Wed, 27 Mar 2019 07:25:14 GMT
Server: ViPR/1.0
X-Amz-Id-2:
X-Amz-Request-Id: 0a13f10f:1688be490dd:40eef:4df

mc: <DEBUG> Response Time:  52.908376ms

[2018-02-07 09:04:43 CET]     0B aplog_prd/


Below fails
minio/mc --debug ls s3/aplog_prd/
mc: <DEBUG> GET /aplog_prd/?location= HTTP/1.1
Host: 172.17.36.142
User-Agent: Minio (linux; amd64) minio-go/v6.0.20 mc/2019-03-20T21:29:03Z
Authorization: AWS4-HMAC-SHA256 Credential=aplog_prd/20190327/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190327T073543Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 144
Content-Type: application/xml
Date: Wed, 27 Mar 2019 07:35:43 GMT
Server: ViPR/1.0
X-Amz-Id-2: 4c91a172f1b165a18b5a9403656a649220e848f5fe55ceaa949c96a638e92914
X-Amz-Request-Id: 0a13f10d:1688bd99d44:431d0:11

mc: <DEBUG> Response Time:  6.874396ms

mc: <DEBUG> HEAD / HTTP/1.1
Host: aplog_prd.172.17.36.142
User-Agent: Minio (linux; amd64) minio-go/v6.0.20 mc/2019-03-20T21:29:03Z
Authorization: AWS4-HMAC-SHA256 Credential=aplog_prd/20190327/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190327T073543Z

mc: <DEBUG> HTTP/1.1 405 Method Not Allowed
Content-Length: 250
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=iso-8859-1
Date: Wed, 27 Mar 2019 07:35:43 GMT
Date: Wed, 27 Mar 2019 07:35:43 GMT
Server: ViPR/1.0
X-Amz-Id-2:
X-Amz-Request-Id: 0a13f10e:1688bdf779d:42e01:19

mc: <DEBUG> Response Time:  12.603226ms

mc: <DEBUG> GET /?delimiter=%2F&max-keys=1000&prefix= HTTP/1.1
Host: aplog_prd.172.17.36.142
User-Agent: Minio (linux; amd64) minio-go/v6.0.20 mc/2019-03-20T21:29:03Z
Authorization: AWS4-HMAC-SHA256 Credential=aplog_prd/20190327/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190327T073543Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 427
Content-Type: application/xml
Date: Wed, 27 Mar 2019 07:35:43 GMT
Server: ViPR/1.0
X-Amz-Id-2:
X-Amz-Request-Id: 0a13f10e:1688bdf779d:42df9:cf

mc: <DEBUG> Response Time:  36.494213ms

mc: <ERROR> Unable to stat `s3/aplog_prd/`. 405 Method Not Allowed
 (3) ls-main.go:102 cmd.checkListSyntax(..) Tags: [s3/aplog_prd/]
 (2) client-url.go:184 cmd.url2Stat(..) Tags: [s3/aplog_prd/]
 (1) client-s3.go:1136 cmd.(*s3Client).Stat(..) Tags: [aplog_prd]
 (0) client-s3.go:1678 cmd.(*s3Client).bucketStat(..)
 Release-Tag:RELEASE.2019-03-20T21-29-03Z | Commit:3ea090fe18dd | OS:linux | Arch:amd64 | Lang:go1.11.4 | Mem:2.2MB/70MB | Heap:2.2MB/66MB.

Thanks

**Comment by erland64** [comment]
Below works

minio/mc --debug ls s3
mc: <DEBUG> GET / HTTP/1.1
Host: 172.17.36.142
User-Agent: Minio (linux; amd64) minio-go/v6.0.20 mc/2019-03-20T21:29:03Z
Authorization: AWS4-HMAC-SHA256 Credential=aplog_prd/20190327/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190327T074314Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 427
Content-Type: application/xml
Date: Wed, 27 Mar 2019 07:43:14 GMT
Server: ViPR/1.0
X-Amz-Id-2:
X-Amz-Request-Id: 0a13f112:1688bf35d94:408d7:1b3

mc: <DEBUG> Response Time:  46.229649ms

mc: <DEBUG> GET / HTTP/1.1
Host: 172.17.36.142
User-Agent: Minio (linux; amd64) minio-go/v6.0.20 mc/2019-03-20T21:29:03Z
Authorization: AWS4-HMAC-SHA256 Credential=aplog_prd/20190327/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190327T074314Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 427
Content-Type: application/xml
Date: Wed, 27 Mar 2019 07:43:14 GMT
Server: ViPR/1.0
X-Amz-Id-2:
X-Amz-Request-Id: 0a13f112:1688bf35d94:408db:12b

mc: <DEBUG> Response Time:  37.526272ms

[2018-02-07 09:04:43 CET]     0B aplog_prd/

Below does not work
minio/mc --debug ls s3/aplog_prd
mc: <DEBUG> GET /aplog_prd/?location= HTTP/1.1
Host: 172.17.36.142
User-Agent: Minio (linux; amd64) minio-go/v6.0.20 mc/2019-03-20T21:29:03Z
Authorization: AWS4-HMAC-SHA256 Credential=aplog_prd/20190327/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190327T074337Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 144
Content-Type: application/xml
Date: Wed, 27 Mar 2019 07:43:37 GMT
Server: ViPR/1.0
X-Amz-Id-2: 4c91a172f1b165a18b5a9403656a649220e848f5fe55ceaa949c96a638e92914
X-Amz-Request-Id: 0a13f10b:1688bcbe3f7:42e28:77

mc: <DEBUG> Response Time:  17.815361ms

mc: <DEBUG> HEAD / HTTP/1.1
Host: aplog_prd.172.17.36.142
User-Agent: Minio (linux; amd64) minio-go/v6.0.20 mc/2019-03-20T21:29:03Z
Authorization: AWS4-HMAC-SHA256 Credential=aplog_prd/20190327/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190327T074337Z

mc: <DEBUG> HTTP/1.1 405 Method Not Allowed
Content-Length: 250
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=iso-8859-1
Date: Wed, 27 Mar 2019 07:43:37 GMT
Date: Wed, 27 Mar 2019 07:43:37 GMT
Server: ViPR/1.0
X-Amz-Id-2:
X-Amz-Request-Id: 0a13f10c:1688bd2a88b:4300f:453

mc: <DEBUG> Response Time:  15.108693ms

mc: <DEBUG> HEAD / HTTP/1.1
Host: aplog_prd.172.17.36.142
User-Agent: Minio (linux; amd64) minio-go/v6.0.20 mc/2019-03-20T21:29:03Z
Authorization: AWS4-HMAC-SHA256 Credential=aplog_prd/20190327/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190327T074337Z

mc: <DEBUG> HTTP/1.1 405 Method Not Allowed
Content-Length: 250
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=iso-8859-1
Date: Wed, 27 Mar 2019 07:43:37 GMT
Date: Wed, 27 Mar 2019 07:43:37 GMT
Server: ViPR/1.0
X-Amz-Id-2:
X-Amz-Request-Id: 0a13f10c:1688bd2a88b:430ba:7

mc: <DEBUG> Response Time:  44.062426ms

mc: <ERROR> Unable to stat `s3/aplog_prd`. 405 Method Not Allowed
 (3) ls-main.go:102 cmd.checkListSyntax(..) Tags: [s3/aplog_prd]
 (2) client-url.go:184 cmd.url2Stat(..) Tags: [s3/aplog_prd]
 (1) client-s3.go:1136 cmd.(*s3Client).Stat(..) Tags: [aplog_prd]
 (0) client-s3.go:1678 cmd.(*s3Client).bucketStat(..)
 Release-Tag:RELEASE.2019-03-20T21-29-03Z | Commit:3ea090fe18dd | Host:lsp7441a.sebank.se | OS:linux | Arch:amd64 | Lang:go1.11.4 | Mem:2.2MB/70MB | Heap:2.2MB/66MB.

Thanks

**Comment by kannappanr** [comment]
I think you have enabled `dns` style bucket lookup

Can you try something similar to `mc config host add mys3 http://localhost:9000                 <Access_KEY> <Secret_KEY> --api "s3v4"`

Then try listing objects under a bucket

**Comment by erland64** [comment]
Yes, you are correct. Thanks, now it is working.

The reason for my question is that I'm trying implement snapshots in an Elasticsearch cluster but it hangs just like mc does if "lookup" : "dns".

Is it possible in Minio server to set "lookup" : "auto" even if the client tries to use DNS?

Thanks
Erland

**Comment by kannappanr** [comment]
@erland64 I don't think it is possible, as the user might think that `DNS` is working fine. Closing this issue as I feel this has been resolved and this is not a minio issue. Feel free to reach out to us on https://slack.min.io if you have further questions.
