### ISSUE TITLE
minio heal broken after delete both part.1 and xl.json file

### ISSUE THREAD

**Issue by chinglinwen** [minio/minio#7421]
## Expected Behavior

mc admin heal command, should heal the object in the volume ( even if part and xl.json file not exist )

## Current Behavior

heal dones't work ( waited half an hour )

## Steps to Reproduce (for bugs)

```
two node, with 2 volume each

mc mb minios/try1
echo "hello" > try1.txt
mc cp try1.txt minios/try1/try1.txt
rm part.1 xl.json  # node2/volume2

mc admin heal -r minios/try1

// change to use node2 ip directly,  minios is ingress ip

[wen@t s3heal]$ mc admin heal -r minios236/try1
mc: <ERROR> Failed to start heal sequence. Heal is already running on the given path (use force-start option to stop and start afresh). The heal was started by IP 192.168.10.234 at Mon, 25 Mar 2019 09:49:46 GMT, token is 18008093-5570-4e01-96c5-5776c3246e82
mc: <ERROR> Unable to display heal status. Heal is already running on the given path (use force-start option to stop and start afresh). The heal was started by IP 192.168.10.234 at Mon, 25 Mar 2019 09:49:46 GMT, token is f8a21f5c-c878-414b-87f6-ddacac1bc60d
[wen@t s3heal]$

[wen@t s3heal]$ date
Mon Mar 25 17:49:50 CST 2019

// since not working for at least five minutes, I've try stop and start again

mc admin heal -r -s minios236/try1/try1.txt
mc admin heal -r -f minios236/try1/try1.txt  # start again, hang here for half an hour, no error output
```

## Context

I'm trying to testing disk broken, data loss emulate

## Your Environment

* Version used (`minio version`):

Version: 2019-03-06T22:47:10Z
Release-Tag: RELEASE.2019-03-06T22-47-10Z
Commit-ID: b05825ffe825646dc075996d33c583f6cf456837

* Environment name and version (e.g. nginx 1.9.1):
k8s 1.9

* Server type and version:

centos7.3.1611

[root@kube-test-10-236 ~]# docker version 
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:22 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:19:08 2018
  OS/Arch:          linux/amd64
  Experimental:     false
* Operating System and version (`uname -a`):

Linux kube-test-10-236 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by kannappanr** [comment]
@chinglinwen Will repro the issue and see why the command is hanging. Thanks for filing this issue.

**Comment by harshavardhana** [comment]
Most probably this PR #7407 might fix this.

**Comment by kannappanr** [comment]
Yes, I verified that #7407 handles this scenario

**Comment by kannappanr** [comment]
closing this issue as #7407 has been merged

**Comment by chinglinwen** [comment]
it's good to hear that
