### ISSUE TITLE
a way to report object (bad) status

### ISSUE THREAD

**Issue by chinglinwen** [minio/minio#7426]
I need to know if object is in bad state, so I think it should have a command or UI show's?, let's focus command first

we need a cli ( etc ) to report the object status ( similar to scan? )

I have try `mc admin heal`, it can report some info, I think there need some other ways ( not reporting the summary, but every items )

the purpose of reporting status, is : 
  1. check object status
  2. provide data for the fix

we often do fix by using heal command ( despite heal's issue for now )

I'd like to have a two method for the fix: 
1. the first one is heal
1. the second one is by recreating the object

in order to recreating the object, we need to know which object need to fix ( currently we don't know ).

## Expected Behavior

constantly ( or at least, when we do a read operation on a object ), detect it's state, if in bad state report it ( log it, and have the data for the mc admin object state ( kind of )

## Current Behavior

when some data deleted, I see no logs, no command to query objects state.
no way to know if something is broken ( try fix soon when we can still do the read )

## Possible Solution

see above

## Steps to Reproduce (for bugs)

1. delete part file or xl.json ( or modify to corrupt the file )
2. see if there's log instantly ( or do a read, see if there's log about it's bad state )
3. no command to query the detail too

## Context

see above

## Your Environment

* Version used (`minio version`):

Version: 2019-03-06T22:47:10Z
Release-Tag: RELEASE.2019-03-06T22-47-10Z
Commit-ID: b05825ffe825646dc075996d33c583f6cf456837

* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:  centos 7.3.1611
* Operating System and version (`uname -a`): Linux kube-test-10-236 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by nitisht** [comment]
> constantly ( or at least, when we do a read operation on a object ), detect it's state, if in bad state report it ( log it, and have the data for the mc admin object state ( kind of )

We do log server side error if we find an object to be not readable..(quorum not available). If the object is readable we return the data (quorum is available). With millions or even billions of objects I am not sure if tracking each object for its status is a good idea.

**Comment by chinglinwen** [comment]
tracking is one way I think, I'm not expert on this, I think there may be another way that can resolve the issue, I think bad state been unknown is not good ( when error log happen, it's too late to fix? ).

also, heal need someway to detect the state? ( is it done already? ) @nitisht

**Comment by nitisht** [comment]
> also, heal need someway to detect the state? ( is it done already? ) @nitisht

Yes, to check state of each object you can try

```
./mc admin heal <alias> -r --dry-run
```

optionally add `--json` flag to get json output

**Comment by chinglinwen** [comment]
It does report summary info ( though it's not working for now ),  but it's not reporting the detail items of object state  @nitisht 

```
[wen@t k8stest ~]$ mc admin heal -n -f -r --json --scan deep minios/try1
{
 "status": "error",
 "error": {
  "message": "Failed to start heal sequence.",
  "cause": {
   "message": "Post http://minio-cluster.tt.haodai.net/minio/admin/v1/heal/try1?forceStart=true: dial tcp: lookup minio-cluster.tt.haodai.net on 180.76.76.76:53: no such host",
   "error": {
    "Op": "Post",
    "URL": "http://minio-cluster.tt.haodai.net/minio/admin/v1/heal/try1?forceStart=true",
    "Err": {
     "Op": "dial",
     "Net": "tcp",
     "Source": null,
     "Addr": null,
     "Err": {
      "Err": "no such host",
      "Name": "minio-cluster.tt.haodai.net",
      "Server": "180.76.76.76:53",
      "IsTimeout": false,
      "IsTemporary": false
     }
    }
   }
  },
  "type": "error",
  "sysinfo": {
   "host.arch": "amd64",
   "host.cpus": "8",
   "host.lang": "go1.12",
   "host.name": "t",
   "host.os": "linux",
   "mem.heap.total": "66MB",
   "mem.heap.used": "1.8MB",
   "mem.total": "70MB",
   "mem.used": "1.8MB"
  }
 }
}
{
 "status": "error",
 "error": {
  "message": "Unable to display heal status.",
  "cause": {
   "message": "Post http://minio-cluster.tt.haodai.net/minio/admin/v1/heal/try1?forceStart=true: dial tcp: lookup minio-cluster.tt.haodai.net on 180.76.76.76:53: server misbehaving",
   "error": {
    "Op": "Post",
    "URL": "http://minio-cluster.tt.haodai.net/minio/admin/v1/heal/try1?forceStart=true",
    "Err": {
     "Op": "dial",
     "Net": "tcp",
     "Source": null,
     "Addr": null,
     "Err": {
      "Err": "server misbehaving",
      "Name": "minio-cluster.tt.haodai.net",
      "Server": "180.76.76.76:53",
      "IsTimeout": false,
      "IsTemporary": true
     }
    }
   }
  },
  "type": "error",
  "sysinfo": {
   "host.arch": "amd64",
   "host.cpus": "8",
   "host.lang": "go1.12",
   "host.name": "t",
   "host.os": "linux",
   "mem.heap.total": "66MB",
   "mem.heap.used": "1.8MB",
   "mem.total": "70MB",
   "mem.used": "1.8MB"
  }
 }
}
[wen@t k8stest ~]$

[wen@t k8stest ~]$ mc cat minios/try1/try1.txt
mc: <ERROR> Unable to read from `minios/try1/try1.txt`. unexpected EOF.
[wen@t k8stest ~]$

[wen@t k8stest ~]$ mc ls minios/
[2019-03-18 18:38:23 CST]     0B hd-test/
[2019-03-13 15:38:44 CST]     0B hello/
[2019-03-19 18:11:06 CST]     0B loadgen/
[2019-03-26 14:11:02 CST]     0B test/
[2019-03-25 17:47:33 CST]     0B try1/
[wen@t k8stest ~]$ mc ls minios/test
[2019-03-25 17:15:22 CST]     6B a.txt
[2019-03-25 17:19:32 CST]  63KiB hello.png
[2019-03-26 14:11:02 CST]    64B test.py
[2019-03-25 15:22:30 CST] 200KiB test.txt
[2019-03-12 16:10:18 CST]    12B testObj
[wen@t k8stest ~]$
```

**Comment by nitisht** [comment]
> it's not working for now 

Do you have a proxy in between mc and minio server?

**Comment by kannappanr** [comment]
@chinglinwen Here is what I see for an item that is missing `xl.json` and `part.1` file

```
{
 "status": "success",
 "type": "object",
 "name": "test/issue",
 "before": {
  "color": "yellow",
  "offline": 0,
  "online": 3,
  "missing": 1,
  "corrupted": 0,
  "drives": [
   {
    "uuid": "",
    "endpoint": "/tmp/1",
    "state": "missing"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9002/tmp/2",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9003/tmp/3",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9004/tmp/4",
    "state": "ok"
   }
  ]
 },
 "after": {
  "color": "yellow",
  "offline": 0,
  "online": 3,
  "missing": 1,
  "corrupted": 0,
  "drives": [
   {
    "uuid": "",
    "endpoint": "/tmp/1",
    "state": "missing"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9002/tmp/2",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9003/tmp/3",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9004/tmp/4",
    "state": "ok"
   }
  ]
 },
 "size": 20
}
```
Here it doesn't tell you if `xl.json` or `part.1` or both are missing, but it does tell you that you have a problem with that disk.

**Comment by harshavardhana** [comment]
We will be moving to auto heal model soon, you won't need to know the status of the object in this manner using a tool.

With auto heal at any given point in time you can know what is currently being healed and what are currently healthy objects.

**Comment by chinglinwen** [comment]
auto heal feature is great.

> With auto heal at any given point in time you can know what is currently being healed and what are currently healthy objects.

this sounds good.

**Comment by nitisht** [comment]
Closing this as we already have an issue to track auto heal feature progress @chinglinwen 

pls refer: https://github.com/minio/minio/issues/6782

**Comment by chinglinwen** [comment]
since auto heal feature may provide the function of report bad object status, let's consider it duplicate, I'll check this later ( when auto heal landed )
