### ISSUE TITLE
I want double gateway backend ,could minio  do it?

### ISSUE THREAD

**Issue by gyb997** [minio/minio#7432]
I want to use minio as a proxy of storage.The backend is a OSS  and a S3 backend.
Can I use minio do it?
When I store a file ,just like a.jpg. The OSS storage a file ,also the S3 store It.

**Comment by kannappanr** [comment]
@gyb997 Unable to understand your question. Are you saying that you want to have two copies of an object. One on S3 and another on OSS?

If yes, You can either run `mc cp` to both `oss` and `s3`. `oss` will be via gateway.

Else, you can `mc cp` to either `oss vis gateway` or `s3` and do `mc mirror` to the other. Minio doesn't do double backend.

**Comment by nitisht** [comment]
Closing this as there is no action required .

**Comment by gyb997** [comment]
Ok @kannappanr  ,I know what you said.I don't want use mc cp or mirror cmd. I just want a online reverse proxy . Which I can select use nginx+lua do it. For me I just want to know if minio can .

Or maybe in the next release can handle it.
The detail is I can use minio store file on two storage backend . And I can make a config to define which bachend is the primary backend.(if file storaged in the primary，the storage operation can success)
