### ISSUE TITLE
Use binary on centos 7, error when start

### ISSUE THREAD

**Issue by huangll99** [minio/minio#7438]
Endpoint:  http://10.3.10.131:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://192.168.122.1:9000  http://127.0.0.1:9000      
AccessKey: YAWV7NRM5VTJUDK5MB42 
SecretKey: cZP1Ren2foGm3tU4VFYK36hR3+bRlDIER0DuHoXT 

Browser Access:
   http://10.3.10.131:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://192.168.122.1:9000  http://127.0.0.1:9000      

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://10.3.10.131:9000 YAWV7NRM5VTJUDK5MB42 cZP1Ren2foGm3tU4VFYK36hR3+bRlDIER0DuHoXT

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xffffffffff67f830 pc=0xffffffffff67f830]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0xffffffffff67f830
stack: frame={sp:0x7ffebeb79560, fp:0x7ffebeb79590} stack=[0x7ffebeb69dc8,0x7ffebeb79d60)

**Comment by harshavardhana** [comment]
Can you provide more details like 

- kernel version
- MinIO version
- selinux enabled or disabled
- provide an strace -f output for the minio binary
