### ISSUE TITLE
minio is not handling double-double quotes in CompleteMultiPartUpload ETag

### ISSUE THREAD

**Issue by androda** [minio/minio#7441]
I am testing the Vertica S3 Export feature against minio. Unfortunately the export fails with Vertica giving me an error.

## Expected Behavior
* Running an S3 Export from Vertica should succeed against minio

## Current Behavior
* Running an S3 Export from Vertica fails, with minio returning a 500 internal error in response to Vertica's last call to minio

## Possible Solution
It looks like S3 will simply remove as many double-quotes as it finds in ETags, but minio may only be removing a single set.  Vertica is sending the ETag with two sets of double-quotes.

## Steps to Reproduce (for bugs)
1. Start a multipart upload
2. Upload a single part
3. Complete the multipart upload and send the ETag wrapped in two sets of double-quotes, like so:  `<ETag>""ETag value""</ETag>`

## Context
* Here is an example POST request which caused the minio error (some parts censored):

POST /bucket/path/7f018980-5ff7-47c4-a687-7b33cad6da22/a44e9279-2625-4fd8-b69e-24903bab2932/export.ab1a6cea.csv?uploadId=324b64dc-49f5-4329-ba9c-00e8d9a0c6c7 HTTP/1.1
Host: s3.amazonaws.com
Accept: */*
Authorization: AWS4-HMAC-SHA256 Credential=CREDS/20190328/us-east-1/s3/aws4_request,SignedHeaders=content-type;date;host;x-amz-content-sha256,Signature=SIGNATURE
Content-Type: text/xml
Date: 20190328T221206Z
x-amz-content-sha256: SHA256
Content-Length: 177

`<?xml version="1.0" encoding="UTF-8"?><CompleteMultipartUpload><Part><PartNumber>1</PartNumber><ETag>""e357af0ed6e5dddcdb5a7ad36954f090""</ETag></Part></CompleteMultipartUpload>`

* This is the response body from minio:
`<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Key>path/7f018980-5ff7-47c4-a687-7b33cad6da22/a44e9279-2625-4fd8-b69e-24903bab2932/export.ab1a6cea.csv</Key><BucketName>bucket</BucketName><Resource>/bucket/path/7f018980-5ff7-47c4-a687-7b33cad6da22/a44e9279-2625-4fd8-b69e-24903bab2932/export.ab1a6cea.csv</Resource><RequestId>15903EFCA1F951C8</RequestId><HostId>a4a4209d-91aa-4f3e-87b4-b41fbcb4ae13</HostId></Error>`

* This is the error log (from minio log) which appeared at the time of the error response (relevant part bolded):
2019-03-28T16:48:09.463279972Z time="2019-03-28T16:48:09Z"
level=error msg="Unable to complete multipart upload."
**cause="encoding/hex: invalid byte: U+0022 '"'"**
source="[object-handlers.go:952:objectAPIHandlers.CompleteMultipartUploadHandler()]"
stack="object-api-utils.go:185:getCompleteMultipartMD5 fs-v1-multipart.go:714:fsObjects.CompleteMultipartUpload <autogenerated>:387:(*fsObjects).CompleteMultipartUpload object-handlers.go:950:objectAPIHandlers.CompleteMultipartUploadHandler api-router.go:50:(objectAPIHandlers).CompleteMultipartUploadHandler-fm" 

## Regression
Not a regression

## Your Environment
* Version used: Minio RELEASE.2019-03-27T22-35-21Z

**Comment by westse** [comment]
Looks like this could be addressed  by refactoring [this code](https://github.com/minio/minio/blob/8689ec258b220615b2167b7f6f6d26ed8f100d42/cmd/object-handlers-common.go#L232-L235) to the following
```
var etagRegex = regexp.MustCompile("\"*([^\"]+)\"*")

// canonicalizeETag returns ETag with leading and trailing double-quotes removed,
// if any present
func canonicalizeETag(etag string) string {
	return etagRegex.ReplaceAllString(etag, "$1")
}

```
