### ISSUE TITLE
error in saving object There were headers present in the request which were not signed (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID

### ISSUE THREAD

**Issue by Chandra4Aws** [minio/minio#7443]
My observations on this issue.
Environment: Api gateway -> Lambda function (Java) -> S3.
There are 2 observations

When there is a space in the Custom metadata key, it doesn't create it.
Eg: "Account Number" -> Not creating
"Account-Number" -> It creates

When there is a : (Colon) in the key, it throws "There were headers present in the request which were not signed (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID:XXXXX".

First issue doesn't happen in console, but second issue consistent. S3 can throw a better exception rather not signed.

Thanks

**Comment by kannappanr** [comment]
@Chandra4Aws Can you please follow the template? Can you be more specific about your use case?

`Environment: Api gateway -> Lambda function (Java) -> S3.`
is it 
`Environment: Amazon Api gateway -> AWS Lambda function (Java) -> S3.` ?
Also, what java sdk are you using ? is it `minio-java`?
I am assuming you are using `minio`, when you specify `S3`

Can you provide a sample code for us to reproduce the issue?

**Comment by nitisht** [comment]
closing this for now @Chandra4Aws . Feel free to reopen when you have the requested info

**Comment by Chandra4Aws** [comment]
Sorry for the delay.
Java version: 1.8
Amazon API Gateway, -> AWS Lamda Function (Java jar upload) -> S3.

Code:

private boolean parseInputStream(InputStream inputStream) {
		System.out.println("parseInputStream :: Start");
		BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));
		int letter;
		boolean status = true;
		StringBuffer requestParam = new StringBuffer();
		JSONParser parser = new JSONParser();
		byte[] fileArr = null;
		Map<String, String> userMetadata = new HashMap<String, String>();
		try {
			System.out.println("converting into stringBuffer");
			while ((letter = reader.read()) != -1) {
				requestParam.append(Character.toChars(letter));
			}

			
			final ObjectMapper mapper2 = new ObjectMapper();
			JsonNode json = mapper2.readTree(requestParam.toString());
			String metaData = json.path("headers").path("metaData").asText();
			System.out.println("metaData :: "+ metaData);
			try {
				userMetadata = getUserMetaData(metaData);
				if (userMetadata.size() > 0) {
					JSONObject jsonObj = (JSONObject) parser.parse(requestParam.toString());
					fileArr = Base64.decode((String) jsonObj.get("body"));
					System.out.println("file size :: " + fileArr.length);
				} else {
					status = false;
				}
			} catch (Exception e) {
				System.out.println("Error in saving Object :: " + e.getMessage());
				e.printStackTrace();
			}

			if (!saveObject(fileArr, userMetadata)) {
				status = false;
			}
			System.out.println("parseInputStream :: End");
		} catch (Exception e) {
			e.printStackTrace();
			status = false;
		}
		return status;
	}

	private boolean saveObject(byte[] fileArr, Map<String, String> userMetadata) {
		System.out.println("saveObject :: Start");
		ByteArrayInputStream stream = null;
		try {
			stream = new ByteArrayInputStream(fileArr);
			AwsS3Client client = new AwsS3Client();
			AmazonS3 c = client.getS3Client();
			ObjectMetadata metaData = new ObjectMetadata();
			metaData.setContentType("application/pdf");
			metaData.setUserMetadata(userMetadata);
			metaData.setContentLength(fileArr.length);
			c.putObject("chandra1504bucket", userMetadata.get("docName").toString(), stream, metaData);
			System.out.println("saveObject :: End");
		} catch (Exception e) {
			System.out.println("error in saving object " + e.getMessage());
			e.printStackTrace();
			return false;
		}
		return true;

	}

	private Map<String, String> getUserMetaData(String input) {
		Map<String, String> userMetaData = new HashMap<String, String>();
		
		  try { ObjectMapper mapper = new ObjectMapper(); DocumentMetaData data =
		  mapper.readValue(input, DocumentMetaData.class);
		  
		  if(!saveMetadaObject(data)) { return userMetaData; }
		  
		  userMetaData.put("docName", data.getDocName()); for(Object key:
		  data.getChallangeQuestionAnswers().getList()) { Map<String, String>
		  questionMap = (Map<String, String>) key; for(String q : questionMap.keySet())
		  { userMetaData.put("q-"+q , questionMap.get(q)); } } for(Object key:
		  data.getPaymentInformation().getList()) { Map<String, String> informationMap
		  = (Map<String, String>) key; for(String q : informationMap.keySet()) {
		  userMetaData.put("m-"+q , informationMap.get(q)); } } }catch (Exception e) {
		  System.out.println("Error in parsing meta data :: "+ e.getMessage());
		  System.out.println(e.getMessage()); }
		 
		return userMetaData;
	}

Payload used: 

{
	"docName": "billingSummary.pdf",
	"challangeQuestionAnswers": {
		"list": [{
				"Account-Number": "12345",
				"Street-Name": "My Main Street",
				"Zip-Code": "28210"
			}
		]
	},
	"paymentInformation": {
		"list": [{
				"account number": "2211976542",
				"invDate : ": "12th March 2019",
				"invAmount : ": "5329.90",
				"minAmount : ": "2890.55"
			}
		]
	}
}
