### ISSUE TITLE
[New Feature] Support log rotation for HTTP traces

### ISSUE THREAD

**Issue by aeltawela** [minio/minio#7447]
If HTTP traces is enabled, log file becomes huge that it is very difficult to open or copy. Log rotation would solve this problem. This also can be applied for any file-based logs in Minio.

**Comment by harshavardhana** [comment]
We are moving to a different model, by deprecating the env and moving to `mc admin trace` command only behavior.

**Comment by aeltawela** [comment]
Do you have details on how it is going to work? mc fetches the traces from certain APIs?  what if the client lost the connection, will it lose the traces? is it possible to have multiple clients fetching the same traces?

**Comment by harshavardhana** [comment]
You can follow the changes here https://github.com/minio/minio/pull/7128 @ahmedabt - yes the changes will be lost if the `mc admin trace` loses the connection. 

But you are only interested in tracing only when you are debugging an application behavior, HTTP trace is not a replacement for HTTP logging/audit etc. 

For that we have `MINIO_AUDIT_LOGGER_HTTP_ENDPOINT`

**Comment by kannappanr** [comment]
@ahmedabt Closing this issue as you can follow the changes in #7128.
