### ISSUE TITLE
Impossible to emulate GCS: Check your Google secret key and signing method.

### ISSUE THREAD

**Issue by symonsoft** [minio/minio#7448]
Unable to initialize GCS service with example provided by the documentation
https://docs.minio.io/docs/minio-client-quickstart-guide.html

    $ mc config host add gcs https://storage.googleapis.com BKIKJAA5BMMU2RHO6IBB V8f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12
    mc: <ERROR> Unable to initialize new config from the provided credentials. The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.

    $ minio version
    Version: 2019-03-27T22:35:21Z
    Release-Tag: RELEASE.2019-03-27T22-35-21Z
    Commit-ID: 6df05e489dc789cf26e82810cf5cfeefb1d90761

    $ mc version
    Version: 2019-03-28T20:43:56Z
    Release-tag: RELEASE.2019-03-28T20-43-56Z
    Commit-id: 7f2770e68f1fa398c2964b3b2655b85823f12868

**Comment by nitisht** [comment]
can you add `--api S3v2` i.e. 

```
mc config host add gcs https://storage.googleapis.com <access-key> <secret-key> --api S3v2
```

**Comment by symonsoft** [comment]
@nitisht Thanks, it works!
I think the documentation should be updated.

**Comment by harshavardhana** [comment]
@symonsoft it's already written 

> mc config host add gcs  https://storage.googleapis.com BKIKJAA5BMMU2RHO6IBB V8f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12

> NOTE: Google Cloud Storage only supports Legacy Signature Version 2, so you have to pick - S3v2

Also GCS started supporting S3v4 already not sure why its not working for you

**Comment by symonsoft** [comment]
Although I successfully ran the command I still can't login with given credentials:
![image](https://user-images.githubusercontent.com/12235978/55279120-bc0fc400-5336-11e9-8b96-8d0bab12026a.png)
