### ISSUE TITLE
Accessing custom “X-AMZ-META-xx” metadata from pure frontend application

### ISSUE THREAD

**Issue by asb14690** [minio/minio#7451]
In an application built using ReactJs and Minio Javascript SDK, I want to access objects and its metadata (both custom and default) from the bucket stored in the cloud server. I am able to fetch both default as well as custom meta data of the object from the bucket stored in AWS S3 but I failed to access custom metadata of the object stored in minio server bucket.

Note: My application is pure frontend application. Therefore, I’m not using any backend server like Nodejs, Golang to access the API with SDK. 

## Expected Behavior
When I use SDK method “statObject”, I expect in it's response to return default and custom metadata of objects stored in the self hosted Minio Server/cloud storage.

## Current Behavior
In AWS S3: When I add custom metadata X-AMZ-META-TEST to the object, and expose the same in the bucket CORS configuration with exposedHeader tag. I get both the custom X-AMZ-META-TEST information along with default metadata in SDK API response. As expected.

In Minio Server : When I call SDK method statObject to fetch custom metadata of object stored in minio server, then it returns the default “X-AMZ-META” metadata only. I am unable to fetch custom metadata which I had added to the object.

## Possible Solution
Ability to expose header on the minio server to avoid CORS issue and to access custom X-AMZ-META
## Context
Using Amazon S3 I could configure this with the CORSConfiguration

**Comment by nitisht** [comment]
Thanks for reporting @asb14690 we'll take a look

**Comment by kanagarajkm** [comment]
@asb14690 can you give the sample code used for putObject and statObject?

**Comment by kanagarajkm** [comment]
I tried with folllowing code, i see the custom metadata shown on statObject and getObject.

React component
```javascript
import React, { Component } from "react";
import logo from "./logo.svg";
import "./App.css";
import { Client } from "./minio-browser";

const minioClient = new Client({
  endPoint: "localhost",
  useSSL: false,
  port: 9000,
  accessKey: "minio",
  secretKey: "minio123"
});

class App extends Component {
  componentDidMount() {
    minioClient.statObject("testbucket", "sample1.jpg", function(err, stat) {
      if (err) {
        return console.log(err);
      }
      console.log(stat);
    });
    var size = 0;
    minioClient.getObject("testbucket", "sample1.jpg", function(err, dataStream) {
      if (err) {
        return console.log(err);
      }
      dataStream.on("data", function(chunk) {
        size += chunk.length;
      });
      dataStream.on("end", function() {
        console.log("End. Total size = " + size);
      });
      dataStream.on("error", function(err) {
        console.log(err);
      });
    });
  }
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
        </header>
      </div>
    );
  }
}

export default App;
```
Stat output:
```javascript
{
  etag: "83340520d28b704ca4f4b019effb33dc"
  lastModified: Mon Apr 01 2019 22:36:38 GMT+0530 (India Standard Time) {}
  metaData: {content-type: "image/jpg", example: "5678", h1: "1234", h2: "3456"}
  size: 120253
}
```

Response headers for getObject
```
Accept-Ranges: bytes
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: *
Content-Length: 120253
Content-Security-Policy: block-all-mixed-content
Content-Type: image/jpg
Date: Wed, 03 Apr 2019 05:31:31 GMT
Etag: "83340520d28b704ca4f4b019effb33dc"
Last-Modified: Mon, 01 Apr 2019 17:06:38 GMT
Server: Minio/RELEASE.2019-03-27T22-35-21Z
Vary: Origin
X-Amz-Meta-Example: 5678
X-Amz-Meta-H1: 1234
X-Amz-Meta-H2: 3456
X-Amz-Request-Id: 1591DFDE0697DDC7
X-Minio-Deployment-Id: d54a26b6-33d5-4d9a-8255-065727daf95a
X-Xss-Protection: 1; mode=block
```

Following code is used upload an object with metadata
```javascript
var Minio = require("minio");

const minioClient = new Minio.Client({
  endPoint: "localhost",
  useSSL: false,
  port: 9000,
  accessKey: "minio",
  secretKey: "minio123"
});

var metaData = {
  "Content-Type": "image/jpg",
  "X-Amz-Meta-h1": 1234,
  "X-Amz-Meta-h2": 3456,
  example: 5678
};

 minioClient.fPutObject(
   "testbucket",
   "sample1.jpg",
   "/home/kanagaraj/tmp/sample1.jpg",
   metaData,
   function(err, etag) {
     if (err) return console.log(err);
     console.log("File uploaded successfully.");
   }
 );
```

**Comment by asb14690** [comment]
@kanagarajkm Thanks for the quick response. I have called the statObject method in the same way as you have done in your code above. However, after spending some time with the code, I realized that code is working fine with demo Minio instance hosted at https://play.minio.io:9000. But It's not working with my Minio server instance.

Since I am able to fetch all metadata(both custom and default) from the demo Minio server running at https://play.minio.io:9000 using the same code. Therefore I think there is some permission issue with my Minio server instance.

It will be a great help if you can suggest command/permission which I can enable in my Minio server instance to access all metadata.

Thanks in advance.

**Comment by kanagarajkm** [comment]
@asb14690 can you run `mc stat` and see if the headers are present?
For example, `mc stat local/testbucket/sample1.jpg`

It returned the following result for me
```
Name      : sample1.jpg
Date      : 2019-04-01 22:36:38 IST 
Size      : 117 KiB 
ETag      : 83340520d28b704ca4f4b019effb33dc 
Type      : file 
Metadata  :
  X-Amz-Meta-Example   : 5678 
  X-Amz-Meta-H1        : 1234 
  X-Amz-Meta-H2        : 3456 
  X-Minio-Deployment-Id: d54a26b6-33d5-4d9a-8255-065727daf95a 
  Content-Type         : image/jpg 
```

**Comment by asb14690** [comment]
Thanks @kanagarajkm for your support. I just updated the minio server to the latest version and now I am able to fetch all the metadata in the browser.
