### ISSUE TITLE
env variable MINIO_LOGGER_HTTP_ENDPOINT does not change configuration

### ISSUE THREAD

**Issue by thomaslange24** [minio/minio#7466]
I am starting a standalone minio server with the following commands, inserting the corresponding hostname for the http endpoint env variable:

export MINIO_ACCESS_KEY=admin
export MINIO_SECRET_KEY=password
export MINIO_LOGGER_HTTP_ENDPOINT=http://hostname:8080/minio/logs
./minio server /archive/minio_storage

I would like to enable the http target logging. But when i try to access the endpoint it is not possible. Looking into the server configuration file, you can get with:
mc admin config get myminio > my-serverconfig
I see that the option for http target logging is not set according to the environment variable and still shows the default configuration:

"logger": {
		"console": {
			"enabled": true
		},
		"http": {
			"target1": {
				"enabled": false,
				"endpoint": "https://username:password@example.com/api"
			}
		}
	}

What am i doing wrong? I expect the http target to be enabled and the endpoint to be set to the one i specified with the corresponding environment variable and the log to be accessible through the url http://hostname:8080/minio/logs.

**Comment by kannappanr** [comment]
@thomaslange24 setting `MINIO_LOGGER_HTTP_ENDPOINT` does not modify the config file. Can you run a webhook say at `http://localhost:9000` and then set it's URL as `MINIO_LOGGER_HTTP_ENDPOINT`'s value

**Comment by thomaslange24** [comment]
I have never worked with webhooks. What do i have to do exactly?

**Comment by kanagarajkm** [comment]
@thomaslange24 Mino server will send the logs to the configured endpoint as HTTP POST request. So you need to have a web server running which can accept POST requests from minio server. Let's say you have it running on port 9999, then `MINIO_LOGGER_HTTP_ENDPOINT` would be `http://localhost:9999/`.

**Comment by thomaslange24** [comment]
Thats fine. I understand it much better now. But does that mean i can provide any logger http endpoint? The endpoint and port do not have to match the ones for minio server?

**Comment by kanagarajkm** [comment]
yes, it can be any http endpoint.

**Comment by thomaslange24** [comment]
Thanks. That was all i wanted to know.

**Comment by thomaslange24** [comment]
Although, one more thing. I am starting the server as systemd service on CentOS and would like to view any Logs from Minio in Kibana. How would i do that the best way?

**Comment by kanagarajkm** [comment]
I assume you already have an elastic backend for kibana. This post explains the steps to configure logstash to receive http messages https://www.elastic.co/blog/introducing-logstash-input-http-plugin. Once its configured you need to set MINIO_LOGGER_HTTP_ENDPOINT to logstash url.

**Comment by thomaslange24** [comment]
Thanks

**Comment by thomaslange24** [comment]
What does a log entry from minio look like in json format? WHich fields does it have? It is hard to make minio log some error.

**Comment by kannappanr** [comment]
Here is the template
```
{
 "deploymentid": <Deployment_ID, optional in the case of Gateway>,
 "level": "ERROR",
 "time": "<Time in UTC format>",
 "api": {
 "name": "<API_NAME>",
 "args": {
  "bucket": "<Bucket_name, optional>",
  "object": "<Object_name, optional>"
  }
 },
 "remotehost": "<Client Host/IP>",
 "requestID": "<x-amz-request-id returned to the client as part of response>",
 "userAgent": "<User_Agent header sent by the client>",
 "error": {
 "message": "<Error message>",
 "source": [
   <Stack Trace>
 ],
 "variables": {
   "Key1": "Value",
   "Key2": "Value",
   .....
  }
 }
}
```

Here is the sample output

```

{
  "deploymentid": "3ae9ef41-ce1b-435a-abc9-4b441a4914bd",
  "level": "ERROR",
  "time": "2019-03-21T22:14:31.475878214Z",
  "api": {
    "name": "PutObject",
    "args": {
         "bucket": "test",
         "object": "issue"
     }
  },
 "remotehost": "127.0.0.1",
 "requestID": "158E190E7B258FDB",
 "userAgent": "Minio (linux; amd64) minio-go/v6.0.20 mc/2019-03-15T20:48:52Z",
 "error": {
    "message": "read tcp 172.16.1.105:9000->172.16.1.103:44678: read: connection reset by peer",
    "source": [
             "cmd/object-handlers.go:1073:cmd.objectAPIHandlers.PutObjectHandler()",
             "cmd/api-router.go:79:cmd.objectAPIHandlers.PutObjectHandler-fm()",
             "net/http/server.go:1964:http.HandlerFunc.ServeHTTP()"
    ],
    "variables": {
       "peerAddress": "127.0.0.1:9000"
     }
  }
}
```

The documentation at https://github.com/minio/minio/tree/master/docs/logging should have this information. Will try to add it here.

**Comment by kannappanr** [comment]
@thomaslange24 Closing this issue as answered. Please feel free to reach out to us if you have further questions.
