### ISSUE TITLE
Minio container is showing the status unhealthy 

### ISSUE THREAD

**Issue by snandy-git** [minio/minio#7482]
Minio container is sometimes not working and we are restarting the container and it becomes ok. I checked that the status of minio container is always unhealthy .

## Current Behavior
 Minio container is showing the status unhealthy. When I am running "docker restart <container_id>", then it is again ok. But after sometimes it again becomes unhealthy.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`): 2019-02-26T19:51:46Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):Linux innolx4055 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

Screenshot :- 

94a8608d0fc8        minio/minio                "/usr/bin/docker-ent…"   5 weeks ago         Up 5 weeks (unhealthy)    0.0.0.0:9003->9000/tcp                       minio4
48a95e55e1ba        minio/minio                "/usr/bin/docker-ent…"   5 weeks ago         Up 5 weeks (unhealthy)    0.0.0.0:9002->9000/tcp                       minio3
f0f521b4a66d        minio/minio                "/usr/bin/docker-ent…"   5 weeks ago         Up 5 weeks (unhealthy)    0.0.0.0:9001->9000/tcp                       minio1
94a9e5f30e97        minio/minio                "/usr/bin/docker-ent…"   5 weeks ago         Up 24 hours (unhealthy)   0.0.0.0:9000->9000/tcp                       minio2

**Comment by nitisht** [comment]
We made some relevant fixes in new releases @snandy-git can you update to latest release and try again?

**Comment by snandy-git** [comment]
Can you tell me the latest release name ?

**Comment by nitisht** [comment]
`RELEASE.2019-03-27T22-35-21Z `

**Comment by snandy-git** [comment]
Thanks. Now I will use the docker compose to install minio cluster . But I have already installed it before with the previous release. So, should I remove the previous containers or it will automatically merge or update with those containers ?

**Comment by nitisht** [comment]
you can try a docker compose down, update the yaml with latest image tags and then again docker compose up..

I am assuming you have persistent volume mounts to ensure data is not lost when container are recreated.

**Comment by kannappanr** [comment]
ping @snandy-git Can you please try the suggestion and get back to us?

**Comment by kannappanr** [comment]
@snandy-git Closing this issue as answered. Please feel free to reopen if you still face issues.
