### ISSUE TITLE
Failed to retrieve object error in distributed mode

### ISSUE THREAD

**Issue by prasus** [minio/minio#7484]
## Expected Behavior

File download using s3 client/mc should work if the file exits in the minio cluster.

## Current Behavior

I have got a six node distributed setup on k8s, what I observed is that my cluster sometimes seems to have problems when downloading larger files (`> 20Mb`) using s3 client, I get `Failed to retrieve object at xxxxxxx` error, but the file does exist and surprisingly it works fine and downloads the file correctly if I retry the program. 

I also tried to manually download the file using the below command:

`mc cp miniopoc/rawdata/xe_os_events_status,com.moon,20190403.csv.gz .`

This command also failed with the below error for the first time and it worked fine from the second attempt onwards.

`mc: <ERROR> Unable to validate source miniopoc/rawdata/xe_os_events_status,com.moon,20190403.csv.gz`

Is this a known behaviour? 

## Environment

Version: 2019-03-13T21:05:06Z
Env: Kubernetes
Replicas: 8
Deployed on Kubernetes using official helm chart.

**Comment by nitisht** [comment]
@prasus please follow the issue template, we need info like Minio version you're using, your setup details like memory available on each container, etc..

**Comment by prasus** [comment]
@nitisht done. thank you.

**Comment by nitisht** [comment]
Thanks @prasus . This is not expected or known. Are you trying these operations in parallel? How are you uploading the files? What is the backend storage being used here, I mean the PV type?

**Comment by prasus** [comment]
Thanks for your response @nitisht, No we are not trying the operation in parallel. The read is performed after the files are uploaded to the cluster.

We use self hosted kubernetes (bare-metal) and local storage, The PV's are created from underlying SSD disks.

Let me know if you need any other details, Thanks!

**Comment by kannappanr** [comment]
@prasus Can you try `mc cp --debug miniopoc/rawdata/xe_os_events_status,com.moon,20190403.csv.gz . ` This might have more information when you encounter a failure.

**Comment by kannappanr** [comment]
ping @prasus Can you please provide the requested output and any errors on the server console, better yet, if you can start the server that you are hitting from the client with `MINIO_HTTP_TRACE` set?

**Comment by kannappanr** [comment]
Closing this as stale. Will re-open when we have the requested information.
