### ISSUE TITLE
How to install minio from source ?

### ISSUE THREAD

**Issue by eorsavik** [minio/minio#7485]
How to build and install Minio from source ?
In the url it says to execute the following command :
"go get -u github.com/minio/minio" 

Does the above command only download the source?  What are the steps to build the Minio?

**Comment by nitisht** [comment]
you can check the document here https://github.com/minio/minio/blob/master/CONTRIBUTING.md

closing this for now, feel free to join us on Slack [https://slack.min.io] for more such questions.
