### ISSUE TITLE
User secretKey in plain text in the identity.json file

### ISSUE THREAD

**Issue by vermaden** [minio/minio#7488]
Hi,

The **secretKey** is kept in _plain text_ in the **identity.json** file on Minio.

Example below. The Minio version is 2019-02-06.

```
[root@srv15 ~]# cat /ftp/.minio.sys/config/iam/users/myuser/identity.json
{"secretKey":"password","status":"enabled"}
[root@srv15 ~]#
```

I would like to convert that _plain text_ password to some hash that will not be readable as plain text and Minio will still work.

Example solution.

```
[root@srv15 ~]# cat /ftp/.minio.sys/config/iam/users/myuser/identity.json
{"secretKey":"$5$2039ujdis3984yrfshi8yhrfsw8r3yw9yrhsoiehfd8s3ryosr$","status":"enabled"}
[root@srv15 ~]#
```

Is it possible?

Thanks,
vermaden

**Comment by harshavardhana** [comment]
It is currently intentionally kept this way @vermaden 

You should enable server side encryption which we already provide to encrypt these objects.

**Comment by aead** [comment]
Hi @vermaden this is on purpose and it is actually not possible to store just a 'hash' value (like the output of argon2). The reason for this is how AWS S3 authentication works. It's not like you sending the access key / secret key to the server as part of a request but you actually compute a HMAC over certain request headers using the secret key as HMAC key. If we would store just PBKDF hash of the secret key we would not be able to verify the HMAC hash of the request and could not check whether a request is authenticated or not.

S3 authentication does not work like regular password-based authentication. However, as @harshavardhana pointed out already you can enable server-side encryption (see e.g. https://github.com/minio/minio/blob/master/docs/kms/README.md) to encrypt the identity.json file.

**Comment by aead** [comment]
Closing this since this is not possible - please reopen if you've still concerns

**Comment by vermaden** [comment]
Thank you very much for working alternative - encryption - that will do :)

Regards,
vermaden
