### ISSUE TITLE
Unable to upload using the UI, UI shows 100% uploaded, but the file is not actually uploaded

### ISSUE THREAD

**Issue by Raghu-Farmagain** [minio/minio#7489]
Unable to upload files to any bucket using UI, this is a recent issue earlier we were able to upload. The progress bar says 100% but the file is not getting uploaded

**Comment by nitisht** [comment]
@Raghu-Farmagain please use the issue template to provide details. It is really difficult to identify the problem otherwise. Closing this for now, feel free to reopen once you have all the info as per the template
