### ISSUE TITLE
access denied by intermitance

### ISSUE THREAD

**Issue by marcadella** [minio/minio#7490]
## Expected Behavior

Here is my set-up:
I deployed Minio with docker (sha beginning with "ea5c51d826ad") in an environment using OAuth2. Since Minio does not support OAuth2, I use the following work around:
- the authorization service has the admin credentials of Minio and is free to create as many users as it wishes (for now I used read-write policy only) via mc.
- when a component needs to access data on Minio (either upload or download), it first asks authorization service a new credential (the authorization service uses mc to create a new random access key / access secret) and returns them to the component that requested them.
- the component is free to use those credentials (using the java API this time) for 1 hour after which the authorization service removes automatically the user from Minio (still using mc).

## Current Behavior
What happens is that it works fine in most cases, but sometimes I get:
"io.minio.errors.ErrorResponseException: The access key ID you provided does not exist in our records."
and this while the user is still present in Minio (I check both with `mc admin user list` and by logging in with the GUI using the credentials returned by the auth service). In addition, I added a loop in my code to retry upon failrue in case it was some timing issue (like you create the user on Minio but somehow it is not ready yet), but the loop would just keeping failing all the time while I could connect on to the GUI.

Note: with this method I potentially create a dozen of users simultaneously (or very close in time) using mc. Is that an issue?
Is there a better way to integrate Minio in an OAuth environment?

## Steps to Reproduce (for bugs)
I can provide the Auth service image if needed.

## Your Environment
Minio image ea5c51d826ad

**Comment by harshavardhana** [comment]
Which version of MinIO are you running? And also a sample script to reproduce this?

**Comment by harshavardhana** [comment]
> Which version of MinIO are you running? And also a sample script to reproduce this?

Can you provide more information?

**Comment by harshavardhana** [comment]
Closing this as stale issue @marcadella - please respond back with more details.

**Comment by marcadella** [comment]
I'm using the image ea5c51d826ad.
I did the following experiment: I add a user (using mc) and immediately start a loop to download a file which will loop (with 10s interval) until no exception is thrown (i.e. the download succeeds). In most cases the loop is executed once (as expected). In other cases it loops for two minutes until Minio stops complaining that the user does not exist.
If you want to test by yourself you can clone [https://gitlab.com/uit-sfb/newpan-tools](this project) and follow the read me, but it might be much quicker for you to just startup image ea5c51d826ad and create a loop that create a user with read-write rights via mc then attempt to download or upload a file using this user's credentials (using the Java API). The loop should be run several times per seconds. At some point you should see that Minio starts saying that your user does not exist even though `mc admin user list` returns this user as part of the list.
Hope that helps.

**Comment by harshavardhana** [comment]
Okay will do thanks for the reproducer..

**Comment by harshavardhana** [comment]
Can this be reproduced with MinIO master ? @marcadella

**Comment by marcadella** [comment]
Hi, I tested today with master and I still get the same issue.

**Comment by harshavardhana** [comment]
@marcadella is there no simple reproducer? using an entire java project?

**Comment by harshavardhana** [comment]
@marcadella can this be tested again with master?

**Comment by marcadella** [comment]
Given that it is a bit inconvenient to test and that we modified the way we interact with Minio, we are no longer experiencing this issue.
