### ISSUE TITLE
Access-Control-Expose-Headers must not be a wildcard (*)

### ISSUE THREAD

**Issue by bagr001** [minio/minio#7492]
PR #7331 fixes the issue, but not completely. According to the comment  https://github.com/minio/minio/issues/7289#issuecomment-471321861 the wildcard breaks the functionality in Firefox. The bug is tracked here: [https://bugzilla.mozilla.org/show_bug.cgi?id=1309358](https://bugzilla.mozilla.org/show_bug.cgi?id=1309358)

## Expected Behavior
Access-Control-Expose-Headers response header contains list of all exposed headers instead of wildcard (*)
## Current Behavior
Access-Control-Expose-Headers response header contains wildcard (*)

## Steps to Reproduce (for bugs)
eg. try to a Blob PUT to a presigned URL in Firefox and try to access ETag header.

## Regression
Original Isuue: #7289
PR: #7331
Version: [RELEASE.2019-04-04T18-31-46Z](https://github.com/minio/minio/releases/tag/RELEASE.2019-04-04T18-31-46Z)

**Comment by kannappanr** [comment]
@bagr001 Thanks for filing this issue. We will talk internally and get back to you on how this can be done.

**Comment by ramondeklein** [comment]
Is there a Minio version that I can downgrade to safely? We have this issue now on our production services and all Firefox users are experiencing this issue...

**Comment by bagr001** [comment]
@ramondeklein [RELEASE.2019-01-31T00-31-19Z](https://github.com/minio/minio/releases/tag/RELEASE.2019-01-31T00-31-19Z) and older should be fine.

**Comment by ramondeklein** [comment]
@bagr001 Is it always safe to downgrade Minio, because it also has some meta-information and it's not quite clear when I can safely downgrade. Would be great to have page on compatible versions somewhere...

I have created another workaround. We use NGINX as a reverse proxy, so I added the following lines to the location block:

```
location / {
    # ...all other configuration removed...
    proxy_hide_header       Access-Control-Expose-Headers;
    add_header              Access-Control-Expose-Headers ETag;
}
```

This adds the proper header without the need to downgrade.

**Comment by adamhooper** [comment]
A suggestion: How about just changing `Access-Control-Expose-Header` from `*` to `ETag`? From where I'm sitting, #7331 didn't solve #7289 in the first place....

Replacing `*` with `ETag` may cause a _new_ regression for some people; but surely that's an awfully tiny number of people. `*` is better if users want to read headers other than ETag on Chrome specifically (which is fringe if not entirely useless); `ETag` is better if users want to perform multipart upload on all browsers (which is common).
