### ISSUE TITLE
Post (not put) to upload to public bucket

### ISSUE THREAD

**Issue by Hermain** [minio/minio#7495]
## Expected Behavior
I am trying to upload to a bucket with public or upload policy using a Post.

Is it possible to upload a file (lets say with curl) to a public bucket using the post method and no authentication?

I would like to be able to post for an upload without authentication: e.g: 

curl -v  http://localhost:9000/ -F bucket=test -F file=@myfile

## Current Behavior
```* Connected to localhost (127.0.0.1) port 9000 (#0)
> POST / HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 8926527
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------80a7e203929c608b
> 
* Done waiting for 100-continue
< HTTP/1.1 405 Method Not Allowed
< Content-Security-Policy: block-all-mixed-content
< Vary: Origin
< X-Amz-Request-Id: 159375707AF83F64
< X-Minio-Deployment-Id: a80acf8e-d883-41ea-9039-7b3730403025
< X-Xss-Protection: 1; mode=block
< Date: Mon, 08 Apr 2019 09:23:43 GMT
< Content-Length: 0
< Connection: close
< 
* we are done reading and this is set to close, stop send
* Closing connection 0
```

I would expect the file to upload with this or a similar curl post instead of giving bad request or Method not allowed.

## Possible Solution
Allow for post upload for buckets with public upload policy without authentication.
Tell me how to properly upload to a bucket with upload policy using post.

## Steps to Reproduce (for bugs)
1. Create a bucket
2. mc policy update bucket
3. Try uploading using the curl with post (as described above or in any other way using a post)

## Context
All the unauthenticated examples I found use PUT, but the library with which I want to upload currently only supports POST. This is because it was implemented with authentication in mind (where a Post is necessary).

## Your Environment

* RELEASE.2019-04-04T18-31-46Z
* Ubuntu 16.04

**Comment by nitisht** [comment]
@Hermain please use the issue template. It helps us understand the context, also please provide a sample code snippet to help us recreate the problem you're facing.

**Comment by Hermain** [comment]
I updated it. Is it possible at all to do what I want or is a put the only way to upload without authentication?

**Comment by Praveenrajmani** [comment]
@Hermain , You can construct a pre-signed post URL. Please refer - [https://docs.min.io/docs/golang-client-api-reference.html#PresignedPostPolicy](https://docs.min.io/docs/golang-client-api-reference.html#PresignedPostPolicy)

The steps are

- Create a bucket
- Set the bucket policy with `mc policy`
- Create a presigned post url
- Curl the url

**Comment by kannappanr** [comment]
@Hermain I don't think it is possible. I tried this with AWS S3 and here is the result

```
> POST / HTTP/1.1
> Host: s3.amazonaws.com
> User-Agent: curl/7.64.0
> Accept: */*
> Content-Length: 324
> Content-Type: multipart/form-data; boundary=------------------------3bffe529f91e2dd1
> 
< HTTP/1.1 405 Method Not Allowed
< x-amz-request-id: B5D7590934DD30AC
< x-amz-id-2: P+ipPIn/nfyBrdZjSh5hkOHD46Tx/8LkNUSU7Bq/Lgrm3jY9laXhXC7z/FwUZxCtFqEGftlx94c=
< Allow: GET
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Date: Mon, 08 Apr 2019 17:00:59 GMT
< Connection: close
< Server: AmazonS3
< 
<?xml version="1.0" encoding="UTF-8"?>
* Closing connection 0
<Error><Code>MethodNotAllowed</Code><Message>The specified method is not allowed against this resource.</Message><Method>POST</Method><ResourceType>SERVICE</ResourceType><RequestId>B5D7590934DD30AC</RequestId></Error>
```

**Comment by Hermain** [comment]
@Praveenrajmani unfortunately that presigned url only works with authentication as far as I can tell. I couldn't get it to work by removing the signature and other x-amz parts.
Though I didn't use the go client instead the mc client but the curl comand they spit out should be the same right=?

**Comment by kannappanr** [comment]
@Hermain The link has been updated. With pre-signed URL, the application will only have access to the URL. Yes, to generate the URL, you need to have credentials.

**Comment by kannappanr** [comment]
@Hermain If you are ok with using `PUT`, then ```curl -X PUT -T /etc/issue https://play.min.io:9000/public/issue```  will work. Here `public` is a `public` bucket that I created on `play`

But I see that you do not want to use `PUT`. Then your option probably is to use pre-signed url like explained by @Praveenrajmani

**Comment by kannappanr** [comment]
@Hermain Closing this issue as working as intended. Please feel free to reach out to us if you have more questions.

**Comment by Hermain** [comment]
The whole point is to not use put. I wanted to know if and how its possible to upload a file without authentication using post. kannappanr says he doesn't think its possible so I guess it isnt.

**Comment by harshavardhana** [comment]
It is not possible without authentication using POST @Hermain

**Comment by Hermain** [comment]
Thank you for clearing that up
