### ISSUE TITLE
Listing not working properly when using gateway & SSE

### ISSUE THREAD

**Issue by schlitte** [minio/minio#7496]
The "ls" command is very slow when used for listing bucket/directory content. For large directories, the list of files corrupt. It does not show all files and all the files it lists are all listed twice. Both the slowness and the fact that the results are not reliable cause a problem for us.

## Expected Behavior
Complete list of files is returned within a few seconds

## Current Behavior
- "ls" on a directory that contains nothing but 25 subdirectories takes 25 seconds. It returns the correct list of subdirectories.
- "ls" on a dirctory that contains 18.000 files and 3 subdirectories  take 4m9s and returns 2000 lines. 

These 2000 lines look like this:

- File 1-997 (of 18.000)
- File 1-997 (of 18.000)
- Directory 1-3 (of 3)
- Directory 1-3 (of 3)

- Using ls to list a specific file is working as expected. The correct result is returned in less than a second.

## Steps to Reproduce (for bugs)
Use Minio in gateway mode and enable SSE. 

## Context
The setup with SSE on Gateway nodes allows us to store confidential data on the Minio server nodes while running them on devices that are managed by a service provider on OS-level and thus are not fully trusted.

## Regression
not tested

Environment:
- Minio Gateway --> (4) Minio Server
- HTTP between Gateway and Server
- mc on same machine as Gateway
- Gateway access via HTTP
- MINIO_SSE_AUTO_ENCRYPTION=on on Gateway

* Version used (`minio version`): 2019-03-20T22:38:47Z
* Operating System and version (`uname -a`): 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
This is fixed in #7491

**Comment by kannappanr** [comment]
Closing this as fixed by #7491
