### ISSUE TITLE
Invalid bucket name labels being created

### ISSUE THREAD

**Issue by thaney071** [minio/minio#7499]
I am finding that buckets like `apple-.one` are being created when they are invalid names. This causes issues when an object is stored in the said bucket because the object cannot be deleted due to an invalid bucket name.

## Expected Behavior
Buckets with labels separated by dot (.) should not begin or end with hyphens (-)
`one-.two` or `one.-two` is invalid.

basically, labels in a bucket name must begin and end with a letter or number. 

## Current Behavior
Bucket names with labels beginning or ending with hyphens are created.
![minio-bucket-error](https://user-images.githubusercontent.com/9327064/55759381-0c111980-5a0e-11e9-899e-612c08cdd002.png)
![minio-bucket-error-2](https://user-images.githubusercontent.com/9327064/55759382-0ca9b000-5a0e-11e9-807a-0c6ed871cc75.png)

## Steps to Reproduce (for bugs)
1. pull down the latest minio docker image and run
2. Open the web page and log in
3. Create a bucket with the name `one-.two`
4. Add an object to the new bucket
5. Try to delete the object
6 Get error about invalid bucket name

## Context
This prevents me from trusting that the makebucket api call for the golang client will return an error when invalid bucket names are given. Therefore addtional error checking needs to be implemented before creating buckets and mainted to keep up with bucket name restrictions.

## Regression
 Not sure.

## Your Environment
* mino docker container using tag `RELEASE.2019-04-04T18-31-46Z`
* container run in Windows 10 Enterprise
* ![docker-info](https://user-images.githubusercontent.com/9327064/55759623-af622e80-5a0e-11e9-874a-842950f927fc.png)

**Comment by kannappanr** [comment]
@thaney071 We will look into this issue. I think we should not be creating the bucket in the first place as described in AWS https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html

**Comment by nitisht** [comment]
fixed by https://github.com/minio/minio-go/pull/1097
