### ISSUE TITLE
worm config of minio server should be turned on by the mc command

### ISSUE THREAD

**Issue by JiandongLu** [minio/minio#7502]
## Current Behavior
if the worm of a cluster has been turned on,
we could turn off worm **only by** setting the environtment variable  MINIO_OFF=off
it is very hard to use for users of minio

## Possible Solution
1) the worm should be turned off by the command
mc admin config set minio_name < ./minio.conf

2)  worm  should be turned on/off specific bucket but currently on the whole cluster

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by kannappanr** [comment]
Please take a look at https://docs.min.io/docs/minio-server-configuration-guide.html

**Comment by harshavardhana** [comment]
Environment variables if set override the config, just remove the env and you should be able to use `mc admin config get/set`

**Comment by vadmeste** [comment]
Just wanted to say this has a bad user experience, when one user turns on WORM flag via mc config in a production environment, it won't be able to revert it back.

Also I know that if WORM is enabled, users should not be able to disable it, I am not sure what is the correct trade off here

Probably we can have a warning message in the config help message that will come later.

**Comment by harshavardhana** [comment]
> Just wanted to say this has a bad user experience, when one user turns on WORM flag via mc config in a production environment, it won't be able to revert it back.

WORM is special, it's like saying if I turn off encryption - all my objects should be decrypted. We shouldn't do that so should be WORM.

**Comment by kannappanr** [comment]
@JiandongLu Closing this issue as working as intended. Please feel free to reach out to us if you have further questions.

**Comment by JiandongLu** [comment]
wo have modified the second solution as:
"worm should be turned on/off specific some bucket(s) but currently on the whole cluster"
