### ISSUE TITLE
Allow encryption at REST without TLS

### ISSUE THREAD

**Issue by Brunni** [minio/minio#7504]
When running Minio behind a reverse proxy which takes care about TLS, I want to be able to use encryption at rest although TLS is not activated for minio itself.

## Expected Behavior
Allow encryption at REST for certain hosts (e.g localhost connections only).

## Current Behavior
As described in https://github.com/minio/cookbook/blob/master/docs/how-to-use-minio-server-side-encryption-with-aws-cli.md encryption at rest is not possible with HTTP.

## Possible Solution
Add some configuration key or parameter, which allows to run minio with encryption at rest on HTTP. Probably with some parameter stating from which hosts connections are accepted (e.g. localhost only)

**Comment by harshavardhana** [comment]
You can do that with SSE-S3 auto encryption feature https://docs.min.io/docs/minio-kms-quickstart-guide.html

**Comment by harshavardhana** [comment]
Closing this as working as intended.
