### ISSUE TITLE
HTTP POST multipart/form-data; issue with Signature v4

### ISSUE THREAD

**Issue by flado** [minio/minio#7508]
HTTP POST multipart/form-data; issue with Signature v4

## Expected Behavior

Would expect AWS S3 presignedPOstPolicy v4 to work with Minio 
 

## Current Behavior

Trying to HTTP POST a presigned Post request build with `aws-s3` client for nodejs:

`s3 = new AWS.S3({   
    accessKeyId: 'B20Y9KYKNTNWKL3P084H',
    secretAccessKey: 'abx8qijUUW5oWdNB+k6FXMA0ujxZoRnDhre+yurj',
    endpoint: 'http://127.0.0.1:9000',
    s3ForcePathStyle: true, 
    signatureVersion: 'v4'
  });`

Using `s3.createPresignedPost` method to retrieve the fields to be included in a HTTP POST 

When trying to HTTP POST the ` multipart/form-data;` I always get back: 

`HTTP/1.1 400 Bad Request
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Thu, 11 Apr 2019 00:50:10 GMT
Server: Minio/RELEASE.2019-04-04T18-31-46Z
Transfer-Encoding: chunked
Vary: Origin
X-Amz-Request-Id: 1594452837CC0A58
X-Minio-Deployment-Id: e6de9ffe-7ea3-4541-b512-966764070d31
X-Xss-Protection: 1; mode=block`

`<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MalformedPOSTRequest</Code><Message>The body of your POST request is not well-formed multipart/form-data.</Message><BucketName>7160444b44ce0950b011f1ed7a3859e0</BucketName><Resource>/7160444b44ce0950b011f1ed7a3859e0</Resource><RequestId>1594452837CC0A58</RequestId><HostId>e6de9ffe-7ea3-4541-b512-966764070d31</HostId></Error>`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Minio Logs:

`[REQUEST objectAPIHandlers.PostPolicyBucketHandler-fm] [155494367.937540] [2019-04-11 10:47:59 +1000]
POST /7160444b44ce0950b011f1ed7a3859e0
Host: 127.0.0.1:9000
User-Agent: HTTPie/1.0.2
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 2227
Content-Type: multipart/form-data; boundary=c22dc312892d5469ea8819aaf09ed287

<BODY>

[RESPONSE] [155494367.937540] [2019-04-11 10:47:59 +1000]
400 Bad Request
Vary: Origin
X-Xss-Protection: 1; mode=block
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 15944509B6E6C518
X-Minio-Deployment-Id: e6de9ffe-7ea3-4541-b512-966764070d31
Server: Minio/RELEASE.2019-04-04T18-31-46Z
Accept-Ranges: bytes
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MalformedPOSTRequest</Code><Message>The body of your POST request is not well-formed multipart/form-data.</Message><BucketName>7160444b44ce0950b011f1ed7a3859e0</BucketName><Resource>/7160444b44ce0950b011f1ed7a3859e0</Resource><RequestId>15944509B6E6C518</RequestId><HostId>e6de9ffe-7ea3-4541-b512-966764070d31</HostId></Error>`

## Your Environment

* Version used (`minio version`):

Version: 2019-04-04T18:31:46Z
Release-Tag: RELEASE.2019-04-04T18-31-46Z
Commit-ID: 0146a9d592194c2141851565ba7bb8bf90351b8b

* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
arwin MPXLT093 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
macOS mojave 10.14.3
* Link to your project:

**Comment by flado** [comment]
Using: "aws-sdk": "^2.372.0",

  s3 = new AWS.S3({
    accessKeyId: 'B20Y9KYKNTNWKL3P084H',
    secretAccessKey: 'abx8qijUUW5oWdNB+k6FXMA0ujxZoRnDhre+yurj',
    endpoint: 'http://127.0.0.1:9000',
    s3ForcePathStyle: true, // needed with minio?
    signatureVersion: 'v4'
  });

var params = {
      Bucket: `${resource.id}.${resource.accountAlias}`,
      Expires: 1800, // 30 minutes
      Conditions: [
        {"acl": "private"},
        ['starts-with', '$Content-Type', `audio/`],
        ['content-length-range', 10, 10485760] //allows a file size from ~0 to 10 MiB:
      ],
      Fields: {
        success_action_status: 201,
        // All values passed in as fields will be signed as exact match conditions.
        key: `${resource.templateId}/${resource.resourceId}`
      }
    };
    platform.s3.createPresignedPost(params, function(err, data) { ... }) => use data's fields to issue an HTTP POST multipart as in example below (https://httpie.org - as cmd line client): 


`http -f POST 127.0.0.1:9000/7160444b44ce0950b011f1ed7a3859e0.wellawareness X-Amz-Signature='9bbe0e20d0f7e51e357f0b35d0fc5b0c3d727c05e3a0e767f3dd7490880960a1'  bucket='7160444b44ce0950b011f1ed7a3859e0.wellawareness' key='12345/Uulv22PIB' X-Amz-Algorithm='AWS4-HMAC-SHA256' X-Amz-Credential='B20Y9KYKNTNWKL3P084H/20190410/ap-southeast-2/s3/aws4_request' X-Amz-Date='20190410T044942Z' Policy='eyJleHBpcmF0aW9uIjoiMjAxOS0wNC0xMFQwNTozOToxMFoiLCJjb25kaXRpb25zIjpbeyJhY2wiOiJwcml2YXRlIn0sWyJzdGFydHMtd2l0aCIsIiRDb250ZW50LVR5cGUiLCJhdWRpby8iXSxbImNvbnRlbnQtbGVuZ3RoLXJhbmdlIiwxMCwxMDQ4NTc2MF0seyJzdWNjZXNzX2FjdGlvbl9zdGF0dXMiOjIwMX0seyJrZXkiOiIxMjM0NS8wdSRTRVp3Y3QifSx7ImJ1Y2tldCI6IjcxNjA0NDRiNDRjZTA5NTBiMDExZjFlZDdhMzg1OWUwLndlbGxhd2FyZW5lc3MifSx7IlgtQW16LUFsZ29yaXRobSI6IkFXUzQtSE1BQy1TSEEyNTYifSx7IlgtQW16LUNyZWRlbnRpYWwiOiJCMjBZOUtZS05UTldLTDNQMDg0SC8yMDE5MDQxMC9hcC1zb3V0aGVhc3QtMi9zMy9hd3M0X3JlcXVlc3QifSx7IlgtQW16LURhdGUiOiIyMDE5MDQxMFQwNTA5MTBaIn1dfQ==' file@audio2.mp3`


Mionio LOGS:

[REQUEST objectAPIHandlers.PostPolicyBucketHandler-fm] [155494873.191125] [2019-04-11 12:12:11 +1000]
POST /7160444b44ce0950b011f1ed7a3859e0.wellawareness
Host: 127.0.0.1:9000
User-Agent: HTTPie/1.0.2
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 2949772
Content-Type: multipart/form-data; boundary=0f6a3f636d3b238fa6a9dc627c77a3e9

<BODY>

[RESPONSE] [155494873.191125] [2019-04-11 12:12:11 +1000]
400 Bad Request
X-Amz-Request-Id: 159449A2198113F8
X-Minio-Deployment-Id: e6de9ffe-7ea3-4541-b512-966764070d31
X-Amz-Bucket-Region: ap-southeast-2
Content-Security-Policy: block-all-mixed-content
X-Xss-Protection: 1; mode=block
Server: Minio/RELEASE.2019-04-04T18-31-46Z
Accept-Ranges: bytes
Content-Type: application/xml
Vary: Origin

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MalformedPOSTRequest</Code><Message>The body of your POST request is not well-formed multipart/form-data.</Message><BucketName>7160444b44ce0950b011f1ed7a3859e0.wellawareness</BucketName><Resource>/7160444b44ce0950b011f1ed7a3859e0.wellawareness</Resource><RequestId>159449A2198113F8</RequestId><HostId>e6de9ffe-7ea3-4541-b512-966764070d31</HostId></Error>


- Same ERROR when POSt-ing from a FORM in the browser as described @ https://aws.amazon.com/articles/browser-uploads-to-s3-using-html-post-forms/

**Comment by flado** [comment]
**A partial number of fields in the multipart request returns an expected response regarding the signature not matching as below:** 

 
$ http -v -f POST 127.0.0.1:9000/7160444b44ce0950b011f1ed7a3859e0 X-Amz-Signature="9bbe0e20d0f7e51e357f0b35d0fc5b0c3d727c05e3a0e767f3dd7490880960a1"  X-Amz-Credential="B20Y9KYKNTNWKL3P084H/20190410/ap-southeast-2/s3/aws4_request" file@audio2.mp3
POST /7160444b44ce0950b011f1ed7a3859e0 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 2948670
Content-Type: multipart/form-data; boundary=c613f54b426cd8ef068d5611174b735f
Host: 127.0.0.1:9000
User-Agent: HTTPie/1.0.2



+-----------------------------------------+
| NOTE: binary data not shown in terminal |
+-----------------------------------------+

HTTP/1.1 403 Forbidden
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Thu, 11 Apr 2019 02:27:26 GMT
Server: Minio/RELEASE.2019-04-04T18-31-46Z
Transfer-Encoding: chunked
Vary: Origin
X-Amz-Bucket-Region: ap-southeast-2
X-Amz-Request-Id: 15944A76F9A13DD0
X-Minio-Deployment-Id: e6de9ffe-7ea3-4541-b512-966764070d31
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><BucketName>7160444b44ce0950b011f1ed7a3859e0</BucketName><Resource>/7160444b44ce0950b011f1ed7a3859e0</Resource><RequestId>15944A76F9A13DD0</RequestId><HostId>e6de9ffe-7ea3-4541-b512-966764070d31</HostId></Error>

**Comment by flado** [comment]
Just found a clue in the String value of some fields ...if `Policy` field contains the `==` sequence in the end of the value, the POST request it's failing with `MalformedPOSTRequestThe body of your POST request is not well-formed multipart/form-data` ....btw: the postfix `==` for Policy is generated by `s3.createPresignedPost`

**Comment by Cuneytt** [comment]
Is there any workaround for 
`MalformedPOSTRequestThe body of your POST request is not well-formed multipart/form-data
`
Policy field generated by `s3.createPresignedPost` call always has the suffix `==`

**Comment by harshavardhana** [comment]
Your MinIO server version looks older, have you tried with latest release binary ?
