### ISSUE TITLE
option to change secretkey

### ISSUE THREAD

**Issue by jebinjeb** [minio/minio#7509]
Hi,

We are using latest stable mino but as part of security requirement we have to change/rotate secretkey periodically. But i con't able to find and document for this.

[root@kubernetes-1 ~]# helm list minio
NAME            REVISION        UPDATED                         STATUS          CHART           APP VERSION                     NAMESPACE
neo-minio       1               Thu Apr 11 09:00:21 2019        DEPLOYED        minio-2.4.3     RELEASE.2019-02-12T21-58-47Z    neo

Tried with mc but didn't helped.
[root@kubernetes-1 ~]# export MC_HOST_jebin=http://ACCESS_KEY:MINIO_salainen_avain@192.168.5.38:9000
[root@kubernetes-1 ~]# ./mc admin credential jebin ACCESS_KEY MINIO_salainen_avain1
mc: <ERROR> Unable to set new credential to 'jebin'. The specified method is not allowed against this resource.

Also change the secretkey in the secrets and restarted the single pod, that also didn't helped.

[root@kubernetes-1 ~]# kubectl logs neo-minio-0 -nneo
Waiting for a minimum of 2 disks to come online (elapsed 0s)

Waiting for a minimum of 2 disks to come online (elapsed 1s)

Waiting for a minimum of 2 disks to come online (elapsed 2s)

Waiting for a minimum of 2 disks to come online (elapsed 5s)

Waiting for a minimum of 2 disks to come online (elapsed 16s)

Unable to connect to http://neo-minio-1.neo-minio.neo.svc.cluster.local:9000/export:

Unable to connect to http://neo-minio-2.neo-minio.neo.svc.cluster.local:9000/export:

Unable to connect to http://neo-minio-3.neo-minio.neo.svc.cluster.local:9000/export:

Waiting for a minimum of 2 disks to come online (elapsed 38s)

## Context
security 

## Your Environment
minio-2.4.3
kubernetes-1.13.3

**Comment by harshavardhana** [comment]
ENVs are the only way to reset it @jebinjeb - secret keys are used to internode communication so cannot be changed using `mc admin` commands.

**Comment by jebinjeb** [comment]
Hi @harshavardhana ,

After changing ENV will it take automatically without restarting the pod ?

**Comment by harshavardhana** [comment]
> After changing ENV will it take automatically without restarting the pod ?

It won't that's what I explained 

>  internode communication requires access/secret keys

You cannot change them without restarting the pod.

**Comment by jebinjeb** [comment]
is any way to avoid downtime ? because one by one pod restart didn't help

**Comment by harshavardhana** [comment]
> is any way to avoid downtime ? because one by one pod restart didn't help

It's not possible @jebinjeb - same access/secret keys are used by clients to connect to the server.  They will fail anyways to connect.

**Comment by nitisht** [comment]
Closing this as based on the discussion looks like there is no action from our side. @jebinjeb feel free to reopen / reach out on Slack (https://slack.min.io) if there are further questions.
