### ISSUE TITLE
"read-only file system" Distributed mode

### ISSUE THREAD

**Issue by chernykhse** [minio/minio#7510]
<! ---

Hello.
We have a distributed minio cluster
from 7 nodes on 2 disks. On virtual machines in vmware ESX.

Found degradation of reading and writing to the cluster.
There are a lot of 3 types of logs in journalctl. see below (log samples)

On the nodes there was a high reading load over 1000 iops
And on the disks of two nodes, write operations were completely missing.

tried to manually create a folder in "/mnt/minio/data1/.minio.sys/tmp/", it was created without problems.

At the same time "mc admin info" give out "All servers online, Disks : 14, 0"

All nodes with errors, was restarted
On Node-ap232 nodes Node-ap233 (those nodes on which write operations stopped) dmesg write:
```
[7.033565] EXT4-fs warning (device sdb): ext4_clear_journal_err: 4670: Filesystem error recorded from previous mount: IO failure
[7.033567] EXT4-fs warning (device sdb): ext4_clear_journal_err: 4671: Marking fs in need of filesystem check.
[7.034821] EXT4-fs (sdb): warning:
[7.035255] EXT4-fs (sdb): recovery complete
```
### what do the logs mean (did not find the description in the documentation)
 what went wrong?
 how to avoid it in the future?
[Journal-samples.txt](https://github.com/minio/minio/files/3068075/Journal-samples.txt)

log samples:
```
Apr 10 07:14:27 Node-ap237 minio [552]: Time: 07:14:27 MSK 10/04/2019
Apr 10 07:14:27 Node-ap237 minio [552]: RequestID: 159401A13088860A
Apr 10 07:14:27 Node-ap237 minio [552]: RemoteHost: 172.21.14.215
Apr 10 07:14:27 Node-ap237 minio [552]: UserAgent: Minio (linux; amd64) minio-go / v6.0.17 mc / 2019-02-13T19: 48: 27Z
Apr 10 07:14:27 Node-ap237 minio [552]: Error: mkdir /mnt/minio/data1/.minio.sys/tmp/a25733ab-3794-48ee-95af-98bd4bf9cdec: read-only file system
Apr 10 07:14:27 Node-ap237 minio [552]: 1: cmd / xl-v1-metadata.go: 429: cmd.writeXLMetadata ()
Apr 10 07:14:27 Node-ap237 minio [552]: 2: cmd / xl-v1-object.go: 537: cmd.xlObjects.renameCorruptedObject ()
Apr 10 07:14:27 Node-ap237 minio [552]: 3: cmd / xl-v1-object.go: 555: cmd.xlObjects.getObjectInfo ()
Apr 10 07:14:27 Node-ap237 minio [552]: 4: cmd / xl-sets.go: 778: cmd. (* XlSets) .ListObjects ()
Apr 10 07:14:27 Node-ap237 minio [552]: 5: cmd / bucket-handlers-listobjects.go: 177: cmd. (ObjectLayer) .ListObjects-fm ()
Apr 10 07:14:27 Node-ap237 minio [552]: 6: cmd / bucket-handlers-listobjects.go: 184: cmd.objectAPIHandlers.ListObjectsV1Handler ()
Apr 10 07:14:34 Node-ap237 minio [552]: API: ListObjectsV1 (bucket = temp)
```
```
Apr 09 10:47:54 Node-ap234 minio [554]: Time: 10:47:54 MSK 04/09/2019
Apr 09 10:47:54 Node-ap234 minio [554]: RequestID: 1593BECADAEDCD2C
Apr 09 10:47:54 Node-ap234 minio [554]: RemoteHost: 172.21.14.213
Apr 09 10:47:54 Node-ap234 minio [554]: UserAgent: Minio (linux; amd64) minio-go / v6.0.20 mc / 2019-03-20T21: 29: 03Z
Apr 09 10:47:54 Node-ap234 minio [554]: Error: The requested range "bytes 0-47174 / 47174" is not satisfiable.
Apr 09 10:47:54 Node-ap234 minio [554]: 1: cmd / api-errors.go: 1785: cmd.toAPIErrorCode ()
Apr 09 10:47:54 Node-ap234 minio [554]: 2: cmd / object-handlers.go: 439: cmd.objectAPIHandlers.GetObjectHandler ()
Apr 09 10:47:54 Node-ap234 minio [554]: 3: cmd / api-router.go: 68: cmd. (ObjectAPIHandlers) .GetObjectHandler-fm ()
Apr 09 10:47:54 Node-ap234 minio [554]: 4: net / http / server.go: 1947: http.HandlerFunc.ServeHTTP ()
Apr 09 10:47:55 Node-ap234 minio [554]: API: GetObject (bucket = temp, object = 2019-04-04 / f8a738e0-a952-413b-995d-aea5d1d8e963.CORRUPTED)
```
```
Apr 09 14:06:49 Node-ap231 minio [538]: Time: 14:06:49 MSK 04/09/2019
Apr 09 14:06:49 Node-ap231 minio [538]: RequestID: 1593C9A59049F819
Apr 09 14:06:49 Node-ap231 minio [538]: RemoteHost: 172.21.8.114
Apr 09 14:06:49 Node-ap231 minio [538]: UserAgent: Minio (Microsoft Windows NT 6.2.9200.0; x86_64) minio-dotnet / 1.0.9
Apr 09 14:06:49 Node-ap231 minio [538]: Error: mkdir /mnt/minio/data1/.minio.sys/tmp/ea3ca4ff-6c02-4deb-9ad5-0bc3cc0864b1: read-only file system
Apr 09 14:06:49 Node-ap231 minio [538]: 1: cmd / xl-v1-metadata.go: 429: cmd.writeXLMetadata ()
Apr 09 14:06:49 Node-ap231 minio [538]: 2: cmd / xl-v1-metadata.go: 520: cmd.writeSameXLMetadata.func1 ()
Apr 09 14:06:49 Node-ap231 minio [538]: API: NewMultipartUpload (bucket = bgtender, object = notification__2019030100_2019040100_001.xml.zip)
```
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):  2018-12-06T01:27:43Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): Linux urudc1ap231 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2 (2017-06-12) x86_64 GNU/Linux
* Link to your project:

**Comment by nitisht** [comment]
@chernykhse did you have a power failure in this cluster? Looks like you're hitting some variation of this https://bugzilla.redhat.com/show_bug.cgi?id=839891

MinIO logs basically indicate that MinIO wasn't able to write to `ext4`. This is because filesystem usually go into `read-only` mode while its checking if there is a consistency issue. Once the check is done, it gets remounted as `read-write` and you're able to make changes.

**Comment by chernykhse** [comment]
> @chernykhse did you have a power failure in this cluster? Looks like you're hitting some variation of this https://bugzilla.redhat.com/show_bug.cgi?id=839891

> 
> MinIO logs basically indicate that MinIO wasn't able to write to `ext4`. This is because filesystem usually go into `read-only` mode while its checking if there is a consistency issue. Once the check is done, it gets remounted as `read-write` and you're able to make changes.

Checked the logs, did not find problems with the cluster.
The file system was not in read-only mode. We ran the mkdir command in the folder where the log was pointing and everything was created there.

**Comment by harshavardhana** [comment]
@chernykhse you disk is failing you need to run fsck to see the issues. Don't believe that you could create directories.

**Comment by chernykhse** [comment]
> @chernykhse you disk is failing you need to run fsck to see the issues. Don't believe that you could create directories.

that time we rebooted the nodes, so we didn’t see what the errors were there.
Now the problem has appeared on four different nodes.
dmesg says: 
```
[32862.020920] EXT4-fs error (device sdb): ext4_validate_inode_bitmap: 134: comm minio: Corrupt inode bitmap - block_group = 2004, inode_bitmap = 65536020
[32862.022233] EXT4-fs (sdb): Remounting filesystem read-only
```
we used e2fsck
```
e2fsck /dev/sdb
e2fsck 1.43.4 (31-Jan-2017)
/dev/sdb: recovering journal
/dev/sdb contains a file system with errors, check forced.
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
Free blocks count wrong (89040816, counted=87519862).
Fix<y>? yes
Free inodes count wrong (35272239, counted=35052009).
Fix<y>? yes

/dev/sdb: ***** FILE SYSTEM WAS MODIFIED *****
/dev/sdb: 17376791/52428800 files (0.0% non-contiguous), 122195338/209715200 blo                                                 cks
```
### Why disk errors continue to appear?

We have recorded more than half a million small files (300Kb). Maybe we chose the wrong file system or something else?

**Comment by harshavardhana** [comment]
> We have recorded more than half a million small files (300Kb). Maybe we chose the wrong file system or something else?

You may need to contact your disk vendor @chernykhse - this means that your disk has bad sectors.

**Comment by nitisht** [comment]
@chernykhse closing this for now as doesn't look like any action needed from our side, feel free to reopen if there are further issues..

**Comment by chernykhse** [comment]
> > We have recorded more than half a million small files (300Kb). Maybe we chose the wrong file system or something else?
> 
> You may need to contact your disk vendor @chernykhse - this means that your disk has bad sectors.


virtual disks are hosted on the LUN, from the enterprise storage system. Since RAID is used there, we were assured that there are no bad sectors on virtual disks.
just in case, we ran e2fsck -c, bad sectors were not found.

**Comment by harshavardhana** [comment]
> virtual disks are hosted on the LUN, from the enterprise storage system. Since RAID is used there, we were assured that there are no bad sectors on virtual disks.
> just in case, we ran e2fsck -c, bad sectors were not found.

That seems odd @chernykhse - ext4 seems to be complaining about exactly such things. The errors indicate that your LUN is either getting corrupted over time. Which clearly indicates - storage infrastructure issue. 

Now to pinpoint to an exact situation

- how often does this occur?
- is there a pattern for this occurrence?
- any specific directory where this occurs? 

Next time when it happens please capture dumpe2fs such that this can be shared with your vendor.

**Comment by chernykhse** [comment]
> The errors indicate that your LUN is either getting corrupted over time. Which clearly indicates - storage infrastructure issue.

We have enterprise storage systems https://www.infinidat.com/
LUNs are not a representation of a physical disk, there are many disks in the storage system, from which LUNs are created, which in turn are connected to the ECX host. The storage system checks for the status of physical disks, in case of problems, the disk changes immediately, and since its blocks are duplicated, even if several disks fail, not one bit will be lost. I explained how I could :)
The basic idea is that damage on the physical level is impossible, and if it were, there are more than a hundred virtual machines, and not one of them has never appeared disk errors.

> how often does this occur? 

Last week it happened on 4 different cluster nodes.

> is there a pattern for this occurrence?

we make an "MC mirror" for backup purposes. For the weekend, the mirror was not turned on, and the problem did not recur. Today launched a mirror of all baskets, 4 hours later, drive
  on one of the nodes it switched to read only mode, errors appeared again.
Perhaps this is somehow related to intensive reading.

> any specific directory where this occurs?

I did not quite understand this question

> Next time when it happens please capture dumpe2fs such that this can be shared with your vendor.

we ran this command, after e2fsck -c, the output contained the following:
```
#dumpe2fs -b /dev/sdb
dumpe2fs 1.43.4 (31-Jan-2017)
```
I assume it means that there are no bad sectors

**Comment by chernykhse** [comment]
last  e2fsck -v
```
e2fsck -v /dev/sdb
e2fsck 1.43.4 (31-Jan-2017)
/dev/sdb: recovering journal
/dev/sdb contains a file system with errors, check forced.
Pass 2: Checking directory structure sizes
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
Free blocks count wrong (88632526, counted=83997109).
Fix<y>? yes
Free inodes count wrong (35203858, counted=33531213).
Fix<y>? yes to all

/dev/sdb: ***** FILE SYSTEM WAS MODIFIED *****

    18897587 inodes used (36.04%, out of 52428800)
         659 non-contiguous files (0.0%)
        1212 non-contiguous directories (0.0%)
             # of inodes with ind/dind/tind blocks: 0/0/0
             Extent depth histogram: 18897454/123/2
   125718091 blocks used (59.95%, out of 209715200)
           0 bad blocks
           1 large file

    11967814 regular files
     6929764 directories
           0 character device files
           0 block device files
           0 fifos
           0 links
           0 symbolic links (0 fast symbolic links)
           0 sockets
------------
    18897578 files
```

**Comment by harshavardhana** [comment]
A consistent read-only also means that there might be a kernel bug, which kernel version are you on?

**Comment by chernykhse** [comment]
> A consistent read-only also means that there might be a kernel bug, which kernel version are you on?

4.9.0-3-amd64

**Comment by harshavardhana** [comment]
Would it be possible to upgrade to latest or move to new FS and see the issue goes away? We have seen some reports of ext4 corruption bug in 4.x kernels.

**Comment by chernykhse** [comment]
> Would it be possible to upgrade to latest or move to new FS and see the issue goes away? We have seen some reports of ext4 corruption bug in 4.x kernels.

based on your experience which file system is most suitable for minio?

**Comment by harshavardhana** [comment]
XFS is our recommended choice

**Comment by chernykhse** [comment]
it will take time, first we need to try in a test environment.

**Comment by kannappanr** [comment]
ping @chernykhse Did you get a chance to try it out?

**Comment by chernykhse** [comment]
> ping @chernykhse Did you get a chance to try it out?

We tested the transition to XFS. in a test environment. And they considered that the transfer of all servers would take about 1000 hours, due to copying.
Plus, this is still not solve the problems with cluster backup.
Therefore, we are now considering other object storages.
This issues can be closed if we continue to work with the minio i reopen this issues
