### ISSUE TITLE
setup nginx reverse proxy with minio server: why use default location?

### ISSUE THREAD

**Issue by thomaslange24** [minio/minio#7511]
I am starting a minio server on some remote machine with the following command:
minio server --address :9000 /opt/archive/minio_storage

Now i want to set up a Nginx reverse proxy and redirect all requests to the host on which the minio server is running.  

I am revering to the documentation: 
https://docs.min.io/docs/setup-nginx-proxy-with-minio.html
 
What confuses me is that the default location is used for directing the requests to the minio server.
location / {
   proxy_set_header Host $http_host;
   proxy_pass http://localhost:9000;
   health_check uri=/minio/health/ready;
 }

I already have another redirect specification for the default location in my nginx conf, which would be concurrent to the recommended specification for minio from the documentation. So how would i change the location in order to handle all requests to the minio server?

**Comment by kannappanr** [comment]
@thomaslange24 In the same document, you can look at section `Proxy requests based on the bucket` and in the location you can use the buckets. The catch here is that all the bucket names that currently exist and will be created should be listed here.

**Comment by thomaslange24** [comment]
So for any bucket that will be created i also have to add an location entry in the nginx configuration?

**Comment by kannappanr** [comment]
Yes

**Comment by kannappanr** [comment]
@thomaslange24 closing this issue. Please feel free to reach out to us if you have further questions.
