### ISSUE TITLE
Use etcd watch apis to update the bucket policy cache

### ISSUE THREAD

**Issue by sgandon** [minio/minio#7515]
when using the multiple instances of the gateway connected to an etcd instance for handling bucket policies when a new user is created, there is a 5 minutes duration before the other instances are updated with the change of the bucket policy. 

## Expected Behavior

It would be great that the policy bucket update was perfomed immediatly.

## Current Behavior

wait for 5 minutes, see this : https://github.com/minio/minio/blob/5ecac91a551c043160fbe17dd615280939b83892/cmd/globals.go#L86

## Possible Solution

use the etc watch APIs so that every instances are notified automatically when a policy change occurs : https://coreos.com/etcd/docs/latest/learning/api.html#watch-streams

**Comment by sgandon** [comment]
here is the link to the slack discussion 
https://minio.slack.com/conversation/C3NDUB8UA/p1554901280616300

**Comment by nitisht** [comment]
Thanks for reporting the issue, we'll see how to incorporate this @sgandon

**Comment by harshavardhana** [comment]
> use the etc watch APIs so that every instances are notified automatically when a policy change occurs : https://coreos.com/etcd/docs/latest/learning/api.html#watch-streams

Bucket policies are not kept on etcd only user policies, users are kept on etcd @sgandon .So the issue description is incorrect here. 

Nevertheless, a PR #7551 is here.

**Comment by sgandon** [comment]
Thanks a lot guys !

**Comment by sgandon** [comment]
humm, it seems not to be working and even to not propagate the policies anymore :(

**Comment by harshavardhana** [comment]
> humm, it seems not to be working and even to not propagate the policies anymore :(

we have tested this already and it was working at the time of the PR @sgandon - can you confirm your etcd version and open a new issue?
