### ISSUE TITLE
unhealthy with https

### ISSUE THREAD

**Issue by axelll** [minio/minio#7517]
When i use HTTPS containers is showing unhealthy status

## Expected Behavior
Should showing healthy status

## Current Behavior
in file healthcheck.go don't work a check:
// This means sever is configured with https
if resp.StatusCode == http.StatusForbidden && bodyString == "SSL required"

Print URL and response
2019/04/12 11:55:35 http url: http://127.0.0.1:9000/minio/health/live
resps: &http.Response{Status:"400 Bad Request", StatusCode:400, Proto:"HTTP/1.0", ProtoMajor:1, ProtoMinor:0, Header:http.Header{}, Body:(*http.cancelTimerBody)(0xc00014e060), ContentLength:-1, TransferEncoding:[]string(nil), Close:true, Uncompressed:false, Trailer:http.Header(nil), Request:(*http.Request)(0xc000142100), TLS:(*tls.ConnectionState)(nil)}

Print Body
2019/04/12 11:55:35 Client sent an HTTP request to an HTTPS server.

## Steps to Reproduce (for bugs)
1.
2.
3.
4.

## Your Environment

* Version used (`minio version`): 2019-04-09T01:22:30Z
* Environment name and version (e.g. nginx 1.9.1): docker 18.09.0
* Server type and version: 
* Operating System and version (`uname -a`): Linux 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by nitisht** [comment]
Thanks for reporting @axelll we'll take a look soon

**Comment by vadmeste** [comment]
> Thanks for reporting @axelll we'll take a look soon

Looks like this happened after the migration to http2

**Comment by harshavardhana** [comment]
It happened after migration to go1.12 , we removed our custom error.
