### ISSUE TITLE
Bulk delete

### ISSUE THREAD

**Issue by EugenMayer** [minio/minio#7538]
I would love to be able to bulk delete, similar to be able to bulk download. Any way this could be implemented? I see that https://github.com/minio/minio/issues/956 was needed, but seems to be solved already or it might be related to https://github.com/minio/minio/issues/7311

Thank you

**Comment by kannappanr** [comment]
@EugenMayer MinIO already supports bulk delete. https://docs.aws.amazon.com/AmazonS3/latest/API/multiobjectdeleteapi.html is already implemented. You can use any of `MinIO` or any `S3` compatible SDK today to do this.

**Comment by EugenMayer** [comment]
Hello, i probably was confusing UI - mean using the UI, not the REST endpoints. Could you reopen that issue? Thank you

**Comment by kannappanr** [comment]
![Screenshot from 2019-04-13 07-35-27](https://user-images.githubusercontent.com/30541348/56081138-c44c1280-5dbe-11e9-800b-5e1b2e346ad6.png)
This is also supported on the browser.

**Comment by EugenMayer** [comment]
Sorry - i missed that. My bad! thank a lot
