### ISSUE TITLE
[Question] MinIO Admin RestApi documentation

### ISSUE THREAD

**Issue by ptr1120** [minio/minio#7539]
Hello,
is there any public (Rest) API description for managing users? The mc client application is nice, but I need to manage users and policies dynamic (using dotnet). What is the suggested way to do such things?

Best regards
Peter

**Comment by harshavardhana** [comment]
REST API is documented here https://github.com/minio/minio/tree/master/pkg/madmin , for now, we are not planning to implement different language libraries for Admin REST API.  Our SDKs are only meant for S3 APIs only. 

The suggested way is to use `mc` tool or use the Go API directly or write your own wrapper for your language choice.

**Comment by ptr1120** [comment]
@harshavardhana: thank you. But this means we can not use minio from other languages than golang if we want to dynamically manage user. 
Using the `mc` command line tool from our program seems not to be a robust solution.
Using the Api is difficult due to the undocumented way of encoding sensitive data and required parameters. Would it at least be an option to provide the encoding function for the different language libraries (to make it possible to write a custom client for these admin operations)? Or is there an option to disable the requirement of encoding sensitive data  (minio is not public in our environment)

Thank you and regards,
Peter

**Comment by harshavardhana** [comment]
@ptr1120 it is not currently a priority to provide admin APIs in various languages. We may get back to this in future.
