### ISSUE TITLE
Unable to connect MiniO by using v4 signature.

### ISSUE THREAD

**Issue by mzch** [minio/minio#7540]
I can't connect my clients to Minio by using v4 signature. When using v2 signature, they can connect Minio successfully.

## Expected Behavior

Using AWS v4 signature, my client apps should connect successfully.
Client App 1: Dropshare https://dropshare.app/ 
Client App 2: Forklift https://binarynights.com/
Client App 3: Mattermost https://www.mattermost.org/

I don't know which side has a problem. Any idea?
## Current Behavior

Using AWS v4 signature thru my client apps, they report 'Access Denied' or 'The request signature we calculated does not match the signature you provided. Check your key and signing method.' When using v2 signature, they can connect successfully.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
Version: 2019-04-09T01:22:30Z
Release-Tag: RELEASE.2019-04-09T01-22-30Z
Commit-ID: a2e344bf30c7750c0a152f046a70d327f2f5ccf5
* Environment name and version (e.g. nginx 1.9.1):Apache/2.4.25 (Debian) OpenSSL/1.0.2r
* Server type and version:
* Operating System and version (`uname -a`):Linux ny 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
* Link to your project:

**Comment by nitisht** [comment]
@mzch can you confirm if same set of clients work with AWS S3?

**Comment by mzch** [comment]
Yes, they work fine with AWS S3.

**Comment by nitisht** [comment]
Also pathstyle access should be enabled on these clients for minIO to work, is that done?

**Comment by mzch** [comment]
sorry, I can't find settings to enforce path-style access in them. I have posted articles related this issue to client apps' forums and support teams, but ATM no replies.

**Comment by nitisht** [comment]
@mzch closing this for now as we have tests running with AWS S3 and MinIO SDK that use S3 v4. These tests are working. Feel free to reopen if enforcing path-style doesn't work..
