### ISSUE TITLE
MINIO_DRIVE_SYNC on Windows

### ISSUE THREAD

**Issue by uroni** [minio/minio#7542]
I do not think MINIO_DRIVE_SYNC works on Windows as the O_SYNC flag has no effect there.

## Expected Behavior

Every write to a file is written to disk immediately (O_SYNC) on Windows.

## Current Behavior

Minio behaves as if MINIO_DRIVE_SYNC is not set (on Windows).

## Possible Solution

Call fsync() instead of using O_SYNC.

## Steps to Reproduce (for bugs)

1. Set MINIO_DRIVE_SYNC on Windows
2. Reset Windows box immediately after PUT object
3. Observe that object is missing

**Comment by kannappanr** [comment]
@uroni Thanks for filing this issue. We will send in a fix.

**Comment by harshavardhana** [comment]
Shall be fixed here https://github.com/minio/minio/pull/7479

**Comment by uroni** [comment]
The direct IO lib you use sets FILE_FLAG_WRITE_THROUGH on Windows which just sets the FUA bit in disk write requests (https://devblogs.microsoft.com/oldnewthing/?p=95505). Most SCSI drives just ignore the FUA bit, though, so you'll still have to use fsync/FlushFileBuffers if you want the MINIO_DRIVE_SYNC behaviour on Windows.

**Comment by harshavardhana** [comment]
This feature won't be implemented on Windows as it's not a priority for us, you can use Linux instead which provides this functionality as expected.

**Comment by kannappanr** [comment]
@uroni Please feel free to send a PR.

**Comment by kannappanr** [comment]
Closing this is as stale. Please feel free to send a PR.
