### ISSUE TITLE
Minio Gateway + Cache hangs when file is deleted

### ISSUE THREAD

**Issue by navossoc** [minio/minio#7549]
Minio Gateway hangs when a file is deleted on upstream server.

## Expected Behavior
Don't hang the request...
Just show the cached file or send a 404.

## Current Behavior
Hang the request forever (10 minutes)...

## Possible Solution
No idea what is happening here.
This is the far I could get.

## Steps to Reproduce (for bugs)

1. Set up a minio server (you can use play.minio.io)
2. Set up a gateway server to a s3 server.
3. Create a bucket on the server.
4. Allow readonly access on that bucket.
5. Upload a file to it.
6. Check the link on the server (ok / 200).
7. Check the link on the gateway (ok / 200).
8. Delete the file on the server (minio web ui)
9. Check the link on the server again (ok / 404).
10. Check the link on the gateway again (connection hangs for 10 minutes / 404)

A little script to help:
```bash
# setup gateway
export MINIO_BROWSER=off

export MINIO_ACCESS_KEY=Q3AM3UQ867SPQQA43P2F
export MINIO_SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG

export MINIO_CACHE_DRIVES="/data/minio/"
export MINIO_CACHE_EXPIRY=90
export MINIO_CACHE_MAXUSE=80
minio gateway s3 https://play.minio.io:9000

# type on another terminal

mc mb play/github-bug/
mc policy download play/github-bug/
wget https://min.io/resources/img/logo/MINIO_wordmark.png
mc cp MINIO_wordmark.png play/github-bug/

# simulate a user getting the file with the browser
wget https://play.minio.io:9000/github-bug/MINIO_wordmark.png # 200 / ok
wget http://gateway.minio.io:9000/github-bug/MINIO_wordmark.png # 200 / ok

mc rm play/github-bug/MINIO_wordmark.png
# also, this command seems not working on windows

# check both links again
wget https://play.minio.io:9000/github-bug/MINIO_wordmark.png # 404 / not found
wget http://gateway.minio.io:9000/github-bug/MINIO_wordmark.png # hangs

# end test... nuke everything
#mc rm --force --recursive play/github-bug/
#rm -rf /data/minio
#pkill minio
```

## Context

Badly, if somehow the file on the upstream is deleted you can hang the gateway server.

## Regression
No idea, probably not.

## Your Environment
**s3 server:**
play.minio.io

**gateway:**

Minio:
Version: 2019-04-09T01:22:30Z
Release-Tag: RELEASE.2019-04-09T01-22-30Z
Commit-ID: a2e344bf30c7750c0a152f046a70d327f2f5ccf5

No reverse proxy at all.

Debian 9 x64

**Comment by nitisht** [comment]
Thanks for reporting @navossoc we'll take a look

**Comment by harshavardhana** [comment]
This issue might be related to the caching fix https://github.com/minio/minio/commit/ddb0d646aafa05ae9f03a15c99435ca43885fd5a
