### ISSUE TITLE
[not a bug] Why Standalone Multi-Tenant Deployment is faster than Standalone normal？(write or put)

### ISSUE THREAD

**Issue by linuxrc** [minio/minio#7550]
I want a fast object storage tool and did a performance test for Minio. I found that if I deploy Minio in Standalone mode, Multi-Tenant (4) is fatster than norma node,I want to know why.
     I start Minio like this:
 * Normal:    minio server --address :9000 ./DATA1
* Multi-Tenant: minio server --address :9000 ./DATA{1...4}
The directory DATA1~DATA4 is just a directory, I didn't mount it to any disk devices.

## Expected Behavior

 As far as I know, if we split one file to many small files and did something like Erasure Code, and then rewrite it to such small files, the write rate can't be faster than I write it to only one file.

## Current Behavior

     But, the truth is that Multi-Tenant mode (4 nodes) is fatster than Normal mode. My result is:
* Normal mode: maybe 50times/s, that is, I can write a file which size is 10KB to Minio 50 times persecond, so the rate is 500KB/s;
* Multi-Tenant mode: 180times/s, the rate is 1800KB/s.

## Steps to Reproduce (for bugs)

1. start two Minio instances which is in normal mode and Multi-Tenant mode ;
2. PUT a complete file that is 10KB size into Minio to test the upload performance in both mode;
3. compare the performance or write rate between this two mode.
4.

## Your Environment

* Version used (`minio version`): 2018-11-06
* Environment name and version (e.g. nginx 1.9.1):  Minio standalone mode in normal and Multi-Tenant run directoly in CentOS 7.4.
* Server type and version:  Virtual machine run CentOS 7.4 in VMWARE
* Operating System and version (`uname -a`): Linux zcw61 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by kannappanr** [comment]
@linuxrc Will run this test and get back to you with the numbers and explanation. Thanks for filing this issue.

**Comment by ghost** [comment]
because fsMate is written to disk immediately (O_SYNC).

**Comment by kannappanr** [comment]
@linuxrc Testing such small objects for is probably not a very good use case for object storage in general. 

I ran this test on stand alone mode

```
time mc cp -r myminio/test /tmp/lll
http://127.0.0.1:9000/test/issue100:                                1000.00 KiB / 1000.00 KiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 6.62 MiB/s 0s
real	0m0.210s
user	0m0.193s
sys	0m0.055s
```

same test on locally erasure coded deployment

```
time mc cp -r myminio/test /tmp/lll
http://127.0.0.1:9000/test/issue100:                                1000.00 KiB / 1000.00 KiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 4.11 MiB/s 0s
real	0m0.314s
user	0m0.172s
sys	0m0.086s
```

Not sure how it is faster on your end.

**Comment by kannappanr** [comment]
@linuxrc One difference in my case is that I used single disk and not multiple disks. For your test, you have used Virtual Machine, which I did not.

**Comment by linuxrc** [comment]
@kannappanr I did my test on real physical machine again and got the same result. I used Amazon AWS S3 API to store these objects to Minio, and I used http/1.1 pipeline scheme. What objects do you have in myminio/test? I put a lot of objects(maybe 100000) which have the same size 10KB one by one to Minio using AWS S3 API in a single thread(http/1.1 pipeline).

**Comment by linuxrc** [comment]
@kannappanr I think if you use mc to test the performance of copying files, the result is not exact, because you did not reach the toplimit of Minio in a single connection.

**Comment by harshavardhana** [comment]
@linuxrc mc does parallel copy, and with in a object does multipart in parallel as well. Not able to understand what are you saying about toplimit of single connection.

**Comment by linuxrc** [comment]
@harshavardhana I mean, when I try to put many objects in a single tcp connection, Minio will process the request one by one in their order. If I use http pipeline in my client, the later request is sent directly to Minio, whereas there‘s no need to wait the former request to accomplish its operation. So, Minio will be busy processing my PUT requests, and there’s no idle state to wait the request to come, because the requests are too many to process in the single TCP connection.

I did another test, the result shows that the GET/READ operation is slower in Multi-Tenant mode, this is exactly what I want to see.

So, I wonder why the PUT/WRITE operation is faster in Multi-Tenant mode.

**Comment by kannappanr** [comment]
`So, I wonder why the PUT/WRITE operation is faster in Multi-Tenant mode.`

Are we still talking about 10 KB files?

**Comment by linuxrc** [comment]
> 
> 
> `So, I wonder why the PUT/WRITE operation is faster in Multi-Tenant mode.`
> 
> Are we still talking about 10 KB files?

Yes.

**Comment by kxion** [comment]
thanks a lot

**Comment by darkdragon-001** [comment]
This issue also affects me!

**Comment by klauspost** [comment]
Not sure it is positive, but this no longer seems to be the case:
```
λ warp put -obj.size=10KiB -duration=1m

Operation: PUT. Concurrency: 32. Hosts: 1.
* Average: 10.06 MiB/s, 1030.01 obj/s (59.859s, starting 12:21:37 CEST)

Aggregated Throughput, split into 59 x 1s time segments:
 * Fastest: 11.3MiB/s, 1159.69 obj/s (1s, starting 12:21:56 CEST)
 * 50% Median: 10.3MiB/s, 1059.06 obj/s (1s, starting 12:22:30 CEST)
 * Slowest: 6.7MiB/s, 685.26 obj/s (1s, starting 12:22:08 CEST)
```

```
Operation: PUT. Concurrency: 32. Hosts: 4.
* Average: 2.16 MiB/s, 221.25 obj/s (59.555s, starting 12:19:35 CEST)

Aggregated Throughput, split into 59 x 1s time segments:
 * Fastest: 2.3MiB/s, 230.77 obj/s (1s, starting 12:19:53 CEST)
 * 50% Median: 2.2MiB/s, 222.04 obj/s (1s, starting 12:20:03 CEST)
 * Slowest: 2.0MiB/s, 209.43 obj/s (1s, starting 12:20:25 CEST
```
Feel free to join community slack to discuss performance.
