### ISSUE TITLE
Reopen "read-only file system" Distributed mode

### ISSUE THREAD

**Issue by chernykhse** [minio/minio#7553]
Could not reopen issue https://github.com/minio/minio/issues/7510
Collecting information for your last question took a lot of time.

Can you reopen my last issue (https://github.com/minio/minio/issues/7510)? or do i need to rewrite everything in this new

**Comment by nitisht** [comment]
Please continue the discussion at https://github.com/minio/minio/issues/7510, feel free to close this issue

**Comment by chernykhse** [comment]
tnx
