### ISSUE TITLE
Multiple NFS shares

### ISSUE THREAD

**Issue by barthalexander** [minio/minio#7554]
Hi,

first of all thanks for Minio it's very cool.

I want to use multiple nfs shares with minio. 
I have tried to start it with `./minio gateway nas /data`.
The folder data contains multiple nfs shares.
Every time when I want to upload a file I get an error with cross linking.
What I'm doing wrong.

Kind Regards,
Alex

**Comment by kannappanr** [comment]
@barthalexander Can you please use the issue template that we have. I don't think we allow this setup.

**Comment by harshavardhana** [comment]
We don't support cross mounts inside a directory, you should just start one MinIO per share.

Closing this as not supported.
