### ISSUE TITLE
Default Windows cert path is incorrect

### ISSUE THREAD

**Issue by BGodding** [minio/minio#7562]
~6 months ago I setup a minio as multi-tentant after following https://forum.duplicati.com/t/setting-up-self-hosted-minio-on-windows-10-with-automatically-renewing-ssl-certificate/645 to backup several computers. It has been running great with no issues, but finally decided to upgrade just to keep things up to date and secure.

I now get the following when trying to launch the server
'''D:\minio>minio.exe server --address :58001 --config-dir C:\Users\BGodd\.minio-tenant1 D:\minio-data\tenant1\
7[41m[37m[1mERROR[0m[0m[0m 8[6C[31mUnable to load the TLS configuration: [1mCreateFile /C:\Users\BGodd\.minio\certs: The filename, directory name, or volume label syntax is incorrect..[0m[0m'''

The certificates are present in C:\Users\BGodd\.minio\certs and work fine with the old version.

D:\minio>minio.exe version
Version: 2019-04-18T21:44:59Z
Release-Tag: RELEASE.2019-04-18T21-44-59Z
Commit-ID: 2c096c569f2e57408ae657c669dc5740cba7a603

Windows 10 Pro version 1806 build 17134.706

**Comment by BGodding** [comment]
Just realized the path is not correct, it should be C:\Users\BGodd\\.minio\certs

**Comment by BGodding** [comment]
I think this is probably actually a bug on Windows, but if I am wrong feel free to close.
The \ before the . in minio looks like it is treated like an escape character and dropped

**Comment by kannappanr** [comment]
Can you try 
```
minio.exe server --address :58001 --certs-dir C:\Users\BGodd\.minio\certs D:\minio-data\tenant1
```

or 

```
minio.exe server --address :58001 D:\minio-data\tenant1
```

**Comment by BGodding** [comment]
Yes, --certs-dir C:\Users\BGodd\\.minio\certs does in fact work and that I what changed my local initialization to.

**Comment by kannappanr** [comment]
Closing the issue then. Please feel free to reach out to us if you have further questions.

**Comment by BGodding** [comment]
According to https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls.html the default path should be ```Windows: C:\Users\<Username>\.minio\certs\CAs``` but it appears that currently it is actually ```Windows: C:\Users\<Username>.minio\certs\CAs``` so should https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls.html be updated or this bug be closed?

**Comment by kannappanr** [comment]
@BGodding Will verify this on Windows and let you know. `C:\Users\<Username>\.minio\certs` should be the default value.

**Comment by eco-minio** [comment]
@BGodding Looks like there is a typo in your server command:

D:\minio>minio.exe server --address :58001 --config-dir C:\Users\BGodd.minio-tenant1\ D:\minio-data\tenant1

Note here it was \BGodd.minio instead of \BGodd\\.minio. When you give --config-dir as an argument, it creates that directory if it does not exist.  So, in this case, there would be a C:\Users\BGodd.minio-tenant1\certs directory created where the private.key and public.crt need to be copied.  Without --config-dir, minio will look in the default location (C:\Users\\{username}\\.minio\\certs).  Tested and confirmed the default location works as expected, feel free to ask if you have more questions.

**Comment by kannappanr** [comment]
@BGodding Closing this as working. Please feel free to reach out to us if you have more questions.

**Comment by BGodding** [comment]
Sorry about the confusion, the typo (where the forward slash before . is treated as an escape char and dropped) occurred when I copied and pasted the command into github, it's what triggered the thought in my mind that maybe a similar issues was occurring with in the minio code. I probably should have gone back and edited the comments.

The facts are:
if I run
```D:\minio>minio.exe server --address :58001 --config-dir C:\Users\BGodd\.minio-tenant1\ D:\minio-data\tenant1``` I get the message ```Unable to load the TLS configuration: CreateFile /C:\Users\BGodd.minio\certs: The filename, directory name, or volume label syntax is incorrect```
but if I add ```--certs-dir C:\Users\BGodd\.minio\certs``` to the arguments there is no error. This means that when I do not append ```--certs-dir``` the default directory does NOT appear to be ```C:\Users\<Username>\.minio\certs```

Hopefully that clears things up

**Comment by harshavardhana** [comment]
We will take a look

**Comment by BGodding** [comment]
Took a quick shot at reproducing, but output looks fine.
Must just be a fluke on that machine. ¯\\_(ツ)_/¯
```
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/mitchellh/go-homedir"
)

const (
	// Default minio configuration directory where below configuration files/directories are stored.
	defaultMinioConfigDir = ".minio"

	// Directory contains below files/directories for HTTPS configuration.
	certsDir = "certs"

	// Directory contains all CA certificates other than system defaults for HTTPS.
	certsCADir = "CAs"

	// Public certificate file for HTTPS.
	publicCertFile = "public.crt"

	// Private key file for HTTPS.
	privateKeyFile = "private.key"
)

func getDefaultConfigDir() string {
	homeDir, err := homedir.Dir()
	if err != nil {
		return ""
	}

	return filepath.Join(homeDir, defaultMinioConfigDir)
}

func getDefaultCertsDir() string {
	return filepath.Join(getDefaultConfigDir(), certsDir)
}

func getPublicCertFile() string {
	return filepath.Join(getDefaultCertsDir(), publicCertFile)
}

func getPrivateKeyFile() string {
	return filepath.Join(getDefaultCertsDir(), privateKeyFile)
}

// isFile - returns whether given path is a file or not.
func isFile(path string) bool {
	if fi, err := os.Stat(path); err == nil {
		return fi.Mode().IsRegular()
	}

	return false
}

func main() {
	fmt.Println(getDefaultConfigDir())
	fmt.Println(getDefaultCertsDir())
	fmt.Println(getPublicCertFile())
	fmt.Println(getPrivateKeyFile())
	fmt.Println(isFile(getPublicCertFile()))
	fmt.Println(isFile(getPrivateKeyFile()))
}
```
```
C:\Users\BGodd\.minio
C:\Users\BGodd\.minio\certs
C:\Users\BGodd\.minio\certs\public.crt
C:\Users\BGodd\.minio\certs\private.key
true
true

Process finished with exit code 0
```

**Comment by harshavardhana** [comment]
Probably can you confirm works on other systems?

**Comment by BGodding** [comment]
Setup a new VM and with the same config and drive paths, and issue does not repeat. 

Played with the issue system, and found if I dropped the ```--config-dir C:\Users\BGodd\.minio-tenant1``` from the command the issue went away. Must be something leftover from an old config causing the issue.
