### ISSUE TITLE
More data was sent than what was advertised

### ISSUE THREAD

**Issue by kmatt** [minio/minio#7568]
When copying JSON data files to a 4 disk Minio cluster, the following error is repeated frequently in the terminal session running the Minio server:

    API: SYSTEM()
    Time: ...
    Error: more data was sent that what was expected
    storageDisk= (any of the 4 disks in the system)
    1: cmd/bitrot-streaming.go:89:cmd.newStreamingBitrotWriter.func1()

This occurs using `minio cp` and with rclone.

## Expected Behavior
Files are appearing in Minio storage, seen in `minio ls`.
Uncertain if the error means some files are not being written or files are incomplete.

## Steps to Reproduce (for bugs)
1) Install Minio binary on servers
2) Create 4 dedicated paths for data across 3 hosts
3) Start server with: `minio server --address ':9001' http://dev0/localdata3/miniohttp://dev0/localdata4/minio http://dev1/localdata/minio http://dev2/localdata/minio`
4) Create bucket with: `mc mb minio/logs`
5) Copy files into storage with: `mc cp '*.json' minio/logs`

## Your Environment
* Version used (`minio version`):
    Version: 2019-04-18T21:44:59Z
    Release-Tag: RELEASE.2019-04-18T21-44-59Z
    Commit-ID: 2c096c569f2e57408ae657c669dc5740cba7a603
* Server type and version: `CentOS Linux release 7.6.1810 (Core)`
* Operating System and version (`uname -a`): `Linux 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

* Only change to config for compression:
```
"compress": {
    "enabled": true,
    "extensions": [
      ".txt",
      ".log",
      ".csv",
      ".json",
      ".dat"
    ],
```

**Comment by kannappanr** [comment]
@kmatt Will take a look. Can you confirm that you do not see this issue, if `compression` is not enabled?

**Comment by kmatt** [comment]
@kannappanr Created a new bucket, disabled compression and restarted load via rclone. The errors appear to have stopped in the console:

```
Transferred:       57.540G / 247.088 GBytes, 23%, 46.394 MBytes/s, ETA 1h9m43s
Errors:                 0
```

Unfortunately rclone was not recognizing them so previous error count is not available (which may be an rclone issue).
