### ISSUE TITLE
CompleteMultipartUpload Error: encoding/hex: invalid byte: U+002D '-'

### ISSUE THREAD

**Issue by lseelenbinder** [minio/minio#7573]
When uploading using the official Python client to a MinIO server in B2 gateway mode with disk cache enabled, I'm seeing this error consistently:

```
API: CompleteMultipartUpload(bucket=bucketname-with-dashes, object=48191817212958.orig-audio)
Time: 15:07:47 UTC 04/23/2019
RequestID: 159822EB9A67A27A
RemoteHost: 10.233.69.170
UserAgent: Minio (Linux; x86_64) minio-py/4.0.13
Error: encoding/hex: invalid byte: U+002D '-'
       1: cmd/object-api-utils.go:198:cmd.getCompleteMultipartMD5()
       2: cmd/fs-v1-multipart.go:507:cmd.(*FSObjects).CompleteMultipartUpload()
       3: cmd/disk-cache.go:853:cmd.cacheObjects.CompleteMultipartUpload()
       4: cmd/object-handlers.go:2284:cmd.objectAPIHandlers.CompleteMultipartUploadHandler()
       5: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()
```

It does not seem to affect B2, since the file is uploaded and available from B2. It does however affect the disk cache, as the file does not appear in the cache until it's been accessed once.

## Expected Behavior
CompleteMultiPartUpload succeeds and the file is cached in the disk cache.

## Current Behavior
CompleteMultiPartUpload fails, the file is not cached, but is present in B2.

## Steps to Reproduce (for bugs)

1. Setup a MinIO server in gateway and disk cache mode with B2 as the backend.
2. Upload a file via multipart.
3. Check error logs and if file is in cache (it won't be).

## Regression
Unknown.

## Your Environment

* Version used (`minio version`): `RELEASE.2019-04-18T21-44-59Z`
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by nitisht** [comment]
Thanks for reporting, we'll take a look @lseelenbinder

**Comment by lseelenbinder** [comment]
It may be connected to the fact there is a `-` in the object name. I haven't ruled that out yet.

**Comment by poornas** [comment]
@lseelenbinder, this issue is due to the ETag generated by B2 not being MD5Sum, so part verification fails during CompleteMultipartUpload - will see how we can address this.

**Comment by lseelenbinder** [comment]
Thanks @poornas! Let me know if and how I can help.

**Comment by kannappanr** [comment]
#7575 was reverted, so re-opening this issue
