### ISSUE TITLE
In federation mode Minio queries etcd with prefix option not the exact name

### ISSUE THREAD

**Issue by aeltawela** [minio/minio#7578]
In federation mode, Minio queries etcd with the bucket name as a prefix, not the exact name which gives wrong results in case you have a bucket that starts with another bucket name. For example: abc, abc_setup2, abc_setup3

## Expected Behavior

Minio should look for the exact name or filter the results

## Current Behavior

Minio returns all the records and queries the wrong node

## Possible Solution

Minio should look for the exact name or filter the results in minio/pkg/dns/etcd_dns.go:list:c.etcdClient.Get(ctx, key, etcd.WithPrefix())

**Comment by nitisht** [comment]
what is the MinIO version here @ahmedabt

**Comment by harshavardhana** [comment]
This is fixed and released https://github.com/minio/minio/commit/4c048963dc05edf642538b8bc71588f475854ac6

**Comment by kannappanr** [comment]
@ahmedabt Please use the issue template where we ask the MinIO version. Can you please confirm that the latest version of MinIO works as expected.

**Comment by harshavardhana** [comment]
Fixed and released closing.
