### ISSUE TITLE
No modification date for directories

### ISSUE THREAD

**Issue by boris779** [minio/minio#7582]
## Expected Behavior
When creating directories I would expect that the creation date of the directory is displayed in the "Last Modified" column

Actual the column is empty for directories

## Your Environment
* Version used (`minio version`): 2.4.13 (2019-04-09T01:22:30Z)
* Server type and version: minio-68c6df946d-vg7bq | OS: linux | Arch: amd64, Runtime  Version: go1.12 | CPUs: 8
* Operating System and version (`uname -a`):  SMP Debian 4.9.110-3+deb9u5~deb8u1 (2018-10-03) x86_64 GNU/Linux
* kubernets installation, helm installation

![2019-04-25_08h51_31](https://user-images.githubusercontent.com/10259016/56715229-5cd78080-6737-11e9-9c1c-fd12b6c4ad88.png)

**Comment by harshavardhana** [comment]
Directories are fake in a flat namespace they don't represent anything special on the disk, it is intentional that they don't have mod times. Their job is to give prefix based navigation and permissions. They don't represent the same thing that is usually represented on POSIX fs.

Only objects are the real entities which carry mod time and other metadata.

**Comment by boris779** [comment]
Maybe I get somethingwrong. In my case I do not have a flat namespace, I do exactly have these directories on disk.

![2019-04-25_09h37_19](https://user-images.githubusercontent.com/10259016/56717845-da05f400-673d-11e9-860e-f604abca98cd.png)

**Comment by harshavardhana** [comment]
@boris779 showing backend disk directories are not meaningful for MinIO - we translate POSIX into a flat namespace. So we purposefully don't care about modTimes, you shouldn't rely on directory modTimes on S3 API they inherently have no meaning. 

Directories are simply a prefix in a hierarchy delimited by `/` - this is not an issue, it is the intended behavior.

**Comment by boris779** [comment]
ok thanks.
