### ISSUE TITLE
Policy creation excessive etcd traffic and huge slowdowns in federated mode

### ISSUE THREAD

**Issue by chrono2002** [minio/minio#7587]
Hi, folks!

I have created a test Kubernetes environment with 5 minio instances in federated (with etcd) mode on separate nodes located nearby with 1gbps channel between them. Same for 3 etcd instances, even tested with 1. When i begin to create a large number of policies (more than 200), here comes more than 10 seconds slowdowns with arithmetic progression on every new policy creation, a really huge etcd cpu load and bandwidth utilization. Why is that? 

Everything is ok on localhost though. I have tried different version of etcd, with or without ssl with no luck.

Here is commands I use in the loop:

minio-mc admin policy add minio user${COUNTER} ./policy.json
minio-mc admin user add minio user${COUNTER} user${COUNTER} user${COUNTER} 
minio-mc admin user policy minio user${COUNTER} user${COUNTER}

policy.json:
```
{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Principal": {
"AWS": [
"user${COUNTER}"
]
},
"Action": [
"s3:GetBucketLocation",
"s3:ListBucket",
"s3:GetObject",
"s3:PutObject",
"s3:DeleteObject"
],
"Resource": [
"arn:aws:s3:::user${COUNTER}/*"
]
}
]
}
```
                      
Steps to reproduce:
1. create etcd cluster with instances on separate nodes
2. create minio cluster with instances on separate nodes with etcd (federated) support
3. create a lot of policies (more than 200) and see a huge traffic flow between nodes on every new policy creation

<img width="170" alt="2019-04-26 01_00_14-Kubernetes _ USE Method _ Cluster - Grafana" src="https://user-images.githubusercontent.com/16898214/56796785-f6785e00-681b-11e9-830d-ddd2f45b2f84.png">

It is very important for me to have more than even 100.000 policies in federation, but looking at this slowdowns would kill everything.

Environment:

- latest minio from master branch
- etcd v3.3.12 from quay.io/coreos/etcd
- 32-cores nodes with no load at all
- 1gbps channels between nodes with no load at all
- debian 9
- kubernetes 1.14 with calico 3.6

**Comment by harshavardhana** [comment]
First, you don't need to create 100's of policies if you want same policies for each user just use the `{aws:username}` keyword and you only need one policy which can be used across users.

FWIW - the issue is most probably fixed by https://github.com/minio/minio/pull/7551

**Comment by chrono2002** [comment]
thank you for your answer, harshavardhana
still same here but now for over 500 users and latest minio master branch

```
minio-mc admin policy add minio own_bucket ./token.json
while :; do
  minio-mc admin user add minio user${COUNTER} secrettoken own_bucket
done
```

token.json:
```
{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Principal": {
"AWS": [
"test123"
]
},
"Action": [
"s3:GetBucketLocation",
"s3:ListBucket",
"s3:GetObject",
"s3:PutObject",
"s3:DeleteObject"
],
"Resource": [
"arn:aws:s3:::{aws:username}/*"
]
}
]
}
```

**Comment by nitisht** [comment]
#7551 was just merged @chrono2002 , you'll need to either build it from master or use the `minio/minio:edge` Docker image to test this until we make a release

**Comment by chrono2002** [comment]
same excessive traffic and load
it grows on 1 sec per every 100 users
so on 1000 users a request could take about 10 sec

```
Added user `user0` successfully.

real    0m0.270s
user    0m0.116s
sys     0m0.064s
Added user `user1` successfully.

real    0m0.178s
user    0m0.096s
sys     0m0.088s
Added user `user2` successfully.

real    0m0.202s
user    0m0.080s
sys     0m0.104s
Added user `user3` successfully.

real    0m0.181s
user    0m0.108s
sys     0m0.088s

-- cut here --

Added user `user380` successfully.

real    0m1.784s
user    0m0.116s
sys     0m0.068s
Added user `user381` successfully.

real    0m2.108s
user    0m0.084s
sys     0m0.116s
Added user `user382` successfully.

real    0m1.820s
user    0m0.084s
sys     0m0.112s
Added user `user383` successfully.

real    0m2.105s
user    0m0.076s
sys     0m0.128s
Added user `user384` successfully.

real    0m2.023s
user    0m0.100s
sys     0m0.080s
```

**Comment by harshavardhana** [comment]
Can you create the same tests using etcdctl PUT and see if etcd uses CPU at all? 

If yes then it's expected, continuously creating policies and users on etcd will cause a spike if you are doing a while true run. It is practically unexpected, and this may be a common etcd behavior.

So I don't see why we should reduce the CPU usage of etcd.

**Comment by chrono2002** [comment]
OK, I have tried to run minio distributed without kubernetes on local virtualbox cluster
the first configuration was:
3 etcd instances without https 
1 minio instance
it takes for around 0.3 sec to create user not depending on quantity

then I have changed configuration to look like this:
3 etcd instances without https
4 minio instances in distributed mode
here it takes for about 20 second per user with huge network i/o and etcd cpu load

Enviroment is:
4 two-core virtualboxes, 2gb ram, debian 9
latest minio from master branch
etcd v3.3.12

With test stript I have already provided early, here is the config files I have used:

```
ETCD_NAME=etcd-1
ETCD_HOST_IP=192.168.56.10

etcd \
 --name ${ETCD_NAME} \
 --data-dir /var/lib/etcd \
 --initial-advertise-peer-urls http://${ETCD_HOST_IP}:2380 \
 --listen-peer-urls http://${ETCD_HOST_IP}:2380 \
 --listen-client-urls http://${ETCD_HOST_IP}:2379,http://127.0.0.1:2379 \
 --advertise-client-urls http://${ETCD_HOST_IP}:2379 \
 --initial-cluster-token etcd-cluster-1 \
 --initial-cluster etcd-1=http://192.168.56.10:2380,etcd-2=http://192.168.56.11:2380,etcd-3=http://192.168.56.12:2380 \
 --initial-cluster-state new \
 --heartbeat-interval 1000 \
 --election-timeout 5000
```

```
export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=minio123
#export MINIO_ETCD_ENDPOINTS=http://localhost:2379
export MINIO_ETCD_ENDPOINTS="http://192.168.56.10:2379,http://192.168.56.11:2379,http://192.168.56.12:2379"

mkdir /minio
minio server http://192.168.56.1{0...3}:9000/minio
```

**Comment by chrono2002** [comment]
now I have run a single etcd instance with debugging turned on
minio still in distributed mode
it takes around 1 sec per user, 2 sec per user when user count ~200 etc
still high network and cpu load on etcd node

```
Added user `user77` successfully.

real    0m1.077s
user    0m0.120s
sys     0m0.632s
Added user `user78` successfully.

real    0m1.121s
user    0m0.088s
sys     0m0.660s
Added user `user79` successfully.
```

I have attached the etcd debug log to see what happens if I add 200th user.

[etcd_debug.log](https://github.com/minio/minio/files/3127284/etcd_debug.log)

Looks like every minio instance goes to etcd to fetch all policies on every single policy operation, am I right? Why is that so?

**Comment by harshavardhana** [comment]
Each instance needs to handle each request independently, so each instance loads policies and users as needed.

It is possible for us to filter out appropriately, what we need to reload. Let me think about if there is a better optimal way to do it.

**Comment by chrono2002** [comment]
hi, Harshavardhana
any luck with this?

**Comment by chrono2002** [comment]
> Each instance needs to handle each request independently, so each instance loads policies and users as needed.
> 
> It is possible for us to filter out appropriately, what we need to reload. Let me think about if there is a better optimal way to do it.

hi, Harshavardhana
any luck with this?

**Comment by chrono2002** [comment]
in cmd/admin-handlers.go i see:

```
	if err = globalIAMSys.SetUser(accessKey, uinfo); err != nil {
		writeErrorResponseJSON(ctx, w, toAdminAPIErr(ctx, err), r.URL)
		return
	}

	// Notify all other MinIO peers to reload users
	for _, nerr := range globalNotificationSys.LoadUsers() {
		if nerr.Err != nil {
			logger.GetReqInfo(ctx).SetTags("peerAddress", nerr.Host.String())
			logger.LogIf(ctx, nerr.Err)
		}
	}
```

maybe it's more logical to notify peers FetchOnlySpecificUser(username)?

**Comment by harshavardhana** [comment]
That is not the problem here, the problem is Watch() routine is loading users recursively for all of them

**Comment by harshavardhana** [comment]
I have tried to reproduce this but without luck - I can see that even at 300 users the overall responsiveness is the same and the performance doesn't decrease. 

```
...
...

real	0m0.217s
user	0m0.333s
sys	0m0.104s
Added user `user305` successfully.

real	0m0.201s
user	0m0.258s
sys	0m0.164s
Added user `user306` successfully.

real	0m0.174s
user	0m0.221s
sys	0m0.078s
Added user `user307` successfully.

real	0m0.120s
user	0m0.116s
sys	0m0.127s
Added user `user308` successfully.

real	0m0.121s
user	0m0.123s
sys	0m0.123s
Added user `user309` successfully.

real	0m0.127s
user	0m0.144s
sys	0m0.111s
Added user `user310` successfully.

real	0m0.125s
user	0m0.147s
sys	0m0.109s
Added user `user311` successfully.

real	0m0.133s
user	0m0.223s
sys	0m0.052s
Added user `user312` successfully.

real	0m0.138s
user	0m0.103s
sys	0m0.178s
Added user `user313` successfully.

real	0m0.171s
user	0m0.183s
sys	0m0.164s
Added user `user314` successfully.

real	0m0.182s
user	0m0.271s
sys	0m0.096s
Added user `user315` successfully.

real	0m0.187s
user	0m0.219s
sys	0m0.137s
Added user `user316` successfully.

real	0m0.190s
user	0m0.186s
sys	0m0.186s
Added user `user317` successfully.

real	0m0.203s
user	0m0.252s
sys	0m0.167s
Added user `user318` successfully.

real	0m0.216s
user	0m0.305s
sys	0m0.123s
Added user `user319` successfully.

real	0m0.254s
user	0m0.238s
sys	0m0.176s
Added user `user320` successfully.

real	0m0.128s
user	0m0.147s
sys	0m0.106s
```

**Comment by harshavardhana** [comment]
@eco-minio were you able to reproduce this in your setup?

**Comment by eco-minio** [comment]
Yes I was able to reproduce with just 4 node docker-compose cluster (no etcd, no federation), @kannappanr is reviewing the traces I produced.

**Comment by rbs-cloud** [comment]
Hi Guys,
export MINIO_ETCD_ENDPOINTS="http://192.168.56.10:2379,http://192.168.56.11:2379,http://192.168.56.12:2379"

genarally we are using etcd to store the temporary credentials and i have deployed minio in k8s cluster and i have set the endpoints like ./mc addmin config set minio/ etcd endpoints=http://localhost:2379 or ipaddress and restarted the minio

to store the credentials , setting up the endpoints enough or do we need to any other changes

how can i know the credentials are stored in etcd and how endpoints works
