### ISSUE TITLE
Question - CAP Theorem

### ISSUE THREAD

**Issue by nelsonmarcos** [minio/minio#7589]
Hello,

Reading the docs: "For example, an 8-node distributed MinIO setup with 1 disk per node would continue serving files, even if up to 4 disks are offline. But, you'll need at least 5 disks online to create new objects."

Can I say that, related with the [CAP theorem](https://towardsdatascience.com/cap-theorem-and-distributed-database-management-systems-5c2be977950e), minio offers consistency and partition tolerante(CP) ?

**Comment by harshavardhana** [comment]
MinIO does provide consistency, fault tolerance and also performance.

**Comment by harshavardhana** [comment]
Closing this as answered..
