### ISSUE TITLE
version mismatch not reported when creating cluster

### ISSUE THREAD

**Issue by Gibheer** [minio/minio#7594]
When initializing a new cluster, there are now errors printed when something is wrong, like the server time. But there is no such report, when the version between the nodes doesn't match.

I had this issue when I updated from 2019.03.27.22.35.21 to 2019.04.23.23.50.36. On two nodes, I forgot this step and the cluster waited for nodes and reported missing disks.

With all nodes on the newest version, the cluster came up without problems.

## Expected Behavior
* an error should be printed, when the version doesn't match

## Current Behavior
* just the waiting loop is running and nothing more happens

## Possible Solution
* like with the reporting of mismatching time, report an issue with the version

## Steps to Reproduce (for bugs)
1. install two different versions
2. start the cluster with mismatched versions

## Context
It was an error on my side, but it could be found earlier if minio would report a mismatch in version or any other possible cause of the problem.

## Regression
No

## Your Environment
* Version used (`minio version`): old 2019.03.27.22.35.21, new 35d19a4ae287179a0c7d6938b2b1c8e63b4747c1
* Environment name and version (e.g. nginx 1.9.1): nothing
* Server type and version: nothing
* Operating System and version (`uname -a`): FreeBSD 12.0-RELEASE-p3

Thank you

**Comment by harshavardhana** [comment]
The behavior is expected as they shouldn't connect, additionally we will print an error message about version mismatch.

**Comment by Gibheer** [comment]
Thank you very much :)

**Comment by harshavardhana** [comment]
Closing this as behavior is expected..
