### ISSUE TITLE
Service help description wrong for windows user

### ISSUE THREAD

**Issue by tinohager** [minio/minio#7598]
On Windows `export` not working to set enviorment variable, use `SET` instead.
https://stackoverflow.com/questions/18701783/windows-equivalent-of-export

File to change [server-main.go](https://github.com/minio/minio/blob/091b9b661fe79f992af8167e17b794977f9214cf/cmd/server-main.go)

**Comment by harshavardhana** [comment]
> On Windows `export` not working to set enviorment variable, use `SET` instead.
> https://stackoverflow.com/questions/18701783/windows-equivalent-of-export
> 
> File to change [server-main.go](https://github.com/minio/minio/blob/091b9b661fe79f992af8167e17b794977f9214cf/cmd/server-main.go)

The documentation there is meant for Unix only @tinohager we can automatically change it based on the platform though.

**Comment by tinohager** [comment]
@harshavardhana That's good news, I hope there will be documentation for both systems soon.

**Comment by tinohager** [comment]
👍
