### ISSUE TITLE
GCS gateway: PutObject sometimes errors with NoSuchKey

### ISSUE THREAD

**Issue by adamhooper** [minio/minio#7605]
## Expected Behavior

We upload ~10,000 files per day from 3 Python services to a pair of minio GCS gateways on GKS (Kubernetes). File sizes range from 1kb to 2GB; median is perhaps 100kb. We use `boto3` to upload them (a single TransferManager with long-living connections), but previously we've used `minio-py` as well.

We expect all `PutObject` calls to succeed -- or to _report the correct error message_ if they don't.

## Current Behavior

Once or twice per week, PutObject fails with: `botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the PutObject operation: The specified key does not exist.`

This is certainly the wrong error message. (Nothing differentiates the keys that fail from the keys that upload correctly.)

This happens with `botocore`, and it happened with `minio-py` previously.

After this error, the file exists in Google Storage. I don't know whether it's truncated.

## Possible Solution

I can't reproduce this outside of production. (Perhaps because it's so rare?) But I can suggest why the error message is wrong.

[gateway-gcs.go:PutObject()](https://github.com/minio/minio/blob/c113d4e49c621dd45b1cbc2947c51069255808a1/cmd/gateway/gcs/gateway-gcs.go#L917-L926) seems to ignore error reports from GCS storage writers.

The code looks like this:

```go
	// Close the object writer upon success.
	w.Close()

	attrs, err := object.Attrs(ctx)
	if err != nil {
		logger.LogIf(ctx, err)
		return minio.ObjectInfo{}, gcsToObjectError(err, bucket, key)
	}
```

This ignores an error from [writer.Close()](https://godoc.org/cloud.google.com/go/storage#Writer.Close). Also, it makes an [unnecessary HTTP request](https://godoc.org/cloud.google.com/go/storage#ObjectHandle.Attrs) (`object.Attrs(ctx)`) -- if my reading of the [Writer docs](https://godoc.org/cloud.google.com/go/storage#Writer.Attrs) is correct, `attrs := w.Attrs()` ought to suffice. That extra HTTP request can (and does) throw nonsense exceptions like `NoSuchKey`.

Shouldn't the code be:

```go
	// Close the object writer upon success.
	err = w.Close()
        if err != nil {
		logger.LogIf(ctx, err)
		return minio.ObjectInfo{}, gcsToObjectError(err, bucket, key)
	}

        attrs := w.Attrs()
```

(Ditto for `PutObjectPart()`.)

I'm no expert in Go, S3, Google Storage or minio; but I'd expect this to at least report the correct error message?

## Steps to Reproduce (for bugs)

Unfortunately, I can't reproduce this bug on demand. We just keep running our service, and if the bug doesn't occur for a month I'd assume it's fixed.

## Context

Retry can circumvent the problem. But I'm loath to retry blindly -- I want to see the correct error message first.

## Regression

Is this issue a regression? No.

## Your Environment

* Version used: `minio/minio:RELEASE.2019-04-18T21-44-59Z`
* Environment name and version: `GKS 1.11.8-gke.6`
* Link to your project: https://github.com/CJWorkbench/cjworkbench (`server/minio.py`)

**Comment by adamhooper** [comment]
Whoops -- I forgot to supply the error on the minio side:

```
API: PutObject(bucket=production-stored-objects.workbenchdata.com, object=14018/59177/71edf80a-6b2e-11e9-a70d-0a580a347504.dat)
Time: 09:58:03 UTC 04/30/2019
RequestID: 159A3814E696420F
RemoteHost: 10.52.117.4
UserAgent: Boto3/1.9.134 Python/3.7.2 Linux/4.14.91+ Botocore/1.12.134
Error: storage: object doesn't exist
       1: cmd/gateway/gcs/gateway-gcs.go:922:gcs.(*gcsGateway).PutObject()
       2: cmd/object-handlers.go:1254:cmd.objectAPIHandlers.PutObjectHandler()
       3: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()
```

**Comment by poornas** [comment]
@adamhooper, as you pointed out  the issue is due to not checking whether writer closed successfully before updating metadata attributes. Sending a PR to fix this.

**Comment by adamhooper** [comment]
Awesome! That's so quick! Thank you.

Maybe this is outside the scope of the issue (but maybe not): any thoughts on replacing `object.Attrs()` and associated error handling with `w.Attrs()`, which never errors? I haven't tested, but I'd expect a large speed boost (and cost savings) because it would remove an HTTP request. And it would prevent PutObject from throwing `NoSuchKey` in the event of a race.

**Comment by poornas** [comment]
> Awesome! That's so quick! Thank you.
> 
> Maybe this is outside the scope of the issue (but maybe not): any thoughts on replacing `object.Attrs()` and associated error handling with `w.Attrs()`, which never errors? I haven't tested, but I'd expect a large speed boost (and cost savings) because it would remove an HTTP request. And it would prevent PutObject from throwing `NoSuchKey` in the event of a race.

@adamhooper, that's a great catch - w.Attrs() already returns the metadata which can be used
