### ISSUE TITLE
minio cluster stops responding if a host is down

### ISSUE THREAD

**Issue by JohnKiller** [minio/minio#7618]
I'm experimenting with minio cluster. I've setup a 4 node, 1 disk per node, cluster.

If I kill the minio process on a host, the other 3 continues to work as expected.
However, if I shutdown the node, the cluster becomes unresponsive. The web ui works but lists no file. S3 clients stops getting file listings and after some seconds even the buckets disappears.
Booting up the server again, even without restarting minio, brings the cluster up again. Starting the minio process reattaches itself successfully and the cluster is healthy.

To me it seems like it is waiting for a response on the failed node. If the machine is still up, it responds immediately with a TCP NACK, so the cluster continues to work. But if the node is down, the NACK never arrives and never timeouts.

I've tried to keep the node down for about 10 minutes, but the others never recover.

## Expected Behavior
Cluster works normally on a node failure

## Current Behavior
If the host is completely down (not only the minio process) the cluster stops responding

## Possible Solution
Not sure. Maybe timeout related.

## Steps to Reproduce (for bugs)
1. Boot up 4 VM
2. Start minio in cluster mode, single disk per VM
3. Upload some data. Verify cluster works.
4. Stop the minio process on VM1, without killing the VM itself, just the process
5. Verify that cluster still works and files are still accessible
6. Shutdown the VM1. Cluster becomes unresponsive
7. Start the VM1 again, but don't run minio yet. Cluster become available again
8. Upload another file or make any changes to the bucket
9. Restart the minio process on VM1. Observe the cluster healing and getting the modified files correctly as expected.

## Context
High availability scenario is broken this way.

## Regression
Seems related to #7400

## Your Environment

* Version used (`minio version`): Version: 2019-05-02T19:07:09Z
Release-Tag: RELEASE.2019-05-02T19-07-09Z
Commit-ID: 4b858b562a0887e10bfd0414dc87e68f1af31c3a

* Environment name and version (e.g. nginx 1.9.1): Ubuntu 16.04
* Server type and version: Droplet on DigitalOcean
* Operating System and version (`uname -a`): Linux minio-t1 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by kannappanr** [comment]
@JohnKiller Thanks for filing this issue. We will take a look at this issue.

**Comment by Praveenrajmani** [comment]
@JohnKiller I have got some questions. Can u reach us at slack - https://minio.slack.com/join/shared_invite/enQtNDAzMjM0Njc4OTMzLWVhYTYyZjRlZWQ2YjhkNjAxNmM5MTEyZTZkZTI2NWJlZGUzMDI5ZjkzMDBmNGNkNDZhNGU2MmRjZmEwNGQwNTE

**Comment by JohnKiller** [comment]
Setup is working as expected, it's just an initial delay (about 30 seconds) before the cluster detects that the node is down before accepting new requests again.

Some suggestions are lowering the timeout value (maybe configurable) and marking the node as "failed" and don't try to contact it again on each request until another thread marks it as "online" again.

Thanks for your patience and for the great product.
