### ISSUE TITLE
Bucket name captured incorrectly when using MINIO_DOMAIN

### ISSUE THREAD

**Issue by GreenVine** [minio/minio#7619]
Hi there,

I'm opening this to report a bucket name capture issue with the latest version: `RELEASE.2019-05-02T19-07-09Z`.

I have set my `MINIO_DOMAIN` to `example.com` and have a bucket named `mybucket`. I'd assume that direct access to objects via `mybucket.example.com` is possible. To make the issue more obvious, I have tested my deployment by using an incorrect signature to access the file `testfile.txt`. 

With the aforementioned version:

Request: `https://mybucket.example.com/testfile.txt?X-Amz-Algorithm=SOME_INCORRECT_TOKEN`

```xml
<Error>
  <Code>SignatureDoesNotMatch</Code>
  <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
  <BucketName>testfile.txt</BucketName>
  <Resource>/testfile.txt</Resource>
  <RequestId>159B8B79B91BDB7D</RequestId>
  <HostId>0e9f2dcf-2fc3-418f-b896-49ac3fa3d2e7</HostId>
</Error>
```

Downgrade to `RELEASE.2019-03-27T22-35-21Z` and it works perfectly (the file can also be accessed if supplied with a correct signature):

```xml
<Error>
  <Code>SignatureDoesNotMatch</Code>
  <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
  <Key>testfile.txt</Key>
  <BucketName>mybucket</BucketName>
  <Resource>/testfile.txt</Resource>
  <RequestId>159B8B899D72112E</RequestId>
  <HostId>0e9f2dcf-2fc3-418f-b896-49ac3fa3d2e7</HostId>
</Error>
```

Note that the file name is captured as `BucketName` per the error message. Any ideas on how to resolve it?

Similar issue: https://github.com/minio/minio/issues/7577

**Comment by kannappanr** [comment]
@GreenVine Thanks for filing this issue. We will take a look and fix this issue.

**Comment by kannappanr** [comment]
@GreenVine I tried something like `curl -v http://mybucket.test.com:9000/issue?X-Amz-Algorithm=SOME_INCORRECT_TOKEN` and the response was 

```
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key>issue</Key><BucketName>mybucket</BucketName><Resource>/issue</Resource><RequestId>159BADC44B1D6A6E</RequestId><HostId>6c58c792-b518-4f09-8462-6c0647646d08</HostId></Error>
``` 
This is with the latest master.

**Comment by GreenVine** [comment]
> @GreenVine I tried something like `curl -v http://mybucket.test.com:9000/issue?X-Amz-Algorithm=SOME_INCORRECT_TOKEN` and the response was
> 
> ```
> <Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key>issue</Key><BucketName>mybucket</BucketName><Resource>/issue</Resource><RequestId>159BADC44B1D6A6E</RequestId><HostId>6c58c792-b518-4f09-8462-6c0647646d08</HostId></Error>
> ```
> 
> This is with the latest master.

When you say the latest master, is it newer than `RELEASE.2019-05-02T19-07-09Z`?

**Comment by GreenVine** [comment]
@kannappanr I have also tested with the edge branch, looks like the issue persists. The key problem here is the first path segment is incorrectly treated as `BucketName` when using virtual host style.

@jonhai also reported the same issue in the earlier thread: https://github.com/minio/minio/issues/7577#issuecomment-489545563

**Comment by kannappanr** [comment]
@GreenVine So, the fix we had did not take care of one scenario explained in #7577 . Have sent a fix in that will handle that scenario also.

**Comment by GreenVine** [comment]
Awesome, cheers for your work!
