### ISSUE TITLE
`presignedGetObject` return url cannot use as download url

### ISSUE THREAD

**Issue by belugaliu** [minio/minio#7620]
i'm testing browser use minio-java `presignedGetObject`'s url  to download object. but response header not contains `Content-Disposition`.  so, i can not download object as a local file.
## Expected Behavior
![4fe4e4b0a66a44fdb289a4cafcee6441](https://user-images.githubusercontent.com/24370993/57189772-41455480-6f45-11e9-9b14-91aef7dbadf4.png)

## Current Behavior
![56b8c1f8dae34092a91f93e53af4252b](https://user-images.githubusercontent.com/24370993/57189778-5fab5000-6f45-11e9-8c2b-0010508b0c9d.png)

## Your Environment
* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by nitisht** [comment]
@liuliliGithub please use the issue template to report issues, otherwise it is difficult to reproduce/analyse bug reports. Closing this for now, please reopen once you add the details as per the issue template
