### ISSUE TITLE
Gateway azure got error: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by heavenwing** [minio/minio#7622]
## Expected Behavior
List containers and blobs of Azure storage from Minio Browser

## Current Behavior
I got this error:
API: SYSTEM()
Time: 15:12:22 CST 05/06/2019
Error: [31m[1mGet https://[myaccountname].blob.core.windows.net/?comp=list: x509: certificate signed by unknown authority[0m[0m
       1: cmd\policy.go:101:cmd.(*PolicySys).refresh()
       2: cmd\policy.go:163:cmd.(*PolicySys).Init()

I can't see anything in Minio Browser

## Possible Solution
I have no idea.

## Steps to Reproduce (for bugs)
1. open windows cmd 
2. set MINIO_ACCESS_KEY and MINIO_SECRET_KEY environment variables
3. Run "minio gateway azure"
4. Open http://localhost:9000 in Web Browser 

## Context
I just try gateway mode

## Regression
No

## Your Environment
* Version used (`minio version`):  2019-04-23T23:50:36Z
* Environment name and version (e.g. nginx 1.9.1): N/A
* Server type and version: N/A
* Operating System and version (`uname -a`): Windows 10 1809
* Link to your project: N/A

**Comment by nitisht** [comment]
Thanks for reporting @heavenwing we'll take a look

**Comment by heavenwing** [comment]
I updated latest version (2019-05-02T19:07:09Z), this issue is still here.

**Comment by poornas** [comment]
@heavenwing, It looks like you have a self-signed certificate in use where your certificate authority is not trusted by the azure backend

**Comment by poornas** [comment]
@heavenwing, this link might help you resolve the cert issue - https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors

**Comment by heavenwing** [comment]
@poornas  Thanks for you help. It's working.

However actually I don't use self-signed certificate , Azure Storage Blob use CA's certificate, its issuer is 
CN = Microsoft IT TLS CA 5
OU = Microsoft IT
O = Microsoft Corporation
L = Redmond
S = Washington
C = US
its subject is 
CN = *.blob.core.windows.net

I use OpenSSL get this certificate then copy it into  C:\Users\<Username>\.minio\certs\CAs
and run minio.exe gateway azure again, it's working.

Furthermore, if I run minio gateway azure in Docker , it's working without copying CA's certificate.

**Comment by shaliniGovindaNayak** [comment]
@poornas I did refer the docs to generate a CA certificate -https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=1804#error-self-signed-certificate-in-certificate-chain-and-similar-errors
I use Ubuntu but there is no implementation for Ubuntu in the above docs, could u please help me with that.

**Comment by harshavardhana** [comment]
This issue is addressed please come to https://slack.minio.io @shaliniGovindaNayak
