### ISSUE TITLE
Amazon S3 will no longer support path-style API requests

### ISSUE THREAD

**Issue by shamil** [minio/minio#7628]
https://forums.aws.amazon.com/ann.jspa?annID=6776

How we will able to use official AWS SDK with minio server when `path-style` option will be removed from there?

**Comment by harshavardhana** [comment]
> How we will able to use official AWS SDK with minio server when `path-style` option will be removed from there?

Use MINIO_DOMAIN to set MinIO to support virtual DNS style @shamil https://github.com/minio/minio/tree/master/docs/config#domain
