### ISSUE TITLE
Error running Mino as Windows service with TLS/HTTPS

### ISSUE THREAD

**Issue by labnewbie** [minio/minio#7630]
## Expected Behavior
Minio server should be accessible via HTTPS when run as a service

## Current Behavior
The service starts without any errors:
PS C:\> start-service minio
PS C:\> get-service minio

Status   Name               DisplayName
------   ----               -----------
Running  Minio              minio

But when I try to access the server this is the error:
PS C:\> mc admin service status myminio
mc.exe: <ERROR> Cannot get service status. Get https://192.168.86.133:9000/minio/admin/v1/service: http: server gave HTTP response to HTTPS client.

When I tried to add the https client i get this:
PS C:\> mc.exe config host add myminio https://192.168.86.133:9000 admin passwd
mc.exe: <ERROR> Unable to initialize new config from the provided credentials. Get https://192.168.86.133:9000/probe-bucket-sign-kdsdp4aqfewb/?location=: http: server gave
HTTP response to HTTPS client.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
I need to manually start the Minio server whenever the host vm gets rebooted.
## Your Environment

* Version used (`minio version`):  2019-05-02T19:07:09Z
* Environment name and version (e.g. nginx 1.9.1):  Version: go1.12 
* Server type and version: OS: windows | Arch: amd64
* Operating System and version (`uname -a`): Windows Server 20116
* Using local Admin account to start service
*Used NSSM pre-release 2.24-101-g897c7ad

**Comment by kannappanr** [comment]
@labnewbie I don't think this has got anything to do with `service`. What command did you type when you installed the service. 
The information given in https://github.com/minio/minio-service/tree/master/windows doesn't talk about `https`

**Comment by labnewbie** [comment]
I used NSSM and the command was:

c:\nssm.exe install Minio C:\Minio\minio.exe server C:\Minio\Data
Service "Minio" installed successfully!

When I remove the cert files from the %%USERPROFILE%%.minio\certs folder everything works fine so it definitely https rather than the actual service creation.  The https works fine when I start the Minio server from the cli.  It's only when running as a service.

Thanks for your help and patience.

**Comment by kannappanr** [comment]
@labnewbie I think it might be because you are running `MINIO` as service with probably a different account than what you are running under as when you run it with `cli`. 

Can you try something like this `c:\nssm.exe install Minio C:\Minio\minio.exe server -S C:\tmp\certs C:\Minio\Data` ? Assuming that you have the certs at `c:\tmp\certs`

**Comment by labnewbie** [comment]
I was able to start the service with your -S recommendation and the service started.
C:\Windows\system32>nssm.exe install Minio C:\Minio\minio.exe server -S C:\GnuTLS\win64-build C:\Minio\Data
Service "Minio" installed successfully!

I also am able to execute mc commands and access Minio via the webpage via https.

I will continue testing today.  If everything works I will close this.

I will also update my documentation to include the -S parameter to allow the Minio service to be started in https/tls mode.

Thanks for your help.  As always you rocked!!!!
