### ISSUE TITLE
Can't find some dependencies

### ISSUE THREAD

**Issue by xilipilige** [minio/minio#7631]
cloud.google.com/go v0.37.2
google.golang.org/api v0.3.0
contrib.go.opencensus.io/exporter/ocagent v0.4.10

**Comment by vadmeste** [comment]
@xilipilige can you describe more the issue you are seeing if any and how to reproduce it ?

**Comment by harshavardhana** [comment]
Closing this issue as incomplete for now, feel free to reopen with more reproducible steps.

Thanks
