### ISSUE TITLE
S3 gateway mode does not support bucket to bucket operations with SSE-KMS

### ISSUE THREAD

**Issue by jjsp556** [minio/minio#7636]
When using minio in S3 gateway mode on a S3 bucket that is configured with SSE-KMS default encryption, performing basic cp/mv operations works when performing local to S3 bucket, or S3 bucket to local operations. However, performing S3 bucket to S3 bucket operations does not seem to be supported. I would like to request this functionality. 

Here's an example of a failure when using the aws cli against minio operating in S3 gateway mode using passthrough SSE (MINIO_ACCESS_KEY=secretaccess MINIO_SECRET_KEY=secretkey ./minio gateway s3): 

[user@localhost:] AWS_ACCESS_KEY_ID=secretaccess AWS_SECRET_ACCESS_KEY=secretkey aws s3 mv s3://s3bucket/file1.txt s3://s3bucket/file2.txt --endpoint-url=http://localhost:9000
move failed: s3://s3bucket/file1.txt to s3://s3bucket/file2.txt An error occurred (InvalidArgument) when calling the CopyObject operation: Server Side Encryption with AWS KMS managed key requires HTTP header x-amz-server-side-encryption : aws:kms

Adding --sse aws:kms gives a different error:

[user@localhost:] AWS_ACCESS_KEY_ID=secretaccess AWS_SECRET_ACCESS_KEY=secretkey aws s3 mv s3://s3bucket/file1.txt s3://s3bucket/file2.txt --endpoint-url=http://localhost:9000 --sse aws:kms
move failed:  s3://s3bucket/file1.txt to s3://s3bucket/file2.txt An error occurred (NotImplemented) when calling the CopyObject operation: A header you provided implies functionality that is not implemented

**Comment by harshavardhana** [comment]
We don't support SSE-KMS yet, but we are working on supporting it in future.

**Comment by aead** [comment]
@jjsp556 How were the objects uploaded to AWS? Have you uploaded them directly using SSE-KMS to AWS without using the gateway? b/c if you would have tried to upload the object with SSE-KMS through the gateway the gateway should have returned an error.

**Comment by jjsp556** [comment]
> @jjsp556 How were the objects uploaded to AWS? Have you uploaded them directly using SSE-KMS to AWS without using the gateway? b/c if you would have tried to upload the object with SSE-KMS through the gateway the gateway should have returned an error.

I uploaded file1.txt referenced in the example using the AWS web console, which automatically SSE-KMS encrypted the file since the bucket was configured to encrypt with SSE-KMS by default. In the example I am trying to use the minio gateway to then move the file to another file in the same bucket.

**Comment by kannappanr** [comment]
@jjsp556 `I uploaded file1.txt referenced in the example using the AWS web console, which automatically SSE-KMS encrypted the file since the bucket was configured to encrypt with SSE-KMS by default` 

Makes more sense now. Based on your initial statement, we were a bit confused as to how this could have worked. 

As of now, we do not support `SSE-KMS` in Gateway mode.

**Comment by kannappanr** [comment]
@jjsp556 Closing this as won't fix. please feel free to reach to us if you have other questions
