### ISSUE TITLE
GCS gateway and users

### ISSUE THREAD

**Issue by fgarciacode** [minio/minio#7647]
Hello I have a minio configured as a gateway for GCS, and when I try to execute a admin command to create a user it give me the following error:

mc admin user add mygcs newuser newuser123 getonly
mc.exe: <ERROR> Cannot add new user. The specified method is not allowed against this resource.

There´s a way to do that, or currently there's no support for that.

Thank you.

**Comment by harshavardhana** [comment]
You need to use etcd with gateway as mentioned in the documentation to allow multi-users on Gateway 
 mode @fjgarciamacias https://docs.min.io/docs/minio-multi-user-quickstart-guide.html 

Please join us on https://slack.min.io for these questions - closing this for now.
