### ISSUE TITLE
IAM subsystem failed to load credentials from etcd

### ISSUE THREAD

**Issue by JetChars** [minio/minio#7648]
## Current Behavior

```
$ s3cmd ls
ERROR: S3 error: 403 (InvalidAccessKeyId): The access key ID you provided does not exist in our records.
```

## Steps to Reproduce (for bugs)

1. `ETCDCTL_API=3 etcdctl put config/iam/users/foobar/identity.json '{"accessKey":"IS21DTE8W2BTTF0IJZ1I","secretKey":"5kKNe+cGq7TYn2+4XkLjPV1ravn+WXGoWn9ap2wD","expiration":"1970-01-01T00:00:00Z","status":"enabled"}'
`
2. `s3cmd ls`

## Context

for multiuser environment

## Your Environment

* Version used (`minio version`): RELEASE.2019-05-14T23-57-45Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
This issue is incomplete, please re-open the issue with more details as expected by the issue template. Closing this for now.

**Comment by harshavardhana** [comment]
Re-opening the issue since the details are now available

**Comment by harshavardhana** [comment]
> 1. ETCDCTL_API=3 etcdctl put config/iam/users/foobar/identity.json '{"accessKey":"IS21DTE8W2BTTF0IJZ1I","secretKey":"5kKNe+cGq7TYn2+4XkLjPV1ravn+WXGoWn9ap2wD","expiration":"1970-01-01T00:00:00Z","status":"enabled"}'

You shouldn't create users in this manner @JetChars - we won't support modifying etcd backend entries - you are supposed to be using `mc admin user` - - also please provide the `minio version` that you are using.

**Comment by JetChars** [comment]
can't find any docs about iam subsystem, is it a premature feature?

**Comment by JetChars** [comment]
my mc client seems a bit outdated, didn't support `user` subcommand :(

**Comment by harshavardhana** [comment]
> can't find any docs about iam subsystem, is it a premature feature?

https://docs.min.io/docs/minio-multi-user-quickstart-guide.html - no all docs are updated

> my mc client seems a bit outdated, didn't support `user` subcommand :(

First you should update `mc`

**Comment by JetChars** [comment]
got it, I might have found the cause, `newuser` should be replace with accesskey
```
//  key := "config/iam/users/newuser/identity.json"     
//  prefix := "config/iam/users/"                       
//  v := trim(trim(key, prefix), base(key)) == "newuser"
```

**Comment by harshavardhana** [comment]
> //  key := "config/iam/users/newuser/identity.json"     
> //  prefix := "config/iam/users/"                       
> //  v := trim(trim(key, prefix), base(key)) == "newuser"

yes that too but just use `mc admin user` @JetChars which will automatically do this for you.

**Comment by JetChars** [comment]
It's just a pity that you can't store usernames

**Comment by harshavardhana** [comment]
Unable to understand @JetChars as I explained this is not an issue, modifying etcd directly is not supported.

**Comment by JetChars** [comment]
That's all right. I've confirmed what I want to confirm. Thanks！
