### ISSUE TITLE
Accessing minio via AWS Cpp Sdk. Endpoint connection failure.

### ISSUE THREAD

**Issue by naveenmahadevuni** [minio/minio#7653]
I'm running a local minio server on CentOS. Getting "Unable to connect to endpoint" with CPP SDK. I have used the workaround in issue #5301 given for Python with no success.

## Expected Behavior
1) Access using Aws-Cli works
2) Using boto3 works..
3) Using browser to access the endpoint works. 

## Current Behavior
Connection to endpoint fails reporting "Unable to connect to endpoint".

## Steps to Reproduce (for bugs)
Below is the code used to initialize S3Client.
       Aws::Client::ClientConfiguration config;
        config.endpointOverride = "http://127.0.0.1:9000";
        config.region = "us-east-1";
        config.followRedirects = true;
        Aws::S3::S3Client s3_client(Aws::Auth::AWSCredentials(access_key, secret_key), config,						Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Always);

## Your Environment

* Version used (`minio version`): 
Version: 2019-05-14T23:57:45Z
Release-Tag: RELEASE.2019-05-14T23-57-45Z
Commit-ID: 0022c9d210971c5661849c4b886cba8305b2b4f2

* Operating System and version (`uname -a`): 
Linux mybox 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 7.6.1810

**Comment by naveenmahadevuni** [comment]
Got this working. The S3Client constructor argument "useVirtualAdressing"  is set to true by default. The endpoint url provided in client configuration is not being used when this flag is true. If set to false, the endpoint url provided to be overridden is being used.

**Comment by nitisht** [comment]
Closing this as it is working, feel free to join us on slack for more such questions.
