### ISSUE TITLE
using s3fs bucket/folder nosuchkey

### ISSUE THREAD

**Issue by forestnd** [minio/minio#7655]
Setup a minio cluster, and trying to use s3fs to connect to an bucket and subfolder

This works but as soon as i add data to the bucket/folder and umount and remout it fails

putting s3fs in to debug mode i get 

```
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/folername/</Resource><RequestId>XXXXXXXXXXXXXXX</RequestId><HostId>XXXX</HostId></Error>
```

## Expected Behavior
It would mount and so all files in the folder

## Current Behavior
Fails anf gives above error

## Possible Solution
None i am aware of

## Steps to Reproduce (for bugs)
1. Create minio cluster
2. Create bucket with folder in
3. set up s3fs on different server
4. mount bucket and folder
5. added content to mounted drive
6. umount 
7 remount

## Your Environment
* Version used 
Version: 2019-05-14T23:57:45Z
Release-Tag: RELEASE.2019-05-14T23-57-45Z
Commit-ID: 0022c9d210971c5661849c4b886cba8305b2b4f2

* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
Ubuntu 18.04

**Comment by nitisht** [comment]
@forestnd Can you also enable HTTP TRACE on minio using MINIO_HTTP_TRACE variable and post the http trace seen on minio here?

You can export the env. variable MINIO_HTTP_TRACE=</path/to/logfile> and then look at the log file.

**Comment by forestnd** [comment]
Sure
Minio log

Accept: */*
User-Agent: curl/7.58.0
Connection: close
Host: 10.4.1.71
HEAD /minio/health/ready
[REQUEST ReadinessCheckHandler] [155800630.039972] [2019-05-16 11:31:40 +0000]

<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/minions/</Resource><RequestId>XXXXXXXXXXXXXXXX</RequestId><HostId>XXXXX</HostId></Error>
<?xml version="1.0" encoding="UTF-8"?>

X-Xss-Protection: 1; mode=block
Vary: Origin
Content-Type: application/xml
Accept-Ranges: bytes
Server: Minio/RELEASE.2019-01-10T00-21-20Z (linux; amd64)
X-Minio-Deployment-Id: edadf9d0-5025-49f2-bd1b-a5c8ae447e3a
X-Amz-Request-Id: XXXXXXXXXXXXX
Content-Security-Policy: block-all-mixed-content
404 Not Found
[RESPONSE] [155800629.971138] [2019-05-16 11:31:39 +0000]

<BODY>

Connection: close
X-Amz-Date: 20190516T113140Z
X-Amz-Content-Sha256: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Authorization: AWS4-HMAC-SHA256 Credential=7wgt5E4AXVh6Au6r7w3CCCAM5/20190516/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Accept: */*
User-Agent: s3fs/1.82 (commit hash unknown; GnuTLS(gcrypt))
Host: <bucket>.<server>
GET /minions/
[REQUEST objectAPIHandlers.GetObjectHandler-fm] [155800629.971138] [2019-05-16 11:31:39 +0000]


From the syslog on the server

May 16 11:31:40 00021-2-salt-appliance-1 s3fs[22860]:       HTTP response code 404 was returned, returning ENOENT
May 16 11:31:40 XXXXXXXXXXXXXXXXXX s3fs[22860]: curl.cpp:CheckBucket(2953): Check bucket failed, S3 response: <?xml version="1.0" encoding="UTF-8"?>#012<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/minions/</Resource><RequestId>159F2679941C5308</RequestId><HostId>3L137</HostId></Erro>

**Comment by kannappanr** [comment]
@forestnd Can you please provide the command you used to mount ?

Looking at https://github.com/s3fs-fuse/s3fs-fuse/issues/623 .  I don't think you can mount a bucket and folder.  The only way you can maybe try is to mount as a `root`.

**Comment by forestnd** [comment]
sure
/usr/bin/s3fs -o allow_other -o dbglevel=info -o use_path_request_style -o passwd_file=Password-file -o url=http://s3.server -o use_cache=/tmp bucket:/folder /opt/bucket

I can do this with digitalocean and AWS

**Comment by eco-minio** [comment]
@forestnd we were able to reproduce this, we need to discuss internally whether we can support this.  FYI, this works as expected in fs deployment (single node) if you are able to, you can use that as a workaround for now.

**Comment by harshavardhana** [comment]
> @forestnd we were able to reproduce this, we need to discuss internally whether we can support this. FYI, this works as expected in fs deployment (single node) if you are able to, you can use that as a workaround for now.

@eco-minio can you explain what is not working? and what works in FS mode?

**Comment by eco-minio** [comment]
The behaviour has actually changed since the issue was first reported. 

```localhost [REQUEST s3.PutObject] 21:19:48.393
localhost PUT /test/issue_s3fs
localhost Host: localhost:9000
localhost Expect: 100-continue
localhost X-Amz-Date: 20190815T211948Z
localhost Accept: */*
localhost X-Amz-Meta-Uid: 1000
localhost Content-Length: 26
localhost Content-Type: application/octet-stream
localhost X-Amz-Content-Sha256: 1b0b2351a16accc17a641d39a259a02c570cd5ad1e32d06d29103ae20ee2766a
localhost X-Amz-Meta-Mtime: 1565903988
localhost Authorization: AWS4-HMAC-SHA256 Credential=minio/20190815/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-acl;x-amz-content-sha256;x-amz-date;x-amz-meta-gid;x-amz-meta-mode;x-amz-meta-mtime;x-amz-meta-uid, Signature=b49e7ea3aaf8f3a0b1c3fdfdc2d916e8dd56a4f79601ad831822b8e57176e39e
localhost User-Agent: s3fs/1.82 (commit hash unknown; GnuTLS(gcrypt))
localhost X-Amz-Acl: private
localhost X-Amz-Meta-Gid: 1000
localhost X-Amz-Meta-Mode: 33188
localhost <BODY>
localhost [RESPONSE] [21:19:48.406] [ Duration 12.437ms  🠉 203 B  🠋 261 B ]
localhost 200 OK
localhost X-Xss-Protection: 1; mode=block
localhost Accept-Ranges: bytes
localhost Content-Length: 0
localhost Content-Security-Policy: block-all-mixed-content
localhost ETag: "b1f082aef82076503198c1d97458c331-1"
localhost Server: MinIO/RELEASE.2019-08-14T20-37-41Z
localhost Vary: Origin
localhost X-Amz-Request-Id: 15BB35618492EBC5
localhost <BODY>
```
The issue here is that initially, it adds headers to define filesystem attributes (X-Amz-Meta-*)
After remount, these headers were not being sent.  However testing with latest build they are now present:

```
localhost [REQUEST s3.PutObject] 21:25:20.434
localhost PUT /test/issue_s3fs.after_remount
localhost Host: localhost:9000
localhost Authorization: AWS4-HMAC-SHA256 Credential=minio/20190815/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-acl;x-amz-content-sha256;x-amz-date;x-amz-meta-gid;x-amz-meta-mode;x-amz-meta-mtime;x-amz-meta-uid, Signature=8875eb7ddc7dc17528803f6f63c2b3bbe003bbe959cd8e7b9610c8df4444ff6e
localhost Content-Length: 0
localhost Content-Type: application/octet-stream
localhost User-Agent: s3fs/1.82 (commit hash unknown; GnuTLS(gcrypt))
localhost X-Amz-Acl: private
localhost X-Amz-Meta-Gid: 1000
localhost X-Amz-Meta-Mode: 33188
localhost X-Amz-Meta-Uid: 1000
localhost Accept: */*
localhost X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost X-Amz-Date: 20190815T212520Z
localhost X-Amz-Meta-Mtime: 1565904320
localhost <BODY>
localhost [RESPONSE] [21:25:20.440] [ Duration 6.148ms  🠉 170 B  🠋 261 B ]
localhost 200 OK
localhost Accept-Ranges: bytes
localhost Content-Length: 0
localhost Content-Security-Policy: block-all-mixed-content
localhost ETag: "af1a088ac93bedbce71d64120e66e85d-1"
localhost Server: MinIO/RELEASE.2019-08-14T20-37-41Z
localhost Vary: Origin
localhost X-Amz-Request-Id: 15BB35AED3B63242
localhost X-Xss-Protection: 1; mode=block
localhost <BODY>
```
This would result in the object having root permissions (since no gid was set), timestamp of epoch, etc, basically no filesystem data associated to it.  I went back and tested with the version of MinIO this was first reported with and it is not being reproduced:

![image](https://user-images.githubusercontent.com/41090896/63129478-79a8f580-bf6c-11e9-96bf-11b2947c5b48.png)

So possibly something changed in s3fs from the time this was reported.  @forestnd can you confirm if this is still happening for you?

**Comment by kannappanr** [comment]
Closing this as fixed based on the above comment. please test it against the latest version of MinIO.
