### ISSUE TITLE
Bad status in distributed cluster when nodes are restarted

### ISSUE THREAD

**Issue by zieg8301** [minio/minio#7659]
This seems to be related to the fix for #6995 It seems now that when a minio node is restarted while other nodes in the cluster are offline, the node will start, and participate in the cluster, but the status appears as offline, and it will not serve requests.

## Expected Behavior
After #7452 when a minio node gets restarted in a distributed setup, expect the node to start and join the cluster, even if other nodes are still offline.

## Current Behavior
When a node gets restarted in a distributed setup, while other nodes in the cluster are offline, the node will start and appears to the other nodes to be running, but itself returns a status of:
```Error : Server not initialized, please try again```

Remaining online nodes seem to think the affected node is online and participating, and will service writes as long as at least four nodes are online, and the docker container remains running. In this state, the container continuously logs:
```API: SYSTEM()
Time: 18:38:57 UTC 05/16/2019
Error: Storage resources are insufficient for the read operation.
       5: cmd/config-common.go:43:cmd.readConfig()
       4: cmd/iam.go:681:cmd.reloadUsers()
       3: cmd/iam.go:774:cmd.(*IAMSys).refresh()
       2: cmd/iam.go:136:cmd.(*IAMSys).Init()
       1: cmd/server-main.go:349:cmd.serverMain()
Waiting for IAM subsystem to be initialized..
```

Once the remaining offline nodes all come online, the cluster will return to normal, and the affected node will appear as online.

## Possible Solution
I think the issue described in #6995 may be partially fixed, in that the cluster will serve requests as long as the number of nodes 'Online' plus the number of nodes in 'Error : Server not initialized, please try again' equal at least four. 

Perhaps there is simply a bug with how the node is presenting its status to the cluster?

## Steps to Reproduce (for bugs)
1. Deploy minio distributed cluster with > 4 nodes
2. Disable/offline at least 1 of those nodes. Leave node offline.
3. Restart at least 1 of the surviving nodes. (it will stay in `Server not initialized`)
4. Start the nodes disabled in step 2. This will cause all nodes to return to normal status and no further action is needed to recover.

A more detailed example of this process can be found at: https://gist.github.com/zieg8301/c77bf8ed094d08ac6591720c6fc27f86

## Context
The issue causes a problem when trying to run `admin` commands (and occasional problems with s3 operations) against the cluster. We use a distributed setup in kubernetes, and when a minio node is in this status, the containing pod will show as 'Ready', therefore kubernetes will try to route traffic to it, but it will not accept those requests:

```<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioServerNotInitialized</Code><Message>Server not initialized, please try again.</Message><Resource>/</Resource><RequestId>159F3EADC4049E41</RequestId><HostId>b3280fe6-9f67-4b60-93db-7e9979bb10e4</HostId></Error>```

## Regression
No

## Your Environment
Minio version: 2019-05-02T19:07:09Z
Kubernetes version: v1.9.3
Setup: 6 minio pod distributed cluster

**Comment by harshavardhana** [comment]
Can this tested with the latest release @zieg8301 ?

**Comment by zieg8301** [comment]
That appears to have addressed my issue. Closing the issue. Thanks @harshavardhana !

**Comment by Charlesdjy** [comment]
@zieg8301 How did you solve this problem?

**Comment by zieg8301** [comment]
I switched from the 2019-05-02 release to the 2019-05-23 release.

**Comment by zieg8301** [comment]
@Charlesdjy I switched from the 2019-05-02 release to the 2019-05-23 release.
