### ISSUE TITLE
Waiting for configuration to be initialized..

### ISSUE THREAD

**Issue by cocodee** [minio/minio#7660]
I just use docker to start a minio server that uses 4 disks.The command is 
docker run -p 9000:9000 \
  -v /Users/kdi/workspace/test/data1:/data1 \
  -v /Users/kdi/workspace/test/data2:/data2 \
  -v /Users/kdi/workspace/test/data3:/data3 \
  -v /Users/kdi/workspace/test/data4:/data4 \
 -v /Users/kdi/workspace/test/config:/root/.minio \
  -e "MINIO_ACCESS_KEY=kditest" -e "MINIO_SECRET_KEY=kditest123" \
  minio/minio server /data{1...4}
and the server is stucked with below log:
Waiting for configuration to be initialized..
Waiting for configuration to be initialized..
Waiting for configuration to be initialized..
Waiting for configuration to be initialized..
Waiting for configuration to be initialized..
Waiting for configuration to be initialized..
Waiting for configuration to be initialized..
Waiting for configuration to be initialized..
Waiting for configuration to be initialized..
Waiting for configuration to be initialized..
Waiting for configuration to be initialized..
Waiting for configuration to be initialized..
Waiting for configuration to be initialized..
Waiting for configuration to be initialized..
Waiting for configuration to be initialized..

## Expected Behavior

The server should start successfully.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
> minio/minio server /data{1...4}
> and the server is stucked with below log:
> Waiting for configuration to be initialized..
> Waiting for configuration to be initialized..
> Waiting for configuration to be initialized..
> Waiting for configuration to be initialized..
> Waiting for configuration to be initialized..
> Waiting for configuration to be initialized..
> Waiting for configuration to be initialized..
> Waiting for configuration to be initialized..
> Waiting for configuration to be initialized..
> Waiting for configuration to be initialized..
> Waiting for configuration to be initialized..
> Waiting for configuration to be initialized..
> Waiting for configuration to be initialized..
> Waiting for configuration to be initialized..
> Waiting for configuration to be initialized..

It looks like you don't have write access to your drives @cocodee

**Comment by kannappanr** [comment]
@cocodee Closing this based on the previous comment. Please feel free to re-open the issue if you feel otherwise.

**Comment by mrceresa** [comment]
Hi! 
I have the same problem, with the default helm chart, distributed mode and 4 replicas. All the pods starts but they are stuck with
"Waiting for configuration to be initialized.."

I think the pod have write permissions because all the PVs contain:
.minio.sys
.minio.sys/multipart
.minio.sys/config/config.json/xl.json
.minio.sys/format.json

with the exception of the one for s3-minio-1, which is missing the config dir:
.minio.sys
.minio.sys/multipart
.minio.sys/format.json

I imagine that this is what is missing but I cannot understand why it is happening. Is there an option to make it more verbose?

Thanks and regards,

Mario
