### ISSUE TITLE
NGINX times out when reverse proxying to MinIO

### ISSUE THREAD

**Issue by danielgrant** [minio/minio#7661]
Following on from the conversation in #7577, I've upgraded to `RELEASE.2019-05-14T23-57-45Z` from `RELEASE.2019-04-23T23-50-36Z` (I can't test if this issue is present in `RELEASE.2019-05-02T19-07-09Z` due to the issue described in #7577). I currently use MinIO as a target for my Synology NAS's Hyper Backup process. However, I can replicate this issue using any S3 compliant tool (the examples below were generated using Cyberduck CLI).

Since upgrading to `RELEASE.2019-05-14T23-57-45Z`, my NGINX reverse proxy almost always times out when servicing connections to MinIO. If I remove the reverse proxy and connect directly to MinIO, the issue disappears. So this is a problem with how NGINX communicates with MinIO that was introduced in either `RELEASE.2019-05-02T19-07-09Z` or `RELEASE.2019-05-14T23-57-45Z`. There is nothing obvious in the changelogs that would indicate what might be causing this.

I've enabled `MINIO_HTTP_TRACE` and from looking at the logs, it appears that MinIO is servicing the request from NGINX, but from what I can tell something is then causing NGINX to hang, which eventually causes the client to time out.

If I roll back to `RELEASE.2019-04-23T23-50-36Z`, the issue immediately disappears.

I have grabbed some HTTP trace from both versions `RELEASE.2019-04-23T23-50-36Z` and `RELEASE.2019-05-14T23-57-45Z`.

`RELEASE.2019-04-23T23-50-36Z`:

```
[REQUEST objectAPIHandlers.ListBucketsHandler-fm] [155808156.579301] [2019-05-17 09:26:05 +0100]
GET /
Host: <REDACTED>
X-Forwarded-Proto: https
Date: Fri, 17 May 2019 08:26:05 GMT
X-Amz-Content-Sha256: <REDACTED>
Authorization: <REDACTED>
X-Real-Ip: <REDACTED>
X-Forwarded-For: <REDACTED>
Connection: close
X-Amz-Date: 20190517T082605Z
User-Agent: Cyberduck/6.9.4.30164 (Linux/5.0.10-300.fc30.x86_64) (amd64)


[RESPONSE] [155808156.579301] [2019-05-17 09:26:05 +0100]
200 OK
X-Minio-Deployment-Id: <REDACTED>
Server: MinIO/RELEASE.2019-04-23T23-50-36Z
Accept-Ranges: bytes
Content-Type: application/xml
Vary: Origin
X-Xss-Protection: 1; mode=block
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 159F6AEDD42B5EE3

<?xml version="1.0" encoding="UTF-8"?>
<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><ID>REDACTED</ID><DisplayName></DisplayName></Owner><Buckets><Bucket><Name>REDACTED</Name><CreationDate>2018-09-10T22:12:34.542Z</CreationDate></Bucket></Buckets></ListAllMyBucketsResult>
```

`RELEASE.2019-05-14T23-57-45Z`:

```
[REQUEST objectAPIHandlers.ListBucketsHandler-fm] [155808145.606926] [2019-05-17 09:24:16 +0100]
GET /
Host: <REDACTED>
X-Amz-Date: 20190517T082415Z
Authorization: <REDACTED>
X-Real-Ip: <REDACTED>
X-Forwarded-Proto: https
X-Amz-Content-Sha256: <REDACTED>
Date: Fri, 17 May 2019 08:24:15 GMT
User-Agent: Cyberduck/6.9.4.30164 (Linux/5.0.10-300.fc30.x86_64) (amd64)
X-Forwarded-For: <REDACTED>
Connection: close


[RESPONSE] [155808145.606926] [2019-05-17 09:24:16 +0100]
200 OK
X-Minio-Deployment-Id: <REDACTED>
Server: MinIO/RELEASE.2019-05-14T23-57-45Z
Accept-Ranges: bytes
Content-Type: application/xml
Vary: Origin
X-Xss-Protection: 1; mode=block
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 159F6AD4481F1B09

<?xml version="1.0" encoding="UTF-8"?>
<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><ID>REDACTED</ID><DisplayName></DisplayName></Owner><Buckets><Bucket><Name>REDACTED</Name><CreationDate>2018-09-10T22:12:34.542Z</CreationDate></Bucket></Buckets></ListAllMyBucketsResult>
```

For all intents and purposes the requests / responses between the two versions appear to be identical.

I appreciate that the apparently faulty component here is NGINX, however this was working (and has worked since I deployed this last year) up to and include `RELEASE.2019-04-23T23-50-36Z`. So something must have changed on the MinIO side to cause NGINX to start acting up.

## Expected Behavior
NGINX should be able to communicate with MinIO without timing out.

## Current Behavior
NGINX almost always times out when communicating with MinIO. Occasionally (usually after I restart NGINX), a single connection (e.g. to list buckets) will succeed. All subsequent requests then continue to time out.

## Possible Solution
None.

## Steps to Reproduce (for bugs)
1. Configure NGINX to reverse proxy to MinIO
2. Execute a request to NGINX to list buckets
3. Observe that the client times out

## Regression
Yes. Wasn't present in `RELEASE.2019-04-23T23-50-36Z`, is definitely present in  `RELEASE.2019-05-14T23-57-45Z`, may be present to `RELEASE.2019-05-02T19-07-09Z`.

## Your Environment
- OS: Ubuntu 18.04 LTS, fully patched
- MinIO version: `2019-05-14T23:57:45Z`
- NGINX version: `1.14.0-0ubuntu1.2`

MinIO config (i.e. `/etc/default/minio`):

```
MINIO_VOLUMES="/mnt/minio_data/"
MINIO_OPTS="-C /etc/minio --address ':9000'"
MINIO_DOMAIN=<REDACTED>
MINIO_HTTP_TRACE=/var/log/minio/http.log
```

NGINX configs:

`/etc/nginx/nginx.conf`:

```
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
}

http {
        client_max_body_size 1000m;
        proxy_buffering off;

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	gzip on;

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}
```

`/etc/nginx/site-available/minio`

```
server {
    listen 80;
    listen [::]:80;

    server_name <REDACTED>;

    access_log /var/log/nginx/<REDACTED>.log;

    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name <REDACTED>;

    access_log /var/log/nginx/<REDACTED>.log;

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://127.0.0.1:9000;
    }

    ssl_certificate /etc/letsencrypt/live/<REDACTED>/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<REDACTED>/privkey.pem;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;

    ssl_protocols TLSv1.2;
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
    ssl_prefer_server_ciphers on;

    add_header Strict-Transport-Security max-age=15768000;

    ssl_stapling on;
    ssl_stapling_verify on;
}
```

Note that I have also removed the `return 301` and replaced it with the same `location /` block to enable reverse proxy on port 80 too, and the same behaviour is exhibited, so as far as I can tell this isn't an issue related to NGINX being served over SSL.

**Comment by danielgrant** [comment]
To follow up, I'm only seeing this behaviour when executing requests through the S3 API. I can still access and navigate the MinIO Browser without any problems (which obviously is also served through NGINX).

**Comment by nitisht** [comment]
Thanks @danielgrant we'll take a look

**Comment by danielgrant** [comment]
Hi @nitisht,

I have used `pcap` to observe the network traffic between NGINX and MinIO and have found a bit of an anomaly.

The connection from my client to NGINX is HTTP/1.1, as shown by this extract from the NGINX access log:

```
<REDACTED> - - [17/May/2019:11:05:17 +0100] "GET / HTTP/1.1" 200 387 "-" "Cyberduck/6.9.4.30164 (Linux/5.0.10-300.fc30.x86_64) (amd64)"
```

However, the `pcap` trace shows that the communication between NGINX and MinIO is going over HTTP/1.0:

![image](https://user-images.githubusercontent.com/1282690/57921066-66ff2180-7894-11e9-8e28-ecf844792bdc.png)

If I update my NGINX configuration to force the reverse proxy to speak to MinIO using HTTP/1.1, i.e.

```
location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_pass http://127.0.0.1:9000;
    }
```

It works! It appears that NGINX and MinIO are trying to communicate over HTTP/1.0 and I suspect that is causing the connection to hang and never complete, resulting in an eventual timeout in the client.

**Comment by nitisht** [comment]
Thanks for the debugging @danielgrant . Looks like Nginx uses Http 1.0 by default (http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_http_version), let me check if can fix our Nginx documentation or check for http 1.0 compatibility on the server

**Comment by danielgrant** [comment]
@nitisht the fact that NGINX uses HTTP/1.0 by default is obviously relevant however, the problem is that MinIO previously worked fine under HTTP/1.0 for version `RELEASE.2019-04-23T23-50-36Z` and before, and then stopped working from either version `RELEASE.2019-05-02T19-07-09Z` or `RELEASE.2019-05-14T23-57-45Z`. I can still roll back to `RELEASE.2019-04-23T23-50-36Z` with NGINX using HTTP/1.0 and the issue goes away.

So whilst I appreciate that it may appear that it may appear that NGINX is the problem here, something must have changed recently in MinIO to break HTTP/1.0 compatibility. I'm at a loss as to what that was though, since there's no obvious in the changelogs.

**Comment by ParitoshBh** [comment]
I was bitten by this bug as well but in my case request wasn't timing out entirely. They were taking far longer than usual.

**Comment by danielgrant** [comment]
I'm timing out after 30 seconds, which I believe is the default timeout for NGINX workers in a reverse proxy configuration (unless configured otherwise, which I haven't).

**Comment by harshavardhana** [comment]
We didn't expect that deprecating HTTP 1.0 would cause issues. We can bring it back but there are no good reasons, if the nginx config fixes it - we can update our docs properly.

It's rather unusual to choose HTTP 1.0 to communicate to backend for handshake.

We will have to test with traefik, haproxy @nitisht and see what they do for initial handshake.

**Comment by danielgrant** [comment]
> We didn't expect that deprecating HTTP 1.0 would cause issues.

Are you saying that support for HTTP/1.0 has been **intentionally** removed at some point in the last two versions?

Because if it was _deprecated_, I would still expect it to be function for now with perhaps warnings in the MinIO logs or at least something in the changelog forewarning that HTTP/1.0 will stop working at some point in the determinate future.

Instead, it looks like support has been removed entirely with no notification of that made anywhere. Frustrating, I've spent hours trying to get to the bottom of this before I realised what the problem was...

> It's rather unusual to choose HTTP 1.0 to communicate to backend for handshake.

Just to be clear - it appears that HTTP/1.0 is the **default** in NGINX, so this is likely going to affect everyone who uses NGINX as a reverse proxy and possibly other reverse proxies too.

**Comment by harshavardhana** [comment]
I think the deprecation happened when we migrated to Go 1.12, we didn't do anything explicitly though. 

Will need to check why that would be the case here.

**Comment by harshavardhana** [comment]
From whatever I can see HTTP 1.0 is still honored, so it is an issue with nginx interaction here which seems to have changed. 

```
~ curl -v --http1.0 http://localhost:9000
* Rebuilt URL to: http://localhost:9000/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9000 (#0)
> GET / HTTP/1.0
> Host: localhost:9000
> User-Agent: curl/7.58.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 403 Forbidden
< Accept-Ranges: bytes
< Content-Security-Policy: block-all-mixed-content
< Content-Type: application/xml
< Server: MinIO/DEVELOPMENT.2019-05-17T20-21-50Z
< Vary: Origin
< X-Amz-Request-Id: 159F9208011DD2FE
< X-Minio-Deployment-Id: 7564a643-0505-4c84-87fc-5095d5389967
< X-Xss-Protection: 1; mode=block
< Date: Fri, 17 May 2019 20:22:39 GMT
< 
<?xml version="1.0" encoding="UTF-8"?>
* Closing connection 0
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Resource>/</Resource><RequestId>159F9208011DD2FE</RequestId><HostId>7564a643-0505-4c84-87fc-5095d5389967</HostId></Error>
```

**Comment by danielgrant** [comment]
@harshavardhana when I execute

```
curl -v --http1.0 http://<REDACTED>:9000
```

against my MinIO server (hitting MinIO directly and bypassing NGINX), I see the exact same behaviour as detailed in this issue - the response just hangs. MinIO seems to honour it, but the request never completes (or, some have reported it eventually completed a significant amount of time later).

FWIW I'm using the `linux-amd64` release of `RELEASE.2019-05-14T23-57-45Z`. I note the release in your `Server` header is showing a different version?

**Comment by harshavardhana** [comment]
> FWIW I'm using the `linux-amd64` release of `RELEASE.2019-05-14T23-57-45Z`. I note the release in your `Server` header is different.

That's just the master that I compiled locally @danielgrant - let me check with the released binary as well. 

And here is the results from the released binary

```
curl -v --http1.0 http://localhost:9000
* Rebuilt URL to: http://localhost:9000/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9000 (#0)
> GET / HTTP/1.0
> Host: localhost:9000
> User-Agent: curl/7.58.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 403 Forbidden
< Accept-Ranges: bytes
< Content-Security-Policy: block-all-mixed-content
< Content-Type: application/xml
< Server: MinIO/RELEASE.2019-05-14T23-57-45Z
< Vary: Origin
< X-Amz-Request-Id: 159F9300D758F545
< X-Minio-Deployment-Id: 7564a643-0505-4c84-87fc-5095d5389967
< X-Xss-Protection: 1; mode=block
< Date: Fri, 17 May 2019 20:40:27 GMT
< 
<?xml version="1.0" encoding="UTF-8"?>
* Closing connection 0
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Resource>/</Resource><RequestId>159F9300D758F545</RequestId><HostId>7564a643-0505-4c84-87fc-5095d5389967</HostId></Error>
```

Can you provide the output of `curl` for whatever you might get?

**Comment by danielgrant** [comment]
My `curl` output:

```
$ curl -v --http1.0 http://<REDACTED>:9000
* Rebuilt URL to: http://<REDACTED>:9000/
*   Trying <REDACTED>...
* TCP_NODELAY set
* Connected to <REDACTED> (<REDACTED>) port 9000 (#0)
> GET / HTTP/1.0
> Host: <REDACTED>:9000
> User-Agent: curl/7.54.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 403 Forbidden
< Accept-Ranges: bytes
< Content-Security-Policy: block-all-mixed-content
< Content-Type: application/xml
< Server: MinIO/RELEASE.2019-05-14T23-57-45Z
< Vary: Origin
< X-Amz-Request-Id: 159F931C562AE3BE
< X-Minio-Deployment-Id: <REDACTED>
< X-Xss-Protection: 1; mode=block
< Date: Fri, 17 May 2019 20:42:26 GMT
< 
<?xml version="1.0" encoding="UTF-8"?>
```

and that's as far as it gets. The request never completes (or, it hasn't completed yet at the time of writing).

**Comment by harshavardhana** [comment]
Do you have go 1.12 installed? - I may send testable HTTP server without MinIO this would help us narrow down if its a Go only problem on your end?

**Comment by danielgrant** [comment]
I don't have any version of Go installed (I don't think MinIO requires an OS installation of Go to run) on my server currently, but I can if that helps with testing / debugging...

**Comment by harshavardhana** [comment]
This just for debugging it looks like there is some issue at environment level here and is behaving differently. 

Would you mind joining our https://slack.min.io it will help move things faster

**Comment by jtackaberry** [comment]
I have a docker registry using the S3 backend pointing at minio and I'm experiencing this issue upgrading from RELEASE.2019-04-23T23-50-36Z, which works fine, to RELEASE.2019-05-02T19-07-09Z, wherein queries issued from the docker registry to minio stall.

**Comment by harshavardhana** [comment]
Can you use the workaround mentioned here @jtackaberry ? We haven't been able to reproduce this on our end.

Can you give latest release a try ?

**Comment by jtackaberry** [comment]
@harshavardhana, yes, I'm afraid I was a bit hasty in my earlier comment.  I should have more thoroughly read this exchange. :)

One rather relevant detail I forgot to mention is that the registry hits minio via an nginx reverse proxy.

Adding `proxy_http_version 1.1` to the nginx configuration does indeed resolve the issue.  The behavior is the same between RELEASE.2019-05-02T19-07-09Z and the latest version -- in both cases, the queries stall with HTTP 1.0.

And the root cause of this looks to be that minio is not closing the socket after the HTTP response, even though the request is issued with `Connection: close`.  So the timeouts make sense, because the requester is waiting for more data.  This behavior is different with RELEASE.2019-04-23T23-50-36Z where the socket *is* closed after each `Connection: close` request.

With `proxy_http_version 1.1`, nginx is still issuing `Connection: close` and minio is closing the connection after the request.

**Comment by harshavardhana** [comment]
All we did was migrate to Go 1.12 in those releases, this may look like a regression of sorts. We will investigate further.

**Comment by harshavardhana** [comment]
> And the root cause of this looks to be that minio is not closing the socket after the HTTP response, even though the request is issued with `Connection: close`. So the timeouts make sense, because the requester is waiting for more data. This behavior is different with RELEASE.2019-04-23T23-50-36Z where the socket _is_ closed after each `Connection: close` request.

I seem to have not been able to reproduce this issue

```
~ nginx -v
nginx version: nginx/1.15.9 (Ubuntu)
```


```
[REQUEST objectAPIHandlers.GetObjectHandler-fm] [155902052.113295] [2019-05-27 22:15:21 -0700]
GET /config/config.toml
Host: localhost
Connection: close
User-Agent: Minio (linux; amd64) minio-go/v6.0.22 mc/2019-05-23T22:18:05Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20190528/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=bea6e5e7d1f83ae26e5f9c0f05d0be362ade60f9dac775d747e335f2f8606de7
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190528T051521Z

<BODY>

[RESPONSE] [155902052.113295] [2019-05-27 22:15:21 -0700]
200 OK
Content-Type: application/octet-stream
Content-Length: 603
Vary: Origin
X-Xss-Protection: 1; mode=block
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 15A2C0E767AA0871
Last-Modified: Mon, 25 Mar 2019 07:32:45 GMT
ETag: "45b5f47afdc2d2d12d7aeab887b1e7c1-1"
Server: MinIO/DEVELOPMENT.2019-05-28T03-14-47Z
Accept-Ranges: bytes

<BODY>
```

```
[REQUEST objectAPIHandlers.HeadObjectHandler-fm] [155902061.785318] [2019-05-27 22:16:57 -0700]
HEAD /config/config.toml
Host: localhost
Connection: close
User-Agent: Minio (linux; amd64) minio-go/v6.0.22 mc/2019-05-23T22:18:05Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20190528/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=6b263e88645401de897b6592ae4f96d0540742c082a08912b43cd45849d3961e
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190528T051657Z


[RESPONSE] [155902061.785318] [2019-05-27 22:16:57 -0700]
200 OK
Accept-Ranges: bytes
Last-Modified: Mon, 25 Mar 2019 07:32:45 GMT
ETag: "45b5f47afdc2d2d12d7aeab887b1e7c1-1"
Content-Type: application/octet-stream
Content-Length: 603
Vary: Origin
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 15A2C0FDECA3E4F7
Server: MinIO/DEVELOPMENT.2019-05-28T03-14-47Z
X-Xss-Protection: 1; mode=block
```

**Comment by harshavardhana** [comment]
My Nginx config is 

```
~ cat /etc/nginx/sites-enabled/minio 
server {
 listen 80;
 server_name example.com;
 # To allow special characters in headers
 ignore_invalid_headers off;
 # Allow any size file to be uploaded.  
 # Set to a value such as 1000m; to restrict file size to a specific value
 client_max_body_size 0;
 # To disable buffering
 proxy_buffering off;
 location / {
   proxy_set_header Host $http_host;
   proxy_pass http://localhost:9000;
 }
}
```

**Comment by harshavardhana** [comment]
> And the root cause of this looks to be that minio is not closing the socket after the HTTP response, even though the request is issued with `Connection: close`. So the timeouts make sense, because the requester is waiting for more data. This behavior is different with RELEASE.2019-04-23T23-50-36Z where the socket _is_ closed after each `Connection: close` request.

Also `Connection: close` header itself is implicit in HTTP 1.0, so not sure what seems to have changed. At this moment, I have hit a road block - Is there anyone who can help us debug this issue further? we would love to talk to them over at https://slack.min.io whenever your time permits.

**Comment by harshavardhana** [comment]
If there is no help available to reproduce the issue further, we should perhaps go ahead and close the issue and update the docs to reflect the requirement of requirement of http 1.1. It maybe an nginx version issue.

**Comment by danielgrant** [comment]
@harshavardhana as above, I was able to replicate this using only `curl` directly against the HTTP endpoint for MinIO by forcing `curl` to use `HTTP/1.0`, so it's not an NGINX issue.

**Comment by JohnNiang** [comment]
> My `curl` output:
> 
> ```
> $ curl -v --http1.0 http://<REDACTED>:9000
> * Rebuilt URL to: http://<REDACTED>:9000/
> *   Trying <REDACTED>...
> * TCP_NODELAY set
> * Connected to <REDACTED> (<REDACTED>) port 9000 (#0)
> > GET / HTTP/1.0
> > Host: <REDACTED>:9000
> > User-Agent: curl/7.54.0
> > Accept: */*
> > 
> * HTTP 1.0, assume close after body
> < HTTP/1.0 403 Forbidden
> < Accept-Ranges: bytes
> < Content-Security-Policy: block-all-mixed-content
> < Content-Type: application/xml
> < Server: MinIO/RELEASE.2019-05-14T23-57-45Z
> < Vary: Origin
> < X-Amz-Request-Id: 159F931C562AE3BE
> < X-Minio-Deployment-Id: <REDACTED>
> < X-Xss-Protection: 1; mode=block
> < Date: Fri, 17 May 2019 20:42:26 GMT
> < 
> <?xml version="1.0" encoding="UTF-8"?>
> ```
> 
> and that's as far as it gets. The request never completes (or, it hasn't completed yet at the time of writing).

Same issue. It will get stuck in here.

**Comment by harshavardhana** [comment]
Even with curl I am not able to reproduce @danielgrant so there is nothing actionable right now, we are just gonna add 1.1 as recommended for the reverse proxies for now.

**Comment by krishnasrinivas** [comment]
Can you guys verify with this build:
https://krishna-downloads.s3.dualstack.us-east-1.amazonaws.com/public/minio 

We set `Content-Length` explicitly and it seemed to fix the issue with curl. Can you please let us know if it fixes the issue with nginx too?

**Comment by harshavardhana** [comment]
@krishnasrinivas can you send the PR anyways since we know the fix?
