### ISSUE TITLE
Possible ZFS write issue

### ISSUE THREAD

**Issue by stokowski** [minio/minio#7662]
Cannot put new objects to minio - using zfs.

Trace from Minio:

```
Error: Write failed. Insufficient number of disks online
       7: cmd/erasure-encode.go:100:cmd.(*Erasure).Encode()
       6: cmd/xl-v1-object.go:622:cmd.xlObjects.putObject()
       5: cmd/xl-v1-object.go:513:cmd.xlObjects.PutObject()
       4: cmd/xl-sets.go:612:cmd.(*xlSets).PutObject()
       3: cmd/object-handlers.go:1257:cmd.objectAPIHandlers.PutObjectHandler()
       2: pkg/handlers/http-tracer.go:144:handlers.TraceReqHandlerFunc.func1()
       1: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()

```

## Possible Solution
Legacy support for fs without O_DIRECT. O_DIRECT will be supported in ZoL 0.8.x

## Steps to Reproduce (for bugs)
1. start not working release
2. mc cp to minio

## Context
Can't put new objects.

## Regression
Yes,

doesn't work: 
RELEASE.2019-05-14T23-57-45Z
RELEASE.2019-05-02T19-07-09Z

works:
RELEASE.2019-04-23T23-50-36Z
RELEASE.2019-04-18T21-44-59Z

Maybe this PR - https://github.com/minio/minio/pull/7479

## Your Environment
* Version used: see Regression
* Environment name and version (e.g. nginx 1.9.1):

k8s/https, nginx proxy, host mount, ZoL 0.7.x, ubuntu 18.04, 4.15.0-48-generic

**Comment by kannappanr** [comment]
@stokowski Thanks for reporting this issue. We will take a look at this issue and get back to you.

**Comment by harshavardhana** [comment]
We would like to avoid making specific changes like this and have different behavior across filesystems. As this can make debugging issues doubly harder.

Best option is to use XFS instead of ZFS.

**Comment by stokowski** [comment]
In that PR https://github.com/minio/minio/pull/7479 is info about zfs and fallback in case O_DIRECT is not supported, was that implemented ?

**Comment by harshavardhana** [comment]
> In that PR #7479 is info about zfs and fallback in case O_DIRECT is not supported, was that implemented ?

It was avoided on purpose, to avoid multiple ways to do the same thing. It is in general our intention to keep single code paths under all deployments such that our testing is guaranteed across all deployments.

**Comment by stokowski** [comment]
Well, this is not solving my issue. Maybe instead of "recommended" fs lets put "supported" fs and other requirements, especially when this can change from version to version ? :\

**Comment by harshavardhana** [comment]
> Well, this is not solving my issue. Maybe instead of "recommended" fs lets put "supported" fs and other requirements, especially when this can change from version to version ? :\

If you are asking we should turn off consistency features based on the filesystem features then it is harder for us to justify the stability of such a deployment i.e using ZFS in your scenario.

Will circle back on this internally and let you know. For now, XFS is recommended

**Comment by stokowski** [comment]
ZoL 0.8 with direct io has beed released yesterday. If I will have ability to test it I will share results.

**Comment by stokowski** [comment]
Confirmed - succesfully created bucket and uploaded file.

1 node / 4 disks (ebs) setup

Ubuntu 18.04

```
uname -rvo
4.15.0-1039-aws #41-Ubuntu SMP Wed May 8 10:43:54 UTC 2019 GNU/Linux

zfs version
zfs-0.8.0-1
zfs-kmod-0.8.0-1
```

**Comment by harshavardhana** [comment]
So we can close this issue then @stokowski

**Comment by stokowski** [comment]
Yes. it looks so. I think you should put somewhere in docs os/fs requirements.

**Comment by harshavardhana** [comment]
> Yes. it looks so. I think you should put somewhere in docs os/fs requirements.

Thanks. Closing.

**Comment by rnz** [comment]
> > Yes. it looks so. I think you should put somewhere in docs os/fs requirements.
> 
> Thanks. Closing.

That was wrong.
In many cases upgrade of driver of filesystem is not possible or not reasonable.
It’s advisable to add relaxed mode based on buffers OS or buffers of fs driver, as is the case with ZFS. Such as did in ScyllaDB (relaxed-dma).
