### ISSUE TITLE
Kafka S3 event object key slashes are url encoded

### ISSUE THREAD

**Issue by IsNull** [minio/minio#7665]
## Expected Behavior

A minio event notification in Kafka should use the object-key and NOT url encode it.

## Current Behavior

An object is uploaded with:
* **bucket** mybucket
* **object-key** 5cdfb588cea4de1db3034a87/colors.xml

Minio emits the following event to Kafka:
```json
{
    "EventName": "s3:ObjectCreated:Put",
    "Key": "mybucket/5cdfb588cea4de1db3034a87/colors.xml",
    "Records": [
        {
            "eventVersion": "2.0",
            "eventSource": "minio:s3",
            "awsRegion": "",
            "eventTime": "2019-05-18T07:34:32Z",
            "eventName": "s3:ObjectCreated:Put",
            "userIdentity": {
                "principalId": "minio"
            },
            "requestParameters": {
                "accessKey": "minio",
                "region": "",
                "sourceIPAddress": "172.18.0.1"
            },
            "responseElements": {
                "x-amz-request-id": "159FB6B233B08AF0",
                "x-minio-deployment-id": "cd7a0eb7-a1f9-48d9-b21a-56366d75cfdd",
                "x-minio-origin-endpoint": "http://172.18.0.6:9000"
            },
            "s3": {
                "s3SchemaVersion": "1.0",
                "configurationId": "Config",
                "bucket": {
                    "name": "mybucket",
                    "ownerIdentity": {
                        "principalId": "minio"
                    },
                    "arn": "arn:aws:s3:::mybucket"
                },
                "object": {
                    "key": "5cdfb588cea4de1db3034a87%2Fcolors.xml",
                    "size": 261,
                    "eTag": "f5306c6d400629d2abfa8f8976b79ff0",
                    "contentType": "text/xml",
                    "userMetadata": {
                        "cache-control": "no-cache",
                        "content-type": "text/xml"
                    },
                    "versionId": "1",
                    "sequencer": "159FB6B2353A73F4"
                }
            },
            "source": {
                "host": "172.18.0.1",
                "port": "",
                "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
            }
        }
    ]
}
```
While the Key property looks good, the object.key part does not, as the slash here is suddenly url encoded to `%2F`:

```json
                "object": {
                    "key": "5cdfb588cea4de1db3034a87%2Fcolors.xml",
```

## Steps to Reproduce (for bugs)

1. Setup minio for Kafka
2. Enable bucket events to this configured arn
3. Upload an object, ensure the object-key has a slash in it: `my-key/cool.pdf`
4. Inspect the message in Kafka

## Context

This bug is quite problematic since the event points to an object key which does not exist.

## Regression

Unknown if this ever worked correctly.

## Your Environment

* Version used (`RELEASE.2019-05-14T23-57-45Z`):
* Docker on macos

**Comment by harshavardhana** [comment]
URL encoding is expected and is behaving in accordance with S3 eventInfo structure requirement. We cannot drop URL encoding.

Object does exist with %2F i.e a / in URL encoding terms. If you want to unencode it just put a webhook, convert it and send it to Kafka yourself.

**Comment by IsNull** [comment]
Thanks for the fast response.  I overlooked this in the AWS spec.

I mean its a quite strange decision to url encode this field in json (and not url encode the same value in another field), I understand you want to stay compatible to their api which is a good thing.

Therefore this is resolved for me.
