### ISSUE TITLE
Invalid arguments specified

### ISSUE THREAD

**Issue by west789** [minio/minio#7666]
## Steps to Reproduce (for bugs)

I use go run web-Identity.go, the outputs are as follows, why Invalid arguments occurs：
![image](https://user-images.githubusercontent.com/30501870/57967660-36061600-7994-11e9-904e-8c4b2911428e.png)

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
Closing this issue as lack of information, please update or reopen the issue with 

- a reproducer, a statement of fact on what happened and what you were trying to do
- your MinIO version
- any other environment detail

Thanks
