### ISSUE TITLE
The same bug of #3844 is back.

### ISSUE THREAD

**Issue by thekoma** [minio/minio#7668]
The same bug of #3844 is back.

    Version
    2019-05-14T23:57:45Z
    Memory
    Used: 4.9 MB | Allocated: 100 MB | Used-Heap: 4.9 MB | Allocated-Heap: 66 MB
    Platform
    Host: minio | OS: linux | Arch: amd64
    Runtime
    Version: go1.12 | CPUs: 4

**Comment by harshavardhana** [comment]
@Koma-Andrea please explain more the original issue talks about the expiry but that seems to be working fine when I used the browser UI?

**Comment by kannappanr** [comment]
@Koma-Andrea Will send in a PR to fix this issue.
