### ISSUE TITLE
Gateway Bucket Notifications for Public Cloud Object Storage

### ISSUE THREAD

**Issue by thejmazz** [minio/minio#7670]
Hi, I’ve noticed neither of Azure, GCS, or S3 gateways support bucket notifications. I’m guessing this is perhaps due to it requiring vendor specific code and user setup for each gateway? E.g. configuring Cloud Pub/Sub for GCS. This would be useful for centralizing events out of every cloud’s object storage - e.g. multiple MinIO gateways sending events to same NATS.  Looking for clarification if this is going to be on roadmap or if its simply not worth it and users should handle vendor object storage notifications on their own.

See [comment from GCS Gateway docs PR](https://github.com/minio/minio/pull/4622#discussion_r125364594).

Thanks!

**Comment by harshavardhana** [comment]
Gateway will not support bucket notifications, except NAS gateway @thejmazz - this is our current design choice to keep gateway's simple and follow our share nothing architecture.

It is expected that you handle on your own for non-NAS deployments.

**Comment by thejmazz** [comment]
Sounds good - thanks for quick reply!
