### ISSUE TITLE
Do not allow duplicate entry in Notification

### ISSUE THREAD

**Issue by sinhaashish** [minio/minio#7671]
Duplicate entry allowed in Notification.xml

## Expected Behavior

adding the same event must error out stating 
``` 
mc: <ERROR> Cannot enable notification on the specified bucket. An object key name filtering rule defined with overlapping prefixes, overlapping suffixes, or overlapping combinations of prefixes and suffixes for the same event types.
 ```

## Current Behavior

Allows the addtion of duplicate entry in Notification.xml

## Steps to Reproduce (for bugs)

Try 
1. mc event add  myminio/test arn:minio:sqs::1:elasticsearch  --suffix .jpg

The notification XML entry is :
``` 
<?xml version="1.0" encoding="UTF-8"?>
<NotificationConfiguration>
   <QueueConfiguration>
      <Id />
      <Filter>
         <S3Key>
            <FilterRule>
               <Name>suffix</Name>
               <Value>.jpg</Value>
            </FilterRule>
         </S3Key>
      </Filter>
      <Event>s3:ObjectCreated:*</Event>
      <Event>s3:ObjectRemoved:*</Event>
      <Event>s3:ObjectAccessed:*</Event>
      <Queue>arn:minio:sqs::1:elasticsearch</Queue>
   </QueueConfiguration>
</NotificationConfiguration>
 ```

Now add the region in arn and re-run 
2. mc event add  myminio/test1 arn:minio:sqs:us-east-1:1:elasticsearch  --suffix .jpg
Console shows `Successfully added arn:minio:sqs:us-east-1:1:elasticsearch` 
While notification.xml has entry 
```
<?xml version="1.0" encoding="UTF-8"?>
<NotificationConfiguration>
   <QueueConfiguration>
      <Id />
      <Filter>
         <S3Key>
            <FilterRule>
               <Name>suffix</Name>
               <Value>.jpg</Value>
            </FilterRule>
         </S3Key>
      </Filter>
      <Event>s3:ObjectCreated:*</Event>
      <Event>s3:ObjectRemoved:*</Event>
      <Event>s3:ObjectAccessed:*</Event>
      <Queue>arn:minio:sqs::1:elasticsearch</Queue>
   </QueueConfiguration>
   <QueueConfiguration>
      <Id />
      <Filter>
         <S3Key>
            <FilterRule>
               <Name>suffix</Name>
               <Value>.jpg</Value>
            </FilterRule>
         </S3Key>
      </Filter>
      <Event>s3:ObjectCreated:*</Event>
      <Event>s3:ObjectRemoved:*</Event>
      <Event>s3:ObjectAccessed:*</Event>
      <Queue>arn:minio:sqs::1:elasticsearch</Queue>
   </QueueConfiguration>
</NotificationConfiguration>
```

Second scenerio
1. Run 
`mc mb myminio/mybucket
2. Event add using region in arn 
`mc event add  myminio/mybucket arn:minio:sqs:us-east-1:1:elasticsearch  --suffix .jpg`
3. Again run 
`mc event add  myminio/mybucket arn:minio:sqs:us-east-1:1:elasticsearch  --suffix .jpg`
Console shows `Successfully added arn:minio:sqs:us-east-1:1:elasticsearch` 

In this scenario it should error out stating duplicate entries.

## Regression

No

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): 
* Link to your project:

**Comment by harshavardhana** [comment]
Has this been tested with AWS S3 @sinhaashish why should we allow duplicate entries? - or you meant to say we shouldn't allow?

**Comment by sinhaashish** [comment]
> Has this been tested with AWS S3 @sinhaashish why should we allow duplicate entries? - or you meant to say we shouldn't allow?

I meant to say we shouldn't allow duplicate entries. Thanks for updating the title.
