### ISSUE TITLE
sets: isTruncated is set to true when --prefix is passed & --max-keys is set to the number of result elems

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#7672]
## Expected Behavior
When a bucket contains only two objects, named `0` and `00`, listing with `prefix = 0` and `max-keys = 2` should return isTruncated is set to false (check with AWS S3 for confirmation) 

## Current Behavior
isTruncated is set to true

## Possible Solution
Do not know yet

## Steps to Reproduce (for bugs)
1. `mc mb myminio/testbucket/`
2. `mc cp file myminio/testbucket/0 && mc cp file myminio/testbucket/00`
3. `aws --debug --endpoint-url http://localhost:9000 s3api list-objects --bucket testbucket --prefix 0 --max-items 2 --page-size 2`

Check isTruncated in the xml of the debug

## Context
Fixing a regression

## Regression
Yes

## Your Environment
All

**Comment by vadmeste** [comment]
Taking this

**Comment by harshavardhana** [comment]
The side effect of this is that the client may send another Listing request, is that a bad thing?

**Comment by vadmeste** [comment]
> The side effect of this is that the client may send another Listing request, is that a bad thing?

I would say we may have some issues with current SDK libraries if we don't follow stricly S3 here , is there a reason why we should not take this PR ?

**Comment by harshavardhana** [comment]
> I would say we may have some issues with current SDK libraries if we don't follow stricly S3 here , is there a reason why we should not take this PR ?

It is harder to fix AFAICS @vadmeste it may end up making the code complex. Should we consider fixing it if there is an issue reported in the future?

**Comment by vadmeste** [comment]
@harshavardhana I sent this PR https://github.com/minio/minio/pull/7675 which should fix it
