### ISSUE TITLE
Multi-node Cloud Storage Gateway with Cache Replication - Possible gap in documentation?

### ISSUE THREAD

**Issue by ghost** [minio/minio#7679]
This may just be a newbie issue. I'm trying to understand how I can leverage a distributed group of Minio instances to act as a Gateway with a read only cache for in this case Google Cloud Storage.

## Expected Behavior

My goal would be to have a Minio distributed across all nodes of a Kubernetes cluster. They would be running in gateway mode with a local Cache and leverage eraser coding to keep all minio instances up to date and so not keep pulling from Google Storage? Especially in node recovery mode.

We would then leverage environment variables in our scripts to try and keep the traffic local to that host (as best as possible).

For now I'm just testing on a Ubuntu Server (16.04) but I can't figure out the settings I should use:

## Current Behavior

I'm running the following as a test on a single server so I can build the working config before I add other items into the mix

export GOOGLE_APPLICATION_CREDENTIALS=/PATH/credentials.json
export MINIO_ACCESS_KEY=KEY
export MINIO_SECRET_KEY=KEY
export MINIO_CACHE_DRIVES="/mnt/sdb/cache/;/mnt/sdc/cache"
export MINIO_CACHE_EXPIRY=40
export MINIO_CACHE_MAXUSE=80
./minio gateway gcs PROJECT_ID

In order to do multi node I need to add the following but I can't tell where, as it doesn't seem compatible with Gateway

minio server http://10.10.10.103:9000 http://10.10.10.133:9000

## Possible Solution

Is this supported? I've searched the documentation and the open closed issues to try and spot a similar example.

## Steps to Reproduce (for bugs)

I think I have covered this above?

## Context

The goal is to enable very fast access of data from Cloud Object Storage that is localized to the host for optimal access and leverage Eraser coding for cache replication?

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

Ubuntu 16.04.06
Minio 2019-05-14T23:57:45Z

Thanks

**Comment by kannappanr** [comment]
@hassbabaie MinIO  does not support erasure coding in Gateway mode. As of now, if you want HA, you need to run multiple Gateway instances that talks to same backend. Each node has to cache the object that you want to access from GCS.

**Comment by ghost** [comment]
@kannappanr thanks for the quick reply and that now makes sense given I couldn't see it in the documentation. 

If possible can you share if there are any roadmap plans related to this? Just for informational purposes

Thanks

Hass

**Comment by harshavardhana** [comment]
> If possible can you share if there are any roadmap plans related to this? Just for informational purposes

We don't have any plans on implementing erasure coding in gateway mode @hassbabaie - gateway is a share nothing architecture with backend being the persistent store. 

You can use minio server instead to get erasure coding.

**Comment by nitisht** [comment]
Closing this as there nothing to be done from our side. Feel free to reach out on slack for further questions @hassbabaie
