### ISSUE TITLE
checkPortAvailability ignores host/ip given with --address

### ISSUE THREAD

**Issue by rsommer** [minio/minio#7685]
The code in checkPortAvailability does not take into account the given address, leading to false positives while checking for availability.

## Expected Behavior
If I have a local process using port 9000 on IP 10.0.0.1 and start minio with port 9000 with `--address=10.0.0.2:9000`, minio should start just fine.
## Current Behavior
Due to the implementation of the port availability test, minio complains about the port being already in use.

## Possible Solution
checkPortAvailability should not only accept the port but hostAddr and should only check for availability on the given host/IP.

## Reproduce
Add two dedicated IP addresses:
```
ip a a 10.0.0.1/24 dev eth0
ip a a 10.0.0.2/24 dev eth0
```
Open two shells/tmux whatever and in one do
```
minio server --address=10.0.0.1:9000 /tmp/test1
```
and in the other
```
minio server --address=10.0.0.2:9000 /tmp/test2
```
leading to
```
ERROR Unable to start the server: Port :9000 is already in use.
```

## Context
This would be useful when multiple minio instances should run on a single host, all using the default http/https port or alongside othe http/https services.

## Your Environment
Ubuntu Linux 18.04
```
$ minio version
Version: 2019-05-23T00:29:34Z
Release-Tag: RELEASE.2019-05-23T00-29-34Z
Commit-ID: e252114f067b07e6c22b91f46a6fa9815450e7a8
```

**Comment by nitisht** [comment]
Thanks for reporting @rsommer we'll take a look

**Comment by harshavardhana** [comment]
@rsommer a port is unique on the system if you listen on localhost:9000 then you cannot again listen on another IP - since these are two separate processes. 

This behavior is expected and correct.

**Comment by kanagarajkm** [comment]
@rsommer did you run the following commands in the same machine?

`minio server --address=10.0.0.1:9000 /tmp/test1`

`minio server --address=10.0.0.2:9000 /tmp/test2`

**Comment by rsommer** [comment]
@kanagarajkm yes, for testing purpose. But it's all the same if you have a single node with multiple IPs, where for example an apache server is listening on port 443 on one IP, and you want to run minio with TLS on port 443 on another IP on the same node.
