### ISSUE TITLE
[Feature Request] Multiple access/secret key pairs for Gateway Mode

### ISSUE THREAD

**Issue by philipthomasme** [minio/minio#7693]
**Is your feature request related to a problem? Please describe.**
Just like the feature request https://github.com/minio/minio/issues/5305 for server mode, I would need an option to use multiple access and secret key pairs for gateway mode. By allowing this it would be possible to have different users access different buckets without interfering or being able to access each others data (so a proper client separation).

**Describe the solution you'd like**
Configure _n_ key pairs that can be used for authentication with separated access to a storage service like B2 and show the buckets they have access to.

**Describe alternatives you've considered**
The only option right now would be to have a super user configured in MinIO in order to access multiple buckets but this would not create separated authentication and access rights.

**Comment by harshavardhana** [comment]
You need to use etcd in gateway mode to get multi-user feature @philipthomasme

**Comment by philipthomasme** [comment]
Having problems getting this to work (https://github.com/minio/minio/issues/7695) but I guess the feature is implemented and therefore I will close this here.
