### ISSUE TITLE
B2 Gateway + ETCD not listing any buckets

### ISSUE THREAD

**Issue by philipthomasme** [minio/minio#7695]
I try to setup multiple users with ETCD for a minio B2 gateway. The login with admin credentials work and also for any added user but no user shows any buckets. Neither via mc nor via browser.

## Expected Behavior
List buckets using either mc or browser

## Current Behavior
Not showing any buckets

## Possible Solution
No idea, although https://github.com/minio/minio/issues/7191 mentioned the same behaviour for GCS.

## Steps to Reproduce (for bugs)
Start minio gateway gcs with an ETCD_ENDPOINT env variable defined.
List buckets.

## Context
Fresh minio and etcd installation.

## Regression
No idea.

## Your Environment

* Version used (`minio version`): RELEASE.2019-05-23T00-29-34Z
* Environment name and version (e.g. nginx 1.9.1): Docker 18.09.6
* Server type and version: -
* Operating System and version (`uname -a`): Ubuntu 18.04
* Link to your project: private

**Comment by harshavardhana** [comment]
Fixed by #7686

**Comment by philipthomasme** [comment]
Built the latest commit and everything works perfectly.
