### ISSUE TITLE
[Gateway] MINIO_REGION is not working

### ISSUE THREAD

**Issue by krzepah** [minio/minio#7702]
## Expected Behavior
Should be able to set REGION using env

## Current Behavior
    ERROR Unable to initialize gateway backend: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'fr-par'.

## Possible Solution
- Seen https://github.com/minio/minio/issues/5593 and the issue there seems to be resolved and merged. Maybe I'm missing something out with bellow command

## Steps to Reproduce (for bugs)
Scaleway provides buckets that are S3 compatible but are labeled with "fr-par" region.

    docker run -p 9000:9000 --name minio-s3 \
      -e "MINIO_REGION=fr-par" \
      -e "MINIO_ACCESS_KEY=*******" \
      -e "MINIO_SECRET_KEY=*******" \
      minio/minio:RELEASE.2018-11-30T03-56-59Z \
      gateway \
      s3 \
      s3.fr-par.scw.cloud:443

Setting env and using bare minio didn't change it's behaviour.

## Context
Trying to run Minio in gateway mode against [scaleway](scaleway.com)

## Regression
- Seen https://github.com/minio/minio/issues/6873 and tried with RELEASE.2018-11-30T03-56-59Z ; doesn't work either with the same above error

## Your Environment
Tried with Docker and then with bare OS X ; all against a scaleway bucket

**Comment by harshavardhana** [comment]
Region is only honored for AWS S3 endpoints ..

**Comment by krzepah** [comment]
That's sad, do you mean we'd need and improvement to get that working with scaleway or other bucket supplier that have multiple zones ?

Why are only AWS regions honored ?

**Comment by kannappanr** [comment]
Have sent a PR in minio-go to retry once if the server sends AuthorizationHeaderMalformed code and a region. I believe this should be enough to make it work. Once that PR is merged in minio-go and vendorized in minio, hopefully you will not be seeing this issue.

**Comment by krzepah** [comment]
Will definitely check it out asap, thanks for the work, will let know if it has fixed it

**Comment by harshavardhana** [comment]
Fixed by https://github.com/minio/minio-go/pull/1113

**Comment by krzepah** [comment]
When should I expect a vendorize of minio-go ? Is there a way to do that manually waiting for the release ? Thank you all for the great work

**Comment by kannappanr** [comment]
We will probably make a release today.
