### ISSUE TITLE
Request: Add B2's copy API for the S3 Gateway

### ISSUE THREAD

**Issue by Jwink3101** [minio/minio#7703]
**Is your feature request related to a problem? Please describe.**

Not really

**Describe the solution you'd like**

Add support to the B2 gateway for B2's (beta) copy API call.

See [their docs](https://www.backblaze.com/b2/docs/b2_copy_file.html) and a [relevant reddit post](https://reddit.com/r/backblaze/comments/bnvjsy/any_eta_on_b2_serverside_copy/)

**Describe alternatives you've considered**

None

**Additional context**

See the [issue I opened on rclone](https://github.com/ncw/rclone/issues/3210) for some additional discussion

**Comment by kannappanr** [comment]
@Jwink3101 Please feel free to send a PR to add copy API support in `b2` gateway

**Comment by HHousen** [comment]
Backblaze recently finalized these APIs and took them out of beta: https://www.backblaze.com/blog/backblaze-b2-copy-file-beta-is-now-public/. 

Implementing this feature will remove two of the current known limitations of the b2 gateway:

> No support for CopyObject S3 API (There are no equivalent APIs available on Backblaze B2).
No support for CopyObjectPart S3 API (There are no equivalent APIs available on Backblaze B2).

Also, @Jwink3101's issue on rclone https://github.com/ncw/rclone/issues/3210 was implemented in version 1.48, so the code used there may be helpful to anyone looking to implement this feature.

**Comment by harshavardhana** [comment]
We moved to kurin/blazer thanks to PR by @mzukowski-reef - looking forward to another PR with the Copy implementation as well.

**Comment by harshavardhana** [comment]
Closing this gateway issue to be done as a future milestone.
