### ISSUE TITLE
Mint tests failing in SimpleCI

### ISSUE THREAD

**Issue by nitisht** [minio/minio#7706]
## Expected Behavior
Mint tests in SimpleCI should pass

## Current Behavior
```
Running minio-go tests ... FAILED in 1 second
{
  "args": {
    "bucketName": "minio-go-test-nri6b6yecczddwr1",
    "objectName": "minio-go-test-nri6b6yecczddwr1unique",
    "opts": "",
    "size": 135266304
  },
  "duration": 19,
  "error": "invalid argument",
  "function": "PutObject(bucketName, objectName, reader, size, opts)",
  "message": "PutObjectWithSize failed",
  "name": "minio-go: testPutObjectNoLengthV2",
  "status": "FAIL"
}
```
## Possible Solution
NA

## Steps to Reproduce (for bugs)
Run Mint against Server Gateway mode

## Regression
Yes, SimpleCI tests were passing

## Your Environment

* Version used (`minio version`): master

**Comment by harshavardhana** [comment]
Fixed by https://github.com/minio/mint/pull/320
