### ISSUE TITLE
Compact small files like facebook-haystack ?

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [minio/minio#7708]
Should minio add "small files compact" feature like  facebook-haystack ?

**Comment by kannappanr** [comment]
S3 APIs does not support one. Even if we can support this feature, then it will only be for objects that are not encrypted. I don't think we will support a feature like this. Will check internally and get back to you.

**Comment by zhengxiaochuan-3** [comment]
@kannappanr 
Does it mean that the Performance and  Availability of LOSF are not so good so far?  And should take care of it by myself?

**Comment by kannappanr** [comment]
@zhengxiaochuan-3 Availability is not an issue. Performance will definitely be. It will lead to more random I/O on the storage media, if you are dealing with lots of small files. Random I/O performance will not be as good as sequential.

**Comment by kannappanr** [comment]
ping @zhengxiaochuan-3 . Please let me know if your questions have been answered.

**Comment by zhengxiaochuan-3** [comment]
@kannappanr Is there a use case for a large-scale production environment? Especially LOSF case.Hope to get some experience.

**Comment by harshavardhana** [comment]
> @kannappanr Is there a use case for a large-scale production environment? Especially LOSF case.Hope to get some experience.

@zhengxiaochuan-3 what your actual production scale?

**Comment by zhengxiaochuan-3** [comment]
Like 1 billion documents half of a year，We don't have the money to use all ssd/nvme disks, we can only use a lot of SATA disks. Even at Billions/PB scale, if there is no "small file compact", there will still be a lot of performance problems, which is inevitable.

**Comment by harshavardhana** [comment]
> Like 1 billion documents half of a year，We don't have the money to use all ssd/nvme disks, we can only use a lot of SATA disks. Even at Billions/PB scale, if there is no "small file compact", there will still be a lot of performance problems, which is inevitable.

A billion documents on an average size of 2MiB will come to around 2PiB which is still a small scale compared to the capacity of deployments MinIO can support. It is rather premature @zhengxiaochuan-3 to think about performance without benchmarking on real hardware with the real workload that you may generate.

It is usually worthwhile to benchmark with exact application patterns - with some limited hardware first, which may represent a close enough representation of your production workload. Once we know what MinIO is behaving in an expected manner for your performance requirements it is easier to extrapolate from those results.

**Comment by kannappanr** [comment]
@zhengxiaochuan-3 Closing this issue as answered. Please feel free to re-open if you have further questions.
