### ISSUE TITLE
Initial slash in object name causes error on copy

### ISSUE THREAD

**Issue by MrCreosote** [minio/minio#7717]
## Expected Behavior
Minio copy operations work normally when the object name starts with a slash.

## Current Behavior
```
func (t *TestSuite) TestMinioCopyWithSlashes() {
	endpoint := "localhost:" + strconv.Itoa(t.minio.GetPort())
	minioClient, _ := minio.NewWithRegion(
		endpoint, "ackey", "sooporsecret", false, "us-west-1")
	minioClient.MakeBucket("mybukkit", "us-west-1")
	r := strings.NewReader("foo")
	_, err := minioClient.PutObject("mybukkit", "myfile/file1", r, 3, minio.PutObjectOptions{})
	t.Nil(err, "unexpected error")
	src := minio.NewSourceInfo("mybukkit", "/myfile/file1", nil)
	dst, _ := minio.NewDestinationInfo("mybukkit", "/myfile/file2", nil, nil)
	err = minioClient.CopyObject(dst, src)
	t.Nil(err, "unexpected error 2")
}
```
Results in
```
API server listening at: 127.0.0.1:3412
--- FAIL: TestRunSuite (2.78s)
    --- FAIL: TestRunSuite/TestMinioCopyWithSlashes (0.01s)
        s3_test.go:468: 
            	Error Trace:	s3_test.go:468
            	Error:      	Expected nil, but got: minio.ErrorResponse{XMLName:xml.Name{Space:"", Local:"Error"}, Code:"XMinioInvalidObjectName", Message:"Object name contains unsupported characters.", BucketName:"mybukkit", Key:"/myfile/file2", RequestID:"15A3525415EAA639", HostID:"462c8248-67a3-4dc0-b2ad-98055dbc154c", Region:"", StatusCode:400}
            	Test:       	TestRunSuite/TestMinioCopyWithSlashes
            	Messages:   	unexpected error 2
FAIL
```

Removing the initial slash from `/myfile/file2` makes the copy work, which is odd since the initial slash on the copy source causes no problems. Also, including an initial slash in the object name in the parameters to [PutObjectRequest](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.PutObjectRequest) works as expected.

At the very least, the error is confusing since slashes are not unsupported.

## Possible Solution

I *think* this is because the bucket name is automatically appended with a slash, so the path becomes `/mybukkit//myfile/file2`.

The code could automatically clean up the path in this case to avoid the error.

## Steps to Reproduce (for bugs)
See test above.

## Context
We're migrating data from a file store that uses subdirs to manage data, so we're mirroring the subdirs into Minio. The DB starts the names with a slash, so we did the same.

## Regression
Unknown

## Your Environment
```
cat go.mod | grep minio
	github.com/minio/minio-go v0.0.0-20190430232750-10b3660b8f09
./minio version
Version: 2019-04-09T01:22:30Z
Release-Tag: RELEASE.2019-04-09T01-22-30Z
Commit-ID: a2e344bf30c7750c0a152f046a70d327f2f5ccf5
```

Ubuntu 18.04

**Comment by harshavardhana** [comment]
Can you test with latest release @MrCreosote ?

**Comment by MrCreosote** [comment]
@harshavardhana No change with `RELEASE.2019-05-23T00-29-34Z`. I didn't notice anything in the release notes re changes to this behavior which is why I tested with the older version.

**Comment by kannappanr** [comment]
@MrCreosote AWS does returns `The specified key does not exist`, while minio does not. We can change the behavior there. But in the case of minio since the `objects` are stored in the backend as files, we cannot have object names starting with `/`

**Comment by MrCreosote** [comment]
@kannappanr 

> AWS does returns The specified key does not exist

Hmm... I'm using [PutObjectRequest](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.PutObjectRequest), [HeadObject](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.HeadObject), [GetObject](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.GetObject), and [DeleteObject](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.DeleteObject) with object names starting with slashes with Minio with no issues. Also, [CopyObject](https://docs.min.io/docs/golang-client-api-reference.html#CopyObject) works normally when the source object is specified with a leading slash.

I suppose one potential solution is to treat `/obj` and `obj` as the same object, but I haven't thought through the implications. My knee jerk reaction is that that's not a good idea.

The error message is very confusing though, and led me down the wrong path when I was trying to figure this out.

**Comment by kannappanr** [comment]
@MrCreosote The situation I specified is when say there exists a key called `tmp/source`, but not `/tmp/source` in AWS and if you were to use `/tmp/source` in AWS, then you would receive this error. What I am trying to say is that a leading `/` is not supported in MinIO. So, the error you are receiving makes sense.

You can have two objects named `/tmp/source` and `tmp/source` in AWS, but any object starting with `/` is not supported in `MinIO`

**Comment by MrCreosote** [comment]
> I suppose one potential solution is to treat /obj and obj as the same object, but I haven't thought through the implications. My knee jerk reaction is that that's not a good idea.

Well, it looks like minio already does that from the perspective of the amazon client, so maybe that's not so crazy:
```
func (t *TestSuite) TestAMZClientWithLeadingSlash() {
	trueref := true
	endpoint := "localhost:" + strconv.Itoa(t.minio.GetPort())

	sess := session.Must(session.NewSession())
	creds := credentials.NewStaticCredentials("ackey", "sooporsecret", "")
	cli := s3.New(sess, &aws.Config{
		Credentials:      creds,
		Endpoint:         &endpoint,
		Region:           ptr("us-west-1"),
		DisableSSL:       &trueref,
		S3ForcePathStyle: &trueref}) // minio pukes otherwise

	_, err := cli.CreateBucket(&s3.CreateBucketInput{Bucket: ptr("buk")})
	t.Nil(err, "unexpected error")

	poo, err := cli.PutObject(&s3.PutObjectInput{
		Bucket: ptr("buk"), Key: ptr("/obj"), Body: strings.NewReader("foo")})
	t.Nil(err, "unexpected error")
	fmt.Println(poo)

	poo, err = cli.PutObject(&s3.PutObjectInput{
		Bucket: ptr("buk"), Key: ptr("obj2"), Body: strings.NewReader("foo2")})
	t.Nil(err, "unexpected error")
	fmt.Println(poo)

	for _, key := range []string{"/obj", "obj", "/obj2", "obj2"} {
		goo, err := cli.GetObject(&s3.GetObjectInput{Bucket: ptr("buk"), Key: &key})
		t.Nil(err, "unexpected error")
		fmt.Println(goo)
	}
}
```

Results in:
```
{
  ETag: "\"acbd18db4cc2f85cedef654fccc4a4d8\""
}
{
  ETag: "\"92e0057157f69e22a364d6b22dd6bbd5\""
}
{
  AcceptRanges: "bytes",
  Body: buffer(0xc0002b4a00),
  ContentLength: 3,
  ContentType: "application/octet-stream",
  ETag: "\"acbd18db4cc2f85cedef654fccc4a4d8\"",
  LastModified: 2019-05-30 17:42:59 +0000 UTC,
  Metadata: {
  }
}
{
  AcceptRanges: "bytes",
  Body: buffer(0xc00020f200),
  ContentLength: 3,
  ContentType: "application/octet-stream",
  ETag: "\"acbd18db4cc2f85cedef654fccc4a4d8\"",
  LastModified: 2019-05-30 17:42:59 +0000 UTC,
  Metadata: {
  }
}
{
  AcceptRanges: "bytes",
  Body: buffer(0xc0002b4f00),
  ContentLength: 4,
  ContentType: "application/octet-stream",
  ETag: "\"92e0057157f69e22a364d6b22dd6bbd5\"",
  LastModified: 2019-05-30 17:42:59 +0000 UTC,
  Metadata: {
  }
}
{
  AcceptRanges: "bytes",
  Body: buffer(0xc00020f480),
  ContentLength: 4,
  ContentType: "application/octet-stream",
  ETag: "\"92e0057157f69e22a364d6b22dd6bbd5\"",
  LastModified: 2019-05-30 17:42:59 +0000 UTC,
  Metadata: {
  }
}
```

**Comment by MrCreosote** [comment]
@kannappanr 

> So, the error you are receiving makes sense.

I'm going to have to respectfully disagree here. When copying an object to `/obj`, for example, the error is `Object name contains unsupported characters.` It's clear that all the characters in `/obj` are supported since the object name `o/bj` works normally. The error message doesn't describe the actual problem with the object name.

**Comment by kannappanr** [comment]
@MrCreosote If the message is the only thing that needs to be changed, I can check internally and see if we can come up with something generic, that covers both `unsupported characters and unsupported characters at certain position of the key name`

**Comment by MrCreosote** [comment]
@kannappanr That'd help - or two different messages depending on the case would help.

There's also the issue that the amazon client treats `/obj` and `obj` as the same object when communicating with minio - I'm not sure if that's intended, or a bug, or what.

**Comment by kannappanr** [comment]
Amazon does not treat them as same. They are two different objects. In the case of `MinIO` we cannot have an object named `/obj`

**Comment by kannappanr** [comment]
Also, I don't think Amazon client treats them same also. Here is what I did with `AWS CLI` and ran it against my local server

```
$ AWS_ACCESS_KEY_ID=minio AWS_SECRET_ACCESS_KEY=minio123 aws s3api --endpoint-url=http://localhost:9000 put-object --bucket test --key /test --body /etc/issue

An error occurred (XMinioInvalidObjectName) when calling the PutObject operation: Object name contains unsupported characters.
```

**Comment by MrCreosote** [comment]
@kannappanr I demonstrated [here](https://github.com/minio/minio/issues/7717#issuecomment-497417418) that the AMZ client, when pointed at minio, treats `/obj` and `obj` as the same thing.

Could be due to AMZ client internals, but it def ignores leading slashes.

**Comment by kannappanr** [comment]
@MrCreosote It is a Amazon SDK issue, I ran a sample `AWS-sdk-go` code with an `object` named `/obj` and had turned on `HTTP tracing` on `MinIO` and saw this

```
[REQUEST objectAPIHandlers.PutObjectHandler-fm] [155925549.476689] [2019-05-30 15:31:34 -0700]
PUT /test/obj
Host: localhost:9000
User-Agent: aws-sdk-go/1.19.41 (go1.12.1; linux; amd64)
Content-Length: 26
Authorization: AWS4-HMAC-SHA256 Credential=minio/20190530/us-east-1/s3/aws4_request, SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=1ea1efc1f5439641d0d56c845f99d9729b0ac5e3d82f50edf05e3a86db300a8a
Content-Md5: uVRBjmpQ1NTLjwJ3bYZ1UA==
X-Amz-Content-Sha256: 1094a1ff5d6d0d9137ad321396fe5c2a4653258b102f9ac04ec7acae00970598
X-Amz-Date: 20190530T223134Z
Accept-Encoding: gzip

<BODY>

[RESPONSE] [155925549.476689] [2019-05-30 15:31:34 -0700]
200 OK
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 15A3969C77A671D8
X-Minio-Deployment-Id: e6fa1e2e-836c-4c1b-9262-66fbf1d501a3
ETag: "b954418e6a50d4d4cb8f02776d867550"
Server: MinIO/DEVELOPMENT.2019-05-29T21-05-29Z
Accept-Ranges: bytes
Vary: Origin
X-Xss-Protection: 1; mode=block

<BODY>
```
The SDK stripped off the leading `/`

In the case of `AWS CLI` I see the following

```
[REQUEST objectAPIHandlers.PutObjectHandler-fm] [155925551.560072] [2019-05-30 15:31:55 -0700]
PUT /test//test
Host: localhost:9000
Content-Length: 26
Accept-Encoding: identity
X-Amz-Date: 20190530T223155Z
X-Amz-Content-Sha256: 1094a1ff5d6d0d9137ad321396fe5c2a4653258b102f9ac04ec7acae00970598
Authorization: AWS4-HMAC-SHA256 Credential=minio/20190530/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=941e2be25a6298d2b03566ee4eab4530c62e159b55b8ce8a584c8bae567fa72f
User-Agent: aws-cli/1.14.44 Python/3.6.7 Linux/4.15.0-50-generic botocore/1.12.19
Content-Md5: uVRBjmpQ1NTLjwJ3bYZ1UA==
Expect: 100-continue

<BODY>

[RESPONSE] [155925551.560072] [2019-05-30 15:31:56 -0700]
400 Bad Request
X-Minio-Deployment-Id: e6fa1e2e-836c-4c1b-9262-66fbf1d501a3
Server: MinIO/DEVELOPMENT.2019-05-29T21-05-29Z
Accept-Ranges: bytes
Content-Type: application/xml
Vary: Origin
X-Xss-Protection: 1; mode=block
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 15A396A151711354

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioInvalidObjectName</Code><Message>Object name contains unsupported characters.</Message><Key>/test</Key><BucketName>test</BucketName><Resource>/test//test</Resource><RequestId>15A396A151711354</RequestId><HostId>e6fa1e2e-836c-4c1b-9262-66fbf1d501a3</HostId></Error>
```
It doesn't seem to strip off the leading `/`. So if the client is stripping off the leading `/`, then to `MinIO` it is as good as sending it without the leading `/`.

**Comment by kannappanr** [comment]
Like I said earlier, I will check about the message itself. Other than that I don't think there is anything else to look at. Please let me know if you feel otherwise.

**Comment by MrCreosote** [comment]
@kannappanr fair enough, thanks for looking into this.

**Comment by nitisht** [comment]
Closing the issue based on above comments

**Comment by MrCreosote** [comment]
@nitisht @kannappanr I was under the impression this would stay open as you guys were going to look into improving the error messaging? Since this is an area where Minio diverges from S3, IMO it's pretty important to make the problem clear in the message.

**Comment by kannappanr** [comment]
@MrCreosote It must have been a mistake. Like I said before, we will talk about it and get back to you.

**Comment by kannappanr** [comment]
@MrCreosote We will change the message to be as specific as possible.
