### ISSUE TITLE
Failed to access by using signature v4

### ISSUE THREAD

**Issue by mzch** [minio/minio#7718]
## Expected Behavior

Most apps tries to access AWS S3 and compatible storage using signature v4.
Minio should be accessed as well.

## Current Behavior

Minio reported 'Signature does not match' error as below:
```
$ s3cmd info s3://helpy
ERROR: S3 error: 403 (SignatureDoesNotMatch): The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

Of course, s3cmd can access AWS S3 using sig v4.

## Possible Solution

No idea.

## Steps to Reproduce (for bugs)

1. start minio in vhost style or path style.
2. create a certain bucket
3. access to the bucket using s3cmd
4. error.

## Context

Can't use many apps.

## Your Environment

* Version used (`minio version`):
Version: 2019-05-23T00:29:34Z
Release-Tag: RELEASE.2019-05-23T00-29-34Z
Commit-ID: e252114f067b07e6c22b91f46a6fa9815450e7a8
* Environment name and version (e.g. nginx 1.9.1): Apache/2.4.25
* Server type and version: Debian GNU/Linux 9.9 stretch
* Operating System and version (`uname -a`): Linux ny 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux
* Link to your project: e.g. [fog-aws](https://github.com/fog/fog-aws), [s3cmd](https://github.com/s3tools/s3cmd). **These projects are not mine!**

**Comment by mzch** [comment]
...And even when enforcing sig v2, in vhost style the same error occurs, too.

**Comment by harshavardhana** [comment]
Please share your s3cmd config, also have you followed https://docs.min.io/docs/s3cmd-with-minio.html ?

**Comment by mzch** [comment]
Oh, sorry. This issue is solved. My router's touble....
