### ISSUE TITLE
MinIO instances are out of sync after uploading a file to a bucket when running in GCS Gateway mode.

### ISSUE THREAD

**Issue by m00g3n** [minio/minio#7723]
MinIO instances are out of sync after uploading a file to a bucket when running in GCS Gateway mode.

## Expected Behavior

All MinIO instances should be in sync with GCS after uploading a file to a bucket when running in GCS Gateway mode.

## Current Behavior

Only one instance is in sync with GCS after uploading a file to a bucket when running in GCS Gateway mode.

## Steps to Reproduce (for bugs)

1. Start two instances of MinIO in GCS Gateway mode 

```
docker run --rm -p 9000:9000 --name gcs-s3-1 -v <credentials.json path>:/credentials.json \
    -e "GOOGLE_APPLICATION_CREDENTIALS=/credentials.json" \
    -e "MINIO_ACCESS_KEY=acceskeygoeshere" \
    -e "MINIO_SECRET_KEY=secretkeygoeshere" \
    minio/minio:RELEASE.2019-04-09T01-22-30Z gateway gcs mygcpproject
```

```
docker run --rm -p 9001:9000 --name gcs-s3-2 -v <credentials.json path>:/credentials.json \
    -e "GOOGLE_APPLICATION_CREDENTIALS=/credentials.json" \
    -e "MINIO_ACCESS_KEY=acceskeygoeshere" \
    -e "MINIO_SECRET_KEY=secretkeygoeshere" \
    minio/minio:RELEASE.2019-04-09T01-22-30Z gateway gcs mygcpproject
```

On instance that is exposed on port 9000, via web interface

2. Create a new bucket.

3. Change bucket policy to ReadOnly for all users

4. Upload the file

5. Use REST API on instance that is exposed on port 9001 to download the file

The result will be simmilar to:

```
* Preparing request to http://localhost:9001/mw456/foo.yaml
* Using libcurl/7.54.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1
* Current time is 2019-05-30T18:34:44.509Z
* Disable timeout
* Enable automatic URL encoding
* Disable SSL validation
* Enable cookie sending with jar of 0 cookies
* Found bundle for host localhost: 0x7fd9bd46d230 [can pipeline]
* Re-using existing connection! (#17) with host localhost
* Connected to localhost (::1) port 9001 (#17)

> GET /mw456/foo.yaml HTTP/1.1
> Host: localhost:9001
> User-Agent: insomnia/6.5.3
> Accept: */*

< HTTP/1.1 403 Forbidden
< Accept-Ranges: bytes
< Content-Security-Policy: block-all-mixed-content
< Content-Type: application/xml
< Server: Minio/RELEASE.2019-04-09T01-22-30Z
< Vary: Origin
< X-Amz-Request-Id: 15A389AFE3EF39B0
< X-Xss-Protection: 1; mode=block
< Date: Thu, 30 May 2019 18:34:44 GMT
< Transfer-Encoding: chunked


* Received 259 B chunk
* Received 5 B chunk
* Connection #17 to host localhost left intact
```

## Context

When running MinIO on kubernetes the response to download request cycles with `n-1` * `403 Forbidden` and 1 * `200 OK` for `n` pods running MinIO.

## Your Environment

* Version used (`minio version`): RELEASE.2019-04-09T01-22-30Z
* Link to your project: https://github.com/kyma-project

**Comment by harshavardhana** [comment]
This problem is your GCS issue, we are as consistent as your backend. If GCS returns an error we return an error.

They are out of sync simply because GCS is not strictly consistent.

**Comment by m00g3n** [comment]
The exact same scenario with `minio-go` client works as expected.

**Comment by harshavardhana** [comment]
> The exact same scenario with `minio-go` client works as expected.

Yes, it will work as expected since you are reaching the backend directly, gateway remembers state regarding bucket policies - it takes 5 minutes for the policies to propagate to rest of the neighboring gateways.

We are planning to fix this differently by avoiding state in this manner.

**Comment by m00g3n** [comment]
Many thx just a quick two questions:
- When would this fix be available?
- Do you know how could we workaround this issue for the time being?

**Comment by harshavardhana** [comment]
> * When would this fix be available?

Soon

> * Do you know how could we workaround this issue for the time being?

You need to restart neighboring gateway instances.
