### ISSUE TITLE
Cant get minio to log anything other than the intro

### ISSUE THREAD

**Issue by from-nibly** [minio/minio#7724]
## Expected Behavior
I just need some logging so I can debug an issue I'm seeing when trying to run some existing s3 tests I have.  I set MINIO_HTTP_TRACE=/dev/stdout and I even tried adding a config.json file and setting logger.console.enabled=true and logger.console.level=error/debug.  I can't find anything in the docs about how to turn up the logging or even get any logging whatsoever.

## Current Behavior
All I get is the intro splash.

## Steps to Reproduce (for bugs)
Here is the command I'm running
```
docker run -p 9000:9000 -ti \
 -v `pwd`/credentials.json:/credentials.json \
 -e "MINIO_HTTP_TRACE=/dev/stdout" \
 -e "GOOGLE_APPLICATION_CREDENTIALS=/credentials.json" \
 -e "MINIO_ACCESS_KEY=minioaccountname" \
 -e "LOGGER_CONSOLE_ENABLED=false" \
 -e "MINIO_SECRET_KEY=minioaccountkey" \
 -v `pwd`/config:/root/.minio \
 minio/minio:RELEASE.2019-05-23T00-29-34Z gateway gcs ***** --config-dir /root/.minio
```

## Context
I just need some logging so I can figure out why I got a 405 in my testing.

## Regression
No Idea

## Your Environment

* Version used (`minio version`): RELEASE.2019-05-23T00-29-34Z
* Environment name and version (e.g. nginx 1.9.1): Docker?
* Server type and version: GCS Gateway
* Operating System and version (`uname -a`): `Linux jordan-ThinkPad-P51s-18 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by kannappanr** [comment]
@from-nibly Can you please elaborate on what operation you are doing and any other information like client being used etc? If there is a code/command to reproduce the issue, can you please paste it here?

**Comment by from-nibly** [comment]
I mean I could but the real heart of my issue isn't the 405 that I'm getting. My guess is it's something I'm just doing wrong. What I really want is just some logs so I can figure out what is wrong on my own. Even if those logs end up being something I don't know how to solve right away I can come back here and post a new Issue. If I can get error / http trace / debug logs I might have the tools to fix all of my issues one at a time. I'm sure you guys don't want to hold my hand through this whole journey.

**Comment by harshavardhana** [comment]
You can use nc (netcat) and run your app to see what calls you app is making, then subsequently move the same code to MinIO. Copy paste the output of nc from the terminal here, we will know what might be going on..

Also it is helpful if you could tell us what http error you see on the client side..

**Comment by from-nibly** [comment]
So does minio not have logging? I think your guys eagerness to solve my 405 is to be commended but I really just want logging. Like just print something that says "405 not enough permissions in google" or "405 google does not have this functionality".  Right now I am evaluating minio for use in my company. If we can't debug issues like this on our own we are going to have to look at other solutions. I already have people trying to avoid minio because they don't want to support it. I'm not really jazzed about the other "solutions" on the table but if I can't debug this issue on my own I'm not really sure I want to support it either.

**Comment by harshavardhana** [comment]
MinIO is not like Apache server to log everything, we only log unhandled errors. All errors for which we send an error to the client we don't log them. That is why I am asking for client error. 

Trace is meant for debugging purposes in almost all situations, but only if the error is 405 there is an issue where tracing is not invoked most probably how the handlers are stacked.

**Comment by from-nibly** [comment]
OK well I'm going to close this issue then cause I'll just have to troll through my client's code to figure out what the real response is. And like I said earlier this issue is just about the logging.
