### ISSUE TITLE
Windows Server Share Paths Do Not Work if the Path is "Long"

### ISSUE THREAD

**Issue by shanebarnes** [minio/minio#7725]
Minio fails to write files with "long" paths to a mount point when the mount point is configured as a network share (e.g., \\\server\share\a\b).

## Expected Behavior

When uploading files to a Windows Minio server I expect that Minio is capable of writing files with "long" path names to either a local NTFS disk or a file server (e.g., Microsoft Azure File Shares).
 
## Current Behavior

Currently, the Windows Minio server supports writing files with "long" path names to a local NTFS disk (e.g., C:\a\b) **but** only "short" path names to a server share (e.g., \\\server\share\a\b).

## Possible Solution

I suspect that the lack of support for "long" path names with \\\server\share paths is related to the Golang source code. More specifically, a comment in the source code indicates that UNC path prefixes for \\\server\share paths are not prepended to file paths:

```
// The extended form begins with \\?\, as in
// \\?\c:\windows\foo.txt or \\?\UNC\server\share\foo.txt.
// The extended form disables evaluation of . and .. path
// elements and disables the interpretation of / as equivalent
// to \. The conversion here rewrites / to \ and elides
// . elements as well as trailing or duplicate separators. For
// simplicity it avoids the conversion entirely for relative
// paths or paths containing .. elements. For now,
// \\server\share paths are not converted to
// \\?\UNC\server\share paths because the rules for doing so
// are less well-specified.
```

https://github.com/golang/go/blob/master/src/os/path_windows.go#L131

## Steps to Reproduce (for bugs)

I used the Minio client to mirror a directory with a single file (241 bytes). The source directory to be mirrored was:

```
mymirrordirectory\windows2016datacenterlocal\WindowsPowerShell\Modules\Microsoft.PowerShell.Operation.Validation\1.0.1\Test\Modules\Example3.Diagnostics\2.0.1\Diagnostics\Simple\Example3B.Diagnostics.Tests.ps1
```

1. `mc.exe mirror mymirrordirectory minio/mybucket`

In the success case, the file was uploaded to a local NTFS disk with the Minio server setup as follows:

2. `minio.exe server C:\myymirrorfiles.file.core.windows.net\share\minio`

The file was written with a path length of 253 characters:

```
C:\myymirrorfiles.file.core.windows.net\share\minio\mybucket\windows2016datacenterlocal\WindowsPowerShell\Modules\Microsoft.PowerShell.Operation.Validation\1.0.1\Test\Modules\Example3.Diagnostics\2.0.1\Diagnostics\Simple\Example3B.Diagnostics.Tests.ps1
```

In the failure case, the file was uploaded to a network share with the Minio server setup as follows:

3. `minio.exe server \\myymirrorfiles.file.core.windows.net\share\minio`

The file upload failed with the following stack trace:

```
API: PutObject(bucket=mybucket, object=windows2016datacenterlocal/WindowsPowerShell/Modules/Microsoft.PowerShell.Operation.Validation/1.0.1/Test/Modules/Example3.Diagnostics/2.0.1/Diagnostics/Simple/Example3B.Diagnostics.Tests.ps1)
Time: 19:51:39 GMT 05/30/2019
RequestID: 15A38DE25FB5524C
RemoteHost: 127.0.0.1
UserAgent: MinIO (windows; amd64) minio-go/v6.0.26 mc/2019-05-29T21:21:34Z
Error: [31m[1mfile access denied[0m[0m
       4: cmd\fs-v1.go:881:cmd.(*FSObjects).putObject()
       3: cmd\fs-v1.go:822:cmd.(*FSObjects).PutObject()
       2: cmd\object-handlers.go:1257:cmd.objectAPIHandlers.PutObjectHandler()
       1: net\http\server.go:1995:http.HandlerFunc.ServeHTTP()
```

The failure occurred on a file operation because of the "long" path:

https://github.com/minio/minio/blob/e252114f067b07e6c22b91f46a6fa9815450e7a8/cmd/fs-v1.go#L879

Note: It is possible to avoid the failure case by mounting the network share to a drive:

```
> subst M: \\myymirrorfiles.file.core.windows.net\share
> minio.exe server M:\minio
```
Unfortunately, I am not always able to rely on a mounted network share.

## Your Environment

* Version used (`minio.exe version`):
 
```
Version: 2019-05-23T00:29:34Z
Release-Tag: RELEASE.2019-05-23T00-29-34Z
Commit-ID: e252114f067b07e6c22b91f46a6fa9815450e7a8
```

* Version used (`mc.exe version`):

```
Version: 2019-05-29T21:21:34Z
Release-tag: RELEASE.2019-05-29T21-21-34Z
Commit-id: f4bb0b8850cb5a9c2901961572066e48ad972e8c
```

* Server type and version:
* Operating System and version:
 
```
Windows Server 2016 Datacenter: Azure Standard D4s v3 (4 vcpus, 16 GiB memory)
```

**Comment by kannappanr** [comment]
@shanebarnes Thanks for reporting this issue. We will take a look at this.

**Comment by harshavardhana** [comment]
This is a Go upstream issue, we can provide hacks around it but it is better to let Go address this upstream. There is a good reason it hasn't been fixed due to lack of clarity from Windows docs regarding long path behavior with UNC paths.

A better workaround is simply mount the share as a drive and then use it, you can still use the long paths appropriately in this manner.

**Comment by nitisht** [comment]
Closing this based on previous comment, feel free to reach out on slack (https://slack.min.io) if there are more questions @shanebarnes
