### ISSUE TITLE
Streaming into Minio files is very slow

### ISSUE THREAD

**Issue by Non-Descript-Individual** [minio/minio#7729]
Hi all,

I have a Minio server running on one computer B and am practising writing data to it from another computer A. I've been doing some performance tests on streaming arbitrarily sized numpy arrays with random elements from computer A into Minio files hosted on computer B via the Boto3 interface, using the put_object() function of the Boto3 client class, where the "Body" argument is the numpy array converted into bytes using the numpy.to_bytes() function.

At the same time I've been comparing the write speeds of these actions with the write speeds of just using numpy.save() to save the numpy arrays directly to a file on computer B, which is mounted as an NFS on computer A. The write speeds of the Minio/Boto3 approach are far lower than the write speeds achieved by using numpy.save(). A graph is attached showing the trend of the write speeds for files of increasing size, from 8 MB to 800 MB, and this trend continues far beyond these sizes into the 10 GB and 20 GB range.

I'm just wondering how there could possibly be such large differences in write speed and whether I've failed to optimise Minio in any way, or whether Minio is designed in such a way that it would never be expected to equal ordinary write speeds. I followed the standard installation instructions on the website to the letter. The main body of the code used to perform the tests is given below, note the start and end times only wrap around the writing action itself and so nothing else gets included by accident:

```python
tests = 101
s3write = np.empty(tests)
localwrite = np.empty(tests)
s3size = np.empty(tests)
localsize = np.empty(tests)

for i in range(1,tests+1):
    indx = 1000000*i
    rnd = np.random.uniform()
    x = np.random.random([1,indx])
    if rnd < 0.5:
        start = time.time()
        np.save("<PATH>/pylocal%s.npy"%i, x, allow_pickle=False)
        end = time.time()
        localwrite[i-1] = end-start
        statinfo = os.stat("<PATH>/firstbucket/pylocal%s.npy"%i)
        localsize[i-1] = statinfo.st_size
        
        start = time.time()
        s3.put_object(Body=x.tobytes(), Bucket='firstbucket', Key='pyremote%s'%i)
        end = time.time()
        s3write[i-1] = end-start
        statinfo = os.stat("<PATH>/firstbucket/pyremote%s"%i)
        s3size[i-1] = statinfo.st_size
    else:
        start = time.time()
        s3.put_object(Body=x.tobytes(), Bucket='firstbucket', Key='pyremote%s'%i)
        end = time.time()
        s3write[i-1] = end-start
        statinfo = os.stat("<PATH>/firstbucket/pyremote%s"%i)
        s3size[i-1] = statinfo.st_size
        
        start = time.time()
        np.save("<PATH>/firstbucket/pylocal%s.npy"%i, x, allow_pickle=False)
        end = time.time()
        localwrite[i-1] = end-start
        statinfo = os.stat("<PATH>/firstbucket/pylocal%s.npy"%i)
        localsize[i-1] = statinfo.st_size
```

(EDIT: the version of my Minio server is as follows:

Version: 2019-05-23T00:29:34Z

The OS on which the Minio server is running is:

Linux 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)
![Screenshot from 2019-05-31 09-38-41](https://user-images.githubusercontent.com/51129665/58693256-40f37a00-8388-11e9-8d17-ab8088231252.png)

**Comment by nitisht** [comment]
@Non-Descript-Individual can you follow the issue template please? We need info like server version, your hardware setup etc

**Comment by Non-Descript-Individual** [comment]
Sorry - according to Docker (I'm using a Docker image), the version of my Minio server is as follows:

Version: 2019-05-23T00:29:34Z

The OS on which the Minio server is running is:

Linux 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

I'll add this to the original query now.

**Comment by kannappanr** [comment]
@Non-Descript-Individual Can you please provide information like how `MinIO` was started etc. We need to know the command used to start `MinIO`.  What is the network performance here. As much information about the setup would help us here.

**Comment by Non-Descript-Individual** [comment]
@kannappanr The MinIO server was downloaded, installed and started using the following Docker commands:

First:
docker pull minio/minio

Then:
docker run -it -p 0.0.0.0:9000:9000 --name <my_name> -e “MINIO_ACCESS_KEY=ACCESSKEY” -e “MINIO_SECRET_KEY=SECRETKEY” -v <my_path>/data:/data -v <my_path>/config:/root/.minio minio/minio server /data

That was 6 days ago and it has been up and functional ever since. Another interesting thing that happened at the time of initiation (which I did not expect) was that the second command above completely ignored the ACCESSKEY and SECRETKEY parameters that we passed to it, and just generated custom hashes like normal.

**Comment by harshavardhana** [comment]
> Then:
> docker run -it -p 0.0.0.0:9000:9000 --name <my_name> -e “MINIO_ACCESS_KEY=ACCESSKEY” -e “MINIO_SECRET_KEY=SECRETKEY” -v <my_path>/data:/data -v <my_path>/config:/root/.minio minio/minio server /data

Is the path to /data an NFS volume? or a local disk?

**Comment by Non-Descript-Individual** [comment]
The path to /data is an NFS volume. So we would write directly to it as if it were a local path using numpy.save(), and then compare writing to exactly the same location using the Boto3 put_object() function, so that we were comparing like with like.

**Comment by harshavardhana** [comment]
> The path to /data is an NFS volume. So we would write directly to it as if it were a local path using numpy.save(), and then compare writing to exactly the same location using the Boto3 put_object() function, so that we were comparing like with like.

What is the average file size here? @Non-Descript-Individual

**Comment by Non-Descript-Individual** [comment]
As evidenced in the original graph, this appears to apply for all file sizes, anything from 8 MB to 1 GB or more. I have tried it with 5, 10, 20 and 30 GB files as well, and the relationship still holds. So I don't think it would be meaningful for me to give an average file size.

**Comment by harshavardhana** [comment]
> As evidenced in the original graph, this appears to apply for all file sizes, anything from 8 MB to 1 GB or more. I have tried it with 5, 10, 20 and 30 GB files as well, and the relationship still holds. So I don't think it would be meaningful for me to give an average file size.

Have you tried something different from doing 

```
docker run -it -p 0.0.0.0:9000:9000 --name <my_name> -e “MINIO_ACCESS_KEY=ACCESSKEY” -e “MINIO_SECRET_KEY=SECRETKEY” -v <my_path>/data:/data -v <my_path>/config:/root/.minio minio/minio server /data
``` 
v/s just running 

```
./minio server <my_path>/data
```
