### ISSUE TITLE
restarting minio docker container does not re-read event settings properly

### ISSUE THREAD

**Issue by s0rbus** [minio/minio#7731]
## Expected Behavior

When an event has been set for a bucket in minio which is running in docker, and then the docker container is stopped and restarted, I would expect to be able to list and use the event.

## Current Behavior

After the docker container has re-started, an error is generated when trying to list or use the event: mc: <ERROR> Cannot list notifications on the specified bucket. A specified destination ARN does not exist or is not well-formed. Verify the destination ARN.

## Possible Solution

It looks like on restart, notifications.xml is not being re-read, but I don't really know

## Steps to Reproduce (for bugs)

1. docker run --name minio -p 9000:9000 minio/minio server /data
2. set up an event framework as per docs (e.g. kafka)
3. create a bucket as per docs
4. add event to bucket: mc event add  <server/bucket> arn:minio:sqs::1:kafka
5. list event to check OK: mc event list <server/bucket>
6. stop docker: docker stop minio
7. start docker: docker start minio
8. Try and list event again

The only way I could temporarily 'fix' this is to remove the event and add it again.

## Context

Trying to use minio in docker and experiment with events / lambda. I wanted to stop the container and come back to it later. This is when I realised there was a problem. I have discussed this on slack with Anis Elleuch who asked me to raise the issue.

## Regression

No

## Your Environment

* Version used (`minio version`):
Version: 2019-05-23T00:29:34Z
Release-Tag: RELEASE.2019-05-23T00-29-34Z
Commit-ID: e252114f067b07e6c22b91f46a6fa9815450e7a8
* Environment name and version (e.g. nginx 1.9.1):
kafka 2.11, docker 17.05.0-ce
* Operating System and version (`uname -a`):
Ubuntu 16.01 4.4.0-67-generic x86_64
* Link to your project:

**Comment by nitisht** [comment]
> docker run --name minio -p 9000:9000 minio/minio server /data

Do you persist the data using `-v` option @s0rbus? Otherwise data is simply lost as the container dies

**Comment by s0rbus** [comment]
Yes, I forgot to put my -v options in the report, sorry. I have volumes for data and config as per the minio docs. I can look inside there and see the notification.xml for the bucket and it all looks fine

**Comment by nitisht** [comment]
okay, thanks, we'll try to repro this locally

**Comment by vadmeste** [comment]
Taking this

**Comment by vadmeste** [comment]
@s0rbus still not able to reproduce the issue, can you paste logs of your minio container ?

`docker logs minio`

**Comment by s0rbus** [comment]
Sure, here you go. I've also pasted in the notification.xml for my bucket from my docker volume
API: SYSTEM(bucket=barcodes)
Time: 08:05:21 UTC 05/31/2019
Error: ARN 'arn:minio:sqs::1:kafka' not found
       4: cmd/notification.go:943:cmd.readNotificationConfig()
       3: cmd/notification.go:596:cmd.(*NotificationSys).refresh()
       2: cmd/notification.go:625:cmd.(*NotificationSys).Init()
       1: cmd/server-main.go:365:cmd.serverMain()

API: SYSTEM()
Time: 08:05:21 UTC 05/31/2019
Error: ARN 'arn:minio:sqs::1:kafka' not found
       1: cmd/server-main.go:366:cmd.serverMain()
Endpoint:  http://172.17.0.3:9000  http://127.0.0.1:9000

Browser Access:
   http://172.17.0.3:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

API: GetBucketNotification(bucket=barcodes)
Time: 08:05:41 UTC 05/31/2019
RequestID: 15A3B5F0D697DD81
RemoteHost: 172.17.0.1
UserAgent: Minio (linux; amd64) minio-go/v6.0.22 mc/2019-05-23T01:33:27Z
Error: ARN 'arn:minio:sqs::1:kafka' not found
       3: cmd/notification.go:943:cmd.readNotificationConfig()
       2: cmd/bucket-notification-handlers.go:75:cmd.objectAPIHandlers.GetBucketNotificationHandler()
       1: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()

API: GetBucketNotification(bucket=barcodes)
Time: 08:08:45 UTC 05/31/2019
RequestID: 15A3B61B8BC2D10C
RemoteHost: 172.17.0.1
UserAgent: Minio (linux; amd64) minio-go/v6.0.22 mc/2019-05-23T01:33:27Z
Error: ARN 'arn:minio:sqs::1:kafka' not found
       3: cmd/notification.go:943:cmd.readNotificationConfig()
       2: cmd/bucket-notification-handlers.go:75:cmd.objectAPIHandlers.GetBucketNotificationHandler()
       1: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()

API: GetBucketNotification(bucket=barcodes)
Time: 08:17:06 UTC 05/31/2019
RequestID: 15A3B69033824669
RemoteHost: 172.17.0.1
UserAgent: Minio (linux; amd64) minio-go/v6.0.22 mc/2019-05-23T01:33:27Z
Error: ARN 'arn:minio:sqs::1:kafka' not found
       3: cmd/notification.go:943:cmd.readNotificationConfig()
       2: cmd/bucket-notification-handlers.go:75:cmd.objectAPIHandlers.GetBucketNotificationHandler()
       1: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()

=================================================
cat work/minio_data_for_docker/.minio.sys/buckets/barcodes/notification.xml
<NotificationConfiguration><QueueConfiguration><Id></Id><Filter><S3Key></S3Key></Filter><Event>s3:ObjectCreated:*</Event><Event>s3:ObjectRemoved:*</Event><Queue>arn:minio:sqs::1:kafka</Queue></QueueConfiguration></NotificationConfiguration>

**Comment by vadmeste** [comment]
@s0rbus what is the region in your config file ?

`mc admin config get minio/ | jq .region`

**Comment by vadmeste** [comment]
@s0rbus can you also directly check for kafka config directly in work/minio_data_for_docker/.minio.sys/config/config.json ?

`cat work/minio_data_for_docker/.minio.sys/config/config.json | jq .notify.kafka`

**Comment by s0rbus** [comment]
region is an empty string (I thought that was OK from the docs)
kafka config is:
{
  "1": {
    "enable": true,
    "brokers": [
      "172.17.0.1:9092"
    ],
    "topic": "minioevents",
    "tls": {
      "enable": false,
      "skipVerify": false,
      "clientAuth": 0
    },
    "sasl": {
      "enable": false,
      "username": "",
      "password": ""
    }
  }
}

**Comment by vadmeste** [comment]
@s0rbus I am still not able to reproduce this, you must have something different, can you ping me in Slack and set up a remote session, it would be easier to understand what's going on

**Comment by vadmeste** [comment]
@s0rbus can you test with this docker image ? vadmeste/custom-minio, it will print more logs, please ensure that you paste all logs from the beginning.

**Comment by s0rbus** [comment]
i have tried your test image with both new volume dirs and with the volume dirs which seemed to be giving me problems. Both work OK. here are the logs using the existing volume....

[vminio1.logs.txt](https://github.com/minio/minio/files/3251919/vminio1.logs.txt)

**Comment by vadmeste** [comment]
> i have tried your test image with both new volume dirs and with the volume dirs which seemed to be giving me problems. Both work OK. here are the logs using the existing volume....
> 
> [vminio1.logs.txt](https://github.com/minio/minio/files/3251919/vminio1.logs.txt)

Are you saying that using the original image still causing issues ? my image is based on this release RELEASE.2019-05-23T00-29-34Z and it only adds log printing

**Comment by s0rbus** [comment]
No, I am saying that your test image works as expected AND the original image I had also now works as expected. I can only think that something got corrupt in my volume dir which during our experiments got cleared out. I guess we can close this now.

**Comment by vadmeste** [comment]
@s0rbus another possibility is an issue while connecting to the kafka server, I got the same logs as yours yesterday when I had difficulties to connect to my kafka server.

```
API: SYSTEM(bucket=barcodes)
Time: 08:05:21 UTC 05/31/2019
Error: ARN 'arn:minio:sqs::1:kafka' not found
4: cmd/notification.go:943:cmd.readNotificationConfig()
3: cmd/notification.go:596:cmd.(*NotificationSys).refresh()
2: cmd/notification.go:625:cmd.(*NotificationSys).Init()
1: cmd/server-main.go:365:cmd.serverMain()

API: SYSTEM()
Time: 08:05:21 UTC 05/31/2019
Error: ARN 'arn:minio:sqs::1:kafka' not found
1: cmd/server-main.go:366:cmd.serverMain()
Endpoint: http://172.17.0.3:9000 http://127.0.0.1:9000
```

**Comment by s0rbus** [comment]
oh that's interesting. It wasn't obvious that it couldn't connect. Maybe a timing issue?

**Comment by vadmeste** [comment]
yes but it should print a log something like this:

```
API: SYSTEM()
Time: 12:20:37 CET 06/04/2019
Error: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
       3: cmd/config-current.go:673:cmd.getNotificationTargets()
       2: cmd/notification.go:818:cmd.NewNotificationSys()
       1: cmd/server-main.go:362:cmd.serverMain()
```

Let's close this until we see this again.

**Comment by s0rbus** [comment]
Agreed to close since it appears to be intermittent and cannot reliably reproduce.
