### ISSUE TITLE
STS session policies

### ISSUE THREAD

**Issue by adamhooper** [minio/minio#7732]
**Describe the solution you'd like**

I'd like my web app's client side to use `aws-sdk` to upload multipart files to minio, _securely_. I think the best approach is for the AssumeRole API to support [session policies](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html#policies_session).

From my app's perspective, the steps would be:

1. **JS client** requests an STS token from **server**.
2. **server** (minio user `webapp`) authorizes the JS client's request, reserves a key in a bucket, and calls **minio** AssumeRole API with a "session policy" to write a single key.
3. **minio** grants temporary credentials to **server** that only have access to write the single key.
4. **server** forwards the temporary credentials to **JS client**
5. **JS client** uploads with the `aws-sdk` directly to **minio** -- authenticated by the temporary credentials. **minio** would deny access if JS client tried to access anything other than the single key.

**Describe alternatives you've considered**

* [EvaporateJS](https://github.com/TTLabs/EvaporateJS) and [FineUploader S3](https://blog.fineuploader.com/fine-uploader-5-4-aws-s3-version-4-signature-support-f3a3dbadcd05) both implement a workaround: they add a "presign" feature to their multipart logic that hits a special URL on **server**. Both projects give example code for server-side implementations. Unfortunately, their example server-side code presigns _any_ request from JS client. So **JS client** gets the same access to **minio** as **server** does.
* My actual workaround: **JS client** asks **server** for a presigned URL+headers, and then requests from S3 with those URLs.

My workaround fixes the immediate security problem; but it's a ton of work. **JS client** needs a rewritten `aws-sdk` that looks up minio URLs from server; and **server** needs to proxy `create_multipart_upload`+`upload_part`+`abort_multipart_upload`+`complete_multipart_upload`+`put_object`+`delete_object`. Plus, **JS client** ends up sending about double the HTTP requests: each request to **minio** requires a request to **server**.

**Context**

By my reading, session policies seem to be the original motivation behind the AssumeRole API request (https://github.com/minio/minio/issues/6381) and another closed issue (https://github.com/minio/minio/issues/7349)

**Comment by adamhooper** [comment]
@harshavardhana We've finally deployed a commit that uses this feature. Net change: -225 lines of client-side JS and -300 lines of server-side Python code ... with similar reductions in unit-test suites. Plus, STS helps us construct an API we can expose to our customers so they can upload files directly from their own scripts using AWS libraries.

Thank you!

**Comment by harshavardhana** [comment]
That is great @adamhooper
