### ISSUE TITLE
Only first directory is visible as a bucket.

### ISSUE THREAD

**Issue by darkl0rd** [minio/minio#7735]
When running minio against a directory with pre-existing content, only the first directory is visible and accessible as a bucket. The other pre-existing directories are not shown nor accessible.

## Expected Behavior
I would expect that when I run:
```
minio server /data
``` 
that all directories which exist underneath /data are shown as buckets in minio.

## Current Behavior
When I run:
```
mkdir /data/{a,b,c}
minio server /data
```
The UI only shows 'a' as a bucket, b and c are not visible nor are they accessible.

## Steps to Reproduce (for bugs)

1. mkdir /data/{a,b,c}
2. minio server /data
3. open the UI, notice 'a' being a bucket, b and c are missing
4. point your browser to localhost:9000/minio/b explicitly, unable to access b.

## Your Environment
docker 18.09.6
minio:latest (2019-06-01T03:46:14Z)

**Comment by nitisht** [comment]
@darkl0rd what are the names of these pre-existing names of these directories? Note that a bucket name should have at least 3 characters as per S3 Spec

**Comment by darkl0rd** [comment]
@nitisht I was just about to update this issue with that finding. I discovered that when I made the sub-directories at least 3 characters it indeed started working.

Should have read the S3 spec before posting!

**Comment by nitisht** [comment]
thanks @darkl0rd
