### ISSUE TITLE
Minio returning 403 when using a reverse proxy

### ISSUE THREAD

**Issue by depau** [minio/minio#7736]
I'm trying to use Minio as the backing storage for [Pydio Cells](https://github.com/pydio/cells), which is using minio-go ([s3 client source](https://github.com/pydio/cells/blob/dde19a9db2b8acbddaa53cbac49e199c69ffa8ec/data/source/sync/lib/endpoints/client_s3.go)). It mostly works, it is able to store objects.

However I've seen that if I try to download some objects (the issue does not occur with *all* objects, only a few), Minio returns 403 and so does Cells as a result.

I wish I could give you more information, however I have no idea how to detect what's going on other than checking the reverse proxy logs. I'd fire up mitmproxy but I'd like to see if you have some better advice before continuing.

I tried switching to `minio/minio:edge` with no improvements.

Here's some more information on my setup:
- I deployed Minio using docker-compose:

```
version: '3'

services:
  minio1:
    image: minio/minio
    volumes:
      - /srv/docker/volumes/minio:/data
    ports:
      - "127.0.0.1:8010:9000"
    environment:
      MINIO_ACCESS_KEY: [redacted]
      MINIO_SECRET_KEY: [redacted]
    command: server /data
```

- I'm using Nginx as reverse proxy, then CloudFlare on top of it:

```
server {
    server_name minio.redacted.com;
    charset     utf-8;
    client_max_body_size 0;

    location / {
        proxy_pass http://localhost:8010/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    listen 443 ssl; # managed by Certbot

    ssl_certificate /path/to/cert.pem;
    ssl_certificate_key /path/to/privkey.pem;

    if ($scheme != "https") {
        return 301 https://$host$request_uri;
    } # managed by Certbot
}

server {
    if ($host = minio.redacted.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name minio.redacted.com;
    return 404; # managed by Certbot
}
```

- The Nginx error log is full of stuff like this:
```
2019/06/02 20:09:46 [error] 22818#22818: *2364 connect() failed (111: Connection refused) while connecting to upstream, client: x.x.102.240, server: minio.redacted.com, request: "GET /cells-personal/depau/document.pdf HTTP/1.1", upstream: "http://[::1]:8010/cells-personal/depau/document.pdf", host: "minio.redacted.com"
2019/06/02 20:09:46 [warn] 22818#22818: *2364 upstream server temporarily disabled while connecting to upstream, client: x.x.102.240, server: minio.redacted.com, request: "GET /cells-personal/depau/document.pdf HTTP/1.1", upstream: "http://[::1]:8010/cells-personal/depau/document.pdf", host: "minio.redacted.com"
...
2019/06/02 22:07:32 [error] 22818#22818: *3340 upstream timed out (110: Connection timed out) while reading upstream, client: x.x.103.169, server: minio.redacted.com, request: "GET /cells-personal/?policy= HTTP/1.1", upstream: "http://127.0.0.1:8010/cells-personal/?policy=", host: "minio.redacted.com"
2019/06/02 22:08:33 [error] 22818#22818: *3348 upstream timed out (110: Connection timed out) while reading upstream, client: x.x.102.180, server: minio.redacted.com, request: "GET /cells-pydiods/?policy= HTTP/1.1", upstream: "http://127.0.0.1:8010/cells-pydiods/?policy=", host: "minio.redacted.com"
2019/06/02 22:11:32 [error] 22818#22818: *3352 connect() failed (111: Connection refused) while connecting to upstream, client: x.x.198.8, server: minio.redacted.com, request: "GET / HTTP/1.1", upstream: "http://[::1]:8010/", host: "minio.redacted.com"
2019/06/02 22:11:32 [warn] 22818#22818: *3352 upstream server temporarily disabled while connecting to upstream, client: x.x.198.8, server: minio.redacted.com, request: "GET / HTTP/1.1", upstream: "http://[::1]:8010/", host: "minio.redacted.com"
```

I think it's either a problem with minio or my nginx config (as opposed to being a problem with Pydio Cells) because I also have issues with `mc` (i.e. `watch` doesn't work, some admin commands also return 403 Unauthorized). Minio's webui works fine.

Do you have any ideas to help me troubleshoot this?

**Comment by harshavardhana** [comment]
https://docs.min.io/docs/setup-nginx-proxy-with-minio.html only difference I see is in your nginx config and our docs is the `http 1.1` can you enable that ?

**Comment by depau** [comment]
Hi, thank you.

I added the http 1.1 parameter and also some others I had missed. Still 403.

**Comment by kannappanr** [comment]
@Depau Can you try connecting to `MinIO` directly instead of through `Nginx`, that will tell you if it is Nginx or MinIO. Also, the errors you are seeing, are they consistent or are they intermittent. What `mc` admin commands are you trying?

**Comment by depau** [comment]
Hi, I tried connecting to it directly. Still 403.

`mc` commands that don't work:
- `mc admin heal` (405 Method not allowed)
- `mc admin top locks` (405)
- `mc watch` times out with nginx (it does not directly, however authorization errors are not reported)

Other commands seem to work fine.

**Comment by kannappanr** [comment]
@Depau Those admin commands will not work with MinIO started in file system mode. So, that is working as expected. Can you give an example or two of `mc` commands that do not work when you connect directly to `MinIO`?

**Comment by depau** [comment]
The other commands seem to work, so maybe that's not the problem.

Anyway, is there a way to make Minio more explicit on authorization error causes? I've used Google Cloud Storage before and it would tell me precisely what I was doing wrong and what it was expecting in the error response. Is there a way to enable this in Minio with the current releases? How hard would it be to implement it?

**Comment by depau** [comment]
I forgot to answer this one

> Also, the errors you are seeing, are they consistent or are they intermittent[?]

They are consistent. If I try to download some files through Pydio Cells it works. for some other files I get 403. Behavior is consistent: some objects always return 200, others always return 403.

**Comment by vadmeste** [comment]
@Depau did you create any users in Minio server ?

Did you set any custom policy in the bucket ? `mc policy your-alias/your-bucket`

**Comment by depau** [comment]
@vadmeste I did create one user while trying to troubleshoot the issue but I've always used the main credentials (the ones set in the environment) to access the buckets.

```
$ mc policy min/cells-personal
Access permission for `min/cells-personal` is `none`
$ mc policy min/cells-data
Access permission for `min/cells-data` is `none`
$ mc policy min/cells-pydiods
Access permission for `min/cells-pydiods` is `none`
```

**Comment by vadmeste** [comment]
@Depau do you see any logs in Minio server when you run the mc command that leads to 403 error ?

also can you run mc with --debug flag and paste the debug output ?

**Comment by depau** [comment]
Nope, I only have this in the logs:

```
minio1_1  |
minio1_1  | Endpoint:  http://172.20.0.2:9000  http://127.0.0.1:9000
minio1_1  |
minio1_1  | Browser Access:
minio1_1  |    http://172.20.0.2:9000  http://127.0.0.1:9000
minio1_1  |
minio1_1  | Object API (Amazon S3 compatible):
minio1_1  |    Go:         https://docs.min.io/docs/golang-client-quickstart-guide
minio1_1  |    Java:       https://docs.min.io/docs/java-client-quickstart-guide
minio1_1  |    Python:     https://docs.min.io/docs/python-client-quickstart-guide
minio1_1  |    JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
minio1_1  |    .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
```

I don't see how running `mc` with `--debug` would be useful: @kannappanr said that failing admin commands were working as intended. I'm only getting 403 errors when requesting objects through Pydio Cells. Which is why I asked whether there was a better debugging option other than putting a mitm proxy between Pydio and Minio.

Anyway this is the policy command with `--debug` in case that's useful:

```
$ mc policy --debug min/cells-personal                                                                                                     
mc: <DEBUG> GET /cells-personal/?location= HTTP/1.1
Host: localhost:8010
User-Agent: MinIO (linux; amd64) minio-go/v6.0.26 mc/2019-05-29T21:21:34Z
Authorization: AWS4-HMAC-SHA256 Credential=[redacted]/20190604/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190604T124740Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 04 Jun 2019 12:47:40 GMT
Server: MinIO/DEVELOPMENT.2019-06-01T05-24-55Z
Vary: Origin
X-Amz-Request-Id: 15A4FFA65B88F53B
X-Minio-Deployment-Id: 21f6c320-014c-4860-a4dc-f846ffb4b48e
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  9.869972ms

mc: <DEBUG> GET /cells-personal/?policy= HTTP/1.1
Host: localhost:8010
User-Agent: MinIO (linux; amd64) minio-go/v6.0.26 mc/2019-05-29T21:21:34Z
Authorization: AWS4-HMAC-SHA256 Credential=[redacted]/20190604/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190604T124740Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 04 Jun 2019 12:47:40 GMT
Server: MinIO/DEVELOPMENT.2019-06-01T05-24-55Z
Vary: Origin
X-Amz-Request-Id: 15A4FFA65C06B8FA
X-Minio-Deployment-Id: 21f6c320-014c-4860-a4dc-f846ffb4b48e
X-Xss-Protection: 1; mode=block

130
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucketPolicy</Code><Message>The bucket policy does not exist</Message><BucketName>cells-personal</BucketName><Resource>/cells-personal/</Resource><RequestId>15A4FFA65C06B8FA</RequestId><HostId>21f6c320-014c-4860-a4dc-f846ffb4b48e</HostId></Error>
0

mc: <DEBUG> Response Time:  8.340796ms

Access permission for `min/cells-personal` is `none`
```

**Comment by vadmeste** [comment]
@Depau oh okay, I thought you said you are also not able to download using mc. You can set this environment variable MINIO_HTTP_TRACE to /tmp/log.txt for example in your docker compose, and invoke the Pydio Cells action that triggers the 403 error.

**Comment by depau** [comment]
Great! I am indeed able to see errors there. Apparently it's signing the request incorrectly:

```
[REQUEST objectAPIHandlers.GetObjectHandler-fm] [155972871.067774] [2019-06-05 09:58:30 +0000]
GET /cells-personal/depau/document.pdf
Host: [redacted]
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Cdn-Loop: cloudflare
X-Forwarded-For: [redacted]
Accept-Encoding: gzip
X-Amz-Date: 20190605T095830Z
Cf-Visitor: {"scheme":"https"}
User-Agent: Minio (linux; amd64) minio-go/v6.0.11
Cf-Connecting-Ip: [redacted]
Connection: close
X-Forwarded-Proto: https
Cf-Ray: 4e214aae28f0d61c-MXP
Authorization: AWS4-HMAC-SHA256 Credential=[redacted]/20190605/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=9b56984a47214ccef982db80e5c98ef5527b3e9ecfd356effc99cdedd6ee6520
X-Real-Ip: [redacted]
Cf-Ipcountry: IT

<BODY>

[RESPONSE] [155972871.067774] [2019-06-05 09:58:30 +0000]
403 Forbidden
X-Minio-Deployment-Id: 21f6c320-014c-4860-a4dc-f846ffb4b48e
Server: MinIO/DEVELOPMENT.2019-06-01T05-24-55Z
Accept-Ranges: bytes
Content-Type: application/xml
Vary: Origin
X-Xss-Protection: 1; mode=block
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 15A544FFA16B3D2C
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>SignatureDoesNotMatch</Code>
  <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
  <Key>depau/document.pdf</Key>
  <BucketName>cells-personal</BucketName>
  <Resource>/cells-personal/depau/document.pdf</Resource>
  <RequestId>15A544FFA16B3D2C</RequestId>
  <HostId>21f6c320-014c-4860-a4dc-f846ffb4b48e</HostId>
</Error>
```

For whatever reason it's still using the reverse-proxy even though I though I configured it to skip it. I'll do some more tests skipping it and see if that's the problem.

Eventually I'll need to figure out if it's nginx/cloudflare that's changing the signed headers or if it's using `minio-go` incorrectly.

**Comment by depau** [comment]
Okay, it was still using the reverse-proxy because I forgot to restart it and it was using the old config. Now it works perfectly.

```
[REQUEST objectAPIHandlers.GetObjectHandler-fm] [155972947.213555] [2019-06-05 10:11:12 +0000]
GET /cells-personal/depau/document.pdf
Host: 192.168.3.10:8010
User-Agent: Minio (linux; amd64) minio-go/v6.0.11
Authorization: AWS4-HMAC-SHA256 Credential=[redacted]/20190605/us-east-1/s3/aws4_request, SignedHeaders=host;range;x-amz-content-sha256;x-amz-date, Signature=f606f50083e7a8c9961bbb8cf6de704051d3d1a3a499fed9bf82f19034fca753
Range: bytes=0-188576
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190605T101112Z

<BODY>
```

Now, why is it not working when going through the reverse proxy? All signed headers are there.

**Comment by vadmeste** [comment]
@Depau, your nginx file seems to be fine.

Can you try with mc first ? I mean can you make your mc points to your reverse proxy and see if it works ?

**Comment by kannappanr** [comment]
@Depau closing this as stale. Please feel free to reach out to us with the information requested by @vadmeste  we can start investigating as to why the reverse proxy is causing this issue

**Comment by fzxu** [comment]
I can confirm that even `mc stat` does not work with nginx in front. it works without it. any clue?

**Comment by harshavardhana** [comment]
> I can confirm that even `mc stat` does not work with nginx in front. it works without it. any clue?

https://docs.min.io/docs/setup-nginx-proxy-with-minio.html make sure to make the following changes.

**Comment by harshavardhana** [comment]
> I can confirm that even `mc stat` does not work with nginx in front. it works without it. any clue?

also avoid talking on old issues - open a discussion https://github.com/minio/minio/discussions
