### ISSUE TITLE
Configure region in minio gateway without s3:GetBucketLocation

### ISSUE THREAD

**Issue by thefiddler** [minio/minio#7737]
**Is your feature request related to a problem? Please describe.**
According to @vadmeste, minio gateway currently requires the s3:GetBucketLocation permission. Imagine the following scenario:

1. you are using minio in a tightened environment set up by a 3rd-party, i.e. you cannot modify permissions
2. s3:GetBucketLocation is not available
3. you know a priori the bucket ARN and region

In this scenario, minio defaults to us-east-1 and it does not seem to be possible to override that in configuration:

```bash
$ minio gateway s3 https://[bucket name].s3.eu-west-1.amazonaws.com
ERROR Unable to initialize gateway backend: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'
```

**Describe the solution you'd like**
Ideally, we should be able to override the default minio gateway region using `MINIO_REGION="eu-west-1"`, similar to minio server.

**Describe alternatives you've considered**
We also tried to modify the global variables and recompile minio but it still fails with the same error as above.

**Comment by kannappanr** [comment]
@thefiddler Will send a fix to `minio-go` to retry in the `BucketExists` call in `minio-go`. We are also looking at not making the `HeadBucket` call. So, you might be able to start gateway without that permission. For other situations like, make bucket, you can send the region. So, we don't see any scenario where you might have to set the `MINIO_REGION` env. variable in the case of MinIO

**Comment by thefiddler** [comment]
>  For other situations like, make bucket, you can send the region. So, we don't see any scenario where you might have to set the MINIO_REGION env. variable in the case of MinIO

Just to clarify, that means that the following is expected to work?
```bash
$ minio gateway s3 https://[bucket name].s3.eu-west-1.amazonaws.com
ERROR Unable to initialize gateway backend: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'
```

Is the command above the right way to initialize minio gateway to a specific region and bucket? On current master it seems minio gateway is setting us-east-1 in the request header, even when we set the region to eu-west-1 explicitly.

(This occurs when s3:GetBucketLocation is not permitted).

Edit: @kannappanr is there a way to hardcode eu-west-1 and rebuild minio so we can work around this issue until the next official release? We tried to modify every instance of us-east-1, but this didn't seem to help.

**Comment by vadmeste** [comment]
@thefiddler actually I think you can try this command:

`minio gateway s3 https://s3.eu-west-1.amazonaws.com`

It doesn't make any get bucket location

```
12:27 $ minio gateway s3 https://s3.eu-west-1.amazonaws.com
---------START-HTTP---------
HEAD / HTTP/1.1
Host: probe-bucket-sign-09dn1ajhooqm.s3.dualstack.eu-west-1.amazonaws.com
User-Agent: Minio (linux; amd64) minio-go/v6.0.22
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20190603/eu-west-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190603T112741Z

HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Mon, 03 Jun 2019 11:27:42 GMT
Server: AmazonS3
X-Amz-Id-2: Ou339LYZP2V0dHSQTDvj07e+rd+POKB+UleHPYcSccV7RS3x3inwEZumfRfSBwDA4yQwPfwEWW4=
X-Amz-Request-Id: 29CABF78780DE6F3

---------END-HTTP---------

...

```

But then, your S3 client needs to explicitly set a specific region if you still want it

**Comment by thefiddler** [comment]
@vadmeste thanks, this seems to work around the GetBucketLocation issue.

We still need to connect to a specific bucket as suggested by @harshavardhana in https://github.com/minio/minio/issues/7696#issuecomment-496282459

> Also adding a bucket level gateway is quite easy to do as well.
> 
> It would be as good as providing https://bucket.s3.amazonaws.com

What would be the right way to hardcode both the bucket and region? I haven't been able to find this in the documentation.

**Comment by vadmeste** [comment]
> We still need to connect to a specific bucket

Why would you need that ?

**Comment by thefiddler** [comment]
@vadmeste Because we do not have s3:ListAllMyBuckets and that seems to lead to Access Denied errors when trying to connect with mc or otherwise. The suggested workaround in https://github.com/minio/minio/issues/7696#issuecomment-496282459 was to initialize the gateway to a specific bucket.

If I do try to initialize `minio gateway s3 https://s3.eu-west-1.amazonaws.com` and try to configure mc using the string provided by the gateway, I get an access denied error:

```bash
$ mc config host add mys3 http://[ip]:9000 [key] [secret]
mc: <ERROR> Unable to initialize new config file from the provided credentials. Access Denied.
```

I have verified that the key and secret used in mc are correct. Maybe mc is trying to use us-east-1 by default too and failing?

Edit:
The `minio gateway` above keeps repeating the following error:

<img width="555" alt="Screenshot 2019-06-03 at 16 34 25" src="https://user-images.githubusercontent.com/3104289/58810126-96948480-861d-11e9-89e4-9adc9e41bc2a.png">

This seems to fit under the discussion in #7696.

**Comment by harshavardhana** [comment]
This issue is fixed in multiple iterations to minio-go , closing this issue. Feel free to reopen if seen again.
