### ISSUE TITLE
Docker Stack: `global` deployment fails

### ISSUE THREAD

**Issue by mrusme** [minio/minio#7738]
Minio fails to start when trying to deploy through Docker Stack file as `global` instance.

## Expected Behavior
A single instance of Minio should become available inside the Docker Stack.

## Current Behavior
Minio instance won't become available inside the Docker Stack.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. Create a Docker Stack file, [example](https://github.com/paperwork/paperwork/blob/5b63a892696328dd3e4fecdbcedabe4e6033d633/paperwork.yml)
2. Add Minio as global instance, [example](https://github.com/paperwork/paperwork/blob/5b63a892696328dd3e4fecdbcedabe4e6033d633/paperwork.yml#L83)
3. Deploy the stack using `docker stack deploy --orchestrator=${ORCHESTRATOR} --prune --compose-file ${COMPOSE_FILE} ${STACK_NAME}`
4. Check `docker service ls` and see that Minio will first show `0/1` and after the timeout `0/0`.

## Context
At this moment it's not possible for me to use Minio in the demonstration stack linked above.

## Regression
N/A

## Your Environment
* Version used (`minio version`): minio:latest
* Environment name and version (e.g. nginx 1.9.1): N/A
* Server type and version: Docker version 18.09.2, build 6247962
* Operating System and version (`uname -a`): Darwin Kernel Version 18.6.0
* Link to your project: [https://github.com/paperwork/paperwork](https://github.com/paperwork/paperwork)

**Comment by nitisht** [comment]
can you paste the exact error you see via Docker logs @mrusme

**Comment by mrusme** [comment]
@nitisht I would love to, unfortunately I do not get any log output out of this service. It simply won't start, without any output at all. Tried all sorts of things, e.g. `docker service logs -f ...` but everything remained silent. Any idea on how I could investigate this issue further?

**Comment by nitisht** [comment]
Can you try the yaml file from our documentation and see if that works in your setup? Docs are here: https://docs.min.io/docs/deploy-minio-on-docker-compose.html

**Comment by mrusme** [comment]
@nitisht that won't help as your yaml does not configure the Minio containers to run in global mode, which seems to be the only difference. When I run Minio manually with `docker run` everything works fine. And I also believe you when you say that your yaml file works. However, it does not solve this specific issue, where Minio doesn't seem to run in `global` mode.

**Comment by nitisht** [comment]
can you try `docker service inspect`?

**Comment by mrusme** [comment]
@nitisht sure, here:

```
(local) (master)⚡ % docker service inspect  paperwork_service_storages_backend
[
    {
        "ID": "ytj2y3e3ozpp1dz5qs582yos0",
        "Version": {
            "Index": 3097
        },
        "CreatedAt": "2019-06-03T14:20:19.9084691Z",
        "UpdatedAt": "2019-06-03T14:20:19.9125727Z",
        "Spec": {
            "Name": "paperwork_service_storages_backend",
            "Labels": {
                "com.docker.stack.image": "minio:latest",
                "com.docker.stack.namespace": "paperwork"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "minio:latest",
                    "Labels": {
                        "com.docker.stack.namespace": "paperwork"
                    },
                    "Args": [
                        "server",
                        "--address",
                        ":8080",
                        "/data"
                    ],
                    "Env": [
                        "MINIO_ACCESS_KEY=root",
                        "MINIO_SECRET_KEY=roooooot"
                    ],
                    "Privileges": {
                        "CredentialSpec": null,
                        "SELinuxContext": null
                    },
                    "Mounts": [
                        {
                            "Type": "bind",
                            "Source": "/Projects/@paperwork/paperwork/volumes/minio",
                            "Target": "/data/db"
                        }
                    ],
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {},
                    "Isolation": "default"
                },
                "Resources": {},
                "RestartPolicy": {
                    "Condition": "on-failure",
                    "Delay": 10000000000,
                    "MaxAttempts": 3,
                    "Window": 360000000000
                },
                "Placement": {},
                "Networks": [
                    {
                        "Target": "rxjrucgei0zi9ycdybxjva1ca",
                        "Aliases": [
                            "service_storages_backend"
                        ]
                    }
                ],
                "ForceUpdate": 0,
                "Runtime": "container"
            },
            "Mode": {
                "Global": {}
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "RollbackConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "EndpointSpec": {
                "Mode": "vip"
            }
        },
        "Endpoint": {
            "Spec": {
                "Mode": "vip"
            },
            "VirtualIPs": [
                {
                    "NetworkID": "rxjrucgei0zi9ycdybxjva1ca",
                    "Addr": "10.0.11.2/24"
                }
            ]
        }
    }
]
```

**Comment by mrusme** [comment]
Found out what it was by checking the inspect output a second time. Thanks @nitisht! I hate Docker for the way it treats images that do not exist - by simply not outputting any error whatsoever.

The issue was that my Compose file had `minio:latest` specified, instead of `minio/minio:latest`. It really doesn't help that Docker's Registry treats some images as first-class-citizens (e.g. `rabbitmq:latest`), while others have an organisation prefixed to it.

The only command that would throw an error in such a case apparently is `docker service update paperwork_service_storages_backend`.

Never mind, thank you for helping. I will check the Docker issues for a similar issue and otherwise create one to point out the terrible error-reporting.
