### ISSUE TITLE
How to setup HA Cluster with MS DFS?

### ISSUE THREAD

**Issue by michalss** [minio/minio#7739]
Hi team,
Is there any tutorial how to setup HA cluster with using Windows DFS, where only is Master and has all disk attached. I can install minio on both nodes, but what happend when i do failover to other nod, what happend then..

**Comment by kannappanr** [comment]
@michalss Can you please give more info? I understand that you have two nodes. Can you type in the commands that you used to start `MinIO` on both nodes and elaborate more on the failover part?

**Comment by michalss** [comment]
Hi setup is easy. 2 nodes Windows DFS, where only 1 has attached all shared disks/DFS shares a time. This is how DFS generally works. Once you do failover to the other nod, this a new master take all DFS share with it. Means that only 1 server, from CLuster can have attache DFS share. My question was, how to setup/install minio in HA mod to work with windows DFS.  Thx

**Comment by eco-minio** [comment]
@michalss Assuming you are using minio in gateway mode, then DFS (or attendant load balancer) would be responsible for handling failover.  This would not work with minio in server mode.

**Comment by michalss** [comment]
Hi, no im not running minio at all. im looking for the way how to configure it with Windows DFS Cluster, thats all.

**Comment by harshavardhana** [comment]
> Hi, no im not running minio at all. im looking for the way how to configure with Windows DFS Cluster, thats all.

@michalss There is nothing special all you have to do is 

```
minio gateway nas \\<domainname>\<dfsroot>
```

or
 
```
minio gateway nas \\<FQDN>\<dfsroot>
```

If do `net share` mount then you can specify as well. 

```
minio gateway nas Z:\
```

**Comment by michalss** [comment]
@harshavardhana - thank you, and what happen when i do failover to other nod ? Also minio will run on both nodes with same configuration?

**Comment by harshavardhana** [comment]
> @harshavardhana - thank you, and what happen when i do failover to other nod ? Also minio will run on both nodes with same configuration?

You are running `minio gateway` on all servers in the same manner as posted above, and you can bring as many gateways as you want online whenever needed. Gateway is a share nothing architecture they can independently serve concurrent requests. 

All you have to do is just run `minio gateway` on all DFS servers and have a round-robin DNS / fqdn for ll gateway instances or load balance them.

**Comment by michalss** [comment]
On nice, DFS has own clustering system, quorum. So basically it would be enough to simple install minio with gw and fqdn share on both nodes with acting as same right ? but dfs share is always active if any of this 2 nodes running. Would not cause some issue to run minio on both nodes same time ? So this is the case, so it is needed to use some proxy to balance to run minio in this case ?

**Comment by harshavardhana** [comment]
> On nice, DFS has own clustering system, quorum. So basically it would be enough to simple install minio with gw and fqdn share on both nodes with acting as same right ? but dfs share is always active if any of this 2 nodes running. Would not cause some issue to run minio on both nodes same time ? So this is the case, so it is needed to use some proxy to balance to run minio in this case ?

NAS Gateway is designed for exactly this scenario.

**Comment by harshavardhana** [comment]
Closing this as answered, feel free to join our https://slack.min.io for further questions.
