### ISSUE TITLE
Minio server is not starting

### ISSUE THREAD

**Issue by demon-36** [minio/minio#7740]
## Expected Behavior

While installing Minio on ubuntu, at the time of running Minio server it should start Minio server as it starts in Docker

## Current Behavior

Currently after executing required command it gives this error :
`ERROR : Unable to initialize backend: Unable to write to the backend.
                 > Please ensure MinIO binary has write permissions for the backend.
`

## Steps to Reproduce (for bugs)

Followed the documented steps to install and run Minio and executed this commands in terminal
1. `wget https://dl.min.io/server/minio/release/linux-amd64/minio`
2. `chmod +x minio`
3. `./minio server /data`

**Comment by nitisht** [comment]
does the user running MinIO has write permissions on `/data`?

**Comment by demon-36** [comment]
@nitisht thanks for responding, I'm running this commands as sudo and I'm new to Minio so don't know a lot about it :(

**Comment by nitisht** [comment]
> I'm running this commands as sudo

Can you try writing in a non-root writeable directory like `/home/<your-username>/data` and run as normal user

**Comment by demon-36** [comment]
@nitisht  sir I tried earlier to find /data directory but it says `/home/pb/data: No such file or directory`

**Comment by nitisht** [comment]
Please join us on Slack (https://slack.minio.io) we can discuss real time..

**Comment by demon-36** [comment]
Sir I've already posted it there :)

**Comment by demon-36** [comment]
thanks a lot sir for your time and appreciation.

**Comment by yhyddr** [comment]
Is there any new progress? Meet the same problem.
