### ISSUE TITLE
Unable to delete buckets after upgrading minio (Federated minio setup)

### ISSUE THREAD

**Issue by adiospeds** [minio/minio#7741]
Note: I'm using federated minio setup 

After upgrading to the below minio version I was able to create buckets, however I was not able to delete these buckets (or upload any objects to the buckets)

Version being used:
```
Version: 2019-06-01T03:46:14Z
Release-Tag: RELEASE.2019-06-01T03-46-14Z
Commit-ID: 1cfd4a48d9f9026a7f58f92ffb9a691773392b5d
root@prod-sc-minio-netops-netflow-server-01:~#
```

when I try to delete that bucket
I show's me this error
`No entries found for this key`

here's what the logs say
```
Jun  3 14:53:20 prod-sc-minio-netops-netflow-server-01 minio[18793]: API: SYSTEM()
Jun  3 14:53:20 prod-sc-minio-netops-netflow-server-01 minio[18793]: Time: 14:53:20 UTC 06/03/2019
Jun  3 14:53:20 prod-sc-minio-netops-netflow-server-01 minio[18793]: Error: No entries found for this key
Jun  3 14:53:20 prod-sc-minio-netops-netflow-server-01 minio[18793]:        3: cmd/web-handlers.go:1976:cmd.toWebAPIError()
Jun  3 14:53:20 prod-sc-minio-netops-netflow-server-01 minio[18793]:        2: cmd/web-handlers.go:1856:cmd.toJSONError()
Jun  3 14:53:20 prod-sc-minio-netops-netflow-server-01 minio[18793]:        1: cmd/web-handlers.go:273:cmd.(*webAPIHandlers).DeleteBucket()
```

 I used the minio gui to delete it

```
─○ aws s3 mb s3://demo02 --endpoint-url=http://proj.prod-sc.s3.domain.com --no-verify-ssl --profile proj
make_bucket: demo02
```
had created the bucket using aws cli and echo $? was 0

```
ls -l /mnt/data-01/
total 0
drwxr-xr-x 2 minio minio  6 Jun  3 14:53 demo02
drwxr-xr-x 4 minio minio 32 May 31 22:54 netflow
```
I also see that the folder for the bucket is created on all minio servers

```
etcdctl get --keys-only --prefix /skydns
/skydns/com/domain/s3/prod-sc/proj/10.11.12.13

/skydns/com/domain/s3/prod-sc/proj/demo02/10.11.12.13

/skydns/com/domain/s3/prod-sc/proj/netflow/10.11.12.13
```
etcd entry is created inside all etcd servers

and coredns server is able to resolve the bucket
```
dig +short @localhost demo02.proj.prod-sc.s3.domain.com
10.11.12.13
```

Convo with @vadmeste on slack
> Anis Elleuch   [1 hour ago]
> I will try this locally right now and update you @apednekar
> 
> Aditya Pednekar   [1 hour ago]
> cool .. Ichking etcd logs in the mean time - will keep you posted
> 
> Aditya Pednekar   [1 hour ago]
> just a wild guess, issue could be bcas of this patch that had fixed my another issue
> 
> Aditya Pednekar   [1 hour ago]
> https://github.com/minio/minio/pull/7699
> GitHub
> Skip non-bucket DNS entry by harshavardhana · Pull Request #7699 · minio/minio
> Description Skip non-bucket DNS entry Motivation and Context Fixes #7697 Regression Yes perhaps in 4c04896 How Has This Been Tested? Using a local etcd setup and bucket population Types of ...
> 
> Aditya Pednekar   [1 hour ago]
> probably hitting this code when trying to delete buckets
>     ```if srvRecord.Key == "" || srvRecord.Key == etcdPathSeparator {
>             continue
>         }```
> (edited)
> 
> Aditya Pednekar   [1 hour ago]
> after downgrading to minio version Version: 2019-04-18T21:44:59Z, i was able to delete the bucket
> 
> Aditya Pednekar   [1 hour ago]
> this was our previous minio version being used in prod (edited)
> 
> Aditya Pednekar   [1 hour ago]
> this means there was no issue on the etcd or coredns servers - its the new minio code
> 
> Anis Elleuch   [14 minutes ago]
> I can confirm this is reproducible.. can you open a new issue @apednekar?
> 
> Aditya Pednekar   [13 minutes ago]
> yus ..
>

**Comment by harshavardhana** [comment]
@adiospeds thanks let us fix it.
