### ISSUE TITLE
[gateway-gcs] unauth'd object downloads and permissions

### ISSUE THREAD

**Issue by verdverm** [minio/minio#7745]
## Expected Behavior

I should be able to provide unauthenticated object downloads without allowing bucket listing.

## Current Behavior

In order to provide unsigned downloads, the user is instructed to run `mc policy download host/bucket`. This applies the GCS permission "Storage Legacy Bucket Viewer" to "allUsers". This, in turn, allows anyone to list all objects in the bucket.

Setting the GCS permissions to "Storage Legacy Object Viewer" fixes the listing issues, but causes Minio to redirect the request with the `/minio` prefix, due to wanting to sign downloads again.

The GCP service account has full "Storage Admin" permissions. This seems to be an issue with the bucket "allUsers" permission and determining whether a download should require a signed URL or not.

## Possible Solution

Add subcommand, code logic, and/or instructions for switching to Object Viewer, rather than requiring the Bucket Viewer permission.

## Steps to Reproduce (for bugs)

1. Setup GCS Bucket and Minio GCS Gateway as normal
2. Change the bucket policy with `mc policy download host/bucket`
3. Download an object unauthed, list the bucket unauthd. (from storage.googleapis.com and the minio gateway)
4. Change the "allUsers" permission in GCS to use "Storage Legacy Object Viewer" (`s/Bucket/Object/`)
5. View the object through google, ensure bucket is not listable
6. See that the unauth'd download of objects no longer works through minio

## Context

- We are migrating from AWS & S3 to GCP / GKE / GCS.
- We have S3 buckets (now in GCS with this gateway) that contain images for emails and reports.
- The images should be publicly accessible, but the bucket should not be listable, as images could contain sensitive information. These images have random names, so we are ok with the public download without listing capabilities (this is how AWS S3 is setup).
- minio-gatewat-gcs is  a drop in replacement for us, barring this issue. (thanks for the great work!)

This prevents our full migration from S3 to GCS, the last piece of the puzzle.

## Regression

No

## Your Environment

Minio Version: RELEASE.2019-05-23T00-29-34Z

Env:
- GCP, GKE, GCS
- k8s 1.12 with nginx ingress
- minio-gateway-gcs with a service account having full storage admin access
- ingress setup to point 3 buckets at minio by `/bucket-name-1`
- applications use the s3 endpoint to aim at minio-gcs-gateway k8s-service

**Comment by harshavardhana** [comment]
Recent release fixes this, have you tried it already?

**Comment by verdverm** [comment]
oh really?! I will give that a try and close this issue if the problem goes away.

**Comment by verdverm** [comment]
I am still experiencing this issue with Minio: RELEASE.2019-06-04T01-15-58Z

**Comment by verdverm** [comment]
https://github.com/minio/minio/blob/master/cmd/gateway/gcs/gateway-gcs.go#L1395 leads me to believe that new code is needed.

Unless... it is possible to set the bucket permissions "by hand" (w/o `mc`) and the files should be served w/o signed URLs

**Comment by leifcr** [comment]
Currently minio supports these out of the box:
* **ReadOnly** - All clients can browse + download any object without authorization 
* **WriteOnly** - All clients can write but not read objects without authorization 
* **Read+Write** - All clients can do anything without authorization 
* **None** - Only authenticated requests

It would be awesome if a new policy was implemented
* **Download** - All clients can download, but not browse without authorization.

**Comment by string-areeb** [comment]
`./mc policy set download minio/<bucket>/`

Sets download policy but any user can list the items

**Comment by harshavardhana** [comment]
Construct a custom policy and use `mc policy set-json `  to set appropriate permissions

**Comment by string-areeb** [comment]
That is definitely doable, means `has a workaround`. But it is not a solution to the most common use case for storing user media on S3/minio

**Comment by harshavardhana** [comment]
This is the solution not a workaround, we can't keep adding new canned policies to satisfy all use cases. 

The list is quite long and not all such policies are common - set-json is present for this reason alone, for you to provide us your favorite policy.

**Comment by harshavardhana** [comment]
Closing this gateway issue to be done as a future milestone.
