### ISSUE TITLE
[resolved] feature req - s3 gateway without s3:HeadBucket

### ISSUE THREAD

**Issue by tooptoop4** [minio/minio#7765]
**Is your feature request related to a problem? Please describe.**
My organisation does not allow s3:HeadBucket access as different teams share the same root bucket but instead have different slices. ie team1 gets bucket123/team1/.../ and team2 gets bucket123/team2/.../

**Describe the solution you'd like**
I would like minio s3 gateway to be able to read s3 objects from bucket123/team1/.../ onwards as my IAM user access/secret key has that access even though the IAM user does not have access from the root of the bucket. ie without needing s3:HeadBucket priv

**Describe alternatives you've considered**

**Additional context**

docker run -it --rm -p 10015:9000 -e "MINIO_ACCESS_KEY=x" -e "MINIO_SECRET_KEY=y" -e "MINIO_REGION=eu-west-1" minio/minio minio gateway s3 https://s3.eu-west-1.amazonaws.com

API: SYSTEM()
Time: 21:42:28 UTC 06/09/2019
Error: Prefix access is denied: /
       2: cmd/policy.go:117:cmd.(*PolicySys).refresh()
       1: cmd/policy.go:169:cmd.(*PolicySys).Init()
Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000
AccessKey: x
SecretKey: y

Browser Access:
   http://172.17.0.2:9000  http://127.0.0.1:9000

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc config host add mys3 http://172.17.0.2:9000 x y

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

API: webListBuckets()
Time: 21:43:10 UTC 06/09/2019
RemoteHost: xxxx
UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/xxx Safari/537.36
Error: Prefix access is denied: /
       3: cmd/web-handlers.go:2010:cmd.toWebAPIError()
       2: cmd/web-handlers.go:1890:cmd.toJSONError()
       1: cmd/web-handlers.go:372:cmd.(*webAPIHandlers).ListBuckets()

the webUi search for buckets does not find any, it displays 
/ Used: 0 bytes

**Comment by harshavardhana** [comment]
Already fixed in master

**Comment by tooptoop4** [comment]
> Already fixed in master

is it on docker? edge tag still has the issue

**Comment by kannappanr** [comment]
@tooptoop4 with `mc` are you able to repro this issue?  Does an example command like `mc ls alias1/bucket123/team1/` work for you?,  Can you describe exactly what you are seeing with the browser and what you are expecting to see?

**Comment by tooptoop4** [comment]
@kannappanr 
/ # mc config host add s3 https://s3.amazonaws.com acc sec --api s3v4
Added `s3` successfully.
/ # mc ls s3/bucket123/team1/
mc: <ERROR> Unable to stat `s3/bucket123/team1/`. Get https://s3.amazonaws.com/bucket123/?location=: dial tcp 52.xxx.xxx.xxx:443: i/o timeout.

expecting to see objects from s3 in the browser but browser is not showing anything on main page or under search of buckets

**Comment by harshavardhana** [comment]
Without being able to list buckets we can't know which bucket you have access to @tooptoop4 so browser case cannot be supported in the current implementation requirements.

**Comment by kannappanr** [comment]
@tooptoop4 Without `listobjects` permission, you will not see any objects under the object or prefix. So, Gateway looks to work as expected.

**Comment by tooptoop4** [comment]
@kannappanr - i have listobjects (aws cli works for s3/bucket123/team1/), just dont have listbuckets/headbucket

**Comment by harshavardhana** [comment]
For browsers it's not possible to support such things, since we don't know which bucket you have access to. We would have to somehow take this as part of your URL endpoint input.

We will discuss and let you know. It is not going to be a high priority item for us at the moment.

**Comment by harshavardhana** [comment]
Currently there are no plans to expand the scope here., Feel free to reopen if it's a must requirement. We will close this issue for now.

**Comment by tooptoop4** [comment]
Just wanted to report back that it works now:

VERSION
2020-04-15T19:42:18Z
PLATFORM
Host: ip-xx | OS: linux | Arch: amd64
RUNTIME
Version: go1.13.8 | CPUs: 8


Only S3 privs I have are:

Bucket wide:
ListAllMyBuckets
GetBucketAcl
GetBucketCORS
GetBucketLocation
GetBucketLogging
GetBucketNotification
GetBucketObjectLockConfiguration
GetBucketPolicy
GetBucketPolicyStatus
GetBucketPublicAccessBlock
GetBucketRequestPayment
GetBucketTagging
GetBucketVersioning
GetBucketWebsite
GetLifecycleConfiguration
GetObjectAcl
GetObjectVersionAcl

On deep nested folder of a bucket:
GetObject
ListBucket
ListBucketMultipartUploads
AbortMultipartUpload
ListBucketVersions
GetObjectVersion
GetObjectMetadata
GetObjectTorrent
GetObjectTorrentVersion
RestoreObject
PutObject
PutObjectVersion
DeleteObject
DeleteObjectVersion


export MINIO_REGION=eu-west-1
export MINIO_ACCESS_KEY=redact1
export MINIO_SECRET_KEY=redact2
./minio gateway s3 --address :8787 https://s3.eu-west-1.amazonaws.com
