### ISSUE TITLE
su-exec not found on edge version of Docker image

### ISSUE THREAD

**Issue by orevial** [minio/minio#7767]
## Expected Behavior
Minio docker image is expected to run by launching the command depicted in the documentation:
```shell
docker run -p 9000:9000 minio/minio:edge server /data
```

Previous command should launch the container and we should have a running server with log such as this one:

```
Endpoint:  http://192.168.1.1:9000  http://127.0.0.1:9000

Browser Access:
   http://192.168.1.1:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
```

## Current Behavior
Instead of a working server we get an error:
```
/usr/bin/docker-entrypoint.sh: exec: line 63: su-exec: not found
```

## Possible Solution
The bug has been introduced with [this commit](https://github.com/minio/minio/commit/91ceae23d0885de9a452afc692db6d5cb751b40f#diff-08bc83c6a89d6b335935cbb22c40f36eR13) on [this file](https://github.com/minio/minio/blob/master/Dockerfile.dev) :

```
-     apk add --no-cache ca-certificates 'curl>7.61.0' && \
+     apk add --no-cache ca-certificates 'curl>7.61.0' 'su-exec>=0.2' && \
```

## Steps to Reproduce (for bugs)
Run the edge image with Docker:
```shell
docker run -p 9000:9000 minio/minio:edge server /data
```

## Regression
Yes, introduced by commit 91ceae23d0885de9a452afc692db6d5cb751b40f

## Your Environment

* Version used (`minio version`): Minio docker image "edge" version pointing to commit 002a205c9ce5005d3c39b2842b450d51f1cd941f
* Environment name and version (e.g. nginx 1.9.1): Docker

**Comment by nitisht** [comment]
Thanks for reporting @orevial we'll take a look

**Comment by nitisht** [comment]
@orevial could you please validate if #7768 fixes the problem..

**Comment by orevial** [comment]
Just tested, it works with #7768 :+1:
