### ISSUE TITLE
2019-06-11T00-44-33Z breaks user policy

### ISSUE THREAD

**Issue by fgma** [minio/minio#7769]
## Expected Behavior

After upgrading to the latest version user policies should continue to work as before.

## Current Behavior

User policies work using 2019-06-04T01-15-58Z but not anymore with 2019-06-11T00-44-33Z.  Before the upgrade users can login and access their files via the webinterface. After the upgrade they can still login but no buckets or files are visible anymore. Downgrading makes them available again.

My user policy to give users RW access to their own bucket only:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "*"
        ]
      },
      "Action": [
        "s3:GetBucketLocation",
        "s3:ListBucket",
        "s3:ListBucketMultipartUploads"
      ],
      "Resource": [
        "arn:aws:s3:::${aws:username}"
      ]
    },
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "*"
        ]
      },
      "Action": [
        "s3:AbortMultipartUpload",
        "s3:DeleteObject",
        "s3:GetObject",
        "s3:ListMultipartUploadParts",
        "s3:PutObject"
      ],
      "Resource": [
        "arn:aws:s3:::${aws:username}/*"
      ]
    }
  ]
}
```

## Steps to Reproduce (for bugs)

1. Install old version of minio
2. Add user with policy
3. Check access to his own bucket
4. Upgrade
5. User's bucket is not visible anymore in webinterface

## Context

Each user has his own bucket that only the user and the administrator may access.

## Your Environment

* Version used (`minio version`): 2019-06-11T00-44-33Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: Linux custom compiled for ARM.
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
Are you using minio in server mode or gateway? @fgma

**Comment by fgma** [comment]
I'm running it in server mode.

**Comment by harshavardhana** [comment]
Reproduced this @fgma sending a fix.
