### ISSUE TITLE
Bring back config as text files

### ISSUE THREAD

**Issue by alexp700** [minio/minio#7775]
We've been using minio for the last couple of years and its great. However we have had some problems recently. It turns out our version was stuck pre deprecation of config.json. We've worked around this and ready for the future.

However I'd like to add my small voice in defence of simple, easy to manage text files. Many systems have got over complicated with programs to configure stuff.  My request is to remove all the secrets. However how the thing functions concisely defined by a simple text file is still the most flexible way to work. Text files are easy to extend, require simple tooling, version easily etc etc.

PS You may or may not care, but healthcheck is now a 5MB binary over a .sh file of 2008 byte script and a 200K curl binary! 

Many thanks for your consideration!

**Comment by harshavardhana** [comment]
@alexp700 having bigger binaries is not a big deal for most deployments, if you are worried about that then it is unfortunate but it was necessary for us to support various situations where we had to go the binary route and we don't plan on going back. 

Config won't be brought back as text files either - the reasoning is a simplification of the config system. Editing config.json is prone to errors and also adds potential complexity in the deployments which are not needed to begin with for MinIO - most config options in MinIO are POST cluster configuration so it made sense for us to move to a more `mc admin` friendly model. 

The new changes that are coming into config are being able to use it like a key-value store such that
when you want to apply a particular config option you are only doing 

```
mc admin config set notification.mqtt enable=true otherparams=1  ....
``` 

At the scale where we are talking to our users, those deployments can get quickly complicated with editable config.json's etc and confusing versions across all the servers. So config.json will become a first-class citizen, currently, it's in a transition phase but this change will be soon available. 

For now closing this issue as won't fix. I hope I have answered your questions properly.
