### ISSUE TITLE
Improve minio configuration support for container

### ISSUE THREAD

**Issue by IsNull** [minio/minio#7786]
**Motivation**

The goal is to completely specify the (kubernetes) cluster state using configuration (yaml) files, without manually invoking configuration apis. This ensures that the cluster state is always reproducible.

While we can specify a distributed minio cluster and some configuration (like access-key etc) using env variables, a large portion of the configuration requires to use the minio-client cli and its admin / config calls, and worse, even restarting nodes.

For example, I need to configure `notify.kafka` to specify the kafka broker and topic. 

**Describe the solution you'd like**

Ideally, minio would support reading a provided config.json at startup. This must also work in distributed mode. (Because in single mode we can actually hack around it already by mounting a config.json at `/data/.minio.sys/config/config.json`

**Describe alternatives you've considered**

Alternatively, support configuration through environment variables for notify:

* `MINIO_NOTIFIY_KAFKA_ENABLED`
* `MINIO_NOTIFIY_KAFKA_BROKER`
* `MINIO_NOTIFIY_KAFKA_TOPIC`

I have also considered a custom pod init container which configures the cluster but this seems wrong aswell especally for a stateful set.

**Goal**
A clear and clean way to configure a distributed minio in kubernets including notify.* configuration without manual intervention.

**Comment by harshavardhana** [comment]
This will be done in new set of configuration changes which we are bringing in..

**Comment by IsNull** [comment]
Wow that was fast :)

Great news! Can you give any more information how the new config will work?
Also have you any estimate on a ca. ETA (months, end of year...)?

This would help us preparing for this and not doing any unnecessary work for the time being.

**Comment by harshavardhana** [comment]
There is no set ETA, But a broader timeline is end of this month.

**Comment by IsNull** [comment]
@harshavardhana Hey I noticed you have marked this issue as fixed, but I do not understand how the config now works? Is this not yet released or could you point me to the new config documentation?
