### ISSUE TITLE
Add minio_info metric or similar that exposed the same information as "minio version:" does.

### ISSUE THREAD

**Issue by thomasf** [minio/minio#7795]
It's great to have version number in Prometheus.. I have a lot of minio instances and a lot of them are probably not up to date because it's kind of hard to track.

This is an established pattern:

```
prometheus_build_info{branch="HEAD",goversion="go1.12.5",instance="localhost:9090",job="prometheus",revision="d20e84d0fb64aff2f62a977adc8cfb656da4e286",version="2.10.0"}


go_info{instance="localhost:9090",job="prometheus",version="go1.12.5"}


python_info{implementation="CPython",instance="e:443",job="....,major="3",minor="7",patchlevel="3",version="3.7.3"}
```

**Comment by kannappanr** [comment]
@thomasf Thanks for the issue. We will definitely look into this and try to add a versioning mechanism here.

**Comment by Praveenrajmani** [comment]
@thomasf Since, MinIO Version is a `string`. Prometheus wont allow to export a string metric type. They accept only counter-based types. If you see, [`https://prometheus.io/docs/concepts/metric_types/`](url) - these types are numerical and can be counted upon. This definitely makes sense because strings aren't metrics. We cannot construct a graph out of string metrics. It is not recommended to export a string even as a label to a metric.

**Comment by Praveenrajmani** [comment]
This issue speaks more about this - [`https://github.com/prometheus/prometheus/issues/2227`](url)

**Comment by thomasf** [comment]
Strings are supported as label values which is what you should be aiming at, a `minio_info` metric with multiple labels.. At least in the vector types like info would be, you can even see them in my example post in the issue description. It's a label value, not metric value. I'd guess that those info types usually just have a static 1 for value. 
It's very much common to export strings into metric labels, prometheus exposes it's own version that way and string label values are used a lot in general to make metric data meaningful. What is not recommenced is having a label with infinite and always changing string value because every variation of labels is another series for the database to keep track of.

**Comment by Praveenrajmani** [comment]
@thomasf https://github.com/prometheus/prometheus/issues/2227#issuecomment-263201106 - This may hinder the performance as well (as per the comment).

Let me see if it will be relevant to add the version as a label to any of the currently exposed metrics. Will discuss this here and come back

**Comment by Praveenrajmani** [comment]
@thomasf For now, the version info will be exposed under `minio_version_info` with a static-value `1`

**Comment by thomasf** [comment]
there is always relabeling in promeheus to drop those metrics you are not interested in as well. I have some exporters where I drop several thousands of metrics from. Nothing strange about that.. I would suggest `minio_info` instead because you can choose to add other information there later on without it being weird and closer to how most people does it. I've seen some version_info.. ones as well though so you are not completely alone even if that is less common.

**Comment by thomasf** [comment]
The performance problems can start happening when you export an label with infinite variations of the label value where it changes a lot. So it's not really a problem when it's a static value.

**Comment by Praveenrajmani** [comment]
> there is always relabeling in promeheus to drop those metrics you are not interested in as well. I have some exporters where I drop several thousands of metrics from. Nothing strange about that.. I would suggest `minio_info` instead because you can choose to add other information there later on without it being weird and closer to how most people does it. I've seen some version_info.. ones as well though so you are not completely alone even if that is less common.

For now `minio_version_info` will be apt. Since, we did not decide to expose other info yet.
