### ISSUE TITLE
how to check minio distribute mode is working

### ISSUE THREAD

**Issue by little-guy-lxr** [minio/minio#7796]
how to test minio distribution mode can balance load

**Comment by nitisht** [comment]
Please follow the distributed getting started guide: https://docs.min.io/docs/distributed-minio-quickstart-guide.html

For load balancing you simply need to send round robin style requests to MinIO servers, you can using something like Nginx: https://docs.min.io/docs/setup-nginx-proxy-with-minio

Closing this as answered, feel free to join us on slack  (https://slack.min.io) for more such questions
