### ISSUE TITLE
[gateway-azure] Remove user does not work anymore

### ISSUE THREAD

**Issue by bsemperlotti** [minio/minio#7797]
Updating from version `RELEASE.2019-06-04T01-15-58Z` to `RELEASE.2019-06-15T23-07-18Z` (critical bug fix), the `mc --json admin user remove ...` command does not work anymore (it was working with previous release) 

Note: Minio in Azure Gateway mode with ETCD synchronization

## Expected Behavior
User can be created and deleted using command line:

```bash
mc --json admin user add mycluster user001 xxxx  mypolicy
{
 "status": "success",
 "accessKey": "user001",
 "secretKey": "xxxx",
 "userStatus": "enabled"
}
```
```bash
mc --json admin user list mycluster
{
 "status": "success",
 "accessKey": "user001",
 "policyName": "mypolicy",
 "userStatus": "enabled"
}
```
```bash
mc --json admin user remove mycluster user001
{
 "status": "success",
 "accessKey": "user001"
}
```
```bash
mc --json admin user list mycluster
{
}
```
## Current Behavior
User is not deleted properly:

```bash
mc --json admin user add mycluster user001 xxxx  mypolicy
{
 "status": "success",
 "accessKey": "user001",
 "secretKey": "xxxx",
 "userStatus": "enabled"
}
```
```bash
mc --json admin user list mycluster
{
 "status": "success",
 "accessKey": "user001",
 "policyName": "mypolicy",
 "userStatus": "enabled"
}
```
```bash
mc --json admin user remove mycluster user001
{
 "status": "success",
 "accessKey": "user001"
}
```
```bash
mc --json admin user list mycluster
{
 "status": "success",
 "accessKey": "user001",
 "policyName": "mypolicy",
 "userStatus": "enabled"
}
```

## Possible Solution
NA

## Steps to Reproduce (for bugs)
1. Using command line, create a new user
2. Using command line, list users, confirm new user is present
3. Using command line, delete previously created user
4. Using command line, list users, user is still present

## Context
NA

## Regression
Is this issue a regression? Yes
regression in version `RELEASE.2019-06-15T23-07-18Z`
working properly with version `RELEASE.2019-06-04T01-15-58Z` 

## Your Environment

* Version used (`minio version`):

    Version: 2019-06-15T23:07:18Z
    Release-Tag: RELEASE.2019-06-15T23-07-18Z
    Commit-ID: 99bf4d0c429f04dbd013ba98840d07b759ae1702

    mc version RELEASE.2019-06-12T20-35-20Z

* Environment name and version (e.g. nginx 1.9.1):

    Azure-Gateway, Kubernetes deployment, ETCD synchronization

* Operating System and version (`uname -a`):
    Darwin LT-C02VQ1HEHTD6 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

**Comment by nitisht** [comment]
Thanks for reporting @bsemperlotti we'll take a look

**Comment by harshavardhana** [comment]
I can reproduce this @bsemperlotti
