### ISSUE TITLE
Need help with my use case solution

### ISSUE THREAD

**Issue by matemikulic** [minio/minio#7798]
Hey guys, I need help with a scenario I have, hopefully Minio is the solution.
I have application that is located in private data centers(not AWS) around the world. In ~10 locations. Each data center has it's own application cluster and public API endpoint. The data centers are connected between themselves  via private network.

If a client uploads a file via location A public API endpoint and wishes to use it when making an API call on location D endpoint he needs to be able to. Meanin, all locations need to have all files.
The issue is that this needs to be HA, if private connection between DC's is lost primarily and in case one DC has disaster.

Stretched Minio cluster is out of the question since the rule n/2 for read and n/2+1 for write cannot be fulfilled  if one DC is cut off from the rest.

The next best thing that comes to mind is to have multiple Minio clusters, one per each DC, that sync data among each other when they are connected. And if they were to lose connection they would still have both read and write capabilities. Once connection is established they would be able to resync data between them that were added in the meantime.

I know there is a workaround with lsyncd but I'm not comfortable enough with it to make it crucial part of such large infrastructure.

If solution for this use case exists I would appreciate if you could throw some links and point me in the correct direction. Thank you.

**Comment by nitisht** [comment]
@matemikulic have you checked MinIO Federation? https://docs.min.io/docs/minio-federation-quickstart-guide.html 

Also please join us on slack (https://slack.min.io) for more real time discussion..
