### ISSUE TITLE
Connect Minio to S3 without a filesystem

### ISSUE THREAD

**Issue by shubham1172** [minio/minio#7800]
Hi,

Is there a way to connect a Minio server running on my Kubernetes system to an S3 instance directly, without having a PVC locally?

Thanks.

**Comment by nitisht** [comment]
You can use https://github.com/minio/minio/blob/master/docs/gateway/s3.md

Closing this as answered, please join us on slack (https://slack.min.io) for more such questions.

**Comment by shubham1172** [comment]
Thank you! This is exactly what I was looking for!
