### ISSUE TITLE
MINIO_HTTP_TRACE is not working

### ISSUE THREAD

**Issue by kanagarajkm** [minio/minio#7807]
`MINIO_HTTP_TRACE=/tmp/minio.log` is set, and multiple requests are made to minio server but nothing is logged in `/tmp/minio.log` 

## Expected Behavior

Requests should be logged 

## Current Behavior

Requests are not logged

## Steps to Reproduce (for bugs)

1. Run this command `MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 MINIO_HTTP_TRACE=/tmp/minio.log minio server ~/tmp/data`
2. Do some operations using mc .(create bucket, list objects)
3. Check `/tmp/minio.log`, its empty

## Your Environment

* Version used (`minio version`): 2019-06-15T23:07:18Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: FS mode
* Operating System and version (`uname -a`): Linux kanagaraj-X260 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by and0x000** [comment]
According to [this](https://github.com/minio/minio/releases/tag/RELEASE.2019-06-11T00-44-33Z) release note, support for the `MINIO_HTTP_TRACE` environment variable has been removed.

> Add admin API to send trace notifications to registered listeners. Support for MINIO_HTTP_TRACE environment variable has been removed. See (#7128) for more details.

**Comment by harshavardhana** [comment]
Yes this has moved to `mc admin trace` instead. Closing this issue.

**Comment by kanagarajkm** [comment]
@and0x000 @harshavardhana thanks!

The doc needs to be updated here https://github.com/minio/minio/blob/master/docs/config/README.md#http-trace

**Comment by harshavardhana** [comment]
Yes shall be fixed in #7808
