### ISSUE TITLE
minio put object part crash   

### ISSUE THREAD

**Issue by little-guy-lxr** [minio/minio#7809]
upload large file concurrently ,minio crash in PutObjectPartHandler.
logs:

2019-06-19 14:04:28.288948 I | http: panic serving 192.168.100.1:60598: runtime error: invalid memory address or nil pointer dereference
goroutine 166 [running]:
net/http.(*conn).serve.func1(0xc000710500)
        /home/testiceberg/iceberg/tmp/go/src/net/http/server.go:1769 +0x139
panic(0x17966c0, 0x2d33cf0)
        /home/testiceberg/iceberg/tmp/go/src/runtime/panic.go:522 +0x1b5
minio/cmd.criticalErrorHandler.ServeHTTP.func1(0x1cdab80, 0xc0004515e0, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/cmd/generic-handlers.go:795 +0x248
panic(0x17966c0, 0x2d33cf0)
        /home/testiceberg/iceberg/tmp/go/src/runtime/panic.go:522 +0x1b5
net/http.(*body).readLocked(0xc0001412c0, 0xc03bffffe0, 0x20, 0x20, 0x8, 0xc03bfff4c0, 0xb00)
        /home/testiceberg/iceberg/tmp/go/src/net/http/transfer.go:857 +0xcd
net/http.(*body).Read(0xc0001412c0, 0xc03bffffe0, 0x20, 0x20, 0x0, 0x0, 0x0)
        /home/testiceberg/iceberg/tmp/go/src/net/http/transfer.go:808 +0xdb
net/http.(*maxBytesReader).Read(0xc000141c00, 0xc03bffffe0, 0x20, 0x20, 0xb00, 0x20, 0xc03bfff4c0)
        /home/testiceberg/iceberg/tmp/go/src/net/http/request.go:1090 +0x89
io.(*LimitedReader).Read(0xc000240600, 0xc03bffffe0, 0x20, 0x20, 0xb20, 0x0, 0x0)
        /home/testiceberg/iceberg/tmp/go/src/io/io.go:448 +0x63
minio/pkg/hash.(*Reader).Read(0xc000354150, 0xc03bffffe0, 0x20, 0x20, 0xb20, 0x0, 0x0)
        /home/testiceberg/iceberg/src/minio/pkg/hash/reader.go:80 +0x55
minio/cmd.objectAPIHandlers.PutObjectPartHandler(0x1a85fd0, 0x1a85fc8, 0xc00023e580, 0x1ccf780, 0xc000016100, 0xc000420500)
        /home/testiceberg/iceberg/src/minio/cmd/object-handlers.go:2085 +0x15ac
net/http.HandlerFunc.ServeHTTP(0xc00024cc60, 0x1ccf780, 0xc000016100, 0xc000420500)
        /home/testiceberg/iceberg/tmp/go/src/net/http/server.go:1995 +0x44
minio/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0002d80c0, 0x1ccf780, 0xc000016100, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/vendor/github.com/gorilla/mux/mux.go:212 +0xe3
minio/cmd.customHeaderHandler.ServeHTTP(0x1cac880, 0xc0002d80c0, 0x1ccf500, 0xc0000160e0, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/cmd/generic-handlers.go:766 +0x1a6
minio/cmd.securityHeaderHandler.ServeHTTP(0x1caf740, 0xc000725b20, 0x1ccf500, 0xc0000160e0, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/cmd/generic-handlers.go:781 +0x1f0
minio/cmd.bucketForwardingHandler.ServeHTTP(0xc000017900, 0x1caf8a0, 0xc000725b30, 0x1ccf500, 0xc0000160e0, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/cmd/generic-handlers.go:649 +0x1104
minio/cmd.requestValidityHandler.ServeHTTP(0x1caf6c0, 0xc000017920, 0x1ccf500, 0xc0000160e0, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/cmd/generic-handlers.go:634 +0x58f
minio/cmd.httpStatsHandler.ServeHTTP(0x1caf840, 0xc000725b50, 0x1cdab80, 0xc0004515e0, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/cmd/generic-handlers.go:558 +0xb5
minio/cmd.requestSizeLimitHandler.ServeHTTP(0x1caf780, 0xc000725b60, 0x50004000000, 0x1cdab80, 0xc0004515e0, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/cmd/generic-handlers.go:70 +0xd0
minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP(0x1caf820, 0xc000017940, 0x1cdab80, 0xc0004515e0, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/cmd/generic-handlers.go:95 +0x264
minio/cmd.crossDomainPolicy.ServeHTTP(0x1caf800, 0xc000725b70, 0x1cdab80, 0xc0004515e0, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/cmd/crossdomain-xml-handler.go:51 +0x81
minio/cmd.redirectHandler.ServeHTTP(0x1caf720, 0xc000725b80, 0x1cdab80, 0xc0004515e0, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/cmd/generic-handlers.go:253 +0x68
minio/cmd.minioReservedBucketHandler.ServeHTTP(0x1caf7e0, 0xc000725b90, 0x1cdab80, 0xc0004515e0, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/cmd/generic-handlers.go:311 +0xae
minio/cmd.cacheControlHandler.ServeHTTP(0x1caf7c0, 0xc000725ba0, 0x1cdab80, 0xc0004515e0, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/cmd/generic-handlers.go:280 +0x1d5
minio/cmd.timeValidityHandler.ServeHTTP(0x1caf6e0, 0xc000725bb0, 0x1cdab80, 0xc0004515e0, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/cmd/generic-handlers.go:381 +0x32a
minio/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x1cdab80, 0xc0004515e0, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/vendor/github.com/rs/cors/cors.go:214 +0x1af
net/http.HandlerFunc.ServeHTTP(0xc0000179c0, 0x1cdab80, 0xc0004515e0, 0xc000624400)
        /home/testiceberg/iceberg/tmp/go/src/net/http/server.go:1995 +0x44
minio/cmd.resourceHandler.ServeHTTP(0x1cb0a60, 0xc0000179c0, 0x1cdab80, 0xc0004515e0, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/cmd/generic-handlers.go:509 +0xb9
minio/cmd.authHandler.ServeHTTP(0x1caf880, 0xc000725c30, 0x1cdab80, 0xc0004515e0, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/cmd/auth-handler.go:405 +0x3ba
minio/cmd.sseTLSHandler.ServeHTTP(0x1caf6a0, 0xc000725c40, 0x1cdab80, 0xc0004515e0, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/cmd/generic-handlers.go:816 +0x454
minio/cmd.reservedMetadataHandler.ServeHTTP(0x1caf8c0, 0xc000725c50, 0x1cdab80, 0xc0004515e0, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/cmd/generic-handlers.go:145 +0x331
minio/cmd.criticalErrorHandler.ServeHTTP(0x1caf860, 0xc000725c60, 0x1cdab80, 0xc0004515e0, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/cmd/generic-handlers.go:798 +0x8d
minio/cmd/http.(*Server).Start.func1(0x1cdab80, 0xc0004515e0, 0xc000624400)
        /home/testiceberg/iceberg/src/minio/cmd/http/server.go:126 +0xe7
net/http.HandlerFunc.ServeHTTP(0xc000022080, 0x1cdab80, 0xc0004515e0, 0xc000624400)
        /home/testiceberg/iceberg/tmp/go/src/net/http/server.go:1995 +0x44
net/http.serverHandler.ServeHTTP(0xc0002db7c0, 0x1cdab80, 0xc0004515e0, 0xc000624400)
        /home/testiceberg/iceberg/tmp/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000710500, 0x1cddd40, 0xc000482f00)
        /home/testiceberg/iceberg/tmp/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /home/testiceberg/iceberg/tmp/go/src/net/http/server.go:2884 +0x2f4

**Comment by harshavardhana** [comment]
Can you provide more details @little-guy-lxr such as version, what is the application, etc?

We humbly **request** you to use the issue template such that we don't have to repeatedly ask these questions.

**Comment by harshavardhana** [comment]
We will close this issue until we have more information. Thanks.
