### ISSUE TITLE
Error: file access denied Arq/curl

### ISSUE THREAD

**Issue by VeselaHouba** [minio/minio#7811]
I'm testing using minio as s3 backend for ARQ backup SW. I've managed to set it up and working, but after few hours backups start failing with 
```
Error: file access denied
```
I'm using authentication, the bucket is not public.

## Expected Behavior
Access allowed

## Current Behavior
Access denied
```
API: GetObject(bucket=<bucket_name>, object=2C7031A2-7017-49A4-BE18-03893D53DAC3/packsets/123A940E-B1FF-4DFD-9B54-EA7492D394C5-trees/841b8e75be05380f10af8cfc47b2385feeca1bd8.index)
Time: 06:57:18 UTC 06/20/2019
RequestID: 15A9D5D0D78BB97B
RemoteHost: <ip_addr>
Error: file access denied
       5: cmd/fs-v1-helpers.go:246:cmd.fsStatFile()
       4: cmd/fs-v1.go:733:cmd.(*FSObjects).getObjectInfo()
       3: cmd/fs-v1.go:501:cmd.(*FSObjects).GetObjectNInfo()
       2: cmd/object-handlers.go:333:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()
```
When I try to call the same URL with curl, it also gives access denied.
```
#!/usr/bin/env bash

bucket=$1
file=$2

host=_secret_
s3_key='_secret_'
s3_secret=''_secret_'

resource="/${bucket}/${file}"
content_type="application/octet-stream"
date=`date -R`
_signature="GET\n\n${content_type}\n${date}\n${resource}"
signature=`echo -en ${_signature} | openssl sha1 -hmac ${s3_secret} -binary | base64`

curl -v -X GET \
          -H "Host: $host" \
          -H "Date: ${date}" \
          -H "Content-Type: ${content_type}" \
          -H "Authorization: AWS ${s3_key}:${signature}" \
          https://$host${resource}
```
...
```
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key>2C7031A2-7017-49A4-BE18-03893D53DAC3/bucketdata/123A940E-B1FF-4DFD-9B54-EA7492D394C5/refs/heads/master</Key><BucketName>_secret_</BucketName><Resource>/_secret_/2C7031A2-7017-49A4-BE18-03893D53DAC3/bucketdata/123A940E-B1FF-4DFD-9B54-EA7492D394C5/refs/heads/master</Resource><RequestId>15A9D5B2928036A4</RequestId><HostId>194deb7b-bfa6-4868-8882-aff8274e016f</HostId></Error>
```

### Workarounds
Everything starts working when I do one of following
- I try to access the same file via minio web GUI (after authentication)
- I hit the "Clear cache" button in ARQ (not sure what it actually does)
- Restarting the docker container

I thought this is issue of ARQ, but it looks like some kind of auth cache is broken on minio itself.

## Possible Solution
No idea

## Steps to Reproduce (for bugs)

1. Start minio from docker image 
```
#!/usr/bin/env bash
docker run \
  --rm \
  -d \
  -p 30323:9000 \
  --name minio-test \
  -e "MINIO_ACCESS_KEY='_secret_' \
  -e "MINIO_SECRET_KEY='_secret_' \
  -v /data:/data \
  minio/minio \
  server \
  --compat \
  /data
```
2. Set-up nginx with valid https cert as proxy
3. Set-up ARQ backups. Using "other s3-compatible" option. Tried both v2 and v4 settings.
4. Leave the backup running in schedule (e.g. every hour)

## Your Environment
minio docker version: `2019-05-23T00:29:34Z`
windows arq client version: `5.16.0`

**Comment by harshavardhana** [comment]
Can you test with latest release?

**Comment by VeselaHouba** [comment]
> Can you test with latest release?

Sure. Just downloaded `2019-06-19T18:24:42Z` . Will let you know results after few backup cycles

**Comment by VeselaHouba** [comment]
Still the same error
```
API: GetObject(bucket=_secret_, object=2C7031A2-7017-49A4-BE18-03893D53DAC3/buckets/123A940E-B1FF-4DFD-9B54-EA7492D394C5)
Time: 10:36:39 UTC 06/20/2019
DeploymentID: 194deb7b-bfa6-4868-8882-aff8274e016f
RequestID: 15A9E1C92490BF6D
RemoteHost: _secret_
Error: file access denied
       5: cmd/fs-v1-helpers.go:246:cmd.fsStatFile()
       4: cmd/fs-v1.go:731:cmd.(*FSObjects).getObjectInfo()
       3: cmd/fs-v1.go:502:cmd.(*FSObjects).GetObjectNInfo()
       2: cmd/object-handlers.go:333:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()
```

---edit---
Logged via GUI
1. Opened: `https://<url>/minio/<bucket>/2C7031A2-7017-49A4-BE18-03893D53DAC3` - No change
2. Opened: `https://<url>/minio/<bucket>/2C7031A2-7017-49A4-BE18-03893D53DAC3/buckets/` - Access started to work

**Comment by krishnasrinivas** [comment]
@VeselaHouba when this situation happens, can you check the permission of the file in the backend:
ls -l /data/bucket/2C7031A2-7017-49A4-BE18-03893D53DAC3/buckets/123A940E-B1FF-4DFD-9B54-EA7492D394C5

also try to cat it:
cat /data/bucket/2C7031A2-7017-49A4-BE18-03893D53DAC3/buckets/123A940E-B1FF-4DFD-9B54-EA7492D394C5

And see if this works. Basically from the stack trace we can see that stat() syscall on that file returns permission denied error.

**Comment by VeselaHouba** [comment]
@krishnasrinivas Hi, yes, I can access the file (tried as root, docker process is also running as root)
```
$ cat 2C7031A2-7017-49A4-BE18-03893D53DAC3/bucketdata/123A940E-B1FF-4DFD-9B54-EA7492D394C5/refs/heads/master
3923922d40a58171441b08f966f2a2d3b569df2dY
```
After accessing the file directly, minio again starts to work. Any idea what can cause this?

**Comment by harshavardhana** [comment]
Is your backend NFS ? @VeselaHouba

**Comment by VeselaHouba** [comment]
Yes it is, the docker volume is mounted from device which comes over NFS. 
I use following options
```
type nfs4 (rw,relatime,sync,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=_secret_,local_lock=none,addr=_secret_)
```

**Comment by harshavardhana** [comment]
This looks like NFS caching issue..

**Comment by VeselaHouba** [comment]
Ok, I've now disabled NFS cache with `noac` option. 

Also testing direct mount without NFS on second instance. Will let you know results.

**Comment by VeselaHouba** [comment]
Results: The NFS-mounted instance still has issues, direct-mounted is fine. So @harshavardhana you were right, the issues is caused somewhere in NFS-docker-minio connection.

**Comment by harshavardhana** [comment]
> Results: The NFS-mounted instance still has issues, direct-mounted is fine. So @harshavardhana you were right, the issues is caused somewhere in NFS-docker-minio connection.

Don't know what else we can help here @VeselaHouba - you can perhaps not use docker and use the NFS mount directly on the host? 

We can close this issue since this is not a MinIO issue.

**Comment by VeselaHouba** [comment]
Yes, I'll try some other combinations. Thanks for help, feel free to close ticket
