### ISSUE TITLE
Any plan to build real-time dashboard for resource files monitoring ?

### ISSUE THREAD

**Issue by nvcken** [minio/minio#7827]
We want to monitor resource files usage, is it built-in or could you please tell any thid-party can be integrated to Minio for this purpose

Thanks

**Comment by harshavardhana** [comment]
How about this “Monitor Minio server with Prometheus” by Nitish Tiwari https://link.medium.com/tAZrXQGBNX - also please we request that use the issue template in future it really helps triage the issues @nvcken 

For general questions please feel free to join our https://slack.min.io

**Comment by nitisht** [comment]
closing as working as intended
