### ISSUE TITLE
minio/minio:RELEASE.2019-06-19T18-24-42Z: causes high CPU load (automatic healing)

### ISSUE THREAD

**Issue by evilthiesje** [minio/minio#7835]
We’ve updated from docker image minio/minio:RELEASE.2019-03-20T22-38-47Z to minio/minio:RELEASE.2019-06-19T18-24-42Z. After a few seconds, the CPU load on all our servers reached over 90%, the HTTP response times increased heavily (up to 18 seconds for a POST request, instead of 500ms). There was no visible change after two days, so we had to downgrade minio in order to avoid further problems in our system.

## Expected Behavior
Minio update should not influence the CPU load and data throughput. 

## Current Behavior
After updating from image: minio/minio:RELEASE.2019-03-20T22-38-47Z to image minio/minio:RELEASE.2019-06-19T18-24-42Z, the CPU load increases. 

## Possible Solution
From discussions in the slack channel I assume the automatic heal process is the problem. As I understand, there is no way to stop it / disable it. You may have either speed it up in environments like ours (see below) or give us a chance to disable it. 

## Steps to Reproduce (for bugs)
1. Exchange the version in the docker-compose file

## Context
We have 4 minio instances running, each has 4 discs with 500GB attached. Each minio instance runs on its own docker node.

Our system has only a four buckets, each with a lot a smaller files (> 8 millions). The files are structured in two-level sub-folders, named by the first 4 letters (2 letters for level 1, 2 letters for level 2) of their MD5 hash. 
i.e.: <bucket>/ff/ee/<object>

We had a second installation where we only have a few thousands objects stored. There was a short peak after update, gone within two hours.

## Environment
* Version used (`minio version`): 2019-06-19T18-24-42Z
* Environment name and version: docker (swarm) version 18.09.05
Host machines (Docker Swarm):
* Server type and version: 4 core CPU / 8 GB RAM (virtual server)
* Operating System and version: CentOS 7

**Comment by harshavardhana** [comment]
Thank you for opening the issue, we will be fixing this in upcoming releases.

**Comment by ghost** [comment]
I see that you have done POST requests against it. Was it a multipart upload?
If so, then this may be a duplicate of https://github.com/minio/minio/issues/7206 .

**Comment by harshavardhana** [comment]
This issue is not related to #7206

**Comment by harshavardhana** [comment]
To be fixed by fast scan instead of deep scan in #7868

**Comment by deekoder** [comment]
@gustopn since #7868 is merged, closing this issue as fixed.
