### ISSUE TITLE
MinIO Browser - Cannot open a folder in a new Tab

### ISSUE THREAD

**Issue by tinohager** [minio/minio#7836]
It is not possible in chrome to open a folder in a new tab. Its Always open the new tab in the bucket overview.

Steps to Reproduce (for bugs)
Right click on a folder in the bucket overview an choose open in new tab.

Your Environment
Version used (minio version): 2019-06-13T01:41:13Z
Nuget packages: MinIO v3.0.11, AWSSDK.S3 v3.3.102.12
Operating System and version (uname -a): Windows 10 Pro Version 1803

**Comment by harshavardhana** [comment]
@tinohager it is as per design, MinIO browser is a single page application.

**Comment by harshavardhana** [comment]
Are you asking for selecting a bucket and then being able to view that upon selection.. ?

**Comment by tinohager** [comment]
@harshavardhana this is not a problem with a spa application. The route is correct. I think the problem is the empty a href tag.

**Comment by harshavardhana** [comment]
Can you elaborate further are you taking about MinIO browser ?

**Comment by kannappanr** [comment]
@harshavardhana I think what he means is that if we look at Play, there is a bucket named `00test` so when you go to `https://play.minio.io:9000/minio/00test/`, it will display a folder named `test` and when you right click on it and select `open in a new tab`, the link there is `https://play.minio.io:9000/minio/00test/#` . So, in the new tab it will essentially be displaying the same page.

**Comment by kannappanr** [comment]
@tinohager We will implement this change.

**Comment by ForsakenHarmony** [comment]
> @\tinohager it is as per design, MinIO browser is a single page application.

@harshavardhana I can't tell if you're serious, single page apps are still supposed to use urls and not replace links with buttons (but intercept the routing instead)

**Comment by harshavardhana** [comment]
> @harshavardhana I can't tell if you're serious, single page apps are still supposed to use urls and not replace links with buttons (but intercept the routing instead)

I miss understood what @tinohager was asking @ForsakenHarmony

**Comment by ForsakenHarmony** [comment]
OK was a bit confused which question that would be a reply to, because I don't see any way to understand it in a way where it would be a valid answer
