### ISSUE TITLE
A file in a bucket is being deleted automatically by minio at random time interval

### ISSUE THREAD

**Issue by mt-rahul** [minio/minio#7841]
We have a bucket in minio where we keep some files. One of files in the bucket is being randomly deleted. Which is very confusing because only that file is deleted everytime while other files are still present

We don't expect minio to delete any files unless we do it ourselves. Minio is deployed on kubernetes with persistence enabled. 

Files are being copied to the bucket with aws cli commands.  Is there any reason for which minio can delete a file itself or automatically expire a file in the bucket?

**Comment by nitisht** [comment]
@mt-rahul MinIO never deletes a file randomly. Also please follow the issue template, it helps us identify the problem and suggest a fix. Without details it is very difficult to reproduce / analyse the problem

**Comment by mt-rahul** [comment]
@nitisht Apologies for that. We are using minio (v 2.4.16) helm chart to install it in our kubernetes cluster (EKS). I am unable to find any logs for this container. Could you tell me where can I find the logs?

Running these following commands to copy data to minio host which is working fine. 

`aws s3 cp /app/dist s3://${BUCKET_NAME} --endpoint-url='$S3_ENDPOINT_URL' --recursive --acl public-read`
`aws s3 cp /app/dist/index.html s3://${BUCKET_NAME}/index.html --endpoint-url='$S3_ENDPOINT_URL' --acl public-read --cache-control max-age=0`

Index.html is getting deleted randomly. 

I hope I am clear with the issue.

**Comment by harshavardhana** [comment]
> aws s3 cp /app/dist/index.html s3://${BUCKET_NAME}/index.html --endpoint-url='$S3_ENDPOINT_URL' --acl public-read --cache-control max-age=0

why is cache-control "max-age" set? can you also provide us the server deployment details?

**Comment by mt-rahul** [comment]
Thanks Harshavardhana for the response. 

We don't want to cache this file in the browser. 

Following parameters override the default parameters in values.yaml file for Minio, all the other parameters are kept default :
`
accessKey: "<access-key>"
secretKey: "<secret-key>"
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 50Gi
`
We use minio in dev environment to keep everything internal. Staging and Prod environment use AWS S3.  

Minio Helm Chart: v1.16.162
AWS EKS: v1.11
Helm (Client, Tiller): v2.12.3
AWS CLI: v1.16.162

**Comment by harshavardhana** [comment]
Need to know how is MinIO running, is it running in distributed mode ?

**Comment by mt-rahul** [comment]
it is running in standalone mode.

**Comment by nitisht** [comment]
@mt-rahul can you please join us on Slack (https://slack.min.io), it will help discuss faster and understand the problem

**Comment by kannappanr** [comment]
@mt-rahul Closing this as stale. Please feel free to reach out to us if you haven't been able to resolve this yet.
