### ISSUE TITLE
B2 gateway with bucket-restricted app key no longer works

### ISSUE THREAD

**Issue by codl** [minio/minio#7848]
## Expected Behavior
`minio gateway b2`, with an app key that is only allowed access to one bucket, successfully writes and reads objects in that bucket

## Current Behavior
since earlier today, requests to minio hang for minutes and eventually respond with 500 status

the same requests with another app key that has access to all buckets work fine

## Steps to Reproduce (for bugs)
1. create an app key at <https://secure.backblaze.com/app_keys.htm> that is only allowed access to one bucket
2. `env MINIO_ACCESS_KEY=key_id_here MINIO_SECRET_KEY=app_key_here minio gateway b2`
3. open http://localhost:9000/minio/ and log in
4. nothing loads

## Context
I am using minio as a B2 gateway for a Mastodon server since Mastodon only supports S3

## Regression
I don't think this is a regression in minio, rather a recent change in B2, as it stopped working suddenly today without me upgrading or even restarting minio

## Your Environment
* Version used (`minio version`): 
   ```
   Version: 2019-06-27T21:13:50Z
   Release-Tag: RELEASE.2019-06-27T21-13-50Z
   Commit-ID: 36c19f1d653adf3ef70128eb3be1a35b6b032731
   ```
* Operating System and version (`uname -a`):
   ```
   Linux hostname.redacted 4.9.93-mainline-rev1 #1 SMP Tue Apr 10 09:48:45 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
   ```
* Link to your project: <https://github.com/tootsuite/mastodon>

**Comment by nitisht** [comment]
we'll take a look @codl

**Comment by codl** [comment]
I see now in backblaze's twitter mentions that other people are running into the same issue in apps like duplicity and duplicacy [[1]](https://twitter.com/backblaze/status/1144599897275940864)[[2]](https://twitter.com/backblaze/status/1144594047022972929) so it is likely a problem on backblaze's end

**Comment by kannappanr** [comment]
@codl Thanks for updating. Will keep this issue open here. Can you please update us once this issue is resolved on Backblaze's end, so we can close this issue

**Comment by codl** [comment]
Backblaze [reports that they've resolved it](https://twitter.com/backblaze/status/1144687338468982784) and I'm not having the issue with minio anymore 🎉
