### ISSUE TITLE
Minio as Azure Gateway liveness probe fails every hours or so under no load

### ISSUE THREAD

**Issue by victornoel** [minio/minio#7855]
A minio azure gateway deployed with the Helm chart has its liveness probe failing every hours or so.

The liveness reports a timeout and even though we increased the timeout limit to 30sec, it is still not enough.

This is not happening 100% of the time, but there are periods when it happens. For example it happened 45 times since the 27, with the majority of them during the week-end every hours or so when no traffic was happening at all.

The service is not restarted though, because usually it comes back to an healthy state before kubernetes can decide to do so.

## Expected Behavior

The liveness probe not to fail, but at least some more info on how to find the source of this.

## Context

We monitor events from kubernetes about healthiness failure and we are spammed by this information.

## Your Environment

* Version used (`minio version`): RELEASE.2019-06-19T18-24-42Z
* Environment name and version (e.g. nginx 1.9.1): AKS

**Comment by kannappanr** [comment]
@victornoel Can you please let us know more about the status returned in this case? Also, is there any log printed on the `MinIO` console?

**Comment by victornoel** [comment]
@kannappanr there are no logs at all, but I haven't enabled TRACE debug.

There are no return code because the error is a timeout:
```
Liveness probe failed: Get http://10.240.0.44:9000/minio/health/live: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by vadmeste** [comment]
@victornoel you might have a lot of buckets (containers) in Azure and Minio fails to list them all in 30 seconds.

Can you tell us how many buckets you have?

**Comment by victornoel** [comment]
@vadmeste there is only one bucket there

**Comment by harshavardhana** [comment]
@victornoel what @vadmeste meant is `containers`  - how many containers do you have?

**Comment by victornoel** [comment]
@harshavardhana yes, in the storage account there is only one container (which corresponds to one bucket in minio if I understand correctly).

For the record it is a `BlobStorage` storage account, if it is important…

**Comment by harshavardhana** [comment]
Is your azure gateway on Azure cloud as well or is it local to your datacenter?

**Comment by victornoel** [comment]
@harshavardhana the minio azure gateway is deployed on a kubernetes cluster inside the azure cloud (AKS), they are not in the same datacenter though.

**Comment by harshavardhana** [comment]
> @harshavardhana the minio azure gateway is deployed on a kubernetes cluster inside the azure cloud (AKS), they are not in the same datacenter though.

We added some logs can you check `minio/minio:edge` and let us know how your testing goes? @victornoel

**Comment by victornoel** [comment]
@harshavardhana yep, I am going to do that. Any specific option to give to minio or a norma deployment should be alright? Thanks!

**Comment by vadmeste** [comment]
> @harshavardhana yep, I am going to do that. Any specific option to give to minio or a norma deployment should be alright? Thanks!

It is just a normal deployment, you just need to test with this exact image: `minio/minio:edge`

**Comment by victornoel** [comment]
@vadmeste @harshavardhana the problem appeared again during the night, but there are no logs in minio.

I think it makes sense since the liveness probe error is:
```
Liveness probe failed: Get http://10.242.0.68:9000/minio/health/live: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

So maybe from the point of view of minio, the request succeeds, only it does not happens fast enough?

**Comment by harshavardhana** [comment]
Yes do you have an arbitrary timeout on your client side @victornoel ?

**Comment by victornoel** [comment]
@harshavardhana it is explained in the description: it is the liveness probe that fails and the timeout is set to 30 seconds which should be more than enough for checking liveness of minio I believe.

**Comment by harshavardhana** [comment]
It is not about MinIO it is something to do with your storage account, we perform a ListBuckets call to see if backend is alive. If that times we take time.

**Comment by harshavardhana** [comment]
For example in our tests we don't see this problem, it may be that at times your network from Azure container service to blob access is just slower.

**Comment by victornoel** [comment]
@harshavardhana ok, I see, thank you for helping me confirm the source of the problem comes from azure
