### ISSUE TITLE
Support for breakpoint continuation？

### ISSUE THREAD

**Issue by AllenArbiter** [minio/minio#7856]
Everybody is greatly good, I would like to ask whether minIo Java SDK supports breakpoint continuation, and it is better to have a listed website

**Comment by nitisht** [comment]
Don't really understand the question @AllenArbiter can you elaborate a bit on what do you mean by `breakpoint continuation`, are you debugging the java code and want to be able to use breakpoints?

**Comment by kannappanr** [comment]
@Allenrbiter i think you mean multi-part upload like it was explained in general slack (https://minio.slack.com/archives/C3NDUB8UA/p1561970748256300) . Closing this issue based on that. 
Feel free to reach out to us on slack if you have more questions.
