### ISSUE TITLE
Maximum number of concurrent file 

### ISSUE THREAD

**Issue by dsonjohn** [minio/minio#7863]
what is the Maximum number of concurrent file upload in single mode MinIO?

**Comment by harshavardhana** [comment]
It's the value of your `ulimit -Hn`.  Hard limit on number of file descriptors for a user.

**Comment by dsonjohn** [comment]
i want to get number of concurrent upload file request and evaluate load test benchmark.

**Comment by harshavardhana** [comment]
It is your ulimit -Hn value
