### ISSUE TITLE
minio/minio:RELEASE.2019-06-27T21-13-50Z was not tagget on docker hub

### ISSUE THREAD

**Issue by victornoel** [minio/minio#7866]
Docker hub only has a latest tag but not the `RELEASE.2019-06-27T21-13-50Z` tag for the latest image released 5 days ago.

**Comment by harshavardhana** [comment]
We are aware of this, fixing it - hub seems to have erroneously failed @victornoel

**Comment by harshavardhana** [comment]
Fixed closing this issue..

**Comment by victornoel** [comment]
@harshavardhana cool, thx :)
