### ISSUE TITLE
Publish MinIO events via Kafka

### ISSUE THREAD

**Issue by ghost** [minio/minio#7870]
MinIO requires Kafka version 0.10 or 0.9？ but now the Kafka 2.3.0 is the latest release. The current stable version is 2.3.0. Upgrade MinIO to support the latest version of Kafka?

**Comment by harshavardhana** [comment]
MinIO only states minimum version, it should work with latest version of  the Kafka server.

**Comment by harshavardhana** [comment]
Also please use the issue template, for questions like these please use our slack channel https://slack.minio.io

**Comment by kannappanr** [comment]
@Peng-Xia Closing this issue as answered. Please feel free to reach out to us on slack.
