### ISSUE TITLE
Question about  erasure code k+m setting

### ISSUE THREAD

**Issue by iliul** [minio/minio#7871]
**Is your feature request related to a problem? Please describe.**

I read the official documentation but found that the EC mode cannot customize the k m value. The default is k=m, which means double the amount of data redundancy. What is the reason for this design? Is there a supported plan?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by harshavardhana** [comment]
Have you not read “Configurable data and parity drives on Minio server” by Nitish Tiwari https://link.medium.com/OqhmxDwK0X ?

**Comment by iliul** [comment]
> Have you not read “Configurable data and parity drives on Minio server” by Nitish Tiwari https://link.medium.com/OqhmxDwK0X ?

Thanks, I will read it carefully @harshavardhana
