### ISSUE TITLE
Prometheus metrics clean-up

### ISSUE THREAD

**Issue by Praveenrajmani** [minio/minio#7873]
The metrics that we expose currently is quite verbose and incomplete. We discussed and agreed upon few metrics which are meaningful to add and for debugging also

And currently we have some default go related / process related metrics ( not explicitly exposed by MinIO ) such as `go_*` and `process_*` etc. Those can be removed.

The metrics can be simple as follows

<b> Node centered metrics </b>  (Per node details)

These metrics can have their prefix as `minio_hw_` and label as the endpoint
 
- CPU (can use `mc admin monitor` results)
- Memory (can use `mc admin monitor` results)
- Network speed 
- Uptime (Node uptime)
- Per drive usage ( with mount point as label )

<b> Process  centered metrics </b> (Per MinIO process)

These metrics can have their prefix as `minio_server_`

- MinIO server version
- Uptime (Process uptime)
- Memory usage
- HTTP requests ( only outbound requests - no internode calls)
- Bytes received/sent 
- error count

<b> Network centered metrics </b>

- Bytes send/ received (cumulative)

<b> Storage metrics </b>

- Storage used 
- Stoarage available

**Comment by krishnasrinivas** [comment]
Process centered metrics (Per MinIO process)

CPU usage (can use mc admin monitor results)
mem usage (can use mc admin monitor results)
HTTP requests (total)
read throughput (total)
write throughput (total)
error count (total)

**Comment by thomasf** [comment]
Please do not remove  `go_*` and `process_*` metrics,  they are really really useful for monitoring the state of all kinds of applications across a cluster with generalised and consistent metrics.

The `process_` ones are exported by all default prometheus libraries for multiple languages. 

When I query prometheus for `process_open_fds` I expect to get result from all monitored processes. It's just more work writing queries if minio exposes this metric by a different name or even worse not at all. 

In the case of `go_*` we have global alarm of threads/goroutine creation rate and the gc and memstats stuff is useful for after the fact investigating request latency issues, it's very useful to be able to dig down into individual services runtime behaviors.

If someone don't want them they can be dropped by relabelling config for the prometheus scrape target.   All you need to do is something like this.

```yaml
 - job_name: 'minio'
    scheme: https
    metrics_path: '/minio/prometheus/metrics'
    file_sd_configs:
      - files:
        - minio/*.yml
    metric_relabel_configs:
    - source_labels: [ __name__ ]
      regex: '(go_.*|process_.*)'
      action: drop    
```

Please leave it up to the individual users of minio to decide if go_ and process_ are of use or not.

**Comment by abperiasamy** [comment]
OK, agreed.

**Comment by thoro** [comment]
I would like to add my support for this, but possibly add some other metrics:

- heal status
- current heal progress (like reported in mc heal)
- current number of files (if the value is saved somewhere)

Current number of files could be reported on a per bucket basis (maybe optional), but not sure if that is actually help.

Possible error metrics, I'm not sure what can fail on minio, but I would like to have some metrics like:
- broken documents
- missings disks
- write errors
- read errors

**Comment by harshavardhana** [comment]
@Thoro we are planning to get to the first batch of metrics first. We will add more things subsequently.
