### ISSUE TITLE
Minio update on Windows

### ISSUE THREAD

**Issue by tinohager** [minio/minio#7881]
The update progress on Windows have some special chars in the console. It is possible to optimize it?
For me is always the value in the square bracket the default value in this case `yes` but if i press enter the update is not start.

> [32;1mUpdate to RELEASE.2019-06-27T21-13-50Z [yes][0m:

![image](https://user-images.githubusercontent.com/8215186/60706132-122d6e00-9f09-11e9-810d-cd526592a0c6.png)

After confirm with yes no progress info is available

![image](https://user-images.githubusercontent.com/8215186/60706182-3426f080-9f09-11e9-8457-464271d75c0a.png)

VERSION:
2019-06-15T23:07:18Z

**Comment by harshavardhana** [comment]
We will check @tinohager
