### ISSUE TITLE
Logo continuity

### ISSUE THREAD

**Issue by nomandera** [minio/minio#7884]
I am trying to locate the correct/official logo to use when referencing your project.

However there are several variations on the "bird" logo on github and the website that vary colours, facing direction and complexity in terms details within the "bird".

Please clear up which of the variations is the true project logo and ideally also document the license it is under (fair usage etc)

**Comment by nitisht** [comment]
It is documented here https://min.io/logo @anoma

**Comment by nomandera** [comment]
Thank you for the quick reply. It is now obviously very clearly documented and linked from the homepage.
