### ISSUE TITLE
Upload though web console stuck at 100% when files bigger than 1MB - K8s

### ISSUE THREAD

**Issue by mikekuzak** [minio/minio#7893]
## Expected Behavior
File should upload

## Current Behavior
Progress bar in browser hangs on 100%. Smaller file than 1MB did upload and I can see it on the filesystem. 

## Steps to Reproduce (for bugs)
![Minio](https://user-images.githubusercontent.com/18675587/60877573-00640780-a236-11e9-94d4-362e335509e2.JPG)

Request Method: PUT
**Status Code: 413 Request Entity Too Large**
Remote Address: 10.132.194.94:80
Referrer Policy: no-referrer-when-downgrade

## Your Environment
* Version used: 
Version: 2019-05-14T23:57:45Z
Release-Tag: RELEASE.2019-05-14T23-57-45Z
Commit-ID: 0022c9d210971c5661849c4b886cba8305b2b4f2
* Environment name and version (e.g. nginx 1.9.1): Used Helm Chart from Rancher Catalog. Minio Helm Chart 2.5.0
* Server type and version:
* Operating System and version (`uname -a`):
Underlying Host for Docker and K8s
Linux coreos-serv1 4.19.55-coreos #1 SMP Mon Jul 1 19:09:42 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz GenuineIntel GNU/Linux

* Link to your project:

**Comment by nitisht** [comment]
how is the MinIO service exposed outside of the cluster @mikekuzak

**Comment by mikekuzak** [comment]
Looks like the NGINX Ingress config had to be updated to change the allowed upload size
https://github.com/rancher/rancher/issues/14323
