### ISSUE TITLE
[Proposal] S3 select tests

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#7901]
More comprehensive tests for S3 testing (from outside)

Minio code contains many unit tests for S3 testing but no functional tests yet

**Comment by kalkotivinay** [comment]
I would like to work on this. Can we discuss what all s3 functional tests that need to be covered?

**Comment by harshavardhana** [comment]
> I would like to work on this. Can we discuss what all s3 functional tests that need to be covered?

Select needs to cover the basic API functionalities first @kalkotivinay https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectSELECTContent.html

**Comment by kalkotivinay** [comment]
> > I would like to work on this. Can we discuss what all s3 functional tests that need to be covered?
> 
> Select needs to cover the basic API functionalities first @kalkotivinay https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectSELECTContent.html

Thanks @harshavardhana. When you say basic API functionality, it means for all APIs, we should test for different input and output parameters, right?

**Comment by harshavardhana** [comment]
A lot of tests were added in recent refactor of S3 Select closing this as sufficient for now.
