### ISSUE TITLE
A user gets a error from Web UI when trying to edit a bucket policy.

### ISSUE THREAD

**Issue by andrewsav-bt** [minio/minio#7913]
When we create an additional user with full permissions, this user cannot read and edit bucket policies in web ui, however they can add policies with web ui, and they also view, add and edit policies with the mc cli. This feels inconsistent.

## Expected Behavior

It's hard to say what creator's intention was here, I had a chat on slack and @harshavardhana indicated that this is may be by design so that users don't "make accidentally their buckets public". I would expect something more consistent both between mc cli and Web UI, and also in Web UI between add and view/edit.

## Current Behavior

As per summary above.

## Possible Solution

If it was me, and I do not have the entire context, that creators have, I would allow an administrative user who can change something via mc cli also allow change the same via Web UI providing that this is already supported by Web UI for the "main" user.

Failing that, I would make the behaviour consistent:

- Either both allow or both disallow changes in Web UI and mc cli
- Either both allow or both disallow add and read/edit in Web UI

## Steps to Reproduce (for bugs)

Define a policy in `minio-admin.json` like this:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:*",
        "s3:PutBucketPolicy",
        "s3:GetBucketPolicy"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::*"
      ],
      "Sid": ""
    }
  ]
}
```

Push the policy to your minio server:

```powershell
mc admin policy add mt admin minio-admin.json
```

Here we assume that mt is configured for access with the "main" credentials.

Create a new user with this policy:

```powershell
mc admin user add mt user1 password123 admin
```

Login to the WebUI with these credenitals.

In the WebUI create a bucket my-bucket.

Click three dots next to it and select "Edit policy". Observe:
![minio01](https://user-images.githubusercontent.com/27190911/61080041-47413f80-a478-11e9-9011-19c06f30f4d0.png)

Press the blue Add button. 

Observe that inside of the "Bucket Policy" window is unresponsive (although you can close it with `x`.

Press `x` to close the "Bucket Policy" window and `x` to close the red error. 

Log out from WebUI.

Log in as the "main" user. Open the "Bucket Policy" and observe that `user1` actually succeeded at setting the policy despite the error and the unresponsiveness:
![minio02](https://user-images.githubusercontent.com/27190911/61080269-ca629580-a478-11e9-9fa9-303f56283b70.png)

Now from command line add the user:

```powershell
mc config host add mtest https://minio user1 password123
```

(Use your own URL). Now you can list the bucket policy, and delete the bucket policy from command line:
![minio03](https://user-images.githubusercontent.com/27190911/61080393-131a4e80-a479-11e9-9990-5049f6b742e5.png)

but not from the WebUI.

## Context

I would like to give other users access to the minio server that I administer without giving them the "main" credentials. I would like these users to be able to edit bucket policies if they have been given permissions to do so. I would like this not to fail in WebUI, since it's not failing for the "main" user.

## Regression

Unknown.

## Your Environment

* Version used (`minio version`): RELEASE.2019-07-05T21-20-21Z
* Environment name and version (e.g. nginx 1.9.1): minio/minio official docker image
* Server type and version: minio/minio official docker image
* Operating System and version (`uname -a`): minio/minio official docker image
* Link to your project: N/A

**Comment by harshavardhana** [comment]
Thanks for opening the issue @andrewsav-datacom 

@kannappanr @deekoder taking this since I was engaged with @andrewsav-datacom on the chat.
