### ISSUE TITLE
Can not list buckets using hadoop

### ISSUE THREAD

**Issue by ravindraSB** [minio/minio#7918]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
@ravindraSB hadoop doesn't support that on their own - they only support `s3a://<bucket>`

**Comment by harshavardhana** [comment]
Going to close this issue also as incomplete, there is nothing actionable on our end for this.  This is working as intended from hadoop point of view.
