### ISSUE TITLE
Ghost files visible on the Minio UI after file upload

### ISSUE THREAD

**Issue by mikekuzak** [minio/minio#7921]
![Minio1](https://user-images.githubusercontent.com/18675587/61126418-4920f800-a4a4-11e9-9943-f58b50b03fca.JPG)

## Steps to Reproduce (for bugs)
just uploaded files via UI and Java REST client

## Your Environment
Version used:
Version: 2019-05-14T23:57:45Z
Release-Tag: RELEASE.2019-05-14T23-57-45Z
Commit-ID: 0022c9d

Environment name and version (e.g. nginx 1.9.1): Used Helm Chart from Rancher Catalog. Minio Helm Chart 2.5.0

Server type and version:

Operating System and version (uname -a):
Underlying Host for Docker and K8s
Linux coreos-serv1 4.19.55-coreos #1 SMP Mon Jul 1 19:09:42 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz GenuineIntel GNU/Linux

**Comment by kanagarajkm** [comment]
@mikekuzak this is already fixed, can you update to recent version MinIO and try again?

**Comment by mikekuzak** [comment]
confirmed, issue gone with Version: 2019-07-10T00:34:56Z
