### ISSUE TITLE
How to connect with domain minio without port

### ISSUE THREAD

**Issue by vctqs1** [minio/minio#7922]
`const minioConfig = {
    endPoint: 'example.domain,
    useSSL: false,
    accessKey: process.env.accessKey,
    secretKey: process.env.secretKey 
}`

Error:
`{ S3Error: Moved Permanently
    at getError (/Users/macbookpro/Documents/project/kgp_news/api_kgp/node_modules/minio/dist/main/transformers.js:104:15)`

**Comment by kannappanr** [comment]
@vctqs1 Please use Nginx proxy before MinIO to route `80` to the MinIO port.

**Comment by harshavardhana** [comment]
Or start minio on port 80 `minio server --address ":80"`

**Comment by kannappanr** [comment]
@vctqs1 Closing this issue now. Please feel free to reach out to us at https://slack.min.io for such questions.

**Comment by phpjsnerd** [comment]
Don't directly expose to outside network use Reverse proxy such as nginx in Production environment.
