### ISSUE TITLE
Do not fetch AWS ETAG until cache object is stale.

### ISSUE THREAD

**Issue by rldleblanc** [minio/minio#7938]
Currently all cache objects have their ETAG downloaded from AWS before the cache is served even if cache-control is not expired/stale. When an owner specifies a cache-control they assume responsibility that any system in the line can have an out dated item of that length of time. MinIO should not try to enforce the cache has the latest object before serving the object and only request the ETAG if the cache item is stale.

If cache-control is set to 'off', 'none', '0' or some other thing that means don't cache it does not mean that MinIO can't cache the object, it just means that the ETAG needs to be checked for every request (as it does now).

If a stale object matches the ETAG, then reset the timer and serve from cache.

For more improvement, if an object requested only has some percentage of life left (20%), then the item could be served from cache and in the background MinIO can request the ETAG and refresh as needed so that if the item is asked for again it would be either served with the new item or does not have to block for a round trip to AWS to validate a stale item.

This should dramatically improve the performance of small objects in the cache.

**Comment by kannappanr** [comment]
@rldleblanc We will go through the issue and get back to you.
