### ISSUE TITLE
logging: Single-line logs

### ISSUE THREAD

**Issue by srilumpa** [minio/minio#7939]
**Is your feature request related to a problem? Please describe.**
We are running minIO on distributed mode on a Kubernetes cluster and want to gather the minIO logs for troubleshooting purposes (among other things). Problem is that whensomething is logged by minIO, it is done using multiples lines like so:

```
API: webDeleteBucket()
Time: 09:45:15 UTC 07/16/2019
DeploymentID: d55b1be1-197f-429d-8764-f6724e3d3dbc
RemoteHost: 127.0.0.1
UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Error: Bucket not empty: test
        3: cmd/web-handlers.go:2010:cmd.toWebAPIError()
        2: cmd/web-handlers.go:1890:cmd.toJSONError()
        1: cmd/web-handlers.go:286:cmd.(*webAPIHandlers).DeleteBucket()
```

Issue is when collecting all of this in a log management system (we are using Elasticsearch/Logstash/Kibana but issue will be the same for all the other systems I know) we would have one log for the `API:...`, one line for `Time:...` and so one. This makes difficult to correlate all the data once those logs are centralized in our log management platform since there are no logical links between each log line other than their order.

**Describe the solution you'd like**
Having a single line for each log would greatly help process the logs. The ideal might be following some JSON format. The previous log would be then formatted like this:

```json
{"API": "webDeleteBucket()", "Time": "09:45:15 UTC 07/16/2019", "DeploymentID": "d55b1be1-197f-429d-8764-f6724e3d3dbc", "RemoteHost": "127.0.0.1", "UserAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0", "Error": "Bucket not empty: test\n    3: cmd/web-handlers.go:2010:cmd.toWebAPIError()\n    2: cmd/web-handlers.go:1890:cmd.toJSONError()\n    1: cmd/web-handlers.go:286:cmd.(*webAPIHandlers).DeleteBucket()"}
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kanagarajkm** [comment]
@srilumpa you can use `--json` option while starting the minio server

```
--json                        output server logs and startup information in json format
```

**Comment by kannappanr** [comment]
@srilumpa Closing this issue as answered. Please feel free to reach out to us at https://slack.min.io for such questions.
