### ISSUE TITLE
RELEASE.2019-07-17T22-54-12Z breaks Openshift Support

### ISSUE THREAD

**Issue by Reamer** [minio/minio#7943]
Hi,

I use minio on Openshift 3.11. Openshift has a security feature, to run container with "random" uids.
Helpful-Link: ["Why do my applications run as a random user ID?"](https://cookbook.openshift.org/users-and-role-based-access-control/why-do-my-applications-run-as-a-random-user-id.html)

I think #7930 breaks the Openshift Support. [RELEASE.2019-07-10T00-34-56Z](https://github.com/minio/minio/releases/tag/RELEASE.2019-07-10T00-34-56Z) works great on Openshift. 
## Expected Behavior
Minio should be able to start/run with a random uid. Output of command `id` with [RELEASE.2019-07-10T00-34-56Z](https://github.com/minio/minio/releases/tag/RELEASE.2019-07-10T00-34-56Z)
```bash
/ $ id
uid=1000330000 gid=0(root) groups=1000330000
```

## Current Behavior
I get following error message with [RELEASE.2019-07-17T22-54-12Z](https://github.com/minio/minio/releases/tag/RELEASE.2019-07-17T22-54-12Z) at minio startup.
```
su-exec: setgroups(0): Operation not permitted
```

## Possible Solution
revert #7930 or rewrite startup script

## Steps to Reproduce (for bugs)
1. Run Minio on Openshift with default security

other way with only Docker

1. `docker run --user 123123 minio/minio:RELEASE.2019-07-17T22-54-12Z`

## Regression
Yes, [RELEASE.2019-07-10T00-34-56Z](https://github.com/minio/minio/releases/tag/RELEASE.2019-07-10T00-34-56Z) works great. I think #7930 breaks the Openshift Support.

## Your Environment
* Version used (`minio version`):  I'm using docker-images for minio. minio/minio:RELEASE.2019-07-10T00-34-56Z

**Comment by nitisht** [comment]
@Reamer do you have `MINIO_USERNAME` / `MINIO_GROUPNAME` set in the your yaml ?

**Comment by Reamer** [comment]
Hi @nitisht,
no I haven't set `MINIO_USERNAME` or `MINIO_GROUPNAME`, because I think, it's not necessary.
Please checkout #7944. I think I found a typo in `docker-entrypoint.sh`. For me it makes no sense to add a group or a user with an empty `MINIO_USERNAME` or `MINIO_GROUPNAME`

If you set `MINIO_USERNAME` and `MINIO_GROUPNAME` you are in the "fallback" case and `MINIO_USERNAME` and `MINIO_GROUPNAME` has no effect at all.

You can test this with
```bash
$ docker run --user 123234 --env MINIO_USERNAME=minio  minio/minio:RELEASE.2019-07-17T22-54-12Z
su-exec: setgroups(0): Operation not permitted
```

**Comment by rblaine95** [comment]
The `if-statement` itself doesn't really make sense. If you're running the container as any user other than `root`, you'll get a permission denied when trying to `addgroup` and `adduser`.
