### ISSUE TITLE
Can't ‘endpoint’ of webhook set ports 80 and 443?

### ISSUE THREAD

**Issue by tiankongzhixia** [minio/minio#7946]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by nitisht** [comment]
This issue is incomplete @tiankongzhixia please follow the issue template or join us on Slack (https://slack.min.io) for questions.

**Comment by tiankongzhixia** [comment]
Sorry, my network is not very good. I can't edit the above content.
The contents of my config.json

"endpoint": "https://work.timemf.com:443/minio/webhook"
 
Prompt me after startup

panic: target.Send() failed with 'dial tcp: address work.timemf.com: missing port in address'

goroutine 129 [running]:
github.com/minio/minio/pkg/event/target.sendEvents.func1(0xc0000ae330, 0x24, 0x2)
        /q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/store.go:107 +0x355
github.com/minio/minio/pkg/event/target.sendEvents(0x1c17e20, 0xc000356000, 0xc00030ec60, 0xc00054a000)
        /q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/store.go:128 +0x187
created by github.com/minio/minio/pkg/event/target.NewWebhookTarget
        /q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/webhook.go:225 +0x2af

**Comment by Praveenrajmani** [comment]
@tiankongzhixia Can you try pinging `work.timemf.com:443`? looks like the config is missing the port. Can you reach us on https://slack.min.io. And also for any change in the config ( after successful `mc admin config set`) - the server should be restarted.

**Comment by tiankongzhixia** [comment]
I used mc.exe admin config set ...
Change the configuration to

"endpoint": "https://work.timemf.com/minio/webhook"

Still will prompt me
Tcp: address work.timemf.com: missing port in address

Windows version: 2019-07-17T22:54:12Z

I am using this under macOS without this problem.

**Comment by timemf** [comment]
The configuration file has not changed, and the minIo version of macOS has been updated to the latest. This problem has also occurred...

**Comment by Praveenrajmani** [comment]
@tiankongzhixia will send a PR soon

**Comment by timemf** [comment]
@Praveenrajmani thank you for your help
