### ISSUE TITLE
Extending Issue #7892: Knob/Setting to tune the frequency of healing 

### ISSUE THREAD

**Issue by adiospeds** [minio/minio#7952]
I loved it when daily auto healing feature was added. However, even I have a cluster with loads of small files. Even I had recently upgraded to the daily auto healing version and noticed that my cpu was always high and kept receiving lot of socket timeouts on my monitoring apps. Hopefully upgrading to this version will fix this issue for me. But I'd like to have a way to control the auto healing frequency. Some kind of setting in the config file, bcas daily healing worked great for small cluster on vm's with lesser medium sized files. These vm's were oftenly brought down for patching purposes and daily healing fixed the missing files on them. I guess the healing frequency is moreover dependent on size of files on cluster and frequency at which the cluster nodes go down. **Providing a knob to tune the frequency of healing would be greatly helpful.**

**Comment by harshavardhana** [comment]
Healing should have improved quite significantly - do you still see this issue being relevant from latest releases, we would rather avoid providing knobs to tune these parameters..
