### ISSUE TITLE
Minio Browser: Allow for shareable links not to expire

### ISSUE THREAD

**Issue by rafamel** [minio/minio#7956]
Shareable links validity is currently set to a maximum of 7 days. Is there any way you would consider allowing them to be set not to expire at all?

**Comment by nitisht** [comment]
This is as per S3 API Specs : https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html . So there are no plans to change the behaviour. 

One way to achieve this is to set the bucket policy to download

**Comment by harshavardhana** [comment]
Closing as working as intended
