### ISSUE TITLE
Allow use of Signature v2 in S3 gateway configuration

### ISSUE THREAD

**Issue by aqpartners** [minio/minio#7961]
**Is your feature request related to a problem? Please describe.**
When attempting to set up an S3 gateway in front of an API that only accepts requests signed with signature v2 (i.e. EMR ViPR), we get the error `ERROR Unable to initialize gateway backend: The request signature we calculated does not match the signature you provided`.  I confirmed that the gateway currently inly supports v4 signature in the initialization, but would request support for v2 as well.

**Describe the solution you'd like** 
On initialization the gateway can test setting up with the v4 signature and if it fails, attempt with the v2 signature

**Describe alternatives you've considered**
A way to tell the gateway which API to use in the configuration

**Additional context**
Although the v2 signature is soon-to-be-deprecated by AWS, unfortunately some "S3 compliant API" providers still only support v2

**Comment by harshavardhana** [comment]
This was on purpose because v2 signature is insecure, we only support that for legacy reasons on MinIO, so converting a v4 to v2 request is a bad idea.

Can you tell us why are you using S3 gateway? Is it caching?

**Comment by aqpartners** [comment]
Looking for ways to use tools that only support v4 (such as the C++ AWS SDK) with the legacy system.  I understand that it is not as secure but if I am willing to take on the risk, can it at least be configurable?

**Comment by harshavardhana** [comment]
> Looking for ways to use tools that only support v4 (such as the C++ AWS SDK) with the legacy system. I understand that it is not as secure but if I am willing to take on the risk, can it at least be configurable?

You may recompile the code if that is the case @aqpartners - we cannot allow that in our code to run in insecure mode.

**Comment by harshavardhana** [comment]
Closing this as non actionable for us.
