### ISSUE TITLE
Browser: Download as Zip (containing MP4's)

### ISSUE THREAD

**Issue by ghost** [minio/minio#7965]
When using the web GUI to download a folder or files within a bucket as a zip file it seems to work fine for files with type JSON but if you have a list of MP4's if you select more than 1 you get a small 0 byte file.

## Expected Behavior

The zip file should contain all selected MP4 files

## Current Behavior

as described above, when we select more than 1 mp4 we get a zero byte mp4 file in a zip file

## Steps to Reproduce (for bugs)

1. upload a number of mp4's to a folder within a bucket
2.select more than one or the entire folder
3.select download as zip
4.

## Context

impacts using the web gui to download files

## Your Environment

* Version used (`minio version`): 2019-07-10T00:34:56Z
* Environment name and version (e.g. nginx 1.9.1): N/A
* Server type and version: bare metal (4 server cluster each with i9/32GB/8TB SSD)
* Operating System and version (`uname -a`): Linux svr-minio-004 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by kannappanr** [comment]
@hassbabaie Thanks for filing this issue. We will take a look.

**Comment by kaankabalak** [comment]
I am also able to verify this issue on https://play.min.io, regardless of the file extension. When I select multiple files from a bucket and download as zip, I get a zero byte file that has the name of the first selected file.

Also, when I select and download a folder which is inside a bucket; inside any subfolders, only the first items are preserved and if the final item is not a folder, it is corrupted.

As an example, for the folder named `random` inside a bucket that has the following structure:

```
random/
├── myfolder
│   ├── 3_1512386062639.jpg
│   ├── logo_rectangle.png
│   └── winter-22506_640\ (2).jpg
└── test
    └── thumb.jpeg
```

Upon downloading the folder `random` as a .zip, we get the following and 3_1512386062639.jpg is a zero byte object.

```
random/
└── myfolder
    └── 3_1512386062639.jpg
```

However, when I tried this on my local setup in standalone mode where I start the server by using `./minio server /tmp/data_dir`, I am not encountering the issue. I will further look into this issue and keep you updated.

**Comment by kaankabalak** [comment]
@hassbabaie We were able to reproduce this issue using the following command. The issue seems to be caused when the objects being downloaded have been encrypted using SSE-S3:

```
MINIO_SSE_AUTO_ENCRYPTION=on MINIO_SSE_MASTER_KEY=my-minio-key:6368616e676520746869732070617373776f726420746f206120736563726574 minio server /tmp/path
```

We will be working on a fix in the meantime and will keep you updated.

**Comment by kaankabalak** [comment]
@hassbabaie We were able to reproduce this issue using the following command. The issue seems to be caused when the objects being downloaded have been encrypted using SSE-S3:

```
MINIO_SSE_AUTO_ENCRYPTION=on MINIO_SSE_MASTER_KEY=my-minio-key:6368616e6765207468e673f030617373776f726420746f206420736563726574 minio server /tmp/path
```

We will be working on a fix in the meantime and will keep you updated.

**Comment by ghost** [comment]
Thanks @kaankabalak

**Comment by aead** [comment]
Can confirm that this is caused by encryption - the offset/size calculation (during decryption) is wrong. Have to investigate.

**Comment by aead** [comment]
Update: Tried to bisect this for a few hours - problem is that ZIPDownload does not work with SSE-C but not all versions (during bisect) support SSE-S3. Have to do a manual search... However, can confirm from bisect that the issue is a wrong length calculation for encrypted objects...

**Comment by juniorschen** [comment]
how can i download from apis, when i try to do with go it gives me the following error:
![image](https://user-images.githubusercontent.com/46031261/88430319-9ed5f300-cdce-11ea-8fda-bde8a69834ef.png)
