### ISSUE TITLE
Readonly user is not able to view existing buckets

### ISSUE THREAD

**Issue by kanagarajkm** [minio/minio#7970]
IAM user with `readonly` policy is not able to view the buckets.

## Expected Behavior
IAM user with `readonly` policy should have read access to all the buckets on MinIO.

## Current Behavior
IAM user with `readonly` policy does not have access to buckets in MinIO

## Steps to Reproduce (for bugs)

1. Run MinIO in fs mode
2. Add a new user with readwrite policy `mc admin user add local user1 user1passwd readwrite`
3. Add another user with readonly policy `mc admin user add local user2 user2passwd readonly`
4. Login to MinIO browser as user1, create some buckets and upload files, logout
5. Login to MinIO browser as user2, none of the buckets are visible
6. Similar thing happens with mc as well. 
`mc config host add myminio http://127.0.0.1:9000 user2 user2passwd`
`mc ls myminio`
`mc: <ERROR> Unable to list folder. Access Denied.`

## Your Environment

* Version used (`minio version`):  `Version: 2019-07-24T02:02:23Z`
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: FS
* Operating System and version (`uname -a`): `Linux kanagaraj-X260 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Link to your project:

**Comment by harshavardhana** [comment]
> IAM user with `readonly` policy should have read access to all the buckets on MinIO.

It is on purpose avoided @kanagarajkm - users want only GET calls not ListObjects() 

```
{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:GetObject","s3:GetBucketLocation"],"Resource":["arn:aws:s3:::*"]}]}
```

User should come up with an appropriate policy if they wish to list buckets as well.

**Comment by kanagarajkm** [comment]
@harshavardhana understood, i can do GET object as readonly user, closing this issue, thanks!
