### ISSUE TITLE
minio-2019.07.24.02.02.23: gokrb5/v7/service/authenticator.go:85:4: cannot use cl.Credentials

### ISSUE THREAD

**Issue by Zlogene** [minio/minio#7975]
I am Gentoo minio maintainer, today I had hit a compile failure as described in the title ( go version is 1.12.5)

## Expected Behavior

minio compiles fine

## Your Environment

* Version used (2019.07.24.02.02.23)::
* Operating System and version (Linux unrandom 4.19.57-gentoo #1 SMP Wed Jul 17 11:00:04 MSK 2019 x86_64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz GenuineIntel GNU/Linux):

**Comment by harshavardhana** [comment]
You should use GO111MODULE=on and use `go mod` dependencies to build. All our CIs run fine so it is a local issue.

**Comment by kannappanr** [comment]
@Zlogene Closing this issue as answered. Please feel free to let us know if what was suggested doesn't work.
