### ISSUE TITLE
Minio does not handle copy_object properly in federation setup

### ISSUE THREAD

**Issue by aeltawela** [minio/minio#7976]
In federation setup, Minio fails to copy any object that exists on another setup to a third setup.

In other words, if the user tried to copy a file (using SetupA as an endpoint) that exists in SetupB to SetupC, the copy operation fails with a bucket does not exist error.

## Expected Behavior

The copy object should be handled correctly in federation setup regardless of the endpoint.

## Current Behavior

It fails to do so.

## Possible Solution

Check the src bucket properly.

## Steps to Reproduce (for bugs)

1. Setup 3 instances in federation mode (SetupA, SetupB, SetupC)
2. Create bucketB in SetupB
3. Create bucketC in SetupC 
4. Upload file to BucketB
5. Copy the same file from bucketB to bucketC using SetupA as an endpoint.

## Context

Copying files around different Minio instances in federation setup.

## Your Environment

* Version used (`minio version`): RELEASE.2019-03-27T22-35-21Z

## Debug Traces
`mc: <DEBUG> GET /bucketb/?location= HTTP/1.1
Host: minio.intel.com
User-Agent: MinIO (windows; amd64) minio-go/v6.0.31 mc/2019-07-09T23:57:06Z
Authorization: AWS4-HMAC-SHA256 Credential=ata_user/20190725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20190725T194147Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Thu, 25 Jul 2019 19:41:49 GMT
Server: nginx/1.13.12
Strict-Transport-Security: max-age=15724800; includeSubDomains
Vary: Accept-Encoding
Vary: Origin
X-Amz-Request-Id: 15B4BDD8BB9E0850
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  1.8316078s

mc: <DEBUG> GET /bucketb/?delimiter=%2F&max-keys=1000&prefix=GMATHALY-MOBL1_24072019160605%2FfileB HTTP/1.1
Host: minio.intel.com
User-Agent: MinIO (windows; amd64) minio-go/v6.0.31 mc/2019-07-09T23:57:06Z
Authorization: AWS4-HMAC-SHA256 Credential=ata_user/20190725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190725T194149Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Thu, 25 Jul 2019 19:41:50 GMT
Server: nginx/1.13.12
Strict-Transport-Security: max-age=15724800; includeSubDomains
Vary: Accept-Encoding
Vary: Origin
X-Amz-Request-Id: 15B4BDD8F68119B0
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  846.0058ms

mc: <DEBUG> GET /bucketb/?delimiter=%2F&max-keys=1000&prefix=GMATHALY-MOBL1_24072019160605%2FfileB HTTP/1.1
Host: minio.intel.com
User-Agent: MinIO (windows; amd64) minio-go/v6.0.31 mc/2019-07-09T23:57:06Z
Authorization: AWS4-HMAC-SHA256 Credential=ata_user/20190725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190725T194150Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Thu, 25 Jul 2019 19:41:51 GMT
Server: nginx/1.13.12
Strict-Transport-Security: max-age=15724800; includeSubDomains
Vary: Accept-Encoding
Vary: Origin
X-Amz-Request-Id: 15B4BDD9309D22A3
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  757.998ms

mc: <DEBUG> GET /bucketc/?location= HTTP/1.1
Host: minio.intel.com
User-Agent: MinIO (windows; amd64) minio-go/v6.0.31 mc/2019-07-09T23:57:06Z
Authorization: AWS4-HMAC-SHA256 Credential=ata_user/20190725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20190725T194151Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 128
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Thu, 25 Jul 2019 19:41:52 GMT
Server: nginx/1.13.12
Strict-Transport-Security: max-age=15724800; includeSubDomains
Vary: Origin
X-Amz-Request-Id: 15B4BDD970477DA9
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  779.4212ms

mc: <DEBUG> GET /bucketc/?delimiter=%2F&max-keys=1000&prefix=SMS38%2FSMS3822%2FSMS382294%2FSMS38229475%2FfileB HTTP/1.1
Host: minio.intel.com
User-Agent: MinIO (windows; amd64) minio-go/v6.0.31 mc/2019-07-09T23:57:06Z
Authorization: AWS4-HMAC-SHA256 Credential=ata_user/20190725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190725T194152Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 666
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Thu, 25 Jul 2019 19:41:53 GMT
Server: nginx/1.13.12
Strict-Transport-Security: max-age=15724800; includeSubDomains
Vary: Accept-Encoding
Vary: Origin
X-Amz-Request-Id: 15B4BDD99EF3DF0E
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  842.5286ms

mc: <DEBUG> GET /bucketb/?delimiter=%2F&max-keys=1000&prefix=GMATHALY-MOBL1_24072019160605%2FfileB HTTP/1.1
Host: minio.intel.com
User-Agent: MinIO (windows; amd64) minio-go/v6.0.31 mc/2019-07-09T23:57:06Z
Authorization: AWS4-HMAC-SHA256 Credential=ata_user/20190725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190725T194153Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Thu, 25 Jul 2019 19:41:53 GMT
Server: nginx/1.13.12
Strict-Transport-Security: max-age=15724800; includeSubDomains
Vary: Accept-Encoding
Vary: Origin
X-Amz-Request-Id: 15B4BDD9C664948B
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  714.0861ms

mc: <DEBUG> GET /bucketb/?delimiter=%2F&max-keys=1000&prefix=GMATHALY-MOBL1_24072019160605%2FfileB HTTP/1.1
Host: minio.intel.com
User-Agent: MinIO (windows; amd64) minio-go/v6.0.31 mc/2019-07-09T23:57:06Z
Authorization: AWS4-HMAC-SHA256 Credential=ata_user/20190725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190725T194154Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Thu, 25 Jul 2019 19:41:54 GMT
Server: nginx/1.13.12
Strict-Transport-Security: max-age=15724800; includeSubDomains
Vary: Accept-Encoding
Vary: Origin
X-Amz-Request-Id: 15B4BDD9FD8C9488
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  746.9504ms

mc: <DEBUG> GET /bucketc/?delimiter=%2F&max-keys=1000&prefix=SMS38%2FSMS3822%2FSMS382294%2FSMS38229475%2FfileB HTTP/1.1
Host: minio.intel.com
User-Agent: MinIO (windows; amd64) minio-go/v6.0.31 mc/2019-07-09T23:57:06Z
Authorization: AWS4-HMAC-SHA256 Credential=ata_user/20190725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190725T194154Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 666
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Thu, 25 Jul 2019 19:41:55 GMT
Server: nginx/1.13.12
Strict-Transport-Security: max-age=15724800; includeSubDomains
Vary: Accept-Encoding
Vary: Origin
X-Amz-Request-Id: 15B4BDDA348CF541
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  670.7043ms

mc: <DEBUG> GET /bucketb/?delimiter=%2F&max-keys=1000&prefix=GMATHALY-MOBL1_24072019160605%2FfileB HTTP/1.1
Host: minio.intel.com
User-Agent: MinIO (windows; amd64) minio-go/v6.0.31 mc/2019-07-09T23:57:06Z
Authorization: AWS4-HMAC-SHA256 Credential=ata_user/20190725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190725T194155Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Thu, 25 Jul 2019 19:41:56 GMT
Server: nginx/1.13.12
Strict-Transport-Security: max-age=15724800; includeSubDomains
Vary: Accept-Encoding
Vary: Origin
X-Amz-Request-Id: 15B4BDDA5BE41A3D
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  720.8705ms

`SetupA/bucketb/GMATHALY-MOBL1_24072019160605/fileB` -> `SetupA/bucketc/SMS/fileB`
mc: <DEBUG> GET /bucketb/?delimiter=%2F&max-keys=1000&prefix=GMATHALY-MOBL1_24072019160605%2FfileB HTTP/1.1
Host: minio.intel.com
User-Agent: MinIO (windows; amd64) minio-go/v6.0.31 mc/2019-07-09T23:57:06Z
Authorization: AWS4-HMAC-SHA256 Credential=ata_user/20190725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190725T194156Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Thu, 25 Jul 2019 19:41:57 GMT
Server: nginx/1.13.12
Strict-Transport-Security: max-age=15724800; includeSubDomains
Vary: Accept-Encoding
Vary: Origin
X-Amz-Request-Id: 15B4BDDA9349C290
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  740.4099ms

mc: <DEBUG> HEAD /bucketb/GMATHALY-MOBL1_24072019160605/fileB HTTP/1.1
Host: minio.intel.com
User-Agent: MinIO (windows; amd64) minio-go/v6.0.31 mc/2019-07-09T23:57:06Z
Authorization: AWS4-HMAC-SHA256 Credential=ata_user/20190725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190725T194157Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 205284
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/octet-stream
Date: Thu, 25 Jul 2019 19:41:58 GMT
Etag: "37a74f95d5bf5e85bf77d62aac484443"
Last-Modified: Thu, 25 Jul 2019 10:06:20 GMT
Server: nginx/1.13.12
Strict-Transport-Security: max-age=15724800; includeSubDomains
Vary: Origin
X-Amz-Meta-Uuid: d98deafa-aec3-11e9-9040-dad4c78a44ca
X-Amz-Request-Id: 15B4BDDACACF8A8B
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  685.8713ms

mc: <DEBUG> HEAD /bucketb/GMATHALY-MOBL1_24072019160605/fileB HTTP/1.1
Host: minio.intel.com
User-Agent: MinIO (windows; amd64) minio-go/v6.0.31 mc/2019-07-09T23:57:06Z
Authorization: AWS4-HMAC-SHA256 Credential=ata_user/20190725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190725T194158Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 205284
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/octet-stream
Date: Thu, 25 Jul 2019 19:41:58 GMT
Etag: "37a74f95d5bf5e85bf77d62aac484443"
Last-Modified: Thu, 25 Jul 2019 10:06:20 GMT
Server: nginx/1.13.12
Strict-Transport-Security: max-age=15724800; includeSubDomains
Vary: Origin
X-Amz-Meta-Uuid: d98deafa-aec3-11e9-9040-dad4c78a44ca
X-Amz-Request-Id: 15B4BDDAF9D34559
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  809.926ms

mc: <DEBUG> HEAD /bucketb/GMATHALY-MOBL1_24072019160605/fileB HTTP/1.1
Host: minio.intel.com
User-Agent: MinIO (windows; amd64) minio-go/v6.0.31 mc/2019-07-09T23:57:06Z
Authorization: AWS4-HMAC-SHA256 Credential=ata_user/20190725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190725T194158Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 205284
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/octet-stream
Date: Thu, 25 Jul 2019 19:41:59 GMT
Etag: "37a74f95d5bf5e85bf77d62aac484443"
Last-Modified: Thu, 25 Jul 2019 10:06:20 GMT
Server: nginx/1.13.12
Strict-Transport-Security: max-age=15724800; includeSubDomains
Vary: Origin
X-Amz-Meta-Uuid: d98deafa-aec3-11e9-9040-dad4c78a44ca
X-Amz-Request-Id: 15B4BDDB22265F66
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  654.3086ms

mc: <DEBUG> PUT /bucketc/SMS/fileB HTTP/1.1
Host: minio.intel.com
User-Agent: MinIO (windows; amd64) minio-go/v6.0.31 mc/2019-07-09T23:57:06Z
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=ata_user/20190725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-copy-source;x-amz-date;x-amz-meta-uuid;x-amz-metadata-directive, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Copy-Source: bucketb/GMATHALY-MOBL1_24072019160605/fileB
X-Amz-Date: 20190725T194159Z
X-Amz-Meta-Uuid: d98deafa-aec3-11e9-9040-dad4c78a44ca
X-Amz-Metadata-Directive: REPLACE
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Thu, 25 Jul 2019 19:41:59 GMT
Server: nginx/1.13.12
Strict-Transport-Security: max-age=15724800; includeSubDomains
Vary: Accept-Encoding
Vary: Origin
X-Amz-Request-Id: 15B4BDDB31ADCADB
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

164
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><Key>SMS/fileB</Key><BucketName>bucketc</BucketName><Resource>/bucketc/SMS/fileB</Resource><RequestId>15B4BDDB31ADCADB</RequestId><HostId></HostId></Error>
0

mc: <DEBUG> Response Time:  326.7988ms

mc: <ERROR> Failed to copy `https://minio.intel.com/bucketb/GMATHALY-MOBL1_24072019160605/fileB`. Bucket `bucketc` does not exist.
 (3) /q/.q/sources/gopath/src/github.com/minio/mc/cmd/cp-main.go:425 cmd.doCopySession(..) Tags: [https://minio.intel.com/bucketb/GMATHALY-MOBL1_24072019160605/fileB]
 (2) /q/.q/sources/gopath/src/github.com/minio/mc/cmd/common-methods.go:261 cmd.uploadSourceToTargetURL(..) Tags: [https://minio.intel.com/bucketb/GMATHALY-MOBL1_24072019160605/fileB]
 (1) /q/.q/sources/gopath/src/github.com/minio/mc/cmd/common-methods.go:204 cmd.copySourceToTargetURL(..) Tags: [SetupA, https://minio.intel.com/bucketc/SMS/fileB]
 (0) /q/.q/sources/gopath/src/github.com/minio/mc/cmd/client-s3.go:746 cmd.(*s3Client).Copy(..)
 Release-Tag:RELEASE.2019-07-09T23-57-06Z | Commit:df9320134bfb | Host:aaeltawe-MOBL1 | OS:windows | Arch:amd64 | Lang:go1.12.5 | Mem:1.3 MB/11 MB | Heap:1.3 MB/7.9 MB
Total: 200.47 KiB, Transferred: 0 B, Speed: 0 B/s
`

**Comment by kannappanr** [comment]
@ahmedabt Can you try with the latest `MinIO` binary that was released on `07-24` 2019-07-24T02-02-23Z and let us know if you are still seeing this issue?

**Comment by aeltawela** [comment]
@kannappanr unfortunately, it is not that easy to change the baseline on our environment, we have to test it heavily first. Do you suspect a specific fix that fixes this issue? I think it is easy to verify the behavior from the code.

**Comment by harshavardhana** [comment]
Our idea is to handle this properly, will verify your issue here and get back to you @ahmedabt

**Comment by maihde** [comment]
On a similar note, I found that it doesn't require a three node setup.  Here is what I was trying to accomplish and encountered a similar error


1.    Setup 2 instances in federation mode (SetupA, SetupB)
2.    Create testA in SetupA
3.    Create testB in SetupB
4.    Upload fileA to testA

If the destination is on the remote node, the copy succeeds

```
mc = Minio('SetupA')
mc.copy_object(
   "testA",
   "newFile",
   "testB/fileA"
)
```  

However, if the source file is on a remote node, the copy fails:

```
mc = Minio('SetupB')
mc.copy_object(
   "testA",
   "newFile",
   "testB/fileA"
)
```

This appears to be due the fact that getObjectNInfo on the srcBucket is not aware of federated buckets.

``` 
getOpts.CheckCopyPrecondFn = checkCopyPrecondFn
srcOpts.CheckCopyPrecondFn = checkCopyPrecondFn
var rs *HTTPRangeSpec
gr, err := getObjectNInfo(ctx, srcBucket, srcObject, rs, r.Header, lock, getOpts)
if err != nil {
	if isErrPreconditionFailed(err) {
		return
	}
	writeErrorResponse(ctx, w, toAPIError(ctx, err), r.URL, guessIsBrowserReq(r))
	return
}
```

**Comment by harshavardhana** [comment]
The assumption here is that the virtual DNS for the source bucket would have resolved to right node, the issue is not related to GetObjectNInfo() not being aware. The issue is in bucket forwarding handler which should validate if the source is local or remote.
