### ISSUE TITLE
Add STS API to let users from LDAP access Minio

### ISSUE THREAD

**Issue by donatello** [minio/minio#7989]
This issue is to track progress on this feature.

The task breakup is as follows:

1. Add groups support to MinIO - this allows MinIO users to organize users into groups and setting an access policy for all members of a group.
    * Add group creation and management support - https://github.com/minio/minio/pull/7981
    * Add policy mapping support to a group
2. Add LDAP support, including users and groups integration.

**Comment by harshavardhana** [comment]
This feature has been fully implemented.
