### ISSUE TITLE
gateway with etcd: STS token is returned before it's usable by minio cluster

### ISSUE THREAD

**Issue by adamhooper** [minio/minio#7991]
Sometimes a minio server will return STS credentials ... but when we make a request using that STS token, the client receives `InvalidAccessKeyId: The access key ID you provided does not exist in our records`.

## Expected Behavior

I expect minio to only return STS credentials that are valid on all servers in the minio cluster.

## Current Behavior

We're operating two minio servers in GCS gateway mode, configured by a 3-node etcd cluster.

We're using etcd+STS to supply temporary credentials to our JS-client users. I suspect we're hitting a race:

1. our server's minio client creates an STS user on minio server "minio1"
2. minio1 writes the STS credentials to etcd
3. minio1 tells server the STS credentials (after the token is written)
4. server tells JS client credentials
5. JS client connects to minio2, our redundant minio server
6. minio2 responds, InvalidAccessKeyId
7. [OOPS THIS IS TOO LATE] etcd tells minio2 about the STS credentials

## Possible Solution

Brainstorming, with little knowledge of etcd:

* When authenticating, query etcd instead of using a cache.
* If STS credentials aren't in the minio cache, then query etcd as a fallback.

## Steps to Reproduce (for bugs)

```
docker network create minio-test
# Launch etcd (and make it slow)
docker run --network minio-test --name minio-test-etcd -it --cpus=0.5 --rm gcr.io/etcd-development/etcd:v3.3.12 etcd --listen-client-urls=http://0.0.0.0:2379 --advertise-client-urls=http://minio-test-etcd:2379

# Launch minio servers 1-4 on localhost:9001-4 (and make them slow)
for i in `seq 1 4`; do docker run -d --network minio-test --name minio-test-minio-$i --cpus=0.5 --env MINIO_ETCD_ENDPOINTS=http://minio-test-etcd:2379 --env MINIO_ACCESS_KEY=root --env MINIO_SECRET_KEY=rootroot -p 900$i:9000 minio/minio:RELEASE.2019-07-24T02-02-23Z server http://minio-test-minio-1/data http://minio-test-minio-2/data http://minio-test-minio-3/data http://minio-test-minio-4/data; done

# Create user with accessKeyId "guest",secretAccessKey "guestguest"
docker run -it --rm --network minio-test --entrypoint sh minio/mc:RELEASE.2019-07-24T02-55-56Z -c 'mc config host add main http://minio-test-minio-1:9000 root rootroot && mc admin user add main guest guestguest readwrite'

python
```

And in Python:

```
import boto3
sts_client = boto3.session.Session(aws_access_key_id='guest', aws_secret_access_key='guestguest', region_name='us-east-1').client('sts', endpoint_url='http://localhost:9001')
def attempt():
    credentials = sts_client.assume_role(RoleArn='notusednotusednotused', RoleSessionName='notused')['Credentials']
    print('Trying with access key ' + credentials['AccessKeyId'])
    # S3 request goes to a different minio server
    s3_client = boto3.session.Session(aws_access_key_id=credentials['AccessKeyId'], aws_secret_access_key=credentials['SecretAccessKey'], aws_session_token=credentials['SessionToken'], region_name='us-east-1').client('s3', endpoint_url='http://localhost:9004')
    s3_client.list_buckets()  # Should not error with InvalidAccessKeyId

for i in range(100): attempt()
```

On my machine, instead of 100 printed lines, I see:

```
Trying with access key PIWBLMYJIY72KETCKH5D
Trying with access key GKEOQW46OF5NLY2A4LRD
Trying with access key 146ECUS9QQHY90469GFC
Trying with access key O79KZ0Q49B02TWZBP8VC
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in attempt
  File "/home/adam/.local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/adam/.local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListBuckets operation: The access key ID you provided does not exist in our records.
```

To clean up after testing:

```
docker rm -f minio-test-etcd minio-test-minio-{1,2,3,4}
docker network rm minio-test
```

## Context

This is nearly a deal-breaker with STS. In production, we need to delay at least 1s and hope that was long enough for the setting to wend its way through our etcd cluster and back to minio clients.

## Regression

No

## Your Environment

* Version used (`minio version`): RELEASE.2019-07-24T02-02-23Z
* Environment name and version (e.g. nginx 1.9.1): GKE (GCS gateway) and Docker+Python3 on Linux (reduction)
* Server type and version:
* Operating System and version (`uname -a`): Linux
* Link to your project: https://github.com/CJWorkbench/cjworkbench

**Comment by harshavardhana** [comment]
I tried without etcd there are no errors @adamhooper
