### ISSUE TITLE
why HTTP POST multipart/form-data return 204 No Content ?

### ISSUE THREAD

**Issue by wittech** [minio/minio#7994]
why HTTP POST multipart/form-data return 204 No Content ? bug ?

**Comment by nitisht** [comment]
This is an incomplete issue @wittech please follow the issue template so that we have relevant information to help you.

**Comment by harshavardhana** [comment]
@wittech this is part of S3 API - S3 supports 201, 200, 204 and 204 is the default. If you want 200 then you need to set `success_action_status` appropriately.

**Comment by wittech** [comment]
@harshavardhana thanks , but i didn't find how to set success_action_status use minio-java sdk ?

**Comment by harshavardhana** [comment]
> @harshavardhana thanks , but i didn't find how to set success_action_status use minio-java sdk ?

You should open an issue for that in https://github.com/minio/minio-java/issues - server already supports such a feature @wittech 

Closing this issue for now.
