### ISSUE TITLE
Object download in federated mode fails

### ISSUE THREAD

**Issue by maihde** [minio/minio#7995]
After setting up two MinIO servers in basic federated mode, the ability to download an object via the webpage or `mc cp` fails with error that the bucket does not exist.

## Expected Behavior

Downloading objects in a federated environment works transparently.

## Current Behavior

Downloading an object from a federated upstream MinIO server fails.

## Possible Solution

* `objectAPIHandlers.GetBucketLocation` does not appear to be federation aware.
* `webAPIHandlers.Download` does not appear to be federation aware.

## Steps to Reproduce (for bugs)

1. Setup two MinIO server nodes in a federated configuration.

```
export MINIO_ETCD_ENDPOINTS="http://localhost:2379"
export MINIO_DOMAIN=test.local
./minio server --address :9000 /var/tmp/minio1/
./minio server --address :9001 /var/tmp/minio2/
```

2. Created a bucket called `test` on the server running on port 9000.  Place a file in this bucket.

3. Run `mc ls minio2`, observe that the bucket `test` is returned.

4. Run `mc ls minio2/test`, receive error `Unable to stat 'minio2/test'.  Bucket 'test' does not exist.`

5. Open a web-browser to Minio2.  Observe that the bucket `test` is visible.

6. Select the bucket `test` observe that the file within the bucket is visible.

7. Attempt to download the file within the bucket `test`.  This opens a URL 

```
http://IPADDR:9001/minio/download/test/filename?token=....
```
which returns an error `The specified bucket does not exist`.

8. Attempt to copy the file with `mc`, receive error `Unable to validate source minio2/test/filename`

```
mc cp minio2/test/filename temp
```

9. Execute all actions above directly against minio1.  Observe they succeed.
```

## Your Environment
* Version used (`minio version`):
```
Version: 2019-07-29T21:47:20Z
Release-Tag: DEVELOPMENT.2019-07-29T21-47-20Z
Commit-ID: 94c88890b85f4477f47cd45b915ff2a607baf64a
```
* Environment name and version (e.g. nginx 1.9.1): CentOS 7.6.1810
* Operating System and version (`uname -a`): Linux 3.10.0-957.21.3.el7.x86_64

**Comment by kannappanr** [comment]
@maihde Thanks for filing this issue. We will take a look and fix this issue right away.

**Comment by kannappanr** [comment]
@maihde This is probably not a good test case. Can you do something like explained in PR 

https://github.com/minio/minio/pull/7957 ?

**Comment by harshavardhana** [comment]
> ./minio server --address :9000 /var/tmp/minio1/
> ./minio server --address :9001 /var/tmp/minio2/

These are not federated deployments @maihde - you need to have separate IPs otherwise you will see buckets not getting resolved due to local IP clashes.

**Comment by maihde** [comment]
@harshavardhana I had already considered that as a possibility.  When I inspected the code I found the etcd entries were storing both IP address and Port.

```
bucketMsg, err := newCoreDNSMsg(bucket, ip, c.domainPort, defaultTTL)
...
_, err = c.etcdClient.Put(ctx, key, string(bucketMsg))
```

And web-handlers.go are using that port number to when creating the remote client, for example:

```
core, err := getRemoteInstanceClient(r, getHostFromSrv(sr))
...
func getHostFromSrv(records []dns.SrvRecord) string {
	rand.Seed(time.Now().Unix())
	srvRecord := records[rand.Intn(len(records))]
	return net.JoinHostPort(srvRecord.Host, fmt.Sprintf("%d", srvRecord.Port))
}
```

This all implies that MinIO federation is considering both the IP and port when doing federation and making an extra effort to create a SRV record within etc.

Neither the web page nor the `mc ls` call make DNS lookups.  I turned up the logging level for CoreDNS and no DNS requests were made.  To me this implies that MinIO is using the `etcd` records directly when dealing with federation; as such, the port number if available and it should be possible to federate between multiple clients on the same machine.

I'll have time to try and reproduce this across different machines later today, but I see no evidence in the code or the logs that the problem is caused by conflicting IP addresses in DNS lookups.

**Comment by harshavardhana** [comment]
> Neither the web page nor the `mc ls` call make DNS lookups. I turned up the logging level for CoreDNS and no DNS requests were made. To me this implies that MinIO is using the `etcd` records directly when dealing with federation; as such, the port number if available and it should be possible to federate between multiple clients on the same machine.

Top-level is just a list in etcd @maihde - it is not a requirement for us to support such scenarios as mentioned here - will make existing code trickier.  So we would rather not support the same hosts being federated simply because it's meaningless from a production deployment point of view.

You will not be able to reproduce this across different machines simply because the federation setup will work across multiple nodes - since we already have production deployments in this type of setup.

**Comment by maihde** [comment]
@harshavardhana @kannappanr I appreciate that this use case might appear meaningless, I believe it's presumptive to declare that such a feature has no valid production scenarios.

I took a look at this in more detail.  Much of the existing code already uses both IP and port anyways (because even in a multi-host scenario the remote server might use a different port).

In my initial investigation the only part the seemed to not yet be 'port' aware was the code that dealt with `globalDomainIPs`.  I was able to fix the issue with no additional complexity by just including the port number with the IPs in the list, so it seems like this would be a straight-forward thing to include in the baseline and would make MinIO federation more flexible.

The below patch resolves the issue I reported.  With it, federation even works with both servers on the same host.

```
diff --git a/cmd/endpoint.go b/cmd/endpoint.go
index d7ec636f..55ae3a6d 100644
--- a/cmd/endpoint.go
+++ b/cmd/endpoint.go
@@ -720,16 +720,22 @@ func GetRemotePeers(endpoints EndpointList) []string {
 func updateDomainIPs(endPoints set.StringSet) {
        ipList := set.NewStringSet()
        for e := range endPoints {
-               host, _, err := net.SplitHostPort(e)
+               host, port, err := net.SplitHostPort(e)
                if err != nil {
                        if strings.Contains(err.Error(), "missing port in address") {
                                host = e
+                               port = globalMinioPort
                        } else {
                                continue
                        }
                }
                IPs, _ := getHostIP(host)
-               ipList = ipList.Union(IPs)
+
+               IPsWithPort := IPs.ApplyFunc(func(ip string) string {
+                       return net.JoinHostPort(ip, port)
+               })
+
+               ipList = ipList.Union(IPsWithPort)
        }
        globalDomainIPs = ipList.FuncMatch(func(ip string, matchString string) bool {
                return !strings.HasPrefix(ip, "127.") || strings.HasPrefix(ip, "::1")
diff --git a/cmd/object-api-utils.go b/cmd/object-api-utils.go
index 7810b672..1525241f 100644
--- a/cmd/object-api-utils.go
+++ b/cmd/object-api-utils.go
@@ -319,7 +319,7 @@ func isMinioReservedBucket(bucketName string) bool {
 func getHostsSlice(records []dns.SrvRecord) []string {
        var hosts []string
        for _, r := range records {
-               hosts = append(hosts, r.Host)
+               hosts = append(hosts, net.JoinHostPort(r.Host, fmt.Sprintf("%d", r.Port)))
        }
        return hosts
 }
```

While I'm not going to declare that I've tested every scenario yet I'd be willing to do exhaustive testing of this patch or any other changes you require to arrive at a pull request that would be acceptable for inclusion in the baseline.

**Comment by harshavardhana** [comment]
> While I'm not going to declare that I've tested every scenario yet I'd be willing to do exhaustive testing of this patch or any other changes you require to arrive at a pull request that would be acceptable for inclusion in the baseline.

Agreed we can take the PR in, but it is recommended that you would never do this in production and it creates unnecessary complexity. In our experience production deployments fail when they are configured in too many different ways.

So please send a PR @maihde we shall accept this change anyways.

**Comment by maihde** [comment]
Thanks @harshavardhana.  I am in complete agreement about your comments
regarding production deployments and minimizing complexity.   While the
use-cases for this are narrow, I believe it's nice to have the federation
code work consistently regardless of how the servers are deployed.

I appreciate your willingness to accept the PR.  After I have finished
additional testing (along with adding appropriate unittests) I will make a
PR.
