### ISSUE TITLE
Pods stuck in kubernetes helm deployment

### ISSUE THREAD

**Issue by mrceresa** [minio/minio#7996]
Hi!
I have an on-premise kubernetes deployment with the stable helm chart, distributed mode and 4 replicas. All the pods starts but they are stuck with
**"Waiting for configuration to be initialized.."**

I think the pods have write permissions because all the PVs contain:
.minio.sys
.minio.sys/multipart
.minio.sys/config/config.json/xl.json
.minio.sys/format.json

with the exception of the one for s3-minio-1, which is missing the config dir:
.minio.sys
.minio.sys/multipart
.minio.sys/format.json

I imagine that this is what is missing but I cannot understand why it is happening. Is there an option to make it more verbose?

Thanks and regards,

Mario

**Comment by mrceresa** [comment]
I read a similar report here:
https://github.com/minio/minio-operator/issues/29
about this problem happening on filesystems not supporting O_DIRECT. The PVs are on a NFS mounted share and the operations seems to be cached:
$ dmesg | grep nfs
[ 6281.522614] FS-Cache: Netfs 'nfs' registered for caching

I'd rather not use local node path because the space on the nodes is limited. Also standalone Minio is working fine with this config.

Thanks for any suggestions!

Best,
Mario

**Comment by kannappanr** [comment]
cc @nitisht

**Comment by harshavardhana** [comment]
O_DIRECT support for PVs is needed @mrceresa and using NFS as backend wouldn't support that. 

If you already have a NAS just use NAS gateway mode, there is no reason to erasure code on top of existing NAS. It is an Overkill and incorrect deployment architecture.

**Comment by mrceresa** [comment]
Thanks @harshavardhana for your prompt reply. 

Just a couple of questions to elaborate on that:
* Minio standalone works with no problem on the same configuration. Does it not need O_DIRECT?
* How do I create a high-availability deployment in this case: do I run it in distributed mode + NASgateway or standalone+NAS and several replicas?

Thanks and regards,
Mario

**Comment by harshavardhana** [comment]
> * Minio standalone works with no problem on the same configuration. Does it not need O_DIRECT?

Minio standalone is made to work on NAS like backends on purpose without the requirement of O_DIRECT @mrceresa 

> * How do I create a high-availability deployment in this case: do I run it in distributed mode + NASgateway or standalone+NAS and several replicas?

You deploy multiple NAS gateway instances pointing to same shared NAS - each gateway can be concurrently accessed and we manage the locking by using Filesystem locks.

**Comment by mrceresa** [comment]
All set: thanks a lot!
