### ISSUE TITLE
Cannot set configuration using minio client: invalid credentials

### ISSUE THREAD

**Issue by MarsWarrior** [minio/minio#7998]
I'm using a minio and mc container.
From the console of the mc container:
- I can add the minio host
- I can get the configuration
- I can NOT set the configuration
- Other things like setting events does work...

## Expected Behavior

From the mc container I should be able to
- I can get the configuration
- ...edit config with for instance nano...
- I can set the configuration

## Current Behavior

![image](https://user-images.githubusercontent.com/1220775/62144582-64886180-b2f2-11e9-83db-8b4ef5f22471.png)

Using the --debug flag I get the following output:
![image](https://user-images.githubusercontent.com/1220775/62145329-91894400-b2f3-11e9-8f64-8ae1e1fa2384.png)

## Possible Solution

No idea.
## Steps to Reproduce (for bugs)

1. I have tried several versions/tags of minio and mc, but none works
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

Both minio and mc are containers running in a Docker Swarm VM running Ubuntu 18.04 LTS, which is served by VMWare Player v15.

**Comment by kannappanr** [comment]
@MarsWarrior You have your credentials set as environment variable. You cannot change credentials in config.json

**Comment by MarsWarrior** [comment]
> @MarsWarrior You have your credentials set as environment variable. You cannot change credentials in config.json

I have several environments: In some this simply works, in some it doesn't.

I'm enabling mqtt and postgresql entries in the configuration. I don't change the credentials which I do have setup in the docker container environment variables.

This is what I'm used to do & get as result:
![image](https://user-images.githubusercontent.com/1220775/62199108-356e0080-b383-11e9-8534-5da90a45df3d.png)

**Comment by harshavardhana** [comment]
> I have several environments: In some this simply works, in some it doesn't.

In some environments, you have access/secret set in ENV to a different value than provided in the `/tmp/myconfig` if you keep the creds same then you will able to set mqtt and postgresql.

**Comment by MarsWarrior** [comment]
> > I have several environments: In some this simply works, in some it doesn't.
> 
> In some environments, you have access/secret set in ENV to a different value than provided in the `/tmp/myconfig` if you keep the creds same then you will able to set mqtt and postgresql.

That is weird, as I have NEVER have touched the config file for credentials.

I will check the config file for credentials on all systems!

**Comment by MarsWarrior** [comment]
Right. I did the check and the credentials where completely different from the credentials in the environment variables. How is that possible 😩 

So MinIO doesn't check the environment var's with the ones in the `config.json` file and uses the environment variables, unless you try to modify the configuration.

I would expect MinIO to check this @ startup 😄 

As you can see (including --debug), after changing the credentials and restarting the container, I'm able to change the configuration using mc from the mc container...

Me happy!!!

![image](https://user-images.githubusercontent.com/1220775/62203971-86cebd80-b38c-11e9-91ef-854f8e6a8c72.png)

And thanks for the support & the hint. As I never had touched the config file for credentials, I wasn't aware that these would be in there too as I'm using the environment variables.

**Comment by harshavardhana** [comment]
Here are scenarios to remember 

- Env is set and you freshly start MinIO config.json preserves the ENV 
- Env is set after the MinIO was already initialized it would start with a default creds (this is only in standalone mode, the distributed mode doesn't support auto credential generation) - Env is honored and you should make sure that your config.json reflects the server creds when updating notification. This was in your case.
- Env is not set only auto creds from config.json are honored.

**Comment by MarsWarrior** [comment]
I will remember those...

But it still is weird: the demo environment setup in vmware had these problems, the same demo environment in hyper-v simply did not.

Both where setup using compose files (of course with environment var's setup) and manually using Portainer. In BOTH cases the vmware environment gave troubles.

Now I know what to check and know how to fix it and I can create working demo and workshop environments that simply work.

A patch that would give a warning in the log about different credentials would still be very nice though!

**Comment by harshavardhana** [comment]
> A patch that would give a warning in the log about different credentials would still be very nice though!

We can't tell the intention here @MarsWarrior what we follow today is best practices style.

WE are changing the `mc admin config set` behavior in upcoming releases starting with #7963 where you would set notification and other features independently - do not have to deal with an entire `config.json`. 

For now, will close this issue as resolved.

**Comment by MarsWarrior** [comment]
Agreed. Issue solved for me.

Thanx again!
