### ISSUE TITLE
build github.com/minio/minio: cannot load archive/zip: cannot find module providing package archive/zip

### ISSUE THREAD

**Issue by theAkito** [minio/minio#8000]
## Expected Behavior

Install minio from source.

## Current Behavior

Cannot find module `archive/zip`, i.e. cannot install minio.

## Possible Solution

Provide package `archive/zip`

## Steps to Reproduce (for bugs)

1.
```
$ GOPROXY=https://proxy.golang.org GO111MODULE=on go get github.com/minio/minio
```

## Context

Installing minio.

## Regression

Minio used to work a couple of months ago through the same installation method on the same device. Don't remember more.

## Your Environment

* Operating System and version (`uname -a`):
```
Linux 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux
```

**Comment by kannappanr** [comment]
@Akito13 Will try to repro the issue. What version of `golang` are you using? I tried it on 1.12.1 and it works.

**Comment by theAkito** [comment]
@kannappanr 
```
go version go1.12.1 linux/arm
```

**Comment by safaribaer** [comment]
@Akito13 
your GOROOT is wrong. Probably too short. It should point to the directory where it contains the src lib and api folder.
I made the same error. Compilation worked on my raspberry with this:
```
export GOROOT=/opt/src/go/go
export GOPROXY=https://proxy.golang.org
export GO111MODULE=on
go get github.com/minio/minio
```
The go binary was a link to  /usr/local/bin/go from /opt/src/go/go/bin/go
hth

**Comment by theAkito** [comment]
@safaribaer 
BIG THANK YOU!

You reminded me that about a year ago I had to set the _GOROOT_ for a project and since then it is broken. I don't know how to fix it without purging and re-installing Go, entirely. In my case I often have to set an empty _GOROOT_ like this:

```
export GOROOT=""
```

Now it worked.
