### ISSUE TITLE
Client SSL Auth for Notification Events

### ISSUE THREAD

**Issue by malake** [minio/minio#8002]
**Is your feature request related to a problem? Please describe.**
I need to send event notifications to elasticsearch/kafka/etc. but those platforms are configured to only accept certificate based client authentication. 

**Describe the solution you'd like**
I would like the ability to send event notifications to Elasticsearch with a private key and certificate as user credentials.

**Describe alternatives you've considered**
I've tried sending event notifications to a "webhook" of `/dev/stdout` or `/dev/stderr` in an attempt to get something in the console so the filebeats pod on each k8s node will pick up the logging and send it to the monitoring ELK stack for audit purposes.

**Additional context**
We're running Minio on k8s in a distributed stateful set with 4 pods. Updated documentation with descriptions and examples of what each parameter in the configuration file is used for would also be handy.

**Comment by malake** [comment]
@harshavardhana, for your reference. Thanks!

**Comment by harshavardhana** [comment]
Thanks for diligently opening the issue @malake
