### ISSUE TITLE
How do you change the URL for presigned get object?

### ISSUE THREAD

**Issue by jleach** [minio/minio#8007]
Hey,

I'm running minio on k8s (with Traefik as my reverse proxy) when I create a presigned URL I get `http://minio.test.svc:9000/delivery/` where as I want `https://example.com/delivery`. I don't think its clear in any of the docs how to configure this properly. Or to put it another way, I want minio to generate a internet routable URL with the proper protocol (SSL) for my presigned URL.

From reading the docs I'm not sure if `MINIO_DOMAIN` and virtual-domains `https://delivery.example.com/` are meant for this scenario or for distributing workload (federated setup).

Any help is appreciated.

**Comment by kannappanr** [comment]
@jleach In general, you can create pre-signed URL for any S3 endpoint and with any credential and region. Can you elaborate more on how you are trying to do this?

**Comment by jleach** [comment]
In my API service I'm using the minio SDK for nodejs; I call `presignedGetObject` which returns a signed URL. My API is being run in a k8s cluster so I'm using the service name `minio.test.svc:9000` to reach the host. I'd like to return the URL to the Web so that users can download a file but since the URL is not internet routable this wont work and I can't change it because its signed.

I could rewrite it on the way out and have my proxy rewrite it on the way in; seems a bit weird though.

**Comment by kannappanr** [comment]
```
var Minio = require('minio')

var s3Client = new Minio.Client({
  endPoint: 'example.com',
  port: 9000,
  accessKey: 'YOUR-ACCESSKEYID',
  secretKey: 'YOUR-SECRETACCESSKEY',
  useSSL: true,
  region: 'us-east-2'
})

// Presigned get object URL for my-objectname at my-bucketname, it expires in 7 days by default.
var presignedUrl = s3Client.presignedGetObject('my-bucketname', 'my-objectname', 1000, function(e, presignedUrl) {
  if (e) return console.log(e)
  console.log(presignedUrl)
})
```

The above code will run and generate a pre-signed url. It does not connect to any S3 server. Please change it to the values that you want.

**Comment by jleach** [comment]
Thanks @kannappanr. I have that much working but because I use the service name to connect `minio.test.svc` the URL I get back uses the service name; and won't work outside of the cluster. I suppose I could use the internet routable URL to connect form inside the cluster but that, I don't think, is the best way to do it because it needs to go out of the cluster then get routed back in.

Would be cool to tell the client (or minio) what protocol, host, port to use when it creates a pre-signed URL.

**Comment by jleach** [comment]
I ended up just using the internet routable name inside the cluster. It just bounces off the router so it does not really add any overhead. Also, since minio is accessible via the internet it might actually be best to use the internet routeable host name for it.

**Comment by apit** [comment]
how do we tell Minio Console to use external URL? currently in my setup (docker minio+nginx behind proxy), it is using docker internal IP

**Comment by benyaminl** [comment]
related to https://github.com/minio/minio/issues/10222 https://github.com/minio/minio/issues/10284 

Is there anyway in the future this changed? as sometimes we need to test it using docker compose, and returning the URL of docker isn't good thing. 

Thank you 

ping @KevinSmile and @harshavardhana 

EDIT: seems the only way to make it works is... maping the domain to `/etc/hosts` or `C:\Windows\System32\drivers\etc\hosts` file if using docker, use `host.docker.internal` or natively using podman on WSL2 (with port mapping), linux, and mac and use `localhost`, but still.. it is, so sad..

**Comment by corinz** [comment]
Any updates on this at all?

**Comment by iarchean** [comment]
Having the same issue, for me I run minio in k8s, my services access minio cluster through service-name:9000, but users use it from outside the cluster through https://external-fqdn:443, so change the /etc/hosts is not working for me because they have different ports.

**Comment by pkit** [comment]
I'm in awe. Why is this shit not solved since 2019?

**Comment by deonvisser44** [comment]
+1

**Comment by klauspost** [comment]
Presigned URLs cannot be changed. They are *signed*. If you could change them, they would be pointless.

1) The server does not generate the URLs, your SDK does. Change the URL in your SDK to generate the correct one in the first place.
2) Set [MINIO_SERVER_URL](https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#envvar.MINIO_SERVER_URL) allows you to change the URL pre-signed requests are validated against.

**Comment by DoisKoh** [comment]
For the `MINIO_SERVER_URL`, I think it would be good if this were mentioned somewhere in the docs. Perhaps in the [MINIO_SERVER_URL](https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#envvar.MINIO_SERVER_URL) section... At the moment, it's not clear (for me at least) that this is possible from just reading that.

**Comment by dleeha** [comment]
Is it possible to generate an external name from within the internal network (ie. not leaving the internal network)? Would setting `MINIO_SERVER_URL` to the external address of MINIO inevitably have the API call (to get presigned url) hit MINIO on the external address (ie. leaving the internal network)?

**Comment by sirmmo** [comment]
MINIO_SERVER_URL is ignored when generating presigned urls. MinIO VERSION 2023-11-01T18:37:25Z

**Comment by davidhorac3** [comment]
Hi, any chance to actually solve this issue anytime?

**Comment by bearxsh** [comment]
It's a common issue, but it has not been solved yet.

**Comment by sniperking1234** [comment]
This is a problem that is easily encountered in the K8S scenario, and it is worth considering how to solve this issue.

**Comment by mobiusy** [comment]
So far, using an external access address instead of service name has been the better solution

**Comment by AlexanderPershin** [comment]
> So far, using an external access address instead of service name has been the better solution

So, you basically need to
1. deploy `min.io` container to the hosting
2. point a real domain to this service
3. connect from local machine to min.io with this domain
4. and only then generate presigned URL

Yeah, sounds like a paradise for local development... But I don't see a better solution. Hope someone will address this issue at some point in a distant future

**Comment by netthier** [comment]
For anyone having issues generating URLs in the console, I was able to solve this using the answer from here: https://github.com/minio/minio/discussions/15849.
By setting `MINIO_SERVER_URL` to `https://minio.external.com` and `MINIO_BROWSER_REDIRECT_URL` to `http://minio.internal.local:9001`, I was able to generate pre-signed URLs for the external URL from the console hosted at the internal URL. The API call is entirely internal as well (at least according to my browser). Not setting the second environment variable prevented me from logging into the console.
Using `RELEASE.2024-04-06T05-26-02Z`

**Comment by vishrantgupta** [comment]
I am using AWS SDK, and you could use `PresignOptions`,

```

customURL := func(options *s3.PresignOptions) {

	customDomain := func(o *s3.Options) {
		o.BaseEndpoint = &serverConfig.AWSS3CustomPreSignedURL
	}
	options.ClientOptions = append(options.ClientOptions, customDomain)
}
existingOpts = append(existingOpts, customURL)

preSignedURLWithCustomEndpoint := s3.NewPresignClient(client.(*s3.Client), existingOpts...)
```

**Comment by vishrantgupta** [comment]
I am using AWS SDK, and you could use `PresignOptions`,

```

customURL := func(options *s3.PresignOptions) {

	customDomain := func(o *s3.Options) {
		o.BaseEndpoint = <my custom presigned URL>
	}
	options.ClientOptions = append(options.ClientOptions, customDomain)
}
existingOpts = append(existingOpts, customURL)

preSignedURLWithCustomEndpoint := s3.NewPresignClient(client.(*s3.Client), existingOpts...)
```
