### ISSUE TITLE
Support China Azure for Gateway

### ISSUE THREAD

**Issue by heavenwing** [minio/minio#8011]
**Is your feature request related to a problem? Please describe.**
Without this feature, I cannot use gateway in ChinaAzure

**Describe the solution you'd like**
I can run gateway for ChinaAzure

**Describe alternatives you've considered**
Only run server mode

**Additional context**
None

**Comment by kannappanr** [comment]
@heavenwing Will take a look and get back to you.

**Comment by poornas** [comment]
@heavenwing, did you try `minio gateway azure https://azureaccountname.blob.custom.azure.endpoint` replacing  custom endpoint with your china endpoint? If you saw any error with this - can you paste the console message.

**Comment by vadmeste** [comment]
more precisely `https://azureaccountname.blob.core.chinacloudapi.cn` should work

**Comment by heavenwing** [comment]
@kannappanr I don't know can use custom endpoint before, but I tried now with https://azureaccountname.blob.core.chinacloudapi.cn, I got a error "ERROR Invalid argument: lookup [storageaccountname].blob.core.chinacloudapi.cn on 192.168.18.126:53: read udp 172.26.154.148:46955->192.168.18.126:53: i/o timeout. "

**Comment by harshavardhana** [comment]
@heavenwing looks like your DNS doesn't resolve to this domain, do you have access to these domains ?

**Comment by heavenwing** [comment]
I can access theses domains outside container

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Harshavardhana <notifications@github.com>
发送时间: Friday, August 2, 2019 1:51:10 PM
收件人: minio/minio <minio@noreply.github.com>
抄送: Yongguang Zhu <heavenwing@msn.com>; Mention <mention@noreply.github.com>
主题: Re: [minio/minio] Support China Azure for Gateway (#8011)


@heavenwing<https://github.com/heavenwing> looks like your DNS doesn't resolve to this domain, do you have access to these domains ?

―

**Comment by vadmeste** [comment]
> read udp 172.26.154.148:46955->192.168.18.126:53: i/o timeout. "

Something is clearly wrong in your setup, Minio is not able to resolve, can you try in your local machine instead of your container first ?

**Comment by kannappanr** [comment]
ping @heavenwing

**Comment by heavenwing** [comment]
I tried same command in Azure China VM, it's working.
I think that maybe Docker Desktop for Windows (v2.0.5) have some unknown problem,  so this command is not working in my local Windows 10 computer.

**Comment by kannappanr** [comment]
@heavenwing Not sure what is wrong with Docker Desktop for Windows. Can you try the same test bypassing Docker and do it on the Windows machine or a Linux machine if you have access to one? 

The latest release can be found at https://dl.minio.io/server/minio/release/windows-amd64/minio.exe

**Comment by heavenwing** [comment]
@kannappanr I tried it on the Windows command line directly, meet same issue #7622 , must use same workaround to fix.

**Comment by heavenwing** [comment]
I known reason , I used [LCOW ](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10-linux) to run minio, maybe LCOW's network is special, so minio cannot access these domain. 
If I use linux docker, it's working

**Comment by kannappanr** [comment]
@heavenwing Not sure what we can do here. Closing this issue, please feel free to reopen the issue if you have further questions
