### ISSUE TITLE
Distributed mode, loss of one node breaks uploads and server

### ISSUE THREAD

**Issue by nodesocket** [minio/minio#8016]
Running minio `2019-08-01T22:18:54Z` in distributed mode with 4 VM instances `minio1, minio2, minio3, minio4`. I start a 2GB file upload on minio1 via the web interface.

When I shutdown the minio3 VM during the upload on minio1, the upload stops and seems to disrupt service. I can refresh the web interface via minio1, but it just shows a loading spinner for the bucket:

<img width="1004" alt="Screen Shot 2019-08-01 at 10 34 00 PM" src="https://user-images.githubusercontent.com/523312/62342488-a230ea00-b4ac-11e9-86e4-5ae865feb9f9.png">

It was my understanding that running minio in distributed mode, you can lose one of the four VM instances and still continue fully working. Am I misunderstand this? Appreciate the insight.

**Comment by harshavardhana** [comment]
Your understanding is correct, is `mc ls` commands working ?

**Comment by nodesocket** [comment]
@harshavardhana all 4 minio servers running:

```
MacBook-Pro ➜  ~ mc admin info minio-ec2
●  minio1:9000
   Uptime: 3 minutes
  Version: 2019-08-01T22:18:54Z
  Storage: Used 4.9 GiB
   Drives: 4/4 OK

●  minio2:9000
   Uptime: 3 minutes
  Version: 2019-08-01T22:18:54Z
  Storage: Used 4.9 GiB
   Drives: 4/4 OK

●  minio3:9000
   Uptime: 3 minutes
  Version: 2019-08-01T22:18:54Z
  Storage: Used 4.9 GiB
   Drives: 4/4 OK

●  minio4:9000
   Uptime: 3 minutes
  Version: 2019-08-01T22:18:54Z
  Storage: Used 4.9 GiB
   Drives: 4/4 OK
```

I am using `minio1` web interface and start a upload. Then I shutdown `minio3` VM server instance _(hard power off)_ and web interface can't load bucket contents. Just shows spinning loader.

Looking at chrome developer tools, the request to `http://minio1:9000/minio/webrpc` is just pending, eventually times out.

**Comment by krishnasrinivas** [comment]
@nodesocket what underlying virtualization are you using for VMs?

**Comment by nodesocket** [comment]
@krishnasrinivas running on Amazon EC2 instances.

**Comment by Nepoxx** [comment]
I might be running into this. What is your output of `mc admin info` while an instance is dead?

This is what I have (I have 6 instances, losing any one of them results in the web interface complaining about failed lookups, uploads/downloads do not work*, etc.):

```
●  minio0:9000
   Uptime: 1 minute 
  Version: 2019-08-21T19:40:07Z
  Storage: Used 736 GiB
   Drives: 2/2 OK

●  minio1:9000
   Uptime: 50 seconds 
  Version: 2019-08-21T19:40:07Z
  Storage: Used 736 GiB
   Drives: 2/2 OK

●  minio2:9000
   Uptime: offline
    Error: Post http://minio2:9000/minio/peer/v4/serverinfo?: dial tcp: lookup minio2 on 127.0.0.11:53: server misbehaving
●  minio3:9000
   Uptime: 57 seconds 
  Version: 2019-08-21T19:40:07Z
  Storage: Used 736 GiB
   Drives: 2/2 OK

●  minio4:9000
   Uptime: 56 seconds 
  Version: 2019-08-21T19:40:07Z
  Storage: Used 736 GiB
   Drives: 2/2 OK

●  minio5:9000
   Uptime: offline
    Error: Post http://minio5:9000/minio/peer/v4/serverinfo?: dial tcp: lookup minio5 on 127.0.0.11:53: server misbehaving
```

* Some uploads/downloads do work, rarely. I suspect this is when traffic is not sent to the dead instances.

---
edit: `mc ls myminio` works as intended.

I'm using Docker Swarm, 2 minio instances per server and 2 disks per minio instance (12 disks total, 3 servers)

**Comment by Nepoxx** [comment]
My DNS was indeed misbehaving (returning SERVFAIL instead of NXDOMAIN). I've switched to 1.1.1.1 but it does not fix the issue with minio (the error now has `no such host` instead of `misbehaving`)

**Comment by harshavardhana** [comment]
> My DNS was indeed misbehaving (returning SERVFAIL instead of NXDOMAIN). I've switched to 1.1.1.1 but it does not fix the issue with minio (the error now has `no such host` instead of `misbehaving`)

If your node is down it will throw `No such host` are you expecting something else?

**Comment by Nepoxx** [comment]
I am, however I am not expecting minio to misbehave when some nodes are down.

**Comment by harshavardhana** [comment]
What do you mean by misbehave ? Can you explain what happens ?

**Comment by Nepoxx** [comment]
When I refresh the UI, once in a while I get
```
Post http://minio5:9000/minio/storage/v8/export0/statvol?instance-id=c9ca75cb-dc82-4e4a-8e9f-9a474ebfbd03&volume=mybucket: dial tcp: lookup minio5 on 127.0.0.11:53: server misbehaving
```
Uploads and downloads fail most of the time (but not always).

**Comment by harshavardhana** [comment]
> ```
> Post http://minio5:9000/minio/storage/v8/export0/statvol?instance-id=c9ca75cb-dc82-4e4a-8e9f-9a474ebfbd03&volume=mybucket: dial tcp: lookup minio5 on 127.0.0.11:53: server misbehaving
> ```

when you refresh the UI is sending List request to list buckets and objects - this message is expected.  Downloads and Uploads shouldn't fail - do they fail with timeouts or just fail to upload? or hang?

**Comment by Nepoxx** [comment]
This is what I get with AWS's cli,

Upload through load balancer:
```
$ aws  --endpoint-url http://minio.sarbakan.com s3 cp ~/bigtestfile s3://mybucket/trash
upload failed: ./bigtestfile to s3://mybucket/trash An error occurred (502) when calling the UploadPart operation (reached max retries: 4): Bad Gateway`
```

Upload to instance directly:
```
$ aws  --endpoint-url http://venus:9001 s3 cp ~/bigtestfile  s3://mybucket/trash
upload failed: ./bigtestfile to s3://mybucket/trash Connection was closed before we received a valid response from endpoint URL: "http://venus:9001/mybucket/trash?uploadId=ba15030b-89ec-4248-87d2-7eb70aaf3438&partNumber=9".
```

---
edit: Minio client works fine

**Comment by harshavardhana** [comment]
The problem here is that AWS CLI is not properly doing rr-dns - mc automatically picks the next server available upon DNS lookup. 

Also, your load balancer is not ignoring the downed server which it should bas<e on some form of healthcheck to the server.

What type of checks do you have to ensure that this is done? @Nepoxx

**Comment by Nepoxx** [comment]
I'm stuck with Apache unfortunately, and this is my configuration:

```
<Proxy balancer://minio>                                                                                               
    BalancerMember http://192.168.5.196:9001 hcmethod=GET hcuri=/minio/health/ready
    BalancerMember http://192.168.5.196:9002 hcmethod=GET hcuri=/minio/health/ready
    BalancerMember http://192.168.5.222:9003 hcmethod=GET hcuri=/minio/health/ready
    BalancerMember http://192.168.4.133:9004 hcmethod=GET hcuri=/minio/health/ready
    BalancerMember http://192.168.4.133:9005 hcmethod=GET hcuri=/minio/health/ready
    BalancerMember http://192.168.5.222:9006 hcmethod=GET hcuri=/minio/health/ready
    ProxySet lbmethod=bytraffic                                                                                        
</Proxy>                                                                                                               
                                                                                                                       
<Location "/">                                                                                                         
    ProxyPass "balancer://minio/"                                                                                      
    ProxyPassReverse "balancer://minio/"                                                                               
    Header set "Access-Control-Allow-Origin" "*"                                                                       
    Order allow,deny                                                                                                   
    Allow from all                                                                                                     
</Location>                                                                                                            
```

(edit: removed timeouts from config, they were leftover from some debugging)

**Comment by harshavardhana** [comment]
> <Proxy balancer://minio>                                                                                               
>     BalancerMember http://192.168.5.196:9001 hcmethod=GET hcuri=/minio/health/ready
>     BalancerMember http://192.168.5.196:9002 hcmethod=GET hcuri=/minio/health/ready
>     BalancerMember http://192.168.5.222:9003 hcmethod=GET hcuri=/minio/health/ready
>     BalancerMember http://192.168.4.133:9004 hcmethod=GET hcuri=/minio/health/ready
>     BalancerMember http://192.168.4.133:9005 hcmethod=GET hcuri=/minio/health/ready
>     BalancerMember http://192.168.5.222:9006 hcmethod=GET hcuri=/minio/health/ready
>     ProxySet lbmethod=bytraffic                                                                                        
> </Proxy>

Looks like this part is not working appropriately @Nepoxx - 502 gateway error that you get is sent by the LB, not by MinIO server. So your load balancer is not working appropriately here, meaning it is scheduling the request to downed server incorrectly. 

Second error with AWS CLI is it's not using the next IP after the DNS lookup to `venus` which `mc` is doing automatically.  This is also a limitation of AWS CLI.

The issue which you are seeing is not the one @nodesocket is talking about here.

**Comment by Nepoxx** [comment]
Sorry about the noise (we can delete the above comments if needed).

`venus` resolves to a single ip and is not the host with offline nodes. Also, wouldn't using the direct ip remove the DNS requirement? I'm getting the same issue if I use `venus`'s ip directly:
```
$ aws  --endpoint-url http://192.168.5.196:9001 s3 cp ~/bigfile s3://mybucket/trash
upload failed: ./bigfile to s3://mybucket/trash Connection was closed before we received a valid response from endpoint URL: "http://192.168.5.196:9001mybucket/trash?uploadId=5c435867-39d6-4f5a-8e5e-18b4df5c3f94&partNumber=2".
```

---
[Removed to remove noise]

**Comment by harshavardhana** [comment]
> ```
> mc: <ERROR> Unable to initialize new config from the provided credentials. We encountered an internal error, please try again.
> ```

These are all different issues @Nepoxx which we would love to fix. So let's not club them together and confuse on some other issue. Best practice open new issues.
