### ISSUE TITLE
Used storage metric in web interface is incorrect when running in distributed

### ISSUE THREAD

**Issue by nodesocket** [minio/minio#8017]
When viewing a bucket with two files one 1.28GB and the other 1.15GB, the web interface is showing `Used: 613.08 KB` which is obviously incorrect. Running in distributed mode with 4 VM's. Starting with simply:

```bash
minio server http://minio{1...4}/minio-data/{1...4}
```

<img width="1019" alt="Screen Shot 2019-08-01 at 10 50 06 PM" src="https://user-images.githubusercontent.com/523312/62343031-b970d700-b4ae-11e9-8546-8e00e0173bd8.png">

Running `Version: 2019-08-01T22:18:54Z`.

**Comment by harshavardhana** [comment]
It is updated once in 12hrs if you want instantaneous updates use the entire disk

**Comment by nodesocket** [comment]
@harshavardhana, what do you mean use the entire disk? This is a distributed setup with 4 nodes. Thanks.

**Comment by harshavardhana** [comment]
An entire disk is where your disk is mounted, if you provide a path relative to the disk we use crawling to calculate disk usage which is updated every 12 hrs.

**Comment by nitisht** [comment]
closing this as answered @nodesocket feel free to join us on slack (https://slack.min.io) for any more questions

**Comment by kannappanr** [comment]
@nodesocket Closing this issue as answered. Please feel free to let us know if you have further questions.
