### ISSUE TITLE
Change the 5MB Part size limitation

### ISSUE THREAD

**Issue by Meshkati** [minio/minio#8022]
hi, there is a limitation of 5MB per part of multipart upload on S3 API. Is there any solution to change this limitation on minio? I didn't find anything on minio configs :(

**Comment by harshavardhana** [comment]
AWS S3 API mandates all multipart object sizes to be 5MiB or higher excluding the last part which can be lesser than 5MiB. 

We just implement as per the API spec, there are no foreseeable future plans to change this.

**Comment by Meshkati** [comment]
Thanks, do you know the reason behind this decision? Why it can't be smaller than 5MB :( ?

**Comment by harshavardhana** [comment]
Honestly, don't know @Meshkati - there can be many reasons. Going to close this issue, there nothing actionable on our end.
