### ISSUE TITLE
Is HDFS gateway suitable for small files?

### ISSUE THREAD

**Issue by haosdent** [minio/minio#8025]
## Expected Behavior

Use HDFS SequenceFile to reduce small file impact for HDFS.

## Current Behavior

I saw now for every new file, the implementation of HDFS gateway would create an indivual file directly. Because the block size of HDFS is 256MB, this would waste a lot of space and bring high pressure for Hadoop Namenode.

**Comment by harshavardhana** [comment]
@haosdent HDFS gateway primarily is meant for read-only use cases it is not meant to do anything special on HDFS if you upload 1GiB we just stream it to HDFS nothing special gets added to the file on HDFS.  So any object that is uploaded it is uploaded as-is. 

The idea is that tomorrow if you remove HDFS gateway your files are kept as is and are accessibly using HDFS tools. So we make sure that you native access available. 

It is not in our interest to create special format on top of HDFS to circumvent limitations of HDFS, a small file is an HDFS limitation so using HDFS gateway you don't get anything more than what your backend HDFS already provides.

**Comment by harshavardhana** [comment]
Nothing actionable from our end, closing this issue.
