### ISSUE TITLE
The cluster crash and still in CrashLoopBackOff

### ISSUE THREAD

**Issue by citiz3nn** [minio/minio#8039]
We have a MinIO cluster in Kubernetes environment :
- 1 cluster
- 4 pods
- 1 cronJob (Every day at 1:00 pm)

## Expected Behavior
Work perfectly :P

## Current Behavior

Every 1 week about, the pods crash one after the other.
We can see in the logs pods those errors :

- Runtime and GoRoutine (when cluster crash):
  ```bash
    runtime stack:
    runtime.throw(0x194fde5, 0x9)
      /opt/go/src/runtime/panic.go:617 +0x72
    runtime.newosproc(0xc00039ae00)
      /opt/go/src/runtime/os_linux.go:166 +0x1bd
    runtime.newm1(0xc00039ae00)
      /opt/go/src/runtime/proc.go:1861 +0xdf
    runtime.newm(0x19d2e68, 0xc00004ea00)
      /opt/go/src/runtime/proc.go:1840 +0x8f
    runtime.startm(0x0, 0xc0008e7e01)
      /opt/go/src/runtime/proc.go:1977 +0x12c
    runtime.wakep(...)
      /opt/go/src/runtime/proc.go:2058
    runtime.ready(0xc0008e7e00, 0x4, 0x45ed01)
      /opt/go/src/runtime/proc.go:658 +0x120
    runtime.goready.func1()
      /opt/go/src/runtime/proc.go:312 +0x38
    runtime.systemstack(0xc00046a640)
      /opt/go/src/runtime/asm_amd64.s:351 +0x66
    runtime.mstart()
      /opt/go/src/runtime/proc.go:1153

    goroutine 226 [running]:
    runtime.systemstack_switch()
      /opt/go/src/runtime/asm_amd64.s:311 fp=0xc00083db28 sp=0xc00083db20 pc=0x45b3f0
    runtime.goready(0xc0008e7e00, 0x4)
      /opt/go/src/runtime/proc.go:311 +0x5c fp=0xc00083db58 sp=0xc00083db28 pc=0x42f9fc
    runtime.netpollgoready(...)
      /opt/go/src/runtime/netpoll.go:359
    internal/poll.runtime_pollSetDeadline(0x7f045b856af8, 0xea471f4587161a0a, 0x72)
      /opt/go/src/runtime/netpoll.go:280 +0x280 fp=0xc00083dbe0 sp=0xc00083db58 pc=0x42a980
    internal/poll.setDeadlineImpl(0xc00068e400, 0x0, 0xe7791f701, 0x2d3c240, 0x72, 0x0, 0x0)
      /opt/go/src/internal/poll/fd_poll_runtime.go:153 +0x11c fp=0xc00083dc20 sp=0xc00083dbe0 pc=0x48a0bc
    internal/poll.(*FD).SetReadDeadline(...)
      /opt/go/src/internal/poll/fd_poll_runtime.go:130
    net.(*netFD).SetReadDeadline(...)
      /opt/go/src/net/fd_unix.go:276
    net.(*conn).SetReadDeadline(0xc0001801f8, 0x0, 0xe7791f701, 0x2d3c240, 0x0, 0x0)
      /opt/go/src/net/net.go:244 +0x76 fp=0xc00083dc78 sp=0xc00083dc20 pc=0x5cd326
    github.com/minio/minio/cmd/http.(*DeadlineConn).SetReadDeadline(0xc0004b41e0, 0x0, 0xe7791f701, 0x2d3c240, 0x1848220, 0xc000ad0080)
      <autogenerated>:1 +0x5a fp=0xc00083dcb8 sp=0xc00083dc78 pc=0x78532a
    net/http.(*connReader).abortPendingRead(0xc0004b4510)
      /opt/go/src/net/http/server.go:723 +0xa5 fp=0xc00083dcf8 sp=0xc00083dcb8 pc=0x6eae65
    net/http.(*response).finishRequest(0xc00099cee0)
      /opt/go/src/net/http/server.go:1592 +0x97 fp=0xc00083dd20 sp=0xc00083dcf8 pc=0x6efbb7
    net/http.(*conn).serve(0xc0003ba0a0, 0x1c36a60, 0xc00046a640)
      /opt/go/src/net/http/server.go:1883 +0x88f fp=0xc00083dfc8 sp=0xc00083dd20 pc=0x6f0b6f
    runtime.goexit()
      /opt/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00083dfd0 sp=0xc00083dfc8 pc=0x45d341
    created by net/http.(*Server).Serve
      /opt/go/src/net/http/server.go:2884 +0x2f4

    goroutine 1 [select]:
    github.com/minio/minio/cmd.waitForFormatXL(0x1c36aa0, 0xc0000460b0, 0x1c00c00, 0xc00042e8c0, 0x4, 0x4, 0x1, 0x4, 0x0, 0x0, ...)
      /q/.q/sources/gopath/src/github.com/minio/minio/cmd/prepare-storage.go:309 +0x2eb
    github.com/minio/minio/cmd.newObjectLayer(0xc00042e8c0, 0x4, 0x4, 0xc0002b3820, 0xc0002b3800, 0x0, 0x0)
      /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:417 +0x8f
    github.com/minio/minio/cmd.serverMain(0xc000510480)
      /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:317 +0x6b5
    github.com/minio/cli.HandleAction(0x163c100, 0x19d1730, 0xc000510480, 0xc000348600, 0x0)
      /q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.21.0/app.go:500 +0x7c
    github.com/minio/cli.Command.Run(0x194bb88, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x196fb44, 0x1b, 0x0, ...)
      /q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.21.0/command.go:221 +0x996
    github.com/minio/cli.(*App).Run(0xc0000e81a0, 0xc0000ba000, 0x9, 0x9, 0x0, 0x0)
      /q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.21.0/app.go:261 +0x6af
    github.com/minio/minio/cmd.Main(0xc0000ba000, 0x9, 0x9)
      /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:162 +0x89
    main.main()
      /q/.q/sources/gopath/src/github.com/minio/minio/main.go:37 +0x45

    goroutine 4 [chan receive]:
    github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc00008c240, 0xc00008c180)
      /q/.q/sources/gopath/pkg/mod/github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:36 +0xb6
    created by github.com/rjeczalik/notify.newNonrecursiveTree
      /q/.q/sources/gopath/pkg/mod/github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:29 +0xdd
    ...
  ```

- Incomplete body
  ```json
    {
      "deploymentid": "XXX-ID",
      "level": "ERROR",
      "time": "2019-06-18T05:08:00.182764695Z",
      "api": {
        "name": "PutObject",
        "args": {
          "bucket": "logstash-output",
          "object": "archive/path/ARCHIVE.part30.txt.gz"
        }
      },
      "remotehost": "XXX-IP",
      "host": "XXX-POD.svc.cluster.local:9000",
      "requestID": "XXX-ID",
      "userAgent": "aws-sdk-ruby2/2.11.136 jruby/2.3.3 java resources",
      "error": {
        "message": "#has incomplete body",
        "source": ["cmd/xl-v1-object.go:631:cmd.xlObjects.putObject()", "cmd/xl-v1-object.go:513:cmd.xlObjects.PutObject()", "cmd/xl-sets.go:635:cmd.(*xlSets).PutObject()", "cmd/object-handlers.go:1261:cmd.objectAPIHandlers.PutObjectHandler()", "net/http/server.go:1995:http.HandlerFunc.ServeHTTP()"]
      }
    }
  ```

- Connection Refused (Because in crash status I think)
  ```json
    {
      "deploymentid": "XXX-ID",
      "level": "ERROR",
      "time": "2019-06-18T05:08:00.182764695Z",
      "api": {
        "name": "SYSTEM",
        "args": {
          "bucket": "logstash-output",
          "object": "archive/path/ARCHIVE.part140.txt.gz"
        }
      },
      "error": {
        "message": "Post http://XXX-POD.cluster.local:9000/minio/storage/v8/export/readall?file-path=archive%2Fpath%2FARCHIVE.part140.txt.gz%2Fxl.json\u0026instance-id=XXXXX-ID\u0026volume=logstash-output: dial tcp XXX-IP:9000: connect: connection refused",
        "source": ["cmd/xl-v1-utils.go:234:cmd.readXLMeta()", "cmd/xl-v1-utils.go:269:cmd.readAllXLMetadata.func1()"],
        "variables": {
          "disk": "http://XXX-POD.svc.cluster.local:9000/export"
        }
      }
    }
  ```

**All confidential informations are replaced. By XXX-...**

## Possible Solution
For the moment, we delete manually all pods and the cluster is up again but after some times, he crash again.

Possible solutions :
+ Bad parameters?
+ More ressouces?
+ We have no idea but together we can fix it :).

## Steps to Reproduce (for bugs)
It's dificult because, we have no idea where the crash happened. We have a cronJob for purge the old data, maybe the cronJob use too much ressources.
We hope you could give us some approach to investigate.

## Context
We would stabilize and durable MinIO cluster.

## Your Environment
* Version used (`minio version`):
  ```bash
    Version: 2019-08-07T01:59:21Z
    Release-Tag: RELEASE.2019-08-07T01-59-21Z
    Commit-ID: 930943f058f01f37cfbc2265d5f80ea7026ec55d
  ```
* Environment name and version (e.g. nginx 1.9.1):
  ```bash
    Kubernetes : 1.13.3
    Nodes : CentOS 7
    Docker : 18.9.1
  ```

**Comment by vadmeste** [comment]
@briareosiso the stack trace that you pasted doesn't include the reason of the crash, could you paste all the logs that you have and we can inspect them

**Comment by citiz3nn** [comment]
We had an other crash (x4 CrashLoopBackOff), @vadmeste I give you the logs. No logs for minio-{0,1}. 

[minio-2.log](https://github.com/minio/minio/files/3481625/minio-2.log)
[minio-3.log](https://github.com/minio/minio/files/3481626/minio-3.log)

**Comment by vadmeste** [comment]
@briareosiso there is also no stack trace ins the new logs that you posted, only normal Minio logs.

minio-2 and minio-3 were just waiting for other minio servers to run.

**Comment by citiz3nn** [comment]
With MC, we have those logs : 

- `12:59:19.559 [200 OK] internal.Lock minio-0.minio.svc.cluster.local:9000/minio/lock/v2/lock?resource=logstash-output%2Finf%2Fnginx%2F2019%2F08%2F08%2Fnginx-ingress-prod-controller-74c5547567-887gv%2Fls.s3.XXX.2019-08-08T12.19.part2.txt.gz&serverAddr=minio-2.minio.svc.cluster.local%3A9000&serverEndpoint=%2Fminio%2Flock&source=%5Bxl-v1-object.go%3A508%3AxlObjects.PutObject%28%29%5D&uid=XXX  XXX-IP 43µs  🠉 58 B  🠋 0 B
`
- `12:59:19.561 [403 Forbidden] internal.Unlock minio-0.minio.svc.cluster.local:9000/minio/lock/v2/unlock?resource=logstash-output%2Finf%2Fnginx%2F2019%2F08%2F08%2Fnginx-ingress-prod-controller-74c5547567-887gv%2Fls.s3.XXX.2019-08-08T12.19.part2.txt.gz&serverAddr=minio-2.minio.svc.cluster.local%3A9000&serverEndpoint=%2Fminio%2Flock&source=&uid=XXX  XXX-IP 71µs  🠉 58 B  🠋 229 B`

**Comment by vadmeste** [comment]
@briareosiso can you make sure that all your servers are running first ?

`mc admin info your-alias/`

**Comment by citiz3nn** [comment]
@vadmeste. Yes, They're running. But they alternate between running/CrashLoopBackOff.

**Comment by vadmeste** [comment]
> But they alternate between running/CrashLoopBackOff.

The automatic restart is probaby the reason why logs disappear, you can probably stop automatic restart to see what's going on. It is not clear what is causing Minio containers to die

**Comment by nitisht** [comment]
@briareosiso can you try kubectl describe pod <minio-pod-name> and let us know the output, that may have some clue

**Comment by citiz3nn** [comment]
@nitisht, here are the file.
[describe-minio-0.log](https://github.com/minio/minio/files/3482453/describe-minio-0.log)
[describe-minio-1.log](https://github.com/minio/minio/files/3482454/describe-minio-1.log)
[describe-minio-2.log](https://github.com/minio/minio/files/3482455/describe-minio-2.log)
[describe-minio-3.log](https://github.com/minio/minio/files/3482456/describe-minio-3.log)

**Comment by nitisht** [comment]
MinIO pods seem to be OOMKilled @briareosiso , how much memory you have on these pods?

**Comment by citiz3nn** [comment]
@nitisht, they had : 
```bash
    Limits:
      memory:  1Gi
    Requests:
      cpu:     250m
      memory:  640Mi
```
Now, we have a limit to: 
```bash
    Limits:
      memory:  2Gi
```

**Comment by nitisht** [comment]
Can you set the request to 2Gi 

```
    Requests:
      cpu:     250m
      memory:  2Gi
```

**Comment by harshavardhana** [comment]
Don't set such limits if you are planning to heavily use MinIO server, set the value in accordance with number of concurrent requests you need the servers to handle.

1000 concurrent requests you need 10GiB of memory. All of this will be reused but you shouldn't arbitrarily limit the memory usage without prior testing.

**Comment by kannappanr** [comment]
Closing this issue as answered. Please feel free to reach out to us if you have further questions.

**Comment by citiz3nn** [comment]
@harshavardhana. I have one question. For size ram for my cluster, i determines the concurrent requests * 10MB. This is for one pod or for Minio Cluster?

**Comment by harshavardhana** [comment]
> @harshavardhana. I have one question. For size ram for my cluster, i determines the concurrent requests * 10MB. This is for one pod or for Minio Cluster?

Per MinIO process @briareosiso

**Comment by citiz3nn** [comment]
> > @harshavardhana. I have one question. For size ram for my cluster, i determines the concurrent requests * 10MB. This is for one pod or for Minio Cluster?
> 
> Per MinIO process @briareosiso

Thx you !
