### ISSUE TITLE
Sts AssumeRoleWithWebIdentity call is returning expiration date in wrong format

### ISSUE THREAD

**Issue by vsfalexanderpilch** [minio/minio#8041]
Minio is returning the date in an invalid format. This is happening when we're executing an AssumeRoleWithWebIdentity request via AWS Java SDK (version 1.11.605). As a result, the AWS SDK isn't able to parse the expiration date and it's setting it to null instead. There's also an error message on the console. See attached text document for details. The expiration date is the one from the access token. The jwt token is valid until tomorrow, so feel free to experiment with it. It's only an  okta developer account in order to verify the integration with minio.

It's hard to say if it's a bug in aws sdk date parsing logic or a bug in minio. I was assuming that aws sdk is the reference implementation, so I'm reporting it here.

[expiration-date.txt](https://github.com/minio/minio/files/3482429/expiration-date.txt)

Okta jwks uri for tests (see attached text file): https://dev-220054.oktapreview.com/oauth2/ausfvrk1lcEmyM19m0h7/v1/keys

## Expected Behavior
Expiration date should be compatible with aws sdk.

## Current Behavior
sdk is reporting date parsing issue. expiration date is null in aws sdk as a result

## Possible Solution
convert date in response to some compatible format (e.g. iso8601 utc or aws specific subset of iso8601). AWS seems to expect it in format [yyyy-MM-dd'T'HH:mm:ss.SSSZZ.](https://www.joda.org/joda-time/apidocs/org/joda/time/format/ISODateTimeFormat.html#dateTime--) 
`DateTimeFormatter iso8601DateFormat = ISODateTimeFormat.dateTime().withZone(GMT);`

`com.amazonaws.util.DateUtils#parseISO8601Date` is used in `com.amazonaws.transform.SimpleTypeStaxUnmarshallers.DateStaxUnmarshallerFactory#unmarshall` in order to convert the value.

## Steps to Reproduce (for bugs)

see attached text file with stacktrace & sample request/code

## Context
- warning/error is printed in console
- expiration date is set to null, so tracking of expiration isn't possible (without tracking it on our own)

## Your Environment

* Version used (`minio version`): 
Version: 2019-08-07T01:59:21Z
Release-Tag: RELEASE.2019-08-07T01-59-21Z
Commit-ID: 930943f058f01f37cfbc2265d5f80ea7026ec55d
* Server type and version: Windows 10 1703.2

**Comment by harshavardhana** [comment]
Thanks will take a look
