### ISSUE TITLE
Please add cache hit and miss metrics

### ISSUE THREAD

**Issue by rldleblanc** [minio/minio#8042]
It would be really useful to have some cache hit and miss metrics on the Prometheus stats page.

Cache hit count
Cache miss count
Cache hit bytes
Cache miss bytes

The last two are not as critical as the first two, but can help gauge how effective cache is for bandwidth (i.e. a few very large objects being hit, vs lots of small objects being missed).

**Comment by kannappanr** [comment]
@rldleblanc Thanks for the suggestion. we will talk internally and try to incorporate the metrics suggested in this issue.

**Comment by rldleblanc** [comment]
I don't expect persistent cache stats, just the life of the process would be sufficient.

**Comment by rldleblanc** [comment]
We are trying to get a clear picture of how much caching is helping to localize our AWS S3 data. It doesn't seem that `minio_network_received_bytes_total` include traffic from AWS and similarly `minio_network_sent_bytes_total` doesn't include traffic to AWS (since we are only reading from AWS, I can't tell). It would be nice to see those metrics. I'm guessing a gateway won't be serving objects so it could make sense to just add them to these metrics.

**Comment by nitisht** [comment]
Fixed by https://github.com/minio/minio/pull/8591
