### ISSUE TITLE
Buckets created /remove directly in single disk mode are not recognized in federated mode.

### ISSUE THREAD

**Issue by maihde** [minio/minio#8044]
If you run MinIO in single  drive mode (i.e. `minio server /data`) it will recognize buckets that are created directly in the folder (i.e. `mkdir /data/bucketname`).

If you run that same server in federated mode, if a bucket is created directly it will not show up in the bucket list (either direct or federated calls) until the server is restarted.

While the documents indicate that MinIO supports "Pre-existing data", it's silent on the topic if direct modifications in single-disk mode are supported while MinIO is running.  Being able to modify the data directly is useful when integrating applications that don't understand the S3 API.  In non-federated mode it appears to work correctly; so it would be consistent if federated single-disk nodes also behaved the same way.

## Expected Behavior
1. Start a federated MinIO setup with at least two servers; each running single-disk
2. Directly create a directory in one of the nodes data paths
3. In the MinIO web browser refresh the page.
4. The new bucket is visible
5. Directly remove a directory in one of the nodes data paths
6. The removed bucket is no longer visible

## Current Behavior
1. Start a federated MinIO setup with at least two servers; each running single-disk
2. Directly create a directory in one of the nodes data paths
3. In the MinIO web browser refresh the page.
4. The new bucket is _not_ visible
5. Directly remove a directory in one of the nodes data paths
6. The removed bucket is _still_ visible

## Possible Solution

In my analysis, this is due to the fact that when federated mode is used, the bucket list is derived solely from the `globalDnsEntries` list.  I have implemented a potential fix where `fs-v1.go` uses `fsnotify` to watch for buckets being created or removed and then updates the global DNS correctly.

If you are interested in the fix I made I will open a PR.

## Context

I have a collection of nodes where I use MinIO to access data on these nodes.  These nodes are executing software that is not 'S3' aware and will create buckets directly in the file system.  This works as expected in non-federated mode but does not work in federated mode.

**Comment by harshavardhana** [comment]
This is expected @maihde it is a feature to allow existing buckets, but after the server has started you shouldn't be messing with the backend.

**Comment by harshavardhana** [comment]
Modifying the backend without using S3 API is considered intrusive and is considered as corrupting the backend.  Expecting MinIO server to listen on such things is out of scope for the implementation.

There is no way technically to correctly do it as well to listen on such events FS mode is expected to work on NFS and NFS doesn't support fsnotify.

**Comment by harshavardhana** [comment]
Adding code to handle weird cases like this unnecessarily complicates the server implementation, I don't know what is special about writing to backend which cannot be done with like `mc mb` which will essentially create the bucket and also make a proper entry for DNS purposes.

**Comment by maihde** [comment]
Thanks @harshavardhana .  I anticipated this might be the case.  Thanks for taking the time to consider the issue, you may close it.

I agree with you, there are alternatives such as  `mc mb`.  This issue was raised primarily because MinIO behaves differently when you have federation enabled versus when you don't and the documentation doesn't provide guidance on what the supported behavior should be.

It would be useful to add a note to the "Pre-existing data" section that explicitly states that direct modifications to the data while MinIO is running are not supported and there are no guarantees that it will work (even though it does in some scenarios).  I've heard others (not myself) read that section and interpret it as MinIO supporting direct file system manipulation outside of the S3 API.

**Comment by harshavardhana** [comment]
> It would be useful to add a note to the "Pre-existing data" section that explicitly states that direct modifications to the data while MinIO is running are not supported and there are no guarantees that it will work (even though it does in some scenarios). I've heard others (not myself) read that section and interpret it as MinIO supporting direct file system manipulation outside of the S3 API.

This we should document and make it explicit.

**Comment by harshavardhana** [comment]
Going to close this issue, we will update the document.
