### ISSUE TITLE
S3 Gateway Multi-user

### ISSUE THREAD

**Issue by Fabricio20** [minio/minio#8045]
**Is your feature request related to a problem? Please describe.**
I'm currently trying to set up an S3 Gateway, where a set of internal machines don't have internet access but a gateway machine exists, which has external internet access to a backend provider.

MinIO in S3 Gateway mode works perfectly for this, except that I need to configure per-bucket-per-user access control. I read about multi-user support on the documentation page, but that doesn't seem to apply to MinIO when it's running in S3 Gateway mode.

I've also tried creating the IAM Policy and User on the backend provider and then passing the credentials to MinIO upon auth, but that fails with invalid credentials. (Probably because MinIO is just refusing since the credentials don't match MINIO_ACCESS_KEY/MINIO_SECRET_KEY).

**Describe the solution you'd like**
I'd like to be able to create users and policies even when running in gateway mode, so that MinIO restricts access to S3 buckets.

**Describe alternatives you've considered**
An (easier?) alternative would be to add a flag where MinIO would just accept the credentials I'm passing on auth and use it against the backend provider. Effectively disabling MINIO_ACCESS_KEY/MINIO_SECRET_KEY.

**Additional context**
User `a` should be able to access bucket `A` but user `b` should not be able to access bucket `A` while still being able to access bucket `B`, even in Gateway mode.

Sorry if this is an actual feature already, I just struggle to find any documentations on this scenario. (S3 Gateway mode config is really hidden atm!)

**Comment by harshavardhana** [comment]
You can multi-user in gateway with etcd @Fabricio20 - this is already supported and used by quite a few people.

Feel free to join our slack https://slack.min.io for more information

**Comment by kannappanr** [comment]
please look into our docs at https://github.com/minio/minio/blob/master/docs/gateway/s3.md
https://github.com/minio/minio/tree/master/docs/multi-user and https://github.com/minio/minio/tree/master/docs/federation/lookup 
etc-d is explained here in the context of federation, but you can simply just learn how to setup etcd from the doc. With these three docs you should be able to setup multi-users in S3 Gateway. 

Closing this issue now. For further questions feel free to join our slack channel at https://slack.min.io
