### ISSUE TITLE
minio update breaks minio if you configured --address :80

### ISSUE THREAD

**Issue by ahmadalli** [minio/minio#8048]
minio update breaks minio since it won't have the capability to listen to 80 port. if you're on the distributed mode the cluster won't be back up since the nodes can't communicate with each other.

## Expected Behavior
the updated minio must have the same capabilities as the older version

## Current Behavior
minio binary loses the capability to listen to privileged ports after update

## Possible Solution
`minio update` must check it's binary's capabilities and set them after update

## Steps to Reproduce (for bugs)
1. download older version of minio
1. `setcap 'cap_net_bind_service=+ep' /usr/local/bin/minio`
1. `minio update`
1. `getcap /usr/local/bin/minio`

## Your Environment

* Version used (`minio version`): minio.RELEASE.2019-08-07T01-59-21Z
* Operating System and version (`uname -a`): Ubuntu 18.04 LTS

**Comment by kannappanr** [comment]
@ahmadalli  Are you updating `minio` to itself? If not what is the older version of `MinIO` used here. Also we do not support rolling upgrades in the newer version. You will have to replace the binary on all the nodes and restart the cluster.

**Comment by ahmadalli** [comment]
sorry about version. I updated minio from previous version to the current version. after restart cluster nodes couldn't connect to each other and after a while I figured it's because they lost the capability and after re-adding the capability the issue was resolved.

**Comment by harshavardhana** [comment]
If you enabled setcap they can't be auto honored if you did `minio update` because for setcap you need root access.

So it is your responsibility to do it, or use docker like containers to provide such capabilities automatically.

I don't think we can do anything to fix this @ahmadalli

**Comment by ahmadalli** [comment]
the least you can do is show a warning to the user or if minio update is called from a root user I think you can add the permission to the file

**Comment by kannappanr** [comment]
@ahmadalli Just to make sure that I understand you correctly, do you want us to display a warning to the user if `MinIO` is run under a user with `root` privilege? If yes, will check internally and get back to you.

**Comment by ahmadalli** [comment]
no. 
I mean there are few things `minio update` could do in order to prevent breaking:
- if current executable has capability to listen on privileged ports, minio could show user a warning with steps that user must do in order to prevent it (e.g. show user run the `setcap` command)
- if `minio update` has been ran with a privileged user, run `setcap` command automatically

**Comment by harshavardhana** [comment]
> * if current executable has capability to listen on privileged ports, minio could show user a warning with steps that user must do in order to prevent it (e.g. show user run the `setcap` command)

What capabilities were given is outside the scope of MinIO you can give / provide many capabilities we have no way of knowing that. Instead, we should make either external calls to `getcap` command or use some form of cryptic Linux only friendly system calls. 

> * if `minio update` has been ran with a privileged user, run `setcap` command automatically

If you are already a privileged user there is no point in running `setcap`, we can't run setcap on itself as a process. Linux doesn't allow such privilege escalation. You have to be a runtime outside of MinIO to do this. 

AFAICS this is just not worth doing, this was primarily to do with user error and throwing a proper error on the console will suffice in this situation.

Refer to https://github.com/minio/minio/pull/8068

**Comment by harshavardhana** [comment]
Closing this issue as won't fix, we will add more explanatory error messages instead.

**Comment by ahmadalli** [comment]
thanks for adding warning and error messages
