### ISSUE TITLE
XML Parse Error

### ISSUE THREAD

**Issue by jappyjan** [minio/minio#8050]
## Expected Behavior
Uploading a File through the JavaScriptSDK (putObject()) creates a new File on the Minio Instance.

## Current Behavior
The putObject() method fails throwing an "S3Error" with code "unknownError". Following the Stracktrace you end up at the xml-parser.js on line 61 with the error "Unexptected close tag Line: 5 Column: 7 Char: >"

## Steps to Reproduce (for bugs)
1. Setup a Fresh Minio Instance
2. Create A Fresh Bucket
3. (Optionally) Create a Read/Write Policy for this Bucket
4. execute the putObject() method of the JS SDK

## Context
Im trying to Upload an Audio File (JS Blob)

## Your Environment
Minio is Running inside a Docker Container on my CapRover instance/server.
It's been installed as a One-Click App.

**Comment by kannappanr** [comment]
@jappyjan This is probably a `minio-js` issue. Can you provide more information like what version of `minio-js`, version of `minio`, size of the file in question here etc.

**Comment by jappyjan** [comment]
im using minio js in version ^7.0.10
the minio version is the latest available pulled from dockerhub ( minio/minio:latest )

size of file varies/the hole file varies.

it's an audio recorder application which sends its recorded audio to minio.
i never tried sending the same file multiple times...

**Comment by jappyjan** [comment]
i just tried just sending a simple string "hello world".
same result.

**Comment by harshavardhana** [comment]
Can you share the code that you wrote?

**Comment by kaankabalak** [comment]
@jappyjan Could you also paste the output of `npm list minio` to see the exact version of `minio-js` that is installed on your setup please?

**Comment by jappyjan** [comment]
How i create a Minio Connection:

    import {Client} from 'minio';
    import Config from '../../config/Config';
    
    const config = Config.get('minio');
    const con = new Client({
        endPoint: config.endpoint,
        port: config.port,
        useSSL: config.ssl,
        accessKey: config.accessKey,
        secretKey: config.secretKey,
    });

How i put a file:

    public put(content: string | Buffer, key: string) {
        return new Promise((resolve, reject) => {
            this.con.putObject(
                this.bucket,
                key,
                content,
                (err, etag) => {
                    if (err) {
                        reject(err);
                        return;
                    }

                    resolve(etag);
                },
            );
        });
    }`

My "npm list minio" output:

`-- minio@7.0.11

**Comment by kaankabalak** [comment]
@jappyjan Thanks for sharing the code! Would it also be possible to try the same in `minio-js` version 7.0.10? Also, for further investigation, could you send the full stack trace as well? Thanks in advance!

The following snippet that uses `putObject`, taken from [here](https://github.com/minio/minio-js/blob/master/examples/put-object.js), worked for me on version 7.0.11:
```js
import { Client } from "minio"

var minioClient = new Client({
  endPoint: "play.min.io",
  port: 9000,
  useSSL: true,
  accessKey: "Q3AM3UQ867SPQQA43P2F",
  secretKey: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
})

// Upload a string
var str = "Hello world"
minioClient.putObject("testbucket", "my-objectname", str, function(e) {
  if (e) {
    return console.log(e)
  }
  console.log("Successfully uploaded the string")
})
```

**Comment by jappyjan** [comment]
still the same result.

i will now just put some credentials to my minio instance here (will change them as soon as we found a solution... there are no relevant files on there, so theres like no security issues..)

        minio: {
                endpoint: 'minio.unitect.io',
                port: 80,
                accessKey: 'minio',
                secretKey: 'qyU,8yT^_P$S7Ly*',
                bucket: 'unitect-workstation',
                ssl: false,
        },

btw i'm setting ssl to false because with ssl: true i get the following error:

   {
     "errno": "EPROTO",
     "code": "EPROTO",
     "syscall": "write",
     "message": "write EPROTO 4776:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:
"
   }


the stack trace without ssl is:

S3Error: 302
    at getError (C:\Users\janja\WebProjects\Unitect\api\node_modules\minio\dist\main\transformers.js:146:15)
    at C:\Users\janja\WebProjects\Unitect\api\node_modules\minio\dist\main\transformers.js:161:14
    at DestroyableTransform._flush (C:\Users\janja\WebProjects\Unitect\api\node_modules\minio\dist\main\transformers.js:89:10)
    at DestroyableTransform.<anonymous> (C:\Users\janja\WebProjects\Unitect\api\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:135:12)
    at Object.onceWrapper (events.js:291:20)
    at DestroyableTransform.emit (events.js:208:15)
    at DestroyableTransform.EventEmitter.emit (domain.js:476:20)
    at finishMaybe (C:\Users\janja\WebProjects\Unitect\api\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:371:12)
    at endWritable (C:\Users\janja\WebProjects\Unitect\api\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:378:3)
    at DestroyableTransform.Writable.end (C:\Users\janja\WebProjects\Unitect\api\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:356:5)

**Comment by kanagarajkm** [comment]
@jappyjan can you get the output of `mc admin trace <ALIAS> -v` when the `putObject` call fails with XML error.

**Comment by jappyjan** [comment]
Hey guys, thank you all for your help.
I just found the solution. I don't know why but it seems like SSL is broken for minio deployed by caprover. And I had "force SSL" activated so even using "ssl: false" in js actually used the SSL connection.
By turning force SSL of I was able to upload files.
Does anyone ever used minio with caprover before? If so, were you able to use SSL?

Am 12.08.2019 07:49 schrieb Kanagaraj M <notifications@github.com>:

@jappyjan<https://github.com/jappyjan> can you get the output of mc admin trace <ALIAS> -v when the putObject call fails with XML error.

**Comment by kannappanr** [comment]
@jappyjan it could be that you have not setup SSL properly for minio. I looked at https://github.com/caprover/one-click-apps/blob/master/public/v1/apps/minio.json

Looks like they are still using the older style of setting certs and keys. It should work even now. How and where are you setting the certificate and key. What are the names of those files? Also how are you running the container, are you running it as `root`?

**Comment by githubsaturn** [comment]
Hi, Kasra from CapRover here. Came across this thread, and thought I should shed some light:

CapRover uses nginx as the HTTPS (SSL) terminator layer. Normally apps deployed via CapRover don't need access to the certs and keys. Does minio need access to them?

This what it looks like:
```
  +---------+                +-----------+                 +---------+
  |         |  HTTPS @ 443   |           |                 |         |
  |   user  | +------------> |   NGINX   |   HTTP @ 9000   |         |
  |         |                |           | +-------------> |  minio  |
  |         | +------------> |           |                 |         |
  +---------+  HTTP @ 80     +-----------+                 +---------+
```


The problem is this:
```
    minio: {
            endpoint: 'minio.unitect.io',
            port: 80,
            accessKey: 'minio',
            secretKey: 'qyU,8yT^_P$S7Ly*',
            bucket: 'unitect-workstation',
            ssl: false,
    },
```

It's trying to use port 80 with SSL false, which is fine, but if you "force HTTPS" on CapRover, you'll receive a 302 redirect to port 443. I'm not sure how minio handles this scenario. But I guess something like
```
    minio: {
            endpoint: 'minio.unitect.io',
            port: 443,
            accessKey: 'minio',
            secretKey: 'qyU,8yT^_P$S7Ly*',
            bucket: 'unitect-workstation',
            ssl: true,
    },
```

**Comment by jappyjan** [comment]
thank you @githubsaturn !
that was the solution!

ussing port 443 instead of 80 fixed it for me!
