### ISSUE TITLE
debug level setting not sticking

### ISSUE THREAD

**Issue by kozchris** [minio/minio#8055]
setting the debug level as show in https://github.com/minio/minio/issues/2815 does not seem to work

## Expected Behavior

I expect that setting the log level to debug should update the debug level.

## Current Behavior

Configuration is updated and minio is restarted. Retrieving the option shows that the configuration has not changed.

$ mc admin config set cd/ < minio.json 
Setting new MinIO configuration file has been successful.
Please restart your server with `mc admin service restart cd/`.

$ mc admin service restart cd/
Restart command successfully sent to `cd/`.
Restarted `cd/` successfully.

## Steps to Reproduce (for bugs)

1. Get configuration `mc admin config get cd/ > minio.cfg`
2. Update configuration to set debug level: ```
"logger": {
    "console": {
      "enabled": true,
      "level": "debug"
    }
```
3. apply new config: `mc admin config set cd/ < minio.cfg`
4. restart minio server: `mc admin service restart cd/`
5. pull config and no changes are observed and no additional logging appears to be output.

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world --> I am trying to debug errors and can not get the verbose logging I need

## Regression
<!-- Is this issue a regression? (Yes / No) -->
<!-- If Yes, optionally please include minio version or commit id or PR# that caused this regression, if you have these details. -->

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:
```
minio version
Version: 2019-08-07T01:59:21Z
Release-Tag: RELEASE.2019-08-07T01-59-21Z
Commit-ID: 930943f058f01f37cfbc2265d5f80ea7026ec55d
```

kubernetes 1.14

**Comment by harshavardhana** [comment]
There is no debug logging in our logs @kozchris we only support error logging to console - if you are looking at trace logging use `mc admin trace` command

**Comment by kozchris** [comment]
ok, thanks

**Comment by kannappanr** [comment]
Closing this issue. Please feel free to reach out to us at https://slack.min.io for further questions
