### ISSUE TITLE
Testing of Caching Format - Incomplete files being stored in and served from new cache

### ISSUE THREAD

**Issue by ghost** [minio/minio#8061]
I'm testing the new caching format on a minio gateway running in front of a minio cluster.

I'm downloading a very large dataset approx 150GB/1.3m images.

Client accessing this dataset from the gateway are getting corrupted incomplete files.

E.g.

Download entire dataset directly from minio cluster:
```
Transferred:   	  143.339G / 143.339 GBytes, 100%, 118.997 MBytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:      1331169 / 1331169, 100%
Elapsed time:    20m33.4s
```

Download entire dataset via the minio gateway:
```
Transferred:   	   42.748G / 42.748 GBytes, 100%, 124.641 MBytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:      1331169 / 1331169, 100%
Elapsed time:     5m51.2s
```
As you can see the number of files is the same via both paths but the amount of actual data being downloaded is very different.

## Expected Behavior

The amount of data a client gets should be the same if they are going directly to the Minio Cluster or if going via a gateway.

## Current Behavior

A large number of files being stored in the gateway are incomplete.

## Possible Solution

Unsure of reason

## Steps to Reproduce (for bugs)

See above
Running the latest Dev build 2019-08-07T16:45:21Z.
Downloading a very large number of files I don't see this all the time.

1.
2.
3.
4.

## Context

Image processing jobs are failing due to corrupt files. If they bypass the GW (which is used to improve minio performance) issue is resolved

This is already being looked at by Poorna Krishnamoorthy via slack

## Your Environment

* Version used (`minio version`):
Version: 2019-08-07T16:45:21Z
Release-Tag: DEVELOPMENT.2019-08-07T16-45-21Z
Commit-ID: 86e9fc5979ab0be45887f38a59b385bb10546c21
GW is a SuperMicro Xeon D using dedicated Samsung EVO SSD as the cache
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: 
* Operating System and version (`uname -a`):
Linux svr-miniogw-001 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

The other other thing of note is that this server is running two MINIO Gateways one backed by MINIO and one backed by an NFS share for testing. Nobody is using the MINIO NFS Gateway but they are both running and each has a folder for there own cache on the same ssd

**Comment by harshavardhana** [comment]
Are you using the latest master @hassbabaie ? we merged the PR already and you can use the latest master and it seems to have fixes already to handle the issue you are mentioning. 

would you be interested in a new binary? or you can usage `minio/minio:edge` for the latest master.

**Comment by ghost** [comment]
@harshavardhana for the backend cluster I'm using the latest production release. For the Gateways (including the one I'm testing with) I'm using the latest dev release from Poorna. I can do an upgrade on the gateways now? Will it be newer than the one from Poorna. Also Poorna is looking at the issue (and trying to re-produce) via slack and didn't mention it might be a known bug with?

**Comment by poornas** [comment]
could you just use master branch for gateway? I don't see an issue AFAICS with a setup similar to yours

**Comment by ghost** [comment]
thanks @poornas I think I saw the master now supports the new caching format right, but it's not built?

I'm using the binary versus a docker instance so I would need a link to the latest minio file. Assuming it's newer than https://github.com/minio/minio/tree/RELEASE.2019-08-07T01-59-21Z or on this page https://dl.min.io/server/minio/release/linux-amd64/

if you can share a link and if you would like me to erase the cache and upgrade the gateway and do a complete test again I can do that

**Comment by poornas** [comment]
https://play.min.io/bin/minio?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=Q3AM3UQ867SPQQA43P2F%2F20190811%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190811T014750Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=d55a2f1602996fa1a72e2e95672477de718dc1b11b5aff710515dbdb720abff7

**Comment by harshavardhana** [comment]
AFAIK this problem was already observed by Robert and we did fix it. You may try from the master for the gateway or the binary just shared by @poornas

**Comment by ghost** [comment]
Thanks @harshavardhana  @poornas so just to confirm I will do the following: right:

Clear the cache and upgrade the minio gateway (not the backend cluster)
Then re-run the test

Right?

Thanks

**Comment by ghost** [comment]
Thanks @harshavardhana I'll use the link just shared and re-test. Yes I did look back at the slack channel as I was sure Robert would have hit this issue too if it was a bug but didn't spot it.

Thanks

**Comment by poornas** [comment]
> AFAIK this problem was already observed by Robert and we did fix it. You may try from the master for the gateway or the binary just shared by @poornas

@harshavardhana, this PR doesn't have a fix to continue writing to cache even after client connection is closed. That was thought to be an edge case.

**Comment by ghost** [comment]
FYI, cleared the cache and now the gateway is up and running with the latest release:

Aug 11 02:12:53 svr-miniogw-001 minio[401]: Cache Capacity: 3.6 TiB Free, 3.6 TiB Total

Version: 2019-08-11T01:46:02Z
Release-Tag: DEVELOPMENT.2019-08-11T01-46-02Z
Commit-ID: a0715f3b593111c71a730c36df043e5631717f4d

I'll now run a few tests of the full dataset and I'll post the update

Hass

**Comment by ghost** [comment]
@harshavardhana  @poornas FYI, I've now tested multiple times and with increased concurrency and I'm not seeing the issue re-appear so I think it's fixed with the latest binary.

I'll carry on leveraging it tomorrow but so far all is looking good

Thanks

Hass
