### ISSUE TITLE
DNS type request is not working

### ISSUE THREAD

**Issue by sritoleti** [minio/minio#8074]
## Expected Behavior
I am using ES v 6.4.3 and as per documentation it only supports DNS style request to talk to S3 repositories. 

## Current Behavior
I am using DNS settings on Minio which apparently is not working. May be because of my settings ?
The issue is whenI use hostname, where as the IP address as endpoint works fine.

## Possible Solution
Possibly need to change settings in my minio/ES deployment

## Steps to Reproduce (for bugs)

1. Install ES version 6.4.3 with out x-pack
2. Install minio lastest release 
3. Configure ES config map with mino's service name as end point.
4. try to create s3 repository via API call.

## Context
I get below error when I perform API call.

Config:

    s3.client.default.endpoint: "http://minio:9000" # Replace with actual MinIO server endpoint
    s3.client.default.protocol: http                # Replace with actual protocol (http/https)

ENV of minio:

          - name: MINIO_DOMAIN
            value: "minio"

PUT request:

       curl -X PUT "elastic:9200/_snapshot/myminio" -H 'Content-Type: application/json' -d'
      {
       "type": "s3",
        "settings": {
         "bucket": "elasticsearch",
         "endpoint": "http://minio:9000",
        "protocol": "http"
     }
     }
     '

Error:

	{
	   "error":{
		  "root_cause":[
			 {
				"type":"sdk_client_exception",
				"reason":"sdk_client_exception: Unable to execute HTTP request: elasticsearch.minio"
			 }
		  ],
		  "type":"repository_exception",
		  "reason":"[myminio] cannot create blob store",
		  "caused_by":{
			 "type":"sdk_client_exception",
			 "reason":"sdk_client_exception: Unable to execute HTTP request: elasticsearch.minio",
			 "caused_by":{
				"type":"i_o_exception",
				"reason":"elasticsearch.minio"
			 }
		  }
	   },
	   "status":500
	}

## Your Environment

* Version used (`minio version`): latest from: minio/minio
* Environment name and version (e.g. nginx 1.9.1): ES 6.4.3
* Server type and version: K8
* Operating System and version (`uname -a`):Alpine Linux v3.9
* Link to your project:

**Comment by kannappanr** [comment]
@sritoleti Jut with respect to MinIO itself you should make sure that DNS style requests work, before you try it with `ES`

**Comment by harshavardhana** [comment]
> 		 "reason":"sdk_client_exception: Unable to execute HTTP request: elasticsearch.minio",

This looks like elasticsearch.minio is not resolving, you don't have the right DNS entries to resolve here IMO.

**Comment by sritoleti** [comment]
I will troubleshoot it and come back with my findings.

**Comment by deekoder** [comment]
@sritoleti were you able to get more insight?

**Comment by sritoleti** [comment]
hello @deekoder, thanks for reaching out. I could not get this working yet!

I tried standalone installation of Minio and ES 7.1.1 V which worked alright as it used path style requests to access.

But the DNS style requests are not working.

Can someone please take a look at this.

I have deployed minio service as  LoadBalancer and added env variable 

        - name: MINIO_DOMAIN
          value: domain.com

**Comment by harshavardhana** [comment]
@sritoleti just adding MINIO_DOMAIN only makes minio server aware of DNS style requests - you need to make sure that `yourbucket.domain.com` resolves to the MinIO server appropriately. 

I am assuming that you have done that on your elasticsearch instance such that elasticsearch is able to resolve the `yourbucket.domain.com` properly.

You can verify this by doing `ping yourbucket.domain.com` on your elasticsearch server.

**Comment by sritoleti** [comment]
Hello @harshavardhana I see your point, I cannot ping elastic.minio from any of the instances.

All this time I am creating a service during minio installation which then is used to point to in Elasticsearch. 

Since Metadata.name in service cannot contain '.' I cannot create a service 'elastic.minio'

My version of elastic is forcing the right to be DNS style (elastic.minio)bucketname.hostname.

If I do not pass any bucket info, the API call is hitting minio server and results in below error.

##


      curl -X PUT "elastic:9200/_snapshot/myminio" -H 'Content-Type: application/json' -d'
      {
        "type": "s3",
        "settings": {
        "bucket": " ",
        "endpoint": "http://minio:9000",
        "protocol": "http"
        }
      }
     '
    {"error":{"root_cause":[{"type":"repository_exception","reason":"[myminio] cannot create blob   store"}],"type":"repository_exception","reason":"[myminio] cannot create blob store","caused_by":{"type":"illegal_argument_exception","reason":"The bucket [ ] does not exist. Please create it before  creating an s3 snapshot repository backed by it."}},"status":500}

Not sure if I am in the right path on this.

Is there another way to create service with bucket.servername ?

Thanks

**Comment by harshavardhana** [comment]
Closing this issue as incomplete setup and not MinIO issue.
