### ISSUE TITLE
the space of minio is full, how can i extend the storage

### ISSUE THREAD

**Issue by katty0924** [minio/minio#8084]
if i used up the space of minio , there is a solution that i can extend the storage capacity of minio? or can i add a new node into the distributed minio?

**Comment by nitisht** [comment]
@katty0924 you can add a new cluster to existing distributed minio cluster, using federation https://docs.min.io/docs/minio-federation-quickstart-guide.html

Closing this as answered, please join us on Slack (https://slack.min.io) for more such questions
