### ISSUE TITLE
Build fails 

### ISSUE THREAD

**Issue by ghost** [minio/minio#8086]
Finding requirements fails with the following:
```
...
go: finding github.com/gorilla/rpc v1.2.0+incompatible
go: github.com/gorilla/rpc@v1.2.0+incompatible: unexpected status (https://proxy.golang.org/github.com/gorilla/rpc/@v/v1.2.0+incompatible.info): 410 Gone
go: error loading module requirements
```
## Expected Behavior
build succeeds

## Current Behavior
```
~$ GOPROXY=https://proxy.golang.org GO111MODULE=on go get github.com/minio/minio
go: finding github.com/minio/minio latest
go: finding github.com/gorilla/rpc v1.2.0+incompatible
go: github.com/gorilla/rpc@v1.2.0+incompatible: unexpected status (https://proxy.golang.org/github.com/gorilla/rpc/@v/v1.2.0+incompatible.info): 410 Gone
go: error loading module requirements
```

## Possible Solution
Gorilla RPC has perhaps deprecated v1.2 (now they have v2)

## Steps to Reproduce (for bugs)
1. Install Go 1.12.8 as per instructions.
2. Try to build Minio as per instructions.

## Your Environment
* Version used (`minio version`):
latest from github.com/minio/minio
* Environment name and version (e.g. nginx 1.9.1):
- Ubuntu 16.04.6 
- Mac OS Mojave
- Latest Go

**Comment by nitisht** [comment]
@markkutikkanen I can't seem to reproduce the error, it built for me

**Comment by ghost** [comment]
Did you have a pristine empty (no Go nor any packages on your env) machine prior checking? Could it be the gorilla rpc 1.2.0 was already found in your system?

**Comment by harshavardhana** [comment]
All our CI builds use pristine environment so I think this issue is local to your environment

**Comment by ghost** [comment]
I was able to build it when I omitted `GOPROXY=https://proxy.golang.org` from the command line. With that part it fails just the same way.
