### ISSUE TITLE
Allow suppressing version check without quieting startup

### ISSUE THREAD

**Issue by pitrou** [minio/minio#8087]
Currently you need `--quiet` to disable the version check at startup. It would be nice to allow disabling the version check without removing the startup message.

**Comment by kannappanr** [comment]
@pitrou We will discuss internally and get back to you on this.

**Comment by harshavardhana** [comment]
--quiet is implemented to quiet everything literally for MinIO, piece meal based approach will rather complicate the implementation and not satisfy a single user.

You can set MINIO_UPDATE=off which would turn off update check and keep the banner.

**Comment by pitrou** [comment]
The code checking for updates looks like this:
```go
// Check for updates and print a notification message
func checkUpdate(mode string) {
	// Its OK to ignore any errors during doUpdate() here.
	if updateMsg, _, currentReleaseTime, latestReleaseTime, err := getUpdateInfo(2*time.Second, mode); err == nil {
		if updateMsg == "" {
			return
		}
		if globalInplaceUpdateDisabled {
			logger.StartupMessage(updateMsg)
		} else {
			logger.StartupMessage(prepareUpdateMessage("Run `minio update`", latestReleaseTime.Sub(currentReleaseTime)))
		}
	}
}
```

So my understanding is that `MINIO_UPDATE=off` will turn off the update message (`globalInplaceUpdateDisabled`) but not the update check itself.

**Comment by harshavardhana** [comment]
Yes but doesn't that satisfy your requirement @pitrou

**Comment by pitrou** [comment]
No it doesn't, because I'd like to avoid waiting 1 second for the daemon to start when I'm starting it in a rapid manner in unit tests.

**Comment by harshavardhana** [comment]
@pitrou so --quiet is the way to go. Why do you need startup message when --quiet is specified ? Are you trying to scrape the output?

**Comment by pitrou** [comment]
Not really, I can live with it, but the status message indicates me that Minio started correctly with the right parameters :-) Not a big deal though.

**Comment by harshavardhana** [comment]
How about we print one line `Started` ?

**Comment by pitrou** [comment]
Well, I think the full banner is more informative :-)

**Comment by harshavardhana** [comment]
That defeats the purpose of --quiet

**Comment by pitrou** [comment]
Well, yes, hence this issue ;-)

**Comment by harshavardhana** [comment]
I don't think we will change the current behavior, we will add one line to indicate that server started.

**Comment by kannappanr** [comment]
@pitrou We did discuss this internally and decided not to change the current behavior. Closing this issue as won't fix.
