### ISSUE TITLE
Very high TTFB (5~30s) at peak hours

### ISSUE THREAD

**Issue by henrythefool** [minio/minio#8088]
## Expected Behavior
To get object through API/SDK, the TTFB should be less than 1s.

## Current Behavior
At peak hours(night), the TTFB is very high, about 5 ~ 30s.

## Steps to Reproduce (for bugs)

We have a distributed minio of 6 nodes, and each node exposed 443 through Nginx to public. 
Objects are mainly videos(10 ~ 100MB) and images(50 ~ 100KB).
Object are requested by web players through S3 API. More than 95% requests are GET.

In the daytime(50 ~ 150 users online), the TTFB is about **200ms**, which is acceptable.
But at night(200 ~ 300 users online at same time), the TTFB is **5~30s**. 

PS: Although TTFB is high, but once it started downloading, the speed is fast(more than 2MB/s)

## Context
I did `mc admin trace -v -a` to capture logs.

For example, to get the object *9GxYQwBHM3Gp8FqJiFeQqfqp*, it took 5s to respond: 
![getObject](https://user-images.githubusercontent.com/54152943/63118946-8a3f8700-bfd1-11e9-8d8a-bbc09ea077bd.png)
 
The `RLock` `RUnLock` `internal.ReadAll` requests are all very fast, took about 1ms each.
But`internal.ReadFileStream` is slow:

<img width="1167" alt="105 ReadFileStream 2" src="https://user-images.githubusercontent.com/54152943/63118972-9f1c1a80-bfd1-11e9-9f2a-c2e019910dee.png">

<img width="1164" alt="103 ReadFileStream" src="https://user-images.githubusercontent.com/54152943/63118980-a3483800-bfd1-11e9-9f30-4207fbcdb2f0.png">

I don't know why the request took so long, since the disk is SSD and the object is just several MB so it should be very fast.

## Environment

* Minio Version used: 2019-08-07T01:59:21Z
* System: Ubuntu 18.04
* Node machine information：
> SSD: 160 GB RAID-10
> RAM: 8 GB
> CPU: 6x Intel Xeon
> Link speed: 5 Gigabit

1 of the 6 nodes: 
![image](https://user-images.githubusercontent.com/54152943/63119425-ba3b5a00-bfd2-11e9-9f7e-8cbd94b67e23.png)

**Comment by kannappanr** [comment]
@henrythefool We will take a look and get back to you.

**Comment by krishnasrinivas** [comment]
Note from the document:

https://docs.min.io/docs/setup-nginx-proxy-with-minio.html

> Nginx buffers responses by default. To disable Nginx from buffering MinIO response to temp file, set proxy_buffering off;. This will improve time-to-first-byte for client requests.

let us know if it fixes the problem @henrythefool

**Comment by henrythefool** [comment]
@krishnasrinivas  I configured it exactly according to that document.

**Comment by henrythefool** [comment]
@krishnasrinivas Sorry, I checked the nginx.conf, and there are several differences(I guess the doc was updated)

I didn't add those lines:
```
   proxy_read_timeout 15m;
   proxy_send_timeout 15m;
   proxy_request_buffering off;
```

Now I added these, and I'll check the TTFB tonight.

**Comment by henrythefool** [comment]
1. It doesn't fix the problem.I think the TTFB is still high.
2. **I found that the larger the object, the higher the TTFB.**

**Comment by krishnasrinivas** [comment]
How are you measuring TTFB?
Because:
```
play.minio.io [REQUEST s3.PutBucket] [18:37:30.94515]
play.minio.io [RESPONSE] [18:37:30.94582]
```

Here RESPONSE time stamp is completion time not the first byte time.

If you are using a custom tool to measure TTFB can you check directly talking to minIO without nginx in the middle? To see if nginx is causing any issue.

**Comment by henrythefool** [comment]
I measured it by Chrome dev tools, here are some screenshots captured:

![image](https://user-images.githubusercontent.com/54152943/63209280-30de7180-c111-11e9-86fd-bcddaf598536.png)

![image](https://user-images.githubusercontent.com/54152943/63209282-33d96200-c111-11e9-99d2-3ba62e150bbe.png)

If I `ping` the server, it would be 150~200ms

**Comment by henrythefool** [comment]
I did `mc cp` directly in the server local without Nginx.
It takes 10~20s before it started copy.
Time is mainly spent on `s3.ListObjecsV1`(about 3K objects in bucket)

I haven't tested requested by API without Nginx.

**Comment by krishnasrinivas** [comment]
> I did `mc cp` directly in the server local without Nginx.
> It takes 10~20s before it started copy.
> Time is mainly spent on `s3.ListObjecsV1`(about 3K objects in bucket)

This would be a different issue. Can you file it under https://github.com/minio/mc/issues

> I haven't tested requested by API without Nginx.

Can you test the download TTFB without nginx?

**Comment by henrythefool** [comment]
I tested it with ip:9000 (no Nginx).
In short, the delay is the same as when there is Nginx.

We have a 10 nodes minio cluster, which has 3k objects in a main bucket(less than 200GB).
I did a simple test, trying to fetch a 300MB MP4 object in three scenarios in Chrome without Nginx.

1. In Chrome, it took more than 10s TTFB before it started download.
2. In chrome web player, every partial content request has a 5~20s TTFB.
3. In minio official web browser page, downloading (via .../minio/download/) has less TTFB (5~7s)

If there's anything else I can help, please tell me. (I think the problem is annoying since we're a video site. People waited for a long time before the videos start.)

**Comment by harshavardhana** [comment]
@henrythefool what is the network speed between your clients and MinIO server ? And what is the average load on the server like how many GETs per second?

**Comment by henrythefool** [comment]
In downloading it's 1~5MB/s

**Comment by harshavardhana** [comment]
I mean can you run iperf like tool to get a ballpark figure ?

**Comment by henrythefool** [comment]
OK.

PS: 
I build another cluster for test, 6 nodes, same machine, same network, same buckets and objects. 
It has the same TTFB problem. 
So I think it has no relation with "peak hours".

**Comment by henrythefool** [comment]
I used another server as the client, in the same Local Area Network as the minio cluster.

Here is the network speed(by iperf3):
![image](https://user-images.githubusercontent.com/54152943/63495886-5abddc80-c4f3-11e9-83c3-95ab09f2cd97.png)

Then I used CURL to get an object to measure TTFB in the local network: 
![image](https://user-images.githubusercontent.com/54152943/63496054-bee0a080-c4f3-11e9-8463-e5b80e5e3161.png)

So I don't think it's a network issue.

**Comment by henrythefool** [comment]
In the above test, there's only one user (just me).

**Comment by henrythefool** [comment]
Maybe you can build a similar environment on your own server, it's very simple:
1. Run a distributed minio
2. Put 1-3K objects in a bucket (image 100KB, video 20~200MB)
3. Get a 100MB object

**Comment by harshavardhana** [comment]
I don't see such high TTFB's @henrythefool they are usually really small - are your CPUs really slow? 

I have a simple distributed cluster with 4 nodes, I don't see the same problem. 

```
~ curl -o /dev/null      -H 'Cache-Control: no-cache'      -s      -w "Connect: %{time_connect} TTFB: %{time_starttransfer} Total time: %{time_total} \n" http://72.28.97.51:32433/testbucket/bigfile
Connect: 0.018348 TTFB: 0.180903 Total time: 6.337158
```

There is something wrong in your environment @henrythefool

**Comment by harshavardhana** [comment]
I even uploaded 1k objects nothing really changes in terms of TTFB

```
~ mc ls -r test/testbucket/ | wc -l
1889
```

```
~ curl -o /dev/null      -H 'Cache-Control: no-cache'      -s      -w "Connect: %{time_connect} TTFB: %{time_starttransfer} Total time: %{time_total} \n" http://72.28.97.52:32433/testbucket/bigfile
Connect: 0.020074 TTFB: 0.154902 Total time: 9.575070 
```

**Comment by harshavardhana** [comment]
In-fact my client is my laptop and our server is in our data center, my latency is pretty high

```
~ iperf -c 72.28.97.52
------------------------------------------------------------
Client connecting to 72.28.97.52, TCP port 5001
TCP window size: 85.0 KByte (default)
------------------------------------------------------------
[  3] local 10.0.0.17 port 44946 connected with 72.28.97.52 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  7.38 MBytes  6.16 Mbits/sec
```

**Comment by henrythefool** [comment]
OK. Thank you. I'll test it again in my laptop. 

And, could you add some disk space for paly.min.io? Maybe I can test there.

**Comment by harshavardhana** [comment]
> And, could you add some disk space for paly.min.io? Maybe I can test there.

You can upload 100MiB there is enough space

**Comment by krishnasrinivas** [comment]
@henrythefool did you get any more insights on what might be happening?

**Comment by henrythefool** [comment]
> @henrythefool did you get any more insights on what might be happening?

We no longer use clusters, just use stand-alone deployment.
The performance has returned to normal.

**Comment by harshavardhana** [comment]
Closing this as nothing actionable from our end at this point in time.
