### ISSUE TITLE
multipart/form-data upload using a presigned URL

### ISSUE THREAD

**Issue by kerams** [minio/minio#8099]
## Expected Behavior
File is successfully uploaded.

## Current Behavior
Getting a generic error
```
<Error><Code>InvalidRequest</Code><Message>Invalid Request</Message><Resource>/test/hmmm</Resource><RequestId></RequestId><HostId>56b1fea9-9a30-465a-94da-b272b4eb8be4</HostId></Error>
```

## Steps to Reproduce (for bugs)
- Create a presigned URL using the AWS client (setting Expires, Bucket and Key)
- Send a POST to that URL
```
POST https://blah.com/test/hmmm?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Expires=1566826356&Signature=jafSy5U7uuJ%2BeEQRqKV8DcitoyA%3D HTTP/1.1
Host: blah.com
Connection: keep-alive
Content-Length: 481
Sec-Fetch-Mode: cors
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.110 Safari/537.36 Vivaldi/2.7.1628.12
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryw7eAGjkpfQV9p1NK
Accept: */*
Origin: http://127.0.0.1:8080
Sec-Fetch-Site: cross-site
Referer: http://127.0.0.1:8080/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9

------WebKitFormBoundaryw7eAGjkpfQV9p1NK
Content-Disposition: form-data; name="file"; filename="blah.dat"
Content-Type: application/octet-stream

[snip]
------WebKitFormBoundaryw7eAGjkpfQV9p1NK--
```

## Context
Direct upload using the AWS client and credentials works, so I am positive the presigned URL is correctly generated.
The reason I'm bothering with multipart/form-data is the fact that it probably offers the only way to limit upload size to AWS S3 with presigned URLs.

## Your Environment
* The latest Minio version on Docker hub
* Linux ubu 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by deekoder** [comment]
@kerams  I just checked with our play server and it seems to work fine. https://docs.min.io/docs/upload-files-from-browser-using-pre-signed-urls.html is a good doc to test if there may be a policy issue.

**Comment by Praveenrajmani** [comment]
@kerams I tried this locally here. It worked fine for me

```
 curl -v http://localhost:9000/test  -F success_action_status=201 -F key=tmp_file -F x-amz-algorithm=AWS4-HMAC-SHA256 -F x-amz-credential=minio/20190820/us-east-1/s3/aws4_request -F x-amz-date=20190820T062209Z -F policy=eyJleHBpcmF0aW9uIjogIjIwMTktMDgtMjBUMDc6MjI6MDlaIiwgImNvbmRpdGlvbnMiOiBbeyJzdWNjZXNzX2FjdGlvbl9zdGF0dXMiOiAiMjAxIn0sIHsiYnVja2V0IjogInRlc3QifSwgeyJrZXkiOiAidG1wX2ZpbGUifSwgeyJ4LWFtei1hbGdvcml0aG0iOiAiQVdTNC1ITUFDLVNIQTI1NiJ9LCB7IngtYW16LWNyZWRlbnRpYWwiOiAibWluaW8vMjAxOTA4MjAvdXMtZWFzdC0xL3MzL2F3czRfcmVxdWVzdCJ9LCB7IngtYW16LWRhdGUiOiAiMjAxOTA4MjBUMDYyMjA5WiJ9XX0= -F x-amz-signature=f7a15aca628122bb93724a1559cd96e846a3ba6e21f9ac376350a61ea694099e -F file=@DelayedFlights.csv
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9000 (#0)
> POST /test HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 247964642
> Content-Type: multipart/form-data; boundary=------------------------5fc829d4c638a0d4
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 201 Created
< Accept-Ranges: bytes
< Content-Length: 221
< Content-Security-Policy: block-all-mixed-content
< Content-Type: application/xml
< ETag: "82f4e662ba1da3dad47fc96b00efca1f-1"
< Location: http://localhost:9000/test/tmp_file
< Server: MinIO/DEVELOPMENT.2019-08-19T07-23-36Z
< Vary: Origin
< X-Amz-Request-Id: 15BC8FBCFAC05B26
< X-Xss-Protection: 1; mode=block
< Date: Tue, 20 Aug 2019 07:06:52 GMT
< 
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host localhost left intact
<PostResponse><Bucket>test</Bucket><Key>tmp_file</Key><ETag>&#34;82f4e662ba1da3dad47fc96b00efca1f-1&#34;</ETag><Location>http://localhost:9000/test/tmp_file</Location></PostResponse>
```

Can you share us the `mc admin trace -v` output for this occurrence?

**Comment by kerams** [comment]
`mc admin trace -v minio` isn't printing anything at all for this request. A standard PUT is logged properly, however.

In fact, empty GET and PUT requests using the presigned URL do get logged, but not POST.

**Comment by kerams** [comment]
Empty PUT requests in Postman to presigned URLs generated by both the Minio .NET client and AWS return `SignatureDoesNotMatch`. This might be the underlying problem (apart from the fact that my failing POST requests aren't logged to trace). Any idea why this could be? Both clients upload data correctly when I use PutObjectAsync.

**Comment by Praveenrajmani** [comment]
> In fact, empty GET and PUT requests using the presigned URL do get logged, but not POST.

@kerams `mc admin trace` should be logging presigned hits also. Looks like, the request is not reaching the MinIO server at all. Can you try curling it - like,

`curl -v http://localhost:9000/test  -F success_action_status=201 -F key=tmp_file -F x-amz-algorithm=AWS4-HMAC-SHA256 -F x-amz-credential=minio/20190820/us-east-1/s3/aws4_request -F x-amz-date=20190820T085347Z -F policy=eyJleHBpcmF0aW9uIjogIjIwMTktMDgtMjBUMDk6NTM6NDdaIiwgImNvbmRpdGlvbnMiOiBbeyJzdWNjZXNzX2FjdGlvbl9zdGF0dXMiOiAiMjAxIn0sIHsiYnVja2V0IjogInRlc3QifSwgeyJrZXkiOiAidG1wX2ZpbGUifSwgeyJ4LWFtei1hbGdvcml0aG0iOiAiQVdTNC1ITUFDLVNIQTI1NiJ9LCB7IngtYW16LWNyZWRlbnRpYWwiOiAibWluaW8vMjAxOTA4MjAvdXMtZWFzdC0xL3MzL2F3czRfcmVxdWVzdCJ9LCB7IngtYW16LWRhdGUiOiAiMjAxOTA4MjBUMDg1MzQ3WiJ9XX0= -F x-amz-signature=c5c3a44e7490696f48c48208ea26563c40b920023d0d01dd5741fe906ce3f848 -F file=@DelayedFlights.csv`

**Comment by Praveenrajmani** [comment]
It would be better if you can join the #general slack channel - https://minio.slack.com/join/shared_invite/enQtNjM3MDQ5NzI1MjUxLTlmMzIxNmUxZjBlNWUzMzI4YTkyYmE4ZDRiZTYyMDZjY2QyZjlmODY0MTMxODQxODc0MzkxZTExNTUyNjdmYjc

**Comment by Praveenrajmani** [comment]
> Empty PUT requests in Postman to presigned URLs generated by both the Minio .NET client and AWS return `SignatureDoesNotMatch`. This might be the underlying problem (apart from the fact that my failing POST requests aren't logged to trace). Any idea why this could be? Both clients upload data correctly when I use PutObjectAsync.

You should use `POST` method for presigned post urls

**Comment by kerams** [comment]
The response I am getting for POST is `<Error><Code>InvalidRequest</Code><Message>Invalid Request</Message><Resource>/test/hmmm</Resource><RequestId></RequestId><HostId>56b1fea9-9a30-465a-94da-b272b4eb8be4</HostId></Error>`, so it is reaching the server.

**Comment by Praveenrajmani** [comment]
> The response I am getting for POST is `<Error><Code>InvalidRequest</Code><Message>Invalid Request</Message><Resource>/test/hmmm</Resource><RequestId></RequestId><HostId>56b1fea9-9a30-465a-94da-b272b4eb8be4</HostId></Error>`, so it is reaching the server.

Did you see the trace in `mc admin trace` ? @kerams

**Comment by Praveenrajmani** [comment]
> InvalidRequest

@kerams How are you constructing your POST request? Can you try curl? ... looks like Postman's latest version - v7.5.0 does not have an option to frame a body with multipart form data

**Comment by Praveenrajmani** [comment]
ping @kerams

**Comment by kerams** [comment]
@Praveenrajmani Thanks for your help and time. I have misunderstood the way the presigned URL is to be used, all good now (except for the fact that the request in my original post did not get logged, even though your curl did).
