### ISSUE TITLE
Why has the usual way of Versioning (X.Y.Z) not been adapted ? 

### ISSUE THREAD

**Issue by gk-patel** [minio/minio#8103]
## Expected Behavior
Usually, many softwares have a versioning scheam like X.Y.Z - where, X=Major, Y=Minor and Z=features. I am wondering, why this type of scheme has not been implemented here. Such a scheame would help users decide when they should/want to update. 

## Current Behavior
Versioning is done based on release timestamp. This scheme is monotonous and does not let users classify between major and minor changes. 

## Your Environment
I plan to use Minio for a long term storage of files. I usually upgard versions when a major version become stable over time, thereby avoiding the risk of loosing the data and also staying up-to-date with the new security fixes, etc. I dont see this possibility with the current versioning scheme. 

Thank you for your time and consideration

**Comment by harshavardhana** [comment]
Explained here https://github.com/minio/minio/issues/2318#issuecomment-235992350

**Comment by gk-patel** [comment]
Ya. So as long as we use the stable version, it is sort of garuenteed, that updating the version will work out of the box. But somethings are still not clear, is there a specifc guide that one needs to follow for updating Minio instances, 

because, for example, in your comments (linked above), you said that minio will handle migrations automatically. But, in one of the latest release (RELEASE.2019-08-14T20-37-41Z), there is a statement "Rolling upgrade is not recommended for this release, please upgrade all servers". 

This indicates that there is no single set of instructions, that one can/should follow to upgrade deployed instances. 

When storing data for long term, it is really important not to bet on software-update procedure that could potentially corrupt data. And, if the procedure is slightly different each time, we are bound to make mistakes. 

Is minio somehow resistant to mistakes made during updates ? Is there a known procedure to recover data if problems happen during updates ? 

P.S. sorry for the very long comment, I personally really like Minio and I am planning to use it, but I just want to know if I can safely store data for long term and also update the software regularly. 

Thanks, and best Regards,

**Comment by kannappanr** [comment]
@gk-patel regarding your comment `"Rolling upgrade is not recommended for this release, please upgrade all servers".`

Have changed the release note to just say `"Rolling upgrade is not recommended for this release"`

Basically, what this means is that in the case of `distributed MinIO`, you will have to upgrade MinIO binary on all the nodes and then restart, as the internal APIs to talk between the nodes have been changed. This has got nothing to do with data being stored and migration of the format.

**Comment by harshavardhana** [comment]
You can safely use MinIO long term, and update the software regularly. We adopted this model due to cloud native deployment style. Each MinIO server makes sure either migrate the data to new format or retains the ability to read older formats appropriately. We guarantee this contract whoever is using our software.

Semver is useful in libraries such as minio-go but not for MinIO server.  Going to close this issue since there is nothing actionable for us.

**Comment by gk-patel** [comment]
@kannappanr: I think you missed to get my point, its not about a specific release. I am using minio with docker, wherein my compose-file has a statement like `image: minio/minio:latest`. Now lets say, I restart/update my service, which will automatically pull the latest image and start multiple containers with the latest image -- the question is:  **Is it garuenteed that the data created by the previous version will work out-of-the-box with the new instances (containing newer version) ?** becuase the images are pulled automatically. 

If there would be a Semver, I would write something like `image: minio/minio:X` (where, X is a particular Major version). This way, every service update/release would get me the latest features for that major version (via the automatic pull), and at some point of time, .... when version X would not be supported, I would refer to the migration guide and change my compose file to point to version Y. 

What I was looking for is the best of two worlds, 1) Automatically pull images without having to worry about format incompatibality issues and 2) Once in a while update to newer versions by systematically going through some migration guide. 

Nevertheless, according to the answer from @harshavardhana, I understand that minio manages format-compatibality out-of-the-box. 

---- 
Although, not my use-case, I would like to present you with a following (unrealistic) scenario, 

lets say, I have a few minio instances running in a distributed manner. I don't update these instances for 2 years, and suddenly I decide to update them. **Will the formats still be compitable ?**, will it still work-out-of-the-box ? 

In such cases, if Semver were to be used, I would have a clear migration guide(s), on how to migrate through different major versions that were rolled out during the last two years. 


@kannappanr and @harshavardhana thank you very much for your time and replies, I really appreciate your efforts.

**Comment by harshavardhana** [comment]
> lets say, I have a few minio instances running in a distributed manner. I don't update these instances for 2 years, and suddenly I decide to update them. **Will the formats still be compitable ?**, will it still work-out-of-the-box ?

Yes, they will be - it is guaranteed that they will be compatible. That is the guarantee we want to give to our users. In-fact our binary has been compatible with our releases even from early 2017.

**Comment by harshavardhana** [comment]
Our point is there is no migration needed and shouldn't be needed at the scale we are talking these days. The scale that is being deployed in the storage world, anyone sane wouldn't attempt migration of stored content.  This is where we saw semver is not useful and is a hindrance to our release strategy even introducing such thing might confuse users. We are interested in making frequent releases quickly such that bugs fixed are delivered as fast we develop them.

You are right in asking these questions but this is something that we fundamentally built into the software itself so any data that was created today or in the past would still be readable anytime in future.

**Comment by gk-patel** [comment]
Okay. So minio has "backward compitability forever". Thats a very practical and a state-of-the-art approach you guys have implemented. Nice to know, I am impressed. Thanks for answering my questions (with pacience ;) ).
