### ISSUE TITLE
Support namespaced JWT Claims

### ISSUE THREAD

**Issue by edude03** [minio/minio#8107]
**Is your feature request related to a problem? Please describe.**
I'd like to use Minio with Auth0 providing authentication via JWTs, however, because  auth0 requires the use of namespaced keys for custom claims (ie, `min.io/policy` instead of just `policy`) I'm unable to use the two together

**Describe the solution you'd like**
Support an additional parameter such as `JWT_CLAIM_NAMESPACE` that would allow policy to be set via auth0 source JWT

**Comment by harshavardhana** [comment]
Thanks @edude03 for opening the issue

**Comment by harshavardhana** [comment]
@kanagarajkm is adding this in his PR #8075
