### ISSUE TITLE
server: Support multiple api keys

### ISSUE THREAD

**Issue by anuaimi** [minio/minio#811]
We'd like have each key be limited to specific buckets. There are many use cases where this would be useful. Out use case is a different buffer for development servers and production. We'd like to limit access to production buckets to only team members with access to production servers. The rest of the team would just have access to the development buckets

**Comment by rghv** [comment]
:+1: 

would be a very useful feature!

**Comment by anuaimi** [comment]
Could you explain why this is marked "won't fix"?  Thanks

**Comment by harshavardhana** [comment]
> Could you explain why this is marked "won't fix"? Thanks

Minio micro service will not have multiple user serviceable console and no way to provision multiple users per instance. Minio micro service should be used for multiple users with several instances.  So "won't fix" is for Minio micro service. 

Minio XL which is separated into a new project will have multiple users and a self serviceable console.

**Comment by Crafter6432** [comment]
Does this project exist yet ?

**Comment by GarimaKapoor** [comment]
Minio follows a microstorage design. You achieve multi tenancy by spinning one Minio instance per user.
