### ISSUE TITLE
Data Corruption : multipart/form-data upload using PUT presigned URL through .net c#

### ISSUE THREAD

**Issue by scorpuva** [minio/minio#8111]
When i tried to upload a file content (as multipart/form-data) using .net core c# library.
It uploads successfully but it corrupts the file content.
When i open the file, i see the uploaded file content has the boundary text as well.
I have attached the sample code to simulate this issue.
I was able to reproduce the issue in Postman as well. (attached screenshot **postman.png** for sample request)
1. Get the presigned put upload url from miniosdk
2. Paste it in the postman request window
3. Change the http verb to PUT (by default the request window goes to GET)
4. Select Body => Select form-data => Select key as File
5. Browse and choose the file
6. hit Send button

## Expected Behavior
Should store only the file content.

## Current Behavior
It stores the multipart boundary strings, content-types and other headers part of multipart

## Steps to Reproduce (for bugs)
Attached files.
**Sample.txt (Attached)** is the file which i used to upload through .net core app and postman using the presigned put upload url
**testobjectmultipart.txt (Attached)** is the file being created or stored by the minio. You could see the original file got modified after i uploaded using the presigned put url.
**MinioStorageClient.cs (below code)** is the .net core implementation used to get presigned put url and upload file
```
using Minio;
using System.Threading.Tasks;
using System.IO;
using System;
using System.Net.Http;

public class MinioStorageClient
{
    MinioClient StorageClient = null;
    public MinioStorageClient()
    {
        StorageClient = new MinioClient("127.0.0.1:9000",
                                   "accesskey",
                                   "blahblahblahblah=="
                             ).WithSSL();
    }

    public async Task<string> GetUploadPutUrl(string containerName, string objectName)
    {
        try
        {
            return await StorageClient.PresignedPutObjectAsync(containerName, objectName, 60 * 60);
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.ToString());
            return string.Empty;
        }
    }
    public async Task<bool> Upload(string putUrl, string filePath)
    {        
        var Stream = new StreamReader(filePath);
        using (var client = new HttpClient())
        {
            using (var content = new MultipartFormDataContent("MultipartUploadBoundary----"))
            {
                content.Add(new StreamContent(Stream.BaseStream));
                using (var message = await client.PutAsync(putUrl, content))
                {
                    var input = await message.Content.ReadAsStringAsync();
                }
            }
        }
        return true;
    }
}
```
**program.cs (below code)** is the main file of the .net core app

```
using System;

namespace MinioTestClient
{
    class Program
    {
        static void Main(string[] args)
        {
            var Client = new MinioStorageClient();
            var UploadUrl = Client.GetUploadPutUrl("testbucket", "testobjectmultipart.txt").GetAwaiter().GetResult();
            Client.Upload(UploadUrl, "sample.txt").GetAwaiter().GetResult();
            Console.WriteLine("Hello World!");
        }                
    }
}
```

## Your Environment

* Version used RELEASE.2019-08-14T20-37-41Z
* Ran in cmd window => minio.exe server c:\testfolder
![Postman](https://user-images.githubusercontent.com/54331981/63383033-0b987000-c36a-11e9-9687-afc9691227c2.png)
[Sample.txt](https://github.com/minio/minio/files/3522506/Sample.txt)
[testobjectmultipart.txt](https://github.com/minio/minio/files/3522507/testobjectmultipart.txt)

**Comment by harshavardhana** [comment]
You need to use POST if you are using PUT doesn't recognize multipart form boundaries the behavior is same as AWS S3

**Comment by scorpuva** [comment]
Getting an error,
`<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented</Message><Resource>/testbucket/testobjectmultipart.txt</Resource><RequestId></RequestId><HostId>4e9a3580-ea37-4346-ba3b-ee8aaff4312b</HostId></Error>`

Url I formed for POST,
`https://127.0.0.1:9000/testbucket/testobjectmultipart.txt?x-amz-algorithm=AWS4-HMAC-SHA256&x-amz-credential=minioobjectstorage/20190820/us-east-1/s3/aws4_request&x-amz-date=20190820T211903Z&policy=eyJleHBpcmF0aW9uIjoiMDAwMS0wMS0wMVQwMDowMDowMC4wMDBaIiwiY29uZGl0aW9ucyI6W1siZXEiLCIkYnVja2V0IiwidGVzdGJ1Y2tldCJdLFsiZXEiLCIka2V5IiwidGVzdG9iamVjdG11bHRpcGFydC50eHQiXSxbImVxIiwiJHgtYW16LWFsZ29yaXRobSIsIkFXUzQtSE1BQy1TSEEyNTYiXSxbImVxIiwiJHgtYW16LWNyZWRlbnRpYWwiLCJtaW5pb29iamVjdHN0b3JhZ2UvMjAxOTA4MjAvdXMtZWFzdC0xL3MzL2F3czRfcmVxdWVzdCJdLFsiZXEiLCIkeC1hbXotZGF0ZSIsIjIwMTkwODIwVDIxMTkwM1oiXV19&x-amz-signature=43c73a4a143515ac8716b6640bdf216d29db9080874e6418ad39a8c2e9a6fb24`

code used to form post url
```
public async Task<string> GetUploadPostUrl(string containerName, string objectName)
    {
        try
        {
            PostPolicy policy = new PostPolicy();
            policy.SetBucket(containerName);
            policy.SetKey(objectName);
            var Response =  await StorageClient.PresignedPostPolicyAsync(policy);
            var Endpoint = Response.Item1;
            var PostUrlParts = "";
            foreach(var keyvaluepair in Response.Item2)
            {
                if (keyvaluepair.Key.Equals("bucket", StringComparison.InvariantCultureIgnoreCase))
                {
                    Endpoint = Endpoint + keyvaluepair.Value + "/";
                    continue;
                }
                if (keyvaluepair.Key.Equals("key", StringComparison.InvariantCultureIgnoreCase))
                {
                    Endpoint = Endpoint + keyvaluepair.Value;
                    continue;
                }
                if (!string.IsNullOrEmpty(PostUrlParts))
                {
                    PostUrlParts = $"{PostUrlParts}&";
                }
                PostUrlParts = $"{PostUrlParts}{keyvaluepair.Key}={keyvaluepair.Value}";
            }
            return $"{Endpoint}?{PostUrlParts}";
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.ToString());
            return string.Empty;
        }
    }
```

**Comment by harshavardhana** [comment]
Post URL is uploaded in multipart form not using query params

**Comment by scorpuva** [comment]
Getting error as 
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MethodNotAllowed</Code><Message>The specified method is not allowed against this resource.</Message><BucketName>testbucket</BucketName><Resource>/testbucket/testobjectmultipart.txt</Resource><RequestId>15BCC2779688E4B8</RequestId><HostId>4e9a3580-ea37-4346-ba3b-ee8aaff4312b</HostId></Error>
```
Do you have any sample application for .net ?
Even if you share me postman collection also works for me.

**Comment by scorpuva** [comment]
The URL I used to do post multipart: 
`https://127.0.0.1:9000/testbucket/testobjectmultipart.txt`

Below is the payload
```
--c25c7371-6ca4-4e92-ad53-ae29a0dd787d
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data

key=testobjectmultipart.txt
--c25c7371-6ca4-4e92-ad53-ae29a0dd787d
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data

x-amz-algorithm=AWS4-HMAC-SHA256
--c25c7371-6ca4-4e92-ad53-ae29a0dd787d
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data

x-amz-credential=minioobjectstorage/20190820/us-east-1/s3/aws4_request
--c25c7371-6ca4-4e92-ad53-ae29a0dd787d
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data

x-amz-date=20190820T224339Z
--c25c7371-6ca4-4e92-ad53-ae29a0dd787d
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data

policy=eyJleHBpcmF0aW9uIjoiMjAxOS0wOC0yMVQwMDo0MzozOS4wMDBaIiwiY29uZGl0aW9ucyI6W1siZXEiLCIkYnVja2V0IiwidGVzdGJ1Y2tldCJdLFsiZXEiLCIka2V5IiwidGVzdG9iamVjdG11bHRpcGFydC50eHQiXSxbImVxIiwiJHgtYW16LWFsZ29yaXRobSIsIkFXUzQtSE1BQy1TSEEyNTYiXSxbImVxIiwiJHgtYW16LWNyZWRlbnRpYWwiLCJtaW5pb29iamVjdHN0b3JhZ2UvMjAxOTA4MjAvdXMtZWFzdC0xL3MzL2F3czRfcmVxdWVzdCJdLFsiZXEiLCIkeC1hbXotZGF0ZSIsIjIwMTkwODIwVDIyNDMzOVoiXV19
--c25c7371-6ca4-4e92-ad53-ae29a0dd787d
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data

x-amz-signature=4c58161c29569a6e7a9b1851a44966b7bc7382fc151d3dcffc86cb560ebd7d19
--c25c7371-6ca4-4e92-ad53-ae29a0dd787d--
```

**Comment by harshavardhana** [comment]
All of those are actually not correct, the correct way is documented here https://aws.amazon.com/blogs/developer/uploading-to-amazon-s3-with-http-post-using-the-aws-sdk-for-net/

**Comment by scorpuva** [comment]
@harshavardhana  all I am asking is a sample HTTP message of multipart formdata. It would be great if you show me one using .net httpclient. The link which you gave explains about the C# aws sdk client. If you have any other link or share me some sample would really helps here.

**Comment by deekoder** [comment]
@scorpuva see if this helps : https://github.com/minio/minio-dotnet/tree/master/Minio.Examples/Cases

**Comment by scorpuva** [comment]
Still not working with .net core HTTP client. 

I created the curl command using the sample you shared

`curl -X POST  -F bucket=testbucket -F key=sample.txt -F x-amz-algorithm=AWS4-HMAC-SHA256 -F x-amz-credential=minioobjectstorage/20190821/us-east-1/s3/aws4_request -F x-amz-date=20190821T232930Z -F policy=eyJleHBpcmF0aW9uIjoiMjAxOS0wOC0yMlQwMToyOTozMC4wMDBaIiwiY29uZGl0aW9ucyI6W1siZXEiLCIkYnVja2V0IiwidGVzdGJ1Y2tldCJdLFsiZXEiLCIka2V5Iiwic2FtcGxlLnR4dCJdLFsiZXEiLCIkeC1hbXotYWxnb3JpdGhtIiwiQVdTNC1ITUFDLVNIQTI1NiJdLFsiZXEiLCIkeC1hbXotY3JlZGVudGlhbCIsIm1pbmlvb2JqZWN0c3RvcmFnZS8yMDE5MDgyMS91cy1lYXN0LTEvczMvYXdzNF9yZXF1ZXN0Il0sWyJlcSIsIiR4LWFtei1kYXRlIiwiMjAxOTA4MjFUMjMyOTMwWiJdXX0= -F x-amz-signature=b68a4999c89ad9c772c940abe5ddb37be5a85e720bdd843eb1b62513864fe17f -F file=@sample.txt https://127.0.0.1:9000/`

Used the below link to convert curl command to .net command
https://curl.olsh.me/

```
using (var httpClient = new HttpClient())
{
    using (var request = new HttpRequestMessage(new HttpMethod("POST"), "https://127.0.0.1:9000/"))
    {
        var multipartContent = new MultipartFormDataContent();
        multipartContent.Add(new StringContent("testbucket"), "bucket");
        multipartContent.Add(new StringContent("sample.txt"), "key");
        multipartContent.Add(new StringContent("AWS4-HMAC-SHA256"), "x-amz-algorithm");
        multipartContent.Add(new StringContent("minioobjectstorage/20190821/us-east-1/s3/aws4_request"), "x-amz-credential");
        multipartContent.Add(new StringContent("20190821T232930Z"), "x-amz-date");
        multipartContent.Add(new StringContent("eyJleHBpcmF0aW9uIjoiMjAxOS0wOC0yMlQwMToyOTozMC4wMDBaIiwiY29uZGl0aW9ucyI6W1siZXEiLCIkYnVja2V0IiwidGVzdGJ1Y2tldCJdLFsiZXEiLCIka2V5Iiwic2FtcGxlLnR4dCJdLFsiZXEiLCIkeC1hbXotYWxnb3JpdGhtIiwiQVdTNC1ITUFDLVNIQTI1NiJdLFsiZXEiLCIkeC1hbXotY3JlZGVudGlhbCIsIm1pbmlvb2JqZWN0c3RvcmFnZS8yMDE5MDgyMS91cy1lYXN0LTEvczMvYXdzNF9yZXF1ZXN0Il0sWyJlcSIsIiR4LWFtei1kYXRlIiwiMjAxOTA4MjFUMjMyOTMwWiJdXX0="), "policy");
        multipartContent.Add(new StringContent("b68a4999c89ad9c772c940abe5ddb37be5a85e720bdd843eb1b62513864fe17f"), "x-amz-signature");
        multipartContent.Add(new ByteArrayContent(File.ReadAllBytes("sample.txt")), "file", Path.GetFileName("sample.txt"));
        request.Content = multipartContent; 

        var response = await httpClient.SendAsync(request);
    }
}
```

**Comment by scorpuva** [comment]
It works after adding the bucket name to the url.
The sample has to be corrected ! 
[PresignedPostPolicy.cs](https://github.com/minio/minio-dotnet/blob/master/Minio.Examples/Cases/PresignedPostPolicy.cs)

Tuple<string, Dictionary<string, string>> tuple = await client.PresignedPostPolicyAsync(form);
                string curlCommand = "curl -X POST ";
                foreach (KeyValuePair<string, string> pair in tuple.Item2)
                {
                    curlCommand = curlCommand + $" -F {pair.Key}={pair.Value}";
                }
                **curlCommand = curlCommand + " -F file=@/etc/bashrc " + tuple.Item1+my-bucketname;**

**Comment by scorpuva** [comment]
I am getting an error with file upload of size = 2GB
Using Post Url

```
Error: [31m[1mmultipart: message too large[0m[0m
       4: cmd\bucket-handlers.go:596:cmd.objectAPIHandlers.PostPolicyBucketHandler()
       3: cmd\http-tracer.go:209:cmd.Trace()
       2: cmd\handler-utils.go:346:cmd.httpTraceHdrs.func1()
       1: net\http\server.go:1995:http.HandlerFunc.ServeHTTP()
```

Do i need to modify any config settings of minio?

**Comment by harshavardhana** [comment]
Are you sure your file size is 2GiB ? This error message is related to the multipart form keys being larger than acceptable values. Are you trying to base64 encode your stream by any chance ?

**Comment by harshavardhana** [comment]
Also please do share the code..

**Comment by scorpuva** [comment]
the code which i used to perform test,
Started minio in cmd with below parameters
>>`minio.exe server c:\localstorage`

Test Code:
```
```
    class Program
    {
        static void Main(string[] args)
        {
            var Client2 = new MinioStorageClientTest();
            Client2.Test().GetAwaiter().GetResult();
        }                
    }
```
public class MinioStorageClientTest
{
    MinioClient StorageClient = null;
    public MinioStorageClientTest()
    {
        StorageClient = new MinioClient("127.0.0.1:9000",
                                   "accesskey",
                                   "secretkey"
                             ).WithSSL();
    }

    /// <summary>
    /// Invoke the test method
    /// </summary>
    /// <returns></returns>
    public async Task<bool> Test()
    {
        await Post2GBFileData("testbucket");
        return true;
    }

    private async Task<Tuple<string, Dictionary<string, string>>> Post2GBFileData(string containerName, string fileName = @"2GBFile.zip")
    {
        try
        {
            string BucketKeyName = "bucket";
            PostPolicy policy = new PostPolicy();
            policy.SetBucket(containerName);
            policy.SetKey(fileName);
            policy.SetExpires(DateTime.UtcNow.AddHours(2));
            var Response = await StorageClient.PresignedPostPolicyAsync(policy);
            var Endpoint = Response.Item1;
            foreach (var keyvaluepair in Response.Item2)
            {
                if (keyvaluepair.Key.Equals(BucketKeyName, StringComparison.InvariantCultureIgnoreCase))
                {
                    Endpoint = Endpoint + keyvaluepair.Value;
                    break;
                }
            }
            await UploadAsFormData(Endpoint, fileName, Response.Item2);
            return Response;
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.ToString());
            throw ex;
        }
    }

    private async Task<bool> UploadAsFormData(string putUrl, string filePath, Dictionary<string, string> keys)
    {
        string FileFormdataKeyName = "file";
        var Stream = new StreamReader(filePath);
        using (var client = new HttpClient())
        {
            using (var content = new MultipartFormDataContent())
            {
                foreach (var keyvaluepair in keys)
                {
                    content.Add(new StringContent(keyvaluepair.Value), keyvaluepair.Key);
                }
                content.Add(new StreamContent(Stream.BaseStream), FileFormdataKeyName);
                //var FormDataMessage = await content.ReadAsStringAsync();                
                using (var message = await client.PostAsync(putUrl, content))
                {
                    var Response = await message.Content.ReadAsStringAsync();
                    Console.WriteLine(message.StatusCode);
                    Console.WriteLine(Response);
                }
            }
        }
        return true;
    }
}
```

**Comment by scorpuva** [comment]
> Are you sure your file size is 2GiB ? This error message is related to the multipart form keys being larger than acceptable values. Are you trying to base64 encode your stream by any chance ?

Yes. its 1.97 GB. i am not doing base64 encode
