### ISSUE TITLE
Bucket `images` does not exist

### ISSUE THREAD

**Issue by EugenePisotsky** [minio/minio#8117]
Hello!

```bash
$ mc ls dev/
[2019-03-09 13:36:53 EET]      0B core/
[2019-08-11 15:53:56 EEST]      0B images/

$ mc ls dev/images/
mc: <ERROR> Unable to stat `dev/images/`. Bucket `images` does not exist.
```

Any ideas why it prints "Bucket does not exist" even though it's visible in the root `mc ls` output?

**Comment by harshavardhana** [comment]
Closing this issue as incomplete, please reopen the issue with issue template filled with enough details about server version etc.

Thank you..
