### ISSUE TITLE
Starting docker container failed with permission error

### ISSUE THREAD

**Issue by JinghengHuang** [minio/minio#8119]
## Expected Behavior

It was run on production smoothly for a few month. Recently there were some event that caused the production server to shutdown and reboot. After the reboot, I tried to restart the docker container with `docker restart <container name>`.  This should normally work, and it worked as expected before.

## Current Behavior

Instead of starting the container normally, it raised an error: `[8] System error: mkdir /var/lib/docker/devicemapper/mnt/faef4dc64ae96126b7fa500793cfe49db52d1db354b03a1595373f8e1e80d2c7/rootfs/dev/pts: permission denied`

## Possible Solution

I have no idea why this would happen, but I suspect it is something wrong with docker and the server (using CentOS 7)

## Steps to Reproduce (for bugs)

1.restart the container with `docker start <container name>`

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: 
* Operating System and version (`uname -a`): 
* Link to your project:

**Comment by harshavardhana** [comment]
This looks like docker issue @JohnHenryEden have you verified this locally ?

**Comment by JinghengHuang** [comment]
@harshavardhana Locally it worked fine, I guess it is docker issue.

**Comment by harshavardhana** [comment]
Yes MinIO doesn't do anything related to pts directory this is outside our control ..  feel free to close the issue if you have no further questions.
