### ISSUE TITLE
Bucket policies to allow only GetObject but not ListObjects is denied on Azure Kubernetes

### ISSUE THREAD

**Issue by ewolfman** [minio/minio#8121]
I am trying to setup a minio on Azure Kubernetes with GetObject but without/deny ListObject. 
This is designated to provide urls to explicit files on a public azure but not to allow listing.
It works great on a local Minio server but on Azure, using the release (RELEASE.2019-08-14T20-37-41Z), I get this for every policy configuration that I try in order to reach my goal:
"_A header you provided implies functionality that is not implemented._"

## Expected Behavior
Setting up a policy with only GetObject on Azure should work, or some other configuration to allow me to provide public access to specific files but deny public listing of all the files.

This is an example policy that I am trying and is working perfectly in my local minio server:
`{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"AWS":["*"]},"Action":["s3:GetObject"],"Resource":["arn:aws:s3:::tmp/*"]}]}`

So this works: http://localhost:9000/tmp/1.wav
And this should be denied: http://localhost:9000/tmp

## Current Behavior
Trying to apply the above policy, or any policy that attempts to Deny ListObject, fails with the error: "_A header you provided implies functionality that is not implemented._"

Using 'mc admin trace' I saw that I keep getting 501 Not Implemented:

> 127.0.0.1 [RESPONSE] [13:58:32.550544041]
127.0.0.1 501 Not Implemented
127.0.0.1 Content-Length: 277
127.0.0.1 Content-Security-Policy: block-all-mixed-content
127.0.0.1 Content-Type: application/xml
127.0.0.1 Server: MinIO/RELEASE.2019-08-14T20-37-41Z
127.0.0.1 Vary: Origin
127.0.0.1 X-Amz-Request-Id: 15BCA633F5599B34
127.0.0.1 X-Xss-Protection: 1; mode=block
127.0.0.1 Accept-Ranges: bytes
127.0.0.1 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented</Message><BucketName>tmp</BucketName><Resource>/tmp/</Resource><RequestId>15BCA633F5599B34</RequestId><HostId></HostId></Error>

## Steps to Reproduce (for bugs)
1. Setup a minio deployment on Azure Kubernetes.
2. Try applying a policy to allow GetObject and without/deny ListObject.

## Context
Trying to provide public anonymous download urls to files but deny their listing.

## Your Environment
* Version used (`minio version`): RELEASE.2019-08-14T20-37-41Z
* Environment name and version (e.g. nginx 1.9.1): Azure kubernetes v1.14.3

**Comment by harshavardhana** [comment]
> It works great on a local Minio server but on Azure, using the release (RELEASE.2019-08-14T20-37-41Z), I get this for every policy configuration that I try in order to reach my goal:

This is mentioned in the documentation https://github.com/minio/minio/blob/master/docs/gateway/azure.md#known-limitations 

These are limitations of Azure Blob Store, we don't try to simulate AWS style policies if backend doesn't provide such functionalities. So gateway simply exposes the limitations of backend.

**Comment by nitisht** [comment]
Closing this as there are no plans to do this
