### ISSUE TITLE
Invalid total number of endpoints

### ISSUE THREAD

**Issue by krakazyabra** [minio/minio#8123]
## Expected Behavior
I run MinIO on the storage with 100+ hard drives (1 drive = 1 FS).  
`minio server \ $(for i in $(ls /mnt); do echo /mnt/$i; done)`  
I expected to add 99 of endpoints to minio server, but i got

## Current Behavior  
`ERROR Unable to validate passed endpoints: Invalid total number of endpoints (99) passed, supported upto 32 unique arguments`

## Possible Solution
Allow to add more endpoints

## Steps to Reproduce (for bugs)
Create more then 32 filesystems on your drives, start `minio server` with all these filesystems

## Context
I have huge storage: 99 drives, 10Tb each. I'd like to use each disk as single filesystem, to be able replace it in fail-over situation.

## Your Environment

* Version used (`minio version`):  
`Version: 2019-08-21T19:40:07Z
Release-Tag: RELEASE.2019-08-21T19-40-07Z
Commit-ID: 2fa98b1d6a013e0fda0d810ae9b6cda94b026dfc
`
* Environment name and version (e.g. nginx 1.9.1):  
nothing
* Server type and version:
HPE CL5800
* Operating System and version (`uname -a`):
`Linux petastor1 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 GNU/Linux`

**Comment by nitisht** [comment]
are all of these drives attached to single node @krakazyabra ? If yes, can you try with an even number of drives?

**Comment by harshavardhana** [comment]
> `minio server \ $(for i in $(ls /mnt); do echo /mnt/$i; done)`

The point is just providing `minio server /mnt/{1...1024}` in ellipses syntax, if your mounts are not enumerated then enumerate them and It will make it work. Also they should be even number of disks.

What you are doing is providing way more endpoints that MinIO can use on the command line, there is a hard limit of 32.

**Comment by kannappanr** [comment]
Closing this as answered. Please feel free to reach out to us at https://slack.min.io for such questions

**Comment by krakazyabra** [comment]
> are all of these drives attached to single node @krakazyabra ? If yes, can you try with an even number of drives?

Hi! Yes, all these drives are attached to one node. 


> > `minio server \ $(for i in $(ls /mnt); do echo /mnt/$i; done)`
> 
> The point is just providing `minio server /mnt/{1...1024}` in ellipses syntax, if your mounts are not enumerated then enumerate them and It will make it work. Also they should be even number of disks.
> 
> What you are doing is providing way more endpoints that MinIO can use on the command line, there is a hard limit of 32.

Hi! With `minio server \ $(for i in $(ls /mnt); do echo /mnt/$i; done)` everything is fine, it works as intended. 
In this issue i would like to make future request to increase the number of endpoint devices.

**Comment by harshavardhana** [comment]
We won't increase it anytime soon, this is why we provide ellipses syntax @krakazyabra
