### ISSUE TITLE
GCS gateway with disk cache - cache is corrupted when first-time request is aborted

### ISSUE THREAD

**Issue by jaroslawr** [minio/minio#8130]
I run the minio GCS proxy with disk cache enabled. When I make a first time GET request to read some file from the minio gateway server, for a file which is not yet present in the minio disk cache, and I abort the request before it finishes, minio apparently corrupts its cache - the correct md5 sum (etag) is stored, the same one that is returned when downloading the file directly from the google cloud, but empty file contents. Now any further client requests to the gateway receive an empty file as a response but the correct md5. Some S3 clients then detect that the md5 does not match the file contents and raise an error.

I run minio from the Docker image `minio/minio:RELEASE.2019-08-14T20-37-41Z`. My setup is very simple, along the lines of:

```
export GOOGLE_APPLICATION_CREDENTIALS=credentials.json
export MINIO_CACHE_DRIVES="/var/minio-xyz/data"
export MINIO_CACHE_EXPIRY=365
export MINIO_CACHE_MAXUSE=90
minio gateway gcs xyz
```

**Comment by kannappanr** [comment]
@jaroslawr We will take a look at this issue and get back to you.
