### ISSUE TITLE
public 

### ISSUE THREAD

**Issue by bisegni** [minio/minio#8131]
**Is your feature request related to a problem? Please describe.**
I have server host in a private network with some floating ip that expose these machine to public. I have the ssl certificate of each one fo the server. but when I start minio in distributed mode I can't see a way to let minio that have an external ip that is registered in certificate. Wo Every node can't connect because get an ssl error connection

**Describe the solution you'd like**
Add something to set the specified public ip for a node

**Describe alternatives you've considered**

**Additional context**

**Comment by harshavardhana** [comment]
This is not MinIO related issue, you need to have a public proxy terminator which communicates back to private IP.  MinIO cannot do anything in your setup.

**Comment by bisegni** [comment]
thank you

**Comment by nitisht** [comment]
closing this as working as intended
