### ISSUE TITLE
multipart upload error with cohesity

### ISSUE THREAD

**Issue by sc00byy** [minio/minio#8133]
I'm using an S3 bucket with Cohesity appliance.  I'm getting an issue that Cohesity is jamming. 
 With support, we are trying to pinpoint the problem.  After some check with them, they traced the following behavior in logs:

bridge_exec.ERROR:E0821 17:23:15.188688 181295 curl_http_rpc_executor.cc:226] Response for the failed RPC: 10421 is <?xml version="1.0" encoding="UTF-8"?>
bridge_exec.ERROR-<Error><Code>NoSuchUpload</Code><Message>The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.</Message><Key>cohesity_icebox_data/7055675740745988/1531233182148/471685_543895_3178641156_3200803029_1566055605111693_v2</Key><BucketName>cohesity</BucketName><Resource>/cohesity/cohesity_icebox_data/7055675740745988/1531233182148/471685_543895_3178641156_3200803029_1566055605111693_v2</Resource><RequestId>15BD16DF9D05A680</RequestId><HostId>1b0a3fb8-e430-4a4e-bcfb-b3ad7f84c94d</HostId></Error>
--
bridge_exec.ERROR:E0821 17:23:15.274554 181312 curl_http_rpc_executor.cc:226] Response for the failed RPC: 38825 is <?xml version="1.0" encoding="UTF-8"?>
bridge_exec.ERROR-<Error><Code>NoSuchUpload</Code><Message>The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.</Message><Key>cohesity_icebox_data/7055675740745988/1531233182148/286764_432555_2959593597_3171354499_1565841163660399_v2</Key><BucketName>cohesity</BucketName><Resource>/cohesity/cohesity_icebox_data/7055675740745988/1531233182148/286764_432555_2959593597_3171354499_1565841163660399_v2</Resource><RequestId>15BD16DF9FB751E1</RequestId><HostId>1b0a3fb8-e430-4a4e-bcfb-b3ad7f84c94d</HostId></Error>
--
bridge_exec.ERROR:E0821 17:23:15.326936 181315 curl_http_rpc_executor.cc:226] Response for the failed RPC: 38831 is <?xml version="1.0" encoding="UTF-8"?>
bridge_exec.ERROR-<Error><Code>NoSuchUpload</Code><Message>The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.</Message><Key>cohesity_icebox_data/7055675740745988/1531233182148/286764_432555_2959593597_3170784204_1565833975942469_v2</Key><BucketName>cohesity</BucketName><Resource>/cohesity/cohesity_icebox_data/7055675740745988/1531233182148/286764_432555_2959593597_3170784204_1565833975942469_v2</Resource><RequestId>15BD16DFA3DCFA45</RequestId><HostId>1b0a3fb8-e430-4a4e-bcfb-b3ad7f84c94d</HostId></Error>
--
bridge_exec.ERROR:E0821 17:23:15.402143 181347 curl_http_rpc_executor.cc:226] Response for the failed RPC: 38832 is <?xml version="1.0" encoding="UTF-8"?>
bridge_exec.ERROR-<Error><Code>InvalidPart</Code><Message>One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part&#39;s entity tag.</Message><Key>cohesity_icebox_data/7055675740745988/1531233182148/286760_329697_2955169177_3174825767_1565910630847078_v2</Key><BucketName>cohesity</BucketName><Resource>/cohesity/cohesity_icebox_data/7055675740745988/1531233182148/286760_329697_2955169177_3174825767_1565910630847078_v2</Resource><RequestId>15BD16DFA384D59F</RequestId><HostId>1b0a3fb8-e430-4a4e-bcfb-b3ad7f84c94d</HostId></Error>

Is there anyone here that his also using Cohesity with Minio?  Are you also getting this kind of error message?  Have you open up a case with them?

My Environment
* Version used (`minio version`): 
Version: 2019-06-15T23:07:18Z
Release-Tag: RELEASE.2019-06-15T23-07-18Z
Commit-ID: 99bf4d0c429f04dbd013ba98840d07b759ae1702

* Server type and version:  
Freenas 11.2-U5
* Operating System and version (`uname -a`):
FreeBSD 11.2-STABLE FreeBSD 11.2-STABLE #0 r325575+6aad246318c(HEAD): Mon Jun 24 17:25:47 UTC 2019     root@nemesis:/freenas-releng/freenas/_BE/objs/freenas-releng/freenas/_BE/os/sys/FreeNAS.amd64  amd64

Regards,

**Comment by harshavardhana** [comment]
@sc00byy we have been able to reproduce this as well - thanks for opening the bug.

**Comment by harshavardhana** [comment]
> bridge_exec.ERROR:E0821 17:23:15.402143 181347 curl_http_rpc_executor.cc:226] Response for the failed RPC: 38832 is 
> bridge_exec.ERROR-`InvalidPart`One or more of the specified parts could not be found. The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.cohesity_icebox_data/7055675740745988/1531233182148/286760_329697_2955169177_3174825767_1565910630847078_v2cohesity/cohesity/cohesity_icebox_data/7055675740745988/1531233182148/286760_329697_2955169177_3174825767_1565910630847078_v215BD16DFA384D59F1b0a3fb8-e430-4a4e-bcfb-b3ad7f84c94d

The real issue is this.

**Comment by harshavardhana** [comment]
Fixed by #8142
