### ISSUE TITLE
GUI does not seem to support Proxying under Sub-Path

### ISSUE THREAD

**Issue by vanthome** [minio/minio#8134]
**Is your feature request related to a problem? Please describe.**
I have tried to proxy minio using the following Nginx config (extracted from several other issues):

```
    location /admin/minio/ {
        proxy_pass http://minio1:9000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_cache_bypass $http_upgrade;
        proxy_ignore_client_abort on;

        # forward headers
        proxy_buffering off;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
```

But whatever setting I try, I get this when accessing the URL `/admin/minio/` in the browser.

```
<Error>
<Code>InvalidRequest</Code>
<Message>
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
</Message>
<Resource>/minio/</Resource>
<RequestId/>
<HostId>5f474dcf-7a73-42b6-875e-67ad448494b1</HostId>
</Error>
```

I don't know why it does not work as expected but other such tools respect `X-Forwarded-For`  and support being proxied under sub-paths.

**Describe the solution you'd like**
The GUI should be proxy aware.

**Comment by harshavardhana** [comment]
This is working as expected as per design, you are not allowed to change sub-paths @vanthome - you shouldn't add things like `location /admin/minio` and rewrite the requests.

**Comment by nitisht** [comment]
closing as working as intended

**Comment by vanthome** [comment]
ok, any statement as to why this is suppressed?

**Comment by harshavardhana** [comment]
Because in AWS S3 you cannot change the path on the fly, path is encoded as part of the signature. Sub-path based approach may work in certain situations but it is not recommended and it will fail in unforseen ways.

**Comment by vanthome** [comment]
ok, understdood, thx.
