### ISSUE TITLE
Need Sets to have a unique identifier

### ISSUE THREAD

**Issue by dvaldivia** [minio/minio#8137]
Currently `mc admin info server play` returns a list of lists for sets inside `storage.backend.sets`, it would be useful to keep track of a set if the set had a unique identifier (uuid) for scenarios such as when a set was healed, it'd be possible to track via it's uuid on the logs.

Current set information:
```
"sets": [
    [
     {
      "uuid": "7be2d265-7e8e-46e7-8ac2-986035f08237",
      "endpoint": "/home/play/data1",
      "state": "ok"
     },
     {
      "uuid": "ee4f05f1-57f8-4adf-b158-155c98608e10",
      "endpoint": "/home/play/data2",
      "state": "ok"
     },
     {
      "uuid": "7e7af70a-814f-4594-a52e-dbc6251f99cd",
      "endpoint": "/home/play/data3",
      "state": "ok"
     },
     {
      "uuid": "80cb0bba-73cd-4214-a769-80bdf1916b49",
      "endpoint": "/home/play/data4",
      "state": "ok"
     }
    ]
   ]
```

Desired set information:
```
  "sets" : [
    {
      "disks" : [
        {
          "state" : "ok",
          "endpoint" : "/home/play/data1",
          "uuid" : "7be2d265-7e8e-46e7-8ac2-986035f08237"
        },
        {
          "state" : "ok",
          "endpoint" : "/home/play/data2",
          "uuid" : "ee4f05f1-57f8-4adf-b158-155c98608e10"
        },
        {
          "state" : "ok",
          "endpoint" : "/home/play/data3",
          "uuid" : "7e7af70a-814f-4594-a52e-dbc6251f99cd"
        },
        {
          "state" : "ok",
          "endpoint" : "/home/play/data4",
          "uuid" : "80cb0bba-73cd-4214-a769-80bdf1916b49"
        }
      ],
      "uuid" : "80cb0cca-84cd-1245-b769-80bdf1916b55"
    }
  ]
```
Alternative we would need a warranty that the set order will never change, but keeping track of changes on the cluster such a healing a set would be hard for monitoring tools.

**Comment by harshavardhana** [comment]
Sets don't need a unique identifier, sets are floating @dvaldivia a set is simply an index like 

0th index is first set
1st index is second set and so on.

**Comment by harshavardhana** [comment]
Also set order will never change because of `format.json` which captures the set information as it is presented in the output here. @dvaldivia - it is also the reason why a Set is a two-dimensional array

**Comment by dvaldivia** [comment]
So if a set is healed how will this be reported in the logs in a way that can be co-related to the existing sets? I guess something like `deployment_id-server_address-server_index` would need to be reported

**Comment by harshavardhana** [comment]
> So if a set is healed how will this be reported in the logs in a way that can be co-related to the existing sets? I guess something like `deployment_id-server_address-server_index` would need to be reported

No there is no reason to @dvaldivia - we actively want users to not think in terms of sets - set is an internal concept - there is nothing that users need to know beyond the cluster. An object never goes beyond a set (never).  So if a disk failed we show in this output which disk failed - there is no direct relation for them in sets. 

Knowing which disk failed automatically tells them which disk they need to replace etc, showing them sets is useless information as to its meaning is only internal.

**Comment by harshavardhana** [comment]
Adding UUID to set is not useful as it's not useful for anything internally, neither does it tell users what they should do with this value.

A sets slice is nothing but a two-dimensional array of disks - each index in the set is a static value which never changes which in itself is a collection of disks. 

set itself is not unique and has no relation internally in our xl.json or objects, objects by themselves don't know which set they belong to. This information about sets is a virtual layer which is built on top of the collection of disks.

**Comment by harshavardhana** [comment]
> So if a set is healed how will this be reported in the logs in a way that can be co-related to the existing sets? I guess something like `deployment_id-server_address-server_index` would need to be reported

All that our users need to know is did all my objects are healed or not - did my set got healed is never useful because S3 APIs don't have any such relationship for a given object.  Like it would make sense if while doing Put() you choose which set to put the object in. That is not how it is implemented, which set is chosen is automatic based on the object name and users have no idea where the object exists - this information is never presented as per design.

Adding UUID will have other challenges such as migration of existing `format.json` and also making sure to preserve the order during migration - as Go map's don't preserve the order. So we need to save that indirection somewhere. 

Slice is used simply because it preserves the order and set by itself is a virtualized concept

So IMO there is no value in saving sets information as UUID.

On the other hand, you can open an issue in `mc`- where `mc admin info` can present this value in a more meaningful way - such as providing Sets() as a mapped value of key value.

**Comment by dvaldivia** [comment]
yeah, even if the set itself becomes an object and it's `set_index` or similar is presented it would be useful.
