### ISSUE TITLE
Rclone --size-only documentation misleading.

### ISSUE THREAD

**Issue by Hermain** [minio/minio#8150]
**Is your feature request related to a problem? Please describe.**

The minio [docs](https://docs.min.io/docs/rclone-with-minio-server.html) state that:
```
MinIO doesn't support all the features of S3 yet. In particular it
doesn't support MD5 checksums (ETags) or metadata. This means Rclone
can't check MD5SUMs or store the modified date. However you can work
around this with the --size-only flag of Rclone.
```
This is misleading. The way I understood it its necessary to use --size-only for minio to work with rclone. However rclone works better without size-only.

When I change only a single byte in a file (same size) and reupload it using --size-only, the file won't change on minio, without --size-only it is correctly updated.
 
**Describe the solution you'd like**
--size-only is not recommended anymore 

**Describe alternatives you've considered**
The documentation explains more clearly in which situation --size-only should be used

**Comment by kannappanr** [comment]
@Hermain Please feel free to send a PR

**Comment by Hermain** [comment]
Is this documentation based on a github repo? It doesn't look like any md file.
Please share where I can change that

**Comment by nitisht** [comment]
This is the doc @Hermain https://github.com/minio/minio/blob/master/README.md

**Comment by harshavardhana** [comment]
The doc to fix is this https://github.com/minio/cookbook/blob/master/docs/rclone-with-minio.md
