### ISSUE TITLE
Problem On Heal

### ISSUE THREAD

**Issue by Haazeel** [minio/minio#8151]
## Expected Behavior

We have lost a disk, during 2 days we have continues without.
We have mount a other disk for back a the normal et launch the command "mc admin heal -r myminio " for try reconstruct the disk (250G), and continues to use the cluster minio.

After end of command, we notes that miss bucket and the disk size are at (8G).
We try a other heal but now an error messages appear:

mc: <ERROR> Failed to start heal sequence. The provided heal sequence path overlaps with an existing heal path: 
 (0) admin-heal.go:231 cmd.mainAdminHeal(..)

Can you explain the error and may be help us for resolve?

## Steps to Reproduce (for bugs)

1. lost disk and mount 
2. launch "mc admin heal myminio"
3. use during process
4. 

## Your Environment

* Version used (`minio version`):
Release-Tag:RELEASE.2019-08-07T23-14-43Z | Commit:fef437bdd6bd |
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux
* Link to your project:

**Comment by nitisht** [comment]
looks like initial heal did not complete @Haazeel , error message is simply conveying that you have a heal process already running

**Comment by Haazeel** [comment]
Ok thank you, I have see with my colleague.

Sorry for the inconvenience and thank for your speed and sympathy.
