### ISSUE TITLE
High disk IO consumption

### ISSUE THREAD

**Issue by kaxap** [minio/minio#8152]
Minio has been deployed on 8 servers with 128 GB RAM and 32 cores (16 virtual) with 5x 7200 SATA HDDs in RAID 0. A stream of small files (7-15KB) are continuously fed to the cluster at rate of 15-20 files per second.

## Expected Behavior
Files are ingested at fast pace. Comparatively low latency of file read (0-2 sec)

## Current Behavior
Due to high disk IO consumption (screen from iotop attached) operations like making HTTP request to the web frontend and downloading files take up to 180 seconds.

![image](https://user-images.githubusercontent.com/2851970/63949252-eb6c5d80-ca9b-11e9-946e-cb8bb0183e48.png)

## Possible Solution
IMO the high number of goroutines each with small disk IO throughput suggest a problem involving IO competition. At some point increase in number of goroutines leads to IO performance degradation and as a consequence more time is needed to perform IO operation which leads to more goroutines running simultaneously and even higher IO congestion rates.

Reduce (or make it configurable) the number of goroutines simultaneously writing to the disk, since HDD disks have poor performance on random IO. 

## Steps to Reproduce (for bugs)
1. Deploy Minio on 8 servers with 7200 RPM HDD
2. Write small files continuously at rate of 15-20 files per second for a prolonged period of time (or at least a couple of days)
3. Check disk IO with iotop

## Context
We are storing continuous image feed from low FPS webcameras for post processing and historical needs.

## Regression
This problem is not a regression.

## Your Environment
```
Version: 2019-05-02T19:07:09Z
Release-Tag: RELEASE.2019-05-02T19-07-09Z
Commit-ID: 4b858b562a0887e10bfd0414dc87e68f1af31c3a
```
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:  CPU 2x E5-2620v4, 128 GB RAM, 5x 2TB 7200 RPM HDD in RAID 0
* Operating System and version (`uname -a`): 4.4.0-145-generic #171-Ubuntu SMP Tue Mar 26 12:43:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Two things architecturally you need

- For such small files you should be using SSD for performance,
- You should provide MinIO the disks directly and remove RAID 0.

**Comment by kaxap** [comment]
The high disk IO consumption continues even when the writing process has been stopped.

**Comment by kaxap** [comment]
> * For such small files you should be using SSD for performance,

The max throughput is 300 KB per second (+ fraction of this for the erasure code), why is it necessary to have SSD for such low write rate?

> * You should provide MinIO the disks directly and remove RAID 0.

Apologies, could you please clarify on this?

**Comment by harshavardhana** [comment]
RAID0 is useless with MinIO, controllers come in the way. MinIO should be given the disks directly that is our recommended architecture.

No matter what to reduce random I/O for small files you shall be using SSD. Also file sizes such as 5k are not well suited for MinIO - you should pack them into larger objects and upload from the client.

**Comment by harshavardhana** [comment]
Also how did you store these files? Did you dump objects directly at bucket level or is there a proper heirarchy ?

**Comment by kaxap** [comment]
> Also how did you store these files? Did you dump objects directly at bucket level or is there a proper heirarchy ?

yes, there is a proper hierarchy

**Comment by harshavardhana** [comment]
How many files do you have right now ? Can you perform some disk numbers for me using dd command `dd if=/dev/zero of=file bs=16k count=10240 oflag=direct` ?

**Comment by ghost** [comment]
https://github.com/minio/minio/issues/8071

"The high disk IO consumption continues even when the writing process has been stopped."

The same happens with my case. Using `mc admin trace -a` and `tcpdump` I can see lots of `internal.ReadAll` and `internal.StatsFile` requests going on when all the clients have been taken out (by shutting down our reverse proxy). This seems to be part of the normal healing process `daily-sweep`. According to file lock it has been going on for 23 hour.  For our cluster there are also ~1700 and ~2000 `minio` threads running on the two nodes. When even part of them are doing disk io on the rotating disks, this surely leads to high iowait.

**Comment by harshavardhana** [comment]
To be fixed in https://github.com/minio/minio/pull/8209 @markkutikkanen @kaxap

**Comment by harshavardhana** [comment]
Closing as duplicate of #8071
