### ISSUE TITLE
minio not listing all files stored

### ISSUE THREAD

**Issue by svistoi** [minio/minio#8154]
mc ls and mc du is not showing all the files

## Expected Behavior
mc ls to show all files

## Current Behavior
When I do `mc ls` or `mc du` the reported number of files (202, 34MiB) in the bucket is significantly smaller than the number that was copied and stored on 4-node minio cluster.

When I go to the filesystem for individual minio instance and do ls/du I get 11384 items, 5480 MB.

I identified itemA (not actual name) on the filesystem that's not displayed by `mc ls`.  itemA does not contain special characters - all appear to be within ASCII range.

`mc ls myserver mybucket/itemA` returns nothing.  However `mc cp myserver mybucket/itemA ~/itemA` copies the file and it appears to be uncorrupted.

## Steps to Reproduce (for bugs)
This is difficult to describe, I've been running this cluster for a while, upgrading to new releases.    Releases marked as "no rolling update", I've been destroying all instances and re-creating new versions.  I can't trace back to when problem started occurring or why.

## Your Environment
* minio 2019-08-29T00:25:01Z
* mc version RELEASE.2019-08-29T00-40-57Z
* Kubernetes 1.14.3, NFS persistent volume for minio

**Comment by harshavardhana** [comment]
are you running Minio distributed on top of NFS? @svistoi

**Comment by svistoi** [comment]
@harshavardhana Yes

**Comment by harshavardhana** [comment]
@svistoi that is not recommended, NFS is notorious for being commonly inconsistent we write

- O_SYNC for xl.json
- O_DIRECT for data 

Both of them are hardly supported or incorrectly implemented in NFS. It is better to use local disks with XFS.

You may be running the cluster for a while but we would never recommend running this over NFS, and you should never do that.

**Comment by svistoi** [comment]
@harshavardhana  I see.  Thank you for the suggestion.

Is there some validation I can do on xl.json metadata for files that are not displayed as part of `mc ls`?  The `mc cp` behavior I described suggests that minio can return the file, and that it's not corrupt.

Is there an index or do the minio instances re-query metadata reply to `mc ls`?

On a slightly separate note
`mc admin info server myserver` shows all instances up. 

For each pod
`time -f"%e" kubectl exec pod/minio-0 -- ls /data/mybucket | wc -l` lists the ~11k files in reasonable time of ~0.38 seconds

**Comment by harshavardhana** [comment]
As I said NFS has issues, you shouldn't run another NAS product on top of another NAS product - you are prone to issues and it will never work properly.

**Comment by harshavardhana** [comment]
Closing this issue as non-actionable for us - NFS shouldn't be used as a backend for distributed setup,  it is well suited to be used as `minio gateway nas` instead.

**Comment by Aronabv** [comment]
@harshavardhana - I face same issue. Even when changing to `minio gateway nas` still receive 202 files. Do you have any idea why?

**Comment by svistoi** [comment]
@Aronabv I moved the files from NFS to XFS, pointed 4 minio instances to the 4 sets and tested that.  Those instances backed by XFS were showing all files.  So it does seem NFS related.  And my suggestion is to move to XFS to get your data back.

However I'm not sure specifically what it is about O_SYNC and O_DIRECT used for write, that interferes with the read.

**EDIT** Sorry I misread your message.  My comment is unrelated to minio gateway nas.

**Comment by harshavardhana** [comment]
@svistoi listing had a bug which is fixed already in the last couple of releases.  

@Aronabv please open a new issue. This issue is not related.
