### ISSUE TITLE
Can't add config.json file for MINIO Server which is a docker image deployed into Kubernetes.

### ISSUE THREAD

**Issue by rjshree** [minio/minio#8160]
I'm trying to add rabbitmq server details in the config.json file of Minio Server. I got to know I have to create one.

Version Details:
Version: 2019-08-29T00:40:57Z
Release-tag: RELEASE.2019-08-29T00-40-57Z
Commit-id: bd7564a2d4524335a594f0f4e10b06c033eb299c

Command I used to create config.json:
mc admin config set minio < /tmp/my-serverconfig
Setting new MinIO configuration file has been successful.
Please restart your server with `mc admin service restart minio`.

Command I used to restart server:
>mc admin service restart minio
mc: <ERROR> Cannot restart the server. The request body failed to parse.

Could anyone please help me to configure Minio Server to add rabbitmq server details?

Thanks in Advance

**Comment by kannappanr** [comment]
@rajashreetutgirl PTAL https://docs.min.io/docs/minio-server-configuration-guide.html You need to get the current config first, then modify it and set it. Please look at https://docs.min.io/docs/minio-bucket-notification-guide#AMQP for more details.

**Comment by harshavardhana** [comment]
Once server is upgraded , you need to upgrade mc as well @rajashreetutgirl

**Comment by rjshree** [comment]
>mc admin config get minio/ > /tmp/myconfig
mc: <ERROR> Cannot get server configuration file. We encountered an internal error, please try again.

**Comment by rjshree** [comment]
Also when I ran kubectl logs for my minio pod, I'm getting below error logs.  I am new to Minio. ANy leads would be helpful. Thanks in Advance!!

API: GetConfigHandler()
Time: 16:50:18 UTC 08/31/2019
DeploymentID: bd85de5d-aa3f-4ced-b148-ce4e395fe20a
RequestID: 15C00FF5A517C696
RemoteHost: 10.233.87.0
Host: 10.12.40.161:31265
UserAgent: MinIO (windows; amd64) madmin-go/0.0.1 mc/2019-08-29T00:40:57Z
Error: invalid character 'e' after object key:value pair
       5: cmd/api-errors.go:1692:cmd.toAPIErrorCode()
       4: cmd/admin-handlers.go:952:cmd.toAdminAPIErrCode()
       3: cmd/admin-handlers.go:957:cmd.toAdminAPIErr()
       2: cmd/admin-handlers.go:834:cmd.adminAPIHandlers.GetConfigHandler()
       1: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()

**Comment by rjshree** [comment]
I wanted to create notification event to send message to rabbitmq. It gives no error as well could not be consumed. Same Rabbitmq pod I created standalone publisher to send message. It can consumed by consumer. But the notification is not at all being sent. I think my config changes are not reflecting.

Consumer Code:
import pika

connection = pika.BlockingConnection(pika.ConnectionParameters(
        host='localhost'))
channel = connection.channel()

channel.exchange_declare(exchange='bucketevents',
                         exchange_type='fanout')

result = channel.queue_declare(queue='bucketlogs',exclusive=False)
queue_name = result.method.queue
print('q name', queue_name)
channel.queue_bind(exchange='bucketevents', routing_key='bucketlogs',
                   queue=queue_name)

print(' [*] Waiting for logs. To exit press CTRL+C')

def callback(ch, method, properties, body):
    print(" [x] %r" % body)

channel.basic_consume(queue_name, callback, auto_ack=True,)

channel.start_consuming()

**Comment by nitisht** [comment]
can you paste the `config.json` file you're trying to set? Looks like it has some invalid cahracters

**Comment by rjshree** [comment]
@nitisht 

Please find my config.json and please do let me know if any invalid characters are there:
```json
{
	"version": "33",
	"credential": {
		"accessKey": "minio",
		"secretKey": "minio123",
		"expiration": "1970-01-01T00:00:00Z",
		"status": "enabled"
	},
	"region": "",
	"worm": "off",
	"storageclass": {
		"standard": "",
		"rrs": ""
	},
	"cache": {
		"drives": [],
		"expiry": 90,
		"maxuse": 80,
		"exclude": []
	},
	"kms": {
		"vault": {
			"endpoint": "",
			"auth": {
				"type": "",
				"approle": {
					"id": "",
					"secret": ""
				}
			},
			"key-id": {
				"name": "",
				"version": 0
			}
		}
	},
	"notify": {
		"amqp": {
			"1": {
				"enable": true,
				"url": "amqp://user:ir9mqmXlGi@rabbitmq-headless.edisonai-brahmos:5672",
				"exchange": "bucketevents",
				"routingKey": "bucketlogs",
				"exchangeType": "fanout",
				"deliveryMode": 0,
				"mandatory": false,
				"immediate": false,
				"durable": false,
				"internal": false,
				"noWait": false,
				"autoDeleted": false,
				"queueDir": "",
				"queueLimit": 0
			}
		},
		"elasticsearch": {
			"1": {
				"enable": false,
				"format": "",
				"url": "",
				"index": "",
				"queueDir": "",
				"queueLimit": 0
			}
		},
		"kafka": {
			"1": {
				"enable": false,
				"brokers": null,
				"topic": "",
				"queueDir": "",
				"queueLimit": 0,
				"tls": {
					"enable": false,
					"skipVerify": false,
					"clientAuth": 0
				},
				"sasl": {
					"enable": false,
					"username": "",
					"password": ""
				}
			}
		},
		"mqtt": {
			"1": {
				"enable": false,
				"broker": "",
				"topic": "",
				"qos": 0,
				"username": "",
				"password": "",
				"reconnectInterval": 0,
				"keepAliveInterval": 0,
				"queueDir": "",
				"queueLimit": 0
			}
		},
		"mysql": {
			"1": {
				"enable": false,
				"format": "",
				"dsnString": "",
				"table": "",
				"host": "",
				"port": "",
				"user": "",
				"password": "",
				"database": "",
				"queueDir": "",
				"queueLimit": 0
			}
		},
		"nats": {
			"1": {
				"enable": false,
				"address": "",
				"subject": "",
				"username": "",
				"password": "",
				"token": "",
				"secure": false,
				"pingInterval": 0,
				"queueDir": "",
				"queueLimit": 0,
				"streaming": {
					"enable": false,
					"clusterID": "",
					"async": false,
					"maxPubAcksInflight": 0
				}
			}
		},
		"nsq": {
			"1": {
				"enable": false,
				"nsqdAddress": "",
				"topic": "",
				"tls": {
					"enable": false,
					"skipVerify": false
				},
				"queueDir": "",
				"queueLimit": 0
			}
		},
		"postgresql": {
			"1": {
				"enable": false,
				"format": "",
				"connectionString": "",
				"table": "",
				"host": "",
				"port": "",
				"user": "",
				"password": "",
				"database": "",
				"queueDir": "",
				"queueLimit": 0
			}
		},
		"redis": {
			"1": {
				"enable": false,
				"format": "",
				"address": "",
				"password": "",
				"key": "",
				"queueDir": "",
				"queueLimit": 0
			}
		},
		"webhook": {
			"1": {
				"enable": false,
				"endpoint": "",
				"queueDir": "",
				"queueLimit": 0
			}
		}
	},
	"logger": {
		"console": {
			"enabled": true
		},
		"http": {
			"target1": {
				"enabled": false,
				"endpoint": "https://username:password@example.com/api"
			}
		}
	},
	"compress": {
		"enabled": false,
		"extensions": [
			".txt",
			".log",
			".csv",
			".json"
		],
		"mime-types": [
			"text/csv",
			"text/plain",
			"application/json"
		]
	},
	"openid": {
		"jwks": {
			"url": null
		}
	},
	"policy": {
		"opa": {
			"url": null,
			"authToken": ""
		}
	}
}
```

**Comment by nitisht** [comment]
config looks fine @rajashreetutgirl do you mind joining us on Slack (https://slack.min.io) so we can discuss real time and fix this quickly.

**Comment by rjshree** [comment]
Sure @nitisht . When can i join?

**Comment by kannappanr** [comment]
@rajashreetutgirl I see that you have joined general channel on slack. You can ping us over there and we would be happy to help you. FYI, I tried the exact config file that you pasted here and that worked, except that it threw some error regarding the `amqp` server being not reachable, which is expected

**Comment by nitisht** [comment]
Closing this for now due to no response, please reopen if you have further inputs
