### ISSUE TITLE
Error: error in sending event

### ISSUE THREAD

**Issue by dcharbonnier** [minio/minio#8162]
There is no notification setup on this server and this server is not a cluster

Config https://gist.github.com/dcharbonnier/b35b956a54b467f32f09b78ab38ca3c1
Version : minio/minio:RELEASE.2019-08-29T00-25-01Z
Command: server /export

We have a lot of errors :
```
API: SYSTEM(bucket=registry, object=docker/registry/v2/repositories/xxx/_uploads/c440654a-d697-4ed2-a4f6-80cc094ae91a/hashstates/sha256/66650466)
Time: 13:58:07 UTC 08/30/2019
DeploymentID: bb1469f0-b1ef-4a84-99f1-d0917dc8385e
Error: error in sending event
       EventName=s3:ObjectCreated:Put, targetID=30499
       3: cmd/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()
       2: cmd/logger/logonce.go:80:logger.LogOnceIf()
       1: cmd/notification.go:1166:cmd.sendEvent.func1()
```

In the end the docker private registry is not able to push the images anymore and restarting only minio fix the issue of the registry (3 times today). I'm not able to tell at this point of I can PUT objects at different url or if only those objects are "locked".
The problem of minio not working anymore may not be related to those error messages but without anything setup for notifications it looks like an issue anyway.

**Comment by dcharbonnier** [comment]
we have a `mc mirror --remove --json -w source/$SOURCE_BUCKET target/$TARGET_BUCKET;` running that explain the fact that something is listening to the notifications probably

**Comment by harshavardhana** [comment]
Since you have --watch it is listening for events..
