### ISSUE TITLE
minIO server writes to deprecated `$HOME/.minio`

### ISSUE THREAD

**Issue by fahrradflucht** [minio/minio#8163]
## Expected Behavior
minIO server shouldn't write to `$HOME/.minio` since the `--config-dir` is deprecated.

## Current Behavior
On server startup minIO tries to write to `$HOME/.minio/config.json`. If it can't it exits with the following message.

```
ERROR Unable to initialize config system: Insufficient permissions to access path, `/home/minio/.minio/config.json`
```

If `$HOME/.minio` isn't writable, this forces the deprecated `--config-dir` flag to be used.

## Steps to Reproduce
1. `useradd -M -r minio`
2. `su minio`
3. `minio server data`

## Your Environment
* Version used (`minio version`):
```
Version: 2019-08-29T00:25:01Z
Release-Tag: RELEASE.2019-08-29T00-25-01Z
Commit-ID: eb18c82976251d9a0c0730df27e10204c89beae2
```
* Operating System and version (`uname -a`):
```
Linux 5.2.9-200.fc30.x86_64
```

**Comment by harshavardhana** [comment]
It migrates your existing config.json - it is actually failing for the stat operation here.

**Comment by harshavardhana** [comment]
This issue is fixed and PR is merged already.
