### ISSUE TITLE
`--json` CI Arg does auto enable quite mode.

### ISSUE THREAD

**Issue by LostKobrakai** [minio/minio#8170]
## Expected Behavior

`minio --json server $PATH` should output startup information in json format.

## Current Behavior

The `--json` flag does also contrary to it's CLI docs enable quiet mode.

## Possible Solution

https://github.com/minio/minio/blob/master/cmd/logger/logger.go#L121-L124
Do not add the quiet flag here.

## Steps to Reproduce (for bugs)

1. Run `minio --json server $PATH`
2. Miss startup information

## Context

I'd like to automate starting up minio from a language binding where not having to parse the startup information from plain strings would be very nice.

## Your Environment

* Version used (`minio version`): 2019-08-29T00:25:01Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by kannappanr** [comment]
@LostKobrakai Can you tell us what information you want to parse that is displayed in the CLI output?

**Comment by LostKobrakai** [comment]
I've now gone ahead and defined it explicitly when starting minio, but I was looking for the endpoint information as well as the secrets.

**Comment by kannappanr** [comment]
The idea in not displaying that information is that `json` mode will be the one used in scripts and we did not want to display secrets and other info that doesn't change on every startup. Closing this issue for now. Please let us know if this needs to be looked at again.

**Comment by LostKobrakai** [comment]
> and we did not want to display secrets and other info that doesn't change on every startup.

That's what `--quiet` is for though. If the default is the problem than there should at least be a way to opt into showing those information imo.

If you really don't want to change the implementation at least the cli help documentation should be adjusted to document the behaviour. Currently it mentions that both logs and startup information will be shown in json format.
