### ISSUE TITLE
Administrative users

### ISSUE THREAD

**Issue by arouene** [minio/minio#8172]
## Expected Behavior
It's probably a feature request or an information request if it's already exists.

Have a mean to create an **administrative user** that are able to create users for specific buckets or set a user's policy without knowing the access_key.

## Current Behavior
Today, you can only create users with an access_key.

## Steps to Reproduce (for bugs)
1. Create a user with fullaccess policy
2. Register the bucket in **mc** with the user as AccessKey, the password as SecretKey
3. Try to create a user with **mc** to the new bucket
4.

## Context
Try to give partial administrative rights without giving the Access Keys.

## Regression
No

## Your Environment

* Version used (`minio version`): 2019-07-03T18:14:53Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: Azure Storage as bucket S3
* Operating System and version (`uname -a`): Minio in Docker
* Link to your project:

**Comment by harshavardhana** [comment]
There is only one MinIO admin with admin API access - we wish to keep that scope limited. Root credential is always one. 

We already have a concept of groups, users and policies. You should upgrade to latest to get these features.

**Comment by arouene** [comment]
Ok, so if I understand, to create users we must have the Access Key of the storage account (for Azure storage account backend) ? Correct me if I'm wrong.

I will close the "issue" if it's the intended behavior. Thank you.

**Comment by harshavardhana** [comment]
> Ok, so if I understand, to create users we must have the Access Key of the storage account (for Azure storage account backend) ? Correct me if I'm wrong.

Azure backend is a gateway - what I am actually talking about is server mode here @arouene . In case of gateway the root credential is the same one that used to talk to the backend.
