### ISSUE TITLE
UI Upload issues on federation setup

### ISSUE THREAD

**Issue by imrane2e** [minio/minio#8173]
we have a federated setup with 2 clusters with a 3 node Etcd setup. 

## Expected Behavior
uploads and list items should work on both UI and mc

## Current Behavior
- On any upload of an item on minio webUI, it shows a message of file uploaded successfully, but the item doesnt get listed on the UI
- The uploads and listing happen normally over mc 

## Steps to Reproduce (for bugs)
- Login to any of the clusters over the UI and use the upload feature to select a file to upload
- The message `File '<name>' uploaded successfully` gets displayed
- The uploaded file or folder doesn't get listed

## Context
- we are trying to setup a federated cluster

## Your Environment
* Minio - 2019-08-29T00:25:01Z
* CentOS Linux release 7.6.1810 (Core)
* Linux 3.10.0-957.12.1.el7.x86_64 #1 SMP Mon Apr 29 14:59:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nitisht** [comment]
Thanks @imrane2e we’ll take a look soon.
