### ISSUE TITLE
A very high number of buckets causes very slow performance in the UI

### ISSUE THREAD

**Issue by kanadaj** [minio/minio#8181]
Due to certain reasons, we have deployed minio on our production Kubernetes system as we migrated away from our previous cloud provider. Due to configuration reasons and the legacy setup, we ended up with several thousand buckets on minio. The server handles this just fine, however, the web UI struggles badly since it loads the full list of the buckets.

## Expected Behavior
Ideally, a paged list of buckets in the sidebar or simply a maximum limit to the number of loaded buckets would be what I expect to make the system responsive even in such a setup.

## Current Behavior
The UI loads all the buckets, then freezes or outright crashes.

## Steps to Reproduce (for bugs)
1. Create a new Minio server
2. Create 5000 buckets, though it might work with way less to reproduce
3. Load the Web UI

## Regression
No, I don't believe so

## Your Environment

* Version used (`minio version`): latest on docker hub at the time of this post
* Environment name and version (e.g. nginx 1.9.1): Openshift Origin 3.11, CentOS 7 but not really relevant to the issue

**Comment by nitisht** [comment]
@kanadaj we'll take a look
