### ISSUE TITLE
How to repair a broken node

### ISSUE THREAD

**Issue by wlwcjl** [minio/minio#8182]
I have a distributed cluster with 4 nodes. After a node was taken out of service and had its volume wiped, when i start the cluster, the console shows the message that unformatted disk found,how do i repaire the broken node? help me, please, thank you!

**Comment by harshavardhana** [comment]
`mc admin heal -r myminio`

**Comment by wlwcjl** [comment]
I  executed the command as you said,but there was nothing on my new volume, do I have to wait a long time?  thank you！ @harshavardhana

**Comment by nitisht** [comment]
`heal` gives a status banner while it is running. What do you see there @wlwcjl
