### ISSUE TITLE
AuthorizationHeaderMalformed even when the region is correct

### ISSUE THREAD

**Issue by asm582** [minio/minio#8183]
I get the exception of AuthorizationHeaderMalformed even when the region is correct. I am trying to use codalab with Django on python 2.7 which uses boto.

## Expected Behavior
I am expecting object to be downloaded from the bucket

## Current Behavior
```<Error>
<link type="text/css" id="dark-mode" rel="stylesheet" href=""/>
<style type="text/css" id="dark-mode-custom-style"/>
<Code>AuthorizationHeaderMalformed</Code>
<Message>
The authorization header is malformed; the region is wrong; expecting 'us-east-1'.
</Message>
<Key>dataset_data_file/None/a4d2a/something.txt</Key>
<BucketName>private</BucketName>
<Resource>
/private/dataset_data_file/None/a4d2a/something.txt
</Resource>
<Region>us-east-1</Region>
<RequestId>15C16B683ABFD491</RequestId>
<HostId>6faeded5-5cf3-4133-8a37-07c5d500207c</HostId>
</Error>```



## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used (`minio version`): MinIO/RELEASE.2019-08-29T00-25-01Z
* Environment name and version (e.g. nginx 1.9.1): platform linux2 -- Python 2.7.16  django-2.9.1
* Server type and version: Macbook pro
* Operating System and version (`uname -a`): docker container running linux

**Comment by kannappanr** [comment]
@asm582 Don't have much information here to repro the issue. One thing that can be done is to use latest `minio` and `mc`.

Once `minio` is running, make sure to run `mc admin trace -v -a <alias>` and make sure that you are capturing the logs printed there when you are seeing this error

**Comment by kannappanr** [comment]
ping @asm582

**Comment by kannappanr** [comment]
@asm582 Closing this for now. Please feel free to reach out to us when you have the requested info.

**Comment by asm582** [comment]
@kannappanr  Thanks for reaching out. I am using codalab with minIO. I got the above error when trying to store files on the object store. I will post more details soon.
