### ISSUE TITLE
Unable to load certificate after docker run for the minio/mint:latest

### ISSUE THREAD

**Issue by lirany1** [minio/minio#8184]
```
 docker run -e SERVER_ENDPOINT=https://10.100.14.18:31311 -e ACCESS_KEY=minio \
             -e SECRET_KEY=minio123 -e ENABLE_HTTPS=1 minio/mint
```

## Current Behavior

```
unable to load certificate
139814423496344:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:701:Expecting: TRUSTED CERTIFICATE
```

## Your Environment
under gravity shell 
Edition:        open-source
Version:        5.5.8
Git Commit:     699557029db3d1d9523be3cba92bd3303d411fb2
Helm Version:   v2.12
tiller-app:5.5.2
kubernetes:5.5.8 

* Version used (`minio version`):
minio version
Version: 2019-08-07T01:59:21Z
Release-Tag: RELEASE.2019-08-07T01-59-21Z
Commit-ID: 930943f058f01f37cfbc2265d5f80ea7026ec55d

* Operating System and version (`uname -a`):
my host and gravity run on:
Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
This should be just

```
docker run -e SERVER_ENDPOINT=10.100.14.18:31311 -e ACCESS_KEY=minio \
             -e SECRET_KEY=minio123 -e ENABLE_HTTPS=1 minio/mint:edge
```

latest image is hardly updated .

**Comment by lirany1** [comment]
> This should be just
> 
> ```
> docker run -e SERVER_ENDPOINT=10.100.14.18:31311 -e ACCESS_KEY=minio \
>              -e SECRET_KEY=minio123 -e ENABLE_HTTPS=1 minio/mint:edge
> ```
> 
> latest image is hardly updated .

got the same 
unable to load certificate
140663528957592:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:701:Expecting: TRUSTED CERTIFICATE

**Comment by kannappanr** [comment]
If you were to try against a trusted certificate for your MinIO deployment or run MinIO without a certificate, you will not see this issue. Please try steps listed in https://medium.com/@paraspatidar/add-self-signed-or-ca-root-certificate-in-kubernetes-pod-ca-root-certificate-store-cb7863cb3f87 and see if you can add the self signed certificate that you are using to the cert store. Closing this issue now, please feel free to reach out to us at https://slack.min.io for such questions.
