### ISSUE TITLE
read: connection reset by peer

### ISSUE THREAD

**Issue by wlwcjl** [minio/minio#8192]
read: connection reset by peer

## Expected Behavior
When I tested 10 people uploading more than 1G files at the same time, there was an exception message'read: connection reset by peer'. I don't know what caused it. I didn't use docker deployment, but simple cluster deployment. How should I fix this problem?

I expect a lot of people to upload large files at the same time without problems.

## Current Behavior
read: connection reset by peer

## Possible Solution
mybe it‘s the network.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
Minio Distributed Storage System does not work well and will not be able to serve customers in the future

## Your Environment

* Version used (`minio version`): latest
* Environment name and version (e.g. linux CentOS 7):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by nitisht** [comment]
This is an incomplete issue @wlwcjl please fill in the issue template so we can help you. Closing this for now.

**Comment by anandsinghkunwar** [comment]
@wlwcjl Did you ever end up solving it?
