### ISSUE TITLE
unable to compile: "thrift@v0.12.0 used for two different module paths"

### ISSUE THREAD

**Issue by ManOrs88** [minio/minio#8201]
Hello,

I'm trying to compile latest release but only get the reported error

* `git pull` of latest release (commit 5bde31d021b49955d97ab84b90bd22d4e0521307)
* `go version`:
  * `go version go1.13 linux/amd64` (with explicit `GOARCH="arm"` and `GOARM="6"`)
  * `go version go1.13 linux/arm`
* OS
  * openSUSE 15.1 on amd64
  * Raspbian 10 on arm

last lines of the `GOPROXY=https://proxy.golang.org GO111MODULE=on make` output are:
> go: github.com/apache/thrift@v0.12.0 used for two different module paths (git.apache.org/thrift.git and github.com/apache/thrift)
> make: *** [Makefile:74: build] Error 1

**Comment by harshavardhana** [comment]
This shall be fixed in #8203

**Comment by harshavardhana** [comment]
Fixed in master #8203
