### ISSUE TITLE
 "Action": "s3:*" in bucket policy receives error `Policy has invalid resource`

### ISSUE THREAD

**Issue by bwitt** [minio/minio#8202]
## Expected Behavior

successfully add a policy with Action like `"Action": "s3:*",`

## Current Behavior

Receives an error: `Policy has invalid resource.`

## Possible Solution
Haven't looked into it yet

## Steps to Reproduce (for bugs)

1. ./mc mb minio/mybucket
2. create file policy.json:
```
{                                                                               
    "Version": "2012-10-17",                                                    
    "Statement": [                                                              
        {                                                                       
            "Sid": "AllowThisBucketOnly",                                       
            "Effect": "Allow",                                                  
            "Action": "s3:*",                                                   
            "Resource": [                                                       
                "arn:aws:s3:::mybucket/*",                                      
                "arn:aws:s3:::mybucket"                                         
            ]                                                                   
        }                                                                       
    ]                                                                           
}
```
3. ./mc policy set-json policy.json minio/mybucket
mc: <ERROR> Unable to set-json policy `policy.json` for `minio/mybucket`. Policy has invalid resource.

## Context
I was trying to add a policy to a bucket that allows all access to that bucket.

## Regression
Yes
Last known to work on 2017-03-16T21-50-32Z (in python using `boto3` client and `put_bucket_policy`)

## Your Environment
* Version used (`minio version`):  2019-09-05T23:24:38Z
* Environment name and version (e.g. nginx 1.9.1):  N/A
* Server type and version:  Fedora 30
* Operating System and version (`uname -a`): Linux 5.2.9-200.fc30.x86_64
* Link to your project: N/A

**Comment by bwitt** [comment]
well, actually I can't make this work using the command line client `mc`, even if I specify an `Action` like `s3:GetObject`; but setting the `Action` to `s3:GetObject` does help if I use the `boto3` python client and use `put_bucket_policy` to set the policy

**Comment by kannappanr** [comment]
@bwitt Thanks for filing the issue, we will take a look and get back to you.

**Comment by r734** [comment]
I'm also running into this. Tried to apply the following:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
        "Action": [
            "s3:PutObject",
            "s3:GetObject",
            "s3:GetObjectVersion",
            "s3:DeleteObject",
            "s3:DeleteObjectVersion"
        ],
        "Effect": "Allow",
        "Resource": [
            "arn:aws:s3:::mybucket/*"
        ],
        "Sid": ""
        }
    ]
}
```

Got `mc: <ERROR> Cannot add new policy. Policy has invalid resource.`

I'm running the Bitnami Helm chart bitnami/minio-1.2.16, which is running Minio 2019.10.02.

**Comment by kannappanr** [comment]
> I'm also running into this. Tried to apply the following:
> 
> ```json
> {
>     "Version": "2012-10-17",
>     "Statement": [
>         {
>         "Action": [
>             "s3:PutObject",
>             "s3:GetObject",
>             "s3:GetObjectVersion",
>             "s3:DeleteObject",
>             "s3:DeleteObjectVersion"
>         ],
>         "Effect": "Allow",
>         "Resource": [
>             "arn:aws:s3:::mybucket/*"
>         ],
>         "Sid": ""
>         }
>     ]
> }
> ```
> 
> Got `mc: <ERROR> Cannot add new policy. Policy has invalid resource.`
> 
> I'm running the Bitnami Helm chart bitnami/minio-1.2.16, which is running Minio 2019.10.02.

You can try something like this

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
        "Action": [
            "s3:PutObject",
            "s3:GetObject",
            "s3:DeleteObject"
        ],
"Principal": {
    "AWS": [
     "*"
    ]
   }, 
        "Effect": "Allow",
        "Resource": [
            "arn:aws:s3:::mybucket/*"
        ],
        "Sid": ""
        }
    ]
}
```

We do not support `GetObjectVersion` and `DeleteObjectVersion` APIs

**Comment by kannappanr** [comment]
> well, actually I can't make this work using the command line client `mc`, even if I specify an `Action` like `s3:GetObject`; but setting the `Action` to `s3:GetObject` does help if I use the `boto3` python client and use `put_bucket_policy` to set the policy

I don't think we support blanket `*` you might have to set individual APIs and also we might not support adding array of `ARNs` in one statement.

**Comment by harshavardhana** [comment]
Anonymous access is on purpose disabled for 's3:*' actions, so the error here is appropriate. If you need 's3:*' then you should use IAM policies to provide further restricted actions. 

Adding more elaborate error would make it more apparent here, sending a PR.

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/pull/8726 should provide a more context-aware error as @kannappanr mentioned https://github.com/minio/minio/issues/8202#issuecomment-543411443 is the way to go.
