### ISSUE TITLE
S3 Select WHERE IN clause doesn't work

### ISSUE THREAD

**Issue by jaydg** [minio/minio#8205]
## Expected Behavior
Given the following JSON file (tc.json) in the bucket _issue_:
```
{"id": 0,"title": "Test Record","desc": "Some text","synonyms": ["foo", "bar", "wahtever"]}
{"id": 1,"title": "Second Record","desc": "another text","synonyms": ["some", "synonym", "value"]}
```

the query `SELECT * from s3object s WHERE 'foo' IN s.synonyms` should return

```
{"id": 0,"title": "Test Record","desc": "Some text","synonyms": ["foo", "bar", "wahtever"]}
```

(as AWS S3 does)

## Current Behavior
S3 client call (outlined in steps to reproduce 3) fails with error 

> ClientError: An error occurred (ParseSelectFailure) when calling the SelectObjectContent operation: <source>:1:38: unexpected token "IN"

## Steps to Reproduce (for bugs)
1. create a bucket issue. insert file tc.json with the content given in expected behavior
2. create a S3 client object
3. execute this call:
```Python
s3.select_object_content(
	Bucket='issue', 
	Key='tc.json', 
	ExpressionType='SQL', 
	Expression="SELECT * from s3object s WHERE 'foo' IN s.synonyms", 
	InputSerialization={'CompressionType': 'NONE','JSON': {'Type': 'Lines'}}, 
	OutputSerialization={'JSON': {'RecordDelimiter': '$'}}
)
```
4. error is triggered

## Regression
No.

## Your Environment
* Version used: 2019-08-21T19:40:07Z
  Release-Tag: RELEASE.2019-08-21T19-40-07Z
  Commit-ID: 2fa98b1d6a013e0fda0d810ae9b6cda94b026dfc

**Comment by nitisht** [comment]
Thanks for reporting @jaydg we'll take a look

**Comment by klauspost** [comment]
The correct syntax is `SELECT * from s3object s WHERE s.synonyms[0] IN ('foo')`, which works.

BUT the wildcard matching version `SELECT * from s3object s WHERE s.synonyms[*] IN ('foo')` does not work correctly, nor does `SELECT * from s3object s WHERE s.synonyms[*] = 'foo'`.

The "ArrayWildcard" operator returns an `[]interface{}`: https://github.com/minio/minio/blob/5ecac91a551c043160fbe17dd615280939b83892/pkg/s3select/sql/jsonpath.go#L80

This is picked up in the node evaluation and marshalled to JSON: https://github.com/minio/minio/blob/c9b8bd8de2347258fc693915f0e9425c76c2fec3/pkg/s3select/sql/evaluate.go#L350

This means that individual entries are not compared, but the strings `["foo","bar","wahtever"]` and `["some","synonym","value"]` are returned as the value of this node. This means the comparison will be done against the entire string and not each item.

**Comment by klauspost** [comment]
We can keep things here and change the title to `S3 Select array wildcard does not match correctly` or something like that.

**Comment by jaydg** [comment]
I think that is a misunderstanding: `SELECT * from s3object s WHERE s.synonyms[0] IN ('foo')` would find all records, for which the *first* element is "foo". 

The query is supposed to look into *any* of the elements of the synonyms array, which also may be of arbitrary length, even contain no elements at all.

**Comment by klauspost** [comment]
@jaydg Please read my entire reply. There is a wildcard operator, but it does not work correctly.
