### ISSUE TITLE
hdfs gateway : unable to create the gateway

### ISSUE THREAD

**Issue by demetthyl** [minio/minio#8206]
Hello guys, i am trying to start a minio using gateway hdfs.
The objective is to take advantage of our existing cluster and of the minio s3 spec.

## Expected Behavior

I am trying to use the hdfs minio gateway to plug a minio instance onto an existing hdfs hadoop cluster.

## Current Behavior

Even after controlling my keytab and KDC, i have the same issue when starting minio

## Steps to Reproduce (for bugs)

1. init a shell with all the needed:
export MINIO_ACCESS_KEY=minio
export HADOOP_CONF_DIR=/usr/hdp/2.6.3.0-235/hadoop/conf
export KRB5CCNAME=/tmp/krb5cc_78911
export HADOOP_HOME=/usr/hdp/2.6.3.0-235/hadoop
export MINIO_SECRET_KEY=minio123
./minio gateway hdfs

2. exec the shell 
bash-4.2$ ./start.sh

3. retrieve error :
ERROR Unable to initialize gateway backend: no available namenodes: SASL handshake: sasl call failed with FATAL_UNAUTHORIZED (javax.security.sasl.SaslException)

4. retrieve the namenode error :
INFO  ipc.Server (Server.java:doRead(1006)) - Socket Reader #1 for port 8020: readAndProcess from client xxx.xxx.xxx.xxxt hrew exception [javax.security.sasl.SaslException: Final handshake step failed [Caused by GSSException: Defective token detected (Mechanism level: MIC Token (new format):Defective Token ID!)]]

## Your Environment

* Version used (`minio version`): 
Version: 2019-08-29T00:25:01Z
Release-Tag: RELEASE.2019-08-29T00-25-01Z
Commit-ID: eb18c82976251d9a0c0730df27e10204c89beae2

* Operating System and version (`uname -a`):
Linux  3.10.0-957.5.1.el7.x86_64 #1 SMP Wed Dec 19 10:46:58 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

Anyone having a though on my painful issue ?
All the tests i did are using encryption type aes256-cts-hmac-sha1-96

Regards,
Guillaume

**Comment by harshavardhana** [comment]
@demetthyl Thanks for the issue we will take a look

**Comment by demetthyl** [comment]
Hello,

Anything i can do to help you resolve this?
Is there a way to set krb5go lib inside minio on debug mode to give you more input?

Regards,
Guillaume

**Comment by harshavardhana** [comment]
Currently this is a lower priority @demetthyl while we finish other high priority tasks. We will get back to you soon when we have some free cycles.

**Comment by harshavardhana** [comment]
Closing this gateway issue to be done as a future milestone.

**Comment by wwm-git-self** [comment]
Hi @harshavardhana , 
Has this problem been solved? I still facing the error with latest minio: ERROR Unable to initialize gateway backend: mkdir /.minio.sys/tmp: unexpected sequence number

**Comment by harshavardhana** [comment]
> unexpected sequence number

Its an issue upstream https://github.com/colinmarc/hdfs/issues/144#issuecomment-443937512 @wwm-git-self
