### ISSUE TITLE
Latest Minio Release does not appear to support Multi-Drive Cache settings (S3 Gateway Mode)

### ISSUE THREAD

**Issue by ghost** [minio/minio#8210]
when running the latest production release the following would only add one of the two drives:

MINIO_CACHE_DRIVES="/mnt/miniocache/cache1;/mnt/miniocache/cache2"

Gateway starts and reports 3.4TB Cache

However when leveraging (rolling back) in this case to VERSION: 2019-08-21T19:40:07Z

MINIO_CACHE_DRIVES="/mnt/miniocache/cache1;/mnt/miniocache/cache2"

Gateway starts and reports 7TB Cache (expected)

## Expected Behavior

See above

## Current Behavior

See above

## Steps to Reproduce (for bugs)

1. see steps above, the issue fixed itself just by rolling back the Minio version
2.
3.
4.

## Regression

Yes I think so

## Your Environment

* Version used (`minio version`): Was on /RELEASE.2019-09-05T23-24-38Z rolled back to RELEASE.2019-08-21T19-40-07Z 
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): Ubuntu 18.04.x
* Link to your project:

**Comment by kannappanr** [comment]
@hassbabaie Thanks for reporting, We will take a look and get back to you

**Comment by klauspost** [comment]
@poornas Related to #7694 maybe?

**Comment by poornas** [comment]
@hassbabaie, you seem to have deleted the .minio.sys/format.json on one of the cache drives while clearing out the contents manually. Is this consistently reproducible? There was no changes pertaining to the storage info reported for cache in the 2 releases you mentioned.

**Comment by ghost** [comment]
When we cleared the cache we remove everything to treat it like a new
gateway. Yes as far as I can tell it is reproducible. When we first
configured the gateway it had two drives but would only work with the first
one. The minute I rolled back the version it registered both drives I
didn’t change anything in the config, just the binary. I can test again
tonight / tomorrow AM and confirm.

Thanks

**Comment by harshavardhana** [comment]
I don't think there is a bug here.. 

```
~ MINIO_CACHE_DRIVES="/tmp/1;/tmp/2" minio server --address ":9001" ~/test
Cache Capacity: 20 GiB Free, 88 GiB Total
Endpoint:  http://192.168.1.143:9001  http://172.17.0.1:9001  http://127.0.0.1:9001          
AccessKey: minio 
SecretKey: minio123 

Browser Access:
   http://192.168.1.143:9001  http://172.17.0.1:9001  http://127.0.0.1:9001          

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.1.143:9001 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
^CExiting on signal: INTERRUPT
```

```
~ rm -rf /tmp/{1..2}
```

```
~ MINIO_CACHE_DRIVES="/tmp/1;/tmp/2;/tmp/3" minio server --address ":9001" ~/test
Cache Capacity: 30 GiB Free, 131 GiB Total
Endpoint:  http://192.168.1.143:9001  http://172.17.0.1:9001  http://127.0.0.1:9001          
AccessKey: minio 
SecretKey: minio123 

Browser Access:
   http://192.168.1.143:9001  http://172.17.0.1:9001  http://127.0.0.1:9001          

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.1.143:9001 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

```

**Comment by ghost** [comment]
@harshavardhana @poornas yes this must have just been a quirk during our initial setup as the testing this afternoon was done on last weeks release (albeit without encryption enabled) but it does appear to be using both drives. So yes we might be all good here.

**Comment by harshavardhana** [comment]
Thanks closing as per last comment..
