### ISSUE TITLE
Kafka TLS Connection with custom CAs not working

### ISSUE THREAD

**Issue by fubezz** [minio/minio#8211]
Connecting a Kafka Bucket Notification service by a self-signed certificate SSL encryption to a Kafka broker fails because we are not able to provide the custom CAs to the Shopify/sarama library, which is used for connection by the Kafka Bucket Notification service. 

## Expected Behavior
1. Starting Minio with "--cert-dir" argument to provide the custom CA which has signed all certificates used for the ssl connection
2. By `mc admin config set` we update the config to configure kafka endpoints and events
2. Kafka Bucket Notification connects to Kafka 

## Current Behavior
Connection to kafka fails.
Error on Minio side: 
`mc: <ERROR> Cannot set server configuration file. kafka(provenance): kafka: client has run out of available brokers to talk to (Is your cluster reachable?).`
Error on Kafka side:
`INFO [SocketServer brokerId=0] Failed authentication with 10.128.3.108/10.128.3.108 (SSL handshake failed) (org.apache.kafka.common.network.Selector)`

## Possible Solution
The connection to kafka works properly but the the clients needs to verify the certificates.
The [global variable](https://github.com/minio/minio/blob/8a71b0ec5a722ce0ce67ee0ad84eb87d2feedc1a/cmd/globals.go#L162) of minio which stores the custom CAs pool  is not provided when [creating](https://github.com/minio/minio/blob/16a45e5aff422caed577067b3eb3a16462debc74/pkg/event/target/kafka.go#L201) the config of sarama.
I think the problem could be solved in the same way like this commit [3d22a9d](https://github.com/minio/minio/commit/3d22a9d84fc85f402599e6205b8336e1b86e5b84).

**Comment by nitisht** [comment]
Thanks for reporting @fubezz we'll take a look
