### ISSUE TITLE
Openstack swift gateway

### ISSUE THREAD

**Issue by cambierr** [minio/minio#8213]
**Is your feature request related to a problem? Please describe.**
I would like to benefit from the power of Minio on all our customer environments, which includes OpenStack Swift as object storage. Thus, I'd like to be able to use minio as a gateway on top of that service.

**Describe the solution you'd like**
An Openstack swift implementation of minio gateway

**Describe alternatives you've considered**
Not using Minio on those environments and using something else, or include a compatibility layer in our software... which would make minio useless in our business.

**Additional context**
N/A

**Comment by harshavardhana** [comment]
You can enable Swift-S3 and use `minio gateway s3`  are you expecting us to write S3 to Swift here?

**Comment by kannappanr** [comment]
@cambierr Closing this issue based on the above comment. Please feel free to reach out to us if you have further questions.

**Comment by benweet** [comment]
S3 compatibility is hardly offered by storage providers (eg. OVH). I think Swift has its place in the list of supported backends (https://github.com/minio/minio/tree/master/docs/gateway).

**Comment by harshavardhana** [comment]
> S3 compatibility is hardly offered by storage providers (eg. OVH). I think Swift has its place in the list of supported backends (https://github.com/minio/minio/tree/master/docs/gateway).

@benweet FWIW we would love community contributions on this one, currently, we are short of cycles to address these use cases. 

As we get more breathing room we may perhaps get back to this issue. Anyone with urgent inclination should implement it from the community and we will help them if they have questions on our slack https://slack.min.io
