### ISSUE TITLE
Notification exclude directory 

### ISSUE THREAD

**Issue by SolarisYan** [minio/minio#8217]
**Is your feature request related to a problem? Please describe.**
I have many directory in a bucket, and i want exclude only one directory without notification, can minio do it now? I know that when add event on bucket minio provide --prefix and --suffix to filter, but if files or directory have no pattern for that, how can we do it?

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
Other, i find that when add event with default --event put,delete,get, if i only ls the files, i will get 
s3:ObjectAccessed:Head event, but i don't want to record this event, how can i do it?

**Additional context**
N/A

**Comment by harshavardhana** [comment]
There is no S3 API to exclude, there is only include and S3 API doesn't provide wildcard match.  So it is not possible for us to implement such extensions to existing API unless S3 provides enhancements to their API

**Comment by kannappanr** [comment]
@SolarisYan Closing this based on the above comment. Please feel free to reach out to us if you have further questions.
