### ISSUE TITLE
Share images uploaed in minio to public

### ISSUE THREAD

**Issue by anrajan** [minio/minio#8218]
We have the files and images uploaded to minio . The policy has been created to recursively grant permissions for images to be accessed . But I find that unless i append the keys in the request , i am never able to hit the images . 

The url i am trying to access is   
https://object1.cs.boeing.com:9021/stage-bucket/images/Achu.jpg

The error i get is  
<Code>AccessDenied</Code>
<Message>Could not determine namespace from anonymous request. Please use a namespace BaseURL or include an x-emc-namespace header
</Message>

When i append with all the headers including the access key and  other details i am very well able to access that .

## Expected Behavior
As per the documents , the url should be publicly accessible . 
 
## Current Behavior
Images are not accessible without including the keys 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by nitisht** [comment]
@anrajan can you paste the policy you used? Also please fill out the issue template, it makes it easier for us to help

**Comment by kannappanr** [comment]
@anrajan You can also use Play to repro the issue

**Comment by anrajan** [comment]
The policy i was using is :  


{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:GetObject"
      ],
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "*"
        ]
      },
      "Resource": [
        "arn:aws:s3:::stage-bucket/images/*"
      ],
      "Sid": ""
    }
  ]
}


Command executed is : 

mc policy -r set-json policy.json minio/stage-bucket/images
Access permission for `minio/stage-bucket/images` is set from `policy.json`

**Comment by anrajan** [comment]
@kannappanr , sorry , i am relatively new to minio . Could you please let me know what is expected from me here .

**Comment by nitisht** [comment]
@anrajan can you please use this policy with command: 

`mc policy -r set-json policy.json minio/stage-bucket`

```json
{
	"Statement": [{
		"Action": [
			"s3:GetObject"
		],
		"Effect": "Allow",
		"Principal": {
			"AWS": [
				"*"
			]
		},
		"Resource": [
			"arn:aws:s3:::stage-bucket/images/*"
		]
	}],
	"Version": "2012-10-17"
}
```

**Comment by anrajan** [comment]
Tried that . But no difference in the response .

**Comment by nitisht** [comment]
do you mind joining us on Slack (https://slack.minio.io), we can discuss realtime and close this quickly. I am ‘nitish’ on slack

**Comment by kannappanr** [comment]
@anrajan I tried the same `json` provided here on `play` and it seems to work fine.

**Comment by anrajan** [comment]
Ok . I am not able to join to slack also due to restrictions put by my office firewall . 

Let me see if the issue is with restrictions set at the domain/namespace level (Not sure if that is at all possible or not ) .I Will update you soon on that .
    On Thursday, September 12, 2019, 4:17:37 AM GMT+5:30, kannappanr <notifications@github.com> wrote:  
 
 
@anrajan I tried the same json provided here on play and it seems to work fine.

**Comment by nitisht** [comment]
@anrajan checking to see if it worked?

**Comment by anrajan** [comment]
No , That didnt work . Some more observations , on including the credentials in the url (through postman) , i could see the images , otherwise it is the same behavior . On accessing the url like <bucketname>.miniohost:9021/<image path> i see bucket not available error .
I tried giving public access to bucket and object both , no change in behavior .
Regards,Anoop 

    On Friday, September 13, 2019, 11:49:47 AM GMT+5:30, Nitish Tiwari <notifications@github.com> wrote:  
 
 
@anrajan checking to see if it worked?

**Comment by nitisht** [comment]
@anrajan this is weird / unexpected. Do you mind dropping a line on nitish@min.io , we can schedule some time to debug this quickly..

**Comment by nitisht** [comment]
@anrajan closing this for now, please reach out if on the email to and we'll try to see what's going wrong in your deployment
