### ISSUE TITLE
Could Structured Data Storage be Supported?

### ISSUE THREAD

**Issue by javacoderxxp** [minio/minio#8225]
I want to store structured data in minio. for example, the data in table with oracle database.
And, how does it integrate query engines?

**Comment by javacoderxxp** [comment]
also, i just want to know how to store data in minio instead of oracle

**Comment by nitisht** [comment]
@javacoderxxp please join us on Slack (https://slack.minio.io) for such questions. Closing this issue for now..

**Comment by javacoderxxp** [comment]
ok
