### ISSUE TITLE
mc:  Unable to update the server. open /usr/local/bin/.minio.new: permission denied

### ISSUE THREAD

**Issue by kanagarajkm** [minio/minio#8226]
This happens when MinIO is run as systemd service by following the steps here
https://github.com/minio/minio-service/tree/master/linux-systemd

`minio` binary is owned by `minio` user.
```
-rwxr-xr-x 1 minio minio 43720704 Sep 12 05:27 minio
```
Then when `mc admin update` is executed, it fails with following error
```
mc:  Unable to update the server. open /usr/local/bin/.minio.new: permission denied
```

## Expected Behavior

`mc admin update` should work fine without the `minio` user needing write permission on `/usr/local/bin`.  Having write permissions for `/usr/local/bin/minio` should be enough.

## Current Behavior

`minio` user should have write permissions on `/usr/local/bin` for the update to work

## Steps to Reproduce (for bugs)

1. Run minio as systemd service as described here https://github.com/minio/minio-service/tree/master/linux-systemd
2. Make sure `/usr/local/bin/minio` is owned by the `minio` (refer User on minio.service file) user
3. Start the service
4. Run `mc admin update`

## Context

`/usr/local/bin` needs to be owned by `minio` user to perform the upgrade

## Your Environment

* Version used (`minio version`): minio.RELEASE.2019-09-05T23-24-38Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: 
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
You need to have full permissions where the binary is kept. It's useless to run as minio user which doesn't have permissions to write to /usr/local/bin 

The update library uses atomic renames to achieve in-place updates.

**Comment by kannappanr** [comment]
Closing this issue for now as we have documented the requirements in #8228
