### ISSUE TITLE
Distributed setup performance bottleneck diagnostics

### ISSUE THREAD

**Issue by khumps** [minio/minio#8245]
We are running a test cluster with 4 nodes each with a single disk and running Apache Bench(ab) against approximately 20k files on the cluster. The cpu usage peaks at around 60% per node, `iotop` reports are negligible because all the images have been cached to ram, and `iftop` for the bonded 10G NIC's isnt going above 1GB/s total (using a combination of ab and nginx, we have been able to push the full 20G across the NIC's but minio doesn't seem to saturate CPU (all CPU's cap at around 60%), memory, IO, nor network(caps at 1Gbps) and we aren't sure why.

## Expected Behavior
Much higher requests per second(RPS) on the minio cluster as load on the system increases
## Current Behavior
currently peaking at around 2000 RPS while not peaking on any resources

## Steps to Reproduce (for bugs)
1.) set up 4 minio nodes each with 1 disk
2.) run multiple test configurations against the cluster (1 client, 4 clients, nginx with all the instances as upstreams, directly hitting one instance, each client hitting its own instance, etc) 

## Context
We are unable to push more than 2000 RPS through minio and we would like to find out what the bottleneck is.

## Your Environment

* Version used (`minio version`): 2019-07-31T18:57:56Z
* Environment name and version (e.g. nginx 1.9.1):
* Operating System and version (`uname -a`): Centos 7 4.14.15-1.el7.elrepo.x86_64

I can provide more details, logs, config information if needed.

**Comment by khumps** [comment]
Updated to RELEASE.2019-09-11T19-53-16Z and it still stands

**Comment by harshavardhana** [comment]
Some questions need answers here @khumps 

- What is the average object size here?
- Can you avoid nginx and connect directly to the server without nginx? - share your nginx config as well?
- dd if=/dev/zero of=<disk>/bigfile bs=1M count=1024 oflag=direct  (to get baseline performance of all the disks)
- if your object is < 128KiB we would need to get `dd if=/dev/zero of=<disk>/bigfile bs=32k count=10240 oflag=direct`

**Comment by khumps** [comment]
Of course:

- Average object size is around 256KB

- Ran a test just now where I disabled nginx and hyperthreading which gave around 400 more RPS (going to run a longer test with nginx back on to make sure that isn't just a result of hyperthreading and report those results here)

- I ran the first dd you provided and got 369, 469, 358, 368 MB/s across the machines

**Comment by harshavardhana** [comment]
So it is a small file workload.. can you also do the 32K number for dd ?

**Comment by ginkel** [comment]
Isn't Apache Bench about reading data? Why would `dd` write statistics be relevant for that scenario?

**Comment by harshavardhana** [comment]
> Isn't Apache Bench about reading data? Why would `dd` write statistics be relevant for that scenario?

@ginkel the point is any performance-related will come back to writes as well for the disks - it is to establish a baseline.

**Comment by harshavardhana** [comment]
> for the bonded 10G NIC's isnt going above 1GB/s total (using a combination of ab and nginx, we have been able to push the full 20G across the NIC's but minio doesn't seem to saturate CPU (all CPU's cap at around 60%), memory, IO, nor network(caps at 1Gbps) and we aren't sure why.

Bonded NICs will never give you 20G unless you have switch level bonding, if this is software only bonding then it is simply a failover NIC. So you should look at 10G as the actual number here not 20G. How did you verify the network performance? @khumps 

What is the backend filesystem in use here? @khumps if its xfs can you provide the output of xfs_info() ? also the mount options used `mount | grep disk` 

Also, make sure that following kernel settings have been applied on the server @khumps in /etc/sysctl.conf 

```
# maximum number of open files/file descriptors
fs.file-max = 4194303
# use as little swap space as possible
vm.swappiness = 0
# prioritize application RAM against disk/swap cache
vm.vfs_cache_pressure = 10
# minimum free memory
vm.min_free_kbytes = 1000000
# maximum receive socket buffer (bytes)
net.core.rmem_max = 268435456
# maximum send buffer socket buffer (bytes)
net.core.wmem_max = 268435456
# default receive buffer socket size (bytes)
net.core.rmem_default = 67108864
# default send buffer socket size (bytes)
net.core.wmem_default = 67108864
# maximum number of packets in one poll cycle
net.core.netdev_budget = 1200
# maximum ancillary buffer size per socket
net.core.optmem_max = 134217728
# maximum number of incoming connections
net.core.somaxconn = 65535
# maximum number of packets queued
net.core.netdev_max_backlog = 250000
# maximum read buffer space
net.ipv4.tcp_rmem = 67108864 134217728 268435456
# maximum write buffer space
net.ipv4.tcp_wmem = 67108864 134217728 268435456
# enable low latency mode
net.ipv4.tcp_low_latency = 1
# socket buffer portion used for TCP window
net.ipv4.tcp_adv_win_scale = 1
# queue length of completely established sockets waiting for accept
net.ipv4.tcp_max_syn_backlog = 30000
# maximum number of sockets in TIME_WAIT state
net.ipv4.tcp_max_tw_buckets = 2000000
# reuse sockets in TIME_WAIT state when safe
net.ipv4.tcp_tw_reuse = 1
# time to wait (seconds) for FIN packet
net.ipv4.tcp_fin_timeout = 5
# disable icmp send redirects
net.ipv4.conf.all.send_redirects = 0
# disable icmp accept redirect
net.ipv4.conf.all.accept_redirects = 0
# drop packets with LSR or SSR
net.ipv4.conf.all.accept_source_route = 0
# MTU discovery, only enable when ICMP blackhole detected
net.ipv4.tcp_mtu_probing = 1
```

Borrowed from our benchmarking docs https://min.io/resources/docs/MinIO-throughput-benchmarks-on-HDD.pdf

**Comment by khumps** [comment]
@harshavardhana 

- Network performance was determined by running a test with just nginx serving a static image and running ab against that from the 4 clients (capped at 17-19 Gb/s using a 5MB image, a lot less for small 256KB images but the RPS was at 50k+ and capped by the CPU handling that many connections)

- Backing FS is ext4

- Will try those sysctl props for the next test run

- Also ran the 32k benchmark and got 216, 339, 255, and 233 MB/s

**Comment by harshavardhana** [comment]
Using nginx vs MinIO is an unfair comparison. Nginx is not a distributed entity with strictly consistent locking requirements, there is 1/2 bandwidth goes for internode traffic.

Also please use xfs not ext4 in your next iteration, mount it with noatime

**Comment by khumps** [comment]
@harshavardhana that nginx test was purely for making sure that the NIC's could push the bandwidth, I'll probably have to wait till next week to test with XFS, the sysctl settings added some performance. I tried running your s3-benchmark and I could push around 4000 RPS @256KB/request. That seemed to be possibly be limited by IO because it is not caching them in RAM like our current test is. Do you have any profiling tools available to see what might be throttling it when everything is cached?

**Comment by ginkel** [comment]
You can run `mcli admin profile start --type cpu TARGET` to profile CPU.

**Comment by harshavardhana** [comment]
Closing this issue, for now, please re-open if you want to debug further.
