### ISSUE TITLE
[build failure] apache thrift migration

### ISSUE THREAD

**Issue by CosmicToast** [minio/minio#8246]
## Expected Behavior
`go build` produces a binary

## Current Behavior
`go build` fails with:
```
go: git.apache.org/thrift.git@v0.12.0: unknown revision v0.12.0                                                                               go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/toast/aports/testing/minio/src/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:                fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Operation timed out       go: error loading module requirements
```

## Possible Solution
Update `go.mod` as per https://github.com/kubernetes/minikube/issues/5245, though extra steps may be required.

## Steps to Reproduce (for bugs)
1. Download release tarball
2. `export GO111MODULE=on`
3. `go build` (ldflags etc not mentioned for simplicity)

## Context
I'm the package maintainer for MinIO over at [Alpine Linux](https://pkgs.alpinelinux.org/packages?name=minio) and cannot bump the package version (as it'll fail to build).

mc is also affected, bug here: https://github.com/minio/mc/issues/2894

## Regression
Yes, but it was caused by Apache (migrating without setting up any sort of redirection).

**Comment by harshavardhana** [comment]
You should be using go 1.13 we do not support go1.12

**Comment by CosmicToast** [comment]
Oh, that was unexpected (given that go's release policy is to support the latest and before-latest release (see [this](https://golang.org/doc/devel/release.html#policy)), but noted.
Will check back once 1.13 is in tree.

**Comment by harshavardhana** [comment]
You can still build it just use GOPROXY=https://proxy.golang.org and you may have to fix main.go to build with go1.12

**Comment by CosmicToast** [comment]
Oh, the 1.13 workaround is just to use proxy (which is on by default at that point)?
I don't think any go proxy implementation guarantees keeping cache indefinitely...
The redirect will need to be done eventually one way or another, but since it's not a direct dependency I suppose hoping the relevant upstream(s) get there eventually is enough.

**Comment by harshavardhana** [comment]
Go 1.13 is going to change it later, when our dependent package updates or fixes it. It will get fixed automatically.

**Comment by yu2003w** [comment]
I also met the same issue when I tried to build tag RELEASE.2019-04-09T01-22-30Z using go 1.12.
Build completed several weeks ago. However, it failed recently. 
Is this caused by go changes or anything else?
Why does it work after switch to go 1.13?

**Comment by harshavardhana** [comment]
Because of GOPROXY settings..

**Comment by harshavardhana** [comment]
Closing as working as intended
