### ISSUE TITLE
Bulk delete fails silently

### ISSUE THREAD

**Issue by shvandehoef** [minio/minio#8247]
When I'm deleting 1000 objects through the aws-sdk for nodejs against a local Minio instance running in a docker container, the deletion fails without any error message, i.e., the client gets the response that all objects are successfully deleted even though they are not. If I delete a small number of objects (say 10), the problem does not occur. If I delete the 1000 objects with no delay in-between one-by-one or in batches of 10, it also fails without any indication of an error. If I delete in batches of 10 and put 100 ms delay between each call, the objects get successfully deleted. 

## Expected Behavior
All objects get deleted or the response indicates an error deleting the objects.

## Current Behavior
The objects don't get deleted but the response indicates successful deletion. 

## Possible Solution
--

## Steps to Reproduce (for bugs)
1. Run a docker container with Minio (latest version).
2. Create a bucket an upload 1000 objects (~100 kb each).
3. Delete these objects using the AWS SDK for nodeJS, function "deleteObjects".
4. Objects are still present.

## Context
I've encountered the issue when deleting all objects related to a "unit of work". 

## Regression
--

## Your Environment
About screen in the Minio UI:

    Version
    2019-09-11T19:53:16Z
    Memory
    Used: 7.5 MB | Allocated: 137 GB | Used-Heap: 7.5 MB | Allocated-Heap: 65 MB
    Platform
    Host: 74b6d1ec34ce | OS: linux | Arch: amd64
    Runtime
    Version: go1.13 | CPUs: 4

Running in a docker container on a Linux host. 
Using AWS SDK  for nodejs version: "2.528.0"

**Comment by kanagarajkm** [comment]
@shvandehoef  do you see any errors on MinIO log?

**Comment by harshavardhana** [comment]
You should give us a small code snippet to reproduce this issue @shvandehoef - that will go a long way.

**Comment by shvandehoef** [comment]
No errors whatsoever from what I can tell. 

Here is some code that should cover the problem:

```
const AWS = require('aws-sdk');
const BUCKET = "test"

const MINIO_CONFIG = {
    ACCESS_KEY: "your access key",
    SECRET_KEY: "your secret key"
}

var batch = (await s3client.listObjects({Bucket: BUCKET}).promise())
        .Contents
        .map((fileInfo => fileInfo.Key));

var client = new AWS.S3({
            accessKeyId: MINIO_CONFIG.ACCESS_KEY,
            secretAccessKey: MINIO_CONFIG.SECRET_KEY,
            endpoint: "http://127.0.0.1:9000",
            s3ForcePathStyle: true,
            ignatureVersion: 'v4'
        })

res = await s3client.deleteObjects({
                Bucket: BUCKET,
                Delete: {
                    Objects: batch.map((key) => {return {Key: key}})
                }
            }).promise();
```
`batch` is just a sufficiently long list of keys to be deleted.
Add a bunch of files into a bucket called test before running this.

**Comment by harshavardhana** [comment]
@shvandehoef it looks like your code has bugs here is how I implemented it correctly

```js
let AWS = require('aws-sdk');

const MINIO_CONFIG = {
    ACCESS_KEY: "minio",
    SECRET_KEY: "minio123"
}

const s3 = new AWS.S3({
    accessKeyId: MINIO_CONFIG.ACCESS_KEY,
    secretAccessKey: MINIO_CONFIG.SECRET_KEY,
    endpoint: "http://127.0.0.1:9000",
    s3ForcePathStyle: true,
    signatureVersion: 'v4'
})

async function deleteRecursive(bucket, dir) {
    while (true) {
        const listedObjects = await s3.listObjects({
            Bucket: bucket,
            Prefix: dir
        }).promise();

        if (listedObjects.Contents === undefined) {
            throw new Error('Listing S3 returns no contents');
        }
        if (listedObjects.Contents.length !== 0) {
            await s3.deleteObjects({
                Bucket: bucket,
                Delete: {
                    Objects: listedObjects.Contents.map(obj => ({
                        Key: obj.Key
                    }))
                }
            }).promise();
        }
        if (!listedObjects.IsTruncated) {
            return
        }
    }
}

(async function(){
    deleteRecursive("testbucket", "")
}());
```

**Comment by harshavardhana** [comment]
NOTE: deleteObjects can only delete 1000 maximum at a time and you need to batch it appropriately.

**Comment by shvandehoef** [comment]
@harshavardhana 

> 
> 
> NOTE: deleteObjects can only delete 1000 maximum at a time and you need to batch it appropriately.

I know that and my code batches accordingly. I'm using `splice(0, BATCH_SIZE)` for that. The snippet I provided is of course not copy&paste from my code, but covers the bits and pieces to reproduce the bug keeping it as simple as possible. Under "Steps to reproduce the error" I explicitly wrote to upload 1000 objects for that reason. 

In fact, even if my code deletes the objects one-by-one with `deleteObject()` in too quick succession, the objects do not get deleted. 

What your code snippet is doing is to keep retrying the delete until it has been successful. That might be a workaround. Nevertheless I would expect of an object storage to actually delete objects if the response confirms that the object has been deleted. Since the `deleteObjects` call doesn't delete ANY objects in my case if the batch size is too large, I'm pretty sure, the code you suggested would actually end up in an infinite loop.

**Comment by harshavardhana** [comment]
> What your code snippet is doing is to keep retrying the delete until it has been successful. That might be a workaround. Nevertheless I would expect of an object storage to actually delete objects if the response confirms that the object has been deleted. Since the `deleteObjects` call doesn't delete ANY objects in my case if the batch size is too large, I'm pretty sure, the code you suggested would actually end up in an infinite loop.

It is not retrying upon error it is simply deleting 1000 at a time and while doing that I have trace output such that every 1000 entries get one call. In total, I was deleting 3192 entries i.e split across 4 listObjects and 4 deleteObjects calls as shown below

```
23:00:58.174 [200 OK] s3.ListObjectsV1 127.0.0.1:9000/testbucket?prefix=  127.0.0.1         313.695ms    🠉 104 B  🠋 340 KiB
23:00:58.681 [200 OK] s3.DeleteMultipleObjects 127.0.0.1:9000/testbucket?delete  127.0.0.1         6.962196s    🠉 63 KiB  🠋 66 KiB
23:01:05.741 [200 OK] s3.ListObjectsV1 127.0.0.1:9000/testbucket?prefix=  127.0.0.1         247.781ms    🠉 104 B  🠋 349 KiB
23:01:06.070 [200 OK] s3.DeleteMultipleObjects 127.0.0.1:9000/testbucket?delete  127.0.0.1         6.918669s    🠉 73 KiB  🠋 76 KiB
23:01:12.993 [200 OK] s3.ListObjectsV1 127.0.0.1:9000/testbucket?prefix=  127.0.0.1         222.236ms    🠉 104 B  🠋 352 KiB
23:01:13.302 [200 OK] s3.DeleteMultipleObjects 127.0.0.1:9000/testbucket?delete  127.0.0.1         6.999785s    🠉 76 KiB  🠋 78 KiB
23:01:20.317 [200 OK] s3.ListObjectsV1 127.0.0.1:9000/testbucket?prefix=  127.0.0.1         41.263ms     🠉 104 B  🠋 69 KiB
23:01:20.370 [200 OK] s3.DeleteMultipleObjects 127.0.0.1:9000/testbucket?delete  127.0.0.1         1.784662s    🠉 15 KiB  🠋 16 KiB
```

Once it's done all objects are deleted one can see from the `mc ls` output

```
~ mc ls myminio/testbucket/
```

> In fact, even if my code deletes the objects one-by-one with `deleteObject()` in too quick succession, the objects do not get deleted.

I don't think that is true. You haven't demonstrated that yet, neither I can reproduce it.  First, the code shared was incomplete so I had to re-implement it to make it work appropriately with async await syntax.

**Comment by harshavardhana** [comment]
> What your code snippet is doing is to keep retrying the delete until it has been successful. That might be a workaround. Nevertheless I would expect of an object storage to actually delete objects if the response confirms that the object has been deleted. Since the `deleteObjects` call doesn't delete ANY objects in my case if the batch size is too large, I'm pretty sure, the code you suggested would actually end up in an infinite loop.

The fundamental problem in your code or whatever that was shared - is you are ignoring the fact that listObjects() is a batched result, not an infinite iterator. It lists and sets a value as IsTruncated which needs to be used to continue further listing.

I don't know why you would say that it will end in an infinite loop as clearly shown under which conditional the while true will exit. did you even give it a try? @shvandehoef

**Comment by shvandehoef** [comment]
I'm very sorry. It seem, I overlooked indeed that the `listObjects()` call is truncated. Not sure how I missed that...
And thanks a bunch for the help anyway.
