### ISSUE TITLE
Add support for h2c (unencrypted http/2)

### ISSUE THREAD

**Issue by thomasf** [minio/minio#8248]
**Is your feature request related to a problem? Please describe.**
When I set my TLS terminating load balancer to use h2c protocol minio does not respond

**Describe the solution you'd like**
Maybe a command line argument to enable the feature so that unencrypted traffic isn't allowed by mistake.
I think it's quite easy to implement using  https://godoc.org/golang.org/x/net/http2/h2c

**Comment by harshavardhana** [comment]
We do not support http/2 because of many upstream bugs that we have reproduced. It will be quite some time before we migrate back to http/2

**Comment by thomasf** [comment]
I didn't know it was removed. I'll have to look for some proxy that can translate http1 to http2 then for public files serving, nghttpx might be a way to go for that. 

edit: never mind, I see that traefik which is our current load balancer proxy actually does this already.

**Comment by harshavardhana** [comment]
Closing this as won't fix for now. We will support http2.0 in future.

**Comment by fogti** [comment]
it seems like AWS C++ SDK stopped sending the `Authorization:` header in the request that attempts to upgrade to h2 / h2c, which seems to make it incompatible with `minio version RELEASE.2021-11-24T23-19-33Z`. see also: https://github.com/NixOS/nix/issues/5707

**Comment by harshavardhana** [comment]
> it seems like AWS C++ SDK stopped sending the `Authorization:` header in the request that attempts to upgrade to h2 / h2c, which seems to make it incompatible with `minio version RELEASE.2021-11-24T23-19-33Z`. see also: [NixOS/nix#5707](https://github.com/NixOS/nix/issues/5707)

MinIO doesn't do any auto-upgrades for HTTP2 connections - this looks like AWS C++ SDK feature and they are not doing things properly.

**Comment by fogti** [comment]
yes, filed a bug report: https://github.com/aws/aws-sdk-cpp/issues/1821
