### ISSUE TITLE
Custom Authorization Scenario using Minio

### ISSUE THREAD

**Issue by Reza-Noei** [minio/minio#8249]
Hi,

I have a custom authorization scenario for my web service. 

At first, I have AWS Token Authorization on Amazon S3 support platform e.g Minio.
On the other hand, I have My jwt support web service, which Authorize each user request using a defined business. 

My Clients may wants to work with e.g Minio directly. I want to sure that they are  confirm my business dictates. 

So I have so many options on my hands. but the first possible option is to have software supports on Minio.

If i was able to authorize user request by calling a remote api in another web service. I will be happy to get it to work. 

I had some google on this topic but i couldn't find software supported solution.

Is there any way to doing this ?

Thanks,

**Comment by nitisht** [comment]
do you want to use JWT tokens to authenticate with MinIO server @Reza-Noei ?

**Comment by Reza-Noei** [comment]
> 
> 
> do you want to use JWT tokens to authenticate with MinIO server @Reza-Noei ?

No, I have a Rest Api (Called e.g. Foo) and this foo uses JWT. 

I want to say it to Minio: 
'This user Request is allowed to be executed, if and only if my Foo verifies it.'

**Comment by donatello** [comment]
MinIO supports standard oauth tokens given jwks url for pub key based token verification. This would be the way to support your use case https://github.com/minio/minio/blob/master/docs/sts/web-identity.md

**Comment by Reza-Noei** [comment]
I had some research on it so for a brief explanation i have found that in this method Minio will recognize validity of my JWT token in some ways. 

but i need to add actually a business to this api (Minio)
Let say:

Client: I want to put some Objects in Temp\Bucket3 in Minio
Minio: Lets Confirm you request by asking your authurization from Foo.net/api/JWTToken?Root=Temp&Bucket=Bucket3&Action=PutObject
Foo: Oh, he cant/can write on this Bucket.
Minio: Write/Deny Request.
Minio: return result to Client.

**Comment by kannappanr** [comment]
Authorization can be handled by using policies for the user. You can create users and have some sort of policies attached to the user. Policy management can be done either within MinIO or outside. We currently support external policy engine like OPA, you can set up policy there and use it.

**Comment by kannappanr** [comment]
@Reza-Noei Closing this issue for now. Please feel free to reach out to us if you have further questions. It is also easier if you can reach out to us at https://slack.min.io if you have further questions.

**Comment by Reza-Noei** [comment]
Thanks, Im new to Object Storage concepts and i will try to research.

**Comment by astukanov** [comment]
> Authorization can be handled by using policies for the user. You can create users and have some sort of policies attached to the user. Policy management can be done either within MinIO or outside. We currently support external policy engine like OPA, you can set up policy there and use it.

Hi @kannappanr is it possible to use Keycloak Authorization Services for policy enforcement with minio?

**Comment by harshavardhana** [comment]
> > Authorization can be handled by using policies for the user. You can create users and have some sort of policies attached to the user. Policy management can be done either within MinIO or outside. We currently support external policy engine like OPA, you can set up policy there and use it.
> 
> Hi @kannappanr is it possible to use Keycloak Authorization Services for policy enforcement with minio?

@astukanov no we cannot - we require AWS IAM style policies.
