### ISSUE TITLE
How to add cluster nodes through DNS mapping？

### ISSUE THREAD

**Issue by wlwcjl** [minio/minio#8253]
How to add cluster nodes through DNS mapping？please give me a document  link， thank you！

**Comment by kannappanr** [comment]
We don't support adding nodes to an existing cluster. You can add another cluster and expand using federation. Please look at https://docs.min.io/docs/minio-federation-quickstart-guide.html . Closing this issue. Please feel free to reach out to us at https://slack.min.io for such questions.
