### ISSUE TITLE
Mc admin user remove cause InternalError  and cause mc run infinite loop

### ISSUE THREAD

**Issue by domonless** [minio/minio#8255]
Under latest version minio and mc download from minio website.
When the admin user remove command failed for some reason, user not existed etc. , the server response with a 500 Internal Server Error and mc client keep tryting the same command which cause the powershell / cmd / subprocess.Popen hangs.
`.\mc.exe admin user remove minio test2 --json --debug`

## Expected Behavior
Should return a  response with error message and 404 Not Found.
When I try use `admin group remove` to remove an non-exist group, got response with 404 Not Found and error message, and mc exit normally.

## Current Behavior
500 Error and mc keep trying infinitely.
`mc.exe: <DEBUG> HTTP/1.1 500 Internal Server Error
Content-Length: 209
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Tue, 17 Sep 2019 14:17:58 GMT
Server: MinIO/RELEASE.2019-09-11T19-53-16Z
Vary: Origin
X-Amz-Request-Id: 15C53F8353F433B4
X-Xss-Protection: 1; mode=block

{"Code":"InternalError","Message":"We encountered an internal error, please try again.","Resource":"/minio/admin/v1/remove-user","RequestId":"15C53F8353F433B4","HostId":"b974cafa-e140-4d80-a505-b7b3bd849c4e"}
mc.exe: <DEBUG> Response Time:  185.2297ms`

## Your Environment

* Version used (`minio version`): latest
* Operating System and version (`uname -a`): Windows 10 x64

**Comment by kannappanr** [comment]
@domonless Thanks for reporting the issue. We will take a look at it.

**Comment by harshavardhana** [comment]
mc won't try infinitely it will try upto 10 times binomially, when server responded internal error. There will be a log on server side, can you please share that ?

**Comment by domonless** [comment]
> mc won't try infinitely it will try upto 10 times binomially, when server responded internal error. There will be a log on server side, can you please share that ?

FYI.
And my mc actually stop try after a while but leave no return code for prompt hangs which I wrapper with python subprocess.Popen code.

API: RemoveUser()
Time: 22:08:23 CST 09/17/2019
DeploymentID: b974cafa-e140-4d80-a505-b7b3bd849c4e
RequestID: 15C53EFD6F209974
RemoteHost: 127.0.0.1
Host: 127.0.0.1:9000
UserAgent: MinIO (windows; amd64) madmin-go/0.0.1 mc.exe/2019-09-11T20:17:47Z
Error: [31m[1mconfig file not found[0m[0m
       5: cmd\api-errors.go:1694:cmd.toAPIErrorCode()
       4: cmd\admin-handlers.go:1072:cmd.toAdminAPIErrCode()
       3: cmd\admin-handlers.go:1080:cmd.toAdminAPIErr()
       2: cmd\admin-handlers.go:1113:cmd.adminAPIHandlers.RemoveUser()
       1: net\http\server.go:2007:http.HandlerFunc.ServeHTTP()

**Comment by harshavardhana** [comment]
Fixed in #8465
