### ISSUE TITLE
S3 Select *  no longer works with JSONOutputSerialization

### ISSUE THREAD

**Issue by poornas** [minio/minio#8268]
## Expected Behavior

```
 mc sql --json-output ""  -e  "select * FROM S3Object"  myminio/sql/parking-citations-100K.csv
```
should work but does not.
## Current Behavior

Above command works if the --json-output flag is removed.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Regression
 Yes - dac1cf5a9aa70762c8ee7d45ccce3f5c2059bbe3 

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by klauspost** [comment]
PR added.
