### ISSUE TITLE
Minio browser is not accessible with error message currentUiVersion is not defined

### ISSUE THREAD

**Issue by yoonsio** [minio/minio#8270]
Minio Browser is not accessible with error message: 
```
currentUiVersion is not defined
```

## Expected Behavior
Login successfully with correct credentials.

## Current Behavior
Minio browser is throwing error message `currentUiVersion is not defined` when correct credentials are used to login.

<img width="674" alt="Screen Shot 2019-09-19 at 1 48 34 AM" src="https://user-images.githubusercontent.com/24367477/65216645-aa0a1500-da7f-11e9-8b98-13ee3b383713.png">

## Steps to Reproduce (for bugs)
1. Deploy minio through helm chart behind nginx ingress controller
2. Login with correct credentials

## Context
Minio object storage server is still accessible but web ui is not.

## Your Environment
* Kubernetes: `v1.15.3`
* Minio: `RELEASE.2019-09-18T21-55-05Z`
* Ingress controller: `quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.25.1`
* Server: `Ubuntu 18.04.3 LTS`

**Comment by kannappanr** [comment]
@sickyoon We will take a look at this issue and get back to you.

**Comment by harshavardhana** [comment]
Not able to reproduce this, would you mind providing browser console network logs if any?

**Comment by harshavardhana** [comment]
Unable to reproduce this issue. Closing this issue as we haven't heard anything back.

**Comment by yossiepon** [comment]
If 'unsafe-inline' is not included as script-src on the content security policy response header, the currentUiVersion variable is not declared on the login screen, so the above error is reproduced.
