### ISSUE TITLE
minio issue on xfs and rhel7

### ISSUE THREAD

**Issue by demetthyl** [minio/minio#8272]
## Expected Behavior
I am having issue starting minio on a xfs mount, while it works normally on /tmp

## Current Behavior
Working as intending on /tmp
Not able to see my buckets / objects with mc or GUI when on xfs

## Steps to Reproduce (for bugs)
1. create a basic starting shell:
export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=minio123
export MINIO_REGION=eu-west-3
./minio server /home/dlake/appli/minio 

2. get the mc config command
mc config host add myminio http://10.237.82.145:9000 minio minio123

3. use mc to create items
mc mb myminio/test1237 --region=eu-west-3
Bucket created successfully `myminio/test1237`.

mc cp /tmp/kube2.sh myminio/test1237
/tmp/kube2.sh:                   3.54 KiB / 3.54 KiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 561.10 KiB/s 0s

4. list the bucket content and see its empty with mc and the GUI
mc ls myminio/test1237

5. see that on the filesystem, bucket and object are existing:

ls  /home/dlake/appli/minio/test1237/
kube2.sh

## Context
This only fails when i define a xfs as storage. works when i define /tmp which is a tmpfs

## Your Environment

* Version used (`minio version`):
 mc version
Version: 2019-09-11T20:17:47Z
Release-tag: RELEASE.2019-09-11T20-17-47Z
Commit-id: 54ee3a280031adabc49a8309b74e5786cf266706

./minio version
Version: 2019-09-11T19:53:16Z
Release-Tag: RELEASE.2019-09-11T19-53-16Z
Commit-ID: 53e4887e02b94ed37dea8c5173330f17548fe122

disks mount:

OK /tmp : 
tmpfs on /tmp type tmpfs (rw,seclabel)

KO /home/dlake/appli/minio : 
/dev/mapper/applvg1-dlakelv00 on /home/dlake/appli type xfs (rw,nodev,relatime,seclabel,attr2,inode64,noquota)

* Server type and version:
* Operating System and version (`uname -a`):
uname -a
Linux lxin0035ev 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

* Link to your project:

**Comment by demetthyl** [comment]
i also tried using gateway nas and i have the same behavior : OK when targeting /tmp, KO when target xfs

**Comment by nitisht** [comment]
Can you check once with `RELEASE.2019-09-18T21-55-05Z ` @demetthyl , most probably you're seeing issue related to this fix https://github.com/minio/minio/pull/8240

**Comment by kannappanr** [comment]
@demetthyl Please test with the latest release and get back to us if you still see the issue. Closing this issue for now as answered.

**Comment by demetthyl** [comment]
guys,
i confirm that your yesterday night release works, thank you very much for releasing so fast!

Cheers,
Guillaume
