### ISSUE TITLE
Docker Browser Access in startup message ignores run settings

### ISSUE THREAD

**Issue by vikingjs** [minio/minio#8274]
When starting the Docker image, a message is given that can be incorrect.

I started the server with the following:

    docker run -p 9090:9000 minio/minio:RELEASE.2019-09-18T21-55-05Z server /my/data/dir

Note that I am mapping the server to host port 9090, as 9000 was already in use.

When starting up, I got the message:

> Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000
>
>Browser Access:
>   http://172.17.0.2:9000  http://127.0.0.1:9000

Which ignored the actual ports I specified. Not a huge deal, but it caused a moment of confusion and undermined confidence.

I'm running on MacOS 10.14.5, Docker version 18.09.2, build 6247962

**Comment by harshavardhana** [comment]
@vikingjs we can't know what you are trying to bind to using docker CLI from MinIO - this is true with nginx or any http service that you can ask. 

To keep peace of mind just use `docker -p 9000:9000` don't change ports if you do change ports then use it like this

```
docker -p 9090:9090 .... minio server --address ":9090" /mnt/data
```

**Comment by vikingjs** [comment]
You chose a port for minio that has long been used for php-fpm. I would suggest that if you can't get the proper information to display, then don't say anything — or at least make the language less absolute. It comes across as unprofessional when the first thing I see from your product is incorrect.

**Comment by harshavardhana** [comment]
@vikingjs no one owns port in Unix - there are known standard ports which are < 1024  and then rest are for taken. Officially ports beyond 1024 can be taken by any running process. 9000 is assigned a name https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=90&page=3 by IANA which not even assigned to php-fpm.  So every software is free to make such choices and there is no hard written rule.

So I don't think what you say makes sense or at the least technically not right. If you have a favorite port use --address to provide what you want there is a way around it. If you are not happy with that make a technical argument if there are better ways to take ports or auto port pickup based available ports we always entertain all technically sound arguments.

Closing the conversation here feel free to join our slack channel, if you wish to discuss this further.
