### ISSUE TITLE
Status of the buckets in the web interface "MinIO Browser"

### ISSUE THREAD

**Issue by kislik** [minio/minio#8280]
It will be awesome if we get some new feature - "The current status of the bucket" or "Status of 
directories in the bucket" (or current statistic) in the web interface ("MinIO Browser").

Why is it necessary?
For example, when you trying to upload a big bunch of new data in the bucket and at the same times you deleted another one (directory with millions of files) you will probably get a hang of yours disks subsystem. But you can avoid this one if you will be an able watching current statistic in your web interface.

I can illustrate the behavior on the graphic that happened on my servers:
On this picture, we can see that Minio disks - "sdc" and "sdd" have a lot of operations in the queue and it happened because I can't able to see (in web) that another one system administrator executed deletion of huge bucket =)
![disk_read_io](https://user-images.githubusercontent.com/11527999/65310477-0f045e80-db97-11e9-84e6-8f2478da0588.png)
As a result, we get disks 100% utilization:
![disks_utillization](https://user-images.githubusercontent.com/11527999/65311265-acac5d80-db98-11e9-866c-f3d412a77e00.png)

**Comment by nitisht** [comment]
we'll see if this is something we can do @kislik

**Comment by harshavardhana** [comment]
We are planning to add accounting per bucket this is part of the user and usage accounting which is under implementation.
