### ISSUE TITLE
Minio STS (using Client grants) Access and Secret key is not working in Java Client SDK

### ISSUE THREAD

**Issue by mohitrajvardhan17** [minio/minio#8281]
## Expected Behavior

Should be able to get bucket list using Minio Java Client SDK and below mentioned code:

Code for reference:
https://github.com/minio/minio-java/blob/master/examples/ListBuckets.java

STS Access and Secret key for Reference:
<?xml version="1.0" encoding="UTF-8"?>
<AssumeRoleWithClientGrantsResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
    <AssumeRoleWithClientGrantsResult>
        <AssumedRoleUser>
            <Arn></Arn>
            <AssumeRoleId></AssumeRoleId>
        </AssumedRoleUser>
        <Credentials>
            <AccessKeyId>WWKKX3LRDL9A1PS2Y6JG</AccessKeyId>
            <SecretAccessKey>Iu5MaJ6ROru6JkgQMxkWsHEh6maHSA1Q+0sf1ch0</SecretAccessKey>
            <Expiration>2019-09-20T22:35:05Z</Expiration>
            <SessionToken>eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJXV0tLWDNMUkRMOUExUFMyWTZKRyIsImFjciI6IjEiLCJhdWQiOlsibWFzdGVyLXJlYWxtIiwiYWNjb3VudCJdLCJhdXRoX3RpbWUiOjAsImF6cCI6ImFwcC1taW5pby1jbGllbnQiLCJjbGllbnRBZGRyZXNzIjoiMTI3LjAuMC4xIiwiY2xpZW50SG9zdCI6IjEyNy4wLjAuMSIsImNsaWVudElkIjoiYXBwLW1pbmlvLWNsaWVudCIsImVtYWlsIjoic2VydmljZS1hY2NvdW50LWFwcC1taW5pby1jbGllbnRAcGxhY2Vob2xkZXIub3JnIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJleHAiOjE1NjkwMTg5MDUsImlhdCI6MTU2ODk4MjkwNSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgyL2F1dGgvcmVhbG1zL21hc3RlciIsImp0aSI6ImE0MDBmY2Q2LTM4ODktNGIwZS1hMGYwLTJjZmVlOTc3NWI1MiIsIm5iZiI6MCwicG9saWN5IjoicmVhZHdyaXRlIiwicHJlZmVycmVkX3VzZXJuYW1lIjoic2VydmljZS1hY2NvdW50LWFwcC1taW5pby1jbGllbnQiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiY3JlYXRlLXJlYWxtIiwib2ZmbGluZV9hY2Nlc3MiLCJhZG1pbiIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19LCJhcHAtbWluaW8tY2xpZW50Ijp7InJvbGVzIjpbInVtYV9wcm90ZWN0aW9uIl19LCJtYXN0ZXItcmVhbG0iOnsicm9sZXMiOlsidmlldy1pZGVudGl0eS1wcm92aWRlcnMiLCJ2aWV3LXJlYWxtIiwibWFuYWdlLWlkZW50aXR5LXByb3ZpZGVycyIsImltcGVyc29uYXRpb24iLCJjcmVhdGUtY2xpZW50IiwibWFuYWdlLXVzZXJzIiwicXVlcnktcmVhbG1zIiwidmlldy1hdXRob3JpemF0aW9uIiwicXVlcnktY2xpZW50cyIsInF1ZXJ5LXVzZXJzIiwibWFuYWdlLWV2ZW50cyIsIm1hbmFnZS1yZWFsbSIsInZpZXctZXZlbnRzIiwidmlldy11c2VycyIsInZpZXctY2xpZW50cyIsIm1hbmFnZS1hdXRob3JpemF0aW9uIiwibWFuYWdlLWNsaWVudHMiLCJxdWVyeS1ncm91cHMiXX19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJzZXNzaW9uX3N0YXRlIjoiNzQ4YTVlOGMtY2E0My00OWY5LWI0ZTItODVjODlmOTU4ZWY4Iiwic3ViIjoiOTg0ZWVhMmItZjBmNi00M2FhLWFmNTYtOTcwNGM3NTAyODQzIiwidHlwIjoiQmVhcmVyIn0.H0821hXN8wYdiOKZwY__RDKLIvcU98ooDBFCQmPjnW-jT3WVVJPRcklADtWeXTalwahmzkTxLtG7MM4oXxXP_g</SessionToken>
        </Credentials>
        <SubjectFromToken>984eea2b-f0f6-43aa-af56-9704c7502843</SubjectFromToken>
    </AssumeRoleWithClientGrantsResult>
    <ResponseMetadata>
        <RequestId>15C626AC3A2A2763</RequestId>
    </ResponseMetadata>
</AssumeRoleWithClientGrantsResponse>

## Current Behavior

Getting below mentioned error at server side 

Minio Server Error for reference:
localhost [REQUEST s3.ListBuckets] 13:00:49.319
localhost GET /
localhost Host: localhost:9000
localhost X-Amz-Date: 20190920T130049Z
localhost Accept-Encoding: gzip
localhost Authorization: AWS4-HMAC-SHA256 Credential=WWKKX3LRDL9A1PS2Y6JG/20190920/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=a42bce0a539f5f3d6f5d4d9b1210c378d2add134a3170784cad61267911c4f86
localhost Connection: Keep-Alive
localhost Content-Length: 0
localhost User-Agent: MinIO (amd64; amd64) minio-java/dev
localhost X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost
localhost [RESPONSE] [13:00:49.319] [ Duration 338µs  🠉 104 B  🠋 524 B ]
localhost 403 Forbidden
localhost Content-Type: application/xml
localhost Server: MinIO/RELEASE.2019-09-18T21-55-05Z
localhost Vary: Origin
localhost X-Amz-Request-Id: 15C6270B37C1213A
localhost X-Xss-Protection: 1; mode=block
localhost Accept-Ranges: bytes
localhost Content-Length: 267
localhost Content-Security-Policy: block-all-mixed-content
localhost <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidTokenId</Code><Message>The security token included in the request is invalid</Message><Resource>/</Resource><RequestId>15C6270B37C1213A</RequestId><HostId>b5339471-16fc-4955-873f-07a775e5433b</HostId></Error>

## Steps to Reproduce (for bugs)

1. Configure minio server into STS mode using Keycloak and ETCD
2. Generate an access token using client credential flow.
3. Call the minio AssumeRoleWithClientGrants API
Sample Request
http://localhost:9000?Action=AssumeRoleWithClientGrants&DurationSeconds=3600&Token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJhVDNhNnBJSF9xVnB5NjZ3cVFDMVd2ZUtWdGF0Q0xLQlZwWDBab3pGbkdJIn0.eyJqdGkiOiJhNDAwZmNkNi0zODg5LTRiMGUtYTBmMC0yY2ZlZTk3NzViNTIiLCJleHAiOjE1NjkwMTg5MDUsIm5iZiI6MCwiaWF0IjoxNTY4OTgyOTA1LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODIvYXV0aC9yZWFsbXMvbWFzdGVyIiwiYXVkIjpbIm1hc3Rlci1yZWFsbSIsImFjY291bnQiXSwic3ViIjoiOTg0ZWVhMmItZjBmNi00M2FhLWFmNTYtOTcwNGM3NTAyODQzIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYXBwLW1pbmlvLWNsaWVudCIsImF1dGhfdGltZSI6MCwic2Vzc2lvbl9zdGF0ZSI6Ijc0OGE1ZThjLWNhNDMtNDlmOS1iNGUyLTg1Yzg5Zjk1OGVmOCIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiY3JlYXRlLXJlYWxtIiwib2ZmbGluZV9hY2Nlc3MiLCJhZG1pbiIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsibWFzdGVyLXJlYWxtIjp7InJvbGVzIjpbInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwidmlldy1yZWFsbSIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwiY3JlYXRlLWNsaWVudCIsIm1hbmFnZS11c2VycyIsInF1ZXJ5LXJlYWxtcyIsInZpZXctYXV0aG9yaXphdGlvbiIsInF1ZXJ5LWNsaWVudHMiLCJxdWVyeS11c2VycyIsIm1hbmFnZS1ldmVudHMiLCJtYW5hZ2UtcmVhbG0iLCJ2aWV3LWV2ZW50cyIsInZpZXctdXNlcnMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYXV0aG9yaXphdGlvbiIsIm1hbmFnZS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX0sImFwcC1taW5pby1jbGllbnQiOnsicm9sZXMiOlsidW1hX3Byb3RlY3Rpb24iXX19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJjbGllbnRIb3N0IjoiMTI3LjAuMC4xIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJjbGllbnRJZCI6ImFwcC1taW5pby1jbGllbnQiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzZXJ2aWNlLWFjY291bnQtYXBwLW1pbmlvLWNsaWVudCIsImNsaWVudEFkZHJlc3MiOiIxMjcuMC4wLjEiLCJlbWFpbCI6InNlcnZpY2UtYWNjb3VudC1hcHAtbWluaW8tY2xpZW50QHBsYWNlaG9sZGVyLm9yZyIsInBvbGljeSI6InJlYWR3cml0ZSJ9.ES3FUPxYhzFX-6_krlzqkALV4kr_yaOJQhJfQgPPGD1lgQMA_C0zqLB9KQpamJsiAqtXAuz1zG1Rvt0hshNfKV2zGwJztVjl2PVJVfsVqxbZkv8UpobkT-iHBLBeOeCvozsgpiBhBofJXyCmISv_LoX61FR7WEiDZf1dU4zUbqIYYSGNovyQSrOQAKAqgX00IfKUk1TgsXR_wzqywfTdaHlwI5AYZfrnwkNP2lcKLIdZquOaNOWukmkUYmkSWXzypZds_nj4zwQWJo2nHW9WDaDMURW5Fg-CKlNz83YS1FkqHW_2KM7MQecq8JqIttlh5lWuyxpv1vTzbB3rXcUI-A&Version=2011-06-15
4. Use the Access and Secret key to get the bucket list

## Your Environment

* Version used (`minio version`):
Version: 2019-09-18T21:55:05Z
Release-Tag: RELEASE.2019-09-18T21-55-05Z
Commit-ID: 456ce4cc92b6a24cc6087bebacd22f3d810d5de7
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
Linux minio-5c5764898c-v5xb8 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 Linux
* Link to your project:

**Comment by harshavardhana** [comment]
You need to set Session Token ID minio-java SDK doesn't support STS yet. Closing this issue is being tracked at https://github.com/minio/minio-java/issues/793
