### ISSUE TITLE
LDAP STS no login and no query 

### ISSUE THREAD

**Issue by fdefilippo** [minio/minio#8284]
I'm trying to configure minio with ldap sts but no query at all to ldap server.

## Expected Behavior

Login & Query to ldap server 

## Current Behavior

Configuring minio with:

export MINIO_IDENTITY_LDAP_SERVER_ADDR='ldaps://127.0.0.1:636'
export MINIO_IDENTITY_LDAP_USERNAME_FORMAT='uid=${username},ou=Users,dc=l,dc=org'
export MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN='ou=Groups,dc=l,dc=org'
export MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER='(&(objectclass=groupOfNames)(member=${usernamedn}))'
export MINIO_IDENTITY_LDAP_GROUP_NAME_ATTRIBUTE='cn'
export MINIO_IDENTITY_LDAP_STS_EXPIRY_DURATION=60
export MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=true
export MINIO_HTTP_TRACE=~/work/minio/minio.log
export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=minio123
export MINIO_BROWSER=off
./minio server --address 172.31.0.1:1090 ./data

created a bucket with an associated canned policy

tested with awscli:

# aws configure
AWS Access Key ID [****************user]: testuser
AWS Secret Access Key [****************0rd]: Password
Default region name [us-west-1]:
Default output format [json]:

aws configure set default.s3.signature_version s3v4
aws --endpoint-url https://172.31.0.1:1090 --no-verify-ssl s3 ls

An error occurred (InvalidAccessKeyId) when calling the ListBuckets operation: The access key ID you provided does not exist in our records.

and not ldap query (verifyed with tcpdump on port 636)

# ./mc admin policy  list mfts --insecure
readonly
readwrite
writeonly
ciao-nextcloud-rw

# ls -l data/.minio.sys/config/iam/policydb/groups/
-rw-r--r-- 1 root root 42 Sep 21 17:39 nextcloud.json

#./mc admin policy  info mfts ciao-nextcloud-rw --insecure
{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:ListBucketMultipartUploads","s3:GetBucketLocation","s3:ListBucket"],"R
esource":["arn:aws:s3:::ciao"]},{"Effect":"Allow","Action":["s3:PutObject","s3:AbortMultipartUpload","s3:DeleteObject","s3:GetObject","s3:L
istMultipartUploadParts"],"Resource":["arn:aws:s3:::ciao/*"]}]}

the ldap works as you can see from the query below:

# ldapsearch -x -H ldaps://127.0.0.1 -s base
# extended LDIF
#
# LDAPv3
# base <dc=l,dc=org> (default) with scope baseObject
# filter: (objectclass=*)
# requesting: ALL
#

# l.org
dn: dc=l,dc=org
objectClass: top
objectClass: dcObject
objectClass: organization
o: l
dc: l
description: l

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1

## Your Environment
minio version
Version: 2019-09-18T21:55:05Z
Release-Tag: RELEASE.2019-09-18T21-55-05Z
Commit-ID: 456ce4cc92b6a24cc6087bebacd22f3d810d5de7

# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core)
Release:        7.6.1810
Codename:       Core

**Comment by harshavardhana** [comment]
That is not how you would use ldap integration @fdefilippo - you are missing the point of generating STS tokens. 

AWS CLI cannot support MinIO STS extensions @fdefilippo

**Comment by harshavardhana** [comment]
Look at the Go program for the overall flow

https://github.com/minio/minio/blob/master/docs/sts/ldap.go

**Comment by kannappanr** [comment]
@fdefilippo Closing this issue. Please feel free to reach out to us at https://slack.min.io for further questions on this issue.
