### ISSUE TITLE
The minIO server UI not update the used disk after backuping data

### ISSUE THREAD

**Issue by lirany1** [minio/minio#8290]
```
[root@localhost ~]# du -sh /var/lib/data/minio/backup/2019/09/
**93M**     /var/lib/data/minio/backup/2019/09/
```
and in the UI it's still with the previous amount

## Your Environment
[root@localhost ~]# mc version
Version: 2019-09-05T23:43:50Z
Release-tag: RELEASE.2019-09-05T23-43-50Z
Commit-id: 22ab93da0f995172520c8ddf182bff3d10ca5b66
[root@localhost ~]#

![2019-09-23_10-18-54](https://user-images.githubusercontent.com/12675378/65407745-2a1bdc00-ddec-11e9-8cea-545ce7729867.jpg)

**Comment by harshavardhana** [comment]
The value is updated every 12hrs @lirany1

**Comment by lirany1** [comment]
@harshavardhana Is't configurable?

**Comment by harshavardhana** [comment]
> @harshavardhana Is't configurable?

No it is not..

**Comment by kannappanr** [comment]
@lirany1 Closing this issue as answered. Please feel free to reach out to us at https://slack.min.io for further such questions.
