### ISSUE TITLE
STS LDAP breaks IAM configuration?

### ISSUE THREAD

**Issue by phiser678** [minio/minio#8293]
## Expected Behavior

`mc admin group list TARGET`
and
`mc admin user list TARGET`
should report but waits forever with errors on the minio server:
API: ListGroups()
...
Error: Specified IAM action is not allowed under the current configuration
       5: cmd/api-errors.go:1694:cmd.toAPIErrorCode()
       4: cmd/admin-handlers.go:993:cmd.toAdminAPIErrCode()
       3: cmd/admin-handlers.go:1001:cmd.toAdminAPIErr()
       2: cmd/admin-handlers.go:1186:cmd.adminAPIHandlers.ListGroups()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()

I guess I'm missing some documentation.
`mc admin config get TARGET`
shows an empty ldapserverconfig configuration which doesn't seems right

## Possible Solution
Some more documentation in the STS LDAP on how to continue the config?

## Steps to Reproduce (for bugs)

1. Setup STS LDAP
2. add mc admin policy set TARGET readwrite group=*desired_group*
3 . mc admin group list TARGET 

## Your Environment

* Version used (`minio version`): Version: 2019-09-18T21:55:05Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
STS LDAP if enabled replaces multi-users

**Comment by kannappanr** [comment]
@phiser678 Closing this issue as answered. Please feel free to reach out to us at https://slack.min.io for such questions.

**Comment by phiser678** [comment]
But if you put policies on users and groups how can you check them then? I looked in the .minio.sys/config/iam/ directories where they seemed to be stored, but the part.1 is a binairy file.

**Comment by harshavardhana** [comment]
They are erasure coded - they are meant for MinIO to read them and parse them.

**Comment by phiser678** [comment]
So, how can someone see the policies of the users and groups when using STS LDAP then? Is here a way to read them with `mc`?

**Comment by harshavardhana** [comment]
There is no way you can only set the policies for the user, you cannot list users or create groups. We don't expect those permissions from LDAP.

Only thing you create on MinIO is policies to be applied for incoming LDAP users

**Comment by phiser678** [comment]
I know, that's the whole point. If you set policies for the LDAP users and groups how you know which one you applied after a while? There could be 2 or more admins maintaining the policies. There should be some interface which tells for this group you applied this policy and for that user you applied that policy, just like you do without the STS LDAP config and normal users and groups. Otherwise someone has to maintain a double bookkeeping, while this info is in the minio servers, you cannot now query what policies are set.

**Comment by harshavardhana** [comment]
You can query by using `mc admin policy` - unfortunately that's not yet correctly documented yet. Which we shall fix from the point of view from `mc`

You should join our slack for further questions https://slack.min.io - we will clarify all your questions in this area.

**Comment by phiser678** [comment]
To make this clear, with `mc admin policy` you create and list policies, but this it is not what I issued. It's the list of users and group and which policy are apllied.
Sorry, the Slack invite link is no longer active, if you would be so kind to send me a reinvite? Thanks.

**Comment by harshavardhana** [comment]
> To make this clear, with `mc admin policy` you create and list policies, but this it is not what I issued. It's the list of users and group and which policy is applied.

Yes, the reason is that now users are managed at your LDAP server. Meaning you create users on LDAP/AD their login creds will be honored through MinIO STS API. 

Multi-users cannot co-exist with LDAP/AD because users on LDAP/AD might cause conflict with a multi-user system with duplicated names etc. That is why when LDAP is chosen you can't manage users on MinIO. You are actively indicating that to MinIO to disable its multi-user system and honor LDAP/AD credentials.

> Sorry, the Slack invite link is no longer active, if you would be so kind to send me a reinvite? Thanks.

This is fixed please try again.

**Comment by phiser678** [comment]
It's going to be implemented in https://github.com/minio/minio/pull/8307 with `mc admin policy list  TARGET`.

**Comment by harshavardhana** [comment]
> It's going to be implemented in #8307 with `mc admin policy list TARGET`.

To know what you want you should do `mc admin user info NICK` to get the policy that you stored associated with your LDAP user.
