### ISSUE TITLE
 no endpoint pointing to the local machine is found

### ISSUE THREAD

**Issue by wlwcjl** [minio/minio#8298]
## Expected Behavior
I hope to build Minio distributed cluster by  "Federation Quickstart Guide" guidebook！

## Current Behavior
I configured the CoreDNS server and the etcd cluster，but there are something wrong with no endpoint pointing to the local machine is found.

## Steps to Reproduce (for bugs)
1. I built a CoreDNS server
2. I configured the etcd cluster
3. I started the CoreDNS server
4. I configured the Minio cluster by "Federation Quickstart Guide" guidebook

## Context
When i start the minio cluster, there are something wrong with **no endpoint pointing to the local machine is found.  Please provide correct combination of local/remote paths**

export MINIO_ETCD_ENDPOINTS="http://10.0.19.18:2379"
export MINIO_DOMAIN=rainier.com
export MINIO_PUBLIC_IPS=10.0.19.18,10.0.19.83,10.0.19.87

./minio server http://rack1.host1.rainier.com/home/rainier/cluster-node-1 \
               http://rack1.host1.rainier.com/mnt/sda/cluster-node-1 \
               http://rack2.host2.rainier.com/home/rainier/cluster-node-1 \
               http://rack2.host2.rainier.com/mnt/sda/cluster-node-1 \
               http://rack3.host3.rainier.com/home/rainier/cluster-node-1 \
               http://rack3.host3.rainier.com/mnt/sda/cluster-node-1

## Your Environment
* Version used (`minio version`):2019-08-29T00:25:01Z
* Environment name and version (e.g. nginx 1.9.1): etcd API: 3.3/CoreDNS verision:CoreDNS-1.6.3  linux/amd64, go1.12.9, 37b9550
* Server type and version: 
* Operating System and version (`uname -a`): CentOS 7.5
* Link to your project:

**Comment by kannappanr** [comment]
@wlwcjl Must be something wrong in the setup. Will try to follow the steps and see if we run into the same issue as you did.

**Comment by Praveenrajmani** [comment]
@wlwcjl Can you do `dig http://rack2.host2.rainier.com` and see where it resolved to?

**Comment by Praveenrajmani** [comment]
Can you also paste the `Corefile`?

**Comment by harshavardhana** [comment]
Closing this issue as stale.
