### ISSUE TITLE
example in README doesn't work

### ISSUE THREAD

**Issue by kahing** [minio/minio#830]
README says we should launch minio as:

```
./minio mode memory limit 12GB expire 2h
```

but after I build minio from source, it says mode is not a valid command:

```
minio: <ERROR> Old Golang runtime version ‘150’ detected., ‘mc’ requires minimum go1.5 or later.
minio: <FATAL> Command not found: ‘mode’
```

(note the complain about go version, `go version` gives me `go version go1.5 linux/amd64`.

From the help strings, looks like one just starts minio with `minio server` and options are not accepted. Additionally `--debug` doesn't work, which makes it hard to check why `mc` doesn't work:

```
$ minio --debug --address "127.0.0.1:9000" server 
minio: <ERROR> Old Golang runtime version ‘150’ detected., ‘mc’ requires minimum go1.5 or later.
Starting minio server on: http://127.0.0.1:9000, PID: 11154
```

```
mc ls http://127.0.0.1:9000
mc: <ERROR> Old Golang runtime version ‘150’ detected., ‘mc’ requires minimum go1.5.1 or later. 
mc: <ERROR> Unable to list target ‘http://127.0.0.1:9000/’. The specified bucket is not valid.
```

Through trial and error, eventually I figured out that when there's no buckets, list buckets doesn't work:

```
$ mc mb http://127.0.0.1:9000/foo
mc: <ERROR> Old Golang runtime version ‘150’ detected., ‘mc’ requires minimum go1.5.1 or later. 
Bucket created successfully  ‘http://127.0.0.1:9000/foo’
$ mc ls http://127.0.0.1:9000
mc: <ERROR> Old Golang runtime version ‘150’ detected., ‘mc’ requires minimum go1.5.1 or later. 
[2015-09-17 14:30:43 PDT]     0B foo/
```

**Comment by harshavardhana** [comment]
> ./minio mode memory limit 12GB expire 2h

Ah all these are deprecated, i guess we should get rid of these docs. Let me fix them.

**Comment by harshavardhana** [comment]
I see you compiled from source, then these commands won't work anymore since things changed a bit over last couple of months. 

There are no more different modes of operation anymore, memory is now part of donut.  file mode is removed since donut already does this.

**Comment by kahing** [comment]
closing

**Comment by harshavardhana** [comment]
> minio: <ERROR> Old Golang runtime version ‘150’ detected., ‘mc’ requires minimum go1.5 or later.

Added a more rigorous check during compilation #834 - go1.5.1 is necessary, since some important bugs  were introduced in go1.5 related to interface{} checks and pointer conversions.

**Comment by harshavardhana** [comment]
Thanks for taking time on testing minio and mc @kahing appreciate it :-)
