### ISSUE TITLE
What SLOs/SLAs does minio have?

### ISSUE THREAD

**Issue by r-medina** [minio/minio#8301]
I'm looking to building a service on top of minio, but cannot find any documentation around what service level objectives or agreements minio adheres to.

i am aware that in practice the guarantees come mainly from the underlying hardware, but there is some performance and reliability cost associated with going through minio, so i'm wondering if someone could tell me:
- how much latency minio introduces on writes?
- what impact minio has on data availability?

**Comment by krishnasrinivas** [comment]
@r-medina object storage is mainly throughput oriented, minio chokes either the network(100gige) or the disks. CPU is not a bottleneck. Some benchmark numbers: https://min.io/resources/docs/MinIO-throughput-benchmarks-on-NVMe-SSD.pdf

Minio itself is light weight on resources and well optimized on memory and cpu.

For erasure coding we use https://github.com/klauspost/reedsolomon which takes advantage SIMD instructions (you can check the benchmark numbers posted there)

As you said Minio performs as well as the underlying hardware.

**Comment by kannappanr** [comment]
@r-medina Closing this issue as answered. Please feel free to reach out to us at https://slack.min.io for further such questions
