### ISSUE TITLE
Can't start Minio / Minio.service: Start request repeated too quickly.

### ISSUE THREAD

**Issue by rc042** [minio/minio#8302]
Hi!

First, I tried to join the Slack channel but the link seems to be broken (https://github.com/minio/minio-service).

Minio doesn't started with systemd but **works correctly when launched with the command line**.

Any help really appreciated!
Thanks

## Expected Behavior

I used the _minio.service_ file available at https://github.com/minio/minio-service and the service failed to start.

## Current Behavior

The error message is:
```
● minio.service - MinIO
   Loaded: loaded (/etc/systemd/system/minio.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-09-24 13:17:32 UTC; 34s ago
     Docs: https://docs.min.io
  Process: 25353 ExecStart=/usr/local/bin/minio server $MINIO_OPTS $MINIO_VOLUMES (code=exited, status=1/FAILURE)
  Process: 25352 ExecStartPre=/bin/bash -c if [ -z "${MINIO_VOLUMES}" ]; then echo "Variable MINIO_VOLUMES not set in /etc/default/minio"; exit 1; fi (code=exited, status=0/SUCCESS)
 Main PID: 25353 (code=exited, status=1/FAILURE)

Sep 24 13:17:32 aorus systemd[1]: minio.service: Service hold-off time over, scheduling restart.
Sep 24 13:17:32 aorus systemd[1]: minio.service: Scheduled restart job, restart counter is at 5.
Sep 24 13:17:32 aorus systemd[1]: Stopped MinIO.
Sep 24 13:17:32 aorus systemd[1]: minio.service: Start request repeated too quickly.
Sep 24 13:17:32 aorus systemd[1]: minio.service: Failed with result 'exit-code'.
Sep 24 13:17:32 aorus systemd[1]: Failed to start MinIO.
```
journalctl display an error but I don't find something relevant to correct it:
```
Sep 24 13:17:32 aorus minio[25353]: ERROR Failed to read root CAs (file access denied): file access denied
```

## Steps to Reproduce (for bugs)

1. Follow the step on https://github.com/minio and https://linuxhint.com/install_minio_ubuntu_1804/

I saw  https://github.com/minio/minio/issues/6772 but it doesn't help me.

## Context

I change my server, the old one is still working (Minio works fine on it).

## Your Environment

* Version used (`minio version`):
```
Version: 2019-09-18T21:55:05Z
Release-Tag: RELEASE.2019-09-18T21-55-05Z
Commit-ID: 456ce4cc92b6a24cc6087bebacd22f3d810d5de7
```
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):

```
Linux aorus 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
The server is hardened following the CIS: https://github.com/florianutz/Ubuntu1804-CIS

* Link to your project:

**Comment by rc042** [comment]
Hi again,

After more investigation, if I remove the User/Group from _minio.service_, the service start.

Seems a permission issue with _ERROR Failed to read root CAs (file access denied): file access denied_, I will continu to investigate.

**Comment by harshavardhana** [comment]
Thanks closing this issue @reedcrif

**Comment by yusufyilmazfr** [comment]
@reedcrif thank you for your answer. It worked for me! 😃🎉
But I didn't understand, why minio works after the removed user-groups 🤔
