### ISSUE TITLE
[resolved] Can't access image via browser after set bucket to public(instead, it redirect to login page)

### ISSUE THREAD

**Issue by xiebruce** [minio/minio#8305]
OS: `macOS Mojave 10.14.4 (18E226)`
minio version: `2019-09-18T21:55:05Z`
mc version: `mc version RELEASE.2019-09-24T01-36-20Z`
minio installed via: `brew install minio/stable/minio`
mc installed via `brew install minio/stable/mc`

---

I start `minio` server by using this command:
```
minio server --address 127.0.0.1:9003 /Users/bruce/data
```

Now, I can access it via browser, I create a bucket named `markdown` and upload some files, it works fine:
![image](https://user-images.githubusercontent.com/13575500/65570460-c6341780-df93-11e9-99f1-6c78223be812.png)

Then, I set my bucket to public read:
```
mc policy set public ~/data/markdown
```

![image](https://user-images.githubusercontent.com/13575500/65570552-0abfb300-df94-11e9-8047-55876a8de939.png)

If it is as expected, I can now access my files(images) in browser via some link like:
```
http://127.0.0.1:9003/2019/09/25/b2e96873f708b5f0e2b60ce4b0a2d001.jpg
```

But I can't, it redirect to login page once I visit this link in the browser:
![image](https://user-images.githubusercontent.com/13575500/65570879-3a22ef80-df95-11e9-98e5-8b46a32c1353.png)

image `2019/09/25/b2e96873f708b5f0e2b60ce4b0a2d001.jpg` is exists for sure:
![image](https://user-images.githubusercontent.com/13575500/65570856-28d9e300-df95-11e9-8e7f-d2f638c9302a.png)

So, how can I solve this issue?

**Comment by kanagarajkm** [comment]
The command to set the policy is wrong, the correct one is 
```
mc policy set public <ALIAS>/markdown
```
ALIAS is the name given by you while doing `mc config host add <ALIAS> ...`


And the object url will be 
```
http://127.0.0.1:9003/markdown/2019/09/25/b2e96873f708b5f0e2b60ce4b0a2d001.jpg
```
Note that `markdown` is missing in the url you have used.

**Comment by kannappanr** [comment]
Please take a look at our docs at https://docs.min.io/docs/minio-client-complete-guide.html
Please reach out to us at https://slack.min.io for further such questions.

**Comment by kevinhq** [comment]
I got same error on macOS catalina.
