### ISSUE TITLE
Showing file name as title, in signed urls preview

### ISSUE THREAD

**Issue by stoivo** [minio/minio#8306]
When you view a Pre-signed is there a way to pass the title of the page?

## Expected Behavior
I expect that there is an option pass a title 

## Current Behavior
Firefox used PDF.js to render the pdf and users the `filename*` in `response-content-disposition`. Chrome uses the id it was in minio as title 

![Screenshot 2019-09-25 at 11 15 11](https://user-images.githubusercontent.com/3492040/65587262-e0ff8f80-df85-11e9-95ce-95fbfbf215cd.png)

## Steps to Reproduce (for bugs)
the url I have used formated 
```
http://localhost:9000/snotr/gy7tbTHRt9D2XoxVW19VLmWr?
  response-content-disposition=inline; filename="Ordre_102.pdf"; filename*=UTF-8''Ordre_102.pdf
  &response-content-type=application/pdf
  &X-Amz-Algorithm=AWS4-HMAC-SHA256
  &X-Amz-Credential=U6M66SA3IZPAD5D6U741/20190925/eu-east-1/s3/aws4_request
  &X-Amz-Date=20190925T083421Z
  &X-Amz-Expires=300
  &X-Amz-SignedHeaders=host
  &X-Amz-Signature=6699397d7ba51f96bfe3643c9ea0ed44ea1e34a73e74bf27cbca41ad02a152ac
``` 
Original 
```
http://localhost:9000/snotr/gy7tbTHRt9D2XoxVW19VLmWr?response-content-disposition=inline%3B%20filename%3D%22Ordre_102.pdf%22%3B%20filename%2A%3DUTF-8%27%27Ordre_102.pdf&response-content-type=application%2Fpdf&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=U6M66SA3IZPAD5D6U741%2F20190925%2Feu-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190925T083421Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=6699397d7ba51f96bfe3643c9ea0ed44ea1e34a73e74bf27cbca41ad02a152ac
```

**Comment by kannappanr** [comment]
@stoivo If I understand the issue correctly, you are seeing this in specific versions of browser. I don't think MinIO can do much about it.

**Comment by kannappanr** [comment]
closing this issue now. If you feel I have misunderstood the issue, please let us know, we can re-open the issue. We can also be reached at https://min.io for questions like these

**Comment by stoivo** [comment]
I mean it more like a question if there is a way to pass what will be used as title of the page?

I am just stating that I noticed that different browser handeled it differently.
