### ISSUE TITLE
Error Occured uploading ......

### ISSUE THREAD

**Issue by wlwcjl** [minio/minio#8308]
## Expected Behavior
I hope to build Minio distributed cluster by "Federation Quickstart Guide" guidebook！

## Current Behavior

**Now  I can create buckets but I can not upload anything, when I upload file by google browser then the error message that "uploading file error"  displayed immediately。 how to resolve this problem? please help me, thank you very much !**

## Steps to Reproduce (for bugs)
1.I built a CoreDNS server which contains etcd plugins
2.I started the CoreDNS server
3.I configured the Minio cluster by "Federation Quickstart Guide" guidebook

## Context
the command ：

export MINIO_ACCESS_KEY=admin
export MINIO_SECRET_KEY=admin
export MINIO_ETCD_ENDPOINTS="http://10.0.19.18:2379,http://10.0.19.83:2379,
                                                        http://10.0.19.87:2379,http://10.0.19.49:2379"
export MINIO_DOMAIN=dxcc.com
export MINIO_PUBLIC_IPS=10.0.19.18,10.0.19.83,10.0.19.87,10.0.19.49

minio server http://rack{1...4}.dxcc.com/home/rainier/aa \ 
                            http://rack{1...4}.dxcc.com/mnt/sda/aa  \

## Your Environment

* Version used (`minio version`):2019-08-29T00:25:01Z
* Environment name and version (e.g. nginx 1.9.1): etcd API: 3.3/CoreDNS verision:CoreDNS-1.6.3 
* Server type and version:  
* Operating System and version (`uname -a`): CentOS 7.5
* Link to your project:

**Comment by vadmeste** [comment]
@wlwcjl thanks for reporting this issue.

It looks like the browser is not providing enough information about the reason for the issue.

Can you get familiar with `mc` first and try to upload that file using it and see if there is any error which can occur ?

**Comment by kannappanr** [comment]
@wlwcjl You can look at https://docs.min.io/docs/minio-client-complete-guide.html to get more information about how to use `mc` and the commands supported by it.

**Comment by kannappanr** [comment]
@wlwcjl Closing this issue as answered. Please feel free to reach out to us at https://slak.min.io for further such questions
