### ISSUE TITLE
ListBuckets doesn't work when there's no buckets

### ISSUE THREAD

**Issue by kahing** [minio/minio#831]
```
mc ls http://127.0.0.1:9000
mc: <ERROR> Unable to list target ‘http://127.0.0.1:9000/’. The specified bucket is not valid.

$ mc mb http://127.0.0.1:9000/foo
Bucket created successfully  ‘http://127.0.0.1:9000/foo’

$ mc ls http://127.0.0.1:9000
[2015-09-17 14:30:43 PDT]     0B foo/
```

**Comment by harshavardhana** [comment]
> mc: <ERROR> Unable to list target ‘http://127.0.0.1:9000/’. The specified bucket is not valid.

A recent bug introduced in 'mc', you should open the bug on - https://github.com/minio/mc

**Comment by harshavardhana** [comment]
https://github.com/minio/mc/pull/1107, this should fix this issue..

**Comment by harshavardhana** [comment]
Can you test again with 'go get -u github.com/minio/mc' ?

**Comment by kahing** [comment]
:+1:
