### ISSUE TITLE
Updating Minio distributed with kafka notify support failing

### ISSUE THREAD

**Issue by nodesocket** [minio/minio#8331]
I am attempting to update my Minio distributed mode cluster running on Kubernetes with Kafka notify support. Locally on my machine I am able to download the config and then update it with the following:

```
"kafka": {
    "1": {
        "enable": true,
        "brokers": ["kafka.kubeless.svc.cluster.local"],
        "topic": "bucketevents",
        "queueDir": "",
        "queueLimit": 0,
        "tls": {
            "enable": false,
            "skipVerify": false,
            "clientAuth": 0
        },
        "sasl": {
            "enable": false,
            "username": "",
            "password": ""
        }
    }
}
```

`kafka.kubeless.svc.cluster.local` is a service endpoint that resolves inside of Kubernetes which the Minio pods should be able to hit. However, when I try to update Minio with this config it errors with:

```
mc admin config set my-minio-cluster < minio-config.json

mc: <ERROR> Cannot set server configuration file. kafka(1): kafka: client has run out of available brokers to talk to (Is your cluster reachable?).
```

How can I accomplish this update?

**Comment by kannappanr** [comment]
Not sure if solution proposed in this link still applies. https://github.com/Shopify/sarama/issues/941

If not We will take a look.

**Comment by nodesocket** [comment]
@kannappanr my local MC client cannot access kafka.kubeless.svc.cluster.local but the Minio pods inside of Kubernetes can. Is this a requirement that MC can communicate with Kafka?

**Comment by nodesocket** [comment]
I feel stupid, adding the port `kafka.kubeless.svc.cluster.local:9092` worked.

> Setting new MinIO configuration file has been successful.
>  Please restart your server with `mc admin service restart ...`.
