### ISSUE TITLE
Client says Server not initialized, while all nodes are up.

### ISSUE THREAD

**Issue by Meshkati** [minio/minio#8332]
Hi, today one of our 16 nodes failed, we fixed the problem and started the machine again, and a bad latency ( about 5 secs for each requests ) happened. So we tried to reset the cluster with Minio Client, the `mc admin service restart minio-opr` stuck for 10 minutes, so we checked systemctl logs inside the machines and all minio services were in load state.
We finally restarted each process inside machines by `systemctl restart minio.service`, nodes came up and say that `Started MinIO`. But no operation with SDK or even Minio Client works. All say that `Server not initialized, please try again.`. While inside the system logs they say are all up.
Note that we tried to restart some nodes, and after each restart, all other nodes says that that node is gone, so perhaps there is no communication issue between the nodes.
We can also open the browser view and login on it, but there is no buckets in it :(
## Expected Behavior

No latency after node failure, No problem after cluster restart.
## Current Behavior

Can't connect to the cluster with MinioClient and SDK.
## Steps to Reproduce (for bugs)

1. Restart a single node.
2. Reset the whole cluster with MinioClient
3. Reset each node with systemctl

## Your Environment

* Version used (`latest`):

**Comment by harshavardhana** [comment]
> Hi, today one of our 16 nodes failed, we fixed the problem and started the machine again, and a bad latency ( about 5 secs for each requests ) happened. So we tried to reset the cluster with Minio Client, the `mc admin service restart minio-opr` stuck for 10 minutes, so we checked systemctl logs inside the machines and all minio services were in load state.
> We finally restarted each process inside machines by `systemctl restart minio.service`, nodes came up and say that `Started MinIO`. But no operation with SDK or even Minio Client works. All say that `Server not initialized, please try again.`. While inside the system logs they say are all up.
> Note that we tried to restart some nodes, and after each restart, all other nodes says that that node is gone, so perhaps there is no communication issue between the nodes.

@Meshkati nodes may be up but they are not communicating with each other here. can you capture `journalctl` logs for the MinIO service? also when running under systemd you need to make sure that 
if you haven't set 

```
Restart=always
```

Because this can interfere with `mc admin server restart` as it tries to restart the service.

**Comment by Meshkati** [comment]
Here is the log:
```
Sep 29 09:07:55 prd minio[10419]: net/http.(*conn).serve(0xc00eaa41e0, 0x1c36a80, 0xc001169cc0)
Sep 29 09:07:55 prd minio[10419]:         /usr/local/go/src/net/http/server.go:1878 +0x851
Sep 29 09:07:55 prd minio[10419]: created by net/http.(*Server).Serve
Sep 29 09:07:55 prd minio[10419]:         /usr/local/go/src/net/http/server.go:2884 +0x2f4
Sep 29 09:08:05 prd systemd[1]: Stopping MinIO...
Sep 29 09:08:05 prd minio[10419]: Exiting on signal: TERMINATED
Sep 29 09:08:10 prd systemd[1]: minio.service: Main process exited, code=exited, status=1/FAILURE
Sep 29 09:08:10 prd systemd[1]: Stopped MinIO.
Sep 29 09:08:10 prd systemd[1]: minio.service: Unit entered failed state.
Sep 29 09:08:10 prd systemd[1]: minio.service: Failed with result 'exit-code'.
Sep 29 09:15:02 prd systemd[1]: Stopped MinIO.
Sep 29 09:18:02 prd systemd[1]: Starting MinIO...
Sep 29 09:18:02 prd systemd[1]: Started MinIO.
```

Yeah we had `Restart=always` in our service files.

**Comment by harshavardhana** [comment]
looks like there is a crash here @Meshkati you need to capture the entire trace.  Also please paste you MinIO version `minio version` - thanks

**Comment by Meshkati** [comment]
I think that crash is because we killed the process entirely, after `systemctl stop` stuck for another 10 minutes :D I'll add more logs here.
Our version was `Version: 2019-08-11` today, after all of those failures, we updated the minio to `2019-09-26`, but it didn't help either. So we rolled back to `Version: 2019-08-11` again afw moments ago, and the problem still exists.

Here is the logs:
https://paste.ubuntu.com/p/qMdmWbj8W5/

**Comment by harshavardhana** [comment]
> I think that crash is because we killed the process entirely, after `systemctl stop` stuck for another 10 minutes :D I'll add more logs here.
> Our version was `Version: 2019-08-11` today, after all of those failures, we updated the minio to `2019-09-26`, but it didn't help either. So we rolled back to `Version: 2019-08-11` again afw moments ago, and the problem still exists

I would suggest don't rollback it is important to update due to security fix release @Meshkati

**Comment by Meshkati** [comment]
Yeah we will update again, but our service is down for 2 hours and we don't care about that at this moment :D

**Comment by harshavardhana** [comment]
> Yeah we will update again, but our service is down for 2 hours and we don't care about that at this moment :D

AFAICS here 

```
Sep 29 10:42:42 prd-minio-001.c002.host.com minio[19830]: Unable to connect to http://prd-minio-009.c002.host.com:9000/media/files/minio: Post http://prd-minio-009.c002.host.com:9000/minio/storage/v9/media/files/minio/getinstanceid?: dial tcp 192.168.2.211:9000: connect: connection refused
Sep 29 10:42:42 prd-minio-001.c002.host.com minio[19830]: Unable to connect to http://prd-minio-010.c002.host.com:9000/media/files/minio: Post http://prd-minio-010.c002.host.com:9000/minio/storage/v9/media/files/minio/getinstanceid?: dial tcp 192.168.2.212:9000: connect: connection refused
Sep 29 10:42:42 prd-minio-001.c002.host.com minio[19830]: Unable to connect to http://prd-minio-011.c002.host.com:9000/media/files/minio: Post http://prd-minio-011.c002.host.com:9000/minio/storage/v9/media/files/minio/getinstanceid?: dial tcp 192.168.2.213:9000: connect: connection refused
Sep 29 10:42:42 prd-minio-001.c002.host.com minio[19830]: Unable to connect to http://prd-minio-012.c002.host.com:9000/media/files/minio: Post http://prd-minio-012.c002.host.com:9000/minio/storage/v9/media/files/minio/getinstanceid?: dial tcp 192.168.2.214:9000: connect: connection refused
Sep 29 10:42:42 prd-minio-001.c002.host.com minio[19830]: Unable to connect to http://prd-minio-013.c002.host.com:9000/media/files/minio: Post http://prd-minio-013.c002.host.com:9000/minio/storage/v9/media/files/minio/getinstanceid?: dial tcp 192.168.2.215:9000: connect: connection refused
Sep 29 10:42:42 prd-minio-001.c002.host.com minio[19830]: Unable to connect to http://prd-minio-014.c002.host.com:9000/media/files/minio: Post http://prd-minio-014.c002.host.com:9000/minio/storage/v9/media/files/minio/getinstanceid?: dial tcp 192.168.2.216:9000: connect: connection refused
Sep 29 10:42:42 prd-minio-001.c002.host.com minio[19830]: Unable to connect to http://prd-minio-015.c002.host.com:9000/media/files/minio: Post http://prd-minio-015.c002.host.com:9000/minio/storage/v9/media/files/minio/getinstanceid?: dial tcp 192.168.2.217:9000: connect: connection refused
Sep 29 10:42:42 prd-minio-001.c002.host.com minio[19830]: Unable to connect to http://prd-minio-016.c002.host.com:9000/media/files/minio: Post http://prd-minio-016.c002.host.com:9000/minio/storage/v9/media/files/minio/getinstanceid?: dial tcp 192.168.2.218:9000: connect: connection refused
```

No servers are running, can you capture the logs once you have updated @Meshkati ? 

> Yeah we will update again, but our service is down for 2 hours and we don't care about that at this moment :D

I would care since it is better for me to work off the latest release.

**Comment by harshavardhana** [comment]
also, please https://slack.min.io so we can help you in real-time - this looks like something interesting to look at.

**Comment by kannappanr** [comment]
Closing the issue here as the discussion has moved to slack.
