### ISSUE TITLE
AssumeRoleWithWebIdentity in combination with conditions/stable userids in policy

### ISSUE THREAD

**Issue by vsfalexanderpilch** [minio/minio#8345]
We're trying to create user scoped folders in a bucket, so that the user is only able to upload data to his own subfolder in a bucket (Basically a similar policy as https://github.com/minio/minio/issues/7086 is using). The `aws:userid` condition is mapped to the accesskey of the temporary credentials, which is changing if we're rerequesting new ones. A user won't be able to continue his upload as a result. 

Would it be possible to somehow consider the sub field of the access token in a condition of a bucket policy in order to limit access to a folder instead of the access key? 

Sample:

First Auth Request: User is allowed to upload files to `testbucket/users/KIDH9E7JWDMVUPBH9WR9/*`

``` perl
AWS_SESSION_TOKEN=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJLSURIOUU3SldETVZVUEJIOVdSOSIsImF1ZCI6Im1hZ2VudG8tY29ubmVjdG9yIiwiY2lkIjoiMG9hbXMybHU0aVNYWTI2SUowaDciLCJleHAiOjE1NzAwMzQ1ODMsImlhdCI6MTU2OTk0ODE4MywiaXNzIjoiaHR0cHM6Ly9kZXYtMjIwMDU0Lm9rdGFwcmV2aWV3LmNvbS9vYXV0aDIvYXVzZnZyazFsY0VteU0xOW0waDciLCJqdGkiOiJBVC4zZms1azhCMm1YZV9NTW5mNWNRSG1GLUw3QWpncmpwVU5yZWhRNzJMb2E4IiwicG9saWN5Ijoib2t0YS1kZWZhdWx0LXBvbGljeSIsInNjcCI6WyJtYWdlbnRvLWNvbm5lY3RvciJdLCJzdWIiOiIwb2FtczJsdTRpU1hZMjZJSjBoNyIsInZlciI6MX0.ZkC3mt25gUgIftZ8EY0eGW0yBt-scGNPBqEWN2QRUrEcfgwUPSyT0rHqIwuC2355n61H4jDwvNjj5ajNRWpshA
AWS_ACCESS_KEY_ID=KIDH9E7JWDMVUPBH9WR9
```

2nd Auth Request: User is only allowed to upload files to `testbucket/users/PRQTO5SWXBUJAQ4JRAR3/*`

``` perl
AWS_SESSION_TOKEN=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJQUlFUTzVTV1hCVUpBUTRKUkFSMyIsImF1ZCI6Im1hZ2VudG8tY29ubmVjdG9yIiwiY2lkIjoiMG9hbXMybHU0aVNYWTI2SUowaDciLCJleHAiOjE1NzAwMzQ5ODYsImlhdCI6MTU2OTk0ODU4NiwiaXNzIjoiaHR0cHM6Ly9kZXYtMjIwMDU0Lm9rdGFwcmV2aWV3LmNvbS9vYXV0aDIvYXVzZnZyazFsY0VteU0xOW0waDciLCJqdGkiOiJBVC5CbHZZQnNEVXdSZS1pRU1CRjFHWldRM0hLMlFVdEpMSS1XMGFQQjhYZnIwIiwicG9saWN5Ijoib2t0YS1kZWZhdWx0LXBvbGljeSIsInNjcCI6WyJtYWdlbnRvLWNvbm5lY3RvciJdLCJzdWIiOiIwb2FtczJsdTRpU1hZMjZJSjBoNyIsInZlciI6MX0.othsAZvfXgXyh3-dMKbj7mQYAetilC3MrntkAFhFcxbG8stGxJQzaQQbTajnJsK-KHMbF4HiHhwduqFEINbomw
AWS_ACCESS_KEY_ID=PRQTO5SWXBUJAQ4JRAR3
```

It would be great if it would be somehow possible to map it to the sub claim, which would correspond to `testbucket/users/0oams2lu4iSXY26IJ0h7/*`. If a user has to request new temporary credentials, he'll automatically lose access to the existing folders atm.

[Script to obtain temporary credentials](https://github.com/minio/minio/files/3677649/auth.txt)
[Sample policy](https://github.com/minio/minio/files/3677650/policy.txt)

**Comment by harshavardhana** [comment]
Thanks @vsfalexanderpilch this is should be fixable. In-fact perhaps aws:userid is incorrectly used here.

**Comment by vsfalexanderpilch** [comment]
I guess some additional/new condition would be nice. Username/UserId is probably the wrong one for us in this case.

**Comment by vsfalexanderpilch** [comment]
@harshavardhana `cognito-identity.amazonaws.com:sub` seems to be the equivalent in aws terms.  [Example 2](https://docs.aws.amazon.com/cognito/latest/developerguide/iam-roles.html) in Cognito user guide is basically the same:

``` json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": ["s3:ListBucket"],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::mybucket"],
      "Condition": {"StringLike": {"s3:prefix": ["${cognito-identity.amazonaws.com:sub}/*"]}}
    },
    {
      "Action": [
        "s3:GetObject",
        "s3:PutObject"
      ],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::mybucket/${cognito-identity.amazonaws.com:sub}/*"]
    }
  ]
}
```

**Comment by harshavardhana** [comment]
We will perhaps simplify and make it `${jwt:sub}`

**Comment by vsfalexanderpilch** [comment]
@harshavardhana Is there some planned date when this will be implemented? I'm just asking, because I was wondering if it's possible to wait for this feature in our current project, or if we should modify the policies instead. Thanks.

**Comment by harshavardhana** [comment]
I shall be able to add this soon perhaps in a week @vsfalexanderpilch while I finish my other pending work.

**Comment by vsfalexanderpilch** [comment]
@harshavardhana That's great. Thanks a lot. We'll wait in this case...

**Comment by harshavardhana** [comment]
@vsfalexanderpilch here is the PR would you able to test it? https://github.com/minio/minio/pull/8393

**Comment by vsfalexanderpilch** [comment]
@harshavardhana I was using `minio:edge`, although I'm unsure if it's the correct one in order to test it. We're currently seeing some issues with network infrastructure on our side, so I wasn't able to test it yet. I did encounter the following issues in one of the few successful deployments:

```
# docker ps
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                   PORTS               NAMES
abf7c5ac45d9        minio/minio:edge                            "/usr/bin/docker-ent…"   2 minutes ago       Up 2 minutes (healthy)   9000/tcp            minio_node6.1.eoxwfwp7i722tq8dxr217wyax
f9a4e2a6217e        minio/minio:edge                            "/usr/bin/docker-ent…"   2 minutes ago       Up 2 minutes (healthy)   9000/tcp            minio_node5.1.szn5zdti9ck4x8gajzhyd6aol

# docker logs ab
API: BackgroundHeal()
Time: 10:42:31 UTC 10/15/2019
DeploymentID: 4cd7af51-00c9-4c72-a6ce-edbf8cf532bd
Error: file not found
       8: /go/minio/cmd/xl-sets.go:764:cmd.listDirSetsFactory.func1()
       7: /go/minio/cmd/xl-sets.go:796:cmd.listDirSetsFactory.func2()
       6: /go/minio/cmd/tree-walk.go:78:cmd.doTreeWalk()
       5: /go/minio/cmd/tree-walk.go:126:cmd.doTreeWalk()
       4: /go/minio/cmd/tree-walk.go:126:cmd.doTreeWalk()
       3: /go/minio/cmd/tree-walk.go:126:cmd.doTreeWalk()
       2: /go/minio/cmd/tree-walk.go:126:cmd.doTreeWalk()
       1: /go/minio/cmd/tree-walk.go:176:cmd.startTreeWalk.func1()
```

There was also something in mc, when I tried to manually create a user about invalid json format of config. I didn't grab the full output though and I'm currently unable to reproduce it due to the infrastructure issues.

**Comment by harshavardhana** [comment]
Now you can try edge, since the PR is merged. Also you need an updated `mc` to use against the edge branch.

**Comment by vsfalexanderpilch** [comment]
@harshavardhana  lgtm. thanks a lot for implementing it :-)
