### ISSUE TITLE
update is not a minio sub-command. See minio --help

### ISSUE THREAD

**Issue by RooyeKhat** [minio/minio#8350]
Hi
in new version when i try to update minio show this error 

can any one help me why this command is not working ?

Thanks

**Comment by nitisht** [comment]
This command is deprecated, you can use `mc` to update MinIO cluster now, https://docs.min.io/docs/minio-admin-complete-guide.html#update

**Comment by kannappanr** [comment]
@RooyeKhat Closing this issue as working as intended. Please use `mc` to update `MinIO` cluster
