### ISSUE TITLE
Cookies on presigned links

### ISSUE THREAD

**Issue by dimaqq** [minio/minio#8355]
Chrome tells me:

A cookie associated with a cross-site resource at http://localhost/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

In my setup, I'm pretty sure that the only access to `localhost` is to a presigned file link `<img src="...link..."/>` that points to a `minio` container. 

(The frontend is served through ngrok in my setup, and only fake s3 imagery is directly from localhost).

**Comment by nitisht** [comment]
Thanks for reporting @dimaqq we'll take a look

**Comment by dimaqq** [comment]
TBH, I'm not sure that it was minio that set the cookie, I think so, but I can't actually see the cookie name anywhere in Chrome 🤔

**Comment by harshavardhana** [comment]
MinIO doesn't set any cookies - the cookies are perhaps set by other applications or logins you are using.

**Comment by harshavardhana** [comment]
Closing this issue as stale.
