### ISSUE TITLE
ASK: How to download file/object from minio with presigned url?

### ISSUE THREAD

**Issue by user14045** [minio/minio#8357]
First of all, sorry if my question is so basic. But, I couldn't find the way to solve what I need.

I use [minio][1]. I try to get the object in the bucket by generating the url (presigned url). After get the presigned url, my client site could preview the image inside `<img>` tag. But, I try to download the file using that presigned url. I try to use downloadjs npm package ([link][2]) to download from the link but failed. No error, but the downloaded file is some kind of corrupt. here is the way I generate the presigned url:

    // presigned url for 'getObject' method.
    // expires in a day.
    minioClient.presignedUrl('GET', 'mybucket', 'hello.txt', 24*60*60, function(err, presignedUrl) {
      if (err) return console.log(err)
      console.log(presignedUrl)
    });

Then, what is the correct way to download the file from the presigned url?

  [1]: https://docs.min.io/docs/javascript-client-api-reference.html
  [2]: https://www.npmjs.com/package/downloadjs

**Comment by vadmeste** [comment]
@user14045 could you join us in https://slack.min.io where you can ask your questions ?

**Comment by baughmann** [comment]
Great job with this /s
