### ISSUE TITLE
read-only policy marked bucket still allows object add/delete

### ISSUE THREAD

**Issue by sheburn** [minio/minio#8359]
I am applying the following policy to a bucket, and I can still add delete objects in the bucket.  The first two statements are found in some of your code. The last deny was added by me.

policy_read_only = {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Resource": [
                "arn:aws:s3:::BUCKETNAME"
            ]
        },
        {
            "Action": [
                "s3:GetObject"
            ],
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Resource": [
                "arn:aws:s3:::BUCKETNAME/*"
            ]
        },
        {
            "Action": [
                "s3:DeleteObject"
            ],
            "Effect": "Deny",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Resource": [
                "arn:aws:s3:::BUCKETNAME/*"
            ]
        }
    ]
}

## Expected Behavior

I belive that I should get an error when trying to delete objects on the bucket.

## Current Behavior

I am able to dlete objects in the bucket.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Regression

[root@minio1 minio]# ./minio version
Version: 2019-09-26T19:42:35Z
Release-Tag: RELEASE.2019-09-26T19-42-35Z
Commit-ID: 2a2ff96ee1cb263058e7bfcc553e99054a1e9000

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
Are you using root credentials and authenticated requests ?

**Comment by harshavardhana** [comment]
This policy that you are adding is for a regular user on MinIO or bucket policies ?

**Comment by sheburn** [comment]
I am providing the minio access key and secret key just as I would logging into the browser. I have not created any sub accounts.

**Comment by sheburn** [comment]
I am attempting to apply that policy to a bucket. I then try to add and delete the objects. I am logged into the minio environment using the top level credentials. I have not made any accounts.

**Comment by harshavardhana** [comment]
Bucket policies are only meant for anonymous users.. admin user which you are using cannot be restricted in anyway. It is called the operator account. If you want to restrict users create sub-users which are not admins and they can have restricted permissions.

**Comment by sheburn** [comment]
The python api does not seem to show a method for creating accounts.  The mc client uses the following:


https://docs.min.io/docs/minio-multi-user-quickstart-guide.html
Create a new user newuser on MinIO use mc admin user.
Copy mc admin user add myminio newuser newuser123

**Comment by kannappanr** [comment]
@sheburn That is correct, we currently do not allow that in `minio-py`. Will close the issue now. Please use `mc` to create such accounts. If you have further questions please feel free to reach out to us at https://slack.min.io
