### ISSUE TITLE
S3 Select nesting JSON output records

### ISSUE THREAD

**Issue by bpiper** [minio/minio#8371]
## Expected Behavior

Given a JSON file in a bucket `my-bucket` with the following contents:

```
{"foo":"bar"}
{"foo":"baz"}
```
Running this command:
`aws --endpoint-url http://localhost:9000 s3api select-object-content --bucket my-bucket --key foo.json --input-serialization "JSON={Type=LINES}" --output-serialization "JSON={}" --expression-type SQL --expression "select s.* from S3Object s" output`

I would expect to get the following output (as Amazon S3 returns):
```
{"foo":"bar"}
{"foo":"baz"}
```

## Current Behavior

The output I get is as follows:
```
{"_1":{"foo":"bar"}}
{"_1":{"foo":"baz"}}
```

## Your Environment

* Version used (`minio version`): 2019-10-08T22:54:45Z
* Environment name and version (e.g. nginx 1.9.1): Docker edge

**Comment by kannappanr** [comment]
@bpiper Thanks for filing the issue.  We will take a look at this issue. As a workaround, the query can be changed to `select * from s3Object`.

**Comment by bpiper** [comment]
Thanks @kannappanr , that workaround does the trick.
