### ISSUE TITLE
gateway s3: Error: Prefix access is denied: /

### ISSUE THREAD

**Issue by arangyupgrade** [minio/minio#8372]
I deployed `gateway s3` on k8s using the latest minio image "RELEASE.2019-10-02T21-19-38Z"
I tested the deployment and was able to use it to upload objects on us-west-2 bucket.
However, I had to deploy minio pod, after that I'm not able to see any bucket from minio dashboard.
and reciving this error:
``` 
API: webListBuckets()
Time: 21:11:57 UTC 10/09/2019
RemoteHost: 127.0.0.1
Host: localhost:9000
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Error: Prefix access is denied: /
       3: cmd/web-handlers.go:1944:cmd.toWebAPIError()
       2: cmd/web-handlers.go:1822:cmd.toJSONError()
       1: cmd/web-handlers.go:343:cmd.(*webAPIHandlers).ListBuckets()
```

I have this policy in our aws env:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::test-minio-codecov/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": [
                "arn:aws:s3:::test-minio-codecov/"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets"
            ],
            "Resource": "arn:aws:s3:::*"
        }
    ]
}
```
any suggestion would be appreciate to solve this issue

Thanks

**Comment by harshavardhana** [comment]
Are you sure the policy applied here is associated with the Key that is used in your IAM configuration?

**Comment by arangyupgrade** [comment]
@harshavardhana oh I checked that I re attach it again!
now I'm getting another error when I'm trying to open  `test-minio-codecov` bucket from minio UI:

```
Get https://test-minio-codecov.s3.dualstack.us-east-1.amazonaws.com/?delimiter=%2F&encoding-type=url&max-keys=1000&prefix=: 301 response missing Location header
````
the bucket exist in us-west-2. I added MINION_REGION=us-west-2 to its env

**Comment by harshavardhana** [comment]
@arangyupgrade MINIO_REGION is not supported with gateway you need to use the URL directly such as `minio gateway s3 https://s3-us-west-2.amazonaws.com`

**Comment by arangyupgrade** [comment]
I'm surprised because I was able to upload an object to that us-west-2 bucket two days ago, now suddenly it stopped working. Actually I'm using jenkins job to integrate codecov and minio 
https://docs.codecov.io/docs/archiving-reports

So, I'll run a new job with passing bucket URL as you mentioned

**Comment by harshavardhana** [comment]
It will work if you allow GetBucketLocation() @arangyupgrade since you have restricted IAM policy we are not able to automatically figure out the region.  So it defaults to us-east-1

**Comment by arangyupgrade** [comment]
I updated policy by adding GetBucketLocation()
 ```
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::*"
        }
```
Also, because I'm trying to integrate another app, I'm not able to use a bucket URL.
still, I'm receiving error:
```
API: PutObject(bucket=test-minio-codecov, object=v4/raw/2019-10-09/29B70A4170CE291E62E633702CC8C23D/d47c9744d05121fadccd274c6e7b5025b636f03a/c35d0348-f206-43fb-9eb1-572bbc25d4f2.txt)
Time: 22:51:43 UTC 10/09/2019
RequestID: 15CC1C50AC4A4EC1
RemoteHost: 100.96.18.217
Host: codecov-minio:9000
UserAgent: Minio (Linux; x86_64) minio-py/2.2.2
Error: Put https://test-minio-codecov.s3.dualstack.us-east-1.amazonaws.com/v4/raw/2019-10-09/29B70A4170CE291E62E633702CC8C23D/d47c9744d05121fadccd274c6e7b5025b636f03a/c35d0348-f206-43fb-9eb1-572bbc25d4f2.txt: 301 response missing Location header
       4: cmd/api-errors.go:1700:cmd.toAPIErrorCode()
       3: cmd/api-errors.go:1725:cmd.toAPIError()
       2: cmd/object-handlers.go:1258:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```

and this error from minio UI when I choose test-minio-codecov bucket
``` 
Get https://test-minio-codecov.s3.dualstack.us-east-1.amazonaws.com/?delimiter=%2F&encoding-type=url&max-keys=1000&prefix=: 301 response missing Location header
```

**Comment by arangyupgrade** [comment]
oh I removed `/` from resource section in listBucket part and it seems it's working now!
even without GetBucketLocation()

**Comment by harshavardhana** [comment]
> oh I removed `/` from resource section in listBucket part and it seems it's working now!
> even without GetBucketLocation()

Thanks @arangyupgrade closing the issue.
