### ISSUE TITLE
Rails App unable to display images on Minio standalone via docker compose 

### ISSUE THREAD

**Issue by petebytes** [minio/minio#8376]
## Expected Behavior
Uploaded Image should be visible in browser.

## Current Behavior
Image load fails
The response is "Failed to load response data"

## Steps to Reproduce (for bugs)
1. Upload image (works fine)
2. View image (fails)
I have setup the Bucket as Read via GUI

## Context
I am using DigitalOcean Spaces for Staging and Production.  I am running Minio standalone in Docker in order to achieve dev/test parity.

## Regression
No

## Possible Resolution
Since the App works fine with DigitalOcean Spaces and not Minio I expect the issue is how I have configured Minio or that it is being accessed via http using IP address.
 

## Your Environment

* Version used (`minio version`):RELEASE.2019-10-02T21-19-38Z
* Environment name and version (e.g. nginx 1.9.1): Docker Desktop 2.1.0.3; Engine: 19.03.2; Compose: 1.24.1
* Server type and version: macOS 10.14.5
* Operating System and version (`uname -a`): Darwin raven 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

* Additional info:
Rails 6 app which works fine using DigitalOcean Spaces.
Uploads work great, but unable to view the files.
The request URL is 
`Request URL: http://172.28.1.9:9000/mybucket/3drqmidwg2jjcj4k4z0ht9w35z5s?response-content-disposition=inline%3B%20filename%3D%22rock-2_640.jpg%22%3B%20filename%2A%3DUTF-8%27%27rock-2_640.jpg&response-content-type=image%2Fjpeg&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191009%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191009T201526Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=...
`
I just set the bucket policy to "read" via the web GUI.
PS if I use web GUI and create link I can view the file

Thanks

**Comment by vadmeste** [comment]
@petebytes do you have the exact error when trying to open the image ? like the http status code and its body

**Comment by petebytes** [comment]
Status is (failed)
net::ERR_CONNECTION_TIMED_OUT

**Comment by petebytes** [comment]
Made some progress, I can now upload. The app then generates exception 

> Failed to open TCP connection to 127.0.0.1:9000 (Connection refused - connect(2) for "127.0.0.1" port 9000)


docker-compose-yml

>   minio:
    image: minio/minio:RELEASE.2019-10-02T21-19-38Z
    volumes:
      - "minio:/storage"
    ports:
      - "9000:9000"
    env_file:
      - ".env"
    command: server /storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
        testing_net:
            ipv4_address: 172.28.1.9

endpoint: http://172.28.1.9:9000
does not upload and fails with
net::ERR_CONNECTION_TIMED_OUT

endpoint: http://0.0.0.0:9000
uploads then fails with
Failed to open TCP connection to 0.0.0.0:9000 (Connection refused - connect(2) for "0.0.0.0" port 9000)

endpoint: http://127.0.0.1:9000
uploads then fails with
Failed to open TCP connection to 127.0.0.1:9000 (Connection refused - connect(2) for "127.0.0.1" port 9000)

storage.yml
> minio_dev:
  service: S3
  access_key_id: <%= ENV["MINIO_ACCESS_KEY"] %>
  secret_access_key: <%= ENV["MINIO_SECRET_KEY"] %>
  region: us-east-1
  bucket: apsion
  endpoint: http://127.0.0.1:9000
  force_path_style: true

**Comment by ebozduman** [comment]
@petebytes ,

It looks like the first problem you had and now could be different. Let us look into both issues and we'll get back to you.

**Comment by wlan0** [comment]
> endpoint: http://172.28.1.9:9000
> does not upload and fails with
> net::ERR_CONNECTION_TIMED_OUT

All the IP addresses you've used to connect are private address ranges. You won't be able to connect over these IPs. Please use the public IP of the DO machine where minio container is running. You should be able to connect.

**Comment by petebytes** [comment]
Thanks @ebozduman .

Agreed - I think the first issue is just connectivity between host and container not working since I was specifying container IP.

I am working on this some more today and will provide updates if anything changes.

**Comment by petebytes** [comment]
@wlan0 Thanks - I can connect using localhost and 127.0.0.1:9000

GUI works well and the application can now upload.
Still have an issue where app crashes after upload (as decribed above)

**Comment by wlan0** [comment]
Could you please paste the logs of the minio container

@petebytes

**Comment by petebytes** [comment]
This is all I am seeing:

> docker logs -f c0f4e4602e0451f956cb27d4c5f455036f3916fa3b914cff6ab89f0dc824b808
>  You are running an older version of MinIO released 1 week ago 
>  Update: docker pull minio/minio:RELEASE.2019-10-12T01-39-57Z 
> Endpoint:  http://172.28.1.9:9000  http://127.0.0.1:9000
> Browser Access:
>    http://172.28.1.9:9000  http://127.0.0.1:9000
> Object API (Amazon S3 compatible):
>    Go:         https://docs.min.io/docs/golang-client-quickstart-guide
>    Java:       https://docs.min.io/docs/java-client-quickstart-guide
>    Python:     https://docs.min.io/docs/python-client-quickstart-guide
>    JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
>    .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

Tried setting MINIO_HTTP_TRACE=/dev/stdout but did not see a difference

**Comment by ebozduman** [comment]
@petebytes,

Could you run `mc admin trace -v -a` command in another window and go through your reproduction steps?
```
A note for you:
After introduction of `mc admin trace` command, capturing trace information
by setting environment variable, MINIO_HTTP_TRACE, is disabled.
```
