### ISSUE TITLE
Occasional SignatureDoesNotMatch error when uploading files to Minio behind a Nginx proxy

### ISSUE THREAD

**Issue by annkam** [minio/minio#8377]
I have a Minio cluster running in Kubernetes behind a [Nginx Ingress Controller](https://kubernetes.github.io/ingress-nginx/). I use [wal-g](https://github.com/wal-g/wal-g) to upload PostgreSQL backups to Minio. The upload is performed part by part (about 30 parts, each is less than 1 GB). Occasionally, the process fails with SignatureDoesNotMatch error. 

## Expected Behavior
The upload should always be successful.

## Current Behavior
The upload process fails randomly with the following error:

INFO: 2019/10/10 03:17:10.532801 Starting part 11 ...
ERROR: 2019/10/10 03:17:44.315630 failed to upload 'basebackups_005/base_000000010000072D0000002D/tar_partitions/part_011.tar.lz4' to bucket 'smiuatdb2': MultipartUpload: upload multipart failed
    upload id: c763a6c6-ec58-4b78-8464-df1b12e27deb
caused by: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
    status code: 403, request id: 15CC2AD49C123AF6, host id: 
ERROR: 2019/10/10 03:17:44.315694 upload: could not upload 'base_000000010000072D0000002D/tar_partitions/part_011.tar.lz4'
ERROR: 2019/10/10 03:17:44.315717 failed to upload 'basebackups_005/base_000000010000072D0000002D/tar_partitions/part_011.tar.lz4' to bucket 'smiuatdb2': MultipartUpload: upload multipart failed
    upload id: c763a6c6-ec58-4b78-8464-df1b12e27deb
caused by: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
    status code: 403, request id: 15CC2AD49C123AF6, host id: 

## Possible Solution
I am sure something is missing in Ingress configuration which is not mentioned in official docs as the problem disappears when I switch to a NodePort Service instead of Ingress.

## Steps to Reproduce (for bugs)

1. Deploy Minio in distributed mode to a Kubernetes Cluster
2. Configure Nginx Ingress Controller and Ingress with TLS for Minio. I have the following annotations set:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 1048576m
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
   The Ingress Controller also has `ignore_invalid_headers` parameter set to `false`
3.  Try to collect PostgreSQL backups with wal-g configured to use Minio S3 as a back-end

## Your Environment
* Version used (`minio version`): RELEASE.2019-09-11T19-53-16Z
* Environment name and version (e.g. nginx 1.9.1): OpenShift v3.11.0+92b7c41-132, Kubernetes v1.11.0+d4cacc0
* Server type and version: Centos 7
* Operating System and version (`uname -a`): Linux common11d24w02 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Additional information: Ingress Controller version is 0.24.1

**Comment by vadmeste** [comment]
> 2\. kubernetes.io/ingress.class: nginx
>     nginx.ingress.kubernetes.io/proxy-body-size: 1048576m
>     nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
>     nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
>     nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
>     nginx.ingress.kubernetes.io/proxy-http-version: "1.1"

You also need to tell nginx to avoid modifying the Host header that is receiving from the client.
you need something like below:

    nginx.ingress.kubernetes.io/proxy_set_header: "Host $host"

**Comment by annkam** [comment]
> > 2. kubernetes.io/ingress.class: nginx
> > nginx.ingress.kubernetes.io/proxy-body-size: 1048576m
> > nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
> > nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
> > nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
> > nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
> 
> You also need to tell nginx to avoid modifying the Host header that is receiving from the client.
> you need something like below:
> 
> ```
> nginx.ingress.kubernetes.io/proxy_set_header: "Host $host"
> ```

I can't control this header via annotations. However, I've checked the configuration of the ingress controller itself. It sets the Host header to the required value for all vhosts by default. Any other suggestions?

**Comment by vadmeste** [comment]
`mc admin trace` would help to understand, can you paste the output of the failed request ?

**Comment by annkam** [comment]
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local [REQUEST s3.PutObjectPart] 06:23:43.841
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local PUT /smiuatdb2/basebackups_005/base_000000010000072D00000062/tar_partitions/part_031.tar.lz4?partNumber=13&uploadId=99ff4b67-d7a6-41e9-96d6-58e61bff9191
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local Host: myhost.example.com
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local Content-Md5: //eT+h3zn0JZd1oYFe9HRA==
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local X-Amz-Date: 20191010T062343Z
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local X-Scheme: https
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local X-Forwarded-Host: myhost.example.com
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local X-Forwarded-Proto: https
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local X-Request-Id: fc031466abc73b04c2ae84727ce01859
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local User-Agent: aws-sdk-go/1.15.83 (go1.11.12; linux; amd64) S3Manager
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local X-Original-Uri: /smiuatdb2/basebackups_005/base_000000010000072D00000062/tar_partitions/part_031.tar.lz4?partNumber=13&uploadId=99ff4b67-d7a6-41e9-96d6-58e61bff9191
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local Accept-Encoding: gzip
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local Authorization: AWS4-HMAC-SHA256 Credential=ed1G1IcUES21J62d31Nx/20191010/pgdb/s3/aws4_request, SignedHeaders=content-length;content-md5;expect;host;x-amz-content-sha256;x-amz-date, Signature=578bc8765e2d961df166e009f9bbbca0dbfdaab79c75397a553d1cc42fc0835d
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local Content-Length: 20971520
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local X-Amz-Content-Sha256: 44e288c77c45ec8b8a4d5ad82215799a0c9230380bb5df20a81880a3d7cd7cff
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local X-Forwarded-For: 127.0.0.1
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local X-Forwarded-Port: 443
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local X-Real-Ip: 127.0.0.1
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local <BODY>
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local [RESPONSE] [06:23:43.892] [ Duration 50.601ms  🠉 220 B  🠋 800 B ]
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local 403 Forbidden
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local Vary: Origin
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local X-Amz-Request-Id: 15CC34FB44CB6490
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local X-Xss-Protection: 1; mode=block
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local Accept-Ranges: bytes
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local Content-Length: 543
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local Content-Security-Policy: block-all-mixed-content
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local Content-Type: application/xml
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local Server: MinIO/RELEASE.2019-09-11T19-53-16Z
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>basebackups_005/base_000000010000072D00000062/tar_partitions/part_031.tar.lz4</Key><BucketName>smiuatdb2</BucketName><Resource>/smiuatdb2/basebackups_005/base_000000010000072D00000062/tar_partitions/part_031.tar.lz4</Resource><RequestId>15CC34FB44CB6490</RequestId><HostId>e6db8c1a-c2b0-4e81-a2f0-585f402e483c</HostId></Error>
staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local

**Comment by vadmeste** [comment]
@annkam what's the endpoint url that you pass ?

**Comment by annkam** [comment]
@vadmeste it's like `https://pg-backup.mydomain.com`, and the Host header is set to `pg-backup.mydomain.com`

**Comment by vadmeste** [comment]
> staas-minio-0.staas-minio-svc.staas-prod-1.svc.cluster.local Host: myhost.example.com

From the log, it seems like the node received myhost.example.com ^^

**Comment by annkam** [comment]
@vadmeste  I am sorry for the misunderstanding. I have replaced my real endpoint name with this example one in the log above.

**Comment by annkam** [comment]
I am pretty sure that if something was wrong with the Host header, nothing would work at all. Currently the tool may upload succesfully two iterations of backups (about 50 GB broken in multiple parts) and fail at the third iteration while uploading one of the parts. When we disable Ingress, it always works correctly.

**Comment by vadmeste** [comment]
> I am pretty sure that if something was wrong with the Host header, nothing would work at all. Currently the tool may upload succesfully two iterations of backups (about 50 GB broken in multiple parts) and fail at the third iteration while uploading one of the parts. When we disable Ingress, it always works correctly.

When you upload the same file _name_ multiple times, does it fail after some iterations ?

**Comment by annkam** [comment]
> > I am pretty sure that if something was wrong with the Host header, nothing would work at all. Currently the tool may upload succesfully two iterations of backups (about 50 GB broken in multiple parts) and fail at the third iteration while uploading one of the parts. When we disable Ingress, it always works correctly.
> 
> When you upload the same file _name_ multiple times, does it fail after some iterations ?

Actually, I never upload the same file name as it is generated by the backup tool and is different in each iteration. They all look more or less same, however, for example:
'basebackups_005/base_000000010000072F00000031/tar_partitions/part_013.tar.lz4'
'base...' is the unique directory name for each backup iteration. There may be many parts named in the same way like this example: part_018.tar.lz4 etc...

**Comment by vadmeste** [comment]
@annkam as you also suggested, it seems ingress is doing something weird here.

Is this a production deployment ? if you are not using TLS, could you try to sniff the failing http request (with tcpdump for example), along with the failing request printed in `mc admin trace`, to compare both requests.

**Comment by harshavardhana** [comment]
Closing this issue as stale for now, please reopen if you have further information as requested by @vadmeste 

Thanks
