### ISSUE TITLE
Minio as remotecache for bazel build systems

### ISSUE THREAD

**Issue by HemangLavana** [minio/minio#8378]
**Is your feature request related to a problem? Please describe.**
Bazel is a build system open sourced by Google and it has a remote caching feature:

https://docs.bazel.build/versions/1.0.0/remote-caching.html

I think it would be great if minio could be used as a remote cache for bazel build system, as it fits very nicely for this purpose.

**Describe the solution you'd like**
A http server for minio should be provided to support being used as bazel cache system. So we can simply add the following line to our .bazelrc file:

build --remote_cache=http://replace-with-your-minio.host:port

And it should provide the GET and PUT mechanism to access and write to the minio cache. Minio access keys also need to be provided in the above url for it to work correctly.

It also needs a mechanism to configure and expire cache objects after a specified time interval (TTL - time to live) so that older objects that have not been accessed for say 3 months could be purged.

**Describe alternatives you've considered**
Currently I am using the following remote server:

https://github.com/buchgr/bazel-remote

This has been configured to not only save the cache contents locally on disk but also write to mino via the amazon s3 interface. However, I would like to avoid this middle layer if minio supported to be used as bazel cache out of the box.

**Comment by harshavardhana** [comment]
We don't have requirements for this @HemangLavana most of our CI/CD is custom built and we are satisfied with it.

Thank you for opening an issue. We shall close it now.
