### ISSUE TITLE
status become not ready intermittently when deploy on kubernetes

### ISSUE THREAD

**Issue by softarts** [minio/minio#8385]
deploy minio on single node kubernetes cluster, use `hostPath`  as pv

image: "minio/minio:RELEASE.2019-08-07T01-59-21Z"

## Current Behavior

deploy on a single node kubernetes cluster.
read and write files in spark env.
status become not ready intermittently. neither s3cmd nor mc can access.

have used cosbench to benchmark  (64 workers)
512KB read(60%)  636.39 op/s | 325.83 MB/S 
512KB write(30%) 317.27 op/s | 162.44 MB/S 
4MB write(10%)  106.19 op/s | 434.95 MB/S

the spark env system load shouldn't exceed the above range.
in cadvisor it can be seen ,
'memory total usage ' start from 3000 MB, increase to 11GB as more and file object put to S3.
but 'ps' and 'docker stats' only show arround 300MB memory usage.

how can I add some flags to output debug info?

## Possible Solution

NO

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`): "minio/minio:RELEASE.2019-08-07T01-59-21Z"
* Environment name and version (e.g. nginx 1.9.1): based on spark 2.4.3, hadoop-common 2-9-2.jar
* Server type and version: 
* Operating System and version (`uname -a`):Linux 10.40.57.43 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by kannappanr** [comment]
@softarts Can you please be a bit more clear? Are you saying that the status becomes unavailable intermittently?

**Comment by harshavardhana** [comment]
@softarts also use the latest version we have bumped the Go routine requirement for readiness probes to be higher.

**Comment by softarts** [comment]
> @softarts Can you please be a bit more clear? Are you saying that the status becomes unavailable intermittently?

not ready -> means the POD status change to not ready. browser can't access the repo too
can it output more logs?

**Comment by harshavardhana** [comment]
Use the latest version and let us know if you can reproduce this issue @softarts

**Comment by softarts** [comment]
> Use the latest version and let us know if you can reproduce this issue @softarts

you mean minio:latest or a specified version?

**Comment by harshavardhana** [comment]
Yes latest.

**Comment by softarts** [comment]
> Yes latest.

not resolved.. how can I output more logs?

**Comment by harshavardhana** [comment]
> not resolved.. how can I output more logs?

not resolved meaning ?

**Comment by softarts** [comment]
> > not resolved.. how can I output more logs?
> 
> not resolved meaning ?

saw kubernetes POD status became Not Ready when reading/writing to minio
can't access via minio browser

**Comment by harshavardhana** [comment]
> saw kubernetes POD status became Not Ready when reading/writing to minio
> can't access via minio browser

how many concurrent streams did you perform to MinIO ?

**Comment by softarts** [comment]
my spark setting:
fs.s3a.threads.max = 10
fs.s3a.max.total.tasks = 5
fs.s3a.threads.max = 10
fs.s3a.connection.establish.timeout=5000
fs.s3a.connection.timeout=200000
fs.s3a.block.size=32M
fs.s3a.committer.threads=null 
fs.s3a.connection.maximum=15
fs.s3a.fast.upload.active.blocks=4
fs.s3a.socket.recv.buffer=8192
fs.s3a.socket.send.buffer=8192

I guess total concurrent streams would be less than 10. (4~8 executors instance, 1 core)
one more thing is when issue happened, 
I can access s3 via the pod endpoint ip:port, but can't do via service:port within kubernetes cluster nor via nodeport outside cluster;
and kubectl port-forward doesn't work for svc and pod too.
do you think any problem with the readiness and liveness probe?

**Comment by harshavardhana** [comment]
Have you tried removing readiness and testing again ?

**Comment by softarts** [comment]
ya, it turns better after removed readiness, any chance that readiness check has bug?e.g. it wrongly set to 503 status in some cases.

output:
curl -i 192.168.127.149:9000/minio/health/ready
HTTP/1.1 503 Service Unavailable
Accept-Ranges: bytes
Content-Length: 0
Content-Security-Policy: block-all-mixed-content
Server: MinIO/RELEASE.2019-08-07T01-59-21Z
Vary: Origin
X-Amz-Request-Id: 15CE7154A4946161
X-Xss-Protection: 1; mode=block
Date: Thu, 17 Oct 2019 13:12:08 GMT

**Comment by harshavardhana** [comment]
Not sure, will check.

**Comment by Praveenrajmani** [comment]
@softarts Can you get us the `go_goroutines` metric exposed in `/minio/prometheus/metrics` path? You can set this env `MINIO_PROMETHEUS_AUTH_TYPE="public"` to disable the token based authentication. As per the readiness check, a pod is considered to be not ready if the go-routine count is less than 10000. Just want to clarify if it lies below par.

**Comment by harshavardhana** [comment]
Readiness needs to perhaps not be based on Go-routines @Praveenrajmani instead should be based on some other form of I/O activity, go-routines are thin and 10,000 go-routines is not that uncommon for MinIO because we are I/O intensive application. 

AFAICS each concurrent write lets say of 10,000 requests/sec would mean that we will return 503, I would perhaps implement Readiness from the angle of the quorum of disks available. 

```
// connectDisksAndLockersWithQuorum is same as connectDisksAndLockers but waits
// for quorum number of formatted disks to be online in any given sets.
func (s *xlSets) connectDisksAndLockersWithQuorum() {
        var onlineDisks int
        for onlineDisks < len(s.endpoints)/2 {
                for _, endpoint := range s.endpoints {
                        if s.isConnected(endpoint) {
                                continue
                        }
```

perhaps we should simply do `IsZoneReady()` function at the object layer for erasure-coded and calculate if we have offlineDisks >= len(s.endpoints)/2 and for FS mode just let it be 200 OK all the time.

**Comment by Praveenrajmani** [comment]
understood @harshavardhana Will send a fix

**Comment by softarts** [comment]
hi
fixed in which tag?

**Comment by harshavardhana** [comment]
No tag yet @softarts shall be available in next release.
