### ISSUE TITLE
does 3 dots format of minio server cmd only support one parameter?

### ISSUE THREAD

**Issue by RocFang** [minio/minio#8386]
After read https://docs.min.io/docs/distributed-minio-quickstart-guide.html, I deployed a distributed minio cluster by using 3 dots cmd format. 

Unlike the example in the doc, my servers' ip are not sequential, so I run the cmd below:
```
minio server http://192.168.1.101/data{1...8} http://192.168.1.109/data{1...8}
```

## Expected Behavior

 Start distributed MinIO instance on 2 nodes with 8 drives each mounted at /data1 to /data8.

## Current Behavior

Every file I uploaded to minio will locate eigher in 192.168.1.101 or 192.168.1.109, not both. And the content of xl.json shows that two servers both consider they have disks from 1 to 8.

Then I run the cmd using the normal format:
```
minio server http://192.168.1.101/data1
http://192.168.1.101/data2 
......(omit)......
http://192.168.1.101/data8
http://192.168.1.109/data1 
......(omit)......
http://192.168.1.109/data8
```
Then everything works as I expect.
And the content of xl.json shows that two servers both recognize disk from 1 to 16.

So I wonder, does the  3 dots format of minio server cmd only support one parameter?

thanks:)

## Possible Solution

NO.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):  2019-10-02T21:19:38Z
* Operating System and version (`uname -a`):```Linux sr015.mli-sdjn-01.c4hcdn.cn 2.6.32-754.12.1.el6.x86_64 #1 SMP Tue Apr 9 14:52:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by harshavardhana** [comment]
Yes it is meant to support only single, if you split the command it means that they are different sets of their own. 

You should enumerate your IPs with hostnames into single command line.

**Comment by kannappanr** [comment]
@RocFang Closing this issue as answered. Please feel free to reach out to us at https://slack.min.io for such questions.

**Comment by RocFang** [comment]
@harshavardhana  @kannappanr  Appreciate  your explanation:) Thanks.
