### ISSUE TITLE
STS AssumeRole - Getting SignatureDoesNotMatch with Presigned PutObject Request

### ISSUE THREAD

**Issue by bennnjamin** [minio/minio#8391]
I'm pretty sure this is a Minio issue as I have tested the same code against S3 and it works. I've eliminated all other possibilities.

I have a set of temporary credentials, meaning I'm using a Session Token returned from the AssumeRole API. I have tested these credentials using the AWS CLI and a simple PutObject. That request succeeds. When using AWS iOS SDK the same request, with the same credentials fails. I have tried on multiple versions of iOS SDK from the latest, to some pretty old ones all with the exact same result. With http tracing turned on on Minio, the only difference between the two requests is that the working request includes the authentication headers, while the presigned requests submits them as URL Query Parameters. Example requests below:

Working
```
[REQUEST s3.PutObject] 23:53:59.968
PUT /bucket/file.jpg
Host: HOSTNAME.com
Content-Type: text/plain
Expect: 100-continue
X-Amz-Date: 20191011T235359Z
X-Amz-Security-Token: SESSION_TOKEN
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=ACCESS_KEY/20191011/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=7e73f94d9cf741652a0bd5cfa8589fc80393752cdaa4b18f436ca7c14a73391f
Content-Length: 0
User-Agent: aws-cli/1.16.113 Python/3.7.3 Linux/4.19.0-6-amd64 botocore/1.12.103
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
<BODY>
[RESPONSE] [23:53:59.982] [ Duration 14.218ms  🠉 134 B  🠋 261 B ]
200 OK
X-Amz-Request-Id: 15CCBCDFEBFD0A85
X-Xss-Protection: 1; mode=block
Accept-Ranges: bytes
Content-Length: 0
Content-Security-Policy: block-all-mixed-content
ETag: "bd6c49dfcd4b947adf8e974af9b7d89c-1"
Server: MinIO/RELEASE.2019-09-25T18-25-51Z
Vary: Origin
<BODY>
```

Not working

```
PUT /bucket/file.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ACCESS_KEY%2F20191011%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191011T234948Z&X-Amz-Expires=2999&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Security-Token=SESSION_TOKEN&X-Amz-Signature=cd26642f11b8b3c5a8f4786df40ffdf967835d1287ccf7e7d4b19a51c11fa014
Host: HOSTNAME
Accept-Language: en-us
Content-Length: 3592778
User-Agent: aws-sdk-iOS/2.10.3 iOS/12.4.2 en_US transfer-utility
Accept: */*
Accept-Encoding: br, gzip, deflate
Connection: keep-alive
Content-Type: image/jpeg
<BODY>
[RESPONSE] [23:49:50.254] [ Duration 737.341ms  🠉 123 B  🠋 722 B ]
403 Forbidden
X-Xss-Protection: 1; mode=block
Accept-Ranges: bytes
Content-Length: 465
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO/RELEASE.2019-09-25T18-25-51Z
Vary: Origin
X-Amz-Request-Id: 15CCBCA59BE7554D
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>1/80/1-146-80_2019-10-11_22-20-24.jpg</Key><BucketName>lets.minio</BucketName><Resource>/lets.minio/1/80/1-146-80_2019-10-11_22-20-24.jpg</Resource><RequestId>15CCBCA59BE7554D</RequestId><HostId>65039a11-b6d1-4577-b1fd-60251134a48c</HostId></Error>
```

## Expected Behavior

Presigned PutObject requests using temporary credentials from AssumRole API should succeed

## Current Behavior

When making a PUT request like
```PUT /bucket/image.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ZU1YPXXYOENJ1K1EJYR6%2F20191011%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191011T234948Z&X-Amz-Expires=2999&X-Amz-SignedHeaders=content-type%3Bhost%3Bx-amz-server-side-encryption&X-Amz-Security-Token=TOKEN&X-Amz-Signature=cd26642f11b8b3c5a8f4786df40ffdf967835d1287ccf7e7d4b19a51c11fa014```
the request fails with ```SignatureDoesNotMatch```
## Steps to Reproduce (for bugs)

1. Currently using AWSTransferUtility in iOS SDK which generates presigned PutObject requests. To reproduce, generate a presigned PutObject requests using STS temporary credentials. AWS Docs: https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-authentication-HTTPPOST.html

## Context

I am trying to use AWS SDK's to allow untrusted clients temporary access to access files at specific prefixes in a bucket. 

## Your Environment

* Version used (`minio version`): 2019-09-25T18:25:51Z
* Environment name and version (e.g. nginx 1.9.1): 
* Server type and version: EC2 
* Operating System and version (`uname -a`): 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
* Link to your project:

**Comment by kannappanr** [comment]
@bennnjamin Thanks for filing the issue. We will take a look at the issue and get back to you

**Comment by harshavardhana** [comment]
Generating temporary access is already provided with STS, generating presigned URL further doesn't add any benefit. Why do you need presigned URL here if client is already using AWS SDK to upload ?

**Comment by bennnjamin** [comment]
@harshavardhana I understand completely. I'm just using the AWS iOS SDK ```TransferUtility``` (```TransferManager``` is deprecated) for uploads/downloads to S3 and they implemented presigned URL for uploads and downloads in their SDK here: https://github.com/aws-amplify/aws-sdk-ios/blob/2.12.0/AWSS3/AWSS3TransferUtility.m#L1043. 

However, it still seems reasonable that a client should be able to generate presigned URLs with any set of credentials correct? There are certainly times when a client with temporary access may want to generate a presigned URL to share with someone else for a specific file.

**Comment by harshavardhana** [comment]
Yes it is reasonable but I wondered why would anyone need presigned with temporary credentials. Since both solve same usecase ..

**Comment by bennnjamin** [comment]
The best use case I can think of is to share a single file with someone else who does not have authority to get temporary access credentials. Seems like a bit of an edge case. 

Now why they implemented ```TransferUtility``` to use presigned URLs, I don't know, it seems redundant since the client already has valid credentials. But it would be helpful if you can confirm whether or not this is supported by Minio. Then if I can find a workaround in their SDK via issue/pull request/custom implementation, I don't see a huge need for it to be supported by Minio.

**Comment by harshavardhana** [comment]
We will definitely look a the issue , since the request is rejected here..

**Comment by bennnjamin** [comment]
Hello just checking in to see if there has there been any progress on this?

**Comment by harshavardhana** [comment]
Currently, we are busy with other priorities will soon take a look @bennnjamin

**Comment by knobotz** [comment]
@harshavardhana It looks like we're running into a similar issue as well with pre-signed get requests not working with STS credentials.

**Comment by harshavardhana** [comment]
> @harshavardhana It looks like we're running into a similar issue as well with pre-signed get requests not working with STS credentials.

@knobotz does it work without presigned URLs?

**Comment by knobotz** [comment]
Yes, I'm able to download (via the aws ruby sdk and cli) the object with minio STS credentials. However, trying to generate and use a presigned get_object url with the same credentials for the same object always returns: 

```
[RESPONSE] [19:47:56.900] [ Duration 526µs  🠉 179 B  🠋 712 B ]
myhost.com 403 Forbidden
myhost.com Content-Type: application/xml
myhost.com Server: MinIO/RELEASE.2019-09-11T19-53-16Z
myhost.com Vary: Origin
myhost.com X-Amz-Request-Id: 15E678324E78C2A2
myhost.com X-Xss-Protection: 1; mode=block
myhost.com Accept-Ranges: bytes
myhost.com Content-Length: 455
myhost.com Content-Security-Policy: block-all-mixed-content
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>SignatureDoesNotMatch</Code>
  <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
  <Key>path/to/object</Key>
  <BucketName>somebucket</BucketName>
  <Resource>/somebucket/path/to/object</Resource>
  <RequestId>15E678324E78C2A2</RequestId>
  <HostId></HostId>
</Error>
```

**Comment by harshavardhana** [comment]
Okay looks like we don't support this yet @knobotz

**Comment by nargesmomenyan** [comment]
I have a similar problem. 
I'd like to access minio objects (in this case images) via url because they are custom map tiles should be viewed through leaflet.js. The problem is, the access has been given me is temporary credentials generated by assumeRole.
When I generate signedUrl to access the object I see this message :SignatureDoesNotMatch.

@harshavardhana Please consider this issue again. In this case, I don't have any other choice.

**Comment by harshavardhana** [comment]
@nargesmomenyan we can definitely support this, so please provide a self contained reproducer.

**Comment by nargesmomenyan** [comment]
Thanks for your quick consideration.

I receive fileCredential from the assumeRole api.
Here is my typescript code to create aws client and generate signed Url:

```
export default class AWS_S3_Util {
    S3: AWS.S3
    constructor(fileCredential: IFileCredential) {
        let options: S3.Types.ClientConfiguration = {
            sessionToken: fileCredential.SessionToken,
            accessKeyId: fileCredential.AccessKey,
            secretAccessKey: fileCredential.SecretKey,
            endpoint: fileCredential.EndPoint,
            s3ForcePathStyle: true,
            signatureVersion: 'v4'
        };
        this.S3 = new AWS.S3(options)
    }
    getSignedUrlOfObject(fileCredential: IFileCredential): string {
        let url = this.S3.getSignedUrl('getObject', {
            Bucket: fileCredential.Bucket,
            Key: fileCredential.Key
        })
        return url
    }
}
```

**Comment by nargesmomenyan** [comment]
@harshavardhana 
This part of my project is suspended. I'll appreciate if you give me an estimation for providing this feature.

**Comment by VahidShir** [comment]
I ran into this problem too. I hope you you fix it.
Thanks

**Comment by AmirShahid** [comment]
@harshavardhana 
Please solve this issue as soon as possible. we are eagerly waiting for you.
