### ISSUE TITLE
how to add 1T disk to minio 

### ISSUE THREAD

**Issue by ofchan** [minio/minio#8394]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by nitisht** [comment]
Closing this as incomplete @ofchan feel free to reach out on Slack (https://slack.min.io) for such questions

**Comment by ofchan** [comment]
ok

**Comment by ofchan** [comment]
> Closing this as incomplete @ofchan feel free to reach out on Slack (https://slack.min.io) for such questions

ok
