### ISSUE TITLE
Add Support for Life Cycle to the Minio UI

### ISSUE THREAD

**Issue by gwperry** [minio/minio#8396]
Minio is very close to a total solution for us.  One thing my non-developer users need is the life cycle support in the Minio UI.

We are using Minio in a Kubernetes environment.  Having an option in the UI for the users to set up the data in a bucket to purge at either set-up or as an option after set-up would satisfy the last hurdle for us to implement this product as a solution.

Are there any plans to do this?

**Comment by kannappanr** [comment]
@gwperry Thanks for the feature request. I don't think there are any plans to do that, at least in the near future. We have other tasks lined up that we need to finish first. I will let you know if things change at our end.
