### ISSUE TITLE
Minio doesn't send notifications

### ISSUE THREAD

**Issue by Racle** [minio/minio#8403]
## Expected Behavior

Minio would send notifications to our webhook always.

## Current Behavior

Minio doesn't send notifications. Our webhook api logs every request, and it hasn't received any request in hours before rebooting minio.

We had 1700+ .event files on our queueDir. (there were created in ~1-2 hours when checked the created date).
After rebooting minio, events seems to be sent, as we saw webhook request on our go api and queueDir was emptied.

Minio doesn't log any errors.

## Steps to Reproduce (for bugs)

1. Keep server on, have thousands access/put/delete events
2. ???
3. Minio stops sending notifications after random time. Now it took 22 hours to stop sending notifications.

## Context

Our event creation
```bash
mc event add minio/bucketname arn:minio:sqs:eu-fi-1:1:webhook 
```
We just added `--event put,delete` to see if that helps, as we don't currently need access notifications. 

our minio config
```json
{
  "cache":{
    "drives":null,
    "exclude":null,
    "expiry":0,
    "maxuse":0
  },
  "compress":{
    "enabled":false,
    "extensions":null,
    "mime-types":null
  },
  "credential":{
    "accessKey":"",
    "expiration":"0001-01-01T00:00:00Z",
    "secretKey":""
  },
  "kms":{
    "vault":{
      "auth":{
        "approle":{
          "id":"",
          "secret":""
        },
        "type":""
      },
      "endpoint":"",
      "key-id":{
        "name":"",
        "version":0
      }
    }
  },
  "ldapserverconfig":{
    "enabled":false,
    "groupNameAttribute":"",
    "groupSearchBaseDN":"",
    "groupSearchFilter":"",
    "serverAddr":"",
    "skipTLSverify":false,
    "stsExpiryDuration":"",
    "usernameFormat":""
  },
  "logger":{
    "console":{
      "enabled":false
    },
    "http":null
  },
  "notify":{
    "amqp":null,
    "elasticsearch":null,
    "kafka":null,
    "mqtt":null,
    "mysql":null,
    "nats":null,
    "nsq":null,
    "postgresql":null,
    "redis":null,
    "webhook":{
      "1":{
        "enable":true,
        "endpoint":"http:\/\/our_webhook_api:port\/webhook",
        "queueDir":"\/home\/events",
        "queueLimit":0
      }
    }
  },
  "openid":{
    "jwks":{
      "url":null
    }
  },
  "policy":{
    "opa":{
      "authToken":"",
      "url":null
    }
  },
  "region":"eu-fi-1",
  "storageclass":{
    "rrs":"",
    "standard":""
  },
  "version":"33",
  "worm":"off"
}
```

Same behavior was with `ListenBucketNotification` before we moved to use webhook.

## Your Environment

* Version used (`minio version`): RELEASE.2019-10-12T01-39-57Z
* Environment name and version (e.g. nginx 1.9.1): docker, go api to catch webhook

**Comment by crazywako** [comment]
Same happened with Redis events and with minio-go.ListenBucketNotifications. No events after certain amounts of time. Restart helps for a while.

**Comment by Praveenrajmani** [comment]
@Racle Events would reach the queueDir only when it fails due to any connection failures during transit. If there are any other errors other than connection errors, MinIO would log those errors in the console. As you cannot see any errors in the console, the only possibility is that the webhook server would've stopped after some time.

And during restarts, webhook would've restarted and received the persisted events

**Comment by Praveenrajmani** [comment]
Can you try restarting the webhook server in such cases? And see if the events are replayed from the queueDir? @Racle

**Comment by Racle** [comment]
> @Racle Events would reach the queueDir only when it fails due to any connection failures during transit. If there are any other errors other than connection errors, MinIO would log those errors in the console. As you cannot see any errors in the console, the only possibility is that the webhook server would've stopped after some time.
> 
> And during restarts, webhook would've restarted and received the persisted events


And Go api still functioned (as it has other uses also). It hasn't crashed or restarted when minio stopped sending notifications.
Same happened with redis (without persisted events enabled). There was no notifications send to redis either.

And we only restarted minio, not go api.

If this happens again, we can try restart the go api next, and leave minio as it is. Currenlty queueDir is empty.

We noticed this at ~10:00. 
Logs show that our GO api received latest webhook request 9:13 
it was {"Records":null,"Err":null} for some reason. (So minio sends empty webhook for some reason?) Before that there was correct notification, and time between those was 0.2 seconds.

Next log event for our api was 9:15. Not webhook but another request. So API was working correctly. It has not been restarted today.

We restarted minio at 10:10, and after that api received thousands of webhook requests.

**Comment by Praveenrajmani** [comment]
> > @Racle Events would reach the queueDir only when it fails due to any connection failures during transit. If there are any other errors other than connection errors, MinIO would log those errors in the console. As you cannot see any errors in the console, the only possibility is that the webhook server would've stopped after some time.
> > And during restarts, webhook would've restarted and received the persisted events
> 
> And Go api still functioned (as it has other uses also). It hasn't crashed or restarted when minio stopped sending notifications.
> Same happened with redis (without persisted events enabled). There was no notifications send to redis either.
> 
> And we only restarted minio, not go api.
> 
> If this happens again, we can try restart the go api next, and leave minio as it is. Currenlty queueDir is empty.
> 
> We noticed this at ~10:00.
> Logs show that our GO api received latest webhook request 9:13
> it was {"Records":null,"Err":null} for some reason. (So minio sends empty webhook for some reason?) Before that there was correct notification, and time between those was 0.2 seconds.
> 
> Next log event for our api was 9:15. Not webhook but another request. So API was working correctly. It has not been restarted today.
> 
> We restarted minio at 10:10, and after that api received thousands of webhook requests.

The nil bodied requests are pings from MinIO before sending an event. That is expected. You can ignore those requests where body == nil 

And what is a go api?

**Comment by Racle** [comment]
> And what is a go api?

Api made with Golang, sorry for not clearing that up sooner.

(and api uses [gin](https://github.com/gin-gonic/gin) as a router)

**Comment by Praveenrajmani** [comment]
Ok @Racle 

Next time if u see this happening, can you try few things

- Ping the webserver if it was active and returned 200 OK
- Check MinIO console if there were any logs
- Check the queueStore if the events were persisting in such situations

Restart the webhook server and then see if the events are being sent

**Comment by Racle** [comment]
> * Check MinIO console if there were any logs
> * Check the queueStore if the events were persisting in such situations

last time console didn't have anything useful. Latest console log was api guide links and `SQS ARNs: arn:minio:sqs:eu-fi-1:1:webhook`

And like I said, queueDir had 1700 files. Those were empitied after minio restart (as they were send to API).

If this happens again, i'll check those again and report here.

**Comment by kannappanr** [comment]
Closing this issue now. Please report a new issue when you see this issue again @Racle
