### ISSUE TITLE
The object size reported to events is wrong when server side encryption is enabled

### ISSUE THREAD

**Issue by fdefilippo** [minio/minio#8407]
If I enable the server side encryption the size reported to events are wrong:

The encryption size on filesystem are 78 byte:

```
ls -ln data/coda2/test2.ebcdic
-rw-r--r-- 1 23232115 30002 78 Oct 16 10:28 data/coda2/test2.ebcdic
```
the rclone client correctly reports the size of the unencrypted file, 48 byte:

```
$ rclone lsjson srv:coda2/test2.ebcdic
[
{"Path":"minio","Name":"minio","Size":48,"MimeType":"application/octet-stream","ModTime":"2019-10-14T18:55:05.000000000Z","IsDir":false}
]
```

the size  on the event are 78:

``` 
{"Records": [{"s3": {"bucket": {"arn": "arn:aws:s3:::coda2", "name": "coda2
", "ownerIdentity": {"principalId": "admin"}}, "object": {"key": "test2.ebcdic", "eTag": "2001
0f00b03170f5311b15fe3290ca6c-1", "size": 78

```
minio is latest release.

**Comment by harshavardhana** [comment]
Thanks we shall fix it @fdefilippo

**Comment by kannappanr** [comment]
@fdefilippo Thanks for reporting the issue. We will take a look and send a fix soon.

**Comment by kannappanr** [comment]
@fdefilippo I am unable to reproduce this with the latest master. I have tried both `SSE-S3` and `SSE-C` and am unable to reproduce it. The encrypted file is `58` bytes and the unencrypted file is `26` bytes. The event received has the correct size. I tested notification using webhooks.

**Comment by fdefilippo** [comment]
hi, I rebuilt the test environment from scratch and actually the problem does not occur. thanks for support.
