### ISSUE TITLE
How to config BaseUrl when deploy

### ISSUE THREAD

**Issue by RedzRedz** [minio/minio#8421]
In my production, the minio is deployed as a docker service. And the backend service visit minio by docker service name, for example cx-minio.The backend service use dotnet core sdk.   
Its no problem, if just upload or download file by backend service. 
If i want get the preview url, the url is startwith 'cx-minio', which can't be visit from web.  
So, how to set a baseurl which is different with minio endpoint, the previewUrl is start with baseUrl.

**Comment by harshavardhana** [comment]
Docker is running in its own networking layer. You need to run your application on the same network.

Unfortunately this is out of our scope, docker DNS is not visible on the host system because of how docker manages DNS and it's networking.  You need to consult docker docs on how to access services with their DNS names and how to expose them on the host system.

**Comment by RedzRedz** [comment]
I export minio, and minio can access from web ouside the docker, but the backend service is also deploy in docker and it visit minio container by minio docker service name(cx-minio). Because backend service is in the same docker stack with minio, they are connected.  
But minio sdk return  'cx-minio/.../...', when i call preview url, because the endpoint config in backend service in cx-main.The previewUrl is startwith the endpoint.  
I want to config a baseUrl, when i get the previewUrl from minio, it will startwith baseUrl not endpointUrl.Beause endpointUrl maybe not access from web.

**Comment by harshavardhana** [comment]
I have no idea what all of this means and cannot conclude from the limited information in this issue

To start with @RedzRedz 

- You haven't used the issue template to describe your issue appropriately
- MinIO version, Docker version, client SDK which language?
- is it AWS SDK, MinIO SDK? or your own SDK? 

Without all this info the only plan forward is we close this issue in few hrs - if you simply want to ask questions on the setup just join our https://slack.min.io

**Comment by RedzRedz** [comment]
docker version: 19.03.02  
minio image: latest  
client sdk: dotnet minio 3.0.11  
Minio Service named 'cx-minio', backend service named 'cx-attachment', they are in the same docker stack 'cx', so they are connect.  
The backend service config the endpoint of minio service 'cx-minio', if i get the previewUrl by minio client, it return `cx-minio/...` which can't be access by web.

**Comment by jessetalk** [comment]
@harshavardhana  we met the same issue as well
the endpoint we set is：cx-main-minio:9000  (cx-main-minio is the docker service name to access in one docker network internally )  so we get the preview url is :  http://cx-main-mini:9000/path/{preview_url} which is not accessable. Is there a way to set the preview base url without changing the endpoint?

**Comment by harshavardhana** [comment]
MinIO is an S3 API endpoint, the usecase is not clear here, not sure what is not working. 

Closing this issue, please resubmit with more clarity. Preferably with a client code.
