### ISSUE TITLE
S3 SELECT - syntax difference between AWS & MinIO

### ISSUE THREAD

**Issue by MatinF** [minio/minio#8422]
We're using the S3 SELECT to fetch data from CSV files across both AWS and MinIO, with outset in a frontend platform based on the javascript SDK.

We run a standard S3 SELECT query, illustratively as below:

`SELECT ParameterX FROM S3Object WHERE ParameterY in ['X', 'Y']`

This works when fetching from an AWS S3 backend - but when fetching from a MinIO backend, we need to replace the above with the below alternative notation.

`SELECT ParameterX FROM S3Object WHERE ParameterY in ('X', 'Y')`

Based on a reply from Harshavardhana on the Slack channel, this is likely unintentional. It would be great to get this resolved so that we can use consistent syntax.

Martin

**Comment by p11o** [comment]
I tested both syntaxes on S3, and they both work, however only the `()` syntax works on MinIO.  Maybe a quicker workaround would be to update your codebase to always use `()`.  @MatinF Can you confirm?

For my reference, the code that defines the grammar is here: https://github.com/minio/minio/blob/master/pkg/s3select/sql/parser.go#L150-L153

**Comment by MatinF** [comment]
[moved S3 select question regarding more general syntax support to separate issue]

**Comment by klauspost** [comment]
@MatinF Could you add a separate issue for the second problem? It is very well described, so putting in the info you have above should be fine.

**Comment by MatinF** [comment]
Raised the issue regarding strings/dates in the columns in #8458 now
