### ISSUE TITLE
AWS S3 Inventory - support in MinIO?

### ISSUE THREAD

**Issue by MatinF** [minio/minio#8423]
AWS S3 supports the use of an Inventory functionality as outlined below:
https://docs.aws.amazon.com/AmazonS3/latest/dev/storage-inventory.html

This is useful in providing end users the ability to get additional information about their objects summarized in a light-weight log file in a bucket.

As an example of a use case, we would like to let users enable this and then use the S3 SELECT query to extract object data from such a file from specific periods (e.g. last 7 days) and display things like e.g. MB uploaded in a javascript frontend chart. Doing this with recursive listing can get very heavy for millions of objects.

Martin

**Comment by kannappanr** [comment]
@MatinF We have not implemented these APIs currently. Will have to check internally and get back to you
