### ISSUE TITLE
Vultr object storage :: Question

### ISSUE THREAD

**Issue by ghost** [minio/minio#8424]
Hi team,

Does **minio** support [Vultr object storage](https://www.vultr.com/products/object-storage/) the documentation can be viewed [here](https://www.vultr.com/docs/vultr-object-storage) I know it supports **s3cmd** but has anyone used it with **minio**.

**Comment by harshavardhana** [comment]
We would like to keep GitHub issues to largely focus on issues, feature requests. For general QA please join https://slack.min.io we can discuss this in more detail. 

Thanks closing this issue now.
