### ISSUE TITLE
MinIO STS Identity Federation with Pivotal Cloud Foundry using Client Grants

### ISSUE THREAD

**Issue by sydseter** [minio/minio#8426]
I know this might not be possible, but if it is, it would be very interesting for us.
We are trying to see if it is possible to setup MinIO STS Identity Federation with Pivotal Cloud Foundry using client grants.

I set: 

export MINIO_IAM_JWKS_URL=https://uaa.dev.cfdev.sh/token_key #8419 (see: https://docs.cloudfoundry.org/api/uaa/version/74.4.0/index.html#token-key-s)

Created: client credentials with the following properties:

  accessKey: GKILP9N2HURPXSHMGDL0
  aud: scim password clients uaa minio-test
  authorities: clients.read password.write clients.secret uaa.resource clients.write uaa.admin scim.write scim.read
  azp: minio-test
  cid: minio-test
  client_id: minio-test
  exp: 1571704634
  grant_type: client_credentials
  iat: 1571661434
  iss: https://uaa.dev.cfdev.sh/oauth/token
  jti: 602d513fad56499c9b5f449c5295a1fc
  rev_sig: 339d3fae
  scope: clients.read password.write clients.secret uaa.resource clients.write uaa.admin scim.write scim.read
  sub: minio-test
  zid: uaa

I then run: https://github.com/minio/minio/blob/master/docs/sts/client-grants.go

like this:

go run client-grants.go -cid minio-test -csec minio-test -sts-ep http://localhost:9000 -idp-ep https://uaa.dev.cfdev.sh/oauth/token

Here is the trace.log: 
[trace.log](https://github.com/minio/minio/files/3751115/trace.log)

## Expected Behavior

Expected perhaps to succeed with:

//client-grants.go
clnt.PutObject("my-bucketname", "my-objectname", d, d.Size(), minio.PutObjectOptions{})

But maybe this was very optimistic.

Strangely enough I got this generated under .minio.sys/config/iam/sts/GKILP9N2HURPXSHMGDL0/identity.json

    {"version":1,"credentials": {"accessKey":"GKILP9N2HURPXSHMGDL0","secretKey":"jJvlKJqNywPun3mgmV339w8+ilakKL1aTcRB6ynZ","expiration":"2019-10-22T00:37:14Z","sessionToken":"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJHS0lMUDlOMkhVUlBYU0hNR0RMMCIsImF1ZCI6WyJzY2ltIiwicGFzc3dvcmQiLCJjbGllbnRzIiwidWFhIiwibWluaW8tdGVzdCJdLCJhdXRob3JpdGllcyI6WyJjbGllbnRzLnJlYWQiLCJwYXNzd29yZC53cml0ZSIsImNsaWVudHMuc2VjcmV0IiwidWFhLnJlc291cmNlIiwiY2xpZW50cy53cml0ZSIsInVhYS5hZG1pbiIsInNjaW0ud3JpdGUiLCJzY2ltLnJlYWQiXSwiYXpwIjoibWluaW8tdGVzdCIsImNpZCI6Im1pbmlvLXRlc3QiLCJjbGllbnRfaWQiOiJtaW5pby10ZXN0IiwiZXhwIjoxNTcxNzA0NjM0LCJncmFudF90eXBlIjoiY2xpZW50X2NyZWRlbnRpYWxzIiwiaWF0IjoxNTcxNjYxNDM0LCJpc3MiOiJodHRwczovL3VhYS5kZXYuY2ZkZXYuc2gvb2F1dGgvdG9rZW4iLCJqdGkiOiI2MDJkNTEzZmFkNTY0OTljOWI1ZjQ0OWM1Mjk1YTFmYyIsInJldl9zaWciOiIzMzlkM2ZhZSIsInNjb3BlIjpbImNsaWVudHMucmVhZCIsInBhc3N3b3JkLndyaXRlIiwiY2xpZW50cy5zZWNyZXQiLCJ1YWEucmVzb3VyY2UiLCJjbGllbnRzLndyaXRlIiwidWFhLmFkbWluIiwic2NpbS53cml0ZSIsInNjaW0ucmVhZCJdLCJzdWIiOiJtaW5pby10ZXN0IiwiemlkIjoidWFhIn0.88nn1FNfMRCzn5rV0QFFhJBbzujx7wJa917Gy_uf2gz_bPKf52FSZIu1kde-mzmt03BhFtnoaktIy-b1d-kXcg","status":"enabled"}}

## Current Behavior

    13:33:55.116 [403 Forbidden] s3.GetBucketLocation localhost:9000/my-bucketname/?location=  [                 381µs  🠉 98 B  🠋 535 B
    13:33:55.117 [403 Forbidden] s3.PutObject localhost:9000/my-bucketname/my-objectname [                 349µs  🠉 140 B  🠋 572 B

## Possible Solution

What is missing is perhaps to add minio s3 as a service provider on Pivotal Cloud Foundry UAA. Do you use SAML here? How do I then find metadata.xml for minio?

Do I need to create a minio user and setup readwrite policy before AssumeRoleWithClientGrants can be used?

## Steps to Reproduce (for bugs)
1. Installed PCF-dev https://docs.pivotal.io/pcf-dev/index.html
2. gem install cf-uaac
3. uaac target https://uaa.dev.cfdev.sh
4. uaac token client get admin -s admin-client-secret
5. uaac client add minio-test —name mini-test —scope "`uaac client get admin |  awk '/:/{e=0}/authorities:/{e=1;if(e==1){$1="";print}}'` uaa.resource" --authorities "`uaac client get admin |  awk '/:/{e=0}/authorities:/{e=1;if(e==1){$1="";print}}'` uaa.resource" # secret: minio-test
6. export MINIO_IAM_JWKS_URL=https://uaa.dev.cfdev.sh/token_key
7. minio server ./data
8. go run client-grants.go -cid minio-test -csec minio-test -sts-ep http://localhost:9000 -idp-ep https://uaa.dev.cfdev.sh/oauth/token

## Context
We are trying to provide a set of short term credentials using our customer's existing client credentials so that we can improve the security and make it easier for them to do their minio S3 integration using their existing credentials. (Current example has been done from localhost to assert Minio's current capabilities)

## Regression
No

## Your Environment
Minio: 

Version: 2019-09-05T23:24:38Z
Release-Tag: RELEASE.2019-09-05T23-24-38Z
Commit-ID: b52a3e523cc3c4debc0ea2f86386377df5355c81

PCF dev:

pcfdev-v1.2.0-darwin.tgz

**Comment by harshavardhana** [comment]
The reason it won't succeed because of your JWT which is generated by the IDP doesn't have `policy` claim - https://github.com/minio/minio/blob/master/docs/sts/wso2.md#4-jwt-claims 

This policy claim points to the canned policies on MinIO

**Comment by kannappanr** [comment]
@sydseter Closing this issue based on the above comment. Please feel free to let us know if you think otherwise
