### ISSUE TITLE
Question in regards to client credentials MinIO STS Identity Federation

### ISSUE THREAD

**Issue by sydseter** [minio/minio#8427]
Question in regards to client credentials MinIO STS Identity Federation. 

When configuring (client grants)[https://github.com/minio/minio/blob/master/docs/sts/client-grants.md]. Is there some sort of mapping between the default canned policies and the client credentials? Do I need to create a user and a policy before AssumeRoleWithClientGrants can be used?

**Comment by harshavardhana** [comment]
You need to add custom claims https://github.com/minio/minio/blob/master/docs/sts/wso2.md#4-jwt-claims - we look for `policy` claim which points to the right canned policy on MinIO 

Closing this issue - feel free to join our slack for more real-time Q/A discussions.
