### ISSUE TITLE
The configuration path of coredns etcd is modified to /coredns and cannot be resolved

### ISSUE THREAD

**Issue by Jacky2** [minio/minio#8429]
The configuration path of coredns etcd is modified to /coredns and cannot be resolved at this time.

The reason is that Minio Federation does not support etcd path configuration and save to the default /skydns path.

minio version: 
minio/minio:RELEASE.2019-09-18T21-55-05Z

**Comment by nitisht** [comment]
@Jacky2 closing this as incomplete, please follow the issue template, it will help us understand your problem and help you better
