### ISSUE TITLE
Distributed MinIO 4 nodes on 2 docker compose 2 nodes on each docker compose

### ISSUE THREAD

**Issue by robertza93** [minio/minio#8430]
I have two docker compose 
a) docker compose file 1:
minio1:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=abcd123
      - MINIO_SECRET_KEY=abcd12345
    ports:
      - "9001:9000"
    volumes:
      - /tmp/1:/export
    command: server --address minio1:9000 http://minio1:9000/export http://minio2:9000/export http://${DATA_CENTER_IP}:9003/tmp/3 http://${DATA_CENTER_IP}:9004/tmp/4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio1:9000/minio/health/live"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 3m

  minio2:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=abcd123
      - MINIO_SECRET_KEY=abcd12345
    ports:
      - "9002:9000"
    volumes:
      - /tmp/2:/export
    command: server --address minio2:9000 http://minio1:9000/export http://minio2:9000/export http://${DATA_CENTER_IP}:9003/tmp/3 http://${DATA_CENTER_IP}:9004/tmp/4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio2:9000/minio/health/live"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 3m
b) docker compose file 2:
services:
  minio3:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=abcd123
      - MINIO_SECRET_KEY=abcd12345
    ports:
      - "9003:9000"
    volumes:
      - /tmp/3:/export
    command: server --address minio3:9000 http://minio3:9000/export http://minio4:9000/export http://${DATA_CENTER_IP}:9001/tmp/1 http://${DATA_CENTER_IP}:9002/tmp/2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio3:9000/minio/health/live"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 3m

  minio4:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=abcd123
      - MINIO_SECRET_KEY=abcd12345
    ports:
      - "9004:9000"
    volumes:
      - /tmp/4:/export
    command: server --address minio4:9000 http://minio3:9000/export http://minio4:9000/export http://${DATA_CENTER_IP}:9001/tmp/1 http://${DATA_CENTER_IP}:9002/tmp/2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio4:9000/minio/health/live"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 3m

## Expected Behavior
Minio should start up as normal.

## Current Behavior
Waiting for a minimum of 2 disks to come online (elapsed 2m25s)
Unable to connect to http://minio4:9000/export: volume not found
Unable to connect to http://192.168.8.104:9001/tmp/1: Invalid version found in the request 
Unable to connect to http://192.168.8.104:9002/tmp/2: Invalid version found in the request

## Steps to Reproduce (for bugs)
See description above.

## Your Environment

* Version used (`minio version`): RELEASE.2019-08-29T00-25-01Z
* Operating System and version (`uname -a`): linux mint 19

**Comment by nitisht** [comment]
Can you try with `image: minio/minio:RELEASE.2019-10-12T01-39-57Z`

**Comment by Praveenrajmani** [comment]
@robertza93 There is a version mismatch among the instances.. Can you check if all the instances/DCs run the same version of MinIO?

**Comment by robertza93** [comment]
I tried with version minio/minio:RELEASE.2019-10-12T01-39-57Z on each node and result is the same

**Comment by Praveenrajmani** [comment]
And also MinIO running on `DATA_CENTER_IP` @robertza93 ?

**Comment by robertza93** [comment]
There are two docker-compose where first has 2 nodes of minio and the second also has 2 nodes of minio. Is it possible to have 2 machines where each has 1 docker compose with 2 instances minio each?

**Comment by robertza93** [comment]
Yes, I have 2 docker compose on 2 data centers

**Comment by robertza93** [comment]
I think it should work even if I run one docker compose because I have runned two nodes of minio and mapped other 2 which are offline.

**Comment by nitisht** [comment]
@robertza93 can you join us on Slack (https://slack.min.io) for more realtime discussion

**Comment by kannappanr** [comment]
@robertza93  Closing this issue here. Please join us at our slack channel as mentioned above
