### ISSUE TITLE
Cache entries are deleted if a client reads only part of an object

### ISSUE THREAD

**Issue by mbitsnbites** [minio/minio#8431]
When a client only reads a part of a cached object, e.g. a client process starts reading a large object but then gets terminated before the entire object was read, the corresponding cache entry will be treated as if it had been subject to bitrot, and thus deleted from the cache.

## Expected Behavior
The cache entry should remain in the cache (until a *real* bitrot event is detected).

## Current Behavior
The cache entry is deleted from the cache.

## Possible Solution
`bitrotReadFromCache` should not return an error when `io.ErrClosedPipe` occurs (see https://github.com/minio/minio/blob/master/cmd/disk-cache-backend.go#L587 ). Instead it should return `nil`.

## Steps to Reproduce (for bugs)
Using an S3 client, `<s3client>`, for reading an object from a minio server (configured to cache objects), do:
1. Read the complete object using `<s3client>` (this should put the object in the cache).
2. Read the complete object again using `<s3client>`, observing that we get a cache hit (e.g. by monitoring the relevant network traffic or comparing the time it takes to perform the transfer).
3. Read the object again, but this time only read a part of the object by terminating `<s3client>` before it finishes the transfer (**this will evict the cache entry!**)
4. Read the complete object again using `<s3client>`, and observe that there is a cache miss.

## Context
This problem happens with large data streams, where we sometimes need to read only part of the stream, or need to interrupt a reading process before it has completed the read operation.

## Regression
No (AFIK)

## Your Environment
* Version used (`minio version`): GitHub master
* Operating System and version (`uname -a`): Ubuntu 18.04

**Comment by kannappanr** [comment]
@mbitsnbites Thanks for reporting this issue, we have a PR in review to fix this issue
