### ISSUE TITLE
Minio doesn't send notifications #8403

### ISSUE THREAD

**Issue by Racle** [minio/minio#8435]
Reopening #8403 

We have currently 3000+ events in our persistStorage folder.

Restarting either minio OR our api (made with golang) gets minio to send events again.

Minio doesn't log anything.
Our golang api still works and we can manually POST to /webhook url. (we tested this BEFORE restarting API or minio)
API always returns empty result with 200 OK no matter what.

So minio randomly stops sending records, and doesn't log any errors. Our API doesn't log any errors either and doesn't crash. And still works even when minio stops sending events.

Environment hasn't changed since our latest issue #8403 

Also pinging @kannappanr, who closed earlier issue.

**Comment by Praveenrajmani** [comment]
@Racle Did it work when you restarted webhook alone and not MinIO?

**Comment by Racle** [comment]
> @Racle Did it work when you restarted webhook alone and not MinIO?

Yes, minio sent messages after that.

Earlier same happened when we restarted only minio.

There is nothing to show why minio stops sending notifications, it just stops. No crashing on our side, no logs on minio (and it only logs when it starts or stops).

Our API logs every call that is made to it. Our files shows that first message which was stuck on our server was 8:01, and latest /webhook call was 8:01. No errors then, no crashing.

**Comment by Praveenrajmani** [comment]
I could relate this issue with https://github.com/minio/minio/issues/8324. And also as you said earlier that the same happens with listenBucketNotifications - mc watch internally uses listenBucketNotiications. We will investigate this further to find what is causing this @Racle

**Comment by Racle** [comment]
Could be related. But then this also happens with one server instance. Our just seems to be very random. It might take 5 hours to stop or multiple days. 

And with redis, listenBucketNotifications and webhook by our testing.

**Comment by Praveenrajmani** [comment]
There might be a problem in your network switch which requires a periodic flush (restarts) which is causing this intermittent failure. Or, this can be a golang bug

Can you run the following golang script in your machine where MinIO is hosted, This script sends events periodically to the configured webhook. This might take us to the reason.

```
package main

import (
	"fmt"
	"net/http"
	"time"
	"io"
	"io/ioutil"
	"net"
	"bytes"
)

var (
	// Set your webhook url here
	endpoint = "http://localhost:8080/"
	eventJSON = `{"EventName":"s3:ObjectCreated:Put","Key":"testb/issue","Records":[{"eventVersion":"2.0","eventSource":"minio:s3","awsRegion":"","eventTime":"2019-10-23T16:09:39Z","eventName":"s3:ObjectCreated:Put","userIdentity":{"principalId":"minio"},"requestParameters":{"accessKey":"minio","region":"","sourceIPAddress":"127.0.0.1"},"responseElements":{"content-length":"0","x-amz-request-id":"15D052800B058746","x-minio-deployment-id":"1ad93b8f-9f8b-4ca4-b61b-9b053c985629","x-minio-origin-endpoint":"http://192.168.0.123:9000"},"s3":{"s3SchemaVersion":"1.0","configurationId":"Config","bucket":{"name":"testb","ownerIdentity":{"principalId":"minio"},"arn":"arn:aws:s3:::testb"},"object":{"key":"issue","size":26,"eTag":"c71e2e92d0cd73d9eb7f85a2bf1fa69a-1","contentType":"application/octet-stream","userMetadata":{"content-type":"application/octet-stream"},"versionId":"1","sequencer":"15D052800C1722E0"}},"source":{"host":"127.0.0.1","port":"","userAgent":"MinIO (linux; amd64) minio-go/v6.0.39 mc/2019-10-23T16:01:36Z"}}]}`
)

func main() {
	httpClient := &http.Client{
		Transport: &http.Transport{
			DialContext: (&net.Dialer{
				Timeout:   5 * time.Second,
				KeepAlive: 5 * time.Second,
			}).DialContext,
			TLSHandshakeTimeout:   3 * time.Second,
			ResponseHeaderTimeout: 3 * time.Second,
			ExpectContinueTimeout: 2 * time.Second,
		},
	}

	for {
		// Set the time interval 
		time.Sleep(5 * time.Second)
		
		fmt.Println("---> Sending an event")
		req, err := http.NewRequest("POST", endpoint, bytes.NewReader([]byte(eventJSON)))
		if err != nil {
			fmt.Println("Error in creating request ", err)
			continue
		}
		
		req.Header.Set("Content-Type", "application/json")
		
		resp, err := httpClient.Do(req)
		if err != nil {
			fmt.Println("Error in Do: ", err)
			continue
		}
		
		io.Copy(ioutil.Discard, resp.Body)
		_ = resp.Body.Close()
		
		if resp.StatusCode < 200 || resp.StatusCode > 299 {
			fmt.Println("sending event failed with %v", resp.Status)
			continue
		}

		fmt.Println("---> Successfully sent")

	}
	
}

```

NOTE:
- You can set the `endpoint` to the one pointing to your webhook server
- You can modify the timeout based upon the frequency of requests
- You have to set the TLSClientConfig option if TLS is enabled
- Use go version go1.13

**Comment by Racle** [comment]
They are both inside docker network (default, created with docker-compose) and running on same virtual machine on same docker-compose stack.

**Comment by Racle** [comment]
> There might be a problem in your network switch which requires a periodic flush (restarts) which is causing this intermittent failure. Or, this can be a golang bug
> 
> Can you run the following golang script in your machine where MinIO is hosted, This script sends events periodically to the configured webhook. This might take us to the reason.
>

I put script on our server after your post. It's been running every 10 seconds there and has only logged "Sending event" and "Successfully sent". No failures or errors anywhere.

It's been running multiple days just fine, and now it's dead again. Minio stopped sending events to webhook url at 12:36 local time. We restarted our API and persistent storage is empty again.

We also changed our API to return 200 OK and close the connection when it received /webhook post immediately, and run rest of our function after that, so we could eliminate our bugs.

That did not help the situation. So minio bug still exists.

**Comment by Praveenrajmani** [comment]
@Racle The should be some logs when the script stopped. Can you paste it here? For some reasons, the connection gets blocked. AFAICS, This is not related to MinIO as it replays properly when you restart the webhook server. Let us investigate further. The script logs would help. The script is exactly what MinIO is doing internally.

**Comment by Praveenrajmani** [comment]
The events would end up in queueStore only if the connection is inactive / MinIO cannot connect to the target.

**Comment by Racle** [comment]
> @Racle The should be some logs when the script stopped. Can you paste it here? For some reasons, the connection gets blocked. AFAICS, This is not related to MinIO as it replays properly when you restart the webhook server. Let us investigate further. The script logs would help. The script is exactly what MinIO is doing internally.

Script didn't stop, it probably would still run just fine if I didn't stop it by hand. It logged those two lines every 10s as I said. No crashes either. 

And our api logged every connection made by minio (until it stopped) and everything script send to our api.

And only minio in same docker network stops sending data. Our other api's talk to perfectly and that script up there.

**Comment by Praveenrajmani** [comment]
Are you pointing to the same webhook endpoint in the script? Maybe in a different path?

**Comment by Praveenrajmani** [comment]
@Racle ?

**Comment by Racle** [comment]
> Are you pointing to the same webhook endpoint in the script? Maybe in a different path?

Exactly same path what is configured to our minio instance. Same http://api:1234/webhook url which is used by docker internal dns on same docker-compose network. 
And I can post via postman that (outside that network).

And older 2018 January release didn't do this. This happened after we upgraded to latest minio. (and we used listenbucket before we switched to webhook when listener didn't worked anymore)

**Comment by Praveenrajmani** [comment]
@Racle Let me give a custom image with some internal logs. Can you use that instead? Collecting those logs can help

**Comment by Racle** [comment]
> @Racle Let me give a custom image with some internal logs. Can you use that instead? Collecting those logs can help

In theory, yes. 
But as this is server is in use, custom image should be as stable as possible.

We have exactly same setup on less used servers (3 other servers with same stack), and those seems to be working just fine. 
It might be something to do with higher traffic

**Comment by Racle** [comment]
Logs here. Minio script is still sending messages while minio instance just stop.
I removed our minio objects from logs.
And messages are not in fully order. Sometimes golang logs so fast that our logging server cannot keep up and misplaces log rows. That's why it seems to be little off sometimes.

Logs also have random ID (like 1SsHS9jOffkIcaUEFHOhx4srGvL) so we can see logging events. 
POST /webhook log doesn't have this ID, as it's generated by GIN

[log.txt](https://github.com/minio/minio/files/3784312/log.txt)

**Comment by Praveenrajmani** [comment]
@Racle Here is the custom image - `praveenminio/testwebhook` . This image has some log prints added. Can you use this image and report the logs here?

**Comment by Racle** [comment]
> @Racle Here is the custom image - `praveenminio/testwebhook` . This image has some log prints added. Can you use this image and report the logs here?

testwebhook is up and running. I'll report back with logs if we see problems with minio.

It can be day or it can take week to get stuck again.

**Comment by Racle** [comment]
@Praveenrajmani 
```
Post http://our_api:1234/webhook: dial tcp 123.45.0.67:1234: connect: cannot assign requested address
```

I also tried to curl from minio instance to our api (with DNS name and with IP), 
error says `curl: (7) Couldn't connect to server`.

I checked IP and it was correct, and other machines on same docker-compose network can curl to that with DNS name and with IP.

Seems to be something with docker network or with our api perhaps. Or minio docker image. After restarting our api minio sends messages correctly again.

Next step is to figure why this happens :sweat_smile:

**Comment by Praveenrajmani** [comment]
> @Praveenrajmani
> 
> ```
> Post http://our_api:1234/webhook: dial tcp 123.45.0.67:1234: connect: cannot assign requested address
> ```
> 
> I also tried to curl from minio instance to our api (with DNS name and with IP),
> error says `curl: (7) Couldn't connect to server`.
> 
> I checked IP and it was correct, and other machines on same docker-compose network can curl to that with DNS name and with IP.
> 
> Seems to be something with docker network or with our api perhaps. Or minio docker image. After restarting our api minio sends messages correctly again.
> 
> Next step is to figure why this happens sweat_smile

looks like a docker network issue @Racle

**Comment by Racle** [comment]
That's what I was thinking also.

It's just odd that minio machine is only which cannot connect to that api. Everything else connects just fine..

I'll close this and open new one if I find something wrong with minio docker container, but currently it's probably network issue..

**Comment by Racle** [comment]
@Praveenrajmani
Just little update.

I was debugging minio issues (they still persist)

I found out that it might to be something with TCP sockets / connections. 

```
netstat -a | wc -l
28265
```
All connections are with "ESTABLISHED" status

There is lots of connections which stays open.. I don't know if it's our API or minio who doesn't close connections.

Our API uses [gin](https://github.com/gin-gonic/gin) and sends out `c.String(200, "")`. 
I changed that to `c.String(200, "ok")` and see if that fixes our problem.

Could it be that If minio doesn't get anything back, it keeps connection open?

**Comment by Racle** [comment]
For quick look, after I send `c.String(200, "ok")` out instead `c.String(200, "")` connections seems to be closing properly.

Currently I would say this is could be bug in minio, which doesn't close connections if there is no return message.


For fix, I'm just guessing here (as I write mainly Node.js and partly only with Golang)

at https://github.com/minio/minio/blob/9e7a3e6adc6390b9b77cd1ee72c7d7870d64b0e2/pkg/event/target/webhook.go#L145

On online examples, I found that in many code examples there uses `defer resp.Body.Close()` instead of `_ = resp.Body.Close()`.

Could something like that fix issue here also?

EDIT: Tested this (return message) again. Reverted back to first version and connections didn't close properly.

**Comment by harshavardhana** [comment]
> On online examples, I found that in many code examples there uses `defer resp.Body.Close()` instead of `_ = resp.Body.Close()`.

defer is only to close upon return since we do not read body. This is not an issue on our end.

> Currently I would say this is could be bug in minio, which doesn't close connections if there is no return message.

I don't know where you are getting this information. MinIO uses Go HTTP client, the bug is perhaps  in your Webhook server which doesn't implement or support keep-alives properly.

**Comment by Racle** [comment]
@harshavardhana all I can say that after I added "ok" to our return message instead of "", we had zero issues with webhooks.
If we returned only "", connection would be keep open on minio container. That is the reason why I believe it's bug in minio. 

And because `resp` uses `body.close()` I thought that it fails because of the empty body, and `defer` would ensure that connection closes properly.

**Comment by Racle** [comment]
@harshavardhana 
I created quick test.

This golang app is able to reprocude this issue:
```golang
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	router := gin.Default()
	router.POST("/webhook-ok", webhookReturnOK)
	router.POST("/webhook-empty", webhookReturnEmpty)
	router.Run(":9111")
}

func webhookReturnOK(c *gin.Context) {
	c.String(200, "ok")
}

func webhookReturnEmpty(c *gin.Context) {
	c.String(200, "")
}
```
When using "webhook-empty" endpoint, connections would be in "ESTABLISHED" state and never close.
![Screenshot from 2019-12-11 08-31-59](https://user-images.githubusercontent.com/759091/70597950-5cbac100-1bf2-11ea-8925-7b8babcec5b1.png)

But when I changed that to "webhook-ok" endpoint, connections would be in "TIME_WAIT" state and close after while.
![Screenshot from 2019-12-11 08-33-42](https://user-images.githubusercontent.com/759091/70597983-722feb00-1bf2-11ea-8b6e-bd5da3184a50.png)

On both cases I started minio and uploaded 5 items to test bucket.

So far this seems to be minio bug. 

I've attached full project test folder for you to use in testing.
[webhook-minio-test.zip](https://github.com/minio/minio/files/3948779/webhook-minio-test.zip)

It uses your host network

How to use this:

1. Run `go get`, `go build` and `./webhook-minio-test` to get go app started
2. Run minio with 'docker-compose up' -command
3. Create bucket named `test`
4. To change webhook endpoint, change from `minio/config.json` file from `webhook-ok` to `webhook-empty` and run step 5. again
5. Update minio config fast with `sh minio-update-config.sh`. This will also create event listener to minio.
6. to check stuck connections, run 'netstat -natp | grep 9111`

**Comment by harshavardhana** [comment]
I can't still understand why is this a MinIO bug. We are not doing anything special here. The behavior is as per HTTP specification AFAICS which is the behavior of Go net/http client.

If there is no body then Go doesn't keep the connection alive for POST, which is perhaps working as expected in accordance with HTTP standard because HTTP sends an explicit close connection on empty body. This sent by the server itself.

defer and Close has no special meaning which you referred previously, the only difference is when is Close called closing it early or later doesn't affect anything.

In any case I have PR for more performant behavior here by using a better transport defaults.

**Comment by Racle** [comment]
Quick note, I tested using defer. Nothing changed as you expected. 
And I have to give props to minio, develop setup was pretty much painless to get up and running. Great work! 

And if this isn't minio bug, then it's have to be something to do with Gin which doesn't close connections on empty body. Just odd that many code examples sends empty body while using Gin.

**Comment by harshavardhana** [comment]
Will try to understand this behavior in more detail tomorrow, will keep you posted.

**Comment by Racle** [comment]
Odd behavior indeed.

Glad it can be solved currently when sending response in body. You just have to know this. 

I'm also little lost here why this keeps happening, as this seems to be only service + API which behaves like this (could be just coincidence, not ruling that out). Extremely odd.

**Comment by maitredede** [comment]
Hi, sorry for bothering...

Since the empty string value is the zero value of strings, maybe the internals of http responses are waiting for the body of the `200` response. Can the http status `201` "No content" be more appropriate for an empty response ?
If the response `200` + "ok"  works fine full time, that is ok for me :)

**Comment by harshavardhana** [comment]
Webhooks has moved to more performant custom transport, closing this issue for now. Please re-open if you see issues again.
