### ISSUE TITLE
Some inconsistencies between the online documentation and minio server help files

### ISSUE THREAD

**Issue by sydseter** [minio/minio#8440]
Thank you for providing the open-source community with such a great s3 solution.
I found some inconsistencies between the minio server help file and the online documentation.
I one of these wrong? Or can both approaches be used? Is one of them deprecated?

## Expected Behavior

I would expect minio server --help and the KMS documentation online: https://docs.min.io/docs/minio-kms-quickstart-guide.html to be consistent.

## Current Behavior

Here is the minio server --help documentation:

  6. Start minio server with KMS enabled.
     $ export MINIO_SSE_VAULT_APPROLE_ID=9b56cc08-8258-45d5-24a3-679876769126
     $ export MINIO_SSE_VAULT_APPROLE_SECRET=4e30c52f-13e4-a6f5-0763-d50e8cb4321f
     $ export MINIO_SSE_VAULT_ENDPOINT=https://vault-endpoint-ip:8200
     $ export MINIO_SSE_VAULT_KEY_NAME=my-minio-key
     $ minio server /home/shared

Here is the online documentation:

export MINIO_KMS_VAULT_STATE=on
export MINIO_KMS_VAULT_APPROLE_ID=8c03926c-6c51-7a1d-cf7d-62e48ab8d6d7
export MINIO_KMS_VAULT_APPROLE_SECRET=edd8738c-6efe-c226-74f9-ef5b66e119d7
export MINIO_KMS_VAULT_ENDPOINT=http://vault-endpoint-ip:8200
export MINIO_KMS_VAULT_KEY_NAME=my-minio-key
export MINIO_KMS_VAULT_AUTH_TYPE=approle
minio server ~/export

## Your Environment

VERSION:
  2019-10-12T01:39:57Z

**Comment by nitisht** [comment]
Thank you for reporting @sydseter we'll take a look

**Comment by harshavardhana** [comment]
This is because we have new changes which are merged into master @sydseter which are not part of release yet.

**Comment by harshavardhana** [comment]
I will revert the docs website to a particular commit ID such that we don't have such inconsistencies.

**Comment by harshavardhana** [comment]
Now the docs should be pointing to the release.. @sydseter

**Comment by sydseter** [comment]
Thank you. That clarifies things.
