### ISSUE TITLE
Support ObjectTagging

### ISSUE THREAD

**Issue by markush81** [minio/minio#8446]
**Is your feature request related to a problem? Please describe.**

My request is related to https://issues.sonatype.org/browse/NEXUS-17645.

It would be really nice to use minio as S3 backend for Nexus, cause it is a good way to have full on-premise Repository Manager with S3.

Currently this does not workout anymore with newer versions of Nexus (started > 1.36.1 ).

**Describe the solution you'd like**
Support ObjectTagging.

**Additional context**

Nexus tries to create following LifecycleConfiguration cause it is using ObjectTagging.

```
<?xml version="1.0" encoding="UTF-8"?>
<LifecycleConfiguration>
   <Rule>
      <ID>Expire soft-deleted objects in blobstore test</ID>
      <Status>Enabled</Status>
      <Filter>
         <Tag>
            <Key>deleted</Key>
            <Value>true</Value>
         </Tag>
      </Filter>
      <Expiration>
         <Days>3</Days>
      </Expiration>
   </Rule>
</LifecycleConfiguration>
```

```
localhost [REQUEST s3.PutBucketLifecycle] 11:20:17.647
localhost PUT /test/?lifecycle
localhost Host: localhost:9000
localhost Amz-Sdk-Invocation-Id: f44bf9c7-b6ae-3a24-1c07-532830ef5545
localhost Authorization: AWS4-HMAC-SHA256 Credential=SECRET/20191026/eu-west-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-md5;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=XXXX
localhost Content-Type: application/xml
localhost User-Agent: aws-sdk-java/1.11.201 Mac_OS_X/10.15 Java_HotSpot(TM)_64-Bit_Server_VM/25.221-b11 java/1.8.0_221 groovy/2.4.15
localhost X-Amz-Date: 20191026T112017Z
localhost Amz-Sdk-Retry: 0/0/500
localhost Connection: Keep-Alive
localhost Content-Length: 244
localhost Content-Md5: dyU0d3AO7M74NbFHktIAVQ==
localhost Expect: 100-continue
localhost X-Amz-Content-Sha256: 51225f717f62f4f01a97b8cb234670c86beb18d7f32549d4c84881bd3c93c848
localhost
localhost [RESPONSE] [11:20:17.649] [ Duration 2.119ms  🠉 400 B  🠋 595 B ]
localhost 400 Bad Request
localhost Content-Length: 336
localhost Content-Security-Policy: block-all-mixed-content
localhost Content-Type: application/xml
localhost Server: MinIO/RELEASE.2019-10-12T01-39-57Z
localhost Vary: Origin
localhost X-Amz-Request-Id: 15D12E734B41D90C
localhost X-Xss-Protection: 1; mode=block
localhost Accept-Ranges: bytes
localhost <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our published schema.</Message><BucketName>test</BucketName><Resource>/test/</Resource><RequestId>15D12E734B41D90C</RequestId><HostId>b5fad3c6-28bd-46e1-abb6-0cacbce9ba00</HostId></Error>
localhost
```

**Comment by kannappanr** [comment]
@markush81 Thanks for the feature request. Not sure if we plan to implement `objectTagging` feature soon, I can check internally and get back to you

**Comment by markush81** [comment]
@kannappanr this would be nice. The motivation behind is to have Nexus including an S3 storage 100% on-premise. Unfortunately Nexus needs ObjectTagging for this.

**Comment by harshavardhana** [comment]
@kannappanr we should close this for now perhaps bring this up in future when we have more cycles to take a look ?

**Comment by kannappanr** [comment]
@markush81 We do not have cycles currently to look at this feature request. Will get to it when we are free with our current tasks.

**Comment by nitisht** [comment]
Fixed by #8754

**Comment by nitisht** [comment]
Reopening till LifeCycle subsystem is hooked to support tags

**Comment by harshavardhana** [comment]
Let's reopen as a new issue which details about lifecycle support.

**Comment by markush81** [comment]
> Let's reopen as a new issue which details about lifecycle support.

@harshavardhana is there already one someone can follow?

**Comment by harshavardhana** [comment]
About which issue @markush81 ?

**Comment by markush81** [comment]
> Reopening till LifeCycle subsystem is hooked to support tags

@harshavardhana for using object tags in lifecycle system, e.g.

```
<LifecycleConfiguration>
   <Rule>
      <ID>Expire soft-deleted objects in blobstore test</ID>
      <Status>Enabled</Status>
      <Filter>
         <Tag>
            <Key>deleted</Key>
            <Value>true</Value>
         </Tag>
      </Filter>
      <Expiration>
         <Days>3</Days>
      </Expiration>
   </Rule>
</LifecycleConfiguration>
```

**Comment by nitisht** [comment]
@markush81 there is no issue yet, but we're already working on this and will send a fix very soon.

**Comment by harshavardhana** [comment]
Feel free to open an issue this issue was about implementing object tagging.

**Comment by markush81** [comment]
> Feel free to open an issue this issue was about implementing object tagging.

https://github.com/minio/minio/issues/8870 and thanks very much for the work.
