### ISSUE TITLE
Docker image fails to build from Dockerfile

### ISSUE THREAD

**Issue by gversmee** [minio/minio#8447]
## Expected Behavior
Docker image should get built using the Dockerfile provided at the root folder.

## Current Behavior
1. Currently, it appears to have an error line 25 of the Docker file: `COPY dockerscripts/docker-entrypoint.sh /usr/bin/` should be `COPY --from=0 /go/minio/dockerscripts/docker-entrypoint.sh /usr/bin/`.
2. Once this replaced, the Dockerfile can be build. However, I'm using minio as a gateway for S3, and after the image is up and running, I get the following error in the javascript console:
```
TypeError: Cannot read property 'reduce' of null
    at M.value (index_bundle-2019-10-23T04-04-41Z.js:51)
    at j (index_bundle-2019-10-23T04-04-41Z.js:37)
    at beginWork (index_bundle-2019-10-23T04-04-41Z.js:37)
    at T (index_bundle-2019-10-23T04-04-41Z.js:37)
    at N (index_bundle-2019-10-23T04-04-41Z.js:37)
    at D (index_bundle-2019-10-23T04-04-41Z.js:37)
    at k (index_bundle-2019-10-23T04-04-41Z.js:37)
    at e (index_bundle-2019-10-23T04-04-41Z.js:37)
    at u (index_bundle-2019-10-23T04-04-41Z.js:37)
    at y (index_bundle-2019-10-23T04-04-41Z.js:37)
```
It's worth noticing that everything works fine when pulling the image directly from Docker hub.

## Steps to Reproduce (for bugs)

```
git clone https://github.com/minio/minio.git
cd minio
docker build -t minio .
docker run -p 9000:9000 \
-e AWS_ACCESS_KEY_ID=<aws access key> \
-e AWS_SECRET_ACCESS_KEY=<aws secret key> \
-e MINIO_ACCESS_KEY=<some access key> \
-e MINIO_SECRET_KEY=<some secret key> \
minio gateway s3
```

Then go to `localhost:9000`, login using `<some access key>` and `<some secret key>`, nothing appears. The javascript console shows the error noticed above

## Context
I'm building my own image because I want to customize the web ui.

## Also
After further review, the error appears since commit 8836d57e3c9d62c02ea677b2fdb72c6f774ad2d4

**Comment by kannappanr** [comment]
@gversmee Thanks for reporting this issue. We will take a look at it.

**Comment by harshavardhana** [comment]
Looks like you modified something locally and there is bug in your code @gversmee

**Comment by gversmee** [comment]
Did you try to reproduce the error using the code I provided?

```
git clone https://github.com/minio/minio.git
cd minio
docker build -t minio .
docker run -p 9000:9000 \
-e AWS_ACCESS_KEY_ID=<aws access key> \
-e AWS_SECRET_ACCESS_KEY=<aws secret key> \
-e MINIO_ACCESS_KEY=<some access key> \
-e MINIO_SECRET_KEY=<some secret key> \
minio gateway s3
```

I'm simply cloning the repo and building the image from there. I don't modify anything. Can you point me to the bug in my code that you are suggesting?

**Comment by harshavardhana** [comment]
Yes, of course, @gversmee the same docker file is used every time to generate our "edge" container image. So my suspicion is your build system.

**Comment by kanagarajkm** [comment]
PR #8453 will fix the javascript error.

**Comment by harshavardhana** [comment]
This is fixed in master branch closing.

**Comment by gversmee** [comment]
Just tested, works perfectly. Thank you.
