### ISSUE TITLE
Minio front-end web returns 504, or has been loading

### ISSUE THREAD

**Issue by Jacky2** [minio/minio#8452]
## Current Behavior
If there are too many bucket files, the Minio front-end web will return 504 when the bucket is opened to browse the file, or it will be loaded all the time. Can paging browsing be supported?
![5](https://user-images.githubusercontent.com/23411395/67659154-a75fe100-f996-11e9-80c3-28dc5d09cb44.png)

## Environment
* Version used (`minio/minio:RELEASE.2019-09-18T21-55-05Z`):

**Comment by kannappanr** [comment]
@Jacky2 Will take a look and get back to you. Thanks for reporting the issue

**Comment by kaankabalak** [comment]
@Jacky2 How many objects do you have in your bucket? A similar issue was fixed by #7805 and it was working without any issues for 100k objects, however I'm assuming you have more objects in your bucket and we can investigate further what is going on based on your feedback. Thanks in advance!

**Comment by Jacky2** [comment]
@kaankabalak 

I can't count the number of files. The usage space is 13g, and the file size ranges from 1KB to 10m.

**Comment by kaankabalak** [comment]
Thanks @Jacky2, I think this info would be sufficient, I will try to reproduce the issue on a similar configuration.

**Comment by astorath** [comment]
I have the same issue with about 800k objects in a bucket. `mc ls` also times out (with 504 code).   Server version: 2020-01-25T02:50:51Z

**Comment by JimKlapwijk** [comment]
> I have the same issue with about 800k objects in a bucket. `mc ls` also times out (with 504 code). Server version: 2020-01-25T02:50:51Z

Same issue with 340k objects, version `RELEASE.2021-11-24T23-19-33Z`.

**Comment by mirekphd** [comment]
Have you tried increasing the application router timeout? I faced similar timeouts when downloading large files (1GB+) in another file server and increasing the HAProxy router timeout to 3600s solved the problem.

This can be done in your deployment config or with the CLI (here: in Openshift 3.x/4.x):
https://stackoverflow.com/questions/67956832/how-to-change-allowed-timeout-for-http-request-response-for-a-route-in-openshift
