### ISSUE TITLE
S3 SELECT (javascript aws-sdk) does not work for strings/dates

### ISSUE THREAD

**Issue by MatinF** [minio/minio#8458]
_Moving this upon request from klauspost into a new issue._

I'm attempting to use the `aws-sdk` in JavaScript to leverage the `S3 SELECT` call on my MinIO back-end server. I originally looked for a MinIO-specific `S3 SELECT` command, but it seems for now that this is not supported - which I guess is fine if the aws-sdk gets full support. 

My challenge is that I'm trying to run a standard `S3 SELECT` call, fetching data from a CSV file (attached below) to get filtered column data. It works fine when I'm fetching numbers (floats, integers) - but if I try to fetch data from a column of strings/dates, it seems to break as in below.

Note that this issue seems to not only be limited to the parameters extracted, but also for string/date parameters being used as part of `WHERE` filters. For example, I'm unable to fetch data from before dateX and after dateY - as well as data, for which a string column is `in (stringX, stringY)`.

**Works OK:**
`sqlExpression: "SELECT EngineSpeed, BackUpLightandAlarmHornCommand FROM S3Object"`

**Does not seem to work:**
`sqlExpression: "SELECT segments FROM S3Object"`
`sqlExpression: "SELECT timestamps FROM S3Object"`

**Dataset:**
[test.zip](https://github.com/minio/minio/files/3779541/test.zip)

**Eror message (trying to fetch timestamps, which have "-" inside):**
```
"err InternalError: json: error calling MarshalJSON for type jstream.KVS: json: error calling MarshalJSON for type json.RawJSON: invalid character '-' after top-level value"
```

Any help would be greatly appreciated. We'd love to leverage this feature in our frontend so I hope full support will be possible. If any details are needed to replicate this, let me know.

Martin

**Comment by klauspost** [comment]
The problem is the conversion from CSV to JSON. This should of course be fixed.

As a quick workaround you can do `SELECT CAST(segments AS STRING) AS segments FROM s3object s` or output to CSV. I suppose the former is easier.
