### ISSUE TITLE
Adding a minio cluster  to a minio federation cluster will not expand the hard disk space of the cluster where the original bucket is located.

### ISSUE THREAD

**Issue by Jacky2** [minio/minio#8460]
**Is your feature request related to a problem? Please describe.**

In the minio federation cluster mode, if the disk space of the cluster where the bucket is located is full, even joining a minio cluster to the federal cluster will not increase the capacity of the bucket, right?

**Comment by nitisht** [comment]
Yes, it will not increase the capacity of that bucket, instead the whole cluster will look bigger. @Jacky2 please join us on Slack (https://slack.min.io) for such questions. Closing this as answered.
