### ISSUE TITLE
Muti policy in a group

### ISSUE THREAD

**Issue by SolarisYan** [minio/minio#8461]
Hi there, i want to set more than one policy with a group, so minio will be more flexible to grant user, but i don't known how to set?

Does minio support this now? If yes, please tell me how to do.

Thanks a lot.

**Comment by vadmeste** [comment]
> i want to set more than one policy with a group,

If I understood your question correctly, you can pass multiple statements in the same policy document, that's how you do that

**Comment by kannappanr** [comment]
@SolarisYan Closing this issue as answered. Please feel free to reach out to us at https://slack.min.io for further such questions.
