### ISSUE TITLE
Issues upgrading MinIO StatefulSet to new release

### ISSUE THREAD

**Issue by prasus** [minio/minio#8466]
I have got a Kubernetes deployment of Minio running on `minio/minio:RELEASE.2019-03-27T22-35-21Z` and it fails when attempting to upgrader the statefulset  to the latest release (`minio/minio:RELEASE.2019-10-12T01-39-57Z`) leaving the pods in a `CrashLoopBackOff` state, had to revert back the changes for bringing the cluster back to an operational state.

## Expected Behavior
The statefulset upgrade should work flawlessly when following the steps  documented [here](https://github.com/minio/minio/blob/master/docs/orchestration/kubernetes/k8s-yaml.md#update-existing-minio-statefulset)

## Current Behavior
The update attempt fails leaving the pods in a crash looping state, with the below error.

```
API: SYSTEM()
Time: 03:53:58 UTC 10/30/2019
DeploymentID: aaf48699-0bc9-4010-908e-9b128a8e4c86
Error: Parent is object .minio.sys/config/iam/policydb/users
       5: cmd/iam-object-store.go:186:cmd.(*IAMObjectStore).migrateToV1()
       4: cmd/iam-object-store.go:206:cmd.(*IAMObjectStore).migrateBackendFormat()
       3: cmd/iam.go:347:cmd.(*IAMSys).doIAMConfigMigration()
       2: cmd/iam.go:371:cmd.(*IAMSys).Init()
       1: cmd/server-main.go:348:cmd.serverMain()
ERROR Unable to initialize IAM system: Parent is object .minio.sys/config/iam/policydb/users
```

## Steps to Reproduce (for bugs)
`ENV`: MinIO cluster running in Kubernetes with 6 replicas.
`Current Release`:  RELEASE.2019-03-27T22-35-21Z

Try upgrading the SS to the latest image using:

```kubectl patch statefulset minio --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"minio/minio:RELEASE.2019-10-12T01-39-57Z"}]’```

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by nitisht** [comment]
we’ll check and get back @prasus

**Comment by harshavardhana** [comment]
This is fixed in https://github.com/minio/minio/pull/8411

**Comment by prasus** [comment]
Thanks for the response, @nitisht I will wait for the next release then.
