### ISSUE TITLE
How to deploy multi minio server instance on one node with multi disks?

### ISSUE THREAD

**Issue by naughtyGitCat** [minio/minio#8467]
**Describe the solution you'd like**

I have machines equipped with multi disks,
I want to deploy a minio cluster with 1 machine and six minio server instance on each disk
or 
a minio cluster with 2 machines and twelve minio servers instance on each disk

**Comment by nitisht** [comment]
please check this https://docs.min.io/docs/multi-tenant-minio-deployment-guide.html

Join us on slack (https://slack.min.io) for more such questions.

**Comment by nitisht** [comment]
Closing this as answered.
