### ISSUE TITLE
File count limit per bucket on Windows

### ISSUE THREAD

**Issue by MSBilgin** [minio/minio#8476]
I downloaded server app and runned it using `minio server d:\miniostorage` command. Then created a bucket named **files** and then uploaded a file to this bucket. When i checked `d:\miniostorage` path i found **files** folder was created and the uploaded file was inside this folder. it looks that Minio puts files directly to this folder. But if users uploads lot of files much more than file system limits what will be happen ? Does Minio create new directory in case of this situation and put other files to new dir?

**Comment by harshavardhana** [comment]
If users upload lot of files they are limited by the filesystem limits. 

Closing this issue please join on https://slack.min.io for further questions like this.
