### ISSUE TITLE
Running a gateway for B2 and trying to connect with Veeam fails with "File names must not end with '/'"

### ISSUE THREAD

**Issue by TheFiZi** [minio/minio#8477]
I've configured a Minio Gateway to connect to a B2 bucket which appears to be working correctly. When I then try to add a "S3 Compatible" repository in Veeam I appear to be able to connect to the bucket from Veeam -> Minio Gateway -> B2 but when I try to create a folder I get the following error:

```
API: PutObject(bucket=VeeamCloudRepo, object=Veeam/)
Time: 15:05:30 PDT 11/01/2019
DeploymentID: 3488a32c-4b75-463e-9852-8e9d1e49ef83
RequestID: 15D32923969B5B4C
RemoteHost: 192.168.0.12
Host: myhost.mydomain.com:9000
UserAgent: APN/1.0 Veeam/1.0 Backup/10.0
Error: [31m[1mb2_upload_file: 400: File names must not end with '/'[0m[0m
       3: cmd\gateway\b2\gateway-b2.go:579:b2.(*b2Objects).PutObject()
       2: cmd\object-handlers.go:1257:cmd.objectAPIHandlers.PutObjectHandler()
       1: net\http\server.go:2007:http.HandlerFunc.ServeHTTP()
```

## Expected Behavior

The directory "Veeam" to be created in the B2 Bucket.

## Current Behavior

The directory fails to create with an error stating directory names can't end with a /. I think Veeam is automatically appending it via their GUI and I cannot explicitly enter a path without a slash because their GUI is all point and click.

![VeeamB2Bucket](https://user-images.githubusercontent.com/1762426/68060032-f7eb7d00-fcbb-11e9-9767-7ff376d92a13.gif)

## Possible Solution

If a slash is added to directory paths automatically strip it? Or add a flag for Minio like `--veeam-compat` or `--stripslashes` which will enable the slash stripping feature?

## Steps to Reproduce (for bugs)

1. Setup Minio as a B2 gateway per the documentation on the wiki page
2. Add SSL to Minio
3. Download the B2 SSL certificate and place it in the Minio certificate store location
4. Start the Minio B2 Gateway
5. Launch Veeam and add the Minio B2 gateway as a S3 compatible gateway under 'Backup Repositories'
6. When asked which folder in the bucket to place Veeam backups click 'New Folder' and enter anything

## Context

This makes it impossible for me to use Minio as a B2 Gateway with Veeam so I can replicate my local backups to B2

## Regression

No

## Your Environment

* Version used (`minio version`): 2019-10-12T01:39:57Z
* Environment name and version (e.g. nginx 1.9.1): Veeam 9.5.4.2886
* Server type and version: Windows, vSphere VM
* Operating System and version (`uname -a`): 2019 Version 1809 (17763.832)
* Link to your project: N/A

**Comment by harshavardhana** [comment]
Directory creates are not allowed on B2 @TheFiZi  MinIO doesn't circumvent backend limits.  It honors and keeps backend limits as is.   There is nothing we can do to fix it here.

**Comment by TheFiZi** [comment]
Ah. I was not aware.

If I pre-create the directory in my bucket via the B2 WebUI it is not visible in Veeam when I am asked to select a folder.

![image](https://user-images.githubusercontent.com/1762426/68060229-ba3b2400-fcbc-11e9-9d54-a18b83a9eb1a.png)

![image](https://user-images.githubusercontent.com/1762426/68060258-ce7f2100-fcbc-11e9-8242-c2f8601f4bf5.png)

Veeam issue?

**Comment by harshavardhana** [comment]
May be we have no idea and no way for us to test. B2 gateway has its own limitations so please use `minio server /data` and let us know if it works.

If yes we can close this issue.

**Comment by TheFiZi** [comment]
I’m away for a few weeks so I won’t be able to test for a bit.

**Comment by Widmo** [comment]
I have the same issue. 

```
Version: 2019-10-12T01:39:57Z
Release-Tag: RELEASE.2019-10-12T01-39-57Z
Commit-ID: bd106408462ecef70debf51f1e6179de950c5812
```

**Comment by harshavardhana** [comment]
Closing this issue and we will get back to this in future as we get more cycles to work on this issue.

In the mean time feel free to send a PR.

**Comment by MaartenUreel** [comment]
@TheFiZi did you ever find a working solution to have B2 as S3 compatible storage? I'm stuck at the same step here :)

**Comment by TheFiZi** [comment]
@MaartenUreel Sorta. I ended up using rclone (https://rclone.org/) to send all of my backups to GDrive via a Google Business Account (5 seats for unlimited storage). The downside is my synthetic fulls trigger a full re-upload of the entire VM. There are some other limitations I had to work around but I won't go into details unless you need them.

Backblaze B2 now recommends using a product called TigerBridge (free) to accomplish what I was trying with minio (https://help.backblaze.com/hc/en-us/articles/360035732153). I set it up yesterday and it worked as expected but appeared to have a 100mbit/sec limit (GDrive is 250mbit/sec and does multiple streams so I can hit nearly my full gig internet speed) and B2 storage was going to cost me 2x as much a month compared to my Google Business Account solution. Since bandwidth is unlimited for me I'll be sticking with the GDrive solution until B2's next price drop.
