### ISSUE TITLE
Wrong API error when lifecycle policy does not exist

### ISSUE THREAD

**Issue by DReigada** [minio/minio#8489]
When performing the `s3:GetLifecycleConfiguration` action, on a bucket that does not have a lifecycle policy, minio returns `NoSuchBucketLifecycle`, while AWS S3 returns `NoSuchLifecycleConfiguration`.
This is behaviour is specified [here](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketLifecycleConfiguration.html)

## Expected Behavior
When a bucket has no lifecycle policy it should return `NoSuchLifecycleConfiguration`

## Current Behavior
When a bucket has no lifecycle policy it returns `NoSuchBucketLifecycle`

## Possible Solution
I would suggest changing the return error code. But I'm not sure of how breaking this change would be.

## Steps to Reproduce
1. Create a S3 bucket without any lifecycle policy
1. Call `aws s3api get-bucket-lifecycle-configuration  --bucket <s3-bucket>`
1. Create a minio bucket without any lifecycle policy
1. Call `aws s3api get-bucket-lifecycle-configuration  --endpoint-url <minio-url> --bucket <some-minio-bucket>`

## Context
In my case specifically I was using the [fluentd s3 plugin](https://github.com/fluent/fluent-plugin-s3/) to export logs to a minio bucket.
The plugin is capable of creating a new lifecycle policy automatically, but this does not work in minio if the destination bucket has no lifecycle policy created beforehand (since it is expecting one error code but it receives another from minio).
I was able to bypass this problem by creating the policy manually, but it would be nice to fix this issue regardless.

## Regression
Not that I know.

## Your Environment

I'm running the official docker image with tag `RELEASE.2019-10-12T01-39-57Z` in a kubernetes cluster.

**Comment by nitisht** [comment]
Thanks @DReigada we'll take a look

**Comment by harshavardhana** [comment]
This is fixed and released in latest release as per #8656
