### ISSUE TITLE
STS AssumeRole - MissingFields error

### ISSUE THREAD

**Issue by Numernabis** [minio/minio#8493]
I have a latest MinIO server running locally (in docker container) and would like to get temporary credentials for it (like in AWS STS).
I followed instructions from there: https://github.com/minio/minio/blob/master/docs/sts/assume-role.md and created a signed request:
```html
http://127.0.0.1:9000
?Action=AssumeRole
&DurationSeconds=3600
&Version=2011-06-15
&X-Amz-Algorithm=AWS4-HMAC-SHA256
&X-Amz-Credential=minio%2F20191107%2Fus-east-1%2Fs3%2Faws4_request
&X-Amz-Signature=XRQgnMSRe0ffnbBtqib1%2FVBTMjKhBBJjCBlVbmGB%2Be4%3D
&X-Amz-Date=20191107T122804Z
&X-Amz-SignedHeaders=content-type;host;x-amz-date
&X-Amz-Expires=3600
```

## Expected Behavior

Response containing generated temporary credentials, like in the sample: https://github.com/minio/minio/blob/master/docs/sts/assume-role.md#sample-response, or more descriptive error.

## Current Behavior

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>MissingFields</Code>
  <Message>Missing fields in request.</Message>
  <Resource>/</Resource>
  <RequestId>15D4DDD6C902A23F</RequestId>
  <HostId>9c5288d4-e17a-4e23-b401-efc9cbddfcc3</HostId>
</Error>
```

## Steps to Reproduce

1. I run MinIO server with command:
`docker run -p 9000:9000 --name minio1 -it -e "MINIO_ACCESS_KEY=minio" -e "MINIO_SECRET_KEY=minio123" -v minio_data:/data minio/minio:RELEASE.2019-10-12T01-39-57Z server /data`
2. I create and send signed GET request as listed in summary

## Context

I need to obtain temporary credentials and return them to frontend of my app for future usage (e.g. with SDK).

**Comment by donnior** [comment]
@Numernabis I've got temporary credentials in my project using `aws go-sdk` (https://docs.aws.amazon.com/sdk-for-go/api/service/sts/#STS.AssumeRole), it worked well; maybe you could try it without implementing it yourself.

@harshavardhana And will you consider adding this api  to minio's `go-sdk`?

**Comment by harshavardhana** [comment]
Yes happy to accept a PR @donnior

**Comment by harshavardhana** [comment]
> 2\. I create and send signed GET request as listed in summary

GET request is not correct you need to do 'POST' request, the doc shall be updated here #8581

**Comment by harshavardhana** [comment]
Closing this issue as incorrect usage.
