### ISSUE TITLE
ENVVAR to define CIDR ranges that can access web interface

### ISSUE THREAD

**Issue by nodesocket** [minio/minio#8495]
### Feature Request

Using an ENVVAR set CIDR ranges that are allowed to access the web interface.

I know there is the ENVVAR `MINIO_BROWSER=off`, but this disables the web interface completely. I am just looking to whitelist IP CIDR ranges.

Possible suggestion: `MINIO_BROWSER_ACCESS="10.0.0.0/16, 192.168.0.0/24"`.

**Comment by harshavardhana** [comment]
This can be easily done with nginx or any proxy in front. This is out of scope for MinIO or we may implement it but not anytime in near future.

**Comment by harshavardhana** [comment]
Ideal scenario here is to use proxy, iptables or some other routing mechanism.

MinIO server shouldn't be bloated with these type of features, closing this as out of scope for MinIO.

**Comment by nodesocket** [comment]
@harshavardhana appreciate the response. It seems like `MINIO_BROWSER` was implemented which is pretty similar in scope. The problem with adding NGINX or a proxy is how do I allow access to the s3 compatible interface to the world, but only limit access to the web interface?

**Comment by harshavardhana** [comment]
> @harshavardhana appreciate the response. It seems like `MINIO_BROWSER` was implemented which is pretty similar in scope. The problem with adding NGINX or a proxy is how do I allow access to the s3 compatible interface to the world, but only limit access to the web interface?

@nodesocket you can add the CIDR rule to `/minio` requests
