### ISSUE TITLE
Using MooseFS as the storage directory, MinIO cannot run.

### ISSUE THREAD

**Issue by Anbool** [minio/minio#8496]
We use the Client provided by the MooseFS cluster as the MinIO data storage directory (/ofs), but MinIO cannot run. Run: minio server /ofs, the hard disk will be unresponsive.When I looked at a lot of information, I found that there is not much information about this issue. If the MinIO team can do this, I hope that MinIO developers can help us solve this problem together, thank you.

## Expected Behavior

MinIO can run normally on a MooseFS cluster.

## Current Behavior

We have a MinIO server and also serve as the Client role for the MooseFS cluster.
I created the /ofs directory in the root directory to be used as the MinIO storage directory and mounted moosefs-client.
When I run: 

```shell
minio server /ofs
```

minio does not respond, and the hard drive enters a suspended state. When I force kill minio, an error log appears.

![https://i.7yy.co/2019/11/08/kTtM.png](https://i.7yy.co/2019/11/08/kTtM.png)

## Steps to Reproduce (for bugs)

- **Not using MooseFS**

  ![](https://x.7yy.co/20191108/1/1_71q0YTWz_minio1.gif)

- **Use MooseFS**

  ![](https://x.7yy.co/20191108/1/1_fAGqMVZC_minio2.gif)
  
- **Test the most error log multiple times**

  ![](https://i.7yy.co/2019/11/08/kbGj.png)

## Your Environment

```shell
[root@MinIO_C01_A-1 /]# minio version
Version: 2019-10-12T01:39:57Z
Release-Tag: RELEASE.2019-10-12T01-39-57Z
Commit-ID: bd106408462ecef70debf51f1e6179de950c5812
```

```shell
[root@MinIO_C01_A-1 /]# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

```shell
MooseFS: CGI version: 3.0.105 ; python: 2.7
```

**Comment by kannappanr** [comment]
@Anbool We do not have enough cycles right now. So, not sure if we can take a look at this right away. Did you try running this in NAS gateway mode? https://docs.min.io/docs/minio-gateway-for-nas.html

**Comment by harshavardhana** [comment]
We need posix locks implemented on the backend FS, looks like moosefs doesn't implement posix fcntl locks correctly or doesn't implement at all. So it is not possible for us to support moosefs at the moment.

We shall close this issue for now.

**Comment by Anbool** [comment]
> backend FS

Thank you very much for your reply. Can you recommend some backend FS similar to MooseFS? We have a lot of small files, including videos and images.

**Comment by Anbool** [comment]
> We need posix locks implemented on the backend FS, looks like moosefs doesn't implement posix fcntl locks correctly or doesn't implement at all. So it is not possible for us to support moosefs at the moment.
> 
> We shall close this issue for now.

> Thank you very much for your reply. Can you recommend some backend FS similar to MooseFS? We have a lot of small files, including videos and images.

**Comment by Anbool** [comment]
> We need posix locks implemented on the backend FS, looks like moosefs doesn't implement posix fcntl locks correctly or doesn't implement at all. So it is not possible for us to support moosefs at the moment.
> 
> We shall close this issue for now.

Thank you very much for your reply. Can you recommend some backend FS similar to MooseFS? We have a lot of small files, including videos and images.

**Comment by Anbool** [comment]
> We need posix locks implemented on the backend FS, looks like moosefs doesn't implement posix fcntl locks correctly or doesn't implement at all. So it is not possible for us to support moosefs at the moment.
> 
> We shall close this issue for now.

Thank you very much for your reply. Can you recommend some backend FS similar to MooseFS? Need to work with MinIO. We have a lot of small files, including videos and images.

**Comment by harshavardhana** [comment]
We have successfully tested with GlusterFS

**Comment by Anbool** [comment]
> We have successfully tested with GlusterFS

Thank you, I will study it soon!

**Comment by Anbool** [comment]
> We have successfully tested with GlusterFS

Excuse me, I have read some information and I am ready to build a GlusterFS cluster. But before the beginning, a lot of information shows that GlusterFS is not suitable for small file storage. Maybe this information is released for a long time. Our image file size usually does not exceed 1MB. GlusterFS works with MinIO. This way for our production environment. Does it fit? Or does MinIO have recommended parameters to optimize the best performance of the cluster, I think I will start working on this cluster build after I figure this out. Thank you for your patience.
