### ISSUE TITLE
Add the ability to lockdown admin access (IP restriction etc)

### ISSUE THREAD

**Issue by McPo** [minio/minio#8499]
It would be useful to be able to disable admin actions occurring across the public internet (restrict to localhost etc), while still allowing access to buckets. i.e. the default credentials are not of use outside of localhost.

This could be accomplished by the addition of a policy for the default "admin account". It could also be achieved by restricting administrative actions to a specific port number (separate from the general access port) etc. Which will not be exposed to the public internet.

This may be considered general good practice, incase the secrets where ever leaked, they would only be of use if you could also gain access to the machine that Minio is running on.

I wonder if https://github.com/minio/minio/pull/8487 would make this possible.

**Comment by harshavardhana** [comment]
Yes it is possible with #8487 , we won't be be opening new ports that is administratively hard and confusing. 

The point of multiple admins is that you don't need to share your operator credentials anymore to clients for admin operations. Infact operator credentials never need to be shared at all. This allows for central management of admin users as well as central lock down.

With PR #8487 we are also looking at externalizing admin accounts to external IDP as well.

**Comment by kannappanr** [comment]
@McPo With PR #8487 you should have lots of these features available and be able to lock down admin access. Closing this issue as answered, please feel free to let us know if you have further questions.

**Comment by McPo** [comment]
So the solution for when #8487 lands, would be:
- Allow minio to autogenerate the global credentials (Which I can just ignore)
- Create a new user (In my case with a static username/pass). This can be achieved by dropping a `identity.json` file into `/data/.minio.sys/config/iam/users/USERNAME`
- Using #8487 apply an iam policy to the new user, with `aws:SourceIp` condition
- (In my case, lock the new user to using STS, and then have another local application perform the auth and generate temporary credentials with a defined policy using AssumeRole)

Just want to double check that the incoming #8487 iam changes would allow for this. So I know if its worth waiting for.

If so awesome!

Cheers,
Emmet

**Comment by harshavardhana** [comment]
yes this is possible @McPo
