### ISSUE TITLE
Minio OSS Gateway - Error: io: read/write on closed pipe

### ISSUE THREAD

**Issue by kfyhn-gf** [minio/minio#8504]
When deploying Minio OSS Gateway using the Helm chart at [https://github.com/helm/charts/tree/master/stable/minio]() with `image.tag = RELEASE.2019-10-12T01-39-57Z` I am using Minio OSS Gateway to configure external object storage support for Gitlab in OSS as described here: [https://docs.gitlab.com/charts/advanced/external-object-storage/](). I can use the Minio browser without any problems (also to upload a file), but when I try to e.g. upload a build Docker image via Gitlab Registry, I get the following error in Minio:

```
Endpoint:  http://172.27.0.42:9000  http://127.0.0.1:9000

Browser Access:
   http://172.27.0.42:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

API: CopyObject(bucket=gfsc-sandbox-registry, object=docker/registry/v2/blobs/sha256/db/db4ae86aaa55001bff12797b7dde609a994e128982d4b3b14a1cb1fa79cf03f9/data)
Time: 11:27:19 UTC 11/11/2019
DeploymentID: 31a3899f-bbf6-44c2-807a-c3945ee7e102
RequestID: 15D6181EB355E3DE
RemoteHost: 172.27.0.207
Host: minio-oss-gateway:9000
UserAgent: aws-sdk-go/1.15.11 (go1.11.2; linux; amd64)
Error: io: read/write on closed pipe
       3: cmd/gateway/oss/gateway-oss.go:545:oss.ossGetObject()
       2: cmd/gateway/oss/gateway-oss.go:583:oss.(*ossObjects).GetObject()
       1: cmd/gateway/oss/gateway-oss.go:567:oss.(*ossObjects).GetObjectNInfo.func1()

API: CopyObject(bucket=gfsc-sandbox-registry, object=docker/registry/v2/blobs/sha256/15/155bd8f491d884a629b84f00d8f2834ba0cf15a3d9215051e8b892046e2bda8a/data)
Time: 11:27:21 UTC 11/11/2019
DeploymentID: 31a3899f-bbf6-44c2-807a-c3945ee7e102
RequestID: 15D6181EEC59A6A1
RemoteHost: 172.27.0.207
Host: minio-oss-gateway:9000
UserAgent: aws-sdk-go/1.15.11 (go1.11.2; linux; amd64)
Error: io: read/write on closed pipe
       3: cmd/gateway/oss/gateway-oss.go:545:oss.ossGetObject()
       2: cmd/gateway/oss/gateway-oss.go:583:oss.(*ossObjects).GetObject()
       1: cmd/gateway/oss/gateway-oss.go:567:oss.(*ossObjects).GetObjectNInfo.func1()

API: GetObject(bucket=gfsc-sandbox-registry, object=docker/registry/v2/repositories/kfyhn/hello_world/_layers/sha256/39d4af49cb0b3c5d14ab4116e355e71f96b40ba7b4e7b6cdacedc9f921a8e9ad/link)
Time: 11:27:21 UTC 11/11/2019
DeploymentID: 31a3899f-bbf6-44c2-807a-c3945ee7e102
RequestID: 15D6181EFC174125
RemoteHost: 172.27.0.207
Host: minio-oss-gateway:9000
UserAgent: aws-sdk-go/1.15.11 (go1.11.2; linux; amd64)
Error: oss: service returned error: StatusCode=404, ErrorCode=, ErrorMessage="", RequestId=5DC94599B5E5F137386591DD
       5: cmd/gateway/oss/gateway-oss.go:609:oss.ossGetObjectInfo()
       4: cmd/gateway/oss/gateway-oss.go:633:oss.(*ossObjects).GetObjectInfo()
       3: cmd/gateway/oss/gateway-oss.go:554:oss.(*ossObjects).GetObjectNInfo()
       2: cmd/object-handlers.go:336:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()

API: GetObject(bucket=gfsc-sandbox-registry, object=docker/registry/v2/repositories/kfyhn/hello_world/_layers/sha256/39d4af49cb0b3c5d14ab4116e355e71f96b40ba7b4e7b6cdacedc9f921a8e9ad/link)
Time: 11:27:21 UTC 11/11/2019
DeploymentID: 31a3899f-bbf6-44c2-807a-c3945ee7e102
RequestID: 15D6181EFC174125
RemoteHost: 172.27.0.207
Host: minio-oss-gateway:9000
UserAgent: aws-sdk-go/1.15.11 (go1.11.2; linux; amd64)
Error: oss: service returned error: StatusCode=404, ErrorCode=, ErrorMessage="", RequestId=5DC94599B5E5F137386591DD
       4: cmd/api-errors.go:1706:cmd.toAPIErrorCode()
       3: cmd/api-errors.go:1731:cmd.toAPIError()
       2: cmd/object-handlers.go:338:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```

## Expected Behavior
The build Docker image is uploaded correctly to OSS through the Minio OSS Gateway.

## Current Behavior
The upload fails with the above error.

## Steps to Reproduce (for bugs)
1. Create a Kubernetes cluster in Alibaba OSS
2. Deploy Gitlab Helm chart ([https://docs.gitlab.com/charts/]()) and configure to use Minio OSS Gateway as external object storage.
3. Deploy Minio OSS Gateway using Minio Helm chart ([https://github.com/helm/charts/tree/master/stable/minio]())
4. Create a project which builds and uploads a Docker image to the Gitlab Registry in the Gitlab CI/CD pipeline

## Context
I am trying to enable the Gitlab Helm chart to use external object storage in Alibaba.

## Your Environment
* Version used (`minio version`): 2019-10-12T01:39:57Z
* Environment name and version (e.g. nginx 1.9.1): , Helm chart: minio-2.5.18
* Server type and version: Kubernetes: 1.14.8-aliyun.1

**Comment by harshavardhana** [comment]
@kfyhn-gf we do not maintain OSS and do not have access to OSS credentials. We won't be able to address this issue in anytime near future.

**Comment by kfyhn-gf** [comment]
@harshavardhana Ok - thanks for your reply. Could you point me to where that piece of code in the Minio project (https://github.com/minio/minio/tree/master/cmd/gateway/oss) is maintained? Or do you mean that this code is deprecated and will no longer be maintained?

**Comment by harshavardhana** [comment]
@kfyhn-gf we didn't write it, we don't test it so it is safe to assume that it won't work.  Feel free to fix the issue and use it as you see fit. We do not have any cycles to address this at the moment.

**Comment by kfyhn-gf** [comment]
Ok, thank you for the clarification. I have submitted a PR for updating the documentation, such that this information is stated up-front (https://github.com/minio/minio/pull/8511). Feel free to change my wording in the PR if I have gotten something wrong or you would like to describe the situation differently.

**Comment by mbitsnbites** [comment]
This may or may not be related: I had a similar error when using minio in `gateway nas` mode (against CIFS mounts). Browsing the web interface is OK, and trying to get an object that does not exist returns an appropriate error, but when trying to download an object I got this:

```
API: GetObject(bucket=foo, object=bar)
Time: 10:48:37 UTC 11/15/2019
DeploymentID: a220d2a6-59f2-47ce-bbc7-c4801515997d
RequestID: 15D74FC883432E4A
RemoteHost: 127.0.0.1
Host: localhost
Error: io: read/write on closed pipe
       4: /go/minio/cmd/api-errors.go:1700:cmd.toAPIErrorCode()
       3: /go/minio/cmd/api-errors.go:1725:cmd.toAPIError()
       2: /go/minio/cmd/object-handlers.go:386:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```

This seems to be a regression, as the error shows up in the latest `edge` release from docker hub, while `minio/minio:latest` from docker hub does not have this error.

**Comment by vadmeste** [comment]
Yes @mbitsnbites 

There is another issue opened similar to it https://github.com/minio/minio/issues/7286, but I wasn't able to reproduce it.

If you are able to reproduce it, could you update us ?

**Comment by harshavardhana** [comment]
Closing this gateway issue to be done as a future milestone.

**Comment by harrisjoseph** [comment]
I've just hit a very similar traceback + error message on the latest docker image:
```
API: GetObject(bucket=***, object=***)
Time: 18:39:07 UTC 08/24/2020
DeploymentID: d4023093-de5d-46a1-a5b3-e14cdb899109
RequestID: 162E483DB0F478F1
RemoteHost: 10.1.92.24
Host: ***
Error: io: read/write on closed pipe
       4: cmd/api-errors.go:1980:cmd.toAPIErrorCode()
       3: cmd/api-errors.go:2005:cmd.toAPIError()
       2: cmd/object-handlers.go:469:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:2041:http.HandlerFunc.ServeHTTP()
```
Running `minio gateway s3`, with very basic caching configuration `MINIO_CACHE=on`, under fairly high load. Errors started at 18:25 UTC. I'm assuming, gut-instinct-style that this is a symptom of something unusual happening with AWS APIs. Potentially the closed pipe is AWS side?

Line 469 in `cmd/object-handlers.go - GetObjectHandler` occurs when the io.Copy has returned an error. 
```
	// Write object content to response body
	if _, err = io.Copy(httpWriter, gr); err != nil {
		if !httpWriter.HasWritten() && !statusCodeWritten {
			// write error response only if no data or headers has been written to client yet
			writeErrorResponse(ctx, w, toAPIError(ctx, err), r.URL, guessIsBrowserReq(r)) # ERROR is raised here
		}
		return
	}
````

**Comment by guptajiten** [comment]
@harrisjoseph were you able to fix this issue? It seems I am also getting same error under fairly high load. I have minio+AzureGateway+Caching.

Thanks!

**Comment by harrisjoseph** [comment]
@jlohiya Unfortunately not. We had to move away from using minio in production due to this issue.
