### ISSUE TITLE
"Unable to handle encrypted back-end for config" while starting

### ISSUE THREAD

**Issue by ebozduman** [minio/minio#8507]
Just re-based my minio master and ran "make install"
```
ersan@ersanscomputer ~/work/src/github.com/minio/minio (master) $ git fetch origin
remote: Enumerating objects: 278, done.
remote: Counting objects: 100% (278/278), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 349 (delta 266), reused 272 (delta 266), pack-reused 71
Receiving objects: 100% (349/349), 177.39 KiB | 2.14 MiB/s, done.
Resolving deltas: 100% (279/279), completed with 161 local objects.
From github.com:minio/minio
   e31b7cdc..4082764d  master     -> origin/master
ersan@ersanscomputer ~/work/src/github.com/minio/minio (master) $ git rebase origin/master
First, rewinding head to replay your work on top of it...
Fast-forwarded master to origin/master.
```
Then, hit the error while trying to start MinIO. As a result, MinIO went into safe mode.
```
ersan@ersanscomputer ~/work/src/github.com/minio/minio (master) $ MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 ENABLE_HTTPS=0 minio server /var/tmp/ersan
Attempting encryption of all config, IAM users and policies on MinIO backend
Server startup failed with 'Unable to handle encrypted backend for config, iam and policies: ReadMapCB: expect { or n, but found , error found in #0 byte of ...||..., bigger context ...||...'
Server switching to safe mode
Please use 'mc admin' commands to fix this issue
Endpoint:  http://192.168.1.124:9000  http://172.17.0.1:9000  http://127.0.0.1:9000    
AccessKey: minio 
SecretKey: minio123 

Command-line Access: https://docs.min.io/docs/minio-admin-complete-guide.html
   $ mc config host add myminio http://192.168.1.124:9000 minio minio123 --api s3v4
   $ mc admin --help


^CExiting on signal: INTERRUPT
ersan@ersanscomputer ~/work/src/github.com/minio/minio (master) $ 
```

## Expected Behavior
MinIO migrates my old config file and successfully starts.

## Current Behavior
It spits out the error message, "", and goes into Safe mode.

## Steps to Reproduce (for bugs)
Not sure about the reproduction steps. I did not do anything special. Just re-based my minio master, rebuild MinIO executable and tried to start it as usual.

## Context
All-Hands testing.

## Regression
No

## Your Environment
* Version used (`minio version`):
$  minio version
Version: 2019-11-11T18:21:54Z
Release-Tag: DEVELOPMENT.2019-11-11T18-21-54Z
Commit-ID: 4082764d48847db42b5d817b05ff795a1f059cd2

* Server type and version:
FS
* Operating System and version (`uname -a`):
$ uname -a
Linux ersanscomputer 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Please report issues #8434 closing it here it's fixed by #8506
