### ISSUE TITLE
user shown as enabled after disable command

### ISSUE THREAD

**Issue by BigUstad** [minio/minio#8519]
Disable user. List users, disabled user is shown as enabled.
To replicate:
mc admin user add <TARGET> user1 badpassword
mc admin user list <TARGET>
    user1 is shown as enabled.
mc admin user disable <TARGET> user1
mc admin user list <TARGET>
    user1 is shown as enabled.

## Expected Behavior

./mc admin user list <TARGET>
disabled   user1

## Current Behavior

mc admin user add <TARGET> user1 badpassword
mc admin user list <TARGET>
    user1 is shown as enabled.
mc admin user disable <TARGET> user1
mc admin user list <TARGET>
    user1 is shown as enabled.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
Is this with current release or master ?

**Comment by BigUstad** [comment]
I did a pull at 9.13am PDT today.

**Comment by harshavardhana** [comment]
Ah I think i know why it is @BigUstad

**Comment by harshavardhana** [comment]
It shall be fixed in PR #8515

**Comment by harshavardhana** [comment]
Fixed in #8515
