### ISSUE TITLE
Requests take > 1min as soon as one host is down

### ISSUE THREAD

**Issue by philipkozeny** [minio/minio#8531]
For testing purposes I have setup 3 different clusters on 4 physical hosts with docker-compose. Everything is working well as it should. If I stop one node (`docker-compose down`) everything still works as expected and distributed mode works. As soon as I shutdown one node (`shutdown now`) requests take at least 1 min. It doesn't matter if it is `mc ls`, `mc cp`, the browser etc. Some requests like `mc admin info server` take at least 4 minutes in my testing.

## Expected Behavior
I expect that there is no difference in distributed mode between one node not having a running minio client and one node being completely offline since this could happen in production all the time (changing a disk etc.).

## Current Behavior
As soon as one node is offline and not reachable in the network the first requests seems to wait for a timeout of ~1 minute.

## Possible Solution
Timeouts should be way less, otherwise the system is not really usable if every request takes at least one minute when one host is not reachable in the network.

## Steps to Reproduce (for bugs)
1. setup a new Debian 10 server on DigitalOcean, etc.
2. install docker & docker-compose from the official Docker repo
3. use docker-compose to start minio on every host in distributed mode
3. shutdown one host with `docker-compose down` --> works as it should
4. shutdown one host with `shutdown now` --> long timeouts happen

Here is the docker-compose I have used on the hosts

```
version: '2'

services:
 minio:
  image: minio/minio:latest
  volumes:
   - /tmp/data/:/data
  ports:
   - "9000:9000"
  restart: always
  environment:
   MINIO_ACCESS_KEY: test
   MINIO_SECRET_KEY: test123
  command: server http://minio/data http://ip2/data http://ip3/data http://ip4/data
```

Here is the result of a mc ls command, you can see a response time of ~1min for the first part, this is the same with all requests.

```
➜  ~ mc ls test-ocean/test123 --json --debug
mc: <DEBUG> GET /test123/?location= HTTP/1.1
Host: 167.71.53.2:9000
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.39 mc/2019-10-09T22:54:57Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20191117/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20191117T131432Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 128
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Sun, 17 Nov 2019 13:15:32 GMT
Server: MinIO/RELEASE.2019-10-12T01-39-57Z
Vary: Origin
X-Amz-Request-Id: 15D7F573DCC04D4D
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  1m0.121811803s

mc: <DEBUG> HEAD /test123/ HTTP/1.1
Host: 167.71.53.2:9000
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.39 mc/2019-10-09T22:54:57Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20191117/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20191117T131532Z

mc: <DEBUG> HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Sun, 17 Nov 2019 13:15:32 GMT
Server: MinIO/RELEASE.2019-10-12T01-39-57Z
Vary: Origin
X-Amz-Request-Id: 15D7F581DAF175CF
X-Xss-Protection: 1; mode=block
Content-Length: 0

mc: <DEBUG> Response Time:  39.510641ms

mc: <DEBUG> HEAD /test123/ HTTP/1.1
Host: 167.71.53.2:9000
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.39 mc/2019-10-09T22:54:57Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20191117/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20191117T131532Z

mc: <DEBUG> HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Sun, 17 Nov 2019 13:15:32 GMT
Server: MinIO/RELEASE.2019-10-12T01-39-57Z
Vary: Origin
X-Amz-Request-Id: 15D7F581DD504635
X-Xss-Protection: 1; mode=block
Content-Length: 0

mc: <DEBUG> Response Time:  30.910852ms

```

Heres the output from one of the running consoles:

```
minio_1  | API: SYSTEM()
minio_1  | Time: 13:15:58 UTC 11/17/2019
minio_1  | DeploymentID: cc2bab85-c75b-43e7-9592-b3d0af6c4c6a
minio_1  | Error: Post http://xxx:9000/minio/peer/v5/backgroundopsstatus?: dial tcp 134.209.249.194:9000: i/o timeout
minio_1  |        2: cmd/notification.go:290:cmd.(*NotificationSys).BackgroundOpsStatus()
minio_1  |        1: cmd/daily-lifecycle-ops.go:83:cmd.startDailyLifecycle()
```

## Your Environment

* Version used (`minio version`): Version: 2019-10-12T01:39:57Z
* Environment name and version (e.g. nginx 1.9.1), Docker version 19.03.5, build 633a0ea838
* Server type and version: VMs on DigitalOcean, Linode, hetzner
* Operating System and version (`uname -a`): Linux debian-s-1vcpu-1gb-fra1-03 4.19.0-6-cloud-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

**Comment by kannappanr** [comment]
@philipkozeny Thanks for reporting. We will take a look and get back to you.

**Comment by harshavardhana** [comment]
It is only for the first attempt, rest we timeout quickly.

**Comment by philipkozeny** [comment]
@harshavardhana in my test this seems to happen for every request. For example I have an example page where I load 3 images from minio, for every get request I have to wait 1 minute - so 3 minutes in total. 

Same with mc cat for example - I run mc cat on the same object three times in a row, always 1 minute timeout before I get the file contents. Am I doing / understanding anything wrong?

**Comment by harshavardhana** [comment]
I have tested this already @philipkozeny I don't think this is true in my tests, are you sure your network is not flaky here?

**Comment by harshavardhana** [comment]
We will close this issue as not reproducible on our end. Please test with the latest master and let us know if it is reproducible.
