### ISSUE TITLE
Please allow for multiple MINIO_IDENTITY_LDAP_USERNAME_FORMAT entries to support AD with different hierarchies

### ISSUE THREAD

**Issue by Kevin-A-Howard** [minio/minio#8532]
We have Active Directory domains that have hierarchy based on business groups, account types, etc. Variable MINIO_IDENTITY_LDAP_USERNAME_FORMAT currently supports a single entry for the username format template.  

We would like to be able to specify multiple values for the username format to support many different hierarchy combinations:
CN=${username},OU=Users,OU=BUS1,OU=LOB,DC=somedomain,DC=com
CN=${username},OU=Users,OU=BUS2,OU=LOB,DC=somedomain,DC=com
CN=${username},OU=App2App,OU=APP,DC=somedomain,DC=com
...
etc.

**Comment by kannappanr** [comment]
@Kevin-A-Howard Thanks for the feature request. We will take a look and get back to you.

**Comment by csfesta22** [comment]
@kannappanr it be nice to pass only the UID {username} to avoid having to do a complicated configuration of OU hierarchies

**Comment by harshavardhana** [comment]
```
CN=${username},OU=Users,OU=BUS1,OU=LOB,DC=somedomain,DC=com
CN=${username},OU=Users,OU=BUS2,OU=LOB,DC=somedomain,DC=com
CN=${username},OU=App2App,OU=APP,DC=somedomain,DC=com
```

@Kevin-A-Howard how would the binding work here, is it expected that all binds succeed or single binds succeed? to apply the group_search filter?

> @kannappanr it be nice to pass only the UID {username} to avoid having to do a complicated configuration of OU hierarchies

@csfesta22 how would that work? we need to know the user to do the bind_dn so that it is not possible to automatically predict. We also want to avoid using the read-only bind since that is not useful for STS API.

**Comment by NorthFuture** [comment]
Am I wrong, or this the PR related to this issue doesn't work? Please refer to this issue https://github.com/minio/minio/issues/10112. What's the proper usage of MINIO_IDENTITY_LDAP_USERNAME_FORMAT for different organization units?
