### ISSUE TITLE
Broken build from source with bad transitive dependency on asn1-ber?

### ISSUE THREAD

**Issue by anandadalton** [minio/minio#8534]
## Expected Behavior
I expect that when I run

```bash
$ GO111MODULE=on go get -u github.com/minio/minio
```

on a fresh machine, that it will exit with code 0 and successfully build minio's main binary.

## Current Behavior
Instead, it returns something like

```bash
go get: upgrading gopkg.in/asn1-ber.v1@v1.0.0-20181015200546-f715ec2f112d: gopkg.in/asn1-ber.v1@v1.3.1: invalid version: go.mod has non-....v1 module path "github.com/go-asn1-ber/asn1-ber" at revision v1.3.1
```
and exits with code 1.

## Steps to Reproduce (for bugs)
In order to reproduce you can use the following Dockerfile:

```Dockerfile
FROM golang:1.13.4-alpine3.10 AS builder

RUN true \
  && apk update \
	&& apk add git \
	&& true

ARG opts
RUN env ${opts} GO111MODULE=on go get -u github.com/minio/minio
```

and then run

```
$ docker build --build-arg opts="GOARCH=amd64" .
```

## Context
I am attempting to use minio for my home mixed-architecture k8s cluster (which includes the unsupported RPi GOARCH=arm, but never mind that). Because there are no recent releases for GOARCH=arm, I decided to forego the releases the Minio team has provided and build from source. That is how I encountered this error (on one of my amd64 machines).

## Your Environment
Originally, problem encountered on a machine with these specs:

```bash
$ uname -a
Linux ctrl-01 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
$ go version
go version go1.13.4 linux/amd64
```

Reasonably fresh install, gcc and gcc-8 are installed.

**Comment by harshavardhana** [comment]
Don't do `go get -u` just `go get`

**Comment by anandadalton** [comment]
Yes, with

```Dockerfile
FROM golang:1.13.4-alpine3.10 AS builder

RUN true \
  && apk update \
	&& apk add git gcc libc-dev \
	&& true

ARG opts
RUN env ${opts} GO111MODULE=on go get github.com/minio/minio
```

I am able to build (for both GOARCH=amd64 and GOARCH=arm, which is nice!)

Sorry for the spurious report, and thanks for the quick help :)
