### ISSUE TITLE
[s3-gateway] Possibility to configure S3 MinIO gateway to a single S3 bucket

### ISSUE THREAD

**Issue by ivan-sukhomlyn** [minio/minio#8536]
**It's not possible to create gateway to a particular S3 bucket**
```bash
minio gateway s3 https://some-bucket.s3.amazonaws.com
ERROR Unable to initialize gateway backend: Amazon S3 endpoint should be 's3.amazonaws.com'.
```
**Describe the solution you'd like**
It would be nice to have an opportunity to create a gateway behind a single S3 bucket instead of all available and don't provide additional permissions to IAM policies for roles or users to get all buckets.

**Additional context**
I'm looking for using MinIO gateway because Java SDK for MinIO Client doesn't support IAM instances profiles.

**Comment by harshavardhana** [comment]
Right now, we don't have cycles to spend on these feature requests. Feel free to implement it on your own and send a PR.

We shall close this issue for now and get back to it in future.

**Comment by ivan-sukhomlyn** [comment]
@harshavardhana Understood. Thanks for your reply!
