### ISSUE TITLE
listObjects has cache ?

### ISSUE THREAD

**Issue by KevinSmile** [minio/minio#8551]
listObjects has cache ?

## Expected Behavior
listObjects should have stable performance

## Current Behavior
1st call listObjects => slow
2nd call listObjects => fast  (only need 10% time of 1st call)
sleep a long time then call listObjects => slow

## Possible Solution
N/A. 
I found a related PR https://github.com/minio/minio/pull/1186 merged 3 years ago, but it seems that this PR's code had been refactored.

## Steps to Reproduce (for bugs)
I had a folder contains 1000 objects.

1. time mc ls -r dis/kwtest/1/ 
0.08s user 0.04s system 0% cpu 23.632 total (very slow)
2. time mc ls -r dis/kwtest/1/ 
0.09s user 0.06s system 6% cpu 2.405 total ==> same operation, much faster

## Your Environment
* Version used (`minio version`): 
`minio/minio:RELEASE.2019-10-12T01-39-57Z`

**Comment by harshavardhana** [comment]
ListObjects relies on your backend disk @KevinSmile so if your backend disk responds fast, we can respond fast. 

There is nothing special we can do here.

**Comment by KevinSmile** [comment]
@harshavardhana thanks for your reply!

So it's my environment's "cache (kind of)" leads to the much faster 2nd call of listObjects...

**Comment by harshavardhana** [comment]
> So it's my environment's "cache (kind of)" leads to the much faster 2nd call of listObjects...

That is just a filesystem lookup cache @KevinSmile

**Comment by KevinSmile** [comment]
@harshavardhana thank you!
