### ISSUE TITLE
Support sts:* actions

### ISSUE THREAD

**Issue by McPo** [minio/minio#8554]
It is my understanding that by default AWS users are unable to call AssumeRole unless they have been giving explicit permission to via sts:AssumeRole. Minio by default allows sts:AssumeRole to be carried out against any user.

It would be preferential to control this behaviour with the addition of `sts:AssumeRole` action in user policies.

My use case involves locking` sts:AssumeRole` down to the "localhost" using `aws:SourceIp`. In this manner STS credentials can only be requested by another component on the same host, while files can still be accessed publicly.

This FR is a continuation of #8499.

Currently Minio responds with
```
ERROR Unable to initialize IAM system: unsupported action 'sts:AssumeRole'
```

**Comment by harshavardhana** [comment]
sts:AssumeRole is implicit in MinIO you don't need to make addition policies for it.  Any user on MinIO is already sts:AssumeRole capable

**Comment by harshavardhana** [comment]
Closing this..
