### ISSUE TITLE
The format sent to Kafka and Elasticsearch for bucket logs is inefficient

### ISSUE THREAD

**Issue by khumps** [minio/minio#8565]
**Is your feature request related to a problem? Please describe.**
When you use the direct import feature for Elasticsearch logs it contains a nested `Records` field. this is extremely inefficient for parsing in both elasticsearch and kafka

**Describe the solution you'd like**
The entire structure should be flattened into a 1-dimensional json object. So instead of your demo structure which looks like
```
{
    "EventType": "s3:ObjectCreated:Put",
    "Key": "images/myphoto.jpg",
    "Records": [{
        "eventVersion": "2.0",
        "eventSource": "aws:s3",
        "awsRegion": "us-east-1",
        "eventTime": "2017-01-31T10:01:51Z",
        "eventName": "s3:ObjectCreated:Put",
        "userIdentity": {
            "principalId": "88QR09S7IOT4X1IBAQ9B"
        },
        "requestParameters": {
            "sourceIPAddress": "192.173.5.2:57904"
        },
        "responseElements": {
            "x-amz-request-id": "149ED2FD25589220",
            "x-minio-origin-endpoint": "http://192.173.5.2:9000"
        },
        "s3": {
            "s3SchemaVersion": "1.0",
            "configurationId": "Config",
            "bucket": {
                "name": "images",
                "ownerIdentity": {
                    "principalId": "88QR09S7IOT4X1IBAQ9B"
                },
                "arn": "arn:aws:s3:::images"
            },
            "object": {
                "key": "myphoto.jpg",
                "size": 541596,
                "eTag": "04451d05b4faf4d62f3d538156115e2a",
                "sequencer": "149ED2FD25589220"
            }
        }
    }],
    "level": "info",
    "msg": "",
    "time": "2017-01-31T15:31:51+05:30"
}
```

It should look something like:

```
{
   "EventType": "s3:ObjectCreated:Put",
   "Key": "images/myphoto.jpg",
   "eventVersion": "2.0",
   "eventSource": "aws:s3",
   "awsRegion": "us-east-1",
   "eventTime": "2017-01-31T10:01:51Z",
   "eventName": "s3:ObjectCreated:Put",
   "userIdentity-principalId": "88QR09S7IOT4X1IBAQ9B"
   "sourceIPAddress": "192.173.5.2:57904"
   "x-amz-request-id": "149ED2FD25589220",
   "x-minio-origin-endpoint": "http://192.173.5.2:9000"
   "s3SchemaVersion": "1.0",
   "configurationId": "Config",
   "bucket_name": "images",
   "bucket_principalId": "88QR09S7IOT4X1IBAQ9B"
   "bucket_arn": "arn:aws:s3:::images"
   "object_key": "myphoto.jpg",
   "object_size": 541596,
   "object_eTag": "04451d05b4faf4d62f3d538156115e2a",
   "object_sequencer": "149ED2FD25589220"
    "level": "info",
   "msg": "",
   "time": "2017-01-31T15:31:51+05:30"
}
```

**Describe alternatives you've considered**
There really aren't any, this is a root issue in the format that the bucket notifications are sent in that causes huge performance decreases on both elasticsearch and kafka
**Additional context**
A flattened format can be parased on our current system in the order of millions of records per minute. With this format we struggle to parse 100k/minute

**Comment by harshavardhana** [comment]
You should write a webhook to write the flattening, we can't change the data format now.

I don't know why there is a performance issue here, we send verbatim notification info format and it is not possible to change it now.

**Comment by khumps** [comment]
@harshavardhana Because elasticsearch doesn't parse the format into fields. It parses the entire Records structure as one field which means you can't actually filter by any of the data that is in Records. We can send the data to Logstash and have it flatten the structure but that flattening is an extremely costly in comparison, especially for the number of requests we need it to handle

**Comment by harshavardhana** [comment]
@khumps we shall take a look and perhaps start writing in a new format soon as new access format style. 

Can you also provide the Kafka JSON preferred as well? does it also follow elasticsearch style?

**Comment by khumps** [comment]
@harshavardhana the Kafka and Elastic formats would both be ideal in that same format so follow that style. It makes it much more efficient to parse.

**Comment by harshavardhana** [comment]
Thanks, @khumps will let you know soon.

**Comment by harshavardhana** [comment]
One more question is @khumps are you using elasticsearch/kafka as access or namespace format?

**Comment by candlerb** [comment]
Events posted to Kafka are trivially "flattened": write a consumer which reads one JSON event and writes out one or more JSON events to another topic.  This can be extremely fast and a few lines of code (e.g. with faust, or kafka streams).

I don't know about Elasticsearch, in particular whether an [ingest pipeline](https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest.html) can create multiple documents from a single input.

From my point of view, I'd like the format to remain as close as possible to the S3 format of bucket notifications.  See:
* [S3 notification content structure](https://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html)
* [Ceph events format](https://docs.ceph.com/docs/master/radosgw/notifications/#events)

Therefore if "flat" notifications are added, I think this should be an option rather than a complete change of format.

**Comment by harshavardhana** [comment]
Of course, a generic webhook can be written which can write to any target of your choice in whatever format needed, I think the primary issue here is that from the get-go how does one store efficiently on these targets and if the target itself warrants a flattened format. 

If we add it will be a new style of `format` field with values such as namespace, access a new one shall be `flattened`  or just `flat`

**Comment by khumps** [comment]
If this is a trivial thing then we will look into it. Perhaps a custom consumer on the minio end may be useful to others but I can look into it on my end too

**Comment by harshavardhana** [comment]
> Events posted to Kafka are trivially "flattened": write a consumer which reads one JSON event and writes out one or more JSON events to another topic. This can be extremely fast and a few lines of code (e.g. with faust, or kafka streams).

@khumps ^^

**Comment by amitga** [comment]
> @harshavardhana Because elasticsearch doesn't parse the format into fields. It parses the entire Records structure as one field which means you can't actually filter by any of the data that is in Records. We can send the data to Logstash and have it flatten the structure but that flattening is an extremely costly in comparison, especially for the number of requests we need it to handle

This is not accurate: You can set a field as `nested` in Elasticsearch, and then you can query it.
See:
https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html

Performance wise, it might have its implications. But at least functionality wise, it works.

**Comment by harshavardhana** [comment]
Let's close this, for now, and revisit if this is a real problem, moving this to a future milestone.
