### ISSUE TITLE
Environment variable as a prefix for all etcd records.

### ISSUE THREAD

**Issue by ihostage** [minio/minio#8567]
**Is your feature request related to a problem? Please describe.**

We can't configure a prefix for all keys stored on etcd. As a result, we can't use an existing etcd cluster and need to create another only for MinIO 😞 

**Describe the solution you'd like**

Add environment variable `MINIO_ETCD_PREFIX` and use it as a prefix for all etcd records.
![1574458962455](https://user-images.githubusercontent.com/817328/69462627-8f5b6180-0d8a-11ea-8a47-a175cc56a7b9.jpg)

**Describe alternatives you've considered**

Create and **support** yet another etcd instance.

**Comment by harshavardhana** [comment]
Surprisingly we were discussing this already and we will be adding it soon

**Comment by ihostage** [comment]
@harshavardhana 
Yep 😄I wrote about this problem on Slack.

**Comment by ihostage** [comment]
The screenshot is a result of run MinIO Gateway + STS (with `MINIO_ETCD_PREFIX=/minio`) from the branch of my PR. I tried found all communication with etcd in source code but I can't test of all cases 😞

**Comment by harshavardhana** [comment]
https://github.com/ihostage/minio/commit/10641b2a1d585aa04bee0e4a677ac684a249c2b0 This PR is not correct @ihostage let's discuss this further.

**Comment by ihostage** [comment]
@harshavardhana Yes, of course. 👍
