### ISSUE TITLE
getValidPath responsible for 45% of CPU time on upload

### ISSUE THREAD

**Issue by klauspost** [minio/minio#8573]
# Description

When uploading "smaller" 1MB objects [getValidPath](https://github.com/minio/minio/blob/890b493a2e32d7f607e5ee0150a9ce884c3e26ff/cmd/posix.go#L124) is responsible for close to 50% of all CPU usage. This is strictly tied to the number of upload ops.

Usage is fairly even split between `getDiskInfo`, `os.Open`, `os.Close` and `os.Remove`.

# Solution

None proposed, but obviously this seems like a possible optimization that would make a rather big impact for smaller uploads.

**Comment by harshavardhana** [comment]
Yes it is something I wanted to address @klauspost but haven't had time to get to.

**Comment by harshavardhana** [comment]
> When uploading "smaller" 1MB objects [getValidPath](https://github.com/minio/minio/blob/890b493a2e32d7f607e5ee0150a9ce884c3e26ff/cmd/posix.go#L124) is responsible for close to 50% of all CPU usage. This is strictly tied to the number of upload ops.

BTW this is only called once per newPosix @klauspost and shouldn't have any effect on uploading 1MiB objects henceforth object layer has been initialized.

I am surprised to see the CPU usage for getValidPath() are the servers disconnecting due to load?

**Comment by klauspost** [comment]
It could be due to the problem with IsLocal. I will rerun the test.

**Comment by klauspost** [comment]
Yes, this seems to have been fixed by the updates to master. Closing for now 👍
