### ISSUE TITLE
dl.minio.io not accessible from Iran

### ISSUE THREAD

**Issue by hosnas** [minio/minio#8575]
```
./mc admin update m2
mc: <ERROR> Unable to update the server. Get https://dl.min.io/server/minio/release/linux-amd64/minio.shasum: dial tcp 178.128.69.202:443: i/o timeout.
```
I can access this website with VPN. But cant without VPN. If Iran is intentionally restricted, its really foolish and absurd. We are living in 2020 and its not like you're creating the great wall of China to restrict our access. Its more like a Trump wall that can be broken through with an [ordinary 100$ saw](https://www.youtube.com/watch?v=VCkIva2L-B0).

**Comment by harshavardhana** [comment]
It is on purpose @hosnas, unfortunately, needed by US regulations.

**Comment by hosnas** [comment]
Unfortunately US regulations cost me about 5 minutes to break through. :grinning: 
This is embarrassing. :man_facepalming:

**Comment by harshavardhana** [comment]
I hope there was a better answer @hosnas closing this issue for now.
