### ISSUE TITLE
Bacula / MINIO / Backblaze -- unstable

### ISSUE THREAD

**Issue by sruckh** [minio/minio#8584]
Trying to use Bacula with MINIO with Backblaze as the backend.  Uploading 10MB files and have problems (uploads fail) even with small data sets.

## Expected Behavior

Files should upload without error.

## Current Behavior

Only some files upload without error.

## Steps to Reproduce (for bugs)

Using MinIO/RELEASE.2019-10-12T01-39-57Z, Bacula 9.4.4, on CentOS 7.7.  Run MinIO in gateway mode connecting to backblaze.  Using sporadic "mc" commands seems to work, as does using the MinIO web interface.  Bacula is configured for cloud storage.  Bacula is configured to break up files into 10MB parts for uploading.  The daily backup fails almost daily uploading all the parts.  A rough guess would be that 85% of the parts upload without error.

1.
2.
3.
4.

## Context

I would like to use MinIO as a gateway between bacula and Backblaze and to use Backblaze storage for backups.

## Regression

No

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:
Information about environment provided above.

* Trace Log (Error): Edited to hide personal Information.
myalias [REQUEST s3.PutObject] 23:15:34.598
myalias PUT /Bucket/B2-Vol-1110/part.7
myalias Host: localhost:9000
myalias User-Agent: Mozilla/4.0 (Compatible; s3; libs3 3.0; Linux x86_64)
myalias X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
myalias X-Amz-Date: 20191127T231534Z
myalias Accept: */*
myalias Authorization: AWS4-HMAC-SHA256 Credential=xxxxxxxxxxxxxxxxxxxxxxxxx/20191127/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=a3bd80eef472541976daccc317522a2aefaf43400b2ba85a3a79c350bf100d93
myalias Content-Length: 10450944
myalias Expect: 100-continue
myalias <BODY>
myalias [RESPONSE] [23:18:04.388] [ Duration 2m29.790482s  🠉 3.8 MiB  🠋 628 B ]
myalias 500 Internal Server Error
myalias Content-Security-Policy: block-all-mixed-content
myalias Content-Type: application/xml
myalias Server: MinIO/RELEASE.2019-10-12T01-39-57Z
myalias Vary: Origin
myalias X-Amz-Request-Id: 15DB280DD6B647F8
myalias X-Xss-Protection: 1; mode=block
myalias Accept-Ranges: bytes
myalias Content-Length: 359
myalias <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Key>B2-Vol-1110/part.7</Key><BucketName>Bucket</BucketName><Resource>/Bucket/B2-Vol-1110/part.7</Resource><RequestId>15DB280DD6B647F8</RequestId><HostId>0fffffff-0000-000f-0000-00ff000ff000</HostId></Error>
myalias
myalias [REQUEST s3.PutObject] 23:21:23.049
myalias PUT /Bucket/B2-Vol-1110/part.19
myalias Host: localhost:9000
myalias Expect: 100-continue
myalias User-Agent: Mozilla/4.0 (Compatible; s3; libs3 3.0; Linux x86_64)
myalias X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
myalias X-Amz-Date: 20191127T232123Z
myalias Accept: */*
myalias Authorization: AWS4-HMAC-SHA256 Credential=xxxxxxxxxxxxxxxxxxxxxxxxx/20191127/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=c828081c642d7b3a22ea6ae289bf261dcad2dad4aec58b7839e6299f72c7418b
myalias Content-Length: 10450944
myalias <BODY>
myalias [RESPONSE] [23:22:09.666] [ Duration 46.617462s  🠉 950 KiB  🠋 630 B ]
myalias 500 Internal Server Error
myalias Content-Type: application/xml
myalias Server: MinIO/RELEASE.2019-10-12T01-39-57Z
myalias Vary: Origin
myalias X-Amz-Request-Id: 15DB285EF805508E
myalias X-Xss-Protection: 1; mode=block
myalias Accept-Ranges: bytes
myalias Content-Length: 361
myalias Content-Security-Policy: block-all-mixed-content
myalias <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Key>B2-Vol-1110/part.19</Key><BucketName>Bucket</BucketName><Resource>/Bucket/B2-Vol-1110/part.19</Resource><RequestId>15DB285EF805508E</RequestId><HostId>0fffffff-0000-000f-0000-00ff000ff000</HostId></Error>
myalias
*

It is unclear is this a a bacula problem, a MinIO problem, a Backblaze problem, or an ISP problem.  As the above trace log is from MinIO this issue is being reported here.

Thank You.

**Comment by harshavardhana** [comment]
Backblaze is experimental as gateway, can you use our server mode and see if it works fine?

**Comment by harshavardhana** [comment]
Moved this to the future milestone as we have no cycles to work on backblaze gateway issues.

**Comment by sruckh** [comment]
I am not totally sure I understand the comment about use server mode and see if it works.  Is this supposed to mean run minio in server mode and present some local storage as S3 storage, and see if the backups will work without error writing to the local storage but through the MinIO services.  This would just be a test to see if bacula can write to the local storage without errors?  This would just be a test, but has nothing to due with being able to use backblaze, correct?

**Comment by sruckh** [comment]
If what I wrote above was the goal then I can report that a 34GB backup successfully completed with MinIO acting as a server.  A remote bacula client was able to be backed up using the bacula S3 driver to a MinIO server.  The files were backed up to local directory and those files sync'd successfully to the file-system configured with the MinIO server.   It would appear that either MinIO acting as a gateway, my ISP connection, or Backblaze is the problem.  Possibly unrelated, but I have also configured SDFS with Backblaze being the storage server and am able to successfully backup to the SDFS volume without the errors that are experienced when using MinIO as a gateway server.  Completely different mechanism, but same ISP connection and same Backblaze connection.  Thank You.

**Comment by sruckh** [comment]
I see backblaze just announced Beta AWS APIs.  I was curious if any additional work will be done using minio as a gateway to backblaze, or if I should start re-configuring and plan on testing the new beta APIs from backblaze.

Thank You.

**Comment by harshavardhana** [comment]
> I see backblaze just announced Beta AWS APIs. I was curious if any additional work will be done using minio as a gateway to backblaze, or if I should start re-configuring and plan on testing the new beta APIs from backblaze.
> 
> Thank You.

It is generally in your interest to start using S3 gateway if needed with B2, to provide for edge caching.  We may remove B2 gateway in the future as this is not going to be a community requirement anymore.

**Comment by sruckh** [comment]
> 
> It is generally in your interest to start using S3 gateway if needed with B2, to provide for edge caching. We may remove B2 gateway in the future as this is not going to be a community requirement anymore.

Thank you.  I will work on transitioning to the Beta S3 APIs.
