### ISSUE TITLE
minio client how to copy filenames with spaces

### ISSUE THREAD

**Issue by shouldnotappearcalm** [minio/minio#8589]
I am using minio's client for file copying, command like this
```
mc cp test-76/images/Empty xxx fileName test-76/images_copy
```
test-76 is one of my minio storageId，file name is `Empty xxx fileName`, When I execute this command I see the following error

```
mc: <ERROR> Unable to validate source test-76/images/Empty
```
What should I do if there are spaces in the file name

**Comment by harshavardhana** [comment]
Just quote the file names or use bash escaping. This is a standard practice @shouldnotappearcalm

**Comment by kannappanr** [comment]
@shouldnotappearcalm Closing this issue as answered. Please reach out to us at https://slack.min.io for such questions
