### ISSUE TITLE
Feature request: use "X-Amz-Meta-Mtime"

### ISSUE THREAD

**Issue by mearsten** [minio/minio#8590]
**Is your feature request related to a problem? Please describe.**
Programs such as [rclone](https://github.com/rclone/rclone) store a file mtime in "X-Amz-Meta-Mtime" attribute. But when we retrieve that file via HTTP minio uses mtime from storage filesystem. Example:

```
% ls -l --full-time foofoo/bar.txt
-rw-r--r-- 1 root root 4 2018-03-22 19:49:29.000000000 +0300 foofoo/bar.txt
% rclone sync foofoo/bar.txt minio:foofoo
% curl -sv -o /dev/null http://localhost:9000/foofoo/bar.txt |& egrep 'Last-Modified|Mtime'
< Last-Modified: Sun, 01 Dec 2019 12:25:48 GMT
< X-Amz-Meta-Mtime: 1521737369
% ruby -e 'puts Time.at(1521737369)'
2018-03-22 19:49:29 +0300
```

**Describe the solution you'd like**
It would be great if minio will use "X-Amz-Meta-Mtime" as mtime of a file and send it in "Last-Modified" header. If that attribute is absent then fallback to the current behaviour.

**Describe alternatives you've considered**
I could not find a way to set a file mtime on a filesystem when uploading that file to minio.

**Additional context**
None

**Comment by harshavardhana** [comment]
That's not possible, x-amz-meta is arbitrary and adding specific logic would break S3 API.

You should just convert this on the client side instead.
