### ISSUE TITLE
Public Bucket Contents from browser in Federated setup

### ISSUE THREAD

**Issue by mindhash** [minio/minio#8595]
We have a federated setup with 2 clusters (2 nodes each).  I am facing an issue while **accessing** contents of a **public bucket** (policy: download) using **DNS style** URL. The issue occurs only through browser. The request to download succeeds when using cURL.  

We were also able to **reproduce the issue** on command line by passing user agent : 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36

## Expected Behavior

For public buckets, we would like to access contents both from browser and command line (cURL) with DNS style URL.

 
## Current Behavior

Path style URL:
Works as intended.

DNS Style URL:
Unable to access contents of public bucket through browser though the command line works. The issue is reproducible on command line after setting user agent (browser) in cURL header.

## Steps to Reproduce (for bugs)

1. Set bucket policy to Download 
2. Type DNS style URL with object path in browser
3. Returns a 404 (Not found)
4.

## Your Environment

* Version used (`minio version`):

Version: 2019-10-12T01:39:57Z
Release-Tag: RELEASE.2019-10-12T01-39-57Z
Commit-ID: bd106408462ecef70debf51f1e6179de950c5812

* Environment name and version (e.g. nginx 1.9.1): 
nginx/1.12.2

* Server type and version:
* Operating System and version (`uname -a`):
Linux e2e-61-58 3.10.0-957.12.1.el7.x86_64 #1 SMP Mon Apr 29 14:59:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* Link to your project:

**Comment by nitisht** [comment]
Thanks for reporting @mindhash we'll take a look

**Comment by mindhash** [comment]
Just to help further when you get this issue. 
I identified code block thats possibly causing this error.

![image](https://user-images.githubusercontent.com/10277894/70140172-22b16280-16ba-11ea-9114-38365b5379cc.png)

Here in switch cases an additional if block for len(globalDomainNames) > 0 might be required handling for v2 style URLs (i.e. call to request2BucketObjectName instead of urlPath2BucketObjectName).

Anyways thought I will share my findings. 

I could submit a PR if thats ok.

**Comment by harshavardhana** [comment]
Feel free to send a PR there is no need to ask @mindhash
