### ISSUE TITLE
Need quorum health check

### ISSUE THREAD

**Issue by eco-minio** [minio/minio#8596]
**Is your feature request related to a problem? Please describe.**
When setting haproxy (or other load balancers I assume), need a health check end point that determines whether quorum is intact, and only do the failover when quorum is not intact to avoid failing over a single node at a time
**Describe the solution you'd like**
Quorum health check endpoint

**Describe alternatives you've considered**
This can be achieved very simply with fs setups but does not work with xl
**Additional context**
Seen while investigating multi site replication

**Comment by harshavardhana** [comment]
I think this is not useful when radio comes in, we can avoid complicating our healthcheck and instead work on the new project.

**Comment by kannappanr** [comment]
Closing this issue for now. Will re-open later if required
