### ISSUE TITLE
change MINIO_ACCESS_KEY or MINIO_SECRET_KEY Error

### ISSUE THREAD

**Issue by better0332** [minio/minio#8601]
can't change MINIO_ACCESS_KEY or MINIO_SECRET_KEY, it use them to `CreateCredentials`

## Expected Behavior

change OK

## Current Behavior

Unable to initialize server: Unable to initialize config system: Invalid credentials

## Steps to Reproduce (for bugs)

1. MINIO_ACCESS_KEY=key12345 MINIO_SECRET_KEY=pwd12345 minio server /data
2. change MINIO_ACCESS_KEY to abc12345
3. MINIO_ACCESS_KEY=abc12345 MINIO_SECRET_KEY=pwd12345 minio server /data
4. 

## Your Environment

* Version used (`minio version`):edge
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
You didn't follow the docs properly here

https://github.com/minio/minio/tree/master/docs/config

Also if you are going to use master branch you are on your own. Closing this issue as non actionable at the moment.

**Comment by better0332** [comment]
thanks, use MINIO_ACCESS_KEY_OLD

**Comment by gbbenson68** [comment]
Is there a way to reset the credentials if the old credentials are forgotten or lost?

**Comment by harshavardhana** [comment]
> Is there a way to reset the credentials if the old credentials are forgotten or lost?

https://github.com/minio/minio/tree/master/docs/config#rotating-encryption-with-new-credentials and please don't post on old/closed issues.

- Open a new issue
- Or ask a question on slack https://slack.min.io
