### ISSUE TITLE
How can I modify the minio-distributed-daemonset.yaml when I have two nodes and two disks  per node

### ISSUE THREAD

**Issue by Kaleidoscoper** [minio/minio#8602]
I know there must be at least 4 disks in the distributed mode but I've no idea how i can modify the k8s minio-distributed-daemonset.yaml when I have two nodes and each node has two disks .I have referred to https://github.com/minio/minio/blob/master/docs/orchestration/kubernetes/minio-distributed-daemonset.yaml and make some modifications like here
![image](https://user-images.githubusercontent.com/9138997/70131870-01527580-16be-11ea-9dee-1c5eb3f68cbe.png)
but when I apply this yaml I got
![image](https://user-images.githubusercontent.com/9138997/70131907-10d1be80-16be-11ea-8028-cc49d1f70127.png)

**Comment by nitisht** [comment]
@Kaleidoscoper using IP addresses in Kubernetes like env where containers may change IPs at any time, is not recommended. You can use `hostname` instead of the IP and then you current approach should work. 

Closing this as answered, please join us on Slack (https://slack.min.io) for further such questions.

**Comment by Kaleidoscoper** [comment]
These two ips aren't the container ip in the k8s. These are the external IP of the two nodes.So it is requested that the server list here must be in the k8s?

**Comment by Kaleidoscoper** [comment]
> @Kaleidoscoper using IP addresses in Kubernetes like env where containers may change IPs at any time, is not recommended. You can use `hostname` instead of the IP and then you current approach should work.
> 
> Closing this as answered, please join us on Slack (https://slack.min.io) for further such questions.

These two ips aren't the container ip in the k8s. These are the external IP of the two nodes.So it is requested that the server list here must be in the k8s?

**Comment by nitisht** [comment]
I am not sure if k8s can deploy containers on external nodes
