### ISSUE TITLE
Policy Condition failed

### ISSUE THREAD

**Issue by ki827** [minio/minio#8606]
I run the [example](https://docs.min.io/docs/java-client-api-reference.html#presignedPostPolicy) of presignedPostPolicy to upload image, but return an error.

## Expected Behavior

Upload success and response like below:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<PostResponse>
    <Bucket>mybucket</Bucket>
    <Key>myobject.png</Key>
    <ETag>&#34;49a5a2cf40011ff418ee45ace9b04b1c&#34;</ETag>
    <Location>https://play.min.io/mybucket/myobject.png</Location>
</PostResponse>
```

## Current Behavior

The upload fails and the result is as follows:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<Error>
    <Code>PostPolicyInvalidKeyName</Code>
    <Message>Invalid according to Policy: Policy Condition failed</Message>
    <BucketName>mybucket</BucketName>
    <Resource>/mybucket</Resource>
    <RequestId>15DD6AD09768DF60</RequestId>
    <HostId>e06aee7c-545f-4233-9af9-1dcc8b1536ca</HostId>
</Error>
```

## Possible Solution

1. Delete this line in the example: `policy.setSuccessActionStatus(201);`
2. Add success_action_status in the upload parameters and set the value to 201
3. Upload Uploaded successfully

## Steps to Reproduce (for bugs)

1. New a Java Project
2. Copy the code from the sample into the project.
3. Run the project.
4. Copy the output to the command line (this is a curl command for uploading)

## Context

Unable to upload file using PostPolicy policy

## Regression

No

## Your Environment

* Version used (`minio version`): 2019-10-12T01:39:57Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): 19.0.0 Darwin Kernel Version 19.0.0: Darwin bailuns-Mac-mini.local 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64
*  Link to your project:

**Comment by nitisht** [comment]
Thanks for reporting, @qinrongjun we'll take a look

**Comment by kannappanr** [comment]
closing as fixed by https://github.com/minio/minio-java/pull/826
