### ISSUE TITLE
MinIO crash when removing disk in erasure coding mode

### ISSUE THREAD

**Issue by footplus** [minio/minio#8607]
## Expected Behavior

MinIO Server in erasure coding mode should keep running when one disk becomes unavailable because I/O errors.

## Current Behavior

MinIO server seems to crash badly when accessing the out-of-order drive (filesystem gives I/O errors):

```
API: SYSTEM()
Time: 11:28:57 UTC 12/05/2019
DeploymentID: fc826d0a-b55f-4abf-b43b-0e18d440a158
Error: disk is faulty
       disk=/opt/minio/cluster-a/xvdf
       1: cmd/xl-v1.go:89:cmd.getDisksInfo.func1()
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x12a9b9d]

goroutine 78121 [running]:
github.com/minio/minio/cmd.(*posix).ReadAll(0x0, 0x197d11d, 0xa, 0x197f436, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/posix.go:814 +0x9d
github.com/minio/minio/cmd.loadFormatXL(0x1c869a0, 0x0, 0x8, 0xc000219ee8, 0x133217e)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/format-xl.go:394 +0x73
github.com/minio/minio/cmd.loadFormatXLAll.func1(0xc0005dc300, 0xc00065e000, 0x8, 0x8, 0xc000391240, 0x8, 0x8, 0x4, 0x1c869a0, 0x0)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/format-xl.go:338 +0x73
created by github.com/minio/minio/cmd.loadFormatXLAll
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/format-xl.go:335 +0x23a
```

Additionnally, I was unable to start the MinIO server again while the defective drive was still attached, because of an error, so the degradation of one disk takes the whole node down irremediably.

```
ERROR Unable to initialize backend: unable to access (/opt/minio/cluster-a/xvdf/.minio.sys/format.json) stat /opt/minio/cluster-a/xvdf/.minio.sys/format.json: input/output error
```

## Steps to Reproduce (for bugs)

1. Run minio in EC mode with 8 drives (for example).
2. Unplug a drive without unmounting it (in my test case, detaching a mounted EBS from an EC2 instance).
3. Running `mc admin info server myminio` triggers a crash.

## Context

I was testing the erasure coding feature, and assessing a disk failure/filesystem error impact, along with recovery options.

## Regression

This is probably a regression, but I did not test other versions.

## Your Environment

* Version used (`minio version`):
```
Version: 2019-10-12T01:39:57Z
Release-Tag: RELEASE.2019-10-12T01-39-57Z
Commit-ID: bd106408462ecef70debf51f1e6179de950c5812
```
* Operating System and version (`uname -a`): Linux hostname 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* `minio server /opt/minio/server/minio server /opt/minio/cluster-a/xvd{b..i}` with 5GB EBS drives formatted with XFS mounted at `/opt/minio/cluster-a/xvd{b..i}`.

**Comment by nitisht** [comment]
Thanks for reporting @footplus we'll take a look

**Comment by harshavardhana** [comment]
EIO error is properly converted to errDiskFaulty in master branch so that will make the server start properly.

In-turn it also avoids the crash.

**Comment by harshavardhana** [comment]
This is deemed fixed in the released version, closing this issue.
