### ISSUE TITLE
Need ttl to buckets or objects

### ISSUE THREAD

**Issue by FU100** [minio/minio#8614]
How can I add a ttl attribute to a bucket or an object?

Or is there any way to delete expired buckets automatically?

**Comment by nitisht** [comment]
please refer this doc https://github.com/minio/minio/tree/master/docs/lifecycle

closing this as answered, please join us on slack for more questions

**Comment by cchenax** [comment]
> please refer this doc https://github.com/minio/minio/tree/master/docs/lifecycle
> 
> closing this as answered, please join us on slack for more questions

hello,I want to know the lifecycle management design doc,where is?
