### ISSUE TITLE
Policy exceeds the maximum allowed document

### ISSUE THREAD

**Issue by dedumboy** [minio/minio#8625]
hello guys i have a problem while setting policy for a directory on minio
here is my command
`mc policy set download minio/metube-s3/thumbnails/2019/12/09/RAID7stltju3osfh8uoZ`

i get error
`mc: <ERROR> Unable to set policy `download` for `minio/metube-s3/thumbnails/2019/12/09/RAID7stltju3osfh8uoZ`. Policy exceeds the maximum allowed document size.`
how can i remove policy document size limit for this?

**Comment by nitisht** [comment]
the limit is as per s3 API standard, so there is no way to change this limit. Closing this as working as expected..
