### ISSUE TITLE
k8s helm chart installation fails with latest version

### ISSUE THREAD

**Issue by yoonsio** [minio/minio#8640]
k8s helm chart installation fails with latest version with default configuration

## Expected Behavior
minio pod should start successfully

## Current Behavior
minio pod crashloops with error message:
```
ERROR Unable to initialize config system: invalid character '@' looking for beginning of value
```

## Steps to Reproduce (for bugs)
1. create persistent volume & persistent volume claim (manual type in this case)
2. run `helm install cos stable/minio --set image.tag=latest --set persistence.existingClaim=cos-pvc`
3. wait for pod to start

## Context
Unable to deploy latest version of minio

## Your Environment
* Version used: latest, RELEASE.2019-10-12T01-39-57Z
* Environment name and version: K8s v1.17.0, helm v3.0.1
* Server type and version: baremetal
* Operating System and version: Ubuntu 18.04

**Comment by harshavardhana** [comment]
Did you start with edge and then went to latest ?

**Comment by harshavardhana** [comment]
If yes then purge the PVC and start fresh with image.tag as latest

**Comment by yoonsio** [comment]
thanks @harshavardhana still failing even after deleting and recreating pv/pvc

**Comment by yoonsio** [comment]
@harshavardhana it is working now after I removed `.minio.sys` from existing pv.

**Comment by harshavardhana** [comment]
I think for some reason you didn't purge the PVC correctly, otherwise you don't need to specifically remove .minio.sys - current helm is using edge on purpose so that our users can migrate. If you happen to use edge then you can't go back to latest because now config backend is encrypted.

**Comment by harshavardhana** [comment]
I shall close this issue for now.
