### ISSUE TITLE
Splunk Smartstore configuration sends wrong characters to Minio

### ISSUE THREAD

**Issue by gregnsk** [minio/minio#8647]
I'm trying to enable Splunk Smartstore with Minio backend. Splunk is running on a Windows host. I see the following errors in mc trace output:
```
<Error><Code>XMinioInvalidObjectName</Code><Message>Object name contains unsupported characters.</Message><Key>remote_volume/\_internal/db/33/65/1~F4F2DD7A-5395-4CE1-A9AA-B35A054FBA73/guidSplunk-F4F2DD7A-5395-4CE1-A9AA-B35A054FBA73\.rawSize</Key><BucketName>smartstore</BucketName><Resource>/smartstore/remote_volume/\_internal/db/33/65/1~F4F2DD7A-5395-4CE1-A9AA-B35A054FBA73/guidSplunk-F4F2DD7A-5395-4CE1-A9AA-B35A054FBA73\.rawSize</Resource><RequestId>15DFCC15D7A73011</RequestId><HostId>c93d43ff-a17b-45d9-8e25-687a9e869fe7</HostId></Error>
```
## Expected Behavior

PUT request should be successful

## Steps to Reproduce (for bugs)

indexes.conf content on Splunk server:

[default]
remotePath = volume:s3/$_index_name

[volume:s3]
storageType = remote
path = s3://smartstore/remote_volume
remote.s3.access_key = $7$wY9aSdtLUJ3mtWdK2+BUfKNyyYFGczOwzYDMzzAxGAmK8elddQ==
remote.s3.secret_key = $7$U4YWebjzY3IWvKo++XPLHShpp+QqnIVlv9JUBrJjQ1pmfzbgaSN7/A==
remote.s3.supports_versioning = false
remote.s3.endpoint = http://io-wt-11:9000

# This example stanza configures a custom index, "cs_index".
[cs_index]
homePath = $SPLUNK_DB/$_index_name/db
# SmartStore-enabled indexes do not use thawedPath or coldPath, but you
 must still specify them here.
coldPath = $SPLUNK_DB/$_index_name/colddb
thawedPath = $SPLUNK_DB/cs_index/thaweddb
remotePath = volume:s3/$_index_name

[_internal]
remotePath = volume:s3/$_index_name

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by gregnsk** [comment]
Attached Minio trace and indexes.conf files 
[indexes.conf.txt](https://github.com/minio/minio/files/3962166/indexes.conf.txt)

[minio_trace.txt](https://github.com/minio/minio/files/3962162/minio_trace.txt)

**Comment by eco-minio** [comment]
@gregnsk We need to know the MinIO version here, also what version of Splunk and Windows?

**Comment by gregnsk** [comment]
More from Minio output:
API: GetObject(bucket=smartstore, object=remote_volume/\_audit/db/c5/cf/5~F4F2DD7A-5395-4CE1-A9AA-B35A054FBA73\receipt.json)
Time: 19:53:46 IST 12/13/2019
DeploymentID: 30eec2b0-f07c-4d51-a82a-e2ffa46dd271
RequestID: 15DFFFC7565D05FD
RemoteHost: 172.31.79.193
Host: io-wt-11:9000
Error: Object name invalid: smartstore#remote_volume/\_audit/db/c5/cf/5~F4F2DD7A-5395-4CE1-A9AA-B35A054FBA73\receipt.json
       7: cmd/object-api-input-checks.go:50:cmd.checkBucketAndObjectNames()
       6: cmd/object-api-input-checks.go:29:cmd.checkGetObjArgs()
       5: cmd/fs-v1.go:474:cmd.(*FSObjects).GetObjectNInfo()
       4: cmd/object-handlers.go:336:cmd.objectAPIHandlers.GetObjectHandler()
       3: cmd/http-tracer.go:135:cmd.Trace()
       2: cmd/handler-utils.go:346:cmd.httpTraceHdrs.func1()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()



Minio   Version: 2019-10-12T01:39:57Z
Splunk Enterprise Version: 8.0.0 Build: 1357bef0a7f6

PS C:\Program Files\Splunk\bin> (Get-WmiObject -class Win32_OperatingSystem).Caption
Microsoft Windows Server 2012 R2 Datacenter
PS C:\Program Files\Splunk\bin> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
6      3      9600   0

**Comment by eco-minio** [comment]
After testing a quick fix to escape the extraneous `\`, seeing an issue with permissions writing to the backend:

```
23:04:33.189 [403 Forbidden] s3.PutObject localhost:9000/smartstore/remote_volume/\_metrics/db/dd/74/1~F0978F73-7F85-4456-892C-B195F0F2F458/guidSplunk-F0978F73-7F85-4456-892C-B195F0F2F458\.rawSize 127.0.0.1         80.449ms     ↑ 90 B ↓ 785 B
23:04:33.282 [403 Forbidden] s3.PutObject localhost:9000/smartstore/remote_volume/\_metrics/db/3f/52/2~F0978F73-7F85-4456-892C-B195F0F2F458/guidSplunk-F0978F73-7F85-4456-892C-B195F0F2F458\.rawSize 127.0.0.1         67.438ms     ↑ 89 B ↓ 785 B
23:04:33.358 [403 Forbidden] s3.PutObject localhost:9000/smartstore/remote_volume/\_metrics/db/70/ec/3~F0978F73-7F85-4456-892C-B195F0F2F458/guidSplunk-F0978F73-7F85-4456-892C-B195F0F2F458\.rawSize 127.0.0.1         56.887ms     ↑ 90 B ↓ 785 B
23:04:33.425 [403 Forbidden] s3.PutObject localhost:9000/smartstore/remote_volume/\_metrics/db/ab/86/4~F0978F73-7F85-4456-892C-B195F0F2F458/guidSplunk-F0978F73-7F85-4456-892C-B195F0F2F458\.rawSize 127.0.0.1         66.245ms     ↑ 89 B ↓ 785 B
23:04:33.498 [403 Forbidden] s3.PutObject localhost:9000/smartstore/remote_volume/\_metrics/db/f0/a4/5~F0978F73-7F85-4456-892C-B195F0F2F458/guidSplunk-F0978F73-7F85-4456-892C-B195F0F2F458\.rawSize 127.0.0.1         76.021ms     ↑ 90 B ↓ 785 B
23:04:33.580 [403 Forbidden] s3.PutObject localhost:9000/smartstore/remote_volume/\_metrics/db/35/65/6~F0978F73-7F85-4456-892C-B195F0F2F458/guidSplunk-F0978F73-7F85-4456-892C-B195F0F2F458\.rawSize 127.0.0.1         100.912ms    ↑ 90 B ↓ 785 B
```

Noted prefix is created by splunk up to ../guidSplunk but guidSplunk is not created and no objects are not uploaded.

**Comment by harshavardhana** [comment]
@gregnsk we can definitely trim this but I think this is a Splunk issue because there is no reason for Splunk Smart store to escape `_` or `.` characters from the key name as these are not specialized names on Windows.

It would be worth to get their inputs on this issue as well.
