### ISSUE TITLE
Keycloak How to set several policies for a user ?

### ISSUE THREAD

**Issue by Leletir** [minio/minio#8651]
I'm trying to add several policies to an user in Keycloak, adding one works fine, but 2 not.

## Expected Behavior
The user should have access to different buckets based on several policies

## Current Behavior
With 2 policies enables on keycloak it's impossible to login in minio interface.

## Steps to Reproduce (for bugs)

1. Create 2 policies
```json
{
    "Version":"2012-10-17",
    "Statement":[
        {
        "Sid":"",
        "Effect":"Allow",
        "Principal":{"AWS":"*"},
        "Action":"s3:GetBucketLocation",
        "Resource":"arn:aws:s3:::raw-layer-datasource"
        },
        {
        "Sid":"",
        "Effect":"Allow",
        "Principal":{"AWS":"*"},
        "Action":"s3:ListBucket",
        "Resource":"arn:aws:s3:::raw-layer-datasource"
        },
        {
        "Sid":"",
        "Effect":"Allow",
        "Principal":{"AWS":"*"},
        "Action":"s3:GetObject",
        "Resource":"arn:aws:s3:::raw-layer-datasource/*"
        }
    ]
}
```
```json
{
    "Version":"2012-10-17",
    "Statement":[
      {
         "Sid":"",
         "Effect":"Allow",
         "Principal":{"AWS":"*"},
         "Action":"s3:GetBucketLocation",
         "Resource":"arn:aws:s3:::application-layer-qabi"
      },
      {
         "Sid":"",
         "Effect":"Allow",
         "Principal":{"AWS":"*"},
         "Action":"s3:ListBucket",
         "Resource":"arn:aws:s3:::application-layer-qabi"
      },
      {
         "Effect":"Allow",
         "Principal":{"AWS":"*"},
         "Action":[
            "s3:PutObject",
            "s3:GetObject",
            "s3:DeleteObject"
         ],
         "Resource":"arn:aws:s3:::application-layer-qabi/*"
      }
    ]
 }
```
2. Add 2 policies for an usre on keycloak:
![Screenshot 2019-12-15 at 11 35 02](https://user-images.githubusercontent.com/16922595/70861493-fd7ce980-1f2e-11ea-9518-4bdea0ddbcfd.png)

## Result:
`API: WebLoginSTS()
Time: 10:12:50 UTC 12/15/2019
DeploymentID: b38c34df-9c1c-472f-9fc3-860a36d7add2
RemoteHost: 10.189.0.69
Host: <>
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:71.0) Gecko/20100101 Firefox/71.0
Error: 500 Internal Server Error
      21: /go/minio/cmd/web-handlers.go:2110:cmd.toWebAPIError()
      20: /go/minio/cmd/web-handlers.go:1988:cmd.toJSONError()
      19: /go/minio/cmd/web-handlers.go:1972:cmd.(*webAPIHandlers).LoginSTS()
      18: reflect/value.go:460:reflect.Value.call()
      17: reflect/value.go:321:reflect.Value.Call()
      16: /go/pkg/mod/github.com/gorilla/rpc@v1.2.0/v2/server.go:220:v2.(*Server).ServeHTTP()
      15: /go/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212:mux.(*Router).ServeHTTP()
      14: /go/minio/cmd/generic-handlers.go:747:cmd.customHeaderHandler.ServeHTTP()
      13: /go/minio/cmd/generic-handlers.go:762:cmd.securityHeaderHandler.ServeHTTP()
      12: /go/minio/cmd/generic-handlers.go:623:cmd.bucketForwardingHandler.ServeHTTP()
      11: /go/minio/cmd/generic-handlers.go:608:cmd.requestValidityHandler.ServeHTTP()
      10: /go/minio/cmd/generic-handlers.go:544:cmd.httpStatsHandler.ServeHTTP()
       9: /go/minio/cmd/generic-handlers.go:68:cmd.requestSizeLimitHandler.ServeHTTP()
       8: /go/minio/cmd/generic-handlers.go:93:cmd.requestHeaderSizeLimitHandler.ServeHTTP()
       7: /go/minio/cmd/crossdomain-xml-handler.go:51:cmd.crossDomainPolicy.ServeHTTP()
       6: /go/minio/cmd/generic-handlers.go:247:cmd.redirectHandler.ServeHTTP()
       5: /go/minio/cmd/generic-handlers.go:315:cmd.minioReservedBucketHandler.ServeHTTP()
       4: /go/minio/cmd/generic-handlers.go:274:cmd.cacheControlHandler.ServeHTTP()
       3: /go/minio/cmd/generic-handlers.go:385:cmd.timeValidityHandler.ServeHTTP()
       2: /go/pkg/mod/github.com/rs/cors@v1.6.0/cors.go:207:cors.(*Cors).Handler.func1()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()

API: AssumeRoleWithWebIdentity()
Time: 10:36:33 UTC 12/15/2019
DeploymentID: b38c34df-9c1c-472f-9fc3-860a36d7add2
RequestID: 15E08514CA3FA897
RemoteHost: 172.17.0.1
Host: <>
UserAgent: Go-http-client/1.1
Error: Invalid arguments specified
       4: /go/minio/cmd/sts-errors.go:47:cmd.writeSTSErrorResponse()
       3: /go/minio/cmd/sts-handlers.go:364:cmd.(*stsAPIHandlers).AssumeRoleWithJWT()
       2: /go/minio/cmd/sts-handlers.go:408:cmd.(*stsAPIHandlers).AssumeRoleWithWebIdentity()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()

API: WebLoginSTS()
Time: 10:36:33 UTC 12/15/2019
DeploymentID: b38c34df-9c1c-472f-9fc3-860a36d7add2
RemoteHost: 10.189.0.69
Host: <>
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:71.0) Gecko/20100101 Firefox/71.0
Error: 500 Internal Server Error
      21: /go/minio/cmd/web-handlers.go:2110:cmd.toWebAPIError()
      20: /go/minio/cmd/web-handlers.go:1988:cmd.toJSONError()
      19: /go/minio/cmd/web-handlers.go:1972:cmd.(*webAPIHandlers).LoginSTS()
      18: reflect/value.go:460:reflect.Value.call()
      17: reflect/value.go:321:reflect.Value.Call()
      16: /go/pkg/mod/github.com/gorilla/rpc@v1.2.0/v2/server.go:220:v2.(*Server).ServeHTTP()
      15: /go/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212:mux.(*Router).ServeHTTP()
      14: /go/minio/cmd/generic-handlers.go:747:cmd.customHeaderHandler.ServeHTTP()
      13: /go/minio/cmd/generic-handlers.go:762:cmd.securityHeaderHandler.ServeHTTP()
      12: /go/minio/cmd/generic-handlers.go:623:cmd.bucketForwardingHandler.ServeHTTP()
      11: /go/minio/cmd/generic-handlers.go:608:cmd.requestValidityHandler.ServeHTTP()
      10: /go/minio/cmd/generic-handlers.go:544:cmd.httpStatsHandler.ServeHTTP()
       9: /go/minio/cmd/generic-handlers.go:68:cmd.requestSizeLimitHandler.ServeHTTP()
       8: /go/minio/cmd/generic-handlers.go:93:cmd.requestHeaderSizeLimitHandler.ServeHTTP()
       7: /go/minio/cmd/crossdomain-xml-handler.go:51:cmd.crossDomainPolicy.ServeHTTP()
       6: /go/minio/cmd/generic-handlers.go:247:cmd.redirectHandler.ServeHTTP()
       5: /go/minio/cmd/generic-handlers.go:315:cmd.minioReservedBucketHandler.ServeHTTP()
       4: /go/minio/cmd/generic-handlers.go:274:cmd.cacheControlHandler.ServeHTTP()
       3: /go/minio/cmd/generic-handlers.go:385:cmd.timeValidityHandler.ServeHTTP()
       2: /go/pkg/mod/github.com/rs/cors@v1.6.0/cors.go:207:cors.(*Cors).Handler.func1()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()`

It's working fine with only one policy.

## Your Environment
I'm using minio edge within docker.

Do you have any idea how to add more than 1 policy to an usre ?

Thank you for your work, your solution rocks !!!

**Comment by kannappanr** [comment]
@Leletir Can you try this instead

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Stmt1576429846081",
      "Action": [
        "s3:GetBucketLocation"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::raw-layer-datasource",
        "arn:aws:s3:::application-layer-qabi"
      ]
    },
    {
      "Sid": "Stmt1576429923747",
      "Action": [
        "s3:ListBucket"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::raw-layer-datasource",
        "arn:aws:s3:::application-layer-qabi"
      ]
    },
    {
      "Sid": "Stmt1576429978399",
      "Action": [
        "s3:GetObject"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::raw-layer-datasource/*",
        "arn:aws:s3:::application-layer-qabi/*"
      ]
    }
  ]
}
```

**Comment by harshavardhana** [comment]
Just create one policy which has all the requirements, it is not useful to have multiple policies in general.

But we can take comma separated values with the names of the policies to apply. This allows us to provide multiple policies.

**Comment by Leletir** [comment]
I agree with you, but in this case I want to be able to share poicies between users, so I cannot create one policy with all the requirements.
I tried comma separated values but I obtained the issue I post above.

**Comment by harshavardhana** [comment]
I said we can support, we don't support yet.

**Comment by Leletir** [comment]
Oh sorry, I read your message too quickly.

**Comment by harshavardhana** [comment]
A preliminary work has been pushed to master @Leletir as a next step we will be adding multi-policy support.

**Comment by Leletir** [comment]
Hello @harshavardhana, it's a good news ! I will be more than happy to test it.

Thank you very much to keep me posted

**Comment by gzur** [comment]
> A preliminary work has been pushed to master @Leletir as a next step we will be adding multi-policy support.

Is there an issue where this work can be followed?

**Comment by harshavardhana** [comment]
> Is there an issue where this work can be followed?

There is none at the moment, this issue with close when there a relevant PR is merged.

**Comment by gzur** [comment]
Do you have link to the relevant PR?

**Comment by harshavardhana** [comment]
> Do you have link to the relevant PR?

There is none, preliminary work is already finished. We just need to add this feature. Feel free to send a PR yourself if it's urgent. 

We have other priorities right now.

**Comment by harshavardhana** [comment]
To be fixed by #9550

**Comment by csymvoul** [comment]
My question is off topic but is there an example that could showcase how a minio policy can be applied to a keycloak user? 

What I've done so far is create a policy from the Minio Client and set it an attribute to a KeyCloak user as shown in the picture below:
![image](https://user-images.githubusercontent.com/36190914/83527692-cb693f00-a4f0-11ea-932b-193ed035d03c.png)
But it does not seem to work, where on the other hand when I apply it to a minio user created directly from the minio client, it does work. Am I missing any step here?

**Comment by harshavardhana** [comment]
> My question is off topic but is there an example that could showcase how a minio policy can be applied to a keycloak user?
> 
> What I've done so far is create a policy from the Minio Client and set it an attribute to a KeyCloak user as shown in the picture below:
> ![image](https://user-images.githubusercontent.com/36190914/83527692-cb693f00-a4f0-11ea-932b-193ed035d03c.png)
> But it does not seem to work, where on the other hand when I apply it to a minio user created directly from the minio client, it does work. Am I missing any step here?

Once you have created the keycloack user you need to use it with one of the STS APIs.

**Comment by csymvoul** [comment]
How do I do that? It is not clear to me so far.

@harshavardhana I can login to MinIO through KeyCloak. Isn't this login using STS API?
My issue is that the policy is not applied.
