### ISSUE TITLE
Minio gateway to connect linode object storage

### ISSUE THREAD

**Issue by AnishLushte07** [minio/minio#8653]
**Is your feature request related to a problem? Please describe.**
I want to use linode object storage with minio.
Can you suggest any possible way to achieve this?

**Comment by harshavardhana** [comment]
Is Linode S3 compatible?

**Comment by kannappanr** [comment]
It looks like it is https://www.linode.com/2019/10/30/linode-object-storage-is-here/

@AnishLushte07 If Linode is indeed S3 compatible, then you should be able to use something like the following

```
AWS_ACCESS_KEY_ID=<Linode_Access_Key> AWS_SECRET_ACCESS_KEY=<Linode_Secret_Key> MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 minio gateway s3 http://linode_url:port
```

Please reach out to us at https://slack.min.io for such questions
