### ISSUE TITLE
Building minio/minio in docker fails due to ambiguous import of vault API

### ISSUE THREAD

**Issue by anandadalton** [minio/minio#8659]
## Expected Behavior
When I build minio/minio from source in a docker container, it should succeed.

## Current Behavior
Hits build issue during execution of
# GOARCH=amd64 GO111MODULE=on go get github.com/minio/minio

```
build github.com/minio/minio: cannot load github.com/hashicorp/vault/api: ambiguous import: found github.com/hashicorp/vault/api in multiple modules:
        github.com/hashicorp/vault v1.1.0 (/go/pkg/mod/github.com/hashicorp/vault@v1.1.0/api)
        github.com/hashicorp/vault/api v1.0.4 (/go/pkg/mod/github.com/hashicorp/vault/api@v1.0.4)
```

## Steps to Reproduce (for bugs)
1. Install docker using the get.docker.com script.
2. Run $ docker run -it --rm golang:1.13.4-alpine3.10
3. Within the container, run $ apk update && apk add git gcc libc-dev
4. Then, run $ GOARCH=amd64 GO111MODULE=on go get github.com/minio/minio

First saw this in my CI/CD setup on Dec 14 2019 at 8AM PST.

**Comment by harshavardhana** [comment]
Works fine for me @liammdalton looks like GOPROXY is problematic here..

**Comment by anandadalton** [comment]
Hm, what are your GOPROXY settings? Turning it off, setting it to GOPROXY=https://proxy.golang.org,direct, etc. does not seem to work

**Comment by harshavardhana** [comment]
We have CIs running all the time, so what you see as issue is on your end. Most probably purge your perhaps GOPATH/pkg and let Go build it again.

**Comment by harshavardhana** [comment]
Closing this issue as not reproducible and solely a client environment issue.

**Comment by kluiko** [comment]
the same issue on FreeBSD (latest FreeNAS)
# GO111MODULE=on go get github.com/minio/minio
go: finding github.com/minio/minio latest
go: finding github.com/gorilla/rpc v1.2.0+incompatible
go: finding github.com/gorilla/rpc v1.2.0+incompatible
build github.com/minio/minio: cannot load github.com/hashicorp/vault/api: ambiguous import: found github.com/hashicorp/vault/api in multiple modules:
        github.com/hashicorp/vault v1.1.0 (/root/go/pkg/mod/github.com/hashicorp/vault@v1.1.0/api)
        github.com/hashicorp/vault/api v1.0.4 (/root/go/pkg/mod/github.com/hashicorp/vault/api@v1.0.4)

**Comment by kejadlen** [comment]
I'm seeing this as well, both locally on macOS and in Docker (and in both the alpine golang docker image as well as the normal golang image). Since it repros in Docker, I'm not sure it's an issue with a tainted existing environment or an erroneous `GOPROXY`?

**Comment by c-reiter** [comment]
@harshavardhana same issue on macOS 10.14.4 with freshly installed Go 1.13.5. I would be happy to provide more details if helpful/requested!

**Comment by c-reiter** [comment]
Also tried it on a completely fresh environment now. Debian 10. Installed Go exactly like listed on golang.org:

wget https://dl.google.com/go/go1.13.5.linux-amd64.tar.gz
tar -C /usr/local -xzf go1.13.5.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin
GO111MODULE=on go get github.com/minio/minio

and received the same error:

> go: finding github.com/gorilla/rpc v1.2.0+incompatible
go: finding github.com/gorilla/rpc v1.2.0+incompatible
build git.kescher.at/forestCloud/minio: cannot load github.com/hashicorp/vault/api: ambiguous import: found github.com/hashicorp/vault/api in multiple modules:
	github.com/hashicorp/vault v1.1.0 (/root/go/pkg/mod/github.com/hashicorp/vault@v1.1.0/api)
	github.com/hashicorp/vault/api v1.0.4 (/root/go/pkg/mod/github.com/hashicorp/vault/api@v1.0.4)

**Comment by c-reiter** [comment]
I'm not that experienced with golang and gomodules, but I got one idea on what could possibly be the reason: as the log says it's using hashicorp/vault/api@v1.0.4 and v1.1.0, but v1.0.4 doesn't exist anymore on vaults release page:
https://github.com/hashicorp/vault/releases?after=sdk%2Fv0.1.10
https://github.com/hashicorp/vault/tree/v1.0.4

**Comment by anandadalton** [comment]
I was able to build Minio by running the following dockerfile

```Dockerfile
FROM golang:1.13.4-alpine3.10 AS builder

RUN true \
  && apk update \
  && apk add git gcc libc-dev \
  && cd /tmp/ \
  && git clone https://github.com/minio/minio \
  && cd minio \
  && GO111MODULE=on go build . \
  && true

FROM alpine:3.10  
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /tmp/minio/minio /root/minio
RUN /root/minio --version
```

I am not really sure what the difference is between the build instructions I gave at the beginning and these new instructions I've put here--maybe someone with more understanding of how git's module system works could hazard a guess.

Either way, I still think there's a bug somewhere. At the very least, the README.md file says you should be able to run "go get" to build minio from source, and that's not true right now. Can we reopen?

**Comment by harshavardhana** [comment]
No we can't reopen because we build from source using go get all the time. There is nothing we can do to fix this, upstream code broke their build, we have fixed it locally with the right go.mod changes 

Either it's an issue of the goproxy servers located locally for most of the reports here or it's some inherent bug in the go mod system.

All our developers are able to build without issues, even dependent projects such as mc, m3 etc

**Comment by c-reiter** [comment]
Cloning from Github and building from within the directory like @liammdalton explained it also worked for me. Thank you @liammdalton !

**Comment by harshavardhana** [comment]
Fresh install found some time to reproduce this

```
$ ls
snap

$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/harsha/.cache/go-build"
GOENV="/home/harsha/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/harsha/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/4901"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/4901/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build677497440=/tmp/go-build -gno-record-gcc-switches
```

```
$ go get github.com/minio/minio
...
build github.com/minio/minio: cannot load github.com/hashicorp/vault/api: ambiguous import: found github.com/hashicorp/vault/api in multiple modules:
	github.com/hashicorp/vault v1.1.0 (/home/harsha/go/pkg/mod/github.com/hashicorp/vault@v1.1.0/api)
	github.com/hashicorp/vault/api v1.0.4 (/home/harsha/go/pkg/mod/github.com/hashicorp/vault/api@v1.0.4)
```

**Comment by harshavardhana** [comment]
Looks like the problem is one of cyclical dependency from `minio/mc` and `minio/minio` which leads to confusing situation like this.
