### ISSUE TITLE
minio multi-part upload multi instances

### ISSUE THREAD

**Issue by someorz** [minio/minio#8663]
if i upload a larger file to a distributed MinIO cluster,the part of file will upload to different node，after the file upload complete, minio will merge to a complete file?

![image](https://user-images.githubusercontent.com/5456361/71072945-6af07a80-21ba-11ea-9f80-33aaede82a51.png)

**Comment by nitisht** [comment]
Yes MinIO will ensure parts are merged in a complete file. Closing this as answered, please join us on Slack (https://slack.min.io) for more such questions
