### ISSUE TITLE
Can’t apply policy to LDAP integrated user or group

### ISSUE THREAD

**Issue by davemsolomon** [minio/minio#8667]
Using minio edge server from docker hub and mc edge client from docker hub. 

Call that is failing is 
mc admin policy set rnd everything user=ldapintegrateduser

Call is failing with 
mc: <error> Cannot set the policy. The specified user does not exist. 

I know that the LDAP integration is working because I called AssumeRoleWithLDAPIdentity with good and bad LDAP credentials and the call was successful for the good credentials and it failed for the bad credentials as expected.

**Comment by davemsolomon** [comment]
Server Version: 2019-12-18T08:39:59Z

**Comment by davemsolomon** [comment]
Client Version: DEVELOPMENT.2019-12-14T16-56-58Z

**Comment by davemsolomon** [comment]
when investigating this issue it might be interesting to note that it is possible to apply a policy to the accesskey that comes back from assumerolewithldapidentity using  mc admin policy set rnd everything user=accesskeyreturnedfromassumerolewithldapidentity

**Comment by harshavardhana** [comment]
> when investigating this issue it might be interesting to note that it is possible to apply a policy to the accesskey that comes back from assumerolewithldapidentity using mc admin policy set rnd everything user=accesskeyreturnedfromassumerolewithldapidentity

We should definitely disable that @davemsolomon

**Comment by harshavardhana** [comment]
the question is - is the new policy honored @davemsolomon ?

**Comment by davemsolomon** [comment]
> the question is - is the new policy honored @davemsolomon ?

Yes the policy on the temp access id is honored.

**Comment by harshavardhana** [comment]
> Yes the policy on the temp access id is honored.

Ah then its a privilege escalation @davemsolomon I sent a fix already #8675

**Comment by kumy** [comment]
I also can't assign policy to LDAP users being by username or by temp credential (which seems normal thanks to the commits referenced above).

---
**Using ldap username:** (The one that should work)
```bash
# mc admin policy set tvt readwrite user=test
mc: <ERROR> Cannot set the policy. The specified user does not exist.
```
No logs on server side.

**Using the temp credentials:**
```bash
# mc admin policy set tvt readwrite user=6FX6VQ2J1IHMXXI0ZNQU
^Cmc: <ERROR> Cannot set the policy. We encountered an internal error, please try again.
```
Server side logs;
```
API: SetPolicyForUserOrGroup()
Time: 15:18:45 CEST 04/08/2020
DeploymentID: 853499e6-bc41-42b3-8c43-801fb1546abb
RequestID: 1603DAABD3A8BA26
RemoteHost: 127.0.0.1
Host: myhost:9000
UserAgent: MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-04-04T05:28:55Z
Error: Specified IAM action is not allowed under the current configuration
       5: github.com/minio/minio@/cmd/api-errors.go:1807:cmd.toAPIErrorCode()
       4: github.com/minio/minio@/cmd/admin-handlers.go:1059:cmd.toAdminAPIErrCode()
       3: github.com/minio/minio@/cmd/admin-handlers.go:1096:cmd.toAdminAPIErr()
       2: github.com/minio/minio@/cmd/admin-handlers-users.go:654:cmd.adminAPIHandlers.SetPolicyForUserOrGroup()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()

```

Also, display users info give useless results:
```bash
# mc admin user info tvt test
AccessKey: test
Status: 
PolicyName: 
MemberOf: 

# mc admin user info tvt 6FX6VQ2J1IHMXXI0ZNQU
AccessKey: 6FX6VQ2J1IHMXXI0ZNQU
Status: 
PolicyName: 
MemberOf: 

# mc admin user info tvt somethingthatdontexists
AccessKey: somethingthatdontexists
Status: 
PolicyName: 
MemberOf: 
```



Minio version: `RELEASE.2020-04-04T05-39-31Z`

**Comment by donatello** [comment]
@kumy Thanks for your report. I'm fixing the latter problem of listing user info in https://github.com/minio/minio/pull/9302 - however I am yet to find the cause of the user-does-not-exist error.

**Comment by donatello** [comment]
@kumy The problem is fixed in #9303

**Comment by kumy** [comment]
Thanks @danatello, is there some build available, so I can validate the fix?

**Comment by donatello** [comment]
> Thanks @danatello, is there some build available, so I can validate the fix?

You can try it out on the current master as the PR is merged. Thanks!

**Comment by kumy** [comment]
@donatello I still have problems. Now no users are recognized at all by `mc admin user info`.

I have tested `RELEASE.2020-04-10T03-34-42Z` and finally build it myself.

I have issued:
```bash
$ GO111MODULE=on go get github.com/minio/minio
$ GO111MODULE=on go build github.com/minio/minio
$ ll ~/go/pkg/mod/github.com/minio/ | grep minio
drwxr-xr-x  3 root root 4,0K 10 avril 10:55 minio-go
dr-x------ 10 root root 4,0K 10 avril 10:55 minio@v0.0.0-20200410071638-79bcb705bff5
## 79bcb705bff5 is the current master
$ /tmp/minio -v
minio version DEVELOPMENT.GOGET
$ /tmp/minio server --address ":9000" /tmp/test
[…]
```

From another shell:
```bash
$ curl -X POST -k "https://127.0.0.1:9000?Action=AssumeRoleWithLDAPIdentity&LDAPUsername=test&LDAPPassword=test&Version=2011-06-15"; echo
<?xml version="1.0" encoding="UTF-8"?>
<AssumeRoleWithLDAPIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
<AssumeRoleWithLDAPIdentityResult>
  <Credentials>
    <AccessKeyId>T4AM1MW6K9SDPKAP2XSG</AccessKeyId>
    <SecretAccessKey>xxxx</SecretAccessKey>
    <Expiration>2020-04-12T21:08:08Z</Expiration>
    <SessionToken>yyyy</SessionToken>
  </Credentials>
</AssumeRoleWithLDAPIdentityResult>
<ResponseMetadata><RequestId>16046A280C3AFE19</RequestId></ResponseMetadata></AssumeRoleWithLDAPIdentityResponse>

$ mc config host add test https://myrealdnsname:9000 T4AM1MW6K9SDPKAP2XSG xxxx
mc: <ERROR> Unable to initialize new config from the provided credentials. The security token included in the request is invalid.

$ mc config host add tvt https://myrealdnsname:9000 access_key secret_key
Added `tvt` successfully.

$ mc admin user info tvt T4AM1MW6K9SDPKAP2XSG
mc: <ERROR> Cannot get user info. The specified user does not exist.
$ mc admin user info tvt test
mc: <ERROR> Cannot get user info. The specified user does not exist.
$ mc admin user info tvt something
mc: <ERROR> Cannot get user info. The specified user does not exist.
```

The web interface also don't want the credentials
![Screenshot from 2020-04-10 11-12-55](https://user-images.githubusercontent.com/176794/78979513-52ff8680-7b1c-11ea-87d6-6876deeefc59.png)

Am I doing something wrong?

**Comment by kumy** [comment]
However, assigning permission seems working now, but `mc config host add test …` still report an error as of the web interface
```bash
$ mc admin policy set tvt readwrite user=test

Policy readwrite is set on user `test`

# tried authenticate again, but still no luck

$ curl -X POST "https://myrealdnsname:9000?Action=AssumeRoleWithLDAPIdentity&LDAPUsername=test&LDAPPassword=test&Version=2011-06-15"; echo
<?xml version="1.0" encoding="UTF-8"?>
<AssumeRoleWithLDAPIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"><AssumeRoleWithLDAPIdentityResult><Credentials><AccessKeyId>MYOG28CVW4RFI55830D4</AccessKeyId><SecretAccessKey>Ex9G8y0gxxxxx</SecretAccessKey><Expiration>2020-04-12T21:24:47Z</Expiration><SessionToken>eyJhbGciOiJyyyy</SessionToken></Credentials></AssumeRoleWithLDAPIdentityResult><ResponseMetadata><RequestId>16046B1083D35FBF</RequestId></ResponseMetadata></AssumeRoleWithLDAPIdentityResponse>

$ mc config host add test https://myrealdnsname:9000 MYOG28CVW4RFI55830D4 Ex9G8y0gxxxxx
mc: <ERROR> Unable to initialize new config from the provided credentials. The security token included in the request is invalid.
```

**Comment by harshavardhana** [comment]
You cannot yet use LDAP creds on browser @kumy you need to use session token as well.

You can't use mc and MinIO browser they do not support LDAP temporary credentials

**Comment by kumy** [comment]
@harshavardhana you completely loose me!

> You cannot yet use LDAP creds on browser

Do you mean, that credentials `test`/`test` in my example (`LDAPUsername`, `LDAPPassword` in the curl line) ?

> you need to use session token as well.

So we have to use a mix between ldap and xml response? Should the credentials used on the web interface be `test` `yyyy` (`yyyy`? the really long token from the xml response? `<SessionToken>yyyy</SessionToken>`)

> You can't use mc and MinIO browser they do not support LDAP temporary credentials

Really, then what is ldap auth used for?

@davemsolomon @harshavardhana @donatello May you please share some real life examples of using LDAP auth? Is there any page referencing them?  Thanks :)

**Comment by harshavardhana** [comment]
> So we have to use a mix between ldap and xml response? Should the credentials used on the web interface be `test` `yyyy` (`yyyy`? the really long token from the xml response? `<SessionToken>yyyy</SessionToken>`)
> 

It is to be used by an application which supports STS authentication @kumy 




> @davemsolomon @harshavardhana @donatello May you please share some real life examples of using LDAP auth? Is there any page referencing them? Thanks :)

Real life examples require real life applications, AssumeRoleWithLDAP is a MinIO extension API doesn't exist on AWS.  We are also planning to deprecate this usage in the future as we are migrating our efforts 

https://github.com/minio/mcs

**Comment by kumy** [comment]
So there is no possibility to have a multi users minio instance plugged on an existing LDAP server, instead of relying on internal minio accounts?

**Comment by harshavardhana** [comment]
> So there is no possibility to have a multi users minio instance plugged on an existing LDAP server, instead of relying on internal minio accounts?

For now, no @kumy unless you have an application which can use LDAP

**Comment by kumy** [comment]
Then I have to use a proxyserver+auth and enable `readWrite` permission in minio to the `anonymous` user. That will really lower the security level of the solution :(

**Comment by harshavardhana** [comment]
> Then I have to use a proxyserver+auth and enable `readWrite` permission in minio to the `anonymous` user. That will really lower the security level of the solution :(

You can use web-identity @kumy which is supported by Browser!

**Comment by kumy** [comment]
We planned to use minio as a storage for our ldap backed users, each user could have used it's normal credential on web interface or using `mc`, for basic upload/download operation.

I'm wondering if we should not direct ourself to something else like nextcloud (with a minio backend)… We seem to have misunderstood the LDAP functionnality in minio :)

**Comment by harshavardhana** [comment]
> I'm wondering if we should not direct ourself to something else like nextcloud (with a minio backend)… We seem to have misunderstood the LDAP functionnality in minio :)

For now yes @kumy LDAP is not natively a secure protocol so we had to go through the process of STS to make it secure both are not for the same worlds.
