### ISSUE TITLE
When I use erasure code mode, how can my old data become erasure code

### ISSUE THREAD

**Issue by hzw2312** [minio/minio#8670]
When I use erasure code mode, how can my old data become erasure code?

Can you add a configuration to make the erasure code mode support source files?Or should I use a tool to convert all the source files of the old data into erasure codes?

I want to use the tool to convert old data source files into erasure codes, but it's too much!

In addition, in the absence of erasure code mode, how to achieve the file always backup?I am looking forward to your reply. I really appreciate it.

**Comment by harshavardhana** [comment]
you need to use `mc mirror` to copy the data into MinIO @hzw2312

**Comment by kannappanr** [comment]
@hzw2312 Closing this issue as answered. Please feel free to reach out to us at https://slack.min.io for such questions
