### ISSUE TITLE
un-deprecate --config-dir flag for docker/kubernetes

### ISSUE THREAD

**Issue by chrisbecke** [minio/minio#8671]
**Problem Statement**
Minio server stores its config file in its configured data path. This is problematic on Kubernetes and Docker as the data path is probably a persistent volume claim or docker volume, which, at least in the case of docker, means that the Minio config cannot be supplied safely as a Docker config.

**Describe the solution you'd like**
`--config-dir` to allow configuration to be supplied from outside the storage backend. Preferably a :ro config mapping. Actually, given everything else is a env var, `MINIO_CONFIG_PATH` or something like that would go down a treat.

**Describe alternatives you've considered**
Perhaps Minio needs a more sophisticated config system that can merge config from multiple sources.

**Additional context**
When deploying containerised applications, such as Minio, on platforms such as Kubernetes and Docker swarm, deployments are always made easier when the platforms native configuration and secret management features can be properly utilised.

**Comment by harshavardhana** [comment]
This is not useful for us we have already moved l to k8s native 

All configs have env equivalent. What you are suggesting is already supported.

**Comment by chrisbecke** [comment]
They are? 
If they are then I'm very happy to close.
I'm just frustrated right now as theres no *apparent* way to configure rabbitMQ.
How//where do I find the equivalent env vars to configure that?

**Comment by harshavardhana** [comment]
Just do this `mc admin config set myminio notify_amqp --env`

**Comment by chrisbecke** [comment]
I assume you mean `mc admin config get gametech notify_amqp --env` and the `--env` flag must be very bleeding edge as `docker run -it --entrypoint=/bin/sh minio/mc:edge` has no knowledge of it :/

**Comment by harshavardhana** [comment]
No I meant `admin config set`

**Comment by harshavardhana** [comment]
Of course it has that is the whole release we did yesterday. I don't know which version you are running just use the latest release.

**Comment by harshavardhana** [comment]
Also make sure you are running the latest server as well

**Comment by chrisbecke** [comment]
Oh wow.
That took a bit of force updating to get everything to update properly.

```sh
ARGS:
MINIO_NOTIFY_AMQP_URL*           (url)       AMQP server endpoint e.g. `amqp://myuser:mypassword@localhost:5672`
MINIO_NOTIFY_AMQP_EXCHANGE       (string)    name of the AMQP exchange
MINIO_NOTIFY_AMQP_EXCHANGE_TYPE  (string)    AMQP exchange type
MINIO_NOTIFY_AMQP_ROUTING_KEY    (string)    routing key for publishing
MINIO_NOTIFY_AMQP_MANDATORY      (on|off)    quietly ignore undelivered messages when set to 'off', default is 'on'
MINIO_NOTIFY_AMQP_DURABLE        (on|off)    persist queue across broker restarts when set to 'on', default is 'off'
MINIO_NOTIFY_AMQP_NO_WAIT        (on|off)    non-blocking message delivery when set to 'on', default is 'off'
MINIO_NOTIFY_AMQP_INTERNAL       (on|off)    set to 'on' for exchange to be not used directly by publishers, but only when bound to other exchanges
MINIO_NOTIFY_AMQP_AUTO_DELETED   (on|off)    auto delete queue when set to 'on', when there are no consumers
MINIO_NOTIFY_AMQP_DELIVERY_MODE  (number)    set to '1' for non-persistent or '2' for persistent queue
MINIO_NOTIFY_AMQP_QUEUE_DIR      (path)      staging dir for undelivered messages e.g. '/home/events'
MINIO_NOTIFY_AMQP_QUEUE_LIMIT    (number)    maximum limit for undelivered messages, defaults to '10000'
MINIO_NOTIFY_AMQP_COMMENT        (sentence)  optionally add a comment to this setting
```
