### ISSUE TITLE
Unable to expand existing distributed setup

### ISSUE THREAD

**Issue by joonhwan** [minio/minio#8672]
I'm trying to expand a given distributed setup following the [doc](https://github.com/minio/minio/blob/c8d82588c2208d8ee760fa8a79288ad2c9e63466/docs/distributed/README.md#expanding-existing-distributed-setup)

## Expected Behavior
After expanding distributed setup, minio server works correctly with files that uploaded before expanding. 

## Current Behavior
Service hang. see the [log](https://gist.github.com/joonhwan/d92aafcd45dae0b8c9f5a53e9d971c3a#file-docker-compose-log-after-expand-log) though it does not look much helpful.

## Possible Solution
...

## Steps to Reproduce (for bugs)

1. I deploy initial cluster setup the method described at [docker-compose deplyment document](https://github.com/minio/minio/blob/78be3f8947c3578a820e1cb2ab180458e9a91d60/docs/orchestration/docker-compose/README.md). no in each node(`minio{1...4}`), following command is running.

```
minio1 ==> minio server http://minio{1...4}/data{1...2}
minio2 ==> minio server http://minio{1...4}/data{1...2}
minio3 ==> minio server http://minio{1...4}/data{1...2}
minio4 ==> minio server http://minio{1...4}/data{1...2}
```
2. I uploaded several files their.  and then `docker-compose down`.  Please be noted that docker volumes that are created still remain, so that  `minio` server command will know uploaded files there when it is re-exectued again in each node.

3. I modified original `docker-compose.yaml` into new one with additional 4 nodes(`minio5~minio8`) and following commands runs in each node. 

```
minio1 ==> minio server http://minio{1...4}/data{1...2} http://minio{5...8}/data{1...2}
minio2 ==> minio server http://minio{1...4}/data{1...2} http://minio{5...8}/data{1...2}
minio3 ==> minio server http://minio{1...4}/data{1...2} http://minio{5...8}/data{1...2}
minio4 ==> minio server http://minio{1...4}/data{1...2} http://minio{5...8}/data{1...2}

minio5 ==> minio server http://minio{5...8}/data{1...2} http://minio{1...4}/data{1...2}
minio6 ==> minio server http://minio{5...8}/data{1...2} http://minio{1...4}/data{1...2}
minio7 ==> minio server http://minio{5...8}/data{1...2} http://minio{1...4}/data{1...2}
minio8 ==> minio server http://minio{5...8}/data{1...2} http://minio{1...4}/data{1...2}
```
see the full [docker-compose.yaml](https://gist.github.com/joonhwan/d92aafcd45dae0b8c9f5a53e9d971c3a#file-docker-compose-expanded-yaml)

4.  `docker-compose up`  again 

## Context
N/A

## Regression
No

## Your Environment
* Version used (`minio/minio:2019-12-17T23:16:33Z`, and `minio/minio:edge`):
* Environment name and version (e.g. docker for windows /w docker version 19.03.5 ):

**Comment by harshavardhana** [comment]
Don't use docker for windows. Docker for windows is beta version and doesn't provide the right semantics for writing consistently to the backend.

Use the same setup on Linux.

**Comment by harshavardhana** [comment]
Also your input command line is wrong, the input command line should be same for the expanded setup as well.

**Comment by harshavardhana** [comment]
```
minio1 ==> minio server http://minio{1...4}/data{1...2}
minio2 ==> minio server http://minio{1...4}/data{1...2}
minio3 ==> minio server http://minio{1...4}/data{1...2}
minio4 ==> minio server http://minio{1...4}/data{1...2}
```

Should be 

```
minio1 ==> minio server http://minio{1...4}/data{1...2} http://minio{5...8}/data{1...2}
minio2 ==> minio server http://minio{1...4}/data{1...2} http://minio{5...8}/data{1...2}
minio3 ==> minio server http://minio{1...4}/data{1...2} http://minio{5...8}/data{1...2}
minio4 ==> minio server http://minio{1...4}/data{1...2} http://minio{5...8}/data{1...2}

minio5 ==> minio server http://minio{1...4}/data{1...2} http://minio{5...8}/data{1...2}
minio6 ==> minio server http://minio{1...4}/data{1...2} http://minio{5...8}/data{1...2}
minio7 ==> minio server http://minio{1...4}/data{1...2} http://minio{5...8}/data{1...2}
minio8 ==> minio server http://minio{1...4}/data{1...2} http://minio{5...8}/data{1...2}
```

**Comment by joonhwan** [comment]
I'll try this in Ubuntu 18.04

**Comment by joonhwan** [comment]
Yes. the minio server command line arguments was wrong. With corrected one, expanded clusters work as expected. thanks.

**Comment by joonhwan** [comment]
One thing to note. I tested it on docker for windows machine, it worked. The problem was just the command line arguments.

**Comment by harshavardhana** [comment]
> One thing to note. I tested it on docker for windows machine, it worked. The problem was just the command line arguments

Yes but avoid it nonetheless docker for windows is not stable enough for production work, let alone run erasure-coded MinIO on it.

**Comment by zhangpfly** [comment]
OK. Thanks ! I change the command, It takes effect.

first command
```
minio server http://192.168.6.{121...122}/data{1...4}
```
expand existing distributed setup
```
minio server http://192.168.6.{121...122}/data{1...4} http://192.168.6.{123...124}/data{1...4}
```
