### ISSUE TITLE
be able to that the daemon can listen on multiple interfaces but not all

### ISSUE THREAD

**Issue by ghost** [minio/minio#8676]
**Is your feature request related to a problem? Please describe.**
On our nodes we have 4 network interfaces. 2 of them are wireguard interfaces on which the minio daemon should be available over. currently it is only possible to listen on all or one interface. The workaround is to use iptables rules to block external access to the minio server API.

**Describe the solution you'd like**
Be able to specify exactly which interfaces you would minio to listen on via --address statement

**Describe alternatives you've considered**
Well, as I stated. You can just use iptables for now.

**Additional context**
nothing here

**Comment by harshavardhana** [comment]
This is a low priority for us right now, we would rather keep things simple and not complicate it.
