### ISSUE TITLE
`brew audit --new-formula minio/stable/minio` returns problems

### ISSUE THREAD

**Issue by kaankabalak** [minio/minio#8679]
According to the [basic instructions listed on the Formula Cookbook](https://docs.brew.sh/Formula-Cookbook#basic-instructions), we need to make sure that the package passes all `brew audit --new-formula <formula>` tests. 

As we haven't explicitly submitted this formula to the Homebrew upstream, we might not be wanting to follow the guidelines exactly. If that's the case, the issue can be closed, however the problems listed below `brew audit --new-formula minio/stable/minio` run seem to be good improvements to make if we want the formulas to be more idiomatic.

```
minio/stable/minio:
  * C: 5: col 9: Description shouldn't start with the formula name
  * C: 8: col 24: `%r`-literals should be delimited by `{` and `}`.
  * C: 8: col 24: Use `//` around regular expression.
  * C: 8: col 36: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * C: 8: col 42: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * C: 28: col 1: Use 2 spaces for indentation in a heredoc by using `<<~` instead of `<<-`.
  * C: 58: col 1: `EOS` is not aligned with `(testpath/"config.json").write <<-EOS` or beginning of method definition.
Error: 7 problems in 1 formula detected
```

**Comment by harshavardhana** [comment]
Moved the issue here from homebrew tap, @kaankabalak do you have any recommendation for a fix?

**Comment by harshavardhana** [comment]
https://github.com/minio/homebrew-stable/commit/962212458ce447b613c2e0b6617b727d795d17e3 - issues mentioned here are fixed.
