### ISSUE TITLE
error="file currently locked" 423 lockd

### ISSUE THREAD

**Issue by myrust-go** [minio/minio#8685]
**Question**
I upload file often failed.  Chrome tips :  423 locked.

These uploaded files are very large, usually between 15G and 100G.

I use nginx for load balancing and the ip address is 192.168.30.189.
Nginx distributes requests to three servers with IP addresses: 192.168.30.201:9000, 192.168.30.202:9000, 192.168.30.203:9000.

command is:
./tusd -s3-bucket = tus -s3-endpoint = http: //192.168.30.189: 9000 /

tusd command line tips is:  

[tusd] 2019/12/21 19:55:16 event="ResponseOutgoing" status="423" method="PATCH" path="0a1aec18ea7f475dcd9bea41a2c5bdc6+5187e42a-bcbb-40f4-949f-1e875f7ef22c" error="file currently locked"

uppy configure is:
`

.use(Uppy.Tus, {
  endpoint: 'http://192.168.30.189:1080/files',
  chunkSize: 5242880,
  resume: true,
  // limit: 20
 })

`

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: linux centos7
- Used tusd version: 1.0.2
- Used tusd data storage: minio   s3 protected
- Used tusd configuration: ./tusd -s3-bucket=tus -s3-endpoint=http://192.168.30.189:9000/
- Used tus client library: uppy.js
- Used web Server: nginx
- Used Load Balance: nginx upsteam for minio

**Comment by kannappanr** [comment]
@kaiwenli Looks like `423` is being returned by `tusd` MinIO does not return `423`

There are related issues in tusd github. 

https://github.com/tus/tusd/issues?q=is%3Aissue+423

I see that you have also filed one over there.

**Comment by myrust-go** [comment]
Okay, Thank you very much!

I found a bug when tusd is stored in s3. There was a problem with sync's lock mechanism.
But I haven't figured out how to solve it.

**Comment by kannappanr** [comment]
@kaiwenli Closing this issue as there is nothing to be done in MinIO
