### ISSUE TITLE
Add --version flag

### ISSUE THREAD

**Issue by MAHDTech** [minio/minio#8687]
**Is your feature request related to a problem? Please describe.**

In previous versions of minio server there was the ability to get the version number from the cli in a single command. Neither of these work in the current release.

I would like to see a new ```--version``` available in the same format as mc.

```
minio --version
minio version
```

**Describe the solution you'd like**

Consistency between the MinIO Client and MinIO Server that when a user runs the below commands they receive the release version back in the same format.

```
# Current mc does this

mc --version
mc version RELEASE.2019-12-17T23-26-28Z

mc version
Version: 2019-12-17T23:26:28Z
Release-tag: RELEASE.2019-12-17T23-26-28Z
Commit-id: d92d2f0d4f1c21236cecf5a305bd6679b9527f66

# The current MinIO release does this

minio --version
Incorrect Usage. flag provided but not defined: --version

minio version
‘version’ is not a minio sub-command. See ‘minio --help’.
```

**Describe alternatives you've considered**

```
minio --help | tail -n 1
```

**Additional context**

This is particularly useful for those of us using tools like Salt and Ansible to deploy and manage MinIO. I rely on the version number to make determinations about configuration and upgrades. It would be nice to be consistent between both client/server.

In a former minio server release as an example this was possible.

```
minio version
Version: 2019-10-12T01:39:57Z
Release-Tag: RELEASE.2019-10-12T01-39-57Z
Commit-ID: bd106408462ecef70debf51f1e6179de950c5812

minio --version
Incorrect Usage. flag provided but not defined: -version
```

**Comment by harshavardhana** [comment]
We removed it on purpose, what is the purpose behind it @MAHDTech ?

Also good catch for mc, we will be removing that as well.

**Comment by ghost** [comment]
What's the rationale for removing getting version? It's quite standard functionality. Also I couldn't find an issue describing these changes.

**Comment by MAHDTech** [comment]
> We removed it on purpose, what is the purpose behind it @MAHDTech ?
> 
> Also good catch for mc, we will be removing that as well.

So are you saying the only mechanism to determine the version number from the cli is to use ```--help```?

As I mentioned in the issue description I use this in Ansible and Salt to determine the version installed for automation.

**Comment by harshavardhana** [comment]
> What's the rationale for removing getting version? It's quite standard functionality. Also I couldn't find an issue describing these changes.

The rationale is that we don't need that sub-command it is a redundant command. 

@MAHDTech will add --version flag nonetheless, we will not bring back sub-command.

**Comment by harshavardhana** [comment]
Fixed in master on both minio and mc - shall be available in new release

**Comment by MAHDTech** [comment]
@harshavardhana, thanks for adding the --version flag back, if they could be made consistent between the client/server to have or not have the "RELEASE" prefix that would also be great.

**Client**
```
mc --version
mc version RELEASE.2019-12-24T23-41-36Z
```

**Server**
```
minio --version
minio version 2019-12-30T05:45:39Z
```
