### ISSUE TITLE
depoly minio in k8s with helm fail

### ISSUE THREAD

**Issue by RayRay10460** [minio/minio#8688]
deploy minio in k8s with 
helm install --namespace default --name minio-deploy --set persistence.storageClass=nfs-storage,persistence.size=5Gi,mode=distributed,accessKey=minio,secretKey=minio123 stable/minio
will error.

## Expected Behavior

minio work normally

## Current Behavior

minio work abnormally

## Possible Solution

I depploy 4 pods in k8s, minio-deploy-0, 2,  3 seems work normally, but minio-deploy-1 report error:
Waiting for a minimum of 2 disks to come online (elapsed 0s)

Waiting for a minimum of 2 disks to come online (elapsed 2s)

Waiting for the first server to format the disks.
Server startup failed with 'Unable to initialize config system: Unable to initialize etcd config: ParseBool: parsing '': invalid syntax'
Server switching to safe mode
Please use 'mc admin' commands to fix this issue
Status:         4 Online, 0 Offline.

## Steps to Reproduce (for bugs)

1.  run helm install --namespace default --name minio-deploy --set persistence.storageClass=nfs-storage,persistence.size=5Gi,mode=distributed,accessKey=minio,secretKey=minio123 stable/minio
will error.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

env: k8s 
version:   RELEASE.2019-12-19T22-52-26Z

**Comment by harshavardhana** [comment]
First don't use NFS for distributed backend storage, thumb rule is don't run nas on top of another nas solution MinIO.

Also looks like you have been using MinIO with NFS if that is the case now is the time to change.

**Comment by harshavardhana** [comment]
Supporting NFS backend for distributed setup is not supported.
