### ISSUE TITLE
Disk space will not decrease after deleting objects?

### ISSUE THREAD

**Issue by myrust-go** [minio/minio#8696]
**Is your feature request related to a problem? Please describe.**
Disk space will not decrease after deleting objects?

**Describe the solution you'd like**

On the web, delete an object, check disk space and check web storage tips. Disk space is still being used.

**Describe alternatives you've considered**
No

**Additional context**
Nothing.

**Comment by nitisht** [comment]
disk space update routine runs every 12 hours, you should see updated capacity in 12 hours. For more such questions please join us on slack (https://slack.min.io). Closing this as answered
