### ISSUE TITLE
Preliminary s3x support. 

### ISSUE THREAD

**Issue by posix4e** [minio/minio#8701]
**Is your feature request related to a problem? Please describe.**
Not so much a problem as much as a new backend. IPFS as a backend would be incredibly powerful, even if limited backend.

**Describe the solution you'd like**
Begin working with the s3x community to 
1. Identify how and if the two products could come together
2. Pick a preliminary merge back plan so s3x can merge its patches back into minio
3. Identify and prioritize what features are needed for parity with other gateways and inclusion.

**Describe alternatives you've considered**
Keeping s3x totally forked off will probably cause  bitrott  and continued divergence. 

**Additional context**
s3x has numerous limitations beyond what's common in other gateways
- Relatively bad file size limit (4MB)
- No ability to share links
- Normal new project stuff. A lack of docs, etc. 

https://github.com/RTradeLtd/s3x

**Comment by harshavardhana** [comment]
Thanks @posix4e please join https://slack.min.io so we can talk

**Comment by bonedaddy** [comment]
@posix4e i think there is some confusion after re-reading your listed limitations

> No ability to share links

I don't think this is a limitation, it's just not currently available. s3x is still pretty new, and this is a planned feature, but is pending more important things like getting an mvp up and running.

> Normal new project stuff. A lack of docs, etc.

There's a decent bit of documentation via comments in the `.proto` file and the various gateway files.  If the lack of central documentation location is an issue I can certainly improve that but it is probably best if you open an issue on the fork to coordinate this as it is not minio that is responsible for development of this.

> Relatively bad file size limit (4MB)

Not sure where you gathered this information from, as long as minio gateway itself doesn't have a file size limitation, s3x wont  have one.
