### ISSUE TITLE
Periodic errors with empty event storage 

### ISSUE THREAD

**Issue by mrsrvman** [minio/minio#8707]
periodic errors are observed when trying to write to the repository.
The storage is empty or almost empty (10 event files).

## Expected Behavior

periodic errors are observed when trying to write to the repository.
The event storage ( /tmp/minio/events/minio-webhook-1) is empty or almost empty (10 event files).
Most often occurs on one of four nodes.

Log 
```
{
"deploymentid": "2193f469-c66a-4faa-9964-7835f80eedd1",
"level": "ERROR",
"errKind": "MINIO",
"time": "2019-12-27T04:16:58.647162859Z",
"api": {
"name": "SYSTEM",
"args": {
"bucket": "on-demand",
"object": "072019/1234dd_5_a23_Invoice.pdf"
}
},
"error": {
"message": "the maximum store limit reached",
"source": [
"cmd/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()",
"cmd/logger/logonce.go:80:logger.LogOnceIf()",
"cmd/notification.go:1220:cmd.sendEvent.func1()"
],
"variables": {
"EventName": "s3:ObjectCreated:Put",
"targetID": "webhook"
}
}
}
{
"deploymentid": "2193f469-c66a-4faa-9964-7835f80eedd1",
"level": "ERROR",
"errKind": "MINIO",
"time": "2019-12-27T07:18:06.639626147Z",
"api": {
"name": "SYSTEM",
"args": {
"bucket": "docs",
"object": "122019/9156035681313091232"
}
},
"error": {
"message": "the maximum store limit reached",
"source": [
"cmd/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()",
"cmd/logger/logonce.go:80:logger.LogOnceIf()",
"cmd/notification.go:1220:cmd.sendEvent.func1()"
],
"variables": {
"EventName": "s3:ObjectCreated:Put",
"targetID": "webhook"
}
}
}
{
"deploymentid": "2193f469-c66a-4faa-9964-7835f80eedd1",
"level": "ERROR",
"errKind": "MINIO",
"time": "2019-12-27T07:49:16.916299207Z",
"api": {
"name": "SYSTEM",
"args": {
"bucket": "docs",
"object": "122019/9156035888213091994"
}
},
"error": {
"message": "the maximum store limit reached",
"source": [
"cmd/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()",
"cmd/logger/logonce.go:80:logger.LogOnceIf()",
"cmd/notification.go:1220:cmd.sendEvent.func1()"
],
"variables": {
"EventName": "s3:ObjectCreated:Put",
"targetID": "webhook"
}
}
}
```
```
Dec 28 04:59:07 doc-node03 minio: API: SYSTEM(bucket=testbucket2, object=file00000004.bin)
Dec 28 04:59:07 doc-node03 minio: Time: 04:59:07 UTC 12/28/2019
Dec 28 04:59:07 doc-node03 minio: DeploymentID: 2193f469-c66a-4faa-9964-7835f80eedd1
Dec 28 04:59:07 doc-node03 minio: Error: the maximum store limit reached
Dec 28 04:59:07 doc-node03 minio: EventName=s3:ObjectCreated:Put, targetID=webhook
Dec 28 04:59:07 doc-node03 minio: 3: cmd/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()
Dec 28 04:59:07 doc-node03 minio: 2: cmd/logger/logonce.go:80:logger.LogOnceIf()
Dec 28 04:59:07 doc-node03 minio: 1: cmd/notification.go:1220:cmd.sendEvent.func1()
Dec 28 04:59:07 doc-node03 minio: API: SYSTEM(bucket=testbucket2, object=file00000004.bin)
Dec 28 04:59:07 doc-node03 minio: Time: 04:59:07 UTC 12/28/2019
Dec 28 04:59:07 doc-node03 minio: DeploymentID: 2193f469-c66a-4faa-9964-7835f80eedd1
Dec 28 04:59:07 doc-node03 minio: Error: the maximum store limit reached
Dec 28 04:59:07 doc-node03 minio: EventName=s3:ObjectCreated:Put, targetID=webhook
Dec 28 04:59:07 doc-node03 minio: 3: cmd/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()
Dec 28 04:59:07 doc-node03 minio: 2: cmd/logger/logonce.go:80:logger.LogOnceIf()
Dec 28 04:59:07 doc-node03 minio: 1: cmd/notification.go:1220:cmd.sendEvent.func1()

```

## Steps to Reproduce (for bugs)

1. Run test with bulk write-read-delete over 100 000 files
2.  During the test, messages like "maximum store limit reached" begin to appear
3. Stop test
4. Messages will continue to appear periodically even when a file is written once to a specific node.

## Regression
 Yes

## Your Environment

* Version used (`minio version`):  2019-12-24T23:04:45Z
* Environment name and version (e.g. nginx 1.9.1): Load balancing - haproxy 1.8  Webhook - Nginx
* Server type and version:  OEL 7.6
* Operating System and version (`uname -a`):
Linux doc-node03 3.10.0-957.21.3.el7.x86_64 #1 SMP Mon Jun 17 15:42:47 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by harshavardhana** [comment]
Would you mind sharing the webhook configuration using `mc admin config get myminio/ notify_webhook` ?

**Comment by harshavardhana** [comment]
Also provide all the relevant `minio server` command line as well as haproxy config?

**Comment by mrsrvman** [comment]
```
notify_webhook enable=off endpoint= auth_token= queue_limit=0 queue_dir=
notify_webhook:1 endpoint=http://10.101.xx.xx:8080/api/webhook auth_token= queue_dir=/tmp/minio/events queue_limit=10000

```

**Comment by mrsrvman** [comment]
haproxy
bind *:443
```
backend bck_main_minio
    mode http
    fullconn                 10000

    option http-keep-alive
    option http-pretend-keepalive
    cookie storage insert indirect nocache #domain localhost
    option httpchk GET /minio/health/ready
    http-check expect status 200
    server doc-node01  10.101.xx.xx:9000  cookie 51941373945c4e3607fbe788029f230604d290c3 check inter 5000
    server doc-node02  10.101.xx.xx:9000  cookie 464352680d97821fcd201394280633002332f0e9 check inter 5000
    server doc-node03  10.101.xx.xx:9000  cookie 910f45aa52157702f4d2a4a5b875545e047f434c check inter 5000
    server doc-node04 10.101.xx.xx:9000  cookie 134b5ea450a6cd6ebb0875ab72f8d4b32321323d check inter 5000
```

bind to  *:8080
```
backend bck_doc_logs
    mode http
    option http-keep-alive
    cookie storage insert indirect nocache #domain localhost
    server log_server 127.0.0.1:18080  cookie 51941373945c4e3607fbe788029f230604d290c3 check inter 1000
```

**Comment by Praveenrajmani** [comment]
> :18080  c

@mrsrvman looks like the port number is wrong - ` log_server 127.0.0.1:18080 `. Can you please check? 

And I cannot reproduce this locally. Can you re-verify if the store entries were less when you hit this error?

**Comment by mrsrvman** [comment]
On tcp port 18080 a simple nginx logger works.
There may be a problem with the file counter in the event store.
On one node, an error now occurs if about 1-5 files appear in the event store.
[minio-webhook-1]$ ls -la
total 0
drwxr-x--- 2 minio-user minio-user  6 Dec 26 07:28 .
drwxr-x--- 3 minio-user minio-user 29 Dec 26 11:41 ..

**Comment by harshavardhana** [comment]
Let's not jump to conclusions right away.

@mrsrvman Can you explain why the port is different in the config where as the logger endpoint seems to be on 18080 and not 8080 ?

**Comment by mrsrvman** [comment]
Haproxy is used as a single entry point to minio storage and logging.
Haproxy balances connections to both minio nodes and logging nodes.
For this regression, it does not matter how minio connects to the logging point.
The result was checked and the same - an error with an empty event store.

**Comment by Praveenrajmani** [comment]
@mrsrvman Can you give us a reproducer using local fs mode without HA? This works fine for me when tested locally

**Comment by mrsrvman** [comment]
This is a very simple script that executes
1. Upload
2. Download
4. Comparison of downloaded and uploaded data.
5. Clearing test data in minio.
6. Repeat 

Requirements:
1. Install bash, md5deep, aws cli.
2. Preparation of test data.
```
#!/usr/bin/env bash
L_HOME="/home/test_minio/data"
L_PATH="${L_HOME}/test_data"
mkdir -p ${L_PATH}

for n in {1..100000}; do
    echo $RANDOM
    fsize=$(( 3* 1024 ))
    echo $fsize
    dd if=/dev/urandom of=${L_PATH}/file$( printf %08d "$n" ).bin bs=1 count=${fsize}
done

```
3. Preparing checksums - 
```
md5deep -r ./test_data/ > dir1sums
```
4. Access to minio
5. Configure and run the script.
```
#!/usr/bin/env bash

L_HOME="/home/test_minio/data"
L_PATH="./test_data"
L_D_PATH="${L_HOME}/tmp"
ENDPOINT="10.x.x.x"
BUCKET="testbucket2"

cd ${L_HOME}

echo "Upload"
time aws s3 cp ${L_PATH}  s3://${BUCKET}/ --endpoint-url=https://${ENDPOINT} --recursive  --no-verify-ssl  > /dev/null
echo "Download"
mkdir -p ${L_D_PATH}
time aws s3 cp s3://${BUCKET}/ ${L_D_PATH}   --endpoint-url=https://${ENDPOINT} --recursive  --no-verify-ssl  > /dev/null
echo "Compare files"
md5deep -r -n -X ./dir1sums ${L_D_PATH}
echo "Delete files"
rm -rf ${L_D_PATH}
time aws s3 rm s3://${BUCKET}/ --endpoint-url=https://${ENDPOINT} --recursive  --no-verify-ssl > /dev/null
```

**Comment by Praveenrajmani** [comment]
> This is a very simple script that executes
> 
>     1. Upload
> 
>     2. Download
> 
>     3. Comparison of downloaded and uploaded data.
> 
>     4. Clearing test data in minio.
> 
>     5. Repeat
> 
> 
> Requirements:
> 
>     1. Install bash, md5deep, aws cli.
> 
>     2. Preparation of test data.
> 
> 
> ```
> #!/usr/bin/env bash
> L_HOME="/home/test_minio/data"
> L_PATH="${L_HOME}/test_data"
> mkdir -p ${L_PATH}
> 
> for n in {1..100000}; do
>     echo $RANDOM
>     fsize=$(( 3* 1024 ))
>     echo $fsize
>     dd if=/dev/urandom of=${L_PATH}/file$( printf %08d "$n" ).bin bs=1 count=${fsize}
> done
> ```
> 
>     1. Preparing checksums -
> 
> 
> ```
> md5deep -r ./test_data/ > dir1sums
> ```
> 
>     1. Access to minio
> 
>     2. Configure and run the script.
> 
> 
> ```
> #!/usr/bin/env bash
> 
> L_HOME="/home/test_minio/data"
> L_PATH="./test_data"
> L_D_PATH="${L_HOME}/tmp"
> ENDPOINT="10.x.x.x"
> BUCKET="testbucket2"
> 
> cd ${L_HOME}
> 
> echo "Upload"
> time aws s3 cp ${L_PATH}  s3://${BUCKET}/ --endpoint-url=https://${ENDPOINT} --recursive  --no-verify-ssl  > /dev/null
> echo "Download"
> mkdir -p ${L_D_PATH}
> time aws s3 cp s3://${BUCKET}/ ${L_D_PATH}   --endpoint-url=https://${ENDPOINT} --recursive  --no-verify-ssl  > /dev/null
> echo "Compare files"
> md5deep -r -n -X ./dir1sums ${L_D_PATH}
> echo "Delete files"
> rm -rf ${L_D_PATH}
> time aws s3 rm s3://${BUCKET}/ --endpoint-url=https://${ENDPOINT} --recursive  --no-verify-ssl > /dev/null
> ```

Thanks @mrsrvman. Firstly, based upon your configuration pasted, i see the queue_limit been set to `10000` and in the test case provided, There were like `100000` files being uploaded. So, in this case `Error: the maximum store limit reached` is obviously expected as MinIO respects the queue_limit. Let me drop down some details on the working of queue-store in MinIO.

- MinIO enqueues the queue_store if the queue_limit is less. (count will be incremented here)
- And there is a thread which keeps listing the queue_store in batches and keeps replaying an event one by one
- If the target is connected and is OK, MinIO tries to send the event to the target configured.
- Upon a successful transit, the event (by the event id) will be deleted from the queue_store (count will be decremented here)
- When the queue_limit is reached during the enqueue(), MinIO will log it as you can see.

And MinIO will not print any repeated logs. And i suspect that, you saw some old logs when the queue_limit was reached. 

On the test case that you provided - MinIO enqueues the first 10000 events if the target is inactive, and the remaining events are simply lost, as the queue_limit is reached already.  And when the target is back active, it keeps replaying in batches. And the left overs will still reside in the queue_store if the target is again down during the replay. And you should set a higher value for the queue_limit to manage the heavy traffic.

**Comment by Praveenrajmani** [comment]
And the script exactly worked as i expected when tested with 150 files and queue_limit set to 100.

**Comment by mrsrvman** [comment]
I check the same scripts on the version RELEASE.2019-12-30T05-45-39Z, I can not reproduce the problem.
I will ask for a short pause for additional testing.

**Comment by mrsrvman** [comment]
I can say for sure - the errors were not old in time and appeared only at the time of activity.
This has been tested several times.

After updating to a new version and restarting the nodes, the error does not appear.
Now I can not repeat the error "the maximum store limit reached".

But there was another error that clearly appears if I execute a command during a test
```
mc admin service restart minio
```

One node starts to flood with errors like
```
{
  "deploymentid": "2193f469-c66a-4faa-9964-7835f80eedd1",
  "level": "ERROR",
  "errKind": "MINIO",
  "time": "2019-12-31T05:21:02.157521573Z",
  "api": {
    "name": "SYSTEM",
    "args": {}
  },
  "error": {
    "message": "target.Send() failed with 'remove /tmp/minio/events/minio-webhook-1/750ba552-1264-4091-84d6-c35ae7b26a2e.event: no such file or directory'",
    "source": [
      "cmd/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()",
      "cmd/logger/logonce.go:80:logger.LogOnceIf()",
      "pkg/event/target/store.go:112:target.sendEvents.func1()",
      "pkg/event/target/store.go:135:target.sendEvents()"
    ]
  }
}
{
  "deploymentid": "2193f469-c66a-4faa-9964-7835f80eedd1",
  "level": "ERROR",
  "errKind": "MINIO",
  "time": "2019-12-31T05:21:02.168928333Z",
  "api": {
    "name": "SYSTEM",
    "args": {}
  },
  "error": {
    "message": "target.Send() failed with 'remove /tmp/minio/events/minio-webhook-1/f1ae56d7-2e57-4091-b2ae-cf8c9c24f6c6.event: no such file or directory'",
    "source": [
      "cmd/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()",
      "cmd/logger/logonce.go:80:logger.LogOnceIf()",
      "pkg/event/target/store.go:112:target.sendEvents.func1()",
      "pkg/event/target/store.go:135:target.sendEvents()"
    ]
  }
}
```

Tested on RELEASE.2019-12-30T05-45-39Z and minio.RELEASE.2019-12-24T23-04-45Z
Helps only repeat command

```
mc admin service restart minio
```

**Comment by Praveenrajmani** [comment]
@mrsrvman one question - Are you running this in local fs mode (single node)?

**Comment by Praveenrajmani** [comment]
@mrsrvman This is an expected behavior when you try to test distributed mode locally. This known problem happens when you try to point a single `queue_dir` to all the nodes. Here, all the nodes read from the same volume causing a chaos. I would recommend you to use docker/k8s to test a distributed mode where basically each node will get its own ephemeral volume. Where you basically map a volume to a node with a same namespace/path across all the nodes. So that each node will have its own dedicated queue_dir.

You should not see this in local fs with one node.

**Comment by Praveenrajmani** [comment]
Anyway you could ignore such errors locally.. as these are expected to see

**Comment by mrsrvman** [comment]
I will describe the test bench:
4 independent nodes that work with their file and computing resources.
There are no shared file resources.
Data exchange occurs only through the network.
In front of the nodes is a load balancer - haproxy.

I saw errors:
After restarting the node.
Only when several nodes work, since one node always interrupts the operation of my test script when the node is restarted

For one node, I need to conduct a separate testing cycle.

**Comment by Praveenrajmani** [comment]
I am referring to  queue_store being `/tmp/minio/events/` which all the four nodes point @mrsrvman

**Comment by mrsrvman** [comment]
Nodes are configured exactly the same, right down to resources and directories.
/tmp/minio/events/ regular directory inside the operating system.
It is inside each node and does not intersect between nodes in any way.

**Comment by Praveenrajmani** [comment]
Ok.. And you see these errors after/before restarts? @mrsrvman

**Comment by mrsrvman** [comment]
```
target.Send() failed with 'remove 
```
Only after restart command

```
 Error: the maximum store limit reached
```
I will have to remember.
1. After problems with the availability of logging nodes.
2. Restarting the minio node through the command "mc admin service restart minio".

Should I do some additional testing?

**Comment by Praveenrajmani** [comment]
@mrsrvman Yes.. can you please test the following scenarios and see if you can still reproduce the issue?

- Set the queue_limit to a higher value
- Check the queue_dir entries at the time of failure / before restarting (if possible)
- Try reproducing this in local fs mode
- Try restarting with only one event in the queue_store?

And if this still happens.. Is it okay for you if i give you a custom image with logs/fix for better clarity on what is happening?

**Comment by Praveenrajmani** [comment]
@mrsrvman Never mind. I think i got the issue

**Comment by Praveenrajmani** [comment]
Working on this. Will send a PR soon @mrsrvman

**Comment by mrsrvman** [comment]
The patch helped.  The problem is fixed.
Thanks.
