### ISSUE TITLE
File name garbled when i downloaded files as a zip file.

### ISSUE THREAD

**Issue by smileinwind** [minio/minio#8712]
## Current Behavior
Expected the right file  name but garbled .

## Possible Solution
	// Use utf8 to  encode file name when compressing
			header := &zip.FileHeader{
				Name:   strings.TrimPrefix(objectName, args.Prefix),
				Flags:  1 << 11,
				Method: zip.Deflate,
			}
## Steps to Reproduce (for bugs)

1.select multiple uploaded files
2.download all as zip
3.open the zip file

## Context

The name of those files i uploaded was encoded by gbk;

## Regression
NO.

## Your Environment

linux x86_x64;
minio version 2019-12-24T23:04:45Z;

**Comment by harshavardhana** [comment]
Can you also give examples of the filename ?

**Comment by smileinwind** [comment]
Chinese characters for example:"新建文本文件.txt"




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Harshavardhana"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月30日(星期一) 上午10:43
收件人:&nbsp;"minio/minio"<minio@noreply.github.com&gt;;
抄送:&nbsp;"1041862263"<smileinwind@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [minio/minio] File name garbled when i downloaded files as a zip file. (#8712)




Can you also give examples of the filename ?

**Comment by harshavardhana** [comment]
Thanks this is helpful.

**Comment by kannappanr** [comment]
@smileinwind Closing this issue as #8693 has been merged
