### ISSUE TITLE
Error when try to setup a cluster environment

### ISSUE THREAD

**Issue by claytonnog** [minio/minio#8713]
Hi, guys, I am having trouble when I am trying to setup a cluster environment.

My minio.conf:
MINIO_OPTS="http://minio{1...4}:9000/opt/minio/data{1...4}"
MINIO_ACCESS_KEY=xxx
MINIO_SECRET_KEY=xxx

The errors when I try to start minio.service:
Dec 30 11:30:36 xxx minio[1811]: ERROR Unable to initialize backend: 1st disk is already being used in another erasure deployment. (Number of disks specified: 16 but the ...rmat.json: 4)
Dec 30 11:30:36 xxx systemd[1]: minio.service: main process exited, code=exited, status=1/FAILURE
Dec 30 11:30:36 xxx systemd[1]: Unit minio.service entered failed state.
Dec 30 11:30:36 xxx systemd[1]: minio.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

Could you help me please?

**Comment by kannappanr** [comment]
@claytonnog Atleast one of the disks must have been used in another MinIO deployment. You should not have any data in the folder that is being used here.

**Comment by kannappanr** [comment]
@claytonnog Closing this issue as answered. Please feel free to reach out to us if you feel otherwise.
