### ISSUE TITLE
[Proposal] Accelerate upload of a bunch of small files

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#8715]
**Is your feature request related to a problem? Please describe.**

Users are frustrated about the needed time to upload a bunch of small files (days). Although mc has parallel capacity of upload, it is still not enough for them.

I compared mc mirror with a written go code which uses parallel upload using minio-go PutObject, it doesn't seem mc is losing any significant time doing things other than uploading objects.

**Describe the solution you'd like**

Adding a specific metadata during the upload of a tarball archive, will unzip the content of tarball archive from .minio.sys/tmp/* to the actual destination, or probably in a streaming manner.

**Describe alternatives you've considered**

*) Profiling minio-go PutObject() could show possible enhancements.
*) Revisit mc parallel mechanism to see if it reached the maximum optimization

**Additional context**

**Comment by harshavardhana** [comment]
Will fix the problem mentioned in #8710

**Comment by vadmeste** [comment]
Adding a possible other solution here, which is adding an API in web-handlers.go to decompress on the fly a tar ball and adds this feature in MinIO Browser (I am assuming here that users will copy large data set of small files only once a while)

**Comment by teccem** [comment]
the problem is still actual. Performance is too low, when upload tons of files. Compressing-decompressing possibility will solve the issue.

**Comment by xuning97** [comment]
So is there any plan to solve this issue? provide a automatic decompression feature?

**Comment by klauspost** [comment]
Likely not, but keeping it assigned pending discussion.

**Comment by harshavardhana** [comment]
> *) Revisit mc parallel mechanism to see if it reached the maximum optimization

https://github.com/minio/mc/pull/3483 - this helped gain 2x performance for lots of small files @vadmeste
