### ISSUE TITLE
Documentation: how files are mapped to zones

### ISSUE THREAD

**Issue by candlerb** [minio/minio#8718]
## Issue
In distributed mode with multiple zones, I would like to understand how minio maps a particular GET request to the correct zone.

Does it maintain a per-object mapping database? Does it send the query to all zones and see which one answers? Something else?

## Current Documentation
[Documentation](https://docs.min.io/docs/distributed-minio-quickstart-guide.html) says:

> There are 2 zones in this example. Objects are placed in zones based on which zone has the *fmost [sic] free* space. Within each zone, the location of the erasure-set of drives is determined based on a deterministic hashing algorithm.

Identifying the zone with the most free space for a PUT is obvious; it's mapping a subsequent GET to the correct zone which is unclear.

**Comment by harshavardhana** [comment]
> Does it maintain a per-object mapping database? Does it send the query to all zones and see which one answers? Something else?

There is no database, we lookup everywhere @candlerb - PUT looks for free space available as of last resort - if it finds a previously existing object it overwrites the one where it finds. 

Eventually the plan to do a binary search in future, also do optimizations like send GET lookups first to recently completed PUT zone, etc

MinIO is designed to never use any database, our lookup is backend disks themselves which maintain the real namespace.

**Comment by harshavardhana** [comment]
Also, there is an overhaul planned for our docs which will move away from the current style to a more guide style. Closing this issue such that these will be fixed in an umbrella issue coming month.
