### ISSUE TITLE
Documentation: selection of data drives in erasure coding zone

### ISSUE THREAD

**Issue by candlerb** [minio/minio#8719]
## Issue
The [distributed minio quickstart guide](https://docs.min.io/docs/distributed-minio-quickstart-guide.html) gives an example of a cluster with 32 servers x 32 disks = 1024 disks.

A distributed cluster will use erasure coding.  The question is, does every single object get split into 1024 separate parts?  i.e. 512 data parts + 512 parity parts (standard redundancy), or 1022 data parts + 2 parity parts (reduced redundancy)?

The documentation continues:

> Within each zone, the location of the erasure-set of drives is determined based on a deterministic hashing algorithm.

This implies that a *subset* of disks is chosen to stripe each object across.  Otherwise, if every object were striped across every available disk, there would be no need for a deterministic hashing algorithm!  (Unless it's just talking about which disks are parity and which are data? But that's stored in the xl.json file)

However, the [storage class](https://github.com/minio/minio/tree/master/docs/erasure/storage-class) documentation doesn't seem to have a way to set a policy for X data plus Y parity.  Rather, a policy like "EC:2" seems to mean "N-2 disks for data, and 2 disks for parity", where N is the *total* number of disks available.

Could you please clarify the apparent contradiction here?  Either a 1024 disk zone *does* use all disks for an object (in which case no deterministic hash is required); or it does not (in which case, some way to select the number of data disks for each object is required)

As a guess, it's possible that minio picks one disk from each server, meaning that in this example the object would be spread across 32 disks - but if so, that doesn't appear to be mentioned anywhere.

There is a separate page on [erasure coding](https://docs.min.io/docs/minio-erasure-code-quickstart-guide) but that doesn't help: it shows a single server with 8 or 12 disks, and implies that all disks on this server are used.

**Comment by candlerb** [comment]
FWIW, I did an empirical test.

First, I created a four-node cluster each with two disks, running each node as follows: [^1]

```
export MINIO_ACCESS_KEY=minioadmin; export MINIO_SECRET_KEY=minioadmin; \
  ./minio server http://minio{1...4}.home.example.net/data{1...2}
```

Uploaded a PDF file: this was distributed across all 8 disks (not just 1 per server)

```
root@minio1:~# ls -l /data?/blah/test.pdf/part.1
-rw-r--r-- 1 root root 230775 Dec 31 14:21 /data1/blah/test.pdf/part.1
-rw-r--r-- 1 root root 230775 Dec 31 14:21 /data2/blah/test.pdf/part.1
```

(The implication is: with 1024 disks, objects would be striped across them all?? But this doesn't explain the need for a "deterministic hashing algorithm")

I then added 2 more disks to each server [^2], and restarted as an expanded cluster with two zones:

```
export MINIO_ACCESS_KEY=minioadmin; export MINIO_SECRET_KEY=minioadmin; \
  ./minio server http://minio{1...4}.home.example.net/data{1...2}
http://minio{1...4}.home.example.net/data{3...4}
```

After uploading the test document 2 more times, all the copies went to the first zone:

```
root@minio1:~# ls -l /data?/blah/
/data1/blah/:
total 12
drwxr-xr-x 2 root root 4096 Dec 31 14:21 test.pdf
drwxr-xr-x 2 root root 4096 Dec 31 14:42 test2.pdf
drwxr-xr-x 2 root root 4096 Dec 31 14:44 test3.pdf

/data2/blah/:
total 12
drwxr-xr-x 2 root root 4096 Dec 31 14:21 test.pdf
drwxr-xr-x 2 root root 4096 Dec 31 14:42 test2.pdf
drwxr-xr-x 2 root root 4096 Dec 31 14:44 test3.pdf

/data3/blah/:
total 0

/data4/blah/:
total 0
```

This could be because of the lxd container environment, which is just using bind mounts onto the same underlying directory, and hence they all appear to be equally full/empty.

```
root@minio1:~# df -k /data?
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/sda2       14287344 10040868   3497676  75% /data1
/dev/sda2       14287344 10040868   3497676  75% /data2
/dev/sda2       14287344 10040868   3497676  75% /data3
/dev/sda2       14287344 10040868   3497676  75% /data4
```

Therefore I can't see what would happen if a file is placed in the second zone, and how it is found - e.g. if some placeholder is created in the first zone.

-----

[^1] I had some lockups in the secondary nodes when starting: they stuck at "Waiting for the first server to format the disks."  Even ^C was unable to stop them; I had to do ^Z and `kill -9 %1` (simple `kill %1` did not work either).  However after restarting them, they came up.

I also had some hangs from "mc du", and looking at tcpdump output on port 9000, I could see a lot of chatter to do with locks and locks failing (403 Forbidden).  I am not planning to investigate this further, as it's looking like distributed mode isn't going to be suitable for my application anyway.

[^2] I first tried adding a single disk to each server.  However this showed up a limitation of distributed mode which is not explicitly documented: all zones must have the same number of disks.

```
# export MINIO_ACCESS_KEY=minioadmin; export MINIO_SECRET_KEY=minioadmin; ./minio server http://minio{1...4}.home.example.net/data{1...2} http://minio{1...4}.home.example.net/data3
ERROR Invalid command line arguments: All zones should have same drive per set ratio - expected 8, got 4
```

I think that does deserve to be documented, as it means that in effect you have to grow in multiples of your initial cluster size.  (e.g. if you have 1024 disks, it might be better initially to configure it initially as four zones of 256 disks; then you can grow in units of 256 disks)

**Comment by harshavardhana** [comment]
All zones doesn't need same number of disks, new zones need to carry same ratio of erasure sets to maintain the original SLA for objects.

You can start with 1024 drives i.e basically 16 drives per erasure set, then you can add in terms of 16 either it's 32, 48, 64...

**Comment by harshavardhana** [comment]
> I also had some hangs from "mc du", and looking at tcpdump output on port 9000, I could see a lot of chatter to do with locks and locks failing (403 Forbidden). I am not planning to investigate this further, as it's looking like distributed mode isn't going to be suitable for my application anyway.

You don't need to worry about that @candlerb those are internal and expected.

**Comment by candlerb** [comment]
Thank you, I didn't see any documentation saying that erasure coding stripes an object over no more than 16 disks.  [erasure code quick-start](https://docs.min.io/docs/minio-erasure-code-quickstart-guide.html) gives *examples* of 8 disk and 12 disk sets.  [storage classes](https://github.com/minio/minio/tree/master/docs/erasure/storage-class) gives an *example* of a 16 disk set.

Now I know to look for the number 16, I found it in `cmd/config/errors.go`:

```
        ErrInvalidErasureSetSize = newErrFn(
                "Invalid erasure set size",
                "Please check the passed value",
                "Erasure set can only accept any of [4, 6, 8, 10, 12, 14, 16] values",
        )
```

which is invoked from `cmd/endpoint-ellipses.go` which expands `n...m`

```
// Supported set sizes this is used to find the optimal
// single set size.
var setSizes = []uint64{4, 6, 8, 10, 12, 14, 16}
...
// isValidSetSize - checks whether given count is a valid set size for erasure coding.
var isValidSetSize = func(count uint64) bool {
        return (count >= setSizes[0] && count <= setSizes[len(setSizes)-1] && count%2 == 0)
}
```

What I *think* it does is to divide your disks into M sets, where each set is the same size, the set size divides exactly into N, and preferring to choose a small number of large sets (e.g. 16 disks => 1 set of 16 (not 2 sets of 8), but 18 disks => 3 sets of 6?)  This is important to know, because it affects the overhead of a storage class like EC:3.

**Comment by harshavardhana** [comment]
The documentation is not part of standard reference.

https://github.com/minio/minio/blob/master/docs/distributed/DESIGN.md

Currently our docs are going through an overhaul which shall make other docs visible as well. It shall happen in coming months.

**Comment by candlerb** [comment]
Thank you, that doc is exactly what I was looking for.  (Also I just tested 18 dirs, and objects *do* get striped across 6).

Regarding line 117 of `docs/distributed/DESIGN.md`:

```
minio server /mnt{1..4}/controller{1...4}/data{1...16}
```

Are you relying on bash expansion of `/mnt{1..4}` here, or should this say `/mnt{1...4}` ?

**Comment by harshavardhana** [comment]
No of course not we don't rely on bash expansion, that is a typo. We rely on our own ellipses syntax.
