### ISSUE TITLE
Minio hangs when insufficient erasure coding parts available

### ISSUE THREAD

**Issue by candlerb** [minio/minio#8721]
When insufficient erasure coding parts are available, minio API hangs instead of returning an error.

## Expected Behavior

```
mc cat minio1/blah/file2.pdf
```

to return with an error.

## Current Behavior

```
mc cat minio1/blah/file2.pdf
```

hangs.

## Possible Solution
?

## Steps to Reproduce (for bugs)
Start a server with 8 data disks:

```
/root/minio server /data1 /data2 /data3 /data4 /data5 /data6 /data7 /data8
```

Upload a file with reduced redundancy (= 6 data 2 parity)

```
$ mc mb minio1/blah
$ mc cp --storage-class REDUCED_REDUNDANCY testfile.pdf minio1/blah/file2.pdf
```

```
root@minio1:~# ls -l /data?/blah/file2.pdf/part.1
-rw-r--r-- 1 root root 153861 Dec 31 13:04 /data1/blah/file2.pdf/part.1
-rw-r--r-- 1 root root 153861 Dec 31 13:04 /data2/blah/file2.pdf/part.1
-rw-r--r-- 1 root root 153861 Dec 31 13:04 /data3/blah/file2.pdf/part.1
-rw-r--r-- 1 root root 153861 Dec 31 13:04 /data4/blah/file2.pdf/part.1
-rw-r--r-- 1 root root 153861 Dec 31 13:04 /data5/blah/file2.pdf/part.1
-rw-r--r-- 1 root root 153861 Dec 31 13:04 /data6/blah/file2.pdf/part.1
-rw-r--r-- 1 root root 153861 Dec 31 13:04 /data7/blah/file2.pdf/part.1
-rw-r--r-- 1 root root 153861 Dec 31 13:04 /data8/blah/file2.pdf/part.1
```

Move two parts out of the way: file can still be retrieved

```
root@minio1:~# mv /data1/blah{,.xxx}
root@minio1:~# mv /data8/blah{,.xxx}

$ mc cat minio1/blah/file2.pdf | wc
    9708   80702  922970
```

Move a third part out of the way, and mc hangs:

```
root@minio1:~# mv /data7/blah{,.xxx}

$ mc cat minio1/blah/file2.pdf | wc
<< hangs >>
```

## Context
I am testing functionality/stability/dependability of erasure coding

## Regression
N/A

## Your Environment
* Version used (`minio --version`): `minio version 2019-12-30T05:45:39Z`
* Environment name and version (e.g. nginx 1.9.1): N/A
* Server type and version: Ubuntu 18.04 lxd container in Ubuntu 18.04 host
* Operating System and version (`uname -a`): `Linux minio1 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Link to your project: N/A

**Comment by harshavardhana** [comment]
It doesn't hang, mc simply keeps retrying.

You can just do mc cat --debug to see this retry.
