### ISSUE TITLE
Documentation: storage usage calculation

### ISSUE THREAD

**Issue by candlerb** [minio/minio#8722]
## Issue

I could not find a description of how minio handles storage usage reporting in the minio documentation.

I believe the following is roughly true - determined by experimentation, looking at old tickets, and source code:

* The web browser interface shows total storage used
* `mc admin info` shows the total number of objects and buckets, and total size used
* Both appear to be using a JSON-RPC call to `/webrpc`, e.g. `Web.StorageInfo`
* There are stats stored on disk in `.minio.sys/background-ops/data-usage`
    * Includes `"bucketsSizes": {"<bucketname>":<size>}` and histogram of object sizes
* The stats are NOT updated when you PUT or DELETE an object or a bucket (#6576)
* The stats are updated by performing a full walk of the filesystem when minio starts, and at 12-hour intervals thereafter
* There is some code to throttle the filesystem walk if there are more than 10 active I/O operations, tested in 100ms intervals

## References

Issue #6576 asks for storage stats to be updated incrementally in response to PUT and DELETE requests, and also mentions the 12 hour gap between filesystem walks.  It includes the response: "I understand we're not going to take this approach. Okay to close this then?" and "Yes we need a different bug with new set of requirements".  However I cannot find the new ticket.

Issue #8280 says "We are planning to add accounting per bucket this is part of the user and usage accounting which is under implementation" - but no reference to a ticket covering this feature.

Issue #8423 asks for the S3 storage inventory API to be provided.

[cmd/data-usage.go](https://github.com/minio/minio/blob/master/cmd/data-usage.go#L31) defines the fixed 12-hour `dataUsageCrawlInterval`

## Possible Solution
Include a page on docs.min.io explaining what minio provides *today* in terms of storage accounting, and how it is kept up to date.

Also create a separate github issue for the planned improvements to storage accounting.

## Context
I am evaluating minio as a front-end to existing NFS servers.  It would have been helpful it were documented what sort of accounting is available, as it would have avoided reverse engineering.

I was hoping to have accounting at the per-bucket level, especially when using federation.

These servers each contain 100-300TB data over 30-90m files.  Walking them periodically will be expensive.

## Regression
N/A

## Your Environment
I have been testing `minio version 2019-12-30T05:45:39Z`, but this issue relates primarily to documentation

**Comment by harshavardhana** [comment]
Yes most definitely we shall fix it @candlerb
