### ISSUE TITLE
Federated bucket migration process

### ISSUE THREAD

**Issue by candlerb** [minio/minio#8723]
**Is your feature request related to a problem? Please describe.**
I would like to be able to move buckets between servers in a federated environment.

Once a bucket has been created, objects continue to be created on the same node: the filesystem may become full, and it may be necessary to move (this or other) buckets to other nodes to free up space.

**Describe the solution you'd like**
The most basic solution is a documented process for moving a bucket manually.  I *think* the following would work:

1. rsync the bucket from source to destination (both `/data/<bucket>/` and `/data/.minio.sys/buckets/<bucket>/`)
2. make the source bucket readonly (e.g. using filesystem perms)
3. re-run rsyncs to pick up any intervening changes
4. update the etcd entry to point to the new host:
    ```
    etcdctl --endpoints=$ENDPOINTS put /skydns/com/example/minio/<bucketname>/x.x.x.x '{"host":"x.x.x.x","port":9000,"ttl":30,"creationDate":"2019-12-31T10:29:00.000000000Z"}'
    # remove old key too?
    ```
5. ensure the directory is R/W on the target, and remove the directory from the source

Does that seem reasonable?  Any steps missing or unexpected side-effects?

**Describe alternatives you've considered**
A more advanced solution would be to include bucket migration as a managed operation, perhaps running as one of the "background-ops".  It could automatically suspend PUT operations during the final part of the transfer.

**Additional context**
N/A

**Comment by harshavardhana** [comment]
This has been part of the plan as `mc admin` operation in the future, where we plan to support bucket migration or decommissioning a cluster.

**Comment by candlerb** [comment]
Thanks.  As stop-gap, do you think process as described above is sufficient?
