### ISSUE TITLE
New directories not picked up in federated server

### ISSUE THREAD

**Issue by candlerb** [minio/minio#8724]
This is not exactly a bug, but an inconvenient situation you can get into.

## Steps to Reproduce

* Create a federated cluster (e.g. minio1 and minio2)
* After the cluster is running, manually create a new bucket directory on one of the nodes, directly in its data directory.

```
root@minio1:~# mkdir /data/qux1; echo test >/data/qux1/test
```

This newly-created directory is not visible on either node.  This is reasonable, given that there's no etcd mapping for it.

```
$ mc du minio1
5B	bar
5B	baz
13B	foo
23B
$ mc du minio2
5B	bar
5B	baz
13B	foo
23B
$ mc cat minio1/qux1/test
mc: <ERROR> Unable to read from `minio1/qux1/test`. The specified bucket does not exist.
$ mc cat minio2/qux1/test
mc: <ERROR> Unable to read from `minio2/qux1/test`. The specified bucket does not exist.
```

However, you can no longer *create* the bucket either:

```
$ mc mb minio1/qux1
mc: <ERROR> Unable to make bucket `minio1/qux1`. Your previous request to create the named bucket succeeded and you already own it.
$ mc cat minio1/qux1/test
mc: <ERROR> Unable to read from `minio1/qux1/test`. The specified bucket does not exist.
```

This leaves you in the strange situation where `mc mb` tells you the bucket already exists and you already own it, but when you try to use it, you can't!

## Expected Behavior
I would like to be able to access the bucket.

## Current Behavior
See above.  However the data *does* become available if you restart minio, since that walks the buckets again.

To avoid restarting minio, you can create the etcd entry manually using `etcdctl`, if you know what you're doing:

```
etcdctl --endpoints=$ENDPOINTS put /skydns/com/example/minio/qux1/x.x.x.x '{"host":"x.x.x.x","port":9000,"ttl":30,"creationDate":"2019-12-31T10:29:00.000000000Z"}'
```

(probably best done by copying the existing entry for another bucket on the same host)

## Possible Solution
One option is for *any* object access to a bucket which does not exist (according to etcd) to fall back to checking for the bucket on the filesystem - and if found, create the etcd entry.  This is the most user-friendly, but adds an extra filesystem access.

Another option is for PUT a bucket in federated mode for it to check whether the etcd entry exists, and if not, create it.  This would allow "mc mb" to the correct node to fix the problem.

## Context
I am looking to migrate applications from NFS to S3.  During the parallel running period, some older applications may still create directories on NFS, but I want them to be visible to S3 clients.

## Regression
N/A

## Your Environment
* Version used (`minio --version`): `minio version 2019-12-30T05:45:39Z`

**Comment by harshavardhana** [comment]
Adding data to backend in this manner is unexpected @candlerb 

We can't support these type of situations.

**Comment by harshavardhana** [comment]
Also if you restart the server after the server has started when the new directories are created they get populated on etcd.
