### ISSUE TITLE
Plugins / Modules API

### ISSUE THREAD

**Issue by JonathanWilbur** [minio/minio#8725]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
An API for implementing modules / plugins.

**Comment by JonathanWilbur** [comment]
Specifically, I would like the ability to intercept files while they are being downloaded and modify them.

**Comment by harshavardhana** [comment]
This is out of scope for MinIO, fork MinIO and do it in your fork.
