### ISSUE TITLE
static website support (autoindex ability)

### ISSUE THREAD

**Issue by vtolstov** [minio/minio#8729]
Please, add some option to sa that bucket is the static website with autoindex. So when i'm query aaa/b/ path and aaa/b/ contains some files, minio returns it via autoindex with urls to files.

**Comment by harshavardhana** [comment]
This is out of scope for MinIO you may use https://github.com/harshavardhana/s3www

**Comment by vtolstov** [comment]
i don't want to get this in core minio server. But if minio has ability to support some metadata for bucket, this can be easy added via notification system. So you put something like static-site meta label. When somebody upload to bucket new object webhook fired with metadata. And i can easy generate index file based on this data in needed bucket.
What you think?
