### ISSUE TITLE
How to re balance minio data?

### ISSUE THREAD

**Issue by harshul4274** [minio/minio#8731]
Hello i create a 4 minio pod in kubernetes as a  store data in host but a one pod are delete and host data also delete. Now i up a lost pod but actually i don't know how to rebalance data and how to store a lost  host data when pod and host data delete.

**Comment by nitisht** [comment]
you can use the `mc heal` command as documented here https://docs.min.io/docs/minio-admin-complete-guide.html#heal to recreate the data lost on one of the pods. Alternatively, you can wait for MinIO to auto-heal as well. 

Closing this as answered, please join us on Slack (https://slack.min.io) for more such questions

**Comment by harshul4274** [comment]
Thanks @nitisht for share instruction now i can solve this issue with below command. 
Only two command need to data rebalance.
mc config host add ALIAS_NAME YOUR-MINIO-ENDPOINT YOUR-ACCESS-KEY YOUR-SECRET-KEY
mc admin heal --recursive ALIAS_NAME

**Comment by harshul4274** [comment]
mc config host add <ALIAS> <YOUR-MINIO-ENDPOINT> <YOUR-ACCESS-KEY> <YOUR-SECRET-KEY>

**Comment by harshul4274** [comment]
Only two command need to data rebalance.<br>mc config host add ALIAS_NAME YOUR-MINIO-ENDPOINT YOUR-ACCESS-KEY YOUR-SECRET-KEY
./mc.RELEASE.2019-12-17T23-26-28Z admin heal --recursive ALIAS_NAME
