### ISSUE TITLE
When using mc client upload file, shut down one sever eth0 in four distribution minio server, the uploaded time is too long which is 15mins for 100M file.

### ISSUE THREAD

**Issue by enayzhu** [minio/minio#8732]
Hi，
My testbed is distribution mode which has 4 minio servers located different 4 work nodes. 
Using mc client doing upload 100M file takes time should be about 2s which is supposed to be normal. 
while in our test when one server eth0 was down, it took nearly 15mins which is not reasonable.

## Expected Behavior
Expected result is deliver time should be reasonable rather than 15 mins for only 100M file.

## Current Behavior
During the file being uploaded, shut down one server's eth0, the upload time is about 15 mins.

## Possible Solution
We checked the print logs and found that at the beginning there were 4 disks. And then it changed to 3 disks due to one server eth0 down.
however, the server had no reaction until 15mins later putObject failed.
Then the server recalled putObject, this time it re-detected the disk number is 3. So it delivered the file from start and it took 2S to finish successfully.
So from the user perspect, it totally took 15 mins to deliver 100M size files. It was not reasonable.

## Steps to Reproduce (for bugs)
1. get into client container and use mc command to add mc client and create mc bucket.
2. using mc cp to upload a file to server. during the file uploading, login one work node to shut down one server eth0.  
command is "nsenter -t `docker inspect -f <pid> <container-id>` -n ip link set eth0 down". 
using command "ps -ef " get <pid> 
using command "docker ps" get <container-id>

## Context
According to the description of the official document, I think the service should be able to be provided normally at this time

## Your Environment
minio server code version : RELEASE.2019-09-11T19-53-16Z
mc version : latest

**Comment by enayzhu** [comment]
Hi kannappanr  and vadmeste,
I checked the code of minio server and did some test by myself, and here's my finding:
I found that in process NewClient from client.go, the httpClient part of the return struct Client didn't set Timeout.
As the document said, Timeout=0 means no timeout.

In this case, it will follow system kernel parameter'tcp_retries2', which is 15 by default.
When it is 15, the timeout is around 15 minutes and when I change it to 10, the timeout is around 7 minutes.

If i set Timeout in httpClient from above to 3 minutes and tcp_retries2 is 15 as default, the timeout is 3min15seconds.

Hopefully these can help you.

**Comment by harshavardhana** [comment]
We cannot set arbitrary timeouts like this @enayzhu because Go treats it like a connection timeout. Leading to situation where large data transfers get timeout prematurely.

If you wish for kernel to timeout keep alives quickly you have to set the keep alive probes number appropriately. 

Also turning off eth0 is not equivalent of an interface dying or network turned off. Turning off eth0 Linux kernel has a different behavior as seen by you.

**Comment by enayzhu** [comment]
Hi harshavardhana，
The previous test method was modified. During the process of uploading the file, a node running by the server was shut down, and the results were consistent with the previous.
I would like to ask if there are any relevant cases in the test of the minio server. During the file upload process, there is a server that cannot provide services. What is the behavior at this time? Looking forward to your reply，thanks.

**Comment by vadmeste** [comment]
@enayzhu MinIO cluster can recover quickly when the OS says that it cannot reach the killed server. 

@harshavardhana the default timeout for rest calls is 1 minute. I am not sure why we have this 15 minutes. I will investigate this.

Also we probably can check if we can shorten tcp dial timeout which is also 1 minute. Probably, the kernel accepts connections quickly even if the server has a high load usage.

**Comment by harshavardhana** [comment]
@vadmeste the issue here is that eth0 going down is a keep-alive timeout

**Comment by enayzhu** [comment]
@vadmeste I understand that a Minio server can restart if it's in normal state, but it won't restart when the node in the system can't meet its starting demands, and we'll meet the situations in my test before.

@harshavardhana I don't think this is a keep-alive timeout. Because the keep-alive timeout is used when the connection is free, but my current situation is a server crashed while transmitting some data. In this case, a re-transmit is triggered. The re-transmit time is influenced by linux kernel parameter "tcp-retries2". By default it will cost 15 mins in my environment, and I have tried to make tcp_retries2 smaller, and the blocking time is shorter.

These are my analyze and hopefully can help you investigate it.

**Comment by enayzhu** [comment]
Hi vadmeste，
Is there any progress on this issue?
Are there related tests in your test case, and what is the final behavior? Can you share it with me？Looking forward to your reply，thanks.

**Comment by ewagkun** [comment]
@vadmeste, @harshavardhana
Thanks for the support and discussion. 
I think this is exactly the node shutdown case. In case the setup is by physical nodes, and one node is shutdown while a file is under transmission.  Or for VM setup, one VM is shutdown during the file transmission.  Is there any observation that the uploading file transfer time is quite long(~ 15 mins) in above cases ?
