### ISSUE TITLE
Problem with URL Signed Requests in Minio

### ISSUE THREAD

**Issue by Reza-Noei** [minio/minio#8734]
Im using AmazonS3 .NET SDK to generate a url signed requests.

> My amazon s3 nuget package is AWSSDK version 2.3.55.2

here is our sample code: 

     class AmazonTest
     {
         public static string GetTextContents(string path)
         {
             HttpWebRequest request = HttpWebRequest.Create(path) as HttpWebRequest;
             HttpWebResponse response = request.GetResponse() as HttpWebResponse;
             using (Stream stream = response.GetResponseStream())
             using (StreamReader reader = new StreamReader(stream))
             {
                 return reader.ReadToEnd();
             }
     }

     public static string GetPreSigned(AmazonS3Client client, string bucket, string key)
     {
             // Create a CopyObject request
             GetPreSignedUrlRequest request = new GetPreSignedUrlRequest
             {
                 BucketName = bucket,
                 Key = key,
                 Expires = DateTime.Now.AddMinutes(50),
                 Protocol = Protocol.HTTP
             };
             // Get path for request
             return client.GetPreSignedURL(request);            
     }

and here is our usage: 

            var config = new AmazonS3Config
            {
                RegionEndpoint = RegionEndpoint.USEast1, // MUST set this before setting ServiceURL and it should match the `MINIO_REGION` enviroment variable.
                ServiceURL = S3Endpoint, // replace http://localhost:9000 with URL of your MinIO server
                ForcePathStyle = true, // MUST be true to work correctly with MinIO server                           
            };
            var amazonS3Client = new AmazonS3Client("reza", "123456", config);

            var url = AmazonTest.GetPreSigned(amazonS3Client, "organizations", "Equation.txt");
            var Content = AmazonTest.GetTextContents(url);

Minio returns a Forbidden (403) exception. which says: 

     <Error>
     <Code>SignatureDoesNotMatch</Code>
     <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
     <Key>Equation.txt</Key>
     <BucketName>organizations</BucketName>
     <Resource>/organizations/Equation.txt</Resource> 
     <RequestId>15E615B7B7C44B10</RequestId>
     <HostId>2858b804-0459-43c9-b74b-091ee53a1563</HostId>
     </Error>

**Comment by kannappanr** [comment]
@Reza-Noei Can you please upgrade to newer versions of AWS SDK. I tried your code with version `3.3.24.1` and it worked fine. With the newer version, here is a sample presigned URL

```curl -i "http://play.min.io/lll/issue?AWSAccessKeyId=minio&Expires=1578446863&Signature=LaQvrv%2BGHOon3d%2Fpd1DVeRY6s7c%3D"
```

Here is the code that I tried

```
﻿using System;
using Amazon;
using Amazon.S3;
using Amazon.S3.Model;

namespace ConsoleApp17
{
    class Program
    {

	public static string GetPreSigned(AmazonS3Client client, string bucket, string key)
 	{
         // Create a CopyObject request
         GetPreSignedUrlRequest request = new GetPreSignedUrlRequest
         {
             BucketName = bucket,
             Key = key,
             Expires = DateTime.Now.AddMinutes(7000),
             Protocol = Protocol.HTTP
         };
         // Get path for request
         return client.GetPreSignedURL(request);            
 	}


        static void Main(string[] args)
        {
			var config = new AmazonS3Config
			{
				RegionEndpoint = RegionEndpoint.USEast1,
				ServiceURL = "http://play.min.io",
				ForcePathStyle = true,
			};
			var amazonS3Client = new AmazonS3Client("minio", "minio123", config);

        		var url = Program.GetPreSigned(amazonS3Client, "lll", "issue");
			Console.WriteLine(url);
        }
    }
}
```

**Comment by harshavardhana** [comment]
Closing as per https://github.com/minio/minio/issues/8734#issuecomment-570463540
