### ISSUE TITLE
Get XMinioUnknownAPIRequest Unknown API Request error using MinIO Python API

### ISSUE THREAD

**Issue by hossein-kshvrz** [minio/minio#8746]
I am using **Python API** to connect to MinIO, but I get **Unknown API Request** error.

## Expected Behavior
I want to make buckets and upload selected files into a specific bucket via a Python script. The script is like the one on [Python Client API Reference page](https://docs.min.io/docs/python-client-api-reference.html), and it is included in reproduction steps section.

## Current Behavior
I constantly get the following error, no matter MinIO is running on Docker, or without Docker on Ubuntu server:
`minio.error.ResponseError: ResponseError: code: XMinioUnknownAPIRequest, message: Unknown API request at //maylogs/, bucket_name: maylogs`

## Possible Solution
Have no idea!

## Steps to Reproduce (for bugs)
1. Run MinIO on Docker or using the tutorial on quick start page [here](https://docs.min.io/docs/minio-quickstart-guide.html).
2. Execute the following Python code:
```from minio import Minio
from minio.error import (ResponseError, BucketAlreadyOwnedByYou,
                         BucketAlreadyExists)

# Initialize minioClient with an endpoint and access/secret keys.
minioClient = Minio('127.0.0.1:9000/',
                    access_key='minioadmin',
                    secret_key='minioadmin',
                    secure=False)

# Make a bucket with the make_bucket API call.
try:
       minioClient.make_bucket("maylogs")
except BucketAlreadyOwnedByYou as err:
       pass
except BucketAlreadyExists as err:
       pass
except ResponseError as err:
       raise

# Put an object 'pumaserver_debug.log' with contents from 'pumaserver_debug.log'.
try:
       minioClient.fput_object('maylogs', 'test.py', 'test.py')
except ResponseError as err:
       print(err)
```
This code was used when I ran without Docker.

## Your Environment

* Version used (`2020-01-03T19:12:21Z` and `minio:RELEASE.2020-01-03T19-12-21Z` Docker image):
* Operating System and version (`Ubuntu 18:04` and `Ubuntu 16:04`):

**Comment by harshavardhana** [comment]
@hossein-kshvrz remove the extra `/` in the endpoint value

```
# Initialize minioClient with an endpoint and access/secret keys.
minioClient = Minio('127.0.0.1:9000',
                    access_key='minioadmin',
                    secret_key='minioadmin',
                    secure=False)
```

**Comment by hossein-kshvrz** [comment]
Yes. Thanks. It worked -__-
