### ISSUE TITLE
Use of MINIO_ERASURE_SET_DRIVE_COUNT

### ISSUE THREAD

**Issue by candlerb** [minio/minio#8750]
This is probably my lack of understanding of how it's intended to be used, but MINIO_ERASURE_SET_DRIVE_COUNT does not appear to have any effect in either distributed or EC mode.

## Test case

(1) Distributed mode

```
root@minio1:~# MINIO_ERASURE_SET_DRIVE_COUNT=4 ./minio server http://minio1/ec/{1...8}
Attempting encryption of all config, IAM users and policies on MinIO backend
...
```

```
$ mc mb minio1/foo
$ mc cp test.pdf minio1/foo/f1.pdf
```

(2) Single server EC mode

```
root@minio1:~# MINIO_ERASURE_SET_DRIVE_COUNT=4 ./minio server /ec/1 /ec/2 /ec/3 /ec/4 /ec/5 /ec/6 /ec/7 /ec/8
Attempting encryption of all config, IAM users and policies on MinIO backend
...
```

```
$ mc mb minio1/foo
$ mc cp test.pdf minio1/foo/f1.pdf
```

## Expected Behavior

I expected the 8 disks to be treated as two EC sets of 4 disks.

## Current Behavior

What I see in both cases is that the uploaded file is broken into 8 EC parts, as if MINIO_ERASURE_SET_DRIVE_COUNT were unset.

```
root@minio1:~# ls -l /ec/*/foo/f1.pdf
/ec/1/foo/f1.pdf:
total 232
-rw-r--r-- 1 root root 230775 Jan  5 21:07 part.1
-rw-r--r-- 1 root root    583 Jan  5 21:07 xl.json

/ec/2/foo/f1.pdf:
total 232
-rw-r--r-- 1 root root 230775 Jan  5 21:07 part.1
-rw-r--r-- 1 root root    583 Jan  5 21:07 xl.json

/ec/3/foo/f1.pdf:
total 232
-rw-r--r-- 1 root root 230775 Jan  5 21:07 part.1
-rw-r--r-- 1 root root    583 Jan  5 21:07 xl.json

/ec/4/foo/f1.pdf:
total 232
-rw-r--r-- 1 root root 230775 Jan  5 21:07 part.1
-rw-r--r-- 1 root root    583 Jan  5 21:07 xl.json

/ec/5/foo/f1.pdf:
total 232
-rw-r--r-- 1 root root 230775 Jan  5 21:07 part.1
-rw-r--r-- 1 root root    583 Jan  5 21:07 xl.json

/ec/6/foo/f1.pdf:
total 232
-rw-r--r-- 1 root root 230775 Jan  5 21:07 part.1
-rw-r--r-- 1 root root    583 Jan  5 21:07 xl.json

/ec/7/foo/f1.pdf:
total 232
-rw-r--r-- 1 root root 230775 Jan  5 21:07 part.1
-rw-r--r-- 1 root root    583 Jan  5 21:07 xl.json

/ec/8/foo/f1.pdf:
total 232
-rw-r--r-- 1 root root 230775 Jan  5 21:07 part.1
-rw-r--r-- 1 root root    583 Jan  5 21:07 xl.json
```

## Possible Solution
?

## Steps to Reproduce (for bugs)
See above

## Context
Based on #6768, I also tried:

```
root@minio1:~# MINIO_ERASURE_SET_DRIVE_COUNT=4 MINIO_ENDPOINTS="/ec/1 /ec/2 /ec/3 /ec/4 /ec/5 /ec/6 /ec/7 /ec/8" ./minio server
```

But got the same result.

## Your Environment
* Version used (`minio --version`): `minio version RELEASE.2020-01-03T19-12-21Z`
* Server type and version: Ubuntu 18.04

**Comment by xrzhao** [comment]
bug is in the endpoint-ellipses.go, in which customSetDriveCount  is shadowed by  local variable in if block of following function:

```go
func GetAllSets(args ...string) ([][]string, error) {
    var customSetDriveCount uint64
    if v := env.Get("MINIO_ERASURE_SET_DRIVE_COUNT", ""); v != "" {
        customSetDriveCount, err := strconv.ParseUint(v, 10, 64)
        if err != nil {
            return nil, config.ErrInvalidErasureSetSize(err)
        }   
        if !isValidSetSize(customSetDriveCount) {
            return nil, config.ErrInvalidErasureSetSize(nil)
        }   
    }
    ...
}
```

should fix to:

```go
func GetAllSets(args ...string) ([][]string, error) {
    var customSetDriveCount uint64
    var err error
    if v := env.Get("MINIO_ERASURE_SET_DRIVE_COUNT", ""); v != "" {
        customSetDriveCount, err = strconv.ParseUint(v, 10, 64) 
        if err != nil {
            return nil, config.ErrInvalidErasureSetSize(err)
        }   
        if !isValidSetSize(customSetDriveCount) {
            return nil, config.ErrInvalidErasureSetSize(nil)
        }   
    }   
    ....
}
```

**Comment by xrzhao** [comment]
bug is in the endpoint-ellipses.go, in which customSetDriveCount  is shadowed by  local variable in if block of following function:

func GetAllSets(args ...string) ([][]string, error) {
    var customSetDriveCount uint64
    if v := env.Get("MINIO_ERASURE_SET_DRIVE_COUNT", ""); v != "" {
        customSetDriveCount, err := strconv.ParseUint(v, 10, 64)
        if err != nil {
            return nil, config.ErrInvalidErasureSetSize(err)
        }   
        if !isValidSetSize(customSetDriveCount) {
            return nil, config.ErrInvalidErasureSetSize(nil)
        }   
    }
    ...
}

should fix to:

func GetAllSets(args ...string) ([][]string, error) {
    var customSetDriveCount uint64
    var err error
    if v := env.Get("MINIO_ERASURE_SET_DRIVE_COUNT", ""); v != "" {
        customSetDriveCount, err = strconv.ParseUint(v, 10, 64) 
        if err != nil {
            return nil, config.ErrInvalidErasureSetSize(err)
        }   
        if !isValidSetSize(customSetDriveCount) {
            return nil, config.ErrInvalidErasureSetSize(nil)
        }   
    }   
    ....
}

**Comment by harshavardhana** [comment]
@xrzhao there is already a PR to fix this.
