### ISSUE TITLE
All users other than 'Admin' unable to use list_buckets() python API

### ISSUE THREAD

**Issue by pransen** [minio/minio#8756]
I have a user with the following canned policy:

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:ListAllMyBuckets",
        "s3:ListBucket",
        "s3:PutObject",
        "s3:GetObject",
        "s3:DeleteObject",
        "s3:GetBucketLocation",
        "s3:GetBucketPolicy"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::data/*",
        "arn:aws:s3:::data"
      ],
      "Sid": "Public"
    }
  ]
}

The bucket 'data' is created but when I try to list it using the login credentials of this particular user, I get the following error:

Traceback (most recent call last):
  File "C:/Users/User123/PycharmProjects/minio/minio_client.py", line 103, in <module>
    for bucket in client.list_buckets():
  File "C:/Users/User123/PycharmProjects/minio/minio_client.py", line 42, in list_buckets
    return self._minio_client.list_buckets()
  File "C:\Users\User123\AppData\Local\Programs\Python\Python36\lib\site-packages\minio\api.py", line 385, in list_buckets
    raise ResponseError(response, method).get_exception()
minio.error.AccessDenied: AccessDenied: message: Access Denied

Not sure if I did something wrong or this itself is a bug.

**Comment by nitisht** [comment]
can you paste sample code as reproducer @pransen , also what is you MinIO version

**Comment by Praveenrajmani** [comment]
@pransen The Resource defined is bound to the bucket `data`.. Can you change that to `*` for the list buckets to work

**Comment by pransen** [comment]
@nitisht @Praveenrajmani 

I am using the docker image for MinIO. I guess it should be the latest stable version.

On changing the bucket from 'data' to *, it lists all the buckets present.

My objective is to have one bucket (or multiple buckets with others not having access to it) per user and when I create a python MinIO client using the user's **_access_** and **_secret_** keys and call the API **_list_buckets()_** on it, it should be able to return the name of the buckets which are assigned to that particular user.

**Note** It works fine on the browser where I can see only the buckets assigned for a particular user. However, from python client it either lists everything if I go by @Praveenrajmani 's  suggestions or Access Denied if i use the policy as mentioned in my policy.json.

**Comment by Praveenrajmani** [comment]
@pransen  You should use `${aws:username}` in the resource definition for such usecases. Where an user can only access the buckets which have the same name as that of the user's name.

An example will be 
 
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "*"
        ]
      },
      "Action": [
        "s3:GetBucketLocation",
        "s3:ListBucket",
        "s3:ListBucketMultipartUploads"
      ],
      "Resource": [
        "arn:aws:s3:::${aws:username}"
      ]
    },
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "*"
        ]
      },
      "Action": [
        "s3:AbortMultipartUpload",
        "s3:DeleteObject",
        "s3:GetObject",
        "s3:ListMultipartUploadParts",
        "s3:PutObject"
      ],
      "Resource": [
        "arn:aws:s3:::${aws:username}/*"
      ]
    }
  ]
}
```

**Comment by Praveenrajmani** [comment]
https://aws.amazon.com/blogs/security/writing-iam-policies-grant-access-to-user-specific-folders-in-an-amazon-s3-bucket/

**Comment by pransen** [comment]
@Praveenrajmani thanks. Will check this out

**Comment by harshavardhana** [comment]
Closing this as resolved for now, feel free to update if this isn't resolved.
