### ISSUE TITLE
【Question】max disks support per minio 

### ISSUE THREAD

**Issue by SnowfallDan** [minio/minio#8758]
Hi

The challenge I am currently facing is how to solve the storage of 4pb data.I found that minio supports me to do this job.
We use JBOD with EMC 80 disks, each disk has 12T capacity. Four JBODs can fulfill the demand of 4pb.

I am facing the problem of how to deploy it using minio.
I read the minio's documentation in detail and found that a single minio service only supports up to 16 disk mounts.

Q:
1. Does this mean I need 20 minio services? [(80 disks per jbod * 4) / 16 = 20 minio servers] 
If required, can 20 minio be deployed through virtualization.

2. I read a Chinese document describing that mino supports very large bucket. But can't find English version. Document's name is minio-large-bucket-support-quickstart-guide in english. 
https://docs.min.io/cn/minio-large-bucket-support-quickstart-guide.html
This document introduces that minio can break the limit of 16 disks. Whether the content of this document is true. Can you hurry to provide the English version and enrich the content in the document.

3. If the actual storage usage is 4pb, does that mean I need 8pd disks? This means I need to double the number of jbod and disks I purchase. The cost is too high for me. Is there a compromise?

Recommendation: Minio should provide some real customers' deployment methods and performance indicators after use, which is convenient for new users to use and reference

Ths :)

**Comment by nitisht** [comment]
> I read the minio's documentation in detail and found that a single minio service only supports up to 16 disk mounts.

Where do you see this @SnowfallDan, this is not correct. MinIO doesn't impose a limit on number of disk mounts per server or total number of servers in a deployment.

**Comment by kannappanr** [comment]
@SnowfallDan 
Here are the answers to your questions
1. `16` is the max size of `Erasure Set` meaning an object cannot exist in more than 16 disks. You can have as many numbers of disks as you want.
2. MinIO never had a limit of 16 disks. Documentation in English will be the updated one.
3. If the actual storage is 4 pb, then you can use `EC:2` and the required storage can be `4.57 PB` and if you use `5PB` you should be covered. If you plan to use `EC:4`, then the required storage will be `5.33 PB` so if you use around `5.75 PB` you should be good.

You can look at our benchmark numbers here https://blog.min.io/tag/benchmarks/

**Comment by harshavardhana** [comment]
https://blog.min.io/relaxing-the-32-node-restriction-on-minio/ you may also want to read this @SnowfallDan

**Comment by SnowfallDan** [comment]
@harshavardhana @kannappanr @klingtnet 
Thank you for your replies, so it seems that I only need to use 4 servers, each server is connected to a 84-bay JBOD, each disk is 12T. Install one minio mount 84 disks per server. This will meet my needs, right? And does minio support multipath and how
Or do you have a more recommended deployment method?

**Comment by harshavardhana** [comment]
MinIO just wants mount points i.e it's a directory on the host, MinIO doesn't use the raw disks directly you format it with XFS, mount it and rest of the setup is straight forward

**Comment by SnowfallDan** [comment]
@harshavardhana Thank you for your reply. I understand what you mean by mount point.
In a single tenant usage scenario, I have 320 disks, if formatted into 320 mount points respectively. Then use a minio to mount all mount points. Is this solution feasible? What are the reasons and risks of failure? Is there a recommended deployment method? I am now confused about how 320 disks are arranged and used, and how many minio services should be used for mounting. My question is very specific and I look forward to answering it.

**Comment by klauspost** [comment]
If 80 of your disks are mounted on each server as `/export1`, `/export2`, etc, you can link up your cluster with `minio server http://host{1...4}/export{1...80}` assuming your hosts are named `host1`, `host2`, etc. This can also be IP addresses.

Assuming you have set `MINIO_STORAGE_CLASS_xxxx` to your needs this should create and link up your cluster. It should be pretty easy to experiment. If something ends up not working you can just reformat the drives and start over.

**Comment by SnowfallDan** [comment]
@klauspost Thx!
