### ISSUE TITLE
backup file truncated after turning on retention policy

### ISSUE THREAD

**Issue by andypeng2015** [minio/minio#8761]
Not sure if this is normal, but after I turn on the retention via the mc cmd below, the backup file got truncated to smaller size, initially it's all full backup with MegaBytes, now it's only KBytes.

And is there any configure in operator to set the default bucket policy to none? thanks.

```
mc retention mysql/mysql-backup/xtrabackup.gz compliance 7d
```

<img width="959" alt="Screenshot 2020-01-07 at 10 57 07 AM" src="https://user-images.githubusercontent.com/24508594/71865006-7e00c580-313c-11ea-9371-8e9725022b19.png">

**Comment by andypeng2015** [comment]
@harshavardhana I only need to keep the backup for last few days, so I enable the retention policy, but now I observe the file size become smaller, not sure whether it's related to the retention policy I enabled because the last update date is all 6th Jan

**Comment by harshavardhana** [comment]
That is not called retention @andypeng2015 - you are doing it wrong. What you need is lifecycle policy, retention is to enable WORM policy and now you can't unset it until 5days before you can delete these objects.

**Comment by harshavardhana** [comment]
Filesize becoming smaller is also not MinIO issue, you need to check your backups if they are uploading the correct data to MinIO because MinIO won't automatically create small objects.

**Comment by andypeng2015** [comment]
@harshavardhana thanks for the clarification, so the lifecycle policy is not available in mc? not able to find it in mc cmd. how do I delete the retention config via mc? thanks

**Comment by harshavardhana** [comment]
No it is not @andypeng2015 https://github.com/minio/minio/tree/master/docs/lifecycle check here - you can't delete retention config just like that you need to wait for 7days because you enabled compliance mode.

**Comment by andypeng2015** [comment]
I see, so I need to install aws cli to configure the lifecycle policy?

for the retention config, what happen if I run mc cmd to set it to 1day again? I am abe to edit it after 1 day?

**Comment by andypeng2015** [comment]
> That is not called retention @andypeng2015 - you are doing it wrong. What you need is lifecycle policy, retention is to enable WORM policy and now you can't unset it until 5days before you can delete these objects.

@harshavardhana but I can delete the backup files now, I just cannot rewrite the backup?

**Comment by harshavardhana** [comment]
Yes because you have set retention also on an incorrect prefix, you cannot reset retention you can only extend it.

**Comment by harshavardhana** [comment]
Come to our slack we will help you https://slack.min.io
