### ISSUE TITLE
Commit c38ada1 (08/23/2019) regresses distributed MinIO read speed by 90%

### ISSUE THREAD

**Issue by svasilevskiy** [minio/minio#8765]
Commit https://github.com/minio/minio/commit/c38ada1a2665033f9a2a4d8365ddb256c0dc0e1a  regresses cluster read speed by 90+%. The regression is reproducible in the latest MinIO Dec 2019 releases.

Server setup: a four-node MinIO cluster with one disk/node (four disks total). Disks are mountpoints on a single SAN, which is connected to the MinIO nodes and the client (benchmark) node by 25Gbps network link.

Benchmark setup: minio/s3-benchmark tool run from a separate client host against one of the MinIO hosts with the following parameters: -d 30 -z 10M -t 60.

MinIO and benchmark client hosts are dual-socket servers with 40 physical cores/server. "uname -s -r -v" output:
Linux 3.10.0-1062.7.1.el7.x86_64 #1 SMP Mon Dec 2 17:33:29 UTC 2019

## Expected Behavior

Build MinIO up to commit 48bc3f1 (GO111MODULE=on go get github.com/minio/minio@48bc3f1), which immediately precedes commit c38ada1.
Start MinIO cluster on four server nodes.
Run the s3-benchmark:
S3 benchmark program v3.0
Wed, 18 Dec 2019 15:45:57 GMT Loop 1: PUT time 30.9 secs, objects = 3329, speed = 1.1GB/sec, 107.9 operations/sec.
Wed, 18 Dec 2019 15:46:27 GMT Loop 1: GET time 30.1 secs, objects = 8778, speed = **2.8GB/sec**, 291.5 operations/sec.

## Current Behavior

Build MinIO up to commit c38ada1 (GO111MODULE=on go get github.com/minio/minio@c38ada1)
Start MinIO cluster on four server nodes.
Run the s3-benchmark:
S3 benchmark program v3.0
Wed, 18 Dec 2019 17:12:36 GMT Loop 1: PUT time 30.6 secs, objects = 3413, speed = 1.1GB/sec, 111.5 operations/sec.
Wed, 18 Dec 2019 17:13:13 GMT Loop 1: GET time 37.2 secs, objects = 864, speed = **232MB/sec**, 23.2 operations/sec.

The GET speed went down from 2.8GB/sec to 232MB/sec (by 92%). The slowdown reproduces in the latest MinIO builds.
 
## Possible Solution

Not a solution, but changing the readBlockSize back to 32KiB in the offending commit does not fix the read speed. There is other logic in c38ada1 that I haven't tried changing.

Playing with different request sizes affects the regression percentage. With 1MB requests (-z 1M) the read speed is 1.4GB/sec. With 512KB requests (-z 512K) the read speed is 689.6MB/sec. With 2MB requests (-z 2M) the read speed is 302.5MB/sec.
## Steps to Reproduce (for bugs)

1. Build MinIO with commit 48bc3f1 (last good) and c38ada1 (first bad).
2. Setup distributed cluster (four nodes, one disk/node).
3. Run minio/s3-benchmark with "-d 30 -z 10M -t 60"
4.

## Context

Slow performance prevents us from using MinIO.
## Regression

https://github.com/minio/minio/commit/c38ada1a2665033f9a2a4d8365ddb256c0dc0e1a
"write() to disk in 4MB blocks for better performance"
## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

See summary above.

**Comment by harshavardhana** [comment]
@svasilevskiy have you tried latest master?

**Comment by harshavardhana** [comment]
https://github.com/minio/warp can you try warp instead to get the numbers? also are the numbers same with latest released binary as well? also what is your backend filesystem here?  can you provide all of that information.

**Comment by svasilevskiy** [comment]
The latest release is still slow. Here are the numbers from RELEASE.2020-01-03T19-12-21Z binary:
S3 benchmark program v3.0
Tue, 07 Jan 2020 23:36:33 GMT Loop 1: PUT time 30.2 secs, objects = 3094, speed = 1GB/sec, 102.4 operations/sec.
Tue, 07 Jan 2020 23:37:07 GMT Loop 1: GET time 34.0 secs, objects = 435, speed = **128.1MB/sec**, 12.8 operations/sec.

Filesystem type from "stat -f":
Type: xfs
Block size: 4096       Fundamental block size: 4096

minio/warp read speed numbers are also slow; here is a run on RELEASE.2020-01-03T19-12-21Z:
```
./warp get  -obj.size 10M -duration 30s -concurrent 60
warp: Preparing server.
warp: Creating Bucket "warp-benchmark-bucket"...
warp: Uploading 2500 Objects of Random data; 10485760 bytes total, 10485760 byte buffer
┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 26s

warp: Starting benchmark in 1s ...
 00m30s / 00m30s ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 31s

warp: Benchmark data written to "warp-get-2020-01-07[235624]-DIlB.csv.zst"
-------------------
Operation: PUT. Concurrency: 60. Hosts: 1.
* Average: 973.79 MB/s, 97.38 obj/s, 96.47 ops ended/s (24.256s)

Aggregated Throughput, split into 24 x 1s time segments:
 * Fastest: 1034.18 MB/s, 103.42 obj/s, 82.00 ops ended/s (1s)
 * 50% Median: 977.20 MB/s, 97.72 obj/s, 100.00 ops ended/s (1s)
 * Slowest: 915.99 MB/s, 91.60 obj/s, 119.00 ops ended/s (1s)
-------------------
Operation: GET. Concurrency: 60. Hosts: 1.
* Average: 228.58 MB/s, 22.86 obj/s, 23.14 ops ended/s (18.323s)

Aggregated Throughput, split into 18 x 1s time segments:
 * Fastest: 1157.40 MB/s, 115.74 obj/s, 141.00 ops ended/s (1s)
 * 50% Median: 154.54 MB/s, 15.45 obj/s, 17.00 ops ended/s (1s)
 * Slowest: 76.60 MB/s, 7.66 obj/s, 1.00 ops ended/s (1s)
```

**Comment by harshavardhana** [comment]
Can you test on 4.x or 5.x kernel versions? @svasilevskiy

**Comment by klauspost** [comment]
Very strange that the write logic should affect read speeds. Could you attach the `warp-get-2020-01-07[235624]-DIlB.csv.zst` file? There shouldn't be any sensitive information in it, but you are also welcome to send it to `klaus@minio.io`.

It is rather strange that the fastest/50% median reads are so different, so I would like to dig a bit deeper.

**Comment by harshavardhana** [comment]
@klauspost I remember of XFS behaving weirdly because of O_DIRECT writes it leads to some form of an issue in XFS that's why I suspect its an XFS issue here and that's why to test with later kernels than 3.10.x. Higher performance in previous releases is because we never really wrote in O_DIRECT mode for 4MiB blocks we only wrote 32KiB in O_DIRECT

**Comment by svasilevskiy** [comment]
@harshavardhana Like I said in the bug, changing readBlockSize back to 32KiB does not fix the issue for us. It doesn't seem to be related to the block size, but rather to write/buffer alignment logic that was introduced in c38ada1.

I will check if we can test on a newer kernel.

**Comment by harshavardhana** [comment]
Correct @svasilevskiy what I am saying is we don't see this issue in our benchmarks on Ubuntu 16.04 or 18.04

**Comment by svasilevskiy** [comment]
Warp log file attached (I had to zip it, as Github didn't let me attach a .zst or a .csv). @klauspost 

[warp-get-2020-01-07[235624]-DIlB.csv.zip](https://github.com/minio/minio/files/4036862/warp-get-2020-01-07.235624.-DIlB.csv.zip)

**Comment by harshavardhana** [comment]
@svasilevskiy few more questions I think I suspect a false positive 

- what type of drives are on these nodes?
- can you do `dd if=/dev/zero of=<mountpoint>/bigfile bs=4M count=1024` and also `dd if=<mountpoint>/bigfile of=/dev/null bs=4M` ?  before running each of these can you also run `echo '3' > /proc/sys/vm/drop_caches` 
- how many drives are there in this setup? is this single erasure-coded or distributed? - if you have given this information I am not able to see please provide again.

**Comment by svasilevskiy** [comment]
Here is the information you requested.

- The drives are mount points from a Dell SAN storage appliance. The appliance itself has many physical drives (100+), but presents itself as a single volume.
- There are four drives (logical drives, as they are mount points on a SAN appliance) total, one drive per MinIO host. The setup is a MinIO cluster of four hosts with the default single erasure set.
- output of dd benchmarks, with drop_cache echo before each one:
```
dd if=/dev/zero of=/mnt/data1/bigfile bs=4M count=1024
1024+0 records in
1024+0 records out
4294967296 bytes (4.3 GB) copied, 2.03224 s, 2.1 GB/s

dd if=/mnt/data1/bigfile of=/dev/null bs=4M
1024+0 records in
1024+0 records out
4294967296 bytes (4.3 GB) copied, 10.0325 s, 428 MB/s
```
Doing same on a locally attached disk (/) gives about the same read speed:
```
dd if=/bigfile of=/dev/null bs=4M count=1024
1024+0 records in
1024+0 records out
4294967296 bytes (4.3 GB) copied, 10.3074 s, 417 MB/s
```

**Comment by harshavardhana** [comment]
Wait it should be `oflag=direct`,  SAN or otherwise it doesn't really matter here. Can you re-do after `oflag=direct` for writes

```
~ dd if=/dev/zero of=/mnt/data1/bigfile bs=4M count=1024 oflag=direct
```

**Comment by svasilevskiy** [comment]
With oflag=direct and drop_caches echo between each dd:
```
dd if=/dev/zero of=/mnt/data1/bigfile bs=4M count=1024 oflag=direct
1024+0 records in
1024+0 records out
4294967296 bytes (4.3 GB) copied, 37.3114 s, 115 MB/s

dd if=/mnt/data1/bigfile of=/dev/null bs=4M
1024+0 records in
1024+0 records out
4294967296 bytes (4.3 GB) copied, 9.59462 s, 448 MB/s
```

**Comment by harshavardhana** [comment]
So that's your baseline performance per disk @svasilevskiy next, how many drives are being used MinIO setup?

**Comment by svasilevskiy** [comment]
Four drives, like I said before and in the description.

**Comment by harshavardhana** [comment]
> Four drives, like I said before and in the description.

Four drives how? @svasilevskiy single node, distributed? can you share the command line? etc

**Comment by svasilevskiy** [comment]
Copy paste from my previous answer, with emphasis added:
_There are four drives (logical drives, as they are mount points on a SAN appliance) total, **one drive per MinIO host**. The setup is a **MinIO cluster of four hosts** with the default single erasure set._

**Comment by harshavardhana** [comment]
> There are four drives (logical drives, as they are mount points on a SAN appliance) total, **one drive per MinIO host**. The setup is a **MinIO cluster of four hosts** with the default single erasure set.

what is the network between these hosts? @svasilevskiy what is the size each drive? so its just a 4 node 4 drive with 1 drive each setup?

**Comment by svasilevskiy** [comment]
Copy-paste from the Server Setup section in the bug description:
_25Gbps network link_

Size of each drive is 1TB+ (don't know the exact size). Yes, it is a 4-node 4-drive setup with 1 drive/node.

**Comment by svasilevskiy** [comment]
Command line to start each MinIO node:
```
MINIO_ACCESS_KEY=accesskey MINIO_SECRET_KEY=secretkey /minio_rel/minio server http://host1/mnt/data1/minio http://host2/mnt/data1/minio http://host3/mnt/data1/minio http://host4/mnt/data1/minio
```

**Comment by harshavardhana** [comment]
```
~ dd if=/dev/zero of=bigfile bs=4M count=1024 oflag=direct
1024+0 records in
1024+0 records out
4294967296 bytes (4.3 GB) copied, 15.4707 s, 278 MB/s
```

```
~ dd if=bigfile of=/dev/null bs=4M
1024+0 records in
1024+0 records out
4294967296 bytes (4.3 GB) copied, 8.36979 s, 513 MB/s
```

```
~ ./go/bin/warp get --objects 1000 -obj.size 64M -duration 30s -concurrent 60 -host host3:9000,host4:9000,host5:9000,host6:9000
~ Operation: GET. Concurrency: 60. Hosts: 4.
* Average: 1117.15 MB/s, 17.46 obj/s, 17.25 ops ended/s (20.576s)

Throughput by host:
 * http://host3:9000: Avg: 267.09 MB/s, 4.17 obj/s (29.765s)
 * http://host4:9000: Avg: 295.28 MB/s, 4.61 obj/s (29.806s)
 * http://host5:9000: Avg: 287.89 MB/s, 4.50 obj/s (29.645s)
 * http://host6:9000: Avg: 265.37 MB/s, 4.15 obj/s (29.9s)

Aggregated Throughput, split into 20 x 1s time segments:
 * Fastest: 1154.15 MB/s, 18.03 obj/s, 9.00 ops ended/s (1s)
 * 50% Median: 1114.61 MB/s, 17.42 obj/s, 23.00 ops ended/s (1s)
 * Slowest: 1103.39 MB/s, 17.24 obj/s, 17.00 ops ended/s (1s)
warp: Starting cleanup...
```

```
~ ./go/bin/warp get -obj.size 10M -duration 30s -concurrent 60 -host host3:9000,host4:9000,host5:9000,host6:9000

Operation: GET. Concurrency: 60. Hosts: 4.
* Average: 1111.19 MB/s, 111.12 obj/s, 111.32 ops ended/s (27.84s)

Throughput by host:
 * http://host3:9000: Avg: 272.99 MB/s, 27.30 obj/s (29.964s)
 * http://host4:9000: Avg: 271.71 MB/s, 27.17 obj/s (29.979s)
 * http://host5:9000: Avg: 281.20 MB/s, 28.12 obj/s (29.972s)
 * http://host6:9000: Avg: 275.82 MB/s, 27.58 obj/s (29.972s)

Aggregated Throughput, split into 27 x 1s time segments:
 * Fastest: 1140.71 MB/s, 114.07 obj/s, 117.00 ops ended/s (1s)
 * 50% Median: 1113.81 MB/s, 111.38 obj/s, 104.00 ops ended/s (1s)
 * Slowest: 1068.20 MB/s, 106.82 obj/s, 111.00 ops ended/s (1s)
```

Here are the numbers on regular HDDs and this is on 

```
~ uname -r
3.10.0-957.12.2.el7.x86_64
```

and same XFS filesystem

```
/mc admin info myminio
●  host4:9000
   Uptime: 11 minutes 
   Version: 2020-01-03T19:12:21Z
   Network: 4/4 OK 
   Drives: 1/1 OK 
●  host5:9000
   Uptime: 11 minutes 
   Version: 2020-01-03T19:12:21Z
   Network: 4/4 OK 
   Drives: 1/1 OK 
●  host6:9000
   Uptime: 11 minutes 
   Version: 2020-01-03T19:12:21Z
   Network: 4/4 OK 
   Drives: 1/1 OK 
●  host3:9000
   Uptime: 11 minutes 
   Version: 2020-01-03T19:12:21Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

4 drives online, 0 drives offline
```

I suspect we writing in O_DIRECT is creating problems for your SAN disks.

**Comment by harshavardhana** [comment]
Now two clients with distributed warp setup, numbers scale really nicely.

```
./go/bin/warp get --objects 1000 -obj.size 64M -duration 30s -concurrent 60 -host host{3...6}:9000 -warp-client=host{1...2}
warp: Connecting to ws://host1:7761/ws
warp: Accepting connection from server: ysftVSiIdU3nAAkJsnQx
warp: Executing get benchmark.
warp: Client 139.178.88.105:7761 connected...
warp: Connecting to ws://host2:7761/ws
warp: Client 139.178.89.155:7761 connected...
warp: All clients connected...
warp: Requesting stage prepare start...
warp: Starting stage prepare in 999.675721ms
warp: Client 139.178.88.105:7761: Requested stage prepare start..
warp: Client 139.178.89.155:7761: Requested stage prepare start..
warp: Uploading 1000 Objects of Random data; 67108864 bytes total, 10485760 byte buffer
warp: prepare done...
warp: Waiting
warp: Client 139.178.88.105:7761: Finished stage prepare...
warp: Client 139.178.89.155:7761: Finished stage prepare...
warp: All clients prepared...
warp: Requesting stage benchmark start...
warp: Starting stage benchmark in 2.999588096s
warp: Client 139.178.88.105:7761: Requested stage benchmark start..
warp: Client 139.178.89.155:7761: Requested stage benchmark start..
warp: Starting
warp: Stopping
warp: benchmark done...
warp: Benchmark data written to "warp-get-2020-01-09[002158]-H3QJkV.csv.zst"
warp: Client 139.178.88.105:7761: Finished stage benchmark...
warp: Client 139.178.89.155:7761: Finished stage benchmark...
warp: Done. Downloading operations...
warp: Client 139.178.88.105:7761: Operations downloaded.
warp: Client 139.178.89.155:7761: Operations downloaded.
warp: Benchmark data written to "warp-remote-2020-01-09[002235]-XvIr.csv.zst"
warp: Requesting stage cleanup start...
warp: Starting stage cleanup in 0s
warp: Starting cleanup...
warp: Client 139.178.88.105:7761: Requested stage cleanup start..
warp: Client 139.178.89.155:7761: Requested stage cleanup start..
warp: cleanup done...
warp: Client 139.178.88.105:7761: Finished stage cleanup...
warp: Client 139.178.89.155:7761: Finished stage cleanup...
-------------------
...
...
-------------------
Operation: GET. Concurrency: 120. Hosts: 4.
* Average: 1279.77 MB/s, 20.00 obj/s, 18.73 ops ended/s (12.602s)

Throughput by host:
 * http://host3:9000: Avg: 332.65 MB/s, 5.20 obj/s (29.989s)
 * http://host4:9000: Avg: 300.17 MB/s, 4.69 obj/s (29.629s)
 * http://host5:9000: Avg: 306.84 MB/s, 4.79 obj/s (29.941s)
 * http://host6:9000: Avg: 332.00 MB/s, 5.19 obj/s (29.532s)

Aggregated Throughput, split into 12 x 1s time segments:
 * Fastest: 1307.33 MB/s, 20.43 obj/s, 16.00 ops ended/s (1s)
 * 50% Median: 1276.56 MB/s, 19.95 obj/s, 18.00 ops ended/s (1s)
 * Slowest: 1257.93 MB/s, 19.66 obj/s, 27.00 ops ended/s (1s)
warp: Received Disconnect
warp: Closing connection
```

So I am suspecting this is a problem at hardware, not sure why an I/O pattern in write affects the SAN most probably because of how blocks are managed at the hardware level, its perhaps exposing a bug here.

**Comment by harshavardhana** [comment]
anyways deleted my nodes, I have validated the situation with different types of objects. I don't see a regression.

**Comment by svasilevskiy** [comment]
@harshavardhana How do you explain that MinIO works fast on SAN disks prior to commit c38ada1, while after c38ada1 it works slow?

Also, (poorly named) commit c38ada1 doesn't affect writes only, from what I can tell. It contains new logic in CopyAlighed, which implements the copy operation i.e. first the read (pkg/ioutil/ioutil.go line 216) and then the write.
https://github.com/minio/minio/commit/c38ada1a2665033f9a2a4d8365ddb256c0dc0e1a#diff-69b5e79a5e900aedb52879893ef6c24fR216

**Comment by harshavardhana** [comment]
> @harshavardhana How do you explain that MinIO works fast on SAN disks prior to commit [c38ada1](https://github.com/minio/minio/commit/c38ada1a2665033f9a2a4d8365ddb256c0dc0e1a), while after [c38ada1](https://github.com/minio/minio/commit/c38ada1a2665033f9a2a4d8365ddb256c0dc0e1a) it works slow?

That is because you are reading from page-cache @svasilevskiy those numbers are wrong as you can see from your `dd` output server cannot give 2.8GiB/sec

**Comment by harshavardhana** [comment]
> Also, (poorly named) commit [c38ada1](https://github.com/minio/minio/commit/c38ada1a2665033f9a2a4d8365ddb256c0dc0e1a) doesn't affect writes only, from what I can tell. It contains new logic in CopyAlighed, which implements the copy operation i.e. first the read (pkg/ioutil/ioutil.go line 216) and then the write.
> [c38ada1#diff-69b5e79a5e900aedb52879893ef6c24fR216](https://github.com/minio/minio/commit/c38ada1a2665033f9a2a4d8365ddb256c0dc0e1a#diff-69b5e79a5e900aedb52879893ef6c24fR216)

I don't think you understand @svasilevskiy here its showing an underlying hardware issue. As you can see from the numbers that I have posted for the same CentOS 7.x kernel and same XFS with regular HDDs.

**Comment by svasilevskiy** [comment]
> > @harshavardhana How do you explain that MinIO works fast on SAN disks prior to commit [c38ada1](https://github.com/minio/minio/commit/c38ada1a2665033f9a2a4d8365ddb256c0dc0e1a), while after [c38ada1](https://github.com/minio/minio/commit/c38ada1a2665033f9a2a4d8365ddb256c0dc0e1a) it works slow?
> 
> That is because you are reading from page-cache @svasilevskiy those numbers are wrong as you can see from your `dd` output server cannot give 2.8GiB/sec

I don't know if I would trust dd numbers as the source of truth for theoretical bandwidth limit (running it over a locally attached PCI-e SSD gives only 25% of its hardware read speed).
Can you help me understand what line in commit c38ada1 is turning off the page-cache? I would like to change it back to reading from the page cache (but don't change any other c38ada1 logic) to test this hypothesis.

**Comment by harshavardhana** [comment]
dd numbers are real numbers that you would see in real world, if you don't trust them then we cannot proceed further. Theoretical numbers are never realistic, there are quite a few tapered performance limitations at the OS level that come into picture.

Because of the aligned writes the SAN is performing weirdly because, SAN is doing something with the blocks which I don't know what. Lets see if we can remove MinIO out of the equation and run a test program which does exactly as what MinIO would do and let's see if the numbers are consistent?

**Comment by svasilevskiy** [comment]
Wait, so are the slow read speeds because of the aligned writes or because of not reading from page cache (as you mentioned just before)? 

If it's the block alignment, then the culprit could be that SAN is doing something with the blocks, or that MinIO is aligning them sub optimally for SAN (but maybe ok for directly attached disks).

Why not try changing the alignment algorithm in MinIO and seeing if SAN speeds improve? Or adding a switch to disable aligned writes? I can test intermediate MinIO versions as needed on our end.

The end goal for us is to use MinIO with SAN disks, not to prove that the current MinIO works great in your environment and poor in our environment.

**Comment by harshavardhana** [comment]
> Why not try changing the alignment algorithm in MinIO and seeing if SAN speeds improve? Or adding a switch to disable aligned writes? I can test intermediate MinIO versions as needed on our end.

Alignment is nothing special it simply buffers upto 4MiB and writes @svasilevskiy - this is standard O_DIRECT style write.

**Comment by svasilevskiy** [comment]
> > Why not try changing the alignment algorithm in MinIO and seeing if SAN speeds improve? Or adding a switch to disable aligned writes? I can test intermediate MinIO versions as needed on our end.
> 
> Alignment is nothing special it simply buffers upto 4MiB and writes @svasilevskiy - this is standard O_DIRECT style write.

Can we add a switch to MinIO to not do O_DIRECT 4MiB writes, i.e. go to pre c38ada1 checkin behavior? Since this behavior doesn't work for SAN mounted disks?

**Comment by harshavardhana** [comment]
> Can we add a switch to MinIO to not do O_DIRECT 4MiB writes, i.e. go to pre [c38ada1](https://github.com/minio/minio/commit/c38ada1a2665033f9a2a4d8365ddb256c0dc0e1a) checkin behavior? Since this behavior doesn't work for SAN mounted disks?

That would be wrong you are willfully asking for data loss @svasilevskiy , we shouldn't do that I will give you a tool which does something similar without MinIO this way we can track it down.

**Comment by svasilevskiy** [comment]
All I'm saying is to be able to go back to pre-c38ada1 way of doing IO @harshavardhana, which was still with O_DIRECT as far as I know, just different alignment or block handling logic.

I'll be able to run a tool that you provide if it helps to solve this issue.

**Comment by harshavardhana** [comment]
It deceptively looks that way, but it wasn't the alignment was never 32K because we never waited for 32K enough buffer. So for the most part it wrote unaligned turning off O_DIRECT

Just looking at the code you can't know the context here @svasilevskiy 

Give me a day or two I will give that tool.

**Comment by jonassvatos** [comment]
I second that issue, on a erasure-coded node with 32x 8TB 7.2K SAS drives, each on it's own mount (ext4 formatted), read speed decreased mode than 50 times.. from 1GB/s to less than 20MB/s on large files (>100GB/file)
Regression is seen on minio.RELEASE.2020-01-03T19-12-21Z
Release before regression: minio.RELEASE.2019-10-12T01-39-57Z
OS is CentOS 7.6

Anyway, how do I downgrade minio to older version, now it doesn't start b/c config incompatibilities..

**Comment by harshavardhana** [comment]
@lsde lets not hijack the issue here please open a separate issue. Your issue is different for large files uploaded perhaps using multipart had an issue with encoding/json v/s jsoniter usage which is fixed in aa2e89bfe3043a7a39debf650583bfb9ac334041 - try `minio/minio:edge` docker master to validate it. 

Also, you can downgrade by `rm -rf .minio.sys/config .minio.sys/backend-encrypted` from each disks and restarting server.

**Comment by harshavardhana** [comment]
@svasilevskiy can you join our https://slack.min.io so that we can work on this in real time?

I am generally available during PST (US) timezone..

**Comment by harshavardhana** [comment]
This issue is under investigation, removing "working as intended"

**Comment by harshavardhana** [comment]
The issue was investigated and found to be SAN's behavior with O_DIRECT durability. We tested with various block sizes all of them result in some degradation in performance. 

Using local HDD's however, this degradation is not seen. Closing this issue on our end for now - shall re-open later but for now this is not MinIO issue.
