### ISSUE TITLE
Picture thumbnail feature

### ISSUE THREAD

**Issue by nonacosa** [minio/minio#8767]
[when i find picture download on my pc,I always try many times]
 
[if you can have a thumbnail option, you can locate the image directly. When debugging, you don't need to download it for confirmation]
 
![image](https://user-images.githubusercontent.com/14212375/71966975-7ffe7d80-323d-11ea-89f6-bf63d495c0a5.png)

[Image thumbnail if allowed, I would like to contribute this function to minio！thx！]

**Comment by nonacosa** [comment]
I know share file can also preview the image，but only one by one.

**Comment by harshavardhana** [comment]
Closing as duplicate of #3835
