### ISSUE TITLE
Specify the Kafka version

### ISSUE THREAD

**Issue by simoncousins** [minio/minio#8768]
MinIO uses the sarama library to communicate with Kafka. Currently the Kafka version is not set in the sarama config and it defaults to the sarama.MinVersion: 0.8.2.0.

Unfortunately, 0.8.2.0 does not support timestamps in Kafka (the timestamp gets set to -1). This means that I cannot make use of Kafka Streams to process MinIO bucket notifications. See: https://stackoverflow.com/a/52707313

Adding the Kafka version to the MinIO Kafka notification arguments and setting the version on the sarama config would allow me to specify a later Kafka version that creates valid timestamps (>= 0.10).

**Comment by nitisht** [comment]
Thanks for reporting @simontcousins we'll take a look

**Comment by simoncousins** [comment]
Thanks everyone, much appreciated.
