### ISSUE TITLE
Pyspark Write API

### ISSUE THREAD

**Issue by hossein-kshvrz** [minio/minio#8770]
I want to develop a system in which ML models are trained with Python API of Spark ML. I need such models to be saved, and since I have a Spark cluster, I need a distributed file system in order to save the model in a distributed manner. Otherwise, I cannot retrieve the model because separate parts of the model are located on separate nodes. Spark ML models are saved as follows:
```
model.save(MODEL_PATH)
```
Thus, I need a way to save the model on MinIO server just by giving the path of my bucket to the above function. I found [MinIO Spark Select](https://github.com/minio/spark-select), but it seems that it only works with Amazon S3, but my nodes are not that type. It also is just for reading files, but I specially need to write models on file.

**Comment by harshavardhana** [comment]
Spark already has s3a which needs to be used to writing @hossein-kshvrz and it provides various data sources with write capabilities

spark-select is a read optimized data source, it's not scope doesn't go into writes.

**Comment by hossein-kshvrz** [comment]
@harshavardhana Thanks. I am using a Spark Docker image with pre-built Hadoop. Are including the JAR files you mentioned [here](https://github.com/minio/minio/issues/7020#issuecomment-449781153) and the Hadoop configuration mentioned in the comment above it enough? I tested it, and I got the following error:
`Class org.apache.hadoop.fs.s3a.S3AFileSystem not found`
I know it's not within the scope of your repository and it is related to MinIO indirectly, but do you have any idea whether I must setup Hadoop cluster separately or not?

**Comment by hossein-kshvrz** [comment]
I worked a little bit on it, and the error change to the following:
`java.lang.NoSuchMethodError: com.amazonaws.services.s3.transfer.TransferManager`
It is making me cry :((((
Could you please help me get out of this situation if you have any idea?

**Some information about environment:**
Spark image: bde2020/spark:2.4.1-hadoop2.7
aws-java-sdk version:1.7.4
org.apache.hadoop:hadoop-aws version: 2.7.0 (2.7.1, 2.7.2, 2.7.3, 2.7.4 and 2.7.6 also tested)
Hadoop configuration: 
```hadoop_conf=spark._jsc.hadoopConfiguration()
hadoop_conf.set("fs.s3a.impl","org.apache.hadoop.fs.s3a.S3AFileSystem")
hadoop_conf.set("fs.s3a.endpoint","http://MY_PUBLIC_IP_ADDRESS:9000")
hadoop_conf.set("fs.s3a.access.key","**********")
hadoop_conf.set("fs.s3a.secret.key","**********")
hadoop_conf.set("fs.s3a.connection.ssl.enabled","false")
hadoop_conf.set("fs.s3a.path.style.access","true")
```
my command is:
`./bin/spark-submit --packages com.amazonaws:aws-java-sdk:1.7.4,org.apache.hadoop:hadoop-aws:2.7.4 dist_write.py`
