### ISSUE TITLE
Allow different concurrent profiling types

### ISSUE THREAD

**Issue by klauspost** [minio/minio#8771]
MinIO only allows for one profiling type to run concurrently. However when identifying complex issues it is often beneficial to run several profiling types at the same time.

**Describe the solution you'd like**

When starting profiling, enable several types to be specified in `profilerType`, maybe comma separated.

Relevant handlers: 

* [StartProfilingHandler](https://github.com/minio/minio/blob/6695fd6a61afa9cb0a652cc45b2e1c23efd73d5f/cmd/admin-handlers.go#L562)
* [DownloadProfilingHandler](https://github.com/minio/minio/blob/6695fd6a61afa9cb0a652cc45b2e1c23efd73d5f/cmd/admin-handlers.go#L644)

When downloading, include all active profiles in the zip file.

**Describe alternatives you've considered**

Multiple calls, but that just seems clunky and complicates downloading.

**Comment by harshavardhana** [comment]
@klauspost is it possible to enable multiple profiling in Go? and is the timing accurate?

**Comment by klauspost** [comment]
Yes and yes. `trace` is the only one that can really affect the system, but not more than a few percent.

**Comment by harshavardhana** [comment]
Then it is fairly simple for us to support, we just have to take the input profile values as comma separated in the Profile handler.
