### ISSUE TITLE
background-ops not found after Update

### ISSUE THREAD

**Issue by philippjenni** [minio/minio#8781]
After Update to the latest version of minio i become the follow error at startup

```
Jan  9 15:06:18 vstorage01 minio[4726]: Error: Bucket not found: .minio.sys/background-ops
Jan  9 15:06:18 vstorage01 minio[4726]:        2: cmd/data-usage.go:100:cmd.runDataUsageInfoForXLZones()
Jan  9 15:06:18 vstorage01 minio[4726]:        1: cmd/data-usage.go:54:cmd.runDataUsageInfoUpdateRoutine()
```

## Expected Behavior
There should no error displayed on system startup

## Current Behavior
error message in syslog on all minio servers

```
Jan  9 15:06:18 vstorage01 minio[4726]: Error: Bucket not found: .minio.sys/background-ops
Jan  9 15:06:18 vstorage01 minio[4726]:        2: cmd/data-usage.go:100:cmd.runDataUsageInfoForXLZones()
Jan  9 15:06:18 vstorage01 minio[4726]:        1: cmd/data-usage.go:54:cmd.runDataUsageInfoUpdateRoutine()
```

## Possible Solution
if the structure is missing, it should be created.

## Steps to Reproduce (for bugs)
1. Error comes after update to the build of 9. jan. The previous release was 11. sept 2019

## Your Environment
* Version used 2020-01-09
* Environment name and version (e.g. nginx 1.9.1): -
* Server type and version: ubuntu 18.04 lts
* Operating System and version (`uname -a`): Linux vstorage01 4.15.0-62-generic #69-Ubuntu SMP Wed Sep 4 20:55:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project: -

**Comment by vadmeste** [comment]
Thanks @philippjenni, we will take a look!
