### ISSUE TITLE
Test error does not fail CI test

### ISSUE THREAD

**Issue by klauspost** [minio/minio#8782]
The way [CI tests are performed](https://github.com/minio/minio/blob/master/.travis.yml#L35) will hide any errors since the for loop only returns the status of the last call AFAICT.

## Expected Behavior

When an error occurs, return non zero exit code to indicate error.

## Current Behavior

Even if there are [failures](http://ci.min.io:30004/view/9027fd276f36977761d3adac7189d46068b1f2f7#L1363) CI indicates no problem.

## Possible Solution

I don't have enough bash clout to not waste a huge amount of time on this.

Not sure why this has to be done in a loop at all.

## Steps to Reproduce (for bugs)

Run CI tests with a failed test.

**Comment by harshavardhana** [comment]
Let me change it, I also observed it, will try to move `go test -v ./...`

**Comment by harshavardhana** [comment]
This is fixed in #8776 we have a shell script now which will fail appropriately using bash `set -e` feature.
