### ISSUE TITLE
mc admin user list --json returns illegal json

### ISSUE THREAD

**Issue by Eric-Fontana-Bose** [minio/minio#8783]
I'm trying to use minio within our Kubernetes cluster and I want to control the provisioning
of users and groups via REST API, but that doesn't seem possible, or at least I cannot find the documentation for the Admin API endpoints anywhere.

So my fallback (suggested by users was to just call out to the client `mc admin`)

## Current Behavior
First command I tried was
`mc admin user list k8s --json` and what I got back was illegal JSON:

```json
{
 "status": "success",
 "accessKey": "newuser",
 "userStatus": "enabled"
}
{
 "status": "success",
 "accessKey": "newuser2",
 "userStatus": "enabled"
}
```

## Expected Behavior
I sort of expected it to return an array:
```json
[
   {
      "status":"success",
      "accessKey":"newuser",
      "userStatus":"enabled"
   },
   {
      "status":"success",
      "accessKey":"newuser2",
      "userStatus":"enabled"
   }
]
```

## Your Environment
* Version used RELEASE.2020-01-03T20-33-14Z

**Comment by harshavardhana** [comment]
It is not illegal json it's called jsonlines format http://jsonlines.org/

Closing this as a non issue.
