### ISSUE TITLE
Policy not applied when provided by keycloak

### ISSUE THREAD

**Issue by GuillaumeNachury** [minio/minio#8787]
When using the OpenID login feature against a keycloak server, the policy is carries over but not applied 

## Expected Behavior

When logging in with a user A, created thru `mc` with policy `readwrite`, on the Minio browser I can see the buckets B1, B2, B3.
When using the openID button to log in the user B, defined in keycloak with policy attribute set to `readwrite`, on the Minio browser I should see the buckets

## Current Behavior

No buckets displayed after login thru OpenID. 
The policy exists and is placed jwt payload.

## Steps to Reproduce (for bugs)

1. Follow these steps : https://github.com/minio/minio/blob/master/docs/sts/keycloak.md
2. Create 3 buckets thru `mc`
3. Open Minio UI and click the OpenID button
4. Sign on keycloak login page with the user created @ step1

## Your Environment

* Version used (`minio version`): docker minio/minio:edge
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): win10
* Link to your project:

**Comment by harshavardhana** [comment]
can you provide the jwt payload @GuillaumeNachury ? also provide all the settings `mc admin config get myminio identity_openid` ?

**Comment by GuillaumeNachury** [comment]
Results from `mc admin config get myminio identity_openid` : 
```
identity_openid config_url=http://127.0.0.1:8080/auth/realms/master/.well-known/openid-configuration client_id=account claim_prefix= jwks_url= claim_name=policy
```
and here is the jwt payload
```
{
  "jti": "198c3434-253a-48b7-8b43-87380a70fdac",
  "exp": 1578651288,
  "nbf": 0,
  "iat": 1578650388,
  "iss": "http://127.0.0.1:8080/auth/realms/master",
  "aud": "account",
  "sub": "6e571255-c64d-459b-ba6f-98bd43e683e1",
  "typ": "ID",
  "azp": "account",
  "nonce": "zieRSKtLwzwJ6xxH",
  "auth_time": 1578647902,
  "session_state": "f27d4449-9bba-41f7-94a5-a817cec545a5",
  "acr": "0",
  "email_verified": true,
  "name": "Guillaume Nachury",
  "preferred_username": "guillaume",
  "given_name": "Guillaume",
  "family_name": "Nachury",
  "email": "guillaume.nachury@azerty.com",
  "policy": "readwrite"
}
```

**Comment by harshavardhana** [comment]
Thanks checking @GuillaumeNachury
