### ISSUE TITLE
It is possible to get the free space of a MinIO instance?

### ISSUE THREAD

**Issue by tinohager** [minio/minio#8789]
My disk has a size of 500GB. Can I check via api how much free space is still available?

**Comment by tinohager** [comment]
Okay i think this is the api i search. https://github.com/minio/minio/blob/master/docs/metrics/prometheus/README.md

**Comment by nitisht** [comment]
Yes, that is the API, Closing this issue. Feel free to join us on slack (https://slack.min.io) for more such questions
