### ISSUE TITLE
mc: <ERROR> Failed to remove minio/bucket/folder recursively. Truncated response should have continuation token set

### ISSUE THREAD

**Issue by Biond1** [minio/minio#8790]
when I try to remove recursively a folder with the command:
` mc rm -r --force minio/bucket/folder`
I get the error:
`mc: <ERROR> Failed to remove minio/bucket/folder recursively. Truncated response should have continuation token set`
Anyone can help me?

**Comment by harshavardhana** [comment]
What is the server here @Biond1 ?please recreate a new issue following issue template. Closing this issue as non actionable.
