### ISSUE TITLE
Upgrading to latest minio causes s3ql md5 mismatch

### ISSUE THREAD

**Issue by agj32mrgibbits** [minio/minio#8793]
I was previously using s3ql with a minio version before and around feb-22-2019. Since upgrading to RELEASE.2020-01-03T19-12-21Z, s3ql can no longer use the bucket due to repeated MD5 Mismatch errors.

## Expected Behavior
Normal operation

## Current Behavior
Gets stuck trying to mount bucket with the following errors:
```
Encountered BadDigestError (BadDigest: MD5 mismatch for s3ql_seq_no_1556105681 (received: 514bc93b9878adbd582b7596b31c4dd5-1, sent: 446c4b2b3f537692bdd42e2742c00e22)), retrying ObjectW.close (attempt 3)...
Encountered BadDigestError (BadDigest: MD5 mismatch for s3ql_seq_no_1556105681 (received: 38e62e4c3cc5a5c8723ab77b19dfd0c6-1, sent: 446c4b2b3f537692bdd42e2742c00e22)), retrying ObjectW.close (attempt 4)...
WARNING: Encountered BadDigestError (BadDigest: MD5 mismatch for s3ql_seq_no_1556105681 (received: d88fccd70b1d4ce1bb1e94b8488439a2-1, sent: 446c4b2b3f537692bdd42e2742c00e22)), retrying ObjectW.close (attempt 5)...
WARNING: Encountered BadDigestError (BadDigest: MD5 mismatch for s3ql_seq_no_1556105681 (received: 7514c534405cb3aa1225515ceb0958e3-1, sent: 446c4b2b3f537692bdd42e2742c00e22)), retrying ObjectW.close (attempt 6)...
WARNING: Encountered BadDigestError (BadDigest: MD5 mismatch for s3ql_seq_no_1556105681 (received: b9e585f9fc851c995a9928aac34a60ae-1, sent: 446c4b2b3f537692bdd42e2742c00e22)), retrying ObjectW.close (attempt 7)...
WARNING: Encountered BadDigestError (BadDigest: MD5 mismatch for s3ql_seq_no_1556105681 (received: 73b4944557cbecb63f38a27729b514d5-1, sent: 446c4b2b3f537692bdd42e2742c00e22)), retrying ObjectW.close (attempt 8)...
WARNING: Encountered BadDigestError (BadDigest: MD5 mismatch for s3ql_seq_no_1556105681 (received: 5ae3e7c1e02ea0a2d7f7217a4ca86e00-1, sent: 446c4b2b3f537692bdd42e2742c00e22)), retrying ObjectW.close (attempt 9)...
WARNING: Encountered BadDigestError (BadDigest: MD5 mismatch for s3ql_seq_no_1556105681 (received: ce4bbf2385fcf9eb0d88177d9e5b9260-1, sent: 446c4b2b3f537692bdd42e2742c00e22)), retrying ObjectW.close (attempt 10)...

```

## Possible Solution
Possibly an ETag bug? It looks like it is returning a multi-part Etag (the -1 at the end) when this is a single PUT operation, which should just be an MD5 digest of the file with no dashes or part numbers.

## Steps to Reproduce (for bugs)
1. Mount and use a bucket with S3QL on minio build ealier than feb-22-2019
2. Unmount S3QL
3. Upgrade minio to RELEASE.2020-01-03T19-12-21Z
4. Try to mount bucket in S3QL again

## Regression
Somewhere between feb-22-2019 or earlier build and RELEASE.2020-01-03T19-12-21Z

## Your Environment
* Version:  RELEASE.2020-01-03T19-12-21Z
* Environment name and version: S3QL 3.3
* Operating System and version: Linux, Manjaro, x64, kernel 4.19

**Comment by harshavardhana** [comment]
It's mentioned here https://github.com/minio/minio#caveats

**Comment by agj32mrgibbits** [comment]
Is minio still claiming S3 compatibility? This differs from their docs:
https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonRequestHeaders.html
https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html

**Comment by harshavardhana** [comment]
Yes it is md5sum is not cornerstone of S3 compatibility @agj32mrgibbits 

It is mentioned why it is done so and with good intentions.

Applications relying on legacy mechanisms which no application uses for example all enterprise applications like Splunk, Hadoop S3A, everyone has moved on to better mechanisms to perform authenticity and checksum. 

Sticking to md5sum is quite backpedaling, s3ql should be fixed IMHO.

**Comment by harshavardhana** [comment]
If the application is very much interested in checksum it should set content-md5, if it didn't set it, there is no point in expecting server to calculate md5sum which is expensive and not meaningful. 

It is easy to fake md5sum checksums even at few KBs of data. If application tells you just by using md5sum returned by server that it has safely uploaded the data then it is surely relying on incorrect techniques.

**Comment by agj32mrgibbits** [comment]
Agreed, s3ql should fix this. Though, it's a little odd to now have to pass a --compat flag for minio to be compatible with the way the S3 API still works to this day.

**Comment by harshavardhana** [comment]
S3 API is like 14yrs old, applications already moved but there are some lingering with old assumptions.

It is just that we are not supporting legacy behavior by default.

**Comment by i0x71** [comment]
So are there any plans to fix this ?
S3ql is a great client and minio is a great server, it just feels like mom and dad can't agree on this one damn thing and it's getting ridiculous!

**Comment by harshavardhana** [comment]
> So are there any plans to fix this ?
> S3ql is a great client and minio is a great server, it just feels like mom and dad can't agree on this one damn thing and it's getting ridiculous!

@i0x71 you can use --compat option for now

https://github.com/minio/minio#caveats

In lieu of community interest we are actually investigating how to speed up md5sum using a vectorizing technique, which allow us to remove --compat in future, more on this will come in future releases so for now use --compat

**Comment by i0x71** [comment]
Thanks for a quick reply!
