### ISSUE TITLE
Minio Client Server mTLS

### ISSUE THREAD

**Issue by hirik** [minio/minio#8803]
**Is your feature request related to a problem? Please describe.**
We need to validate the client certificate to allow connection with the server(As we can't spread the server access key and password).

**Describe the solution you'd like**
An option to enable TLS mutual authentication through the conf file or command line.

**Comment by harshavardhana** [comment]
This is non S3 feature @hirik , there are no known clients which can support this. We shall reopen when AWS S3 implements this.
