### ISSUE TITLE
MinIO Console error message encoding

### ISSUE THREAD

**Issue by tinohager** [minio/minio#8804]
MinIO Version: RELEASE.2020-01-03T19-12-21Z
OS: Windows 10

The error message output on windows have some special chars in the output.

> C:\Temp\MinIO>minio.exe server C:\Temp\MinIO\Data E:\MinIO1 E:\MinIO2 E:\MinIO3 E:\MinIO4
7[41m[37m[1mERROR[0m[0m[0m 8[6C[31mInvalid command line arguments: [1mInvalid total number of endpoints for erasure mode[0m[0m
7[41m     [0m 8[6C> [43m[30mPlease provide an even number of endpoints greater or equal to 4[0m[0m
7[41m     [0m 8[6C[1mHINT:[0m
7[41m     [0m 8[6C  For more information, please refer to https://docs.min.io/docs/minio-erasure-code-quickstart-guide

![image](https://user-images.githubusercontent.com/8215186/72245576-2d341580-35f1-11ea-8129-0e53be669269.png)

**Comment by nitisht** [comment]
Thanks for reporting @tinohager , @klauspost has a PR for this now #8805
