### ISSUE TITLE
mc: <ERROR> Failed to remove minio/bucket/folder recursively. Truncated response should have continuation token set #8790

### ISSUE THREAD

**Issue by Biond1** [minio/minio#8808]
when I try to remove recursively a folder with the command:
`mc rm -r --force minio/bucket/folder`
I get the error:
`mc: <ERROR> Failed to remove minio/bucket/folder recursively. Truncated response should have continuation token set`
Anyone can help me?

 Version used (`minio version`):  2019-12-17T23:26:28Z
 Server type and version: AWS S3

Is there any other command that I can use or can I reset the bucket?

**Comment by harshavardhana** [comment]
@Biond1 which server are you using? there are no details in your bug report can you also paste `--debug`?

**Comment by Biond1** [comment]
> @Biond1 which server are you using? there are no details in your bug report can you also paste `--debug`?
what do you mean, the server is not S3 Amazon web services?

**Comment by kannappanr** [comment]
@Biond1 Please also give more information, like the command you used to start `minio`.

Can you run `mc rm -r --force --debug minio/bucket/folder` and paste the output here

**Comment by Biond1** [comment]
> @Biond1 Please also give more information, like the command you used to start `minio`.
> 
> Can you run `mc rm -r --force --debug minio/bucket/folder` and paste the output here

`mc: <DEBUG> GET /bucket/folder/%2F HTTP/1.1
Host: mine 
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.45 mc/2019-12-17T23:26:28Z
Authorization: 
X-Amz-Content-Sha256: 
X-Amz-Date: 20200113T214659Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Mon, 13 Jan 2020 21:46:59 GMT
X-Amz-Request-Id: tx0000000000000006e2caf-005e1ce553-76318-default

mc: <DEBUG> Response Time:  21.92367ms`


and the commands where 
'mc config host add bucket <key_2> <key_1>'

**Comment by harshavardhana** [comment]
are you using ceph or digital ocean here? @Biond1 ?

**Comment by harshavardhana** [comment]
From the error it can be clearly seen that the server is sending incorrect data i.e it is setting IsTruncated with NextContinuationToken not set which is AWS S3 incompatible response.  Please ask your server vendor to fix this @Biond1 we can't fix it on our end.
