### ISSUE TITLE
Invalid secret key error when using China Azure Gateway

### ISSUE THREAD

**Issue by D-T-Y** [minio/minio#8809]
## Expected Behavior

Authentication succeeded

## Current Behavior

Authentication failed

## Possible Solution

Not yet
## Steps to Reproduce (for bugs)

docker run -p 9000:9000 --name azure-s3 \
 -e "MINIO_ACCESS_KEY=MyAzureStorageAccountName" \
 -e "MINIO_SECRET_KEY=MyAzurekey" \
 minio/minio gateway azure

【Controller】

> 
> 
>  Endpoint: http://10.42.0.88:9000 http://127.0.0.1:9000
> AccessKey: c*******s
> SecretKey: 11sXVKFy*****************CV//KhBUHEomOsH+oYyp6Wmv0NJ**********Mxy9s/U1QYw==
>  
>  
>  
> Browser Access: 
>    http://10.42.0.88:9000  http://127.0.0.1:9000 
>  
> Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide 
>    $ mc config host add myazure http://10.42.0.88:9000 c*******s 11sXVKFy*****************CV//KhBUHEomOsH+oYyp6Wmv0NJ**********Mxy9s/U1QYw== 
>  
> Object API (Amazon S3 compatible): 
>         https://docs.min.io/docs/golang-client-quickstart-guide 
>       https://docs.min.io/docs/java-client-quickstart-guide 
>     https://docs.min.io/docs/python-client-quickstart-guide 
> https://docs.min.io/docs/javascript-client-quickstart-guide 
>       https://docs.min.io/docs/dotnet-client-quickstart-guide 
>  
> API: WebListBuckets() 
> Time: 12:49:41 CST 01/14/2020 
> DeploymentID: 3abade88-2ae1-4de6-bbf8-51ebaa709d57 
> RemoteHost: 192.168.1.200 
> Host: 192.168.1.200:32568 
> UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36 
> Error:  
> ===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) ===== 
> Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. 
> RequestId:4c1c0908-801e-0077-7096-ca19bf000000 
> Time:2020-01-14T04:49:40.8977001Z, Details: 
>    AuthenticationErrorDetail: The MAC signature found in the HTTP request 'N4ZJFFeTIDb1AkTXuwllOcY1XlRnIgJaPiaxmQKCbIo=' is not the same as any computed signature. Server used following string to sign: 'GET 
>  
> x-ms-client-request-id:11f83f6e-8edb-4b0a-4e17-1ebc2810ea67 
> x-ms-date:Tue, 14 Jan 2020 04:49:39 GMT 
> x-ms-version:2018-11-09 
> /cos/ 
> comp:list 
> timeout:16'. 
> Code: AuthenticationFailed 
>    GET https://cos.blob.core.windows.net?comp=list&timeout=16 
>    Authorization: REDACTED 
>    User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-01-03T19:12:21Z] 
>    X-Ms-Client-Request-Id: [11f83f6e-8edb-4b0a-4e17-1ebc2810ea67] 
>    X-Ms-Date: [Tue, 14 Jan 2020 04:49:39 GMT] 
>    X-Ms-Version: [2018-11-09] 
>
>    -------------------------------------------------------------------------------- 
>
>    RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. 
>    Content-Length: [715] 
>    Content-Type: [application/xml] 
>    Date: [Tue, 14 Jan 2020 04:49:39 GMT] 
>    Server: [Microsoft-HTTPAPI/2.0] 
>   X-Ms-Error-Code: [AuthenticationFailed] 
>    X-Ms-Request-Id: [4c1c0908-801e-0077-7096-ca19bf000000] 
>        3: cmd/web-handlers.go:2108:cmd.toWebAPIError() 
>        2: cmd/web-handlers.go:1986:cmd.toJSONError() 
>        1: cmd/web-handlers.go:340:cmd.(*webAPIHandlers).ListBuckets() 
>  
> API: WebListBuckets() 
> Time: 12:49:41 CST 01/14/2020 
> DeploymentID: 3abade88-2ae1-4de6-bbf8-51ebaa709d57 
> RemoteHost: 192.168.1.200 
> Host: 192.168.1.200:32568 
> UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36 
> Error:  
> ===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) ===== 
> Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. 
> RequestId:4c1c0908-801e-0077-7096-ca19bf000000 
> Time:2020-01-14T04:49:40.8977001Z, Details: 
>    AuthenticationErrorDetail: The MAC signature found in the HTTP request 'N4ZJFFeTIDb1AkTXuwllOcY1XlRnIgJaPiaxmQKCbIo=' is not the same as any computed signature. Server used following string to sign: 'GET 
>  

 
## Your Environment

I am running the minio azure gateway on an Ubuntu 16.04 machine in an Azure Virtual Machine.

**Comment by vadmeste** [comment]
@D-T-Y Azure China seems to have a different endpoint, could you try adding the argument to MinIO gateway command ?

Something like, `minio gateway azure https://MyAzureStorageAccountName.blob.core.chinacloudapi.cn`

**Comment by D-T-Y** [comment]
@vadmeste How do I set up different endpoint? Is there documentation?

**Comment by D-T-Y** [comment]
Thanks, is OK！

Run command：


docker run -p 9000:9000 --name azure-s3
-e "MINIO_ACCESS_KEY=MyAzureStorageAccountName"
-e "MINIO_SECRET_KEY=MyAzurekey"
minio/minio gateway azure https://MyAzureStorageAccountName.blob.core.chinacloudapi.cn

**Comment by kannappanr** [comment]
@D-T-Y Closing the issue as answered. Please feel free to reach out to us at https://slack.min.io for such questions further
