### ISSUE TITLE
[HDFS gateway] getting error with subdirectories in any bucket

### ISSUE THREAD

**Issue by tromika** [minio/minio#8822]
Using the HDFS gateway if there is a subdirectory on HDFS I get `Object not found: ` error.

![image](https://user-images.githubusercontent.com/540472/72436793-9fe3f300-37a1-11ea-81b6-05f751d95fd3.png)

## Expected Behavior

Should list subdirectories.

## Current Behavior

See ^.

## Steps to Reproduce (for bugs)

1. Create a subdirectory with the add new path button
2. Upload a file there
3. Navigate back to the top level folder(bucket)

Also If you have already a directory structure on HDFS will happen if you open a bucket.

## Your Environment

* Version used (`minio version`): minio/minio:RELEASE.2020-01-03T19-12-21Z
* Environment name and version (e.g. nginx 1.9.1): 
* Server type and version:
* Operating System and version (`uname -a`): docker/kubernetes
* Link to your project:

**Comment by kannappanr** [comment]
@tromika Is there any log on the console? Can you please paste that here

**Comment by tromika** [comment]
@kannappanr there was no error in the console just that UI pop-up ^.

@harshavardhana thanks so much for the quick fix!
