### ISSUE TITLE
Minio installation error

### ISSUE THREAD

**Issue by Shriyut** [minio/minio#8823]
I'm trying to setup spinnaker in GKE 

For this purpose when I run the command 

helm install minio --namespace spinnaker --set accessKey="myaccesskey" --set secretKey="mysecretkey" --set persistence.enabled=false stable/minio

It throws the following error on my screen

Error: This command needs 1 argument: chart name

I'm not sure why since the command seems to be correct

**Comment by harshavardhana** [comment]
This is helm version issue @Shriyut 

```
helm install minio --namespace spinnaker --set accessKey="myaccesskey" --set secretKey="mysecretkey" --set persistence.enabled=false <myfavoritename> stable/minio
```

Next time ask these questions on https://slack.min.io more realtime than opening issues.
