### ISSUE TITLE
[not our bug] Minio in distributed mode in OpenShift

### ISSUE THREAD

**Issue by Sammmy1234** [minio/minio#8831]
## Expected Behavior
When I use following YAMLs in our OpenShift cluster, I would expect that I get a working minio cluster:
https://github.com/minio/minio/blob/master/docs/orchestration/kubernetes/minio-distributed-headless-service.yaml?raw=true
https://github.com/minio/minio/blob/master/docs/orchestration/kubernetes/minio-distributed-statefulset.yaml?raw=true
https://github.com/minio/minio/blob/master/docs/orchestration/kubernetes/minio-distributed-service.yaml?raw=true

## Current Behavior
On start I get following error:

ERROR Invalid command line arguments: path '/data' can not be served by different port on same address
    HINT:
        For more information, please refer to https://docs.min.io/docs/minio-erasure-code-quickstart-guide

## Steps to Reproduce (for bugs)
Use the 3 yamls mentioned above on OpenShift v3.10

## Your Environment
* Created my own minio Dockerimage, based on rhel:7

**Comment by nitisht** [comment]
can you explain a bit about your openshift cluster? How many nodes, what is the type of PVC and PV you're using?

**Comment by Sammmy1234** [comment]
Type of PVC / PV doesn't matter. When I start Minio with a local folder like this, the same error occurs.
minio server http://minio-{0...3}.minio.doesntmatter.svc.cluster.local/notAPVC
I try to deploy the Minio Cluster with 4 replicas.

After looking in the source code in https://github.com/minio/minio/blob/37b32199e3ee76f43b0c71e2046fb0ef58cfebc6/cmd/endpoint.go line 574:
The problem seems to be that the OpenShift Pods all have at last one common IP-adress. But why is that a problem?

**Comment by harshavardhana** [comment]
> After looking in the source code in https://github.com/minio/minio/blob/37b32199e3ee76f43b0c71e2046fb0ef58cfebc6/cmd/endpoint.go line 574:
> The problem seems to be that the OpenShift Pods all have at last one common IP-adress. But why is that a problem?

Because you don't want different ports on the same server exporting drives - we need to exclusively lock the drives. I am suspecting an issue with the command line here, we have users running in openshift already.

**Comment by Sammmy1234** [comment]
Could you maybe get more in detail in what you mean with "issues with the command line"? I don't come to an idea what you could mean.

**Comment by gil0109** [comment]
@Lukas012 Did you ever figure this out?  If so, can you share your build/deploy templates?

**Comment by gravitionium** [comment]
@Lukas012 Did you ever figure this out? if so, can you share your build/deploy templates?

**Comment by harshavardhana** [comment]
Since the advent of operator model it is worthwhile @gravitionium for you to look at

https://github.com/minio/minio-operator

**Comment by harshavardhana** [comment]
> Since the advent of operator model it is worthwhile @gravitionium for you to look at
> 
> https://github.com/minio/minio-operator

The operator model is recommended closing this issue.
