### ISSUE TITLE
kernel-tuning/sysctl.sh has typo

### ISSUE THREAD

**Issue by shineygreen** [minio/minio#8833]
The script sysctl.sh in the kernel-tuning directory has a bash 'hear' statement that looks like,

  cat > sysctl.conf <EOF

The correct syntax to introduce a 'hear' keyword is

  cat > sysctl.conf <<EOF

The incorrect syntax will cause the the script to fail.

**Comment by harshavardhana** [comment]
@shineygreen send a PR to fix this.
