### ISSUE TITLE
Any way to manipulate file directly?

### ISSUE THREAD

**Issue by hl-a-k** [minio/minio#8838]
Usage scenario:
My company need to manage a lot of files of epub. After user upload file, my company need extract some information from those file.

Current solution:
First, we upload the file to minio.
Then, we download the file from minio to disk, and parse it.

Ideal solution:
First, we upload the file to minio.
Then, we create a application in the same server which run the minio. The server access the file direct and parse it.

Any way to achieve this?

**Comment by harshavardhana** [comment]
@hl-a-k MinIO is S3 API compatible implementation. If there are any AWS S3 APIs that allow this we can support them too. 

But unfortunately, there are none, closing this issue.
