### ISSUE TITLE
A lot of disks I/O operations after deleting a directory with millions of files.

### ISSUE THREAD

**Issue by kislik** [minio/minio#8840]
For the building my Minio cluster (Minio version RELEASE.2020-01-03T19-12-21Z) I used 2 servers - **server1** and **server2** (Debian stretch)
On each server, I have 2 instances of Mino (in the docker containers. Docker version 5:19.03) every instance has one HDD disk (7200RPM) (`/dev/sdc` and `/dev/sdd` && `xfs fielsystem`)
i.e.
**server1:**
_instance1_ (mounted to /home/data1) && _instance2_ (mounted to /home/data2)
**server2:**
_instance1_ (mounted to /home/data1) && _instance2_ (mounted to /home/data2)

I had a fat directory (~100GB+) with millions of files inside which I decided to delete (from the Minio Web interface).
- After deleting I looked at the graphics and found that disks utilization was 100% on both servers (**server1**, **server2**)
- So I decided to turn off my cluster (each node), but after turning back (turn on) my cluster I saw that my disks operations didn't normalize.
- Then I decided to turn off one of my instances (**server1** _instance1_) for minimizing disks operations and CPU WA, and it a little bit helped.
- I waited for a while and when I look that I/O operations for working instance come to normal working I tuned on my second instance and I got the same behavior as in the beginning both disks were eaten.
- Now I turn off my **server1** _instance1_ and enable **server1** _instance2_ (just for test and what I saw - the disk was eaten =) ) (on the graphics, you can see two disks blue and purple and how the load is growing when one or another instance is turning on or off)

I illustrate the graphics of one of the server **server1:**
![disks_operations](https://user-images.githubusercontent.com/11527999/72549289-790ce600-38a1-11ea-9428-20005ffab06b.png)

![cpu_usage](https://user-images.githubusercontent.com/11527999/72549299-7ca06d00-38a1-11ea-9e7b-fe6f7dc495cc.png)

- For the debugging, I dug `strace` output for each instance. 
I found the name of the biggest directory that I deleted before (the directory with millions of files) it has the name `pr.ru`
Then I count for every process `openat` files from the trace command. The `strace` worked 15 seconds for every instance.
_I disabled one of the instances for the comparing._

`server1 _instance1_`
```
DISABLED (for the test)
```

`server1 _instance2_`
```
# strace -f -p 29056 2>&1 |grep openat |grep pr.ru > /tmp/pr1.txt
# cat /tmp/pr1.txt |wc -l
3131

```
`server2 _instance1_`
```
# strace -f -p 27881 2>&1 |grep openat |grep pr.ru > /tmp/pr1.txt
#  cat /tmp/pr1.txt |wc -l
2257

```

`server2 _instance2_`
```
# strace -f -p 26817 2>&1 |grep openat |grep pr.ru > /tmp/pr2.txt
# cat /tmp/pr2.txt |wc -l
1113
```
The questions are:
- Is it normal behavior for the Minio cluster?
- Why did it happen just after deleting, but before it works perfectly (some kind of indexing? But why for all instances and so aggressive?)
- Can I minimize the IO operations?

**Comment by vadmeste** [comment]
@kislik how many CPU cores do you have in each server ?

**Comment by kislik** [comment]
> @kislik how many CPU cores do you have in each server ?

CPU: 8
model name      : Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz

**Comment by klauspost** [comment]
Probably related to #8711

**Comment by kislik** [comment]
@vadmeste Is it possible to down a Minio cluster and remove a directory from a bucket (I wanna do it from my OS with simple command `rm -rf`)? I want to prevent any disks operation for the fast deleting the directory that has a lot of files for preventing future indexing in the Minio cluster (when I will turn up my cluster)
