### ISSUE TITLE
Remove of groups does not work properly

### ISSUE THREAD

**Issue by philippjenni** [minio/minio#8841]
If i remove a user from a group, the user is not removed at all nodes in the cluster.
i remove the user with the command "mc admin group remove" from a windows 10 client. the server runs under ubuntu 18.04

command to remove
mc admin group remove minio mygroup myuser

command to check
mc admin user info minio myuser

Here an example out put:

```
D:\MinIo>mc admin user info exanic developer
AccessKey: developer
Status: enabled
PolicyName:
MemberOf: heidak-dev-write,newhome-build-write,newhome-dev-write,newhome-integration-write

D:\MinIo>mc admin user info exanic developer
AccessKey: developer
Status: enabled
PolicyName:
MemberOf: heidak-dev-write,newhome-build-write,newhome-dev-write

D:\MinIo>mc admin user info exanic developer
AccessKey: developer
Status: enabled
PolicyName:
MemberOf: heidak-dev-write,newhome-build-write,newhome-dev-write,newhome-integration-write

D:\MinIo>mc admin user info exanic developer
AccessKey: developer
Status: enabled
PolicyName:
MemberOf: heidak-dev-write,newhome-build-write,newhome-dev-write,newhome-integration-write

D:\MinIo>mc admin user info exanic developer
AccessKey: developer
Status: enabled
PolicyName:
MemberOf: heidak-dev-write,newhome-dev-write,newhome-integration-write,newhome-staging-write

D:\MinIo>mc admin user info exanic developer
AccessKey: developer
Status: enabled
PolicyName:
MemberOf: heidak-dev-write,newhome-build-write,newhome-dev-write,newhome-integration-write,newhome-staging-write
```
The commands were carried out one after the other

EDIT:  The Cluster is behind a loadbalancer ... So you can see many different nodes

## Expected Behavior
the user should removed from the group at all nodes inside the cluster

## Current Behavior
it looks like, that the user is only remove at the node it the command executed. In the logs at the server i cant found any exception

## Steps to Reproduce (for bugs)
1. Create a user and a group
2. Add the user to the group
3. Remove the user from the group
4. Check if the user is removed

## Your Environment

* Version used (`minio version`): 2020-01-16T22:40:29Z
* Environment name and version (e.g. nginx 1.9.1): 
* Server type and version: ubuntu 18.04 lts
* Operating System and version (`uname -a`): Linux vstorage01 4.15.0-62-generic #69-Ubuntu SMP Wed Sep 4 20:55:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kannappanr** [comment]
@philippjenni Thanks for reporting we will take a look.

**Comment by donatello** [comment]
I can confirm this bug exists. I am also working on a fix.

**Comment by philippjenni** [comment]
It's possible that the same problem exists if a file is deleted on a node?

EDIT: Ignore this comment. I have create a seperate issue.
