### ISSUE TITLE
mino gateway nas doesn't read credentials created by minio server

### ISSUE THREAD

**Issue by flixr** [minio/minio#8842]
Just changing `minio server /mountpoint` to `minio gateway nas /mountpoint` leads to the minio credentials not working anymore.
It seems gateway doesn't read them or expects them in a different location.

Changing it back to server and credentials are read again correctly.

## Expected Behavior
Running minio as `gateway nas` should work exactly the same as running as `server` (except for the disk usage calculation not being done in gateway mode).

## Current Behavior
Credentials like extra users are apparently not read at all, I only get an error that the credentials don't exist.

## Steps to Reproduce (for bugs)

1. Run `minio server /mountpoint`
2. Create some credentials/users
3. Stop minio and run as `minio gateway nas /mountpoint` instead
4. -> credentials are not valid anymore

## Context

I was running minio in server mode so far, but since this creates high CPU/memory spikes every 12h when disk usage stats are generated I wanted to switch to gatway nas mode.

## Regression

Probably yes -> maybe related to #6004

## Your Environment

* Version used (`minio version`): RELEASE.2020-01-16T22-40-29Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: docker image
* Operating System and version (`uname -a`): `Linux xxx 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Link to your project:

**Comment by harshavardhana** [comment]
This is working as expected you need to set environment variables for credentials as NAS gateway.

```
minio server /data
```

And 

```
minio gateway nas /data
```

Are different in behavior so they cannot be considered same.

**Comment by flixr** [comment]
I have the env vars `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY` set... always have.
Is there anything else I need to do?

What I expected is that the credentials for further users, bucket polices, etc. still work when switching to `gateway nas`.
This is clearly not the case, but why? To me this looks like a bug.

**Comment by flixr** [comment]
Ok, I misunderstood the docs.
I was using multi-user mode when I created/used other users... and that requires etcd.
It would be nice if this could be clarified/stated on the https://docs.min.io/docs/minio-gateway-for-nas.html page.

Closing this as it indeed works as expected then.
