### ISSUE TITLE
high CPU/memory usage when crawling disk usage

### ISSUE THREAD

**Issue by flixr** [minio/minio#8844]
I'm running minio (in server mode) on an edge server for local object storage.
Every 12h when disk usage is crawled this results in a peak of CPU/memory usage.
Since there are quite a few other things running on this edge node, this breaks my use case.

It was working fine with version RELEASE.2019-09-26T19-42-35Z

Related:
* documentation about this: #8722
* rss increase: #8664

## Expected Behavior

Disk usage calculation does NOT create high peaks in CPU/memory usage.

## Current Behavior

Disk usage calculation creates high peaks in CPU/memory usage.

## Possible Solution

Disk usage calculation should either run non-aggressively in the background (probably preferred) or an option provided to turn this feature off.

## Steps to Reproduce (for bugs)

1. run minio server
2. observe the high CPU/memory usage every 12h

## Context

This prevents me from using minio for local object storage on our edge nodes as these high peaks degrade the performance of the other processes running on the same edge node too much.

## Regression

For my use-case this is a clear regression.

## Your Environment

* Version used (`minio version`): `RELEASE.2020-01-16T22-40-29Z`
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: various smaller x86 edge nodes
* Operating System and version (`uname -a`): Linux
* Link to your project:

**Comment by kannappanr** [comment]
@flixr We will take a look at this issue and get back to you.

**Comment by flixr** [comment]
Profiling info run with latest mc build from source via `mc admin profile start --type cpu,mem,block`:
[profile.zip](https://github.com/minio/minio/files/4081323/profile.zip)

**Comment by harshavardhana** [comment]
Thanks we will take a look @flixr

**Comment by harshavardhana** [comment]
Looks like here are few locations where things are bad

```
~ (pprof) top10 --cum 
Showing nodes accounting for 136801.93MB, 5.82% of 2348970.12MB total
Dropped 768 nodes (cum <= 11744.85MB)
Showing top 10 nodes out of 94
      flat  flat%   sum%        cum   cum%
         0     0%     0% 1227741.06MB 52.27%  github.com/minio/minio/cmd.(*walker).doWork
         0     0%     0% 1227741.06MB 52.27%  github.com/minio/minio/cmd.(*walker).walk
         0     0%     0% 1225241.34MB 52.16%  github.com/minio/minio/cmd.readDirFn
136728.43MB  5.82%  5.82% 913793.40MB 38.90%  github.com/minio/minio/cmd.(*walker).onDirEnt
       1MB 4.3e-05%  5.82% 871884.58MB 37.12%  github.com/minio/minio/cmd.(*IAMObjectStore).loadAll
         0     0%  5.82% 871776.07MB 37.11%  github.com/minio/minio/cmd.(*IAMObjectStore).loadIAMConfig
         0     0%  5.82% 869399.34MB 37.01%  github.com/minio/minio/cmd.(*IAMObjectStore).watch.func1
   44.50MB 0.0019%  5.82% 856695.50MB 36.47%  github.com/minio/minio/pkg/madmin.DecryptData
         0     0%  5.82% 854247.74MB 36.37%  golang.org/x/crypto/argon2.IDKey
      28MB 0.0012%  5.82% 854247.74MB 36.37%  golang.org/x/crypto/argon2.deriveKey
(pprof)
```

```
~ top
Showing nodes accounting for 2016.37GB, 87.90% of 2293.92GB total
Dropped 768 nodes (cum <= 11.47GB)
Showing top 10 nodes out of 94
      flat  flat%   sum%        cum   cum%
  832.15GB 36.28% 36.28%   833.44GB 36.33%  golang.org/x/crypto/argon2.initBlocks
  364.79GB 15.90% 52.18%   539.81GB 23.53%  os.statNolog
  274.56GB 11.97% 64.15%   274.56GB 11.97%  time.NewTicker
  180.56GB  7.87% 72.02%   180.56GB  7.87%  syscall.ByteSliceFromString
  133.52GB  5.82% 77.84%   892.38GB 38.90%  github.com/minio/minio/cmd.(*walker).onDirEnt
   50.79GB  2.21% 80.05%    50.79GB  2.21%  strings.genSplit
   50.62GB  2.21% 82.26%    50.62GB  2.21%  strings.(*Builder).grow
   48.04GB  2.09% 84.36%    48.04GB  2.09%  github.com/minio/minio/cmd.parseDirEnt
   42.44GB  1.85% 86.21%    84.99GB  3.71%  github.com/minio/minio/cmd.splitN
   38.90GB  1.70% 87.90%    38.90GB  1.70%  path.(*lazybuf).append
```

```
~ (pprof) top
Showing nodes accounting for 2016.37GB, 87.90% of 2293.92GB total
Dropped 768 nodes (cum <= 11.47GB)
Showing top 10 nodes out of 94
      flat  flat%   sum%        cum   cum%
  832.15GB 36.28% 36.28%   833.44GB 36.33%  golang.org/x/crypto/argon2.initBlocks
  364.79GB 15.90% 52.18%   539.81GB 23.53%  os.statNolog
  274.56GB 11.97% 64.15%   274.56GB 11.97%  time.NewTicker
  180.56GB  7.87% 72.02%   180.56GB  7.87%  syscall.ByteSliceFromString
  133.52GB  5.82% 77.84%   892.38GB 38.90%  github.com/minio/minio/cmd.(*walker).onDirEnt
   50.79GB  2.21% 80.05%    50.79GB  2.21%  strings.genSplit
   50.62GB  2.21% 82.26%    50.62GB  2.21%  strings.(*Builder).grow
   48.04GB  2.09% 84.36%    48.04GB  2.09%  github.com/minio/minio/cmd.parseDirEnt
   42.44GB  1.85% 86.21%    84.99GB  3.71%  github.com/minio/minio/cmd.splitN
   38.90GB  1.70% 87.90%    38.90GB  1.70%  path.(*lazybuf).append
```

The offending part is largely os.statNoLog() 

```
~ (pprof) top10 --cum
Showing nodes accounting for 7556832273, 40.68% of 18577648869 total
Dropped 744 nodes (cum <= 92888244)
Showing top 10 nodes out of 118
      flat  flat%   sum%        cum   cum%
         0     0%     0% 14907108545 80.24%  github.com/minio/minio/cmd.(*walker).doWork
         0     0%     0% 14907108545 80.24%  github.com/minio/minio/cmd.(*walker).walk
         0     0%     0% 14859239751 79.98%  github.com/minio/minio/cmd.readDirFn
1413175489  7.61%  7.61% 11260931105 60.62%  github.com/minio/minio/cmd.(*walker).onDirEnt
         0     0%  7.61% 9895624410 53.27%  github.com/minio/minio/cmd.(*FSObjects).crawlAndGetDataUsageInfo.func1
         0     0%  7.61% 4253204903 22.89%  github.com/minio/minio/cmd.(*FSObjects).waitForLowActiveIO
4253204903 22.89% 30.50% 4253204903 22.89%  time.NewTicker
         0     0% 30.50% 3793509646 20.42%  os.Stat
1890451881 10.18% 40.68% 3793509646 20.42%  os.statNolog
         0     0% 40.68% 3601933839 19.39%  github.com/minio/minio/cmd.readDir
```

```
~ (pprof) top        
Showing nodes accounting for 15662783966, 84.31% of 18577648869 total
Dropped 744 nodes (cum <= 92888244)
Showing top 10 nodes out of 118
      flat  flat%   sum%        cum   cum%
4253204903 22.89% 22.89% 4253204903 22.89%  time.NewTicker
1964485833 10.57% 33.47% 1964485833 10.57%  syscall.ByteSliceFromString
1890451881 10.18% 43.64% 3793509646 20.42%  os.statNolog
1623549936  8.74% 52.38% 1623549936  8.74%  strings.genSplit
1436519659  7.73% 60.12% 1436519659  7.73%  github.com/minio/minio/cmd.parseDirEnt
1424026048  7.67% 67.78% 2851787762 15.35%  github.com/minio/minio/cmd.splitN
1413175489  7.61% 75.39% 11260931105 60.62%  github.com/minio/minio/cmd.(*walker).onDirEnt
 816034862  4.39% 79.78%  816034862  4.39%  strings.(*Builder).grow
 420789180  2.27% 82.05%  420789180  2.27%  path.(*lazybuf).string
 420546175  2.26% 84.31%  420546175  2.26%  path.(*lazybuf).append
```

**Comment by harshavardhana** [comment]
@flixr would it be possible for you to give a test binary a spin to calculate more memory profiling?

**Comment by harshavardhana** [comment]
~[minio.zip](https://github.com/minio/minio/files/4082364/minio.zip) can you test this? @flixr and grab `mem` profile again - thanks.~

**Comment by harshavardhana** [comment]
[minio.zip](https://github.com/minio/minio/files/4088939/minio.zip) - updated with the latest master and rebased - PTAL @flixr

**Comment by flixr** [comment]
@harshavardhana thanks for the quick iteration here.
Sorry, I'm super busy right now.. I will probably have time to test on Thursday...
Although I will need to go through the trouble to build this into a docker image first... or is there a nightly build of this available?

**Comment by harshavardhana** [comment]
> @harshavardhana thanks for the quick iteration here.
> Sorry, I'm super busy right now.. I will probably have time to test on Thursday...
> Although I will need to go through the trouble to build this into a docker image first... or is there a nightly build of this available?

@flixr if docker is all you need here you go `y4m4/minio:dev` :cake:

**Comment by flixr** [comment]
:+1: perfect, that makes it easy... profiling started...

**Comment by flixr** [comment]
Did the schedule change? I now only saw this peak once...:
[profile.zip](https://github.com/minio/minio/files/4097338/profile.zip)

**Comment by vadmeste** [comment]
@flixr crawling is scheduled each 12 hours, restarting the cluster won't automatically start crawling until the 12 hours will elapse

**Comment by harshavardhana** [comment]
Okay looks like now all parts are optimized the one which we cannot optimize is os.Stat() call itself

```
(pprof) top10 --cum
Showing nodes accounting for 392959.81MB, 19.43% of 2022355.07MB total
Dropped 644 nodes (cum <= 10111.78MB)
Showing top 10 nodes out of 128
      flat  flat%   sum%        cum   cum%
         0     0%     0% 573835.13MB 28.37%  os.Stat
392848.30MB 19.43% 19.43% 573835.13MB 28.37%  os.statNolog
         0     0% 19.43% 573486.38MB 28.36%  github.com/minio/minio/cmd.(*walker).doWork
         0     0% 19.43% 573486.38MB 28.36%  github.com/minio/minio/cmd.(*walker).walk
         0     0% 19.43% 573486.38MB 28.36%  github.com/minio/minio/cmd.readDirFn
       5MB 0.00025% 19.43% 554895.99MB 27.44%  github.com/minio/minio/cmd.(*IAMObjectStore).loadAll
         0     0% 19.43% 554476.25MB 27.42%  github.com/minio/minio/cmd.(*IAMObjectStore).loadIAMConfig
         0     0% 19.43% 552380.62MB 27.31%  github.com/minio/minio/cmd.(*IAMObjectStore).watch.func1
  106.50MB 0.0053% 19.43% 540736.10MB 26.74%  github.com/minio/minio/pkg/madmin.DecryptData
         0     0% 19.43% 534813.18MB 26.45%  golang.org/x/crypto/argon2.IDKey
```

The in_use memory is in around 200MiB's - allocation seems to be higher only in os.Stat() - I think we have reached the potential of optimizing here

How does your graph look like @flixr ?

**Comment by flixr** [comment]
I don't see any noticeable difference in memory usage:

![Selection_010](https://user-images.githubusercontent.com/104257/73086986-f9e76580-3ed1-11ea-8758-aba9b4b31418.png)

Profiling data:
[profile.zip](https://github.com/minio/minio/files/4109586/profile.zip)

But base CPU load seems to be lower now... not really sure why.
But the problematic CPU peaks are also still there.

Would you consider an option to turn this feature off?

**Comment by harshavardhana** [comment]
@flixr that won't be possible, we can't turn it off. You just have to provide more memory. The CPU spike has gone down because of reduced allocations in certain hot paths.

There are two more portions to optimize i.e

- Go's os.Stat() is using unusually large amount of memory.
- Go's argon2 uses 64MiB per IAM user (I am assuming you have some amount of users in this setup)

**Comment by flixr** [comment]
It's not only about the memory...
CPU peaks didn't go down, rather slightly more... "just" the CPU usage when disk usage is not crawled went down a bit (the new dev version was deployed at 19:45 in this graph where the "ripples" get less):
![Selection_012](https://user-images.githubusercontent.com/104257/73089983-b132ab00-3ed7-11ea-8cb1-8cebb6822c78.png)
