### ISSUE TITLE
MinIO gateway from ~/.aws/config

### ISSUE THREAD

**Issue by solracsf** [minio/minio#8853]
[Docs states](https://github.com/minio/minio/blob/master/docs/gateway/s3.md#using-binary-in-ec2) that:

    MinIO gateway will automatically look for list of credential styles in following order, if your backend URL is AWS S3.

    AWS env vars (i.e. AWS_ACCESS_KEY_ID)
    AWS creds file (i.e. AWS_SHARED_CREDENTIALS_FILE or ~/.aws/credentials)

I was expecting that it also reads `~/.aws/config`

    [default]
    region = nl-ams
      s3 =
        endpoint_url = https://s3.nl-ams.scw.cloud
        signature_version = s3v4
        max_concurrent_requests = 100
        max_queue_size = 1000
        multipart_threshold = 50MB
        multipart_chunksize = 10MB
    s3api =
        endpoint_url = https://s3.nl-ams.scw.cloud

and `~/.aws/credentials`

    [default]
    aws_access_key_id=<ACCESS_KEY>
    aws_secret_access_key=<SECRET_KEY>

would be read by `minio gateway s3`, but they aren't:

    ERROR Unable to validate credentials inherited from the shell environment: Invalid credentials
      > Please provide correct credentials
      HINT:
        Access key length should be at least 3, and secret key length at least 8 characters

Non-implemented or bug?

**Comment by harshavardhana** [comment]
It is expected to be not implemented @acs-ferreira we are not planning to increase the scope here for gateway.

Its feature complete and stable not taking any more changes for near future, unless there are bugs.

**Comment by solracsf** [comment]
So `~/.aws/credentials` is read but not `~/.aws/config`, right?

**Comment by harshavardhana** [comment]
Correct it's never meant to be read.

**Comment by solracsf** [comment]
Ok, closing, thanks @harshavardhana

**Comment by solracsf** [comment]
Sorry to ask @harshavardhana but having  `~/.aws/credentials` set why `minio gateway s3 https://s3.fr-par.scw.cloud` outputs the same error? Am i missing something here?
```
[default]
aws_access_key_id=<ACCESS_KEY>
aws_secret_access_key=<SECRET_KEY>
```
