### ISSUE TITLE
how to mount the S3 data on local 

### ISSUE THREAD

**Issue by hahahaL** [minio/minio#8860]
------
------
If I use the minio like a data-center,the scenes is that windonw’platflot use the data to do some computes,my way is to use s3fs let the server mount on one node,and use samba or nfs to share the data,do you have the better way to do these let the data can invent and used

**Comment by harshavardhana** [comment]
There are no plans to support mountable filesystem for MinIO, you need to use the S3 API directly to make rest calls.

Closing this as out of scope.

**Comment by jbarotin** [comment]
Hi, have you tried https://github.com/kahing/goofys ?
