### ISSUE TITLE
The mc retention doesn't work

### ISSUE THREAD

**Issue by hahahaL** [minio/minio#8861]
ENV: RELEASE.2020-01-03T20-33-14Z
------
I do that like documention,which step I do the wrong,why I still can rm the data?
[@localhost minio]# mc retention haha/one/prefix compliance 30d
Object retention successfully set for prefix `haha/one/prefix`.

[@localhost minio]# mc cp ./nginxdir haha/one/prefix/
./nginxdir:            8 B / 8 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 112 B/s 0

[root@localhost minio]# mc rm haha/one/prefix/a.csv
Removing `haha/one/prefix/a.csv`.

**Comment by harshavardhana** [comment]
Retention is applied on existing objects what you want is `mc lock` 

It's working as intended.
