### ISSUE TITLE
Why isn't environment variable MINIO_NOTIFY_KAFKA_ENABLE documented?

### ISSUE THREAD

**Issue by amitga** [minio/minio#8863]
I am trying to enable Minio notifications to Kafka using the `MINIO_NOTIFY_KAFKA_BROKERS` and `MINIO_NOTIFY_KAFKA_TOPIC` environment variables, as documented (in docs, and in `mc` command line).

## Expected Behavior

Minio should configure notifications to Kafka accordingly.

## Current Behavior

Minio ignores these env vars, and notification to Kafka is not set (looking at the logs, no mention of the SQS).
## Possible Solution

- Using `mc` to configure the Minio instance with notification to Kafka works fine.

- Browsing the code, I found this environment variable: `MINIO_NOTIFY_KAFKA_ENABLE`. 
Setting it to "true" makes Minio read the `MINIO_NOTIFY_KAFKA_BROKERS` and `MINIO_NOTIFY_KAFKA_TOPIC` environment variables, and configure the `notify_kafka` feature.
I didn't find it mentioned anywhere in the docs! Why isn't it documented? Did I miss something?
## Steps to Reproduce (for bugs)

1. Run an instance of Minio server using Docker (or locally), set env vars `MINIO_NOTIFY_KAFKA_BROKERS` and `MINIO_NOTIFY_KAFKA_TOPIC` accordingly.
2. Look at logs of Minio, see if SQS is mentioned.

## Context

I have spent alot of time trying to get the notification to work. The lack of documentation of this environment variable caused this. The docs are not that clear in this area.
I suppose this might affect other types of notification targets (having relevant `MINIO_NOTIFY_*_ENABLE` variable that isn't documented).

## Your Environment

* Version used (`minio version`): Docker image:  `minio/minio:RELEASE.2020-01-16T22-40-29Z`
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): Ubuntu 16.04
* Link to your project:

**Comment by nitisht** [comment]
Thanks for reporting @amitga-rnd we'll take a look
