### ISSUE TITLE
Assume-role inline policy does not work properly

### ISSUE THREAD

**Issue by elliott-wen** [minio/minio#8865]
The inline policy in Asume-role seems not working properly.
An example code as follows, where the inline policy denies all actions. However, the temporary credential is still able to carry out putObject operations.
The parent accesskey/secret has Get/Put/Del Object permissions.

```
"use strict";
var AWS = require('aws-sdk');
// Set the Region 
var sts = new AWS.STS({ apiVersion: '2011-06-15',
    accessKeyId: "parentkey",
    secretAccessKey: "parentSecret",
    endpoint: "http://xxxx",
    region: 'us-east-1'
});
var params = {
    Policy: '{"Version":"2012-10-17","Statement":[{"Sid":"Stmt1","Effect":"Deny","Action":"s3:*", "Principal": "*", "Resource":"arn:aws:s3:::*"}]}',
    RoleArn: "arn:xxx:xxx:xxx:xxxx",
    RoleSessionName: "anything",
};
sts.assumeRole(params, function (err, data) {
    if (err)
        console.log(err, err.stack); // an error occurred
    else {
        var keyid = data['Credentials']['AccessKeyId'];
        var secret = data['Credentials']['SecretAccessKey'];
        var token = data['Credentials']['SessionToken'];
        var s3 = new AWS.S3({
            accessKeyId: keyid,
            secretAccessKey: secret,
            sessionToken: token,
            endpoint: "http://xxxx",
            s3ForcePathStyle: true,
            signatureVersion: 'v4'
        });
        var bucketParams = { Bucket: "test",
            Key: "hello.txt",
            Body: "hello world"
        };
        //Put Object should be denied. 
        s3.putObject(bucketParams, function (err, data) {
            if (err) {
                console.log("Error", err);
            }
            else if (data) {
                console.log("Success", data);
            }
        });
    }
});


```
## Your Environment
* Version used (`minio version`): Minio Docker latest image.
* Environment name and version (e.g. nginx 1.9.1): Ubuntu 18.04

**Comment by harshavardhana** [comment]
This behavior is the same as AWS IAM @elliott-wen inline policies cannot override their parent policies. Because in this manner you can gain write access where your parents might have denied.

It is different than having two implicit deny with two statements, both are not the same.

**Comment by elliott-wen** [comment]
Thanks. Kindly let me make myself understood again.

My parent policy has put/get/del permissions. I want my inline policy to
deny put/del operations.

In other words I just want get permission in temp credentials obtained.

I didn't ask for extra permissions but just want part of parents
permissions.

Cheers
Elliott

**Comment by harshavardhana** [comment]
>     Policy: '{"Version":"2012-10-17","Statement":[{"Sid":"Stmt1","Effect":"Deny","Action":"s3:*", "Principal": "*", "Resource":"arn:aws:s3:::*"}]}',

You policy is not doing that @elliott-wen

**Comment by elliott-wen** [comment]
Could you kindly point out a direction?

I have tried Policy: '{"Version":"2012-10-17","Statement":[{"Sid":"Stmt1","
Effect":"Allow","Action":"s3:GetObject", "Principal": "*",
"Resource":"arn:aws:s3:::*"}]}',

But it still doesnt work.

Cheers
Elliott
