### ISSUE TITLE
wrong calculate used capacity of uploaded file

### ISSUE THREAD

**Issue by invent-lwj** [minio/minio#8866]
I uploaded a file, but display twice of the actually size of file in UI. I am deployed with distributed mode. 4 nodes on openshift. image is latest of Jan 17 2020.
<img width="1081" alt="Screen Shot 2020-01-21 at 09 24 46" src="https://user-images.githubusercontent.com/20390953/72767724-f46af080-3c2f-11ea-9e4a-1fc00ed08ac8.png">

## Expected Behavior
Display file size actually

## Current Behavior
I uploaded a file, but display twice of the actually size of file in UI. I am deployed with distributed mode. 4 nodes on openshift.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):  latest of Jan 17 2020 on dockerhub
* Environment name and version (e.g. nginx 1.9.1): no nginx, deploy on openshift.
* Server type and version:
* Operating System and version (`uname -a`): openshift 4.2
* Link to your project:

**Comment by harshavardhana** [comment]
The usage is showing disk usage which is twice the object size.
