### ISSUE TITLE
I can't find an official page to list all policy actions which are supported by MiniO

### ISSUE THREAD

**Issue by tanvstan** [minio/minio#8869]
**Is your feature request related to a problem? Please describe.**
I can't find an official page to list all policy actions which are supported by MiniO. And describe their resource targets, related operations, etc. 

**Describe the solution you'd like**
Could you provide an online page to list them? 
Like AWS has done: https://docs.aws.amazon.com/AmazonS3/latest/dev/using-with-s3-actions.html

**Describe alternatives you've considered**
Or provide a mc command to do so?

**Additional context**
NA

**Comment by harshavardhana** [comment]
Other that Torrent, Acl, Versioning we implement all other APIs

**Comment by harshavardhana** [comment]
Check here https://docs.min.io/docs/minio-server-limits-per-tenant.html

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/blob/master/pkg/iam/policy/action.go#L31 here is another list.

**Comment by tanvstan** [comment]
Thanks for your reply, Harshavardhana.

**Comment by kannappanr** [comment]
@tanvstan Closing this issue as answered Please feel free to reach out to us https://slack.min.io for further questions
