### ISSUE TITLE
Slack is not a suitable platform for open source software collaboration

### ISSUE THREAD

**Issue by ddevault** [minio/minio#8874]
Please ditch Slack or bridge with a better platform, such as IRC or Matrix.

Slack is proprietary, eschews open source integrations, and holds your data hostage. Participation in the Slack channel requires users and contributors to utilize closed source clients which require obscene amounts of resources (RAM, CPU, disk space, etc) to run. It's not appropriate to host open source projects on Slack.

**Comment by kannappanr** [comment]
@ddevault Thanks for the suggestion. We will review the request internally and see what can be done. Closing this issue for now.
