### ISSUE TITLE
Missing test suite

### ISSUE THREAD

**Issue by feld** [minio/minio#8875]
Where is the test suite that validates all of Minio's functions and API calls are returning expected results?

**Comment by harshavardhana** [comment]
@feld https://github.com/minio/minio/tree/master/mint

**Comment by feld** [comment]
OK, so where's the test that proves deleting files works as expected? i.e., #8873

**Comment by harshavardhana** [comment]
> OK, so where's the test that proves deleting files works as expected? i.e., #8873

It's there in all SDKs @feld and mint runs each SDKs against each PR

**Comment by feld** [comment]
Is the test buggy then? Because deleting doesn't work. This is an obvious bug to catch, so something is wrong with the test environment. Should I file a PR for someone to fix the test?

**Comment by harshavardhana** [comment]
> Is the test buggy then? Because deleting doesn't work. This is an obvious bug to catch, so something is wrong with the test environment. Should I file a PR for someone to fix the test?

You should open a separate issue with reproducible steps if the steps are already in #8873 we should continue our discussion there, we will try to see what is the environment and give you an analysis.

There is nothing wrong in our test environment, deletes are working fine AFAICS. Let's continue our discussion on a relevant issue with reproducible steps.
