### ISSUE TITLE
Implement service accounts for regular users

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#8893]
**Is your feature request related to a problem? Please describe.**
Allow credentials to be generated for regular users created using `mc admin user`. 
This allows external SSO such as LDAP users, OpenID users to create more 
credentials with inherited permissions on MinIO. 

**Describe the solution you'd like**
These credentials will inherit the same permissions as its parent `user` or can
be further restricted with special policies. These credentials are similar to STS
but without any explicit expiry. 

**Describe alternatives you've considered**
There is no alternative right now, AWS implements this in a bit poor manner with
lots of API level complications but we can implement it cleanly.

**Additional context**
Primarily to allow static credentials support based on MinIO multi-users.

**Comment by vadmeste** [comment]
Fixed by https://github.com/minio/minio/pull/9029
