### ISSUE TITLE
Can't get MC to work on Windows

### ISSUE THREAD

**Issue by labnewbie** [minio/minio#8899]
When I start the minio service from the command line it starts fine.

PS C:\Users\administrator.HOMELAB> minio server c:\minio\data
Endpoint:  http://192.168.86.133:9000  http://127.0.0.1:9000      

Browser Access:
   http://192.168.86.133:9000  http://127.0.0.1:9000      

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

I was able to add the minio service with no errors:
PS C:\Users\administrator.HOMELAB> mc config host add minio http://192.168.86.133 admin admin1234 --api S3v4
Added `minio` successfully.

But whenever I try any MC commands the command seems to timeout with the following error:
PS C:\Users\administrator.HOMELAB> mc admin info minio
mc : mc.exe: <ERROR>  Cannot get service status
At line:1 char:1
+ mc admin info minio
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (mc.exe: <ERROR>... service status:String) [], Remote 
   Exception
    + FullyQualifiedErrorId : NativeCommandError

This has been working fine since May of 2019, but I recently updated the minio server/client to test the object lock capabilities.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
PS C:\Users\administrator.HOMELAB> mc --version
mc version RELEASE.2020-01-25T03-02-19Z

* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
Windows VM
* Operating System and version (`uname -a`):
Windows 2016
* Link to your project:

**Comment by kannappanr** [comment]
The command should be `mc config host add minio http://192.168.86.133:9000 admin admin1234 --api S3v4` You are hitting `minio` at port `80` while it is running at port `9000`

**Comment by kannappanr** [comment]
@labnewbie closing this issue as answered. please feel free to reach out to us at https://slack.min.io for further questions
