### ISSUE TITLE
400s requests for objects beginning with "%2F"

### ISSUE THREAD

**Issue by blottn** [minio/minio#8902]
When performing a `GetObject` request for a key beginning with a `%2F` in the URL the response is always 400 as it interprets this to be referring to an api endpoint (full error attached). Apparently this should be an acceptable start to an object as s3 handles this just fine.

## Expected Behavior
A 404 if the object doesn't exist or a 200 and the `s3Object` if the object does exist.
Example expected response:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>NoSuchKey</Code>
    <Message>The specified key does not exist.</Message>
    <Key>/testKey</Key>
    <RequestId>BDC415F5C40A180C</RequestId>
    <HostId>nc1KSQn4HDoFIqjcGBAvd0w6ERjWFOWyc01pP/A0FaXZx9+iEq9iK3szNF8CgJ5Ck+9Q5D4c42o=</HostId>
</Error>
```
## Current Behavior
Currently returns a 400 with this body:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>XMinioUnknownAPIRequest</Code>
    <Message>Unknown API request at //testKey</Message>
    <Resource>//testKey</Resource>
    <RequestId>15EE1750BADDE4BC</RequestId>
    <HostId>a6472c26-7a30-482a-8c47-4bf0f160ede0</HostId>
</Error>
```

## Possible Solution
It is likely todo with how paths are decoded but I'm not sure of the implementation specifics

## Steps to Reproduce (for bugs)
1. Run minio (In this case I used: `docker run -p 80:9000 minio/minio server --compat /data`
2. Create a bucket (my reproduction script uses the name `snap`)
3. Download my reproducing script (depends on `pytz` and `requests`) [script here](https://gist.github.com/blottn/79829639ec88303e88795eb41f12a881)
3. Run with python2.7 `python minio-breaking.py`

## Context
This is preventing using minio as a gateway to export snapshots from hbase to s3. It would be possible to just use S3 directly but we would prefer if we could use minio as we also want to use google cloud storage.

## Regression
No

## Your Environment
* Version used (`minio version`): RELEASE.2020-01-16T22-40-29Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: Running on a mac laptop
* Operating System and version (`uname -a`): `Darwin blottn 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64`
* Link to your project: Not available

**Comment by harshavardhana** [comment]
We don't support `/` in the same manner as AWS S3. So you can never create a key with `/` at the beginning.

Fix your client application to do not prepend an unnecessary `/`

**Comment by blottn** [comment]
Thanks for the quick reply
