### ISSUE TITLE
[resolved] Need to have a design document for Healing

### ISSUE THREAD

**Issue by Praveenrajmani** [minio/minio#8904]
This is to specifically ease the reviewing of healing related PRs. As we know, healing has more asynchronous decoupled tasks which we need to keep track to join our thoughts (specially during the review)

A design documentation, maybe with a design diagram would help to understand the process and differences between self-healing and admin-healing

Ideally we can keep track of the fore coming changes in the doc as well.

**Comment by Praveenrajmani** [comment]
cc @vadmeste

**Comment by klauspost** [comment]
@Praveenrajmani It seems like we will be doing a refactor of the healing process to make it more oriented towards continuous healing. So it would be reasonable to do alongside that.

**Comment by harshavardhana** [comment]
Continous healing is merged in #10103
