### ISSUE TITLE
Alternative method to create certs other than GnuTLS for Windows?

### ISSUE THREAD

**Issue by labnewbie** [minio/minio#8906]
I am having issues with the GnuTLS utility to create my private/public keys.  Do you recommend any other tools?  I tried OpenSSL, but your instructions don't have the configurations for Windows listed.  I tried using the linux example for OpenSSL, but with no success.
## Expected Behavior

No errors when creating the keys via GnuTLS

## Current Behavior

This is what I see:
c:\GnuTLS>certtool.exe --generate-privkey --outfile private.key
Generating a 3072 bit RSA private key...
c:\GnuTLS>certtool.exe --generate-self-signed --load-privkey private.key --template cert.cnf --outfile public.crt
libopts error 0 (No error) calling read for 'cert.cnf'
configFileLoad: Unknown error
Error loading template: cert.cnf

## Steps to Reproduce (for bugs)

1. This is the contents of my cert.cnf file:
organization = "Homelab" 
state = "NY" 
country = "US" 
cn = "John Smith" 
expiration_days = 365 
dns_name = "localhost" 
ip_address = "192.168.86.133" 
tls_www_server

## Context

Trying to generate keys to use minio with https

## Your Environment

* Version used (`minio version`): 
mc version RELEASE.2020-01-25T03-02-19Z

* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
Windows 2016 vm

* Operating System and version (`uname -a`):
Windows 2016

* Link to your project:

**Comment by kannappanr** [comment]
You can also try https://github.com/FiloSottile/mkcert for Windows. Please reach out to us at https://slack.min.io for further questions. closing this issue as answered.
