### ISSUE TITLE
TLS issues: mc client works from windows, but fails on linux (needs --insecure)

### ISSUE THREAD

**Issue by laymonk** [minio/minio#8907]
Server has a valid SSL certificate, with necessary chains in place and has generally been working.

Running mc commands from windows works, and I have not had to 'trust' the certs on windows (mc\certs and mc\certs\CAs are both empty).

However, running mc commands on linux to the same Minio server using identical config.json (ubuntu ... tried 2 different systems), I get:
>  x509: certificate signed by unknown authority

The only way commands work on linux is if I add in '--insecure'

## Expected Behavior

mc commands should work the same on linux as windows 

## Current Behavior

Doesn't work on linux, except '--insecure' is used 

## Possible Solution
Use '--insecure' in every command

## Steps to Reproduce (for bugs)

1. install mc client
2. eith copy in config.json or create one with 'mc config' commands

## Context

Cannot use mc client on linux as expected

## Regression
Not sure 

## Your Environment

* Version used (`minio version`):  Version: 2019-10-12T01:39:57Z
* Operating System and version (`uname -a`):  Debian Buster (10.2)

**Comment by laymonk** [comment]
Just adding that:
* I added linux packages with CA certificates: ca-certificates and ca-cacert 
* I also ran `sudo update-ca-certificates` for good measure
* I have no other ssl client or TLS issues on these 2 systems where I tested it

**Comment by laymonk** [comment]
More info ... turns out the linux client is even more recent than the windows client:

* linux client: `RELEASE.2019-10-09T22-54-57Z`
* windows client: `RELEASE.2019-01-10T00-38-22Z`

I have just updated both (windows and linux) to `RELEASE.2020-01-25T03-02-19Z`

Now on windows, ls works fine but user management commands don't work:
> mc: <ERROR> Cannot list user. Failed to parse server response.

On linux, the command doesn't even return.  Running it under strace shows and endless epoll_pwait until some timeout is reached :
> [pid 16138] epoll_pwait(4, [{EPOLLOUT, {u32=634011304, u64=139866244005544}}], 128, -1, NULL, 3) = 1

Guess it seems there have been major changes in the mc client that I have to adjust to first ...

**Comment by laymonk** [comment]
Updated server to `RELEASE.2020-01-25T02-50-51Z`, and now windows user and group commands, along with all other sub-commands are working as expected again.

Linux client is not even running OK, talk-less of demanding '--insecure' ... will resolve this first and update this ticket.

**Comment by kannappanr** [comment]
@laymonk You need to update your Linux `mc` client. please download the latest from https://dl.minio.io/client/mc/release/linux-amd64/mc

Please look at https://tarunlalwani.com/post/self-signed-certificates-trusting-them/ to get the self signed certificate trusted by your mc client machine.

Please feel free to reach out to us at https://slack.min.io for further questions

**Comment by laymonk** [comment]
@kannappanr, million thanks for responding.

> @laymonk You need to update your Linux mc client. please download the latest from https://dl.minio.io/client/mc/release/linux-amd64/mc

I already had the latest (RELEASE.2020-01-25T03-02-19Z), and just downloaded and installed it again for good measure.  The only response I can get from this binary is '--version' or '--help' ... any interactions that involves navigating ~/.mc or interacting with a server, just hangs (exactly as I reported above) ... Linux host is ubuntu server 18.04.

> Please look at https://tarunlalwani.com/post/self-signed-certificates-trusting-them/ to get the self signed certificate trusted by your mc client machine.

I am not using a self-signed certificate, but a valid SSL certificate with all the appropriate SANs and chains in there ... mc on windows sees the certificates as valid and works well.  mc on linux doesn't, and that is my issue.

**Comment by vadmeste** [comment]
@laymonk does curl under your Linux distribution show the same problem ?

**Comment by harshavardhana** [comment]
You don't need to add your cert part of system cert, some OS do things differently and doesn't work all the time.

Better just drop your server public.crt into `~/.mc/certs/CAs` - mc will automatically trust the server cert.

This will work in a platform independent way.

**Comment by harshavardhana** [comment]
Closing this issue - the recommended approach is to use `~/.mc/certs/CAs`
