### ISSUE TITLE
Minio metadata normalizes characters differently from S3

### ISSUE THREAD

**Issue by vibbix** [minio/minio#8930]
When attaching metadata to a object, the key name doesn't normalize to all lowercase like it does on AWS S3.

## Expected Behavior
![java lang AssertionError](https://user-images.githubusercontent.com/1731900/73698703-e1383600-46af-11ea-84b3-83a9cc7b059d.png)
## Current Behavior
![java lang AssertionError 2](https://user-images.githubusercontent.com/1731900/73698700-e0070900-46af-11ea-8782-f5bf1e960bad.png)

## Possible Solution
In the meantime, i enforce all lower case values, but it's pretty hacky.

## Steps to Reproduce (for bugs)
1. upload a object with user metadata like `ImmutableMap.of("key1", "value1", "key2", "value2", "KEY3", "VALUE3");`
2. On a minio server it returns `ImmutableMap.of("Key1", "value1", "Key2", "value2", "Key3", "VALUE3");` when it should be returning `ImmutableMap.of("key1", "value1", "key2", "value2", "key3", "VALUE3");`

## Context
Using the S3 Client with minio server still causes this, so some tests are failing.

## Your Environment
MinIO/RELEASE.2019-07-10T00-34-56Z
CentOS 8

**Comment by harshavardhana** [comment]
This is not a bug http headers are case insensitive and metadata is case insensitive because it is a HTTP header and cannot preserve it.

Key1 is same as key1. This is true with AWS S3 as well it doesn't preserve them differently.

**Comment by vibbix** [comment]
Thanks for the clarification!

**Comment by kannappanr** [comment]
@vibbix What you are saying is also true for AWS S3. As described by @harshavardhana `http headers` are case insensitive, so you should modify your test cases to reflect the fact that they are case insensitive.
