### ISSUE TITLE
STS AssumeRoleWithWebIdentity with multiple JWT audiences

### ISSUE THREAD

**Issue by matteo-s** [minio/minio#8933]
When using an OIDC provider, Minio expects JWT tokens to contain a ``string`` claim for audiences. When the IdP returns an array the resulting tokens emitted by minio for STS won't work.

## Expected Behavior
As per OpenID Connect Core specification, ``aud`` can either be a single *string*, in which case it should match the *client_id*, or it can be an *array of strings*, which should contain the *client_id* among the others.

See https://openid.net/specs/openid-connect-core-1_0.html#IDToken

## Current Behavior
The call to AssumeRole works correctly, Minio STS delivers a set of credentials and a sessionToken, but subsequent calls with this token will result in error, caused by the presence of an array of strings in the ``aud`` claim.

## Possible Solution
Analyze the claim to establish if *client_id* should exacly match *aud* as string or if *aud* should contain *client_id*

## Steps to Reproduce (for bugs)
1. Configure an OpenID provider to return multiple audiences as string array, as per spec
2. Configure minio with **identity_openid client_id** 
3. Try to access via Minio Browser, the login will happen but the subsequent calls to /webrpc with the sessionToken will receive a ``401 Unauthorized`` response.
4. Observe the traffic and the JWT

server trace
```
172.17.0.1 [RESPONSE] [13:21:30.236] [ Duration 211µs  ↑ 96 B  ↓ 218 B ]
172.17.0.1 200 OK
172.17.0.1 Server: MinIO/RELEASE.2020-01-25T02-50-51Z
172.17.0.1 Vary: Origin
172.17.0.1 X-Amz-Request-Id: 15F035ADE772A829
172.17.0.1 X-Xss-Protection: 1; mode=block
172.17.0.1 Accept-Ranges: bytes
172.17.0.1 Content-Length: 0
172.17.0.1 Content-Security-Policy: block-all-mixed-content
172.17.0.1 
172.17.0.1 
localhost [REQUEST (*sts).AssumeRoleWithWebIdentity-fm] 13:23:45.589
localhost POST /?Action=AssumeRoleWithWebIdentity&Version=2011-06-15&WebIdentityToken=eyJraWQiOiJ0ZXN0MSIsImFsZyI6IlJTMjU2In0.eyJhdF9oYXNoIjoib0RBRDV0MThtMGlqVS1rdlpZRHhSZyIsInN1YiI6IjE3IiwiYXVkIjpbImRhODgxZDgwLTJhYjktNGZhOC1iYTQ2LTQzMTU4Y2UwNjYyNCIsImNhcmJvbi5zdXBlci1BQUMtMS4wLjAiXSwiYXpwIjoiZGE4ODFkODAtMmFiOS00ZmE4LWJhNDYtNDMxNThjZTA2NjI0Iiwia2lkIjoidGVzdDEiLCJpc3MiOiJodHRwOlwvXC8xOTIuMTY4LjQyLjYxOjkwOTBcL2FhYyIsImV4cCI6MTU4MDgyNjIyMiwiaWF0IjoxNTgwODIyNjI1LCJub25jZSI6IkxtcGFNWEdNaFk5bEJxTHIiLCJqdGkiOiI2MjZlMTE5ZC0wZGM4LTRiMWItYTdmNS0wNjllZWFjMWRhMmMiLCJwb2xpY3kiOiJyZWFkd3JpdGUifQ.R2iYMvSJuXPm96_hvOF2OIjmgABmbqVuGcgAAgGGAlj8TpKD32BE-G41ukayj2coXzOdsfTY_jpyX9CF6entJUu_-qAIp-EYp6Evfm0dENn0zKms0cH-pzlaktUJx476yxVGn55L5C-YHC52jzkOeZ5TXEEoEgiyVZ9_lNMe9vgSbGhHgLXysDD_8eCm3RMrtkJ3DIroSkI1IeeKfe_L_TvpQA2X2Vq82OdlLDbR80op50yyFEcyu9-o5A6W4bYatUYwt4O7SJRb5agNkcsC18uKMh1RNA0mFknb_NRc9TpUFyJM8BlZUlAVQMMCES9l17Vg2ucnagJBsFHR-B9rpg
localhost Host: localhost:9000
localhost Content-Length: 0
localhost User-Agent: Go-http-client/1.1
localhost 
localhost [RESPONSE] [13:23:45.638] [ Duration 49ms  ↑ 31 B  ↓ 1.5 KiB ]
localhost 200 OK
localhost Content-Length: 1290
localhost Content-Security-Policy: block-all-mixed-content
localhost Content-Type: application/xml
localhost Server: MinIO/RELEASE.2020-01-25T02-50-51Z
localhost Vary: Origin
localhost X-Amz-Request-Id: 15F035CD6B28CF40
localhost X-Xss-Protection: 1; mode=block
localhost Accept-Ranges: bytes
localhost <?xml version="1.0" encoding="UTF-8"?>
<AssumeRoleWithWebIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"><AssumeRoleWithWebIdentityResult><AssumedRoleUser><Arn></Arn><AssumeRoleId></AssumeRoleId></AssumedRoleUser><Credentials><AccessKeyId>9S10E7MOOZWUUGHP7BKL</AccessKeyId><SecretAccessKey>MC3xGqBX9MojRZJoOgoMvYF+SXb2uX9NBcdEDukH</SecretAccessKey><Expiration>2020-02-04T14:23:42Z</Expiration><SessionToken>eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiI5UzEwRTdNT09aV1VVR0hQN0JLTCIsImF0X2hhc2giOiJvREFENXQxOG0waWpVLWt2WllEeFJnIiwiYXVkIjpbImRhODgxZDgwLTJhYjktNGZhOC1iYTQ2LTQzMTU4Y2UwNjYyNCIsImNhcmJvbi5zdXBlci1BQUMtMS4wLjAiXSwiYXpwIjoiZGE4ODFkODAtMmFiOS00ZmE4LWJhNDYtNDMxNThjZTA2NjI0IiwiZXhwIjoxNTgwODI2MjIyLCJpYXQiOjE1ODA4MjI2MjUsImlzcyI6Imh0dHA6Ly8xOTIuMTY4LjQyLjYxOjkwOTAvYWFjIiwianRpIjoiNjI2ZTExOWQtMGRjOC00YjFiLWE3ZjUtMDY5ZWVhYzFkYTJjIiwia2lkIjoidGVzdDEiLCJub25jZSI6IkxtcGFNWEdNaFk5bEJxTHIiLCJwb2xpY3kiOiJyZWFkd3JpdGUiLCJzdWIiOiIxNyJ9.1c1tN0M1Gh6IeM1H-Tro8bo0rFGmLozItO5xIH6Q_u4CVrJ1INe341zhALVPxnNSGIa0bgAWWbHrMGG9TV7i1Q</SessionToken></Credentials><SubjectFromWebIdentityToken>17</SubjectFromWebIdentityToken></AssumeRoleWithWebIdentityResult><ResponseMetadata><RequestId>15F035CD6B28CF40</RequestId></ResponseMetadata></AssumeRoleWithWebIdentityResponse>
```

Token decoded 
```
{
  "accessKey": "9S10E7MOOZWUUGHP7BKL",
  "at_hash": "oDAD5t18m0ijU-kvZYDxRg",
  "aud": [
    "da881d80-2ab9-4fa8-ba46-43158ce06624",
    "carbon.super-AAC-1.0.0"
  ],
  "azp": "da881d80-2ab9-4fa8-ba46-43158ce06624",
  "exp": 1580826222,
  "iat": 1580822625,
  "iss": "http://192.168.42.61:9090/aac",
  "jti": "626e119d-0dc8-4b1b-a7f5-069eeac1da2c",
  "kid": "test1",
  "nonce": "LmpaMXGMhY9lBqLr",
  "policy": "readwrite",
  "sub": "17"
}
```

## Your Environment
Docker relase of minio: MinIO/RELEASE.2020-01-25T02-50-51Z

**Comment by matteo-s** [comment]
As a side note, I've noticed that any claim present in the IdP ``id_token`` is carried over inside the JWT emitted by Minio STS.

For example, this *id_token* 
```
{
  "at_hash": "lehTEEmpR26rvFmDF_maFQ",
  "sub": "17",
  "aud": [
    "da881d80-2ab9-4fa8-ba46-43158ce06624",
    "carbon.super-AAC-1.0.0"
  ],
  "azp": "da881d80-2ab9-4fa8-ba46-43158ce06624",
  "kid": "test1",
  "iss": "http://192.168.42.61:9090/aac",
  "garbageclaim": "somerandomstring",
  "exp": 1580826222,
  "iat": 1580822885,
  "nonce": "J0KL4Z42aOQt7mLH",
  "jti": "32ab36b8-8b34-4872-88f6-dbfd90d07fef",
  "policy": "readwrite"
}
```




will produce this *session token*
```
{
  "accessKey": "WRJ0MYVYI7WNO0MIO0UP",
  "at_hash": "lehTEEmpR26rvFmDF_maFQ",
  "aud": [
    "da881d80-2ab9-4fa8-ba46-43158ce06624",
    "carbon.super-AAC-1.0.0"
  ],
  "azp": "da881d80-2ab9-4fa8-ba46-43158ce06624",
  "exp": 1580826222,
  "garbageclaim": "somerandomstring",
  "iat": 1580822885,
  "iss": "http://192.168.42.61:9090/aac",
  "jti": "32ab36b8-8b34-4872-88f6-dbfd90d07fef",
  "kid": "test1",
  "nonce": "J0KL4Z42aOQt7mLH",
  "policy": "readwrite",
  "sub": "17"
}
```

Please note the *garbageclaim* carried over.

Given that session tokens are exclusively consumed by Minio, I suggest to limit the exposure of potentially reserved information contained in the id_token to clients by restricting claims in sessionToken.

Maybe you can define a minimal subset of claims to carry over, which are actually used by Minio, and drop everything else when translating the id_token?

**Comment by harshavardhana** [comment]
Our existing JWT library doesn't allow `aud` to be a slice so this fails, we shall fix this to allow for proper JWT parsing.

**Comment by harshavardhana** [comment]
The way JWT parsing is done has changed on the server -can you verify this with `minio/minio:edge` container?

**Comment by matteo-s** [comment]
On ``minio/minio:edge`` audience is correctly handled in both cases:
* *string array* which contains *client_id*
* *single string* equal to client_id

Looks like the bug is fixed.

@harshavardhana can you comment about the claim leakage from ``id_token`` to ``sessionToken`` described in https://github.com/minio/minio/issues/8933#issuecomment-581912044 ?
I'd like to know your opinion before implementing claim filtering on the IdP side.

**Comment by harshavardhana** [comment]
What does it mean claim leakage I don't understand, MinIO will not filter jwt fields at all because we have no idea about the data structure.

Can you explain further?

**Comment by matteo-s** [comment]
I'm referring to the *verbatim copy* of claims from ``id_token`` to ``sessionToken`` that you can observe in the comment.

When Minio builds the JWT for the sessionToken, it looks like it simply copies all the claims presented in the ``id_token`` and adds it's own *accessKey*. IMHO this approach is *potentially* insecure, since it will leak any claim to the sessionToken. It's a minor problem, given that the user agent will receive both tokens and thus confidentiality is not a goal. But what happens if the IdP includes an *accessToken* claim?

Even claims like *issuer*, *expiration*, *issued_at*, *token_id* look like they are copied as-is, which result in a somehow strange JWT issued *by Minio* but presented as issued by the upstream IdP.
How does Minio validate the sessionToken?

My point is: given that you can't filter the JWT since you have no idea about the structure, why even bother coping it given that you are the one issuing the sessionToken? 
To me it looks simpler and more secure to grab the single claim you are interested in (the *policy*) and then build from scratch a dedicated token with your own set of claims (correct issuer, expiration, jti..), instead of manipulating the id_token and then resigning it.

**Comment by harshavardhana** [comment]
There is no security at this level, you simply see this to be as id_token but it is not, internally we generate a new jwt based on the user specified expiry.

The information has no prior security requirement as this information has no security. It is always publicly available.

The validation of session token happens by using a constant time comparison to avoid timing attacks. Then the token is decoded with the admin secret key to validate the payload as HS512 signature.

What we do is preserve what is sent by the id_token in a new mapClaim so that audit loggers can scan for invalid sources etc and external policy management entities like OPA can further apply restriction. 

We cannot filter arbitrarily because we need to preserve the source claims, and we may add extra claims on top.

So I don't see there is any issue here, now that audience portion is also clear and it works as expected.

**Comment by harshavardhana** [comment]
The issue in question here is already fixed, let's continue our conversation in a new issue if you feel we lack some security guarantees.
