### ISSUE TITLE
Allow multiple volume mounts inside of /minio

### ISSUE THREAD

**Issue by ainiml** [minio/minio#8949]
**Describe the solution you'd like**
Allow multiple volume mounted inside of /minio

`
7ERROR 8Invalid command line arguments: Cross-device mounts detected on path (/minio) at following locations [/minio/data /minio/notebooks]. Export path should not have any sub-mounts, refusing to start.
`

**Describe alternatives you've considered**
We tried multiple minio servers for each volume mount, but it would just be nice to access both volumes from the same minio server

**Comment by harshavardhana** [comment]
As the message suggests this is not possible for us to support due to consistency requirements.

We have closed many issues on this in the past.
