### ISSUE TITLE
Minio doesn't handle special characters correctly.

### ISSUE THREAD

**Issue by buengese** [minio/minio#8950]
I'm working on tool called rclone that allows you to manager files on various cloud storage providers. We recently noticed that some of our S3 integrations tests fail when running against minio. These tests throw a variety of special characters like punction and control characters at the API.

## Expected Behavior

Match Amazon S3. While most of these characters would realistically never be used in names minio should match Amazon S3 for consistency.

## Current Behavior

The API returns a `MalformedXML` error

## Steps to Reproduce (for bugs)

The tests that are failing on our side are:
   - `TestIntegration/FsMkdir/FsPutFiles/SetTier`
   - `TestIntegration/FsMkdir/FsEncoding/control_chars`
   - `TestIntegration/FsMkdir/FsEncoding/leading_LF`
   - `TestIntegration/FsMkdir/FsEncoding/leading_VT` 
   - `TestIntegration/FsMkdir/FsEncoding/punctuation` 
   - `TestIntegration/FsMkdir/FsEncoding/trailing_LF` 
   - `TestIntegration/FsMkdir/FsEncoding/trailing_VT`

These are implemented here:  
https://github.com/rclone/rclone/blob/fe6f4135b420fb22bafc9a25baf1ee91ec9291ac/fstest/fstests/fstests.go#L557 

If you want to run these yourself you'll have to setup an Minio backend in rclone as described in our docs [here](https://rclone.org/s3/) and run the [S3 integration tests](https://github.com/rclone/rclone/blob/fe6f4135b420fb22bafc9a25baf1ee91ec9291ac/backend/s3/s3_test.go#L12) against it.

## Context

Minio is one of the backends we use for testing and these errors can effect other tests too.

## Your Environment

* Version used (`minio version`): minio version RELEASE.2020-01-25T02-50-51Z
* Operating System and version (`uname -a`): Linux ws 4.19.99-1-bmn #1 SMP Mon Jan 27 15:10:18 UTC 2020 x86_64 GNU/Linux

* Link to your project: https://github.com/rclone/rclone

**Comment by harshavardhana** [comment]
> * `TestIntegration/FsMkdir/FsPutFiles/SetTier`
> * `TestIntegration/FsMkdir/FsEncoding/control_chars`
> * `TestIntegration/FsMkdir/FsEncoding/leading_LF`
> * `TestIntegration/FsMkdir/FsEncoding/leading_VT`
> * `TestIntegration/FsMkdir/FsEncoding/punctuation`
> * `TestIntegration/FsMkdir/FsEncoding/trailing_LF`
> * `TestIntegration/FsMkdir/FsEncoding/trailing_VT`

MinIO uses the backend filesystem as the namespace unless disk filesystems can provide this support we do not support this or translate this on our end in any special way. @buengese

**Comment by buengese** [comment]
Are there any plans to abstract this at some point in the future? We can fix this on our side but expected the goal of Minio to be 100% compatibility with S3.

**Comment by harshavardhana** [comment]
> Are there any plans to abstract this at some point in the future? We can fix this on our side but expected the goal of Minio to be 100% compatibility with S3.

There are no such plans @buengese we have no requirement to support such characters. Because in most situations this is a bug in the application, they can never really preserve these names on any known NAS or filesystems. So what MinIO is doing is make filesystem look like object storage.

If there is a strong requirement in the future we may do it, but as of now there are no known applications that we have seen which require these characters to be in strict requirement.

**Comment by ncw** [comment]
@harshavardhana wrote:
> MinIO uses the backend filesystem as the namespace unless disk filesystems can provide this support we do not support this or translate this on our end in any special way.

A  normal linux filesystem supports all of these special case file names, so I think there must be something else going on?

**Comment by harshavardhana** [comment]
> A normal linux filesystem supports all of these special case file names, so I think there must be something else going on?

can you provide a few examples? @ncw we would love to address this without doing any extra translation work.

**Comment by ncw** [comment]
@harshavardhana 

The failing tests are these ones

- TestIntegration/FsMkdir/FsEncoding/control_chars
- TestIntegration/FsMkdir/FsEncoding/leading_LF
- TestIntegration/FsMkdir/FsEncoding/leading_VT
- TestIntegration/FsMkdir/FsEncoding/punctuation
- TestIntegration/FsMkdir/FsEncoding/trailing_LF
- TestIntegration/FsMkdir/FsEncoding/trailing_VT

These are defined in the rclone source here

https://github.com/rclone/rclone/blob/4ee3c21a9d6e4331f45b08805a6ed853bada3941/fstest/fstests/fstests.go#L568-L585

```go
				{"control chars", "\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0A\x0B\x0C\x0D\x0E\x0F\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1A\x1B\x1C\x1D\x1E\x1F\x7F"},
				{"punctuation", "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"},
				{"leading CR", "\rleading CR"},
				{"leading LF", "\nleading LF"},
				{"trailing CR", "trailing CR\r"},
				{"trailing LF", "trailing LF\n"},
```

What the test does is try to create keys of those names (both as directories and leaf names).

The tests pass on s3 but not on minio.

**Comment by harshavardhana** [comment]
Thanks @ncw let me create few tests to see whats going on.
