### ISSUE TITLE
Can't get MC to work on Centos with self signed certs

### ISSUE THREAD

**Issue by sfirmes** [minio/minio#8951]
I am having issues getting the MC command to work with TLS.  The web client is working fine via https so the issue seems to be with the MC command and the certs.

I used openssl instructions found at https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls.html#generate-use-self-signed-keys-certificates tp generate my self signed certs.

Here is my openssl.conf settings:
[root@Minio-Centos minio]# cat openssl.conf 
[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no

[req_distinguished_name]
C = US
ST = VA
L = Somewhere
O = MyOrg
OU = MyOU
CN = MyServerName

[v3_req]
subjectAltName = @alt_names

[alt_names]
IP.1 = 192.168.10.100 

[root@Minio-Centos minio]# openssl req -x509 -nodes -days 730 -newkey rsa:2048 -keyout private.key -out public.crt -config openssl.conf
Generating a RSA private key
.....................................+++++........+++++writing new private key to 'private.key'-----
    
[root@Minio-Centos certs]# mc config host add myminio https://192.168.10.100:9000 admin password --api S3v4                                               
Added `myminio` successfully.

[root@Minio-Centos certs]# mc admin info myminio                               
mc: <ERROR>  Cannot get service status                                         

## Expected Behavior

[root@Minio-Centos certs]# mc admin info myminio                               
●  192.168.10.100:9000                                                         
   Uptime: 43 seconds 
   Version: 2020-01-25T02:50:51Z
   Network: 1/1 OK 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
mc version RELEASE.2020-01-25T03-02-19Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
Centos8 vm
* Operating System and version (`uname -a`):
Linux Minio-Centos.homelab.local 4.18.0-147.el8.x86_64 #1 SMP Wed Dec 4 21:51:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* Link to your project:

**Comment by kannappanr** [comment]
@sfirmes Can you please try `mc admin info myminio --insecure`

**Comment by sfirmes** [comment]
Thanks for the quick response.
Sorry for forgetting to mention that the --insecure flag didn't work either.

[root@Minio-Centos certs]# mc admin info myminio --insecure                    
mc: <ERROR>  Cannot get service status

**Comment by harshavardhana** [comment]
@sfirmes this means that your `mc` and `server` incompatible - most probably `mc` is older here.

**Comment by sfirmes** [comment]
I just verified that I have the latest mc and sever code:

VERSION:
  RELEASE.2020-01-25T03-02-19Z

[root@Minio-Centos certs]# mc admin update myminio                             
Server `myminio` already running the most recent version 2020-01-25T02:50:51Z of MinIO

If my version of mc is incompatible with the server version, is there a place to download the appropriate version?

**Comment by harshavardhana** [comment]
`mc admin update` updates server not client you need to run `mc update` to update your client.

**Comment by sfirmes** [comment]
Thanks.  I updated mc and now the --insecure is working.

[root@Minio-Centos .minio]# mc admin info myminio                              
mc: <ERROR>  Cannot get service status                                         
[root@Minio-Centos .minio]# mc admin info myminio --insecure
●  192.168.10.100:9000
   Uptime: 3 minutes 
   Version: 2020-01-25T02:50:51Z
   Network: 1/1 OK

**Comment by harshavardhana** [comment]
Not just insecure even without `--insecure` should work @sfirmes

**Comment by harshavardhana** [comment]
Paste --debug output @sfirmes

**Comment by sfirmes** [comment]
@harshavardhana 
This is the --insecure --debug
[root@Minio-Centos .minio]# mc admin info myminio --insecure --debug
mc: <DEBUG> GET /minio/admin/v2/info HTTP/1.1
Host: 192.168.10.100:9000
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-02-05T20:07:22Z
Authorization: AWS4-HMAC-SHA256 Credential=admin/20200206//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200206T031231Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 493
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Thu, 06 Feb 2020 03:12:32 GMT
Server: MinIO/RELEASE.2020-01-25T02-50-51Z
Vary: Origin
X-Amz-Request-Id: 15F0B19BD15CB1D0
X-Xss-Protection: 1; mode=block

mc: <DEBUG> TLS Certificate found: 
mc: <DEBUG>  >> Country: US
mc: <DEBUG>  >> Organization: MyOrg
mc: <DEBUG>  >> Expires: 2022-02-04 23:40:11 +0000 UTC
mc: <DEBUG> Response Time:  34.624227ms

●  192.168.10.100:9000
   Uptime: 8 minutes 
   Version: 2020-01-25T02:50:51Z
   Network: 1/1 OK 


This is without --insecure and with --debug
[root@Minio-Centos .minio]# mc admin info myminio --debug           
mc: <ERROR>  Cannot get service status
 (0) admin-info.go:68 cmd.clusterStruct.String(..)
 Release-Tag:RELEASE.2020-02-05T20-07-22Z | Commit:551a124804c9 | Host:Minio-Centos.testlab.local | OS:linux | Arch:amd64 | Lang:go1.13.7 | Mem:4.5 MB/72 MB | Heap:4.5 MB/67 MB

**Comment by harshavardhana** [comment]
> [root@Minio-Centos .minio]# mc admin info myminio --debug
> mc: Cannot get service status
> (0) admin-info.go:68 cmd.clusterStruct.String(..)
> Release-Tag:RELEASE.2020-02-05T20-07-22Z | Commit:551a124804c9 | Host:Minio-Centos.testlab.local | OS:linux | Arch:amd64 | Lang:go1.13.7 | Mem:4.5 MB/72 MB | Heap:4.5 MB/67 MB

have you copied the server public.crt to `~/.mc/certs/CAs` ?

**Comment by sfirmes** [comment]
I had the public.crt file in the ~/.mc/certs/  

moved it to the correct location of ~/.mc/certs/CAs folder and it now works fine.

Thanks for the help @harshavardhana 

Your help and patience is greatly appreciated!!!!
