### ISSUE TITLE
A Question: Does minio can use for backend storage solution in Kubernetes and How or Example for this !

### ISSUE THREAD

**Issue by scila1996** [minio/minio#8956]
I'm very interesting about Minio S3 Solution, and some system was mention for that. Minio is fast, easy, scaling, stable ... So Can i use Minio as Storage backend for Kubernetes, alternatives OpenEBS, CEPH, Rook v.v... and How cookbook to deploy or example for basic system ! Thank you !

**Comment by harshavardhana** [comment]
Please use issue template to clearly describe your issue, for generic questions please join https://slack.min.io - closing this issue for now.
