### ISSUE TITLE
Minio server crashs during uploading 700 small files(size: 10Byte) to distributed MinIO server with background of local storage(HDD) by executing 7 "mc cp" commands synchronously in one container.

### ISSUE THREAD

**Issue by yangwwii** [minio/minio#8960]
Minio server crashs during uploading 700 small files(size: 10Byte) to distributed MinIO server with background of local storage(HDD) by executing 7 "mc cp" commands synchronously in one container.

## Current Behavior
It was observed that MinIO processes are killed without any error info. it's reproduced 100%. CPU and memeory resources of each MinIO pods are reserved in large numbers. So it's not due to resource exhaustion.

## Steps to Reproduce (for bugs)

1. Create 7 folders in one container. There are 100 files (size: 10 Byte) in each local folder.
2. Excute mc copy in container like this,

mc cp -r test1/  abc/test1/ &
mc cp -r test2/  abc/test2/ &
...
mc cp -r test7/  abc/test7/ &

## Your Environment

* Version used (`minio version`): RELEASE.2019-09-11T19-53-16Z
* Version ('mc version'): RELEASE.2019-05-29T21-21-34Z
* 4 MinIO server pods and one client pod are scheduled on different k8s worker node.

**Comment by harshavardhana** [comment]
Please upgrade to latest and test again @yangwwii

**Comment by yangwwii** [comment]
Sure, harshavardhana, we are doing this on the version below, 
Minio - https://github.com/minio/minio/tree/RELEASE.2020-01-25T02-50-51Z
Mc - https://github.com/minio/mc/tree/RELEASE.2020-01-25T03-02-19Z

**Comment by kannappanr** [comment]
@yangwwii are you still seeing this issue?

**Comment by harshavardhana** [comment]
Closing this issue for now, please re-open if seen again @yangwwii

**Comment by yangwwii** [comment]
Thanks harshavardhana and kannappanr, the issue does not happen on the latest version we've got an test on RELEASE.2020-02-07T23-28-16Z

**Comment by harshavardhana** [comment]
Thanks for the update @yangwwii
