### ISSUE TITLE
Minio service stops when notify_kafka is configured 

### ISSUE THREAD

**Issue by patrikdanhall** [minio/minio#8963]
## Current Behavior

The service crash on  with the following log:

Feb  6 10:16:35 minionode10 minio: panic: send on closed channel
Feb  6 10:16:35 minionode10 minio: goroutine 413 [running]:
Feb  6 10:16:35 minionode10 minio: github.com/Shopify/sarama.(*asyncProducer).shutdown(0xc000301110)
Feb  6 10:16:35 minionode10 minio: /q/.q/sources/gopath/pkg/mod/github.com/!shopify/sarama@v1.24.1/async_producer.go:1017 +0xd9
Feb  6 10:16:35 minionode10 minio: github.com/Shopify/sarama.withRecover(0xc000726560)
Feb  6 10:16:35 minionode10 minio: /q/.q/sources/gopath/pkg/mod/github.com/!shopify/sarama@v1.24.1/utils.go:45 +0x4d
Feb  6 10:16:35 minionode10 minio: created by github.com/Shopify/sarama.(*asyncProducer).AsyncClose
Feb  6 10:16:35 minionode10 minio: /q/.q/sources/gopath/pkg/mod/github.com/!shopify/sarama@v1.24.1/async_producer.go:297 +0x6b
Feb  6 10:16:35 minionode10 systemd: minio.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Feb  6 10:16:35 minionode10 systemd: Unit minio.service entered failed state.
Feb  6 10:16:35 minionode10 systemd: minio.service failed.

## Steps to Reproduce (for bugs)

1. mc admin config set SERVER notify_kafka:1 enable=on topic=minioevent brokers=SERVER1:6667,SERVER2:6667,SERVER3:6667 sasl_username= sasl_password= client_tls_cert= client_tls_key= tls_client_auth=0 sasl=off tls=off tls_skip_verify=off queue_limit=0 queue_dir=

2. If minio.service is started again the system work, but as soon as "mc admin info" or other mc admin commands are used the service on the responding servernode fail.  

3. Starting minio.service and resetting the notify_kafka configuration and restarting via "mc admin service restart ---" make the system fully operational again

## Your Environment

Version used: releases 2020-02-07T04:56:50Z, 2020-01-25T02-50-51Z adn 2020-01-16T22-40-29Z
Server type and version: Virtual VMware
Operating System and version: RHEL7
Reproduced on a distributed 4 node cluster and a standalone node

**Comment by nitisht** [comment]
Thanks @patrikdanhall we'll take a look
