### ISSUE TITLE
Minio slowdown on SMB mounted drives

### ISSUE THREAD

**Issue by rtfreedman** [minio/minio#8969]
When using minio in either single server mode or in distributed mode (4 nodes, 1 drive each) there is a noticeable slowdown in operation of the mounted drive while minio is active on the VM where the mount exists. This behavior does not occur on local storage or when using minio as a gateway to the mount.
## Expected Behavior

To operate on the drive without performance issues.
## Current Behavior

After starting the minio service the drive takes up to a full second to ls empty directories and far longer for populated directories. When the service is turned off the latency issues go away.
This causes excessively slow transfer rates for files (30 kB pdf transferred in around a minute).
We noticed this behavior after putting around 430k files into a directory but were able to reproduce in a subdirectory in single server mode with no files.
## Possible Solution

Not sure.
## Steps to Reproduce (for bugs)

Mount network drive with cifs on Linux and target directory with minio server.

## Context

We are attempting to migrate data from our Mongo database to a local minio instance on commodity hardware to save on hardware costs.

## Regression

No

## Your Environment

* Version used (`minio version`): `minio version RELEASE.2020-02-07T23-28-16Z`
* Environment name and version (e.g. nginx 1.9.1): 
* Server type and version: 
* Operating System and version (`uname -a`): `Linux minio_1 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* Link to your project: N/A

**Comment by harshavardhana** [comment]
Have you verified if cifs mount is performant? Can you provide us average latency on the backend first?

Also are you trying to run distributed MinIO on a cifs backed mounts? If this is true then this setup is not recommended or supported.  MinIO erasure coding on top of another NAS is not supported such as NFS, CIFS mounts.

You should provide distributed MinIO direct drives such as JBODs

**Comment by rtfreedman** [comment]
> Have you verified if cifs mount is performant? Can you provide us average latency on the backend first?

### Timing tests
#### Minio service on
```bash
user@minio_1:~$ time dd if=/dev/zero of=/mnt/data/testfile bs=16k count=128k
131072+0 records in
131072+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 14.1323 s, 152 MB/s

real	0m14.137s
user	0m0.024s
sys	0m2.300s
```
```bash
user@minio_2:~$ time dd if=/dev/zero of=/mnt/data/testfile bs=16k count=128k
131072+0 records in
131072+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 285.793 s, 7.5 MB/s

real	4m46.225s
user	0m0.040s
sys	0m2.152s
```
```bash
user@minio_3:~$ time dd if=/dev/zero of=/mnt/data/testfile bs=16k count=128k
131072+0 records in
131072+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 15.9094 s, 135 MB/s

real	0m15.918s
user	0m0.044s
sys	0m2.368s
```
```bash
user@minio_4:~$ time dd if=/dev/zero of=/mnt/data/testfile bs=16k count=128k
131072+0 records in
131072+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 14.7392 s, 146 MB/s

real	0m14.746s
user	0m0.064s
sys	0m1.820s
```
#### Minio service off
```bash
user@minio_1:~$ time dd if=/dev/zero of=/mnt/data/testfile bs=16k count=128k
131072+0 records in
131072+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 4.16861 s, 515 MB/s

real	0m4.324s
user	0m0.048s
sys	0m2.800s
```
```bash
user@minio_2:~$ time dd if=/dev/zero of=/mnt/data/testfile bs=16k count=128k
131072+0 records in
131072+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 4.25948 s, 504 MB/s

real	0m4.413s
user	0m0.060s
sys	0m2.144s
```
```bash
user@minio_3:~$ time dd if=/dev/zero of=/mnt/data/testfile bs=16k count=128k
131072+0 records in
131072+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 3.23494 s, 664 MB/s

real	0m3.400s
user	0m0.032s
sys	0m2.368s
```
```bash
user@minio_4:~$ time dd if=/dev/zero of=/mnt/data/testfile bs=16k count=128k
131072+0 records in
131072+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 3.5656 s, 602 MB/s

real	0m3.691s
user	0m0.008s
sys	0m1.908s
```

> Also are you trying to run distributed MinIO on a cifs backed mounts? If this is true then this setup is not recommended or supported. MinIO erasure coding on top of another NAS is not supported such as NFS, CIFS mounts.

I see, we were attempting to do that. We were still experiencing the slowdown with a singleton (no erasure coding) on top of our CIFS mount. Is this supported?

**Comment by harshavardhana** [comment]
You need to use oflag=direct - this won't show the real performance @rtfreedman what is supported is `minio gateway nas /mnt/ciffs`

**Comment by rtfreedman** [comment]
Makes sense. I'll go with that solution then. Thank you for the help.
