### ISSUE TITLE
Dynamically add/remove domain for Virtualhoststyle style path without restart

### ISSUE THREAD

**Issue by MasoudKaviani** [minio/minio#8970]
Is the any soultion for MINIO to add/remove domain for Virualhost style pathing without restarting the MINIO server? <br />
I config a MINIO server with service and every time that I need to add new Domain, I must restrart the MINIO service <br />
According to documentation: [https://docs.min.io/docs/minio-server-configuration-guide.html](url) this feature only accepts Domain in environment

**Comment by harshavardhana** [comment]
No there is no way to do it, because of router registration requirements. 

Setting domain is considered a one time activity per deployment. So you set as env and start the service. There is no benefit in making it dynamic, it also not technically feasible due to the nature of http handlers.
