### ISSUE TITLE
How to port Minio -> AWS S3?

### ISSUE THREAD

**Issue by win32nipuh** [minio/minio#8972]
Is it possible to develop an application using minio s3 API and later port it to AWS S3?

**Comment by nitisht** [comment]
@win32nipuh yes, MinIO is S3 API compatible so you can develop a S3 compatible application and use it with MinIO and then move to AWS S3. Closing this as answered, please join us on slack for more such questions

**Comment by win32nipuh** [comment]
Thanks, yes, sorry, I have detected the Slack and already joined to it.
