### ISSUE TITLE
Notifications in minIO browser

### ISSUE THREAD

**Issue by win32nipuh** [minio/minio#8973]
I run the minIO server at host3 and browsers http://host1:9000 and http://host2:9000/ 
It will be good if I add/delete a file using http://host1:9000 and the change displayed at http://host2:9000 page.

**Comment by harshavardhana** [comment]
You need to refresh the page `F5` or `ctrl+r` @win32nipuh there is no active view on MinIO browsers and unfortunately we won't add it atleast in near future as it will simply complicate our internal codebase.

MinIO browser is meant for minimal use cases, not meant to be a replacement for Dropbox like functionality. For those things you would have to write your own application based on bucket notifications or use anything available in the community.

Closing this issue.

**Comment by win32nipuh** [comment]
thnx, I see.
