### ISSUE TITLE
ObjectTagging from Sonatype Nexus fails

### ISSUE THREAD

**Issue by markush81** [minio/minio#8976]
Nexus uses ObjecTagging to delete objects.

https://github.com/sonatype/nexus-public/blob/b1e7eb410bc18a4e858fcb72666fa88c1b6fcd64/plugins/nexus-blobstore-s3/src/main/java/org/sonatype/nexus/blobstore/s3/internal/S3BlobStore.java#L366

## Expected Behavior
Tag should be set.

## Current Behavior
Tagging fails.

mc admin trace

```
minio PUT /nexus-blob/content/directpath/nexus-repository-docker/791068c3-4d1b-46ea-a56d-aa4c77638557/0.bytes?tagging
minio Host: minio:9000
minio Content-Length: 84
minio Content-Md5: oNFTUY/PImkQumTISYNGaA==
minio X-Amz-Content-Sha256: aaa85a86d8bb398440f7398696e2107ea9d0e59696325d071ddcd873e87d79ef
minio Authorization: AWS4-HMAC-SHA256 Credential=minio/20200211/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-md5;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=ef4abbcafac206866806d44bf2561f35f423b2f272154701da2940d1633e8f5d
minio Amz-Sdk-Retry: 3/122/431
minio Connection: Keep-Alive
minio Content-Type: application/xml
minio Expect: 100-continue
minio User-Agent: aws-sdk-java/1.11.201 Linux/4.19.76-linuxkit OpenJDK_64-Bit_Server_VM/25.232-b09 java/1.8.0_232 groovy/2.4.15
minio X-Amz-Date: 20200211T101425Z
minio Amz-Sdk-Invocation-Id: b2caf379-9097-c4c4-ffea-0e163d3ea755
minio <BODY>
minio [RESPONSE] [10:14:25.900] [ Duration 6.099ms  ↑ 240 B  ↓ 764 B ]
minio 500 Internal Server Error
minio Vary: Origin
minio X-Amz-Request-Id: 15F2518881B0AF8E
minio X-Xss-Protection: 1; mode=block
minio Accept-Ranges: bytes
minio Content-Length: 495
minio Content-Security-Policy: block-all-mixed-content
minio Content-Type: application/xml
minio Server: MinIO/RELEASE.2020-02-07T23-28-16Z
minio <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Key>content/directpath/nexus-repository-docker/791068c3-4d1b-46ea-a56d-aa4c77638557/0.bytes</Key><BucketName>nexus-blob</BucketName><Resource>/nexus-blob/content/directpath/nexus-repository-docker/791068c3-4d1b-46ea-a56d-aa4c77638557/0.bytes</Resource><RequestId>15F2518881B0AF8E</RequestId><HostId>32940449-06bf-4941-bae2-f1c4a3f0f981</HostId></Error>
```

log file

```
API: PutObjectTagging(bucket=nexus-blob, object=content/directpath/nexus-repository-docker/993c0f8f-fb50-43d0-aa5d-f968b9d913c3/0.bytes)
Time: 10:16:31 UTC 02/11/2020
DeploymentID: 32940449-06bf-4941-bae2-f1c4a3f0f981
RequestID: 15F251A5CA7D0A38
RemoteHost: 172.23.0.3
Host: minio:9000
UserAgent: aws-sdk-java/1.11.201 Linux/4.19.76-linuxkit OpenJDK_64-Bit_Server_VM/25.232-b09 java/1.8.0_232 groovy/2.4.15
Error: expected element <Tagging> in name space http://s3.amazonaws.com/doc/2006-03-01/ but have no name space
       6: cmd/api-errors.go:1767:cmd.toAPIErrorCode()
       5: cmd/api-errors.go:1792:cmd.toAPIError()
       4: cmd/object-handlers.go:2885:cmd.objectAPIHandlers.PutObjectTaggingHandler()
       3: cmd/http-tracer.go:126:cmd.Trace()
       2: cmd/handler-utils.go:356:cmd.httpTraceHdrs.func1()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```

## Steps to Reproduce (for bugs)
1. Use minio as S3 storage in Nexus OSS 3.20.1-01
2. Push Docker Image

What is interesting is that mc admin trace does not show a body part for the PUT request, not sure how i can get this one to find out if the issue is on minio side or nexus side. Since Nexus is working with AWS S3 ... i tend to minio.

## Context
minio not usable as S3 storage backend

## Your Environment
* Version used 2020-02-07T23:28:16Z

**Comment by nitisht** [comment]
Thanks @markush81 we'll take a look soon

**Comment by markush81** [comment]
> Thanks @markush81 we'll take a look soon

In case more information is needed, just let me know. Thx.

**Comment by harshavardhana** [comment]
> API: PutObjectTagging(bucket=nexus-blob, object=content/directpath/nexus-repository-docker/993c0f8f-fb50-43d0-aa5d-f968b9d913c3/0.bytes)
> Time: 10:16:31 UTC 02/11/2020
> DeploymentID: 32940449-06bf-4941-bae2-f1c4a3f0f981
> RequestID: 15F251A5CA7D0A38
> RemoteHost: 172.23.0.3
> Host: minio:9000
> UserAgent: aws-sdk-java/1.11.201 Linux/4.19.76-linuxkit OpenJDK_64-Bit_Server_VM/25.232-b09 java/1.8.0_232 groovy/2.4.15
> Error: expected element <Tagging> in name space http://s3.amazonaws.com/doc/2006-03-01/ but have no name space
>        6: cmd/api-errors.go:1767:cmd.toAPIErrorCode()
>        5: cmd/api-errors.go:1792:cmd.toAPIError()
>        4: cmd/object-handlers.go:2885:cmd.objectAPIHandlers.PutObjectTaggingHandler()
>        3: cmd/http-tracer.go:126:cmd.Trace()
>        2: cmd/handler-utils.go:356:cmd.httpTraceHdrs.func1()
>        1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()

This looks like namespace is optional @nitisht in tagging XML Nexus is not setting this value and failing.

**Comment by nitisht** [comment]
yeah should be small fix
