### ISSUE TITLE
Cache meta not getting set properly on upload

### ISSUE THREAD

**Issue by mrkurt** [minio/minio#8979]
## Expected Behavior

When I upload a file in gateway mode with the cache set and `MINIO_CACHE_AFTER=0`, the next GET should be a cache hit.

## Current Behavior
It appears the file gets cached, but cache.json doesn't include the file meta. Here's a gist of the sequence:

https://gist.github.com/mrkurt/55f1faf4a3e75f2e7f229c32a4a1b38c

## Steps to Reproduce (for bugs)
* Run Minio in Gateway mode with MINIO_CACHE_AFTER set to 0
* Upload file
* Get file with headers, see `Cache: MISS` and `Cache-Lookup: HIT`

## Your Environment
Running Docker minio/minio with this Dockerfile (and env vars for keys passed in)
```
FROM minio/minio

ENV MINIO_CACHE "on"
ENV MINIO_CACHE_DRIVES "/data"
ENV MINIO_CACHE_EXPIRY 30
ENV MINIO_CACHE_QUOTA 90
ENV MINIO_CACHE_AFTER 0

CMD ["minio", "gateway", "s3", "https://s3.dualstack.us-east-2.amazonaws.com/"]% 
```

And this Docker run command:

```
docker run -p 9000:9000 -ti -e MINIO_ACCESS_KEY -e MINIO_SECRET_KEY -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -v /data/:/data/ minio-cache 
```

**Comment by kannappanr** [comment]
@mrkurt Thanks for filing this issue. We will take a look into it
