### ISSUE TITLE
[resolved] Active Directory Groups with Policies

### ISSUE THREAD

**Issue by jpc2350** [minio/minio#8980]
## Expected Behavior

Expected that AD groups would be known by the application and be able to assign policies to them.

## Current Behavior

running /usr/local/bin/mc admin policy set local ad_policy group=myadgroup returns
mc: <ERROR> Cannot set the policy. The specified group does not exist.
The group very much exists in AD, and the filters, basedn etc are all correct. 
Should I be seeing the AD groups in minio, if not - How do I assign policies based on AD Groups as per the documentation? 

## Steps to Reproduce (for bugs)

1. Configure MinIO to connect to AD
2.  Test working configuration using STS API
3. Generate policy using AWS Policy Generator (and follow instructions for adding policy)
4. /usr/local/bin/mc admin policy set local ad_policy group=myadgroup

## Context

Looking at STS integrated with Active Directory, and setting up access and control policies for buckets. 

## Regression

Not that I am aware of.

## Your Environment

* Version used (`minio version`): RELEASE.2020-02-07T23-28-16Z
* Environment name and version (e.g. nginx 1.9.1):  Nginx 1.16.1 Proxy
* Server type and version: Virtual
* Operating System and version (`uname -a`): RHEL 7.7
* Link to your project: N/A

**Comment by harshavardhana** [comment]
Do you have an application that supports this API? how do you plan on using this? are you writing a custom application? 

These questions are important before we go down this route, LDAP/AD with STS is a very niche/specific API support and is not quite useful in all scenarios and would be quite cumbersome to use.

We have another feature being implemented called service accounts which would allow for having multiple credentials associated with an `mc admin user` - we would extend this eventually to include LDAP/AD which would be easier and more easier to use.

**Comment by jpc2350** [comment]
At the moment, we're still investigating the use cases from an internal perspective. My requirements are to look at a system of implementing S3 API's for internal storage (which MinIO is perfect for) for use with Terraform, and forward thinking into the world of S3 compatibility for other internal users and use cases. 

The issue is that we are only able to support Active Directory as the authentication provider which will not change, so I'm just investigating whether it's something we can work with, or not. I'm willing to build custom apps to work with it etc.

**Comment by harshavardhana** [comment]
> running /usr/local/bin/mc admin policy set local ad_policy group=myadgroup returns

This is fixed in the latest released @jpc2350 

> The issue is that we are only able to support Active Directory as the authentication provider which will not change, so I'm just investigating whether it's something we can work with, or not. I'm willing to build custom apps to work with it etc.

Please use the latest release
