### ISSUE TITLE
Data-center aware management of data

### ISSUE THREAD

**Issue by jbarotin** [minio/minio#8983]
I'm looking to implement a simple DVCS, to ensure the High Availability of my infrastructure. I'm  currently considering minio. I haven't found any place to discuss with the community, and I have questions considering datacenter management of data. So, I create this issue.

**Is your feature request related to a problem? Please describe.**

I'm a bit confused by the 2/N +1 parity of minio. From what I understand, we take the hypothesis that same number of volumes is configured on each minio server and that my infrastrure is composed of 2 different (DC1 and DC2) datacenters : I start 4 minio server on DC1 and 4 servers on DC2. 

If DC1 went down, and there's only server on DC2 up, my cluster will be able to read (4 = (8/2+1)), but write will not work  (4 < (8/2+1)). 

That's annoying, datacenter down is so not rare, and we need to have an independant datacenter that stay up.    

**Describe the solution you'd like**
I' d like to get the ability to tag the datacenter where the minio server is located. That tag will ensure the data is replicated in all datacenters. N/2+1 rule should work internaly in these datacenter.

**Describe alternatives you've considered**
If we found no alternative, maybee we'll consider having 3 datacenters with 4 node each

**Comment by kannappanr** [comment]
@jbarotin There are two options here. One is to not erasure code across data centers and have the data copied and kept in sync across data centers. The other is your alternative solution.

**Comment by jbarotin** [comment]
Hi, @kannappanr  could you help find the right configuration for this solution :

> not erasure code across data centers and have the data copied and kept in sync across data centers

**Comment by harshavardhana** [comment]
@jbarotin you are looking at `mc mirror`
