### ISSUE TITLE
minio server MINIO_ACCESS_KEY and MINIO_SECRET_KEY via command line?

### ISSUE THREAD

**Issue by ZedZipDev** [minio/minio#8996]
It will be good feature to pass MINIO_ACCESS_KEY and MINIO_SECRET_KEY via command line.
In that case I can easy run minio as a windows service, also, I can run multiple instances on one host.

**Comment by harshavardhana** [comment]
Why is setting as ENV a problem? @Oleg26Dev it is specifically avoid to disallowing snooping of the CLI options in `ps` output. 

I don't think we shall be doing this.

**Comment by ZedZipDev** [comment]
"Why is setting as ENV a problem?" - it is not a problem, but it is not so easy to run minio as a service. Also, to run N instances on one host.
For example, I am developing multi-tenant web server, it works with database and with documents. S3 has no hierarchy, it has only
Storage
   bucket
      folder
          file

To separate docs storage for different tenants I can use multiple minio server instances on one host, which have different storages. In this case I need different access and secret keys for each minio.

**Comment by harshavardhana** [comment]
> "Why is setting as ENV a problem?" - it is not a problem, but it is not so easy to run minio as a service. Also, to run N instances on one host.

You can run multiple windows batch/service files @Oleg26Dev

**Comment by harshavardhana** [comment]
Also read here https://github.com/minio/minio-service/tree/master/windows#manual-install-with-envs
