### ISSUE TITLE
[resolved] Can't configure mysql notifications 

### ISSUE THREAD

**Issue by LinQing2017** [minio/minio#8998]
My minio version  is RELEASE.2020-02-07T23-28-16Z.
An error occurred when I used the following command to configure MySQL notification！

this is my command :
**mc admin config set myminio notify_mysql:test table="events" format="namespace" dsn_string="root:Ruijie_123@tcp(172.24.33.77:3306)/minio_event?Unicode=true&characterEncoding=UTF-8&useSSL=false"**

this is mc client error msg 

mc: <ERROR> Cannot set 'notify_mysql:test table=events format=namespace dsn_string=root:Ruijie_123@tcp(172.24.33.77:3306)/minio_event?Unicode=true&characterEncoding=UTF-8&useSSL=false' to server. Put http://172.24.33.77:9000/minio/admin/v2/set-config-kv: Connection closed by foreign host http://172.24.33.77:9000/minio/admin/v2/set-config-kv.

this is error log on minio server:

2020/02/14 03:02:35 http: panic serving 172.24.33.77:56944: runtime error: invalid memory address or nil pointer dereference
goroutine 217 [running]:
net/http.(*conn).serve.func1(0xc0007c6500)
	/opt/go/src/net/http/server.go:1767 +0x139
panic(0x1886360, 0x3094790)
	/opt/go/src/runtime/panic.go:679 +0x1b2
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP.func1(0x1e48c00, 0xc0003be380, 0xc00030ed00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:776 +0x248
panic(0x1886360, 0x3094790)
	/opt/go/src/runtime/panic.go:679 +0x1b2
sync.(*RWMutex).RLock(...)
	/opt/go/src/sync/rwmutex.go:48
github.com/minio/minio/pkg/event.(*TargetList).TargetMap(0x0, 0x0)
	/q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/targetlist.go:136 +0x35
github.com/minio/minio/cmd/config/notify.RegisterNotificationTargets.func1(0xc00064bdf8, 0xc00064bdf0)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/config/notify/parse.go:74 +0x47
github.com/minio/minio/cmd/config/notify.RegisterNotificationTargets(0xc0002924b0, 0xc000386300, 0xc0006f7040, 0x0, 0x0, 0x0, 0x40cb01, 0x0, 0x1e17800, 0xc0002c6000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/config/notify/parse.go:195 +0x1002
github.com/minio/minio/cmd/config/notify.TestNotificationTargets(0xc0002924b0, 0xc000386300, 0xc0006f7040, 0x0, 0x0, 0x0, 0x0, 0x0)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/config/notify/parse.go:45 +0x86
github.com/minio/minio/cmd.validateConfig(0xc0002924b0, 0x0, 0x0)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/config-current.go:291 +0x7ab
github.com/minio/minio/cmd.adminAPIHandlers.SetConfigKVHandler(0x1e46880, 0xc0007c7040, 0xc00030f000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-handlers-config-kv.go:146 +0x71b
net/http.HandlerFunc.ServeHTTP(...)
	/opt/go/src/net/http/server.go:2007
github.com/minio/minio/cmd.httpTraceHdrs.func1(0x1e46880, 0xc0007c7040, 0xc00030f000)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/handler-utils.go:353 +0x148
net/http.HandlerFunc.ServeHTTP(0xc000507f40, 0x1e46880, 0xc0007c7040, 0xc00030f000)
	/opt/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0006c60c0, 0x1e46880, 0xc0007c7040, 0xc00030ed00)
	/q/.q/sources/gopath/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212 +0xe2
github.com/minio/minio/cmd.customHeaderHandler.ServeHTTP(0x1e17960, 0xc0006c60c0, 0x1e46600, 0xc0002cc3e0, 0xc00030ed00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:747 +0x162
github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP(0x1e1b100, 0xc00051d170, 0x1e46600, 0xc0002cc3e0, 0xc00030ed00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:762 +0x1d6
github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP(0xc000412600, 0x1e1b240, 0xc00051d1a0, 0x1e46600, 0xc0002cc3e0, 0xc00030ed00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:623 +0xcc
github.com/minio/minio/cmd.requestValidityHandler.ServeHTTP(0x1e1b060, 0xc000484380, 0x1e46600, 0xc0002cc3e0, 0xc00030ed00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:607 +0x58f
github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP(0x1e1b1e0, 0xc00051d1f0, 0x1e48c00, 0xc0003be380, 0xc00030ed00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:543 +0x106
github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP(0x1e1b120, 0xc00051d230, 0x50004000000, 0x1e48c00, 0xc0003be380, 0xc00030ed00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:68 +0xcf
github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP(0x1e1b1c0, 0xc0004843a0, 0x1e48c00, 0xc0003be380, 0xc00030ed00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:93 +0x264
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x1e1b1a0, 0xc00051d240, 0x1e48c00, 0xc0003be380, 0xc00030ed00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/crossdomain-xml-handler.go:51 +0x81
github.com/minio/minio/cmd.redirectHandler.ServeHTTP(0x1e1b0e0, 0xc00051d250, 0x1e48c00, 0xc0003be380, 0xc00030ed00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:247 +0x68
github.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP(0x1e1b180, 0xc00051d290, 0x1e48c00, 0xc0003be380, 0xc00030ed00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:315 +0xac
github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP(0x1e1b160, 0xc00051d2a0, 0x1e48c00, 0xc0003be380, 0xc00030ed00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:274 +0x1c2
github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP(0x1e1b080, 0xc00051d2b0, 0x1e48c00, 0xc0003be380, 0xc00030ed00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:385 +0x32a
github.com/rs/cors.(*Cors).Handler.func1(0x1e48c00, 0xc0003be380, 0xc00030ed00)
	/q/.q/sources/gopath/pkg/mod/github.com/rs/cors@v1.6.0/cors.go:207 +0x1af
net/http.HandlerFunc.ServeHTTP(0xc000484420, 0x1e48c00, 0xc0003be380, 0xc00030ed00)
	/opt/go/src/net/http/server.go:2007 +0x44
github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0x1e1bcc0, 0xc000484420, 0x1e48c00, 0xc0003be380, 0xc00030ed00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:523 +0xa8
github.com/minio/minio/cmd.authHandler.ServeHTTP(0x1e1b220, 0xc00051d320, 0x1e48c00, 0xc0003be380, 0xc00030ed00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/auth-handler.go:450 +0x392
github.com/minio/minio/cmd.sseTLSHandler.ServeHTTP(0x1e1b040, 0xc00051d340, 0x1e48c00, 0xc0003be380, 0xc00030ed00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:797 +0x454
github.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP(0x1e1b260, 0xc00051d350, 0x1e48c00, 0xc0003be380, 0xc00030ed00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:136 +0x264
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x1e1b200, 0xc00051d360, 0x1e48c00, 0xc0003be380, 0xc00030ed00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:779 +0xac
github.com/minio/minio/cmd/http.(*Server).Start.func1(0x1e48c00, 0xc0003be380, 0xc00030ed00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/http/server.go:104 +0x2ab
net/http.HandlerFunc.ServeHTTP(0xc0003d40c0, 0x1e48c00, 0xc0003be380, 0xc00030ed00)
	/opt/go/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc0000fc480, 0x1e48c00, 0xc0003be380, 0xc00030ed00)
	/opt/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0007c6500, 0x1e50580, 0xc0003c83c0)
	/opt/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/opt/go/src/net/http/server.go:2928 +0x384

**Comment by harshavardhana** [comment]
Fixed by #8986

**Comment by LinQing2017** [comment]
> Fixed by #8986

When I use an older version of the image, I can use the MC command to configure MySQL notifications.
However, when I set format = access, the following error occurred

mc: Cannot set 'notify_mysql:test table=events format=namespace dsn_string=root:Ruijie_123@tcp(172.24.33.77:3306)/minio_event' to server. Error 1071: Specified key was too long; max key length is 3072 bytes.

I think it's because the server exceeded the MySQL limit when creatingtables!!

Please tell me how to solve this problem!!!

**Comment by harshavardhana** [comment]
> mc: Cannot set 'notify_mysql:test table=events format=namespace dsn_string=root:Ruijie_123@tcp(172.24.33.77:3306)/minio_event' to server. Error 1071: Specified key was too long; max key length is 3072 bytes.

Just delete the mysql table and let it re-populate it @LinQing2017

**Comment by LinQing2017** [comment]
> namespace

It doesn't work！
When using the namespace mode, Minio cannot automatically create tables in MySQL.

**Comment by kawa23** [comment]
> > Fixed by #8986
> 
> When I use an older version of the image, I can use the MC command to configure MySQL notifications.
> However, when I set format = access, the following error occurred
> 
> mc: Cannot set 'notify_mysql:test table=events format=namespace dsn_string=root:Ruijie_123@tcp(172.24.33.77:3306)/minio_event' to server. Error 1071: Specified key was too long; max key length is 3072 bytes.
> 
> I think it's because the server exceeded the MySQL limit when creatingtables!!
> 
> Please tell me how to solve this problem!!!

@LinQing2017 I got the same problem, do you solve it?
