### ISSUE TITLE
[not our bug] The request signature we calculated does not match the signature you provided.

### ISSUE THREAD

**Issue by vanvanni** [minio/minio#8999]
## Expected Behavior

Set the policy...

## Current Behavior

The request signature we calculated does not match the signature you provided. Check your key and signing method.

## Possible Solution

1) Going over HTTP instead of HTTPS
2) Adding the snippet below to NGINX config
```
proxy_set_header Host $host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection upgrade;
proxy_set_header Accept-Encoding gzip;
```

## Steps to Reproduce (for bugs)

1. I just execute the following command, nothing more nothing less `./mc policy set public s3/galaxy`

## Context
Using the MC client on my server, this error occurs on all commands involving the s3 server

## Your Environment

* Version used (`minio version`): minio version RELEASE.2020-02-07T04-56-50Z
* Client version used (`mc -v`): mc version RELEASE.2020-02-05T20-07-22Z
* Environment name and version (e.g. nginx 1.9.1): nginx version: nginx/1.14.0 (Ubuntu)
* Server type and version: Ubuntu?
* Operating System and version (`uname -a`): Linux Orbit-A 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project: N/A

**Comment by harshavardhana** [comment]
Looks like wrong nginx config here, can you paste your nginx config?

**Comment by vanvanni** [comment]
> Looks like wrong nginx config here, can you paste your nginx config?

Sorry forgot to paste it:
```
upstream s3 {
    server 127.0.0.1:9000;
}

server {
    listen 80;
	server_name DOMAIN;
 
    location / {
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Accept-Encoding gzip;
        proxy_pass http://s3;
    }
}

server {
    listen 443 ssl;
    index index.html;
    server_name DOMAIN;

    access_log off;
    error_log off;
    
    location / {
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Accept-Encoding gzip;
        proxy_pass http://s3;
    }

    ssl_certificate PATH;
    ssl_certificate_key PATH;
}
```

**Comment by zj8487** [comment]
Same problem
@xJoeyv do you have any progress on it. thank you very much

**Comment by vanvanni** [comment]
> Same problem
> @xJoeyv do you have any progress on it. thank you very much

I did but what I did back at that time is something I do not know now. I switched to docker for my personal stack. Sorry
