### ISSUE TITLE
Add OpenID scope customization

### ISSUE THREAD

**Issue by jsmouret** [minio/minio#9010]
**Is your feature request related to a problem? Please describe.**

It would be nice to be able to customize the scopes requested by OpenID.
More specifically the line: https://github.com/minio/minio/blob/master/browser/app/js/browser/utils.js#L22
```javascript
 params.set("scope", "openid")
```
should be customizable to
```javascript
 params.set("scope", "openid groups")
```
This way it becomes possible to write OPA rules like:
```rego
package httpapi.authz
import input
default allow = false

allow {
  input.claims.groups[_] == input.bucket
}
allow {
  input.owner
}
```
which enables access to a bucket if you belong to the group of the same name.

**Describe the solution you'd like**

The most confortable solution would be to add a variable like:
```shell
export MINIO_IDENTITY_OPENID_SCOPE="openid email groups"
```

**Describe alternatives you've considered**

The current workaround is to intercept the call to the OpenID provider (Dex for instance) with something like:
```yaml
    nginx.ingress.kubernetes.io/configuration-snippet: |
        if ($args ~* (.*)scope=openid&(.*)) {
          set $args $1scope=openid%20email%20groups&$2;
          rewrite ^.*$ $1 redirect;
        }
```

**Additional context**

Thanks a lot

**Comment by harshavardhana** [comment]
what if we add all the scopes? @jsmouret because based on the Discovery doc endpoint we do obtain all the SupportedScopes() which we can use as a whole.

**Comment by jsmouret** [comment]
That would work in my case but I'm not sure if "supported scopes" also means "authorized scopes".

For example [gitlab openid config](https://gitlab.com/.well-known/openid-configuration) returns:
```json
"scopes_supported": [
    "api",
    "read_user",
    "read_repository",
    "write_repository",
    "read_registry",
    "sudo",
    "openid",
    "profile",
    "email"
]
```
But when registering an application, we can enable only a few scopes:
![image](https://user-images.githubusercontent.com/2038285/74891342-bc3b0700-53c1-11ea-840e-369a9f7cfc66.png)

I am not sure what is the behavior if a requested scope is not allowed even if it is listed as supported.

**Comment by harshavardhana** [comment]
AFAIK it is advisory not mandatory @jsmouret feel free to test #9015

**Comment by jsmouret** [comment]
Looks good :)
Thanks a lot
