### ISSUE TITLE
 Found MINIO_SECRET_KEY in environ file

### ISSUE THREAD

**Issue by AlexanderChiyun** [minio/minio#9011]
When starting minio server with MINIO_ACCESS_KEY and MINIO_SECRET_KEY as environment variables, we found MINIO_SECRET_KEY in /proc/{pid}/environ, it may not be safe.
## Expected Behavior

MINIO_SECRET_KEY is not available or encrypted in /proc/{pid}/environ.

## Steps to Reproduce (for bugs)

1.export MINIO_ACCESS_KEY='Y2PHOKQV00SDN7498S8W'
2.export MINIO_SECRET_KEY='hymYTBeerolV5QzGhNRZiTqof'
3./usr/bin/minio server -C ./conf --quiet ./data1 &
4.cat /proc/{pid of minio}/environ | tr '\0' '\n'
![github](https://user-images.githubusercontent.com/13920454/74717485-710ee000-526b-11ea-9218-68084a53f6e6.PNG)

## Your Environment

* Version used (`minio version`):2019-10-12T01-39-57Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
proc is only accessible for the user @AlexanderChiyun and root. Running MinIO as a regular user is recommended in-fact running it like a user `nobody:nobody` is the best-recommended approach.

Another more secure way to deploy is to use systems like k8s, docker for secrets. These are deployment-specific things to manage yourself to keep it more secure.
