### ISSUE TITLE
Minio service not starting after server reboot.

### ISSUE THREAD

**Issue by kirankanth** [minio/minio#9014]
Everytime we restart a node running minio service, minio doesn't come back online. We have to manually re-start the process. Our's is a 4 node cluster with 2 disks on each server.

Below is the startup script we are using.

# cat /usr/lib/systemd/system/minio.service
Description=Minio
Documentation=https://docs.minio.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/usr/local/bin/minio

[Service]
#WorkingDirectory=/usr/local/

User=miniol
Group=miniol

#PermissionsStartOnly=true

#EnvironmentFile=/home/miniol/.minio/
#ExecStartPre=/bin/bash -c "[ -n \"${MINIO_VOLUMES}\" ] || echo \"Variable MINIO_VOLUMES not set in /etc/default/minio\""

ExecStart=/home/miniol/run_minio.bash

# Let systemd restart this service only if it has ended with the clean exit code or signal.
Restart=on-success
#StandardOutput=journal
#StandardError=inherit

# Specifies the maximum file descriptor number that can be opened by this process
#LimitNOFILE=65536

# Disable timeout logic and wait until process is stopped
#TimeoutStopSec=0

# SIGTERM signal is used to stop Minio
KillSignal=SIGTERM

SendSIGKILL=no

SuccessExitStatus=0

[Install]
WantedBy=multi-user.target
#

**Comment by harshavardhana** [comment]
Please share the entire service file properly @kirankanth put them in markdown quotes to avoid markdown formatting, also share the shell script being used here. Looks like you have been modifying with the service file.

**Comment by kirankanth** [comment]
[service.txt](https://github.com/minio/minio/files/4225900/service.txt)

Attached is the service and startup script.

**Comment by harshavardhana** [comment]
So when you said MinIO doesn't comeback what is the error that you see?

**Comment by kirankanth** [comment]
[minio output after reboot.txt](https://github.com/minio/minio/files/4226038/minio.output.after.reboot.txt)
Attached is the log. Every month we patch these servers and after the reboot, minio service is not coming back.

**Comment by harshavardhana** [comment]
IT clearly indicates that your DNS services are not up after reboot @kirankanth 

```
Feb 17 21:49:58 server01.phx.aexp.com run_minio.bash[1382]: ERROR Invalid command line arguments: 'https://server02.phx.aexp.com/mnt/server0201': lookup lppbd
Feb 17 21:49:58 server01.phx.aexp.com run_minio.bash[1382]: > Please provide correct combination of local/remote paths.
Feb 17 21:49:58 server01.phx.aexp.com run_minio.bash[1382]: HELP:
Feb 17 21:49:58 server01.phx.aexp.com run_minio.bash[1382]: For more information, please refer to https://docs.minio.io/docs/minio-erasure-code-quickstart-guide
```

You need to make sure that DNS is working before starting MinIO

**Comment by kirankanth** [comment]
That's the same case for every server. I see it is looking for only "network-online.target" unit, would you recommend changing it to anything else? For example "multi-user.target"

Wants=network-online.target
After=network-online.target

**Comment by harshavardhana** [comment]
> Wants=network-online.target
> After=network-online.target

This should be sufficient but it looks like in your setup there are some other orthogonal services that enable DNS later or come in the way.  First look at the list of services called after minio and see if that enables the DNS in some way. There is no other reason why would MinIO run after it has successfully rebooted.

Also, I am not sure why have you edited your service files from our recommended approach https://github.com/minio/minio-service/blob/master/linux-systemd/distributed/minio.service - running a script inside service file is a bit haphazard style and clunky. There is no reason to put this in a service you can just dump the script in /etc/rc.local it will serve the same purpose.

**Comment by kirankanth** [comment]
We have been using this setup since more than a year. I was suspecting our engineers might have got older version of the minio.service. There were not many changes from the original file, except for the user id's and stuff. Regarding rc.local, that seems to be deprecated in RHEL7, thought it may be possible. But we are figuring out the process to see if this can be achieved through systemd service. There is no specifc server for dns, but somehow the network is not going out to DNS while minio is trying to start and that's the reason i was asking whether it is ok to use multi-user.target.

**Comment by harshavardhana** [comment]
First you need to fix why network is not up, perhaps there is a dnsmasq stuff that is running and it's coming in the way.

**Comment by kannappanr** [comment]
@kirankanth Closing this issue based on the comments. Please feel free to reach out to us for further questions.
