### ISSUE TITLE
additional metadata insertion API separately for existing object 

### ISSUE THREAD

**Issue by sumanadak** [minio/minio#9016]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by harshavardhana** [comment]
You can do that with server-side CopyObject() with x-amz-meta-directive: REPLACE flag @sumanadak 

https://github.com/aws/aws-sdk-php/issues/274#issuecomment-39983830

**Comment by sumanadak** [comment]
@harshavardhana  thanks.. But this way, I need to write our object again. means to only update metadata, I need read file again and write to minio. My file size is quit large ..more than 10GB.  But i think, there is no plan to update separate metadata API rather than copyObject() API now.

**Comment by harshavardhana** [comment]
You don't need to read the object again, first you do headObject and then perform copyObject() with the right header.

It won't again copy the data it will only update the metadata of the object. So it doesn't matter how large is your object.

**Comment by sumanadak** [comment]
@harshavardhana  thanks a lot. it solves my problem.

**Comment by sumanadak** [comment]
Hello Guys, I am trying to update metadata for Object which I already stored. I am trying to do with javascript sdk. I tried to call statObject() to get the metadata of that object. I got to know that I can make copyObject() with  x-amz-meta-directive: REPLACE. But I could not able to figure out how to add new metadata and attach to CopyObject() call. Documentation says, this coding 
`var conds = new Minio.CopyConditions()
conds.setMatchETag('bd891862ea3e22c93ed53a098218791d')
minioClient.copyObject('mybucket', 'newobject', '/mybucket/srcobject', conds, 
........
}) `
 
I am not able to figure out, how to add new metadata with copyObject() call. CopyConditions has only four methods. which I didn't see any method for adding metadata. could you please help me

**Comment by harshavardhana** [comment]
> Hello Guys, I am trying to update metadata for Object which I already stored. I am trying to do with javascript sdk. I tried to call statObject() to get the metadata of that object. I got to know that I can make copyObject() with x-amz-meta-directive: REPLACE. But I could not able to figure out how to add new metadata and attach to CopyObject() call. Documentation says, this coding
> `var conds = new Minio.CopyConditions() conds.setMatchETag('bd891862ea3e22c93ed53a098218791d') minioClient.copyObject('mybucket', 'newobject', '/mybucket/srcobject', conds, ........ }) `
> 
> I am not able to figure out, how to add new metadata with copyObject() call. CopyConditions has only four methods. which I didn't see any method for adding metadata. could you please help me

Your source and destination should be the same object, replace tag is added automatically by the SDK.

**Comment by sumanadak** [comment]
Thanks, I am sorry. I cant still figure out. My problem is how do I attach new metadata as we do with fputObject() call with metaData arguments. I first call fputObject() with defined metadata. Then I get metadata using statObject() call and then I modify metadata and now I want to update with copyObject() call. But I didn't see any arguments for metadata or method on copyconditions . I am learning minion now. Please help me with this?

**Comment by sumanadak** [comment]
> > Hello Guys, I am trying to update metadata for Object which I already stored. I am trying to do with javascript sdk. I tried to call statObject() to get the metadata of that object. I got to know that I can make copyObject() with x-amz-meta-directive: REPLACE. But I could not able to figure out how to add new metadata and attach to CopyObject() call. Documentation says, this coding
> > `var conds = new Minio.CopyConditions() conds.setMatchETag('bd891862ea3e22c93ed53a098218791d') minioClient.copyObject('mybucket', 'newobject', '/mybucket/srcobject', conds, ........ }) `
> > I am not able to figure out, how to add new metadata with copyObject() call. CopyConditions has only four methods. which I didn't see any method for adding metadata. could you please help me
> 
> Your source and destination should be the same object, replace tag is added automatically by the SDK.

Thanks, I am sorry. I cant still figure out. My problem is how do I attach new metadata as we do with fputObject() call with metaData arguments. I first call fputObject() with defined metadata. Then I get metadata using statObject() call and then I modify metadata(Well most of the case, my metadata is custom metadata)and now I want to update with copyObject() call. But I didn't see any arguments for metadata or method on copyconditions . I am learning minion now. Please help me with this?
