### ISSUE TITLE
Running minio controller first time generates an error

### ISSUE THREAD

**Issue by technosophos** [minio/minio#902]
After a fresh install, if I run `minio controller`, I get this error because the `.minio` directory does not yet exist.

```
$ minio controller
FATA[0000] Failed to generate keys for minio.            error=open /Users/mattbutcher/.minio/users.json: no such file or directory probe={"cause":{"Op":"open","Path":"/Users/mattbutcher/.minio/users.json","Err":2},"trace":[{"line":198,"file":".../src/github.com/minio/minio/pkg/quick/quick.go","func":"quick.config.Save"},{"line":114,"file":".../src/github.com/minio/minio/server-auth-config.go","func":"main.SaveConfig"},{"line":134,"file":".../src/github.com/minio/minio/controller-main.go","func":"main.genAuthFirstTime"},{"line":166,"file":".../src/github.com/minio/minio/controller-main.go","func":"main.firstTimeAuth"},{"line":222,"file":".../src/github.com/minio/minio/controller-main.go","func":"main.controllerMain"}],"sysinfo":{"host.arch":"amd64","host.cpus":"8","host.lang":"go1.5.1","host.name":"ENG001590.local","host.os":"darwin","mem.heap.total":"786kB","mem.heap.used":"334kB","mem.total":"3.1MB","mem.used":"334kB"}}
```

**Comment by harshavardhana** [comment]
> FATA[0000] Failed to generate keys for minio.            error=open /Users/mattbutcher/.minio/users.json: no such file or directory probe={"cause":{"Op":"open","Path":"/Users/mattbutcher/.minio/users.json","Err":2},"trace":[{"line":198,"file":".../src/github.com/minio/minio/pkg/quick/quick.go","func":"quick.config.Save"},{"line":114,"file":".../src/github.com/minio/minio/server-auth-config.go","func":"main.SaveConfig"},{"line":134,"file":".../src/github.com/minio/minio/controller-main.go","func":"main.genAuthFirstTime"},{"line":166,"file":".../src/github.com/minio/minio/controller-main.go","func":"main.firstTimeAuth"},{"line":222,"file":".../src/github.com/minio/minio/controller-main.go","func":"main.controllerMain"}],"sysinfo":{"host.arch":"amd64","host.cpus":"8","host.lang":"go1.5.1","host.name":"ENG001590.local","host.os":"darwin","mem.heap.total":"786kB","mem.heap.used":"334kB","mem.total":"3.1MB","mem.used":"334kB"}}

Ah my bad! .. thanks for testing. Will fix it in a bit.

**Comment by technosophos** [comment]
If you don't mind, I think I might try to do a quick pull request.

**Comment by harshavardhana** [comment]
> If you don't mind, I think I might try to do a quick pull request.

Not at all an issue.. go ahead :-)

**Comment by harshavardhana** [comment]
You can use `createAuthConfigPath()`

**Comment by technosophos** [comment]
Oh! Excellent. Thanks.

**Comment by technosophos** [comment]
Well, that seemed pretty easy.

**Comment by harshavardhana** [comment]
> Well, that seemed pretty easy.

Yes it was! :-) Thank you.
