### ISSUE TITLE
getSignedUrl doesn't support StorageClass

### ISSUE THREAD

**Issue by pdufour** [minio/minio#9020]
If you try to create a presigned PUT request url, it says `SignatureDoesNotMatch` when you try to use it.

## Expected Behavior
````
const params = {
    Key: key,
    Expires: 1800, // 30 min
    ContentType: 'application/pdf',
    StorageClass: 'REDUCED_REDUNDANCY',
};

bucket.getSignedUrl('putObject', params, callback)
````
- Returns signed PUT url
- Send PUT request with this url and it should go through

## Current Behavior
- Call getSignedUrl with storage class set
- Gives error when you try to use the URL:
`SignatureDoesNotMatch`

**Comment by harshavardhana** [comment]
Did you set the x-amz-storage-class http header while uploading the object? It is not just about putting it as part of the signed URL.

**Comment by pdufour** [comment]
@harshavardhana This has been working when previously connecting directly to s3. The signedUrl function adds the x-amz-storage-class to the signed url.

Here is a reproducible test case showing the problem:

````
'use strict';

const AWS            = require('aws-sdk');
const RequestPromise = require('request-promise');

process.env.AWS_ACCESS_KEY_ID = 'minioadmin';
process.env.AWS_SECRET_ACCESS_KEY = 'minioadmin';

const _main = async () => {
  AWS.config.signatureVersion = 'v4';

  const bucket = new AWS.S3({
    endpoint: 'http://localhost:9000',
    region: 'us-east-1',
    s3ForcePathStyle: true,
    params: { Bucket: 'bucket' }
  });

  const key = 'test.pdf';

  const params = {
    Key: key,
    Expires: 1800, // 30 min
    ContentType: 'application/pdf',
    StorageClass: 'STANDARD'
  };

  const callback = async (_, url) => {
    await RequestPromise.put({
      uri: url,
      body: 'foo'
    });
  };

  bucket.getSignedUrl('putObject', params, callback);
};

_main();

````

Remove `StorageClass: 'STANDARD'` and things work fine.

**Comment by harshavardhana** [comment]
Understood let's take a look
