### ISSUE TITLE
Readiness check fails in the case of minio server upgrade from RELEASE.2020-02-07T04-56-50Z to RELEASE.2020-02-07T23-28-16Z

### ISSUE THREAD

**Issue by yangwwii** [minio/minio#9021]
This issue only happens in the test case of Minio server upgrade.

## Current Behavior
When upgrading distributed minio from RELEASE.2020-02-07T04-56-50Z to RELEASE.2020-02-07T23-28-16Z, minio server can't start up in pods, and readiness check fails.
# kubectl get pods -n viola
NAME            READY   STATUS    RESTARTS   AGE
viola-minio-0   1/1     Running   0          3h6m
viola-minio-1   1/1     Running   0          3h6m
viola-minio-2   1/1     Running   0          3h6m
**viola-minio-3   0/1     Running   0          172m**
# kubectl describe pods -n viola viola-minio-3
    Liveness:   http-get http://:http/minio/health/live delay=5s timeout=1s period=30s #success=1 #failure=3
    **Readiness:  http-get http://:http/minio/health/ready delay=120s timeout=1s period=20s #success=1 #failure=3**
Events:
  Type     Reason     Age                    From                         Message
  ----     ------     ----                   ----                         -------
  **Warning  Unhealthy  2m4s (x505 over 170m)  kubelet, node-10-210-156-73  Readiness probe failed: HTTP probe failed with statuscode: 503**

## Steps to Reproduce (for bugs)
1. download and modify the chart in https://github.com/helm/charts/tree/master/stable/minio (base on the commit of 5d1a52a1717359760d75d12f332dbec431a885da). change image.tag=RELEASE.2020-02-07T04-56-50Z.
     #helm install ./minio --name viola --namespace viola
2. Once the server is ready, update the helm release with, image.tag=RELEASE.2020-02-07T23-28-16Z
     #helm install  viola ./minio --install

## Your Environment
storageclass is "nfs"

**Comment by yangwwii** [comment]
Hi, the minio server can be deployed successfully by helm install, but when upgrading to a new version of minio image, the minio server can't start up and readiness check fails.
I also checked the log of failed pod viola-minio-3, this error log are printed in period, kindly please refer to the info shown below,
2020/02/20 07:05:42 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
2020/02/20 07:05:42 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
2020/02/20 07:05:42 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
 Waiting for a minimum of 2 disks to come online (elapsed 2h58m41s)
Waiting for a minimum of 2 disks to come online (elapsed 2h58m42s)
Waiting for a minimum of 2 disks to come online (elapsed 2h58m42s)
Waiting for a minimum of 2 disks to come online (elapsed 2h58m43s)
Waiting for a minimum of 2 disks to come online (elapsed 2h58m43s)

**Comment by nitisht** [comment]
Thanks for reporting @yangwwii we'll take a look

**Comment by nitisht** [comment]
How are you starting the MinIO cluster, can you paste the yaml

**Comment by harshavardhana** [comment]
Also can you do mc admin trace -a to this cluster?

**Comment by yangwwii** [comment]
@nitisht I deployed the services by helm install the yaml chart from  https://github.com/helm/charts/tree/master/stable/minio
before installing, i just make a change on the minio image version, to RELEASE.2020-02-07T04-56-50Z.

@harshavardhana  do you mean create an docker with mc in it and do execute,
mc admin trace -a
am i right?

**Comment by harshavardhana** [comment]
which helm version are you using? @yangwwii can you do `helm repo update` and re-deploy? - We can't seem to reproduce the problem.

**Comment by mrsrvman** [comment]
https://github.com/minio/minio/issues/8968

**Comment by yangwwii** [comment]
Hi @harshavardhana,
This is my helm version:
$ helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"e18ac6f56f488dedea2bf8fc621e23027387d298", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"bf1a9adb587795da9a165ef411c3b6e1eeca6ffe", GitTreeState:"clean"}

i saw the problem on the docker image minio/minio:RELEASE.2020-02-07T04-56-50Z and  minio/minio:RELEASE.2020-02-07T23-28-16Z

when do you have a new docker image on which the issue is resolved? so that i can have a verification on the new release.

**Comment by nitisht** [comment]
please try `minio/minio:edge`

**Comment by yangwwii** [comment]
Thanks @nitisht I will have a try and back to you once i have the result.

**Comment by yangwwii** [comment]
Hi @nitisht  I'm afraid that it doesn't fix on minio/minio:edge.
I depoly the minio service based on image minio/minio:RELEASE.2020-02-07T23-28-16Z. and execute upgrade it to minio/minio:edge via,
$ helm upgrade viola ./minio --install
the error info is, 
$ kubectl get pods -n viola
NAME            READY   STATUS    RESTARTS   AGE
viola-minio-0   1/1     Running   0          23m
viola-minio-1   1/1     Running   0          23m
viola-minio-2   1/1     Running   0          23m
viola-minio-3   0/1     Running   0          8m15s
please see the viola-minio-3, it failed to restart due to readiness check, the same issue as i raised in this issue. refer to the output of "kubectl describe pods -n viola viola-minio-3"
Events:
  Type     Reason     Age                   From                         Message
  ----     ------     ----                  ----                         -------
  Normal   Scheduled  <unknown>             default-scheduler            Successfully assigned viola/viola-minio-3 to node-10-210-156-73
  Normal   Pulling    8m33s                 kubelet, node-10-210-156-73  Pulling image "minio/minio:edge"
  Normal   Pulled     8m30s                 kubelet, node-10-210-156-73  Successfully pulled image "minio/minio:edge"
  Normal   Created    8m30s                 kubelet, node-10-210-156-73  Created container minio
  Normal   Started    8m30s                 kubelet, node-10-210-156-73  Started container minio
  Warning  Unhealthy  19s (x19 over 6m19s)  kubelet, node-10-210-156-73  Readiness probe failed: HTTP probe failed with statuscode: 503

Additional, I got the logs from pod viola-minio-3,
$ kubectl logs -n viola viola-minio-3
Waiting for a minimum of 2 disks to come online (elapsed 15m22s)
Waiting for a minimum of 2 disks to come online (elapsed 15m22s)
Waiting for a minimum of 2 disks to come online (elapsed 15m23s)
Waiting for a minimum of 2 disks to come online (elapsed 15m23s)

@nitisht  what information would you like me to collect for your investigation, kindly please let me know.

**Comment by harshavardhana** [comment]
The issue won't be fixed in this release, because you are running a release that has this issue. The issue was a problem in rolling upgrades and will be only fixed once you have completely moved to the new release and then from next release after that, you shall see rolling upgrades to work fine.

**Comment by harshavardhana** [comment]
Best approach right now is simply `helm uninstall` and `helm install` with `minio/minio:edge` using the PVs

**Comment by yangwwii** [comment]
Thanks for explanation, @harshavardhana , it's clear that i should work on minio/minio:edge first, based on this consideration, the upgrade will work.
Could I know when do you plan have an new release image?

**Comment by harshavardhana** [comment]
> Could I know when do you plan have an new release image?

The plan is soon, there is no set ETA @yangwwii
