### ISSUE TITLE
Docker swarm deployment : Unable to access MinIO from browser

### ISSUE THREAD

**Issue by pransen** [minio/minio#9025]
I deployed MinIO using docker swarm as in the tutorial.

## Expected Behavior
1. Expected to be able to access MinIO on <Master Host IP>:9000 which is not the case.
2. Able to login to MinIO on any of the host IPs in the cluster and the port on which MinIO is running. However, when I login and try to create a bucket, it says 'Server not initialized, please try again '

**Comment by nitisht** [comment]
@pransen please follow the issue template for us to be able to help you. Right now it is not clear what may be wrong here because we have no idea about your environment. For a more interactive q/a style discussion, please join us on Slack.

**Comment by harshavardhana** [comment]
Let's close this issue until we get clarity on what is going on.
