### ISSUE TITLE
Minio behind nginx ingress, bucket not found

### ISSUE THREAD

**Issue by base698** [minio/minio#9032]
I currently have 8 minio nodes `mc admin info minio`:

```
●  minio.somwhere.net
   Uptime: 15 hours
   Version: 2020-02-20T22:51:23Z
   Network: 1/1 OK
   Drives: 24/24 OK

0 B Used, 2 Buckets, 0 Objects
24 drives online, 0 drives offline
```

The problem is, if I create a bucket: `mc mb minio/test-1/`  It only exists on the node it hits.  The minio instance is sitting behind the load balancer, so every 8th request it succeeds when doing `mc ls minio/test-1` or `mc cp file minio/test-1/` the rest of the requests complain (doing a `cp`): `mc: <ERROR> Failed to copy /tmp/somefile.yaml. Bucket test-1 does not exist.`

**Comment by kannappanr** [comment]
@base698 How did you start `MinIO`, looks like you have 8 different minio instances running behind nginx. If that is the case, what you are seeing is expected.

**Comment by base698** [comment]
https://github.com/minio/minio/blob/master/docs/orchestration/kubernetes/minio-distributed-statefulset.yaml

Using that, but have more than one data directory so have globbing at the end with `data{0...2}` at the end.

**Comment by harshavardhana** [comment]
From admin info it doesn't look like you have distributed setup running @base698 - please share your entire deployment yaml and also nginx configuration.

**Comment by base698** [comment]
Does this know to use port 9000: https://github.com/minio/minio/blob/master/docs/orchestration/kubernetes/minio-distributed-statefulset.yaml#L28

**Comment by base698** [comment]
At any rate, putting the port and http on it works.  I had deleted it when I copied.  Thanks for the help.
