### ISSUE TITLE
moving files manually in filesystem?

### ISSUE THREAD

**Issue by agoddard** [minio/minio#9035]
This project is awesome, I'm hoping I'm asking this question in the right place, feel free to point me elsewhere & close this if I'm not 😬. I'm using a pretty much vanilla setup - just pointing minio to a local zfs volume. I'm aware that much like S3, I can't `mv` a file, but rather I can copy a file to a new location and then delete the old one - in my testing it seems like I can go into the filesystem and `mv` a file to a new bucket and then minio sees the file correctly in the new bucket. I'm wondering though whether there's any minio metadata or similar that might break behind the scenes when I'm doing this, or whether it's ok to `mv` files in the filesystem in a small (1 user, me) minio install?

Thanks for such an ace project!

**Comment by kannappanr** [comment]
@agoddard There are things like `retention` that can be set on the object and those are stored in a different place. If you `mv` files in the backend, you will end up having stale metadata files. We will not advise this.

**Comment by agoddard** [comment]
thanks @kannappanr!
