### ISSUE TITLE
[Question] How to calculate used size

### ISSUE THREAD

**Issue by invent-lwj** [minio/minio#9038]
I run minio with openshift.
This is environment details:
Openshift 4.2, distributed mode, default setting of storage class, 4 instances, minio version: 2019-08-07T01-59-21Z.
/export directory is mounted with nfs persistence volume, each persistence volume is 4GB capacity.

The question:
1. After deployed, don't upload any files, the used size of UI display is 442.73GB, nfs server capacity is large, but the pv size is 4G.
<img width="1417" alt="Screen Shot 2020-02-25 at 15 07 47" src="https://user-images.githubusercontent.com/20390953/75223652-e9345300-57e1-11ea-90b3-36bac89e6c02.png">

after i upload 1GB files, the used size of UI display is 456.71GB. 
<img width="1427" alt="Screen Shot 2020-02-25 at 15 12 07" src="https://user-images.githubusercontent.com/20390953/75223661-f05b6100-57e1-11ea-8411-994f145205df.png">

Question:
1. Minio how to calculate used size and how to calculate the max available capacity for user?
2. Why have so large used size in original state?
3. Why i upload 1G file, but the used size increase about 14GB? 
Thanks!

**Comment by harshavardhana** [comment]
Usage is based on the disk usage @invent-lwj in UI its basically displaying `df -h` output for your disk

**Comment by kannappanr** [comment]
@invent-lwj Currently browser displays usage like described by Harsha. If you want to know the actual data usage, you can use `mc admin info` command. Closing this issue as answered. Please feel free to reach out to us at https://slack.min.io for further questions
