### ISSUE TITLE
Make Cache Limit configurable as an absolute value

### ISSUE THREAD

**Issue by bagrat** [minio/minio#9040]
**Is your feature request related to a problem? Please describe.**
When deploying MinIO on Kubernetes as S3 gateway using ephemeral storage, the available space that is visible to MinIO represents the size of the Node volume, which might be different across the Nodes and especially across clusters. Because of this, we cannot apply the same `MINIO_CACHE_LIMIT` percentage value for all pods.

**Describe the solution you'd like**
It would be very handy to be able to configure the cache limit as an absolute value (e.g. 50GB), so that no matter how much space you have on your Node, MinIO will use up to that much for caching. In case if there is less available space than the configured limit value, MinIO can fall back to using 80% of available space.

**Describe alternatives you've considered**
N/A

**Additional context**
The documentation states that Persistence Storage is required for S3 gateway mode, however we were able to deploy MinIO as S3 gateway using ephemeral storage, which is exactly what we need since we use it as a caching layer.

**Comment by harshavardhana** [comment]
> The documentation states that Persistence Storage is required for S3 gateway mode, however we were able to deploy MinIO as S3 gateway using ephemeral storage, which is exactly what we need since we use it as a caching layer.

where does it say that persistence is needed for s3 gateway? - if you want caching to persist then you need it to be persistent. Ephemeral means that if the container is destroyed all your cached content is gone.

> When deploying MinIO on Kubernetes as S3 gateway using ephemeral storage, the available space that is visible to MinIO represents the size of the Node volume, which might be different across the Nodes and especially across clusters. Because of this, we cannot apply the same `MINIO_CACHE_LIMIT` percentage value for all pods.

Please deploy with equal storage, it is not in our interest to support heterogeneous environments.

**Comment by bagrat** [comment]
> where does it say that persistence is needed for s3 gateway?

From the official Helm Chart I inferred that running in gateway mode is actually the standalone mode, and [this doc](https://github.com/minio/minio/blob/6f2b4675fa781a8497501e5ee38d99099cb72de3/docs/docker/README.md#run-standalone-minio-on-docker) says it needs persistent storage. But this is a secondary question.

> Ephemeral means that if the container is destroyed all your cached content is gone.

Right, this is actually exactly what we need for our deployment.

> Please deploy with equal storage, it is not in our interest to support heterogeneous environments.

The nodes in our cluster may have different storage sizes. Does this ^ mean you will not consider this issue further?

**Comment by harshavardhana** [comment]
@bagrat we designed cache to be deployed on homogeneous nodes, it doesn't make sense for us to support heterogeneous use cases at all. It complicates deployment in general.

So yes it is not something we would want to pursue.

**Comment by bagrat** [comment]
Thanks for the explanation @harshavardhana
