### ISSUE TITLE
Minio doesn't respond to AWS copyObject()... sometimes

### ISSUE THREAD

**Issue by OmegaVVeapon** [minio/minio#9041]
Use-case
I'm using the AWS Java SDK to do a [copyObject()](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3.html#copyObject-com.amazonaws.services.s3.model.CopyObjectRequest-) call to Minio in order to add some metadata to an existing object after successfully writing it to Minio.

Expected Behavior
The method should replace the Minio S3 object's metadata successfully.

## Current Behavior
Ok, so here's where things get really really strange.

I'm testing 2 paths.

Path #1- I run the copyObject() from a Java process running on my local host machine to a Minio Docker container exposed on port 9000.

Path #2- I run the copyObject()  from a Java process running on a Docker container in the same network as Minio.

Path #1 works **PERFECTLY**

My application sends:

```
PUT /dev/gM7MgOzmxc/LdcxqPxm/0pKCEdS1/0pKCEdS1 HTTP/1.1
Host: localhost:9000
amz-sdk-invocation-id: 6c6d2719-9a54-c8b6-90ba-01244e478660
amz-sdk-retry: 0/0/500
Authorization: AWS4-HMAC-SHA256 Credential=lmltester/20200225/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-acl;x-amz-content-sha256;x-amz-copy-source;x-amz-date;x-amz-meta-content-type;x-amz-metadata-directive, Signature=af816d48c3fc79cfb2ea503058e48d07bb8b8067b3c4440fe72bb082d6cce9c8
Content-Type: video/mp4
User-Agent: aws-sdk-java/1.11.700 Linux/4.15.0-88-generic OpenJDK_64-Bit_Server_VM/11.0.6+10-post-Ubuntu-1ubuntu118.04.1 java/11.0.6 vendor/Ubuntu
x-amz-acl: public-read
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-copy-source: /dev/gM7MgOzmxc/LdcxqPxm/0pKCEdS1/0pKCEdS1
X-Amz-Date: 20200225T141751Z
x-amz-meta-Content-Type: video/mp4
x-amz-metadata-directive: REPLACE
Content-Length: 0
Connection: Keep-Alive
````

And minio responds:

```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 232
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO/RELEASE.2020-02-20T22-51-23Z
Vary: Origin
X-Amz-Request-Id: 15F6AAF1175F7031
X-Xss-Protection: 1; mode=block
Date: Tue, 25 Feb 2020 14:17:52 GMT

<?xml version="1.0" encoding="UTF-8"?>
<CopyObjectResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><LastModified>2020-02-25T14:17:51.375Z</LastModified><ETag>&#34;87d3918b0c48c90864d264289d175acd&#34;</ETag></CopyObjectResult>
```

However, the Docker use-case (Path #2) causes Minio to NOT respond for whatever reason?

In this use case I send:

```
PUT /dev/gM7MgOzmxc/Q0DEaOCE/o7liPAbj/o7liPAbj HTTP/1.1
Host: minio:9000
amz-sdk-invocation-id: c26cb47e-de3b-c36b-4be2-7b6bce998048
amz-sdk-retry: 0/0/500
Authorization: AWS4-HMAC-SHA256 Credential=lmltester/20200225/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-acl;x-amz-content-sha256;x-amz-copy-source;x-amz-date;x-amz-meta-content-type;x-amz-metadata-directive, Signature=f8b55e6d6091917febf880836ca5fd5029c1b41b3d254010a924733faabdfe86
Content-Type: video/mp4
User-Agent: aws-sdk-java/1.11.700 Linux/4.15.0-88-generic OpenJDK_64-Bit_Server_VM/25.212-b04 java/1.8.0_212 vendor/IcedTea
x-amz-acl: public-read
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-copy-source: /dev/gM7MgOzmxc/Q0DEaOCE/o7liPAbj/o7liPAbj
X-Amz-Date: 20200225T152031Z
x-amz-meta-Content-Type: video/mp4
x-amz-metadata-directive: REPLACE
Content-Length: 0
Connection: Keep-Alive
```

and Minio doesn't respond back at all (Notice how the `Host` header is now `minio:9000`. Minio being the service name for the Minio container, the IP is resolvable by the Java process.) 

The AWS library retries multiple times, and never gets a response. Eventually, it gives up and throws an exception.

## Possible Solution
Wish I knew... I don't know why this codepath is behaving differently.

## Steps to Reproduce (for bugs)

1. Change the S3 object's metadata with copyObject in Minio
2. Do this when both minio and your application are bound to localhost
3. Do this when they are on different domains (like they were in my Docker setup)

## Context

I'm trying to use Minio as a dev S3 container for testing inside a docker-compose.yml.

## Regression
Not to my knowledge

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

`Linux 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
Can you share an example code? This helps us reproduce this faster.

**Comment by OmegaVVeapon** [comment]
Yeah, I was thinking about that.

I could try to write a quick Python script (my relationship with Java is rocky at best) and try to repro the issue with that.
If it works, I'll gladly send you a Github link to the repo. I should have it ready no latter than tomorrow.

Thanks for the super quick response!

**Comment by kannappanr** [comment]
@OmegaVVeapon If there is no response, then the most probable reason would be that the request did not reach `MinIO` server

**Comment by OmegaVVeapon** [comment]
> @OmegaVVeapon If there is no response, then the most probable reason would be that the request did not reach `MinIO` server

Yes, that's what I thought as well, except that's ruled out by the fact that I see the application's `PUT` request to change the S3 object's metadata on the Minio container. So it's definitely getting there.

**Comment by harshavardhana** [comment]
@OmegaVVeapon understood, an example code would go a long way -- thanks

**Comment by OmegaVVeapon** [comment]
Yeah, I was not able to reproduce this issue with the Python boto3 lib. My branch is [here](https://github.com/OmegaVVeapon/minio-test/tree/dev).

I guess I'll have to recode this in Java with the same AWS library that's failing in our production code over the weekend. At least now it sounds like the issue is with the Java library and not with Minio. I'll update as soon as I can.

**Comment by harshavardhana** [comment]
> I guess I'll have to recode this in Java with the same AWS library that's failing in our production code over the weekend. At least now it sounds like the issue is with the Java library and not with Minio. I'll update as soon as I can.

Thanks for the update @OmegaVVeapon

**Comment by OmegaVVeapon** [comment]
Was never able to reproduce the issue in an isolated environment.
It seems to only happen in that module for some unknown reason.
I'll close this ticket, thank you for your help.
