### ISSUE TITLE
Panic Reading Cached Object in New Gateway S3

### ISSUE THREAD

**Issue by christopherbate** [minio/minio#9053]
When starting a new server in S3 gateway mode with caching enabled, read/copy commands to objects will succeed until I hit the "MINIO_CACHE_AFTER" mark, after which the server panics and the `mc` CLI hangs.  I can see the cache directory has data in it. 

## Expected Behavior

The server should complete the request and return my object.

## Current Behavior

The server panics at the MINIO_CACHE_AFTER+1 request.

## Possible Solution

It looks from the panic message that the line in question is `cmd/disk-cache.go:209`. There is no nil pointer check in the `if` statement, while the previous case does do a nil pointer check, which seems odd.

## Steps to Reproduce (for bugs)

1. Start new Minio Gateway S3 server using current recommended MINIO_CACHE_ values 
from the documentation
2. Execute `minio config host add ...`
3. Execute `minio cp [some object] ./someObj`  MINIO_CACHE_AFTER+1 times.

## Regression

Possibly, as it looks like the last merge is related to the caching. I haven't used caching behavior before and am trying to start a new server.

## Your Environment

* Version used (`minio version`): 
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:
Linux Ubuntu 18.04, latest Docker image RELEASE.2020-02-27T00-23-05Z

**Comment by kannappanr** [comment]
@christopherbate Thanks for reporting this issue. We will take a look and get back to you.

**Comment by trapped** [comment]
Running into this panic as well; changing https://github.com/minio/minio/blob/224b4f13b8e94e1a3bd4b4149e3127c847168cb3/cmd/disk-cache.go#L209 to `if cc != nil && c.noStore` should probably be enough
