### ISSUE TITLE
ERROR Unable to initialize gateway backend: function not implemented

### ISSUE THREAD

**Issue by yuyuanshifu** [minio/minio#9065]
1、/gshare is my lustre path
2、I want to use minio to manage lustre file by this command:
docker run -p 9005:9000 --name minio5  -e "MINIO_ACCESS_KEY=minio"  -e "MINIO_SECRET_KEY=minio123" -v /gshare:/gdata minio/minio gateway nas /gdata
3、Then occured the error:ERROR Unable to initialize gateway backend: function not implemented
4、How can I fix it?

**Comment by harshavardhana** [comment]
Your backend seems to not support fcntl locks, without such a support you cannot run nas gateway

**Comment by harshavardhana** [comment]
Closing as not our issue.
