### ISSUE TITLE
Failed to add notify_nats config using mc

### ISSUE THREAD

**Issue by RemiSahl** [minio/minio#9066]
Mc command fails when trying to add a new notification configuration:
```bash
mc admin config set dev/ notify_nats:1 address=default-nats.default.svc:4222 subject=minio.1
mc: <ERROR> Cannot set 'notify_nats:1 address=default-nats.default.svc:4222 subject=minio.1' to server. Unable to disable configured targets '_:amqp'.
```

My minio is also connected to a rabbitmq broker and everything works fine when I add new notifications there. When I try on the default notification (notify_nats), the notification is setup even though the error is the same:
```bash
mc admin config set dev/ notify_nats address=default-nats.default.svc:4222 subject=test
mc: <ERROR> Cannot set 'notify_nats address=default-nats.default.svc:4222 subject=test' to server. Unable to disable configured targets '_:amqp'.
mc admin config get dev notify_nats
notify_nats address=default-nats.default.svc:4222 subject=test username= password= token= tls=off tls_skip_verify=off cert_authority= client_cert= client_key= ping_interval=0 streaming=off streaming_async=off streaming_max_pub_acks_in_flight=0 streaming_cluster_id= queue_dir= queue_limit=0
```

Everything works fine when I set amqp notifications:
```bash
mc admin config set dev notify_amqp:2 durable=on exchange=test exchange_type=fanout routing_key=test url=amqp://rabbitmq-service.default.svc:5672
Setting new key has been successful.
Please restart your server with `mc admin service restart dev`.
```

## Expected Behavior

I was expecting nats notifications to work properly, and not to interact with unrelated amqp broker.

## Current Behavior

I cannot configure nats notifications

## Possible Solution

The error is raised here, I don't think nats notifications were supposed to impact amqp setup. https://github.com/minio/minio/blob/1b427ddb695a89bf731c3045859a3fee976585a2/cmd/config/notify/parse.go#L273

## Context
I configured the amqp notifications a while ago, when mc was still using the json version, and just recently was trying to add nats notifications
```
mc admin config get > config.json
```

## Your Environment

I am running the latest mc and minio versions. My minio is running in docker on a kubernetes cluster as a statefulset (single instance).

**Comment by RemiSahl** [comment]
I managed to get it to work.
I had setup default amqp notifications using environment variables like this:
```
 - name: MINIO_NOTIFY_AMQP_ENABLE
   value: "on"
 - name: MINIO_NOTIFY_AMQP_URL
   value: amqp://rabbitmq-service.default.svc:5672
 - name: MINIO_NOTIFY_AMQP_EXCHANGE
   value: minio_events
 - name: MINIO_NOTIFY_AMQP_EXCHANGE_TYPE
   value: fanout
 - name: MINIO_NOTIFY_AMQP_DURABLE
   value: "on"
``` 
Commenting these and restarting the server fixed the issue somehow and I was able to use mc to setup all the notifications.

**Comment by harshavardhana** [comment]
Using ENV means ENV overrides all `mc admin config` settings for those targets, but it is unusual that AQMP is affecting nats settings - looks like a bug // cc @kannappanr
