### ISSUE TITLE
Overwrite header host when making resigned URL

### ISSUE THREAD

**Issue by b4nst** [minio/minio#9069]
**Is your feature request related to a problem? Please describe.**

Currently it is not possible to change the host of the generated presigned url. This could be useful in many cases like this one :

A gateway running inside a docker container, communicating with Minio server through docker network (http://minio:9000) will generate a presigned url with minio:9000 link. But the final user will use the Minio public endpoint to use this link.

**Describe the solution you'd like**
To be able to overwrite the host option through presignedUrl function, which is already used and implemented.

**Describe alternatives you've considered**
Setting Minio public endpoint inside the gateway (not ideal in terms of network isolation, and do not work on local stacks)

**Comment by harshavardhana** [comment]
You generate the presigned URL on the client side, with the correct hostname which talks or proxies to MinIO. 

There is no server component change needed. Presigned is entirely client driven operation.

**Comment by b4nst** [comment]
Oops sorry, I though I was raising the issue on NodeJS client, my bad.
