### ISSUE TITLE
[resolved] Docker registry can't push images to Minio in distributed mode

### ISSUE THREAD

**Issue by annkam** [minio/minio#9070]
I followed [this](https://github.com/harshavardhana/harbor-minio) guide to set up Minio as storage backend for Harbor Docker Registry. It works ok if I use one instance of Minio. However, I run Minio in distributed mode in production (12 nodes) and it seems that registry can't work with it correctly.

## Expected Behavior
I should be able to push an image to my registry with s3 cluster configured as backend as it's described in the post.

## Current Behavior
This is what happens in Docker CLI when I try to push an image:
`# docker push registry-ha-31.s7.aero/library/python:alpine3.7                                                                                                                                                                                      
The push refers to repository [registry-ha-31.s7.aero/library/python]
5fa31f02caa8: Pushing [==================================================>]  6.453MB
88e61e328a3c: Pushing [==================================================>]  4.608kB
9b77965e1d3f: Retrying in 1 second
50f8b07e9421: Pushing [==================================================>]  838.7kB
629164d914fc: Pushing [==================================================>]  4.464MB
blob upload unknown`

I see the following error in registry logs:

`Feb 27 03:52:43 10.11.52.1 registry[4604]: time="2020-02-27T03:52:43.834679964Z" level=error msg="upload resumed at wrong offest: 308642 != 308482" auth.user.name=admin go.version=go1.12.12 http.request.host=registry-ha-31.s7.aero http.request.id=e418f27f-3ee2-4a1d-b145-7e3ab19d44e4 http.request.method=PUT http.request.remoteaddr=10.7.33.246 http.request.uri="/v2/library/python/blobs/uploads/92a9b9bf-2b60-49da-888f-f84361eaa3ce?_state=I17NrvwNAA3P9S_GUe4bOXOmjTWFsKh-8qcHpx3KGdh7Ik5hbWUiOiJsaWJyYXJ5L3B5dGhvbiIsIlVVSUQiOiI5MmE5YjliZi0yYjYwLTQ5ZGEtODg4Zi1mODQzNjFlYWEzY2UiLCJPZmZzZXQiOjMwODQ4MiwiU3RhcnRlZEF0IjoiMjAyMC0wMi0yN1QwMzo1Mjo0MloifQ%3D%3D&digest=sha256%3A692f29ee68fa6bab04aa6a1c6d8db0ad44e287e5ff5c7e1d5794c3aabc55884d" http.request.useragent="docker/19.03.2 go/go1.12.8 git-commit/6a30dfca03 kernel/4.9.0-11-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.2 \(linux\))" vars.name="library/python" vars.uuid=92a9b9bf-2b60-49da-888f-f84361eaa3ce`

## Steps to Reproduce (for bugs)
1. Set up Minio in distributed mode
2. Configure Harbor to use it as a storage backend
3. Push an image

## Context
I want to deploy HA Harbor installation and consider HA Minio as an image and chart storage

## Your Environment
* Minio RELEASE.2020-02-27T00-23-05Z running in Docker
* Harbor Registry v1.9.4
* Docker 18.06.3-ce
* Docker CLI version 19.03.2 (used to push image)
* Server type and version:
* Operating System and version (`Linux 4.19.95-coreos`):

**Comment by harshavardhana** [comment]
Thanks @annkam we will take a look.

**Comment by harshavardhana** [comment]
@annkam would it be possible to generate an `mc admin trace -v` when you are doing `docker push`? and attach it here.

**Comment by annkam** [comment]
[trace1.log](https://github.com/minio/minio/files/4322102/trace1.log)

**Comment by annkam** [comment]
Are there any updates on this issue? The problem is still present with Harbor 1.10.2 and Minio RELEASE.2020-04-15T19-42-18Z

**Comment by harshavardhana** [comment]
> Are there any updates on this issue? The problem is still present with Harbor 1.10.2 and Minio RELEASE.2020-04-15T19-42-18Z

@annkam we haven't had time to look at this, we have other priority work. We will get back to this in future.

**Comment by harshavardhana** [comment]
So @annkam I tested with docker registry and it seems to be working fine? are you using any auto-encryption with server config?

**Comment by annkam** [comment]
Hello! Yes, we use auto-encryption.

**Comment by harshavardhana** [comment]
Fixed by #9970
