### ISSUE TITLE
[wont fix] Google cloud storage gateway full S3 support

### ISSUE THREAD

**Issue by anton-kotenko** [minio/minio#9073]
**Is your feature request related to a problem? Please describe.**
We are running docker registry (https://docs.docker.com/registry/)  in GCP, AZURE and AWS.
And from organizational point of view,it would be easier for us  and more consistent to use docker-registry over S3 based storage (though according to doc's it is able to work on top of google cloud storage). 
So we've tried to run minio as google-cloud-storage gateway and docker-registry on top of it. It happens that it works for small images (e.g. `alpine:latest`), but does not work for our own (I suppose due to larger size, approx. 100MB).

Investigation (`mc admin trace -ev`) gives result: minio as google cloud storage gateway does not support several methods, like `ListMultipart`, and several more.

**Describe the solution you'd like**
So it would be great if minio would provide full support for all S3 methods in gateway to google cloud storage mode.

**Describe alternatives you've considered**
In our case we would be able to run docker registry over google cloud storage buckets directly,
or start minio as s3 server over google filestore (simply nfs mounted to machine with minio) 

So In general this more like a question then feature request:
1. Is it possible to provide full support for S3 in such case
2. It it's possible, do you have plans to do it?

**Comment by harshavardhana** [comment]
> So it would be great if minio would provide full support for all S3 methods in gateway to google cloud storage mode.

Unfortunately, this is not a priority right now, feel free to send PRs if you must we will happily review and accept it.

**Comment by anton-kotenko** [comment]
Hi, @harshavardhana 
Thank you for answer. 
I understand. Probably, if there will be time to prepare PR's, than it will be done.

**Comment by harshavardhana** [comment]
> I understand. Probably, if there will be time to prepare PR's, than it will be done.

Let's close this and please submit PRs when you have the time GCS supports S3 API in compatibility mode already, we have no intention to provide a full S3 layer on top of GCS ourselves. 

Current implementation serves our purpose for now. Closing this issue.
