### ISSUE TITLE
create bucket in feration mode

### ISSUE THREAD

**Issue by smallollams** [minio/minio#9074]
**Is your feature request related to a problem? Please describe.**
 I'm always confused about how to create a bucket in federation mode.
The first thing I know to save the object is to get the cluster IP according to mybucket.domin,but if i want to create a new bucket,how can i get the ip addr of the cluster,and How do I know which cluster has enough capacity to hold the next object.

thank you for your attention

**Comment by kannappanr** [comment]
@smallollams Not sure I understand your question. In federation mode, a bucket does not reside in more than one cluster. If you are referring to a bucket then objects within that bucket will not reside in another cluster.

Federation mode means there is a collection of clusters and you should know the IP address of the clusters, so that you can use that to create a bucket in a cluster where there is more free space.

**Comment by smallollams** [comment]
Thanks for your reply. I didn't make it clear。

The situation is，using the federation mode with etcd and coreDNS. if A bucket already exists in a cluster，client can get the cluster ip by mybucket.domin.when client want to create a new bucket, can't get cluster ip by newbucket.domin,because newbucket reside in no one cluster.
so how client can get the right cluster ip.the "right cluster" means the cluster which is free space,because several of the clusters maybe is not space free.

thank you again!

**Comment by smallollams** [comment]
> @smallollams Not sure I understand your question. In federation mode, a bucket does not reside in more than one cluster. If you are referring to a bucket then objects within that bucket will not reside in another cluster.
> 
> Federation mode means there is a collection of clusters and you should know the IP address of the clusters, so that you can use that to create a bucket in a cluster where there is more free space.

@kannappanr
Thanks for your reply. I didn't make it clear。

The situation is，using the federation mode with etcd and coreDNS. if A bucket already exists in a cluster，client can get the cluster ip by mybucket.domin.when client want to create a new bucket, can't get cluster ip by newbucket.domin,because newbucket reside in no one cluster.
so how client can get the right cluster ip.the "right cluster" means the cluster which is free space,because several of the clusters maybe is not space free.

thank you again!

**Comment by smallollams** [comment]
> @smallollams Not sure I understand your question. In federation mode, a bucket does not reside in more than one cluster. If you are referring to a bucket then objects within that bucket will not reside in another cluster.
> 
> Federation mode means there is a collection of clusters and you should know the IP address of the clusters, so that you can use that to create a bucket in a cluster where there is more free space.

@kannappanr
Thanks for your reply. I didn't make it clear。

The situation is，using the federation mode with etcd and coreDNS. if A bucket already exists in a cluster，client can get the cluster ip by mybucket.domin.when client want to create a new bucket, can't get cluster ip by newbucket.domin,because newbucket reside in no one cluster.
so how client can get the right cluster ip.the "right cluster" means the cluster which is free space,because several of the clusters maybe is not space free.

thank you again!

**Comment by harshavardhana** [comment]
First you shouldn't be using federation for expanding storage, this used to be the case in the past but not anymore.

@smallollams https://github.com/minio/minio/tree/master/docs/distributed#expanding-existing-distributed-setup

Federation is necessary for global namespace across data centers. Creating buckets based on free space is not really a requirement.

**Comment by kannappanr** [comment]
@smallollams Closing this issue. Please feel free to reach out to us if you have further questions
