### ISSUE TITLE
AWS s3 Full access to work

### ISSUE THREAD

**Issue by downright-ux** [minio/minio#9080]
## Expected Behavior
When setting the following I would assume that I would be able to read any s3 bucket information for that region.
`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "aws:RequestedRegion": "your-region"
                }
            }
        }
    ]
}
`

## Current Behavior
Does nothing. I go to console and displays no buckets.
If I give full access to s3 then everything works fine.

## Possible Solution
Make a variable for default bucket on s3 

## Steps to Reproduce (for bugs)
basic setup and use the following above permissions to any region

## Your Environment
Running this via docker-compose and also helm

**Comment by harshavardhana** [comment]
> { "Version": "2012-10-17", "Statement": [ { "Sid": "VisualEditor0", "Effect": "Allow", "Action": "s3:*", "Resource": "*", "Condition": { "StringEquals": { "aws:RequestedRegion": "your-region" } } } ] }

We do not support `aws:RequestedRegion` @downright-ux conditional because MinIO is a single region deployment. You cannot have multiple regions of buckets on single deployment.

**Comment by downright-ux** [comment]
Then is this the more preferred way to set IAM. 
``

**Comment by downright-ux** [comment]
Is this the more preferred way


`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:GetAccessPoint",
                "s3:PutAccountPublicAccessBlock",
                "s3:GetAccountPublicAccessBlock",
                "s3:ListAllMyBuckets",
                "s3:ListAccessPoints",
                "s3:ListJobs",
                "s3:CreateJob",
                "s3:HeadBucket"
            ],
            "Resource": "*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:*:*:accesspoint/*",
                "arn:aws:s3:::*/*",
                "arn:aws:s3:*:*:job/*",
                "arn:aws:s3:::<your bucket name>"
            ]
        }
    ]
}
`

**Comment by harshavardhana** [comment]
This is full access @downright-ux to a specific bucket

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:CreateBucket",
        "s3:DeleteBucket"
      ],
      "Effect": "Deny",
      "Resource": "arn:aws:s3:::bucket_name"
    },
    {
      "Action": [
        "s3:GetBucketLocation"
      ],
      "Effect": "Allow",
      "Resource": "arn:aws:s3:::bucket_name"
    },
    {
      "Action": "s3:*",
      "Effect": "Allow",
      "Resource": "arn:aws:s3:::bucket_name/*"
    }
  ]
}
```

**Comment by downright-ux** [comment]
Thank you I got this working now
