### ISSUE TITLE
there's no recovery message after a node rejoins the cluster

### ISSUE THREAD

**Issue by FlorinAndrei** [minio/minio#9081]
I made a 4-node cluster. Each node has one volume.
I killed one node and kept an eye on the other three nodes. I saw the error messages posted by the remaining nodes.
Then I brought the 4th node back up.

## Expected Behavior

I was expecting the other 3 nodes to post a message saying "okay, all is good now, the 4th node has rejoined us".

## Current Behavior

Nothing happened. There's was no message posted on stdout/stderr from the other nodes.

## Possible Solution

Would be very nice to print something indicating recovery.

## Steps to Reproduce (for bugs)

1. Launch a 4-node distributed cluster
2. Kill one node, wait for error messages from the other 3 nodes
3. Rejoin the 4th node.
4. Wait for messages.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
This is on purpose, to avoid flooding the console. The best way to monitor nodes is using Prometheus, or mc admin info.

**Comment by kannappanr** [comment]
@FlorinAndrei Closing the issue based on the above comment. Please feel free to let us know if you have further questions.

**Comment by FlorinAndrei** [comment]
Guys, it's quite confusing when you're new to it and you're wondering what's going on.

Later on you can filter out a lot of stuff, in ELK or Prometheus. But "ninja" software that doesn't tell you what it's doing is hard to approach at first.
