### ISSUE TITLE
Minio always returns the default ETag for tarballs

### ISSUE THREAD

**Issue by thomas-jakemeyn** [minio/minio#9083]
## Expected Behavior
The ETag of a tarball should change when the tarball is updated (aka overridden in Minio).

## Current Behavior
The Etag of a tarball is always the default one: `00000000000000000000000000000000-1`. It is the same Etag for all tarballs and it does not change when the tarball is updated.

## Steps to Reproduce (for bugs)
1. Create a new bucket: `mc mb minio/test`.
2. Expose the bucket over HTTP: `mc policy set download minio/test`.
3. Upload a tarball into the bucket, e.g. `any.tar.gz`.
4. Check the header with `curl -I http://localhost:9000/test/any.tar.gz`. You should see the default ETag.

## Context
I use Minio to serve data [bundles](https://www.openpolicyagent.org/docs/latest/external-data/#option-3-bundle-api) to [OPA](https://www.openpolicyagent.org/) (_Open Policy Agent_) over HTTP. OPA expects tarballs and uses the ETag to know when to re-download a tarball. When OPA start, I see this:

```bash
{"level":"info","msg":"Bundle downloaded and activated successfully. Etag updated to \"00000000000000000000000000000000-1\".","name":"bundle1","plugin":"bundle","time":"2020-03-04T12:46:11Z"}
{"level":"info","msg":"Bundle downloaded and activated successfully. Etag updated to \"00000000000000000000000000000000-1\".","name":"bundle2","plugin":"bundle","time":"2020-03-04T12:46:11Z"}
```

## Regression
No

## Your Environment
* Version used: `RELEASE.2019-10-12T01-39-57Z` (but reproducible with `RELEASE.2020-02-27T00-23-05Z`)
* Operating System and version: Alpine 3.10 (in Docker)

**Comment by harshavardhana** [comment]
@thomas-jakemeyn how are you uploading the object?

**Comment by thomas-jakemeyn** [comment]
I do a `docker cp`.

**Comment by thomas-jakemeyn** [comment]
Good catch, that was the problem!
I replaced `docker cp` by `mc cp` and it works like a charm.
I will close this issue.
Thank you for your support!
