### ISSUE TITLE
Permit underscores in bucket names optionally.

### ISSUE THREAD

**Issue by chrisbecke** [minio/minio#9088]
**Is your feature request related to a problem? Please describe.**
minfs is a deprecated minio project that provided a
1. a FUSE driver that allowed minio (any s3) to be used as a mountable file system on linux.
2. a Docker plugin (minio/minfs) that, in turn, allowed `docker volume create` to leverage `minfs` to create and mount minio buckets as docker volumes.

* [Deprecate MinFS project](https://github.com/minio/minfs/issues/60)

However, the linked project rexray/s3fs, creates buckets using the passed in volume name, which in a compose, or swarm deployment, use an underscore as a namespace separator.

This causes recent versions of minio/minio itself (rather than mc) to fail to create volumes, with the error:

```
create example_data: VolumeDriver.Create: docker-legacy: Create: example_data: failed: error creating s3 bucket
```

when I try to `docker stack deploy -c mystack.yml example`

**Describe the solution you'd like**
An option to  minio would allow underscores in bucket names.

**Describe alternatives you've considered**
There is an outstanding issue on the rexray/s3fs issue board 
* https://github.com/rexray/rexray/issues/1309

Also am toying with the idea of using a proxy with a regex to rewrite the request, but suspect that that will fall afoul of the signing requirements.

**Additional context**
I am really torn on wether I prefer stronger compliance with the AWS bucket name requirements, or, given that the buckets represent docker volumes, and having a direct name mapping would aid diagnostics immensely, prefer in this one case to allow special characters.

**Comment by harshavardhana** [comment]
Existing directories on your disk in standalone mode are already supported to have _ or capitalized names.

We do not support creating new buckets in this manner because of AWS S3 DNS requirements.

So I am afraid it won't be possible.

**Comment by chrisbecke** [comment]
While I do appreciate that usually it is a good idea to adhere to the AWS S3 DNS requirements, 
1. the default mode of minio is path style rather than dns style.
2. this neatly avoids taking responsibility for the effective bait-and-switch of deprecating the minio/minfs project in favour of rexray/s3fs, but then breaking interop with rexray/s3fs having pushed minio docker users towards it.

**Comment by harshavardhana** [comment]
Unfortunately no it's not possible @chrisbecke , we wish to avoid cockpit style options in MinIO.

s3fs in general we encourage users to avoid, but if you must for legacy reasons rexray/s3fs is more maintained.

We may come back to it in future, if we see traction. But for now these are legacy use cases which we are not interested in supporting.
