### ISSUE TITLE
Cannot move folder loca form minion setting vps

### ISSUE THREAD

**Issue by TrungPhuNA** [minio/minio#9089]
- Cannot move(path_loca, path_minio)
`
		$full_path_source = Storage::disk('public')->getDriver()->getAdapter()->applyPathPrefix('css');
		$full_path_dest = Storage::disk('minio')->getDriver()->getAdapter()->applyPathPrefix('123job');

		\Storage::disk('minio')->move($full_path_source, $full_path_dest);`

**Comment by nitisht** [comment]
Please use the issue template to report issues, it is currently not clear what you're trying to achieve
