### ISSUE TITLE
Generate Pre-Signed Urls using Temporary Credential

### ISSUE THREAD

**Issue by Reza-Noei** [minio/minio#9093]
Hi guys, We want to generate Pre-Signed  Url using AWS Temporary Credentials.
Our Enterprise application uses Temp Tokens to grant access to one or more resources to an specific user.

we must to use pre-signed urls to get access into a bunch of resources directly.
So we must be able to give the ability of generating new Pre-signed Urls based on the Temp Token we gave to a Client. 

Anyway, the Client must be able to provide a pre-signed url to access directly to a resource.

here is the code we use: 

        class AmazonTest
         {
             public static string GetTextContents(string path)
             {
                 HttpWebRequest request = HttpWebRequest.Create(path) as HttpWebRequest;
                 HttpWebResponse response = request.GetResponse() as HttpWebResponse;
                 using (Stream stream = response.GetResponseStream())
                 using (StreamReader reader = new StreamReader(stream))
                 {
                     return reader.ReadToEnd();
                 }
         }

         public static string GetPreSigned(AmazonS3Client client, string bucket, string key)
         {
                 // Create a CopyObject request
                 GetPreSignedUrlRequest request = new GetPreSignedUrlRequest
                 {
                     BucketName = bucket,
                     Key = key,
                     Expires = DateTime.Now.AddMinutes(50),
                     Protocol = Protocol.HTTP
                 };
                 // Get path for request
                 return client.GetPreSignedURL(request);            
         }

and here is our usage:

        var config = new AmazonS3Config
        {
            RegionEndpoint = RegionEndpoint.USEast1, // MUST set this before setting ServiceURL and it should match the `MINIO_REGION` enviroment variable.
            ServiceURL = S3Endpoint, // replace http://localhost:9000 with URL of your MinIO server
            ForcePathStyle = true, // MUST be true to work correctly with MinIO server                           
        };
        var amazonS3Client = new AmazonS3Client("TempAccessKey", "TempSecretKey","TempSessionToken", config);

        var url = AmazonTest.GetPreSigned(amazonS3Client, "organizations", "Equation.txt");
        var Content = AmazonTest.GetTextContents(url);`

but we get this Error: 

         <Error>
         <Code>SignatureDoesNotMatch</Code>
         <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
         <Key>Equation.txt</Key>
         <BucketName>organizations</BucketName>
         <Resource>/organizations/Equation.txt</Resource> 
         <RequestId>15E615B7B7C44B10</RequestId>
         <HostId>2858b804-0459-43c9-b74b-091ee53a1563</HostId>
         </Error>

Can we have count on this feature ?
It's critically needed to our Enterprise application development Process.

**Comment by harshavardhana** [comment]
@Reza-Noei which version of MinIO are you using?

**Comment by Reza-Noei** [comment]
> 
> 
> @Reza-Noei which version of MinIO are you using?

Im using Minio Server Version :
RELEASE.2020-02-27T00-23-05Z

and AWSSDK.SecurityToken version: 3.3.104.38
and AWSSDK.S3 version: 3.3.110.30

**Comment by harshavardhana** [comment]
How did you obtain the temporary credentials?

**Comment by Reza-Noei** [comment]
> 
> 
> How did you obtain the temporary credentials?

Here is my function (body) for generating Temporary Credential: 

        public CredentialModel RequestTempReadToken(string Bucket)
        {
            Bucket = Bucket.ToLower();

            var amazonSecurityTokenService = new AmazonSecurityTokenServiceClient(Config.Instance.AccessKey,
                                                                                  Config.Instance.SecretKey,
                                                                                  GetSTSConfig(Config.Instance.EndPoint));

            Policy Policy = new Policy()
            {
                Version = POLICY_VERSION_DATE,
                Statements =
                new List<Statement>()
                    {
                        new Statement(Statement.StatementEffect.Allow)
                            {
                                Id = string.Empty,
                                Actions = new List<ActionIdentifier>() { new ActionIdentifier(GET_OBJECT_ACTION) },
                                Resources = new List<Resource>() { new Resource(RESOURCE_PREFIX + Bucket + "/*") }
                            }
                    }
            };

            var response = amazonSecurityTokenService.AssumeRole(new AssumeRoleRequest
            {
                DurationSeconds = Config.Instance.TempTokenLifeTime,
                Policy = Policy.ToJson(),
                RoleArn = DEFAULT_ARN_AWS,
                RoleSessionName = DEFAULT_ROLE_SESSION_NAME,
                ExternalId = DEFAULT_EXTERNAL_ID,
            });

            return new CredentialModel(response.Credentials.AccessKeyId,
                                       response.Credentials.SecretAccessKey,
                                       response.Credentials.SessionToken,
                                       response.Credentials.Expiration,
                                       Bucket);
        }


and here is GetSTSConfig: 

        private AmazonS3Config GetSTSConfig(string Endpoint)
        {
            return new AmazonS3Config
            {
                RegionEndpoint = RegionEndpoint.USEast1, // MUST set this before setting ServiceURL and it should match the `MINIO_REGION` enviroment variable.
                ServiceURL = Endpoint, // replace http://localhost:9000 with URL of your MinIO server
                ForcePathStyle = true, // MUST be true to work correctly with MinIO server                
            };
        }

**Comment by muktiarip** [comment]
@Reza-Noei may be the problem lies on AWS SDK you use, not the minio server.

I'm using minio server RELEASE.2020-02-27T00-23-05Z. Creating pre-signed URL for `getObject` operation using AWS SDK for JavaScript and AWS SDK for Python, both work well.

**Comment by Reza-Noei** [comment]
> 
> 
> @Reza-Noei may be the problem lies on AWS SDK you use, not the minio server.
> 
> I'm using minio server RELEASE.2020-02-27T00-23-05Z. Creating pre-signed URL for `getObject` operation using AWS SDK for JavaScript and AWS SDK for Python, both work well.

Ok, 

We were testing it on Javascript also.
Thanks for reply, i will ask from our FrontEnd Developer to check this on JavaScript.

I will back soon.

**Comment by chrisbecke** [comment]
How are you managing the endpoint you are dealing with?
In an enterprise environment, typically you will have your back end service communicating with minio using a different url (because its an in-data-center server to server call) than you return to the actual web client, and rewrite rules can get involved at various points.

The important thing is, the host header you provide to minio when building the presigned url, and the host header that eventually gets passed to minio later on when the presigned url is processed, must match.

**Comment by Reza-Noei** [comment]
> 
> 
> How are you managing the endpoint you are dealing with?
> In an enterprise environment, typically you will have your back end service communicating with minio using a different url (because its an in-data-center server to server call) than you return to the actual web client, and rewrite rules can get involved at various points.
> 
> The important thing is, the host header you provide to minio when building the presigned url, and the host header that eventually gets passed to minio later on when the presigned url is processed, must match.

If i was understood it, correct,
 
It's absolutely server to server calls while I'm preparing Temp Token for my Front End Application.

Actually I have a Permanent token which is set by config file in my back end and using this token i will try to create some temporary token for my client so using this token he could do anything permitted to actual minio server.

**Comment by Reza-Noei** [comment]
> 
> 
> @Reza-Noei may be the problem lies on AWS SDK you use, not the minio server.
> 
> I'm using minio server RELEASE.2020-02-27T00-23-05Z. Creating pre-signed URL for `getObject` operation using AWS SDK for JavaScript and AWS SDK for Python, both work well.

Hi, Again

I asked from our IT manager to install latest version of Minio on Linux Server. 

He just Checked it's version but it was about 2019.

Here is full description of Latest version of minio on Linux.
(We have downloaded this version past day from your Download Page)

     root@minio:~# minio version
     Version: 2019-09-05T23:24:38Z
     Release-Tag: RELEASE.2019-09-05T23-24-38Z 
     Commit-ID: b52a3e523cc3c4debc0ea2f86386377df5355c81

Is there any update for 2020 ?

**Comment by muktiarip** [comment]
@Reza-Noei The download link is https://min.io/download#/linux

More specific: `https://dl.min.io/server/minio/release/linux-amd64/minio`

**Comment by harshavardhana** [comment]
@Reza-Noei please upgrade to latest and let us know. Closing this issue for now as it's fixed already.
