### ISSUE TITLE
Webhook notification configuration via environment variables

### ISSUE THREAD

**Issue by kumy** [minio/minio#9094]
Enable webhook notification via environment variable as described [here](https://docs.min.io/docs/minio-bucket-notification-guide.html#webhooks)

## Expected Behavior
When configured via environment variables, the following command should output something like:
```bash
$ mc admin config get gk-new-theme-house/ notify_webhook:_
notify_webhook:_ endpoint=http://website/file-uploaded auth_token=mytoken queue_limit=0 queue_dir=
```

## Current Behavior
When declaring environment variables `MINIO_NOTIFY_WEBHOOK_ENABLE`, `MINIO_NOTIFY_WEBHOOK_ENDPOINT`, `MINIO_NOTIFY_WEBHOOK_AUTH_TOKEN` the SQS ARNS is listed on startup logs, but don't seems effective as shown by command:
```bash
$ mc admin config get gk-new-theme-house/ notify_webhook:_
notify_webhook:_ enable=off endpoint= auth_token= queue_limit=0 queue_dir= 
```

## Steps to Reproduce (for bugs)
Used two shells, one for `minio`, the other for `mc`
```
# shell 1
$ MINIO_ACCESS_KEY=test MINIO_SECRET_KEY=debugdebug ./minio server ./data
Attempting encryption of all config, IAM users and policies on MinIO backend
Endpoint:  http://192.168.125.103:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000                                  
AccessKey: test 
SecretKey: debugdebug 

Browser Access:
   http://192.168.125.103:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000                                  

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.125.103:9000 test debugdebug

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

# shell 2
$ mc config host add test http://127.0.0.1:9000 test debugdebug
Added `test` successfully.
$ mc admin config get test/ notify_webhook:_
notify_webhook:_ enable=off endpoint= auth_token= queue_limit=0 queue_dir= 


# shell 1
^C
$ MINIO_ACCESS_KEY=test MINIO_SECRET_KEY=debugdebug MINIO_NOTIFY_WEBHOOK_ENABLE=on MINIO_NOTIFY_WEBHOOK_ENDPOINT=http://127.0.0.1:8080/ MINIO_NOTIFY_WEBHOOK_AUTH_TOKEN=mytoken ./minio server ./data
Endpoint:  http://192.168.125.103:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000                                  
AccessKey: test 
SecretKey: debugdebug 
SQS ARNs:  arn:minio:sqs::_:webhook

Browser Access:
   http://192.168.125.103:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000                                  

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.125.103:9000 test debugdebug

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

# shell 2
$ mc admin config get test/ notify_webhook:_
notify_webhook:_ enable=off endpoint= auth_token= queue_limit=0 queue_dir= 

$ mc admin config set test notify_webhook enable=on endpoint="http://website/s3/file-uploaded" auth_token="mytoken"
Setting new key has been successful.
Please restart your server with `mc admin service restart test`.
$ mc admin config get test/ notify_webhook:_
notify_webhook:_ enable=off endpoint= auth_token= queue_limit=0 queue_dir= 
$ mc admin service restart test
Restart command successfully sent to `test`.
Restarted `test` successfully.


# shell 1
Restarting on service signal
Endpoint:  http://192.168.125.103:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000                                  
AccessKey: test 
SecretKey: debugdebug 
SQS ARNs:  arn:minio:sqs::_:webhook

Browser Access:
   http://192.168.125.103:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000                                  

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.125.103:9000 test debugdebug

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

# shell 2
$ mc admin config get test/ notify_webhook:_
notify_webhook:_ endpoint=http://website/s3/file-uploaded auth_token=mytoken queue_limit=0 queue_dir= 
```

## Context
Tried to configure a webhook in minio out of the box in a docker swarm stack.

## Regression
I don't know.

## Your Environment
* Version used (`minio version`): RELEASE.2020-03-05T01-04-19Z and docker latest image from today.
* Server type and version: `Ubuntu 19.10`
* Operating System and version (`uname -a`): `Linux kumy-desktop 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Link to your project: https://github.com/geokrety/geokrety-website/tree/feature/new-theme

## Note
I've first seen this as the webhook was never received by the webserver, to open this issue, I found that relying on `mc admin config get test/ notify_webhook:_` result seems reliable.

Thanks for your time!

**Comment by poornas** [comment]
@kumy, this is expected behavior. the `mc admin config get` command will not show config set via environment variables - however when server starts up, any config settings in config.json (set via mc) will be overridden by the env settings. Did you do a `mc event add` as described in the [docs](https://docs.min.io/docs/minio-client-complete-guide.html#event) using the SQS ARN `arn:minio:sqs::_:webhook`  to subscribe to event notifications?

**Comment by kumy** [comment]
> this is expected behavior. the mc admin config get command will not show config set via environment variables

Ok, why not…

> Did you do a mc event add as described in the docs using the SQS ARN arn:minio:sqs::_:webhook to subscribe to event notifications?

I have tried `mc event add` at one moment, but can't remember what the exact result was. My normal workflow would be to ensure notifications configurations are present in minio by declaring them via code. The first step `mc admin config set…` seems feasible per using environment variables - but only _allow to declare one weebhook url_ :disappointed:? The [syntax](https://docs.min.io/docs/minio-bucket-notification-guide.html#webhooks) `MINIO_NOTIFY_WEBHOOK_ENABLE` doesn't allow defining the `:name`, I would have thought it would be `MINIO_NOTIFY_WEBHOOK_<NAME>_ENABLE`, `MINIO_NOTIFY_WEBHOOK_<NAME>_ENDPOINT`…

My actual code is:

https://github.com/geokrety/geokrety-website/blob/918a05f6a9b03e42052f1cb9cbf8bdd138f02311/website/app/GeoKrety/Controller/Cli/S3Buckets.php#L90-L106

https://github.com/geokrety/geokrety-website/blob/918a05f6a9b03e42052f1cb9cbf8bdd138f02311/website/app/GeoKrety/Controller/Cli/S3Buckets.php#L125-L127

With this code I successfully used `mc event list test/gk-avatars` and seen expected outputs.
I receive webhook calls only after issuing manually `mc admin config set test notify_webhook enable=on […]` + `mc admin service restart test` - Just using environment variables are not sufficient. At this point I successfully receive 2 calls per `mc cp …`.

BTW: is this normal to receive 2 webhook calls for one HTTP PUT?
* One with content type header something like ~`binary gz`, an empty payload and no Authorization header.
* And a second with the correct Authorisation header and a json body.

Should I open a issue for that or [just ignore the first request](https://github.com/geokrety/geokrety-website/blob/918a05f6a9b03e42052f1cb9cbf8bdd138f02311/website/app/GeoKrety/Controller/WebhookS3PictureUploaded.php#L7-L11)?

**Comment by harshavardhana** [comment]
The env value is not prefixed in-between but at the end

```
<Env>_targetname
```

**Comment by harshavardhana** [comment]
> Should I open a issue for that or [just ignore the first request](https://github.com/geokrety/geokrety-website/blob/918a05f6a9b03e42052f1cb9cbf8bdd138f02311/website/app/GeoKrety/Controller/WebhookS3PictureUploaded.php#L7-L11)?

Just ignore the first request @kumy the first request is a dummy to ensure the backend is online. 

> I have tried `mc event add` at one moment, but can't remember what the exact result was. My normal workflow would be to ensure notifications configurations are present in minio by declaring them via code. The first step `mc admin config set…` seems feasible per using environment variables - but only _allow to declare one weebhook url_ ? The [syntax](https://docs.min.io/docs/minio-bucket-notification-guide.html#webhooks) `MINIO_NOTIFY_WEBHOOK_ENABLE` doesn't allow defining the `:name`, I would have thought it would be `MINIO_NOTIFY_WEBHOOK_<NAME>_ENABLE`, `MINIO_NOTIFY_WEBHOOK_<NAME>_ENDPOINT`…


Then env should be 

```
MINIO_NOTIFY_WEBHOOK_ENABLE_<target>
MINIO_NOTIFY_WEBHOOK_ENDPOINT_<target>
```

> Ok, why not…
> 

It will be presented differently in the future, for now, it is only config values.

**Comment by kumy** [comment]
Thanks @harshavardhana @poornas now that I have updated my env it seems to work nicely.
Please find PR #9103.
