### ISSUE TITLE
[resolved] Access denied if the targeted folder doesn't exist : putObject

### ISSUE THREAD

**Issue by hamednaim** [minio/minio#9095]
putObject works fine if the folder already exists,    the problem is when the folder is not existant before

io.minio.errors.ErrorResponseException: Access Denied.
	at io.minio.MinioClient.executeReq(MinioClient.java:1220)
	at io.minio.MinioClient.execute(MinioClient.java:1082)

minioClient.putObject(bucketName, fileName, InputStream, "application/octet-stream");

![image](https://user-images.githubusercontent.com/36676939/76066290-a286eb80-5f8d-11ea-982e-bc4077a9f1f0.png)

**Comment by klauspost** [comment]
Do you mean if the bucket doesn't exist? Your question isn't very clear.

The S3 API requires you to create the bucket before adding content to it.

**Comment by hamednaim** [comment]
Thanks for your reply, 
No, the bucket does exist, my problem is that if i try to putObject(bucketName,**"subfolder/file.txt"**,InputStream,contentType)   the **subfolder** **doesn't get created on its own**, it work only if the subfolder directory **already exists**.

**Comment by kannappanr** [comment]
@hamednaim Can you please use the standard template and fill in that information. Maybe the minio process does not have permission to create subfolders

```
 $ mc ls play/test
mc: <ERROR> Unable to stat `play/test`. Bucket `test` does not exist.
$ mc mb play/test
Bucket created successfully `play/test`.
$ mc cp /etc/issue play/test/prefix/prefix/test
/etc/issue:                          26 B / 26 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 414 B/s 0s
 $ mc ls -r play/test
[2020-03-06 10:44:53 PST]     26B prefix/prefix/test
```

As you can see it does work with play.

**Comment by hamednaim** [comment]
I don't think it's a permissions issue.
as i said  **minioClient.putObject(bucketName,"subfolder/file.txt",InputStream,contentType)**   is giving me ### Access denied message when trying to put an object in subfolders that **does not already exist.**
On the other hand **minioClient.putObject(bucketName, objectName, fileName)** is **working just fine**.

so the only solution that i found was like this:
**minioClient.putObject(bucketName, "subfolder/temporaryfile.txt", "temporaryfile.txt");**
 **minioClient.putObject(bucketName,"subfolder/file.txt",InputStream,contentType);**
**minioClient.removeObject(bucketName, "subfolder/temporaryfile.txt");**


1-put a temporary file with the wanted path.
2-put my real file(now the subfolders already exist)
3-remove the temporary file.

I don't believe this is the right approach but at least it works.

**Comment by harshavardhana** [comment]
@hamednaim can you add trace on to your original code - the workaround that you posted is wrong and not needed.

**Comment by hamednaim** [comment]
@harshavardhana i figured where is messed things up,

 i was passing the **fileName** parameter with backward slashes "\\" and it doesn't seem to accept that.
 so i just  had to replace them with the forward slashes "/".
minioClient.putObject(bucket **fileName**, targetStream, "application/octet-stream");

**surprisingly if the subfolders exist already, the fileName with the backward slash works just fine!**

thank you again for your replies.

**Comment by harshavardhana** [comment]
> thank you again for your replies.

Thanks closing.
