### ISSUE TITLE
Self-Assigned certs with Minio/Mint

### ISSUE THREAD

**Issue by downright-ux** [minio/minio#9108]
Adding CA and Intermediate to docker container gives the following error

unable to load certificate
140022074840728:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:701:Expecting: TRUSTED CERTIFICATE

## Expected Behavior
able to load CA's for self-assigned certs.

## Current Behavior
explained above 

## Steps to Reproduce (for bugs)
1. I've tried docker-compose with volumes to load certs via directory and run cmds to update the ca-certificates 
2. I used dockerfile and added the following. I see the certs are added but when starting docker I get the same error.
`
COPY CA.crt /usr/local/share/ca-certificates/
COPY Intermediate.crt CA.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates
`

**Comment by harshavardhana** [comment]
Thanks @downright-ux for opening the issue, we will get to this when we can.

**Comment by vadmeste** [comment]
> unable to load certificate
> 140022074840728:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:701:Expecting: TRUSTED CERTIFICATE

mint already accepts self signed certificates, no need to do anything about it. 

I suspect the certificate has a weird format.

What's the output of this command @downright-ux ?
```
openssl x509 -noout -text -in your-certificate.crt 
```

**Comment by downright-ux** [comment]
I don't really want to post that information in here sorry, but I can let you know before installing the CA and Intermediate certs curl gave me the following error. " SSL certificate problem: unable to get local issuer certificate". After installation of both certs I got the following.
`
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
`

The cmd I used was the following 
`curl -vvI https://<mywebsite-minio-proxy-aws>`

**Comment by vadmeste** [comment]
> I don't really want to post that information in here sorry,

Does the command show an error or it is informative ?

**Comment by downright-ux** [comment]
So we create new cert CA and wildcard certificate that seems to be working fine in browser and across some of our other application.
I've added the cert into the docker image, then try bringing up with docker-compose.
docker-compose.yml
`version: '3.3'
services:
    minio-tester:
        image: '<server>/docker/minio-mint:snapshot'
        privileged: true
        environment:
            - SERVER_ENDPOINT=<my-url-server>:443
            - ACCESS_KEY=xxxxxxxxxxxxxxxx
            - SECRET_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            - ENABLE_HTTPS=1`

here is the output 

`
| W: /usr/share/ca-certificates//usr/local/share/ca-certificates/CA.crt not found, but listed in /etc/ca-certificates.conf.
minio-tester_1  | (1/14) Running aws-sdk-go tests ... FAILED in 2 seconds
minio-tester_1  | {
minio-tester_1  |   "alert": "",
minio-tester_1  |   "args": {
minio-tester_1  |     "bucketName": "aws-sdk-go-test-3bvnub0zht1qns",
minio-tester_1  |     "expiry": 60000000000,
minio-tester_1  |     "objectName": "presignedTest"
minio-tester_1  |   },
minio-tester_1  |   "duration": 1713,
minio-tester_1  |   "error": "NoSuchBucket: The specified bucket does not exist\n\tstatus code: 404, request id: 15FBFC79FA6051AB, host id: ",
minio-tester_1  |   "function": "PresignedPut",
minio-tester_1  |   "message": "AWS SDK Go CreateBucket Failed",
minio-tester_1  |   "name": "aws-sdk-go",
minio-tester_1  |   "status": "FAIL"
minio-tester_1  | }
minio-tester_1  | 
`
