### ISSUE TITLE
Browser ui becomes slower and unresponsive when bucket storage is up to 416.00 GB

### ISSUE THREAD

**Issue by sh1yu** [minio/minio#9109]
as described in title, Browser ui becomes slower and unresponsive when bucket storage is up to 416.00 GB. Minio version is 2020-02-07T23:28:16Z. Other bucket is not affected.

## Expected Behavior

Browser ui should display the file in the bucket successfully.

## Current Behavior

 Browser ui becomes slower and unresponsive when bucket storage is up to 416.00 GB.

## Possible Solution
Some relevant issues cound be found in the old minio version. #8181 #2831. But the problem seems still exist in the latest version.

## Steps to Reproduce (for bugs)
1. set up a minio environment.
2. upload files to one bucket up to 416GB or more.
3. visit the bucket files via browser UI.

## Context

This problem brings some trouble for us using minio in production environment. We can't visit the uploaded files, and we can't judge whether the service is normal or not.

## Your Environment

* Version used (`minio version`):
2020-02-07T23:28:16Z

* Operating System and version (`uname -a`):
Host: es-17-13 | OS: linux | Arch: amd64
Version: go1.13.7 | CPUs: 4

**Comment by harshavardhana** [comment]
How is the file layout @psy-core ? Did you dump all your objects at bucket level or did you create a proper heirarchy?

**Comment by sh1yu** [comment]
@harshavardhana These files only be uploaded for test and just simply in a flat layout. 

how could I do to dump objects at bucket level?

**Comment by kannappanr** [comment]
@psy-core How many objects are you talking about here?

**Comment by sh1yu** [comment]
@kannappanr about 762385 objects. (command `mc ls` quite slowly.)

![image](https://user-images.githubusercontent.com/4922741/76300435-ab621f00-62f7-11ea-99ca-79c16e247733.png)

**Comment by harshavardhana** [comment]
That looks like you dump the objects without a heirarchy. MinIO uses filesystem heirarchy so if you dump objects at bucket level without a heirarchy it will become slow. 

This is not unusual it is expected, because this slows down filesystems themselves. It is not a good practice to dump all your objects without a heirarchy.

**Comment by harshavardhana** [comment]
So the issue is the way you are uploading objects, always upload with a different prefix with a proper heirarchy and honor filesystem limits.

**Comment by sh1yu** [comment]
@harshavardhana objects without heirarchy could cause browser UI unresponsive?

**Comment by klauspost** [comment]
@psy-core Yes. Arrange the files in folders for better performance.

**Comment by harshavardhana** [comment]
Closing this as a non-issue, just a workload thing from the client.
