### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by oscni** [minio/minio#9110]
minio dies with the error "fatal error: runtime: out of memory"

## Expected Behavior
To handle unlimited number of objects in the same bucket.
https://github.com/minio/minio/blob/master/docs/minio-limits.md

## Current Behavior
When bucket reaches around ~120k files in it minio eats all memory and then dies. Running pprof shows that readDirN is using all the memory.
Noticed that there was a difference in linux and windows version regarding readDirN so i tried to install minio on windows instead but then after some data had been added it settled on 14GB RAM usage and instead CPU hang on 100%.

## Steps to Reproduce (for bugs)
I can reproduce it by just starting everything and start copying data. Objectivefs splits up the data in several small files and when reaching around ~120k files it dies.

## Your Environment
80GB RAM
14x2TB SAS drives
ubuntu 18.04
minio version: RELEASE.2020-02-27T00-23-05Z

**Comment by harshavardhana** [comment]
@oscni 120k files is not nearly as close as the memory required here, are you sure that objectivefs is working correctly here returning correct pointers for readdir to work properly?

**Comment by oscni** [comment]
I'm guessing that it should work but of course I can't know for sure. Is there some some debugging commands that can be run in minio?

There was also some errors on the console, don't know if they have something to do with the problem, they looked like below. Now when I think about it, it's not something stupid with the object characters being used?
API: GetObject(bucket=test1, object=5VUNJZ0L3W01ui_1O~kN1DmR_dwQXhJKqiW4PH7Ujts3_iSEaR~mBNF6fBLinYM52K57Vl9kxWuD_ERvsxM~JPs5Td5WppGUzZOih1Mr/)
Time: 14:30:17 UTC 02/28/2020
DeploymentID: 1cc83abe-28c6-4e3d-98c9-40187205138d
RequestID: 15F7975C754E0C96
RemoteHost: X.X.X.X
Host: xyz:9000
Error: 'bytes=4294966976-18446744073709551295' does not have a valid last byte position value
       2: cmd/object-handlers.go:353:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()

**Comment by harshavardhana** [comment]
This byte comes down to 18446744073709551295 --> 16EiB (16 exabytes) - there is no such object this looks like a bug in objectivefs implementation. 

I suspect there is some interaction issue here, we have millions of deployments with some of them at the range of multiple petabytes worth of content so clearly 80GiB RAM is enough. I just ran MinIO on my /usr/share which has 500k contents and it doesn't even use more than 400MiB of my 8GiB laptop. 

So I don't think this issue is MinIO, we need to look at what objectivefs is trying to do here.

**Comment by klauspost** [comment]
Closing for now. This seems more of an issue with Objectivefs than MinIO.
