### ISSUE TITLE
permanent disk reads

### ISSUE THREAD

**Issue by yverbin** [minio/minio#9112]
Hello ! I have distributed minio installation on 3 nodes with 4 disks on each. One of my bucket contains  5000 subfolders and 15 million files. Аfter i run the mirror command minio starts read disk infinitely. Network exchange between nodes looks like 
```
video/mp2t.etag"c7cccbd5df419cd7cd96940aa6961a66-1......2.p..2.p..........{mybucket}..{mydir}/{myfile1}...........$........<....content-type
video/mp2t.etag"e335a29502fa5d72bae4c959e1b7f3ea-1.......<....<...........{mybucket}..{mydir}/{myfile2}...........&l.......t@...content-type
video/mp2t.etag"7b20d1c3c8010f78016b6d6e54be64c6-1.......t@...t@..........{mybucket}..{mydir}/{myfile3}...........%.B&......(...content-type
video/mp2t.etag"ac0b1e094d849a3c546ca6b540675436-1........(....(..........{mybucket}..{mydir}/{myfile4}...........2,u......s....content-type
```
Any commands like mc admin heal --force-stop does not take any effect. 

## Expected Behavior
any way to get background processes information and possibility to set priority for it
 
## Current Behavior
very slow write operations, unuseful cluster state.

## Your Environment
 Intel(R) Xeon(R) CPU E3-1271 v3 @ 3.60GHz/32Gb/4xHDD 10TB 

minio runs using docker:
docker run -d  --name minio \
  -e "MINIO_ACCESS_KEY=mykey" \
  -e "MINIO_SECRET_KEY=mysecret" \
  --network host \
  -v /DISKS/disk1:/disk1 \
  -v /DISKS/disk2:/disk2 \
  -v /DISKS/disk3:/disk3 \
  -v /DISKS/disk4:/disk4 \
  minio/minio:RELEASE.2020-03-09T18-26-53Z server http://{1...3}.mydomain/disk{1...4}

**Comment by yverbin** [comment]
[profiles.zip](https://github.com/minio/minio/files/4313136/profiles.zip)

pprof files in attachment

**Comment by klauspost** [comment]
This is likely the disk usage crawler. We are currently working on refactoring it here: https://github.com/minio/minio/pull/9075

I will double check the profile and close the issue if I can confirm that.

**Comment by klauspost** [comment]
Yes, all usage is from the usage crawler.
