### ISSUE TITLE
web-identity API example in STS/Keycloak docs is incorrect

### ISSUE THREAD

**Issue by gzur** [minio/minio#9114]
While trying to wrap my head around how to integrate my service with minio and keycloak, I came across the [Using WebIdentity API section of the STS/Keycloak documentation](https://github.com/minio/minio/blob/5ab9cc029d1de8105388e02538ac78e1891de2d9/docs/sts/keycloak.md#4-using-webidentiy-api)

That section directs you to a go program - [docs/sts/web-identity.go](https://github.com/minio/minio/blob/c9940d8c3f1f7a2b3e087abaecd7550a68b4fdb6/docs/sts/web-identity.go) which is supposed to print out credentials, but which instead prints out some buckets.

It appears that the [code snippet was updated](https://github.com/minio/minio/commit/64759189f589f2995b71b4ebd7df5be8c6d1105c#diff-9621d8ca0476c134a0717cab3f014017L168), possibly to match some other piece of documentation, while the Keycloak documentation languished.

This caused me some confusion until I had a look at the code myself.

## Expected Behavior
Running the `web-identity.go` program prints out my credentials

## Current Behavior
Running the `web-identity.go` program prints out a list of buckets

## Possible Solution
I see 3 options

1. Revert the code snippet so that it prints out the credentials as specified by the STS/Keycloak docs
2. Change the STS/Keycloak docs to match the code snippet
3. Implement a separate snippet (as seems to be de rigueur inside that directory) that fleshes out the use-case specified in the Keycloak documentation.

##### Contrast:
* [the documentation](https://github.com/minio/minio/blob/5ab9cc029d1de8105388e02538ac78e1891de2d9/docs/sts/keycloak.md#4-using-webidentiy-api):
> [...]
> upon successful login, STS credentials will be printed on the screen, for example
> 
> ```
> ##### Credentials
> {
> 	"accessKey": "6N2BALX7ELO827DXS3GK",
> 	"secretKey": "23JKqAD+um8ObHqzfIh+bfqwG9V8qs9tFY6MqeFR",
> 	"expiration": "2019-10-01T07:22:34Z",
> 	"sessionToken": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiI2TjJCQUxYN0VMTzgyN0RYUzNHSyIsImFjciI6IjAiLCJhdWQiOiJhY2NvdW50IiwiYXV0aF90aW1lIjoxNTY5OTEwNTUyLCJhenAiOiJhY2NvdW50IiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJleHAiOjE1Njk5MTQ1NTQsImlhdCI6MTU2OTkxMDk1NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2F1dGgvcmVhbG1zL2RlbW8iLCJqdGkiOiJkOTk4YTBlZS01NDk2LTQ4OWYtYWJlMi00ZWE5MjJiZDlhYWYiLCJuYmYiOjAsInBvbGljeSI6InJlYWR3cml0ZSIsInByZWZlcnJlZF91c2VybmFtZSI6Im5ld3VzZXIxIiwic2Vzc2lvbl9zdGF0ZSI6IjJiYTAyYTI2LWE5MTUtNDUxNC04M2M1LWE0YjgwYjc4ZTgxNyIsInN1YiI6IjY4ZmMzODVhLTA5MjItNGQyMS04N2U5LTZkZTdhYjA3Njc2NSIsInR5cCI6IklEIn0._UG_-ZHgwdRnsp0gFdwChb7VlbPs-Gr_RNUz9EV7TggCD59qjCFAKjNrVHfOSVkKvYEMe0PvwfRKjnJl3A_mBA"
> }
> ```
> [...]

##### with
* [the code](https://github.com/minio/minio/blob/c9940d8c3f1f7a2b3e087abaecd7550a68b4fdb6/docs/sts/web-identity.go#L221):
```
		for _, bucket := range buckets {
			log.Println(bucket)
		}
```
vs.

```
			w.Write([]byte("##### Credentials\n"))
			c, err := json.MarshalIndent(a.Result.Credentials, "", "\t")
[...]
			w.Write(c)
```
## Context
I have an existing microservices platform that uses Keycloak/JWT's - and I am investigating whether to integrate minio as a storage backend for a RESTful service that is in charge of managing a "project" schema that resides on NFS. To that end, I am checking whether `minio` can act as a general-purpose File/CRUD API on top of the NFS with IAM being handled exclusively by Keycloak.

## Regression
Not a regression per se, but it was introduced by https://github.com/minio/minio/pull/8501

## Your Environment

* Version used (`minio version`):  I'm running off `origin/master` `5ab9cc02`.
* Operating System and version (`uname -a`): `Darwin NC-MBP-0288.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64`

**Comment by harshavardhana** [comment]
@gzur feel free to send a fix

**Comment by gzur** [comment]
Which of the 3 solutions do you think makes most sense?

**Comment by harshavardhana** [comment]
> Which of the 3 solutions do you think makes most sense?

Change the code to print the Credentials as well as `log` the buckets, to check if the credentials worked with the relevant permissions.  Thanks @gzur
