### ISSUE TITLE
[minikube]ERROR Unable to initialize backend: The disk size is less than the minimum threshold

### ISSUE THREAD

**Issue by NanXuejiao** [minio/minio#9118]
## Expected Behavior
Deploy minio in minikube.

## Current Behavior
It works several times,  but occurs  `ERROR Unable to initialize backend: The disk size is less than the minimum threshold`after redeploy minio.

**Comment by harshavardhana** [comment]
Please use the issue template to clearly describe your issue, please re-open a new issue with all the details.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project (if any):
