### ISSUE TITLE
[minikube]ERROR Unable to initialize backend: The disk size is less than the minimum threshold 

### ISSUE THREAD

**Issue by NanXuejiao** [minio/minio#9119]
## Expected Behavior
Deploy minio in minikube.

## Current Behavior
It works several times,  but occurs  `ERROR Unable to initialize backend: The disk size is less than the minimum threshold`after redeploy minio.

## Steps to Reproduce (for bugs)

For me, this error occurs when exec `kubectl apply -f minio.yaml`.

## Context

[minio-yaml.zip](https://github.com/minio/minio/files/4317838/minio-yaml.zip)

## Regression

I don't know
## Your Environment

* Version used (`minio version`):
```
minio version RELEASE.2020-03-05T01-04-19Z
```
* Environment name and version (e.g. nginx 1.9.1):
```
minikube v1.2.0
kubernetes v1.14.0
```
* Server type and version:

* Operating System and version (`uname -a`):
```
Darwin Kernel Version 18.2.0
```
* Link to your project:
It's private project.

**Comment by nitisht** [comment]
MinIO expects atleast 1GiB of capacity on the drives before starting, please ensure you have a PV of this capacity before starting MinIO.

**Comment by nitisht** [comment]
Closing this as answered and this is working as expected. For more Q/A style interaction, please join us on Slack
