### ISSUE TITLE
Minio Distributed: Restore files from SnapShots on k8s

### ISSUE THREAD

**Issue by lukpre** [minio/minio#9126]
Hey

We run MinIO in both distributed and single mode on k8s, where PV's are managed through NetApp Trident. The available storageClasses allow to create snapshots within the PV which works great for file/object restores in single mode. Unfortunately restores from snapshots in distributed mode can't be achieved the same way. If i restore a file from a SnapShot on the pv of one node, it gets instantly deleted. This must have to do something with the way storage is handled by minio when running in distributed mode. 

## Expected Behavior
* Having a way to copy the folder or file back to one of the PV's and use mc heal to make the lost object or buket available again 
* On Single Node a simple: `cp .snapshots/snapshotdaily_1900.2019-08-17_1900/testbucket/test.txt ./testbucket/test.txt` works to make the file is available again. 
* A way to restore accidentally deleted objects or buckets directly on the pv. 

## Current Behavior
* Copied File instantly get's deleted on the node where it is restored therefore no healing can be performed. 

## Steps to Reproduce (for bugs)
1. Run minio distributed on k8s with a storageClass that provides snapshots
2. Delete an Object / Bucket
3. Copy the deleted Object from the snapshot / backup dir back to its original place
4. Object disappears after a short time on the node where it was restored

## Context
We are working on a backup concept for Minio Distributed and wanted to find a way to restore a file when accidentally deleted by endusers. Current alternatives would be to mirror the whole Minio Storage to another Storage Backend, which we would like to avoid (if possible). Couldn't find any documentation how this could be done with minio distributed.

## Environment
* Minio Version: 2019-11-28T07:47:11Z 
* Environment: kubernetes 1.10

many thanks

**Comment by nitisht** [comment]
> Copy the deleted Object from the snapshot / backup dir back to its original place

To make this work, you need to restore at least quorum number of snapshots in a distributed mode. Please join us on Slack we can discuss further, I don't think there is any change needed to be done on MinIO server to handle this.

**Comment by lukpre** [comment]
Thank you very much for your fast response! Just didn't find or rather know that fact about the quorum number of snapshots. Worked like charm doing the snapshot restore on 2 nodes on a 4 node cluster! I will close this.
