### ISSUE TITLE
Provide lock metrics in prometheus

### ISSUE THREAD

**Issue by wazzy83** [minio/minio#9133]
Currently lock metrics is available in mc admin top locks command when minio in distributed mode.
A customer requested lock metrics to be provided in the prometheus endpoint as well as it gets monitored.

**Comment by harshavardhana** [comment]
Lock metrics is not that useful, can you provide a proper proposal on what is needed? This issue lacks clarity.

**Comment by wazzy83** [comment]
Recently we had a problem with locks, that were holding a part of the bucket.
It was caused by improper VM reboot with minio volume attached.
However, liveness probes were fine and minio_disks_offline count eq 0
We only found cluster outage when monitoring system compared minio backup size.
Then we saw "mc admin top locks" and rebooted this node once again.
"mc admin heal" didn't help

output was like

`1 ❯ mc admin top locks rabota
Time                  Type    Owner                 Resource
1149 hours            Write                         .minio.sys/leader-data-usage-info
1148 hours            Write                         .minio.sys/leader
544 hours             Read                          .minio.sys/config/iam/policies/rocketchat/policy.json
544 hours             Read                          .minio.sys/config/iam/users/terraform/identity.json
544 hours             Write                         system/lock-maintenance-ops
544 hours             Read                          sbs-prod/jsons/32/service-catalog.json
544 hours             Read                          sbs/jsons/32/service-catalog.json
544 hours             Read                          sbs/jsons/32/service-catalog.json
544 hours             Read                          sbs/jsons/32/service-catalog.json
544 hours             Read                          .minio.sys/config/iam/users/sbs-backend/identity.json`

`❯ mc admin heal -r rabota
 ◓  sbs
    2/60,003 objects; 33 GiB in 1h7m25s
    ┌────────┬────────┬─────────────────────┐
    │ Green  │ 60,012 │ 100.0% ████████████ │
    │ Yellow │      0 │   0.0%              │
    │ Red    │      0 │   0.0%              │
    │ Grey   │      0 │   0.0%              │
    └────────┴────────┴─────────────────────┘
`

So, no we have monitoring somewhat like 
url -H'X-Amz-Date: 20200313T092420Z' -H'  a lot of headers' https://domain.com/minio/admin/v2/top/locks | jq length

That's rather uncomfortable.
Thanks.

**Comment by harshavardhana** [comment]
First I think the issue of holding locks shouldn't happen, even if it happens it needs to be fixed regardless of lock metrics.

Now from a metrics point of view, not sure what makes sense? Because as you trying to look for latency? Or active locks?

**Comment by wazzy83** [comment]
I believe, we are doing fine with monitoring -> alerting -> bug-fixing chain.
Latency is under control with s3_ttfb_seconds_* group.
I just want to see lock count for active locks monitoring.
