### ISSUE TITLE
cannot dynamic modification endpoint in ：minio gateway s3

### ISSUE THREAD

**Issue by tianxiaer1995** [minio/minio#9134]
i am in china dev,now i want to excute: minio gateway s3,connect aws s3 service,i will used endpoint https://s3.cn-northwest-1.amazonaws.com,but this commond cannot dynamic modification endpoint， so aws return me : The AWS Access Key Id you provided does not exist in our records.
## Expected Behavior
minio gateway s3 Support dynamic endpoint setting,

## Steps to Reproduce (for bugs)
1. my aws s3 in china,region is cn-northwest-1
2. excute minio gateway s3, return error message:The AWS Access Key Id you provided does not exist in our records.
3. because Minio just looked for the key under the default https://s3.amazonaws.com

## Your Environment
release

**Comment by tianxiaer1995** [comment]
when i add  urlStr = "https://s3.cn-northwest-1.amazonaws.com" in /minio/cmd/gateway/s3/gateway-s3.go line :163 .I solved the problem
code eg:
// newS3 - Initializes a new client by auto probing S3 server signature.
func newS3(urlStr string) (*miniogo.Core, error) {
	urlStr = "https://s3.cn-northwest-1.amazonaws.com"
	if urlStr == "" {
		urlStr = "https://s3.amazonaws.com"
	}

**Comment by poornas** [comment]
You should pass the address to  s3 gateway like this 
`minio gateway s3 https://s3.cn-northwest-1.amazonaws.com.cn` 

your endpoint is missing [.cn](https://docs.amazonaws.cn/en_us/aws/latest/userguide/endpoints-Ningxia.html)

**Comment by tianxiaer1995** [comment]
> You should pass the address to s3 gateway like this
> `minio gateway s3 https://s3.cn-northwest-1.amazonaws.com.cn`
> 
> your endpoint is missing [.cn](https://docs.amazonaws.cn/en_us/aws/latest/userguide/endpoints-Ningxia.html)

Thank you very much. Perfect solution
