### ISSUE TITLE
Problem with PDF page layout

### ISSUE THREAD

**Issue by geraldinesortmybooks** [minio/minio#9135]
when an Invoice is saved as PDF, it is out of alignment on the page
Left margin is 1.5 inches and Right margin is 2.5 inches

Please see screen shot
![image](https://user-images.githubusercontent.com/19873130/76617381-142ae080-651e-11ea-935e-7ab98ab1ada3.png)

**Comment by harshavardhana** [comment]
Not sure if this related to MinIO, you haven't mentioned anything related to MinIO in the issue report.

Closing this issue.
