### ISSUE TITLE
Wrong version on homebrew stable minio.rb

### ISSUE THREAD

**Issue by ghost** [minio/minio#9136]
## Expected Behavior
`brew install minio/stable/minio` should install minio.

## Current Behavior
Got a 404 error, see following output:
```
==> Installing minio from minio/stable
==> Downloading https://dl.minio.io/server/minio/release/darwin-amd64/minio.RELEASE.2020-03-09T18-26-53Z
#=#=-#  #                                                                     
curl: (22) The requested URL returned error: 404 
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "minio"
Download failed: https://dl.minio.io/server/minio/release/darwin-amd64/minio.RELEASE.2020-03-09T18-26-53Z
```

## Possible Solution
update `minio.rb` on https://github.com/minio/homebrew-stable/blob/478408f31c160d47767822584d2a0632e63e9f3f/minio.rb
with correct version `RELEASE.2020-03-14T02-21-58Z`

**Comment by harshavardhana** [comment]
Will fix it, we were about to fix it.
