### ISSUE TITLE
reopen minio/minfs

### ISSUE THREAD

**Issue by chrisbecke** [minio/minio#9137]
**Is your feature request related to a problem? Please describe.**
The "better supported" project that was referenced as the rationale for archiving the minfs project down has been abandoned:
https://github.com/rexray/rexray/issues/1338 

**Describe the solution you'd like**
'minio/minfs' to be available as a docker volume plugin again.

**Describe alternatives you've considered**
I would gladly take any docker volume plugin that create volumes conforming to minio's bucket naming restrictions and can mount s3fs volumes.

**Additional context**
Docker Swarm is pretty dead and there are many better options out there. But for legacy projects involving Docker Swarm, using Minio to serve s3fs volumes is convenient and compelling use case.

**Comment by harshavardhana** [comment]
We have other high priority projects which require all our time. So we won't be able to bring it back, maintain it and fix issues that you may encounter. 

Shall close this issue for now.
