### ISSUE TITLE
Unsupported action AssumeRole

### ISSUE THREAD

**Issue by OwO1** [minio/minio#9141]
I use docker to deploy 
```
docker run -p 9000:9000 --name minio1 \
  -e "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE" \
  -e "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" \
  -v /mnt/data:/data \
  minio/minio server /data
```

after this i plan to send request to get token.
```
import requests
data = {
    'DurationSeconds':'3600',
    'Version':'2011-06-15',
    'Policy':{"Version":"2012-10-17","Statement":[{"Sid":"Stmt1","Effect":"Allow","Action":"s3:*","Resource":"arn:aws:s3:::*"}]},
    'AUTHPARAMS':"",
    'Action':'AssumeRole',
}
r = requests.post('...', data = data)
r.text
```
my response is 
```
<?xml version="1.0" encoding="UTF-8"?>\n<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"><Error><Type></Type><Code>InvalidParameterValue</Code><Message>Unsupported action AssumeRole</Message></Error><RequestId>15FCB72E0F925B84</RequestId></ErrorResponse>
```
the docker info was 
```
API: AssumeRoleJWTCommon()
Time: 08:01:33 UTC 03/16/2020
DeploymentID: 57fad6ba-4909-4ddb-a07b-01e79df4e17d
RequestID: 15FCBA039A1F2683
RemoteHost: ...
Host: ...
UserAgent: python-requests/2.18.4
Error: Unsupported action AssumeRole
       3: cmd/sts-errors.go:47:cmd.writeSTSErrorResponse()
       2: cmd/sts-handlers.go:278:cmd.(*stsAPIHandlers).AssumeRoleWithJWT()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```
 what i was missing here?

**Comment by muktiarip** [comment]
Based on AWS STS API documentation, the call to `STS API assume role` uses HTTP GET method. Your Python code calls this API using HTTP POST method.

**Comment by OwO1** [comment]
according to this page.i use POST method.
https://github.com/minio/minio/blob/master/docs/sts/assume-role.md 

when i switch to GET method.
```
import requests
data = {
    'DurationSeconds':'3600',
    'Version':'2011-06-15',
    'Policy':{"Version":"2012-10-17","Statement":[{"Sid":"Stmt1","Effect":"Allow","Action":"s3:*","Resource":"arn:aws:s3:::*"}]},
    'AUTHPARAMS':"",
    'Action':'AssumeRole',    
}
r = requests.get('...', params = data)
print(r.text)
```
become 
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied.</Message>
<Resource>/</Resource>
<RequestId>15FCC138B41C9E64</RequestId>
<HostId>d971501e-799f-43ed-8495-2e617ce961ed</HostId>
</Error>
```

i didnt use aws .should this only work on aws?

**Comment by muktiarip** [comment]
Do you sign your API call with Minio credentials?

IMO, it is easier if you use minio SDK or AWS SDK (boto3) instead of Python requests module, since it requires you to manualy sign your API request.

Here is client code using boto3 to get temporary credentials from minio server.

```python
import json
import boto3

def getTempCredentials():
    stsClient = boto3.client(
        'sts',
        region_name='us-east-1',
        endpoint_url='http://localhost:9000',
        aws_access_key_id=YOUR_MINIO_ACCESS_KEY_ID,
        aws_secret_access_key=YOUR_MINIO_SECRET_ACCESS_KEY
    )
    policy = {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "GetObj",
                "Effect": "Allow",
                "Action": ["s3:GetObject"],
                "Resource": f"arn:aws:s3:::mybucket/*"
            },
            {
                "Sid": "PutDelObj",
                "Effect": "Allow",
                "Action": ["s3:PutObject", "s3:DeleteObject"],
                "Resource": f"arn:aws:s3:::anotherbucket/uploads/*"
            }
        ]
    }
    response = stsClient.assume_role(
        RoleArn='arn:xxx:xxx:xxx:xxxx',
        RoleSessionName='whatever',
        Policy=json.dumps(policy, separators=(',',':')),
        DurationSeconds=3600
    )
    return response
```

**Comment by muktiarip** [comment]
> 
> i didnt use aws .should this only work on aws?

No. I use minio as storage server. For client, I use both minio SDK and AWS SDK.

**Comment by OwO1** [comment]
> > i didnt use aws .should this only work on aws?
> 
> No. I use minio as storage server. For client, I use both minio SDK and AWS SDK.

i mean dont have aws server. if is ok to use normal ubuntu server deploy minio and use AWS SDK

**Comment by OwO1** [comment]
when i use the code upper(boto3).
```
Traceback (most recent call last):
  File "1.py", line 39, in <module>
    getTempCredentials()
  File "1.py", line 35, in getTempCredentials
    Policy=json.dumps(policy, separators=(',',':')),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InternalError) when calling the AssumeRole operation (reached max retries: 4): We encountered an internal error generating credentials, please try again.
```

**Comment by muktiarip** [comment]
Based on error message

`botocore.exceptions.ClientError: An error occurred (InternalError) when calling the AssumeRole operation (reached max retries: 4): We encountered an internal error generating credentials, please try again.`

it could be:

* your python script couldn't connect to minio server
* your minio server isn't properly configured
* your `policy` statement's resource contains invalid ARN (non-existent bucket and/or prefix)

**Comment by harshavardhana** [comment]
@OwO1 when running these scripts just run `mc admin trace -v myminio` to your MinIO server and also the error for "InternalError" will be logged on the container console.

**Comment by OwO1** [comment]
i want use MinIO STS AssumeRole API.so i go [here](<https://github.com/minio/minio/blob/master/docs/sts/assume-role.md>).

First i run minio by this
```
docker run -p 9000:9000 -d --name minio1 \
  -e "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE" \
  -e "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" \
  -v /mnt/data:/data \
  minio/minio server /data
```



for the testing part .i try to use aws-cli

```
apt install awscli
```

after this

```
aws configure
# AWS Access Key ID [None]: AKIAIOSFODNN7EXAMPLE
# AWS Secret Access Key [None]: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
# Default region name [None]: us-east-1
# Default output format [None]:
aws configure set default.s3.signature_version s3v4

```

then i go

```
aws --endpoint-url http://localhost:9000 sts assume-role --policy '{"Version":"2012-10-17","Statement":[{"Sid":"Stmt1","Effect":"Allow","Action":"s3:*","Resource":"arn:aws:s3:::*"}]}' --role-arn arn:xxx:xxx:xxx:xxxx --role-session-name anything
```

i try to use localhost and my public ip address is return the same 



An error occurred (AccessDenied) when calling the AssumeRole operation: Generating temporary credentials **not allowed** for this request.



by the way,when i run below,it work fine

```
aws --endpoint-url https://localhost:9000 s3 ls
# 2020-03-17 15:20:23 123
```



i think the main problem why AccessDenied and not allowed.

**Comment by OwO1** [comment]
it seems to me. i must use mc to create a new user and use this new user's Access Key  and Secret Access it will return me the response.
thanks a lot

**Comment by yuyuanshifu** [comment]
> it seems to me. i must use mc to create a new user and use this new user's Access Key and Secret Access it will return me the response.
> thanks a lot

Hi, I have got the SecretAccessKey、SessionToken、AccessKeyId by with boto3 sdk, then I posted a request to minio such as:http://xxxx:xxxx?Action=AssumeRoleWithClientGrants&DurationSeconds=3600&Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiI5SFFUUzVGMzIyMFMwTzZHN0cwRiIsImV4cCI6MzYwMDAwMDAwMDAwMDAsInBvbGljeSI6IiIsInNlc3Npb25Qb2xpY3kiOiJleUpXWlhKemFXOXVJam9pTWpBeE1pMHhNQzB4TnlJc0lsTjBZWFJsYldWdWRDSTZXM3NpUVdOMGFXOXVJanBiSW5Nek9rZGxkRTlpYW1WamRDSXNJbk16T2tkbGRFSjFZMnRsZEV4dlkyRjBhVzl1SWl3aWN6TTZVSFYwVDJKcVpXTjBJaXdpY3pNNlJHVnNaWFJsVDJKcVpXTjBJaXdpY3pNNlEzSmxZWFJsUW5WamEyVjBJaXdpY3pNNlRHbHpkRUoxWTJ0bGRDSXNJbk16T2tSbGJHVjBaVUoxWTJ0bGRDSmRMQ0pTWlhOdmRYSmpaU0k2SW1GeWJqcGhkM002Y3pNNk9qb3FMeW9pTENKRlptWmxZM1FpT2lKQmJHeHZkeUlzSWxOcFpDSTZJa2RsZEU5aWFpSjlYWDA9In0.bsKDxlSspYUVOnkc0yj58TevhYBZzrITfyU2rIoC5eSGaerC53oOd9VqFrdK-7nhoZStt6yGuwa8V0vaLKxflg&Version=2011-06-15.
But the minio respone:InvalidParameterValue, provider jwt doesn't exist.
Then I setted a jwt in the request header, but the error was still.
How should I solved it?

**Comment by harshavardhana** [comment]
> Hi, I have got the SecretAccessKey、SessionToken、AccessKeyId by with boto3 sdk, then I posted a request to minio such as:http://xxxx:xxxx?Action=AssumeRoleWithClientGrants&DurationSeconds=3600&Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiI5SFFUUzVGMzIyMFMwTzZHN0cwRiIsImV4cCI6MzYwMDAwMDAwMDAwMDAsInBvbGljeSI6IiIsInNlc3Npb25Qb2xpY3kiOiJleUpXWlhKemFXOXVJam9pTWpBeE1pMHhNQzB4TnlJc0lsTjBZWFJsYldWdWRDSTZXM3NpUVdOMGFXOXVJanBiSW5Nek9rZGxkRTlpYW1WamRDSXNJbk16T2tkbGRFSjFZMnRsZEV4dlkyRjBhVzl1SWl3aWN6TTZVSFYwVDJKcVpXTjBJaXdpY3pNNlJHVnNaWFJsVDJKcVpXTjBJaXdpY3pNNlEzSmxZWFJsUW5WamEyVjBJaXdpY3pNNlRHbHpkRUoxWTJ0bGRDSXNJbk16T2tSbGJHVjBaVUoxWTJ0bGRDSmRMQ0pTWlhOdmRYSmpaU0k2SW1GeWJqcGhkM002Y3pNNk9qb3FMeW9pTENKRlptWmxZM1FpT2lKQmJHeHZkeUlzSWxOcFpDSTZJa2RsZEU5aWFpSjlYWDA9In0.bsKDxlSspYUVOnkc0yj58TevhYBZzrITfyU2rIoC5eSGaerC53oOd9VqFrdK-7nhoZStt6yGuwa8V0vaLKxflg&Version=2011-06-15.
> But the minio respone:InvalidParameterValue, provider jwt doesn't exist.
> Then I setted a jwt in the request header, but the error was still.
> How should I solved it?

You have to present the JWT from your IDP not from boto3 follow the documentation properly - use the following sample code to understand how to use boto3 to use AssumeRoleWithClientGrants API https://github.com/harshavardhana/clientgrantsprovider

**Comment by yuyuanshifu** [comment]
> > Hi, I have got the SecretAccessKey、SessionToken、AccessKeyId by with boto3 sdk, then I posted a request to minio such as:http://xxxx:xxxx?Action=AssumeRoleWithClientGrants&DurationSeconds=3600&Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiI5SFFUUzVGMzIyMFMwTzZHN0cwRiIsImV4cCI6MzYwMDAwMDAwMDAwMDAsInBvbGljeSI6IiIsInNlc3Npb25Qb2xpY3kiOiJleUpXWlhKemFXOXVJam9pTWpBeE1pMHhNQzB4TnlJc0lsTjBZWFJsYldWdWRDSTZXM3NpUVdOMGFXOXVJanBiSW5Nek9rZGxkRTlpYW1WamRDSXNJbk16T2tkbGRFSjFZMnRsZEV4dlkyRjBhVzl1SWl3aWN6TTZVSFYwVDJKcVpXTjBJaXdpY3pNNlJHVnNaWFJsVDJKcVpXTjBJaXdpY3pNNlEzSmxZWFJsUW5WamEyVjBJaXdpY3pNNlRHbHpkRUoxWTJ0bGRDSXNJbk16T2tSbGJHVjBaVUoxWTJ0bGRDSmRMQ0pTWlhOdmRYSmpaU0k2SW1GeWJqcGhkM002Y3pNNk9qb3FMeW9pTENKRlptWmxZM1FpT2lKQmJHeHZkeUlzSWxOcFpDSTZJa2RsZEU5aWFpSjlYWDA9In0.bsKDxlSspYUVOnkc0yj58TevhYBZzrITfyU2rIoC5eSGaerC53oOd9VqFrdK-7nhoZStt6yGuwa8V0vaLKxflg&Version=2011-06-15.
> > But the minio respone:InvalidParameterValue, provider jwt doesn't exist.
> > Then I setted a jwt in the request header, but the error was still.
> > How should I solved it?
> 
> You have to present the JWT from your IDP not from boto3 follow the documentation properly - use the following sample code to understand how to use boto3 to use AssumeRoleWithClientGrants API https://github.com/harshavardhana/clientgrantsprovider

Thanks.
I follwed the code by https://github.com/minio/minio/blob/master/docs/sts/client-grants.go.
But I replaced the getTokenExpiry with boto to get the token.
Do I have to get the token from idp?

**Comment by bai597030001** [comment]
> according to this page.i use POST method.
> https://github.com/minio/minio/blob/master/docs/sts/assume-role.md
> 
> when i switch to GET method.
> 
> ```
> import requests
> data = {
>     'DurationSeconds':'3600',
>     'Version':'2011-06-15',
>     'Policy':{"Version":"2012-10-17","Statement":[{"Sid":"Stmt1","Effect":"Allow","Action":"s3:*","Resource":"arn:aws:s3:::*"}]},
>     'AUTHPARAMS':"",
>     'Action':'AssumeRole',    
> }
> r = requests.get('...', params = data)
> print(r.text)
> ```
> 
> become
> 
> ```
> <Error>
> <Code>AccessDenied</Code>
> <Message>Access Denied.</Message>
> <Resource>/</Resource>
> <RequestId>15FCC138B41C9E64</RequestId>
> <HostId>d971501e-799f-43ed-8495-2e617ce961ed</HostId>
> </Error>
> ```
> 
> i didnt use aws .should this only work on aws?

Hi, I got the same error as you did, How did you solve it
