### ISSUE TITLE
"The filename, directory name, or volume label syntax is incorrect" on Windows

### ISSUE THREAD

**Issue by pitrou** [minio/minio#9144]
We're seeing this weird error message in our Windows CI logs:
https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/31494125/job/basa0ctripws44i3#L2047

```
Error: open C:\Users\appveyor\AppData\Local\Temp\1\s3fs-test-6p2icn8x/s3fs-test-bucket/AB/def/: The filename, directory name, or volume label syntax is incorrect.
       3: cmd\fs-v1.go:1065:cmd.(*FSObjects).listDirFactory.func1()
       2: cmd\tree-walk.go:78:cmd.doTreeWalk()
       1: cmd\tree-walk.go:176:cmd.startTreeWalk.func1()
```

The error message seems to correspond to `ERROR_INVALID_NAME`. I don't understand how that can happen: perhaps the file does not exist, but the file path looks syntactically correct.

I can reproduce locally with version 2019-09-11T19:53:16Z.

**Comment by harshavardhana** [comment]
That is because of Windows doesn't return correct errors messages for non-existent objects, you can ignore it as it won't affect anything on the client side.

**Comment by pitrou** [comment]
Oh, I see. Out of curiosity, what is the Windows API function that returns such error codes?

**Comment by harshavardhana** [comment]
It is simple os.Open but underneath its a win32 API to read the file

**Comment by pitrou** [comment]
I see. Weird, I've never witnessed that before.
