### ISSUE TITLE
有没有flutter的sdk？

### ISSUE THREAD

**Issue by simanlx** [minio/minio#9146]
有没有flutter的sdk？

**Comment by klauspost** [comment]
Nothing official it seems. Maybe this can help you: https://stackoverflow.com/questions/49618844/flutter-dart-and-aws-sdk

**Comment by simanlx** [comment]
这个只支持 amazonaws.com

**Comment by xtyxtyx** [comment]
I just created a package for dart, maybe this can help you
https://pub.dev/packages/minio
