### ISSUE TITLE
GetLifecycleConfiguration returns invalid response

### ISSUE THREAD

**Issue by WolfspiritM** [minio/minio#9147]
I've used the aws .NET SDK to create and list a bucket lifecycle. The creation works fine but once I try to get the Policy it returns an error:

```AmazonUnmarshallingException: Error unmarshalling response back from AWS. The Filter element must contain at most one 'Prefix', 'Tag', or 'And' predicate.```

It seems like Minio creates some empty tags and the SDK doesn't like that. The filter I've set was:
```
<LifecycleConfiguration>
    <Rule>
        <Expiration>
            <Days>1</Days>
        </Expiration>
        <ID>Cleanup</ID>
        <Filter>
            <Prefix>data/</Prefix>
        </Filter>
        <Status>Enabled</Status>
    </Rule>
</LifecycleConfiguration>
```

The response from minio is:
```
<LifecycleConfiguration>
    <Rule>
        <ID>Cleanup</ID>
        <Status>Enabled</Status>
        <Filter>
            <Prefix>data-in/</Prefix>
            <And></And>
            <Tag></Tag>
        </Filter>
        <Expiration>
            <Days>1</Days>
        </Expiration>
    </Rule>
</LifecycleConfiguration>
```

It does work with an older version of minio. Tested with: 2019-10-12T01:39:57Z

## Expected Behavior
GetLifecycleConfiguration doesn't throw an exception with S3 sdk

## Current Behavior
GetLifecycleConfiguration does throw an exception with S3 sdk

## Possible Solution
Remove the empty tags from the XML response

## Steps to Reproduce (for bugs)

1. Create a lifecycle policy like mentioned above
2. Query that lifecycle policy with the .NET AWS S3 API

## Context

I tried to list currently active Lifecycle Policies and it fails.

## Regression
No

## Your Environment

* Version used (`minio version`): 2020-03-14T02:21:58Z
* Environment name and version (e.g. nginx 1.9.1): docker
* Server type and version: docker for win
* Operating System and version (`uname -a`): Windows (docker)

**Comment by vadmeste** [comment]
@WolfspiritM yes I confirm the latest version has this issue. We will get it fixed quickly.

**Comment by vadmeste** [comment]
We need a custom json marsheler here

**Comment by harshavardhana** [comment]
> We need a custom json unmarsheler here

You mean XML @vadmeste

**Comment by vadmeste** [comment]
> You mean XML @vadmeste

oups yes, right.

Taking this

**Comment by vadmeste** [comment]
Fixed by https://github.com/minio/minio/pull/9201
