### ISSUE TITLE
[resolved] Deploy Minio on Kubernetes fails

### ISSUE THREAD

**Issue by gioargyr** [minio/minio#9153]
I am following your guide about deploying Minio in a Kubernetes installation, but it doesn't get me anywhere. I have a Kubernetes installed in 4 nodes and OpenFaaS above it. I want to use Minio for my functions that run on OpenFaaS.
I am following your instructions and I create a headless-service, a statefulset and a service, but after that it's blurry on what to do.
Am I supposed to update the statefulset right now, or it is an instruction for the future?
Am I supposed to do the resource cleanup before deploying it to the cluster nodes?
Am I supposed to run the deamonset?
Do I need to modify the yaml for the deamonset first?

What I did was to skip updating the statefulset and the resource cleanup because it didn't make sense to me and I modified the deamonset yaml according to my cluster before creating it.  Also, I labeled the nodes as you say. I ended up with 3 running minio pods (in nodes 1, 2 and 3 even though I have 4 nodes. node4 has no minio) and right now I see nothing.

Am I missing any prerequisite?

## Expected Behavior

Deploy Minio on Kubernetes

## Current Behavior

I checked all the IP of my 4 nodes and I get nothing in port 9000 and nothing on any other port. Also, it's not clear where to get the MINIO_ACCESS_KEY and MINIO_SECRET from.

## Possible Solution

There are instructions or prerequisites that I am missing.

## Steps to Reproduce (for bugs)

1. Just follow your instructions. The prerequisites in the beginning are pointing to the standalone. I am aiming to distributed, so I didn't follow these prerequisites.

## Context

I couldn't deploy Minio.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by nitisht** [comment]
> I am following your instructions and I create a headless-service, a statefulset and a service, but after that it's blurry on what to do.

Can you try `kubectl get pods` after StatefulSet is deployed? Also please join us on Slack for more interactive q/a type scenarios.

**Comment by gioargyr** [comment]
Hello, I will answer to your question and I will also update with some new info.
Right now I kubectl create the headless-service and the statefulset and the only thing I changed is the last line of the statefulset to "1Gi" instead of "10Gi".
What I get when I kubectl get pods is:
"
minio-0   0/1     Pending   0          12s
minio-1   0/1     Pending   0          12s
minio-2   0/1     Pending   0          12s
minio-3   0/1     Pending   0          12s
"
And when I kubectl describe pod one of the pods I get the same return:
"Warning  FailedScheduling  <unknown>  default-scheduler  error while running "VolumeBinding" filter plugin for pod "minio-0": pod has unbound immediate PersistentVolumeClaims"

I searched about this a little, I had no clue that persistentVolumes and PersistentVolumeClaims exist, so I created a persistent volume following this  https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes, which is available, has capacity of 2Gi. Of course, I created the persistent volume before running the headless-service and statefulset.
However, my persistent volume is not being claimed by anyone and the minio pods keep pending.

Am I supposed to create persistent volumes before running the statefulset? If yes, how many?
Also, am I supposed to run the deamonset?
Last but not least, how should I modify all these files in order to run minio in my Kubernetes installation?

By the way, I joined slack (gioargyr [at] gmail [dot] com) and I joined the github channel.

**Comment by harshavardhana** [comment]
> And when I kubectl describe pod one of the pods I get the same return:
> "Warning FailedScheduling default-scheduler error while running "VolumeBinding" filter plugin for pod "minio-0": pod has unbound immediate PersistentVolumeClaims"

This looks like PVC/PV creation issue, outside of MinIO's problem we shall go ahead and close this issue.

**Comment by bretagne-peiqi** [comment]
@harshavardhana  Hello, as far as I know. deployment yaml is not complete if it's correct, which leads to the pending issue. So I think its the problem of this project need to solve.

besides, I think pv is supported by minio system ? how could we create first and manually then deploy minio ?  is it a good solution ???
