### ISSUE TITLE
How to add new gateway support?

### ISSUE THREAD

**Issue by Grade-Two** [minio/minio#9155]
There have been several gateway supported by minio like azure and hdfs. 
I want to add my new gateway for supporting other cloud storage platform. 
How to add new gateway support in minio? And is there any file I should change for compiling and running my new gateway code?
Thank you very much for answering my question above.

**Comment by nitisht** [comment]
@Grade-Two for such questions it is better join us on Slack. Please discuss with the team on Slack with your questions and way forward. Closing this issue.
