### ISSUE TITLE
Server not initialized, please try again

### ISSUE THREAD

**Issue by zth390872451** [minio/minio#9156]
## Current Behavior
1、Console startup log:
Unable to read 'format.json' from http://84.201.146.158:9000/minio1/minio: 404 page not found
2、The browser selects to create a bucket, and then prompts: Server not initialized, please try again

## Steps to Reproduce (for bugs)
On the thress server,my sh script is here : 
export MINIO_REGION_NAME=us-east-1
export MINIO_ACCESS_KEY=name
export MINIO_SECRET_KEY=passwordxxxxxxxxx
minio server  \
http://ip1/minio1/minio  http://ip1/minio2/minio \
http://ip2/minio1/minio  http://ip2/minio2/minio \
http://ip3/minio1/minio http://ip3/minio2/minio > /data/log/minio.log  2>&1

context:
minio version RELEASE.2020-03-14T02-21-58Z
Linux version 3.10.0-1062.9.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Fri Dec 6 15:49:49 UTC 2019

Other problem:I start one minio on server ok,but cluster fail,Conflict?
I find nothing in my dir /minio1/minio /minio2/minio when I start the run script.
server initial failed? how to sloved it?pls,thsk!

**Comment by nitisht** [comment]
instead of 

```
http://ip1/minio1/minio http://ip1/minio2/minio
http://ip2/minio1/minio http://ip2/minio2/minio
http://ip3/minio1/minio http://ip3/minio2/minio
```

can you try 

```
http://ip1/minio1/data http://ip1/minio2/data
http://ip2/minio1/data http://ip2/minio2/data
http://ip3/minio1/data http://ip3/minio2/data
```

**Comment by zth390872451** [comment]
> instead of
> 
> ```
> http://ip1/minio1/minio http://ip1/minio2/minio
> http://ip2/minio1/minio http://ip2/minio2/minio
> http://ip3/minio1/minio http://ip3/minio2/minio
> ```
> 
> can you try
> 
> ```
> http://ip1/minio1/data http://ip1/minio2/data
> http://ip2/minio1/data http://ip2/minio2/data
> http://ip3/minio1/data http://ip3/minio2/data
> ```

I tried this,but no use.

**Comment by nitisht** [comment]
> I tried this,but no use.

Try 

```
http://ip1/data1 http://ip1/data2
http://ip2/data1 http://ip2/data2
http://ip3/data1 http://ip3/data2
```

**Comment by zth390872451** [comment]
> > I tried this,but no use.
> 
> Try
> 
> ```
> http://ip1/data1 http://ip1/data2
> http://ip2/data1 http://ip2/data2
> http://ip3/data1 http://ip3/data2
> ```

still no use!

**Comment by zth390872451** [comment]
> > I tried this,but no use.
> 
> Try
> 
> ```
> http://ip1/data1 http://ip1/data2
> http://ip2/data1 http://ip2/data2
> http://ip3/data1 http://ip3/data2
> ```

the console always show that:
Unable to read 'format.json' from http://84.201.146.158:9000/data2: 404 page not found

**Comment by caizhenboy** [comment]
I have the same question,Do you solve it?

**Comment by zth390872451** [comment]
> I have the same question,Do you solve it?

no...

**Comment by caizhenboy** [comment]
> > I have the same question,Do you solve it?
> 
> no...

Do you try to deploy the minio for one node?Is it successful?

**Comment by zth390872451** [comment]
> > > I have the same question,Do you solve it?
> > 
> > 
> > no...
> 
> Do you try to deploy the minio for one node?Is it successful?

I had tried Single machine deployment and it is success,after that,I tried to deploy cluster but failed even though I deleted the things that  when single macheine deployment .

**Comment by zth390872451** [comment]
I had delete some old directory and start it ok.

**Comment by caizhenboy** [comment]
> I had delete some old directory and start it ok.

Congratulations! Would you mind telling me some details about what you did,and send it to my email 1249318869@qq.com.Thank you very much.

**Comment by vyacheslavdanilyuk** [comment]
@zth390872451 please write in more detail what you deleted ?

**Comment by pgassmann** [comment]
Similar Issue here, 3 nodes, 2 disks each.

logs are repeating:
```
minio_1      | Waiting for a minimum of 3 disks to come online (elapsed 11s)
minio_1      | 
minio_1      | Unable to read 'format.json' from http://minio.kafka01t.mydomain.sh:9000/data1: 404 page not found
minio_1      | 
minio_1      | 
minio_1      | Unable to read 'format.json' from http://minio.kafka02t.mydomain.sh:9000/data1: 404 page not found
minio_1      | 
minio_1      | 
minio_1      | Unable to read 'format.json' from http://minio.kafka03t.mydomain.sh:9000/data1: 404 page not found
minio_1      | 
minio_1      | 
minio_1      | Unable to read 'format.json' from http://minio.kafka01t.mydomain.sh:9000/data2: 404 page not found
minio_1      | 
minio_1      | 
minio_1      | Unable to read 'format.json' from http://minio.kafka02t.mydomain.sh:9000/data2: 404 page not found
minio_1      | 
minio_1      | 
minio_1      | Unable to read 'format.json' from http://minio.kafka03t.mydomain.sh:9000/data2: 404 page not found

```

url is reachable, but is not json but xml with "Server not initialized"
```
curl http://minio.kafka03t.mydomain.sh:9000/data2
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioServerNotInitialized</Code><Message>Server not initialized, please try again.</Message><BucketName>data2</BucketName><Resource>/data2</Resource><RequestId>1601303CB20BBDD3</RequestId><HostId></HostId></Error>/ # 

```

**Comment by harshavardhana** [comment]
> minio_1      | Waiting for a minimum of 3 disks to come online (elapsed 11s)
> minio_1      | 
> minio_1      | Unable to read 'format.json' from http://minio.kafka01t.mydomain.sh:9000/data1: 404 page not found
> minio_1      | 
> minio_1      | 
> minio_1      | Unable to read 'format.json' from http://minio.kafka02t.mydomain.sh:9000/data1: 404 page not found
> minio_1      | 
> minio_1      | 
> minio_1      | Unable to read 'format.json' from http://minio.kafka03t.mydomain.sh:9000/data1: 404 page not found

This means that your DNS is not resolving to the host where the /data1 resides @pgassmann - fix DNS to resolve to nodes where your disks are being mounted/exported from.

**Comment by pgassmann** [comment]
@harshavardhana dns should be ok. that curl was executed inside the minio container sh.

my `docker-compose.yml`, same on all three hosts, except the hostname setting.
```yaml
version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2020-03-25T07-03-04Z
    volumes:
      - minio-data1:/data1
      - minio-data2:/data2
    ports:
      - "9000:9000"
    expose:
      - 9000
    hostname: kafka01t.mydomain.sh
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: secret
      VIRTUAL_HOST: "minio.kafka01t.mydomain.sh"
    command: server http://minio.kafka0{1...3}t.mydomain.sh/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio-data1:
  minio-data2:
```

how does a minio server know which node of the cluster it is?

**Comment by harshavardhana** [comment]
> how does a minio server know which node of the cluster it is?

it needs to know by resolving the DNS and the local interfaces should use the same IP as the one resolved by the DNS if it's not the case it won't start.

**Comment by pgassmann** [comment]
ok, but then it is not possible to run it in docker in distributed mode without overlay network? in docker, the container always has a local ip.

**Comment by harshavardhana** [comment]
> ok, but then it is not possible to run it in docker in distributed mode without overlay network? in docker, the container always has a local ip.

Yes its not possible @pgassmann - or expose the host IP

**Comment by pgassmann** [comment]
Thank you for that information. it works when setting `network_mode: host`

**Comment by gmoulard** [comment]
Hi, 
I send on 4 server: 

docker run -p 9000:9000 --name=minio  \
  -e "MINIO_ACCESS_KEY=$OMCLOUD_MINIO_ACCESS_KEY"  \
  -e "MINIO_SECRET_KEY=$OMCLOUD_MINIO_SECRET_KEY"   \
  minio/minio \
  server --address '0.0.0.0:9000' http://x.27.y.112:9000/data http://x.27.193.113:9000/data \
  http://x.25.193.112:9000/data http://x.25.y.113:9000/data

all  server log: 
Unable to read 'format.json' from http://x.27.y.112:9000/data: 404 page not found
Unable to read 'format.json' from http://x.25.y.112:9000/data: 404 page not found
Unable to read 'format.json' from http://x.25.y.113:9000/data: 404 page not found
Waiting for a minimum of 2 disks to come online (elapsed 2m34s)

when I curl the server direcly from one other mv my debug send:
0.0.0.0 [REQUEST s3.ListObjectsV1] 15:56:54.109
0.0.0.0 GET /data
0.0.0.0 Host: x.27.y.112:9000
0.0.0.0 Accept: */*
0.0.0.0 Content-Length: 0
0.0.0.0 User-Agent: curl/7.29.0
0.0.0.0
0.0.0.0 [RESPONSE] [15:56:54.109] [ Duration 274µs  ↑ 38 B  ↓ 548 B ]
0.0.0.0 503 Service Unavailable
0.0.0.0 Server: MinIO/RELEASE.2020-04-10T03-34-42Z
0.0.0.0 X-Amz-Request-Id: 16056C33F3EA50E0
0.0.0.0 X-Xss-Protection: 1; mode=block
0.0.0.0 Accept-Ranges: bytes
0.0.0.0 Retry-After: 120
0.0.0.0 Content-Type: application/xml
0.0.0.0 Vary: Origin
0.0.0.0 Content-Length: 264
0.0.0.0 Content-Security-Policy: block-all-mixed-content
0.0.0.0 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioServerNotInitialized</Code><Message>Server not initialized, please try again.</Message><BucketName>data</BucketName><Resource>/data</Resource><RequestId>16056C33F3EA50E0</RequestId><HostId></HostId></Error>


Do you have any info?
G.

**Comment by harshavardhana** [comment]
> Hi, 
> I send on 4 server: 
> 
> docker run -p 9000:9000 --name=minio  \
>   -e "MINIO_ACCESS_KEY=$OMCLOUD_MINIO_ACCESS_KEY"  \
>   -e "MINIO_SECRET_KEY=$OMCLOUD_MINIO_SECRET_KEY"   \
>   minio/minio \
>   server --address '0.0.0.0:9000' http://x.27.y.112:9000/data http://x.27.193.113:9000/data \
>   http://x.25.193.112:9000/data http://x.25.y.113:9000/data
> 
> all  server log: 
> Unable to read 'format.json' from http://x.27.y.112:9000/data: 404 page not found
> Unable to read 'format.json' from http://x.25.y.112:9000/data: 404 page not found
> Unable to read 'format.json' from http://x.25.y.113:9000/data: 404 page not found
> Waiting for a minimum of 2 disks to come online (elapsed 2m34s)
> 
> when I curl the server direcly from one other mv my debug send:
> 0.0.0.0 [REQUEST s3.ListObjectsV1] 15:56:54.109
> 0.0.0.0 GET /data
> 0.0.0.0 Host: x.27.y.112:9000
> 0.0.0.0 Accept: */*
> 0.0.0.0 Content-Length: 0
> 0.0.0.0 User-Agent: curl/7.29.0
> 0.0.0.0
> 0.0.0.0 [RESPONSE] [15:56:54.109] [ Duration 274µs  ↑ 38 B  ↓ 548 B ]
> 0.0.0.0 503 Service Unavailable
> 0.0.0.0 Server: MinIO/RELEASE.2020-04-10T03-34-42Z
> 0.0.0.0 X-Amz-Request-Id: 16056C33F3EA50E0
> 0.0.0.0 X-Xss-Protection: 1; mode=block
> 0.0.0.0 Accept-Ranges: bytes
> 0.0.0.0 Retry-After: 120
> 0.0.0.0 Content-Type: application/xml
> 0.0.0.0 Vary: Origin
> 0.0.0.0 Content-Length: 264
> 0.0.0.0 Content-Security-Policy: block-all-mixed-content
> 0.0.0.0 <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>XMinioServerNotInitialized</Code><Message>Server not initialized, please try again.</Message><BucketName>data</BucketName><Resource>/data</Resource><RequestId>16056C33F3EA50E0</RequestId><HostId></HostId></Error>
> 
> 
> Do you have any info?
> G.

Don't use unexpected IPs on overlay network either use overlay network or use --net=host

**Comment by gmoulard** [comment]
`--net=host` run perfectly, many thanks
G.

**Comment by strima** [comment]
instead of `--net=host`  you can also use it like this for e.g. 2 servers with each 6 disks

```
SERVER 1:

/usr/bin/docker run -d --rm \
    -p 9000:9000 \
    --hostname minio01.yourdomain.internal \
    -v /export:/export \
    -e "MINIO_ACCESS_KEY=minio" \
    -e "MINIO_SECRET_KEY=changeme" \
    --name minio01 minio server --address ':9000' http://minio0{1...2}.yourdomain.internal/export/data0{1...6}


SERVER 2:

/usr/bin/docker run -d --rm \
    -p 9000:9000 \
    --hostname minio02.yourdomain.internal \
    -v /export:/export \
    -e "MINIO_ACCESS_KEY=minio" \
    -e "MINIO_SECRET_KEY=changeme" \
    --name minio02 minio server --address ':9000' http://minio0{1...2}.yourdomain.internal/export/data0{1...6}

```
