### ISSUE TITLE
Share button for public objects

### ISSUE THREAD

**Issue by ihostage** [minio/minio#9157]
### Given

We have a public bucket with read-only access for all users. 

### Problem

MinIO Browser users can't by one-click copy public link to object.

### Solution

The sharing button should just copy the link to the clipboard if the object is already public.

### Alternatives

It can be another button, but I think that additional logic for the sharing button is a good solution.

### Additional context

We don't use MinIO as S3 storage. We use MinIO Browser on gateway mode for external S3 storage.

**Comment by ihostage** [comment]
@egorkaru will create a pull request with our vision of implementation.

**Comment by harshavardhana** [comment]
Fixed by #9162
