### ISSUE TITLE
GCS Docs Page returns a 404 and is not listed in the sidebar

### ISSUE THREAD

**Issue by J12934** [minio/minio#9174]
I tried to access the Google Cloud Storage Docs page (https://docs.minio.io/docs/minio-gateway-for-gcs.html) which is still linked from a number of sources but the page returns a 404. The Page still exists in github, see: https://github.com/minio/minio/blob/master/docs/gateway/gcs.md

I briefly scrolled through the files git history but could not find any reference to it being deprecated or removed on purpose, so I'm opening up this issues just to make sure it's done on purpose. 

## Expected Behavior

Go to https://docs.minio.io/docs/minio-gateway-for-gcs.html

See rendered markdown file from github repo.

## Current Behavior

Shows empty page.

## Possible Solution

If accidental, fix it ;) and link it back in the sidebar.

If removed on purpose, please add a warning in the gcs markdown file to make this clear why it was removed.

## Context

Was trying do deploy minio as a gcs gateway, but I'm fell like it might not be properly supported anymore.

**Comment by harshavardhana** [comment]
@J12934 it's not encouraged so removed from official reference - you can still find it here https://github.com/minio/minio/blob/master/docs/gateway/gcs.md
