### ISSUE TITLE
Add support for Admin bind to LDAP Server

### ISSUE THREAD

**Issue by nitisht** [minio/minio#9178]
**Is your feature request related to a problem? Please describe.**
Currently MinIO uses simple bind with LDAP server which allows to query only the groups of the authenticating member. Some LDAP environments may need to use Regular bind (admin bind) approach where the admin who may not be a part of any group can still query all groups.

**Describe the solution you'd like**
MinIO uses regular bind approach as explained here https://help.fortinet.com/fadc/4-8-0/olh/Content/FortiADC/handbook/remote_ldap_server.htm

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by kumy** [comment]
We're definitely interested in this feature. This seems necessary to correctly lookup the user's `DN` based on `MINIO_IDENTITY_LDAP_USERNAME_SEARCH_FILTER` filter especially when users are used to use their `uid`, and the `DN` is based in `CN` attribute.

**Comment by kumy** [comment]
Another example of different bind methods at Postgres (which worked for us). They call them `simple bind mode` (the one which seems already implemented in minio) and `search+bind mode`, the one that we request here :) See: https://www.postgresql.org/docs/10/auth-methods.html#AUTH-LDAP

**Comment by harshavardhana** [comment]
Closing as duplicate of #10112

**Comment by conrallendale** [comment]
This isn't a duplicate of #10112. That is different formats for bind. This is bind DN to search a user (Regular bind). Still an issue, please reopen.
