### ISSUE TITLE
event time is not in ISO-8601 format as per specification

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#9182]
`ListenBucketNotification` REST API in minio returns like `2020-03-22T05:14:32Z` but it breaks time format as per [Event Message Structure](https://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html),

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
ListenBucket is not AWS S3 specification @balamurugana so I don't think we need to comply here

**Comment by balamurugana** [comment]
> ListenBucket is not AWS S3 specification @balamurugana so I don't think we need to comply here

`ListenBucketNotification` is one way to get events. This issue is about event message structure issue, not with `ListenBucketNotification` specifics.

**Comment by harshavardhana** [comment]
@balamurugana if you look at ISO-8601 specifics the .000 is considered optional and 

> "2006-01-02T15:04:05Z"

can be used interchangeable with

> "2006-01-02T15:04:05.000Z"

**Comment by balamurugana** [comment]
I am not sure on that. The spec https://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html doesn't say anything about that, but specifies examples with fraction-of-second.

**Comment by kannappanr** [comment]
Bala, PTAL https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations and http://jsfiddle.net/wq7tjec7/14/ where you try out giving both the time formats provided by Harsha

**Comment by balamurugana** [comment]
> Bala, PTAL https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations and http://jsfiddle.net/wq7tjec7/14/ where you try out giving both the time formats provided by Harsha

From where do you see about fration-of-time in the format is optional? AFAICS, ISO 8601 is broad range with various permissible formats `For example, "2007-04-05T14:30Z" or "2007-04-05T12:30-02:00"` (from the link you mentioned).

I see event message structure defines time format with examples. If we defer from the structure, I have no issues to handle AWS S3 format and MinIO format separately.

**Comment by kannappanr** [comment]
Closing this issue as we are handling both versions of ISO 8601 format in minio-java SDK
