### ISSUE TITLE
mc cannot list user data for due to a sio error

### ISSUE THREAD

**Issue by ktarplee** [minio/minio#9193]
I was trying to give full admin privileges to new minio user but `mc admin user list` is broken.

## Expected Behavior

`mc admin user list test2` should produce the output (see the steps to reproduce below).
```txt
enabled    admin2
```

This is the output when `mc admin user list test` is used (i.e. with the original admin user).

## Current Behavior
mc: <ERROR> Cannot list user: sio: data is not authentic.

## Steps to Reproduce (for bugs)
```bash
docker run \
  -d \
  -p 9000:9000 \
  -e MINIO_ACCESS_KEY=admin \
  -e MINIO_SECRET_KEY=secretkey \
  --name minio \
  --restart no \
  minio/minio server /data

sleep 2;

cat > /tmp/admin.json << EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "admin:*"
      ],
      "Effect": "Allow",
      "Sid": ""
    },
    {
      "Action": [
        "s3:*"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::*"
      ],
      "Sid": ""
    }
  ]
}
EOF

export MC_HOST_test="http://admin:secretkey@localhost:9000/"

mc admin user list test
mc admin user add test admin2 adminpass
mc admin group add test admins admin2
mc admin policy add test admin /tmp/admin.json
mc admin policy set test admin group=admins

export MC_HOST_test2="http://admin2:adminpass@localhost:9000/"
# This fails with "mc: <ERROR> Cannot list user: sio: data is not authentic."
mc admin user list test2
```
## Your Environment

* Version used (`minio version`):
mc client version: RELEASE.2020-03-06T23-29-45Z
minio version: RELEASE.2020-03-19T21-49-00Z

**Comment by harshavardhana** [comment]
Use the latest server and latest `mc` - most probably your client is old here.

**Comment by harshavardhana** [comment]
Latest `mc` and `latest`  minio - `mc admin user list` works fine 

```
mc admin user list play | tail -10
enabled    kopiauser-ef7641      readwrite           
enabled    kopiauser-fa4c16      readwrite           
enabled    kopiauser-1fb04d      readwrite           
enabled    kopiauser-295608      readwrite           
enabled    kopiauser-406967      readwrite           
enabled    kopiauser-7fa66a      readwrite           
enabled    minio                 readwrite           
enabled    kopiauser-209e66      readwrite           
enabled    kopiauser-3aaee7      readwrite           
enabled    kopiauser-b25274      readwrite           
```

**Comment by ktarplee** [comment]
I get this output
```txt
ff477ba839261c8073b7e790acc612f779d51fbbd91b0c9e339ab2e50fce06b3
Added user `admin2` successfully.
Added members {admin2} to group admins successfully.
Added policy `admin` successfully.
Policy admin is set on group `admins`
mc: <ERROR> Cannot list user: sio: data is not authentic.
```
I just pulled minio/minio:latest and I just updated my mc to the latest version RELEASE.2020-03-14T01-23-37Z.

What exact versions are you using?

**Comment by ktarplee** [comment]
Are you using the default (original) admin user for those commands or the one the policy is creating?

**Comment by harshavardhana** [comment]
> Are you using the default (original) admin user for those commands or the one the policy is creating?

admin

**Comment by harshavardhana** [comment]
> ff477ba839261c8073b7e790acc612f779d51fbbd91b0c9e339ab2e50fce06b3
> Added user `admin2` successfully.
> Added members {admin2} to group admins successfully.
> Added policy `admin` successfully.
> Policy admin is set on group `admins`
> mc: <ERROR> Cannot list user: sio: data is not authentic.

I see the problem because the encrypted content is sent as the super admin, not the admin that you used. I think the issue is because of that.

**Comment by ktarplee** [comment]
The default (original) admin works great.  When I try to create the admin it no longer works.  Lots of other `mc admin user` commands work such as `mc admin user info test2 admin2`

```txt
AccessKey: admin2
Status: enabled
PolicyName: 
MemberOf: admins
```

**Comment by ktarplee** [comment]
It seems to be specific to "list" but I am not sure.

**Comment by harshavardhana** [comment]
Sent a fix thanks for the reproducer @ktarplee
