### ISSUE TITLE
memory keep rising as objects increase

### ISSUE THREAD

**Issue by NeoyeElf** [minio/minio#9197]
I'm running a test about memory that minio cost. And I found out that the memory minio used rised as objects increase.

## Expected Behavior
Memory should not rise as objects increase

## Current Behavior
Memory rise as objects increase, and don't release

## Possible Solution
no ideas yet.

## Steps to Reproduce (for bugs)
my test code (I used aws-sdk-go ): 

```
sess := session.Must(session.NewSession(&aws.Config{
	Region:               aws.String("cn-north-1"),
	DisableSSL:       aws.Bool(true),
	Credentials:      credentials.NewStaticCredentials("AccessKeyId", "AccessKeySecret", ""),
	Endpoint:         aws.String("Endpoint"),
	S3ForcePathStyle: aws.Bool(true),
}))
service := s3.New(sess)
bucket := "test"

meta := make(map[string]string)
meta["head"] = strconv.Itoa(AWSExpectHead)
meta["length"] = strconv.Itoa(AWSExpectLength)

for i := 0; i < 500; i++ {
	key := strconv.Itoa(i) + "aaa"
	content := strings.Repeat(guid, i)
	_, err := service.PutObject(&s3.PutObjectInput{
		Body:        io.ReadSeeker(strings.NewReader(content)),
		Bucket:      aws.String(bucket),
		Key:         aws.String(key),
		Metadata:    aws.StringMap(meta),
		ContentType: aws.String("text/plain"),
	})
	if err != nil {
		t.Log("aws put error", err)
	}
}

fmt.Println("done!")
```

1. 
```
docker run -p 9088:9000 --name minio1 -d \
  -m 1G --memory-swap=1G \
  -e "MINIO_ACCESS_KEY=your-ak" \
  -e "MINIO_SECRET_KEY=your-sk" \
  -v /data/minio:/data \
  minio/minio server /data
```
2. run the code
3. change the key name(e.g. "aaa" -> "bbb")
4. repeat 2~3, observe the memory minio used (using `docker stats`) in the meantime

## Context
minio's memory keep rising in my production env

## Your Environment

* Version used (`minio version`): RELEASE.2020-03-19T21-49-00Z
* Operating System and version (`uname -a`):  Darwin liuwenzhedeMacBook-Pro.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

**Comment by klauspost** [comment]
It is quite common that buffers, etc is kept in memory and that Go releases these lazily.

If you are interested in digging into the details, you can run the profiler to get before/after using `mc admin profile start --type=mem myminio && run-test && mc admin profile stop myminio`.

This will download server profiles you can inspect with Go tools like `go tool pprof -base=profile-172.31.91.126_9000-mem-before.pprof profile-172.31.91.126_9000-mem.pprof`. But this of course requires some insight into the Go development tools.

**Comment by NeoyeElf** [comment]
my top10 result:
![20200325105934](https://user-images.githubusercontent.com/6872731/77497212-c734fb80-6e87-11ea-9e52-93bf8aae53a1.jpg)

In my test env, the increased memory is not released after I stopped the test code for 10m. when will the increased memory be released?

**Comment by harshavardhana** [comment]
It's released when GC decides to give it back based on when it's automatically triggered. This is not our usage, instead used by internally. 

Go GC's are triggered when growth of memory allocations are 2x than before. This is generally controlled by GOGC variable, if you need more aggressive behavior.

Closing this issue as not a real problem. Unless the memory increases and OOM the system there is nothing for us to do here.

**Comment by NeoyeElf** [comment]
this is the profile in our production env :
![image](https://user-images.githubusercontent.com/6872731/77506740-8cd85800-6ea1-11ea-9cf0-052f97feb2f8.png)

Our usage scenario:
we use minio frequently, 100~1000 objects will be add every day in several buckets. And there will be many put, get, head operations.
we deployed 6 node for minio, and every node's memory have reached around 3G, 2 of them are around 4G. Is this normal? 
Is there any way to prevent the memory from growing endlessly or to limit the memory usage of minio, and return some errors when necessary

**Comment by harshavardhana** [comment]
It won't grow endlessly @NeoyeElf

**Comment by NeoyeElf** [comment]
the memory metrics for 1 node in last 24 hours in our production env:
![image](https://user-images.githubusercontent.com/6872731/77508635-2144b980-6ea6-11ea-89fe-ff5dbc97f131.png)
there are very few requests at night, but memory usage hasn't dropped much.

If I want to limit the memory that minio used, what can I do?
For example, I deploy the minio using k8s, and limit the memory to 4G, when it's memory usage exceed 4G, then it will be killed by OOM. I don't want it be killed, what can I do?

**Comment by harshavardhana** [comment]
> For example, I deploy the minio using k8s, and limit the memory to 4G, when it's memory usage exceed 4G, then it will be killed by OOM. I don't want it be killed, what can I do?

It won't get killed @NeoyeElf

**Comment by NeoyeElf** [comment]
> > For example, I deploy the minio using k8s, and limit the memory to 4G, when it's memory usage exceed 4G, then it will be killed by OOM. I don't want it be killed, what can I do?
> 
> It won't get killed @NeoyeElf

yes, it was get killed by OOM when we limit the memory to 4G. now we raise it to 6G

**Comment by harshavardhana** [comment]
> yes, it was get killed by OOM when we limit the memory to 4G. now we raise it to 6G

if you have less memory requirement you should limit servers for a number of API requests, if you pound server buffers with large API requests and set 4G you are under-provisioning the servers.

You need to let the time for GC to kick in - https://github.com/minio/minio/tree/master/docs/throttle

**Comment by NeoyeElf** [comment]
wow~ that's Exciting. When will the feature be released?

**Comment by harshavardhana** [comment]
> wow~ that's Exciting. When will the feature be released?

Being released as we speak @NeoyeElf
