### ISSUE TITLE
Distributed minio low read performance

### ISSUE THREAD

**Issue by rvadim** [minio/minio#9198]
Hi, thank you for you hard work.

I'm requesting 1 file `index.html` with `Hello world!` content from minio using `ab`

## Expected Behavior
5-10 ms 98 percentile for head/getObject request(small object).

### Part one
```
$ ab -c 10 -n 1000 "https://minio/rvadim-test/index.html?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=rvadim-test%2F20200324%2F%2Fs3%2Faws4_request&X-Amz-Date=20200324T085719Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=..."
Document Length:        13 bytes

Concurrency Level:      10
Time taken for tests:   3.440 seconds
Complete requests:      1000
Failed requests:        0
Write errors:           0
Total transferred:      490000 bytes
HTML transferred:       13000 bytes
Requests per second:    290.68 [#/sec] (mean)
Time per request:       34.402 [ms] (mean)
Time per request:       3.440 [ms] (mean, across all concurrent requests)
Transfer rate:          139.10 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        3    5   1.3      4      14
Processing:    17   29   8.9     28      86
Waiting:       17   29   8.9     28      86
Total:         21   34   9.3     32      95

Percentage of the requests served within a certain time (ms)
  50%     32
  66%     36
  75%     38
  80%     40
  90%     45
  95%     51
  98%     60
  99%     64
 100%     95 (longest request)
```
Also `mc admin trace minio` reports 15-30ms time:
```
09:40:00.340 [200 OK] s3.GetObject minio./rvadim-test/index.html?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=rvadim-test%2F20200324%2F%2Fs3%2Faws4_request&X-Amz-Date=20200324T085719Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=...  123.123.123.123    24.692ms
```
### Part two
If I try to increase ab concurrency more then 20, response time begins to grow.
For example, with `ab -c 100` 105ms 50 percentile and 200+ms 98 percentile, minio trace reports 30-200ms time

## Questions
1. Is it normal for my configuration to have ~15-30ms response on minio?
2. Is it normal that with the increase of concurrent requests increases the response time of the minio?

## Your Environment

* Version used (`minio version`): RELEASE.2020-03-14T02-21-58Z
* Environment name and version (e.g. nginx 1.9.1): Kubernetes 1.15.9 
* Server type and version: --
* Operating System and version (`uname -a`): Centos 7 4.4.213-1
* Configuration: 2 zones by 16 disks
* 20M objects in storage
```
minio_args:
    - minio
    - server
    - https://minio-z0-{0...3}.minio-z0:9000/data{0...3}
    - https://minio-z1-{0...3}.minio-z1:9000/data{0...3}
```
4 nodes with 8 disks each especially for minio, 2 minio pods on each node.
80 cores(16 available for each minio)
32 Gb RAM available for each minio
3.6 Tb SSD disks, 4 disk per minio pod

**Comment by klauspost** [comment]
This doesn't seem completely unreasonable. For very small files like this a regular http server will likely outperform it. MinIO has to coordinate between all your servers on each request, so small payloads will have a considerable overhead.

'ab' is generally not considered a good benchmark, even for HTTP servers. You can give [warp](https://github.com/minio/warp) a try. In particular you can see request times for different payload sizes using the `--obj.randsize` option.

Maybe try `warp get --obj.randsize --autoterm --concurrent=10 --obj.size=50MB --requests` to get an idea of the performance. It will test up to 50MiB objects. You can set host and credentials with env variables.

**Comment by rvadim** [comment]
The actual problem:
We run rclone for full server backup, rclone check timestamps and check each file. So it's near 20M requests, it's create a lot of CPU usage(all available cores). So, if we increase number of concurrent thread for rclone performance decreased.
Why it consume so much CPU on HEAD requests? And why it starts working slower as in example above?

**Comment by harshavardhana** [comment]
> We run rclone for full server backup, rclone check timestamps and check each file. So it's near 20M requests, it's create a lot of CPU usage(all available cores). So, if we increase number of concurrent thread for rclone performance decreased.
> Why it consume so much CPU on HEAD requests? And why it starts working slower as in example above?

There are lot of why's but no concrete information from your end

- what is the disk type? 
- what type of hardware is being used?
- Have you done a benchmark on your hardware to see if it can handle a small file workload?
- what is the interconnect and network speed?

Without any of this information, there is just no way to proceed.

**Comment by olddanmer** [comment]
I can answer about the hardware we are using.
There are 4 servers Intel R2000WF Family. Each server have two CPU Xeon Gold 6248 with 20 cores, 768GB RAM and 11 SSD disks Intel D3-S4610 3.84TB. The interconnection between servers is two 10G links. Servers are working under CentOS 7.
@rvadim could tell more about how SSDs are parted and used.

**Comment by klauspost** [comment]
@olddanmer Have you considered something like restic that AFAIK doesn't require crawling the remote file system? rclone basically downloads the entire directory structure which will be resource intensive.

You can use warp to get some idea of the expected speed/throughput of various operations.

**Comment by olddanmer** [comment]
@klauspost I've read restic documentation and as I understand it can use Minio only as backend. restic can't backup from remote Minio to local filesystem. But we are using exactly this way. So, unfortunately, restic can't helps us.

**Comment by harshavardhana** [comment]
We made some performance improvements in recent release can you upgrade and test again @olddanmer @rvadim ?

**Comment by rvadim** [comment]
Yes, we can.
> Breaking Change related to multiple LDAP OU support, so rolling upgrade is not supported.

Can you please explain how to upgrade kubernetes minio setup in this case? Just set replicas to 0, change image tag and than set replicas back? Or maybe another proper way?
Thank you.

**Comment by harshavardhana** [comment]
> Can you please explain how to upgrade kubernetes minio setup in this case? Just set replicas to 0, change image tag and than set replicas back? Or maybe another proper way?
> Thank you.

That is the correct way @rvadim

**Comment by rvadim** [comment]
Hi,
cluster have been upgraded. But performance of read and head operations not changed at all.
Interesting thing is zone0 minios uses 15 cores during backup, but zone1 minios uses near 5-9 cores(see screenshot).
Minio service contains all endpoints:
```
~$ kubectl get endpoints minio-service -o yaml |grep name:
  name: minio-service
      name: minio-z0-3
      name: minio-z1-0
      name: minio-z1-3
      name: minio-z0-1
      name: minio-z1-1
      name: minio-z0-2
      name: minio-z1-2
      name: minio-z0-0
```
![Screenshot(15)](https://user-images.githubusercontent.com/7434399/77994176-d7d2ef00-7329-11ea-97ed-f69673355897.png)

**Comment by harshavardhana** [comment]
> Hi,
> cluster have been upgraded. But performance of read and head operations not changed at all.
> Interesting thing is zone0 minios uses 15 cores during backup, but zone1 minios uses near 5-9 cores(see screenshot).
> Minio service contains all endpoints:
> 
> ```
> ~$ kubectl get endpoints minio-service -o yaml |grep name:
>   name: minio-service
>       name: minio-z0-3
>       name: minio-z1-0
>       name: minio-z1-3
>       name: minio-z0-1
>       name: minio-z1-1
>       name: minio-z0-2
>       name: minio-z1-2
>       name: minio-z0-0
> ```
> 
> ![Screenshot(15)](https://user-images.githubusercontent.com/7434399/77994176-d7d2ef00-7329-11ea-97ed-f69673355897.png)

Once you have upgraded to latest release please run `mc admin obd` to capture network and disk profile for your setup?

**Comment by rvadim** [comment]
Hi!
```
/ $ mc admin obd minio
● Admin Info ... ✔ 
● CPU ... ✔ 
● Disk Hardware ... ✔ 
● Os Info ... ✔ 
● Mem Info ... ✔ 
● Process Info ... ✔ 
● Config ... ✔ 
● Drive ... ✔ 
● Net ... ✔ 
```
Is it store diagnostic results somewhere?

**Comment by harshavardhana** [comment]
Yes it should be stored locally to your disk is that not the case ?

**Comment by rvadim** [comment]
fs is in ro mode on the my mc installation.
I run it with `--json` and save the output. Also I cut part of the fqdn.
[obd.json.gz](https://github.com/minio/minio/files/4489407/obd.json.gz)

**Comment by harshavardhana** [comment]
> fs is in ro mode on the my mc installation.
> I run it with `--json` and save the output. Also I cut part of the fqdn.
> [obd.json.gz](https://github.com/minio/minio/files/4489407/obd.json.gz)

You can see here your servers are not responding here

```
  {
    "addr": "minio-z0-0.minio-z0.it.svc:9000",
    "error": "Post https://minio-z0-0.minio-z0.it.svc:9000/minio/peer/v7/dispatchnetobdinfo?: net/http: timeout awaiting response headers"
  },
```

Simple tests such as OBD are not even completing @rvadim - the issue here points to clearly something in your network layer. Your network layer is giving on an average on some remotes and some are all over the place. 

```
~ for i in $(jq .obdInfo.perf.net obd.json | grep avg_bytes_per_sec | awk {'print $2'} | cut -f1 -d,); do echo "$i*8" | bc -l | numfmt --to=si; done
3.7G
4.0G
4.6G
3.7G
5.7G
4.1G
79G
7.9G
4.0G
81G
8.5G
5.8G
82G
3.6G
4.0G
4.3G
8.0G
7.6G
4.7G
3.7G
4.9G
```

I clearly think your network has some serious issues here @rvadim its not optimal to what it is supposed to be, perhaps performing sub-optimally. The overall latency is also higher between nodes so all of this can constitute your current problems.

On a happy note, all your drives on an average give equal performance which is a very good sign
```
for i in $(jq .obdInfo.perf.drives obd.json | grep avg_bytes_per_sec | awk {'print $2'} | cut -f1 -d,); do echo "$i" | bc -l | numfmt --to=si; done
436M
436M
432M
435M
436M
435M
433M
435M
435M
434M
436M
435M
435M
434M
434M
438M
436M
437M
437M
437M
437M
436M
436M
439M
442M
436M
437M
430M
430M
430M
429M
435M
436M
436M
436M
436M
434M
434M
434M
435M
434M
434M
434M
436M
436M
435M
434M
422M
436M
434M
423M
438M
436M
436M
436M
438M
435M
437M
434M
436M
436M
436M
436M
```

**Comment by rvadim** [comment]
> Simple tests such as OBD are not even completing @rvadim - the issue here points to clearly something in your network layer. Your network layer is giving on an average on some remotes and some are all over the place.

It is because 4 servers, 2 minio pods on each, 8 total.

> The overall latency is also higher between nodes so all of this can constitute your current problems.

What is `net.latency` actually means? Is it ping latency, or http request latency? How to reproduce it?

**Comment by harshavardhana** [comment]
> > Simple tests such as OBD are not even completing @rvadim - the issue here points to clearly something in your network layer. Your network layer is giving on an average on some remotes and some are all over the place.
> 
> It is because 4 servers, 2 minio pods on each, 8 total.
> 

Your performance cannot be improved beyond this, your servers themselves are under-provisioned for the workload you want. You need to bring more servers to get better bandwidth.

The primary reason is, you are using zoned setup by creating fake zones which do not exist in reality. i.e your zone expansion is not beyond 4+4 servers instead you provision more on the same server, so in essence, your HA has not improved you have unnecessarily split the nodes. 

Zones should be used as a resort when you are really wanting to expand, not as a way to split your setup unnecessarily where your availability is not expanding but you have simply overly complicated your setup when is clearly not needed. It doesn't add any advantage to use zones.

For simple testing it's fine, but the added complexity is meaningless if these are not physical nodes themselves, your bandwidth is getting halved for no good reason, neither your disks can collectively provide more bandwidth because I/O is unnecessarily split.

So it is better to not split zones

```
minio_args:
    - minio
    - server
    - https://minio-z0-{0...3}.minio-z0:9000/data{0...3}
    - https://minio-z1-{0...3}.minio-z1:9000/data{0...3}
```

This is wrong for your setup.

```
minio_args:
    - minio
    - server
    - https://minio-{0...3}.minio-z:9000/data{0...7}
```

This would be correct still keeps the 16 disks per erasure set. 

> What is `net.latency` actually means? Is it ping latency, or http request latency? How to reproduce it?

You run `mc admin obd` and you reproduce that's it.

**Comment by SergeyZh** [comment]
@harshavardhana First of all thanks a lot for detailed answers!
We created 2 zones because we're planning to expand our Minio cluster 120Tb via 60Tb chunks only. I'll investigate our possible network problems (I don't sure network is guilty) and return with results.
