### ISSUE TITLE
Running a heal is killing the cluster

### ISSUE THREAD

**Issue by l0bster** [minio/minio#9199]
Hi there,

i'm running a 4 node minio cluster on prem. Hosting OS is Ubuntu 18.04.4 LTS (Bionic Beaver). Minio Server Version: 
2020-03-19T21:49:00Z

## Expected Behavior
running a heal shouldn't kill other nodes, rendering the whole minio cluster unusable.

## Current Behavior
Restarting the whole cluster via 

`mc  admin service restart mdh`

Then running
`mc admin heal --remove -r mdh4/`

where mdh4 is node 4 in cluster mdh. The heal is starting an running for several minutes and is doing some good progress. But then suddenly the io load on the other 3 nodes explodes from reading kb/s to 100-200MB/s. The heal count on items is no longer increasing and the whole cluster is no longer able so serve requests.

## Context

I switched the filesystem the nodes were using one by one, starting with node 1. The heal was running without any problems on this node. After it finised we changed the filesystem on the 2nd node and healed it again, everything was fine. Uppon reaching node 3 and 4 the nodes 1 and 2 began dying during the healing process. We now reached a point where the whole cluster is dying withing minutes after a full restart of all nodes.

The nodes are holding several millions of small files, don't know if this helps.

## Your Environment

* Version used (`minio version`):
2020-03-19T21:49:00Z
* Environment name and version (e.g. nginx 1.9.1):
Ubuntu 18.04.4 LTS (Bionic Beaver)
xfs filesystem
* Server type and version:
vmware vm
* Operating System and version (`uname -a`):
Linux mdhlxminio01 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by vadmeste** [comment]
> I switched the filesystem the nodes were using one by one, starting with node 1. The heal was running without any problems on this node. After it finised we changed the filesystem on the 2nd node and healed it again, everything was fine.

Hey @l0bster, could you elaborate more what do you mean by switching the filesystem ?

**Comment by l0bster** [comment]
sure.

we were using ext4 and had problems regarding max inodes.
so we stopped the first node, deleted the filesystem, recreated an xfs filesystem on this node and started a heal. After the heal was finished we did the same on the second node. Until then, everything was fine. Now we reached the third node and we started expierencing problems as described above.

**Comment by vadmeste** [comment]
@l0bster it is possible that healing and crawling were running in parallel. I am going to write some mc commands to have more control on the background processes and their aggressiveness 

@l0bster do you still face an issue on your side ?

**Comment by l0bster** [comment]
@vadmeste , since applications were still accessing the cluster i would say, yes, maybe.

We stopped running the heals on our side to make the cluster accessible for the applications and started mirroring it's contents to a new cluster. We're planning to switch our applications over to the new cluster on monday. Hopefully the sync will be finished then ...

Today i discovered that running a 'mc ls' on a specific subfolder which itself is containing many many subfolders is causing the same problem as the heal. I ran fs checks online, everything looks fine on this side. browsing this specific directory on os side is working fine.

Thanks in advance!

**Comment by l0bster** [comment]
Hey @vadmeste, 

i'm closing this issue now because i'm convinced it's not a pure minio problem. minio is able to produce this issue much faster, but i was able to reproduce this error with os only tools.

Thanks for your help! i really appreciate it ;)
