### ISSUE TITLE
webhook event missing accessKey downloading a object from webgui

### ISSUE THREAD

**Issue by fdefilippo** [minio/minio#9200]
Accessing from webgui and downloading an object the related event is is missing the accessKey:

{"EventName":"s3:ObjectAccessed:Get","Key":"test/chrome_F803V5obKv.png","Records":[{"eventVersion":"2.0","eventSource":"minio:s3","awsRegion":"","eventTime":"2020-03-24T10:00:55Z","eventName":"s3:ObjectAccessed:Get","userIdentity":{"principalId":""},"requestParameters":{**"accessKey":""**,"region":"","sourceIPAddress":"192.168.3.10"},"responseElements":{"content-length":"72612","x-amz-request-id":"15FF352B9CD6970C","x-minio-deployment-id":"f0b05647-345a-4547-aba4-539e879e809f","x-minio-origin-endpoint":"http://192.168.10.3:9100"},"s3":{"s3SchemaVersion":"1.0","configurationId":"Config","bucket":{"name":"test","ownerIdentity":{"principalId":""},"arn":"arn:aws:s3:::test"},"object":{"key":"chrome_F803V5obKv.png","size":72612,"eTag":"a7b1c73f7f67a91c15eefe741f8794a4-1","contentType":"image/png","userMetadata":{"content-type":"image/png"},"versionId":"1","sequencer":"15FF352B9CECA986"}},"source":{"host":"192.168.3.10","port":"","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"}}]}

\# minio -v
minio version RELEASE.2020-03-06T22-23-56Z

**Comment by harshavardhana** [comment]
Let's re-open the issue with a proper description of a reproducer by filling out our issue template. Look at other issues for guidance on how to open a proper issue. 

Closing this issue.
