### ISSUE TITLE
two PNG files with same md5 but different name,  it displays diffrent content-type in chrome.

### ISSUE THREAD

**Issue by PoplarYang** [minio/minio#9205]
The two files with the same md5 but different name，in chrome it displays content-type.
## Expected Behavior
In fact, two PNG files should be the same content-type.

## Current Behavior

content-type in chrome
* 15-31-41-ZYGRZAAm.png  image/png
* 15-31-41-ZYGRZAAM.png  application/octet-stream

```
[root@iZuf64cw1gup8aagpfo2nuZ 25]# md5sum 15-31-41-ZYGRZAAm.png 15-31-41-ZYGRZAAM.png
0156b61a1b8ae18d597729cb95c57f8d  15-31-41-ZYGRZAAm.png
0156b61a1b8ae18d597729cb95c57f8d  15-31-41-ZYGRZAAM.png
[root@iZuf64cw1gup8aagpfo2nuZ 25]# stat 15-31-41-ZYGRZAAm.png 15-31-41-ZYGRZAAM.png
  文件："15-31-41-ZYGRZAAm.png"
  大小：10703     	块：24         IO 块：4096   普通文件
设备：fd01h/64769d	Inode：1575187     硬链接：1
权限：(0644/-rw-r--r--)  Uid：(    0/    root)   Gid：(    0/    root)
最近访问：2020-03-25 15:32:41.254553524 +0800
最近更改：2020-03-25 15:31:46.371290144 +0800
最近改动：2020-03-25 15:32:33.381515742 +0800
创建时间：-
  文件："15-31-41-ZYGRZAAM.png"
  大小：10703     	块：24         IO 块：4096   普通文件
设备：fd01h/64769d	Inode：1575188     硬链接：1
权限：(0644/-rw-r--r--)  Uid：(    0/    root)   Gid：(    0/    root)
最近访问：2020-03-25 15:37:07.488831159 +0800
最近更改：2020-03-25 15:32:41.254553524 +0800
最近改动：2020-03-25 15:32:41.254553524 +0800
创建时间：-
[root@iZuf64cw1gup8aagpfo2nuZ 25]# file 15-31-41-ZYGRZAAm.png 15-31-41-ZYGRZAAM.png
15-31-41-ZYGRZAAm.png: PNG image data, 574 x 288, 8-bit colormap, non-interlaced
15-31-41-ZYGRZAAM.png: PNG image data, 574 x 288, 8-bit colormap, non-interlaced
```

## Possible Solution
Unknow

## Steps to Reproduce (for bugs)

1. upload 15-31-41-ZYGRZAAM.png to minio by AWS s3 go SDK, its content-type is `application/octet-stream`
2. In minio backend, cp 15-31-41-ZYGRZAAM.png to 15-31-41-ZYGRZAAm.png, its content-type change to `image/png`.
3. when using the web to upload `15-31-41-ZYGRZAAM.png`,  its content-type is `application/octet-stream`

## Context

[15-31-41-ZYGRZAAM.png](https://minio.echosoul.cn/image/2020/3/25/15-31-41-ZYGRZAAM.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=poi1fl3hsjejahkrbnq54h5lug075kbmme0xllg7%2F20200325%2Fcn-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200325T080727Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=41d56b084622510689aef8661fccbae01ffaa5f8b73261cb03ccc34fb607dec2) can be download here in 7 days.

## Regression
minio version RELEASE.2020-03-19T21-49-00Z

## Your Environment

* Version used (`minio version`): minio version RELEASE.2020-03-19T21-49-00Z
* Environment name and version (e.g. Nginx 1.9.1): nginx version: nginx/1.16.1
* Server type and version: CentOS Linux release 7.7.1908 (Core)
* Operating System and version (`uname -a`): Linux iZuf64cw1gup8aagpfo2nuZ 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by klauspost** [comment]
We do not support manually changing data in the back end. If you do, you are on your own.

You don't provide information on how you run your server. I suppose are are running it with a single disk. In that case metadata i stored in `/disk/.minio.sys/buckets/bucket/15-31-41-ZYGRZAAm.png 15-31-41-ZYGRZAAM.pn/fs.json`.

This may change with no notice, so use that information at your own risk.

**Comment by PoplarYang** [comment]
Thanks a lot.

The key point is not my copy directly on the server-side.
Now, upload same file in two way, 
1. by aws go s3 sdk, content-type is image/png
```
-rw-r--r-- 1 root root 2.1K 3月  25 18:00 18-0-4-MTLHFDFX.png
fea2b122b22afb1ab1adc799c6734184  18-0-4-MTLHFDFX.png
root@iZuf64cw1gup8aagpfo2nuZ 25]# cat image_out.png/fs.json
{"version":"1.0.2","checksum":{"algorithm":"","blocksize":0,"hashes":null},"meta":{"content-type":"image/png","etag":"2296da29f9a79a97f02b70ff899c78fd-1"}}[root@iZuf64cw1gup8aagpfo2nuZ 25]# cat 18-0-4-MTLHFDFX.png/fs.json
```
2. by the minio web, content-type is application/octet-stream
```
-rw-r--r-- 1 root root 2.1K 3月  25 18:01 image_out.png
fea2b122b22afb1ab1adc799c6734184  image_out.png
[root@iZuf64cw1gup8aagpfo2nuZ 25]# cat 18-0-4-MTLHFDFX.png/fs.json
{"version":"1.0.2","checksum":{"algorithm":"","blocksize":0,"hashes":null},"meta":{"content-type":"application/octet-stream","etag":"fea2b122b22afb1ab1adc799c6734184"}}
```
By adding content-type to s3 go sdk, content-type is correct. 

I have another question, why the same file has different ETag?

**Comment by klauspost** [comment]
@PoplarYang The client uploading the content is responsible for setting the content type. The server accepts the content-type as sent by the client.

Different clients may have different way of detecting/setting it.

**Comment by PoplarYang** [comment]
You're right.
I change endpoint to AWS S3, I found the same behavior.
