### ISSUE TITLE
Distributed MinIO requirements for drivers

### ISSUE THREAD

**Issue by NeoyeElf** [minio/minio#9206]
It's not a bug report, just to ask a question:

> MinIO creates erasure-coding sets of 4, 6, 8, 10, 12, 14 or 16 drives. The number of drives you provide must be a multiple of one of those numbers.

When I deploy distributed minio, to ensure full data protection, the number of drives above is the total drives for all nodes or the drives number for each node? e.g. 6 nodes, 1 drive per node is enough? or 6 nodes, 4 drive per node at least?

Thks.

**Comment by klauspost** [comment]
Please ask questions on slack: https://slack.min.io/

You can see information on erasure setup here: https://docs.min.io/docs/minio-erasure-code-quickstart-guide.html and https://docs.min.io/docs/distributed-minio-quickstart-guide.html
