### ISSUE TITLE
Healing always find yellow objects

### ISSUE THREAD

**Issue by the-glu** [minio/minio#9211]
Hello,

I'm having a strange issue on a minio cluster of 4 machines.
We added a lifecycle policy to automatically cleanup a bucket. During that cleanup, it's seems that we (sometime) ran into errors on other node: "Error: Write failed. Insufficient number of disks online".
I was wondering if somehow the instance doing cleanup lock herself and there is not enough redundancy with node.

So I tried to "heal --recursive" all nodes, and got ~10% of objects in yellow state.
What is strange is that if I run healing a second time, I still get objects (but less) in yellow. The more time I wait, the more objects I get in that state.

Is that a normal behavior ? What a yellow object mean exactly ? Do I have a way to debug this ?

For me, if there was no restart nor service interruption, objects should not go in yellow state.

I checked connections between minio and everything seems fine. All mc admin info (on each 4 nodes) is fully happy. Nothing relevant in logs.

## Your Environment
* Version used: RELEASE.2020-01-16T22-40-29Z (not the latest one, but I cannot upgrade easily the cluster and I did not see something relevant in changelog - but I may be wrong)
* Environment name: Minio instances are behing 2 haproxy doing loadbalancing.
* Server type and version: debian 9

Thanks a lot for your help,

**Comment by vadmeste** [comment]
@the-glu Yellow means that the object was partially healed.

`admin heal` command with --json will provide more details information, each line in the debug corresponds to a healing result of an object, 

Could you do this:
`mc admin heal --json -r your-alias/your-bucket | grep yellow | head -n1` 

and paste the output here ? (or contact me in https://slack.min.io if you want to send it in private)

**Comment by the-glu** [comment]
`{"status":"success","type":"object","name":"[hiddenobjectname]","before":{"color":"yellow","offline":1,"online":3,"missing":0,"corrupted":0,"drives":[{"uuid":"","endpoint":"/opt/minio/data/2","state":"ok"},{"uuid":"","endpoint":"http://10.2.8.18:6102/opt/minio/data/2","state":"ok"},{"uuid":"","endpoint":"http://10.2.8.17:6102/opt/minio/data/2","state":"ok"},{"uuid":"","endpoint":"http://10.2.8.16:6102/opt/minio/data/2","state":"offline"}]},"after":{"color":"yellow","offline":1,"online":3,"missing":0,"corrupted":0,"drives":[{"uuid":"","endpoint":"/opt/minio/data/2","state":"ok"},{"uuid":"","endpoint":"http://10.2.8.18:6102/opt/minio/data/2","state":"ok"},{"uuid":"","endpoint":"http://10.2.8.17:6102/opt/minio/data/2","state":"ok"},{"uuid":"","endpoint":"http://10.2.8.16:6102/opt/minio/data/2","state":"offline"}]},"size":100546}`

I checked on the 'offline' endpoint, the file is present on the server, with the part and the xl.json.

Endpoint is up, accessible from the mino doing the heal (I curled just to be sure).

```
●  10.2.8.16:6102
   Uptime: 1 week 
   Version: 2020-01-16T22:40:29Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

●  10.2.8.17:6102
   Uptime: 1 week 
   Version: 2020-01-16T22:40:29Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

●  10.2.8.18:6102
   Uptime: 1 week 
   Version: 2020-01-16T22:40:29Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

●  10.2.8.19:6102
   Uptime: 1 week 
   Version: 2020-01-16T22:40:29Z
   Network: 4/4 OK 
   Drives: 1/1 OK
```

**Comment by vadmeste** [comment]
Could you check if the error is not intermittent ? run this multiple times

```
mc admin heal --json your-alias/your-bucket/[hiddenobjectname]
```

**Comment by the-glu** [comment]
Yes, it seems to be intermittent. I was not able to have it again in yellow by running the command multiple time.

**Comment by vadmeste** [comment]
> Yes, it seems to be intermittent. I was not able to have it again in yellow by running the command multiple time.

You probably have some networking issues or very high load

**Comment by the-glu** [comment]
The load is present, but not very high.

About network, rest of the stack seem fine. Is there a way to know why the endpoint is think as down ? (And never down in admin info ?) ?

Is healing opening a new connection for each object or use a premenent connection between minios ?

**Comment by the-glu** [comment]
So it seems #9397 is going to fix my original issue.
I don't notice network errors, but that my nodes are going down during automatic cleanup of files (witch I'm not sure is expected).

I close the issue since it's probably not relevant anymore.
