### ISSUE TITLE
LustreFS with file locking disabled

### ISSUE THREAD

**Issue by thoth291** [minio/minio#9212]
**related to a problem**
Currently I can't start a minio server at LustreFS with filelocking disabled.
I don't know what other important features of LFS are causing it to fail - filelocking is obvious first suspect.
Here is what I get:
```bash
$ ./minio server /lustre/path/with/some/TB/of/files
ERROR Unable to initialize backend: function not implemented
```

**alternatives I've considered**
Enabling filelocking is not an option - since that introducing performance degradation

Thanks in Advance!

**Comment by harshavardhana** [comment]
It's not possible unfortunately, we use file locking on FS mode for multiple concurrent access.

Performance degradation is a Lustre issue, we shouldn't be taking these burden in our software.

**Comment by thoth291** [comment]
@harshavardhana, it would be preferable to have an option to specify where your file locking related folder should be placed. This way no burden for your software and greater community (national labs) can finally use it.
For example - SVN failed to do it for us, but GIT has an option and in addition to that relocated it's lock related file to $HOME folder. So now we can use GIT on LustreFS.

**Comment by harshavardhana** [comment]
We would like to avoid too many options @thoth291 - unfortunately at this time we will not do it.

**Comment by thoth291** [comment]
It's fair reply from the point of ownership of the project. After all - that's not my business, but... Honestly, I don't understand why would one limit such a great tool. Being a step away from such a big community and simply ignoring us. I also can see how big companies (energy, oil&gas, aerospace,...) with on prem HPC would benefit from that.
While I highly appreciate your reply - is there anyway to keep this as OPEN feature request for further discussions?

**Comment by harshavardhana** [comment]
If there is a strong customer requirement we may do it, but our point is to be opinionated. Every new option is a maintenance nightmare. MinIO is a big project which does quite a lot of things in a single binary. Every new option brings it's own tangential history. It may be one option for you but it's one of those 100 others for us which we need to keep track of.

Our usecases for NAS gateway, works fine with NetApp, Qumulo. We have production deployments on them. Our users happily use on GlusterFS as well.

So clearly Lustre implementation is the culprit here, and we shouldn't hide it. Enable it while using MinIO report to Lustre and let them fix it.

If we ever implement it, we will reopen. In the interest of issue management this will remain closed.

**Comment by thoth291** [comment]
Just to clarify it's not Lustre issue - we decided to switch off file locking as redundant operation which is not worth to support when you deal with Petabytes of data and hundreds of users accessing it simultaneously.
...Tried to symlink .minio.sys to NetApp, assuming that file locking is concentrated in that folder but got badly operating server. Webview is working, I can create buckets, but I can't upload any data or see actual folder structure (I have folder X - which I don't see in the list of buckets)...

```bash
API: SYSTEM()
Time: 10:03:02 CDT 03/27/2020
DeploymentID: 684478ab-1702-4313-b672-48760bd91355
Error: Rename across devices not allowed, please fix your backend configuration (/lustre/path/folder/TEST/.minio.sys/tmp/fb7a8a4a-ffc4-444d-8ab2-113aa4f5bdd2/6134ad28-8679-4385-80f7-f50ca03480a3)->(/lustre/path/folder/TEST/ttt/Screen Shot 2020-03-25 at 1.45.58 PM.png)
       4: cmd/fs-v1-helpers.go:413:cmd.fsRenameFile()
       3: cmd/fs-v1.go:987:cmd.(*FSObjects).putObject()
       2: cmd/fs-v1.go:874:cmd.(*FSObjects).PutObject()
       1: cmd/web-handlers.go:1123:cmd.(*webAPIHandlers).Upload()

API: SYSTEM()
Time: 10:03:02 CDT 03/27/2020
DeploymentID: 684478ab-1702-4313-b672-48760bd91355
Error: Rename across devices not allowed, please fix your backend configuration (/lustre/path/folder/TEST/.minio.sys/tmp/fb7a8a4a-ffc4-444d-8ab2-113aa4f5bdd2/6134ad28-8679-4385-80f7-f50ca03480a3)->(/lustre/path/folder/TEST/ttt/Screen Shot 2020-03-25 at 1.45.58 PM.png)
       3: cmd/web-handlers.go:2208:cmd.toWebAPIError()
       2: cmd/web-handlers.go:2218:cmd.writeWebErrorResponse()
       1: cmd/web-handlers.go:1125:cmd.(*webAPIHandlers).Upload()

API: SYSTEM()
Time: 10:03:02 CDT 03/27/2020
DeploymentID: 684478ab-1702-4313-b672-48760bd91355
Error: Rename across devices not allowed, please fix your backend configuration (/lustre/path/folder/TEST/.minio.sys/tmp/fb7a8a4a-ffc4-444d-8ab2-113aa4f5bdd2/6134ad28-8679-4385-80f7-f50ca03480a3)->(/lustre/path/folder/TEST/ttt/Screen Shot 2020-03-25 at 1.45.58 PM.png)
       5: cmd/api-errors.go:1801:cmd.toAPIErrorCode()
       4: cmd/api-errors.go:1826:cmd.toAPIError()
       3: cmd/web-handlers.go:2209:cmd.toWebAPIError()
       2: cmd/web-handlers.go:2218:cmd.writeWebErrorResponse()
       1: cmd/web-handlers.go:1125:cmd.(*webAPIHandlers).Upload()
```
My minio is of this version:
```bash
$ minio --version
minio version RELEASE.2020-03-19T21-49-00Z
```
I don't know if there anything else I can configure here -- assuming that "fix your backend configuration" from minio means anything -- or simply give-up.

Please advise.

**Comment by harshavardhana** [comment]
You cannot do this too, because .minio.sys and your actual object should be on the same mount.

If enabling file locking reduces performance on lustre,  it is a lustre issue that's a fact here. Honestly we cannot support what you want right now.
