### ISSUE TITLE
Add multi-language client and user role permissions

### ISSUE THREAD

**Issue by zhangleijie** [minio/minio#9215]
Dear everyone, I want known The minio project the road map of feature.
### suggest one.
I suggest add multi user and multi role permissions.  only one admin user can manage minio、
other user have delete permission function or update permission function or delete permission function. 
e.g  
user               role              permission
admin          admin           all(add、query、delete、update)
zhangsan     query           query
lisi                delete           delete
wangwu       add               add,update

### suggest two.
Add multi-language client 
eg.  php client、objectc client、switch client
sks

**Comment by kannappanr** [comment]
@zhangleijie We already support multi users with different policies. Please take a look at https://docs.minio.io/docs/minio-multi-user-quickstart-guide.html

Regarding SDKs for more languages, we do not have the bandwidth right now, to work on more SDKs. We might do them in the future, but do not have any new language in the pipeline.

**Comment by kannappanr** [comment]
Please feel free to reach out to us at https://slack.min.io for such questions in the future
