### ISSUE TITLE
Binding address to accept connection from other hosts

### ISSUE THREAD

**Issue by thoth291** [minio/minio#9216]
Here is my setup:
- Linux machine, with fixed IP, to serve minio
- Windows machine, with random IP, which can discover Linux machine by hostname
- IP ranges of Linux and Windows are different and all communication happens through VPN-ish hostname resolution.

In some other web servers I use I need only these to set up working connection to my Linux from my Windows:
- bind IP address at Linux server is set 0.0.0.0 (preferable)
- ssh tunneling - my normal workaround was not working.

**Comment by harshavardhana** [comment]
You can do `minio server --address 0.0.0.0:9000`

**Comment by thoth291** [comment]
Doesn't work - as I mentioned above (probably not very clear).

**Comment by harshavardhana** [comment]
> Doesn't work - as I mentioned above (probably not very clear).

Of course, it will that is the default `bind` it binds on all interfaces - it looks like some network issue on your end. If you need to access it over a private subnet you need to configure it in such a manner.

PS: Preferably use the issue template from next time to describe your issue in detail @thoth291 - we ask that to ensure that we don't ask repeated questions. For example, right now I do not know which version of MinIO are you talking about.

**Comment by thoth291** [comment]
>  it looks like some network issue on your end.
You were completely right - I did it 2 days in the row and it was not working - but now it's working. We have got new firewall rules and given all the "distancing" we are going through - it caused some restrictions to become more strict, thus my experiments were not working.
Thank you for your help!
And sorry for wasting your time.
