### ISSUE TITLE
Make MinIO response an accessible URL after upload successful

### ISSUE THREAD

**Issue by vinqin** [minio/minio#9217]
**Is your feature request related to a problem? Please describe.**
My web server uses presignedPostPolicy to generate a minio upload policy and delivers this policy to my web client which is going to upload some files. However minio server responses an inaccessible url after my web client upload successful by using the upload policy. It responses such xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<PostResponse>
    <Bucket>temp-bucket-1</Bucket>
    <Key>spiderweb/b71bd7ae4be8497090042cdb4b4970f9</Key>
    <ETag>&#34;af9025ba4f2581b4a948ae6f1910d385-1&#34;</ETag>
    <Location>http://172.18.0.2:9000/temp-bucket-1/testfile</Location>
</PostResponse>
```
The URL `http://172.18.0.2:9000/temp-bucket-1/testfile` can not be access directly.
when I use mc to show the policy of the file my web client upload, it prints such:
```bash
$ mc policy get myminio/temp-bucket-1/testfile
Access permission for `myminio/temp-bucket-1/testfile` is `none`
```

**Describe the solution you'd like**
MinIO server responses an accessible URL after upload successful.

**Describe alternatives you've considered**
I make the policy of bucket `temp-bucket-1` be `download` and all new files uploaded to this bucket can be downloaded after that.
```bash
$ mc policy set download myminio/temp-bucket-1
Access permission for `myminio/temp-bucket-1` is set to `download`

$ mc policy get myminio/temp-bucket-1
Access permission for `myminio/temp-bucket-1` is `download`
```

**Additional context**

**Comment by vadmeste** [comment]
@vinqin we need to follow the S3 specification here, we cannot do that.

**Comment by nitisht** [comment]
Closing this as working as expected @vinqin
