### ISSUE TITLE
[wont fix] Minio mounted with s3fs always displays same permissions to all files and fails to change them

### ISSUE THREAD

**Issue by d-goro** [minio/minio#9223]
When mounting s3fs on minio it always displays bucket contents with permissions 640 (disregarding what permissions were on original files). When I try to chmod - I get an error:
`chmod: Unable to change file mode on xxx.yyy: Input/output error`

## Expected Behavior
When I start minio server on some folder, mount s3fs on this folder and perform ls -la on mounted folder I should get a list of files with original permissions

## Current Behavior
ls -la on mounted folder display bucket content where all files have permission 640
![image](https://user-images.githubusercontent.com/35920455/77849674-1ce60c80-71d6-11ea-8e5d-0df9e62b1b00.png)

## Steps to Reproduce (for bugs)
1. create folder tmp, inside folder One and place some file to folder One
2. start minio server on folder tmp: `./minio server ~/tmp`
3. mount s3fs: `s3fs One ${HOME}/s3minio -o passwd_file=${HOME}/.passwd-s3fs,use_path_request_style,url=http://127.0.0.1:9000`
4. list folder content:  `ls -la ~/s3minio/`
5. try to chmod any file inside s3minio: `chmod 400 ~/s3minio/cert.pem`

Please, see screenshot below with full reproduction
![image](https://user-images.githubusercontent.com/35920455/77850338-7f410c00-71da-11ea-890c-b9aee30b258e.png)

Actually, chmod fails here: minio/cmd/fs-v1.go:470:cmd.(*FSObjects).CopyObject()
because fsMetaPath is equals to `/Users/dgoro/tmp/.minio.sys/buckets/One/cert.pem/fs.json`

Anyway, it's not chmod that bothers me, but file permissions that make impossible to use cert files in certain situations, like ssh

## Your Environment

* Version used (minio version): last docker minio image
* s3fs used: V1.85
* Environment name and version: MacOS 10.14.6, Ubuntu 18.04

**Comment by harshavardhana** [comment]
We may not be able to address issues related to s3fs due to our current priorities, it's a usecase we decided to not encourage or pursue.

Feel free to send a PR to fix this if you must use s3fs.

**Comment by d-goro** [comment]
> We may not be able to address issues related to s3fs due to our current priorities, it's a usecase we decided to not encourage or pursue.
> 
> Feel free to send a PR to fix this if you must use s3fs.

Could you please, at least, point out for me where in your source file permissions are defined? I am trying to find it for a few days already.

**Comment by harshavardhana** [comment]
> Could you please, at least, point out for me where in your source file permissions are defined? I am trying to find it for a few days already.

We do not store it anywhere, its s3fs which uses S3 API to store it perhaps in x-amz-meta form, you may need to look at what s3fs is trying to do which calls are failing. 

Use `mc admin trace` to figure this out.

**Comment by harshavardhana** [comment]
I shall close this issue on our end as this is not actionable to us.
