### ISSUE TITLE
Login wih OpenID button disappeared

### ISSUE THREAD

**Issue by jsmouret** [minio/minio#9224]
## Expected Behavior

On the login page, there should be the option to "Log in with OpenID" when OpenID is configured.

## Current Behavior

Since the latest release, the button disappeared.

## Possible Solution

Rollback to RELEASE.2020-03-19T21-49-00Z

## Steps to Reproduce (for bugs)

Just open the web page.

## Context

Login screen

## Regression

Yes, first seen on RELEASE.2020-03-25T07-03-04Z
Was ok on RELEASE.2020-03-19T21-49-00Z

## Your Environment

Environment variable used:
```
export MINIO_DOMAIN=example.com
export MINIO_ACCESS_KEY=abcdef
export MINIO_SECRET_KEY=abcdef
export MINIO_IDENTITY_OPENID_CONFIG_URL=https://openid/.well-known/openid-configuration
export MINIO_IDENTITY_OPENID_CLIENT_ID=abcdef
export MINIO_POLICY_OPA_URL=http://localhost:8181/v1/data/httpapi/authz/allow
```

Thank you :)

**Comment by kannappanr** [comment]
@jsmouret Thanks for reporting this issue. We will take a look and get back to you.

**Comment by plb538** [comment]
Hi @jsmouret, 

I was wondering if this issue was ever resolved for you? I am also seeing the same behavior with RELEASE.2020-09-10T22-02-45Z. We're going to roll-back to the version you proposed above, but I figured it wouldn't hurt to ask for an update.

Thanks!

Patrick

**Comment by jsmouret** [comment]
No, the issue has not been resolved.
I am looking to replace minio with other solutions as they don't seem to care about this use case...

**Comment by xli1026** [comment]
Hi @jsmouret,

Is the problem solved now? I've encounted the same problem.

**Comment by xli1026** [comment]
Hi @jsmouret ,

Is the problem solved now? I've encountered the same problem.

**Comment by jsmouret** [comment]
It was for while but now MINIO_POLICY_OPA_URL doesn't seem to be supported anymore.
