### ISSUE TITLE
ERROR Unable to initialize backend: found backend fs, expected xl

### ISSUE THREAD

**Issue by zhangleijie** [minio/minio#9225]
Hi , who known this problem.

I first start ./minio server /newdev5 after that , It's success .  I kill this 
nex start this  ./minio server /newdev5 /newdev6/ /newdev4 /newdev3
ERROR Unable to initialize backend: found backend fs, expected xl

**Comment by kannappanr** [comment]
@zhangleijie You cannot do this. You need to delete all the folders under `/newdev5` including hidden ones. Please reach out to us at https://slack.min.io for further such questions

**Comment by zhangleijie** [comment]
But , How standalone expands

**Comment by harshavardhana** [comment]
> But , How standalone expands

Standalone is not meant for expansion - deploy with erasure coding with get-go to expand. https://docs.minio.io/docs/distributed-minio-quickstart-guide.html
