### ISSUE TITLE
ERROR whenI Expanding existing distributed setup 

### ISSUE THREAD

**Issue by zhangpfly** [minio/minio#9226]
when I do as [https://docs.min.io/docs/distributed-minio-quickstart-guide.html](url) to Expanding existing distributed setup , report an error 
```
ERROR Unable to initialize backend: 1st disk is already being used in another erasure deployment. (Number of disks specified: 8 but the number of disks found in the 1st disk's format.json: 4)
```

first config is
```
export MINIO_ACCESS_KEY=admin
export MINIO_SECRET_KEY=admin
./minio server http://192.168.6.121/data3 http://192.168.6.121/data4 \
http://192.168.6.122/data3 http://192.168.6.122/data4
```

new config is
```
export MINIO_ACCESS_KEY=admin
export MINIO_SECRET_KEY=admin
./minio server http://192.168.6.121/data3 http://192.168.6.121/data4 \
http://192.168.6.122/data3 http://192.168.6.122/data4 \
http://192.168.6.123/data3 http://192.168.6.123/data4 \
http://192.168.6.124/data3 http://192.168.6.124/data4
```

when I stop the first 192.168.6.121-122 server and use new config start 192.168.6.121-124 server, then report this error:
```
ERROR Unable to initialize backend: 1st disk is already being used in another erasure deployment. (Number of disks specified: 8 but the number of disks found in the 1st disk's format.json: 4)
```

**Comment by harshavardhana** [comment]
You cannot expand in this manner @zhangpfly you can only expand in zones i.e using the ellipses syntax. 

More details here https://github.com/minio/minio/tree/master/docs/distributed#expanding-existing-distributed-setup

**Comment by zhangpfly** [comment]
OK. Thanks ! I change the command, It takes effect.

first command
```
minio server http://192.168.6.{121...122}/data{1...4}
```
expand existing distributed setup
```
minio server http://192.168.6.{121...122}/data{1...4} http://192.168.6.{123...124}/data{1...4}
```

**Comment by ZhangXuYangSKR** [comment]
Why do I still get an error setting like you
./minio server --address :9010 http://10.20.31.{100...101}/data/prod{1...4} http://10.20.31.{144...145}/data/prod{1...4}
Should all server scripts be changed like this？Or only new server changes?

**Comment by harshavardhana** [comment]
> Why do I still get an error setting like you
> ./minio server --address :9010 [http://10.20.31.{100...101}/data/prod{1...4}](http://10.20.31.%7B100...101%7D/data/prod%7B1...4%7D) [http://10.20.31.{144...145}/data/prod{1...4}](http://10.20.31.%7B144...145%7D/data/prod%7B1...4%7D)
> Should all server scripts be changed like this？Or only new server changes?

all of them @xiaoluji

**Comment by ZhangXuYangSKR** [comment]
> > Why do I still get an error setting like you
> > ./minio server --address :9010 [http://10.20.31.{100...101}/data/prod{1...4}](http://10.20.31.%7B100...101%7D/data/prod%7B1...4%7D) [http://10.20.31.{144...145}/data/prod{1...4}](http://10.20.31.%7B144...145%7D/data/prod%7B1...4%7D)
> > Should all server scripts be changed like this？Or only new server changes?
> 
> all of them @xiaoluji

i try it,but it doesn't work,server100and101 would report an error:Unable to initial backend:1st/2nd disk is already used in anthor erasure deployment.(xxxxxxx16,butxxxxxxxx8 format.json).Then quit...

**Comment by ZhangXuYangSKR** [comment]
> > Why do I still get an error setting like you
> > ./minio server --address :9010 [http://10.20.31.{100...101}/data/prod{1...4}](http://10.20.31.%7B100...101%7D/data/prod%7B1...4%7D) [http://10.20.31.{144...145}/data/prod{1...4}](http://10.20.31.%7B144...145%7D/data/prod%7B1...4%7D)
> > Should all server scripts be changed like this？Or only new server changes?
> 
> all of them @xiaoluji

Is it because of version of minio ?or it is supported from beginning,1st version

**Comment by sindevil** [comment]
> > > Why do I still get an error setting like you
> > > ./minio server --address :9010 [http://10.20.31.{100...101}/data/prod{1...4}](http://10.20.31.%7B100...101%7D/data/prod%7B1...4%7D) [http://10.20.31.{144...145}/data/prod{1...4}](http://10.20.31.%7B144...145%7D/data/prod%7B1...4%7D)
> > > Should all server scripts be changed like this？Or only new server changes?
> > 
> > 
> > all of them @xiaoluji
> 
> Is it because of version of minio ?or it is supported from beginning,1st version

i got the same problem,did you solved it ? how it works

**Comment by SpootDev** [comment]
If you're reusing disks from another deployment, reformat the disk it's complaining about.

**Comment by checkHup** [comment]
excuse me
When I expand one server, there is no problem, but there will be an error after two servers
The details are as follows：
   API: SYSTEM()
Time: 16:15:58 CST 11/17/2021
Error: http://192.168.11.237:9000/home/minio/data1 as has incorrect configuration: Expected endpoint http://192.168.10.136/home/minio/data1, seen http://192.168.10.136:9000/home/minio/data1 (*fmt.wrapError)
       1: cmd/server-main.go:533:cmd.serverMain()

My script is as follows
#!/bin/bash
export MINIO_ROOT_USER=minio
export MINIO_ROOT_PASSWORD=miniostorage

/home/minio/minio server --console-address ":9001" --config-dir /etc/minio \
--address "192.168.10.136:9000" \
			   http://192.168.10.{136...136}/home/minio/data{1...4}\
			   http://192.168.11.{237...237}/home/minio/data{1...4}\
			   http://192.168.10.{111...111}/home/minio/data{1...8}\

**Comment by harshavardhana** [comment]
> [http://192.168.10.{136...136}/home/minio/data{1...4}\](http://192.168.10.%7B136...136%7D/home/minio/data%7B1...4%7D%5C)
> [http://192.168.11.{237...237}/home/minio/data{1...4}\](http://192.168.11.%7B237...237%7D/home/minio/data%7B1...4%7D%5C)
> [http://192.168.10.{111...111}/home/minio/data{1...8}\](http://192.168.10.%7B111...111%7D/home/minio/data%7B1...8%7D%5C)

This is the poorest way to expand - you are just expanding single node instances into multiple nodes - with no HA nothing whatsoever. This is going to be a broken deployment. 

Read the requirements on how to expand and how to have a proper setup https://docs.min.io/docs/distributed-minio-quickstart-guide.html

Also please do not comment on old issues @checkHup it is very distracting.
