### ISSUE TITLE
[resolved] Kafka Topics has been created on Confluent but there is no update on Minio Bucket

### ISSUE THREAD

**Issue by haikalshiddiq** [minio/minio#9227]
Based on guide on this site : https://developer.sh/posts/configure-minio-kafka that there is no error on Kafka or Minio, but strangely there is no update on Minio Bucket if Kafka Topics has been created

## Expected Behavior

Minio Bucket should be updated if Kafka Topics has been created.

## Current Behavior

Minio Bucket not updated using command "./mc ls -r myminio" although Kafka Topics has been started.
![image](https://user-images.githubusercontent.com/7146943/77875601-bd8e0800-727a-11ea-889f-318a04b9aea9.png)

Kafka Topics process 
![image](https://user-images.githubusercontent.com/7146943/77875636-e31b1180-727a-11ea-9d8b-894d3addc045.png)

Also on verbose logging Minio, here is for the result
![image](https://user-images.githubusercontent.com/7146943/77875897-b5829800-727b-11ea-9487-cabd46910667.png)

## Possible Solution

I don't know since guide on google search is very limited.

## Steps to Reproduce (for bugs)

i'm still stuck, could you help me to fix this problem ?

## Context

1. Change value on Kafka to store the Topics at 1 times with 3 Topics.
2. Make sure AWS_ACCESS_KEY_ID and AWS_SCRET_ACCESS_KEY already created on credentials Kafka machine, same with MINIO_ACCESS_KEY and MINIO_SECRET_KEY.
3. Ensure region name is same on Minio using command 
./mc admin config set myminio region name=us-east-1
export MINIO_REGION_NAME="us-east-1
./admin service restart myminio
![image](https://user-images.githubusercontent.com/7146943/77876386-fe871c00-727c-11ea-9717-51349aa1da31.png)
4. And it's for bucket which created before
![image](https://user-images.githubusercontent.com/7146943/77876471-427a2100-727d-11ea-99db-a1ee857947e4.png)

## Your Environment

* Version used (`minio version`):
mc version RELEASE.2020-03-14T01-23-37Z
* Environment name and version (e.g. nginx 1.9.1):
Confluent 5.4.1
* Server type and version: Virtualize by VMware vSphere 6.7.
* Operating System and version (`uname -a`): Linux minio.all.data 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project: here is for step on document https://drive.google.com/file/d/1IVmV1QuEGOtYAsMGFXNYtbRGxxA42Uc1/view?usp=sharing

**Comment by kannappanr** [comment]
@haikalshiddiq Did you get a chance to look at https://blog.minio.io/journaling-kafka-messages-with-s3-connector-and-minio-83651a51045d

**Comment by harshavardhana** [comment]
@haikalshiddiq `mc ls` won't trigger any events are triggered for 

- GetObject/HeadObject
- Put operations
- Delete operations

In your setup after you have enabled Kafka target you need to make sure to enable it for your bucket https://docs.minio.io/docs/minio-bucket-notification-guide.html#apache-kafka

Once enabled using `mc` you can now either upload a file or download a file from the configured bucket you should see Kafka notifications go through.

AFAICS this is a setup issue and you have not followed the document correctly. 

PS: https://developer.sh/posts/configure-minio-kafka this guide is wrong it misses an important step. Follow our official documentation when in doubt.

**Comment by haikalshiddiq** [comment]
well noted, will try later. Thanks all for your help :)

**Comment by haikalshiddiq** [comment]
> @haikalshiddiq Did you get a chance to look at https://blog.minio.io/journaling-kafka-messages-with-s3-connector-and-minio-83651a51045d

i have following this guide, but there is no clear step on setting environment variable on Kafka Server.

**Comment by harshavardhana** [comment]
> i have following this guide, but there is no clear step on setting environment variable on Kafka Server.

That is an old blog, check our latest documentation always @haikalshiddiq
