### ISSUE TITLE
[faq] Does MINIO has any method of dynamic adding servers to existing distributed cluster? 

### ISSUE THREAD

**Issue by zcgecho** [minio/minio#9228]
actually minio is lightable and easy to use,but there was not a good thing that it is hard to extend storay ability if i want to add a new storage node.
My question is,
Does MINIO has any method of dynamic adding servers to existing distrubited cluster? if not ,does it has any plan of realizing this feature?  
thanks.

**Comment by nitisht** [comment]
@zcgecho MinIO does support dynamically adding new servers to a distributed cluster, please take a look at https://github.com/minio/minio/tree/master/docs/distributed#expanding-existing-distributed-setup

Closing this as working as expected. Please join us on Slack (https://slack.min.io) for more such questions

**Comment by TreeKat71** [comment]
Hi @nitisht 
I also face the same problem. And I am not sure the document is clear.
Currently, I run minio cluster on k8s and deploy with helm chart.
As I read from the document, there are two ways to expand existing cluster:
1. the [link](https://github.com/minio/minio/tree/master/docs/distributed#expanding-existing-distributed-setup) you mention 
2. Federation
If there is anything wrong, please let me know.

I would like to try the option one, but I don't know how to scale out in helm chart.
Two problems I am facing are
1. add zones are not allowed in helm chart, at least it doesn't work for me
2. If it does work, it seems it is not rolling update and there must be a downtime

Want to know if I understand it correctly, thanks!

**Comment by harshavardhana** [comment]
> Hi @nitisht
> I also face the same problem. And I am not sure the document is clear.
> Currently, I run minio cluster on k8s and deploy with helm chart.
> As I read from the document, there are two ways to expand existing cluster:
> 
> 1. the [link](https://github.com/minio/minio/tree/master/docs/distributed#expanding-existing-distributed-setup) you mention
> 2. Federation
>    If there is anything wrong, please let me know.
> 
> I would like to try the option one, but I don't know how to scale out in helm chart.
> Two problems I am facing are
> 
> 1. add zones are not allowed in helm chart, at least it doesn't work for me
> 2. If it does work, it seems it is not rolling update and there must be a downtime
> 
> Want to know if I understand it correctly, thanks!

Correcting @nitisht MinIO doesn't support dynamically adding servers, but instead, you simply add a new command-line zone and do a rolling restart.

**Comment by TreeKat71** [comment]
Hi harshavardhana 
Thanks your reply. 
So the truth is we can't scale minio nodes like scaling pods on k8s. But we can scale out cluster by adding zones and achieve zero-downtime by rolling update?
Do I understand it correctly?
Thanks!

**Comment by harshavardhana** [comment]
> So the truth is we can't scale minio nodes like scaling pods on k8s. But we can scale out cluster by adding zones and achieve zero-downtime by rolling update?

k8s scaling pods has nothing to do with MinIO scaling, MinIO scales in its own way its documented on how it can be done

https://github.com/minio/minio-operator/blob/master/docs/operator-fields.md look at what we currently support in minio-operator 

spec.zones | Set the number of servers per MinIO Zone. Add a new Zone field to expand the MinIO cluster. Read more on MinIO zones here.
-- | --

**Comment by TreeKat71** [comment]
Hi harshavardhana,
I know Minio offer minio-operator to manage and scale cluster in a easier way. 
Due to our production k8s version, I am not able to use this feature. Instead, I use helm chart to deploy minio cluster. 
The issue I am facing is, I increase the "zones" values in helm chart, and use "helm upgrade" to scale out my minio cluster. Is it the way you expect? If it is, I am not able to do so. 

For example, I use chart under stable/minio.
I expand a cluster with 4 nodes to 8 nodes by increasing the “zones” in values.yaml from 1 to 2.
After I run "helm upgrade", it doesn't work. The number of pods do increase, but node 4~7 log show “Waiting for the first server to format the disks.”
Thanks in advance.

**Comment by TreeKat71** [comment]
Hi All,
I have updated the helm chart, and it seems that I use an older version.
The issue has completely solved, I can use "helm upgrade" to scale out the minio cluster by increasing the number of "zones". And the k8s cluster will do the rolling update, the service will be still available.

**Comment by edergillian** [comment]
@TreeKat71, can you please share your K8s and Helm chart versions?
I'm facing exactly the same issue (adding a 2nd zone with 4 servers each, helm upgrade through Rancher Apps, nodes 4 to 7 show "Waiting for first server to format the disks") and I'm using the latest chart version, which is 5.0.31; k8s cluster version is 1.18.
Thanks in advance!

**Comment by TreeKat71** [comment]
I just used the latest helm chart and I also updated the values.yaml (newer docker image).
Try to delete the old pvc and pv if you use storage class with provisioner.
