### ISSUE TITLE
Minio gateway oss compat

### ISSUE THREAD

**Issue by majorovms** [minio/minio#9229]
Minio gateway for OSS doesn't support the **--compat** option or it doesn't take any effect. As a result aws sdk v2 throws the exception:
```
java.lang.IllegalArgumentException: Invalid base 16 character: '-'

	at software.amazon.awssdk.utils.internal.Base16Codec.pos(Base16Codec.java:80)
	at software.amazon.awssdk.utils.internal.Base16Codec.decode(Base16Codec.java:66)
	at software.amazon.awssdk.utils.internal.Base16Lower.decode(Base16Lower.java:65)
	at software.amazon.awssdk.services.s3.checksums.ChecksumsEnabledValidator.validatePutObjectChecksum(ChecksumsEnabledValidator.java:144)
```

The reason is redundant "-1" suffix in the Etag value. For example:
Aws sdk expects `Etag: 1D4690BA4BC0FC9D867E990630876A34`
But gets `Etag: 1D4690BA4BC0FC9D867E990630876A34-1`

I found issues:
https://github.com/minio/minio/issues/7642
https://github.com/minio/minio/issues/7756
and tried to enable compat mode but it didn't work out.
What are plans for **compat** option for OSS gateway? It would be great if it is supported.

## Steps to reproduce:

1. Start gateway `MINIO_ACCESS_KEY=*** MINIO_SECRET_KEY=*** minio --compat gateway oss https://oss-cn-hongkong.aliyuncs.com --address 127.0.0.1:9090`
2. Run Java sample
```
        final S3Client s3Client = S3Client.builder()
                .endpointOverride(ossEndpoint)
                .region(Region.of(region))
                .credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create(accessKey, secretKey)))
                .build();
        final PutObjectRequest putRequest = PutObjectRequest.builder().bucket(bucket).key(key).build();
        RequestBody body = RequestBody.fromString("");
        s3Client.putObject(putRequest, body);
```

## Environment
MacOS Catalina
minio version RELEASE.2020-03-25T07-03-04Z
aws sdk 2.11.4

**Comment by kannappanr** [comment]
@majorovms We will remove the `-1` appended to the etag
