### ISSUE TITLE
Can't set lock or retention on docker installed minio

### ISSUE THREAD

**Issue by roycec** [minio/minio#9236]
I set up an S3 storage via docker/docker-compose. Everything works so far, data ist stored in the correct bucket/directory. Now I tried to set a policy on this storage (either a lock on the bucket or a retention policy on the files). I use the mc client binary for that, configuring and accessing the storage backend also works. But trying to set the policy ends up with errors like

`mc: <ERROR> Cannot enable object lock configuration on the specified bucket. Object Lock configuration cannot be enabled on existing buckets.`

I also deleted an existing bucket and tried to set the policy/lock on an empty one, but with the same result. In the case of the compliance policy on single files

`Cannot set object retention on /backup/myfolder/2020-03-28T04:27:45Z_backup.zip .Bucket is missing ObjectLockConfiguration`

Should the mc binary work with the docker setup? According to issue [#5184](https://github.com/minio/minio/issues/5184), I think it should. But what I am doing wrong here?

## Expected Behavior
It should be possible to use the minio client to set locks/policies on (existing?) buckets or files.

## Current Behavior
Setting these policies is not possible (see error messages above)

## Steps to Reproduce (for bugs)
1. Set up minio (single server) with docker-compose
2. Create bucket via UI or minio client
3. Set retention policy/lock on bucket

## Context
Using s3/minio for etcd snapshots. RKE in this case should handle the retention and delete files after a configured period. Due to a bug in RKE (https://github.com/rancher/rancher/issues/24544) I tried to solve this via Minio retention in the meanwhile.

## Regression
unknown

## Your Environment

* Version used (`minio version`): RELEASE.2020-03-09T18-26-53Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: Single server install
* Operating System and version (`uname -a`):  Linux ........ 3.10.0-1062.el7.x86_64 #1 SMP Thu Jul 18 20:25:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by harshavardhana** [comment]
> It should be possible to use the minio client to set locks/policies on (existing?) buckets or files.

Existing buckets it's not possible as per AWS S3 API @roycec - so it is not possible to set this on existing buckets.

**Comment by roycec** [comment]
How is it then possible in general?

**Comment by harshavardhana** [comment]
> How is it then possible in general?

All documented here https://github.com/minio/minio/tree/master/docs/retention

**Comment by kannappanr** [comment]
@royec Bucket should be created with lock enabled

```
mc mb play/test4 -l
```

Closing this issue as answered. Please feel free to reach out to us at https://slack.min.io
