### ISSUE TITLE
Unable to create bucket with mirror, but bucket already created - Client error

### ISSUE THREAD

**Issue by Neurozone** [minio/minio#9237]
I'm trying to mirror a local folder to my personnal minio instance (by the way great tool)
but mc mirror output an error and with the SAME configuration mc cp works ???

## Expected Behavior
/opt/mc mirror /data/backup/mysql backup.neurozone.fr/neurozone
 -> mirroring folder to bucket

"api": "S3v4",

## Current Behavior
/opt/mc mirror /data/backup/mysql backup.xxx.fr/yyy
mc: <ERROR> Unable to create bucket at `backup.xxx.fr/yyy`. The authorization header is malformed; the region is wrong; expecting 'us-east-1'.

but cp is working ???

/opt/mc cp /data/backup/mysql backup.xxx.fr/yyy--recursive
...ckup/mysql/20200328/cloud.sql.gz:  7.17 GiB / 14.47 GiB 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`): minio version RELEASE.2020-03-25T07-03-04Z
* Environment name and version (e.g. nginx 1.9.1): nginx 1.17
* Server type and version: Bare metal with CentOS 8
* Operating System and version (`uname -a`): 4.18.0-147.5.1.el8_1.x86_64
* Link to your project:

**Comment by vadmeste** [comment]
@Neurozone before you run mirror command, does the bucket `yyy` already exist ?

**Comment by Neurozone** [comment]
> 
> 
> @Neurozone before you run mirror command, does the bucket `yyy` already exist ?

Yes, I created it, with the good rights, because cp doesn't create the buckets ^^

that's why it's really strange.

**Comment by vadmeste** [comment]
> Yes, I created it, with the good rights, because cp doesn't create the buckets ^^
> 
> that's why is really strange.

mirror has --region flag. If you set the region correctly, then the issue will disappear, so that workaround should work.

However, if the bucket was already present before you invoke the mirror command, then this is also an mc that needs to be fixed

**Comment by Neurozone** [comment]
Tried with region attribute:

`/opt/mc mirror --region backup-neurozone-de /etc/nginx backup.xxx.fr/yyy/mid.xxx.fr
mc: <ERROR> Unable to create bucket at `backup.xxx.fr/yyy/mid.xxx.fr`. Buckets or prefixes can only be created with `/` suffix.`

**Comment by Neurozone** [comment]
Maybe I'm using it in a wrong way ?

**Comment by Neurozone** [comment]
Ok, it seems I was using it wrong:

I was mirroring into an already created bucket yyy with a subfolder mid.xxx.fr
It seems when you do that you need to put a trailing slash 
I'm sorry for the report, it was a PEBKAC

/opt/mc mirror --region backup-neurozone-de /etc/nginx backup.xxx.fr/yyy/mid.xxx.fr/
/etc/nginx/win-utf:               243.98 KiB / 243.98 KiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 49.02 KiB/s 4s

**Comment by harshavardhana** [comment]
> I'm sorry for the report, it was a PEBKAC

Closing this issue.
