### ISSUE TITLE
lifecycle does not work

### ISSUE THREAD

**Issue by simbatsad** [minio/minio#9240]
I have set minio with local folder and added a lifecycle Json with expiration of 1 day.
after a day nothing was deleted.

## Expected Behavior
object are deleted when expired

## Current Behavior
objects are not deleted

## Steps to Reproduce (for bugs)
minio setup:
sudo docker run -p 9000:9000 --name minio1 \
  -e "MINIO_ACCESS_KEY=aa" \
  -e "MINIO_SECRET_KEY=bb" \
  -v /mnt/data:/data \
  minio/minio server /data

command used:
aws s3api put-bucket-lifecycle-configuration --bucket delivery --endpoint-url http://minioaddress:9000 --lifecycle-configuration file://c:/temp/retention.json

retention.json used:
{
    "Rules": [
        {
            "Expiration": {
                "Days": 1
            },
	    "Filter": {
                "Prefix": "tracking1/"
            },
            "ID": "Delete temporary uploads",
            "Status": "Enabled"
        }
    ]
}

objects under "delivery" bucket are 
tracking1/logx
tracking1/logy

wait 1 day (and more) and objects are still there.

## Your Environment
ubuntu
* Version used (2020-03-25T07:03:04Z):

**Comment by vadmeste** [comment]
@simbatsad you need to expect that lifecycle rules are evaluated against objects once 24 hours (+1 hour sometimes). Also, when you start your server, you still need to wait another 24 hours until lifecycle subsystem works.

Could you wait for another day to check ?

**Comment by simbatsad** [comment]
@vadmeste you were right it was deleted a day after! thanks!
Before closing the issue what would be needed to have the deletion for the entire bucket (without any filtering)?  just remove the "Filter" part from the JSON or something else?

**Comment by vadmeste** [comment]
> what would be needed to have the deletion for the entire bucket (without any filtering)? just remove the "Filter" part from the JSON or something else?

yes, removing Filter or setting it to empty means remove all objects in that bucket

**Comment by simbatsad** [comment]
thanks! closing the issue
