### ISSUE TITLE
[resolved] Pre-defined Azure blocks size for multipart upload too small

### ISSUE THREAD

**Issue by boazhuisman** [minio/minio#9245]
We encountered an error for chunk uploads to Azure using MinIO. When doing a multipart upload of chunks of 5 MB, MinIO received the following error from Azure: 

_The uncommitted block count cannot exceed the maximum limit of 100,000 blocks._

The error occurred after upgrading MinIO. 

## Expected Behavior
MinIO is able to upload a large blob larger than 25 GiB in multiple blocks to Azure with a reasonable low number of blocks in order to perform the upload in a timely fashion. 

## Current Behavior
We have a suspicion this may be because of the block size for chunked uploads to Azure, which has recently been limited (#8537) to 0.25 MiB. Unfortunately this change could have resulted in a maximum object size of 25 GiB for chunked uploads and also requires many more individual HTTP request, slowing down uploads considerably. 

![image](https://user-images.githubusercontent.com/15123825/78107106-29947b80-73f5-11ea-80c5-d7836246543f.png)
(minio/minio/cmd/gateway/azure/gateway-azure.go)

The Azure documentation [points out](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs) that a blob can be uploaded in blocks with a maximum of 100,000 uncommitted blocks. With the current default block (i.e. chunk) size, this results in a size limit of 100,000 * 0.25 MiB = 25 GiB. Uploading 10.000 blocks of 5 MiB to a MinIO configured to use an Azure object store currently fails.

## Possible Solution
Ideally, the block size would be configurable such that we can set our own block size. 

## Steps to Reproduce (for bugs)
1. Perform a Multipart upload with 10.000 blocks of 5MiB to MinIO configured to store this in a Azure blob store.

## Your Environment
* We are using the image: minio/minio:RELEASE.2019-10-12T01-39-57Z

**Comment by harshavardhana** [comment]
Feel free to send a PR @boazhuisman

**Comment by DennisRutjes** [comment]
It has worked seems to mee its a regression bug?

**Comment by vadmeste** [comment]
@boazhuisman I guess a workaround here is to use the multipart upload, a single PUT in S3 does not allow more than 5 GB

**Comment by boazhuisman** [comment]
Dear @vadmeste, @harshavardhana, thanks for the replies. We are already using minio for a multipart upload of a 37 GB file. We're uploading chunks of 5 MB to minio. With `mc admin trace `, we can see we're using the function PutObjectPart to upload the chunks. 

Minio then forwards the uploads to azure, using the azure gateway. After exactly 5000 uploads, we get the following error:

```
API: PutObjectPart(bucket=public, object=XX/7bf00800-fd31-46a9-831d-f23f2c4c81fb/bgt-citygml-nl.zip)
 Time: 13:24:29 UTC 04/06/2020
 DeploymentID: e73dcfe3-4cd5-4ad6-8057-d610ee25855d
 RequestID: 16033DD2C08F07E0
 RemoteHost: 
 UserAgent: aws-sdk-java/1.11.466 Linux/4.15.0-1064-azure OpenJDK_64-Bit_Server_VM/11.0.6+10-LTS java/11.0.6 kotlin/1.3.0
 Error: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.8.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=BlockCountExceedsLimit) =====
Description=The uncommitted block count cannot exceed the maximum limit of 100,000 blocks.
RequestId:398837a7-301e-00d5-6216-0c5dda000000
Time:2020-04-06T13:24:29.3525471Z, Details: 
   Code: BlockCountExceedsLimit
   PUT https://processingartifacts.blob.core.windows.net/public/XX/7bf00800-fd31-46a9-831d-f23f2c4c81fb/bgt-citygml-nl.zip?blockid=NzQ3MGY1NjUtYmUyNC00MTJkLTgxYjctNTFmOWRjNDAyMDlj&comp=block&timeout=16
   Authorization: REDACTED
   Content-Length: [262144]
   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-04-04T05:39:31Z]
   X-Ms-Client-Request-Id: [21545d95-3560-4c55-579b-5ffdbafdd54f]
   X-Ms-Date: [Mon, 06 Apr 2020 13:24:29 GMT]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 409 The uncommitted block count cannot exceed the maximum limit of 100,000 blocks.
   Content-Length: [269]
   Content-Type: [application/xml]
   Date: [Mon, 06 Apr 2020 13:24:29 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [BlockCountExceedsLimit]
   X-Ms-Request-Id: [398837a7-301e-00d5-6216-0c5dda000000]
   X-Ms-Version: [2018-11-09]        6: github.com/minio/minio@/cmd/api-errors.go:1807:cmd.toAPIErrorCode()
        5: github.com/minio/minio@/cmd/api-errors.go:1832:cmd.toAPIError()
        4: github.com/minio/minio@/cmd/object-handlers.go:2121:cmd.objectAPIHandlers.PutObjectPartHandler()
        3: github.com/minio/minio@/cmd/http-tracer.go:127:cmd.Trace()
        2: github.com/minio/minio@/cmd/handler-utils.go:357:cmd.httpTraceHdrs.func1()
        1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```

This corresponds with the 100,000 uncommited blocks upload limit. When looking at the code in minio/cmd/gateway/azure/gateway-azure.PutObjectPart(), we see that each 5 MB upload is split up in chunks of 0.25 mb (resulting in 20 blocks) which are then uploaded to Azure. The 20 blocks * 5000 uploads = 100.000 uncommited blocks. Microsoft allows uploads of blocks up to 100 MB and since we're running our apps in Azure, upload speed will not be an issue for us.

This puts a limit of 25 GB on the multipart upload size and prevents us from upgrading to the newest version of minio. 

I am working on a PR.

**Comment by boazhuisman** [comment]
Created a PR #9292! I hope you guys can find time to review! We would really like to upgrade our MinIO version to the latest version. 

Thanks in advance!
