### ISSUE TITLE
After upgrade to Version: 2020-03-25T07:03:04Z the report from mc admin info doesn't match anymore what we use to have

### ISSUE THREAD

**Issue by titansmc** [minio/minio#9247]
After upgrade to Version: 2020-03-25T07:03:04Z the report from mc admin info doesn't match anymore what we use to have. 
Before it use to report:
```
xemacs@alatxa:~/bin/guira-3.2.1$ mc admin info embl
●  ops-object01.domain.de:443
   Uptime: 11 seconds 
   Version: 2020-03-25T07:03:04Z
   Network: 2/2 OK 
   Drives: 88/96 OK 

●  ops-object02.domain.de:443
   Uptime: 10 minutes 
   Version: 2020-01-25T02:50:51Z
   Network: 2/2 OK 
   Drives: 96/96 OK 

2.8 TiB Used, 15 Buckets, 4,275,331 Objects
184 drives online, 8 drives offline

```
And now  it reports:
```
xemacs@alatxa:~/bin/guira-3.2.1$ mc --version
mc version RELEASE.2020-03-14T01-23-37Z
xemacs@alatxa:~/bin/guira-3.2.1$ mc admin info domain
●  ops-object01.domain.de:443
   Uptime: 3 minutes 
   Version: 2020-03-25T07:03:04Z
   Network: 2/2 OK 
   Drives: 96/96 OK 

●  ops-object02.domain.de:443
   Uptime: 3 minutes 
   Version: 2020-03-25T07:03:04Z
   Network: 2/2 OK 
   Drives: 96/96 OK 

1.0 TiB Used, 14 Buckets, 72,192 Objects
192 drives online, 0 drives offline

```

## Expected Behavior
Be consistent also with the web interface that reports :
![image](https://user-images.githubusercontent.com/8192096/78133355-91ab8780-741e-11ea-9300-194926532eb0.png)

## Current Behavior
missmatch 

## Steps to Reproduce (for bugs)

Upgrade server to the latest available and client to the latest available too (note they are different)

## Context
I am not sure if the data got lost during the upgrade or it is just wrong reporting....

## Your Environment
running behind HAProxy over docker  19.03

**Comment by klauspost** [comment]
Disk usage crawling was changed. It will require a full crawl until your data is updated. While it is crawling it will add buckets as they are finished.
