### ISSUE TITLE
Minio with Keycloak in Kubernetes environment - CORS or AssumeRole Error

### ISSUE THREAD

**Issue by KadKla** [minio/minio#9256]
We try to get Minio working with Keycloak via OIDC. We use Traefik a reverse proxy. When running Minio on NodePort (access with: http://<host>:9000) everything works fine. We start the Minio page, we are redirected to Keycloak, we log in and we are logged in in Minio and can see the buckets. However, when accessing Minio via the url which runs on https://<host>/minio we are also redirected to Keycloak, we log in and we are back on the Minio page, but not log in. Instead the cliend-id page is open. Entering the client id does not help. Taking a look into the logs of the minio docker container we get:

`UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
Error: expected element type <AssumeRoleWithWebIdentityResponse> but have 
      23: cmd/api-errors.go:1788:cmd.toAPIErrorCode()
      22: cmd/api-errors.go:1813:cmd.toAPIError()
      21: cmd/web-handlers.go:2209:cmd.toWebAPIError()
      20: cmd/web-handlers.go:2079:cmd.toJSONError()
      19: cmd/web-handlers.go:2068:cmd.(*webAPIHandlers).LoginSTS()
      18: reflect/value.go:460:reflect.Value.call()
      17: reflect/value.go:321:reflect.Value.Call()
      16: /q/.q/sources/gopath/pkg/mod/github.com/gorilla/rpc@v1.2.0/v2/server.go:220:v2.(*Server).ServeHTTP()
      15: /q/.q/sources/gopath/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212:mux.(*Router).ServeHTTP()
      14: cmd/generic-handlers.go:748:cmd.customHeaderHandler.ServeHTTP()
      13: cmd/generic-handlers.go:763:cmd.securityHeaderHandler.ServeHTTP()
      12: cmd/generic-handlers.go:624:cmd.bucketForwardingHandler.ServeHTTP()
      11: cmd/generic-handlers.go:608:cmd.requestValidityHandler.ServeHTTP()
      10: cmd/generic-handlers.go:544:cmd.httpStatsHandler.ServeHTTP()
       9: cmd/generic-handlers.go:68:cmd.requestSizeLimitHandler.ServeHTTP()
       8: cmd/generic-handlers.go:93:cmd.requestHeaderSizeLimitHandler.ServeHTTP()
       7: cmd/crossdomain-xml-handler.go:51:cmd.crossDomainPolicy.ServeHTTP()
       6: cmd/generic-handlers.go:247:cmd.redirectHandler.ServeHTTP()
       5: cmd/generic-handlers.go:315:cmd.minioReservedBucketHandler.ServeHTTP()
       4: cmd/generic-handlers.go:274:cmd.cacheControlHandler.ServeHTTP()
       3: cmd/generic-handlers.go:385:cmd.timeValidityHandler.ServeHTTP()
       2: /q/.q/sources/gopath/pkg/mod/github.com/rs/cors@v1.6.0/cors.go:207:cors.(*Cors).Handler.func1()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()`

In the Browser console log we get:

`Error: We encountered an internal error, please try again.`

Taking a look to the cookies we find a AUTH_SESSION_ID, a KEYCLOAK_IDENTITY and KEYCLOAK_SESSION

Logging in with the admin credentials works as expected also on https

## Expected Behavior
We should be redirected to the view of the buckets

## Current Behavior
Stuck to https://<host>/minio/login/openid+session_state=...

## Possible Solution
Maybe a CORS error or do we miss something with the AssumeRole 

## Steps to Reproduce (for bugs)
Creating the same setup with Kubernetes, Traefik and Keycloak.

## Context
We need to run Minio on a subpath and behind a reverse proxy.

## Regression
No

## Your Environment
minio version RELEASE.2020-03-14T02-21-58Z in Docker
mc version RELEASE.2020-03-14T01-23-37Z in Docker
traefik:v1.7.19-alpine Docker
FROM jboss/keycloak:7.0.1 Docker

**Comment by phonique** [comment]
Same issue, except with nginx (1.15.6) as ingress on rancher 2.2.8.
minio RELEASE.2020-06-14T18-32-17Z
mc RELEASE.2020-06-16T19-24-41Z

**Comment by AH012** [comment]
Same issue. Any news on how to fix it ?

**Comment by Weissger** [comment]
Same issue using dex. Error in console:
`Uncaught (in promise) Error: We encountered an internal error, please try again.: cause(name claim missing from the JWT token, credentials will not be generated)` Even tough the JWT in `.../minio/login/openid#access_token=eyJ...` contains a name field.

Edit:
In my case the issue was solved setting up the right policies via `mc admin`. The error message seems to wrongly state that the token is missing a field, while it should be about no matching policies.

**Comment by klauskades** [comment]
So I am not 100% sure if this fixes the error or not, but we are able to use Keycloak with Minio by overwriting the auth endpoint manually in the jwt.go file (https://github.com/minio/minio/blob/master/cmd/config/identity/openid/jwt.go). We overwrite the AuthEndpoint before the return statement in line 277 manually with `d.AuthEndpoint = env.Get(<your-auth-endpoint>, d.AuthEndpoint)`  with `<your-auth-endpoint>=https://<hostname>/auth/realms/<realm>/protocol/openid-connect/auth`. We then build the docker container with this change cf. https://github.com/kaapana/kaapana/tree/425e8415cfe7fe9abf6da25133c4d3b16c68ea6f/services/store/minio/docker Maybe this helps!
