### ISSUE TITLE
Rolling upgrade to 2020-04-02T21-34-49Z from previous fails

### ISSUE THREAD

**Issue by solsson** [minio/minio#9257]
The new version gets 404 on format.json when starting up in a cluster running previous version.

## Expected Behavior

Bumping the release version to next bug fix release, that doesn't recommend against rolling upgrades in release notes, should upgrade the Minio cluster.

## Current Behavior

The following rolling upgrade fails in Kubernetes

```
-        image: minio/minio:RELEASE.2020-03-25T07-03-04Z@sha256:5e96d539583afd9a7da14e0d9bf2360d316e4e8219659d82b8ef106a9d75b16c
+        image: minio/minio:RELEASE.2020-04-02T21-34-49Z@sha256:8786346b1e200647c34f4a614f3186c9374d24fbfe309c5d6ffe3efb06e68392
```

The pod that restarts first fails to go online, with the following error listed for all pods

`Unable to read 'format.json' from http://minio-6.minio-hl-svc.blobs.svc.cluster.local:9000/export: 404 page not found`

I've verified name resolution, and with `kubectl rollout undo` the same pod goes up properly.

## Steps to Reproduce (for bugs)
1. Set up a minio statefulset for distributed mode with version 2020-03-25T07-03-04Z
2. Set image to version 2020-04-02T21-34-49Z
3. Log the first rotated pod

## Regression
Yes. Previous upgrade worked.

## Your Environment
* Version used (`minio version`): 2020-04-02T21-34-49Z
* Server type and version: Kubernetes 1.15.9
* Operating System and version (`uname -a`): Linux

**Comment by harshavardhana** [comment]
Rolling upgrade is not supported for this release @solsson - we will update the release docs.

**Comment by harshavardhana** [comment]
> Rolling upgrade is not supported for this release @solsson - we will update the release docs.

@kannappanr ^^
