### ISSUE TITLE
[working as intended] Too many requests from config.json on disks. Wasnt there before.

### ISSUE THREAD

**Issue by lssolutions-ie** [minio/minio#9265]
Unraid Docker
In the past minio wouldnt write dir sys.confid into /data share just bucket data. Now all config files are stored in /data causing json file to wake up disks every so often it even wakes up parity drives with so many writes opens and reads.
## Expected Behavior

sys config folder wasnt in /data share in the past

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by lssolutions-ie** [comment]
Here's file logs:
Apr 05 16:13:23 OPEN => /mnt/disk1/Floor Design/.minio.sys/buckets/.minio.sys/buckets/.usage.json/fs.json
Apr 05 16:13:23 CREATE => /mnt/disk1/Floor Design/.minio.sys/tmp/5f508020-99b7-410a-a0aa-83f7d38a8e40/62fd688e-8084-481d-be28-29b79626b485
Apr 05 16:13:23 OPEN => /mnt/disk1/Floor Design/.minio.sys/tmp/5f508020-99b7-410a-a0aa-83f7d38a8e40/62fd688e-8084-481d-be28-29b79626b485
Apr 05 16:13:23 ATTRIB => /mnt/disk1/Floor Design/.minio.sys/tmp/5f508020-99b7-410a-a0aa-83f7d38a8e40/62fd688e-8084-481d-be28-29b79626b485
Apr 05 16:13:23 MOVED_FROM => /mnt/disk1/Floor Design/.minio.sys/tmp/5f508020-99b7-410a-a0aa-83f7d38a8e40/62fd688e-8084-481d-be28-29b79626b485
Apr 05 16:13:23 MOVED_TO => /mnt/disk1/Floor Design/.minio.sys/buckets/.usage.json

That cycle is repeating almost every minute

**Comment by harshavardhana** [comment]
This crawling @korshakov if you want to disable it just disable crawling..

https://github.com/minio/minio/tree/master/docs/config#usage-crawler
