### ISSUE TITLE
[resolved] notifications: Webhooks don't use configured local CAs

### ISSUE THREAD

**Issue by MartijnVdS** [minio/minio#9266]
While setting up a bucket notification webhook to a web server with a certificate signed by a local CA, I noticed they didn't work and leave error messages in the log instead, even though the CA certificate is present in `/root/.minio/certs/CAs` (filename `rootCA.pem`) inside the container.

## Expected Behavior

Webhook notifications use CAs configured in `~/.minio/certs/CAs` to verify the server certificate.

## Current Behavior

An error is shown in the minio container logs:
```
Error: Post https://example.com/webhook: x509: certificate signed by unknown authority
       EventName=s3:ObjectCreated:Put, targetID=webhook
       3: github.com/minio/minio@/cmd/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()
       2: github.com/minio/minio@/cmd/logger/logonce.go:80:logger.LogOnceIf()
       1: github.com/minio/minio@/cmd/notification.go:1484:cmd.sendEvent.func1()
```

(I've changed the URL in the error message)

When using the `minio/mc` container this does work (there we mount it to `/root/.mc/certs/CAs`)

## Steps to Reproduce (for bugs)

1. Set up a web server with a certificate signed by local CA or using a self-signed certificate
2. Start `minio` with `MINIO_NOTIFY_WEBHOOK_ENDPOINT` pointing to that web server. Ensure the custom CA certificate is in a file in ~/.minio/certs/CAs/ (.pem and .cer)
3. Create a bucket and set up notification for it: `mc event add local/mybucket arn:minio:sqs::_:webhook`
4. Upload something to the bucket: `touch test.txt && mc cp test.txt local/mybucket/test`
5. See the error in the logs

## Context

Our development environment consists of a `docker-compose` setup with certificates signed by a local "development only" CA (to mimic the "real" deployment with certificates signed by known CAs as close as possible).

We use [mkcert](https://github.com/FiloSottile/mkcert/releases) to generate the certificates, then mount the root certificate into the relevant locations in the containers.

When using the `minio/mc` container this does work (there we mount it to `/root/.mc/certs/CAs`)

## Regression

I think this, or something very similar, was fixed before:
https://github.com/minio/minio/issues/3984 (https://github.com/minio/minio/pull/4000)

## Your Environment
* Version used (`minio version`): minio version RELEASE.2020-04-04T05-39-31Z (docker image "minio/minio", sha256:5efbd41b8fbc094d006590ea2c8e0f5db90719a3e44736c24dc4bacf423f7c95)
* Operating System and version (`uname -a`): Debian 10, Docker version 19.03.8, build afacb8b7f0

**Comment by harshavardhana** [comment]
> * Start `minio` with `MINIO_NOTIFY_WEBHOOK_ENDPOINT` pointing to that web server. Ensure the custom CA certificate is in a file in ~/.minio/certs/CAs/ (.pem and .cer)

did you keep your public.crt in `~/.minio/certs/CAs`  ?

**Comment by MartijnVdS** [comment]
> did you keep your public.crt in `~/.minio/certs/CAs` ?

Yes, I did. I tried mounting the CA certificate with multiple names inside the docker container (rootCA.pem, rootCA.crt, public.crt), none of them work.

I made a small demonstration repository that shows off the problem (it requires docker-compose, mkcert, mc and curl to run) at https://github.com/MartijnVdS/minio-bug-demo

**Comment by kannappanr** [comment]
@MartijnVdS Thanks. We will try to reproduce the issue.

**Comment by srisco** [comment]
Hello, I'm experiencing similar problems.

I think it would be useful to have an option for disabling TLS verification (like in NATS) for webhook endpoints, it would only be necessary to modify its custom transport.

**Comment by harshavardhana** [comment]
Webhook already uses the rootCAs properly loaded from either `--certs-dir` or legacy option `--config-dir` or default location `~/.minio/certs/CAs` - validated this locally.

Please use the latest release and let us know.
