### ISSUE TITLE
[faq] Best way to move a minio node on another server

### ISSUE THREAD

**Issue by lucas-dehandschutter** [minio/minio#9267]
**Is your feature request related to a problem? Please describe.**

My minio instance are distributed on a SWARM cluster running on bare metal servers.
Each minio instance is sticky on a node and his data are mounted in a local folder (/opt/data).
We have to replace some of these servers gradually and I want to move my minio instances from the old to the new servers in a rolling fashion way. 

**Describe the solution you'd like**

After the new server was added to the swarm, the ideal solution would be:
1. Stop minio instance x on old server
2. Copy minio data folder from old server to new server
3. Start minio instance x on the new server
4. Ensure the minio cluster is stable
5. Restart from 1. for the next server

Is this procedure correct?
How can I ensure step 4 before migrating the next node?

**Describe alternatives you've considered**

**Additional context**

**Comment by 4n70w4** [comment]
The same issue!

**Comment by mahomedh** [comment]
I have also been searching for steps and documentation to do this. I have tried asking in the slack but not received any detailed steps. Klaus did give some very minimal information about using `mc` to export the config and to read the docs. Unfortunately the `mc config export/import` and even the `mc config get/set` combination did not appear to do anything and definitely has not moved across the user accounts and policies. One user did recommend just copying across `.minio.sys` but Klaus said not to do this as it would have unintended effects.

I am now stuck with a failed upgrade/migration.

**Comment by mahomedh** [comment]
@lucas-dehandschutter Did you workout a solution in the end?

**Comment by MrSevy-zero** [comment]
It's supposed to be resilient, so I think you can failover to a new node just moving the label.... I'm about to try it :P
----
New unformatted drives detected attempting to heal the content...
Healing disk 'http://minio4:9000/export' on 1st zone
----

**Comment by mahomedh** [comment]
Did it work @MrSevy-zero?

**Comment by MrSevy-zero** [comment]
Flawlessly... 
I used a ansible playbook to add the new vps to the swarm and swap the labels with the old vps and all the data was online with no problem during all the failover....
