### ISSUE TITLE
API: System() "Bucket not found"

### ISSUE THREAD

**Issue by chess-equality** [minio/minio#9268]
I upgraded to the latest version just now, I'm getting the following from the log:

```
API: SYSTEM()
Time: 07:55:37 UTC 04/06/2020
DeploymentID: c936474f-20c0-4c3d-b139-0aeaa375b3db
Error: Bucket not found: .minio.sys/buckets
       1: github.com/minio/minio@/cmd/data-usage.go:69:cmd.runDataUsageInfo()
```

## Expected Behavior

Before the upgrade I don't get this.

## Current Behavior

Files are persisted and can be downloaded, however I'm not sure if it has affected something.

## Steps to Reproduce (for bugs)
1. `docker run -p 9000:9000 -d minio/minio server /data`
2. Do stuff, upload, download, delete.
3. Message above will appear in logs.

## Your Environment

* Version used (`minio version`): I pulled `minio/minio:latest`
* Operating System and version (`uname -a`): Linux zorinvm 5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

It's a Zorin OS 15.2 on VMware.

**Comment by kannappanr** [comment]
cc @klauspost

**Comment by vadmeste** [comment]
@chess-equality what's your MinIO version ?

**Comment by klauspost** [comment]
This is noise and should disappear once a bucket crawl has completed.

I will fix this as part of #9208

**Comment by chess-equality** [comment]
@vadmeste How to get the version from MinIO Docker image?

**Comment by klauspost** [comment]
@chess-equality Never mind, we don't need it.

**Comment by chess-equality** [comment]
@klauspost I just would like to know how.

**Comment by vadmeste** [comment]
@klauspost although the error seems to be harmless, I think it is not something to ignore, do you know why this is happening ?

@chess-equality: `docker run minio/minio version`

**Comment by klauspost** [comment]
@vadmeste It happens because there is no data usage saved yet. It is harmless.

**Comment by vadmeste** [comment]
> @vadmeste It happens because there is no data usage saved yet. It is harmless.

oh did you know that we can have '.minio.sys/buckets/' under '/path/to/fs-backend/.minio.sys/buckets/' ?

**Comment by chess-equality** [comment]
@vadmeste Thanks, it is `minio version RELEASE.2020-04-04T05-39-31Z`.

**Comment by harshavardhana** [comment]
This is fixed in the latest release..
