### ISSUE TITLE
Crawler Not Turning Off

### ISSUE THREAD

**Issue by lssolutions-ie** [minio/minio#9269]
I've tried to follow your comment where you said to turn it off. In the link you sent there is no mention of disabling it only to delay it. I've tried adding variable MINIO_DISK_USAGE_CRAWL_DELAY and set value to 100 tried value 30, 300 and 300. Same issue the crawler still open files every 5 minutes.
I have tried custom variable MINIO_DISK_USAGE_CRAWL='off' or MINIO_DISK_USAGE_CRAWL='disabled' or MINIO_DISK_USAGE_CRAWL='false'

still no joy. when i ssh into docker i can see in export that variables are there and i have tried to change timezone to see if variable are written and they are. heres export command:

export HOME='/root'
export HOSTNAME='f66f511f7032'
export HOST_OS='Unraid'
export MINIO_ACCESS_KEY='not showing this to public'
export MINIO_ACCESS_KEY_FILE='access_key'
export MINIO_DISK_USAGE_CRAWL='off'
export MINIO_DISK_USAGE_CRAWL_DELAY='30000'
export MINIO_KMS_MASTER_KEY_FILE='kms_master_key'
export MINIO_SECRET_KEY='not showing this to public'
export MINIO_SECRET_KEY_FILE='secret_key'
export MINIO_SSE_MASTER_KEY_FILE='sse_master_key'
export MINIO_UPDATE='off'
export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
export PWD='/'
export SHLVL='1'
export TCP_PORT_9000='9000'
export TERM='xterm'
export TZ='Europe/Dublin'

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by klauspost** [comment]
The environment variable to turn it off is called `MINIO_DISK_USAGE_CRAWL_ENABLE=off`. Do however note that this variable is not official, and may be deprecated without notice or have side other effects in the future.


`MINIO_DISK_USAGE_CRAWL_DELAY=30000` will, as documented, slow down the crawling, not stop it.
