### ISSUE TITLE
minio mc docker file not create bucket

### ISSUE THREAD

**Issue by tapos007** [minio/minio#9270]
version: "3"
services:
    es:
        image: "elasticsearch:7.6.1"
        container_name: myelasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - discovery.type=single-node
        restart: always
    re:
        image: redis
        container_name: myredis
        ports:
            - "6379:6379"
        restart: always
    rabbitmq:
        image: "rabbitmq:3-management"  
        container_name: myrabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"
        restart: always
        environment:
            - "RABBITMQ_DEFAULT_USER=admin"
            - "RABBITMQ_DEFAULT_PASS=Rcis123$$.."
    minio1:
        image: "minio/minio:RELEASE.2020-04-04T05-39-31Z"
        container_name: myminio
        ports:
            - "9000:9000"
        environment:
            - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
            - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
        restart: always
        volumes:
          - data1-1:/data1
          - data1-2:/data2
        command: server http://minio{1...4}/data{1...2}
    mymeniomc:
        image: "minio/mc"
        depends_on:
            - minio1
        container_name: myminiomc
        entrypoint: >
                    /bin/sh -c "
                     /usr/bin/mc config host rm local;
                     /usr/bin/mc config host add local http://minio1:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
                     /usr/bin/mc mb local/mybucket;
                     /usr/bin/mc policy set public local/mybucket;
                     exit 0;
                     "

volumes:
  data1-1:
  data1-2:

**Comment by nitisht** [comment]
@tapos007 please join us on Slack for such questions. We'll be able to help you there faster. Closing this as this is not an issue
