### ISSUE TITLE
minio cannot be restarted if only n/2 disks available

### ISSUE THREAD

**Issue by rudolpho1** [minio/minio#9271]
We have two servers and I am running one minio instance (with two disks) on each server. This is working fine. When I shut down one server, I am still able to read files but cannot write, as expected. Now, when I try to restart minio on the running server it does not come up again.

## Expected Behavior
Minio comes up again, and I am able to read files (not write of cause).

## Current Behavior
After restart, minio does not respond to any `mc` requests. The UI does not show any bucktes.

## Steps to Reproduce (for bugs)

1. Start minio on server A (IP 192.168.0.2): `./minio server http://192.168.0.{2...3}/mnt/minio{1...2}`
2. Start minio on server B (IP 192.168.0.3): `./minio server http://192.168.0.{2...3}/mnt/minio{1...2}`
3. Add some buckets and files
4. Stop minio on server B
5. Verify that you can still read your files
6. Stop minio on server A and restart it again (same command as in 1.)
7. Now, you can no longer read any files. Minio does not respond to `mc` requests.

## Context
We would like to use minio in our system and I am investigating it now. I would like to simulate the case where one server breaks down and it takes some time
to get a replacement. Ideally, I would like to add two additional disk to the minio instance that is still running, during this time period. This way it would have four disks and allow write operations again. However, I doubt that this is possible. At least I need to be able to operate the server in n/2 mode for a while. And that includes the ability to restart it. 

## Your Environment
* 2 Openstack servers with 16GB RAM, 4 CPUs each
* Fedora 31
* Minio version 2020-03-25T07:03:04Z

**Comment by klauspost** [comment]
@harshavardhana This seems to be related to locks being unable to be generated:

Goroutine trace:
```
#	0x4452d8	sync.runtime_Semacquire+0x48					c:/go/src/runtime/sema.go:56
#	0x4750fa	sync.(*WaitGroup).Wait+0x6a					c:/go/src/sync/waitgroup.go:130
#	0x127a445	github.com/minio/minio/pkg/dsync.lock+0x325			d:/minio/minio/pkg/dsync/drwmutex.go:294
#	0x1279d85	github.com/minio/minio/pkg/dsync.(*DRWMutex).lockBlocking+0x2c5	d:/minio/minio/pkg/dsync/drwmutex.go:148
#	0x14d639d	github.com/minio/minio/pkg/dsync.(*DRWMutex).GetLock+0xad	d:/minio/minio/pkg/dsync/drwmutex.go:100
#	0x14d6352	github.com/minio/minio/cmd.(*distLockInstance).GetLock+0x62	d:/minio/minio/cmd/namespace-lock.go:153
#	0x1556560	github.com/minio/minio/cmd.initSafeMode+0x120			d:/minio/minio/cmd/server-main.go:170
#	0x1557f7b	github.com/minio/minio/cmd.serverMain+0xaab			d:/minio/minio/cmd/server-main.go:447
#	0x11bb792	github.com/minio/cli.HandleAction+0x82				e:/gopath/pkg/mod/github.com/minio/cli@v1.22.0/app.go:500
#	0x11bc9b7	github.com/minio/cli.Command.Run+0x997				e:/gopath/pkg/mod/github.com/minio/cli@v1.22.0/command.go:225
#	0x11b9a31	github.com/minio/cli.(*App).Run+0x6b1				e:/gopath/pkg/mod/github.com/minio/cli@v1.22.0/app.go:261
#	0x14d13bf	github.com/minio/minio/cmd.Main+0x8f				d:/minio/minio/cmd/main.go:159
#	0x180998b	main.main+0x4b							d:/minio/minio/main.go:37
#	0x434eed	runtime.main+0x21d						c:/go/src/runtime/proc.go:203
```


FWIW the server will give up after some time with `ERROR Unable to initialize server switching into safe-mode: Operation timed out`.

**Comment by harshavardhana** [comment]
@klauspost the issue is that we need locks for config migration, leader locks so we cannot take server online just with N/2 number of servers alone.

So this is working as expected.

**Comment by klauspost** [comment]
That seems like an unfortunate sideeffect.

**Comment by kannappanr** [comment]
@rudolpho1 Based on the comment looks like this is working as expected as of now. we will document this better, so users are aware of the expected behavior
