### ISSUE TITLE
server should be allowed to bind for any 127.0.0.x IPs

### ISSUE THREAD

**Issue by justablob** [minio/minio#9274]
## Expected Behavior

Minio should listen to the specified IP.

## Current Behavior

When specifiying a 127.0.0.x address except 127.0.0.1, minio doesn't start. I'm currently trying to listen on 127.0.0.28 but minio seems to think this isn't a local IP.

## Possible Solution

Add 127.x.x.x as local IPs.

## Steps to Reproduce (for bugs)

1. Start minio and bind to any 127.0.0.x address except 127.0.0.1. 

## Context

I'm organizing my services in development mode by binding different services to different localhost IPs (127.0.0.0/8 / 127.x.x.x). Minio doesn't seem to like this.

## Regression
 No

## Your Environment

* Version used (`minio version`): RELEASE.2020-04-04T05-39-31Z
* Environment name and version (e.g. nginx 1.9.1): No real env, i'm running minio standalone at the moment.
* Operating System and version: Windows 10 Pro build# 18363.720

**Comment by harshavardhana** [comment]
This is not a bug your DNS host should resolve to something that can be communicated over.

So use a DNS or IP which allows external connection.

**Comment by justablob** [comment]
127.x.x.x are all working IPs though. If i listen on 127.0.0.233 using a simple mockup NodeJS server, i can access it via 127.0.0.233. DNS shouldn't even be involved in this as i'm not specifying a hostname but an IP to listen on.

**Comment by harshavardhana** [comment]
Paste your script how are you running?

**Comment by justablob** [comment]
```
cross-env MINIO_ACCESS_KEY=something MINIO_SECRET_KEY=something minio.exe server --address '127.0.0.28:1001' ./data
```

cross-env is a utility to allow bash-like env variable setting for specific commands only.

**Comment by harshavardhana** [comment]
> cross-env is a utility to allow bash-like env variable setting for specific commands only.

Yes this is not allowed because we validate if the interface belongs to local setup, I know that 127.0.0.1 is special but it is not implemented the way you want it. 

There are many such variations that we do not support, why? - because we want to be able to run MinIO on some real interfaces with real IPs.

But it is easy to fix nonetheless..

**Comment by justablob** [comment]
I've compiled your fork, it's working. Thanks a lot for the quick response. When the PR is merged, i'll close this issue.
