### ISSUE TITLE
Signature Does Not Match over Https

### ISSUE THREAD

**Issue by rjshree** [minio/minio#9284]
Hi,
I have deployed minio server on a kubernetes cluster.
Version: 
RELEASE.2020-04-04T05-39-31Z

We are using AWS S3 client in our javascript and trying to download file from Minio.

Code:
s3client = new AWS.S3({
        accessKeyId: s3AccessKey,
        secretAccessKey: s3SecretKey,
        sslEnabled: false,
        endpoint: minioEndpoint,
        s3ForcePathStyle: true,
        signatureVersion: 'v4'
      });
s3client
      .getObject({
        Bucket: options.bucket,
        Key: options.key,
        Range: options.range
      })

Error:
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
<Key>abcd/f1341a2c-7a54-4d68-9f40-a8b2d14d3806/f788fee4-4c37-42f8-9d81-e22e077b894c/0004.png</Key>
<BucketName>bucket1</BucketName>
<Resource>/bucket1/abcd/f1341a2c-7a54-4d68-9f40-a8b2d14d3806/f788fee4-4c37-42f8-9d81-e22e077b894c/0004.png</Resource>
<RequestId>1603907EBDF10EEA</RequestId>
<HostId>461ef2fd-3762-48cb-9925-6aa43d3e340d</HostId>
</Error>

We are trying to download the object via https then we are getting above error. With same code download via http works fine.

Any lead would be very much helpful.

Thanks
Rajashree

**Comment by kannappanr** [comment]
```
s3client = new AWS.S3({
accessKeyId: s3AccessKey,
secretAccessKey: s3SecretKey,
sslEnabled: true,
endpoint: minioEndpoint,
s3ForcePathStyle: true,
signatureVersion: 'v4'
});
```
can you try the above change in `https`?

Also, please reach out to us at https://slack.min.io for such questions. Closing this issue as answered

**Comment by rjshree** [comment]
@kannappanr 

We tried the above snippet. It gives same error.

Thanks
Rajashree
