### ISSUE TITLE
[resolved] permission denied to putobject in a worm bucket with general policy

### ISSUE THREAD

**Issue by guliujian** [minio/minio#9286]
## Expected Behavior
with the ability to putobject in the  worm bucket

## Current Behavior
it tells me don`t have sufficient permission to put the object 
```
mc: <ERROR> Failed to copy `./test`. Insufficient permissions to access this file
```

## Steps to Reproduce (for bugs)

1.  i create a two node minio cluster for test 
2. i create the bucket named testbucket used `mc mb xxx/testbucket` 
3. i set the bucket worm configuration by ```aws s3api put-object-lock-configuration --bucket testbucket  --object-lock-configuration 'ObjectLockEnabled="Enabled",Rule={DefaultRetention={Mode="COMPLIANCE",Days=1}}'```
4. i create the user xxx with policy as 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::testbucket"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:ListMultipartUploadParts",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::testbucket/*"
            ]
        }
    ]
}
```
5. i use this user to put object just use ```mc cp ./test xxx/testbucket/123131414``` it returns access denied and Insufficient permission
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key>123131414</Key><BucketName>testbucket</BucketName><Resource>/testbucket/123131414</Resource><RequestId>16039583F6D5472A</RequestId><HostId>678e359e-1b38-4884-b84e-e8fa7dfcdb87</HostId></Error>mc: <DEBUG> Response Time:  799.437505ms
````
 
## Your Environment

* Version used (`minio version`):  master branch , ef6304c5
* Environment name and version (e.g. nginx 1.9.1): mc: master  , eeeca233
* Server type and version: - 
* Operating System and version (`uname -a`): 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux 
* Link to your project: -

**Comment by kannappanr** [comment]
Thanks for reporting this issue. We are sort of refactoring this functionality a little bit. So, we will fix this soon. Currently, MinIo is expecting the user to also have `PutObjectRetention` action. As a work around, can you please also add `s3:PutObjectRetention` action.

**Comment by guliujian** [comment]
Thansk for the help ,after i add ```PutObjectRetention``` to policy ,it works .

**Comment by kannappanr** [comment]
@guliujian Thanks for letting us know. closing this issue as answered. Once we have the refactor done, you will not need that action to be part of the policy json anymore.
