### ISSUE TITLE
Misleading error when incorrect credentials are used with assume role

### ISSUE THREAD

**Issue by hardbyte** [minio/minio#9290]
This appears to be a minio server bug rather than a client bug. I've tested against aws as well as minio. The short version is boto at least is reporting a `MalformedPolicyDocumentException` to a assume role request (that doesn't even have a policy), when the issue should be with the credentials.

## Expected Behavior

Using boto with the default AWS endpoint a `ClientError` is raised:

`botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid.`

## Current Behavior

Running the same test with a local Minio deployment, boto raises a very different and misleading error message:

`botocore.errorfactory.MalformedPolicyDocumentException: An error occurred (MalformedPolicyDocument) when calling the AssumeRole operation: The request was rejected because the policy document was malformed.`

## Steps to Reproduce

1. Launch Minio locally - serving on port 9000. 
2. Run this with `python -m pytest`:

```python

import boto3

class TestAssumeRole:

    def test_create_temp_credentials_with_boto(self):
        session = boto3.Session(
            aws_access_key_id='newuser',
            aws_secret_access_key='newuser123',
            region_name='us-east-1'
        )
        sts_client = session.client('sts', endpoint_url="http://minio:9000")

        response = sts_client.assume_role(
            RoleArn="arn:xxx:xxx:xxx:xxxx",
            RoleSessionName="anything",
            # note not providing a Policy
            DurationSeconds=3000,
        )

```
3. Observe the exception.

## Context

I'm adding support for assume role to the minio-py client and I wanted to check that the minio server  behaves similar to AWS sts service. I was running tests with the boto client when I ran into this inconsistency. I actually had a `Policy` and believed the error message thinking I must have inadvertently modified my test policy, when I investigated it was actually the credentials were no longer valid.

## Regression
Not as far as I know.

## Environment

* Version used (`minio version`): Docker image was `minio/minio:RELEASE.2020-04-04T05-39-31Z`
* Environment name and version: local tests using docker compose.
* Link to your project: [wip gist for minio-py](https://gist.github.com/hardbyte/8d6261154b5c840a0f29e6d34cb181c9)

**Comment by harshavardhana** [comment]
Run `mc admin trace -v` to provide more information @hardbyte

**Comment by hardbyte** [comment]
Sure:

```
minio [REQUEST sts.AssumeRole] 02:13:41.467
minio POST /
minio Host: minio:9000
minio Authorization: AWS4-HMAC-SHA256 Credential=newuser/20200408/us-east-1/sts/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=9420f791ecc34bec2fae715a845f483d7f5d04638ba73bbcc1d956d825e74f0b
minio Content-Length: 119
minio Content-Type: application/x-www-form-urlencoded; charset=utf-8
minio User-Agent: Boto3/1.12.37 Python/3.8.2 Linux/5.3.0-45-generic Botocore/1.15.37
minio X-Amz-Date: 20200408T021341Z
minio Accept-Encoding: identity
minio Action=AssumeRole&Version=2011-06-15&RoleArn=arn%3Axxx%3Axxx%3Axxx%3Axxxx&RoleSessionName=anything&DurationSeconds=3000
minio [RESPONSE] [02:13:41.467] [ Duration 682µs  ↑ 204 B  ↓ 568 B ]
minio 400 Bad Request
minio Content-Length: 309
minio Content-Security-Policy: block-all-mixed-content
minio Content-Type: application/xml
minio Server: MinIO/RELEASE.2020-04-04T05-39-31Z
minio Vary: Origin
minio X-Amz-Request-Id: 1603B660FE71BBB7
minio X-Xss-Protection: 1; mode=block
minio Accept-Ranges: bytes
minio <?xml version="1.0" encoding="UTF-8"?>
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"><Error><Type></Type><Code>MalformedPolicyDocument</Code><Message>The request was rejected because the policy document was malformed.</Message></Error><RequestId>1603B660FE71BBB7</RequestId></ErrorResponse>
```
