### ISSUE TITLE
ERROR Invalid command line arguments: no endpoint pointing to the local machine is found

### ISSUE THREAD

**Issue by kirankanth** [minio/minio#9291]
## Current Behavior
Getting below error from minio status

Apr 07 16:08:33 server04 run_minio.bash[852]: Starting Minio process..
Apr 07 16:08:34 server04 run_minio.bash[852]: ERROR Invalid command line arguments: no endpoint pointing to the local machine is found.
Apr 07 16:08:34 server04 run_minio.bash[852]: > Please provide correct combination of local/remote paths.
Apr 07 16:08:34 server04 run_minio.bash[852]: HELP:
Apr 07 16:08:34 server04 run_minio.bash[852]: For more information, please refer to https://docs.minio.io/docs/minio-erasure-code-quickstar
Apr 07 16:08:34 server04 systemd[1]: minio.service: main process exited, code=exited, status=1/FAILURE
Apr 07 16:08:34 server04 systemd[1]: Unit minio.service entered failed state.
Apr 07 16:08:34 server04 systemd[1]: minio.service failed.

## Steps to Reproduce (for bugs)
Everytime we reboot the server, service is not coming back. Have to manually start it.

## Your Environment

* Version used (`minio version`):# minio version
Version: 2019-01-23T23:18:58Z
Release-Tag: RELEASE.2019-01-23T23-18-58Z
Commit-ID: bd25f31100f44646cffae99dfec23179366593e2
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: VM (VMware)
* Operating System and version (`uname -a`): RHEL 7.7

**Comment by kirankanth** [comment]
[minio startup.txt](https://github.com/minio/minio/files/4448080/minio.startup.txt)

**Comment by harshavardhana** [comment]
@kirankanth your server DNS should resolve to atleast one of the local interface IP

**Comment by kirankanth** [comment]
I have added all the host entries in /etc/hosts file (4 servers), so that it won't rely on DNS servers.
Ex:
# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
1.1.1.1 server04.com server04
2.2.2.2 server01.com server01
3.3.3.3 server02.com server02
4.4.4.4 server03.com server03

**Comment by harshavardhana** [comment]
Is your local IP on the interface 1.1.1.1 ?

**Comment by kirankanth** [comment]
I have replaced the actual IP with 1.1.1.1, but yes that's the primary IP of the server.

**Comment by harshavardhana** [comment]
> I have replaced the actual IP with 1.1.1.1, but yes that's the primary IP of the server.

 I don't think so that helps us @kirankanth we need to know exactly what the IPs are here.

**Comment by kirankanth** [comment]
I shouldn't be posting the IP's here due to security concerns, but they are all in the same subnet (10.x.x.x)

Here is how it goes:

10.x.x.71
10.x.x.72
10.x.x.73
10.x.x.74

**Comment by kirankanth** [comment]
Checking to see if you are aware of go package net log below and whether it is related to anything.

Apr 08 17:30:02 server04.phx.aexp.com run_minio.bash[862]: go package net: built with netgo build tag; using Go's DNS resolver
Apr 08 17:30:02 server04.phx.aexp.com run_minio.bash[862]: ERROR Invalid command line arguments: no endpoint pointing to the local machine is found.
Apr 08 17:30:02 server04.phx.aexp.com run_minio.bash[862]: > Please provide correct combination of local/remote paths.
Apr 08 17:30:02 server04.phx.aexp.com run_minio.bash[862]: HELP:
Apr 08 17:30:02 server04.phx.aexp.com run_minio.bash[862]: For more information, please refer to https://docs.minio.io/docs/minio-erasure-code-quickstart-guide
Apr 08 17:30:02 server04.phx.aexp.com systemd[1]: minio.service: main process exited, code=exited, status=1/FAILURE

**Comment by harshavardhana** [comment]
@kirankanth please provide the entire journalctl logs as requested here https://subnet.min.io/support/686

**Comment by kirankanth** [comment]
-- Reboot --
Apr 08 17:29:49 server04.com systemd[1]: [/usr/lib/systemd/system/minio.service:1] Assignment outside of section. Ignoring.
Apr 08 17:29:49 server04.com systemd[1]: [/usr/lib/systemd/system/minio.service:2] Assignment outside of section. Ignoring.
Apr 08 17:29:49 server04.com systemd[1]: [/usr/lib/systemd/system/minio.service:3] Assignment outside of section. Ignoring.
Apr 08 17:29:49 server04.com systemd[1]: [/usr/lib/systemd/system/minio.service:4] Assignment outside of section. Ignoring.
Apr 08 17:29:49 server04.com systemd[1]: [/usr/lib/systemd/system/minio.service:5] Assignment outside of section. Ignoring.
Apr 08 17:29:57 server04.com systemd[1]: Started minio.service.
Apr 08 17:29:57 server04.com run_minio.bash[862]: Starting Minio process..
Apr 08 17:29:57 server04.com run_minio.bash[862]: + /usr/local/bin/minio server https://server01.com/mnt/server0101 https://server01.com/mnt/server0102 https://server02.com/mnt/server0201 https://server02.com/mnt/server0202 https://server03.com/mnt/server0301 https://server03.com/mnt/server0302 https://server04.com/mnt/server0401 https://server04.com/mnt/server0402
Apr 08 17:30:02 server04.com run_minio.bash[862]: go package net: built with netgo build tag; using Go's DNS resolver
Apr 08 17:30:02 server04.com run_minio.bash[862]: ERROR Invalid command line arguments: no endpoint pointing to the local machine is found.
Apr 08 17:30:02 server04.com run_minio.bash[862]: > Please provide correct combination of local/remote paths.
Apr 08 17:30:02 server04.com run_minio.bash[862]: HELP:
Apr 08 17:30:02 server04.com run_minio.bash[862]: For more information, please refer to https://docs.minio.io/docs/minio-erasure-code-quickstart-guide
Apr 08 17:30:02 server04.com systemd[1]: minio.service: main process exited, code=exited, status=1/FAILURE
Apr 08 17:30:02 server04.com systemd[1]: Unit minio.service entered failed state.
Apr 08 17:30:02 server04.com systemd[1]: minio.service failed.
Apr 08 17:31:14 server04.com systemd[1]: [/usr/lib/systemd/system/minio.service:1] Assignment outside of section. Ignoring.
Apr 08 17:31:14 server04.com systemd[1]: [/usr/lib/systemd/system/minio.service:2] Assignment outside of section. Ignoring.
Apr 08 17:31:14 server04.com systemd[1]: [/usr/lib/systemd/system/minio.service:3] Assignment outside of section. Ignoring.
Apr 08 17:31:14 server04.com systemd[1]: [/usr/lib/systemd/system/minio.service:4] Assignment outside of section. Ignoring.
Apr 08 17:31:14 server04.com systemd[1]: [/usr/lib/systemd/system/minio.service:5] Assignment outside of section. Ignoring.

After manual restart:

Apr 08 17:35:04 server04.com systemd[1]: Started minio.service.
Apr 08 17:35:04 server04.com run_minio.bash[3862]: Starting Minio process..
Apr 08 17:35:04 server04.com run_minio.bash[3862]: + /usr/local/bin/minio server https://server01.com/mnt/server0101 https://server01.com/mnt/server0102 https://server02.com/mnt/server0201 https://server02.com/mnt/server0202 https://server03.com/mnt/server0301 https://server03.com/mnt/server0302 https://server04.com/mnt/server0401 https://server04.com/mnt/server0402
Apr 08 17:35:04 server04.com run_minio.bash[3862]: go package net: built with netgo build tag; using Go's DNS resolver
Apr 08 17:35:05 server04.com run_minio.bash[3862]: Status:         8 Online, 0 Offline.
Apr 08 17:35:05 server04.com run_minio.bash[3862]: Endpoint:  https://10.xx.xx.74-nfs:9000  https://10.yy.yy.74:9000  https://127.0.0.1:9000
Apr 08 17:35:05 server04.com run_minio.bash[3862]: Browser Access:
Apr 08 17:35:05 server04.com run_minio.bash[3862]: https://10.xx.xx.74-nfs:9000  https://10.yy.yy.74-nfs:9000  https://127.0.0.1:9000
Apr 08 17:35:05 server04.com run_minio.bash[3862]: Object API (Amazon S3 compatible):
Apr 08 17:35:05 server04.com run_minio.bash[3862]: Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
Apr 08 17:35:05 server04.com run_minio.bash[3862]: Java:       https://docs.minio.io/docs/java-client-quickstart-guide
Apr 08 17:35:05 server04.com run_minio.bash[3862]: Python:     https://docs.minio.io/docs/python-client-quickstart-guide
Apr 08 17:35:05 server04.com run_minio.bash[3862]: JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
Apr 08 17:35:05 server04.com run_minio.bash[3862]: .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide

**Comment by harshavardhana** [comment]
Okay this looks like the order of networking coming online is wrong here @kirankanth minio systemd service should come online after your networking services are up

**Comment by harshavardhana** [comment]
What is the OS here? @kirankanth

**Comment by harshavardhana** [comment]
```
Apr 08 17:29:49 server04.com systemd[1]: [/usr/lib/systemd/system/minio.service:1] Assignment outside of section. Ignoring.
Apr 08 17:29:49 server04.com systemd[1]: [/usr/lib/systemd/system/minio.service:2] Assignment outside of section. Ignoring.
Apr 08 17:29:49 server04.com systemd[1]: [/usr/lib/systemd/system/minio.service:3] Assignment outside of section. Ignoring.
Apr 08 17:29:49 server04.com systemd[1]: [/usr/lib/systemd/system/minio.service:4] Assignment outside of section. Ignoring.
Apr 08 17:29:49 server04.com systemd[1]: [/usr/lib/systemd/system/minio.service:5] Assignment outside of section. Ignoring.
```

Looks like your service IP has `[Unit]` section missing. 

```
# cat /usr/lib/systemd/system/minio.service
[Unit]
Description=Minio
Documentation=https://docs.minio.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/usr/local/bin/minio
```

Going to close this issue for now.

**Comment by kirankanth** [comment]
Should i just add the "[Unit]" and test?

Red Hat Enterprise Linux Server release 7.8 (Maipo)

**Comment by harshavardhana** [comment]
> Should i just add the "[Unit]" and test?

It will work just add that.

**Comment by kirankanth** [comment]
That worked. Thanks much for your help.
