### ISSUE TITLE
SignatureDoesNotMatch over Https

### ISSUE THREAD

**Issue by rjshree** [minio/minio#9307]
Hi,
I have deployed minio server on a kubernetes cluster.
Version:
RELEASE.2020-04-04T05-39-31Z

We are using AWS S3 client in our javascript and trying to download file from Minio.

Code:
s3client = new AWS.S3({
accessKeyId: s3AccessKey,
secretAccessKey: s3SecretKey,
sslEnabled: true/false,
endpoint: minioEndpoint,
s3ForcePathStyle: true,
signatureVersion: 'v4'
});
s3client
.getObject({
Bucket: options.bucket,
Key: options.key,
Range: options.range
})

Error:

SignatureDoesNotMatch
The request signature we calculated does not match the signature you provided. Check your key and signing method.
abcd/f1341a2c-7a54-4d68-9f40-a8b2d14d3806/f788fee4-4c37-42f8-9d81-e22e077b894c/0004.png
bucket1
/bucket1/abcd/f1341a2c-7a54-4d68-9f40-a8b2d14d3806/f788fee4-4c37-42f8-9d81-e22e077b894c/0004.png
1603907EBDF10EEA
461ef2fd-3762-48cb-9925-6aa43d3e340d
We are trying to download the object via https then we are getting above error. With same code download via http works fine.

we tried both sslEnabled: true and false.

Last issue was closed and could not be reopened hence I'm opening a new issue.

Thanks
Rajashree

**Comment by kannappanr** [comment]
```
var AWS = require('aws-sdk');

var s3  = new AWS.S3({
          accessKeyId: 'minio' ,
          secretAccessKey: 'minio123' ,
          endpoint: 'https://127.0.0.1:9000' ,
          s3ForcePathStyle: true,
	  sslEnabled: true,
          signatureVersion: 'v4'
         
});

// getObject operation.

var params = {Bucket: 'test', Key: 'issue'};

var file = require('fs').createWriteStream('/tmp/mykey');

s3.getObject(params).
on('httpData', function(chunk) { file.write(chunk); }).
on('httpDone', function() { file.end(); }).
send();
```
I have tried the above code against both Play and my local host.

**Comment by rjshree** [comment]
@kannappanr 
The extra code would be 
on('httpData', function(chunk) { file.write(chunk); }).
on('httpDone', function() { file.end(); }).
send();

Where you are writing the key path resource to the file and trying to send the file over http .
How this will help the file download over https?
A little explanation would be very much helpful for me to replicate this in angular application.

Thanks
Rajashree

**Comment by kannappanr** [comment]
Maybe something like this will help you understand

```
var AWS = require('aws-sdk');

var s3  = new AWS.S3({
          accessKeyId: 'minio' ,
          secretAccessKey: 'minio123' ,
          endpoint: 'https://play.min.io:9000' ,
          s3ForcePathStyle: true,
	  sslEnabled: true,
          signatureVersion: 'v4'
         
});

// getObject operation.

var params = {Bucket: 'test', Key: 'issue'};

var file = require('fs').createWriteStream('/tmp/mykey');

s3.getObject(params, function(err, data) {
   if (err) console.log(err, err.stack); // an error occurred
   else     console.log(data.Body.toString('utf-8'));           // successful response
 });
```
PTAL https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getObject-property for documentation on AWS SDK and how to use it.

Also, PTAL https://intellipaat.com/community/32594/how-to-get-response-from-s3-getobject-in-node-js

PTAL at https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/ for more documentation

Please reach out to us at https://slack.min.io for further questions
