### ISSUE TITLE
Example of using GCP gateway with Helm chart

### ISSUE THREAD

**Issue by Rep1AI** [minio/minio#9310]
There is an example with [docker](https://github.com/minio/minio/blob/master/docs/gateway/gcs.md#12-run-minio-gcs-gateway-using-docker) and [binary](https://github.com/minio/minio/blob/master/docs/gateway/gcs.md#13-run-minio-gcs-gateway-using-the-minio-binary)

Need an example with helm chart and operator please..

**Comment by harshavardhana** [comment]
https://github.com/helm/charts/tree/master/stable/minio#configuration

| Parameter                                 | Description                                                                                                                             | Default                                    |
|:------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------|
| `gcsgateway.enabled`                      | Use MinIO as a [Google Cloud Storage gateway](https://docs.minio.io/docs/minio-gateway-for-gcs)                                         | `false`                                    |
| `gcsgateway.gcsKeyJson`                   | credential json file of service account key                                                                                             | `""`                                       |
| `gcsgateway.projectId`                    | Google cloud project id                                                                                                                 | `""`                                       |

**Comment by harshavardhana** [comment]
> Need an example with helm chart and operator please..

The operator doesn't support gateway yet.

**Comment by Rep1AI** [comment]
> gcsgateway.gcsKeyJson

Can you give an example of how to use gcsgateway.gcsKeyJson in helm..

Also, I was looking for a way to use existing secret like in  https://github.com/helm/charts/blob/master/stable/mysqldump/values.yaml#L96

**Comment by harshavardhana** [comment]
> > gcsgateway.gcsKeyJson
> 
> Can you give an example of how to use gcsgateway.gcsKeyJson in helm..
> 
> Also, I was looking for a way to use existing secret like in https://github.com/helm/charts/blob/master/stable/mysqldump/values.yaml#L96

Nope none of that is possible right now @RohitR1 , feel free to send a support for such things to our upstream helm chart if needed.
