### ISSUE TITLE
Waiting for a minimum of 8 disks to come online (elapsed 20m49s)

### ISSUE THREAD

**Issue by Blue-Skies-firststar** [minio/minio#9314]
## Your Environment

* Version used (`minio version`): 
[root@localhost opt]# ./minio -v
minio version RELEASE.2020-04-04T05-39-31Z

* Operating System and version (`uname -a`):
[root@localhost data1]# cat /etc/redhat-release 
CentOS release 6.8 (Final)
[root@localhost data1]# uname -r
2.6.32-642.el6.x86_64

**Comment by Blue-Skies-firststar** [comment]
**this is My deployment steps**
export MINIO_ACCESS_KEY=<ACCESS_KEY>
export MINIO_SECRET_KEY=<SECRET_KEY>
./minio server http://192.168.1.11/export1 http://192.168.1.11/export2 \ http://192.168.1.11/export3 http://192.168.1.11/export4 \ http://192.168.1.12/export1 http://192.168.1.12/export2 \ http://192.168.1.12/export3 http://192.168.1.12/export4 \ http://192.168.1.13/export1 http://192.168.1.13/export2 \ http://192.168.1.13/export3 http://192.168.1.13/export4 \ http://192.168.1.14/export1 http://192.168.1.14/export2 \ http://192.168.1.14/export3 http://192.168.1.14/export4


but  Waiting for a minimum of 8 disks to come online (elapsed 20m49s)
Unable to cluster

**Comment by harshavardhana** [comment]
> **this is My deployment steps**
> export MINIO_ACCESS_KEY=<ACCESS_KEY>
> export MINIO_SECRET_KEY=<SECRET_KEY>
> ./minio server http://192.168.1.11/export1 http://192.168.1.11/export2 \ http://192.168.1.11/export3 http://192.168.1.11/export4 \ http://192.168.1.12/export1 http://192.168.1.12/export2 \ http://192.168.1.12/export3 http://192.168.1.12/export4 \ http://192.168.1.13/export1 http://192.168.1.13/export2 \ http://192.168.1.13/export3 http://192.168.1.13/export4 \ http://192.168.1.14/export1 http://192.168.1.14/export2 \ http://192.168.1.14/export3 http://192.168.1.14/export4
> 
> but Waiting for a minimum of 8 disks to come online (elapsed 20m49s)
> Unable to cluster

check if ports are open?, make sure Selinux is in permissive mode. Also not need to laboriously type all your args can be written nicely in one line, when in doubt always use simpler syntax. 

``` 
./minio server http://192.168.1.1{1...4}/export{1...4}
```

Use this, cleanup your backend again and get back to us.

**Comment by Blue-Skies-firststar** [comment]
This is not a bug，I have solved，because the added hard drive is not clean
the cluster is ok after I format the disk

**Comment by klauspost** [comment]
ok, closing.
