### ISSUE TITLE
Heal had an error - Storage resources are insufficient for the write operation.

### ISSUE THREAD

**Issue by i0x71** [minio/minio#9318]
Not sure if this is an issues or expected behavior, but i just did a test with 4 servers 1 disk each, and everything was rebuild successfully, however there is an error which gets thrown the first time heal is run any ideas what it means ?

Is this expected behavior ?

Just an fyi, when rm -rf /disk/* was ran only on NODE_A
and heal was ran afterwards, everything healed without any issues
I have not done any data verification tests.

## Expected Behavior
No error should be shown ?

## Current Behavior
Below error is shown after heal is run with 2/4 damaged replaced disks
mc: Unable to display heal status. Heal had an error - Storage resources are insufficient for the write operation.

## Steps to Reproduce (for bugs)
Procedure
Setup 4 hosts with 1 disk each
minio server http://NODE_A:9000/disk http://NODE_B:9000/disk http://NODE_C:9000/disk http://NODE_D:9000/disk

Client running on laptop configured as follows:
mc config host add cluster http://NODE_A:9000

On NODE_A and NODE_B run rm -rf /disk/*
Right after that run
mc admin heal -r cluster
mc: Unable to display heal status. Heal had an error - Storage resources are insufficient for the write operation.

The second time i run it, everything shows properly as healing and cluster is back to normal.
## Context
Not sure if this is a bug or expected behavior, i am guessing that heal tries to write some metadata and fails since there are only 2 replicas available.

mc --version
mc version RELEASE.2020-04-04T05-28-55Z
minio --version
minio version RELEASE.2020-04-10T03-34-42Z

**Comment by i0x71** [comment]
If that error is infact shown due to the lack of necessary worte replicas, I think it would make sense to add text saying that it's attempting to rebuild it and notify user to rerun heal to recheck status.

**Comment by vadmeste** [comment]
@i0x71 thanks for reporting this. I am able to reproduce it. 

Yeah it should not return an error here since half of disks are fine. I will send a fix soon.
