### ISSUE TITLE
Some disks ioutil cannot reach more than 80%

### ISSUE THREAD

**Issue by xiaosong135** [minio/minio#9325]
We wanted to test the performance of minio, but  we found that when on one disk’s ioutil reached 100%, it will block the others disk, causing not all the disks to work and the overall ioutil is about 40 to 50 percent. We want to know how can we make ioutil as high as possible to get better performance?
![image](https://user-images.githubusercontent.com/12624490/79042906-29368480-7c2e-11ea-85dc-2ea4af42d9d3.png)

Your Environment
minio version RELEASE.2020-04-10T03-34-42Z

**Comment by klauspost** [comment]
Data is spread evenly across disks, so your slowest drive will be your bottleneck.

For that reason it is recommended to use the same type of disks for each installation.

That said, the difference between 83 and 98% utilization often doesn't equal the same difference in actual performance.
