### ISSUE TITLE
[resolved] feat: Add continous lifecycle management for objects

### ISSUE THREAD

**Issue by ramondeklein** [minio/minio#9327]
I have enabled the bucket lifecycle configuration to remove objects after 7 days. It seems that it always starts the cleaning process around 06:30 (UTC), which is during office hours. We would rather have the cleaning process at a different schedule (i.e. at night) to reduce the IO during working hours. I haven't found any configuration to do this.

**Comment by harshavardhana** [comment]
> I have enabled the bucket lifecycle configuration to remove objects after 7 days. It seems that it always starts the cleaning process around 06:30 (UTC), which is during office hours. We would rather have the cleaning process at a different schedule (i.e. at night) to reduce the IO during working hours. I haven't found any configuration to do this.

We will be changing this to a continuous lifecycle which runs always, so it is never needed to be configurable. This is done in conjunction with our data usage implementation.

PS: Also please we prefer that you use the issue templates which we painstakingly wrote to help us, by describing your issue in more detail.

**Comment by ramondeklein** [comment]
Sorry for not using the template. I thought this was the most compact way to describe the issue. Great to hear that it will be switched to a continuous maintenance task. Can I track that feature (I couldn't find an issue for it).

**Comment by harshavardhana** [comment]
No issue yet we will use this issue instead and close it out when it's merged 

PR #9255

**Comment by harshavardhana** [comment]
This is fixed and released as well
