### ISSUE TITLE
[resolved] Slow performance

### ISSUE THREAD

**Issue by i0x71** [minio/minio#9336]
I seem to be experiencing very slow write performance when copying a file to fresh cluster.
I have 4 servers sitting on a gigabit switch, each server has an ssd in it.
iperf between servers show 950Mbit and dd write test to the ssd's shows about 300MB
As a test i setup a minio instance on each of the servers by running the following command on each server
export MINIO_ACCESS_KEY=xxxx
export MINIO_SECRET_KEY=xxxxxxxxxxxx
./minio server http://10.0.0.{3...6}:9000/export/0

After that i created a dummy binary file with dd
dd if=/dev/urandom of=test bs=1M count=5000

Created a bucket and tried uploading the file, the problem is that while the upload is going i am getting a constant 5.60 MiB/s

testFile:                    460.34 MiB / 4.88 GiB ┃▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃ 5.62 MiB/s

That seems like an awfully low number, im not even sure where to start looking.
Any suggestions ?

FYI,
I setup a non distributed instance on the first box and i am getting proper speeds
(/root/minio/minio server /export/0)
testFile:                    3.49 GiB / 4.88 GiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░░░░░░░░░░░░░░┃ 332.00 MiB/stestFile:                    3.49 GiB / 4.88 GiB 

I am running latest version of minio and mc
minio
minio version RELEASE.2020-04-10T03-34-42Z
mc
mc version RELEASE.2020-04-04T05-28-55Z

**Comment by harshavardhana** [comment]
> After that i created a dummy binary file with dd
> dd if=/dev/urandom of=test bs=1M count=5000

The problem you need to first test is with `oflag=direct` and `oflag=sync` to see what is your real disk performance across all servers and also capture

`mc admin info obd`

**Comment by i0x71** [comment]
root@dot3:~/minio# ./mc admin info dot3
●  10.0.0.3:9000
   Uptime: 47 seconds
   Version: 2020-04-10T03:34:42Z
   Network: 4/4 OK
   Drives: 1/1 OK

●  10.0.0.5:9000
   Uptime: 22 minutes
   Version: 2020-04-10T03:34:42Z
   Network: 4/4 OK
   Drives: 1/1 OK

●  10.0.0.6:9000
   Uptime: 22 minutes
   Version: 2020-04-10T03:34:42Z
   Network: 4/4 OK
   Drives: 1/1 OK

●  10.0.0.4:9000
   Uptime: 22 minutes
   Version: 2020-04-10T03:34:42Z
   Network: 4/4 OK
   Drives: 1/1 OK

0 B Used, 1 Bucket, 0 Objects
4 drives online, 0 drives offline

**Comment by i0x71** [comment]
records out
1048576000 bytes (1.0 GB, 1000 MiB) copied, 3.74102 s, 280 M
B/s

**Comment by harshavardhana** [comment]
> records out
> 1048576000 bytes (1.0 GB, 1000 MiB) copied, 3.74102 s, 280 M
> B/s

Are you sure you did this across servers? please paste you `oflag` values for both sync and `direct` 
and also `obd`

**Comment by i0x71** [comment]
What are you referring to as obd ? Output of this command ./mc admin info server ?

dot3
root@dot3:~/minio# dd if=/dev/zero of=q bs=1M count=1000 oflag=sync
1000+0 records in
1000+0 records out
1048576000 bytes (1.0 GB, 1000 MiB) copied, 4.58216 s, 229 MB/s
root@dot3:~/minio# dd if=/dev/zero of=q bs=1M count=1000 oflag=direct
1000+0 records in
1000+0 records out
1048576000 bytes (1.0 GB, 1000 MiB) copied, 2.51824 s, 416 MB/s
root@dot3:~/minio# dd if=/dev/zero of=q bs=1M count=1000 oflag=direct oflag=sync
1000+0 records in
1000+0 records out
1048576000 bytes (1.0 GB, 1000 MiB) copied, 3.8184 s, 275 MB/s

dot4
root@dot4:~/minio# dd if=/dev/zero of=q bs=1M count=1000 oflag=sync
1000+0 records in
1000+0 records out
1048576000 bytes (1.0 GB, 1000 MiB) copied, 4.86506 s, 216 MB/s
root@dot4:~/minio# dd if=/dev/zero of=q bs=1M count=1000 oflag=direct
1000+0 records in
1000+0 records out
1048576000 bytes (1.0 GB, 1000 MiB) copied, 2.19316 s, 478 MB/s
root@dot4:~/minio# dd if=/dev/zero of=q bs=1M count=1000 oflag=direct oflag=sync
1000+0 records in
1000+0 records out
1048576000 bytes (1.0 GB, 1000 MiB) copied, 3.75366 s, 279 MB/s

dot5
root@dot5:~/minio# dd if=/dev/zero of=q bs=1M count=1000 oflag=sync
1000+0 records in
1000+0 records out
1048576000 bytes (1.0 GB, 1000 MiB) copied, 4.72824 s, 222 MB/s
root@dot5:~/minio# dd if=/dev/zero of=q bs=1M count=1000 oflag=direct
1000+0 records in
1000+0 records out
1048576000 bytes (1.0 GB, 1000 MiB) copied, 2.22419 s, 471 MB/s
root@dot5:~/minio# dd if=/dev/zero of=q bs=1M count=1000 oflag=direct oflag=sync
1000+0 records in
1000+0 records out
1048576000 bytes (1.0 GB, 1000 MiB) copied, 4.38521 s, 239 MB/s


dot6
root@dot6:~/minio# dd if=/dev/zero of=q bs=1M count=1000 oflag=sync
1000+0 records in
1000+0 records out
1048576000 bytes (1.0 GB, 1000 MiB) copied, 4.09517 s, 256 MB/s
root@dot6:~/minio# dd if=/dev/zero of=q bs=1M count=1000 oflag=direct
1000+0 records in
1000+0 records out
1048576000 bytes (1.0 GB, 1000 MiB) copied, 2.50261 s, 419 MB/s
root@dot6:~/minio# dd if=/dev/zero of=q bs=1M count=1000 oflag=direct oflag=sync
 
1000+0 records in
1000+0 records out
1048576000 bytes (1.0 GB, 1000 MiB) copied, 4.11118 s, 255 MB/s

**Comment by i0x71** [comment]
Here is the output of the info comman from each node

root@dot3:~/minio# ./mc admin info dot3
●  10.0.0.3:9000
   Uptime: 7 minutes 
   Version: 2020-04-10T03:34:42Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

●  10.0.0.5:9000
   Uptime: 7 minutes 
   Version: 2020-04-10T03:34:42Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

●  10.0.0.6:9000
   Uptime: 7 minutes 
   Version: 2020-04-10T03:34:42Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

●  10.0.0.4:9000
   Uptime: 7 minutes 
   Version: 2020-04-10T03:34:42Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

0 B Used, 1 Bucket, 0 Objects
4 drives online, 0 drives offline
root@dot3:~/minio# ./mc admin info dot4
●  10.0.0.3:9000
   Uptime: 7 minutes 
   Version: 2020-04-10T03:34:42Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

●  10.0.0.5:9000
   Uptime: 7 minutes 
   Version: 2020-04-10T03:34:42Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

●  10.0.0.6:9000
   Uptime: 7 minutes 
   Version: 2020-04-10T03:34:42Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

●  10.0.0.4:9000
   Uptime: 7 minutes 
   Version: 2020-04-10T03:34:42Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

0 B Used, 1 Bucket, 0 Objects
4 drives online, 0 drives offline
root@dot3:~/minio# ./mc admin info dot5
●  10.0.0.3:9000
   Uptime: 7 minutes 
   Version: 2020-04-10T03:34:42Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

●  10.0.0.5:9000
   Uptime: 7 minutes 
   Version: 2020-04-10T03:34:42Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

●  10.0.0.6:9000
   Uptime: 7 minutes 
   Version: 2020-04-10T03:34:42Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

●  10.0.0.4:9000
   Uptime: 7 minutes 
   Version: 2020-04-10T03:34:42Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

0 B Used, 1 Bucket, 0 Objects
4 drives online, 0 drives offline
root@dot3:~/minio# ./mc admin info dot6
●  10.0.0.3:9000
   Uptime: 7 minutes 
   Version: 2020-04-10T03:34:42Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

●  10.0.0.5:9000
   Uptime: 7 minutes 
   Version: 2020-04-10T03:34:42Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

●  10.0.0.6:9000
   Uptime: 7 minutes 
   Version: 2020-04-10T03:34:42Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

●  10.0.0.4:9000
   Uptime: 7 minutes 
   Version: 2020-04-10T03:34:42Z
   Network: 4/4 OK 
   Drives: 1/1 OK 

0 B Used, 1 Bucket, 0 Objects
4 drives online, 0 drives offline

**Comment by harshavardhana** [comment]
> What are you referring to as obd ? Output of this command ./mc admin info server ?

I am talking about `mc admin obd`

**Comment by i0x71** [comment]
Ok, its seems to be stuck on the Net part

On one of the nodes this is getting printed
API: SYSTEM()
Time: 22:31:35 UTC 04/13/2020
DeploymentID: 44259624-b895-4f3f-9573-847af68c504a
Error: network overloaded
       remotePeer=10.0.0.5:9000
       3: github.com/minio/minio@/cmd/notification.go:952:cmd.(*NotificationSys).NetOBDInfo()
       2: github.com/minio/minio@/cmd/admin-handlers.go:1495:cmd.adminAPIHandlers.OBDInfoHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()

**Comment by i0x71** [comment]
Also, on the node where im running mc

root@dot3:~/minio# ./mc admin obd dot3
● Admin Info ... ✔ 
● CPU ... ✔ 
● Disk Hardware ... ✔ 
● Os Info ... ✔ 
● Mem Info ... ✔ 
● Process Info ... ✔ 
● Config ... ✔ 
● Drive ... ✔ 
● Net ... -- 

API: SYSTEM()
Time: 22:33:15 UTC 04/13/2020
DeploymentID: 44259624-b895-4f3f-9573-847af68c504a
Error: network overloaded
       remotePeer=10.0.0.4:9000
       3: github.com/minio/minio@/cmd/notification.go:952:cmd.(*NotificationSys).NetOBDInfo()
       2: github.com/minio/minio@/cmd/peer-rest-server.go:527:cmd.(*peerRESTServer).DispatchNetOBDInfoHandler()
● Net ... --

**Comment by i0x71** [comment]
I seems that network performance to one of the nodes is getting capped at 94mbit, more info to follow

**Comment by harshavardhana** [comment]
> I seems that network performance to one of the nodes is getting capped at 94mbit, more info to follow

Now you know the problem @i0x71

**Comment by i0x71** [comment]
Apologies, it turned out to be a bad port on the switch.
Cluster copy is super fast now!
To all the devs, thanks for writing this amazing piece of software!

**Comment by harshavardhana** [comment]
> Apologies, it turned out to be a bad port on the switch.
> Cluster copy is super fast now!
> To all the devs, thanks for writing this amazing piece of software!

Thank you
