### ISSUE TITLE
[resolved] Clearing metadata

### ISSUE THREAD

**Issue by i0x71** [minio/minio#9337]
This probably is not the right place to post this but im not sure where else to post.
Im trying to figure out how to clear metadata,

Started all servers with this command
/root/minio/minio server http://10.0.0.{3...6}:9000/export/{0...1}

After stopping them removed all /export/* folders (including .minio.sys)
Restarted servers, now when i run heal it reports missing objects
root@dot3:~/minio# ./mc admin heal -r --scan deep dot3
 ◓  [bucket-metadata].minio.sys/buckets/
    0/0 objects; 0 B in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 3 │  75.0% █████████    │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 1 │  25.0% ███          │
    └────────┴───┴─────────────────────┘

Is there some other cache directory that i am missing ?
I already tried dropping system caches and removing ~/.mc and ~/.minio

I assumed that after removing all the data in /exports and restarting i would be starting a new instance of the cluster ?

**Comment by kannappanr** [comment]
@i0x71 Are you able to reproduce this more than once? Also you can run the command in json mode to get more information.

**Comment by i0x71** [comment]
It happening every time, i just did once again with the following procedure
kill minio on all servers
(/export/1 is another mounted disk)
rm -rf /export/0; rm -rf /export/1/*; rm -rf /export/1/.*
restart minio, run heal, grey 25% shows up, is that expected behavior or am i missing something obvious here ?

Before wiping data
root@dot3:~/minio# ./mc admin heal -r --scan deep dot3
 ◒  test/testFile
    0/1 objects; 4 GiB in 15s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 7 │  87.5% ███████████  │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 1 │  12.5% ██           │
    └────────┴───┴─────────────────────┘

After wiping data
root@dot3:~/minio# ./mc admin heal -r --scan deep dot3
 ◓  [bucket-metadata].minio.sys/buckets/
    0/0 objects; 0 B in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 3 │  75.0% █████████    │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 1 │  25.0% ███          │
    └────────┴───┴─────────────────────┘

**Comment by i0x71** [comment]
It seems to be related to the fact that /export/1 is exists prior to starting the server, since if i test it with just a local folder that doesnt exist i don't see the same behavior.

**Comment by i0x71** [comment]
After testing without mounting another drive under /export/1 everything behaves as normal, more to follow

**Comment by i0x71** [comment]
So it does seem like abnormal behavior, and happens every time, so its easy to replicate.
(/export/0 is supposed to be local disk, hence nothing to unmount)
(/export/1 is a second disk)

Stop all minio instances
umount /export/1
rm -rf /export
mkfs.ext4 /dev/sdXX
mkdir -p /export/0
mkdir -p /export/1
mount /dev/sdXX /export/1
start minio with
export MINIO_ACCESS_KEY=xxxxxxxxxxxx
export MINIO_SECRET_KEY=xxxxxxxxxxxxx
/root/minio/minio server http://10.0.0.{3...6}:9000/export/{0...1}

 ◓  [bucket-metadata].minio.sys/buckets/
    0/0 objects; 0 B in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 3 │  75.0% █████████    │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 1 │  25.0% ███          │
    └────────┴───┴─────────────────────┘

It seems to be directly related with the fact that there is another drive mounted under /export/1, i have also tried this by passing a subdir to the export path instead of giving the root
/root/minio/minio server http://10.0.0.{3...6}:9000/export/{0...1}/minio

Same behavior

**Comment by vadmeste** [comment]
@i0x71 are you sure your MinIO binary is able to write on your mounted disk ? is .minio.sys/ directory created after you running heal command?

Also running heal command with --json flag shows better what is reporting grey. Could you paste your json output ?

**Comment by i0x71** [comment]
Its definitely able to write to it, i can see new objects created in there as well as .minio.sys before i delete it

Sorry forgot about json data, here it is

{
 "status": "success",
 "type": "system",
 "name": "disk-format",
 "before": {
  "color": "grey",
  "offline": 4,
  "online": 4,
  "missing": 0,
  "corrupted": 0,
  "drives": [
   {
    "uuid": "",
    "endpoint": "http://10.0.0.3:9000/export/0",
    "state": "offline"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.4:9000/export/0",
    "state": "offline"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.5:9000/export/0",
    "state": "offline"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.6:9000/export/0",
    "state": "offline"
   },
   {
    "uuid": "177e98ad-5218-46c6-8d57-68a4ed7e591b",
    "endpoint": "http://10.0.0.3:9000/export/1",
    "state": "ok"
   },
   {
    "uuid": "0f58a152-c13b-4dc4-889e-11ac1271e918",
    "endpoint": "http://10.0.0.4:9000/export/1",
    "state": "ok"
   },
   {
    "uuid": "d6087eac-580a-4979-b383-7bfb1d749ea7",
    "endpoint": "http://10.0.0.5:9000/export/1",
    "state": "ok"
   },
   {
    "uuid": "36d2780d-2bc9-4d20-b047-a6300e72bb57",
    "endpoint": "http://10.0.0.6:9000/export/1",
    "state": "ok"
   }
  ]
 },
 "after": {
  "color": "grey",
  "offline": 4,
  "online": 4,
  "missing": 0,
  "corrupted": 0,
  "drives": [
   {
    "uuid": "",
    "endpoint": "http://10.0.0.3:9000/export/0",
    "state": "offline"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.4:9000/export/0",
    "state": "offline"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.5:9000/export/0",
    "state": "offline"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.6:9000/export/0",
    "state": "offline"
   },
   {
    "uuid": "177e98ad-5218-46c6-8d57-68a4ed7e591b",
    "endpoint": "http://10.0.0.3:9000/export/1",
    "state": "ok"
   },
   {
    "uuid": "0f58a152-c13b-4dc4-889e-11ac1271e918",
    "endpoint": "http://10.0.0.4:9000/export/1",
    "state": "ok"
   },
   {
    "uuid": "d6087eac-580a-4979-b383-7bfb1d749ea7",
    "endpoint": "http://10.0.0.5:9000/export/1",
    "state": "ok"
   },
   {
    "uuid": "36d2780d-2bc9-4d20-b047-a6300e72bb57",
    "endpoint": "http://10.0.0.6:9000/export/1",
    "state": "ok"
   }
  ]
 },
 "size": 0
}
{
 "status": "success",
 "type": "system",
 "name": "bucket-metadata:.minio.sys/config/config.json",
 "before": {
  "color": "green",
  "offline": 0,
  "online": 8,
  "missing": 0,
  "corrupted": 0,
  "drives": [
   {
    "uuid": "",
    "endpoint": "/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.4:9000/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.5:9000/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.6:9000/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "/export/1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.4:9000/export/1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.5:9000/export/1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.6:9000/export/1",
    "state": "ok"
   }
  ]
 },
 "after": {
  "color": "green",
  "offline": 0,
  "online": 8,
  "missing": 0,
  "corrupted": 0,
  "drives": [
   {
    "uuid": "",
    "endpoint": "/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.4:9000/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.5:9000/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.6:9000/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "/export/1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.4:9000/export/1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.5:9000/export/1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.6:9000/export/1",
    "state": "ok"
   }
  ]
 },
 "size": 0
}
{
 "status": "success",
 "type": "system",
 "name": "bucket-metadata:.minio.sys/config/iam/format.json",
 "before": {
  "color": "green",
  "offline": 0,
  "online": 8,
  "missing": 0,
  "corrupted": 0,
  "drives": [
   {
    "uuid": "",
    "endpoint": "/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.4:9000/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.5:9000/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.6:9000/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "/export/1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.4:9000/export/1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.5:9000/export/1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.6:9000/export/1",
    "state": "ok"
   }
  ]
 },
 "after": {
  "color": "green",
  "offline": 0,
  "online": 8,
  "missing": 0,
  "corrupted": 0,
  "drives": [
   {
    "uuid": "",
    "endpoint": "/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.4:9000/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.5:9000/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.6:9000/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "/export/1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.4:9000/export/1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.5:9000/export/1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.6:9000/export/1",
    "state": "ok"
   }
  ]
 },
 "size": 0
}
{
 "status": "success",
 "type": "system",
 "name": "bucket-metadata:.minio.sys/buckets/",
 "before": {
  "color": "green",
  "offline": 0,
  "online": 8,
  "missing": 0,
  "corrupted": 0,
  "drives": [
   {
    "uuid": "",
    "endpoint": "/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.4:9000/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.5:9000/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.6:9000/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "/export/1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.4:9000/export/1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.5:9000/export/1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.6:9000/export/1",
    "state": "ok"
   }
  ]
 },
 "after": {
  "color": "green",
  "offline": 0,
  "online": 8,
  "missing": 0,
  "corrupted": 0,
  "drives": [
   {
    "uuid": "",
    "endpoint": "/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.4:9000/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.5:9000/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.6:9000/export/0",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "/export/1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.4:9000/export/1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.5:9000/export/1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://10.0.0.6:9000/export/1",
    "state": "ok"
   }
  ]
 },
 "size": 0
}
{
 "status": "success",
 "type": "summary",
 "objects_scanned": 0,
 "objects_healed": 0,
 "items_scanned": 4,
 "items_healed": 0,
 "size": 0,
 "duration": 1
}

**Comment by vadmeste** [comment]
Could you join https://slack.min.io ?

**Comment by i0x71** [comment]
joined

**Comment by vadmeste** [comment]
This is how to reproduce using docker compose:
```
version: '3.7'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
  server1:
    image: minio/minio
    ports:
      - "9001:9000"
    volumes:
      - server1-data:/export1
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://server{1...4}:9000/export{0...1}/
  server2:
    image: minio/minio
    ports:
      - "9002:9000"
    volumes:
      - server2-data:/export1
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://server{1...4}:9000/export{0...1}/
  server3:
    image: minio/minio
    ports:
      - "9003:9000"
    volumes:
      - server3-data:/export1
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://server{1...4}:9000/export{0...1}/
  server4:
    image: minio/minio
    ports:
      - "9004:9000"
    volumes:
      - server4-data:/export1
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://server{1...4}:9000/export{0...1}/

volumes:
  server1-data:
  server2-data:
  server3-data:
  server4-data:
```

Probably because rootfs & mounted disks are used at the same time.

**Comment by vadmeste** [comment]
Oh that's the reason, MinIO does not heal rootfs disks https://github.com/minio/minio/blob/master/cmd/xl-sets.go#L1459

All of your disks should be mounted for distributed setup.

**Comment by i0x71** [comment]
Something here doesnt make sense, because when i run 4 node cluster with this command (on the local rootfs disk) everything works
/root/minio/minio server http://10.0.0.{3...6}:9000/export/0
(Which is located in only rootfs and not a mounted drive)

There are grey files
root@dot3:~/minio# ./mc admin heal -r --scan deep dot3
 ◓  [bucket-metadata].minio.sys/buckets/
    0/0 objects; 0 B in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 4 │ 100.0% ████████████ │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘

Also if i run the cluster with /root/minio/minio server http://10.0.0.{3...6}:9000/export/1
Exclusivery only on mounted disks everything also works

 ◓  [bucket-metadata].minio.sys/buckets/
    0/0 objects; 0 B in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 4 │ 100.0% ████████████ │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘


However if i mix 1 disk on rootfs and one disk is mounted then i get the grey file

**Comment by vadmeste** [comment]
@i0x71 that's actually expected.

We just do not want from MinIO server to unexpectedly write in the root FS when a disk is unmounted for some reasons (like a failed disk)

However it is still allowed if all disks are rootfs. It just disallow the mixup use of rootfs and external disks.

**Comment by i0x71** [comment]
Ah that makes sense, thanks for your help!

**Comment by i0x71** [comment]
We should put this in a doc somewhere :)

**Comment by harshavardhana** [comment]
> @i0x71 that's actually expected.
> 
> We just do not want from MinIO server to unexpectedly write in the root FS when a disk is unmounted for some reasons (like a failed disk)
> 
> However it is still allowed if all disks are rootfs. It just disallow the mixup use of rootfs and external disks.

This is reported now as part of server startup.
