### ISSUE TITLE
deploy Minio  in China  Azure

### ISSUE THREAD

**Issue by fujianan** [minio/minio#9338]
I want to deploy minio in Azure
But I can't find minio in Azure 
I read this blob(https://az.minio.io/)
I want to confirm if Minio supports it in China Azure

**Comment by harshavardhana** [comment]
> I want to confirm if Minio supports it in China Azure

We do not support Azure App in china @fujianan - you can download the binary and run it on an Azure VM instead

https://github.com/minio/minio/blob/master/docs/gateway/azure.md
