### ISSUE TITLE
[not our bug] after minio upgrade, the client uplode time is longger, performance degraded

### ISSUE THREAD

**Issue by hebe9585** [minio/minio#9342]
after minio upgrade, the client uplode time is longger, performance degraded
**We upgrade minio version from RELEASE.2019-09-25T18-25-51Z to RELEASE.2020-02-27T00-23-05Z.** 
our test result is 
upload 500M,  time is about 10s on RELEASE.2019-09-25T18-25-51Z
upload 2G file time is about 35s on RELEASE.2019-09-25T18-25-51Z
upload 5G file time is about 1m30s on RELEASE.2019-09-25T18-25-51Z

but on same condition(cpu and memory resource limit), 
upload 500M time is about 17s on RELEASE.2020-02-27T00-23-05Z
upload 2G file time is about 1m10s on RELEASE.2020-02-27T00-23-05Z
upload 5G file time is about 2m55s on RELEASE.2020-02-27T00-23-05Z

The performance is degraded obviously. Nearly 50% or even more.
**Then we tested on the latest minio version RELEASE.2020-04-10T03-34-42Z, the result is almost the same as on RELEASE.2020-02-27T00-23-05Z**  compared the RELEASE.2019-09-25T18-25-51Z
, the upload time performance degraded. 

**But for the download time performance, we didn't see much degraded.** 
## Expected Behavior

the performance shouldn't be degraded too much.

## Current Behavior

The performance is degraded obviously. Nearly 50% or even more.
**Then we tested on the latest minio version RELEASE.2020-04-10T03-34-42Z, the result is almost the same as on RELEASE.2020-02-27T00-23-05Z**  compared the RELEASE.2019-09-25T18-25-51Z
, the upload time performance degraded. 

**But for the download time performance, we didn't see much degraded.** 

## Possible Solution

could you please help to check that ?

## Steps to Reproduce (for bugs)

1. using minio client to push files to minio server. record the upload and download time.
2. upgrade minio version
3. retest  using minio client to push files to minio server. record the upload and download time.
4.compare these file delivery time to see the performance has a degrade or not.

## Context

the upload time is too long 

## Regression

as described the previous steps

## Your Environment

* Version used (`minio version`):RELEASE.2020-02-27T00-23-05Z,  RELEASE.2020-04-10T03-34-42Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: minio
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by klauspost** [comment]
@hebe9585 Could you describe your server setup, commandline, env vars, etc?

Could you try running [warp](https://github.com/minio/warp) and post the resulting files?

Something like `warp put --host=10.0.0.1:9000 --access-key= --secret-key= --serverprof=cpu,mem,block --obj.size=50MB --duration=3m --autoterm` should give a good basis for comparison.

**Comment by harshavardhana** [comment]
> after minio upgrade, the client uplode time is longger, performance degraded
> **We upgrade minio version from RELEASE.2019-09-25T18-25-51Z to RELEASE.2020-02-27T00-23-05Z.**
> our test result is
> upload 500M, time is about 10s on RELEASE.2019-09-25T18-25-51Z
> upload 2G file time is about 35s on RELEASE.2019-09-25T18-25-51Z
> upload 5G file time is about 1m30s on RELEASE.2019-09-25T18-25-51Z
> 
> but on same condition(cpu and memory resource limit),
> upload 500M time is about 17s on RELEASE.2020-02-27T00-23-05Z
> upload 2G file time is about 1m10s on RELEASE.2020-02-27T00-23-05Z
> upload 5G file time is about 2m55s on RELEASE.2020-02-27T00-23-05Z
> 
> The performance is degraded obviously. Nearly 50% or even more.
> **Then we tested on the latest minio version RELEASE.2020-04-10T03-34-42Z, the result is almost the same as on RELEASE.2020-02-27T00-23-05Z** compared the RELEASE.2019-09-25T18-25-51Z
> , the upload time performance degraded.

You haven't explained how are you running MinIO @hebe9585 - is it just a single drive mode, multiple drives? etc.

**Comment by hebe9585** [comment]
Hi ,
Thanks so much.
@harshavardhana it's distribution mode. there are four minio server and one client.
@klauspost it's distribution mode. there are four minio server and one client.
each time , everything of the testbed and environment keep same, only change the minio version.
I used the command "mc cp " to push file.
mc config host add abc $DNS $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
mc mb abc/qqq
"time mc cp /script/files/aaa1 abc/qqq/"

**Comment by harshavardhana** [comment]
> Hi ,
> Thanks so much.
> @harshavardhana it's distribution mode. there are four minio server and one client.
> @klauspost it's distribution mode. there are four minio server and one client.
> each time , everything of the testbed and environment keep same, only change the minio version.
> I used the command "mc cp " to push file.
> mc config host add abc $DNS $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
> mc mb abc/qqq
> "time mc cp /script/files/aaa1 abc/qqq/"

Just upgrade to latest and run `mc admin obd`

**Comment by hebe9585** [comment]
@klauspost 
we used warp to do the test. the result is also to get the same conclusion.
RELEASE.2020-02-27T00-23-05Z performance is degrade compared with RELEASE.2019-09-25T18-25-51Z. 
here is our test result on RELEASE.2019-10-12T01-39-57Z and RELEASE.2020-02-27T00-23-05Z

[RELEASE.2019-10-12T01-39-57Z-benchmark.txt](https://github.com/minio/minio/files/4484807/RELEASE.2019-10-12T01-39-57Z-benchmark.txt)
[RELEASE.2020-02-27T00-23-05Z-benchmark.txt](https://github.com/minio/minio/files/4484808/RELEASE.2020-02-27T00-23-05Z-benchmark.txt)

**Comment by harshavardhana** [comment]
@hebe9585 you should use the latest release instead of 02-27 to run the comparisons, we won't be going to back to older releases to fix any issues that may exist.

**Comment by harshavardhana** [comment]
Also once the numbers are run please share the saved .zst files from the warp runs for both releases @hebe9585

**Comment by klauspost** [comment]
Interesting. Frankly there shouldn't be any measurable difference between these object sizes. How consistent are these differences?

Maybe do a run with `--obj.size=5120MB --obj.randsize` - that will use sizes up to the given size. And if you can zip up the output files that would help as well (there is information beside the hostname in the file).

**Comment by klauspost** [comment]
Also adding the `--serverprof=cpu,mem,block` and sending the zip file with the result will help us see where resources are spent.

**Comment by hebe9585** [comment]
Hi Klauspost,
We're trying to add the params to get all these resource information.
By the way, May I ask one question about the performance minio. Did you have any conclusion or test report which indicated that the new version of minio will consume more cpu and memory than the old version?

**Comment by klauspost** [comment]
@hebe9585 No, that is why I am asking for profiles, so I can see what is the bottleneck in your system.

**Comment by harshavardhana** [comment]
Looks like a stale issue and there has been no conclusive evidence of any regression across other deployments.
