### ISSUE TITLE
Unlimited event queue

### ISSUE THREAD

**Issue by starinacool** [minio/minio#9344]
**Is your feature request related to a problem? Please describe.**
What happens when event queue reaches its maximum of 10000 items? Minio stops saving events and they are lost.

**Describe the solution you'd like**
Remove limit for number of queued events.

**Comment by harshavardhana** [comment]
> **Is your feature request related to a problem? Please describe.**
> What happens when event queue reaches its maximum of 10000 items? Minio stops saving events and they are lost.
> 
> **Describe the solution you'd like**
> Remove limit for number of queued events.

You can increase the value to whatever number you want, there is no ulimited queue ever.

**Comment by starinacool** [comment]
With webhook minio reply that 10000 is the maximum

**Comment by harshavardhana** [comment]
> With webhook minio reply that 10000 is the maximum

Yes that is good enough, if your notification target is down for more than 100k entries then you have really other problems to fix and you don't really care about your notification target at that point.

100k events stored per node, so in a distributed setup it's N nodes multiplied by 100k

We won't fix unusual usecases, 100k is sufficient for all practical requirements.

**Comment by starinacool** [comment]
Here is the line: https://github.com/minio/minio/blob/bfec5fe200fda100ef811873cc3762384c8457ce/pkg/event/target/webhook.go#L74
