### ISSUE TITLE
[resolved] Bump up maxLimit magic number up to 1000000

### ISSUE THREAD

**Issue by starinacool** [minio/minio#9348]
I suggest to bump maxLimit to 1000000 at least or remove this limitation. 

On high loaded systems with a lot of uploads 10000 could be maxed out very quickly in case of problems with receiving side of notifications.

We already had this issue on a production system and events was lost.

https://github.com/minio/minio/blob/d48fd6fde96a05ab204f83219a7a0948f8bc0957/pkg/event/target/queuestore.go#L33

**Comment by harshavardhana** [comment]
Please send a PR if you want we shall accept. @starinacool 

PS: Next time please use the issue template to describe your issue appropriately, if it's a feature request use the feature request option.

**Comment by starinacool** [comment]
https://github.com/minio/minio/pull/9349

**Comment by harshavardhana** [comment]
Fixed in #9380 - thanks for the initial effort @starinacool
