### ISSUE TITLE
[wontfix] Bind minio service to two different ports

### ISSUE THREAD

**Issue by VladimirKhil** [minio/minio#9351]
**Is your feature request related to a problem? Please describe.**
I need to expose minio service at both ports 80 and 443. The reason that I cannot use only port 443 is because my client application does not work with HTTPS correctly. That cannot be fixed because it contains proprietary components for loading data. But it needs only read permissions on port 80. Write operations should be performed through port 443.

**Describe the solution you'd like**
An ability to provide two different ports via command line args.

**Describe alternatives you've considered**
Maybe it is safe to run two minio instances with different ports pointing to the same folder? I have not tried that.

**Comment by harshavardhana** [comment]
MinIO requires single port and single port it shall be for the near future. We shall not be doing this, not being able to use single port simply points to an architectural issue on your end. MinIO is not nginx like HTTP server to serve different assets on different ports either. So it is a design choice to keep it predictable and simple.

Currently there are no real requirements for these type of unusual setups from any of our customers, and any enterprise applications that we have found in the field.

We shall close this issue for now as won't fix.

**Comment by i0x71** [comment]
As a better workaround for your case, you could use a load balancer to listen to both ports.
Either sidekick listening on both ports or haproxy.

**Comment by socketpair** [comment]
What if I want to have authenticated PUTs using aws cli on HTTPS endpoint, but serve content without encryption using HTTP ?
