### ISSUE TITLE
Minio does not periodically check for etcd availability

### ISSUE THREAD

**Issue by jdheyburn** [minio/minio#9353]
**Is your feature request related to a problem? Please describe.**
Minio when running in gateway s3 mode (and I suppose others when etcd is enabled) only enables etcd mode when the endpoint is available on boot. When the etcd endpoint is subsequently available later the only way to get minio to enable etcd is to bounce minio.

**Describe the solution you'd like**
Minio should periodically check for etcd connectivity so that a bounce is not required.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Praveenrajmani** [comment]
We need etcd to be configured while starting up because it is needed for some boot loading work in MinIO. And restart is always needed in such cases to finish those jobs that were pending due to an inactive etcd.

**Comment by harshavardhana** [comment]
Once the initial bootstrap is done, etcd automatically reconnects there after.
