### ISSUE TITLE
[not our bug] MinIO Cluster encountered write error:Insufficient number of disks online.

### ISSUE THREAD

**Issue by donglinpeng** [minio/minio#9358]
MinIO Cluster with two zones encountered write error:Insufficient number of disks online while only one zone went well.

## Expected Behavior
All upload requests would be handled correctly.

## Current Behavior
Minio encountered write error:Insufficient number of disks online. About only one third objects were uploaded successfully.

## Steps to Reproduce (for bugs)
1. Setup 3 hosts with 32 sata disk each;
2.  minio server http://TEST-NODE00{4...6}/var/lib/minio/export{1...26}  http://TEST-NODE00{4...6}/var/lib/minio/export{27...32}
3. lanch cosbench with 3 drivers which direct 3 minio servers and running upload case.

## Context
cat > /etc/systemd/system/minio.service <<EOF
[Unit]
Description=Minio
Documentation=https://docs.minio.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/opt/minio/minio

[Service]
WorkingDirectory=/opt/minio/
User=minio
Group=minio
PermissionsStartOnly=true
# Specifies the maximum file descriptor number that can be opened by this process
EnvironmentFile=/opt/minio/envi-minio
ExecStart=/opt/minio/minio server $MINIO_OPTS $MINIO_VOLUMES
LimitNOFILE=65536
Restart=on-failure
RestartSec=3
StandardOutput=journal
StandardError=inherit
# Disable timeout logic and wait until process is stopped
TimeoutStopSec=infinity
# SIGTERM signal is used to stop Minio
KillSignal=SIGTERM
SendSIGKILL=no
SuccessExitStatus=0
[Install]
WantedBy=multi-user.target

cat > /opt/minio/envi-minio << EOF
MINIO_ACCESS_KEY="minio"
MINIO_SECRET_KEY="miniokey"
MINIO_STORAGE_CLASS_STANDARD=EC:2
MINIO_OPTS="--config-dir /etc/minio --address :9000"
MINIO_VOLUMES="http://TEST-NODE00{4...6}/var/lib/minio/export{1...26} http://TEST-NODE00{4...6}/var/lib/minio/export{27...32}"

cosbench script:
```
<?xml version='1.0' encoding='utf-8'?>
<workload name="put_4MB_object_test_with_60_workers">
        <workflow>
                <workstage name="put_4MB_object_test_with_60_workers">
                        <work driver="1x.xx.xx.19" name="put_4MB_object_work_0_with_20_workers" totalOps="60000" workers="20">
                                <storage config="timeout=30000;accesskey=minio;secretkey=miniokey;endpoint=http://TEST-NODE004:9000;retry=3" type="s3">
                                        </storage>
                                <operation config="cprefix=bck1;oprefix=60w_4MB_rgw_;containers=c(0);objects=s(1,20000);sizes=c(4)MB" ratio="100" type="write">
                                        </operation>
                        </work>
                        <work driver="1x.xx.xx.20" name="put_4MB_object_work_1_with_20_workers" totalOps="60000" workers="20">
                                <storage config="timeout=30000;accesskey=minio;secretkey=miniokey;endpoint=http://TEST-NODE005:9000;retry=3" type="s3">
                                        </storage>
                                <operation config="cprefix=bck2;oprefix=60w_4MB_rgw_;containers=c(0);objects=s(20001,40000);sizes=c(4)MB" ratio="100" type="write">
                                        </operation>
                        </work>
                        <work driver="1x.xx.xx.21" name="put_4MB_object_work_2_with_20_workers" totalOps="60000" workers="20">
                                <storage config="timeout=30000;accesskey=minio;secretkey=miniokey;endpoint=http://TEST-NODE006:9000;retry=3" type="s3">
                                        </storage>
                                <operation config="cprefix=bck3;oprefix=60w_4MB_rgw_;containers=c(0);objects=s(40001,60000);sizes=c(4)MB" ratio="100" type="write">
                                        </operation>
                        </work>
                </workstage>
        </workflow>
</workload>
```
## Regression
Yes, it can be reproduced.

## Your Environment

* Version used (`minio version`):
mc version RELEASE.2020-02-25T18-10-03Z
minio version RELEASE.2020-03-09T18-26-53Z

* Environment name and version (e.g. nginx 1.9.1): 
* Server type and version: 
Huawei 5288 V5 ;CPU Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz ;MEM:196GB 
* Operating System and version (`uname -a`):
Linux 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:
[InsufficientDisk.log](https://github.com/minio/minio/files/4484704/InsufficientDisk.log)
[mc-trace.log](https://github.com/minio/minio/files/4484705/mc-trace.log)

**Comment by harshavardhana** [comment]
@donglinpeng please upgrade to the latest and run this test again both minio and mc. Also, make sure that you have run `mc admin obd` first to capture what you system is capable of.

**Comment by donglinpeng** [comment]
Strangely，I used the newest minio(version RELEASE.2020-04-10T03-34-42Z) but got an ERROR :"Invalid command line arguments: Invalid set drive count. Acceptable values for 18 number drives are [6 9]" when start minio service with the same configuation.  As i know, minio accept max 16 drives as a erasure code set. I want to use erasure code size as 6 and set data/parity drives as 4/2.

**Comment by donglinpeng** [comment]
> @donglinpeng please upgrade to the latest and run this test again both minio and mc. Also, make sure that you have run `mc admin obd` first to capture what you system is capable of.

Strangely，I used the newest minio(version RELEASE.2020-04-10T03-34-42Z) but got an ERROR :"Invalid command line arguments: Invalid set drive count. Acceptable values for 18 number drives are [6 9]" when start minio service with the same configuation. As i know, minio accept max 16 drives as a erasure code set. I want to use erasure code size as 6 and set data/parity drives as 4/2.

**Comment by harshavardhana** [comment]
> > @donglinpeng please upgrade to the latest and run this test again both minio and mc. Also, make sure that you have run `mc admin obd` first to capture what you system is capable of.
> 
> Strangely，I used the newest minio(version RELEASE.2020-04-10T03-34-42Z) but got an ERROR :"Invalid command line arguments: Invalid set drive count. Acceptable values for 18 number drives are [6 9]" when start minio service with the same configuation. As i know, minio accept max 16 drives as a erasure code set. I want to use erasure code size as 6 and set data/parity drives as 4/2.

Correct in this scenario you need to make sure to set the DRIVE_COUNT because your deployment was incorrect, to begin with, for example, you don't need zones at all. Zones are meant for the expansion of the cluster. You have all the drives that are available to you across all the nodes. 

Splitting them across zones is pointless when your HA i.e your actual number of nodes has not increased. 

You should re-do your setup and deploy it appropriately to use all the drives that are available as 

```
http://TEST-NODE00{4...6}/var/lib/minio/export{1...32}
```

This allows for better distribution and maximum availability, zones are only meant for expansion for future needs - most of our customers hardly expand beyond single-zone due to high-density servers these days we have been able to deploy up to 40-50PiB in single cluster alone.

So when you have the drives and the nodes there is no point splitting them up. 

As you said you wanted to force the drive count - this needs to be done using `
MINIO_ERASURE_SET_DRIVE_COUNT=6` value which allows you to define the total erasure pack size.

**Comment by donglinpeng** [comment]
@harshavardhana thank you very much, it helps me a lot.
I modify file /opt/minio/envi-minio as follow:
```
MINIO_ACCESS_KEY="minio"
MINIO_SECRET_KEY="miniokey"
MINIO_STORAGE_CLASS_STANDARD=EC:2
MINIO_OPTS="--config-dir /etc/minio --address :9000"
MINIO_VOLUMES="http://TEST-NODE00{4...6}/var/lib/minio/export{1...20} http://TEST-NODE00{4...6}/var/lib/minio/export{21...30}"
```
I tested again using the newest minio and mc. The error "write error:Insufficient number of disks online " happens again but most objects were upload successfully. I totally upload 60000 objects and  14 objects weren't uploaded successfully.

obd info are as attachement i modify some Sensitive information.
[InsufficientDisk.log](https://github.com/minio/minio/files/4485999/InsufficientDisk.log)
[obd.log](https://github.com/minio/minio/files/4486000/obd.log)

**Comment by harshavardhana** [comment]
> ```
> MINIO_VOLUMES="http://TEST-NODE00{4...6}/var/lib/minio/export{1...20} http://TEST-NODE00{4...6}/var/lib/minio/export{21...30}"
> ```

This is still not correct @donglinpeng you should merge them together for appropriate distribution, this is not going to be a real-world scenario so you shouldn't test it this way. For real world testing of zones bring more servers.

**Comment by donglinpeng** [comment]
@harshavardhana I have to reopen this issue cause i reproduced it under the new setup and deploy it appropriately to use all the drives that are available as  http://TEST-NODE00{4...6}/var/lib/minio/export{1...32}.
There were some other errors such as "Error: dataUsageCache: unknown version: 102" or "Error: file not found".  It was confusing that cosbench's Succ-Ratio was 100% but actually 4 objects were uploaded failed. System log and mc obd info are as attachment.
![cosbench](https://user-images.githubusercontent.com/20284390/79570642-66968880-80ec-11ea-9aa8-65de832fa5da.png)
[InsufficientDisk.log](https://github.com/minio/minio/files/4492937/InsufficientDisk.log)
[minio-obd_20200417161752.txt](https://github.com/minio/minio/files/4492939/minio-obd_20200417161752.txt)

minio version RELEASE.2020-04-10T03-34-42Z
mc version RELEASE.2020-04-15T20-18-00Z

**Comment by klauspost** [comment]
Interesting. Is there a proxy defined on the system as indicated by the environment variables HTTP_PROXY, HTTPS_PROXY and NO_PROXY (or the lowercase versions thereof)?

It seems something is desync'ing HTTP calls between servers.

**Comment by klauspost** [comment]
Also check your system limits. A lot of disk tests tests fail with "resource temporarily unavailable" and "bad file descriptor".

**Comment by donglinpeng** [comment]
> Interesting. Is there a proxy defined on the system as indicated by the environment variables HTTP_PROXY, HTTPS_PROXY and NO_PROXY (or the lowercase versions thereof)?
> 
> It seems something is desync'ing HTTP calls between servers.

There is no proxy. I used 3 cosbench clients direct to the 3 minio server(one client points to a minio server)

**Comment by donglinpeng** [comment]
> Also check your system limits. A lot of disk tests tests fail with "resource temporarily unavailable" and "bad file descriptor".

I did some kernel tuning followed by "https://github.com/minio/minio/tree/master/docs/deployment/kernel-tuning".
ulimit -n returns 65535.
Filesystem inode info as follow:
![fs-inode](https://user-images.githubusercontent.com/20284390/79627285-8324d600-8169-11ea-9ca8-bdf32bddf7e3.png)

If you need other info ,please let me know, thank y !

**Comment by xoraingroup** [comment]
I am also getting same issue with distributed cluster. 

![image](https://user-images.githubusercontent.com/17129052/81495802-a8fe5000-92bb-11ea-951c-c42fc3b367be.png)


Even though mc commands show all disks as online. Also They are linked on same rack via 10G link. 

minio version RELEASE.2020-03-19T21-49-00Z

**Comment by harshavardhana** [comment]
> I am also getting same issue with distributed cluster.
> 
> ![image](https://user-images.githubusercontent.com/17129052/81495802-a8fe5000-92bb-11ea-951c-c42fc3b367be.png)
> 
> Even though mc commands show all disks as online. Also They are linked on same rack via 10G link.
> 
> minio version RELEASE.2020-03-19T21-49-00Z

Upgrade to latest and then run `mc admin obd` tests to see baseline performance of your network and see if things are slow.

**Comment by xoraingroup** [comment]
Sorry @harshavardhana , it was my mistake. It seemed the disks were not mounted and minio used local file system. You can disregard my comment. :)

**Comment by harshavardhana** [comment]
> Sorry @harshavardhana , it was my mistake. It seemed the disks were not mounted and minio used local file system. You can disregard my comment. :)

Closing this issue..
