### ISSUE TITLE
[working as intended] User Policy does not work without setting a bucket policy.

### ISSUE THREAD

**Issue by darkl0rd** [minio/minio#9361]
1. Create a bucket, "test"
2. Create a second user, named "test" and grant it access on bucket "test" with policy readonly

I would expect user 'test' to be able to see the content of bucket 'test'; the user does not see the content nor can it retrieve a file through the full path.

When I apply a policy to the bucket itself, allowing for anonymous access, for instance '* readonly' then the user (obviously) can list the content of the respective bucket. At this point the specific 'user' policy is also respected.

For instance:
bucket: */readonly
user: readwrite

User can now write in the bucket 'test'.

I really do not want to set a bucket wide policy allowing the "world" to list the contents of my bucket but only allow specific users to list the content. Is above behavior as intended, or is this actually a bug?

Running: minio version RELEASE.2020-04-15T19-42-18Z

**Comment by harshavardhana** [comment]
> I would expect user 'test' to be able to see the content of bucket 'test'; the user does not see the content nor can it retrieve a file through the full path.

That is not how it is buckets and users have no relationship without a policy - this is how AWS IAM requirements are implemented. This is not going to change and it is as per design. No users get access by default without a policy it is called implicit deny.

You can restrict users to specific buckets or prefixes you need to know how to write these policies https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html

https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html you can use variables to assign a single policy across all users which have access to buckets or prefixes which coincide with their user name. 

Bucket policies are not meant for users, they are meant to provide anonymous access and should be used only for assets that require public access.

**Comment by darkl0rd** [comment]
Clear, thanks.

However, I understand that I am unable to LIST the bucket with the default read-only policy which is defined like:

```
mc admin policy info myminio readonly
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "s3:GetBucketLocation",
    "s3:GetObject"
   ],
   "Resource": [
    "arn:aws:s3:::*"
   ]
  }
 ]
}
```

However, I would expect that the following user:

```
mc admin --json user list myminio
{
 "status": "success",
 "accessKey": "test",
 "policyName": "readonly",
 "userStatus": "enabled"
}
```

Could perform a GET of an object like so:

```
mc cp myminio-test/test/dummy-file /tmp
```

Instead this gives me:

```mc: <ERROR> Unable to validate source myminio-test/test/dummy-file```

**Comment by kannappanr** [comment]
so, with `mc cp`, we were also doing listing, and since this did not have that permission, it was failing. We are fixing this and the next release of mc will have this fix
