### ISSUE TITLE
[faq] migrating data with code

### ISSUE THREAD

**Issue by spinelsun** [minio/minio#9363]
Hi,

is there an option to migrate data between two server (e.g local minion and gcs ) with the python sdk?
I saw that it is possible via mc by using the mirror command but I can't find a way to that with code

**Comment by nitisht** [comment]
python SDK has no feature like mirror

**Comment by harshavardhana** [comment]
> is there an option to migrate data between two server (e.g local minion and gcs ) with the python sdk?
> I saw that it is possible via mc by using the mirror command but I can't find a way to that with code

mc mirror use minio-go to write the mirror functionality, with minio-py you need to write this logic yourself there is readily available abstraction that you can use. 

minio-py SDK's provide primitives for you to build such an application.

**Comment by spinelsun** [comment]
is there any option to migrate data between two servers without mirroring?

**Comment by harshavardhana** [comment]
> is there any option to migrate data between two servers without mirroring?

No @spinelsun

**Comment by spinelsun** [comment]
where can I find the implementation of the mirror command with go?

**Comment by harshavardhana** [comment]
> where can I find the implementation of the mirror command with go?

@spinelsun https://github.com/minio/mc/blob/master/cmd/mirror-main.go please join our https://slack.min.io to ask more questions
