### ISSUE TITLE
Minio scaling using Azure blob and Kubernetes

### ISSUE THREAD

**Issue by softwareyoga** [minio/minio#9367]
Based on [7986](https://github.com/minio/minio/issues/7986), I understand that Minio was initially not developed by keeping in mind the regular definition of scaling storage and nodes. You have added a comment in the end saying that it is now supported in distributed mode.

However, it appears to be a manual process by executing some commands.
Also, if I am not wrong, disks have to be still added so that total number of them are multiples of 4, 8 etc.

Requirement:
I have a use case wherein:

1. I have to use Azure blog as the storage and be able to add more storage. 
2. Minio instances themselves should be scalable to handle more traffic and will be automatically created or destroyed using Kubernetes. 

Questions:
1.  We want the ability to add one disk for example and disks not always multiples of 4, 8 etc. In this case, Is it possible that these new Minio instances make use of the newly added storage automatically ?

2. Also, it should be possible that all the K8 pods of Minio are able to query and operate on the data in all disks i.e. Minio pods should be able to see all data in all storage.

3. Is older data before the addition of new disks and nodes available after the upgrade? Or should it be backed up before and restored later?

**Comment by klauspost** [comment]
> We want the ability to add one disk for example and disks not always multiples of 4, 8 etc. In this case, Is it possible that these new Minio instances make use of the newly added storage automatically ?

Expansion of clusters are done by adding 'zones' of the same size as the base cluster, multiplying your cluster size by 2. See "Expanding existing distributed setup" here: https://docs.min.io/docs/distributed-minio-quickstart-guide.html

If you require more fine-grained control the only option is to move all your data to a fresh cluster.

> Also, it should be possible that all the K8 pods of Minio are able to query and operate on the data in all disks i.e. Minio pods should be able to see all data in all storage.

> Is older data before the addition of new disks and nodes available after the upgrade? Or should it be backed up before and restored later?

Adding new zones is a seamless operation and your cluster will remain fully operational, besides a server restart. New data will simply be distributed between the zones based on the amount of free disk space in each.

**Comment by softwareyoga** [comment]
Thanks for your reply @klauspost 

I want to clarify some aspects further.
1. Reading Minio documentation on distributes mode, there needs to be minimum of 4 disks so it translates into 4 nodes/pods. In my case using Kubernetes anti affinity configuration (i.e. only one instance of minio can run on a node), how can I use a 3 node cluster? Looks like that is impossible.

2. I see that there is "Minio Azure Gateway". Does it come work using the same principles as zones i.e. each addition should essentially double the size of the deployment? Does it not take into account the fact that Azure blob may be managed differently using the Azure console?

3. Is gateway available to use outside the [managed services](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/minio.minioblob?tab=Overview)?

**Comment by klauspost** [comment]
>  minimum of 4 disks

That is across the cluster, so you can have 3 nodes with 2 disks each for example.

> Does it come work using the same principles as zones

No, it provides an S3 API for Microsoft Azure Blob Storage. Everything is handled by Azure and the gateway merely translates the API calls.

Your other questions I don't have answers for.

**Comment by softwareyoga** [comment]
Can you point to someone who can answer ques 3.

Also, back to the distributed mode from the docs, 

> NOTE: Each zone you add must have the same erasure coding set size as the original zone, so the same data redundancy SLA is maintained.
> For example, if your first zone was 8 drives, you could add further zones of 16, 32 or 1024 drives each.

Is it not possible for the new zone to be 8 disks as well, does it have to be doubled each time i.e. the next zone needs to have 16 disks?

**Comment by kannappanr** [comment]
for new zones, the main criteria is that the new zone should have the same erasure set. You can have it as 8 drives also.  To answer your other question, gateway is available to use outside of managed services. Please reach out to us at https://slack.min.io for questions like these.
