### ISSUE TITLE
[faq] Clarification on minio distributed mode architecture

### ISSUE THREAD

**Issue by vclvm** [minio/minio#9368]
I've read distributed minio quick start guide but still confused about disks usage:

does distributed mode mean that I have to use same drives accessible on all minio instances like fiber channel attached, or my minio instances can have independent disks mounted in this mode? 
If I have independent drives attached to each minio instance will the file saved to one of them be spread across other instances disks, so even if I lose the first instance, that file be accessible through the remaining ones?

The main source of my confusion is this picture:
![Architecture-diagram_distributed_32](https://user-images.githubusercontent.com/26500813/79471581-79855c00-800b-11ea-9c1a-f61ad5b06a0b.png)
The arrows are spreading file across disks, without communication to other minio nodes, does this mean those disks must be directly attached to each node?

**Comment by klauspost** [comment]
The hosts do not need direct access to each others disks. This is purely handled by inter-server communication.

All servers are able to handle requests for all files and will contact other servers as needed.
