### ISSUE TITLE
[not a bug] Should return body when error happen!

### ISSUE THREAD

**Issue by honsunrise** [minio/minio#9371]
According to the API documentation of Amazon S3, the body should be returned.

https://github.com/minio/minio/blob/c50ae1fdbe599dbbc54c7c4c08056cef1ae24c9c/cmd/object-handlers.go#L443-L447

**Comment by harshavardhana** [comment]
It does in all the calls, head object doesn't need to return a body as head request has no body returned.

PS: please issue template to describe your issue properly.
