### ISSUE TITLE
[resolved] minio gateway s3 - per user authorization

### ISSUE THREAD

**Issue by tooptoop4** [minio/minio#9373]
Currently users can be LDAP authenticated to login to Minio browser and then they can upload/download/delete objects. Problem is there is nothing restricting what they can do once authenticated. I am looking to use Minio as like a per-user private dropbox. ie user Bob can only upload/download files to/from 'bob' folder. user Alice can only upload/download files to/from 'alice' folder. 

I would like to avoid setting policies on AWS side for any new user that comes along. Ie there could be 100s of users

For this feature I was thinking minio could be started with optional authorisation JSON: 
"per_user_s3_base_path": "s3://somebucket/part1/part2/part3/<USER>"

Then Minio knows to only allow the LDAP authenticated user's name to touch objects under their specific username folder under s3://somebucket/part1/part2/part3/. ie s3://somebucket/part1/part2/part3/bob/ for bob, s3://somebucket/part1/part2/part3/alice/ for alice

They should be denied from touching objects under any other path

**Comment by kannappanr** [comment]
i am not sure if this can be done, will check internally and let you know

**Comment by poornas** [comment]
@tooptoop4 , you could set a user or group policy or set a inline session policy - have you tried this? More documentation [here](https://github.com/minio/minio/blob/f4e779c964d8193d9b4ff6f10025b07d446dbc5d/docs/sts/ldap.md#configuring-adldap-on-minio). In gateway mode, you can set policies to users or groups if you have enabled [etcd](https://github.com/minio/minio/blob/master/docs/sts/etcd.md)

**Comment by tooptoop4** [comment]
@poornas it's not really clear how to achieve this. ie s3://somebucket/part1/part2/part3/bob/ for bob, s3://somebucket/part1/part2/part3/alice/ for Alice. Plus don't want to do any changes once a new user is added to the LDAP group. ie if next week Sarah joins the group, was hoping she could automatically use s3://somebucket/part1/part2/part3/sarah/

**Comment by harshavardhana** [comment]
> @poornas it's not really clear how to achieve this. ie s3://somebucket/part1/part2/part3/bob/ for bob, s3://somebucket/part1/part2/part3/alice/ for Alice. Plus don't want to do any changes once a new user is added to the LDAP group. ie if next week Sarah joins the group, was hoping she could automatically use s3://somebucket/part1/part2/part3/sarah/

All you need is to add in resources `somebucket/part1/part2/part3/${aws:username}` or in case of LDAP use `somebucket/part1/part2/part3/${jwt:ldapUser}`
