### ISSUE TITLE
Implement BucketTagging support

### ISSUE THREAD

**Issue by astorath** [minio/minio#9374]
When requesting a list of tags on non-existent bucket, Minio returns a list of one empty tag. Should have returned an empty list.

## Expected Behavior
`GET /bucket_name?tagging`

should return

`<Tagging><TagSet></TagSet></Tagging>`

## Current Behavior

`GET /bucket_name?tagging`

returns

`<Tagging><TagSet><Tag></Tag></TagSet></Tagging>`

## Your Environment

* Version used (`minio version`):
```
[andrey@minio-sandbox ~]$ /opt/minio/bin/minio --version
minio version RELEASE.2020-04-15T19-42-18Z
```
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
```
[andrey@minio-sandbox ~]$ uname -a
Linux minio-sandbox 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
* Link to your project:

**Comment by harshavardhana** [comment]
> `<Tagging><TagSet><Tag></Tag></TagSet></Tagging>`

What is the problem here @astorath ?  we do not implement bucket tagging yet. So this is a dummy call.

**Comment by kannappanr** [comment]
In the case of non-existent bucket. I do not see tags being returned for both MinIO and AWS S3.

In the case of AWS S3 it is 

```
<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>nonexistentbucket</BucketName><RequestId>4D9678C54614037E</RequestId><HostId>v160o4Fj3Fjja50JGv6evjiOB5Sq8i2vgVoLlATqttTTKeujHqwqwjTA638r0yxtdu69P3pdWUg=</HostId></Error>
```
Testing the same on play

```
<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>nonexistentbucket</BucketName><Resource>/testwewew</Resource><RequestId>16067525C417B15E</RequestId><HostId>96fa3866-7ee6-4546-87d9-4283e3def6c3</HostId></Error>
```

**Comment by kannappanr** [comment]
I believe we added this return to support some other application that was expecting it in this format, on a bucket that exists. We will add bucket tagging API soon and that would return results just like what AWS would. Closing this issue for now.

**Comment by astorath** [comment]
> I believe we added this return to support some other application that was expecting it in this format, on a bucket that exists. We will add bucket tagging API soon and that would return results just like what AWS would. Closing this issue for now.

The problem is, due to this bug, ansible is unable to manage minio buckets anymore, it crushes on receiving an empty tag (not empty list, but empty tag)

@kannappanr @harshavardhana

**Comment by harshavardhana** [comment]
> The problem is, due to this bug, ansible is unable to manage minio buckets anymore, it crushes on receiving an empty tag (not empty list, but empty tag)
> 
> @kannappanr @harshavardhana

We will fix it soon @astorath there is nothing that can be done right now. This looks like an Ansible bug since XML tags can have empty values.

**Comment by astorath** [comment]
Yes, XML can have empty values, but tag name and tag value cannot be both empty - this fails validation check. Can we at least leave the issue open, cause it's a bug - current behaviour differs from s3 and causes issues.

**Comment by harshavardhana** [comment]
> Yes, XML can have empty values, but tag name and tag value cannot be both empty - this fails validation check. Can we at least leave the issue open, cause it's a bug - current behaviour differs from s3 and causes issues.

Sure we can @astorath we shall rename this issue as implement `Bucket Tagging support`
