### ISSUE TITLE
Snapshots

### ISSUE THREAD

**Issue by i0x71** [minio/minio#9376]
Snapshots right! Would be great to have them!
You know in case if some bucket gets deleted accidentally, or the medium between the keyboard and the chair deletes some files accidentally.
The only other viable alternative I can see is using rclone to keep an identical copy in the cloud which will be taking up identical amount of space ?
Is this perhaps that something was considered at some point ?

Other suggestions are welcome also.
Thank you

**Comment by harshavardhana** [comment]
We will be implementing versioning @i0x71 not snapshots this is AWS S3 compatible API #2111
