### ISSUE TITLE
[resolved] Invalid according to Policy: Policy Condition failed<

### ISSUE THREAD

**Issue by zth390872451** [minio/minio#9382]
## Current Behavior

curl --location --request POST 'https://file.sw.elari.systems/elari' \
--header 'Content-Type: multipart/form-data; ' \
--form 'X-Amz-Credential=umeox/20200417/us-east-1/s3/aws4_request' \
--form 'X-Amz-Algorithm=AWS4-HMAC-SHA256' \
--form 'X-Amz-Date=20200417T082258Z' \
--form 'Policy=eyJleHBpcmF0aW9uIjoiMjAyMC0wNC0yMlQwODoyMjo1OC4wMDBaIiwiY29uZGl0aW9ucyI6W3siYnVja2V0IjoiZWxhcmkifSx7ImFjbCI6InB1YmxpYy1yZWFkIn0seyJ4LWFtei1jcmVkZW50aWFsIjoidW1lb3gvMjAyMDA0MTcvdXMtZWFzdC0xL3MzL2F3czRfcmVxdWVzdCJ9LHsieC1hbXotYWxnb3JpdGhtIjoiQVdTNC1ITUFDLVNIQTI1NiJ9LHsieC1hbXotZGF0ZSI6IjIwMjAwNDE3VDA4MjI1OFoifSx7InN1Y2Nlc3NfYWN0aW9uX3N0YXR1cyI6IjIwMCJ9LFsic3RhcnRzLXdpdGgiLCIka2V5IiwiIl1dfQ==' \
--form 'X-Amz-Signature=ac54cb9b28370c415419b8fc12bff379b2e0c063d537f11ddcaab28986aa6185' \
--form 'file=@/C:/Users/pc/Pictures/1112442.png'

## Possible Solution
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AccessDenied</Code>
    <Message>Invalid according to Policy: Policy Condition failed</Message>
    <BucketName>elari</BucketName>
    <Resource>/elari</Resource>
    <RequestId>16068FE8EC5AC540</RequestId>
    <HostId>d9ab8076-c245-4ad7-9af4-c07dca273921</HostId>
</Error>

## Steps to Reproduce (for bugs)
1.use postman to upload file

**Comment by harshavardhana** [comment]
Please provide MinIO version, full reproducible steps i.e client code.

We will close this issue for now, please reopen with relevant information.

**Comment by zth390872451** [comment]
minio version RELEASE.2020-03-14T02-21-58Z 
I used the sdk jar upload file success:
`
<groupId>io.minio</groupId>
<artifactId>minio</artifactId>			
<version>6.0.8</version> 
`
but I tried to upload file failed bu use the postman.
I had use the same code to upload file success a few months ago by the postman client through the old minio server version :RELEASE.2019-07-05T21-20-21Z.

**Comment by harshavardhana** [comment]
> minio version RELEASE.2020-03-14T02-21-58Z
> I used the sdk jar upload file success:
> `<groupId>io.minio</groupId> <artifactId>minio</artifactId> <version>6.0.8</version> `
> but I tried to upload file failed bu use the postman.
> I had use the same code to upload file success a few months ago by the postman client through the old minio server version :RELEASE.2019-07-05T21-20-21Z.

Use the latest release, with latest Java version and let us know.

**Comment by zth390872451** [comment]
> > minio version RELEASE.2020-03-14T02-21-58Z
> > I used the sdk jar upload file success:
> > `<groupId>io.minio</groupId> <artifactId>minio</artifactId> <version>6.0.8</version> `
> > but I tried to upload file failed bu use the postman.
> > I had use the same code to upload file success a few months ago by the postman client through the old minio server version :RELEASE.2019-07-05T21-20-21Z.
> 
> Use the latest release, with latest Java version and let us know.

I used the latest version is the same problem,but I use the sdk client upload success.
I use the postman to upload thoes files

**Comment by zth390872451** [comment]
I use the cmd: mc admin trace -v -a minio,find the log like this:
```
10.129.0.24 [REQUEST s3.PostPolicyBucket] 08:07:57.862
10.129.0.24 POST /elari
10.129.0.24 Host: file.sw.elari.systems
10.129.0.24 Content-Length: 1065722
10.129.0.24 Content-Type: multipart/form-data; boundary=--------------------------939851851015933146106107
10.129.0.24 User-Agent: PostmanRuntime/7.24.1
10.129.0.24 Cache-Control: no-cache
10.129.0.24 Connection: close
10.129.0.24 X-Forwarded-For: 183.14.31.161
10.129.0.24 X-Forwarded-Proto: https
10.129.0.24 X-Real-Ip: 183.14.31.161
10.129.0.24 Accept: */*
10.129.0.24 Accept-Encoding: gzip, deflate, br
10.129.0.24 <BODY>
10.129.0.24 [RESPONSE] [08:07:57.862] [ Duration 4.431ms  ↑ 1.0 MiB  ↓ 587 B ]
10.129.0.24 403 Forbidden
10.129.0.24 Server: MinIO/RELEASE.2020-04-15T19-42-18Z
10.129.0.24 Vary: Origin
10.129.0.24 X-Amz-Bucket-Region: us-east-1
10.129.0.24 X-Xss-Protection: 1; mode=block
10.129.0.24 Accept-Ranges: bytes
10.129.0.24 Content-Type: application/xml
10.129.0.24 X-Amz-Request-Id: 16072A186084A46B
10.129.0.24 Content-Length: 299
10.129.0.24 Content-Security-Policy: block-all-mixed-content
10.129.0.24 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Invalid according to Policy: Policy Condition failed</Message><BucketName>elari</BucketName><Resource>/elari</Resource><RequestId>16072A186084A46B</RequestId><HostId>e83d36c4-8c4e-46e6-80ae-59c85e6220ca</HostId></Error>
10.129.0.24 
10.129.0.24 [REQUEST internal.Expired] 08:07:59.768
10.129.0.24 POST /minio/lock/minio1/data1/v3/expired?source=&uid=b742fede-bc87-454f-9108-8cc827d59fe7
10.129.0.24 Host: 10.129.0.24:9000
10.129.0.24 Content-Length: 18
10.129.0.24 User-Agent: Go-http-client/1.1
10.129.0.24 X-Minio-Time: 2020-04-19T08:07:59Z
10.129.0.24 Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJ1bWVveCIsImF1ZCI6InNvdXJjZT1cdTAwMjZ1aWQ9Yjc0MmZlZGUtYmM4Ny00NTRmLTkxMDgtOGNjODI3ZDU5ZmU3IiwiZXhwIjoxNTg3Mjg0NTc5LCJzdWIiOiJ1bWVveCJ9.Shf5sXHikFyvRO9_XPc65ZnapJy5ANCa-ORoZdz7-E6HQLb4_vTh5fj7tLQfJ2dz8uvohj-p-i40PaxuVO8PMg
10.129.0.24 .minio.sys/leader
```

**Comment by zth390872451** [comment]
> > minio version RELEASE.2020-03-14T02-21-58Z
> > I used the sdk jar upload file success:
> > `<groupId>io.minio</groupId> <artifactId>minio</artifactId> <version>6.0.8</version> `
> > but I tried to upload file failed bu use the postman.
> > I had use the same code to upload file success a few months ago by the postman client through the old minio server version :RELEASE.2019-07-05T21-20-21Z.
> 
> Use the latest release, with latest Java version and let us know.

I soloved the problem,I add the varible: success_action_status=200,then upload files is ok,when I remove the success_action_status,it failed.
I remmmer it is Unnecessary variables before,why it must now?
