### ISSUE TITLE
GCS: Return correct error message when wrong location is used in makeBucket

### ISSUE THREAD

**Issue by flokli** [minio/minio#9391]
This is a copy of #6931, which was closed due to inactivity and marked as resolved, while it's not yet resolved, but should be kept in the "Future" milestone.

cc @kannappanr as the original author.

if `us-west-1` is used for location, then the error sent to the client is `InvalidBucketName`, though the failure is because of invalid location. Correct error should be sent to the client.

## Expected Behavior
makeBucket should fail with Invalid Region error

## Current Behavior
makeBucket fails with InvalidBucketName

## Steps to Reproduce (for bugs)
```py
from minio import Minio
from minio.error import ResponseError

client = Minio('192.168.1.70:9000',
               access_key='minio',
               secret_key='minio123',
	       secure=False)

# Make a new bucket
try:
    client.make_bucket('bucket-name', 'us-east-2')
except ResponseError as err:
    print(err)
```

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
Moving to lower priority GCS gateway is in maintenance mode not taking any new feature requests, feel free to send the PR to fix this @flokli

**Comment by flokli** [comment]
Hm, I still think this was originally a bug report, and not a feature request, and think the original issue shouldn't have been closed as "resolved" - it is a bug users run into.

However, I also got enough stuff on my plate, and worked it around, so if you don't intend to fix the issue, I can very well just close this issue.
