### ISSUE TITLE
PutObject on Minio server on Windows does not support long file name

### ISSUE THREAD

**Issue by NMD49** [minio/minio#9393]
PutObject on Minio server on Windows does not support long file name

## Expected Behavior

PutObject should handle Key length up to 1024 bytes.

## Current Behavior

PutObject fail even if Key length is under 1024 bytes.

minio version RELEASE.2020-04-15T19-42-18Z

API: PutObject(bucket=securisauve, object=data/G_792/srv-tse/c/users/denis/documents/gestion!20locative/heritier/propri!E9taire/20190101_a2.03!20-!20m.!20heritier!20re!B4mi!20-!20proce!60s-verbal!20de!20livraison!20et!20de!20remise!20des!20cle!B4s!20acque!B4reurs!20-!204-!20livraison!20-!20lp!20promotion!20toulouse!20-!20encre!20et!20plume!20-!205!20de!B4c.!202019!20a!60!2012-49.pdf.ecc)
Time: 16:49:58 CEST 04/18/2020
DeploymentID: 9a6de223-7664-4566-9fab-f81833b1c77c
RequestID: 1606F173ED7A0BD8
RemoteHost: 127.0.0.1
Host: 127.0.0.1:9000
Error: file name too long
       4: github.com\minio\minio@\cmd\fs-v1.go:946:cmd.(*FSObjects).putObject()
       3: github.com\minio\minio@\cmd\fs-v1.go:887:cmd.(*FSObjects).PutObject()
       2: github.com\minio\minio@\cmd\object-handlers.go:1387:cmd.objectAPIHandlers.PutObjectHandler()
       1: net\http\server.go:2007:http.HandlerFunc.ServeHTTP()
       
On client side, the error returned is "400 Bad Request : XMinioInvalidObjectName Object name contains unsupported characters."

## Possible Solution

Use of the prefix "\\?\" with absolute path
https://docs.microsoft.com/fr-fr/windows/win32/fileio/naming-a-file#maximum-path-length-limitation

See : https://github.com/golang/go/issues/18468

If Minio handle long file name, it must not use relative path.

There is no error on Linux.

## Steps to Reproduce (for bugs)

PutObject("data/G_792/srv-tse/c/users/denis/documents/gestion!20locative/heritier/propri!E9taire/20190101_a2.03!20-!20m.!20heritier!20re!B4mi!20-!20proce!60s-verbal!20de!20livraison!20et!20de!20remise!20des!20cle!B4s!20acque!B4reurs!20-!204-!20livraison!20-!20lp!20promotion!20toulouse!20-!20encre!20et!20plume!20-!205!20de!B4c.!202019!20a!60!2012-49.pdf.ecc")

## Your Environment

* Version used (`minio version`):
minio version RELEASE.2020-04-15T19-42-18Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
Windows 10
* Link to your project:

**Comment by ig-sinicyn** [comment]
UP:)
We've met same error, but under linux container (run via docker desktop).
container:
```
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - ${MINIO_PORT}:9000
    tmpfs: /data:size=1G
    environment:
      MINIO_ACCESS_KEY: ${MINIO_CLIENT_ID}
      MINIO_SECRET_KEY: ${MINIO_CLIENT_SECRET}
    command: server /data
```

container log:
```
 You are running an older version of MinIO released 3 weeks ago 
 Update: docker pull minio/minio:RELEASE.2020-04-15T19-42-18Z 


Attempting encryption of all config, IAM users and policies on MinIO backend
Endpoint:  http://172.26.0.2:9000  http://127.0.0.1:9000

Browser Access:
   http://172.26.0.2:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

API: PutObject(bucket=ce258cff734445d5b50a227d7eba5d89, object=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA)
Time: 14:29:21 UTC 04/20/2020
DeploymentID: f2171c04-d69f-4528-aa0b-6566601be562
RequestID: 16078D7CF470DB8F
RemoteHost: 172.26.0.1
Host: localhost:9000
UserAgent: MinIO (Microsoft Windows 10.0.18363;X64) minio-dotnet/1.0.9
Error: file name too long
       6: cmd/fs-v1.go:769:cmd.(*FSObjects).getObjectInfo()
       5: cmd/fs-v1.go:803:cmd.(*FSObjects).getObjectInfoWithLock()
       4: cmd/fs-v1.go:814:cmd.(*FSObjects).GetObjectInfo()
       3: cmd/object-lock.go:173:cmd.checkPutObjectLockAllowed()
       2: cmd/object-handlers.go:1338:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()

API: HeadObject(bucket=be97e2e23f444356b360d52b0c045f6c, object=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA)
Time: 14:31:19 UTC 04/20/2020
DeploymentID: f2171c04-d69f-4528-aa0b-6566601be562
RequestID: 16078D987E3E56A6
RemoteHost: 172.26.0.1
Host: localhost:9000
UserAgent: MinIO (Microsoft Windows 10.0.18363;X64) minio-dotnet/1.0.9
Error: file name too long
       5: cmd/fs-v1.go:769:cmd.(*FSObjects).getObjectInfo()
       4: cmd/fs-v1.go:803:cmd.(*FSObjects).getObjectInfoWithLock()
       3: cmd/fs-v1.go:814:cmd.(*FSObjects).GetObjectInfo()
       2: cmd/object-handlers.go:531:cmd.objectAPIHandlers.HeadObjectHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```

**Comment by harshavardhana** [comment]
We rely on Go to do the translation for the UNC path, if they don't we do not do anything specifically.  If you have long file names which may not be supported on windows use Linux server as alternative which supports longer file names.

**Comment by NMD49** [comment]
@harshavardhana 
Long file name is supported on Windows and Go when using \\\\?\\ prefix.
Please see this thread for example : [https://github.com/golang/go/issues/21782].
My company uses Windows and I can't impose Linux.
How can Minio claim to be Windows compatible if it doesn't allow a key name with 1024 characters?

**Comment by vadmeste** [comment]
This is also reproducible under Linux

@harshavardhana do you know why each segment in a path should not exceed 255 characters ?

**Comment by harshavardhana** [comment]
> This is also reproducible under Linux
> 
> @harshavardhana do you know why each segment in a path should not exceed 255 characters ?

Yes that is posix limitation @vadmeste

**Comment by harshavardhana** [comment]
> @harshavardhana 
> Long file name is supported on Windows and Go when using \\\\?\\ prefix.
> Please see this thread for example : [https://github.com/golang/go/issues/21782].
> My company uses Windows and I can't impose Linux.

That is unfortunate.

> How can Minio claim to be Windows compatible if it doesn't allow a key name with 1024 characters?
> 

Correct they do Go auto translates this for us, if they don't not sure why they dont. 

AWS S3 spec doesn't support keys beyond 1024 while Windows may support it.

**Comment by harshavardhana** [comment]
AFAIK this is not a bug here instead backend limitation either use Linux, or wait for us to reproduce this and fix it ourselves in future for Windows - of course you won't be able to use more than 1024 characters.

Linux limitations are already explained. @vadmeste

**Comment by NMD49** [comment]
@harshavardhana Thank you. Use of \\\\?\\ prefix with an absolute path on Windows should solve this issue. OK I do not ask to use more than 1024 characters. It's a pity that the priority is low because it's blocking for us.

**Comment by harshavardhana** [comment]
> @harshavardhana Thank you. Use of \\\\?\\ prefix with an absolute path on Windows should solve this issue. OK I do not ask to use more than 1024 characters. It's a pity that the priority is low because it's blocking for us.

I definitely know the fix, in-fact we worked with upstream Go to address the UNC path issues in Go1.9 and Go1.10

The problem is not that simple and is quite complicated due to UNC specification has been vague about specific characters.

We will try to debug this further when we are free from our other internal priorities.

**Comment by ig-sinicyn** [comment]
@harshavardhana, thanks for explanation!

Could you confirm that minio uses underlying system apis to validate object keys?
If this is true, there's mismatch between current logic and [S3 specification](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html)

> These names are the object keys. The name for a key is a sequence of Unicode characters whose 
UTF-8 encoding is at most 1,024 bytes long.

Most of file systems do not allow path segments longer than 255 symbols. This means that we cannot use long object identifiers (A...A x500, as example) that are valid for S3 storage.

**Comment by harshavardhana** [comment]
> @harshavardhana, thanks for explanation!
> 
> Could you confirm that minio uses underlying system apis to validate object keys?

MinIO doesn't do any translation or further encoding of the incoming path, it is stored as is on the backend filesystem.

> If this is true, there's mismatch between current logic and [S3 specification](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html)
> 

I have to disagree read further on implications,   on Windows there is a difference in behavior it's different because of the unexpected UNC path behavior for certain key names such as when characters have `!` in them etc.

> > These names are the object keys. The name for a key is a sequence of Unicode characters whose 
> UTF-8 encoding is at most 1,024 bytes long.
> 
> Most of file systems do not allow path segments longer than 255 symbols. This means that we cannot use long object identifiers (A...A x500, as example) that are valid for S3 storage.

You cannot do that, the intention is 255/255/255/255/ satisfies 1024 for path segments and key itself can be as long as 1024 . On Linux the limit is 4096 so it a
Is always well within the limits. 1024 is a flat length value so `/` is included as part of the key length.

So what is not supported is of this form 255/500/255..

The reasoning here is such that, if you have keys longer than this can never ever be backed up or ever saved back to any sane filesystem without further transformation of those key names.

So practically speaking Unix limits are suitable for all well written enterprise applications such as Splunk, Hadoop S3A, Druid, NiFi and a countless others.. that we have tested over the last 6yrs. So even when AWS allows this their recommendation is to follow best practices (here you can shoot yourself in the foot). In case of MinIO best practice is the default behavior. 

We are not trying to implement everything for the sake of compatibility with S3 in whatever manner possible, we always do what is practically suitable first and which allows us to simple, maintainable in the long run.

**Comment by ig-sinicyn** [comment]
Ok, I think I got it:)
Thanks again for very detailed response!
