### ISSUE TITLE
minio cluster download performance degraded obviously when client concurrent workers reached at 60.

### ISSUE THREAD

**Issue by donglinpeng** [minio/minio#9395]
minio cluster download performance degraded obviously when client concurrent workers reached at 60 and there also were many page allocation failure messages in the system log.

## Expected Behavior
Minio cluster should performance well or degrade slightly.

## Possible Solution
Could you give me some suggestion?

## Steps to Reproduce (for bugs)
1.  set up minio cluster using 3 servers with 32 disks each(actually 33 disks )
2.  upload 60000 objects of 40,000 Bytes. 
3.  lanch cosbench with 3 drivers which direct 3 minio servers and run download cases.
4.  when cosbench concurrent workers reached at 60(each minio server) minio cluster download performance degraded obviously, 

## Context
cat > /etc/systemd/system/minio.service <<EOF
```
[Unit]
Description=Minio
Documentation=https://docs.minio.io
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/opt/minio/minio

[Service]
WorkingDirectory=/opt/minio/
User=minio
Group=minio
PermissionsStartOnly=true
EnvironmentFile=/opt/minio/envi-minio
ExecStart=/opt/minio/minio server $MINIO_OPTS $MINIO_VOLUMES
LimitNOFILE=65536
Restart=on-failure
RestartSec=3
StandardOutput=journal
StandardError=inherit
TimeoutStopSec=infinity
KillSignal=SIGTERM
SendSIGKILL=no
SuccessExitStatus=0
[Install]
WantedBy=multi-user.target
```

cat > /opt/minio/envi-minio << EOF
```
MINIO_ACCESS_KEY="minio"
MINIO_SECRET_KEY="miniokey"
MINIO_ERASURE_SET_DRIVE_COUNT=4
MINIO_OPTS="--config-dir /etc/minio --address :9000"
MINIO_VOLUMES="http://TEST-NODE00{4...6}/var/lib/minio/export{1...32}"
```
cosbench download scripts
```
<?xml version='1.0' encoding='utf-8'?>
<workload name="get_4MB_object_test_with_180_workers">
        <workflow>
                <workstage name="get_4MB_object_test_with_180_workers">
                        <work driver="1xx.xx.xx.19" interval="1" name="get_4MB_object_work_0_with_60_workers" totalOps="60000" workers="60">
                                <storage config="timeout=1800000;accesskey=minio;secretkey=miniokey;endpoint=http://1xx.xx.xx.22:9000;retry=3" type="s3">
                                        </storage>
                                <operation config="cprefix=bck1;oprefix=180w_4MB_rgw_;containers=c(0);objects=s(1,20000)" ratio="100" type="read">
                                        </operation>
                        </work>
                        <work driver="1xx.xx.xx.20" interval="1" name="get_4MB_object_work_1_with_60_workers" totalOps="60000" workers="60">
                                <storage config="timeout=1800000;accesskey=minio;secretkey=miniokey;endpoint=http://1xx.xx.xx.23:9000;retry=3" type="s3">
                                        </storage>
                                <operation config="cprefix=bck2;oprefix=180w_4MB_rgw_;containers=c(0);objects=s(20001,40000)" ratio="100" type="read">
                                        </operation>
                        </work>
                        <work driver="1xx.xx.xx.21" interval="1" name="get_4MB_object_work_2_with_60_workers" totalOps="60000" workers="60">
                                <storage config="timeout=1800000;accesskey=minio;secretkey=miniokey;;endpoint=http://1xx.xx.xx.24:9000;retry=3" type="s3">
                                        </storage>
                                <operation config="cprefix=bck3;oprefix=180w_4MB_rgw_;containers=c(0);objects=s(40001,60000)" ratio="100" type="read">
                                        </operation>
                        </work>
                </workstage>
        </workflow>
</workload>
```

## Regression
Yes, even thought  restart minio service.

## Your Environment
minio version RELEASE.2020-04-10T03-34-42Z
mc version RELEASE.2020-04-15T20-18-00Z
No proxy.
3 cosbench driver points to 3 minio server directly.
OS :Linux 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
each server has 2*10GE bond mode 4 with xmit_hash_policy as "layer2+3 2"
mc obd info:
[minio-obd.log](https://github.com/minio/minio/files/4504141/minio-obd.log)
System log:
[PAF.log](https://github.com/minio/minio/files/4504142/PAF.log)

Minio perfermance well when client had 60 concurrent workers(20 workers each cosbench driver)
![60 workers](https://user-images.githubusercontent.com/20284390/79764214-a8773700-8357-11ea-98e7-78dfd0dea153.png)

**Comment by donglinpeng** [comment]
More Info:
Minio server mem is 196GB.
vm.min_free_kbytes=2097152
did kernel tunning according to https://github.com/minio/minio/tree/master/docs/deployment/kernel-tuning.
During download, mem status were as follow:
![mem_info](https://user-images.githubusercontent.com/20284390/79814133-15b6b680-83b0-11ea-95a3-b952d0031f03.png)

**Comment by eco-minio** [comment]
@donglinpeng these look like environmental issues that are a bit out of scope for community support, one example is that there appear to be many stack traces in the PAF.log.  We do have a paid offering you can look into here - https://min.io/pricing - which includes real time support for such issues.  cc // @GarimaKapoor
