### ISSUE TITLE
If no CORS set, Minio should reply with 404 instead of sending an empty CORSConfiguration

### ISSUE THREAD

**Issue by fviard** [minio/minio#9396]
When no CORS is set for a bucket, Minio will send the following reply content:
```
{'data': b'<CORSConfiguration></CORSConfiguration>',
```
Instead of sending a `404 (Not Found)` response as expected for any available sub-resources

(The request is: `/mybucket/?cors`)

## Expected Behavior
Response with a 404 status code.

Visible with s3cmd info:
```
s3://mybucket/ (bucket):
   Location:  eu-central-1
   Payer:     BucketOwner
   Expiration Rule: none
   Policy:    none
   CORS:      none
   ACL:       abcde...42: FULL_CONTROL
```

## Current Behavior
An empty CORSConfiguration is sent.

Visible with s3cmd info:
```
s3://mybucket/ (bucket):
   Location:  us-east-1
   Payer:     none
   Expiration Rule: none
   Policy:    none
   CORS:      <CORSConfiguration></CORSConfiguration>
   ACL:       CanonicalUser: FULL_CONTROL

```

## Steps to Reproduce (for bugs)
1. (Good) s3cmd -c aws_s3.config info s3://mybucket
2. (Bad) s3cmd -c minio_s3.config info s3://mybucket

## Regression
Is this issue a regression? No

## Your Environment
minio version RELEASE.2020-03-14T02-21-58Z
Linux

**Comment by harshavardhana** [comment]
@fviard we are not planning to support this MinIO supports CORS by default on all buckets there is no special configuration required.

In AWS this is a special requirement because they run a proxy in-front of your buckets to support CORS. 

So you may expect it to always return 200 OK in the near future.

**Comment by fviard** [comment]
As I said, to support it or not is not the question here.

If you don't support it, you are supposed to return the following http error when the client do a GET request for this sub-resource:
501 (Not supported)

Alternatively, if you kind of prefer to pretend that I is supported, even if it not usable in any way, you should reply with a http 404 (Not found) error, so that would mean to the client that:
"No CORS rule" set.

**Comment by harshavardhana** [comment]
I already explained in another issue why it won't be done @fviard
