### ISSUE TITLE
[resolved] Run container as non-root user

### ISSUE THREAD

**Issue by acim** [minio/minio#9398]
**Is your feature request related to a problem? Please describe.**
Minio [Dockerfile](https://hub.docker.com/r/minio/minio/dockerfile) doesn't switch to non-root user before the binary is started.

**Describe the solution you'd like**
It should create a normal user and switch to it as soon as possible and this is almost immediately in the main image, as I would say after a quick look. 

**Additional context**
OpenShift for example would not allow Minio to run as this. The same applies for Kubernetes clusters with PodSecurityPolicy which disallows run of containers under root user.

**Comment by harshavardhana** [comment]
@acim you just need to run it either as `--user` or use `MINIO_USERNAME, MINIO_GROUPNAME, MINIO_UID, MINIO_GID` feature. 

We already support this anyways.

**Comment by harshavardhana** [comment]
Clearly mentioned here how to do it

### Run MinIO Docker as a regular user
Docker provides standardized mechanisms to run docker containers as non-root users.

#### GNU/Linux and macOS
On Linux and macOS you can use `--user` to run the container as regular user.

> NOTE: make sure --user has write permission to *${HOME}/data* prior to using `--user`.
```sh
mkdir -p ${HOME}/data
docker run -p 9000:9000 \
  --user $(id -u):$(id -g) \
  --name minio1 \
  -e "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE" \
  -e "MINIO_SECRET_KEY=wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY" \
  -v ${HOME}/data:/data \
  minio/minio server /data
```

**Comment by acim** [comment]
I am running this in Kubernetes and I installed it using [Helm chart](https://github.com/helm/charts/tree/master/stable/minio). I could add these extra arguments by extraArgs, but container created by your [Dockerfile](https://hub.docker.com/r/minio/minio/dockerfile) doesn't have any special user to use. Here is the output of the /etc/passwd:

```
root:x:0:0:root:/root:/bin/ash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
news:x:9:13:news:/usr/lib/news:/sbin/nologin
uucp:x:10:14:uucp:/var/spool/uucppublic:/sbin/nologin
operator:x:11:0:operator:/root:/sbin/nologin
man:x:13:15:man:/usr/man:/sbin/nologin
postmaster:x:14:12:postmaster:/var/spool/mail:/sbin/nologin
cron:x:16:16:cron:/var/spool/cron:/sbin/nologin
ftp:x:21:21::/var/lib/ftp:/sbin/nologin
sshd:x:22:22:sshd:/dev/null:/sbin/nologin
at:x:25:25:at:/var/spool/cron/atjobs:/sbin/nologin
squid:x:31:31:Squid:/var/cache/squid:/sbin/nologin
xfs:x:33:33:X Font Server:/etc/X11/fs:/sbin/nologin
games:x:35:35:games:/usr/games:/sbin/nologin
postgres:x:70:70::/var/lib/postgresql:/bin/sh
cyrus:x:85:12::/usr/cyrus:/sbin/nologin
vpopmail:x:89:89::/var/vpopmail:/sbin/nologin
ntp:x:123:123:NTP:/var/empty:/sbin/nologin
smmsp:x:209:209:smmsp:/var/spool/mqueue:/sbin/nologin
guest:x:405:100:guest:/dev/null:/sbin/nologin
nobody:x:65534:65534:nobody:/:/sbin/nologin
```
Of course I can make my Dockerfile and fix this by adding (in Alpine version):

RUN adduser -D minio
USER minio

but this means that everyone using Helm chart and your official image would need to do. My opinion is that it should run as non-root out of the box, so the right place to modify it would be [here](https://github.com/minio/minio/blob/master/Dockerfile).

**Comment by harshavardhana** [comment]
> I am running this in Kubernetes and I installed it using [Helm chart](https://github.com/helm/charts/tree/master/stable/minio). I could add these extra arguments by extraArgs, but container created by your [Dockerfile](https://hub.docker.com/r/minio/minio/dockerfile) doesn't have any special user to use. Here is the output of the /etc/passwd:
> 
> ```
> root:x:0:0:root:/root:/bin/ash
> bin:x:1:1:bin:/bin:/sbin/nologin
> daemon:x:2:2:daemon:/sbin:/sbin/nologin
> adm:x:3:4:adm:/var/adm:/sbin/nologin
> lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
> sync:x:5:0:sync:/sbin:/bin/sync
> shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
> halt:x:7:0:halt:/sbin:/sbin/halt
> mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
> news:x:9:13:news:/usr/lib/news:/sbin/nologin
> uucp:x:10:14:uucp:/var/spool/uucppublic:/sbin/nologin
> operator:x:11:0:operator:/root:/sbin/nologin
> man:x:13:15:man:/usr/man:/sbin/nologin
> postmaster:x:14:12:postmaster:/var/spool/mail:/sbin/nologin
> cron:x:16:16:cron:/var/spool/cron:/sbin/nologin
> ftp:x:21:21::/var/lib/ftp:/sbin/nologin
> sshd:x:22:22:sshd:/dev/null:/sbin/nologin
> at:x:25:25:at:/var/spool/cron/atjobs:/sbin/nologin
> squid:x:31:31:Squid:/var/cache/squid:/sbin/nologin
> xfs:x:33:33:X Font Server:/etc/X11/fs:/sbin/nologin
> games:x:35:35:games:/usr/games:/sbin/nologin
> postgres:x:70:70::/var/lib/postgresql:/bin/sh
> cyrus:x:85:12::/usr/cyrus:/sbin/nologin
> vpopmail:x:89:89::/var/vpopmail:/sbin/nologin
> ntp:x:123:123:NTP:/var/empty:/sbin/nologin
> smmsp:x:209:209:smmsp:/var/spool/mqueue:/sbin/nologin
> guest:x:405:100:guest:/dev/null:/sbin/nologin
> nobody:x:65534:65534:nobody:/:/sbin/nologin
> ```
> 
> Of course I can make my Dockerfile and fix this by adding (in Alpine version):
> 
> RUN adduser -D minio
> USER minio
> 
> but this means that everyone using Helm chart and your official image would need to do. My opinion is that it should run as non-root out of the box, so the right place to modify it would be [here](https://github.com/minio/minio/blob/master/Dockerfile).

Those are not needed @acim it is on purpose avoided since there are easier and better mechanisms to run it using `docker --user` context.

**Comment by harshavardhana** [comment]
> 
> Those are not needed @acim it is on purpose avoided since there are easier and better mechanisms to run it using `docker --user` context.

Also the recommended approach from docker, k8s @acim

**Comment by acim** [comment]
There is no "docker --user" in Kubernetes, there are just extraArgs in Helm chart and the number or users is limited in your container, there is no appropriate user. What shall I put as extraArgs? --user games? Or --user nobody? Is it really appropriate to run minio as user nobody or games and have no rights to write own home directories?

We obviously do not understand each other, but you can just read Dockerfile best practice:

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user

**Comment by harshavardhana** [comment]
> There is no "docker --user" in Kubernetes, there are just extraArgs in Helm chart and the number or users is limited in your container, there is no appropriate user. What shall I put as extraArgs? --user games? Or --user nobody? Is it really appropriate to run minio as user nobody or games and have no rights to write own home directories?
> 
> We obviously do not understand each other, but you can just read Dockerfile best practice:
> 
> https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user

@acim on k8s it is much simpler

```
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
```

Our helm chart has https://github.com/helm/charts/tree/master/stable/minio


Parameter | Description | Default
-- | -- | --
securityContext.enabled | Enable to run containers as non-root. NOTE: if persistence.enabled=false then securityContext will be automatically disabled | true
securityContext.runAsUser | User id of the user for the container | 1000
securityContext.runAsGroup | Group id of the user for the container | 1000
securityContext.fsGroup | Group id of the persistent volume mount for the container | 1000

I don't think we are planning to add anything beyond this, adding users as part of the container is not going to work, it is not an OS. Run the container itself as the user of your choice and let the orchestration decide.

**Comment by acim** [comment]
Then you have bug in the Helm chart, documentation says default value for securityContext.enabled is true, but it is actually false in values.yaml.

https://github.com/helm/charts/blob/798110021704387e8ef26526f9dac89b553dfc44/stable/minio/values.yaml#L177

**Comment by harshavardhana** [comment]
> Then you have bug in the Helm chart, documentation says default value for securityContext.enabled is true, but it is actually false in values.yaml.
> 
> https://github.com/helm/charts/blob/798110021704387e8ef26526f9dac89b553dfc44/stable/minio/values.yaml#L177

Thanks @acim feel free to send a fix.

**Comment by acim** [comment]
I will, thank you.
