### ISSUE TITLE
No notification on DELETE of zero-length object

### ISSUE THREAD

**Issue by mlschuh** [minio/minio#9408]
When working with zero-length objects (to simulate a folder structure), I am successfully receiving notifications to Redis from PUT. I am not receiving any of the DELETE notifications. I do receive DELETE notifications on all other objects with size >0.

## Expected Behavior
I should be able to get notified of every object delete, even if it's zero length.

## Current Behavior
I only get notified when objects of length > 0 are deleted

## Steps to Reproduce (for bugs)
1. Setup notifications and add them to the bucket. We use redis but I expect it's the same with any other output.
```
//Javascript

let bucketNotification = new Minio.NotificationConfig();
let queue = new Minio.QueueConfig("...mycurrentarn...");
queue.addEvent(Minio.ObjectRemovedAll);
queue.addEvent(Minio.ObjectCreatedAll);
bucketNotification.add(queue);

minioClient.setBucketNotification('prefix-validate', bucketNotification)

```
2.PUT a zero length object and an object with size for comparison.
```
//Javascript

  await minioClient
    .putObject("prefix-validate", "my/path/", "", 0)
    .catch((err) => {
      console.log(`Object Ensure Prefix error adding object to minio: ${err}`);
    });
  await minioClient
    .putObject("prefix-validate", "myobject", "1234", 0)
    .catch((err) => {
      console.log(`Object Ensure Prefix error adding object to minio: ${err}`);
    });
````
3. Through the Minio browser, delete each of them.
4. Check notifications. It will only have one DELETE. Should have two.

## Context
We are implementing push updates to users of a web client and deleting of 'folders' (not really folders...) never shows up unless the user refreshes the page. We are already handling most of the odd nature of folders without any problem, only not being able to catch when one is deleted and cleaning it up properly.

## Your Environment
* Version used (`minio version`): docker minio:RELEASE.2020-04-10T03-34-42Z
* Environment name and version (e.g. nginx 1.9.1): 
  * docker minio:RELEASE.2020-04-10T03-34-42Z
  * docker 19.03.4
  * minio js library 7.0.15
  * redis 5

All containers are on the same overlay network on the same VM.

**Comment by kannappanr** [comment]
@mlschuh I am able to see the folder being deleted via `mc admin trace` when I delete it using `aws cli`. So, I would expect Redis notification also to receive this.

I also tested this with a webhook and received the following event notification

```
{"EventName":"s3:ObjectRemoved:Delete","Key":"test/folder/","Records":[{"eventVersion":"2.0","eventSource":"minio:s3","awsRegion":"","eventTime":"2020-04-22T06:25:46Z","eventName":"s3:ObjectRemoved:Delete","userIdentity":{"principalId":"minio"},"requestParameters":{"accessKey":"minio","region":"","sourceIPAddress":"127.0.0.1"},"responseElements":{"x-amz-request-id":"","x-minio-deployment-id":"d535bfab-5872-4427-9a5a-b85f7d59a2cf","x-minio-origin-endpoint":"http://192.168.86.26:9000"},"s3":{"s3SchemaVersion":"1.0","configurationId":"Config","bucket":{"name":"test","ownerIdentity":{"principalId":"minio"},"arn":"arn:aws:s3:::test"},"object":{"key":"folder%2F","versionId":"1","sequencer":"160810428AA7949A"}},"source":{"host":"127.0.0.1","port":"","userAgent":"aws-cli/1.16.198 Python/3.6.8 Linux/4.15.0-70-generic botocore/1.12.188"}}]}
```

Here is the aws cli command that I used
`AWS_ACCESS_KEY_ID=minio AWS_SECRET_ACCESS_KEY=minio123 aws --endpoint-url http://localhost:9000 s3api delete-object --bucket test --key folder/`

If the server received a delete object request, it sends out a notification

**Comment by kannappanr** [comment]
Also, I don't think you can delete an empty folder currently in MinIO browser

**Comment by mlschuh** [comment]
@kannappanr I can confirm that you are correct, it only exhibits with the MinIO browser. I was able to make it at least appear that folders were deleted in the browser by going to the root of the bucket and deleting it from there, essentially deleting the entire key. I would say that's a different issue and clearly less important (I won't even open an issue in github for it unless you want me to).

Here's the JS I used to validate in case anyone in the future needs it:

```
	minioClient.putObject('fooo', 'my/test/directory/', '', 0, (err) => {
		if (err) {
			console.log('Error adding directory', err);
			return;
		}
		console.log('Successfully added file');
		minioClient.removeObject('fooo', 'my/test/directory/', (err) => {
			if (err) {
				console.log('Error deleting directory', err);
				return;
			}
			console.log('Deleted Directory');
		});
	});
```

**Comment by kannappanr** [comment]
@mlschuh we do not have an option to delete a folder in the browser. Closing this issue now as there is no issue with the notification itself. Please feel free to let us know if you have further questions.
