### ISSUE TITLE
Can't create empty folders in MinIO Browser

### ISSUE THREAD

**Issue by kaankabalak** [minio/minio#9409]
## Expected Behavior

Empty folders should be able to be created in MinIO Browser

## Current Behavior

Currently, we don't have an option to explicitly create folders in MinIO Browser. However, currently, we navigate to the folders by entering the bucket path in the directory path input in header, or editing the URL from the address bar of the browser. When a file is uploaded inside a folder, the folder persists, however if the user navigates away from a folder without uploading an object in it, the folder disappears.

## Possible Solution

We might want to discuss if we would like an explicit option to create a folder, or we can create folders on all directories where the user navigates to.

## Steps to Reproduce (for bugs)

1. Create a bucket named "test"
2. Click on the "Choose or create new path" button on the directory path in the header and enter a path inside the bucket, like `test/dir1`, which will direct you to the folder `dir1` inside bucket `test`
3. Upload an object inside the `dir1` folder, navigate back to the `test` bucket and verify that the folder `dir1` is still present
4. Click on the "Choose or create new path" button on the directory path in the header and enter a path inside the bucket, like `test/dir2`, which will direct you to the folder `dir2` inside bucket `test`
5. Navigate back to the `test` bucket without uploading any objects inside `dir2` and verify that the `dir2` folder isn't present anymore inside the `test` bucket

## Context

The current behavior might be unintuitive for users who would like to create folders from the MinIO Browser.

## Regression

No

## Your Environment

* Version used (`minio version`): latest master
* Environment name and version (e.g. nginx 1.9.1): play.min.io
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by darkdragon-001** [comment]
Still an issue.

**Comment by Twilek-de** [comment]
I have my Minio install mapped as an external storage in Nextcloud. When I copy plain files it all goes well. If I try to copy a directory structure where in the first directory level there are again only directories Minio does create one empty directory but then fails to put anything into it. Interestingly I cannot delete the empty directory from the nextcloud interface if it is still empty. If I put a file into the directory it can be removed via nextcloud without a problem. I am seeing similar problems when trying to use "Cloud Sync" on my NAS. It seems that Minio really doesn´t like empty directories and recursive copying.

**Comment by harshavardhana** [comment]
This is being implemented properly in https://github.com/minio/console

**Comment by mqu** [comment]
this strange behavior is still present in latest version of minio, minio-console.

**Comment by bmitchinson** [comment]
Still an issue

**Comment by nurlanf** [comment]
still an issue

**Comment by Logistikon97** [comment]
still an issue
