### ISSUE TITLE
content-type image/svg+xml does not properly being set

### ISSUE THREAD

**Issue by kesuskim** [minio/minio#9412]
svg file of which content-type is `image/svg+xml` does not being properly set; it is just application/octet-stream.

```sh
$ mc stat filepath/2d9358676968956de66c3dab5dcdb635.svg
Name      : 2d9358676968956de66c3dab5dcdb635.svg
Date      : 2020-04-22 13:29:31 KST
Size      : 341 B
ETag      : f90c9087a411d222ea667c766a5bfcf1-1
Type      : file
Metadata  :
  Content-Type              : application/octet-stream
```

`2d9358676968956de66c3dab5dcdb635.svg` is this file (which I can see from browser clearly, and works well with nginx, but not work with minio because of content-type)
```xml
<svg id="layer" data-name="layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 302 48">
  <defs>
    <style>
      .cls-1 {
        fill: #404040;
      }
    </style>
  </defs>
  <title>arrow-11</title>
  <rect id="square_747" data-name="square 747" class="cls-1" x="72.62" y="22.16" width="156.76" height="4"/>
</svg>

```

## Expected Behavior

```sh
$ mc stat filepath/2d9358676968956de66c3dab5dcdb635.svg
Name      : 2d9358676968956de66c3dab5dcdb635.svg
Date      : 2020-04-22 13:29:31 KST
Size      : 341 B
ETag      : f90c9087a411d222ea667c766a5bfcf1-1
Type      : file
Metadata  :
  Content-Type              : image/svg+xml
```

## Current Behavior

```sh
$ mc stat filepath/2d9358676968956de66c3dab5dcdb635.svg
Name      : 2d9358676968956de66c3dab5dcdb635.svg
Date      : 2020-04-22 13:29:31 KST
Size      : 341 B
ETag      : f90c9087a411d222ea667c766a5bfcf1-1
Type      : file
Metadata  :
  Content-Type              : application/octet-stream
```

## Possible Solution

svg+xml should be detected

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`): 2020-04-22T00:11:12Z
* Environment name and version (e.g. nginx 1.9.1): CentOS 7
* Server type and version: HP DL160 Gen9
* Operating System and version (`uname -a`): Linux cemware.com 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by harshavardhana** [comment]
You need to set this when you are uploading the content @kesuskim we don't do automatic detection its only best-case scenario 

```
mc cp --attr content-type=...
```

**Comment by kannappanr** [comment]
@kesuskim Closing this issue as answered. This has got nothing to do with MinIO server. The content-type needs to be set as part of the input request by the client application.
Please refer here for more details
https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html

Not sure which application you used to upload this file. If you had used `mc` I think this value would have been set properly. Same is the case with minio browser.

Please feel free to reach out to us at https://slack.min.io for further questions.

**Comment by kesuskim** [comment]
@harshavardhana @kannappanr 
Oh, I did not catch that. I tried both mc and Cloudberry Explorer, but somehow another content-type seemed to be set but svg+xml. 😅

Thanks for clarification!
