### ISSUE TITLE
[not out bug] Unable to initialize server switching into safe-mode: Unable to initialize config system: Invalid credentials

### ISSUE THREAD

**Issue by patsevanton** [minio/minio#9413]
I have minio with version
`minio version RELEASE.2020-04-15T19-42-18Z`

Certificates store in /etc/minio/certs:

    ls /etc/minio/certs
    CAs  private.key  public.crt

When run minio

**MINIO_ACCESS_KEY=4t4twr3r3rw3 MINIO_SECRET_KEY=ert4t4t43rwtw /usr/bin/minio server --certs-dir=/etc/minio/certs --address 0.0.0.0:9000 --certs-dir=/etc/minio/certs/ /var/lib/minio/**

Get error:

    ERROR Unable to initialize server switching into safe-mode: Unable to initialize config system: Invalid credentials

How will fix?
Create issue on github minio? may be not corret my run command?

**Comment by harshavardhana** [comment]
> **MINIO_ACCESS_KEY=4t4twr3r3rw3 MINIO_SECRET_KEY=ert4t4t43rwtw /usr/bin/minio server --certs-dir=/etc/minio/certs --address 0.0.0.0:9000 --certs-dir=/etc/minio/certs/ /var/lib/minio/**

This means your credentials are wrong @patsevanton did you set different credentials before?

**Comment by patsevanton** [comment]
Hello. Yes.
I try use minio rpm
https://copr.fedorainfracloud.org/coprs/lkiesow/minio/
Changed MINIO_ACCESS_KEY and MINIO_SECRET_KEY

**Comment by harshavardhana** [comment]
> Hello. Yes.
> I try use minio rpm
> https://copr.fedorainfracloud.org/coprs/lkiesow/minio/
> Changed MINIO_ACCESS_KEY and MINIO_SECRET_KEY

We do not support community maintained binaries @patsevanton feel free to take this document into consideration when you want to change your keys. 

It requires rotation https://github.com/minio/minio/tree/master/docs/config#rotating-encryption-with-new-credentials

**Comment by kannappanr** [comment]
closing this issue based on the previous comment. Please feel free to reach out to us at https://slack.min.io for further questions
