### ISSUE TITLE
operation not permitted on the default exchange

### ISSUE THREAD

**Issue by xiaosong135** [minio/minio#9415]
hi
 I wanted to use message notification to rabbitmq, but operation not permitted on the default exchange.
Error: Exception (403) Reason: "ACCESS_REFUSED - operation not permitted on the default exchange"

my config is 
notify_amqp:1 url=amqp://user:user@192.168.0.23:5672 exchange= exchange_type=direct routing_key=test01 mandatory=true durable=false no_wait=false internal=false auto_deleted=true delivery_mode=0 queue_limit=0 queue_dir=

I would like to ask if exchange is a must？

**Comment by harshavardhana** [comment]
@xiaosong135 it is a must.

**Comment by xiaosong135** [comment]
so exchange Can't be “” ？

**Comment by harshavardhana** [comment]
@xiaosong135 correct AFAICS

**Comment by xiaosong135** [comment]
Thx

**Comment by harshavardhana** [comment]
@Praveenrajmani we need to change the keys to be listed as mandatory for `exchange`

**Comment by Praveenrajmani** [comment]
> @Praveenrajmani we need to change the keys to be listed as mandatory for `exchange`

will send a PR @harshavardhana
