### ISSUE TITLE
Browser shows Used:99Gb / data is no longer visible / heal refuses to work

### ISSUE THREAD

**Issue by carsoni** [minio/minio#9427]
We are storing our Gitlab log data onto a minio instance which uses a ZFS array as its data store. 
We recently replaced a failed drive (in a raidz2 configuration) which resilvered without issue but the minio browser no longer shows any data. Despite no data being visible the browser shows "Used:99.90Gb" in the upper panel.
We have attempted to run heal but are getting "Unexpected client 'admin' API version found 'v2', expected 'v3'" messages with every released version of mc back to the beginning of 2016.
I can accept that the data may indeed be gone but the 99.9Gb reference in the browser is holding out some hope, to which I am currently clinging :-), and I'd like to be able to confirm that the data is either there (and recover it) or gone (and move on) 

Thanks in advance

## Expected Behavior
Twofold
- Heal works and does not give version errors
- Browser provides accurate Used value

## Regression
1 Possible issue problem in relation to the heal issue. All the mc versions I have downloaded from archive all show RELEASE.2020-02-25T18-10-03Z when I run mc -v

## Your Environment
* Version used (`minio version`): 2020-04-22T00:11:12Z
* Server type and version: Ubuntu 18.04.4 LTS
* Operating System and version (`uname -a`):Linux  4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> We have attempted to run heal but are getting "Unexpected client 'admin' API version found 'v2', expected 'v3'" messages with every released version of mc back to the beginning of 2016.

when you upgrade the server you need to upgrade the `mc` as well usually and we diligently mention this change if needed in the release notes which you should read.

Once the `mc` upgrade is done proceed to heal by `mc admin heal -r <alias>` or wait for 10minutes it will auto-heal the newly replaced drive.

**Comment by carsoni** [comment]
Hi @harshavardhana 

I have upgraded as your suggest and get the following error when running 
    
    mc admin heal -r myminio

    mc: <ERROR> Failed to start heal sequence. This 'admin' API is not supported by server in 'mode-server-fs'.

Is it the case that heal only works with erasure-code? I had not started the server in that fashion as the data folder is on a ZFS array and thought the two would be incompatible

Does this mean that my 99Gb is gone forever?

Thanks in advance

**Comment by harshavardhana** [comment]
> Hi @harshavardhana 
> 
> I have upgraded as your suggest and get the following error when running 
>     
>     mc admin heal -r myminio
> 
>     mc: <ERROR> Failed to start heal sequence. This 'admin' API is not supported by server in 'mode-server-fs'.
> 
> Is it the case that heal only works with erasure-code? I had not started the server in that fashion as the data folder is on a ZFS array and thought the two would be incompatible
> 
> Does this mean that my 99Gb is gone forever?
> 
> Thanks in advance
> 
>     

Of course healing is only for erasure code, you need to check why your ZFS volume is reporting size incorrectly..

FS mode is very simple exposes what is there on your disk that's all. You need to check your disk here MinIO doesn't do anything here.

**Comment by carsoni** [comment]
Hi @harshavardhana

Thanks for your help on this.

Just one clarification - Minio is reporting 99Gb used in the UI **not** ZFS. I was assuming that Minio may have some mechanism by which the data it stores is somehow "hidden" from the underlying file system and that I might be able to get this 99Gb back.

Is this even a possibility?

**Comment by harshavardhana** [comment]
> Just one clarification - Minio is reporting 99Gb used in the UI **not** ZFS. I was assuming that Minio may have some mechanism by which the data it stores is somehow "hidden" from the underlying file system and that I might be able to get this 99Gb back.

No the UI report is actually the `df -h` value obtained by doing a statvfs call.

**Comment by carsoni** [comment]
Thanks mate. I'll go and have a wander through the fs and see what I can find.

Thanks for your help
 👍

**Comment by carsoni** [comment]
Hi @harshavardhana 

Quick followup (for the sake of completeness) which may help others facing a similar issue.

The fact that I could see that there was used space on the array

    df -h
   
    Filesystem      Size  Used Avail Use% Mounted on
    zfs_array       6.9T  101M  6.9T   1% /zfs_array

but couldn't see it in the file manager was really nagging at me. After a good sleep and a determined mindset this morning I was able to recover/reveal the missing data with the following steps

1. Stop the minio docker container

    `docker stop <container-id>`

2. Export the ZFS array (effectively 'unmount')

    `sudo zpool export <array name>`

3. Import the ZFS array (effectively 'mount')

    `sudo zpool import <array name>`

4. Restart the minio docker container (ensure that key and secret id are unchanged )

    `docker start <container-id>`
