### ISSUE TITLE
Get stuck on sending multiple async GetObjectRequest

### ISSUE THREAD

**Issue by squadgazzz** [minio/minio#9432]
## Current Behavior
When I send more than a single async GetObjectRequest, the program gets stuck forever.
I don't have this problem with HeadObjectRequest for example or when the bucket is empty or when I send a single request only.

## Steps to Reproduce (for bugs)
Sample code: https://gist.github.com/squadgazzz/476f915f590738c173c84a768498ef90
Output logs: https://gist.github.com/squadgazzz/331dcd6d9204e2bd5fb56fc1286cfabb

## Your Environment
*AWS SDK 2.11.12
*Minio RELEASE.2020-04-10T03-34-42Z
*Scala 2.12
*OpenJDK 8u241

**Comment by klauspost** [comment]
From what I can see in the logs, the requests complete fine and it looks on the surface as an SDK issue. We cannot offer help with SDK's.

You are welcome to ask on our slack if someone has a similar setup: https://slack.min.io/
