### ISSUE TITLE
when i use “mc admin policy list myminio” ，it reported : unsupported action 'admin:HardwareInfo'

### ISSUE THREAD

**Issue by Logan80s** [minio/minio#9439]
## Expected Behavior

show the policylist

## Current Behavior

it reported : unsupported action 'admin:HardwareInfo'
## Steps to Reproduce (for bugs)

1. run command line   " mc admin policy list myminio "
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by vadmeste** [comment]
@Logan80s thanks for reporting this.

Did this happen after upgrading the server ?

**Comment by vadmeste** [comment]
The reason is that `admin:HardwareInfo` is not supported anymore. What can we do is to relax listing & getting policy documents

**Comment by vadmeste** [comment]
@Logan80s could you try to upgrade to the latest version ?

**Comment by harshavardhana** [comment]
Fixed in #9442 to allow for the server to work properly when incompatible changes happen.

**Comment by Logan80s** [comment]
@vadmeste @harshavardhana sorry to reply so late
It not happen again, I don't know why
