### ISSUE TITLE
Docker cannot be run: Unable to initialize backend

### ISSUE THREAD

**Issue by ZedZipDev** [minio/minio#9448]
I have Windows 7 and installed Minio windows service, it works fine.

It uses folder d:\MinioDisk  as a storage.
I'd like to replace it wth docker container. 
When I try to run the docker I receive the error:

```
# docker run -p 9022:9000 --name minio2 -e "MINIO_ACCESS_KEY=minio" -e "MINIO_SECRET_KEY=minio7890" -v /d/MinioDisk:/data  minio/minio server /data

ERROR Unable to initialize backend: The disk size is less than the minimum threshold

```

What is the reason and how to fix it?

**Comment by harshavardhana** [comment]
As the message suggests we need minimum 1GiB

**Comment by ZedZipDev** [comment]
The disk D: has 8GB free from total 111GB.
The Windows service works with the same folder fine.
Also, I have tried to run using this cmd

```
# docker run -p 9022:9000 --name minio4 -v D:\MinioDisk:/data minio/minio server /data
docker: Error response from daemon: invalid mode: /data.

```

I have tried to use another disk G (30 GB free/256GB total)

```
# docker run -p 9022:9000 --name minio14 -v /G/MinioDisk:/data minio/minio server /data
ERROR Unable to initialize backend: The disk size is less than the minimum threshold
```

**Comment by harshavardhana** [comment]
This is because docker on windows is broken just use the binary directly, on your windows host.

**Comment by ZedZipDev** [comment]
Ah, I see, ok. Thank you.
Btw, MinIO Docker on Mac and Ubuntu works ok? Can I use it?
