### ISSUE TITLE
server crash after multiple disks replacement

### ISSUE THREAD

**Issue by igomura** [minio/minio#9449]
After few simultaneous disk replacements node fail to start
```
Apr 25 03:41:20 localhost minio[502]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 25 03:41:20 localhost minio[502]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x158b06c]
Apr 25 03:41:20 localhost minio[502]: goroutine 57449 [running]:
Apr 25 03:41:20 localhost minio[502]: github.com/minio/minio/cmd.xlObjects.StorageInfo(0xc01e979da0, 0xc01e979dc0, 0xc062d52300, 0x10, 0x10, 0xc007d8a7e0, 0xc01e403000, 0x0, 0xc02432fc80, 0x202d2a0, ...)
Apr 25 03:41:20 localhost minio[502]: github.com/minio/minio@/cmd/xl-v1.go:185 +0x29c
Apr 25 03:41:20 localhost minio[502]: github.com/minio/minio/cmd.(*xlSets).StorageInfo.func1(0xc00b963780, 0xc01aa12380)
Apr 25 03:41:20 localhost minio[502]: github.com/minio/minio@/cmd/xl-sets.go:397 +0xfb
Apr 25 03:41:20 localhost minio[502]: github.com/minio/minio/pkg/sync/errgroup.(*Group).Go.func1(0xc024229740, 0xc023ef7e50, 0x20)
Apr 25 03:41:20 localhost minio[502]: github.com/minio/minio@/pkg/sync/errgroup/errgroup.go:55 +0x5d
Apr 25 03:41:20 localhost minio[502]: created by github.com/minio/minio/pkg/sync/errgroup.(*Group).Go
Apr 25 03:41:20 localhost minio[502]: github.com/minio/minio@/pkg/sync/errgroup/errgroup.go:52 +0x6c
```

## Expected Behavior
Server expected to start and format new disks

## Current Behavior
Server crash

## Steps to Reproduce (for bugs)
1. Setup cluster of 16 nodes
MINIO_ERASURE_SET_DRIVE_COUNT="16"
MINIO_STORAGE_CLASS_STANDARD="EC:6"

2. Remove data from few random disks but only one disk in erasure set
Node1: disks A, B, C
Node2: disks D, E, F
Node3: disks X, Y, Z

3. Nodes 1, 2, 3 will not be able to start but nodes 4-16 work fine

## Regression
Not sure. I was able to recover after single disks failure. This is the first time we test multiple failures

## Your Environment
* Version used (`minio version`): 2020-04-15T19:42:18Z
* Server type and version: amd64
* Operating System and version (`uname -a`):Linux 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
This looks like a bug in the code @igomura you should be able to recover any number of disks - this is simply a `nil` check failure.

**Comment by harshavardhana** [comment]
This issue specifically happens in the Prometheus metrics handler
