### ISSUE TITLE
[resolved] webhook called twice

### ISSUE THREAD

**Issue by dyipon** [minio/minio#9453]
Setuped a webhook to get notification for every PUT event, but webhook called twice. Once with 0 byte, and once with correct header size.

## Expected Behavior
It should call the webhook only 1 time

## Current Behavior
1st call:
```
".POST /hooks/minio-webhook HTTP/1.1
Host: localhost:999
User-Agent: Go-http-client/1.1
Content-Length: 0
Accept-Encoding: gzip"
```

2nd call:
```
POST /hooks/minio-webhook HTTP/1.1
Host: localhost:999
User-Agent: Go-http-client/1.1
Content-Length: 1091
Content-Type: application/json
```

## Steps to Reproduce (for bugs)

1. ./minioclient admin config set myminio notify_webhook:1 queue_limit="0"  endpoint="http://localhost:999/hooks/minio-webhook" queue_dir=""
2. ./minioclient event add myminio/bigbucket arn:minio:sqs::1:webhook --event put
3. upload something

## Regression
Not really, but it makes noisy logs.

## Your Environment

* Version used (`minio version`): minio version RELEASE.2020-04-23T00-58-49Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): Linux minio 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
* Link to your project:

**Comment by Praveenrajmani** [comment]
@dyipon That is actually a part of MinIO's internal behaviour. MinIO will send a ping initially before sending any event to see if the target is active or not.

Such pings will have req.body as nil. You could simply ignore such pings and move on parsing the event which has body != nil

**Comment by dyipon** [comment]
it's clear, thanks!
