### ISSUE TITLE
svg served with wrong content-type

### ISSUE THREAD

**Issue by busshimoe** [minio/minio#9455]
## Expected Behavior

.svg should be served with image/svg+xml
## Current Behavior

.svg is served with application/octet-stream
## Possible Solution

Change the content type .svg files are served with
## Steps to Reproduce (for bugs)

1. Upload a .svg file to a minio instance
2. GET the file
## Context

This prevents me from embedding .svg files served on minio in my website, or viewing them in the browser.
## Regression

No
## Your Environment

* Version used (`minio version`): RELEASE.2020-01-03T19-12-21Z
* Environment name and version (e.g. nginx 1.9.1): nginx/1.14.0
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
You need to set the right content-type when uploading the object @busshimoe

**Comment by kannappanr** [comment]
@busshimoe closing this issue as `content-type` is passed by the client application. Please feel free to reach out to us at https://slack.min.io for further such questions.

**Comment by busshimoe** [comment]
Thank you for the information.
