### ISSUE TITLE
Deleted files do not get removed after disconnected node reconnects 

### ISSUE THREAD

**Issue by peterfroehlich** [minio/minio#9473]
We noticed that files in a data directories do not get removed on hosts that were disconnected when the remove command was issued. That can lead to a resource leak without a clear path to fix it nor indication (except differently sized data directories).  

That said, this seems so obvious... sorry if this dub or expected, I didn't find an issue or documentation about this happening the way it does. 

## Expected Behavior
Analog to new or changed files that are replicated on the the host on reconnection, files deleted from the cluster should be removed from the reconnecting host as well. 

## Current Behavior
After the removal command, the file is no longer accessible and is removed from the data directories of the connected host. After the disconnected host reconnects it syncs all new and changed files, but does not sync removal of files. The file is not visible in the API or webinterface though.  

## Steps to Reproduce (for bugs)
1. Create a file in a working three node cluster
2. shut down a node
3. remove the file 
4. start the node again 
5. look for the file in the data directories of the newly reconnected host, its still there. 

## Your Environment
- minio version RELEASE.2020-04-15T19-42-18Z on Centos7 
- Linux minio03.redacted 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- 3 nodes with 4 data directories on separate (non-root) disks

**Comment by vadmeste** [comment]
@peterfroehlich those stale objects can be removed if you issue `mc admin heal --remove` command.

Yes, there is no good documentation about healing yet, I will do that.

**Comment by peterfroehlich** [comment]
> @peterfroehlich those stale objects can be removed if you issue `mc admin heal --remove` command.

Thanks for the fast answer! I just tried that in our test setup. I needed to use the option "-r" in addition to "--remove" to get rid of the objects in the bucket root, but I worked fine. Thank you. 

Is there an internal scheduler that will clean up stale objects by itself? 
What are the experiences with this command running on a bucket with a few million files?

**Comment by vadmeste** [comment]
> Is there an internal scheduler that will clean up stale objects by itself?

There is an internal healing process, but it is not allowed to remove stale objects yet but probably it will in the near future. 

> What are the experiences with this command running on a bucket with a few million files?

Healing supports huge number of files, it will also slow down if there are active S3 requests reaching the server.

**Comment by peterfroehlich** [comment]
Thanks again :)
