### ISSUE TITLE
Retention issue: mc cp can overwrite an object in compliance mode

### ISSUE THREAD

**Issue by ebozduman** [minio/minio#9476]
Object in compliance mode is overwritten by a regular file when `mc cp`ed.
## Expected Behavior
Object in compliance mode should never be overwritten.
## Current Behavior
`mc cp` overwrites the protected object in compliance mode by a regular file after default lock is `--clear`ed.
## Possible Solution
None
## Steps to Reproduce (for bugs)
1. $ mc mb myminio/xxx -l
Bucket created successfully `myminio/xxx`.
2. $ mc lock myminio/xxx governance 1d
GOVERNANCE mode is enabled for 1d
3. $ mc cp /etc/issue myminio/xxx --retention-duration 1d --retention-mode compliance
/etc/issue:            26 B / 26 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 2.11 KiB/s 0s
4. $ mc lock myminio/xxx --clear
No object lock configuration is enabled
5. $ mc stat myminio/xxx/
Name      : issue
Date      : 2020-04-28 08:55:09 PDT
Size      : 26 B
ETag      : 9c771e1fa41a5a833f5824b41bd3eb1f
Type      : file
Metadata  :
  Content-Type                       : application/octet-stream
  X-Amz-Object-Lock-Retain-Until-Date: 2020-04-29T15:55:09Z
  X-Amz-Object-Lock-Mode             : COMPLIANCE
6. $ mc cp /etc/issue myminio/xxx
/etc/issue:            26 B / 26 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 2.32 KiB/s 0s
mc stat myminio/xxx/
Name      : issue
Date      : 2020-04-28 08:58:18 PDT
Size      : 26 B
ETag      : 9c771e1fa41a5a833f5824b41bd3eb1f
Type      : file
Metadata  :
  Content-Type: application/octet-stream

The object in compliance retention mode is overwritten.

## Context
I was testing PR#9440 but there are other ways to do the testing, so there was no impact for me.
## Regression

Could be a regression

## Your Environment
* Version used (`minio version`): build from the top of the master branch
* Server type and version: minio fs and mc build from the top of the master branch

**Comment by kannappanr** [comment]
Fixed by #9513
