### ISSUE TITLE
Use aws-sdk-go(v1.30.14) to uploadpart to minio get unexpected error

### ISSUE THREAD

**Issue by beifangxiuwhx** [minio/minio#9482]
## Current Behavior
here is the log(client):
2020-04-29 14:25:53.786297 |E| [dispatch:  157] consumer failed. list : [0xc0000cdb00], err: XAmzContentSHA256Mismatch: The provided 'x-amz-content-sha256' header does not match what was computed.
        status code: 400, request id: 160A36541AF520D3, host id:
## Possible Solution

server's log:
Error: Bad sha256: Expected e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 is not valid with what we calculated edeaaff3f1774ad2888673770c6d64097e391bc362d7d6fb34982ddf0efd18cb
       4: cmd/fs-v1-helpers.go:343:cmd.fsCreateFile()
       3: cmd/fs-v1-multipart.go:305:cmd.(*FSObjects).PutObjectPart()
       2: cmd/object-handlers.go:2180:cmd.objectAPIHandlers.PutObjectPartHandler()
       1: net/http/server.go:2012:http.HandlerFunc.ServeHTTP()

The same code run OK when upload to aws s3

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by vadmeste** [comment]
@beifangxiuwhx could you share a minimal code which reproduces this ?

**Comment by kannappanr** [comment]
@beifangxiuwhx I have tried both single part and multipart, with TLS and without TLS. I tried two versions 1.26.3 and 1.30.17 both of them did not show this error. Please provide as much as possible for us to reproduce this issue, like the exact with the exact filename etc to reproduce the issue

**Comment by beifangxiuwhx** [comment]
Hi，@harshavardhana  @kannappanr , it's not a minio bugs. I just found that s3-go-sdk will get a wrong content-sha256 while use io.readcloser in func uploadpart , it's all ok when I use io.readseeker.
Please close the issue, Thanks!

**Comment by kannappanr** [comment]
@beifangxiuwhx Thanks for letting us know.

**Comment by harshavardhana** [comment]
> Hi，@harshavardhana  @kannappanr , it's not a minio bugs. I just found that s3-go-sdk will get a wrong content-sha256 while use io.readcloser in func uploadpart , it's all ok when I use io.readseeker.
> Please close the issue, Thanks! 

They document specifically for you to use io.Seeker please report this upstream as this can be avoided on their end.
