### ISSUE TITLE
[faq] How to make files in bucket public read but not the bucket?

### ISSUE THREAD

**Issue by uzaysan** [minio/minio#9488]
I want files in bucket to be publicly available to read. But I want to hide bucket.

For example

`myServerIP:9000/myBucket/image.jpg`
this must be available. User must see image.jpg

But when I type `myServerIP:9000/myBucket` or `myServerIP:9000/minio/myBucket` user can see all the files inside bucket. How to prevent this?

**Comment by kannappanr** [comment]
a bucket policy like the following

```
{
 "Statement": [
  {
   "Action": [
    "s3:GetObject"
   ],
   "Effect": "Allow",
   "Principal": {
    "AWS": [
     "*"
    ]
   },
   "Resource": [
    "arn:aws:s3:::bucketname/*"
   ]
  }
 ],
 "Version": "2012-10-17"
}
```
would do this. closing this issue as answered, please feel free to reach out to us at https://slack.min.io for such questions.

**Comment by uzaysan** [comment]
@kannappanr Is this any different from creating readOnly policy using web console? 
Edit: I'm talking about this https://i.ibb.co/sW6tLT6/Untitled.png
