### ISSUE TITLE
[resolved] Server startup failed with 'Unable to handle encrypted backend for config, iam and policies: config file not found'

### ISSUE THREAD

**Issue by caryfitzhugh** [minio/minio#9489]
## Expected Behavior

It is expected that I could update from 
minio/minio:RELEASE.2019-10-12T01-39-57Z
to
minio/minio:RELEASE.2020-04-23T00-58-49Z

and the migrations would happen correctly.

## Current Behavior

When I update all my servers to minio/minio:RELEASE.2020-04-23T00-58-49Z  and restart, the servers report this:
```

     You are running an older version of MinIO released 5 days ago
     Update: docker pull minio/minio:RELEASE.2020-04-28T23-56-56Z


    Attempting encryption of all config, IAM users and policies on MinIO backend
    Server startup failed with 'Unable to handle encrypted backend for config, iam and policies: config file not found'
    Server switching to safe mode
    Please use 'mc admin config' commands fix this issue
    Status:         18 Online, 0 Offline.
    Endpoint:  http://0.0.0.0:9500
```

## Possible Solution

This occurred through an unusual state of events.

1) I had packaged MinIO image with a background task which periodically would look for any buckets which did not have event notifications attached, and attach them (FWIW - if one could create a global / default notification instead of having to add individually, that would be grand)
2) Power went down and a drive failed
3) When trying to bring things back up, the cluster was in an invalid state for days.  Fixing drives , restarting, etc

Things came back up for a day or so, then failed again.

I suspect something with my background task and other environmental effects caused an invalid config.json file to be saved.

When I attempted to bring things up again, slowly, I got an error like this when trying to investigate:

```
mc: <ERROR> Cannot get server '[notify_webhook]' config. We encountered an internal error, please try again. (ReadMapCB: expect { or n, but found ", error found in #10 byte of ...|ersion": "33",
	"cre|..., bigger context ...|{
	"version": "33",
	"credential": {
   ......
```
To me that seemed to indicate that the config.json was being reconstructed internally by MinIO, but parsing was failing.  But there is no way to poke in there and fix what I figured was an obvious formatting issue.  I was hoping for a mc cat and mc pipe ability in .minio.sys/config/config.json, but alas...

At this point, I started to:
* try to move files around in .minio.sys/config/config.json - 
  * would MinIO recreate a default config.json?
* upgrade to the latest version
  * maybe there was new code which handled this situation gracefully?

Asked for help on Slack, and eventually got the fix to "delete .minio.sys/config" on every server/disk.
And restart with the original version.

That seemed to get our prod cluster back online and functioning, but we are not able to upgrade (if we upgrade the version, it gives the error in the title of this issue)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):  Ubuntu
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

Our salt start script is:
```
PORT=9500
IMAGE=minio/minio:RELEASE.2019-10-12T01-39-57Z
#--hostname {{ grains['fqdn'] }} \
{% set  disks = ['disk4', 'disk5'] %}
{% set  port = '9500' %}docker pull $IMAGEsh ./stop.shdocker run -d \
    --name minio-alpha \
    --network host \
    -v /mnt/chunks/disk4/minio:/disk4 \
    -v /mnt/chunks/disk5/minio:/disk5 \
    -v $PWD/minio.config:/minio.config.json \
    -e MINIO_ACCESS_KEY=$(cat ./minio.access_key) \
    -e MINIO_SECRET_KEY=$(cat ./minio.secret_key) \
    -e MINIO_ERASURE_SET_DRIVE_COUNT=6 \
    -e MINIO_PORT={{port}} \
    -e MINIO_DOMAIN=minio.internal \
    --log-opt max-size=5m \
    --log-opt max-file=4 \
    --restart always \
    $IMAGE \
    server \
    --address "0.0.0.0:{{port}}" \
    {% for disk in disks -%}
    {% for host in salt['pillar.get']('master:nodegroups:minio', []) -%}
    http://{{host}}:{{port}}/{{disk}} \
    {% endfor %}
    {%- endfor %}
```

Disks appear to be ext3

I was asked to test O_DIRECT, this seemed to pass.
```
sudo dd if=/dev/urandom of=/mnt/chunks/disk4/testfile bs=1M count=1 oflag=direct
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.0782254 s, 13.4 MB/s
```

## Suggestions
 If I could have used some "danger-mode" flag, and been able to directly read / write config.json it may have been easier to figure things out. 
e.g. ```mc cat --danger-mode .minio.sys/config/config.json```

If there was a global / default notification that got added to new buckets, that would be a great thing.

**Comment by harshavardhana** [comment]
You don't need to any of this just do this

```
~ mc admin config export alias > mycfg.txt
~ mc admin config import alias < mycfg.txt
```

And then restart all your services..

**Comment by caryfitzhugh** [comment]
I tried this just now.

My newer version of mc has this command, but the server is too old (I think) so I get this response:

```
 ~ () $ mc admin config export alpha
mc: <ERROR> Cannot get server config. Failed to parse server response.
```

If I go back to use the older mc, it tells me that it is not a command.
```
 ~ () $ mc.old admin config export alpha
mc.old: <ERROR> `export` is not a mc command. See `mc --help`.
```

I could try to update the version of the cluster to current and then run it again, but typically the mc admin * commands would hang b/c the servers weren't initialized (since the backend / etc wasn't up)

**Comment by harshavardhana** [comment]
> I tried this just now.
> 
> My newer version of mc has this command, but the server is too old (I think) so I get this response:
> 
> ```
>  ~ () $ mc admin config export alpha
> mc: <ERROR> Cannot get server config. Failed to parse server response.
> ```
> 
> If I go back to use the older mc, it tells me that it is not a command.
> 
> ```
>  ~ () $ mc.old admin config export alpha
> mc.old: <ERROR> `export` is not a mc command. See `mc --help`.
> ```
> 
> I could try to update the version of the cluster to current and then run it again, but typically the mc admin * commands would hang b/c the servers weren't initialized (since the backend / etc wasn't up)

You need upgrade your `mc` to match the server version @caryfitzhugh

**Comment by harshavardhana** [comment]
> minio/minio:RELEASE.2020-04-23T00-58-49Z

Your server version should be this @caryfitzhugh

**Comment by caryfitzhugh** [comment]
mc version:  RELEASE.2020-04-25T00-43-23Z
mc.old version:  RELEASE.2019-10-09T22-54-57Z
cluster version:  RELEASE.2019-10-12T01-39-57Z


I shall attempt to update the cluster version to 2020-04-23 and see what we see...  back in a moment!

**Comment by harshavardhana** [comment]
> mc version: RELEASE.2020-04-25T00-43-23Z

This will not work with 

> cluster version: RELEASE.2019-10-12T01-39-57Z

**Comment by caryfitzhugh** [comment]
agreed. I also have "mc.old" which is my older version of mc.

When I tried it with mc.old I got this
```
mc.old: <ERROR> `export` is not a mc command. See `mc --help`.
```

Since mc.old is a compatible version with my current cluster, and it does not have the desired commands, I attempted to instead, update the version running on the cluster to ``` RELEASE.2020-04-23T00-58-49Z ``` and running again.

The error I get in that case is:
```
 ~ () $ mc admin config export alpha
    mc: <ERROR> Cannot get server config. We encountered an internal error, please try again. (madmin: invalid AEAD algorithm ID).
```

The servers are emitting logs like this:  
```
   Attempting encryption of all config, IAM users and policies on MinIO backend
    Server startup failed with 'Unable to handle encrypted backend for config, iam and policies: config file not found'
```

and specifically

```
    API: GetConfigHandler()
    Time: 20:13:52 UTC 04/29/2020
    DeploymentID: 0b094524-b188-430e-bd6f-048d937ef8c1
    RequestID: 160A6382E4C3B89B
    RemoteHost: 10.0.8.7
    Host: -----:9500
    UserAgent: MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-04-25T00:43:23Z
    Error: madmin: invalid AEAD algorithm ID
           5: github.com/minio/minio@/cmd/api-errors.go:1825:cmd.toAPIErrorCode()
           4: github.com/minio/minio@/cmd/admin-handlers.go:908:cmd.toAdminAPIErrCode()
           3: github.com/minio/minio@/cmd/admin-handlers.go:945:cmd.toAdminAPIErr()
           2: github.com/minio/minio@/cmd/admin-handlers-config-kv.go:424:cmd.adminAPIHandlers.GetConfigHandler()
           1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```

**Comment by harshavardhana** [comment]
> Since mc.old is a compatible version with my current cluster, and it does not have the desired commands, I attempted to instead, update the version running on the cluster to `RELEASE.2020-04-23T00-58-49Z` and running again.

Here is what you should do on all servers

```
~ rm -rf /backend/.minio.sys/backend-encrypted
~ rm -rf /backend/.minio.sys/config/config.json
```

And then restart all the servers and then `mc admin config export alpha`

**Comment by harshavardhana** [comment]
Also please use `RELEASE.2020-04-28T23-56-56Z` server release.

**Comment by caryfitzhugh** [comment]
ok. attempted this.  In a few servers I saw this:

```

    API: SYSTEM()
    Time: 20:40:22 UTC 04/29/2020
    DeploymentID: 0b094524-b188-430e-bd6f-048d937ef8c1
    Error: EOF
           2: github.com/minio/minio@/cmd/data-update-tracker.go:210:cmd.(*dataUpdateTracker).load()
           1: github.com/minio/minio@/cmd/data-update-tracker.go:182:cmd.(*dataUpdateTracker).start()
    Attempting encryption of all config, IAM users and policies on MinIO backend
    Server startup failed with 'Unable to handle encrypted backend for config, iam and policies: config file not found'
    Server switching to safe mode
    Please use 'mc admin config' commands fix this issue
    Use `mc admin info` to look for latest server/disk info
     Status:         16 Online, 2 Offline.
    Endpoint:  http://0.0.0.0:9500
```

the rest just had 
```
    Attempting encryption of all config, IAM users and policies on MinIO backend
    Server startup failed with 'Unable to handle encrypted backend for config, iam and policies: config file not found'
    Server switching to safe mode
    Please use 'mc admin config' commands fix this issue
    Status:         18 Online, 0 Offline.
    Endpoint:  http://0.0.0.0:9500
```

Then I ran:
```
 ~ () $ mc admin config export alpha > alphaconfig
 ~ () $ mc admin config import alpha < alphaconfig
Setting new key has been successful.
Please restart your server with `mc admin service restart alpha`.

 ~ () $ mc admin service restart alpha
Restart command successfully sent to `alpha`.
Restarted `alpha` successfully.
```
### That was encouraging!
Seeing these errors:
```
    Server startup failed with 'Unable to initialize IAM system: unexpected EOF'
    Server switching to safe mode
```

I'm guessing I should also delete the IAM directory in ```.../.minio.sys/config/iam```  and try these steps again?

**Comment by harshavardhana** [comment]
> I'm guessing I should also delete the IAM directory in `.../.minio.sys/config/iam` and try these steps again?

yes @caryfitzhugh

**Comment by caryfitzhugh** [comment]
All I am seeing now are these errors, which i think make 100% sense since the kafka configs were deleted (and easily fixed).

```
    API: SYSTEM(bucket=test)
    Time: 20:48:19 UTC 04/29/2020
    DeploymentID: 0b094524-b188-430e-bd6f-048d937ef8c1
    Error: ARN 'arn:minio:sqs::1:kafka' not found
           6: github.com/minio/minio@/cmd/notification.go:1366:cmd.readNotificationConfig()
           5: github.com/minio/minio@/cmd/notification.go:738:cmd.(*NotificationSys).load()
           4: github.com/minio/minio@/cmd/notification.go:783:cmd.(*NotificationSys).Init()
           3: github.com/minio/minio@/cmd/server-main.go:265:cmd.initAllSubsystems()
           2: github.com/minio/minio@/cmd/server-main.go:222:cmd.initSafeMode()
           1: github.com/minio/minio@/cmd/server-main.go:457:cmd.serverMain()
```

## Thank You! :)
