### ISSUE TITLE
[resolved] multipart upload error with minio.error.InvalidPart: InvalidPart (fs mode)

### ISSUE THREAD

**Issue by Eshwin** [minio/minio#9493]
## Expected Behavior
 I should be able to push the files with folder structure in minio storage

## Current Behavior
 I am trying to push  some folders with files in it using client.fput_object(). but while pushing i got the below error.

minio.error.InvalidPart: InvalidPart: message: One or more of the specified parts could not be found. The part might not have been uploaded, or the specified entity tag might not have matched the part's entity tag

I am calling client.fput_object() method to put the files in minio.
I am calling fput_objects inside a loop, where i am iterating with folders and files and pushing it.

## Steps to Reproduce (for bugs)

1. But another point is, I am not getting this error always, suddenly this errors comes.
so I am not able to reproduce this issue always.

## Context
 I am working on automation where i need to put some data in minio to test..fetching the data from git hub and pushing in minio 

## Regression
Is this issue a regression? (Yes / No)  No

## Your Environment
Include as many relevant details about the environment you experienced the bug in 
* Version used (`minio version`): 3.0.4
* Operating System and version (`uname -a`): Mac OS

**Comment by kannappanr** [comment]
@Eshwin Can you file an issue following the template we have?

**Comment by Eshwin** [comment]
@kannappanr I have updated my post
Thank you
 
Contributor
kannappanr

**Comment by kannappanr** [comment]
@Eshwin There is no minio version named `3.0.4`.  Can you provide the exact version of `minio`? Are you using `minio-py`? Please give as much info as possible for us to look at the issue. We need the actual version, sample code to reproduce with which you are reproducing this issue. 

Also, can you provide the command you used to start `minio`?

**Comment by Eshwin** [comment]
well to be more specific 
I am calling minio api using python code.
First i have created virtual environment(.sh file), there I am giving minio version to install 

$PYTHON_VENV_PATH $PIP_VENV_PATH install minio==3.0.4 requests urllib3==1.23 \

I am not using command to start the minio, I am using  minio APIs to connect using python

client = Minio(endpoint,
                  access_key=access_key,
                  secret_key=secret_key,
                  secure=True)

with this "client" object I am calling fput_object() method inside a loop.
the reason why it is inside loop because there is root folder , inside the root folder there are many sub folders and files within it.
So I am walking through each file path and pushing it in minio.

This code works perfectly and I am able to push all the files too, but some time the same code gives the above error(
minio.error.InvalidPart: InvalidPart: message: One or more of the specified parts could not be found.)

**Comment by harshavardhana** [comment]
> well to be more specific
> I am calling minio api using python code.
> First i have created virtual environment(.sh file), there I am giving minio version to install
> 
> $PYTHON_VENV_PATH $PIP_VENV_PATH install minio==3.0.4 requests urllib3==1.23 \
> 
> I am not using command to start the minio, I am using minio APIs to connect using python
> 
> client = Minio(endpoint,
> access_key=access_key,
> secret_key=secret_key,
> secure=True)
> 
> with this "client" object I am calling fput_object() method inside a loop.
> the reason why it is inside loop because there is root folder , inside the root folder there are many sub folders and files within it.
> So I am walking through each file path and pushing it in minio.
> 
> This code works perfectly and I am able to push all the files too, but some time the same code gives the above error(
> minio.error.InvalidPart: InvalidPart: message: One or more of the specified parts could not be found.)

First minio-py 3.0.4 is like 2yrs old you should use the latest release and let us know.

**Comment by Eshwin** [comment]
I tried with the version 5.0.10, but still it same for me.
The error is below

File "<stdin>", line 74, in <module>
  File "/data/jenkins/workspace/ci-benchmark-training-job_master/c9224bd6-cc92-475b-a59b-25c4d254bbbd/lib/python3.6/site-packages/minio/api.py", line 575, in fput_object
    content_type, metadata)
  File "/data/jenkins/workspace/ci-benchmark-training-job_master/c9224bd6-cc92-475b-a59b-25c4d254bbbd/lib/python3.6/site-packages/minio/api.py", line 781, in put_object
    data, length, metadata=metadata)
  File "/data/jenkins/workspace/ci-benchmark-training-job_master/c9224bd6-cc92-475b-a59b-25c4d254bbbd/lib/python3.6/site-packages/minio/api.py", line 1569, in _stream_put_object
    metadata=metadata)
  File "/data/jenkins/workspace/ci-benchmark-training-job_master/c9224bd6-cc92-475b-a59b-25c4d254bbbd/lib/python3.6/site-packages/minio/api.py", line 1653, in _complete_multipart_upload
    content_sha256=sha256_hex)
  File "/data/jenkins/workspace/ci-benchmark-training-job_master/c9224bd6-cc92-475b-a59b-25c4d254bbbd/lib/python3.6/site-packages/minio/api.py", line 1806, in _url_open
    object_name).get_exception()
minio.error.InvalidPart: InvalidPart: message: One or more of the specified parts could not be found. The part might not have been uploaded, or the specified entity tag might not have matched the part's entity tag

**Comment by harshavardhana** [comment]
> I tried with the version 5.0.10, but still it same for me.
> The error is below
> 
> File "", line 74, in
> File "/data/jenkins/workspace/ci-benchmark-training-job_master/c9224bd6-cc92-475b-a59b-25c4d254bbbd/lib/python3.6/site-packages/minio/api.py", line 575, in fput_object
> content_type, metadata)
> File "/data/jenkins/workspace/ci-benchmark-training-job_master/c9224bd6-cc92-475b-a59b-25c4d254bbbd/lib/python3.6/site-packages/minio/api.py", line 781, in put_object
> data, length, metadata=metadata)
> File "/data/jenkins/workspace/ci-benchmark-training-job_master/c9224bd6-cc92-475b-a59b-25c4d254bbbd/lib/python3.6/site-packages/minio/api.py", line 1569, in _stream_put_object
> metadata=metadata)
> File "/data/jenkins/workspace/ci-benchmark-training-job_master/c9224bd6-cc92-475b-a59b-25c4d254bbbd/lib/python3.6/site-packages/minio/api.py", line 1653, in _complete_multipart_upload
> content_sha256=sha256_hex)
> File "/data/jenkins/workspace/ci-benchmark-training-job_master/c9224bd6-cc92-475b-a59b-25c4d254bbbd/lib/python3.6/site-packages/minio/api.py", line 1806, in _url_open
> object_name).get_exception()
> minio.error.InvalidPart: InvalidPart: message: One or more of the specified parts could not be found. The part might not have been uploaded, or the specified entity tag might not have matched the part's entity tag

We can't seem to reproduce this at all not sure what this might have caused please explain your setup again like are you using

- erasure coded? fs mode?
- size of the object? - how frequently this error happens?
- what is the backend being used here?

**Comment by harshavardhana** [comment]
This should be fixed in the latest release @Eshwin PTAL

**Comment by gcsun** [comment]
i met the same problem.
minio version : 7.0.4
when upload a file (700M) with fput_object() function ,  the error occured.

but when upload a smaller file it's work well, such as 10M size file.

and when upload the 700M file through web browser, it's work well also.

anyone can help me, thanks a lot 


here is the error message:
```
---> 24 client.fput_object(bucket_name=bucket_name, object_name='test_fput', file_path=test_file_path
     25                    )
     26 

~/opt/anaconda3/envs/p37/lib/python3.7/site-packages/minio/api.py in fput_object(self, bucket_name, object_name, file_path, content_type, metadata, sse, progress, part_size, num_parallel_uploads, tags, retention, legal_hold)
   1022                 metadata=metadata, sse=sse, progress=progress,
   1023                 part_size=part_size, num_parallel_uploads=num_parallel_uploads,
-> 1024                 tags=tags, retention=retention, legal_hold=legal_hold,
   1025             )
   1026 

~/opt/anaconda3/envs/p37/lib/python3.7/site-packages/minio/api.py in put_object(self, bucket_name, object_name, data, length, content_type, metadata, sse, progress, part_size, num_parallel_uploads, tags, retention, legal_hold)
   1807                     bucket_name, object_name, upload_id,
   1808                 )
-> 1809             raise exc
   1810 
   1811     def list_objects(self, bucket_name, prefix=None, recursive=False,

~/opt/anaconda3/envs/p37/lib/python3.7/site-packages/minio/api.py in put_object(self, bucket_name, object_name, data, length, content_type, metadata, sse, progress, part_size, num_parallel_uploads, tags, retention, legal_hold)
   1792 
   1793             result = self._complete_multipart_upload(
-> 1794                 bucket_name, object_name, upload_id, parts,
   1795             )
   1796             return ObjectWriteResult(

~/opt/anaconda3/envs/p37/lib/python3.7/site-packages/minio/api.py in _complete_multipart_upload(self, bucket_name, object_name, upload_id, parts)
   1597                 "Content-MD5": md5sum_hash(body),
   1598             },
-> 1599             query_params={'uploadId': upload_id},
   1600         )
   1601         return CompleteMultipartUploadResult(response)

~/opt/anaconda3/envs/p37/lib/python3.7/site-packages/minio/api.py in _execute(self, method, bucket_name, object_name, body, headers, query_params, preload_content, no_body_trace)
    420                 query_params=query_params,
    421                 preload_content=preload_content,
--> 422                 no_body_trace=no_body_trace,
    423             )
    424         except S3Error as exc:

~/opt/anaconda3/envs/p37/lib/python3.7/site-packages/minio/api.py in _url_open(self, method, region, bucket_name, object_name, body, headers, query_params, preload_content, no_body_trace)
    394             self._region_map.pop(bucket_name, None)
    395 
--> 396         raise response_error
    397 
    398     def _execute(

S3Error: S3 operation failed; code: InvalidPart, message: One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag., resource: /dm-v2-task-bucket-task-1156/test_fput, request_id: 169381C037C2F244, host_id: e72e1d54-ec2b-45a9-a93b-b614b2724e03, bucket_name: dm-v2-task-bucket-task-1156, object_name: test_fput
```
