### ISSUE TITLE
[resolved] Sends empty Content-Encoding header for image/svg+xml mimetype

### ISSUE THREAD

**Issue by bkielczewski** [minio/minio#9506]
## Expected Behavior
No empty Content-Encoding sent, if there's no content encoding of course.

## Current Behavior
Sends empty Content-Encoding for object with mime type `image/svg+xml`. I'm guessing this is for other mime types as well.

## Steps to Reproduce (for bugs)
```
curl -v http://localhost:9000/bucket/image.svg
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Encoding:
< Content-Length: 12967
< Content-Security-Policy: block-all-mixed-content
< Content-Type: image/svg+xml
< ETag: "0b86a7a3eb0cfe9c46620087a80b606d-1"
< Last-Modified: Fri, 01 May 2020 13:50:30 GMT
< Server: MinIO/RELEASE.2020-03-05T01-04-19Z
< Vary: Origin
< X-Amz-Request-Id: 160AEFDA09BC1154
< X-Xss-Protection: 1; mode=block
< Date: Fri, 01 May 2020 15:05:38 GMT
```
For other types it seems ok:
```
curl -v http://localhost:9000/bucket/image.png
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 14727
< Content-Security-Policy: block-all-mixed-content
< Content-Type: image/png
< ETag: "db9430002464161a1b38a02885101545-1"
< Last-Modified: Fri, 01 May 2020 15:02:30 GMT
< Server: MinIO/RELEASE.2020-03-05T01-04-19Z
< Vary: Origin
< X-Amz-Request-Id: 160AF0087175B2A3
< X-Xss-Protection: 1; mode=block
< Date: Fri, 01 May 2020 15:08:57 GMT
```

## Context
That wouldn't be much of a problem as browsers ignore this header when empty. But imagine putting a proxy in front of minio and turning on gzip compression for this mime type. The result is double Content-Encoding headers, one empty, one gzip. Browsers don't seem to cope with that, i.e. Chrome tries to parse gzipped bytes as xml.

Work-around for nginx for anyone interested, just add that to your proxy config:
`more_clear_headers 'Content-Encoding';`

## Your Environment
Using docker image `minio/minio:RELEASE.2020-03-05T01-04-19Z`, but this behaviour is present in earlier ones.

**Comment by harshavardhana** [comment]
You need to set the correct content-type during PUT object, don't expect server to automatically fetch this information for you.

**Comment by bkielczewski** [comment]
@harshavardhana this issue is ***not*** about content-type header, which is sent correctly.

**Comment by harshavardhana** [comment]
> @harshavardhana this issue is ***not*** about content-type header, which is sent correctly.

You need to set the content-encoding as well during PUT to be sent back during Head or Get operations

**Comment by bkielczewski** [comment]
> You need to set the content-encoding as well during PUT to be sent back during Head or Get operations

I don't want `Content-Encoding` to be sent back. Since minio won't serve it gzipped this would be plain wrong. I don't want it to be sent at all when it's not set.

Maybe here's the problem. I'm using java client 7.0.1 to put the object, test case below:

```
    @Test
    fun shouldNotServeEmptyContentEncodingAfterThat() {
        val client = MinioClient("http://localhost:9000","access-key", "secret-key")
        val filename = "test.svg"
        val fileSize = Files.size(Path.of(filename))
        val objectName = StringUtils.getFilename(filename)
        val options = PutObjectOptions(fileSize, -1)
        options.setContentType("image/svg+xml")
        client.putObject("bucket", objectName, filename, options)
    }
```

Which results in:

```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Encoding: 
Content-Length: 12967
Content-Security-Policy: block-all-mixed-content
Content-Type: image/svg+xml
ETag: "0b86a7a3eb0cfe9c46620087a80b606d-1"
Last-Modified: Fri, 01 May 2020 16:34:43 GMT
Server: MinIO/RELEASE.2020-03-05T01-04-19Z
Vary: Origin
X-Amz-Request-Id: 160AF4B7989649AF
X-Xss-Protection: 1; mode=block
Date: Fri, 01 May 2020 16:34:47 GMT
```

So as you see if I don't set it, it has empty value, but should not be served at all.

**Comment by harshavardhana** [comment]
>     @Test
>     fun shouldNotServeEmptyContentEncodingAfterThat() {
>         val client = MinioClient("http://localhost:9000","access-key", "secret-key")
>         val filename = "test.svg"
>         val fileSize = Files.size(Path.of(filename))
>         val objectName = StringUtils.getFilename(filename)
>         val options = PutObjectOptions(fileSize, -1)
>         options.setContentType("image/svg+xml")
>         client.putObject("bucket", objectName, filename, options)
>     }

That is a bug in the client @bkielczewski, not server https://github.com/minio/minio-java/commit/62f58a1603e9cb009e4ae475e51dea22a58140b6 so upgrade to 7.0.2

**Comment by bkielczewski** [comment]
I can confirm it all behaves correctly after update to 7.0.2. Thanks for your help.
