### ISSUE TITLE
minio server failover

### ISSUE THREAD

**Issue by hebe9585** [minio/minio#9508]
minio server distributed to four work node. when files upload, shut down one work node which is the exectly the client real connected to. in this case, the left three minio server upload file will not success and also will not return fail until restart the node which was shutdown before. At this moment, the minio server recover four and the file upload will success.
## Expected Behavior

upload file will success no matter the shut down work node is the client real connected or not.   

## Current Behavior

minio server distributed to four work node. when files upload, shut down one work node which is the exactly the client real connected to. in this case, the left three minio server upload file will not success and also will not return fail until restart the node which was shutdown before(it's holding about Dozens of minutes ). At this moment, the minio server recover four and the file upload will success.

## Steps to Reproduce (for bugs)

1.set up distribution mode, four minio server distributed to four work node
2.shut down one work node which is the exact client real connected to.
3.the left three minio server is hanging over dozens of minutes until the shutdown work node recover.

## Context

minio failover cause the file upload time over dozens of minutes unless recover the shutdown work node.

## Your Environment

* Version used (`minio version`):RELEASE.2020-02-27T00-23-05Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
Please use the latest release and let us know @hebe9585

**Comment by hebe9585** [comment]
Hi ,
I tested on the latest version RELEASE.2020-05-01T22-19-14Z and found that after shut down node 25 mins, minio server return "A timeout occurred while trying to lock a resource" and also file upload failed. 
is it a correct reaction for minio?
Thanks so much. look forward for your reply.

**Comment by sapiens-sapide** [comment]
Hi, 
I'm considering Minio as a backend for an email service. I began an experimental platform few days ago on FreeBSD (12.1 RELEASE).  
I've installed four minio (v2020.04.15.00.39.01) within four freebsd's jails, with 4 disks each. I played with minio via the web interface.  

The fact is that,  
if I switch off a jail, so a minio node is down, the service becomes UN-USABLE. It takes minutes to do anything on the web interface or with `mc`.  
As soon as the node is back, everything works as expected.  
Working with `mc` is also very, very slow if a node is down. Even a simple command like `mc admin info <ALIAS>` takes 2 minutes to respond on the CLI…

Indeed, no data are lost when a node is down. But it's like if the whole service was almost down, for just one failure…

What's wrong ?

**Comment by klauspost** [comment]
@hebe9585 If you kill a server you cannot connect to it. That is how servers work. The issue as you describe it should be solved on the client side or through a load balancer.

@sapiens-sapide #9799 very significantly improves server performance when a server goes offline.

**Comment by harshavardhana** [comment]
Fixed in #9808 and #9858

**Comment by kedarkulkarni** [comment]
@hebe9585 does it work for you now?

**Comment by HenkHindriks** [comment]
So no automatic failover between nodes?
