### ISSUE TITLE
Suggestion - Remove accessKeyMinLen & secretKeyMinLen for MC and Minio Gateway

### ISSUE THREAD

**Issue by hassanbabaie** [minio/minio#9510]
This isn't a bug per say as I know it's deliberate however I think it should be removed

This relates to:
Minio Gateway
MC

## Expected Behavior

Today on both products you have the following validation

MC
cmd/config-utils.go
```
accessKeyMinLen = 3
secretKeyMinLen = 8
```

Minio GW:
```
pkg/auth/credentials.go

// Minimum length for MinIO access key.
	accessKeyMinLen = 3

// Minimum length for MinIO secret key for both server and gateway mode.
	secretKeyMinLen = 8
```

I think the Minimum Length should only be enforced on the **Minio Server application** and not on the Gateway or MC client.
I understand the rationale but I think it is slightly off, AWSCLI etc.. don't do this.

I suggest only enforcing the Minimum length for keys on MC and Minio GW to the minimum required for the code to work versus enforce good length practices as this is the role of the application your connecting to .

MC and Minio Gateway's are used as a tool to access other systems.

As an extreme example it would be like Google Chrome not allowing you to type a password in to the login page on hotmail.com because it was shorter than 10 characters. Do we feel this makes sense?

I would suggest if you want to warn users that they are crazy for having such a short access/secret key then stamp out a warning but not stop the product from working?

Again I've seen other tickets and the push back, but I just spent a couple of days forking Minio/MC only to try and change these to test something but come unstuck due to my lack of skills in programing and the go module paths...

So I thought I would try once more as I feel these are good intentions by minio but are incorrectly applied.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
// cc @aead

**Comment by hassanbabaie** [comment]
@harshavardhana @aead thanks for taking this ticket, let me know if I can help with any of it, I would do the PR but I had a problem when trying to test this using my fork due to module paths.

Thanks in advance

**Comment by harshavardhana** [comment]
> I think the Minimum Length should only be enforced on the **Minio Server application** and not on the Gateway or MC client.
> I understand the rationale but I think it is slightly off, AWSCLI etc.. don't do this.

We have best practices, these best practices are reflected in the software and do not see why this needs to be changed anywhere for that matter.

This is a design decision, I don't think we would change this behavior.

**Comment by hassanbabaie** [comment]
@harshavardhana I understand what you're saying but you should not apply that to an application that by design leverages the account management (and it's username/password rules) of another system.

I can understand 100% why it would be this way on Minio Server, but it should not be set this way on an S3 Client or S3 Gateway that is designed to connect to systems other than Minio Server. It doesn't seem like an appropriate design decision to put account (username/password) rules on something that has no management of the given user account. 

As of now it just flat out breaks the tool from being used on backends that don't conform to this with no method of getting round it.

**Comment by bdsoha** [comment]
I am unable to properly deploy a S3 Gateway because my organization uses access keys that are deemed too short by the abovementioned thread.

It would be great if this limitation could be circumvented via configs or *envs*.
