### ISSUE TITLE
Missing Prometheus metrics when restarting server with different Endpoint order

### ISSUE THREAD

**Issue by anthu** [minio/minio#9512]
Starting with the first April release my team realised that some disk-related metrics are missing or wrong for Prometheus. Affected metrics were minio_storage_* (missing) minio_disks_* (always 0).

After a while I could finally reproduce the behaviour in a different environment by permutating the endpoints when restarting the server.

## Expected Behavior
All metrics should be present after the restart

## Current Behavior
Disk related metrics are only present if the cluster is being started with exact the same endpoint order.

## Possible Solution
I could make it to work by removing the `IsLocal` check in
https://github.com/minio/minio/blob/master/cmd/xl-v1.go#L186

Be aware, I realised that removing the other check actually makes the metric to report metrics from a disk on another node (may be another bug effects versions prior to RELEASE.2020-04-02T21-34-49Z). 

## Steps to Reproduce (for bugs)
1. Start a cluster in distributed mode using:
` MINIO_ACCESS_KEY=minioadmin MINIO_SECRET_KEY=minioadmin ./minio server http://10.0.0.{1...4}:9000/data/disk1`
2. Check prometheus metrics -> eg. minio_disks_total = 1
3. Restart the same cluster with a different disk order, eg:
`MINIO_ACCESS_KEY=minioadmin MINIO_SECRET_KEY=minioadmin ./minio server http://10.0.0.2:9000/data/disk1 http://10.0.0.1:9000/data/disk1 http://10.0.0.3:9000/data/disk1 http://10.0.0.4:9000/data/disk1`
4. Check Prometheus metrics -> eg. Minio_disks_total is now 0, while /minio/admin/v3/{storageinfo, info} are showing total disks correctly and the cluster is operating as expected 

## Context
We used to generate the list of hosts and disks from Ansible repository. In the initial stage the hostname- & disk-order was random for each deployment. A strategy MinIO seemed not to care too much about. With the upgrade to RELEASE.2020-04-02T21-34-49Z we realised the absence of the metrics what could not have been associated with the former deployment strategy up until now.

## Regression
Yes
https://github.com/minio/minio/pull/9210/files#diff-ffeebb13b8b03478d42c5d299a72c69e

## Your Environment
* Version used (`minio version`): RELEASE.2020-03-25T07-03-04Z <-good-|-bad-> RELEASE.2020-04-02T21-34-49Z
* Server type and version: various, Debian & RHEL
* Operating System and version (`uname -a`): various, eg. Linux debian-2gb-nbg1-6 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux

I'm up to contribute a fix.

**Comment by harshavardhana** [comment]
@anthu you should upgrade to the latest and let us know.

**Comment by anthu** [comment]
Sorry, I might have been unclear on that point - we are running the latest release and still seeing this issue. I was just referring to the regression Release.

**Comment by annkam** [comment]
Hello, I confirm this problem. Yesterday I upgraded my 12-node cluster from RELEASE.2020-03-25T07-03-04Z to RELEASE.2020-05-01T22-19-14Z and now 11 nodes are exporting wrong disk related metrics to Prometheus. They're definitely wrong as mc admin info shows everything's ok.  It's minio_disks_total 0 and minio_disks_offline 0 while disk_storage_* is not exported at all. This is critical as we can't monitor our cluster properly without these metrics.

However, the order of the endpoints is the same in systemd units on each Minio VM:
  ```
server \
  --address 172.17.68.148:9000 \
   http://172.17.68.147/export http://172.17.68.148/export http://172.17.68.149/export http://172.17.68.150/export http://172.17.68.151/export http://172.17.68.152/export http://172.17.68.153/export http://172.17.68.154/export http://172.17.68.155/export http://172.17.68.156/export http://172.17.68.142/export http://172.17.68.144/export
```

Does it matter in which order I actually start Minio instances in this case?...

**Comment by harshavardhana** [comment]
> Hello, I confirm this problem. Yesterday I upgraded my 12-node cluster from RELEASE.2020-03-25T07-03-04Z to RELEASE.2020-05-01T22-19-14Z and now 11 nodes are exporting wrong disk related metrics to Prometheus. They're definitely wrong as mc admin info shows everything's ok. It's minio_disks_total 0 and minio_disks_offline 0 while disk_storage_* is not exported at all. This is critical as we can't monitor our cluster properly without these metrics.
> 
> However, the order of the endpoints is the same in systemd units on each Minio VM:
> 
> ```
> server \
> --address 172.17.68.148:9000 \
>  http://172.17.68.147/export http://172.17.68.148/export http://172.17.68.149/export http://172.17.68.150/export http://172.17.68.151/export http://172.17.68.152/export http://172.17.68.153/export http://172.17.68.154/export http://172.17.68.155/export http://172.17.68.156/export http://172.17.68.142/export http://172.17.68.144/export
> ```
> 
> Does it matter in which order I actually start Minio instances in this case?...

No there is no such order requirement, we will look at it soon @annkam
