### ISSUE TITLE
#9469 do not fix long file name on Windows

### ISSUE THREAD

**Issue by NMD49** [minio/minio#9515]
Despite merged pull request [#9469](https://github.com/minio/minio/pull/9469) long file name on Windows is not fixed.
## Expected Behavior
Same issue as [#9393](https://github.com/minio/minio/issues/9393)
## Current Behavior
`minio --version`
`minio version RELEASE.2020-05-01T22-19-14Z`

`API: PutObject(bucket=securisauve, object=data/G_792/srv-tse/c/users/denis/documents/gestion!20locative/heritier/propri!E9taire/20190101_a2.03!20-!20m.!20heritier!20re!B4mi!20-!20proce!60s-verbal!20de!20livraison!20et!20de!20remise!20des!20cle!B4s!20acque!B4reurs!20-!204-!20livraison!20-!20lp!20promotion!20toulouse!20-!20encre!20et!20plume!20-!205!20de!B4c.!202019!20a!60!2012-49.pdf.ecc)`
`Time: 15:21:32 CEST 05/04/2020`
`DeploymentID: 9a6de223-7664-4566-9fab-f81833b1c77c`
`RequestID: 160BD5E96B421B24`
`RemoteHost: 127.0.0.1`
`Host: 127.0.0.1:9000`
`Error: file name too long`
`       4: github.com\minio\minio@\cmd\fs-v1.go:970:cmd.(*FSObjects).putObject()`
`       3: github.com\minio\minio@\cmd\fs-v1.go:911:cmd.(*FSObjects).PutObject()`
`       2: github.com\minio\minio@\cmd\object-handlers.go:1439:cmd.objectAPIHandlers.PutObjectHandler()`
`       1: net\http\server.go:2007:http.HandlerFunc.ServeHTTP()`

**Comment by harshavardhana** [comment]
Are you using MinIO on windows or Linux?

**Comment by harshavardhana** [comment]
I see found the issue, looks like a random error we introduced.

**Comment by NMD49** [comment]
@harshavardhana Thank you !
