### ISSUE TITLE
Heal scheduled countdown remains constant

### ISSUE THREAD

**Issue by igomura** [minio/minio#9521]
```
$ mc admin heal <alias>
Background healing status:
 ●  8755 item(s) scanned in total
 ●  Completed 3 seconds ago
 ●  Next scheduled in 29 days
```

This 29 days countdown value remains constant forever. 

## Expected Behavior
It is expected for this countdown to change over time as it gets closer to the time when heal is scheduled for. For some reason this is not happening. Please correct me if my expectation is wrong.

## Current Behavior
The countdown shows constant value.

## Steps to Reproduce (for bugs)
1. mc admin heal <alias>

## Regression
No. I was always like that since it was introduced.

## Your Environment
* Version used (`minio version`): 2020-04-15T19:42:18Z
* Server type and version: linux amd64
* Operating System and version (`uname -a`): Linux localhost 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kannappanr** [comment]
@igomura Thanks for reporting this issue. We will take a look and get back to you.

**Comment by vadmeste** [comment]
@igomura sorry for the delay. I already tried to reproduce the issue before with no luck. Is the issue still there for you ? 

`mc --json admin heal <alias>` will show the exact time of the next heal cycle instead of the generic one (29 days), could you try it ?

**Comment by igomura** [comment]
It has been fixed in 2020-05-01T22:19:14Z or earlier. This issue can be closed.
