### ISSUE TITLE
[resolved] mc admin info inconsistent Bucket and space

### ISSUE THREAD

**Issue by i0x71** [minio/minio#9524]
## Actual behavior
i0x71@debian:~$ mc ls dot3 | wc -l
9

(I have 9 buckets and atleast 55GB of data)

Running mc admin info command within seconds of each other shows different bizzare results
 
mc admin info dot3 | grep Bucket
**11 GiB Used, 1 Bucket, 300,577 Objects**

mc admin info dot3 | grep Bucket
**72 GiB Used, 9 Buckets, 309,425 Objects**

mc admin info dot3 | grep Bucket
**61 GiB Used, 8 Buckets, 8,848 Objects**

mc admin info dot3 | grep Bucket
**11 GiB Used, 2 Buckets, 300,583 Objects**

No data was being uploaded at the time
If there is some additional info i can provide, please let me know

## mc --version
mc version RELEASE.2020-04-17T08-55-48Z

**Comment by i0x71** [comment]
fyi, all nodes show same incorrect behavior

**Comment by harshavardhana** [comment]
> What do you mean by commandline ?

`minio server <what>`  - the `<what>` is needed..

**Comment by i0x71** [comment]
minio server http://10.0.0.{3...9}/export/{0...1}/alpha

**Comment by i0x71** [comment]
Now it seems to be changing **exactly every 5 minutes**
Back and forth between
61 GiB Used, 8 Buckets, 8,848 Objects
11 GiB Used, 2 Buckets, 300,583 Objects

**Comment by harshavardhana** [comment]
> Now it seems to be changing **exactly every 5 minutes**
> Back and forth between
> 61 GiB Used, 8 Buckets, 8,848 Objects
> 11 GiB Used, 2 Buckets, 300,583 Objects

Enable this `MINIO_DISK_USAGE_CRAWL_DEBUG=on` and share the logs on the server.. which occur every 5 minutes.

**Comment by i0x71** [comment]
How do i enable it ?
Is it an environment variable i need to set before restarting server ?
do i enable with mc admin set ?

**Comment by harshavardhana** [comment]
> Is it an environment variable i need to set before restarting server ?

`MINIO_DISK_USAGE_CRAWL_DEBUG=on` - yes

**Comment by i0x71** [comment]
> > Is it an environment variable i need to set before restarting server ?
> 
> `MINIO_DISK_USAGE_CRAWL_DEBUG=on` - yes

Ok, is mc admin console host enough for log or is there another log that you need ?

**Comment by i0x71** [comment]
Fyi, minio version
minio version RELEASE.2020-04-28T23-56-56Z

**Comment by klauspost** [comment]
This could be a side effect of an un-synchronized cluster.

Could you try running `mc admin heal -r --scan=deep dot3/` assuming `dot3` is your cluster.

**Comment by i0x71** [comment]
> This could be a side effect of an un-synchronized cluster.
> 
> Could you try running `mc admin heal -r --scan=deep dot3/` assuming `dot3` is your cluster.
Ok, will post when its done

**Comment by i0x71** [comment]
> This could be a side effect of an un-synchronized cluster.
> 
> Could you try running `mc admin heal -r --scan=deep dot3/` assuming `dot3` is your cluster.

Ran heal a few times, however the issue remains, should i try updating minio or do you need any other info ?

**Comment by i0x71** [comment]
Any news on this ?

**Comment by annkam** [comment]
I have the same problem with minio version **RELEASE.2020-05-01T22-19-14Z** which appeared right after the upgrade.

mc admin info results with 5 min interval:

777 GiB Used, 26 Buckets, 560,680 Objects 
12 drives online, 0 drives offline 

and then

19 GiB Used, 6 Buckets, 23,700 Objects
12 drives online, 0 drives offline

I have upgraded another cluster and it's ok there.

**Comment by klauspost** [comment]
@i0x71 @annkam 

If you can set the environment variable `MINIO_DISK_USAGE_CRAWL_DEBUG=on` on all you servers, restart and capture the logs I can help you.

You can send them to klaus (at) minio (dot) io and I will treat them confidentially.

**Comment by klauspost** [comment]
This *could* have fixed it: https://github.com/minio/minio/pull/9569 - maybe check your logs.

**Comment by i0x71** [comment]
By logs are you referring to the mc admin console ? Is there another parameter to have minio log somewhere ?

**Comment by klauspost** [comment]
@i0x71 The logs the servers output to stdout while running.

**Comment by harshavardhana** [comment]
This should be fixed in latest release and it's released now @i0x71 the bucket usage should be consistent now. Closing for now please report back if that's not the case.
