### ISSUE TITLE
Audit Log should include Access Token created for AssumeRoleWith* requests

### ISSUE THREAD

**Issue by anthu** [minio/minio#9529]
**Is your feature request related to a problem? Please describe.**
We are using the STS feature where programmatic clients are connecting by assuming a role using WebIdentity (AWS S3 v2 Client). From that point we can track this client using the logged Access Key.

Unfortunately we cannot correlate the Auditlog for the AssumeRoleWith* with the requests using this AccessToken.

**Describe the solution you'd like**
The Auditlog could be extended by an additional struct to provide information about the request beyond HTTP Headers.
This could also be used to eg. identify the exact 403 Reason in other APIs

**Describe alternatives you've considered**
Time based correlation was not helpful due to parallel processing on the same host not sharing the same AccessKey, but OpenID credentials.

**Additional context**
We are seeing 403 responses for requests made using STS tokens. These tokens have been generated on the same host as they have been used for eg. GetObject. The same token does work on a different host for the same Object. We can not trace the whole request chain, nor identify the exact "Forbidden" reason.

**Comment by timhughes** [comment]
Same issue in the AdminUI where it has switched to a `Bearer` token. 


```
{
"version":"1",
"deploymentid":"d98222d1-af03-461d-a8f3-4b57ae296e04",
"time":"2020-05-18T16:47:19.972956586Z",
"api":{"name":"WebUpload",
"bucket":"disk2",
"object":"tenant2/somedata.txt",
"status":"OK",
"statusCode":200,
"timeToFirstByte":"0s",
"timeToResponse":"19.667509ms"},
"remotehost":"127.0.0.1",
"requestID":"16102D445411F343",
"userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0",
"requestHeader":{"Accept":"*/*",
"Accept-Encoding":"gzip, deflate",
"Accept-Language":"en-GB,en;q=0.5",
"Authorization":"Bearer eyJhXXXXXXXXXXXXXXXXXXXXXXVCJ9.eyJhY2XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXWluIn0.w1GBBtPsgODowkUYXtHY-e8IiYd4XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXMSipGQYrKbKys-TQ",
"Connection":"keep-alive",
"Content-Length":"0",
"Content-Type":"text/plain",
"Cookie":"grafana_session=dc3023a409aabb8692182f4b338aa25b",
"Dnt":"1",
"Origin":"http://127.0.0.1:9000",
"Referer":"http://127.0.0.1:9000/minio/disk2/tenant2/",
"User-Agent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0",
"X-Amz-Date":"20200518T164719Z"},
"responseHeader":{"Access-Control-Allow-Credentials":"true",
"Access-Control-Allow-Origin":"*",
"Access-Control-Expose-Headers":"Date, Etag, Server, Connection, Accept-Ranges, Content-Range, Content-Encoding, Content-Length, Content-Type, X-Amz*, X-Amz*, *",
"Content-Security-Policy":"block-all-mixed-content",
"ETag":"",
"Vary":"Origin",
"X-Amz-Request-Id":"16102D445411F343",
"X-Xss-Protection":"1; mode=block"}
}
```

**Comment by timhughes** [comment]
For the WebUI case If we add to getSessionToken the ability to get the "token" from the url parameters https://github.com/minio/minio/blob/a3f41c70498c0b8b18d036ff789e3249042bdff8/cmd/auth-handler.go#L175-L182

```go
 // Fetch the security token set by the client.
func getSessionToken(r *http.Request) (token string) {
	token = r.Header.Get(xhttp.AmzSecurityToken)
	if token != "" {
		return token
	}
	token = r.URL.Query().Get(xhttp.AmzSecurityToken)
	if token != "" {
		return token
	}
	return r.URL.Query().Get("token")
}
```
We then have the token when we get to `getClaimsFromToken` but `globalPolicyOPA` is `nil` and so are both `pokOpenID` and `pokSA` so we return the error `errAuthentication` on line 226   https://github.com/minio/minio/blob/a3f41c70498c0b8b18d036ff789e3249042bdff8/cmd/auth-handler.go#L192-L227 

The because we throw away the error the following, we end up with an empty `claims` which will disappear in the logging https://github.com/minio/minio/blob/a3f41c70498c0b8b18d036ff789e3249042bdff8/cmd/auth-handler.go#L186-L189  


I suspect that the Access Token created for AssumeRoleWith* disappears in `getClaimsFromToken` as well but I don't have a setup that can step through that with a debugger.

**Comment by timhughes** [comment]
I have just realised that this does work with AssumeRoleWithLDAPIdentity and i see something like
```json
{
  "version": "1",
  "deploymentid": "d98222d1-af03-461d-a8f3-4b57ae296e04",
  "time": "2020-05-18T20:35:52.716266219Z",
  "api": {
    "name": "GetObject",
    "bucket": "disk2",
    "object": "tenant1/somedata.txt",
    "status": "OK",
    "statusCode": 200,
    "timeToFirstByte": "3.262021ms",
    "timeToResponse": "3.313487ms"
  },
  "remotehost": "::1",
  "requestID": "161039BCE0225B81",
  "userAgent": "aws-cli/1.18.62 Python/3.8.2 Linux/5.6.12-300.fc32.x86_64 botocore/1.16.12",
  "requestClaims": {
    "accessKey": "1X2T9RX2LJ1L3HYZM5BX",
    "exp": 1590049225,
    "ldapGroups": null,
    "ldapUser": "Philip J. Fry"
  },
  "lotsMoreJson": {
    "gone":"This section has been removed"
  }
}
```

**Comment by anthu** [comment]
Hey @timhughes 
I think we're messing up different topics here.
I was referring to Audit logs regrading the API "AssumeRoleWith*". So something like

```
{
    "version": "1",
    "deploymentid": "a35f94a1-9a35-4e68-ba80-d57a3f8f4c74",
    "time": "2020-05-19T07:10:02.415737887Z",
    "api": {
        "name": "AssumeRoleWithWebIdentity",
        "status": "OK",
        "statusCode": 200,
        "timeToFirstByte": "207.100747ms",
        "timeToResponse": "207.14946ms"
    },
    "remotehost": "<redacted>",
    "requestID": "16105C582AE90501",
    "userAgent": "aws-sdk-java/2.11.6 Linux/3.10.0-1127.el7.x86_64 OpenJDK_64-Bit_Server_VM/11.0.7+10-LTS Java/11.0.7 vendor/Oracle_Corporation io/sync http/Apache",
    "requestHeader": {
        "Amz-Sdk-Invocation-Id": "035d9808-51fc-0622-1ceb-db1ce62feed4",
        "Amz-Sdk-Retry": "0/0/",
        "Content-Length": "1434",
        "Content-Type": "application/x-www-form-urlencoded; charset=utf-8",
        "User-Agent": "aws-sdk-java/2.11.6 Linux/3.10.0-1127.el7.x86_64 OpenJDK_64-Bit_Server_VM/11.0.7+10-LTS Java/11.0.7 vendor/Oracle_Corporation io/sync http/Apache",
        "X-Forwarded-For": "<redacted>"
    },
    "responseHeader": {
        "Accept-Ranges": "bytes",
        "Content-Length": "1776",
        "Content-Security-Policy": "block-all-mixed-content",
        "Content-Type": "application/xml",
        "ETag": "",
        "Server": "MinIO/RELEASE.2020-05-01T22-19-14Z",
        "Vary": "Origin",
        "X-Amz-Request-Id": "16105C582AE90501",
        "X-Xss-Protection": "1; mode=block"
    }
}
```

From this Audit Log I can not figure out what STS user has been created but looking at time and remotehost.

Decoded Bearer Token would be another **Feature Request** IMHO.

**Comment by anthu** [comment]
But an interesting thing in your shared Audit logs is the `timeToFirstByte` field in the first one. It shouldn't be at 0s 🤔

**Comment by vadmeste** [comment]
> But an interesting thing in your shared Audit logs is the `timeToFirstByte` field in the first one. It shouldn't be at 0s

Yes, I am aware with this. I will need to talk with the team about this. I am not sure how to define time to first byte when the body does not contain any data, like a 204 HTTP response code.

**Comment by anthu** [comment]
> > But an interesting thing in your shared Audit logs is the `timeToFirstByte` field in the first one. It shouldn't be at 0s
> 
> Yes, I am aware with this. I will need to talk with the team about this. I am not sure how to define time to first byte when the body does not contain any data, like a 204 HTTP response code.

Haha - true 🤔 
I'm not that familiar with Golang, but shouldn't the time to first byte be calculated on the first response byte of the header as provided here:
https://golang.org/pkg/net/http/httptrace/#ClientTrace

Thank you for looking into this and PR #9641 by your team removing the humanising - this will make profiling way easier

**Comment by timhughes** [comment]
@anthu Yeah i see what you mean. Similar but slightly different issue. I have raised another issue https://github.com/minio/minio/issues/9644 and moved some of my comments so as not to confuse the two.  


This is start of the auditlog event with `"timeToFirstByte":"0s",` for reference
```
{
   "version":"1",
   "deploymentid":"d98222d1-af03-461d-a8f3-4b57ae296e04",
   "time":"2020-05-18T16:47:19.972956586Z",
   "api":{
      "name":"WebUpload",
      "bucket":"disk2",
      "object":"tenant2/somedata.txt",
      "status":"OK",
      "statusCode":200,
      "timeToFirstByte":"0s",
      "timeToResponse":"19.667509ms"
   },
```

**Comment by harshavardhana** [comment]
A minor refactor is needed here, will send it coming week.
