### ISSUE TITLE
Support for User access control through Principal in Bucket policies

### ISSUE THREAD

**Issue by cywattebled** [minio/minio#9530]
## Expected Behavior
When setting a Bucket Policy through the AWS S3 SDK against the actual AWS S3, the policy allows to set Principals for which the policy would apply.

It would be great to allow managing Bucket access control through the principal field when Minio Users would be assigned to.

With the policy below, myUser1 and myUser2 would get read access to my-bucketname/*

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "myPolicy",
      "Action": [
        "s3:GetObject"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::my-bucketname/*"
      ],
      "Principal": { "AWS", ["minio:users/myUser1", "minio:users/myUser2"]}
    }
  ]
}
```

## Current Behavior
Principal fields seem to be ignored in bucket policies. There doesn't seem to be a way to assign ACL outside of using _mc_.

**Comment by kannappanr** [comment]
We support bucket policies only for anonymous users. You can create the same functionality using IAM policies for the user.

**Comment by harshavardhana** [comment]
This is as per design, there is no intention to support cross user policies for now. 

Bucket policies are only meant for anonymous users

**Comment by cywattebled** [comment]
@kannappanr @harshavardhana 
> We support bucket policies only for anonymous users. You can create the same functionality using IAM policies for the user.

Would you mind providing more information about how to create those IAM policies for the MinIO User? Did you mean to say through the group as described here?

https://docs.min.io/docs/minio-multi-user-quickstart-guide.html

**Comment by harshavardhana** [comment]
> @kannappanr @harshavardhana 
> > We support bucket policies only for anonymous users. You can create the same functionality using IAM policies for the user.
> 
> Would you mind providing more information about how to create those IAM policies for the MinIO User? Did you mean to say through the group as described here?
> 
> https://docs.min.io/docs/minio-multi-user-quickstart-guide.html

Yes

**Comment by cywattebled** [comment]
We are currently using minio to make our products work interchangeably when hosted on AWS or on-premise.
Our hope was to solely rely on AWS S3 SDK to manage bucket creation and subsequent access control policies.
 
The problem with this approach is that we can't and we had to integrate the internal API that mc admin tool uses to assign the policies to a group/user.

Using Principals in the Bucket policies would have been a nice approach to this truly transparent.

Would you suggest another approach to avoid having to use internal mc tool API ?

Thanks for you help.

**Comment by harshavardhana** [comment]
> We are currently using minio to make our products work interchangeably when hosted on AWS or on-premise.
> Our hope was to solely rely on AWS S3 SDK to manage bucket creation and subsequent access control policies.
> 
> The problem with this approach is that we can't and we had to integrate the internal API that mc admin tool uses to assign the policies to a group/user.
> 
> Using Principals in the Bucket policies would have been a nice approach to this truly transparent.
> 
> Would you suggest another approach to avoid having to use internal mc tool API ?
> 
> Thanks for you help.

@cywattebled mc is built using pkg/madmin API available in this repo.

**Comment by blackandred** [comment]
I also try to implement a Minio + Amazon S3 compatible app and hit a wall there as well as @cywattebled.
Will have to create for now as a workaround two adapters separate for Minio and S3.

It may be a good option in the future to make Min.io policies to be more compatible with S3, so the applications could be easily ported to Min.io :wink: Btw. Thanks for this cool project, I really appreciate it when hosting terabytes for non-profits (that would cost on S3) :+1:
