### ISSUE TITLE
Add a search/filter box for the minio browser

### ISSUE THREAD

**Issue by jdheyburn** [minio/minio#9531]
**Is your feature request related to a problem? Please describe.**
It is frustrating having to scroll through a bucket containing a large number of items in order to find a file.

**Describe the solution you'd like**
It would be helpful for the minio browser to include a text box used for filtering the currently selected bucket - in a way that is similar to how AWS S3 currently works (we use minio in gateway s3 mode).

**Describe alternatives you've considered**
The AWS CLI pointing to minio endpoint is an alternative, however it will be helpful to have this in the minio browser to help not just those in gateway s3 mode but in other modes too. 

**Additional context**
N/A

**Comment by darkdragon-001** [comment]
Still an issue.

**Comment by raarts** [comment]
As a new user it's surprising to me this is missing. Same for navigating folders by the way.

**Comment by harshavardhana** [comment]
> As a new user it's surprising to me this is missing. Same for navigating folders by the way.

Feel free to write the feature and send a PR @raarts we are happy to accept any patches.

**Comment by harshavardhana** [comment]
Minimal implementation was added in #10424 - but more deeper work - all-new features shall go here https://github.com/minio/console
