### ISSUE TITLE
[resolved] Disaggregated HDP Spark and Hive with MinIO 

### ISSUE THREAD

**Issue by coolljoe87** [minio/minio#9533]
Disaggregated HDP Spark and Hive with MinIO
refer : https://docs.min.io/docs/disaggregated-spark-and-hadoop-hive-with-minio.html
## Expected Behavior

scala> val file = sc.textFile("s3a://testbucket/testdata")
file: org.apache.spark.rdd.RDD[String] = s3a://testbucket/testdata MapPartitionsRDD[1] at textFile at <console>:24

scala> val counts = file.flatMap(line => line.split(" ")).map(word => (word, 1)).reduceByKey(_ + _)
counts: org.apache.spark.rdd.RDD[(String, Int)] = ShuffledRDD[4] at reduceByKey at <console>:25

scala> counts.saveAsTextFile("s3a://testbucket/wordcount")

## Current Behavior

scala> val file = sc.textFile("s3a://testbucket/testdata")
file: org.apache.spark.rdd.RDD[String] = s3a://testbucket/testdata MapPartitionsRDD[1] at textFile at <console>:24

scala> val counts = file.flatMap(line => line.split(" ")).map(word => (word, 1)).reduceByKey(_ + _)
java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.spark.hadoop.fs.s3a.S3AFileSystem not found
  at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2597)

## Your Environment

HDP 3.1.14-315 (hadoop 3.1.1 ,spark2.3.2)
minio : 2020-04-15T19:42:18Z
OS : ubuntu 18.04 x64 
hadoop fs -copyFromLocal /etc/hadoop/conf/log4j.properties s3a://testbucket/testdata
It is OK.
I know dependencies issue.
Do I need those *.jar and where do I copy them ?

**Comment by harshavardhana** [comment]
This looks like your spark is configured incorrectly.. if HDP is your vendor you need to ask HDP for missing jars here.

Doesn't look like a MinIO issue.

**Comment by coolljoe87** [comment]
OK,Thank you.I will ask the same question to cloudera.

**Comment by kannappanr** [comment]
@coolljoe87 Closing this issue as answered. Please feel free to reach out to us if you have further questions.

**Comment by coolljoe87** [comment]
I understood the issue.
  Your document show : spark-defaults.xml
  spark.hadoop.fs.s3a.impl=org.apache.hadoop.spark.hadoop.fs.s3a.S3AFileSystem
I change it.
  spark.hadoop.fs.s3a.impl=org.apache.hadoop.hadoop.fs.s3a.S3AFileSystem
It is OK.
scala> val counts = file.flatMap(line => line.split(" ")).map(word => (word, 1)).reduceByKey(_ + _)
counts: org.apache.spark.rdd.RDD[(String, Int)] = ShuffledRDD[4] at reduceByKey at <console>:25
