### ISSUE TITLE
how to start resume from break-point by Java client

### ISSUE THREAD

**Issue by tracy139** [minio/minio#9535]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by klauspost** [comment]
Without more information there isn't much we can do. Guessing by your topic:

If it is related to the java SDK there is documentation here: https://docs.min.io/docs/java-client-api-reference.html

If it is a problem specific to the java sdk open a more descriptive issue here: https://github.com/minio/minio-java

If it is a general Java problem, consult the appropriate documentation or you can ask here on slack: https://slack.min.io/
