### ISSUE TITLE
[resolved] Document typo in performance tuning

### ISSUE THREAD

**Issue by ftong2020** [minio/minio#9538]
In performance tuning [guide](https://github.com/minio/minio/tree/master/docs/deployment/kernel-tuning),  the swappiness recommandation is 1, while the text stated 10

Recommended virtual memory settings are as follows.

`swappiness : This parameter controls the relative weight given to swapping out runtime memory, as opposed to dropping pages from the system page cache. It takes values from 0 to 100, both inclusive. We recommend setting it to **10.**
sysctl -w vm.swappiness=**1**

**Comment by harshavardhana** [comment]
Those settings will be removed, as most of them don't make sense anymore on latest Linux kernels.
