### ISSUE TITLE
Long file name support on Windows (relative to fix #9515)

### ISSUE THREAD

**Issue by NMD49** [minio/minio#9539]
See issue [#9393](https://github.com/minio/minio/issues/9393).

@harshavardhana has done an excellent job with fix [#9515](https://github.com/minio/minio/pull/9520) which allows a long file path on Windows.

So I checked that PutObject mentioned in issue [#9393](https://github.com/minio/minio/issues/9393) worked.

I was very surprised when I got an error on `mkdir`.

After digging, I learned that each segment of a path on Windows should not exceed 255 characters. And it turns out that the file name mentioned in issue [#9393](https://github.com/minio/minio/issues/9393) exceeds 255 characters.

Please see [File System Limits](https://docs.microsoft.com/en-us/windows/win32/fileio/filesystem-functionality-comparison#limits).

@harshavardhana Sorry about that. 

When the filename is truncated to 255 characters, Minio accepts it. 

So I got an error but not the right one!

## Expected Behavior
A PutObject as mentionned in [#9393](https://github.com/minio/minio/issues/9393) should return 
an `errFileNameTooLong` error not because of the long path name which is fine but a segment of that path that exceeds 255 characters.
## Current Behavior
`minio version RELEASE.2020-05-06T23-23-25Z`

`API: PutObject(bucket=securisauve, object=data/G_792/SRV-TSE/c/users/denis/documents/gestion!20locative/heritier/propri!E9taire/20190101_a2.03!20-!20m.!20heritier!20re!B4mi!20-!20proce!60s-verbal!20de!20livraison!20et!20de!20remise!20des!20cle!B4s!20acque!B4reurs!20-!204-!20livraison!20-!20lp!20promotion!20toulouse!20-!20encre!20et!20plume!20-!205!20de!B4c.!202019!20a!60!2012-49.pdf.ecc)`
`Time: 12:28:45 CEST 05/07/2020`
`DeploymentID: 9a6de223-7664-4566-9fab-f81833b1c77c`
`RequestID: 160CB8397F63F1BC`
`RemoteHost: 127.0.0.1`
`Host: 127.0.0.1:9000`
`Error: mkdir F:\Minio/.minio.sys/buckets/securisauve/data/G_792/SRV-TSE/c/users/denis/documents/gestion!20locative/heritier/propri!E9taire/20190101_a2.03!20-!20m.!20heritier!20re!B4mi!20-!20proce!60s-verbal!20de!20livraison!20et!20de!20remise!20des!20cle!B4s!20acque!B4reurs!20-!204-!20livraison!20-!20lp!20promotion!20toulouse!20-!20encre!20et!20plume!20-!205!20de!B4c.!202019!20a!60!2012-49.pdf.ecc: La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte.`
`       4: github.com\minio\minio@\cmd\api-errors.go:1853:cmd.toAPIErrorCode()`
`       3: github.com\minio\minio@\cmd\api-errors.go:1878:cmd.toAPIError()`
`       2: github.com\minio\minio@\cmd\object-handlers.go:1428:cmd.objectAPIHandlers.PutObjectHandler()`
`       1: net\http\server.go:2007:http.HandlerFunc.ServeHTTP()`

## Possible solution
in `cmd/posix.go` function `checkPathLength` should - for OS Windows - check also that each path segment length is <= 255 as it does for all Unix platforms.

## Your Environment
Windows 10

**Comment by harshavardhana** [comment]
So what is this application which tries to create such long filenames on windows?

How does it even work when copying the data out of some centralized storage?

**Comment by NMD49** [comment]
@harshavardhana It is a backup software. Most of our customers use Windows and sometimes give very weird names...

In order to be compliant with S3 Object Key Naming Guidelines, we have our own encoding for the key name. All characters except `'()-.`, `0..9`, `A..Z`, `_` and `a..z` are encoded with `!xx` ie `!20` is a space.

On GetObjet, such a key name is decoded before creating file on disk.

That's why the file name does not exceed 255 characters on my customer's disk.

**Comment by harshavardhana** [comment]
That is not even necessary even on AWS S3, AWS supports all UTF-8 characters all you need to do is simply path encode them during upload and it shall be translated automatically by client SDK during download.

Adding unnecessary custom encoding has led to an expansion of the original pathname, in-fact you have reduced the overall character length in this process without relying on URL encoding.

I think this is bug in the backup software that needs to be fixed, as it never really had to make such assumptions to begin with.

I shall fix the MinIO code, but I think there is a design problem in the backup software here which can be simplified.

**Comment by NMD49** [comment]
I see your point.
In Object Key Naming Guidelines there is some characters to avoid and our customers use these characters.
So we did our own encoding to be sure that if one day we use another object storage we wouldn't have a problem.
I shall fix my software to ensure envery segment of an encoded path does not exceed 255 characters.
In that case, I shall refuse to backup the file.

**Comment by harshavardhana** [comment]
Fixed in #9594
