### ISSUE TITLE
[fixed] Multiarch container images for AMD64, ARM64, ARM and PPC64le

### ISSUE THREAD

**Issue by carlosedp** [minio/minio#9546]
Currently, Minio container images published on `minio/minio` only supports AMD64. 

I've changed the Minio and Minio-mc Dockerfiles to be able to build multiarch images using Docker buildx on Travis-CI using Minio published binaries from https://dl.min.io.

My repo on https://github.com/carlosedp/minio-multiarch provides the Dockerfiles and script. I could send a PR with these improvements if there is interest.

The images are built for AMD64, ARM, ARM64 and PPC64le. I publish them on https://hub.docker.com/r/carlosedp/minio and https://hub.docker.com/r/carlosedp/minio-mc

**Comment by harshavardhana** [comment]
> My repo on https://github.com/carlosedp/minio-multiarch provides the Dockerfiles and script. I could send a PR with these improvements if there is interest.

Let us know if this can be built automatically on hub.docker.com if they cannot be then its not that useful 

we already have the relevant Dockerfiles

```
[2020-05-05 10:40:22 PDT]  1.2KiB Dockerfile.arm.release
[2020-05-05 10:40:22 PDT]  1.2KiB Dockerfile.arm64.release
```

**Comment by carlosedp** [comment]
There is a sample repo that implements multiarch builds using DockerHub overriding the build phases:

https://github.com/rmoriz/multiarch-test

Requires some changes but might work. Any reason to not migrate image build to Travis?

**Comment by harshavardhana** [comment]
> Requires some changes but might work. Any reason to not migrate image build to Travis?

Our credentials cannot be shared with travis, we cannot trust CI/CD third parties for having push access to our repos - this is tightly controlled and internal requirement.

If https://hub.docker.com is where its hosted so the hosting provider has to be implicitly trusted anyways here, it is always either better to build in a local closed environment and push the containers or let hub build it securely on their servers.

**Comment by dwsteele** [comment]
Yes, please! I'd love to add S3 support to the pgBackRest ppc64le tests on Travis.

**Comment by skandragon** [comment]
bump: it'd be nice to have this on arm64

**Comment by harshavardhana** [comment]
It will be done @skandragon in future releases we already have the relevant docker files in place

**Comment by harshavardhana** [comment]
https://hub.docker.com/repository/docker/minio/minio/tags?page=1&name=RELEASE.2020-07-11T06-07-16Z multiarch containers are published now and will be thus released for each release.

**Comment by yasker** [comment]
Hi,

It seems `minio/minio:latest` is still an AMD64 only image.

```
$ docker manifest inspect --verbose minio/minio:latest
{
	"Ref": "docker.io/minio/minio:latest",
	"Descriptor": {
		"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
		"digest": "sha256:6a8dd42e0261a416db8af3a70e51b1853495ff168e6cb0d979a86c19102cb447",
		"size": 740,
		"platform": {
			"architecture": "amd64",
			"os": "linux"
		}
	},
	"SchemaV2Manifest": {
		"schemaVersion": 2,
		"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
		"config": {
			"mediaType": "application/vnd.docker.container.image.v1+json",
			"size": 4445,
			"digest": "sha256:73bc37c3cdd51968548cbbcd5443ea1dd91e3dfbb9a1cc67e4ddfeef3e832a26"
		},
		"layers": [
			{
				"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
				"size": 2797541,
				"digest": "sha256:df20fa9351a15782c64e6dddb2d4a6f50bf6d3688060a34c4014b0d9a752eb4c"
			},
			{
				"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
				"size": 21221148,
				"digest": "sha256:788b6860465fe06c085da0d02847da50edccdff1273928681c79e88a3ebad036"
			}
		]
	}
}
```

While comparing to a known multi-arch build:
```
$ docker manifest inspect --verbose rancher/local-path-provisioner:v0.0.17
[
	{
		"Ref": "docker.io/rancher/local-path-provisioner:v0.0.17@sha256:b41a024cb48ea5a2afee889e565c1b48e6b57aab762dec5f194f057e7f11a224",
		"Descriptor": {
			"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
			"digest": "sha256:b41a024cb48ea5a2afee889e565c1b48e6b57aab762dec5f194f057e7f11a224",
			"size": 740,
			"platform": {
				"architecture": "amd64",
				"os": "linux"
			}
		},
		"SchemaV2Manifest": {
			"schemaVersion": 2,
			"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
			"config": {
				"mediaType": "application/vnd.docker.container.image.v1+json",
				"size": 3057,
				"digest": "sha256:afa0746ea83b2d12b856138cd28209533b1a9f30a88863fdd07ff96a5a9542fd"
			},
			"layers": [
				{
					"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
					"size": 2797541,
					"digest": "sha256:df20fa9351a15782c64e6dddb2d4a6f50bf6d3688060a34c4014b0d9a752eb4c"
				},
				{
					"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
					"size": 10779545,
					"digest": "sha256:f648004d17480e9e69f9333bc139121e821c4c9236c7b5fbcd1c4e8e36bbccfb"
				}
			]
		}
	},
	{
		"Ref": "docker.io/rancher/local-path-provisioner:v0.0.17@sha256:9d7c3831d4e5d35e9ee689a800f1b5a69893249c86d9b393e7e371d41871ad18",
		"Descriptor": {
			"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
			"digest": "sha256:9d7c3831d4e5d35e9ee689a800f1b5a69893249c86d9b393e7e371d41871ad18",
			"size": 739,
			"platform": {
				"architecture": "arm64",
				"os": "linux"
			}
		},
		"SchemaV2Manifest": {
			"schemaVersion": 2,
			"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
			"config": {
				"mediaType": "application/vnd.docker.container.image.v1+json",
				"size": 3059,
				"digest": "sha256:f6128b5d29082563f680111106b7fb08337c7ba194e5258a1b0fe8120b06015c"
			},
			"layers": [
				{
					"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
					"size": 2707964,
					"digest": "sha256:b538f80385f9b48122e3da068c932a96ea5018afa3c7be79da00437414bd18cd"
				},
				{
					"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
					"size": 9808703,
					"digest": "sha256:0e08a774d4b407b4890ec587efdf670da1cf7a029969adeddfbc95b6e58464ad"
				}
			]
		}
	},
	{
		"Ref": "docker.io/rancher/local-path-provisioner:v0.0.17@sha256:dff538e0a9d8743d2decd27429446ec7a373de9338a12c0698de925dd2b7ab7e",
		"Descriptor": {
			"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
			"digest": "sha256:dff538e0a9d8743d2decd27429446ec7a373de9338a12c0698de925dd2b7ab7e",
			"size": 740,
			"platform": {
				"architecture": "arm",
				"os": "linux"
			}
		},
		"SchemaV2Manifest": {
			"schemaVersion": 2,
			"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
			"config": {
				"mediaType": "application/vnd.docker.container.image.v1+json",
				"size": 3056,
				"digest": "sha256:8ac42ae1ba750dfdb1c6284f0b52e97c937ed0c3b5d0e2a543aab4031a50134d"
			},
			"layers": [
				{
					"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
					"size": 2603286,
					"digest": "sha256:b4b72e716706d29f5d2351709c20bf737b94f876a5472a43ff1b6e203c65d27f"
				},
				{
					"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
					"size": 10044551,
					"digest": "sha256:8a6213e3e60c8535d025a5668d364203ce968ec33cd82dbf8800559fc494863a"
				}
			]
		}
	}
]
```

I am wondering is it just my setup or `minio/minio:latest` remains at AMD64 only? cc: @boknowswiki

**Comment by harshavardhana** [comment]
@yasker you need to use `minio/minio:RELEASE.2020-10-12T21-53-21Z-arm64` - for relevant platforms.

**Comment by harshavardhana** [comment]
As mentioned here https://hub.docker.com/repository/docker/minio/minio/tags?page=1&name=RELEASE.2020-10-12T21-53-21Z

**Comment by yasker** [comment]
Thanks for the quick reply @harshavardhana .

It's better if we can use the same deployment file/image for different architectures. For example, in the case of Local Path Provisioner https://github.com/rancher/local-path-provisioner , the deployment file remains the same for all the supported architectures since the image is built as a [multi-arch image](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/).

**Comment by yasker** [comment]
I think someone else is building a multi-arch image for MinIO (https://github.com/jessestuart/minio-multiarch), but we do wish to have the multi-arch image from the official MinIO repo.

**Comment by harshavardhana** [comment]
> Thanks for the quick reply @harshavardhana .
> 
> It's better if we can use the same deployment file/image for different architectures. For example, in the case of Local Path Provisioner https://github.com/rancher/local-path-provisioner , the deployment file remains the same for all the supported architectures since the image is built as a [multi-arch image](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/).

Unfortunately we don't have the luxury to do this right now.

**Comment by harshavardhana** [comment]
The latest release now has support for multiarch manifests @alexellis @yasker @skandragon

**Comment by alexellis** [comment]
@Waterdrips
