### ISSUE TITLE
Minio with docker volume does not start on Mac OS, O_DIRECT

### ISSUE THREAD

**Issue by AtzeDeVries** [minio/minio#9554]
Minio does not start anymore on mac os. 

## Expected Behavior

Run on linux
```
docker pull minio/minio:RELEASE.2020-05-08T02-40-49Z && docker run -v $HOME/temp:/storage minio/minio:RELEASE.2020-05-08T02-40-49Z server /storage
RELEASE.2020-05-08T02-40-49Z: Pulling from minio/minio
21c83c524219: Already exists 
9bdca4c12db8: Pull complete 
c414f3e2cf9d: Pull complete 
20d75f769f6a: Pull complete 
Digest: sha256:05dd142f7a67d3b79a84b24d1520c0c58876be14e165491b6dfca171fe11c1f6
Status: Downloaded newer image for minio/minio:RELEASE.2020-05-08T02-40-49Z
docker.io/minio/minio:RELEASE.2020-05-08T02-40-49Z
Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000

Browser Access:
   http://172.17.0.2:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
Detected default credentials 'minioadmin:minioadmin', please change the credentials immediately using 'MINIO_ACCESS_KEY' and 'MINIO_SECRET_KEY'
```

## Current Behavior

Run on mac os

```
docker pull minio/minio:RELEASE.2020-05-08T02-40-49Z && docker run -v $HOME/temp:/storage minio/minio:RELEASE.2020-05-08T02-40-49Z server /storage
RELEASE.2020-05-08T02-40-49Z: Pulling from minio/minio
21c83c524219: Already exists 
9bdca4c12db8: Pull complete 
c414f3e2cf9d: Pull complete 
20d75f769f6a: Pull complete 
Digest: sha256:05dd142f7a67d3b79a84b24d1520c0c58876be14e165491b6dfca171fe11c1f6
Status: Downloaded newer image for minio/minio:RELEASE.2020-05-08T02-40-49Z
docker.io/minio/minio:RELEASE.2020-05-08T02-40-49Z
ERROR Unable to initialize backend: Unable to write to the backend
      > Please ensure your disk supports O_DIRECT
      HINT:
        '/storage' does not support O_DIRECT flags, refusing to use
```

## Regression
related commit seems to be https://github.com/minio/minio/commit/2dc46cb153c81fc928a1990cb64df01ee71c74d8

**Comment by anthu** [comment]
It's obviously introduced in #9497 by intention.
But tbh this is a pretty harsh fix without that much context given in the PR.

To @vadmeste, @harshavardhana & @krisis
Docker on Mac was obviously working prior to this fix (there might have been some limitations like performance and such). 
Wouldn't a handling of an issue with stated "351.2M+ Docker pulls" could have been solved better than breaking stuff for a subset of users which are not running docker on linux hosts?

I would have wished something like a **RED WARNING** or Deprecation message. And I'm totally aware:
- this is OSS, so I could contribute a fix to this and limit the impact to users of exactly these two docker image tags
- some of you are working full time on it and have to adapt to wishes of paying customers 


But please keep in mind that not everybody is aware of O_DIRECT and most customers expect
> near-zero system administration tasks and fewer paths to failures.

In any case you are all doing a great job, delivering an amazing piece of software as OSS but don't leave your community behind. 

Sorry @AtzeDeVries for capturing your Issue for this!

**Comment by AtzeDeVries** [comment]
It seems like #9497 had a bit to much fixing it it. If you run the latest tag your software might break. 

I don't think it is the intention to require `O_DIRECT` if you run in standalone mode. Also check below:

> * Minio standalone works with no problem on the same configuration. Does it not need O_DIRECT?

Minio standalone is made to work on NAS like backends on purpose without the requirement of O_DIRECT @mrceresa 

> * How do I create a high-availability deployment in this case: do I run it in distributed mode + NASgateway or standalone+NAS and several replicas?

You deploy multiple NAS gateway instances pointing to same shared NAS - each gateway can be concurrently accessed and we manage the locking by using Filesystem locks.

_Originally posted by @harshavardhana in https://github.com/minio/minio/issues/7996#issuecomment-516742693_

**Comment by vadmeste** [comment]
O_DIRECT will avoid having any corrupted object after a server shutdown incident, but yes, maybe the check should be relaxed in some cases. We will discuss this.

**Comment by harshavardhana** [comment]
> O_DIRECT will avoid having any corrupted object after a server shutdown incident, but yes, maybe the check should be relaxed in some cases. We will discuss this.

The relaxation in case of FS mode might be fine for now, we need O_DIRECT only for erasure coding anyways.

**Comment by harshavardhana** [comment]
@vadmeste can you send a fix to relax the check for FS mode alone? We still need to keep the permissions check.

**Comment by vadmeste** [comment]
> @vadmeste can you send a fix to relax the check for FS mode alone? We still need to keep the permissions check.

Yes, I will do now

**Comment by CVarisco** [comment]
Hi everyone!
Is it possible that with `latest` image tag I have the same error?

Thanks for your support guys 👍 

Updated: I tested with `edge` tag and it works.

**Comment by tarikhagustia** [comment]
same here with latest tag

**Comment by 3pns** [comment]
same error here on OSX 10.14.6 with minio/minio:RELEASE.2020-08-16T18-39-38Z

Edit : I created a separate issue as there seem to be a regression #10277
