### ISSUE TITLE
API Compatibility with Azure Storage

### ISSUE THREAD

**Issue by atrauzzi** [minio/minio#9556]
**Is your feature request related to a problem? Please describe.**
I have some scenarios where applications are built to run both on Azure and standalone. When running standalone, we use minio and S3-related drivers. When running on Azure, our implementation is abstracted such that we simply swap drivers/SDKs to best leverage the platform we're running on.

While this works, it doesn't account for some differences in the APIs, such as generating single use keys (SAS vs presigned URLs).

**Describe the solution you'd like**
It would be nice if minio was able to be targeted by the official Azure Storage SDKs, thus reducing a layer of abstraction.

**Describe alternatives you've considered**
N/A

**Additional context**
Worth noting, I am not talking about the Azure bridge.

**Comment by harshavardhana** [comment]
MinIO is S3 only, for near future it will never speak any other API.
