### ISSUE TITLE
[faq] Cannot write to ZFS backend

### ISSUE THREAD

**Issue by CHTJonas** [minio/minio#9565]
A recent regression appears to be causing minio to fail at startup, complaining that a ZFS backend does not support O_DIRECT.

## Expected Behavior

Minio should startup as normal.

## Current Behavior

Minio fails to start due to an error:

```
ERROR Unable to initialize backend: Unable to write to the backend
      > Please ensure your disk supports O_DIRECT
      HINT:
        '/mnt/tank/blah' does not support O_DIRECT flags, refusing to use
```

## Steps to Reproduce (for bugs)

1. Create a new ZFS dataset.
2. Start minio with said dataset as its backend.
3. 😭

## Regression

This appears to be a regression. I have tested as working correctly in RELEASE.2020-05-01T22-19-14Z.

## Your Environment

* Version used (`minio version`): minio.RELEASE.2020-05-08T02-40-49Z version RELEASE.2020-05-08T02-40-49Z
* Operating System and version (`uname -a`): Linux 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Erasure coding needs O_DIRECT still,  if you are only using FS we have relaxed this already in PR #9558 

zfs latest versions also support O_DIRECT already.
