### ISSUE TITLE
Minio distributed mode deployment and scaling guide for kubernetes

### ISSUE THREAD

**Issue by rdev101** [minio/minio#9571]
Does someone have a good guide/documentation on deploying high performance minio in distributed mode on an aws eks cluster and on how to scale the cluster, I have been using the official minio helm charts for this and find that I am struggling to get more than ~1300 puts/sec.. I am not sure how i would go about scaling the cluster to break this put request throttle. I have tried deploying a 4 node cluster on 4 * c5.4xlarge and tried to scale it to 8 nodes and beyond but looks like the more nodes i add the slower it gets. I have also tried to scale the resources of each node vertically (more cpu , memory) but no impact. Any help would be much appreciated. Thank you.

**Comment by nitisht** [comment]
> I have tried deploying a 4 node cluster on 4 * c5.4xlarge and tried to scale it to 8 nodes and beyond but looks like the more nodes i add the slower it gets

@rdev101 a quick look at AWS EC Docs shows that c5.4xlarge is EBS only, with EBS throughput limited bandwidth to 4750 Mbps. This will limit the through put that MinIO can offer.

**Comment by nitisht** [comment]
@rdev101 closing this issue for now, please proceed with warp testing and we can review the capacity of the cluster.
