### ISSUE TITLE
Bucket contains more than 100 million items, listobject is not available

### ISSUE THREAD

**Issue by xiaosong135** [minio/minio#9574]
hi，
In our application scenario, a single bucket might contain a lot of objects, but our tests found that when the number is large, such as 100 million pieces of data, the listobject is completely unavailable. 
Is there any way to avoid or alleviate this problem？
Is there a recommended maximum number for a single bucket？
When the single-layer directory reaches 100 million, the listobject is not available. If we become 10,000 directories, under each directory, 10,000 objects, is it better?

**Comment by harshavardhana** [comment]
Please fill out all the details as requested in the issue template as requested here



## Expected Behavior



## Current Behavior



## Possible Solution



## Steps to Reproduce (for bugs)


1.
2.
3.
4.

## Context



## Regression



## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by xiaosong135** [comment]
### Expected Behavior
I hope that when a bucket can have more than 100 million objects, it can still have a normal listobject
### Current Behavior
When I used MC for ls, the listobject failed after a long time
### Possible Solution
When the single-layer directory reaches 100 million, the listobject is not available. If we become 10,000 directories, under each directory, 10,000 objects, is it better?
### Steps to Reproduce (for bugs)

1. Start the minio，Command is “minio server --address :9001 http://10.229.157.130:9001/data{1...16}”

2. Using cosbench putobject,Configuration is
![image](https://user-images.githubusercontent.com/12624490/81654709-54e49e80-9468-11ea-9901-4e5c617913eb.png)

3. I have a bucket and I have 100 million objects under it，Use MC for ls
mc ls myminio/pocrw20200304001 
or user S3Sdk to listobject

### Context

![image](https://user-images.githubusercontent.com/12624490/81655670-fa980d80-9468-11ea-9ff1-2c4e6fc8f92f.png)
### Regression
null
### Your Environment

mc version RELEASE.2020-03-14T01-23-37Z
minio version RELEASE.2020-05-08T02-40-49Z
cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)

**Comment by klauspost** [comment]
> If we become 10,000 directories, under each directory, 10,000 objects, is it better?

Yes.

**Comment by xiaosong135** [comment]
Is there any way to avoid or alleviate this problem？In addition to reducing the number of directories

**Comment by kannappanr** [comment]
adding a directory hierarchy instead of flat files will help you avoid these problems. With 100 million files in one directory, even regular `ls` on the file system will take a very long time. Closing this issue as answered, please feel free to reach out to us if you have further questions
