### ISSUE TITLE
Cant disable bin tracker.

### ISSUE THREAD

**Issue by lssolutions-ie** [minio/minio#9583]
Bin tracker is waking my disks every five minutes. I need to be able to disable this to avoid pointless disk wake ups. Any idea how to disable this?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
> Bin tracker is waking my disks every five minutes. I need to be able to disable this to avoid pointless disk wake ups. Any idea how to disable this?

Upgrade to latest it won't walk unless there is write activity @korshakov no need to disable it.

**Comment by lssolutions-ie** [comment]
Hello and thank you for coming back to me. I forgot to mention that minio is running in docker and it is indeed on the latest version. I have currently this variable in place
MINIO_DISK_USAGE_CRAWL_ENABLE=off
would that be somehow connected to that?
