### ISSUE TITLE
Nas gateway: InvalidBucketState: Object Lock configuration cannot be enabled on existing buckets

### ISSUE THREAD

**Issue by zzzuzik** [minio/minio#9585]
Hello,

Minio with the most latest version. I'm getting: 

`InvalidBucketState: Object Lock configuration cannot be enabled on existing buckets`

while trying to create a new bucket through terraform.
This is `nasgateway`. I see #9548 commit were made for lock/gateway.
Will it take care of this issue? If yes, could you please cut a new release. 
Thank you for the Minio

**Comment by kannappanr** [comment]
@zzzuzik I tested the latest master and did not see this issue. So, you will not see this issue with the next release. We will be making a release in a couple of days. We will send out a message on https://slack.min.io when we make a release. Closing this issue as answered, please feel free to reach out to us at https://slack.min.io if you have further questions

**Comment by zzzuzik** [comment]
Just upgraded to the latest release. It starts failing with:
`DEBUG: Validate Response s3/GetObjectLockConfiguration failed, attempt 0/25, error NotImplemented: A header you provided implies functionality that is not implemented`

looks like the terraform-aws waits for different error `MethodNotAllowed`
https://github.com/terraform-providers/terraform-provider-aws/blob/14c139d67eb1129c790d2bcd516ef7e40b440eac/aws/resource_aws_s3_bucket.go#L2680

**Comment by harshavardhana** [comment]
> Just upgraded to the latest release. It starts failing with:
> `DEBUG: Validate Response s3/GetObjectLockConfiguration failed, attempt 0/25, error NotImplemented: A header you provided implies functionality that is not implemented`
> 
> looks like the terraform-aws waits for different error `MethodNotAllowed`
> https://github.com/terraform-providers/terraform-provider-aws/blob/14c139d67eb1129c790d2bcd516ef7e40b440eac/aws/resource_aws_s3_bucket.go#L2680

That doesn't look correct @zzzuzik NotImplemented is a proper error and it shall not be implemented with NAS gateway/FS mode in MinIO - it should be properly ignored on the terraform side.

**Comment by harshavardhana** [comment]
https://github.com/terraform-providers/terraform-provider-aws/pull/13366 sent the fix here @zzzuzik

**Comment by zzzuzik** [comment]
@harshavardhana thank you for the light speed feedback. Will track it in the terraform provider. Cheers!
