### ISSUE TITLE
--address flag is ignored for "minio gateway s3"

### ISSUE THREAD

**Issue by ebozduman** [minio/minio#9599]
`"minio gateway s3"` command with `"--address :9001"` flag and endpoint pointing to the local minio server, `"http://localhost:9000"` fails with the following incorrect error message:

```
ERROR Invalid argument: endpoint points to the local gateway
```

The same/similar command successfully starts minio gateway on MacOS.

## Expected Behavior
Minio gateway starts successfully since the port numbers are different.

## Current Behavior
```
$ MINIO_ACCESS_KEY=user1 MINIO_SECRET_KEY=minio123 minio gateway s3 http://localhost:9000 --address :9001
ERROR Invalid argument: endpoint points to the local gateway
```
## Possible Solution
I think the issue here is the port number specified with `"--address"` flag is ignored and the         default port is used which causes the clash error.

## Steps to Reproduce (for bugs)
1. Start minio server at default port number, `":9000"`
$ MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123  minio server ~/data 
2. Set an alias for the server
$ mc config host add mm http://192.168.1.12:9000 minio minio123
Added `mm` successfully.
3. Create a user on the minio server
mc admin user add mm user1 minio123
Added user `user1` successfully.
4. Run the `minio gateway s3` command using a different port number and the newly created user credentials, and it fails
$ MINIO_ACCESS_KEY=user1 MINIO_SECRET_KEY=minio123 minio gateway s3 http://localhost:9000 --address localhost:9001
ERROR Invalid argument: endpoint points to the local gateway

## Context
Could not finish my review and testing of PR #9580 on my Ubuntu system.

## Regression
This could be a possible regression.

## Your Environment
Regular minio build from the top of the tree.

**Comment by ebozduman** [comment]
It looks like the problem was the placement of the `--address` flag in the command. AWS credentials were also missing, but that is irrelevant at this point.

The flag is supposed to be placed exactly in between `minio gateway` and `s3` in the command line, otherwise the port information is ignored and hence gateway uses the same default port, `9000`, which causes the error message.

By the way, `minio gateway s3` usage info is not correct.
``` $ minio gateway s3 -h
NAME:
  minio gateway s3 - Amazon Simple Storage Service (S3)

USAGE:
  minio gateway s3 [FLAGS] [ENDPOINT]
```

**Comment by harshavardhana** [comment]
> It looks like the problem was the placement of the `--address` flag in the command. AWS credentials were also missing, but that is irrelevant at this point.
> 
> The flag is supposed to be placed exactly in between `minio gateway` and `s3` in the command line, otherwise the port information is ignored and hence gateway uses the same default port, `9000`, which causes the error message.
> 
> By the way, `minio gateway s3` usage info is not correct.
> 
> ```
> NAME:
>   minio gateway s3 - Amazon Simple Storage Service (S3)
> 
> USAGE:
>   minio gateway s3 [FLAGS] [ENDPOINT]
> ```

This must be a recent mistake it is expected that `--address` to work for all sub-commands @ebozduman
