### ISSUE TITLE
Minio Tracker Still Active even after advise to update.

### ISSUE THREAD

**Issue by lssolutions-ie** [minio/minio#9600]
May 14   03:17:54 OPEN => /mnt/disk1/.minio.sys/buckets/.tracker.bin
May 14 03:22:54 OPEN =>   /mnt/disk1/.minio.sys/buckets/.tracker.bin
May 14 03:27:54 OPEN   =>/mnt/disk1/.minio.sys/buckets/.tracker.bin

This is happening every 5 minutes all the time.

I did already open this issue and i was told to update minio, but minio is on latest version.

Minio is running in docker with disabled crawler.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by klauspost** [comment]
Please fill out the form and describe what the actual problem you are experiencing is.

Update tracking is always running and will commit its data every 5 minutes.

**Comment by klauspost** [comment]
Seems to be a followup to #9583

**Comment by lssolutions-ie** [comment]
Thank you
