### ISSUE TITLE
minio[2126]: Waiting for a minimum of 6 disks to come online

### ISSUE THREAD

**Issue by narrington** [minio/minio#9605]
I'm trying to build a distributed cluster of minio servers. 3 servers, 4 drives each, using a service to run minio. when I clear the config (# rm -R /volume/{1...4}/* && rm -R /etc/minio/*) and start minio using the following command:
`# MINIO_ACCESS_KEY=[REMOVED] MINIO_SECRET_KEY=[REMOVED] /usr/local/bin/minio server -C /etc/minio http://192.168.1.{1...3}:8000/volume/{1...4}/`
things seem to work. I can access each node, upload files, all seems happy.
then I try to start the service (which basically evokes the same command) the system never starts but just keeps repeating "Waiting for a minimum of 6 disks to come online"

I'm not getting anything very verbose about the issue so I'm not %100 about where to start. the service is running as user "minio-user" which does not have login rights. but this was done per the documentation. I also did this in an attempt to eliminate a permissions problem:
`# chown minio-user:minio-user -vR /volume/ && chown minio-user:minio-user -vR /etc/minio/`
but I'm not positive that's all I need to do.

ideas?

## Steps to Reproduce (for bugs)
Followed this guide: https://linuxhint.com/install_minio_ubuntu_1804/
modified for my needs based on this documentation: https://docs.min.io/docs/distributed-minio-quickstart-guide.html

## Your Environment
running on Ubuntu server 20.04.

**Comment by narrington** [comment]
UPDATE* I removed the port# from the command and it works now... however this is not helpful. I will be adding TLS in the near future and I need to specify port 443 (don't I?)... adding that port back to the command breaks things.

**Comment by harshavardhana** [comment]
> `# MINIO_ACCESS_KEY=[REMOVED] MINIO_SECRET_KEY=[REMOVED] /usr/local/bin/minio server -C /etc/minio http://192.168.1.{1...3}:8000/volume/{1...4}/`

If you specified port here you need to match that with `--address ":8000"`
