### ISSUE TITLE
[resolved] Minio gateway s3 multipartupload failing with rclone copy

### ISSUE THREAD

**Issue by dpgarrick** [minio/minio#9608]
Follow on from #9597 -  unsure if this issue is related but additional context is provided there.

I set up a Minio s3 gateway with disk cache. I'm using rclone to transfer files to and from the s3 via the gateway endpoint.

By default, latest rclone does a multipart upload for files >200MB. I am trying to upload a 2GB file which is failing to upload via the gateway but uploads fine if the same command is used to upload directly to the aws s3 endpoint.

However, the upload is only successful through the minio gateway by disabling multipart upload with the rclone flag "--s3-upload-cutoff 3000M"  for the 2GB file.

mc cp can successfully upload the same file without issue via the minio gateway, even without --disable-multipart set, so unsure if it is using multipart upload or not.
## Expected Behavior

Using the basic rclone copy command to upload a file:

`rclone copy myfile.bin aws-s3:mybucket`

should work identically whether using the aws-s3 endpoint or the minio s3 gateway endpoint.

Only by disabling rclone multipart upload via --s3-upload-cutoff 3000M flag for a 2GB file does upload work to the minio gateway endpoint, i.e.
`rclone copy myfile.bin minio-s3:mybucket --s3-upload-cutoff 3000M`

## Current Behavior

Minio gateway is failing on multipart upload. When trying to attempt the upload the minio gateway server logs are giving me repeated messages of the form and the rclone upload progress hangs after getting to 45MB transferred.
```
minio[29196]: API: PutObjectPart(bucket=mybucket, object=myfile.bin)
May 15 15:56:02 h minio[29196]: Time: 15:56:02 NZST 05/15/2020
May 15 15:56:02 h minio[29196]: DeploymentID: 9a766332-491c-4220-b4fc-653eebd1bf94
May 15 15:56:02 h minio[29196]: RequestID: 160F176C2442FF46
May 15 15:56:02 h minio[29196]: RemoteHost: XXXXXXXXX
May 15 15:56:02 h minio[29196]: Host: XXXXXXXX
May 15 15:56:02 h minio[29196]: UserAgent: rclone/v1.50.1
May 15 15:56:02 h minio[29196]: Error: Your socket connection to the server was not read from or written to within the timeout period. Idle
May 15 15:56:02 h minio[29196]:        4: github.com/minio/minio@/cmd/api-errors.go:1853:cmd.toAPIErrorCode()
May 15 15:56:02 h minio[29196]:        3: github.com/minio/minio@/cmd/api-errors.go:1878:cmd.toAPIError()
May 15 15:56:02 h minio[29196]:        2: github.com/minio/minio@/cmd/object-handlers.go:2162:cmd.objectAPIHandlers.PutObjectPartHandler()
May 15 15:56:02 h minio[29196]:        1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```

## Possible Solution

Current workaround is to disable rclone multipart upload using the flag "--s3-upload-cutoff 3000M" since I know I will never be uploading >3GB files.

## Steps to Reproduce (for bugs)

1. Define cache settings for an s3 gateway
```
MINIO_CACHE="on"
MINIO_CACHE_DRIVES="/minio/cache"
MINIO_CACHE_QUOTA=80
MINIO_CACHE_AFTER=0
MINIO_CACHE_WATERMARK_LOW=70
MINIO_CACHE_WATERMARK_HIGH=90
MINIO_ACCESS_KEY=access_key
MINIO_SECRET_KEY=secret_key
```
2. Run Minio
```
minio gateway s3
```
2.  Download rclone from rclone.org, set up rclone.conf to gateway
```
[ms3]
type = s3
provider = Minio
env_auth = false
access_key_id = access_key
secret_access_key = secret_key
endpoint = localhost:9000
```
3. Multipart upload - first create a 20MB myfile.bin, then
```
rclone --config rclone.conf copy myfile.bin ms3:mybucket -vvv --s3-upload-cutoff 1M
```
4. Check minio server logs...
5. Disable multipart for 20mb file and upload via minio gateway
```
rclone --config rclone.conf copy myfile.bin ms3:mybucket -vvv --s3-upload-cutoff 100M
```
6. Alternatively multipart direct to aws s3 endpoint, which is successful

## Regression

Unknown

## Your Environment

* Version used (`minio version`):
`minio version RELEASE.2020-05-08T02-40-49Z`
```
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7
```
* Operating System and version (`uname -a`):
`5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by dpgarrick** [comment]
On a possibly related note, uploaded files are not being added to the minio cache as I expected from here https://github.com/minio/minio/pull/5182

The gateway endpoint is https but I otherwise do not have any encryption enabled in the minio gateway or on the s3 bucket. 

The cache quick start guide does not say anything about uploads and I can't find any other more detailed documentation, so has cache on PUT been disabled?  If not I can create another issue...

**Comment by kannappanr** [comment]
Cache on PUT is disabled for multi-parts

**Comment by dpgarrick** [comment]
> Cache on PUT is disabled for multi-parts

Ahh, great I see that it is indeed being cached when I disable multipart - original issue above is unrelated to that then. Thanks

**Comment by harshavardhana** [comment]
@dpgarrick please upgrade to the latest and let us know if you can still reproduce it.

**Comment by dpgarrick** [comment]
Seems to work without error now with the following
```
minio version 2020-06-18T02:23:35Z
```
```
rclone v1.52.1
- os/arch: linux/amd64
- go version: go1.14.4
```
