### ISSUE TITLE
Web UI: Add folder "..." menu > Download as zip

### ISSUE THREAD

**Issue by darkdragon-001** [minio/minio#9617]
**Is your feature request related to a problem? Please describe.**
It took me a while to find out that I can download a folder as zip when selecting it. 

**Describe the solution you'd like**
It would be more intuitive to offer this option via "..." menu similar as the one for single files.

**Describe alternatives you've considered**
Selecting it previously is not as intuitive as visually suggesting actions with the "..." menu.

**Additional context**
![No-folder-menu](https://user-images.githubusercontent.com/177976/82157245-8c948180-9880-11ea-9c5e-9239574af2b1.png)

**Comment by harshavardhana** [comment]
Please report the issue as a proper issue using our template, with screenshots, your version name etc.

Incomplete issues shall be closed as non actionable.

**Comment by darkdragon-001** [comment]
Updated issue to use _Feature request_ template. Please reopen.
