### ISSUE TITLE
Web UI: Selection improvements

### ISSUE THREAD

**Issue by darkdragon-001** [minio/minio#9618]
**Is your feature request related to a problem? Please describe.**
Selecting 100 items takes a long time...

**Describe the solution you'd like**
It would be awesome to improve selection behavior in the web ui by adding intuitive options as _Select all_ (button, Ctrl+A), _Remove selection_ (button, Esc), _Shift+click_ for selection range.

_Remove selection_ could be implemented `onClick()` for the selection checkmark in the blue selection menu.

**Describe alternatives you've considered**
Selecting many items one by one taking forever.

**Comment by harshavardhana** [comment]
Please use the feature request template properly. Closing this issue as non actionable..

**Comment by darkdragon-001** [comment]
Using the template now. Please reopen.

**Comment by darkdragon-001** [comment]
What would be the preferred of implementing _Select all_? An additional button in the blue selection menu? Should it go on the left side near the selection information? Or should a click on the checkmark first select all and only another click when everything is selected already would then remove selection? This way no additional button is needed although I doubt many users will find out this behavior intuitively.

**Comment by darkdragon-001** [comment]
This is still an issue.

**Comment by vasyakrg** [comment]
+1 This is still an issue.

**Comment by harshavardhana** [comment]
MinIO Browser is in sort of code-freeze and only taking bug fixes - all-new features shall go here https://github.com/minio/console
