### ISSUE TITLE
Web UI: Upload whole folder via drag&drop

### ISSUE THREAD

**Issue by darkdragon-001** [minio/minio#9619]
Folder upload via drag&drop would be really nice.

**Comment by harshavardhana** [comment]
Thanks for the issue we will not be supporting this, next time please use proper issue template.

**Comment by darkdragon-001** [comment]
Is there any reason, why you won't be supporting this? It should only be a few lines of frontend code, no backend changes necessary: https://stackoverflow.com/a/11410455/3779655

**Comment by harshavardhana** [comment]
> Is there any reason, why you won't be supporting this? It should only be a few lines of frontend code, no backend changes necessary: https://stackoverflow.com/a/11410455/3779655

Feel free to send a PR if you must, we do not have cycles to address this for now.

**Comment by darkdragon-001** [comment]
I created an [example](https://codesandbox.io/embed/elastic-haslett-xzk2g), but it requires newer versions of `react-dropzone` to have the `file.path` property available. I have seen that your React dependencies are quite outdated and have many security vulnerabilities. Do you plan on updating the dependencies?

**Comment by harshavardhana** [comment]
> I created an [example](https://codesandbox.io/embed/elastic-haslett-xzk2g), but it requires newer versions of `react-dropzone` to have the `file.path` property available. I have seen that your React dependencies are quite outdated and have many security vulnerabilities. Do you plan on updating the dependencies?

These examples are perfectly fine, whatever is needed you can update and show us your proposal and we shall take look.  If it makes sense we will take and make a release given no other functionality gets broken.
