### ISSUE TITLE
[faq] Config SSL on Docker

### ISSUE THREAD

**Issue by pramodShehan5** [minio/minio#9622]
Hello,

I am using minio docker. I want to configure SSL on minio.
**docker run -p 9000:9000 -e "MINIO_ACCESS_KEY=minio" -e "MINIO_SECRET_KEY=minio123" -v /tmp/.minio/:/root/.minio**

I have created cert using below command.
**sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /tmp/.minio/certs/private.key -out /tmp/.minio/certs/public.crt**

I can access this one using "https://127.0.0.1:9000".
There is some certificate related issues like "remote error: tls: unknown certificate"

Is there any way to fix this?

**Comment by nitisht** [comment]
You're using self signed certificates, hence the error. To add this as a trusted certificate, add the `public.crt` in `certs/CAs/` directory also. Closing this as answered.
