### ISSUE TITLE
[resolved] Enable user to specify private key file path and public cert file path (for Docker)

### ISSUE THREAD

**Issue by inieves** [minio/minio#9624]
Enable user to specify private key file path and public cert file path (for Docker)

This would be consistent with many other Docker images that allow this.

**Comment by harshavardhana** [comment]
Please use the issue template to better describe your issue and what issue you are facing. Without using templates the issue is not actionable for us.

**Comment by harshavardhana** [comment]
On the NOTE of certs, you can configure the directory (--certs-dir) wherever you want all we ask is it's `public.crt` and private.key 

The reason we ask the only directory and a consistent name for the `public.crt` and `privatey.key` -  is that we support auto-reloads of your certs once they are renewed without restarting the system, unlike other systems

**Comment by inieves** [comment]
Thanks for this information.  I am aware of --certs-dir.

Is it not possible to support auto-reload and configurable file paths at the same time?  When using Docker secrets, the secrets must exist in /run/secrets.  --certs-dir can be used to ask minio to look for files there.  No problem.  But secrets themselves often have more descriptive names than just private.key or public.crt because there are often many secrets in that directory.

This is minor overall, but people using Docker alot would find this functionality to be missing.

**Comment by harshavardhana** [comment]
> Is it not possible to support auto-reload and configurable file paths at the same time? When using Docker secrets, the secrets must exist in /run/secrets. --certs-dir can be used to ask minio to look for files there. No problem. But secrets themselves often have more descriptive names than just private.key or public.crt because there are often many secrets in that directory.
> 

Of course, it's possible but it is not simple @inieves  handling watches for individual files becomes a complicated ordeal, it would be worth to have watchers for just directories works on all platforms.

> This is minor overall, but people using Docker alot would find this functionality to be missing.

We have been at this for 6yrs now, and it has never come up,  we provide a richer functionality here so I guess the tradeoff is meaningful.

**Comment by inieves** [comment]
Thank you for your explanation
