### ISSUE TITLE
[faq] Increase number of disk on distributed minio cluster

### ISSUE THREAD

**Issue by patsevanton** [minio/minio#9625]
Hello!
Thanks for Minio.
Possible to increase number of disk on distributed minio cluster at Future?

https://github.com/minio/minio/issues/5205
https://github.com/minio/minio/issues/6672
https://github.com/minio/minio/issues/4364

**Comment by nitisht** [comment]
It is already available, pls refer the docs https://github.com/minio/minio/tree/master/docs/distributed#expanding-existing-distributed-setup
