### ISSUE TITLE
[faq] unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by pramodShehan5** [minio/minio#9626]
Hello,
I am using minio docker and java amazon sdk client. I have enabled SSL in minio docker.
Here I am using self signed certificate to configure SSL on minio.
After that I am getting  error called **"com.amazonaws.SdkClientException: Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target".**

Is there any way to fix it?

**Comment by nitisht** [comment]
Please try something like https://www.artificialworlds.net/blog/2015/12/07/java-https-to-a-server-with-a-self-signed-certificate/

Closing this as answered, pls join our slack channel for more such questions at https://slack.min.io
