### ISSUE TITLE
Distributed MinIO under Windows

### ISSUE THREAD

**Issue by sPhinX-LHJ** [minio/minio#9630]
I write a windows client application (by amazon s3 client, .net 4.0) to upload files to a minio server (run on the my notebook, windows 10), everything looks fine when I run the command:
`set MINIO_ACCESS_KEY=Test
set MINIO_SECRET_KEY=Test
minio server http://localhost:9000/D:\TestData{1...4}`
but when I edit command like this then run minio server again:
`minio server http://localhost:9000/D:\TestData{1...4} http://localhost:9000/E:\TestData{1...4}`
the upload progress became very slow.
for comparion:
1st time, upload 1GB+ cost 29s
2nd time upload 169MB cost 1m15s

I know "Running Distributed MinIO on Windows operating system is experimental. ", is the test result seems normal? Is there sth i can do to speed up my upload?

## Possible Solution
I dont know

## Steps to Reproduce (for bugs)
see top

## Your Environment
windows 10 1909
windows client application (by amazon s3 client, .net 4.0)

**Comment by klauspost** [comment]
You are specifying 2 zones on the same server.

What you probably want is a single zone with 1 set of 8 drives. You can specify that like this:

`minio server http://localhost:9000/D:\TestData1 http://localhost:9000/D:\TestData2 http://localhost:9000/D:\TestData3 http://localhost:9000/D:\TestData4 http://localhost:9000/E:\TestData1 http://localhost:9000/E:\TestData2 http://localhost:9000/E:\TestData3 http://localhost:9000/E:\TestData4`

**Comment by klauspost** [comment]
@harshavardhana 

Using this setup (in original post) makes memory usage explode and OOM for me. My estimate is that something is off with different zones on the same host.

We can either disallow it explicitly or look deeper. Thoughts?

**Comment by sPhinX-LHJ** [comment]
thank you for reply.
Actually what I am doing is  try to find a way to expand minio server storage, so I specify one zone on each phsycal drive. If I add 2 new storage drive(F:, G:), then I can run following command:
`minio server http://localhost:9000/D:\TestData{1...4}  http://localhost:9000/E:\TestData{1...4} http://localhost:9000/F:\TestData{1...4} http://localhost:9000/G:\TestData{1...4}`
Everything looks fine, minio server report no error or warning:
`minio server http://localhost:9000/D:\TestData{1...4}  http://localhost:9000/E:\TestData{1...4} http://localhost:9000/F:\TestData{1...4} http://localhost:9000/G:\TestData{1...4}
Waiting for all MinIO sub-systems to be initialized.. lock acquired
All MinIO sub-systems initialized successfully
Status:         16 Online, 0 Offline.
Endpoint:  http://169.254.210.221:9000  http://169.254.40.76:9000  http://169.254.115.58:9000  http://2.0.1.33:9000  http://192.168.50.24:9000  http://169.254.52.23:9000  http://169.254.57.17:9000  http://192.168.159.1:9000  http://192.168.2.1:9000  http://127.0.0.1:9000
AccessKey: Test
SecretKey: Test
Browser Access:
   http://169.254.210.221:9000  http://169.254.40.76:9000  http://169.254.115.58:9000  http://2.0.1.33:9000  http://192.168.50.24:9000  http://169.254.52.23:9000  http://169.254.57.17:9000  http://192.168.159.1:9000  http://192.168.2.1:9000  http://127.0.0.1:9000
Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc.exe config host add myminio http://169.254.210.221:9000 Test_Admin Test_Pass
Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide` 
My app runs no error, but upload speed is the problem.
I use minio not long, so please correct me if there is any error or misunderstanding.

**Comment by harshavardhana** [comment]
> @harshavardhana 
> 
> Using this setup (in original post) makes memory usage explode and OOM for me. My estimate is that something is off with different zones on the same host.
> 
> We can either disallow it explicitly or look deeper. Thoughts?

Do you have a memory profile @klauspost it looks incorrect to me..

**Comment by klauspost** [comment]
@sPhinX-LHJ ok - then you will likely have to wait for a fix. Good thing is it is rather easy to reproduce. We don't usually recommend expanding the setup on the same server.

@harshavardhana No, it crashes within a few seconds running warp. I suspect some recursive calling going on. I can investigate more tomorrow.

**Comment by sPhinX-LHJ** [comment]
@klauspost Is there something new? Please let me know, thx.
