### ISSUE TITLE
Web UI: Improve download behavior

### ISSUE THREAD

**Issue by darkdragon-001** [minio/minio#9632]
**Is your feature request related to a problem? Please describe.**
Make downloading items easier.

**Describe the solution you'd like**
- ~~Click on item should preview (e.g. images), open in new tab (if browser can open this file type) or download (if browser can't open directly)~~ _(conflicts with #9649)_
- `href` attribute should link to download location --> For example to make use of browsers' right-click > _Copy link URL_ action in order to paste the link into `wget` for headless systems
- Route `download/bucket/prefix.zip` to zip downloader

**Describe alternatives you've considered**
Everything is possible from the UI but has its shortcomings.

**Comment by darkdragon-001** [comment]
Still an issue.

**Comment by leohxj** [comment]
A question about how to implement zip download， minio not privoder this API，it should implements by client，right?

**Comment by darkdragon-001** [comment]
@leohxj Zip download is already implemented and working -> select multiple files or in the latest release use menu to download folder (#9631).

**Comment by harshavardhana** [comment]
MinIO browser is code freeze, all future browser work goes to https://github.com/minio/console
