### ISSUE TITLE
[working as intended] Output logs to console in Docker container

### ISSUE THREAD

**Issue by juanjoDiaz** [minio/minio#9643]
**Is your feature request related to a problem? Please describe.**
I'm running Minio using the oficial docker container.
I'm having some issues around presigned URL and there are no logs that I could find.
Without response or logs. It's impossible to know what's happening.

**Describe the solution you'd like**
Access log are output to console.
Maybe configurable to also output to a file.

**Comment by harshavardhana** [comment]
> **Is your feature request related to a problem? Please describe.**
> I'm running Minio using the oficial docker container.
> I'm having some issues around presigned URL and there are no logs that I could find.
> Without response or logs. It's impossible to know what's happening.
> 
> **Describe the solution you'd like**
> Access log are output to console.
> Maybe configurable to also output to a file.

This used to be the traditional model which led to useless logs being printed incessantly by the application, we got away from this model and built a better version which is called `mc admin trace`. 

Where a client can listen for API traces from the server this is a more productive way to debug because you can see what the server is doing at the time of the request arrived and what was the reason why it returned an error or success. 

A sample behavior can be seen as below when I perform `mc ls play/vadmeste/` 

```
play.minio.io [REQUEST s3.ListObjectsV2] 20:07:42.908
play.minio.io GET /vadmeste/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=
play.minio.io Host: play.minio.io
play.minio.io Content-Length: 0
play.minio.io User-Agent: MinIO (linux; amd64) minio-go/v6.0.58 mc/2020-07-03T19:40:50Z
play.minio.io X-Amz-Date: 20200703T200742Z
play.minio.io X-Forwarded-For: 24.4.6.252
play.minio.io X-Real-Ip: 24.4.6.252
play.minio.io Authorization: AWS4-HMAC-SHA256 Credential=Q3AM3UQ867SPQQA43P2F/20200703/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=0ed0f4a777bc22e40e43b08382e6a1473c92ba0e2d7d27633f503e3c3cd184b8
play.minio.io X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
play.minio.io X-Forwarded-Proto: https
play.minio.io 
play.minio.io [RESPONSE] [20:07:42.908] [ Duration 303.932ms  ↑ 121 B  ↓ 604 B ]
play.minio.io 200 OK
play.minio.io X-Amz-Request-Id: 161E56E5AE1FCDAB
play.minio.io X-Xss-Protection: 1; mode=block
play.minio.io Accept-Ranges: bytes
play.minio.io Content-Length: 350
play.minio.io Content-Security-Policy: block-all-mixed-content
play.minio.io Content-Type: application/xml
play.minio.io Server: MinIO/DEVELOPMENT.2020-07-02T23-22-09Z
play.minio.io Vary: Origin
play.minio.io <?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>vadmeste</Name><Prefix></Prefix><KeyCount>1</KeyCount><MaxKeys>50000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><CommonPrefixes><Prefix>dir/</Prefix></CommonPrefixes><EncodingType>url</EncodingType></ListBucketResult>
play.minio.io 
```

Closing this issue as we have sufficiently addressed this by making the debugging a more productive exercise than an administrative headache of managing logs.

**Comment by juanjoDiaz** [comment]
Hi @harshavardhana ,

Thanks for the response.

Your response targets debugging and relies on mc.
Logs can be used for more than just debugging on the fly. For example to retrospectively look at what happened already in a running server.
Also, I use Minio as a replacement for Amazon S3 for local deployment with no access to the cloud, so I use the AWS client instead of mc.
I guess that I could run a sidecar container with mc tracing at all times, but sounds like an overkill for something as trivial as getting logs.

**Comment by harshavardhana** [comment]
> Hi @harshavardhana ,
> 
> Thanks for the response.
> 
> Your response targets debugging and relies on mc.
> Logs can be used for more than just debugging on the fly. For example to retrospectively look at what happened already in a running server.

Retrospective requirement we have something called as audit logs, which can configured to log to any http endpoint.

> Also, I use Minio as a replacement for Amazon S3 for local deployment with no access to the cloud, so I use the AWS client instead of mc.

You should use mc, no reason not to. AWS client is a very limited tool.

> I guess that I could run a sidecar container with mc tracing at all times, but sounds like an overkill for something as trivial as getting logs.
> 
> 

We do log, but only in cases of situations when there are unhandled errors and we couldn't write a proper error response to the client.
