### ISSUE TITLE
[faq] Feedback on MinIO and TensorFlow Blog Post

### ISSUE THREAD

**Issue by hassanbabaie** [minio/minio#9648]
**Is your feature request related to a problem? Please describe.**

This is a quick bit of feedback on the on the recent MinIO and TensorFlow Blog Post by @dvaldivia 

**Describe the solution you'd like**

Hi @dvaldivia I've not used TensorFlow myself and might have a go at following your example when I get time as I think it really well documented. 

https://blog.min.io/hyper-scale-machine-learning-with-minio-and-tensorflow/

The only thing I was going to suggest is that you might want to do some benchmarking in doing this with a machine talking to a Minio Server and then also talking to Minio Server through a Minio Gateway.

**Describe alternatives you've considered**

The key part is dataload time (getting the data there for the GPU's to consume), I know you're doing some conversion to speed this up but when we were doing this at my prior company we got really good speeds when placing a Gateway using a local SSD and cache-control between the Minio Server and the server running in our case pytorch. We had help from @poornas @harshavardhana and a few of the community to get it running very fast

**Additional context**

**Comment by harshavardhana** [comment]
This doesn't look like a MinIO issue, please comment on the blog directly where it can be addressed. I shall close this issue for now.

**Comment by hassanbabaie** [comment]
thanks @harshavardhana agreed, I wasn't sure where to put it, I will do that
