### ISSUE TITLE
The service modification password under docker deployment prompts this: Credentials of this user cannot be updated through MinIO Browser.

### ISSUE THREAD

**Issue by cander0815** [minio/minio#9652]
The service modification password under docker deployment prompts this: Credentials of this user cannot be updated through MinIO Browser.

**Comment by klauspost** [comment]
Please use the provided template and fill in the information we ask. You can edit your top comment or close+reopen.

**Comment by harshavardhana** [comment]
> Please use the provided template and fill in the information we ask. You can edit your top comment or close+reopen.

Let's close incomplete issues.

**Comment by zhsn99** [comment]
I HAVE THE SAME PROBLEM! WHAT SHOULD I DO?

**Comment by cetrulin** [comment]
Me too. I'm running the last version of the docker container and I'm not able to change the credentials from the interface. Any way to proceed? Please, let me know if there is another thread for this. I have not been able to find anything similar.
