### ISSUE TITLE
When using a listobject, the first time can take a long time

### ISSUE THREAD

**Issue by xiaosong135** [minio/minio#9653]
### Expected Behavior
The listobject can be returned relatively quickly
### Current Behavior
When I have 2 million objects in my directory, the first return takes 18 minutes
### Possible Solution
Our tests found that this line of code took more than 17 minutes to execute
https://github.com/minio/minio/blob/0cc2ed04f59ccbf364b30c845139f839155eae22/cmd/posix.go#L917
We found out that this should just judge is a file or folder, and we wondered if we could move this line over here

https://github.com/minio/minio/blob/0cc2ed04f59ccbf364b30c845139f839155eae22/cmd/tree-walk.go#L96

Although some logic changes are required, the return time is reduced to less than two minutes.
I want to ask whether it is ok to change it like this？
### Regression
null

### Your Environment
mc version RELEASE.2020-03-14T01-23-37Z
minio version RELEASE.2020-05-08T02-40-49Z
cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)

**Comment by klauspost** [comment]
@xiaosong135 Sounds reasonable. I will take a look. 

Thanks for the great report and your research!

**Comment by harshavardhana** [comment]
Delay in leaf check is possible, it is the way we used to Walk in an older piece of the code before the leaf check was moved closer to the disk.

The primary reason for ListDir taking longer is you have pretty much dumped keys in a flat manner without heirarchy..

**Comment by xiaosong135** [comment]
Yes, but we have a lot of same-level objects in our business, so it's a big deal for us

**Comment by harshavardhana** [comment]
> Yes, but we have a lot of same-level objects in our business, so it's a big deal for us

That is unexpected for any filesystem, so it won't really scale beyond a certain value. It is better to create heirarchy for your future needs.

Also if you still want to stick to this model, you should keep the reference for each of these objects in an external database. Avoid doing unnecessary listing.

Any application can be changed to have heirarchy, and you control the application here - almost all applications do this for better management of objects. Look at large scale applications like hadoop, splunk, spark. 

Do this and it will be automatically better and everything would work normally.

**Comment by xiaosong135** [comment]
OK,thx
