### ISSUE TITLE
Ability to copy/move files in the web GUI

### ISSUE THREAD

**Issue by jdheyburn** [minio/minio#9654]
**Is your feature request related to a problem? Please describe.**
Minio web GUI does not provide a means of copying or moving a file from one location to another

**Describe the solution you'd like**
Additional buttons near to where Delete Object and Download Object currently are when an object is selected

**Describe alternatives you've considered**
Our workaround is to use the AWS CLI pointed to the minio endpoint to move the files

**Additional context**
N/A

**Comment by darkdragon-001** [comment]
In addition, Drag&Drop could be used to move files or folders.

**Comment by darkdragon-001** [comment]
Still an issue.

**Comment by harshavardhana** [comment]
MinIO Browser is in a sort of code-freeze and only taking bug fixes - all-new features shall go here https://github.com/minio/console
