### ISSUE TITLE
CompleteMultipartUpload: Reduce Time Between File Rename and Stat

### ISSUE THREAD

**Issue by shanebarnes** [minio/minio#9671]
When Minio is running as an object storage server there can be a significant time delay during the CompleteMultipartUpload operation between the file rename and file stat if the server is writing/deleting to a bucket on a NAS and the file uploaded consists of hundred or thousands of parts. This scenario presents a window of opportunity for the CompleteMultipartUpload to fail. For example, if the renamed file is moved out of the bucket by an external process before it can be stat'd by the CompleteMultipartUpload caller.

Here is the applicable [code](https://github.com/minio/minio/blob/master/cmd/fs-v1-multipart.go#L685):

```
        err = fsRenameFile(ctx, appendFilePath, pathJoin(fs.fsPath, bucket, object))
	if err != nil {
		logger.LogIf(ctx, err)
		return oi, toObjectErr(err, bucket, object)
	}
	fsRemoveAll(ctx, uploadIDDir)
	// It is safe to ignore any directory not empty error (in case there were multiple uploadIDs on the same object)
	fsRemoveDir(ctx, fs.getMultipartSHADir(bucket, object))
	fi, err := fsStatFile(ctx, pathJoin(fs.fsPath, bucket, object))
	if err != nil {
		return oi, toObjectErr(err, bucket, object)
	}
```

## Expected Behavior

I would expect the fsStatFile call to occur immediately after the fsRenameFile call to reduce the chance of an error being returned to the client that initiated the completion of the multipart upload.

## Current Behavior

If the renamed file is moved out of the bucket or to a different position in the bucket before the file stat is performed then a confusing response is returned to the client where an error message is found in the response body but the status code is set to 200. I am not sure, but this mapping of NoSuchKey with a 200 status code may also be a sign of a shadowed err variable.

Here is a sample response when using the AWS CLI as a client:

```
2020-05-21 17:09:50,830 - ThreadPoolExecutor-0_1 - botocore.hooks - DEBUG - Event request-created.s3.CompleteMultipartUpload: calling handler <function signal_transferring at 0x10f3bc040>
2020-05-21 17:09:50,831 - ThreadPoolExecutor-0_1 - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=http://127.0.0.1:9000/test/1G.bin?uploadId=3d57e713-d617-40f2-8d86-6b27bbe4e4a2, headers={'User-Agent': b'aws-cli/1.17.9 Python/3.8.1 Darwin/19.4.0 botocore/1.14.9', 'X-Amz-Date': b'20200521T210950Z', 'X-Amz-Content-SHA256': b'a400509105d17c93563b8301c1ba56b7e8559512180df18edfdf6a09adc77bda', 'Authorization': b'AWS4-HMAC-SHA256 Credential=minioadmin/20200521/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=26899cb9c885f0c3ddc313fdef017e74865f413d9dfd0812eb9b8d7fafb1ddbe', 'Content-Length': '17591'}>
2020-05-21 17:10:00,842 - ThreadPoolExecutor-0_1 - urllib3.connectionpool - DEBUG - http://127.0.0.1:9000 "POST /test/1G.bin?uploadId=3d57e713-d617-40f2-8d86-6b27bbe4e4a2 HTTP/1.1" 200 None
2020-05-21 17:10:51,135 - ThreadPoolExecutor-0_1 - botocore.parsers - DEBUG - Response headers: {'Content-Security-Policy': 'block-all-mixed-content', 'Content-Type': 'text/event-stream', 'Vary': 'Origin', 'X-Amz-Request-Id': '161127555182F0D8', 'X-Xss-Protection': '1; mode=block', 'Date': 'Thu, 21 May 2020 21:10:00 GMT', 'Transfer-Encoding': 'chunked'}
2020-05-21 17:10:51,136 - ThreadPoolExecutor-0_1 - botocore.parsers - DEBUG - Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n      <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>1G.bin</Key><BucketName>test</BucketName><Resource>/test/1G.bin</Resource><RequestId>161127555182F0D8</RequestId><HostId>f42342a9-dc70-45f3-a3fe-1b3371a9ae62</HostId></Error>'
```

## Possible Solution

Move the fsStatFile() as closely as possible to the fsRenameFile(). For example, maybe this would be better.

```
        err = fsRenameFile(ctx, appendFilePath, pathJoin(fs.fsPath, bucket, object))
	if err != nil {
		logger.LogIf(ctx, err)
		return oi, toObjectErr(err, bucket, object)
	}
	fi, err := fsStatFile(ctx, pathJoin(fs.fsPath, bucket, object))
	if err != nil {
		return oi, toObjectErr(err, bucket, object)
	}
	fsRemoveAll(ctx, uploadIDDir)
	// It is safe to ignore any directory not empty error (in case there were multiple uploadIDs on the same object)
	fsRemoveDir(ctx, fs.getMultipartSHADir(bucket, object))
```

## Steps to Reproduce (for bugs)

1. Upload a large multipart file to Minio that will require the CompleteMultipartUpload() a minute or more to finish (i.e., due to part cleanup). Alternatively, modify source code to sleep between file rename and stat in the CompleteMultipartUpload() function.
2. Remove file from Minio bucket once it is renamed while CompleteMultipartUpload() is still in progress.
3. Observe the 200 status code that is returned with a NoSuchKey error message in the response body.

## Context

I am not sure if this could occur with multiple clients accessing the same file. For example, client 1 completes multipart upload and client 2 deletes file that is renamed before it can be stat'd.

In my environment, I have a customer who automates the moving of files from the Minio bucket as they show up in the bucket. However, the bucket is using NAS and for large files (> 100GB) with thousands of parts, the part deletion can take a few minutes. If the file is moved out of the bucket during this time, then the client waiting for the multipart upload to complete gets notified that the upload failed.

This may be an edge case but it might also highlight a better ordering of the operations inside the fs.CompleteMultipartUpload() function.

## Your Environment
* Version used (`minio version`): RELEASE.2020-05-16T01-33-21Z (built from source)
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): Darwin SBarnes 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
* Link to your project:

**Comment by klauspost** [comment]
I would argue the metadata shouldn't be written until files are in place and the file has been stat'ed.

Order: rename, stat, write metadata, clean up.

**Comment by harshavardhana** [comment]
> For example, if the renamed file is moved out of the bucket by an external process before it can be stat'd by the CompleteMultipartUpload caller.

The external process shouldn't be modifying the backend, we need exclusive access - if exclusive access is not present then you can't use NAS gateway safely for uploads. 

We can't provide consistency when the backend is modified outside of MinIO. I don't think we can support cases where the backend is being modified and not waiting for CompleteMultipartUpload to return a successful response. 

It is considered only fully committed only when 200 OK is seen by the client with a proper response from the server.  If the application is modifying the object at the backend before this occurs then you are violating the contract we have here, what you are suggesting in terms of code change only reduces the window but doesn't completely remove the opportunity of this occurrence. 

Simplifying this portion is a good idea, I would additionally suggest fixing your application behavior to avoid mutating the backend directly.
