### ISSUE TITLE
ask for debug log and perf counter on the backend IO path

### ISSUE THREAD

**Issue by gwnet** [minio/minio#9687]
## Expected Behavior
after research I only see the HTTP trace. can we add the debug log for IO path? and performance counter for IO path?
^Cwayne@ubuntu:~/go/miniobin$ ./mc admin trace  -v -a  minio
192.168.147.148 [REQUEST (*webui).Upload] 13:25:35.042
192.168.147.148 PUT /minio/upload/test/LICENSE
192.168.147.148 Host: 192.168.147.148:9000
192.168.147.148 Accept-Language: en-US,en;q=0.5
192.168.147.148 Origin: http://192.168.147.148:9000
192.168.147.148 Referer: http://192.168.147.148:9000/minio/test/
192.168.147.148 User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0
192.168.147.148 Accept: */*
192.168.147.148 Accept-Encoding: gzip, deflate
192.168.147.148 Content-Length: 1517
192.168.147.148 X-Amz-Date: 20200523T132535Z
192.168.147.148 Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJtaW5pb2FkbWluIiwiZXhwIjoxNTkwMzIzNDk0LCJzdWIiOiJtaW5pb2FkbWluIn0.F6claLH4aFCB_3fyQXHvSfOu6hKorEcQRWU2Vc5F1Cc6E4PqxWV_7rhVt8F-Mrpu-0fnBQHYqKWv09qBFBvumg
192.168.147.148 Connection: keep-alive
192.168.147.148 <BODY>
192.168.147.148 [RESPONSE] [13:25:35.042] [ Duration 3.715ms  ↑ 1.6 KiB  ↓ 0 B ]
192.168.147.148 200 OK
192.168.147.148 X-Amz-Request-Id: 1611AB28C5744B52
192.168.147.148 X-Xss-Protection: 1; mode=block
192.168.147.148 Access-Control-Allow-Credentials: true
192.168.147.148 Access-Control-Allow-Origin: *
192.168.147.148 Access-Control-Expose-Headers: Date, Etag, Server, Connection, Accept-Ranges, Content-Range, Content-Encoding, Content-Length, Content-Type, X-Amz*, X-Amz*, *
192.168.147.148 Content-Security-Policy: block-all-mixed-content
192.168.147.148 Vary: Origin
192.168.147.148 <BODY>
192.168.147.148 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by nitisht** [comment]
Please use issue template properly for us to be able to help you. Check minio prometheus metrics for detailed metrics.

Join us on Slack for more questions. Closing this as answered.
