### ISSUE TITLE
Object Tagging is not working in distributed mode after expansion

### ISSUE THREAD

**Issue by ynnt** [minio/minio#9693]
Hello,
it looks like object tagging doesn't work in a distributed mode.
Trace: 
```
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>metadata.properties</Key><BucketName>registry</BucketName><Resource>/bucket/metadata.properties</Resource><RequestId>16120FC9B0F7927C</RequestId><HostId>0469e85c-0e25-446d-8515-f87a4bdb39ec</HostId></Error>
```

## Expected Behavior

Object receives tags.

## Current Behavior
Minio returns a wrong error.

## Possible Solution
I have no idea yet...

## Steps to Reproduce (for bugs)
1. Setup Minio in distributed mode
2. Expand a cluster
3. Try to upload an object and add some tags to it.

## Context
Cluster is unusable after expansion because some applications (Nexus) rely on tagging a lot.

## Regression
Yes

## Your Environment

* Version used (`minio version`): minio version RELEASE.2020-05-16T01-33-21Z

**Comment by harshavardhana** [comment]
Can you explain further about your setup?

**Comment by ynnt** [comment]
Yes.
Initially I had 4 nodes x 1 disk. Then I added 1 more disk to each node and expanded a cluster.

**Comment by ynnt** [comment]
Anyway, looks like it works when on master, do you have any ideas why?

**Comment by harshavardhana** [comment]
> Anyway, looks like it works when on master, do you have any ideas why?

Because we fixed quite a few bugs in this area already @ynnt - thanks for confirming, we will make a release coming week. Closing this issue as fixed for now.
