### ISSUE TITLE
[faq] minio server sync 

### ISSUE THREAD

**Issue by Danbuth** [minio/minio#9694]
**Is your feature request related to a problem? Please describe.**
I want sync  minio server data to another minio server at really time.
That is to say. when data update to minio server, the minio server will sync the date to another minio server.

**Describe the solution you'd like**
Can minio server data synchronized with other servers？ or minio server data sync to other servers？

**Comment by harshavardhana** [comment]
We are working on a project called RADIO you would want to look at that @Danbuth this is not part of MinIO https://github.com/minio/radio
