### ISSUE TITLE
[wontfix] Cannot create bucket with object lock feature enabled

### ISSUE THREAD

**Issue by laimutisign** [minio/minio#9696]
Starting with release RELEASE.2020-05-16T01-33-21Z new bucket with object lock feature enabled cannot be created.
Tested with MinIO server installed locally in Windows 10 computer as a service (with <a href="https://github.com/minio/minio-service/tree/master/windows">install-service.ps1</a>).

This prevents using the <a href="https://github.com/minio/minio/tree/master/docs/retention">Object Lock</a> functionality (Object locking requires locking to be enabled on a bucket at the time of bucket creation).

 ## Steps to Reproduce (for bugs)
Execute command with MinIO client:
```
mc mb myminio/test --with-lock
mc: <ERROR> Unable to make bucket `myminio/test`. A header you provided implies functionality that is not implemented
```
Or execute command with MinIO Java Client SDK:
```
minioClient.makeBucket("test", null, true);
error occurred
ErrorResponse(code = NotImplemented, message = A header you provided implies functionality that is not implemented, bucketName = test, objectName = null, resource = /test, requestId = 161219C7A34E2440, hostId = 661ac9d7-47da-4532-a232-d29753b9cc0b)
request={method=PUT, url=http://localhost:9000/test, headers=x-amz-bucket-object-lock-enabled: true
Host: localhost:9000
Accept-Encoding: identity
User-Agent: MinIO (amd64; amd64) minio-java/dev
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20200524T231243Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200524/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-bucket-object-lock-enabled;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=501, headers=Accept-Ranges: bytes
Content-Length: 314
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO/RELEASE.2020-05-16T01-33-21Z
Vary: Origin
X-Amz-Request-Id: 161219C7A34E2440
X-Xss-Protection: 1; mode=block
Date: Sun, 24 May 2020 23:12:43 GMT
}
```

## Regression
Is this issue a regression? Yes

The same command, is executed successfully in the same environment with previous MinIO server release RELEASE.2020-05-08T02-40-49Z:
```
mc mb myminio/test --with-lock
Bucket created successfully `myminio/test`.
```

## Your Environment

* Version used: RELEASE.2020-05-16T01-33-21Z
* Operating System and version: Windows 10 Pro [Version 10.0.18363.836]
* MinIO Java Client SDK: 7.0.2

**Comment by harshavardhana** [comment]
> Is this issue a regression? Yes
> 
> The same command, is executed successfully in the same environment with previous MinIO server release RELEASE.2020-05-08T02-40-49Z:

We do not support object locking with FS mode @laimutisign it will only work with erasure coded, it never really worked so don't use it and needs fundamentally different backend to support object locking.

So it is working as expected.

**Comment by gueste** [comment]
@harshavardhana can you please clarify under which circumstances minio is able to create buckets with object locking enabled?

**Comment by klauspost** [comment]
You must have a setup with more than one disk for this feature to be available: https://docs.min.io/docs/minio-erasure-code-quickstart-guide.html

Feel free to follow up on slack.
