### ISSUE TITLE
Get an object by its MD5

### ISSUE THREAD

**Issue by qwfy** [minio/minio#9699]
**Is your feature request related to a problem? Please describe.**
Yes. Here are my use cases:
1) At work, a lot large binary files are required/produced, that needs to be versioned, ideally they could be version controlled with git, but git doesn't handle large files very well (even with git-lfs).
2) Putting large files in a docker build context cause docker to send it to the daemon, if the file is large, this takes a lot of time.

In either cases, what I actually what is a way to specify a specific version of a file, if minio support this, I could store the file out of git/docker build context dir, and store the link some how in the git/Dockerfile

**Describe the solution you'd like**
Add a command line option to the minio client, maybe like this: `mcli cp --soruce-md5 xxxxxx source-file-name dest-file-name`. Before the copying, if mcli finds out that the source-file-name's md5 is not what specified in the cli, it refuses to copy, or better, mcli can store multiple versions of source-file-name, and --source-md5 selects the specific one.

**Describe alternatives you've considered**
Write and http server and a client, store every file with md5 as the key, and file name as an attribute, upon copying, select what to copy based on the md5, and verify the source-file-name matches.

**Additional context**
None

**Comment by harshavardhana** [comment]
Not part of S3 API spec @qwfy we only implement S3 API and limit extensions.

If you want to build CAS like functionality you need to build this outside in your application.

**Comment by qwfy** [comment]
For anyone who wants a simple solution: https://github.com/qwfy/with-b3#use-case
