### ISSUE TITLE
directIO support question

### ISSUE THREAD

**Issue by gwnet** [minio/minio#9700]
## Expected Behavior
I run S3 benchmark on minio, I see the linux page cache grow very quickly. do minio support directIO mode to file system?

direct IO is more safe. other enterprise product use directIO to persist data.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
We support direct IO mode in erasure coded setups, please explain your setup properly the issue is fully empty here.

**Comment by gwnet** [comment]
thank you so much. @harshavardhana I will test erasure code setup. currently I just run one drive. the most simple setup.

**Comment by klauspost** [comment]
Feel free to follow up on slack.
