### ISSUE TITLE
minio gateway --json nas stdout not in json format on some occasions

### ISSUE THREAD

**Issue by rajeshamdev** [minio/minio#9708]
/px/bin/minio gateway --json nas --address IPA:PORT /mnt/test | python3 -m json.out
Extra data: line 2 column 1 - line 3 column 1 (char 161 - 370)

This indicates that the output not in json format. Here is the complete output.

{
    "level":"INFO",
    "errKind":"",
    "time":"2020-05-26T14:24:07.036560639Z",
    "message":"Attempting encryption of all config, IAM users and policies on MinIO backend\n"
}

{
    "level":"FATAL",
    "errKind":"",
    "time":"2020-05-26T14:24:07.074655841Z",
    "error":{
        "message":"config data not in plain-text form or encrypted",i
        "source":["cmd/gateway/nas/gateway-nas.go:79:nas.nasGatewayMain()"]
    }
}

On another instance, it was in json format:
minio gateway --json nas --address IPA:PORT  /mnt/test2 | python3 -m json.tool
{
    "errKind": "",
    "error": {
        "message": "Specified port is already in use: listen tcp 172.22.12.97:9002: bind: address already in use",
        "source": [
            "cmd/gateway/nas/gateway-nas.go:79:nas.nasGatewayMain()"
        ]
    },
    "level": "FATAL",
    "time": "2020-05-26T15:45:55.242033518Z"
}

## Expected Behavior

It stdout to be in json format as advertised.

In case of error, one json object describing the error.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by rajeshamdev** [comment]
I am on RELEASE.2020-02-27T00-23-05Z

**Comment by harshavardhana** [comment]
It is in the format called jsonlines which is JSON standard - http://jsonlines.org/ you need to use tools like jq or use a python parser which support jsonlines document format.

This is working as intended.

**Comment by rajeshamdev** [comment]
Thanks @harshavardhana for looking at this.

For the single goal - to convey service start success/failI - what is the rationale of having two json results ? If there is a reason for two jsons, which one should we most rely on?
