### ISSUE TITLE
Use SPDK BlobFS as minio backend storage

### ISSUE THREAD

**Issue by jumpapex** [minio/minio#9716]
As we know SPDK BlobFS can bypass kernel and direct write to NVMe device. 
I wonder whether Using SPDK BlobFS as minio backend storage could improve the performance. 
If it is, are we going to work on it. Thanks!

**Comment by harshavardhana** [comment]
Gateway part is feature complete, not taking anymore requests in the near future which are not already blessed.

If you want to write one keep a fork and maintain it yourself, there are already dozen others maintained in this manner.
