### ISSUE TITLE
Immutable blobs for FS backend

### ISSUE THREAD

**Issue by dionorgua** [minio/minio#9723]
**Is your feature request related to a problem? Please describe.**

It looks like currently there are two backends with different behavior. FS allows blob overwriting (replacing one blob content with another without delete) and XL is immutable. It would be cool to have a way for immutable objects with FS backend too. 

#150 was related issue. I was actually confused by first comment 'every object uploaded is immutable by design'.

**Describe the solution you'd like**
it doesn't matter how to do this, via configuration/env variable or bucket policy (like requiring of  `DeleteObject` permission to replace data)

**Describe alternatives you've considered**
Alternatively it's possible to get mostly similar behavior using retention/lock but now it also doesn't work with FS backend

**Additional context**
I'm trying to get append-only behavior for `restic` backup program: after uploading there should be no way to 'modify/replace/overwrite' content.

**Comment by nitisht** [comment]
> #150 was related issue. I was actually confused by first comment 'every object uploaded is immutable by design'.

This is more than five years old. A better way to understand current behaviour is to take a look at our documents. 

Immutability is handled by server using object retention APIs as explained here https://github.com/minio/minio/tree/master/docs/retention . This is applicable to FS / XL backends. Closing this issue as answered

**Comment by dionorgua** [comment]
Hi,
I've looked to docs before creating this. 

As I said there is no way to use retention API with FS backend with latest version:
```
mc mb --with-lock minio/withlock
mc: <ERROR> Unable to make bucket `minio/withlock`. A header you provided implies functionality that is not implemented
```
It was already reported in #9696 

Surely it's still possible to use it with already-created bucket (or create bucket with old version of minio) but it sounds wrong.

**Comment by harshavardhana** [comment]
> ```
> mc: <ERROR> Unable to make bucket `minio/withlock`. A header you provided implies functionality that is not implemented
> ```

Not for FS only erasure coded @dionorgua

**Comment by dionorgua** [comment]
Yes. Now I know this.. That's actually why I created this ticket. Currently there is no way to make bucket immutable with FS. I can disable 'GetObject' and 'DeleteObject' via bucket policy. But it doesn't makes sense if 'PutObject' can overwrite existing data.

**Comment by harshavardhana** [comment]
> Yes. Now I know this.. That's actually why I created this ticket. Currently there is no way to make bucket immutable with FS. I can disable 'GetObject' and 'DeleteObject' via bucket policy. But it doesn't makes sense if 'PutObject' can overwrite existing data.

It will never be implemented @dionorgua the issue will remain closed. Object locking requires versioning and versioning will be never implemented in FS.

Look here https://github.com/minio/minio/pull/9377

**Comment by kliberty** [comment]
@harshavardhana Can you reference a specific rational for why versioning will never be implemented in FS? This seems to affect the whole category of Minio deployments co-located with other services that need to run with a RAID backend.

**Comment by harshavardhana** [comment]
> @harshavardhana Can you reference a specific rational for why versioning will never be implemented in FS? This seems to affect the whole category of Minio deployments co-located with other services that need to run with a RAID backend.

Rationale is simple - why would you need to use RAID ? 

Use MinIO across multiple drives provides better protection than RAID would.

**Comment by makkarpov** [comment]
Because minio can share single RAID drive with other processes that are unaware of S3. I cannot dedicate these drives to minio. Furthermore server that I using does not have four drives to enable erasure coding.

Why does object locking require versioning? What is actually needed is to make `PutObject` fail if object already exists. No versions, no erasure coding, just a simple `if` that would make overwrite operation fail (unless authorized by policy). I don't understand why is this feature specific to erasure coded mode.

By the way, my specific use case is exactly the same as in original question: `restic` backups. I want to restrict access keys that are used for backup to make it impossible to corrupt already stored data, just append-only semantics.
