### ISSUE TITLE
docker Azure Gateway throw exception

### ISSUE THREAD

**Issue by devopg** [minio/minio#9732]
hi i try run "MinIO Azure Gateway" from manual 
https://docs.min.io/docs/minio-gateway-for-azure.html

```
docker run -p 9000:9000 --name azure-s3 \
 -e "MINIO_ACCESS_KEY=azurestorageaccountname" \
 -e "MINIO_SECRET_KEY=azurestorageaccountkey" \
 -e "MINIO_AZURE_CHUNK_SIZE_MB=0.25" \
 minio/minio gateway azure
```
result: 
`ERROR Unable to initialize gateway backend: illegal base64 data at input byte 20`

**Comment by vadmeste** [comment]
@devopg kindly use the issue template next time.


> ERROR Unable to initialize gateway backend: illegal base64 data at input byte 20

You need to use your Azure blob storage credentials. The error message is just cryptic and we need to enhance it.

**Comment by devopg** [comment]
oh i think i can work with minio from C# azure.sdk (azure.storage.blobs) without cloud
sorry .....
