### ISSUE TITLE
[faq] Unable to add policy in NAS gateway mode

### ISSUE THREAD

**Issue by gregnsk** [minio/minio#9739]
Can't define a policy when running Minio in NAS gateway mode

## Expected Behavior
It should be possible to define a policy in the NAS gateway mode - similar to the example at https://docs.min.io/docs/minio-multi-user-quickstart-guide.html. Apparently, it's possible to create multiple users using etcd. We'd like an option to set different policies for different buckets in the NAS GW mode

## Current Behavior
$ ./mc  admin policy add ibox getonly getonly.json
mc: <ERROR> Unable to add new policy. This 'admin' API is not supported by server in 'mode-gateway-nas'.

## Possible Solution
Same as described in https://docs.min.io/docs/minio-multi-user-quickstart-guide.html

## Steps to Reproduce (for bugs)
$ ./mc  admin policy add ibox getonly getonly.json
mc: <ERROR> Unable to add new policy. This 'admin' API is not supported by server in 'mode-gateway-nas'.

## Context
We're trying to define different access rules for different buckets

## Your Environment

* Version used (`minio version`): RELEASE.2020-05-29T14-08-49Z
* Operating System and version (`uname -a`): Linux io-wt-11 3.10.0-957.10.1.el7.x86_64 #1 SMP Wed Mar 13 16:42:50 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> Can't define a policy when running Minio in NAS gateway mode

@gregnsk you need to use etcd

**Comment by gregnsk** [comment]
Will it allow to create several policies?

**Comment by harshavardhana** [comment]
> Will it allow to create several policies?

It will all functionality that is available in server mode for multi-users https://docs.minio.io/docs/minio-multi-user-quickstart-guide.html 

It's even mentioned in the docs in Prerequisites 

> Configure etcd (optional needed only in gateway or federation mode) - Etcd V3 Quickstart Guide
