### ISSUE TITLE
prometheus metrics  : disks count

### ISSUE THREAD

**Issue by fcomte** [minio/minio#9742]
Hello,

I have a setup of 3 servers with 2 disks each.
With the new releases, prometheus report a strange count of disks on each server
#### TYPE minio_disks_offline gauge
minio_disks_offline 4
#### TYPE minio_disks_total gauge
minio_disks_total 6

while mc admin status report
/ # mc admin info minio
●  192.168.253.51:9000
   Uptime: 44 minutes
   Version: 2020-05-28T23:29:21Z
   Network: 3/3 OK
   Drives: 2/2 OK
●  192.168.253.53:9000
   Uptime: 46 minutes
   Version: 2020-05-28T23:29:21Z
   Network: 3/3 OK
   Drives: 2/2 OK
●  192.168.253.52:9000
   Uptime: 48 minutes
   Version: 2020-05-28T23:29:21Z
   Network: 3/3 OK
   Drives: 2/2 OK

## Expected Behavior
I expect that there is no offline disk

## Current Behavior
prometheus reports some offline disk

**Comment by harshavardhana** [comment]
Yes was able to reproduce this, looks like a reporting issue @fcomte

**Comment by fcomte** [comment]
I confirmed that the new release (1 june) solve this regression.
