### ISSUE TITLE
[resolved] Prometheus metrics : new metrics about bucket usage

### ISSUE THREAD

**Issue by fcomte** [minio/minio#9743]
I observe a strange behaviour on my bucket usage : 

![image](https://user-images.githubusercontent.com/48868412/83322786-d6a33d00-a25a-11ea-8eac-56f99e1c457f.png)

All my bucket usage count lack some information regurlarly.
except for one bucket

![image](https://user-images.githubusercontent.com/48868412/83322824-05211800-a25b-11ea-9a08-605dad168d42.png)

Of course my minio job is always up 

![image](https://user-images.githubusercontent.com/48868412/83322859-37327a00-a25b-11ea-8ccd-fcb9591317dd.png)

This feature is really nice for us to monitor the minio usage of our users.

**Comment by harshavardhana** [comment]
This is not a Prometheus info problem but a problem of underlying information capture, most probably the fixes are in crawler routine

How many files do you have @fcomte ?

**Comment by fcomte** [comment]
It s a new cluster. Something like 100000 files and 40 buckets

**Comment by fcomte** [comment]
Something like 100000 and 30 buckets

**Comment by harshavardhana** [comment]
Most probably the fix is in #9718

**Comment by fcomte** [comment]
I will check that in the next release

**Comment by fcomte** [comment]
I have the same bug in the last release (1 june ) but I think #9718 is still not merged.

**Comment by harshavardhana** [comment]
> I have the same bug in the last release (1 june ) but I think #9718 is still not merged.

Its released now @fcomte the bucket usage should be consistent now. Closing for now please report back if that's not the case.
