### ISSUE TITLE
[faq] batch operations

### ISSUE THREAD

**Issue by i0x71** [minio/minio#9745]
Are there any plans to add batch operations like s3 ?

https://aws.amazon.com/blogs/aws/new-amazon-s3-batch-operations/

**Comment by harshavardhana** [comment]
Please open the GitHub issue with more details, if it's feature request use the template.

I shall close this issue as FAQ which can be asked on our slack channel.

**Comment by OliverEvans96** [comment]
For the record, here's the response I got from `Ravind Kumar (MinIO)` on Slack, asking whether Minio supports batch processing:

> S3 Batch operations is not a core S3 API, but rather a job-layer on top of Lambda. That's not to say we don't support "batch" type operations, you just have to build it out yourself using SDK or mc CLI or something similar. We have bucket notifications out to a webhook as well if you know you have a workload that requires post-processing after the initial PUT.
