### ISSUE TITLE
[resolved] Unable to initialize backend: Insufficient permissions to access path

### ISSUE THREAD

**Issue by theriverman** [minio/minio#9746]
## Expected Behavior
minIO should start normally using provided folder as its backend

## Current Behavior
minIO fails to start when provided backend is `/media/pi/Toshiba/minIO.data/` which is a mounted USB HDD. See error message in Title.

## Possible Solution
Literally no idea what's happening. minIO should have the same rights as the user executing the binary but it feels like minIO is ran by a user with less permissions

## Steps to Reproduce (for bugs)
See below in `Your Environment`

## Context
I'm trying to start minIO on a Raspberry PI 4 device under Raspbian.

## Regression
No (?)

## Your Environment
  * RPI 4 + Raspbian
  * No docker
  * Just compiled minio binary from source

```bash
pi@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

pi@raspberrypi:~ $ cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 135.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

minio@raspberrypi:~ $ cat /proc/mounts | grep sda
/dev/sda /media/pi/Toshiba ext4 rw,relatime 0 0
/dev/sda /mnt/Toshiba ext4 rw,relatime 0 0

minio@raspberrypi:~ $ namei -l /media/pi/Toshiba/minIO.data/
f: /media/pi/Toshiba/minIO.data/
drwxr-xr-x root root  /
drwxr-xr-x root root  media
drwxr-xr-x pi   pi    pi
drwxrwxr-x pi   minio Toshiba
drwxrwxr-x pi   minio minIO.data

minio@raspberrypi:~ $ id && group
uid=1001(minio) gid=1002(minio) groups=1002(minio)
bash: group: command not found

minio@raspberrypi:~ $ /usr/local/bin/minio --version
minio version DEVELOPMENT.GOGET

minio@raspberrypi:~ $ (cd /usr/local/src/minio/ && git log --format="%H" -n 1)
8befedef14d7968e0f1ecf8e788bdcdf4e1e2a7f

minio@raspberrypi:~ $ touch /media/pi/Toshiba/minIO.data/newTestFile

minio@raspberrypi:~ $ /usr/local/bin/minio server --address :9000 /media/pi/Toshiba/minIO.data
ERROR Unable to initialize backend: Insufficient permissions to access path
      > Please ensure the specified path can be accessed

minio@raspberrypi:~ $
```

Surprisingly, if I specifcy a different non-user location, it does work as expected:
```bash
minio@raspberrypi:/mnt/Toshiba $ namei -l /opt/minioDATA/
f: /opt/minioDATA/
drwxr-xr-x root  root /
drwxr-xr-x root  root opt
drwxrwxr-x minio root minioDATA
minio@raspberrypi:/mnt/Toshiba $ /usr/local/bin/minio server --address :9000 /opt/minioDATA/
# ...
# OK
```

Am I overseeing something or is this intentional behaviour?
The `minio` user can read/write/access the specified location (no permission error returned by `touch` in my example.

Thanks!

**Comment by ebozduman** [comment]
@theriverman,

I tried a similar scenario with and without a usb stick, but could not succeed to reproduce the issue you've experienced.

On the other side, one thing I've noticed is the ownership of the directory in your failing example:
```
f: /media/pi/Toshiba/minIO.data/
drwxr-xr-x root root  /
drwxr-xr-x root root  media
drwxr-xr-x pi   pi    pi
drwxrwxr-x pi   minio Toshiba
drwxrwxr-x pi   minio minIO.data
```
So, `minIO.data` directory belongs to user `pi` instead of your user `minio`. 
I understand that `touch` command is successful, but could you please just give it a try and change the ownership of the `minIO.data` directory and set it to `minio`?

Please let us know if this changes the error message/behavior or not.
If you still see the problem, please check it out to see if there is more information you can give me about the reproduction steps.

**Comment by theriverman** [comment]
Thanks for taking the time to check out my issue, @ebozduman 

I have modified the permissions as you've requested, but no luck :( 
```bash
root@raspberrypi:~# sudo chown minio:pi /media/pi/Toshiba/minIO.data/
root@raspberrypi:~# su minio
minio@raspberrypi:/root $ cd
minio@raspberrypi:~ $ namei -l /media/pi/Toshiba/minIO.data/
f: /media/pi/Toshiba/minIO.data/
drwxr-xr-x root  root  /
drwxr-xr-x root  root  media
drwxr-xr-x pi    pi    pi
drwxrwxr-x pi    minio Toshiba
drwxrwxr-x minio pi    minIO.data
minio@raspberrypi:~ $ /usr/local/bin/minio server --address :9000 /media/pi/Toshiba/minIO.data
ERROR Unable to initialize backend: Insufficient permissions to access path
      > Please ensure the specified path can be accessed
minio@raspberrypi:~ $
```

I'll do my best to give you some more hopefully useful information, but should you have any idea, I'm absolutely happy to give it a shot and hunt down this bug(?).

So far, out of curiosity, I have created a new folder with my `minio` user in `/media/pi/Toshiba` and surprisingly, I could successfully start minIO there. Once again: same parent folder, same permissions, but one can be used as the *data* folder but the other's not. See my shell log below:
```bash
minio@raspberrypi:~ $ stat /media/pi/Toshiba/minIO.data
  File: /media/pi/Toshiba/minIO.data
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 800h/2048d      Inode: 57409537    Links: 56
Access: (0755/drwxr-xr-x)  Uid: ( 1001/   minio)   Gid: ( 1002/   minio)
Access: 2020-06-15 20:42:05.520031521 +0200
Modify: 2020-06-15 21:08:39.569630081 +0200
Change: 2020-06-15 21:09:42.918927763 +0200
 Birth: -
minio@raspberrypi:~ $
minio@raspberrypi:~ $ stat /media/pi/Toshiba/minIO.data.test/
  File: /media/pi/Toshiba/minIO.data.test/
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 800h/2048d      Inode: 38797313    Links: 3
Access: (0755/drwxr-xr-x)  Uid: ( 1001/   minio)   Gid: ( 1002/   minio)
Access: 2020-06-15 21:09:58.228757212 +0200
Modify: 2020-06-15 21:05:06.171947014 +0200
Change: 2020-06-15 21:09:20.139180953 +0200
 Birth: -
minio@raspberrypi:~ $
minio@raspberrypi:~ $ /usr/local/bin/minio server --address :9000 /media/pi/Toshiba/minIO.data
ERROR Unable to initialize backend: Insufficient permissions to access path
      > Please ensure the specified path can be accessed
minio@raspberrypi:~ $ /usr/local/bin/minio server --address :9000 /media/pi/Toshiba/minIO.data.test/
Endpoint:  http://192.168.1.89:9000  ......
AccessKey: ***********
SecretKey: *************

[...]  # Removed the rest for brevity

^CExiting on signal: INTERRUPT
minio@raspberrypi:~ $
```

So I thought, there's something either in minIO's code or in the folder itself. After some investigation, I've realised there's a hidden `.minio.sys` which according to my Google searches, is very much undocumented.

So I thought, okay, let's see if this breaks my old folder. I have removed this hidden directory in my recently created test directory and tried copying my old one there:
```bash
minio@raspberrypi:/media/pi/Toshiba $ rm -rf minIO.data.test/.minio.sys/
minio@raspberrypi:/media/pi/Toshiba $ cp -rp minIO.data/.minio.sys/ minIO.data.test/.minio.sys/
cp: cannot open 'minIO.data/.minio.sys/format.json' for reading: Permission denied
```
( Sorry about the not too clever directory names. `minIO.data` and `minIO.data.test` are two different directories )

As you could see, there was a file in there with no access for my `minio` user:
```bash
minio@raspberrypi:/media/pi/Toshiba $ ls -lh minIO.data/.minio.sys/format.json
-rw------- 1 pi minio 94 May 15 22:24 minIO.data/.minio.sys/format.json
```

I have tried fixing the situation by executing a recursive ownership change:
```bash
root@raspberrypi:/home/pi# sudo chown -R minio:minio /media/pi/Toshiba/minIO.data
```

But no luck, now I'm facing a different error:
```bash
minio@raspberrypi:/media/pi/Toshiba $ source /etc/default/minio
minio@raspberrypi:/media/pi/Toshiba $ /usr/local/bin/minio server --address :9000 /media/pi/Toshiba/minIO.data
dataUpdateTracker: deprecated data version, updating.
ERROR Unable to initialize server switching into safe-mode: Unable to initialize sub-systems: Credentials missing
minio@raspberrypi:/media/pi/Toshiba $
```

Having no idea nor documentation on what this actually means ( besides #6939 ), I have decided to rename my `.minio.sys` folder and all my problems were gone:
```bash
minio@raspberrypi:/media/pi/Toshiba $ mv minIO.data/.minio.sys/ minIO.data/.minio.sys.BAK
minio@raspberrypi:/media/pi/Toshiba $
minio@raspberrypi:/media/pi/Toshiba $ /usr/local/bin/minio server --address :9000 /media/pi/Toshiba/minIO.data
Endpoint:  *************
AccessKey: ***********
SecretKey: ************
[...]
```

Wrapping it up, minIO probably acts according to design, but the error should state which file ( in my case its `.minio.sys/format.json` ) could not be accessed.
Then it seems the `.minio.sys/config/config.json` got corrupted too which is again not good.

The latter issue was probably caused by me running a minIO instance from Docker reusing that folder, so I absolutely accept this as a user error.
The former issue, in my opinion, needs some improvement in the code base because it was quite painful to debug.

If you agree on that this could use some improvement, I can investigate a little bit more and hopefully open a pull request. Otherwise, feel free to close this issue.

Thanks!

**Comment by ebozduman** [comment]
@theriverman 
This is great debug information. Thank you very much.
I'll go through the new debug information one more time and discuss the case with my colleagues to decide what improvements we can do to make the process more clear and user friendly.

**Comment by ebozduman** [comment]
@theriverman,

I see the issue.
Several options if you would like to start minio server as a different user:

1. You can use a different data directory for each user,
2. You can use a non-existing data directory and have minio create it for your user,
3. Or if you use an existing data directory that was created for another user, hit the error and follow the `"HINT"` provided in the error message (but there is this issue there, that needs to be fixed)

In your scenario, #3 is most probably happened to you;
You tried to start the minio server as user "minio" with the same data directory user "pi" used before. Then you saw the following error message:
```
ERROR Unable to initialize backend: Unable to write to the backend
      > Please ensure MinIO binary has write permissions for the backend
      HINT:
        Use 'sudo chown <new-user> <data-dir> && sudo chmod u+rxw <data-dir>' to provide sufficient permissions.
```
Then, most probably you ran the suggested command `"sudo chown <new-user> <data-dir>"` (suggested second command is irrelevant here), and when you tried, you still see the problem, but this time the error message is a little bit different:
```
ERROR Unable to initialize backend: Insufficient permissions to access path
      > Please ensure the specified path can be accessed
```
I think this is exactly where you were in your case.

Just like you've said, the internal `".minio.sys"` directory was still owned by user `"pi"`. That is simply because the proposed command only changed the ownership of the top layer data directory and it did not touch the ownership of `".minio.sys"` and all other dirs and files it contains.

So, the simple fix is to change the `"HINT"` and add `"-R"` option to it as below:
```
ERROR Unable to initialize backend: Unable to write to the backend
      > Please ensure MinIO binary has write permissions for the backend
      HINT:
        Use 'sudo chown -R <new-user> <data-dir> && sudo chmod u+rxw <data-dir>' to provide sufficient permissions.
```
Again, in your case, the suggested second command is irrelevant.

**Comment by theriverman** [comment]
Thanks for the investigation, @ebozduman !
I cannot remember seeing and/or executing the hinted text, but your described scenario is pretty similar to what I might have had. I'm happy with the proposed change, thank you!

**Comment by ebozduman** [comment]
@theriverman,
 
Of course, I was just guessing. I kind of relied on your very first failure example where your data directory's owner and group name was mixed. (I don't know why Toshiba also has the similar mixed owner and group setting though)
```
minio@raspberrypi:~ $ namei -l /media/pi/Toshiba/minIO.data/
f: /media/pi/Toshiba/minIO.data/
drwxr-xr-x root root  /
drwxr-xr-x root root  media
drwxr-xr-x pi   pi    pi
drwxrwxr-x pi   minio Toshiba
drwxrwxr-x pi   minio minIO.data
```
Somehow the `chown pi <dir-name>` command is run without changing the group name. This is actually the opposite of my assumption. My guess about everything starting with user `pi` looks wrong, maybe it all started with user `minio`.

But one thing I am sure about is the fact that the `-R` option solves the problem. Tested and verified it.
