### ISSUE TITLE
Backup of a MinIO Server

### ISSUE THREAD

**Issue by progtologist** [minio/minio#9752]
**Is your feature request related to a problem? Please describe.**
As an administrator I don't and will not always have control of what data my users will store in their buckets. This means that users can use SSE-C to encrypt their data and protect them.

However, as an administrator I still wish to be able to backup the contents of my server and be able to replicate them in another instance if for some reason I wish to offer offsite backups or access on remote sites that do not have access to internet.

**Describe the solution you'd like**
What I therefore wish to be able to do, is have some functionality that allows me to mirror a minio installation without decrypting the data. I am not interested in reading their data, I am interested in allowing my users to access their data from a different server as if they were accessing the original one.

**Describe alternatives you've considered**
I have tried using rClone but failed. I opened a [ticket](https://forum.rclone.org/t/minio-sse-c-synchronization/16826/7) in rClone but it appears that this issue is not related to rClone.
I tried copying the data folder in another backup folder, manually removing the buckets and then copying the backup back into minio, but minio lost the information that data was encrypted.
```
mc cat minio/aris/enc_file.txt
 ^?^?^?�^?^?��@��Y��3^?^?c�yN�hY�
                                 �
����^?0�Z��ozv�UQKA�^?ٸ�% 
```

**Additional context**

**Comment by klauspost** [comment]
I agree it would be nice if there was a way to copy encrypted data. Unfortunately that is not how the spec is written.

Even if we decided to not to follow S3 specifications, it cannot be retrofitted since it would break security expectations.

Directly interacting with the backend data is also not generally recommended as it is easy to make mistakes as you found out. You are probably missing the metadata files stored separately in FS mode.

So unfortunately there aren't too many options for this setup. You are also welcome to ask on slack: https://slack.min.io/

**Comment by klauspost** [comment]
> So, this problem is not just specify to backups. You cannot mirror SSE-C encrypted objects, too. So, 2-site mirroring does not work for SSE-C encrypted objects.

> Even AWS may have that problem (I need to test this). Take a look at https://docs.aws.amazon.com/AmazonS3/latest/dev/replication-walkthrough-4.html

> Let's say you have an object in bucket-A in region A and you want to replicate it to bucket-B in region B. Can you do that for SSE-C encrypted objects. If so, AWS either has to:
> a) either use an internal data transfer-API that does a blob copy.
> b) or store the SSE-C key - which they claim they don't.

> This is indeed a fundamental problem of the AWS S3 protocol.

**Comment by progtologist** [comment]
True, it appears that in terms of the S3 protocol this is not (and most likely should not) be possible. 
However, what I would like to explore is option A, some internal data transfer-API that does a blob copy that can then be imported in another minIO instance.
I must admit that I have rather limited background in minIO and S3 in general, but I would guess that wanting to take backups of users data for cold-storage in a centralized way is something useful.
It would allow administrators to be able to restore the backups in case of a catastrophic event and redeploy the servers from that data.

**Comment by klauspost** [comment]
There are no concrete plans for it currently, so I would not design my system on it becoming available.

**Comment by aead** [comment]
@progtologist This is a valid use case and it will work - for example `mc wirror` can do a replication of one S3 cluster to another one. However,  the S3 API has a "limitation" such that this does not work for SSE-C. So as for now, I would recommend to use SSE-S3 for server-side encryption or client side encryption (as better replacement for SSE-C).

For ref: https://github.com/minio/minio/blob/master/docs/kms/README.md
