### ISSUE TITLE
Excel files are damaged when uploaded using presigned_put_object

### ISSUE THREAD

**Issue by karimtemsah** [minio/minio#9755]
I am using MinIO (local bucket) with python SDK (version 5.0.5). I am using `presigned_put_object` to upload documents to my bucket and `presigned_get_object` to download them.

For large PDFs `presigned_put_object` has much better performance than normal `put_object`. However, when I have tried to upload an Excel file(.xlsx extension) and download it again, the file did not open properly.

Some code to reproduce:

    @app.route('/upload', methods=['POST'])
    def upload():
        upload_url = minio_client.presigned_put_object('test',
                                               'test.xlsx',
                                               expires=timedelta(minutes=5))

        for fil in request.files.values():
         files_list.append(
           ('file', (fil.filename, fil, fil.mimetype))
         )
         break
     response = requests.put(url=upload_url, files=files_list)
     return "200"

    @app.route('/download', methods=['POST'])
    def download():
         response_headers= {
                'response-content-type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'response-content-disposition': 'filename={test.xlsx}')
            }
        download_url = minio_client.presigned_get_object('test',
                                               'test.xlsx',
                                               expires=timedelta(minutes=5),
                                               response_headers=response_headers)

        return download_url

**Comment by vadmeste** [comment]
```
>     for fil in request.files.values():
>      files_list.append(
>        ('file', (fil.filename, fil, fil.mimetype))
>      )
>      break
```

If you are using presigned_put_object, you just need to put the content of your Excel file in the body without using request.files API.

**Comment by harshavardhana** [comment]
> ```
> >     for fil in request.files.values():
> >      files_list.append(
> >        ('file', (fil.filename, fil, fil.mimetype))
> >      )
> >      break
> ```
> 
> If you are using presigned_put_object, you just need to put the content of your Excel file in the body without using request.files API.

Yeah an incorrect client implementation here @karimtemsah not a bug.

**Comment by karimtemsah** [comment]
@vadmeste thank you for your reply.

> If you are using presigned_put_object, you just need to put the content of your Excel file in the body without using request.files API.

Can you provide an example?

**Comment by klauspost** [comment]
@karimtemsah 

You can ask on the community slack, maybe someone there can assist: https://slack.min.io/

**Comment by karimtemsah** [comment]
Hmm actually I am not sure why the issue is closed here. Probably you haven't understood the question well.

In the code snippet that I have provided, the `upload` function receives a file. That's why I used `request.files` in order to get the file content.
 

> If you are using presigned_put_object, you just need to put the content of your Excel file in the body without using request.files API.

Otherwise, how would you pass the received file to the link from `presigned_put_object` ?

**Comment by harshavardhana** [comment]
> Hmm actually I am not sure why the issue is closed here. Probably you haven't understood the question well.
> In the code snippet that I have provided, the `upload` function receives a file. That's why I used `request.files` in order to get the file content.

Uploading multiple files as single stream will corrupt the content, upload them individually this is what @vadmeste explained.

**Comment by karimtemsah** [comment]
@harshavardhana thanks for your reply! 
I also tried `requests.put(url=upload_url, files={"file": request.file['file']})` but also generates a corrupted excel file when being downloaded.
I have tried PDF files and they work well. The problem is just with the excel files.
I supposed that you have a working solution since you closed the ticket!

**Comment by edgar86cru** [comment]
@karimtemsah Did you resolve your issue?? Can you share the solution... Thank you
