### ISSUE TITLE
minio 4K small object performance is much worse than 4M object

### ISSUE THREAD

**Issue by gwnet** [minio/minio#9758]
4K small object benchmark performance is very bad.
## Expected Behavior

hope to find correct performance bottleneck together

## Current Behavior

===as you can see below, 4K read is much worse than 4M read.=====
wayne@ubuntu:~/go/benchmark/s3-benchmark$ ./s3-benchmark.ubuntu -a minioadmin -b jeff-s3-benchmark -s minioadmin -u http://192.168.147.149:9000 -t 10 -d 10 -z 4k
Wasabi benchmark program v2.0
Parameters: url=http://192.168.147.149:9000, bucket=jeff-s3-benchmark, region=us-east-1, duration=10, threads=10, loops=1, size=4k
2020/06/02 08:03:51 WARNING: createBucket jeff-s3-benchmark error, ignoring BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
	status code: 409, request id: 1614C2534AC04CCB, host id: 
Loop 1: PUT time 10.0 secs, objects = 31765, speed = 12.4MB/sec, 3175.5 operations/sec. Slowdowns = 0
Loop 1: GET time 10.0 secs, objects = 60672, speed = 23.7MB/sec, 6066.3 operations/sec. Slowdowns = 0
Loop 1: DELETE time 4.8 secs, 6585.1 deletes/sec. Slowdowns = 0
wayne@ubuntu:~/go/benchmark/s3-benchmark$ ./s3-benchmark.ubuntu -a minioadmin -b jeff-s3-benchmark -s minioadmin -u http://192.168.147.149:9000 -t 10 -d 10 -z 4M
Wasabi benchmark program v2.0
Parameters: url=http://192.168.147.149:9000, bucket=jeff-s3-benchmark, region=us-east-1, duration=10, threads=10, loops=1, size=4M
2020/06/02 08:07:41 WARNING: createBucket jeff-s3-benchmark error, ignoring BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
	status code: 409, request id: 1614C288DDBF1E64, host id: 
Loop 1: PUT time 10.3 secs, objects = 561, speed = 218.6MB/sec, 54.7 operations/sec. Slowdowns = 0
Loop 1: GET time 10.0 secs, objects = 57990, speed = 22.6GB/sec, 5798.2 operations/sec. Slowdowns = 0
Loop 1: DELETE time 0.1 secs, 4002.4 deletes/sec. Slowdowns = 0

## Possible Solution

to find bottle neck place together
## Steps to Reproduce (for bugs)

1. install ubuntu 20.04 inside vmware workstation. 
2. install minio and run minio server /mnt/data
3. test with s3-benchmark 4K and 4M
4. will see the huge gap

## Context

we want tune together with minio, need debug the root cause
## Regression
No

## Your Environment

* Version used (`minio version`): latest binary
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: vmware workstation guest OS
* Operating System and version (`uname -a`): wayne@ubuntu:~/go/benchmark/s3-benchmark$ uname -a
Linux ubuntu 5.3.0-53-generic #47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

* Link to your project:

**Comment by gwnet** [comment]
@harshavardhana can minio expert work with me to find the bottleneck together? we want to use the intel open-cas cache to accelerate small IO

**Comment by harshavardhana** [comment]
> @harshavardhana can minio expert work with me to find the bottleneck together? we want to use the intel open-cas cache to accelerate small IO

For commercial engagements please reach out to us at https://minio.io/pricing or https://subnet.min.io/subscribe

**Comment by gwnet** [comment]
intel@intel:~/wayne/s3-benchmark$ sudo ./s3-benchmark -a minioadmin -b jeff-s3-benchmark -s minioadmin -u http://127.0.0.1:9000 -t 1 -d 20 -z 4k
[sudo] password for intel: 
S3 benchmark program v3.0
Parameters: url=http://127.0.0.1:9000, bucket=jeff-s3-benchmark, duration=20, threads=1, loops=1, size=4k
Wed, 03 Jun 2020 09:54:18 GMT Loop 1: PUT time 20.0 secs, objects = 15127, speed = 3MB/sec, 756.3 operations/sec.
Wed, 03 Jun 2020 09:54:38 GMT Loop 1: GET time 20.0 secs, objects = 15749, speed = 3.1MB/sec, 787.4 operations/sec.
Wed, 03 Jun 2020 09:54:55 GMT Loop 1: DELETE time 17.4 secs, 867.2 operations/sec.
Benchmark completed.
intel@intel:~/wayne/s3-benchmark$ sudo ./s3-benchmark -a minioadmin -b jeff-s3-benchmark -s minioadmin -u http://127.0.0.1:9000 -t 2 -d 20 -z 4k
S3 benchmark program v3.0
Parameters: url=http://127.0.0.1:9000, bucket=jeff-s3-benchmark, duration=20, threads=2, loops=1, size=4k
Wed, 03 Jun 2020 09:55:28 GMT Loop 1: PUT time 20.0 secs, objects = 32590, speed = 6.4MB/sec, 1629.4 operations/sec.
Wed, 03 Jun 2020 09:55:48 GMT Loop 1: GET time 20.0 secs, objects = 32447, speed = 6.3MB/sec, 1622.3 operations/sec.
Wed, 03 Jun 2020 09:56:06 GMT Loop 1: DELETE time 18.6 secs, 1756.3 operations/sec.
Benchmark completed.
intel@intel:~/wayne/s3-benchmark$ sudo ./s3-benchmark -a minioadmin -b jeff-s3-benchmark -s minioadmin -u http://127.0.0.1:9000 -t 4 -d 20 -z 4k
S3 benchmark program v3.0
Parameters: url=http://127.0.0.1:9000, bucket=jeff-s3-benchmark, duration=20, threads=4, loops=1, size=4k
Wed, 03 Jun 2020 09:59:17 GMT Loop 1: PUT time 20.0 secs, objects = 66480, speed = 13MB/sec, 3323.8 operations/sec.
Wed, 03 Jun 2020 09:59:37 GMT Loop 1: GET time 20.0 secs, objects = 61524, speed = 12MB/sec, 3076.2 operations/sec.
Wed, 03 Jun 2020 09:59:56 GMT Loop 1: DELETE time 18.8 secs, 3537.4 operations/sec.
Benchmark completed.
intel@intel:~/wayne/s3-benchmark$ sudo ./s3-benchmark -a minioadmin -b jeff-s3-benchmark -s minioadmin -u http://127.0.0.1:9000 -t 8 -d 20 -z 4k
S3 benchmark program v3.0
Parameters: url=http://127.0.0.1:9000, bucket=jeff-s3-benchmark, duration=20, threads=8, loops=1, size=4k
Wed, 03 Jun 2020 10:00:45 GMT Loop 1: PUT time 20.0 secs, objects = 114722, speed = 22.4MB/sec, 5735.8 operations/sec.
Wed, 03 Jun 2020 10:01:05 GMT Loop 1: GET time 20.0 secs, objects = 98227, speed = 19.2MB/sec, 4910.8 operations/sec.
Wed, 03 Jun 2020 10:01:23 GMT Loop 1: DELETE time 17.9 secs, 6419.3 operations/sec.
Benchmark completed.
intel@intel:~/wayne/s3-benchmark$ sudo ./s3-benchmark -a minioadmin -b jeff-s3-benchmark -s minioadmin -u http://127.0.0.1:9000 -t 16 -d 20 -z 4k
S3 benchmark program v3.0
Parameters: url=http://127.0.0.1:9000, bucket=jeff-s3-benchmark, duration=20, threads=16, loops=1, size=4k
Wed, 03 Jun 2020 10:01:59 GMT Loop 1: PUT time 20.0 secs, objects = 150906, speed = 29.5MB/sec, 7544.3 operations/sec.
Wed, 03 Jun 2020 10:02:19 GMT Loop 1: GET time 20.0 secs, objects = 125332, speed = 24.5MB/sec, 6265.5 operations/sec.
Wed, 03 Jun 2020 10:02:38 GMT Loop 1: DELETE time 18.8 secs, 8040.4 operations/sec.
Benchmark completed.
intel@intel:~/wayne/s3-benchmark$ sudo ./s3-benchmark -a minioadmin -b jeff-s3-benchmark -s minioadmin -u http://127.0.0.1:9000 -t 32 -d 20 -z 4k
S3 benchmark program v3.0
Parameters: url=http://127.0.0.1:9000, bucket=jeff-s3-benchmark, duration=20, threads=32, loops=1, size=4k
Wed, 03 Jun 2020 10:06:35 GMT Loop 1: PUT time 20.0 secs, objects = 132037, speed = 25.8MB/sec, 6600.9 operations/sec.
Wed, 03 Jun 2020 10:06:55 GMT Loop 1: GET time 20.0 secs, objects = 101079, speed = 19.7MB/sec, 5052.9 operations/sec.
Wed, 03 Jun 2020 10:07:15 GMT Loop 1: DELETE time 20.4 secs, 6476.8 operations/sec.
Benchmark completed.
intel@intel:~/wayne/s3-benchmark$ sudo ./s3-benchmark -a minioadmin -b jeff-s3-benchmark -s minioadmin -u http://127.0.0.1:9000 -t 24 -d 20 -z 4k
S3 benchmark program v3.0
Parameters: url=http://127.0.0.1:9000, bucket=jeff-s3-benchmark, duration=20, threads=24, loops=1, size=4k
Wed, 03 Jun 2020 10:08:09 GMT Loop 1: PUT time 20.0 secs, objects = 158201, speed = 30.9MB/sec, 7908.9 operations/sec.
Wed, 03 Jun 2020 10:08:29 GMT Loop 1: GET time 20.0 secs, objects = 119104, speed = 23.3MB/sec, 5954.0 operations/sec.
Wed, 03 Jun 2020 10:08:49 GMT Loop 1: DELETE time 19.8 secs, 7999.9 operations/sec.
Benchmark completed.
intel@intel:~/wayne/s3-benchmark$ sudo ./s3-benchmark -a minioadmin -b jeff-s3-benchmark -s minioadmin -u http://127.0.0.1:9000 -t 28 -d 20 -z 4k
S3 benchmark program v3.0
Parameters: url=http://127.0.0.1:9000, bucket=jeff-s3-benchmark, duration=20, threads=28, loops=1, size=4k
Wed, 03 Jun 2020 10:09:23 GMT Loop 1: PUT time 20.0 secs, objects = 158297, speed = 30.9MB/sec, 7914.0 operations/sec.
Wed, 03 Jun 2020 10:09:43 GMT Loop 1: GET time 20.0 secs, objects = 108094, speed = 21.1MB/sec, 5404.0 operations/sec.
Wed, 03 Jun 2020 10:10:04 GMT Loop 1: DELETE time 21.6 secs, 7338.2 operations/sec.
Benchmark completed.
intel@intel:~/wayne/s3-benchmark$

**Comment by gwnet** [comment]
from the perf result, it looks like it is minio software bottleneck. it did not use high speed optane SSD fully for small IO.

    66.27%     0.00%  minio    minio              [.] 0x000000000045f9e1
            |
            ---0x45f9e1
               |          
               |--55.86%--0x7087a5
               |          |          
               |           --55.86%--0x70cf04
               |                     0x7099b4
               |                     0x80b9ab
               |                     0x15b7dc3
               |                     |          
               |                      --55.81%--0x145497c
               |                                0x15b81c3
               |                                |          
               |                                 --55.68%--0x1450313
               |                                           0x15b8903
               |                                           |          
               |                                            --55.65%--0x1454cd3
               |                                                      |          
               |                                                       --55.63%--0x15ade93
               |                                                                 |          
               |                                                                  --55.60%--0x1389911
               |                                                                            0x15b8493
               |                                                                            |          
               |                                                                             --55.57%--0x1452405
               |                                                                                       |          
               |                                                                                        --55.55%--0x7099b4
               |                                                                                                  |          
               |                                                                                                   --55.41%--0x11efcaf
               |                                                                                                             0x15b8403
               |                                                                                                             |          
               |                                                                                                              --55.09%--0x14519c5
               |                                                                                                                        0x15b82e3
               |                                                                                                                        |          
               |                                                                                                                         --55.07%--0x1450c82
               |                                                                                                                                   |          
               |                                                                                                                                    --55.07%--0x15b8373
               |                                                                                                                                              |          
               |                                                                                                                                               --55.05%--0x145107c
               |                                                                                                                                                         0x15b8253
               |                                                                                                                                                         |          
               |                                                                                                                                                          --55.02%--0x14509b8
               |                                                                                                                                                                    |          
               |                                                                                                                                                                     --55.00%--0x15b1833
               |                                                                                                                                                                               |          
               |                                                                                                                                                                                --54.98%--0x13e8bf1
               |                                                                                                                                                                                          0x15b8133
               |                                                                                                                                                                                          |          
               |                                                                                                                                                                                           --54.86%--0x144fec3
               |                                                                                                                                                                                                     |          
               |                                                                                                                                                                                                      --54.86%--0x15b809c
               |                                                                                                                                                                                                                |          
               |                                                                                                                                                                                                                 --54.82%--0x144fc2f
               |                                                                                                                                                                                                                           0x15b8523
               |                                                                                                                                                                                                                           |          
               |                                                                                                                                                                                                                            --54.53%--0x1452844
               |                                                                                                                                                                                                                                      |          
               |                                                                                                                                                                                                                                       --54.51%--0x15b85b3
               |                                                                                                                                                                                                                                                 |          
               |                                                                                                                                                                                                                                                  --54.30%--0x1453001
               |                                                                                                                                                                                                                                                            |          
               |                                                                                                                                                                                                                                                             --54.28%--0x15b874c
               |                                                                                                                                                                                                                                                                       0x145322c
               |                                                                                                                                                                                                                                                                       |          
               |                                                                                                                                                                                                                                                                        --54.27%--0x15b8873
               |                                                                                                                                                                                                                                                                                  |          
               |                                                                                                                                                                                                                                                                                   --54.14%--0x1454896
               |                                                                                                                                                                                                                                                                                             |          
               |                                                                                                                                                                                                                                                                                              --54.11%--0x15b87e3
               |                                                                                                                                                                                                                                                                                                        |          
               |                                                                                                                                                                                                                                                                                                         --53.53%--0x1454602
               |                                                                                                                                                                                                                                                                                                                   |          
               |                                                                                                                                                                                                                                                                                                                   |--41.79%--0x760842
               |                                                                                                                                                                                                                                                                                                                   |          |          
               |                                                                                                                                                                                                                                                                                                                   |           --41.76%--0x7099b4
               |                                                                                                                                                                                                                                                                                                                   |                     |          
               |                                                                                                                                                                                                                                                                                                                   |                      --41.74%--0x159a540
               |                                                                                                                                                                                                                                                                                                                   |                                |          
               |                                                                                                                                                                                                                                                                                                                   |                                 --41.18%--0x158d681
               |                                                                                                                                                                                                                                                                                                                   |                                           |          
               |                                                                                                                                                                                                                                                                                                                   |                                           |--39.74%--0x158d548
               |          |                                                                                                                                                                                                                                                                                                        |                                           |          |          
               |                                                                                                                                                                                                                                                                                                                   |                                           |           --39.51%--0x15c3973
               |                     |                                                                                                                                                                                                                                                                                             |                                           |                     |          
               |                     |                                                                                                                                                                                                                                                                                             |                                           |                     |--15.17%--0x14a33bf
               |                     |          |                                                                                                                                                                                                                                                                                  |                                           |                     |          |          
               |                     |                                                                                                                                                                                                                                                                                             |                                           |                     |           --15.15%--0x15c61e0
               |                     |                     |                                                                                                                                                                                                                                                                       |                                           |                     |                     |          
               |                     |                     |                                                                                                                                                                                                                                                                       |                                           |                     |                     |--8.36%--0x143fdd1
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |          
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |--3.71%--0x1443230
               |                     |                     |          |          |                                                                                                                                                                                                                                                 |                                           |                     |                     |          |          |          
               |                     |                     |          |          |                                                                                                                                                                                                                                                 |                                           |                     |                     |          |          |--1.93%--0x1430ebf
               |                     |                     |          |          |          |                                                                                                                                                                                                                                      |                                           |                     |                     |          |          |          |          
               |                     |                     |          |          |                                                                                                                                                                                                                                                 |                                           |                     |                     |          |          |           --1.60%--0x7c4be2
               |                     |                     |          |          |                     |                                                                                                                                                                                                                           |                                           |                     |                     |          |          |                     |          
               |                     |                     |          |          |                                                                                                                                                                                                                                                 |                                           |                     |                     |          |          |                      --1.57%--0x7ce9f2
               |                     |                     |          |          |                                |                                                                                                                                                                                                                |                                           |                     |                     |          |          |                                |          
               |                     |                     |          |          |                                                                                                                                                                                                                                                 |                                           |                     |                     |          |          |                                 --0.95%--0x7e57f8
               |                     |                     |          |          |                                                                                                                                                                                                                                                 |                                           |                     |                     |          |          |                                           0x7e7376
               |                     |                     |          |          |                                           |                                                                                                                                                                                                     |                                           |                     |                     |          |          |                                           |          
               |                     |                     |          |          |                                                                                                                                                                                                                                                 |                                           |                     |                     |          |          |                                            --0.93%--0x7dec88
               |                     |                     |          |          |                                                      |                                                                                                                                                                                          |                                           |                     |                     |          |          |                                                      |          
               |                     |                     |          |          |                                                                                                                                                                                                                                                 |                                           |                     |                     |          |          |                                                       --0.56%--0x7dad83
               |                     |                     |          |          |                                                                                                                                                                                                                                                 |                                           |                     |                     |          |          |          
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |           --1.60%--0x1430e4c
               |                     |                     |          |                     |                                                                                                                                                                                                                                      |                                           |                     |                     |          |                     |          
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |                      --1.28%--0x5a7a20
               |                     |                     |          |                                |                                                                                                                                                                                                                           |                                           |                     |                     |          |                                |          
               |                     |                     |          |                                |                                                                                                                                                                                                                           |                                           |                     |                     |          |                                |--0.69%--0x4acd3b
               |                     |                     |          |                                |          |                                                                                                                                                                                                                |                                           |                     |                     |          |                                |          |          
               |                     |                     |          |                                |                                                                                                                                                                                                                           |                                           |                     |                     |          |                                |           --0.67%--0x4ac88b
               |                     |                     |          |                                |                     |                                                                                                                                                                                                     |                                           |                     |                     |          |                                |                     |          
               |                     |                     |          |                                |                                                                                                                                                                                                                           |                                           |                     |                     |          |                                |                      --0.64%--0x4acf47
               |                     |                     |          |                                |                                                                                                                                                                                                                           |                                           |                     |                     |          |                                |                                0x4462bc
               |                     |                     |          |                                |                                                                                                                                                                                                                           |                                           |                     |                     |          |                                |          
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |                                 --0.56%--0x4acda4
               |                     |                     |          |                                           |                                                                                                                                                                                                                |                                           |                     |                     |          |                                           |          
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |                                            --0.56%--0x4710dc
               |                     |                     |          |                                                      |                                                                                                                                                                                                     |                                           |                     |                     |          |                                                      |          
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |                                                       --0.54%--0x49d685
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |                                                                 0x4959b1
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |          
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |--2.26%--0x1442dac
               |                     |                     |          |          |                                                                                                                                                                                                                                                 |                                           |                     |                     |          |          |          
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |           --1.79%--0x143aad1
               |                     |                     |          |                     |                                                                                                                                                                                                                                      |                                           |                     |                     |          |                     |          
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |                      --1.74%--0x11e96f3
               |                     |                     |          |                                |                                                                                                                                                                                                                           |                                           |                     |                     |          |                                |          
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |                                 --1.13%--0x11e9828
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |                                           0x49e703
               |                     |                     |          |                                           |                                                                                                                                                                                                                |                                           |                     |                     |          |                                           |          
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |                                            --0.64%--0x4a0627
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |          
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |--0.76%--0x1443270
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |          
               |                     |                     |                                                                                                                                                                                                                                                                       |                                           |                     |                     |           --0.74%--0x1442fc2
               |                     |                     |                     |                                                                                                                                                                                                                                                 |                                           |                     |                     |                     |          
               |                     |                     |                                                                                                                                                                                                                                                                       |                                           |                     |                     |                      --0.72%--0x143080e
               |                     |                     |                                |                                                                                                                                                                                                                                      |                                           |                     |                     |                                |          
               |                     |                     |                                                                                                                                                                                                                                                                       |                                           |                     |                     |                                 --0.62%--0x149ac8b
               |                     |                     |                                                                                                                                                                                                                                                                       |                                           |                     |                     |          
               |                     |                     |                                                                                                                                                                                                                                                                       |                                           |                     |                     |--1.91%--0x1440d47
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |          
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |--0.90%--0x148354c
               |                     |                     |          |          |                                                                                                                                                                                                                                                 |                                           |                     |                     |          |          |          
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |           --0.51%--0x1483980
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |          
               |                     |                     |                                                                                                                                                                                                                                                                       |                                           |                     |                     |           --0.88%--0x1483685
               |                     |                     |                     |                                                                                                                                                                                                                                                 |                                           |                     |                     |                     |          
               |                     |                     |                                                                                                                                                                                                                                                                       |                                           |                     |                     |                      --0.76%--0x1482186
               |                     |                     |                                                                                                                                                                                                                                                                       |                                           |                     |                     |          
               |                     |                     |                                                                                                                                                                                                                                                                       |                                           |                     |                     |--1.45%--0x1440655
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |          
               |                     |                     |                                                                                                                                                                                                                                                                       |                                           |                     |                     |           --0.99%--0x143aad1
               |                     |                     |                     |                                                                                                                                                                                                                                                 |                                           |                     |                     |                     |          
               |                     |                     |                                                                                                                                                                                                                                                                       |                                           |                     |                     |                      --0.97%--0x11e96f3
               |                     |                     |                                |                                                                                                                                                                                                                                      |                                           |                     |                     |                                |          
               |                     |                     |                                                                                                                                                                                                                                                                       |                                           |                     |                     |                                 --0.53%--0x11e9828
               |                     |                     |                                                                                                                                                                                                                                                                       |                                           |                     |                     |                                           0x49e703
               |                     |                     |                                                                                                                                                                                                                                                                       |                                           |                     |                     |          
               |                     |                     |                                                                                                                                                                                                                                                                       |                                           |                     |                     |--0.77%--0x1440097
               |                     |                     |          |                                                                                                                                                                                                                                                            |                                           |                     |                     |          |          
               |                     |                     |                                                                                                                                                                                                                                                                       |                                           |                     |                     |           --0.59%--0x142e8f2
               |                     |                     |                                                                                                                                                                                                                                                                       |                                           |                     |                     |                     0x49e703
               |                     |                     |                                                                                                                                                                                                                                                                       |                                           |                     |                     |          
               |                     |                                                                                                                                                                                                                                                                                             |                                           |                     |                      --0.68%--0x143fd01
               |                     |                                |                                                                                                                                                                                                                                                            |                                           |                     |                                |          
               |                     |                                                                                                                                                                                                                                                                                             |                                           |                     |                                 --0.57%--0x143d3d6
               |                     |                                           |                                                                                                                                                                                                                                                 |                                           |                     |                                           |          
               |                     |                                                                                                                                                                                                                                                                                             |                                           |                     |                                            --0.55%--0x142def3
               |                     |                                                      |                                                                                                                                                                                                                                      |                                           |                     |                                                      |          
               |                     |                                                                                                                                                                                                                                                                                             |                                           |                     |                                                       --0.53%--0x142dd69
               |                     |                                                                 |                                                                                                                                                                                                                           |                                           |                     |                                                                 |          
               |                     |                                                                                                                                                                                                                                                                                             |                                           |                     |                                                                  --0.51%--0x4a3a9d
               |                     |                                                                                                                                                                                                                                                                                             |                                           |                     |

**Comment by klauspost** [comment]
@gwnet You are welcome to ask on the community forum or look into the options listed by harsha above. Unless you have a specific issue this is not the place for it.

You can join slack here: https://slack.min.io/ - the options for direct support is listed above.
