### ISSUE TITLE
Minio closes the connection instead of returning a valid error

### ISSUE THREAD

**Issue by AlexNk** [minio/minio#9759]
When using wrong (non-existent or finalized) multipart ID, with relatively large part sizes (8 MiB or more) minio closes the connection. 

## Expected Behavior
NoSuchUpload must be returned.

## Current Behavior
The connection is closed with no response. 

## Steps to Reproduce (for bugs)
1. Create multipart upload
2. Upload Part 1 and Part 2 - both of 16 MiB or larger
3. Finalize multipart upload
4. Try to upload Part 3 using the same multipart ID

## Environment
This is reproducible with both boto3 and our internal S3 API client.
Minio is running in standalone mode with no special configuration.
Tested on the latest release (2020-06-01) and manually built version from "master".
Boto3 version - 1.13.6

## Notes
* With smaller part size this does not happen. 
* Debugging shows that the error is being written to the ResponseWriter, but it stucks on Flush(). The callstack looks the same as here: #9105

**Comment by harshavardhana** [comment]
@AlexNk please share your test program

**Comment by AlexNk** [comment]
> @AlexNk please share your test program

```
import boto3
import botocore

bucket_name = "test3"
obj_name = "mp_file"

client = boto3.client("s3", aws_access_key_id="minio", aws_secret_access_key="minio", endpoint_url="https://minio:9199", verify=False)
client.create_bucket(Bucket=bucket_name)

body_1 = (b'1' * 16*1024*1024)
body_2 = (b'2' * 16*1024*1024)

mp_ret = client.create_multipart_upload(Bucket=bucket_name, Key=obj_name)
p1 = client.upload_part(Bucket=bucket_name, Key=obj_name, PartNumber=1, UploadId=mp_ret["UploadId"], Body=body_1)
p2 = client.upload_part(Bucket=bucket_name, Key=obj_name, PartNumber=2, UploadId=mp_ret["UploadId"], Body=body_2)
parts = {
    "Parts": [
        {
            "PartNumber": 1,
            "ETag": p1["ETag"]
        },
        {
            "PartNumber": 2,
            "ETag": p2["ETag"]
        }
    ]
}

body_3 = (b'3' * 16*1024*1024)
client.complete_multipart_upload(Bucket=bucket_name, Key=obj_name, UploadId=mp_ret["UploadId"], MultipartUpload=parts)
client.upload_part(Bucket=bucket_name, Key="ab", PartNumber=3, UploadId=mp_ret["UploadId"], Body=body_3)
print("This never happens")
```

**Comment by vadmeste** [comment]
I was able to reproduce the issue.

Surprisingly this change would fix the issue:

```diff
diff --git a/cmd/http/server.go b/cmd/http/server.go
index 092d279f..419ad273 100644
--- a/cmd/http/server.go
+++ b/cmd/http/server.go
@@ -19,6 +19,7 @@ package http
 import (
        "crypto/tls"
        "errors"
+       "io"
        "io/ioutil"
        "net/http"
        "runtime/pprof"
@@ -86,6 +87,7 @@ func (srv *Server) Start() (err error) {

        // Wrap given handler to do additional
        // * return 503 (service unavailable) if the server in shutdown.
+       // * always drain the request body
        wrappedHandler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
                // If server is in shutdown.
                if atomic.LoadUint32(&srv.inShutdown) != 0 {
@@ -102,6 +104,11 @@ func (srv *Server) Start() (err error) {

                // Handle request using passed handler.
                handler.ServeHTTP(w, r)
+
+               // Drain the request body
+               if r.Body != nil {
+                       io.Copy(ioutil.Discard, r.Body)
+               }
        })

        srv.listenerMutex.Lock()
```

**Comment by harshavardhana** [comment]
> ```diff
> diff --git a/cmd/http/server.go b/cmd/http/server.go
> index 092d279f..419ad273 100644
> --- a/cmd/http/server.go
> +++ b/cmd/http/server.go
> @@ -19,6 +19,7 @@ package http
>  import (
>         "crypto/tls"
>         "errors"
> +       "io"
>         "io/ioutil"
>         "net/http"
>         "runtime/pprof"
> @@ -86,6 +87,7 @@ func (srv *Server) Start() (err error) {
> 
>         // Wrap given handler to do additional
>         // * return 503 (service unavailable) if the server in shutdown.
> +       // * always drain the request body
>         wrappedHandler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
>                 // If server is in shutdown.
>                 if atomic.LoadUint32(&srv.inShutdown) != 0 {
> @@ -102,6 +104,11 @@ func (srv *Server) Start() (err error) {
> 
>                 // Handle request using passed handler.
>                 handler.ServeHTTP(w, r)
> +
> +               // Drain the request body
> +               if r.Body != nil {
> +                       io.Copy(ioutil.Discard, r.Body)
> +               }
>         })
> 
>         srv.listenerMutex.Lock()
> ```

Looks like some interaction issue between net/http and boto3 HTTP client @vadmeste r.Body shouldn't be drained like a client style it is meant to be consumed automatically by ServeHTTP. 

We should report this upstream and get their feedback. It almost certainly looks like a client bug to me, we can have the workaround though unless without any side-effects. 

Also, limit the io.Copy() drain to let's say 4k bytes beyond this we shouldn't be reading and reject the connection.

**Comment by AlexNk** [comment]
> Looks like some interaction issue between net/http and boto3 HTTP client @vadmeste r.Body shouldn't be drained like a client style it is meant to be consumed automatically by ServeHTTP.
> 
> We should report this upstream and get their feedback. It almost certainly looks like a client bug to me, we can have the workaround though unless without any side-effects.
> 
> Also, limit the io.Copy() drain to let's say 4k bytes beyond this we shouldn't be reading and reject the connection.

As I mentioned in the issue, this also reproduces with our internal S3 API client library.
Also, for some reason, this only happens with large part sizes. Maybe the problem is related to some unfinished receive? This would explain why draining the request helps.


That's what boto3 logs:
```
2020-06-02 14:42:23,905 botocore.hooks [DEBUG] Event needs-retry.s3.UploadPart: calling handler <botocore.retryhandler.RetryHandler object at 0x7f5d5d681f40>
2020-06-02 14:42:23,905 botocore.retryhandler [DEBUG] retry needed, retryable exception caught: Connection was closed before we received a valid response from endpoint URL: "https://minio:9199/main---test-double-finalize-test-ymabq3poovba3as1/ab?partNumber=3&uploadId=dda41a63-4365-40e4-af1a-3487ab6f6f45".
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/lsk/.local/lib/python3.8/site-packages/botocore/awsrequest.py", line 91, in _send_request
    rval = super(AWSConnection, self)._send_request(
  File "/usr/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/lsk/.local/lib/python3.8/site-packages/botocore/awsrequest.py", line 143, in _send_output
    self.send(message_body)
  File "/home/lsk/.local/lib/python3.8/site-packages/botocore/awsrequest.py", line 203, in send
    return super(AWSConnection, self).send(str)
  File "/usr/lib/python3.8/http/client.py", line 964, in send
    self.sock.sendall(datablock)
  File "/usr/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by harshavardhana** [comment]
> 2020-06-02 14:42:23,905 botocore.hooks [DEBUG] Event needs-retry.s3.UploadPart: calling handler <botocore.retryhandler.RetryHandler object at 0x7f5d5d681f40>
> 2020-06-02 14:42:23,905 botocore.retryhandler [DEBUG] retry needed, retryable exception caught: Connection was closed before we received a valid response from endpoint URL: "https://minio:9199/main---test-double-finalize-test-ymabq3poovba3as1/ab?partNumber=3&uploadId=dda41a63-4365-40e4-af1a-3487ab6f6f45".
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
>     httplib_response = self._make_request(
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/usr/lib/python3.8/http/client.py", line 1240, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/home/lsk/.local/lib/python3.8/site-packages/botocore/awsrequest.py", line 91, in _send_request
>     rval = super(AWSConnection, self)._send_request(
>   File "/usr/lib/python3.8/http/client.py", line 1286, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.8/http/client.py", line 1235, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/home/lsk/.local/lib/python3.8/site-packages/botocore/awsrequest.py", line 143, in _send_output
>     self.send(message_body)

what this simply means is that client is hung @AlexNk, the server simply terminates the client since its idle for too long.

> As I mentioned in the issue, this also reproduces with our internal S3 API client library.
> Also, for some reason, this only happens with large part sizes. Maybe the problem is related to some unfinished receive? This would explain why draining the request helps.

Draining request is a hack it simply shows that the server is simply arbitrarily reading the request, it is potentially possible that client for some reason wants the server to consume all of the r.Body() which is not necessary. Without reading the body server can respond back i.e the HTTP RFC standard.

So either client is simply buggy here as we have seen in the past 

https://github.com/boto/boto/issues/840

https://github.com/boto/boto3/issues/1341

https://github.com/boto/botocore/pull/1328

https://github.com/boto/botocore/pull/1990

**Comment by vadmeste** [comment]
It looks like we don't have to take any action for this issue @harshavardhana, could you confirm ?

**Comment by harshavardhana** [comment]
Moving this to priority high for investigation if this is a client issue.
