### ISSUE TITLE
Permissive policy

### ISSUE THREAD

**Issue by kaihendry** [minio/minio#976]
How do I configure a permissive listing policy of my object store?

```
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Resource>/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
```

Similar to `aws s3api put-bucket-acl --bucket example.com --acl public-read`.

I want to be able to address objects on my server as URLs. Bonus: SSL.

**Comment by harshavardhana** [comment]
> Similar to aws s3api put-bucket-acl --bucket example.com --acl public-read.

This is something odd, perhaps a compatibility issue , have you configured 'minio server' with the credentials properly? and also what is your region? 

Since this clearly looks like a 'signature v4' problem.  Have you configured your region to 'milkyway'?

**Comment by harshavardhana** [comment]
To configure SSL you can use your certs this way. 

```
 --cert          Provide your domain certificate.
 --key           Provide your domain private key.
```

**Comment by harshavardhana** [comment]
> Similar to aws s3api put-bucket-acl --bucket example.com --acl public-read.

Also let me find a way to provide a new region through 'aws cli', we haven't documented it yet.

**Comment by harshavardhana** [comment]
> Also let me find a way to provide a new region through 'aws cli', we haven't documented it yet.

Looks like its not possible to provide a new region or a custom region through 'aws cli'  - you might have to use s3cmd or 'mc' to add permissive ACL's. 

Were you able to use 'mc' to do that?

**Comment by harshavardhana** [comment]
Closing this, please re-open if you have more issues regarding permissive policy.
