### ISSUE TITLE
Error in distributed mode

### ISSUE THREAD

**Issue by sPhinX-LHJ** [minio/minio#9761]
There is a 404 error appeared every 5 minutes when I run a distributed minio server, the command is very simple:
`minio server http://127.0.0.1/TestData{1...4}`
Error detail(run on the simple chinese language):
`API: SYSTEM()
Time: 10:06:47 CST 06/03/2020
DeploymentID: f5ce7843-6e8a-47d7-a2b3-cd421e887a29
Error: <!DOCT YPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.o
rg/TR/xhtml1/DTD/xhtml1-strict.dtd">
<ht ml xmlns="http://www.w3.org/1999/xhtml">
<hea d>
<tit le>IIS 8.5 详细错误 - 404.0 - Not Found</title>
<sty le type="text/css">

</style>

</head>
<body>
<div id="content">
<div class="content-container">
  <h3>HTTP 错误 404.0 - Not Found</h3>
  <h4>您要找的资源已被删除、已更名或暂时不可用。</h4>
</div>
<div class="content-container">
 <fieldset><h4>最可能的原因:</h4>
  <ul>  <li>指定的目录或文件在 Web 服务器上不存在。</li>        <li>URL 拼写错误
。</li>         <li>某个自定义筛选器或模块(如 URLScan)限制了对该文件的访问。</li
> </ul>
 </fieldset>
</div>
<div class="content-container">
 <fieldset><h4>可尝试的操作:</h4>
  <ul>  <li>在 Web 服务器上创建内容。</li>      <li>检查浏览器 URL。</li>
<li>创建跟踪规则以跟踪此 HTTP 状态代码的失败请求，并查看是哪个模块在调用 SetStat
us。有关为失败的请求创建跟踪规则的详细信息，请单击<a href="http://go.microsoft.c
om/fwlink/?LinkID=66439">此处</a>。</li> </ul>
 </fieldset>
</div>

<div class="content-container">
 <fieldset><h4>详细错误信息:</h4>
  <div id="details-left">
   <table border="0" cellpadding="0" cellspacing="0">
    <tr class="alt"><th>模块</th><td>&nbsp;&nbsp;&nbsp;IIS Web Core</td></tr>
    <tr><th>通知</th><td>&nbsp;&nbsp;&nbsp;MapRequestHandler</td></tr>
    <tr class="alt"><th>处理程序</th><td>&nbsp;&nbsp;&nbsp;StaticFile</td></tr>

    <tr><th>错误代码</th><td>&nbsp;&nbsp;&nbsp;0x80070002</td></tr>

   </table>
  </div>
  <d iv id="details-right">
   <ta ble border="0" cellpadding="0" cellspacing="0">
    <tr class="alt"><th>请求的 URL</th><td>&nbsp;&nbsp;&nbsp;http://127.0.0.1:80
/minio/peer/v9/cyclebloom</td></tr>
    <t r><t h>物理路径</th><td>&nbsp;&nbsp;&nbsp;D
       2: github.com\minio\minio@\cmd\notification.go:473:cmd.(*NotificationSys)
.updateBloomFilter.func1()
       1: github.com\minio\minio@\pkg\sync\errgroup\errgroup.go:55:errgroup.(*Gr
oup).Go.func1()
`

## Expected Behavior
no error

## Current Behavior
error appeared every 5 minutes

## Possible Solution
no

## Steps to Reproduce (for bugs)
run command, wait 5 minutes

## Your Environment
Win 10 & Win Server 2012 Standard, simple chinese language

**Comment by harshavardhana** [comment]
> There is a 404 error appeared every 5 minutes when I run a distributed minio server, the command is very simple:
> `minio server http://127.0.0.1/TestData{1...4}`
> Error detail(run on the simple chinese language):
> `API: SYSTEM()
> Time: 10:06:47 CST 06/03/2020
> DeploymentID: f5ce7843-6e8a-47d7-a2b3-cd421e887a29
> Error:
> 
> 
> IIS 8.5 详细错误 - 404.0 - Not Found</title>
> </style>
> ### HTTP 错误 404.0 - Not Found
> #### 您要找的资源已被删除、已更名或暂时不可用。
> #### 最可能的原因:
> * 指定的目录或文件在 Web 服务器上不存在。
> * URL 拼写错误
>   。
> * 某个自定义筛选器或模块(如 URLScan)限制了对该文件的访问。
> 
> #### 可尝试的操作:
> * 在 Web 服务器上创建内容。
> * 检查浏览器 URL。
> * 创建跟踪规则以跟踪此 HTTP 状态代码的失败请求，并查看是哪个模块在调用 SetStat
>   us。有关为失败的请求创建跟踪规则的详细信息，请单击[此处](http://go.microsoft.c
>   om/fwlink/?LinkID=66439)。
> 
> #### 详细错误信息:
> ```
> <tr><th>错误代码</th><td>&nbsp;&nbsp;&nbsp;0x80070002</td></tr>
> ```
> 
> 模块	   IIS Web Core
> 通知	   MapRequestHandler
> 处理程序	   StaticFile
> 请求的 URL   http://127.0.0.1:80 /minio/peer/v9/cyclebloom 物理路径   D 2: github.com\minio\minio@\cmd\notification.go:473:cmd.(*NotificationSys) .updateBloomFilter.func1() 1: github.com\minio\minio@\pkg\sync\errgroup\errgroup.go:55:errgroup.(*Gr oup).Go.func1() `
> ## Expected Behavior
> no error
> 
> ## Current Behavior
> error appeared every 5 minutes
> 
> ## Possible Solution
> no
> 
> ## Steps to Reproduce (for bugs)
> run command, wait 5 minutes
> 
> ## Context
> ## Regression
> ## Your Environment
> Win 10 & Win Server 2012 Standard, simple chinese language

This is not the correct way to setup distributed cluster @sPhinX-LHJ follow our docs

**Comment by sPhinX-LHJ** [comment]
Is there a recommended setup to expand disk or partition on single server?
for example, I have a partition (20TB) at first, after servral months, I get another added partition (20TB), so I want to expand to the  added partition. So I try to use Distributed MinIO, Its maybe not good, but I have to do this, please give some advice, Thanks!@harshavardhana

**Comment by klauspost** [comment]
There is nothing related to IIS in Minio. Maybe something else is picking it up.

Maybe run on port 9000 or something similar. Feel free to ask for help on community slack: https://slack.min.io/
