### ISSUE TITLE
cant make public read only ):

### ISSUE THREAD

**Issue by rwb99** [minio/minio#9762]
tried this ![image](https://user-images.githubusercontent.com/63825594/83635995-2d6a8880-a573-11ea-98ca-aad9413ed50b.png) 

also tried "x-amz-acl" 

 

"mc policy set public minio/media"
 "mc policy set public /usr/local/share/minio/media"
"mc policy set public /usr/local/share/minio/media"

i just installed like 10 hours ago

also all mc commands bring up this blue thingy instead of passing the commands
![image](https://user-images.githubusercontent.com/63825594/83636490-0fe9ee80-a574-11ea-9826-2e2bbd923ca6.png)

i followed this guide https://www.digitalocean.com/community/tutorials/how-to-set-up-an-object-storage-server-using-minio-on-ubuntu-18-04

**Comment by klauspost** [comment]
You are running "midnight commander" which is a whole different program.

See here how to install `mc` (MinIO client) https://docs.min.io/docs/minio-client-quickstart-guide.html

**Comment by klauspost** [comment]
You can ask usage questions on Community Slack, which is more appropriate than here. https://slack.min.io/
