### ISSUE TITLE
Bucket policies are broken in gateway nas mode

### ISSUE THREAD

**Issue by DerMitch** [minio/minio#9764]
## Expected Behavior
When running MinIO in "gateway nas" mode, it should be able to deliver files when it's allowed by the bucket policy.

## Current Behavior
MinIO is just logging "Not implemented" in it's console output and preventing access to files.

## Steps to Reproduce (for bugs)
1. Start a fresh instance of MinIO using `minio gateway nas <somewhere>`
2. Observe an error already (macOS only, not seen on Docker):
```
API: SYSTEM()
Time: 18:44:52 CEST 06/03/2020
DeploymentID: c8119235-19a9-4c86-a68f-d5af90ca75d6
Error: invalid argument
       1: github.com/minio/minio@/cmd/gateway-main.go:150:cmd.StartGateway()
```
3. Try to access anything on the server, e.g. using curl: `curl -I http://localhost:9001/bucket/` (returns 403 Forbidden)
4. Another error in the console appears every time the bucket index is accessed:
```
API: SYSTEM()
Time: 18:48:05 CEST 06/03/2020
DeploymentID: c8119235-19a9-4c86-a68f-d5af90ca75d6
Error: Not Implemented
       5: github.com/minio/minio@/cmd/bucket-policy.go:59:cmd.(*PolicySys).IsAllowed()
       4: github.com/minio/minio@/cmd/auth-handler.go:338:cmd.checkRequestAuthTypeToAccessKey()
       3: github.com/minio/minio@/cmd/auth-handler.go:273:cmd.checkRequestAuthType()
       2: github.com/minio/minio@/cmd/bucket-handlers.go:859:cmd.objectAPIHandlers.HeadBucketHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```
5. Create a bucket and set the bucket policy to be public:

```
mc config host add test http://localhost:9001 admin password
mc mb test/bucket
mc policy set download test/bucket
```

6. Upload a file and try to download it. It works when using a signed URL, but using the public policy MinIO just returns 403 and also reports an error in the console:

```
API: SYSTEM()
Time: 18:56:43 CEST 06/03/2020
DeploymentID: b4227057-c2ea-49e4-9856-f15adcbba438
Error: Not Implemented
       3: github.com/minio/minio@/cmd/bucket-policy.go:59:cmd.(*PolicySys).IsAllowed()
       2: github.com/minio/minio@/cmd/object-handlers.go:341:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```

On our staging/production systems we run MinIO with etcd, but have the same problem as well.

## Context
We're using MinIO to manage files on a NetApp NAS (NFS). Since we updated MinIO, access to anything that is public is no longer possible. Fortunately our project is still in staging, but we planned to go live within the next months, and this is a blocker for us.

## Regression
Yes. I don't know the exact version, but it worked around 4-5 weeks ago (I'm currently not able to update to each release when it comes out).

I am aware of #9739, but this is something that worked before - and the changelog only references bugfixes regarding the gateway mode. If it's not meant to work this way, please let us know which is the correct alternative.

## Your Environment
* Version used (`minio version`): RELEASE.2020-06-01T17-28-03Z
* Server type and version: macOS Catalina, Ubuntu 18.04 + Docker

![Bildschirmfoto 2020-06-03 um 18 51 08](https://user-images.githubusercontent.com/178672/83666948-fb3a4480-a5cd-11ea-9798-b46e17f7e16e.png)

**Comment by harshavardhana** [comment]
@DerMitch I don't see how to reproduce this - are you sure you are using the released version?

```
~ minio gateway nas /tmp/nas
Attempting encryption of all config, IAM users and policies on MinIO backend
Configuration file config/config.json migrated from version '28' to '29' successfully.
Configuration file config/config.json migrated from version '29' to '30' successfully.
Configuration file config/config.json migrated from version '30' to '31' successfully.
Configuration file config/config.json migrated from version '31' to '32' successfully.
Configuration file config/config.json migrated from version '32' to '33' successfully.
Configuration file config/config.json migrated from version '33' to new KV format successfully.
Endpoint:  http://10.0.0.67:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000            
AccessKey: minio 
SecretKey: minio123 

Browser Access:
   http://10.0.0.67:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000            

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc config host add mynas http://10.0.0.67:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
```

**Comment by harshavardhana** [comment]
> API: SYSTEM()
> Time: 18:44:52 CEST 06/03/2020
> DeploymentID: c8119235-19a9-4c86-a68f-d5af90ca75d6
> Error: invalid argument
>        1: github.com/minio/minio@/cmd/gateway-main.go:150:cmd.StartGateway()

This we need to ignore on macOS

**Comment by DerMitch** [comment]
@harshavardhana Thank you for your quick response.

On macOS, I used the latest version available from brew (updated today).
```bash
$ sha256sum /usr/local/bin/minio
6d6b80fbd866aa75179274d236e877350c0dc3debf225c3a95655038a2ff525d  /usr/local/bin/minio

$ /usr/local/bin/minio --version
minio version RELEASE.2020-06-01T17-28-03Z
```

---

I also tested the issue with the official docker image, pulled just a few minutes ago:

![Bildschirmfoto 2020-06-03 um 19 50 16](https://user-images.githubusercontent.com/178672/83670456-7eaa6480-a5d3-11ea-979f-eb4ca47727e0.png)

The "Not implemented" appears when doing a `curl http://localhost:9000/bucket/`.

```bash
docker pull minio/minio
docker run -it -e MINIO_ACCESS_KEY=admin -e MINIO_SECRET_KEY=password -p 9000:9000 minio/minio gateway nas /dat
```

**Comment by DerMitch** [comment]
Just tested the new release on our servers, and it works perfectly now.

Thank you very much for the quick fix ❤️

**Comment by harshavardhana** [comment]
> Just tested the new release on our servers, and it works perfectly now.
> 
> Thank you very much for the quick fix
:+1:
