### ISSUE TITLE
[RFC] minio’s web GUI can’t be nginxed to another place than root

### ISSUE THREAD

**Issue by mbannert** [minio/minio#9768]
I open up an issue as discussed with @anthu on Slack. 

I am chasing an issue that was originally brought up @krishnasrinivas . He also made a PR which is why I don’t fork/PR here as his solution tackles the problem. My understanding was that his PR was merged, but still the behavior of minio / issue remains and also the code on master does not seem to contain the changes. So what am I talking about?

**minio’s web gui can’t be nginxed to another place than root.** This is because the “/minio” route is hard coded in several places. For the buckets themselves there seems to be another solution. Yet the GUI issues persist at least with the docker image I pulled lately. Also the code on the official repository seems to have /minio hardcoded in its browser code:
https://github.com/minio/minio/blob/master/browser/app/index.html
See line 12 for example where the css is linked.

**What would I like to see?**
Like @krishnasrinivas suggests the `minioBrowserPrefix` variable should be used consequently so we can use others directories than root. This is relevant when you want to run several instances of minio, e.g., multiple docker containers on the same docker host. 
This should solve the problem: 
https://github.com/krishnasrinivas/minio/commit/8e64f524c256186f20b71d9bdc97e45013697241

**Alternatives I considered**
I know that the above fix would cure the issue (admittedly I haven't tested for side effects so far) because @homocodens and me hacked our way to a solution that does something similar:

```
location ~* ^/someotherfolder/(.*)$ {
        sub_filter_once off;
        sub_filter_types text/html;
        sub_filter "/minio/" "/someotherfolder/";
        client_max_body_size 10m;
        rewrite ^/someotherfolder/(.*)$ /minio/$1 break;
        proxy_redirect off;
        proxy_set_header Host $http_host;
        proxy_set_header Accept-Encoding "";
        #this is just our custom port here
        proxy_pass http://localhost:8234;
    }
```
What we do here is basically ‘gsub’  `/minio` strings in the source code using nginx’ subfilter. I consider this hacky and thought it should be in the original minio code.

**How do you think about this at minio / in the community ?**

**Additional context**
Word on Slack is that this issue came up repeatedly out of the K8 community. Our above 'solution' / hack might also help them.

**Comment by harshavardhana** [comment]
It is not in our interest to do this @mbannert it makes our code complicated.

Feel free to create a fork of MinIO and use it the way you want with additional code changes.

We cannot possibly carry this baggage on our end.

**Comment by anthu** [comment]
This is a somehow disappointing answer.
Could you make clear who is "you" in the context of interest? And how do we know, what is in your interest for the future?

I like the proposal as this is something happening and not an unusual setting in cloud native applications containing frontend redirects.

Regarding the complicated code: hard-coded values make code complicated. We should definitely looking into extracting those values and then the path towards a configurable setting would be easy.

Please reopen this issue and let us discuss this proposal in an appropriate, I cite the Code of Conduct: "open and welcoming environment".

**Comment by harshavardhana** [comment]
> 
> Regarding the complicated code: hard-coded values make code complicated. We should definitely looking into extracting those values and then the path towards a configurable setting would be easy.
> 

I don't think so. You are missing the point of documentation and being able to communicate what this feature entails. 

> Please reopen this issue and let us discuss this proposal in an appropriate, I cite the Code of Conduct: "open and welcoming environment".

The purpose should be carefully understood, the bagge we need to carry for future should be well understood. Everyone has a niche use-case we are not trying to solve all the world's problems in a single software. 

MinIO is working as presented and it works as expected under the constraints of what it is designed as per our design decision. If you don't like the decision then you are always free to modify the code and use it the way you want. 

By quoting out of context our code of conduct is beyond words for me and downright offensive for me who is tirelessly writing code, and fixing bugs that you opened up @anthu along the process. 

The feature and the reference PR was long discussed and deemed unnecessary complication for limited benefit. If it is disappointing so be it, it is not something we wish to carry in our codebase. 

The issue shall remain closed as its a design decision to not do it.

**Comment by anthu** [comment]
It wasn't my intention to be offensive in any way - I'm truly sorry, if I formulated it in a wrong way. You are definitely doing a great job, building Minio and offering it as Open Source. Same goes out to the whole team.

I brought it up once again and hoping for a backlog of features, being discussed by the community and driven by the community.
Pushing back such proposals without hearing the voice of the user-base is not something I expected, when suggesting @mbannert to create such a proposal here over waiting for an answer on Slack.

I want you take this as feedback with only best intentions from my side! I wish to contribute here more at some time. 
Maybe you could work on enabling the community beyond the core team to contribute eg. through transparency over the backlog.

**Comment by harshavardhana** [comment]
Understood @anthu - we will discuss this internally and see if we can come up with something of a label on issues which the community can contribute. 

Thank you for your support.

**Comment by mbannert** [comment]
Me too, never meant to fuel the flame or go to war with this. I was very reluctant to resurrect an old issue here. That's why I timidly brought it to Slack where @anthu suggested to discuss it over here. I was encouraged that our hack might be a workaround others especially from the K8 community might appreciate. 

I don't think I should go for a fork. We love `minio` the way it is and our hack is better than maintaining yet another fork. It's not just a git repo it would also mean to maintain another docker image on dockerhub as this is relevant for the cloud crowd (only).  

Given your decision I am happy I brought the nginx solution up so somebody else could find it in context aware fashion. On an endnote: nginx `sub_filter` won't work when gzip compressed. That was something that was hard to find in the docs for us at first.

EDIT: I fully respect the design decision to not address this, but I give the feedback that it was not clear to a seasoned OSS developer (from another field) from the outside looking in that this was a clear design decision. I had a hunch... but :) 

However, Keep up the great work!

**Comment by leohxj** [comment]
use this Nginx conf, it could visit Minio WEB UI, but not for share url.
example:

original Minio service is on localhost:3000, I can get and visit a shareable url, such as

http://localhost:3000/name_of_bucket/name_of_image.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20200711%2F%2Fs3%2Faws4_request&X-Amz-Date=20200711T080736Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Signature=2d8dbff88274498ece0c58c2e0e093cb4503d8feb750ff0d4a33acbafc0e9a8d

but if we use Nginx proxy, could not visit:
http://localhost:9000/name_of_bucket/name_of_image.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20200711%2F%2Fs3%2Faws4_request&X-Amz-Date=20200711T080736Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Signature=2d8dbff88274498ece0c58c2e0e093cb4503d8feb750ff0d4a33acbafc0e9a8d

how can I fix this problem? need to config bucket proxy??
