### ISSUE TITLE
multipart: Unstable on rpi2

### ISSUE THREAD

**Issue by kaihendry** [minio/minio#977]
Tried to copy a 1.4GB fedora 23 ISO to my Rpi2 minio bucket and it just stalled the whole system. Nothing in `journalctl`. 

http://ix.io/mpi

**Comment by harshavardhana** [comment]
@kaihendry - do you have any other information - do you see any errors on the server side ? 

Can you perhaps do 'mc ls -I <server>'  and see if it hangs ?

**Comment by harshavardhana** [comment]
Also on rpi2 what is the actual disk speed?

**Comment by kaihendry** [comment]
Couldn't find any errors. .Surprised you don't maintain a server side log file ??

http://ix.io/mpj <-- not fond of seeing all the multiparts like that. why not maintain a dot dir like rsync?

Now sure how you would like me to determine the disk speed.

**Comment by harshavardhana** [comment]
> Couldn't find any errors. .Surprised you don't maintain a server side log file ??

By default it logs to console and only logs when there are errors, It has to be configured to log to file.

```
$ minio config logger add file /tmp/minio.log
```

> http://ix.io/mpj <-- not fond of seeing all the multiparts like that. why not maintain a dot dir like rsync?

That is something in flux still, it isn't a finalized design just yet. 

> Now sure how you would like me to determine the disk speed.

Simple tests on the backend with both these commands. 

```
$ dd if=/dev/zero of=<backend_dir>/bigfile bs=1M count=1024 oflag=direct
$ dd if=/dev/zero of=<backend_dir>/bigfile bs=1M count=1024 oflag=sync
```

**Comment by harshavardhana** [comment]
> http://ix.io/mpj <-- not fond of seeing all the multiparts like that. why not maintain a dot dir like rsync?

Oh wait, multiparts should never be listed like that in 'mc ls' output - this is clearly a bug.  Let me check.

**Comment by harshavardhana** [comment]
> Tried to copy a 1.4GB fedora 23 ISO to my Rpi2 minio bucket and it just stalled the whole system. 

The stalling the system experience occurs, since due to multipart upload - it is trying to verify 'md5' of uploaded chunks with CompleteMultipart request.  It is slowing things down on `rpi2` which is perhaps simulated as a system hang. 

I have relaxed that requirement for the time being.  There are many more changes coming, in upcoming days. 

Also i fixed a bug to not list multiparts, there were not supposed to be listed anyways.

**Comment by harshavardhana** [comment]
This bug will be closed after 'multipart' handling is re-written on the server side.

**Comment by harshavardhana** [comment]
Fixed in current master to have granular locking and also adding doing multipart concatenation with large chunks avoided this problem.
