### ISSUE TITLE
LocationConstraint of Bucket is remaining null for different region while creating bucket using Minio Python Client.

### ISSUE THREAD

**Issue by AILearner17** [minio/minio#9770]
LocationConstraint of Bucket is remaining null for different region while creating bucket using Minio Python Client.

I am trying to create bucket using boto3 client for minioserver 
s3_client = boto3.client('s3',
                                      endpoint_url='http://localhost:9000,
                                      aws_access_key_id=self.access_key,
                                      aws_secret_access_key=self.secret_key,
                                      region_name=self.region)
s3_client.create_bucket(Bucket=bucket_name,
                                         CreateBucketConfiguration={
                                             'LocationConstraint': region,
                                         }, )
And trying to fetch all buckets belonging to a particular region using below code 
lstbuckets = []
        try:
            logger.info("In get_all_bucket {}".format(self.region))
            for bucket in self.s3_client.list_buckets()["Buckets"]:
                if self.s3_client.get_bucket_location(Bucket=bucket['Name'])['LocationConstraint'] == self.region:
                    lstbuckets.append({'RegionName': bucket['Name']})
            return lstbuckets 

But unfortunately the list is always empty as LocationConstraint is null for all buckets created as below.
{
      "LocationConstraint": null,
      "ResponseMetadata": {
        "HTTPHeaders": {
          "accept-ranges": "bytes",
          "content-length": "128",
          "content-security-policy": "block-all-mixed-content",
          "content-type": "application/xml",
          "date": "Thu, 04 Jun 2020 12:37:01 GMT",
          "server": "MinIO/RELEASE.2020-06-03T22-13-49Z",
          "vary": "Origin",
          "x-amz-request-id": "1615577927931FC6",
          "x-xss-protection": "1; mode=block"
        },
        "HTTPStatusCode": 200,
        "HostId": "",
        "RequestId": "1615577927931FC6",
        "RetryAttempts": 0
      }
    }
## Expected Behavior
LocationConstraint should have value of the region as below example.
{
      "LocationConstraint": 'us-east-1,
      "ResponseMetadata": {
        "HTTPHeaders": {
          "accept-ranges": "bytes",
          "content-length": "128",
          "content-security-policy": "block-all-mixed-content",
          "content-type": "application/xml",
          "date": "Thu, 04 Jun 2020 12:37:01 GMT",
          "server": "MinIO/RELEASE.2020-06-03T22-13-49Z",
          "vary": "Origin",
          "x-amz-request-id": "1615577927931FC6",
          "x-xss-protection": "1; mode=block"
        },
        "HTTPStatusCode": 200,
        "HostId": "",
        "RequestId": "1615577927931FC6",
        "RetryAttempts": 0
      }
    }

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
By default server has no location set @SnehashishGiri you need to set a region for your server using

```
export MINIO_REGION=custom-region
```

What you are seeing is expected in a default setting, MinIO will accept all regions since server is not deployed with a specific region

**Comment by AILearner17** [comment]
How to set MINIO_REGION in windows pc. Export works only in unix

**Comment by harshavardhana** [comment]
> How to set MINIO_REGION in windows pc. Export works only in unix

on windows its `set MINIO_REGION=`

**Comment by AILearner17** [comment]
thank you
