### ISSUE TITLE
[not our bug] mc admin policy issues : invalid character '<' looking for beginning of value. 

### ISSUE THREAD

**Issue by nsyvr** [minio/minio#9771]
running minio in docker. trying to use the minio/mc docker image to create policies and add users but gettting an error while adding policies
seems to only happen if the minio is a arm image. running the command against amd64 image works fine.

```
VERSION
2017-08-13T20:51:55Z
PLATFORM
Host: 6e7763b96342 | OS: linux | Arch: arm
```

Nirat  8:38 AM
`mc admin policy info ko users`
```
mc: <ERROR> Cannot list policy: invalid character '<' looking for beginning of value.
works properly if the minio server is on a x86_64 architecture server
```
`image: (minio/minio:edge-armhf)`

## Expected Behavior

`mc admin policy list minio`
`writeonly
casa
diagnostics
readonly
readwrite
user`

`(image: minio/minio)`

## Current Behavior

`mc admin policy info ko users`

```
mc: <ERROR> Cannot list policy: invalid character '<' looking for beginning of value.
works properly if the minio server is on a x86_64 architecture server
```

DEBUG info 
```
mc admin policy list ko --debug
mc: <DEBUG> GET /minio/admin/v3/list-canned-policies HTTP/1.1
Host: 192.168.1.68:2222
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-05-28T23:43:36Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200604//s3/aws4_request, SignedHeaders=host;x-amz-content-s                            ha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200604T145206Z
Accept-Encoding: gzip
mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 2021
Accept-Ranges: bytes
Content-Type: text/html; charset=utf-8
Date: Thu, 04 Jun 2020 14:52:06 GMT
Last-Modified: Sat, 24 Jun 2017 08:36:20 GMT
Vary: Origin
mc: <DEBUG> Response Time:  410.032111ms
mc: <ERROR> Cannot list policy: invalid character '<' looking for beginning of value
 (1) admin-policy-list.go:70 cmd.mainAdminPolicyList(..) Tags: [ko]
 (0) admin-policy-list.go:70 cmd.mainAdminPolicyList(..)
 Release-Tag:RELEASE.2020-05-28T23-43-36Z | Commit:2403e7a7441b | Host:aspire | OS:linux | Arch:amd64 | Lang:go1.13.1                            0 | Mem:1.8 MB/72 MB | Heap:1.8 MB/66 MB.
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

```
VERSION
2017-08-05T00:00:53Z
MEMORY
Used: 3.1 MB | Allocated: 4.8 MB | Used-Heap: 3.1 MB | Allocated-Heap: 6.8 MB
PLATFORM
Host: 90ae92e66137 | OS: linux | Arch: arm
RUNTIME
Version: go1.7.5 | CPUs: 4
```
* Server type and version: Raspberry pi 3 running ubuntu 20.04 LTS
* Operating System and version (`uname -a`): Linux ubuntu 5.4.0-1011-raspi #11-Ubuntu SMP Fri May 8 07:43:33 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
* Link to your project:

**Comment by harshavardhana** [comment]
> VERSION
> 2017-08-13T20:51:55Z
> PLATFORM
> Host: 6e7763b96342 | OS: linux | Arch: arm

This MinIO version is like 3yrs old and you are using latest `mc` @niratsthapit did you expect it to work?

**Comment by nsyvr** [comment]
how can i get the latest arm version of the server??
when i pull the latest one, minio server does not start
`minio/minio:latest`
`standard_init_linux.go:211: exec user process caused "exec format error"`

**Comment by harshavardhana** [comment]
> how can i get the latest arm version of the server??
> when i pull the latest one, minio server does not start
> `minio/minio:latest`
> `standard_init_linux.go:211: exec user process caused "exec format error"`

For now you need to build your own or download one from here https://dl.minio.io/server/minio/release/linux-arm/
