### ISSUE TITLE
UI create empty folder/prefix

### ISSUE THREAD

**Issue by darkdragon-001** [minio/minio#9774]
In order to complete #5956, for a follow-up to #9631 I need clarification for the following points
- ~~"..." menu: share folder/prefix
  -> Is there an RPC method to get something like [Javascript SDK presignedUrl()](https://docs.minio.io/docs/javascript-client-api-reference.html#presignedUrl)~~ No, see https://github.com/minio/minio/issues/9774#issuecomment-657187809.
- "+" menu: create empty folder/prefix (see #9409)
  -> Are empty folders supported in the latest version also for _distributed backend_ (#2423 only adds support for _fs_ backend)?

**Comment by harshavardhana** [comment]
// cc @kaankabalak @kanagarajkm

**Comment by harshavardhana** [comment]
> * "..." menu: share folder/prefix
>   -> Is there an RPC method to get something like [Javascript SDK presignedUrl()](https://docs.minio.io/docs/javascript-client-api-reference.html#presignedUrl)


yes its

func (web *webAPIHandlers) PresignedGet(r *http.Request, args *PresignedGetArgs, reply *PresignedGetRep) error {

> * -> Are empty folders supported in the latest version also for _distributed backend_ (#2423 only adds support for _fs_ backend)?

Yes they are supported in all variations @darkdragon-001

**Comment by darkdragon-001** [comment]
> > * "..." menu: share folder/prefix
> >   -> Is there an RPC method to get something like [Javascript SDK presignedUrl()](https://docs.minio.io/docs/javascript-client-api-reference.html#presignedUrl)
> 
> yes its
> 
> func (web *webAPIHandlers) PresignedGet(r *http.Request, args *PresignedGetArgs, reply *PresignedGetRep) error {

How can I call this from the React/JS frontend to get a share-link for a prefix/folder? What would be example parameters in this case?

**Comment by harshavardhana** [comment]
> How can I call this from the React/JS frontend to get a share-link for a prefix/folder? What would be example parameters in this case?

a folder can be shared in AWS S3 spec using something like a form post method https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html

But this is not directly usable for users as a share-able URL @darkdragon-001 because it requires a POST request to be initiated by the client. So it is not easy to allow a shareable folder using browser UI. 

AWS S3 doesn't allow direct uploads to a prefix using presigned URL they only allow uploads to a prefix using POST request as stated above.

From a UI point of view it's a bit of a stretch to add this functionality IMO.

**Comment by darkdragon-001** [comment]
@harshavardhana Thanks for the explanation. Generating a share-link to a single-file is possible that's why I was wondering if the same is possible for prefixes/folders. I agree under these circumstances it doesn't make sense to add this to the UI.

**Comment by darkdragon-001** [comment]
> > * -> Are empty folders supported in the latest version also for _distributed backend_ (#2423 only adds support for _fs_ backend)?
> 
> Yes they are supported in all variations @darkdragon-001

@harshavardhana Is there an RPC method for their creation?

**Comment by harshavardhana** [comment]
> > > * -> Are empty folders supported in the latest version also for _distributed backend_ (#2423 only adds support for _fs_ backend)?
> > 
> > Yes they are supported in all variations @darkdragon-001
> 
> @harshavardhana Is there an RPC method for their creation?

It's Upload() API without a body i.e content-length 0 and append a `/` at the end of the object.

**Comment by harshavardhana** [comment]
MinIO browser is in code freeze, we are migrating fully to https://github.com/minio/console
