### ISSUE TITLE
[resolved] After disk replacement contents of bucket differ between requests

### ISSUE THREAD

**Issue by kalinon** [minio/minio#9776]
Edit: Related issue https://github.com/minio/minio-operator/issues/136 

It seems depending on which server the requests goes to the data results are different.
```
➜  ~ mc ls broken/trove
➜  ~ mc ls broken/trove
[2020-05-17 17:54:25 EDT]   12MiB roll20.txt
[2020-06-05 09:35:26 EDT]      0B Assets/
[2020-06-05 09:35:26 EDT]      0B Books/
[2020-06-05 09:35:26 EDT]      0B Magazines/
[2020-06-05 09:35:26 EDT]      0B Open Source/
[2020-06-05 09:35:26 EDT]      0B Tools/
```

More debug output:
https://pastebin.com/7TT3rTYB

A request with `--debug` that gave bucket contents back:
```
➜  ~ mc ls --debug broken/trove
mc: <DEBUG> GET /trove/?location= HTTP/1.1
Host: localhost:9000
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200605/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200605T132937Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 137
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 05 Jun 2020 13:29:37 GMT
Server: MinIO/RELEASE.2020-05-16T01-33-21Z
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 1615A8EC8E5A8149
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  8.693392ms

mc: <DEBUG> HEAD /trove/ HTTP/1.1
Host: localhost:9000
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200605/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200605T132937Z

mc: <DEBUG> HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Fri, 05 Jun 2020 13:29:37 GMT
Server: MinIO/RELEASE.2020-05-16T01-33-21Z
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 1615A8EC8E89DFD6
X-Xss-Protection: 1; mode=block
Content-Length: 0

mc: <DEBUG> Response Time:  2.309662ms

mc: <DEBUG> HEAD /trove/ HTTP/1.1
Host: localhost:9000
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200605/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200605T132937Z

mc: <DEBUG> HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Fri, 05 Jun 2020 13:29:37 GMT
Server: MinIO/RELEASE.2020-05-16T01-33-21Z
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 1615A8EC8EB1BC3F
X-Xss-Protection: 1; mode=block
Content-Length: 0

mc: <DEBUG> Response Time:  2.474404ms

mc: <DEBUG> GET /trove/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix= HTTP/1.1
Host: localhost:9000
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200605/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200605T132937Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 907
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 05 Jun 2020 13:29:37 GMT
Server: MinIO/RELEASE.2020-05-16T01-33-21Z
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 1615A8EC8EDD75AD
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  6.846142ms

[2020-05-17 17:54:25 EDT]   12MiB roll20.txt
[2020-06-05 09:29:37 EDT]      0B Assets/
[2020-06-05 09:29:37 EDT]      0B Books/
[2020-06-05 09:29:37 EDT]      0B Magazines/
[2020-06-05 09:29:37 EDT]      0B Open Source/
[2020-06-05 09:29:37 EDT]      0B Tools/
```
A response that gave empty bucket back:
```
➜  ~ mc ls --debug broken/trove
mc: <DEBUG> GET /trove/?location= HTTP/1.1
Host: localhost:9000
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200605/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200605T132934Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 137
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 05 Jun 2020 13:29:34 GMT
Server: MinIO/RELEASE.2020-05-16T01-33-21Z
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 1615A8EBCB2DA7FD
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  6.400569ms

mc: <DEBUG> HEAD /trove/ HTTP/1.1
Host: localhost:9000
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200605/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200605T132934Z

mc: <DEBUG> HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Fri, 05 Jun 2020 13:29:34 GMT
Server: MinIO/RELEASE.2020-05-16T01-33-21Z
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 1615A8EBCB4E6453
X-Xss-Protection: 1; mode=block
Content-Length: 0

mc: <DEBUG> Response Time:  2.59942ms

mc: <DEBUG> HEAD /trove/ HTTP/1.1
Host: localhost:9000
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200605/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200605T132934Z

mc: <DEBUG> HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Fri, 05 Jun 2020 13:29:34 GMT
Server: MinIO/RELEASE.2020-05-16T01-33-21Z
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 1615A8EBCB76D413
X-Xss-Protection: 1; mode=block
Content-Length: 0

mc: <DEBUG> Response Time:  2.215956ms

mc: <DEBUG> GET /trove/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix= HTTP/1.1
Host: localhost:9000
User-Agent: MinIO (darwin; amd64) minio-go/v6.0.56 mc/2020-05-16T01:44:37Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200605/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200605T132934Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 293
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Fri, 05 Jun 2020 13:29:34 GMT
Server: MinIO/RELEASE.2020-05-16T01-33-21Z
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 1615A8EBCB9D2BF6
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  6.98146ms
```

Here is the physical contents of the drives for each server:

minio/minio-0, minio/minio-1, minio/minio-2, minio/minio-3, minio/minio-4
```
/export/trove # ls -larth
total 16K
drwxr-xr-x    2 root     root          47 May 17 21:54 roll20.txt
drwxr-xr-x    3 root     root          28 May 17 21:54 Open Source
drwxr-xr-x    6 root     root         127 May 17 21:54 Tools
drwxr-xr-x    8 root     root         128 May 17 21:54 .
drwxr-xr-x   15 root     root         329 May 17 21:57 Assets
drwxr-xr-x   21 root     root        4.0K May 17 22:02 Magazines
drwxr-xr-x  179 root     root        8.0K May 17 22:46 Books
drwxr-xr-x   10 113      119          156 Jun  5 13:32 ..
```

minio/minio-5 (drive replaced)
```
/export/trove # ls -larth
total 0
drwxr-xr-x    2 root     root           6 Jun  4 14:07 .
drwxr-xr-x   10 root     root         156 Jun  5 13:32 ..
```

minio/minio-6 (drive replaced)
```
/export/trove # ls -larth
total 0
drwxr-xr-x    2 root     root           6 Jun  4 14:07 .
drwxr-xr-x   10 root     root         156 Jun  5 13:37 ..
/export/trove #
```

It seems that when the request is forwarded to the node that had the drive replaced it is not aware of the contents of the bucket.

The heal command does not seem to have any effect on it either:

```
➜  ~ mc admin heal broken/trove
 ◐  trove
    0/0 objects; 0 B in 28s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 2 │ 100.0% ████████████ │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
```

## Expected Behavior
The results of a request to a bucket should be consistent no matter the server the request is passed to.

## Current Behavior
If request is passed to a server with a replaced drive it will only return the items that are replicated to that drive.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
* Version used (`minio-operator`): minio/k8s-operator:2.0.3
* Environment name and version (e.g. kubernetes v1.17.2): v1.17.5
* Server type and version: Distributed - RELEASE.2020-05-16T01-33-21Z
* Operating System and version (`uname -a`): Linux kube-02 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Listing can be inconsistent until full heal is complete, did you manually run the heal or did you just let the auto heal to take care of the situation?

**Comment by harshavardhana** [comment]
> ➜  ~ mc admin heal broken/trove
>  ◐  trove
>     0/0 objects; 0 B in 28s
>     ┌────────┬───┬─────────────────────┐
>     │ Green  │ 2 │ 100.0% ████████████ │
>     │ Yellow │ 0 │   0.0%              │
>     │ Red    │ 0 │   0.0%              │
>     │ Grey   │ 0 │   0.0%              │
>     └────────┴───┴─────────────────────┘

mc admin heal -r is what you need to trigger the heal of entire setup @kalinon  - just running `mc admin heal` give you the heal of the drive format. 

> minio/minio-5 (drive replaced)
> 
> ```
> /export/trove # ls -larth
> total 0
> drwxr-xr-x    2 root     root           6 Jun  4 14:07 .
> drwxr-xr-x   10 root     root         156 Jun  5 13:32 ..
> ```
> 
> minio/minio-6 (drive replaced)
> 
> ```
> /export/trove # ls -larth
> total 0
> drwxr-xr-x    2 root     root           6 Jun  4 14:07 .
> drwxr-xr-x   10 root     root         156 Jun  5 13:37 ..
> /export/trove #
> ```

The drives replaced you need to wait for 10minutes before the entire heal kicks in - did you wait for 10minutes? @kalinon

**Comment by kalinon** [comment]
@harshavardhana i tried to trigger multiple heals. I am unsure how long i waited before triggering a heal. I used the command:

```
mc admin heal -r broken
```

As well as each bucket underneath it. Perhaps i did not wait the 10 minutes before? If so, would that prevent the drive replacement from happening correctly?

**Comment by harshavardhana** [comment]
> As well as each bucket underneath it. Perhaps i did not wait the 10 minutes before? If so, would that prevent the drive replacement from happening correctly?

10 minutes is until it needs to wait until the drive starts healing automatically, the idea is you replace the drives and continue your operation - check after 10minutes if the healing has started.

There is no good reason to unnecessarily hurry things by doing a subsequent `mc admin heal` you can perform this procedure once again on your end to observe what is happening. 

> @harshavardhana i tried to trigger multiple heals. I am unsure how long i waited before triggering a heal. I used the command:

Multiple heal trigger is not needed only one is enough.

**Comment by kalinon** [comment]
Ok, so if it was triggered and completed successfully, then this should not happen? Shouldn't the background heal also have taken care of it overnight?

**Comment by harshavardhana** [comment]
> Ok, so if it was triggered and completed successfully, then this should not happen? Shouldn't the background heal also have taken care of it overnight?

Background heal only runs once in 30days @kalinon we don't have active heal which we are currently working on which would avoid all the manual healing altogether.

But disk heal should have triggered if it didn't trigger then either you were doing something with the setup and you didn't allow it to do its job.  Or we have a bug we need to fix we will investigate this and let you know.

**Comment by kalinon** [comment]
For reference i always found it weird that it comes back with `Never executed` when i try to trigger it or look at the status:

<img width="322" alt="Screen Shot 2020-06-05 at 12 31 59 PM" src="https://user-images.githubusercontent.com/5629164/83901318-90515080-a728-11ea-9042-4ffe74446ddb.png">

Also this is the usual response when i try to heal the top level with `-r` as you suggest:
<img width="516" alt="Screen Shot 2020-06-05 at 12 38 34 PM" src="https://user-images.githubusercontent.com/5629164/83901910-7bc18800-a729-11ea-8036-f70aec9d8924.png">

Other weird things im noticing is that `mc admin info` does not seem to give correct information:

```
➜  ~ mc admin info broken
●  minio-1.minio-hl-svc.minio.svc.cluster.local:9000
   Uptime: 1 day
   Version: 2020-05-16T01:33:21Z
   Network: 5/7 OK
   Drives: 1/1 OK

●  minio-2.minio-hl-svc.minio.svc.cluster.local:9000
   Uptime: 1 day
   Version: 2020-05-16T01:33:21Z
   Network: 5/7 OK
   Drives: 1/1 OK

●  minio-3.minio-hl-svc.minio.svc.cluster.local:9000
   Uptime: 1 day
   Version: 2020-05-16T01:33:21Z
   Network: 5/7 OK
   Drives: 1/1 OK

●  minio-4.minio-hl-svc.minio.svc.cluster.local:9000
   Uptime: 1 day
   Version: 2020-05-16T01:33:21Z
   Network: 5/7 OK
   Drives: 1/1 OK

●  minio-5.minio-hl-svc.minio.svc.cluster.local:9000
   Uptime: offline

●  minio-6.minio-hl-svc.minio.svc.cluster.local:9000
   Uptime: offline

●  minio-0.minio-hl-svc.minio.svc.cluster.local:9000
   Uptime: 1 day
   Version: 2020-05-16T01:33:21Z
   Network: 5/7 OK
   Drives: 1/1 OK

949 GiB Used, 2 Buckets, 2,338 Objects
5 drives online, 0 drives offline
```

It should be 5 drives online, 2 offline. I also have a total of 7 buckets. I did take the 2 drives offline as the inconsistent contents was causing issues with my applications.

```
➜  ~ mc ls broken
[2020-05-17 17:09:24 EDT]      0B backup/
[2020-05-28 15:40:32 EDT]      0B diamanti/
[2020-05-17 17:09:25 EDT]      0B htpc/
[2020-05-17 17:09:25 EDT]      0B media/
[2020-05-17 17:09:25 EDT]      0B newznab/
[2020-05-17 17:09:25 EDT]      0B trove/
[2020-05-17 17:09:26 EDT]      0B vault/
➜  ~ mc mb broken/backup
mc: <ERROR> Unable to make bucket `broken/backup`. Your previous request to create the named bucket succeeded and you already own it.
➜  ~ mc mb broken/diamanti
mc: <ERROR> Unable to make bucket `broken/diamanti`. Your previous request to create the named bucket succeeded and you already own it.
➜  ~ mc mb broken/htpc
mc: <ERROR> Unable to make bucket `broken/htpc`. Your previous request to create the named bucket succeeded and you already own it.
➜  ~ mc mb broken/media
mc: <ERROR> Unable to make bucket `broken/media`. Your previous request to create the named bucket succeeded and you already own it.
➜  ~ mc mb broken/newznab
mc: <ERROR> Unable to make bucket `broken/newznab`. Your previous request to create the named bucket succeeded and you already own it.
➜  ~ mc mb broken/trove
mc: <ERROR> Unable to make bucket `broken/trove`. Your previous request to create the named bucket succeeded and you already own it.
➜  ~ mc mb broken/vault
mc: <ERROR> Unable to make bucket `broken/vault`. Your previous request to create the named bucket succeeded and you already own it.
```

**Comment by kalinon** [comment]
> > Ok, so if it was triggered and completed successfully, then this should not happen? Shouldn't the background heal also have taken care of it overnight?
> 
> Background heal only runs once in 30days @kalinon we don't have active heal which we are currently working on which would avoid all the manual healing altogether.
> 
> But disk heal should have triggered if it didn't trigger then either you were doing something with the setup and you didn't allow it to do its job. Or we have a bug we need to fix we will investigate this and let you know.

Appreciate the help. I will try to replace a drive again and let the 10 min timer trigger.

**Comment by harshavardhana** [comment]
> ●  minio-4.minio-hl-svc.minio.svc.cluster.local:9000
>    Uptime: 1 day
>    Version: 2020-05-16T01:33:21Z
>    Network: 5/7 OK
>    Drives: 1/1 OK
> 
> ●  minio-5.minio-hl-svc.minio.svc.cluster.local:9000
>    Uptime: offline
> 
> ●  minio-6.minio-hl-svc.minio.svc.cluster.local:9000
>    Uptime: offline
> 
> ●  minio-0.minio-hl-svc.minio.svc.cluster.local:9000
>    Uptime: 1 day
>    Version: 2020-05-16T01:33:21Z
>    Network: 5/7 OK
>    Drives: 1/1 OK

This is correct because you simply have 1 drive per server and just 7 servers, this is the most uncommon setup for MinIO so it is rightfully showing that you have 5 networks online out of 7 i.e 2 offline.

> ```
> 5 drives online, 0 drives offline
> ```

This is our bug - because we clearly know that node is offline we can show that disk is offline. We need to fix this and this is a client-side issue i.e in `mc`

**Comment by harshavardhana** [comment]
This issue is addressed ListObjects is now back to quorum based listing
