### ISSUE TITLE
[not our bug] Allow specific bucket to list (AWS)

### ISSUE THREAD

**Issue by mistryharshil** [minio/minio#9778]
I am using minio as a gateway for listing AWS s3 buckets and contents. What I am trying is to list only specific bucket(s) to be listed on minio browser that way I can have more control on exposing my all buckets. 

When I am trying to restrict it using IAM policy shown below, I am unable to list any of the buckets
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject"
            ],
            "Resource": "arn:aws:s3:::miniotestbucket/*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::miniotestbucket"
        }
    ]
}`

But adding action as "s3:ListAllMyBuckets" to the policy, allows listing all buckets but unfortunately, there is no control over specific bucket but all. 

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject"
            ],
            "Resource": "arn:aws:s3:::miniotestbucket/*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::miniotestbucket"
        },
        {
            "Sid": "VisualEditor2",
            "Effect": "Allow",
            "Action": "s3:ListAllMyBuckets",
            "Resource": "*"
        }
    ]
}`

Is there any way that I can list specific bucket and control over it? 
Any suggestion would be appreciated to solve this issue. 

Thank you

**Comment by kannappanr** [comment]
Unfortunately, there isn't any way to do that in AWS S3.

**Comment by mistryharshil** [comment]
Well, I have configured minio gateway in ec2 of the same region where bucket(s) exist. Anyways to establish it using policy from minio admin policy or ec2 IAM policy end?

**Comment by harshavardhana** [comment]
> Well, I have configured minio gateway in ec2 of the same region where bucket(s) exist. Anyways to establish it using policy from minio admin policy or ec2 IAM policy end?

AWS doesn't allow this @mistryharshil , you should ask AWS support for this feature

**Comment by mistryharshil** [comment]
Sure, I may find an alternative solution for this. 
Thanks @harshavardhana
