### ISSUE TITLE
[wont fix] Memory Cache

### ISSUE THREAD

**Issue by popey456963** [minio/minio#9795]
It would be useful to get a cache in memory for frequently accessed files, instead of the currently purely disk-based cache.

For instance, we use Minio as a file store.  Sometimes thousands of users can access a file within a few minutes.  At the moment we use an in-memory cache in front of Minio, but this heavily limits the API calls and things we can do, and I feel an in-built solution would be easier & better.

**Comment by harshavardhana** [comment]
Thanks but this is out of scope for us @popey456963 , we already implement a better persistent cache. 

You are better off using our edge caching abilities by pointing them to optane NVMe drives which will be persistent and as fast as your network could be.

https://github.com/minio/minio/tree/master/docs/disk-caching

In-memory caching is seldom useful.

**Comment by popey456963** [comment]
We purely have slow hard drives, which are significantly slower than our network (1gbps versus ~200mbps).  We're a not-for-profit so unfortunately have no money to purchase such expensive drives.

I feel there are still instances where memory caching can be useful.  Especially for last generation technology.

**Comment by harshavardhana** [comment]
> We purely have slow hard drives, which are significantly slower than our network (1gbps versus ~200mbps). We're a not-for-profit so unfortunately have no money to purchase such expensive drives.
> 
> I feel there are still instances where memory caching can be useful. Especially for last generation technology.

I understand but there are cheap NVMe drives available in the market, memory is orders of magnitude still more expensive than NVMe drives - an entry class NVMe is easily < 100$ and gives more than required performance/capacity for the network you are planning to run. 

Alternatively, you can mount the memory as a drive using Linux tmpfs/ramdisk approach and point MinIO caching to use this drive @popey456963

**Comment by titansmc** [comment]
@harshavardhana is it possible to have different tmpfs in a 2 node MinIO cluster? I have 128G of ram in one node and 32 in the other.

Cheers.

**Comment by Padarn** [comment]
@harshavardhana do you mind elaborating on
> In-memory caching is seldom useful.

**Comment by daniel-naegele** [comment]
Would it be possible (and make sense) to create a RamFS and use it as a cache drive?
