### ISSUE TITLE
[incomplete-info] Minio not working with OIDC

### ISSUE THREAD

**Issue by widdix123** [minio/minio#9807]
I get this error when  trying to login via OIDC 

```
index_bundle-2020-05-27T22-08-26Z.js:10 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
```

storage/auto/kube360.minio.kustomization/minio-statefulset.yaml
## Expected Behavior

The browser should show buckets and allow adding of buckets etc 

## Current Behavior

Blank page with above error

## Possible Solution

Unknown
## Steps to Reproduce (for bugs)

Configure MINIO with OIDC

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by widdix123** [comment]
![image](https://user-images.githubusercontent.com/38529736/84401305-be4efd00-ac20-11ea-8ceb-7b6eabd14d75.png)

I get this error

**Comment by harshavardhana** [comment]
> * Version used (`minio version`):
> * Environment name and version (e.g. nginx 1.9.1):
> * Server type and version:
> * Operating System and version (`uname -a`):
> * Link to your project:

These entire questions are left empty can you fill them appropriately?

**Comment by harshavardhana** [comment]
> These entire questions are left empty can you fill them appropriately?

Closing the issue as incomplete, nothing actionable from our end.
