### ISSUE TITLE
[not our bug] Can minio support aliyun oss go sdk which using MIT license file？

### ISSUE THREAD

**Issue by kkuai** [minio/minio#9812]
**Is your feature request related to a problem? Please describe.**
minio have removed support for aliyun OSS go sdk because of license file

**Describe the solution you'd like**
Can minio support aliyun  oss go sdk which using MIT license now？ 
Do aliyun  oss go sdk must have to use the apache license file to be supported ?

**Additional context**
aliyun oss go sdk license file url is below
https://github.com/aliyun/aliyun-oss-go-sdk/blob/master/LICENSE

**Comment by harshavardhana** [comment]
@wangtaowei no we cannot anymore - that ship has sailed, you can use older releases. There are no real interests internally for us anymore.

**Comment by harshavardhana** [comment]
> @wangtaowei no we cannot anymore - that ship has sailed, you can use older releases. There are no real interests internally for us anymore.

Unless our internal priorities change in the future, until that time we have no interest in officially supporting It.
