### ISSUE TITLE
WSO2 Quickstart guide inadequate. Not quick.

### ISSUE THREAD

**Issue by Mattacks** [minio/minio#9817]
The WSO2 Quickstart guide inadequate has a paragraph 'Configure an OAuth service provider.'.

The link does not provide enough information to be abke to do this.

If it calls itself a 'Quick start' guide I expect to be able to start quickly, and not spend more than a day (so far) trying to get it to work.

**Comment by klauspost** [comment]
@Mattacks Could you elaborate on what you would like to see, or alternatively contribute the information you spent more than a day trying to work out.

This is an Open Source project. You are being given the software for free, so instead of opening un-constructive tickets like this may I suggest you take a more active approach in trying to improve it?

**Comment by Mattacks** [comment]
@klauspost Sure. Thanks for picking it up.

I have not got it working yet. If and when I do I will gladly recommend some changes.

As it is, I'm sure the people who wrote the document in the first place must have some more information they can provide. Of course, I have no input into the relative priority of this with other issues.

So, it would be very useful to have some examples of what to fill in what fields. To me it is not even clear if 'Adding a service provider' means 'define a reference to a third party service provider' or 'create an instance of a new service provider.

Yes, this is an open source project. But I expect, if we choose to use it, to pay for Enterpise support and thus contribute $$$ to the primary maintainers - directly and also by our customers.

**Comment by klauspost** [comment]
Thanks for the feedback. I don't have experience with WSO2 setup, but I assume you mean the values in https://github.com/minio/minio/blob/master/docs/sts/wso2.md#4-jwt-claims 

As for configuring the WSO2 server you should probably look into the WSO2 documentation itself. We will not duplicate their documentation.

With regard to evaluating/commercial support you can always contact us at `hello@minio.io` to get assistance in setting up an evaluation cluster for you.

**Comment by harshavardhana** [comment]
As mentioned by @klauspost setting up entire WSO2 is out of scope for us. 

Alternatively you can also use keycloack as well https://github.com/minio/minio/blob/master/docs/sts/keycloak.md
