### ISSUE TITLE
[faq] SSL certificate on QNAP MinIO Server

### ISSUE THREAD

**Issue by alexklu2** [minio/minio#9818]
MinIO Server on QNAP is starting via http so I want to add ssl certificates and start it with https.

A Folder (.minio/certs/) like on the Windows/ Linux Version is not available.
Can this be done with the config.json?

What should the code look like?

**Comment by harshavardhana** [comment]
on windows, it's at the user home directory @alexklu2 `C:\Users\Myname\.minio\certs`

**Comment by harshavardhana** [comment]
Also please use the issue template to correctly describe your issue and list the MinIO version etc. We painfully churn out code for this project the least we ask from the community is to open proper issues that follow our template. 

Please keep this in mind next time.

**Comment by alexklu2** [comment]
Hello,
sorry i'm new here.

But your answer did not answer my question.

My question is how can i install SSL certificates for the Server on a **QNAP System** and not windows?

**Comment by harshavardhana** [comment]
> Hello,
> sorry i'm new here.
> 
> But your answer did not answer my question.
> 
> My question is how can i install SSL certificates for the Server on a **QNAP System** and not windows?

We don't know what QNAP is, you need to ask QNAP vendor for those specifics.

**Comment by alexklu2** [comment]
So this is not offically by you?
https://qnapclub.eu/de/qpkg/632

**Comment by harshavardhana** [comment]
> So this is not offically by you?
> https://qnapclub.eu/de/qpkg/632

Nope MinIO is our brand and product, QNAP is a different product which packages MinIO - we don't officially package it..

**Comment by alexklu2** [comment]
Okay thanks for your answer.

But maybe you can help me anyway.

This is the config.json. Maybe you feel familiar with it and you can see how I can add a statement with path to ssl certificates and the directory etc.

`{
"api":{"_":[{"key":"requests_max","value":"0"},{"key":"requests_deadline","value":"10s"}]},

"audit_webhook":{"_":[{"key":"enable","value":"off"},{"key":"endpoint","value":""},{"key":"auth_token","value":""}]},

"cache":{"_":[{"key":"drives","value":""},{"key":"exclude","value":""},{"key":"expiry","value":"90"},{"key":"quota","value":"80"},{"key":"after","value":"0"},{"key":"watermark_low","value":"70"},{"key":"watermark_high","value":"80"}]},

"compression":{"_":[{"key":"enable","value":"off"},{"key":"extensions","value":".txt,.log,.csv,.json,.tar,.xml,.bin"},{"key":"mime_types","value":"text/*,application/json,application/xml"}]},

"credentials":{"_":[{"key":"access_key","value":""},{"key":"secret_key","value":""}]},

"etcd":{"_":[{"key":"endpoints","value":""},{"key":"path_prefix","value":""},{"key":"coredns_path","value":"/skydns"},{"key":"client_cert","value":""},{"key":"client_cert_key","value":""}]},

"identity_ldap":{"_":[{"key":"server_addr","value":""},{"key":"username_format","value":""},{"key":"username_search_filter","value":""},{"key":"username_search_base_dn","value":""},{"key":"group_search_filter","value":""},{"key":"group_name_attribute","value":""},{"key":"group_search_base_dn","value":""},{"key":"sts_expiry","value":"1h"},{"key":"tls_skip_verify","value":"off"},{"key":"server_insecure","value":"off"}]},

"identity_openid":{"_":[{"key":"config_url","value":""},{"key":"client_id","value":""},{"key":"claim_name","value":"policy"},{"key":"claim_prefix","value":""},{"key":"jwks_url","value":""}]},

"kms_kes":{"_":[{"key":"endpoint","value":""},{"key":"key_name","value":""},{"key":"cert_file","value":""},{"key":"key_file","value":""},{"key":"capath","value":""}]},

"kms_vault":{"_":[{"key":"endpoint","value":""},{"key":"key_name","value":""},{"key":"auth_type","value":"approle"},{"key":"auth_approle_id","value":""},{"key":"auth_approle_secret","value":""},{"key":"capath","value":""},{"key":"key_version","value":""},{"key":"namespace","value":""}]},

"logger_webhook":{"_":[{"key":"enable","value":"off"},{"key":"endpoint","value":""},{"key":"auth_token","value":""}]},

"notify_amqp":{"_":[{"key":"enable","value":"off"},{"key":"url","value":""},{"key":"exchange","value":""},{"key":"exchange_type","value":""},{"key":"routing_key","value":""},{"key":"mandatory","value":"off"},{"key":"durable","value":"off"},{"key":"no_wait","value":"off"},{"key":"internal","value":"off"},{"key":"auto_deleted","value":"off"},{"key":"delivery_mode","value":"0"},{"key":"queue_limit","value":"0"},{"key":"queue_dir","value":""}]},

"notify_elasticsearch":{"_":[{"key":"enable","value":"off"},{"key":"url","value":""},{"key":"format","value":"namespace"},{"key":"index","value":""},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"}]},

"notify_kafka":{"_":[{"key":"enable","value":"off"},{"key":"topic","value":""},{"key":"brokers","value":""},{"key":"sasl_username","value":""},{"key":"sasl_password","value":""},{"key":"sasl_mechanism","value":"plain"},{"key":"client_tls_cert","value":""},{"key":"client_tls_key","value":""},{"key":"tls_client_auth","value":"0"},{"key":"sasl","value":"off"},{"key":"tls","value":"off"},{"key":"tls_skip_verify","value":"off"},{"key":"queue_limit","value":"0"},{"key":"queue_dir","value":""},{"key":"version","value":""}]},

"notify_mqtt":{"_":[{"key":"enable","value":"off"},{"key":"broker","value":""},{"key":"topic","value":""},{"key":"password","value":""},{"key":"username","value":""},{"key":"qos","value":"0"},{"key":"keep_alive_interval","value":"0s"},{"key":"reconnect_interval","value":"0s"},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"}]},

"notify_mysql":{"_":[{"key":"enable","value":"off"},{"key":"format","value":"namespace"},{"key":"dsn_string","value":""},{"key":"table","value":""},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"}]},

"notify_nats":{"_":[{"key":"enable","value":"off"},{"key":"address","value":""},{"key":"subject","value":""},{"key":"username","value":""},{"key":"password","value":""},{"key":"token","value":""},{"key":"tls","value":"off"},{"key":"tls_skip_verify","value":"off"},{"key":"cert_authority","value":""},{"key":"client_cert","value":""},{"key":"client_key","value":""},{"key":"ping_interval","value":"0"},{"key":"streaming","value":"off"},{"key":"streaming_async","value":"off"},{"key":"streaming_max_pub_acks_in_flight","value":"0"},{"key":"streaming_cluster_id","value":""},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"}]},

"notify_nsq":{"_":[{"key":"enable","value":"off"},{"key":"nsqd_address","value":""},{"key":"topic","value":""},{"key":"tls","value":"off"},{"key":"tls_skip_verify","value":"off"},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"}]},

"notify_postgres":{"_":[{"key":"enable","value":"off"},{"key":"format","value":"namespace"},{"key":"connection_string","value":""},{"key":"table","value":""},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"}]},

"notify_redis":{"_":[{"key":"enable","value":"off"},{"key":"format","value":"namespace"},{"key":"address","value":""},{"key":"key","value":""},{"key":"password","value":""},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"}]},

"notify_webhook":{"_":[{"key":"enable","value":"off"},{"key":"endpoint","value":""},{"key":"auth_token","value":""},{"key":"queue_limit","value":"0"},{"key":"queue_dir","value":""}]},

"policy_opa":{"_":[{"key":"url","value":""},{"key":"auth_token","value":""}]},

"region":{"_":[{"key":"name","value":""}]},

"storage_class":{"_":null}}
`
