### ISSUE TITLE
Helm chart with specified access and secret keys

### ISSUE THREAD

**Issue by mtiller** [minio/minio#9820]
## Expected Behavior

If I run:

```helm install test-minio stable/minio -n minio-test --set "persistence.storageClass=local-storage,accessKey=verylongaccesskey,secretKey=verylongsecretkey"```

...I would expect `minio` to be able to use my specified access key and secret key.  But this fails.  I say I would expect it to work because if I just do this:

```helm install test-minio stable/minio -n minio-test --set "persistence.storageClass=local-storage```

It works just fine.

## Current Behavior

In the case where I specify an access key and a secret key, I get an error in the `minio` Pod:

```2020-06-12T14:16:21.246270885Z ERROR Unable to initialize server switching into safe-mode: Unable to initialize config system: Invalid credentials```

## Possible Solution

I don't know about any possible solutions.  But I can say that if I disable persistence, i.e.,

```helm install test-minio stable/minio -n minio-test --set "persistence.enabled=false,accessKey=verylongaccesskey,secretKey=verylongsecretkey"```

...it works fine.  So it clearly has something to do creating a PVC **and** trying to specify credentials.  But I don't see why that should be since the credentials are stored in a `Secret` and don't seem to have any connection to the PVC.

It is also worth mentioning that, as a work around, I tried to install the chart without specifying my own access key or secret key and then tried to change them in the `Secret`.  I can change them fine.  But they don't impact the running `Pod`.  But if I kill the `Pod`, it restarts and I see the same issue I see if I specify the secret key and access key during the initial install.  So it just does not like setting a different access key and secret key.

## Steps to Reproduce (for bugs)

Just run ```helm install test-minio stable/minio -n minio-test --set "persistence.storageClass=local-storage,accessKey=verylongaccesskey,secretKey=verylongsecretkey"```

It also fails if you set `persistence.existingClaim`, BTW.

## Context

I'm just trying to use Helm to provision a minio server.  I was hoping it would be an out of the box kind of thing.  I just assumed that setting non-default access and secret keys would be standard practice.  So I don't understand why I'm running into this.

## Regression

I don't know if this is regression, but this is chart version `5.0.27` and appVersion `master`.

## Your Environment

This is a bare metal cluster running Kubernetes 1.18.2.

**Comment by harshavardhana** [comment]
Rotating credentials is not allowed in our helm chart yet, you may need to manually do it for now by writing a full statefulset yaml @mtiller 

Because you already have a claim which was used previously with a different set of credentials,. Our backend config is encrypted so changing credentials requires setting two envs 

https://github.com/minio/minio/tree/master/docs/config#rotating-encryption-with-new-credentials

**Comment by mtiller** [comment]
Keep in mind, I'm not rotating it...I'm just setting it from the start.  Also, I discovered that if since I wasn't setting the `mode` parameter, I was running in `standalone` mode (which is pretty much what I want).  But I found that if I switched `mode` to `distributed`, then it actually works.

But I don't fully understand the implications of changing to `distributed` mode.  So I will investigate.  Any idea why it seems to work in `distributed` mode? (or does it...?  perhaps I just haven't encountered some underlying issues yet).

**Comment by harshavardhana** [comment]
> Keep in mind, I'm not rotating it...I'm just setting it from the start. Also, I discovered that if since I wasn't setting the `mode` parameter, I was running in `standalone` mode (which is pretty much what I want). But I found that if I switched `mode` to `distributed`, then it actually works.
> 
> But I don't fully understand the implications of changing to `distributed` mode. So I will investigate. Any idea why it seems to work in `distributed` mode? (or does it...? perhaps I just haven't encountered some underlying issues yet).

You are not rotating but you already have a claim which has data which was already encrypted with a different credentials.

**Comment by harshavardhana** [comment]
> helm install test-minio stable/minio -n minio-test --set "persistence.storageClass=local-storage

This works because the backend already is encrypted with default credentials `minioadmin:minioadmin`

**Comment by mtiller** [comment]
I'm really puzzled.  How can you use the Helm chart and use non-default credentials.  I feel like I'm missing something here.

**Comment by harshavardhana** [comment]
> I'm really puzzled. How can you use the Helm chart and use non-default credentials. I feel like I'm missing something here.

As I said rotation is not provided yet, you are not aware of that which is fully understandable - choose a different storageClass 

> helm install test-minio stable/minio -n minio-test --set "persistence.storageClass=new-storage,accessKey=verylongaccesskey,secretKey=verylongsecretkey"

Create a new `PV`

**Comment by Nilegfx** [comment]
I just faced the similar problem and this issue helped me indirectly with the hint of (data already encrypted, and create new PV) however, this is not straight forward and even not documented. 

it took me a couple of hours to reach this issue and those hours were an absolute waste of time. 

I would suggest adding more details about secrets and how the data is being encrypted in the helm readme

**another potential confusion**
a quick inspection to the helm templates shows that if `metrics.serviceMonitor.enabled` is `true` and you want to use `existingSecret` it still expects/uses `accessKey`, `secretkey` to construct [`MC_HOST_target`](https://github.com/helm/charts/blob/master/stable/minio/templates/post-install-prometheus-metrics-job.yaml#L57) env, which means, in that case (installing with `existingSecret` and `metrics.serviceMonitor.enabled`) you have to provide all three configs together (`existingSecret`,`accessKey`, and `secretkey`).

Not sure how the [`MC_HOST_target`](https://github.com/helm/charts/blob/master/stable/minio/templates/post-install-prometheus-metrics-job.yaml#L57) env is being used in context of minio, but if my hypothesis true, it would be also better to document this or change it to read from the same source (secret)

**Comment by Nilegfx** [comment]
I just faced a similar problem and this issue helped me indirectly with the hint of (data already encrypted, and create new PV) however, this is not straight forward and even not documented. 

it took me a couple of hours to reach this issue and those hours were an absolute waste of time. 

I would suggest adding more details about secrets and how the data is being encrypted in the helm readme

**another potential confusion**
a quick inspection to the helm templates shows that if `metrics.serviceMonitor.enabled` is `true` and you want to use `existingSecret` it still expects/uses `accessKey`, `secretkey` to construct [`MC_HOST_target`](https://github.com/helm/charts/blob/master/stable/minio/templates/post-install-prometheus-metrics-job.yaml#L57) env, which means, in that case (installing with `existingSecret` and `metrics.serviceMonitor.enabled`) you have to provide all three configs together (`existingSecret`,`accessKey`, and `secretkey`).

Not sure how the [`MC_HOST_target`](https://github.com/helm/charts/blob/master/stable/minio/templates/post-install-prometheus-metrics-job.yaml#L57) env is being used in the context of minio, but if my hypothesis true, it would be also better to document this or change it to read from the same source (secret)

**Comment by harshavardhana** [comment]
> I just faced a similar problem and this issue helped me indirectly with the hint of (data already encrypted, and create new PV) however, this is not straight forward and even not documented.
> 
> it took me a couple of hours to reach this issue and those hours were an absolute waste of time.
> 
> I would suggest adding more details about secrets and how the data is being encrypted in the helm readme
> 
> **another potential confusion**
> a quick inspection to the helm templates shows that if `metrics.serviceMonitor.enabled` is `true` and you want to use `existingSecret` it still expects/uses `accessKey`, `secretkey` to construct [`MC_HOST_target`](https://github.com/helm/charts/blob/master/stable/minio/templates/post-install-prometheus-metrics-job.yaml#L57) env, which means, in that case (installing with `existingSecret` and `metrics.serviceMonitor.enabled`) you have to provide all three configs together (`existingSecret`,`accessKey`, and `secretkey`).
> 
> Not sure how the [`MC_HOST_target`](https://github.com/helm/charts/blob/master/stable/minio/templates/post-install-prometheus-metrics-job.yaml#L57) env is being used in the context of minio, but if my hypothesis true, it would be also better to document this or change it to read from the same source (secret)

@Nilegfx it is already documented here https://github.com/minio/minio/tree/master/docs/config#rotating-encryption-with-new-credentials

It is not present in helm and in helm we do not support rotating the credentials yet.

**Comment by harshavardhana** [comment]
> Not sure how the [`MC_HOST_target`](https://github.com/helm/charts/blob/master/stable/minio/templates/post-install-prometheus-metrics-job.yaml#L57) env is being used in the context of minio, but if my hypothesis true, it would be also better to document this or change it to read from the same source (secret)

This is used for launching https://github.com/minio/mc

**Comment by mtiller** [comment]
@Nilegfx Glad it helped. I also eventually figured out my issue. The minio flies being stored in the PVC are all hidden. So it was not obvious what was getting left behind Between installs (it looked like nothing was).

I do agree with you on documentation, BTW. While it is true that several links were provided here with information, they were mere dots and more documentation is really needed to connect them and see the big picture.

In my case, it was extremely confusing that the Pod refers to environment variables for the credentials which in turn point to a secret and all of them were correct and yet I had invalid credentials.  This was ultimately because the credentials are ALSO stored in the PVC (which while surely necessary for some reason, was very unintuitive) and it wasn’t immediately obvious that this was true or where they were because of the hidden dot-files.

I guess I looked for a Helm chart because I thought that would be an easy way to install minio vs. just constructing my own deployment. Now that I’ve figured things out, it will definitely be easier in the future, but it was definitely a long day today.

**Comment by harshavardhana** [comment]
@nitisht ^^ about rotating keys

**Comment by Nilegfx** [comment]
> > Not sure how the [`MC_HOST_target`](https://github.com/helm/charts/blob/master/stable/minio/templates/post-install-prometheus-metrics-job.yaml?rgh-link-date=2020-06-13T00%3A58%3A28Z#L57) env is being used in the context of minio, but if my hypothesis true, it would be also better to document this or change it to read from the same source (secret)
> 
> This is used for launching https://github.com/minio/mc

@harshavardhana thanks for your answer, however, it still didn't clarify the confusion nor acknowledging it.
