### ISSUE TITLE
[resolved] ETag computes differently each MultipartUpload

### ISSUE THREAD

**Issue by andemi** [minio/minio#9822]
When upload the same file by REQUEST s3.NewMultipartUpload minio computes every time different ETag.

## Expected Behavior

ETag should be identical as it works when works with aws cli.

## Current Behavior

Response of the "REQUEST s3.PutObjectPart" computes different ETags

## Steps to Reproduce (for bugs)

1. Create MultipartUpload request
2. Upload 1 or more parts
3. Make additional MultipartUpload with the same file and commands

## Context

Trying do not write the same file if ETags are identical

## Your Environment

* Version used (`minio version`):
    Version    2020-03-25T07:03:04Z
* Environment name and version (e.g. nginx 1.9.1):
  Runtime Version: go1.13.8 | CPUs: 8
* Server type and version:
    Docker
* Operating System and version (`uname -a`):
    Platform
    Host: 7e7545fbd361 | OS: linux | Arch: amd64

* Link to your project:

**Comment by harshavardhana** [comment]
> * Version    2020-03-25T07:03:04Z
> *

Use the latest version we moved away from this model @andemi already fixed 

```
commit 7d636a7c139b51267b3f6e85804bf7ee8fb494a6
Author: Harshavardhana <harsha@minio.io>
Date:   Sun Apr 12 18:08:27 2020 -0700

    enable --compat flag by default (#9326)
    
    if needed use --no-compat to disable md5sum while
    verifying any performance numbers.
    
    bring back --compat behavior as default to avoid
    additional documentation and confusing behavior,
    as we are working towards improving md5sum to
    be faster on AVX instructions, enabling this
    should be hardly a problem in future versions
    of MinIO.
    
    fixes #8012
    fixes #7859
    fixes #7642
```

**Comment by andemi** [comment]
Hello @harshavardhana!
I've updated minio to this version 2020-06-12T00:06:19Z
and ETag for 1 part file is the same, but for big file like 18 parts its not!

**Comment by harshavardhana** [comment]
> and ETag for 1 part file is the same, but for big file like 18 parts its not!

It will not be same @andemi https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html 

> When you complete a multipart upload, Amazon S3 creates an object by concatenating the parts in ascending order based on the part number. If any object metadata was provided in the initiate multipart upload request, Amazon S3 associates that metadata with the object. After a successful complete request, the parts no longer exist. Your complete multipart upload request must include the upload ID and a list of both part numbers and corresponding ETag values. Amazon S3 response includes an ETag that uniquely identifies the combined object data. This ETag will not necessarily be an MD5 hash of the object data. You can optionally abort the multipart upload. After aborting a multipart upload, you cannot upload any part using that upload ID again. All storage that any parts from the aborted multipart upload consumed is then freed. If any part uploads were in-progress, they can still succeed or fail even after you aborted. To free all storage consumed by all parts, you must abort a multipart upload only after all part uploads have completed.
