### ISSUE TITLE
[wontfix] Cashed pipes from minio storage to host

### ISSUE THREAD

**Issue by itzsimpl** [minio/minio#9826]
My use case is to use minio as a data storage. I would use parts of this data (not entire buckets, or subfolders, only some files from those and not always the same ones). The software that I use is limited to POSIX io. The mc client supports piping data from host to minio storage, but not in the other direction. 

My feature request would be to provide piping from minio storage as well. If you add to that a possibility to provide a caching drive, where data would be stored locally and retrieved in case of reuse pending it has not changed in minio storage, that would be a killer feature for my use case. I have looked at ways of mounting minio as a posix drive, but all solutions seem to be either overkill or have unsatisfactory performance. Another option would be to have mc mirror, perform two ways selective synching in background, but that's for another feature request.

**Comment by harshavardhana** [comment]
@itzsimpl we implement S3 API and do not plan to break this anytime in future.

If any special work is needed you would need to come onboard as a customer to influence these decisions if you must which are then delivered as part of the stack.

S3 API is the bounds where we would work under, so unfortunately this feature request is out of scope.
