### ISSUE TITLE
Copy fails for files larger than 2GB

### ISSUE THREAD

**Issue by SoftBoil** [minio/minio#9827]
I'm testing copying to my MinIO Server with 3 different video files: 1 GB, 2 GB, and 3GB.  The smaller files complete copying but the 3 GB file fails with error. I get the same error from different files greater than 2 GB.

## Expected Behavior
Successful transfer with: "mc cp --debug test3G.mp4 myminio/test"

## Current Behavior
At some varying point after 2GB the copy fails with the error:

mc: <ERROR> Failed to copy `test3G.mp4`. A timeout occurred while trying to lock a resource, please reduce your request rate
 (3) cp-main.go:562 cmd.doCopySession(..) Tags: [test3G.mp4]
 (2) common-methods.go:525 cmd.uploadSourceToTargetURL(..) Tags: [test3G.mp4]
 (1) common-methods.go:317 cmd.putTargetStream(..) Tags: [myminio, https://**REDACTED**:9000/test/test3G.mp4]
 (0) client-s3.go:1034 cmd.(*S3Client).Put(..)
 Release-Tag:RELEASE.2020-05-28T23-43-36Z | Commit:2403e7a7441b | Host:**REDACTED** | OS:darwin | Arch:amd64 | Lang:go1.13.10 | Mem:651 MB/2.4 GB | Heap:651 MB/2.3 GB

## Regression
No

## Your Environment
Client: 
  version RELEASE.2020-05-28T23-43-36Z
Server:
   Version: 2020-06-12T00:06:19Z
   Network: 1/1 OK 
   Drives: 4/4 OK

**Comment by harshavardhana** [comment]
> I'm testing copying to my MinIO Server with 3 different video files: 1 GB, 2 GB, and 3GB. The smaller files complete copying but the 3 GB file fails with error. I get the same error from different files greater than 2 GB.
> 
> ## Expected Behavior
> Successful transfer with: "mc cp --debug test3G.mp4 myminio/test"
> 
> ## Current Behavior
> At some varying point after 2GB the copy fails with the error:
> 
> mc: Failed to copy `test3G.mp4`. A timeout occurred while trying to lock a resource, please reduce your request rate
> (3) cp-main.go:562 cmd.doCopySession(..) Tags: [test3G.mp4]
> (2) common-methods.go:525 cmd.uploadSourceToTargetURL(..) Tags: [test3G.mp4]
> (1) common-methods.go:317 cmd.putTargetStream(..) Tags: [myminio, https://**REDACTED**:9000/test/test3G.mp4]
> (0) client-s3.go:1034 cmd.(*S3Client).Put(..)
> Release-Tag:RELEASE.2020-05-28T23-43-36Z | Commit:2403e7a7441b | Host:**REDACTED** | OS:darwin | Arch:amd64 | Lang:go1.13.10 | Mem:651 MB/2.4 GB | Heap:651 MB/2.3 GB
> 
> ## Regression
> No
> 
> ## Your Environment
> Client:
> version RELEASE.2020-05-28T23-43-36Z
> Server:
> Version: 2020-06-12T00:06:19Z
> Network: 1/1 OK
> Drives: 4/4 OK

@SoftBoil upgrade to latest and let us know if you see the same issue.

**Comment by SoftBoil** [comment]
@harshavardhana I updated both the client and server earlier.  I have the latest versions according to: 
https://github.com/minio/minio/releases and https://github.com/minio/mc/releases

Is there a different version that I should try?

**Comment by harshavardhana** [comment]
> @harshavardhana I updated both the client and server earlier.  I have the latest versions according to: 
> https://github.com/minio/minio/releases and https://github.com/minio/mc/releases
> 
> Is there a different version that I should try?

Looks like an issue with mc can you update to latest master ?

**Comment by harshavardhana** [comment]
> > @harshavardhana I updated both the client and server earlier.  I have the latest versions according to: 
> > https://github.com/minio/minio/releases and https://github.com/minio/mc/releases
> > 
> > Is there a different version that I should try?
> 
> Looks like an issue with mc can you update to latest master ? 

Is this reproducible all the time @SoftBoil ?

**Comment by harshavardhana** [comment]
> > > @harshavardhana I updated both the client and server earlier.  I have the latest versions according to: 
> > > https://github.com/minio/minio/releases and https://github.com/minio/mc/releases
> > > 
> > > Is there a different version that I should try?
> > 
> > Looks like an issue with mc can you update to latest master ? 
> 
> Is this reproducible all the time @SoftBoil ?

Can you share the entire --debug log?

**Comment by SoftBoil** [comment]
> Looks like an issue with mc can you update to latest master ?

I'll attempt to compile from master.  I haven't compiled with go before so it might take a while.

**Comment by SoftBoil** [comment]
> Is this reproducible all the time @SoftBoil ?

Yes, it fails every time I try to copy.  But the exact progress point that it fails varies.  For example over 4 attempts the last progress is:
1) 3.05 GiB / 3.15 GiB
2) 2.14 GiB / 3.15 GiB
3) 2.39 GiB / 3.15 GiB
4) 2.14 GiB / 3.15 GiB

**Comment by SoftBoil** [comment]
> Can you share the entire --debug log?

Sure, I'll attach the debug output.
[debug.txt](https://github.com/minio/minio/files/4775614/debug.txt)

**Comment by SoftBoil** [comment]
@harshavardhana I built mc from the master branch but got the same error.

Release-Tag:DEVELOPMENT.GOGET | Commit:DEVELOPMENT. | Host:REDACTED | OS:darwin | Arch:amd64 | Lang:go1.14.3 | Mem:464 MB/2.1 GB | Heap:464 MB/2.0 GB

**Comment by harshavardhana** [comment]
Thanks will investigate looks like a regression @SoftBoil

**Comment by harshavardhana** [comment]
> Client:
> version RELEASE.2020-05-28T23-43-36Z
> Server:
> Version: 2020-06-12T00:06:19Z
> Network: 1/1 OK
> Drives: 4/4 OK

is this setup do you have 4 separate drives? @SoftBoil

**Comment by harshavardhana** [comment]
> > Client:
> > version RELEASE.2020-05-28T23-43-36Z
> > Server:
> > Version: 2020-06-12T00:06:19Z
> > Network: 1/1 OK
> > Drives: 4/4 OK
> 
> is this setup do you have 4 separate drives? @SoftBoil

I was able to upload fine 

```
~ mc cp 4g.file myminio/testbucket
4g.file:                     4.00 GiB / 4.00 GiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 74.22 MiB/s 55s
```

And I don't even have 4 separate drives

```
~ minio server export{1..4}
Formatting 1st zone, 1 set(s), 4 drives per set.
```

```
~ mc admin info myminio
●  localhost:9000
   Uptime: 2 minutes 
   Version: 2020-06-13T23:09:51Z
   Network: 1/1 OK 
   Drives: 4/4 OK 

4 drives online, 0 drives offline
```

**Comment by SoftBoil** [comment]
> is this setup do you have 4 separate drives? @SoftBoil

Yes, 2 SSD and 2 HDD on the same host.

**Comment by harshavardhana** [comment]
> Yes, 2 SSD and 2 HDD on the same host.

don't have such disparate setups. use homogenous setups to expect consistent behavior in performance.

**Comment by SoftBoil** [comment]
> don't have such disparate setups. use homogenous setups to expect consistent behavior in performance.

I understand that it is not ideal.  Would you consider this an unsupported scenario? Or is there a way to compensate, maybe "reduce your request rate" as the error message suggests?

**Comment by harshavardhana** [comment]
> > don't have such disparate setups. use homogenous setups to expect consistent behavior in performance.
> 
> I understand that it is not ideal. Would you consider this an unsupported scenario? Or is there a way to compensate, maybe "reduce your request rate" as the error message suggests?

I think I found the issue its not related to your config, will be sending a fix @SoftBoil

**Comment by SoftBoil** [comment]
> I think I found the issue its not related to your config, will be sending a fix @SoftBoil

Thank you. I would be happy to test it.

**Comment by imclaren** [comment]
I am also seeing this bug.  I am using 4 identical drives using erasure code mode.  Thanks.

**Comment by harshavardhana** [comment]
> > I think I found the issue its not related to your config, will be sending a fix @SoftBoil
> 
> Thank you. I would be happy to test it.

The bug is fixed please don't use master branch yet, because you won't be able to revert back to older releases from that.

Will push this fix to release branch where you can build and test locally.

**Comment by harshavardhana** [comment]
> > > I think I found the issue its not related to your config, will be sending a fix @SoftBoil
> > 
> > 
> > Thank you. I would be happy to test it.
> 
> The bug is fixed please don't use master branch yet, because you won't be able to revert back to older releases from that.
> 
> Will push this fix to release branch where you can build and test locally.

No need we made a release anyways..

**Comment by findmyname666** [comment]
Hi @harshavardhana , I expected this issue today. I tried to upload file of size **197GB**. 
```
# ./mc cp /logs/2019/06/21/data.gz backup-minio/logs/2019/06/21/
mc: <ERROR> Failed to copy `/logs/2019/06/21/data.gz`. A timeout occurred while trying 
to lock a resource
````
MinIO runs in distributed mode e.g. 4 nodes with 4 HDD.
MC version:
```
# ./mc -v
mc version RELEASE.2020-06-20T00-18-43Z
```
Upload with Golang LIB finished successfully.
```
    // Upload the log file
    bucketName := "logs"
    objectName := "2019/06/21/data.gz"
    filePath := "/logs/2019/06/21/data.gz"
    contentType := "application/text"
    contentEncoding := "gzip"

    // Upload the file with PutObject
    n, err := minioClient.FPutObject(bucketName, objectName, filePath, minio.PutObjectOptions{ContentType:contentType, ContentEncoding:contentEncoding})
    if err != nil {
        log.Fatalln(err)
    }

    log.Printf("Successfully uploaded %s of size %d\n", objectName, n)
```
Output
```
2020/06/20 23:21:53 Successfully uploaded 2019/06/21/data.gz of size 211035114264
```

**Comment by harshavardhana** [comment]
> Hi @harshavardhana , I expected this issue today. I tried to upload file of size **197GB**. 
> ```
> # ./mc cp /logs/2019/06/21/data.gz backup-minio/logs/2019/06/21/
> mc: <ERROR> Failed to copy `/logs/2019/06/21/data.gz`. A timeout occurred while trying 
> to lock a resource
> ````
> MinIO runs in distributed mode e.g. 4 nodes with 4 HDD.
> MC version:
> ```
> # ./mc -v
> mc version RELEASE.2020-06-20T00-18-43Z
> ```
> Upload with Golang LIB finished successfully.
> ```
>     // Upload the log file
>     bucketName := "logs"
>     objectName := "2019/06/21/data.gz"
>     filePath := "/logs/2019/06/21/data.gz"
>     contentType := "application/text"
>     contentEncoding := "gzip"
> 
>     // Upload the file with PutObject
>     n, err := minioClient.FPutObject(bucketName, objectName, filePath, minio.PutObjectOptions{ContentType:contentType, ContentEncoding:contentEncoding})
>     if err != nil {
>         log.Fatalln(err)
>     }
> 
>     log.Printf("Successfully uploaded %s of size %d\n", objectName, n)
> ```
> Output
> ```
> 2020/06/20 23:21:53 Successfully uploaded 2019/06/21/data.gz of size 211035114264
> ```
> 

Use the latest server version @findmyname666

**Comment by findmyname666** [comment]
> Use the latest server version @findmyname666

Cool it resolved the issue.
