### ISSUE TITLE
[not our bug] Unable to read 'format.json' from.....EOF when trying to start Minio in distributed mode

### ISSUE THREAD

**Issue by jankyjames** [minio/minio#9830]
## Expected Behavior
When I run ./minio server http://hdd{1...2}.mydomain.com/hdd{1...2}/minio-data I expect it to say "Waiting for a minimum of 2 disks to come online (elapsed 1s)" (Like my other node does, port forward is correct on both networks, testing with nmap while waiting). 

## Current Behavior
I get a wall of errors, as well as the "Waiting for a minimum of 2 disks to come online (elapsed 1s)"

<pre><code>API: SYSTEM()
Time: 01:26:01 UTC 06/15/2020
Error: http: panic serving 192.168.88.1:58708: runtime error: invalid memory address or nil pointer dereference
       1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()

API: SYSTEM()
Time: 01:26:01 UTC 06/15/2020
Error: goroutine 299 [running]:
       1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()

API: SYSTEM()
Time: 01:26:01 UTC 06/15/2020
Error: net/http.(*conn).serve.func1(0xc00082e280)
       1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()

API: SYSTEM()
Time: 01:26:01 UTC 06/15/2020
Error: 	net/http/server.go:1767 +0x139
       1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()

...

API: SYSTEM()
Time: 01:26:01 UTC 06/15/2020
Error: 	net/http/server.go:1890 +0x875
       1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()

API: SYSTEM()
Time: 01:26:01 UTC 06/15/2020
Error: created by net/http.(*Server).Serve
       1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()

API: SYSTEM()
Time: 01:26:01 UTC 06/15/2020
Error: 	net/http/server.go:2928 +0x384
       1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
Unable to read 'format.json' from http://hdd1.mydomain.com:9000/hdd1/minio-data: Post http://hdd1.mydomain.com:9000/minio/storage/hdd1/minio-data/v17/readall?disk-id=&file-path=format.json&volume=.minio.sys: EOF

Unable to read 'format.json' from http://hdd1.mydomain.com:9000/hdd2/minio-data: Post http://hdd1.mydomain.com:9000/minio/storage/hdd2/minio-data/v17/readall?disk-id=&file-path=format.json&volume=.minio.sys: EOF

Waiting for a minimum of 2 disks to come online (elapsed 4s)</code></pre>

## Steps to Reproduce (for bugs)
1. Not sure unfortunately. I tested it from my other node and it doesn't throw errors.
2.
3.
4.

## Your Environment
FRESH installation of Ubuntu 20.04 on both machines, firewall off. Port forwarded. I can nmap the ip/port of the failing machine while its erroring and the port shows open. Trying to connect appears to work but It causes both machines to then constantly throw errors.

* Version used (`minio version`): Latest
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: Ubuntu 20.04
* Operating System and version (`uname -a`): Linux jankynode1 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by harshavardhana** [comment]
@JankyGaming this doesn't make sense, can you state which version are you running? specifically 

`minio --version`

**Comment by jankyjames** [comment]
> @JankyGaming this doesn't make sense, can you state which version are you running? specifically
> 
> `minio --version`

minio version RELEASE.2020-06-14T18-32-17Z

**Comment by jankyjames** [comment]
I suspect that it might have something to do with my router in hindsight because it looks like 0 packets have gone through port 9000 since the port forward despite being able to nmap the port when the server is waiting

**Comment by harshavardhana** [comment]
> minio version RELEASE.2020-06-14T18-32-17Z

Are you sure your networking everything is fine? @JankyGaming 

A simple setup seems to be working fine are you sure your networking is all in place? try a fresh setup by deleting everything on the backend drives? 

```
 ~/run-dist.sh
+ endpoints=
+ for i in {02..05}
+ endpoints=' http://localhost:9002/tmp/02'
+ for i in {02..05}
+ endpoints=' http://localhost:9002/tmp/02 http://localhost:9003/tmp/03'
+ for i in {02..05}
+ endpoints=' http://localhost:9002/tmp/02 http://localhost:9003/tmp/03 http://localhost:9004/tmp/04'
+ for i in {02..05}
+ endpoints=' http://localhost:9002/tmp/02 http://localhost:9003/tmp/03 http://localhost:9004/tmp/04 http://localhost:9005/tmp/05'
+ for i in {02..05}
+ for i in {02..05}
+ for i in {02..05}
+ for i in {02..05}
+ minio server --address :9002 http://localhost:9002/tmp/02 http://localhost:9003/tmp/03 http://localhost:9004/tmp/04 http://localhost:9005/tmp/05
+ minio server --address :9003 http://localhost:9002/tmp/02 http://localhost:9003/tmp/03 http://localhost:9004/tmp/04 http://localhost:9005/tmp/05
+ minio server --address :9004 http://localhost:9002/tmp/02 http://localhost:9003/tmp/03 http://localhost:9004/tmp/04 http://localhost:9005/tmp/05
+ minio server --address :9005 http://localhost:9002/tmp/02 http://localhost:9003/tmp/03 http://localhost:9004/tmp/04 http://localhost:9005/tmp/05
```

```
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Formatting 1st zone, 1 set(s), 4 drives per set.
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Attempting encryption of all config, IAM users and policies on MinIO backend
Configuration file config/config.json migrated from version '28' to '29' successfully.
Configuration file config/config.json migrated from version '29' to '30' successfully.
Configuration file config/config.json migrated from version '30' to '31' successfully.
Configuration file config/config.json migrated from version '31' to '32' successfully.
Configuration file config/config.json migrated from version '32' to '33' successfully.
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Configuration file config/config.json migrated from version '33' to new KV format successfully.
All MinIO sub-systems initialized successfully
Waiting for all MinIO IAM sub-system to be initialized.. lock acquired
Status:         4 Online, 0 Offline. 
Endpoint:  http://10.0.0.67:9002  http://172.17.0.1:9002  http://172.18.0.1:9002  http://127.0.0.1:9002      
AccessKey: minio 
SecretKey: minio123 
Region:    us-east-1

Browser Access:
   http://10.0.0.67:9002  http://172.17.0.1:9002  http://172.18.0.1:9002  http://127.0.0.1:9002      

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://10.0.0.67:9002 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
```

**Comment by harshavardhana** [comment]
> I suspect that it might have something to do with my router in hindsight because it looks like 0 packets have gone through port 9000 since the port forward despite being able to nmap the port when the server is waiting

are you trying to set this one up behind a NAT to another NAT?

**Comment by jankyjames** [comment]
Im not 100% sure what you mean by "to another NAT". I have a Mikrotik router with a dst-nat routing traffic on port 9000 to my local machine on port 9000. I also have a "hairpin nat" fix set up which I can elaborate on if it seems necessary.

Just to clarify, I can successfully nmap port 9000 from inside AND outside of my network and get "open" when minio is waiting for drives, despite throwing the wall of errors.

**Comment by harshavardhana** [comment]
> Im not 100% sure what you mean by "to another NAT". I have a Mikrotik router with a dst-nat routing traffic on port 9000 to my local machine on port 9000. I also have a "hairpin nat" fix set up which I can elaborate on if it seems necessary.
> 
> Just to clarify, I can successfully nmap port 9000 from inside AND outside of my network and get "open" when minio is waiting for drives, despite throwing the wall of errors.

AFAICS there is some networking setup issue on your end - I can deploy easily deploy a 10 node setup on local k8s cluster. There is nothing we can do, you may fix your networking problems first. 

Make sure all TCP traffic can go through and also preferably use the distributed setup on the same subnet, distributed MinIO is not designed or tested to work across high latency networks.

**Comment by jankyjames** [comment]
@harshavardhana I have fixed my networking issues (verified by seeing traffic routed in my router, and also by starting single drive non-distributed servers and navigating to the domain.com:9000 and seeing the minio ui and tested upload and download) and I am still getting this error, except now the error is more balanced. Each side of the cluster seems to fail with

`Unable to read 'format.json' from http://hdd{1 or 2}.mydomain.com:9000/hdd2/minio-data: Post http://hdd{1 or 2}.mydomain.com:9000/minio/storage/hdd2/minio-data/v17/readall?disk-id=&file-path=format.json&volume=.minio.sys: EOF`

I am also still getting a wall of errors that seems to start and end with 

`API: SYSTEM()
Time: 13:02:24 UTC 06/18/2020
Error: http: panic serving XXX.XXX.XXX.XXX:59080: runtime error: invalid memory address or nil pointer dereference
       1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()

...

API: SYSTEM()
Time: 13:02:23 UTC 06/18/2020
Error: 	net/http/server.go:2928 +0x384
       1: github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()`

**Comment by goshander** [comment]
Same issue, minio version  RELEASE.2020-07-31T03-39-05Z in docker

Two hosts in others regions, I thought, that I can connect it together. But same error in all cases, even if I use proxy tcp connection to remote host.

It is very strange. When you use multiple hosts in one docker instance all works fine.

I drop this case, after a week trying

Same issues in Slack chat and gitter chat, but no answer, ever

**Comment by harshavardhana** [comment]
> Same issue, minio version RELEASE.2020-07-31T03-39-05Z in docker
> 
> Two hosts in others regions, I thought, that I can connect it together. But same error in all cases, even if I use proxy tcp connection to remote host.
> 
> It is very strange. When you use multiple hosts in one docker instance all works fine.
> 
> I drop this case, after a week trying
> 
> Same issues in Slack chat and gitter chat, but no answer, ever

@Dynan7 distributed setup is not designed for cross regions without low latency interconnect. You cannot expect it work for geo erasure coding use cases.
