### ISSUE TITLE
Update/Correct error messages in Minio Web-client

### ISSUE THREAD

**Issue by damikun** [minio/minio#9832]
Currently if you try to create new bucket under minio server web-client  with some uppercase you will get not correct error response message:

Bucket name: Images (Incorrect because has Upper "I") but error message says nothing about the problem:

![image](https://user-images.githubusercontent.com/54806834/84635067-fdb46c80-aef2-11ea-8709-8c585e33260a.png)

If you try to use some special character (example: "images/ ) inside name you will get good message saying what is possible the problem:

![Capture2](https://user-images.githubusercontent.com/54806834/84635412-787d8780-aef3-11ea-8c31-800d041a3ebb.PNG)

**Recomedation:**

Keep error messages same or correct first example to show that name must be lowercase..

**Comment by harshavardhana** [comment]
@damikun please fix your referenced PR appropriately - we are happy to take the change.

**Comment by bensodenkamp** [comment]
So, reviewing the code here, it looks like bucket names get checked against general minio requirements as well as requirements specific to the back end. @harshavardhana, would it be correct to assume that minio always wants bucket names to be compliant to S3 standards even if the back end is not S3?

**Comment by harshavardhana** [comment]
> So, reviewing the code here, it looks like bucket names get checked against general minio requirements as well as requirements specific to the back end. @harshavardhana, would it be correct to assume that minio always wants bucket names to be compliant to S3 standards even if the back end is not S3?

yes @bensodenkamp
