### ISSUE TITLE
Excessive memory allocations on ListObjects

### ISSUE THREAD

**Issue by klauspost** [minio/minio#9835]
On `RELEASE.2020-06-03T22-13-49Z`

## Expected Behavior

Server uses a reasonable amount for ListObject calls.

## Current Behavior

Server Uses 27GB of RAM for ListObjects calls.

![image](https://user-images.githubusercontent.com/5663952/84663008-6ee32800-aed1-11ea-96d6-8d400be981f5.png)

## Steps to Reproduce (for bugs)

Memory trace supplied.

## Context

Investigate if we can make this scale better.

## Regression

Yes - likely #9697

**Comment by harshavardhana** [comment]
@klauspost the PR referenced is not the regression it is perhaps the higher dentry memory pool that we use now .

Are you using Linux or Windows?

**Comment by klauspost** [comment]
Linux. It is not me, but reported here: https://minio.slack.com/archives/C3NDUB8UA/p1592209733069700

**Comment by klauspost** [comment]
@harshavardhana The PR linked makes it 5x worse, so that is at least part of the problem.

**Comment by harshavardhana** [comment]
This is fixed @klauspost ?

**Comment by klauspost** [comment]
Yeah. Dunno why it wasn't picked up by github.

**Comment by isshwar** [comment]
Hi,

may I know if this has been released.? i dont see the change in any of the recently released versions.

**Comment by klauspost** [comment]
It is merged to master which is unreleased since it has versioning changes that we are currently testing.

Changes for releases are cherrypicked and is only critical changes.
