### ISSUE TITLE
Ability to log into MinIO GUI with LDAP Credentials

### ISSUE THREAD

**Issue by jdheyburn** [minio/minio#9837]
**Is your feature request related to a problem? Please describe.**
Given a MinIO server has been correctly configured with LDAP for identity authentication, users should be able to log into the GUI using their LDAP credentials. This allows for SSO for MinIO for users.

**Describe the solution you'd like**
On MinIO GUI, users enter their LDAP/AD username in the Access Key field, followed by their password in the secret key field.

MinIO then makes a call to LDAP to verify the users credentials. 

The rest of the flow can be done with what is already implemented (get user groups, load assets available given user permissions, etc).

**Describe alternatives you've considered**
We believed we would be able to use the temporary credentials obtained from STS, however this does not look to work - see issue #9836.

**Additional context**
If this feature already exists then please let me know.

**Comment by harshavardhana** [comment]
> **Is your feature request related to a problem? Please describe.**
> Given a MinIO server has been correctly configured with LDAP for identity authentication, users should be able to log into the GUI using their LDAP credentials. This allows for SSO for MinIO for users.
> 
> **Describe the solution you'd like**
> On MinIO GUI, users enter their LDAP/AD username in the Access Key field, followed by their password in the secret key field.
> 
> MinIO then makes a call to LDAP to verify the users credentials.
> 
> The rest of the flow can be done with what is already implemented (get user groups, load assets available given user permissions, etc).
> 
> **Describe alternatives you've considered**
> We believed we would be able to use the temporary credentials obtained from STS, however this does not look to work - see issue #9836.
> 
> **Additional context**
> If this feature already exists then please let me know.

This is on purpose avoided you should look at our 

 https://github.com/minio/mcs

This shall primarily replace all the UI related functionality, PTAL.

**Comment by harshavardhana** [comment]
This functionality is slated to move to mcs closing here.

**Comment by rbs-cloud** [comment]
Hello,

I need to setup LDAP details like username and password in minio in kubernets cluster, i have seen below information but could not get ,how to to setup and where to setup and after setup, where to check if ldap details are set or not.
export MINIO_IDENTITY_LDAP_SERVER_ADDR=myldapserver.com:636
export MINIO_IDENTITY_LDAP_USERNAME_FORMAT="uid=%s,cn=accounts,dc=myldapserver,dc=com"
export MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN="dc=myldapserver,dc=com"
export MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER="(&(objectclass=groupOfNames)(memberUid=%s)$)"
export MINIO_IDENTITY_LDAP_STS_EXPIRY=60h
export MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=on

https://github.com/minio/minio/blob/master/docs/sts/ldap.md--- could not help me much.
