### ISSUE TITLE
ISO 8601 format not accepted

### ISSUE THREAD

**Issue by stefanfritsch** [minio/minio#9838]
If you provide the date header in a PUT request to minio in ISO-8601 format you get the error:

```Invalid date format header, expected to be in ISO8601, RFC1123 or RFC1123Z time format.```

## Expected Behavior

Either you support ISO datetimes or you return an error that specifies that ISO datetimes are not supported.

## Steps to Reproduce (for bugs)

Use the following script and fill in the variables at the top:

```
#!/bin/bash

date=`date -Iseconds`
bucket=mybucket
file=somefile.txt
host=minio.example.com
s3_key=''
s3_secret=''

resource="/${bucket}/${file}"
content_type="application/octet-stream"
presignature="PUT\n\n${content_type}\n${date}\n${resource}"
signature=`echo -en ${presignature} | openssl sha1 -hmac ${s3_secret} -binary | base64`

curl -v -X PUT -T "${file}" \
          -H "Host: $host" \
          -H "Date: ${date}" \
          -H "Content-Type: ${content_type}" \
          -H "Authorization: AWS ${s3_key}:${signature}" \
          https://$host${resource}
```

```
minio-upload.sh
```

fails with 

```
<Error><Code>MalformedDate</Code><Message>Invalid date format header, expected to be in ISO8601, RFC1123 or RFC1123Z time format.</Message><Resource>/projekte/minio-upload.sh</Resource><RequestId></RequestId><HostId></HostId></Error>
```

Now change `date -Iseconds` to `date -R` and it works.

## Context

In many contexts generating ISO datetimes is a lot easier than getting locale independent versions of weekdays and month abbreviations. It is also in my experience the most common way to store timestamps in databases and data files, often as text and not a real timestamp.

It would be really nice if minio supported ISO timestamps.

## Your Environment

* Version used (`minio version`): DEVELOPMENT.GOGET
* Environment name and version (e.g. nginx 1.9.1): go1.14.4
* Server type and version: ?
* Operating System and version (`uname -a`): `Linux 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 GNU/Linux`

Thanks very much
Stefan

**Comment by harshavardhana** [comment]
> In many contexts generating ISO datetimes is a lot easier than getting locale independent versions of weekdays and month abbreviations. It is also in my experience the most common way to store timestamps in databases and data files, often as text and not a real timestamp.
> 
> It would be really nice if minio supported ISO timestamps.

We support what AWS S3 supports @stefanfritsch cannot support time formats beyond that.

**Comment by stefanfritsch** [comment]
@harshavardhana it's not working as intended if the error message is blatantly wrong.
