### ISSUE TITLE
"Invalid argument" errors due to setrlimit calls on macOS

### ISSUE THREAD

**Issue by jtolio** [minio/minio#9855]
Hello!

When using MinIO on macOS, we frequently see log lines that look like the following:

```
API: SYSTEM()
Time: <time>
Error: invalid argument
1: /Users/user/go/pkg/mod/github.com/minio/minio@v0.0.0-20180508161510-54cd29b51c38/cmd/gateway-main.go:166:cmd.StartGateway()
```

These are ignorable and everything seems to work, but still annoying. After a bunch of debugging, we tracked this down to how MinIO is trying to increase rlimits in https://github.com/minio/minio/blob/release/cmd/server-rlimit.go#L25-L55, and in https://github.com/minio/minio/tree/release/pkg/sys

There is an open Go bug about how the Go syscall for getting the max limit is lying. https://github.com/golang/go/issues/30401 This changed between Go releases on macOS, and we believe MinIO is hitting this bug.

Would it be useful to push up a code review to fix this? I think the solution is to extend github.com/minio/minio/pkg/sys to have special darwin-specific handling for not letting the max limit above 10240, as described in the Go issue.

## Expected Behavior
No inscrutable logs about invalid arguments while MinIO starts and tries to set limits.

## Current Behavior
MinIO logs "invalid argument" on macOS

## Possible Solution
Extend github.com/minio/minio/pkg/sys to specifically not allow the max limit above 10240, as described in the Go issue about this (Go's syscall behavior on Darwin changed): https://github.com/golang/go/issues/30401

## Steps to Reproduce (for bugs)
1. Run on macOS, look at logs

## Regression
This is a problem introduced by changing Go standard libraries.

## Your Environment

* Version used (`minio version`): latest
* Environment name and version (e.g. nginx 1.9.1): Go 1.14
* Server type and version: Mac Mini
* Operating System and version (`uname -a`): macOS High Sierra
* Link to your project: https://www.storj.io :wave: 

Thanks so much!

**Comment by harshavardhana** [comment]
> API: SYSTEM()
> Time: <time>
> Error: invalid argument
> 1: /Users/user/go/pkg/mod/github.com/minio/minio@v0.0.0-20180508161510-54cd29b51c38/cmd/gateway-main.go:166:cmd.StartGateway()

This log has been removed from server code, we shall remove from gateway as well. It's not meaningful to print this error.

**Comment by jtolio** [comment]
removing the log doesn't fix the problem though - the purpose of setMaxResources is to actually setMaxResources, and because get_rlimit returns values that set_rlimit won't work with on macOS in Go - setMaxResources is not actually setting max resources.

Shouldn't the fix here be to make it so the call to set_rlimit is valid?

**Comment by jtolio** [comment]
here's an example fix:

```golang
	if runtime.GOOS == "darwin" && set.Cur > 10240 {
		// The max file limit is 10240, even though
		// the max returned by Getrlimit is 1<<63-1.
		// This is OPEN_MAX in sys/syslimits.h.
		set.Cur = 10240
	}
```
