### ISSUE TITLE
"Invalid argument" errors due to setrlimit calls on macOS 

### ISSUE THREAD

**Issue by jtolio** [minio/minio#9857]
I'd like to reopen #9855, as I don't believe the fix provided is actually solving the real problem. The real problem is setMaxResources doesn't work on macOS.

**Comment by harshavardhana** [comment]
If it's not allowed it inherits what is maximum for the user. This what we can do best, we can't set to arbitrary high value if it's not possible.

**Comment by jtolio** [comment]
Thanks!
