### ISSUE TITLE
[faq] Object-prefix is already an object, AWS S3 supports but MinIO doesn't

### ISSUE THREAD

**Issue by quaff** [minio/minio#9865]
It's common to use an empty(zero length) file simulate directory hierarchy.
```
/dir1
/dir1/dir2
/dir1/dir2/file
```
using s3 java sdk
```java
s3.putObject(bucket, "dir1", new ByteArrayInputStream(new byte[0]), metadata);
s3.putObject(bucket, "dir1/dir2", new ByteArrayInputStream(new byte[0]), metadata); //error raised
s3.putObject(bucket, "dir1/dir2/file", new FileInputStream(file), metadata); 
```
error message:
```
com.amazonaws.services.s3.model.AmazonS3Exception: Object-prefix is already an object, please choose a different object-prefix name. (Service: Amazon S3; Status Code: 400; Error Code: XMinioParentIsObject; Request ID: 161980F95575E230; S3 Extended Request ID: 66e06081-0faa-4039-974a-802b86ab31f6), S3 Extended Request ID: 66e06081-0faa-4039-974a-802b86ab31f6
```
Amazon S3 and Ceph Object Gateway both has the expected behavior.

**Comment by harshavardhana** [comment]
We are not going to support this model as this is not worth the effort for us @quaff this is explained repeatedly many times on why its a bad idea https://github.com/minio/minio/issues/7335#issuecomment-470683398 

If you need this feature then you should use AWS S3, MinIO thinks that is not something that should be fixed because of the problems that this brings.

**Comment by eocron** [comment]
How about m3u8 hls video files?
They are served by using this relative structure:
http://foobar/master.m3u8                                              <- manifest file
http://foobar/master.m3u8/p360/index.m3u8                <- manifest file
http://foobar/master.m3u8/p360/index.m3u8/seg_0.ts  <- first part of video in p360 res
http://foobar/master.m3u8/p360/index.m3u8/seg_1.ts  <- second part
http://foobar/master.m3u8/p360/index.m3u8/seg_2.ts  <-....
...

and there is no way to override this behavior.

**Comment by harshavardhana** [comment]
> How about m3u8 hls video files?
> They are served by using this relative structure:
> http://foobar/master.m3u8 <- manifest file
> http://foobar/master.m3u8/p360/index.m3u8 <- manifest file
> http://foobar/master.m3u8/p360/index.m3u8/seg_0.ts <- first part of video in p360 res
> http://foobar/master.m3u8/p360/index.m3u8/seg_1.ts <- second part
> http://foobar/master.m3u8/p360/index.m3u8/seg_2.ts <-....
> ...
> 
> and there is no way to override this behavior.

There is no way, we may support in future but not right now.
