### ISSUE TITLE
[not our bug] Cannot compile with gitpod

### ISSUE THREAD

**Issue by MGlolenstine** [minio/minio#9868]
When trying to install GitPod onto a server with Go 1.14 installed, the installation fails with the output below.
## Expected Behavior

Expected successful MinIO installation.
## Current Behavior

MinIO throws an error related to Go 1.14 update, as there are some unnecessary parentheses in a check.

```
# helm upgrade --install $(for i in $(cat configuration.txt); do echo -e "-f $i"; done) gitpod .
Release "gitpod" does not exist. Installing it now.
Error: template: gitpod-selfhosted/charts/gitpod/charts/minio/templates/deployment.yaml:192:20: executing "gitpod-selfhosted/charts/gitpod/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
```
## Possible Solution

I think that the "bug" could be solved by updating the templates that include those unnecessary parentheses.
## Steps to Reproduce (for bugs)

1. Install Go 1.14 and helm
2. Clone GitPod repository `git clone https://github.com/gitpod-io/self-hosted`
3. Start installing GitPod

```
# helm repo add charts.gitpod.io https://charts.gitpod.io
# helm dep update
# helm upgrade --install $(for i in $(cat configuration.txt); do echo -e "-f $i"; done) gitpod .
```
## Context

I'm trying to install GitPod onto my server.
## Regression

Unsure
## Your Environment

* Operating System and version (`uname -a`): Linux alarm 5.7.1-1-ARCH #1 SMP Tue Jun 9 01:23:20 UTC 2020 aarch64 GNU/Linux
* Link to your project: https://github.com/gitpod-io/self-hosted

### EDIT:
Same problems are occurring with other people as well, so the ARM isn't the issue here.
1: https://github.com/gitpod-io/self-hosted/issues/25
2: https://github.com/helm/charts/issues/21446

**Comment by harshavardhana** [comment]
@MGlolenstine this is already fixed in https://github.com/helm/charts/commit/89a712556d2e3bb8c18acc350dca0bc9a5baba8d

**Comment by MGlolenstine** [comment]
You're right! Thanks!

I'm just not sure why GitPod uses an old version then. I'll ask them and see if it's something they have to solve.

Thanks for your help!
