### ISSUE TITLE
Huge disk-cache directories

### ISSUE THREAD

**Issue by HeavyHorst** [minio/minio#9870]
**Is your feature request related to a problem? Please describe.**
We currently host about 70TB of media in Amazon S3 and and are trying to use minio in gateway mode to save some bandwith costs. 

The problem is that every http-range is cached again, which leads to constantly high traffic from s3 and requires huge amounts of cache storage (people seek around in videos all the time).

For some files I end up with massive cache-directories of 350GB+ for a single 1.6GB video file.
Here is a cache.json file of such a case:
[cache.txt](https://github.com/minio/minio/files/4800388/cache.txt)

**Describe the solution you'd like**
I would like to be able to simply cache the complete files.
I think that would be clearly more efficient in our case (only 1.6GB transfer from amazon instead of 350GB) for just this one file.

**Comment by poornas** [comment]
@HeavyHorst , will discuss internally and get back to you on making this configurable.

**Comment by HeavyHorst** [comment]
Thank you! That would be great.

**Comment by HeavyHorst** [comment]
Is there an easy way to disable range-caching in the source code for testing?
Thanks in advance for your work.

**Comment by poornas** [comment]
> Is there an easy way to disable range-caching in the source code for testing?
> Thanks in advance for your work.

@HeavyHorst , you can use the patch referenced here.

**Comment by HeavyHorst** [comment]
Works great by the way!
