### ISSUE TITLE
[faq] How to share object URL with no expiration?

### ISSUE THREAD

**Issue by hillbun** [minio/minio#9886]
Share object URL with UI always with expiration, how to  share object URL with no expiration?

**Comment by hillbun** [comment]
I upload file with ui

**Comment by harshavardhana** [comment]
You can set your bucket to be download only, to allow URLs without expiration.

Share/Presigned always have an expiry implemented as per S3 spec..

NOTE: please use the issue template and fill each entry appropriately.

For regular questions like these join our https://slack.min.io
