### ISSUE TITLE
[duplicate] Heal aborts when run on folder with many files

### ISSUE THREAD

**Issue by SoftBoil** [minio/minio#9888]
I have a bucket that is populated by ARQ backup (arqbackup.com). The backup creates a shallow but wide directory structure. Three of the significant directories are: 
- /treepacks (~95 sub-folders, ~450 files, 133 MB)
- /blobpacks (~250 sub-folders, ~20k files, 7.7 GB)
- /blobs (~250 sub-folders, ~150k files, 128 GB)

Completes in few seconds:
mc admin heal -r myminio/arq/460ac29a-6921-483b-bebd-7235b6b1ca4e/treepacks

Both abort after a few minutes:
mc admin heal -r myminio/arq/460ac29a-6921-483b-bebd-7235b6b1ca4e/blobpacks
mc admin heal -r myminio/arq/460ac29a-6921-483b-bebd-7235b6b1ca4e/blobs

## Expected Behavior
Heal should successfully finish scan of all files.

## Current Behavior
Heal aborts with message:

mc: <DEBUG> HTTP/1.1 400 Bad Request
Content-Length: 331
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/json
Date: Sun, 21 Jun 2020 01:48:32 GMT
Server: MinIO/RELEASE.2020-06-18T02-23-35Z
Vary: Origin
X-Amz-Request-Id: 161A6BF3BA79C8A0
X-Xss-Protection: 1; mode=block

{"Code":"XMinioHealNoSuchProcess","Message":"No such heal process is running on the server","Key":"460ac29a-6921-483b-bebd-7235b6b1ca4e/blobpacks","BucketName":"arq","Resource":"/minio/admin/v3/heal/arq/460ac29a-6921-483b-bebd-7235b6b1ca4e/blobpacks","RequestId":"161A6BF3BA79C8A0","HostId":"ed42b8aa-5abd-4238-a942-c7d158b15b01"}
mc: <DEBUG> Response Time:  2.577481ms

mc: <ERROR> Unable to display heal status. No such heal process is running on the server
 (1) admin-heal.go:278 cmd.mainAdminHeal(..) Tags: [myminio/arq/460ac29a-6921-483b-bebd-7235b6b1ca4e/blobpacks]
 (0) admin-heal.go:278 cmd.mainAdminHeal(..)
 Release-Tag:RELEASE.2020-06-20T00-18-43Z | Commit:dd47bdfeaa75 | Host:REDACTED | OS:darwin | Arch:amd64 | Lang:go1.13.12 | Mem:2.5 MB/72 MB | Heap:2.5 MB/66 MB

## Your Environment
Client: RELEASE.2020-06-20T00-18-43Z

Server: 2020-06-18T02:23:35Z
Network: 1/1 OK 
Drives: 6/6 OK 
MINIO_STORAGE_CLASS_STANDARD=EC:2

**Comment by harshavardhana** [comment]
Duplicate of #9878
