### ISSUE TITLE
Possibility to configure S3 MinIO gateway to a single S3 bucket

### ISSUE THREAD

**Issue by tooptoop4** [minio/minio#9889]
I would like minio s3 gateway UI to only show a single bucket.

attempt 1:
./minio gateway s3 --address :8787 https://s3.eu-west-1.amazonaws.com

result is all buckets are shown

attempt 2:
./minio gateway s3 --address :8787 https://mybucket.s3.eu-west-1.amazonaws.com

results is no buckets are shown, even though the minio process starts up without error

logs:

AccessKey: abc
SecretKey: redact123

API: WebListBuckets()
UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
Error: The AWS Access Key Id you provided does not exist in our records.
       3: github.com/minio/minio@/cmd/web-handlers.go:2238:cmd.toWebAPIError()
       2: github.com/minio/minio@/cmd/web-handlers.go:2109:cmd.toJSONError()
       1: github.com/minio/minio@/cmd/web-handlers.go:334:cmd.(*webAPIHandlers).ListBuckets()

API: WebListBuckets()
UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
Error: The AWS Access Key Id you provided does not exist in our records.
       5: github.com/minio/minio@/cmd/api-errors.go:1875:cmd.toAPIErrorCode()
       4: github.com/minio/minio@/cmd/api-errors.go:1900:cmd.toAPIError()
       3: github.com/minio/minio@/cmd/web-handlers.go:2239:cmd.toWebAPIError()
       2: github.com/minio/minio@/cmd/web-handlers.go:2109:cmd.toJSONError()
       1: github.com/minio/minio@/cmd/web-handlers.go:334:cmd.(*webAPIHandlers).ListBuckets()

see https://github.com/minio/minio/issues/8536 for prior request

**Comment by harshavardhana** [comment]
@tooptoop4 S3 gateway is purpose-built to be simple these are to quite a lot of niche use cases we are not really interested in extending. 

Now you can, of course, have all the necessary policies in place for restriction in terms of which bucket has access. Then you can directly visit the browser 

http://domain.com/minio/mys3bucket

The browser only shows the relevant bucket and its contents. This is already supported, I don't see any good reason to further extend this.

**Comment by kannappanr** [comment]
@tooptoop4 as explained in the previous comment, you can create a S3 credential in AWS S3, that only has access to a single bucket and use it Gateway as explained in the previous comment. Closing this issue as answered. Please feel free to reach out to us if you have further questions.

**Comment by arrowcircle** [comment]
Hey! It looks like minio does not work with Digital Ocean Spaces because of this things. Any ideas how to make it work?
