### ISSUE TITLE
[resolved] File deletion from MinIO browser throws meaningless error (master branch)

### ISSUE THREAD

**Issue by bensodenkamp** [minio/minio#9891]
When deleting files (on master branch) in S3 gateway mode from the minio browser, the file deletes properly by an error message is always shown: Functionality not implemented. Looking to fix this myself. Feel free to assign to me.

## Expected Behavior

No error should be shown

## Current Behavior

An error message appears

Error message should not appear

## Steps to Reproduce (for bugs)

1. Launch Minio in S3 gateway mode
2. Upload a file
3. Delete the file
4.

## Context

I encountered the problem when looking into a different issue. I intend to fix this myself.

## Your Environment

* Version used (`minio version`): current master branch
* Environment name and version (e.g. nginx 1.9.1): AWS S3
* Server type and version: ec2 host
* Operating System and version (`uname -a`): amazon linux
* Link to your project:

**Comment by harshavardhana** [comment]
@bensodenkamp master branch is not ready for release please report the entire issue here in detail for which we can send a fix for. 

If not we prefer that you use the release branch for now.

**Comment by bensodenkamp** [comment]
I understand master isn't ready. My intention here was just to track my contribution in solving the problem, and let you know what I was doing in case someone else was working in that part of the app. Is there a better workflow if I simply want to contribute?

**Comment by harshavardhana** [comment]
> I understand master isn't ready. My intention here was just to track my contribution in solving the problem, and let you know what I was doing in case someone else was working in that part of the app. Is there a better workflow if I simply want to contribute?

You may send a PR to the best of your knowledge, we will let you know if it's correct or not upon review. Or if someone gets to it first before you in that case you can help validate it.

**Comment by bensodenkamp** [comment]
FYI, this appears to be broken with the fix for versioning: https://github.com/minio/minio/issues/2111 in commit: https://github.com/minio/minio/commit/4915433bd28585868e8259996d43fbcf6b4d7b46

**Comment by harshavardhana** [comment]
> FYI, this appears to be broken with the fix for versioning: #2111 in commit: [4915433](https://github.com/minio/minio/commit/4915433bd28585868e8259996d43fbcf6b4d7b46)

This is fixed in #9938

**Comment by bensodenkamp** [comment]
New behavior: There is no error message, and objects delete successfully, however the "are you sure you want to delete" dialog does not disappear when the user clicks 'ok'. If you click 'ok' then click 'cancel', then reload the screen, only then can you see that the deleted object has been removed from the bucket.

**Comment by harshavardhana** [comment]
> New behavior: There is no error message, and objects delete successfully, however the "are you sure you want to delete" dialog does not disappear when the user clicks 'ok'. If you click 'ok' then click 'cancel', then reload the screen, only then can you see that the deleted object has been removed from the bucket.

feel free to send a PR @bensodenkamp
