### ISSUE TITLE
Empty directories in minio.sys/buckets not being cleaned up

### ISSUE THREAD

**Issue by programmierstube** [minio/minio#9897]
When a file is uploaded, minio creates an fs.json file in a folder with the same name as the file inside the minio.sys/buckets folder. But when deleting a file from minio the fs.json is removed, but not the containing folder (the one with the same name as the file).

## Expected Behavior
Folder containing the fs.json should be removed as well to not end up with lots of empty folders.

## Current Behavior
Currently the folder stays, despite being empty after fs.json was removed.

## Steps to Reproduce (for bugs)

1. upload a file through UI
2. on disk see that the corresponding fs.json + folder was created in minio.sys/buckets
3. delete file in UI
4. the folder in minio.sys/buckets is still there, only the fs.json was removed

**Comment by vadmeste** [comment]
@programmierstube, I am not really able to reproduce this, could you tell what's your MinIO version ?

**Comment by vadmeste** [comment]
Also what operating system is this ? @programmierstube

**Comment by harshavardhana** [comment]
Multiple reports came in @vadmeste were you able to reproduce this?

**Comment by vadmeste** [comment]
> Multiple reports came in @vadmeste were you able to reproduce this?

This could be happening in Windows, I already found that the code is sometimes deleting the object's fs.json file before calling Close() function. But AFAIK, this is not a problem for Linux.

**Comment by vadmeste** [comment]
One user reported this is happening in Linux. I will try to stress test and see.

**Comment by programmierstube** [comment]
We are running minio in a docker swarm. The hosts run Ubuntu 18.04, and the folder minio uses is a NFS mount. 

Here is a screenshot of the about popover in the minio UI:

<img width="630" alt="Screenshot 2020-07-20 at 11 09 40" src="https://user-images.githubusercontent.com/6953867/87920489-9487c200-ca79-11ea-8296-0d6379958e57.png">

Here is how the issue is reproducible for us:

1. Empty state for an empty bucket

<img width="1114" alt="Screenshot 2020-07-20 at 11 04 36" src="https://user-images.githubusercontent.com/6953867/87920739-e892a680-ca79-11ea-8f11-4ca5501cf253.png">
<img width="503" alt="Screenshot 2020-07-20 at 11 04 07" src="https://user-images.githubusercontent.com/6953867/87920743-eaf50080-ca79-11ea-92c0-9a6d70039526.png">

2. State after uploading a file

<img width="1114" alt="Screenshot 2020-07-20 at 11 04 56" src="https://user-images.githubusercontent.com/6953867/87920800-006a2a80-ca7a-11ea-8715-992252b4b4e9.png">
<img width="460" alt="Screenshot 2020-07-20 at 11 05 11" src="https://user-images.githubusercontent.com/6953867/87920834-0e1fb000-ca7a-11ea-84e2-b010ab4dca4f.png">

3. Minio.sys folder contains folder for file incl. fs.json
 
<img width="662" alt="Screenshot 2020-07-20 at 11 07 01" src="https://user-images.githubusercontent.com/6953867/87920875-1c6dcc00-ca7a-11ea-879a-30c5e6545f11.png">

4. File removed through minio UI and state afterwards

<img width="1116" alt="Screenshot 2020-07-20 at 11 07 30" src="https://user-images.githubusercontent.com/6953867/87920957-3d362180-ca7a-11ea-9fb2-1df3fe4fa001.png">
<img width="644" alt="Screenshot 2020-07-20 at 11 08 09" src="https://user-images.githubusercontent.com/6953867/87920983-458e5c80-ca7a-11ea-93ef-b995886cb4dc.png">

As you can see the kittie.jpg folder inside the minio.sys folder stays there and is empty. It is also not garbage collected or anything, so really stays there forever it seems.
