### ISSUE TITLE
[resolved] minio crash when accessed from All-in-One WP Migration tool

### ISSUE THREAD

**Issue by citrus-it** [minio/minio#9904]
##  Expected Behavior

I am trying to use the All-in-One WP Migration tool S3 client plugin to back up wordpress web sites to minio.

## Current Behavior

When I attempt to backup to minio, the plugin reports curl error 52 "nothing" returned, and the minio server logs:

```
http: panic serving 192.168.1.1:60476: runtime error: invalid memory address or nil pointer dereference","source":["github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
goroutine 262 [running]:","source":["github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
"net/http.(*conn).serve.func1(0xc000936000)","source":["github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
...
etc.
```

Taking a packet trace shows that plugin issues three requests in quick succession, which are as follows. Only the third gets a response.

```
HEAD / HTTP/1.1
Host: s3.elided.uk
Accept: */*
User-Agent: All-in-One WP Migration
x-amz-date: 20200623T152202Z
x-amz-content-sha256: ...elided...
Authorization: AWS4-HMAC-SHA256 Credential=unbind-trigger-bail/20200623/oracle/s3/aws4_request,SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date,Signature=...elided...

```

```
PUT / HTTP/1.1
Host: s3.elided.uk
Accept: */*
User-Agent: All-in-One WP Migration
Content-Type: application/xml
x-amz-date: 20200623T152202Z
x-amz-content-sha256: ...elided...
Authorization: AWS4-HMAC-SHA256 Credential=unbind-trigger-bail/20200623/oracle/s3/aws4_request,SignedHeaders=content-type;host;user-agent;x-amz-content-sha256;x-amz-date,Signature=...elided...
Content-Length: 102

<CreateBucketConfiguration><LocationConstraint>oracle</LocationConstraint></CreateBucketConfiguration>
```

```
GET / HTTP/1.1
Host: s3.elided.uk
Accept: */*
User-Agent: All-in-One WP Migration
x-amz-date: 20200623T152202Z
x-amz-content-sha256: ...elided...
Authorization: AWS4-HMAC-SHA256 Credential=unbind-trigger-bail/20200623/oracle/s3/aws4_request,SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date,Signature=...elided...

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 461
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO/RELEASE.2020-06-22T03-12-50Z
Vary: Origin
X-Amz-Bucket-Region: oracle
X-Amz-Request-Id: 161B35815F87D1A1
X-Xss-Protection: 1; mode=block
Date: Tue, 23 Jun 2020 15:22:02 GMT

<?xml version="1.0" encoding="UTF-8"?>
<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><ID>0...elided...</ID><DisplayName></DisplayName></Owner><Buckets><Bucket><Name>leek12-com</Name><CreationDate>2020-06-23T14:19:31.497Z</CreationDate></Bucket><Bucket><Name>migrate</Name><CreationDate>2020-06-23T13:39:06.594Z</CreationDate></Bucket></Buckets></ListAllMyBucketsResult>
```

## Steps to Reproduce (for bugs)

I can reproduce using the mentioned plugin, clicking on update in the control panel causes the error. I have not yet been able to replicate using something like `curl` unfortunately.

## Your Environment
* Version used: RELEASE.2020-06-22T03-12-50Z
* Environment name and version: standalone
* Server type and version: Oracle Enterprise Linux (Oracle cloud server)
* Operating System and version: Linux ns2 4.14.35-1902.301.1.el7uek.x86_64 #2 SMP Tue Mar 31 16:50:32 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> http: panic serving 192.168.1.1:60476: runtime error: invalid memory address or nil pointer dereference","source":["github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
> goroutine 262 [running]:","source":["github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
> "net/http.(*conn).serve.func1(0xc000936000)","source":["github.com/minio/minio@/cmd/server-main.go:453:cmd.serverMain.func2()
> ...
> etc.

Is this the only crash that you have? can you share the entire logs? @citrus-it

**Comment by citrus-it** [comment]
Here's the full log from minio

[miniocrash.txt](https://github.com/minio/minio/files/4841079/miniocrash.txt)

**Comment by harshavardhana** [comment]
@citrus-it would you be able to test a binary?

**Comment by citrus-it** [comment]
Yes, I have a test environment for this in place.
minio is running on x86_64 Linux.

**Comment by harshavardhana** [comment]
https://harshavardhana.s3.amazonaws.com/minio-rc @citrus-it can you test this and see if you reproduce the crash again?

**Comment by citrus-it** [comment]
I tested it and it no longer crashes, thanks!

The plugin doesn't work but that looks like something about the S3 emulation (it works with Amazon S3)

```
HEAD / HTTP/1.1
Host: s3.example.com
Accept: */*
User-Agent: All-in-One WP Migration
x-amz-date: 20200628T211539Z
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Authorization: AWS4-HMAC-SHA256 Credential=unbind-trigger-bail/20200628/oracle/s3/aws4_request,SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date,Signature=...

HTTP/1.1 400 Bad Request
Accept-Ranges: bytes
Content-Length: 254
Content-Type: application/xml
Server: MinIO/DEVELOPMENT.2020-06-28T19-04-28Z
X-Amz-Bucket-Region: oracle
Date: Sun, 28 Jun 2020 21:15:39 GMT
```

```
PUT / HTTP/1.1
Host: s3.example.com
Accept: */*
User-Agent: All-in-One WP Migration
Content-Type: application/xml
x-amz-date: 20200628T211539Z
x-amz-content-sha256: 4775ef6bb818f499cfecfafeb8700adab0bd57961781b2707d44efd3000338f7
Authorization: AWS4-HMAC-SHA256 Credential=unbind-trigger-bail/20200628/oracle/s3/aws4_request,SignedHeaders=content-type;host;user-agent;x-amz-content-sha256;x-amz-date,Signature=...
Content-Length: 102

<CreateBucketConfiguration><LocationConstraint>oracle</LocationConstraint></CreateBucketConfiguration>

HTTP/1.1 400 Bad Request
Accept-Ranges: bytes
Content-Length: 254
Content-Type: application/xml
Server: MinIO/DEVELOPMENT.2020-06-28T19-04-28Z
X-Amz-Bucket-Region: oracle
Date: Sun, 28 Jun 2020 21:15:39 GMT

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioUnknownAPIRequest</Code><Message>Unknown API request at /</Message><Resource>/</Resource><Region>oracle</Region><RequestId></RequestId><HostId>f38e4f9a-fc73-4155-b3cf-416ab925c5b7</HostId></Error>
```

**Comment by harshavardhana** [comment]
> I tested it and it no longer crashes, thanks!
> 
> The plugin doesn't work but that looks like something about the S3 emulation (it works with Amazon S3)
> 
> ```
> HEAD / HTTP/1.1
> Host: s3.example.com
> Accept: */*
> User-Agent: All-in-One WP Migration
> x-amz-date: 20200628T211539Z
> x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
> Authorization: AWS4-HMAC-SHA256 Credential=unbind-trigger-bail/20200628/oracle/s3/aws4_request,SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date,Signature=...
> 
> HTTP/1.1 400 Bad Request
> Accept-Ranges: bytes
> Content-Length: 254
> Content-Type: application/xml
> Server: MinIO/DEVELOPMENT.2020-06-28T19-04-28Z
> X-Amz-Bucket-Region: oracle
> Date: Sun, 28 Jun 2020 21:15:39 GMT
> ```
> 
> ```
> PUT / HTTP/1.1
> Host: s3.example.com
> Accept: */*
> User-Agent: All-in-One WP Migration
> Content-Type: application/xml
> x-amz-date: 20200628T211539Z
> x-amz-content-sha256: 4775ef6bb818f499cfecfafeb8700adab0bd57961781b2707d44efd3000338f7
> Authorization: AWS4-HMAC-SHA256 Credential=unbind-trigger-bail/20200628/oracle/s3/aws4_request,SignedHeaders=content-type;host;user-agent;x-amz-content-sha256;x-amz-date,Signature=...
> Content-Length: 102
> 
> <CreateBucketConfiguration><LocationConstraint>oracle</LocationConstraint></CreateBucketConfiguration>
> 
> HTTP/1.1 400 Bad Request
> Accept-Ranges: bytes
> Content-Length: 254
> Content-Type: application/xml
> Server: MinIO/DEVELOPMENT.2020-06-28T19-04-28Z
> X-Amz-Bucket-Region: oracle
> Date: Sun, 28 Jun 2020 21:15:39 GMT
> 
> <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>XMinioUnknownAPIRequest</Code><Message>Unknown API request at /</Message><Resource>/</Resource><Region>oracle</Region><RequestId></RequestId><HostId>f38e4f9a-fc73-4155-b3cf-416ab925c5b7</HostId></Error>
> ```

Well this is clearly because there is no bucket name in the request, looks like you need to enable path style access to get this working properly.

**Comment by citrus-it** [comment]
Yes, thanks. Adjusted the configuration and now it's working!

Thanks a lot for the help with this.

**Comment by harshavardhana** [comment]
> Yes, thanks. Adjusted the configuration and now it's working!
> 
> Thanks a lot for the help with this.

Great and the crash is already fixed in both branches, we will be making a release on Monday.

Thanks for testing.
