### ISSUE TITLE
Add list support in the claim

### ISSUE THREAD

**Issue by romrzh** [minio/minio#9911]
**Is your feature request related to a problem? Please describe.**
We want to use MinIO with Keycloak, and we want to map policies to the client roles, but roles can be mapped to the JWT as а list `"policy":["readwrite","test_readonly"]`, or as  а string `"policy": "[readwrite, test_readonly]"`, but for now MinIO supports only string with comma separated policies `"policy": "readwrite, test_readonly"` in the  claim.

**Describe the solution you'd like**
Add lists support in the JWTs claim

**Comment by harshavardhana** [comment]
You can provide the claims as comma separated value, this is already supported as part of multiple policies.

Note: please use the issue template appropriately, we tirelessly write code and expect a simple etiquette from community when opening issues. Manually deleting the template, we do not know what you are looking for in which version of the software.

I shall close this issue, as this is already supported.
