### ISSUE TITLE
GET/HEAD of object with partNumber returns entire object content/length

### ISSUE THREAD

**Issue by kjamieson** [minio/minio#9914]
Peforming a HeadObject or GetObject request against a MinIO server with a specific partNumber specified in the query parameters currently returns the Content-Length (and in the case of GetObject, the content) of the entire object rather than the Content-Length (and content) of the specific part.

This deviates from the behaviour of AWS S3 and the S3 documentation:

https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html:

> partNumber: Part number of the object being read. This is a positive integer between 1 and 10,000. Effectively performs a 'ranged' HEAD request for the part specified. Useful querying about the size of the part and the number of parts in this object.

 https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html

> partNumber: Part number of the object being read. This is a positive integer between 1 and 10,000. Effectively performs a 'ranged' GET request for the part specified. Useful for downloading just a part of an object.

## Expected Behavior

For example, given an object created with four parts:

`$ cat /tmp/minio/.minio.sys/buckets/test-bucket/multipart/fs.json | jq
{
  "version": "1.0.2",
  "checksum": {
    "algorithm": "",
    "blocksize": 0,
    "hashes": null
  },
  "meta": {
    "X-Minio-Internal-actual-size": "15728641",
    "content-type": "application/octet-stream",
    "etag": "0aa6cdf3a0b42b1eb084600f2b26d5c0-4"
  },
  "parts": [
    {
      "number": 1,
      "size": 5242880,
      "actualSize": 5242880
    },
    {
      "number": 2,
      "size": 5242880,
      "actualSize": 5242880
    },
    {
      "number": 3,
      "size": 5242880,
      "actualSize": 5242880
    },
    {
      "number": 4,
      "size": 1,
      "actualSize": 1
    }
  ]
}`

Performing a head-object request against a specific part should return the ContentLength of the specific part:

`$ aws --profile minio --endpoint-url http://localhost:9000 s3api head-object --bucket test-bucket --key multipart --part-number 1 
{
    "AcceptRanges": "bytes",
    "LastModified": "Thu, 25 Jun 2020 00:22:22 GMT",
    "ContentLength": 5242880,
    "ETag": "\"0aa6cdf3a0b42b1eb084600f2b26d5c0-4\"",
    "ContentType": "application/octet-stream",
    "Metadata": {},
    "PartsCount": 4
}

$ aws --profile minio --endpoint-url http://localhost:9000 s3api head-object --bucket test-bucket --key multipart --part-number 4
{
    "AcceptRanges": "bytes",
    "LastModified": "Thu, 25 Jun 2020 00:22:22 GMT",
    "ContentLength": 1,
    "ETag": "\"0aa6cdf3a0b42b1eb084600f2b26d5c0-4\"",
    "ContentType": "application/octet-stream",
    "Metadata": {},
    "PartsCount": 4
}`

Similarly, performing a get-object request against a specific part should return just the content of that part.

## Current Behavior

Performing a head-object request against a specific part returns the ContentLength of the entire object:

`$ aws --profile minio --endpoint-url http://localhost:9000 s3api head-object --bucket test-bucket --key multipart --part-number 1 
{
    "AcceptRanges": "bytes",
    "LastModified": "Thu, 25 Jun 2020 00:22:22 GMT",
    "ContentLength": 15728641,
    "ETag": "\"0aa6cdf3a0b42b1eb084600f2b26d5c0-4\"",
    "ContentType": "application/octet-stream",
    "Metadata": {},
    "PartsCount": 4
}

$ aws --profile minio --endpoint-url http://localhost:9000 s3api head-object --bucket test-bucket --key multipart --part-number 4
{
    "AcceptRanges": "bytes",
    "LastModified": "Thu, 25 Jun 2020 00:22:22 GMT",
    "ContentLength": 15728641,
    "ETag": "\"0aa6cdf3a0b42b1eb084600f2b26d5c0-4\"",
    "ContentType": "application/octet-stream",
    "Metadata": {},
    "PartsCount": 4
}`

Similarly, performing a get-object request against a specific part returns the entire contents of the object, not just the part.

## Steps to Reproduce

1. Create an object using the multipart APIs that consists of more than 1 part
2. Perform a HEAD or GET request for a specific part with ?partNumber=N or (with the aws CLI) --part-number N

**Comment by harshavardhana** [comment]
Right now we don't have the value at hand to return this correctly, thanks for opening we may look at fixing this in future.

**Comment by harshavardhana** [comment]
Not stale will be fixing it.
