### ISSUE TITLE
Extend S3 Select To Include $path

### ISSUE THREAD

**Issue by caryfitzhugh** [minio/minio#9915]
## Expected Behavior

When doing S3 Select queries, one should be allowed to select "$path" (or a similarly named variable) which would return the file's bucket / key string as a result.

When we want to downselect and find relevant data, we usually look for a needle in the MinIO haystack, take the files containing those records,  and ingest them into another system.  This is inefficient to do a single S3 Select against each file individually - would be much nicer if one could do something similar to what AWS Athena does, and find the file the row came from:

https://aws.amazon.com/premiumsupport/knowledge-center/find-s3-source-file-athena-table-row/

**Comment by klauspost** [comment]
Removed the "bug report" template stuff.

Seems to be "Amazon Athena" exclusive feature. Should be reasonable to implement, but not trivial.

Putting on low until it has been clairfied.

**Comment by kannappanr** [comment]
Won't the user already know the path when issuing a `SelectObjectContent` API?

**Comment by caryfitzhugh** [comment]
In our case, there are times when you need to look for some data like so:

```
mc sql --recursive --query "select * from S3Object where widget = 'needle' minio/bucket/2020/01
```
The output of this will be a bunch of JSON records to STDOUT.

That keypath may have hundreds of files - but you don't know which file had the "hit" - you just get the data.

In our usecase, we often would like to use this for debugging the workflow.  We have a piece of data already in the indexed datastore (postgres), and want to find it in MinIO so that we can re-run ingestion on that file.

Our current approach is a bash pipeline of ```mc find``` combined with ```mc sql``` on each file individually.

We saw this feature in Athena, and would really love it in S3 Select.

**Comment by klauspost** [comment]
@kannappanr The tricky part is that it appears to be returning a single result in `SELECT $path` when the condition is hit. So it should be treated specially, though the documentation is actually not clear if only one result is returned.

Inserting it as a per record variable is relatively easy except it shouldn't be returned with `SELECT *`. So there are a couple of corner cases to handle.
