### ISSUE TITLE
[wontfix] Upload files to MinIO through FTP/HTTP

### ISSUE THREAD

**Issue by dominicklee** [minio/minio#9923]
**Is your feature request related to a problem? Please describe.**
We have business clients who have **large** datasets. They want to be able to use the MinIO browser or MC command line to be able to put files that are hosted on remote URIs (e.g. FTP and HTTP) into their MinIO buckets.

**Describe the solution you'd like**
We would like a solution where the `cp` command in the MC command line can take a URI (e.g. FTP and HTTP) as an input. It would also be preferable to have a capability in the MinIO browser where the user can provide the URI details to have MinIO fetch data from the remote location without using the local computer.

**Describe alternatives you've considered**
Currently, the ways that we can add a file to MinIO is by (1) using the S3 API, (2) uploading a file from computer using MinIO browser, (3) using the `cp` command from MC command line.

However, our clients have legacy datasets and it is not acceptable or feasible to ask their professionals to spend time running the API for every single object they want to import. Also, they cannot download files from the remote location on their computer as a means to re-upload them into MinIO. It is a security requirement that files be transferred directly from the remote server.

**Comment by harshavardhana** [comment]
We natively are S3 only protocol, we have no interest in being multi-protocol @dominicklee https://github.com/matiaskorhonen/ftp2s3 is something that can be run in front of MinIO to available the same functionality.

**Comment by harshavardhana** [comment]
> We natively are S3 only protocol, we have no interest in being multi-protocol @dominicklee https://github.com/matiaskorhonen/ftp2s3 is something that can be run in front of MinIO to available the same functionality.

https://github.com/fclairamb/ftpserver other maintained alternatives here.

**Comment by harshavardhana** [comment]
> We have business clients who have **large** datasets. They want to be able to use the MinIO browser or MC command line to be able to put files that are hosted on remote URIs (e.g. FTP and HTTP) into their MinIO buckets.

If you have a commercial need please get a subscription https://min.io/pricing - for now will close the issue has won't fix for now as there are other alternatives to use from.

**Comment by harshavardhana** [comment]
With this PR it will also support MinIO https://github.com/fclairamb/ftpserver/pull/34

**Comment by harshavardhana** [comment]
MinIO now natively supports FTP/SFTP all your existing credentials work.

https://github.com/minio/minio/tree/master/docs/ftp
