### ISSUE TITLE
Add a cookbook about anonymous access

### ISSUE THREAD

**Issue by cbou** [minio/minio#9927]
**Is your feature request related to a problem? Please describe.**
We currently have a min.io which stores images. Until now we were using a proxy which has the credentials to request the images and send them back to our user.

Since this proxy does not scale well, we would like to get rid of it. Actually the image are store using a hash in the filename so we do not need the min.io token for fetching the images.

**Describe the solution you'd like**
We would like to find a way to allow getting min.io objects without allowing to list buckets or images. Basically, you can download the object only if you have the path.

**Describe alternatives you've considered**
I know it sounds like a StackOverflow request but I think this could be a good candidate for a new Cookbook of the[ min.io documentation](https://docs.min.io/).

I have a [StackOverflow request](https://stackoverflow.com/questions/62595691/how-to-configure-minio-to-only-allow-anonymous-users-to-download-without-allow-t) already ;)

**Comment by cbou** [comment]
I got an answer. I don't know if it's the right way but it worked for me :)

https://stackoverflow.com/a/62620169/272839

**Comment by harshavardhana** [comment]
> I got an answer. I don't know if it's the right way but it worked for me :)
> 
> https://stackoverflow.com/a/62620169/272839

It is already documented in https://docs.minio.io/docs/minio-client-complete-guide.html#policy

Closing as per the document
