### ISSUE TITLE
File deletion is not correctly processed when a node of the cluster is down

### ISSUE THREAD

**Issue by ysysberserk** [minio/minio#9931]
If a file is deleted when a node of the minio cluster is down, when the node is up and rejoin the cluster, the part of the file will not be deleted and the mc ls command sometimes will find this file as if it was not deleted.
Run mc admin heal on this file will not return any error, but the file will still can be found by mc ls.
Run mc rm --force on this file will remove the file and completely fix the problem,but it is hard to find and run this command on such files, so it is not a good solution.

## Expected Behavior

Deleted file should be processed when the node rejoin the cluster and will never be found by the mc ls command

## Current Behavior

Deleted file will not be processed when the node rejoin the cluster and still can be found by the mc ls command.

## Possible Solution

Store the file information on those running nodes and replay the deletion on the down node when it rejoin the cluster.
Do not show the file if most of its shard is missing. If we can not see the deleted files when using mc ls command, it will not be a big problem.

## Steps to Reproduce (for bugs)

1. start a cluster with 3 node
2. stop a node
3. delete a file
4. restart the stopped node
5. run mc ls  mutiple times and you will see the deleted file sometimes.

## Context

We use minio to store our running task info. So if we see the deleted file, we will take it as a running task and the system will go wrong.

## Regression

Yes
minio version RELEASE.2020-06-22T03-12-50Z
mc version RELEASE.2020-06-20T00-18-43Z

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:
CentOS Linux release 7.4.1708 (Core)
minio version RELEASE.2020-06-22T03-12-50Z
mc version RELEASE.2020-06-20T00-18-43Z

**Comment by harshavardhana** [comment]
This is on purpose the quorum catches up later, the listing is not quorum based it's simply based on 3 drives shuffled across. 
What we are doing is potentially to have continuous healing which would basically garbage collect these dangling objects.

**Comment by harshavardhana** [comment]
We will be addressing this in future anyways, this is part of our todo lists.
