### ISSUE TITLE
 Unable to initialize OpenID

### ISSUE THREAD

**Issue by yuyuanshifu** [minio/minio#9932]
1、 I am following [https://github.com/minio/minio/blob/master/docs/sts/wso2.md](url) , when I Setup MinIO with OpenID configuration URL, I found an error occured in minio : Unable to initialize OpenID: Get https://xxxxxxxxxxxxx/oauth2/oidcdiscovery/.well-known/openid-configuration: x509: cannot validate certificate for xxxxxxxxxx because it doesn't contain any IP SANs. It seems like  that I should configure a certificate somewhere, but I didn't find where to configure and how to generate the certificate. 

2、The minio is still working, but when I used [https://github.com/minio/minio/blob/master/docs/sts/client-grants.go](url) to upload a file, I met the error:  400 Bad Request. And the minio log:   provider jwt doesn't exist.

3、I debugged the procedure, and I found that I had gotten the AccessToken from the idp, the error occured when the procedure post the request to minio for AssumeRoleWithClientGrants.

4、What should I do?

**Comment by harshavardhana** [comment]
> 1、 I am following [https://github.com/minio/minio/blob/master/docs/sts/wso2.md](url) , when I Setup MinIO with OpenID configuration URL, I found an error occured in minio : Unable to initialize OpenID: Get https://xxxxxxxxxxxxx/oauth2/oidcdiscovery/.well-known/openid-configuration: x509: cannot validate certificate for xxxxxxxxxx because it doesn't contain any IP SANs. It seems like that I should configure a certificate somewhere, but I didn't find where to configure and how to generate the certificate.
> 

First fix the error by trusting the IDP public certificate by keeping it at `$HOME/.minio/certs/CAs` 
> 2、The minio is still working, but when I used [https://github.com/minio/minio/blob/master/docs/sts/client-grants.go](url) to upload a file, I met the error: 400 Bad Request. And the minio log: provider jwt doesn't exist.
> 
> 3、I debugged the procedure, and I found that I had gotten the AccessToken from the idp, the error occured when the procedure post the request to minio for AssumeRoleWithClientGrants.
> 
> 4、What should I do?

Then rest will work..

**Comment by yuyuanshifu** [comment]
> > 1、 I am following [https://github.com/minio/minio/blob/master/docs/sts/wso2.md](url) , when I Setup MinIO with OpenID configuration URL, I found an error occured in minio : Unable to initialize OpenID: Get https://xxxxxxxxxxxxx/oauth2/oidcdiscovery/.well-known/openid-configuration: x509: cannot validate certificate for xxxxxxxxxx because it doesn't contain any IP SANs. It seems like that I should configure a certificate somewhere, but I didn't find where to configure and how to generate the certificate.
> 
> First fix the error by trusting the IDP public certificate by keeping it at `$HOME/.minio/certs/CAs`
I followed [https://is.docs.wso2.com/en/latest/administer/enabling-mutual-ssl/](url). 
1、certificateVerification="want"
2、[admin_console.authenticator.mutual_ssl_authenticator]
enable = true

[admin_console.authenticator.mutual_ssl_authenticator.config]
WhiteList = ""

3、keytool -export -alias wso2carbon -file carbon_public2.crt -keystore wso2carbon.jks -storepass wso2carbon
4、copy the carbon_public2.crt to minio $HOME/.minio/certs/CAs
5、restart the wso2 and minio 
But the problem was still
> 
> > 2、The minio is still working, but when I used [https://github.com/minio/minio/blob/master/docs/sts/client-grants.go](url) to upload a file, I met the error: 400 Bad Request. And the minio log: provider jwt doesn't exist.
> > 3、I debugged the procedure, and I found that I had gotten the AccessToken from the idp, the error occured when the procedure post the request to minio for AssumeRoleWithClientGrants.
> > 4、What should I do?
> 
> Then rest will work..

**Comment by yuyuanshifu** [comment]
> > 1、 I am following [https://github.com/minio/minio/blob/master/docs/sts/wso2.md](url) , when I Setup MinIO with OpenID configuration URL, I found an error occured in minio : Unable to initialize OpenID: Get https://xxxxxxxxxxxxx/oauth2/oidcdiscovery/.well-known/openid-configuration: x509: cannot validate certificate for xxxxxxxxxx because it doesn't contain any IP SANs. It seems like that I should configure a certificate somewhere, but I didn't find where to configure and how to generate the certificate.
> 
> First fix the error by trusting the IDP public certificate by keeping it at `$HOME/.minio/certs/CAs`
> 
> > 2、The minio is still working, but when I used [https://github.com/minio/minio/blob/master/docs/sts/client-grants.go](url) to upload a file, I met the error: 400 Bad Request. And the minio log: provider jwt doesn't exist.
> > 3、I debugged the procedure, and I found that I had gotten the AccessToken from the idp, the error occured when the procedure post the request to minio for AssumeRoleWithClientGrants.
> > 4、What should I do?
> 
> Then rest will work..

Hi, I generate the public certificate followed the up reply, but the problem is still, can you help me ?

**Comment by harshavardhana** [comment]
> Hi, I generate the public certificate followed the up reply, but the problem is still, can you help me ?

what is the problem really? all you have to do is put the public certificate at the location where you `~/.minio/certs/CAs` you can see where you `config-dir` defaults to by typing `minio --help`

**Comment by yuyuanshifu** [comment]
> > Hi, I generate the public certificate followed the up reply, but the problem is still, can you help me ?
> 
> what is the problem really? all you have to do is put the public certificate at the location where you `~/.minio/certs/CAs` you can see where you `config-dir` defaults to by typing `minio --help`

When I init my minio by docker, the problem ::Unable to initialize OpenID: Get https://192.168.207.34/oauth2/oidcdiscovery/.well-known/openid-configuration: x509: cannot validate certificate for 192.168.207.34 because it doesn't contain any IP SANs.  
I am not sure where the public certificate is. I followed [mutual-ssl](https://is.docs.wso2.com/en/latest/administer/enabling-mutual-ssl/) to generate carbon_public2.crt, and put it in /root/.minio/certs/CAs/(my ca path).

**Comment by harshavardhana** [comment]
> > > Hi, I generate the public certificate followed the up reply, but the problem is still, can you help me ?
> > 
> > 
> > what is the problem really? all you have to do is put the public certificate at the location where you `~/.minio/certs/CAs` you can see where you `config-dir` defaults to by typing `minio --help`
> 
> When I init my minio by docker, the problem ::Unable to initialize OpenID: Get https://192.168.207.34/oauth2/oidcdiscovery/.well-known/openid-configuration: x509: cannot validate certificate for 192.168.207.34 because it doesn't contain any IP SANs.
> I am not sure where the public certificate is. I followed [mutual-ssl](https://is.docs.wso2.com/en/latest/administer/enabling-mutual-ssl/) to generate carbon_public2.crt, and put it in /root/.minio/certs/CAs/(my ca path).

Since there are no user home dir in docker its at `/.minio/certs/CAs`

**Comment by harshavardhana** [comment]
> When I init my minio by docker, the problem ::Unable to initialize OpenID: Get https://192.168.207.34/oauth2/oidcdiscovery/.well-known/openid-configuration: x509: cannot validate certificate for 192.168.207.34 because it doesn't contain any IP SANs.

Also you generated cert for a domain not an IP which is what the certificate is complaining about

**Comment by harshavardhana** [comment]
> > When I init my minio by docker, the problem ::Unable to initialize OpenID: Get https://192.168.207.34/oauth2/oidcdiscovery/.well-known/openid-configuration: x509: cannot validate certificate for 192.168.207.34 because it doesn't contain any IP SANs.
> 
> Also you generated cert for a domain not an IP which is what the certificate is complaining about

Looks like a setup issue you should generate certs for both IP and domain if you want to use both.

Drop the public certs properly into your container at /.minio/certs/CAs and /root/.minio/certs/CAs it should work properly.

**Comment by yuyuanshifu** [comment]
> > > When I init my minio by docker, the problem ::Unable to initialize OpenID: Get https://192.168.207.34/oauth2/oidcdiscovery/.well-known/openid-configuration: x509: cannot validate certificate for 192.168.207.34 because it doesn't contain any IP SANs.
> > 
> > 
> > Also you generated cert for a domain not an IP which is what the certificate is complaining about
> 
> Looks like a setup issue you should generate certs for both IP and domain if you want to use both.
> 
> Drop the public certs properly into your container at /.minio/certs/CAs and /root/.minio/certs/CAs it should work properly.

Thanks for your reply, I am trying to generate certs for domain and undstand the process.
