### ISSUE TITLE
[faq] Increase number of disk on distributed minio cluster

### ISSUE THREAD

**Issue by hosnas** [minio/minio#9933]
First I started with this command:

`./minio server http://server{0...1}/mnt/drive{1...2}`

Then I tried to add more disk by this:

`./minio server http://server{0...1}/mnt/drive{1...2} http://server{0...1}/mnt/drive{1...4}
`
However I got the following error:

ERROR Invalid command line arguments: duplicate endpoints found

I managed to make minio running by this command:

`./minio server http://server{0...1}/mnt/drive{1...2} http://server{0...1}/mnt/drive{3...4}`

But I dont know if its correct or not. And what if I want to add even more disks? should I go like this?

`./minio server http://server{0...1}/mnt/drive{1...2} http://server{0...1}/mnt/drive{3...4} http://server{0...1}/mnt/drive{5...6} etc`

**Comment by harshavardhana** [comment]
You must expand by zone based expansion https://github.com/minio/minio/blob/release/docs/distributed/README.md#expanding-existing-distributed-setup as mentioned here

If there are no bugs to report, please ask faq's on community slack https://slack.min.io

Note: each command is unique and disks should be unique per host.

**Comment by hosnas** [comment]
> ./minio server http://server{0...1}/mnt/drive{1...2} http://server{0...1}/mnt/drive{1...4}
However I got the following error:
 ERROR Invalid command line arguments: duplicate endpoints found

@harshavardhana 
Ok I will ask in slack. However I followed the documentation but I recieve this error. I think there is somthing wrong there or there should be more clarification.

**Comment by harshavardhana** [comment]
> > ./minio server http://server{0...1}/mnt/drive{1...2} http://server{0...1}/mnt/drive{1...4}
> However I got the following error:
>  ERROR Invalid command line arguments: duplicate endpoints found
> 
> @harshavardhana 
> Ok I will ask in slack. However I followed the documentation but I recieve this error. I think there is somthing wrong there or there should be more clarification.

Yes your disks are duplicate you used the same disks in the first arg as part of second arg.

**Comment by hosnas** [comment]
@harshavardhana 
Sorry if Im not underestanding well, but the documentation says to expand like this: 
```
export MINIO_ACCESS_KEY=<ACCESS_KEY>
export MINIO_SECRET_KEY=<SECRET_KEY>
minio server http://host{1...n}/export{1...m} http://host{1...o}/export{1...m}
```
So here I see some duplication as well. both args contain {1...

**Comment by harshavardhana** [comment]
> @harshavardhana 
> Sorry if Im not underestanding well, but the documentation says to expand like this: 
> ```
> export MINIO_ACCESS_KEY=<ACCESS_KEY>
> export MINIO_SECRET_KEY=<SECRET_KEY>
> minio server http://host{1...n}/export{1...m} http://host{1...o}/export{1...m}
> ```
> So here I see some duplication as well. both args contain {1... 
> 

That is meant to be different hosts it's just an example, copying pasting it is not going to work.

```
./minio server http://server{0...1}/mnt/drive{1...2} http://server{0...1}/mnt/drive{3...4}
```

Just this how hard can this get?

**Comment by AliGolmirzaei** [comment]
@harshavardhana

maybe writing 
`minio server http://host{1...n}/export{1...m} http://host{n+1...o}/export{1...m}`
instead of 
`minio server http://host{1...n}/export{1...m} http://host{1...o}/export{1...m}`
help to understand it a lot better

**Comment by harshavardhana** [comment]
> @harshavardhana
> 
> maybe writing 
> `minio server http://host{1...n}/export{1...m} http://host{n+1...o}/export{1...m}`
> instead of 
> `minio server http://host{1...n}/export{1...m} http://host{1...o}/export{1...m}`
> help to understand it a lot better

Feel free to send a fix the doc
