### ISSUE TITLE
[incomplete] Access-Control-Allow-Origin: '*,*' ，browsers use has cors question

### ISSUE THREAD

**Issue by betate** [minio/minio#9935]
Browsers use to Api presignedPostPolicy info upload file
The server response headers
{
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Access-Control-Allow-Origin, DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range
Access-Control-Allow-Methods: POST, PUT,POST,GET,DELETE,OPTIONS
Access-Control-Allow-Origin: *, *
Access-Control-Max-Age: 1728000
Connection: keep-alive
Content-Length: 0
Date: Mon, 29 Jun 2020 03:03:32 GMT
Server: openresty/1.15.8.2
Vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
}
key: 'Access-Control-Allow-Origin' value Should be '*'
when key: 'Access-Control-Allow-Origin' not equals '*'
browsers CORS question,

**Comment by harshavardhana** [comment]
The issue is fully incomplete, the user has not used issue template.

There is no sample code or reproducible steps involved. 

Nothing actionable from our end.
