### ISSUE TITLE
[faq] standalone installation to distributed installation

### ISSUE THREAD

**Issue by zpavlig** [minio/minio#9936]
Hello.

Please tell me, is it possible to convert standalone installation to distributed installation, if there are already many files upload?

**Comment by nitisht** [comment]
@zpavlig  You'll need to manually mirror data to the new distributed cluster using `mc mirror` command https://docs.minio.io/docs/minio-client-complete-guide.html#mirror . Closing as answered.

**Comment by zpavlig** [comment]
i used mc mirror, files only copy to once server, files not found for distributed servers, and files not found for UI
