### ISSUE TITLE
Unable to put object using AWS S3 Java or .NET Client and version enabled bucket

### ISSUE THREAD

**Issue by RStapley** [minio/minio#9951]
## Expected Behavior

Trying this again, apologize if I am just dense and missing something big here. 

When putting an object into a versioned bucket it adds the object to the bucket.

## Current Behavior

I get an exception:
software.amazon.awssdk.services.s3.model.S3Exception: A header you provided implies functionality that is not implemented (Service: S3, Status Code: 501, Request ID: 161D6036D0CFAE23)

More stack trace: https://gist.github.com/RStapley/26fc475127d25653f1b607e380a38a1a

## Possible Solution

I may take a stab at looking into this, but am currently unfamiliar with the code.

## Steps to Reproduce (for bugs)

1. Make sure I have the master branch checked out:
```
RS025541@W1839171 MINGW64 ~/Documents/GitHub/minio (master)
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

2. Build the docker image:
```
RS025541@W1839171 MINGW64 ~/Documents/GitHub/minio (master)
$ docker build .
Sending build context to Docker daemon  22.74MB
Step 1/17 : FROM golang:1.13-alpine as builder
 ---> cea245765db1
Step 2/17 : LABEL maintainer="MinIO Inc <dev@min.io>"
 ---> Using cache
 ---> ecd0b012010f
Step 3/17 : ENV GOPATH /go
 ---> Using cache
 ---> f6a8c3331bf6
Step 4/17 : ENV CGO_ENABLED 0
 ---> Using cache
 ---> 219f1309408e
Step 5/17 : ENV GO111MODULE on
 ---> Using cache
 ---> afc9d574d0c5
Step 6/17 : RUN       apk add --no-cache git &&      git clone https://github.com/minio/minio && cd minio &&      git checkout master && go install -v -ldflags"$(go run buildscripts/gen-ldflags.go)"
 ---> Using cache
 ---> 6b97553224c9
Step 7/17 : FROM alpine:3.12
 ---> a24bb4013296
Step 8/17 : ENV MINIO_UPDATE off
 ---> Using cache
 ---> e38c5bdbac42
Step 9/17 : ENV MINIO_ACCESS_KEY_FILE=access_key     MINIO_SECRET_KEY_FILE=secret_key     MINIO_KMS_MASTER_KEY_FILE=kms_master_key     MINIO_SSE_MASTER_KEY_FILE=sse_master_key
 ---> Using cache
 ---> ca47d4546719
Step 10/17 : EXPOSE 9000
 ---> Using cache
 ---> 3f3046e3e770
Step 11/17 : COPY --from=builder /go/bin/minio /usr/bin/minio
 ---> Using cache
 ---> e2f5e5903720
Step 12/17 : COPY --from=builder /go/minio/CREDITS /third_party/
 ---> Using cache
 ---> 53eab419483b
Step 13/17 : COPY --from=builder /go/minio/dockerscripts/docker-entrypoint.sh /usr/bin/
 ---> Using cache
 ---> 8d36ddec5fad
Step 14/17 : RUN       apk add --no-cache ca-certificates 'curl>7.61.0' 'su-exec>=0.2' &&      echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >>/etc/nsswitch.conf
 ---> Using cache
 ---> cc233d792021
Step 15/17 : ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]
 ---> Using cache
 ---> 773a0b3ac16f
Step 16/17 : VOLUME ["/data"]
 ---> Using cache
 ---> 4cdac3d0d767
Step 17/17 : CMD ["minio"]
 ---> Using cache
 ---> c99f1cf65557
Successfully built c99f1cf65557
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
```

3. Run the docker image
```
RS025541@W1839171 MINGW64 ~/Documents/GitHub/minio (master)
$ docker run -p 9000:9000 c99f1cf65557 server /data
Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000

Browser Access:
   http://172.17.0.2:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
Detected default credentials 'minioadmin:minioadmin', please change the credentials immediately using 'MINIO_ACCESS_KEY' and 'MINIO_SECRET_KEY'
```

4. Run the .NET code https://github.com/RStapley/MinioBugExampleVersionedBucket

get an exception:
Amazon.S3.AmazonS3Exception: 'A header you provided implies functionality that is not implemented'

## Context

Trying to use Minio as a docker image to isolate my local development ecosystem from Amazon S3.

## Regression

No

## Your Environment

* Version used (`minio version`): Current Master
* Environment name and version (e.g. nginx 1.9.1): Java with Maven and .NET both running on Windows 10 with Docker desktop community 2.3.0.3
* Server type and version: 
* Operating System and version (`uname -a`): Windows 10 build 18363
* Link to your project: https://github.com/RStapley/MinioBugExampleVersionedBucket

**Comment by harshavardhana** [comment]
> Step 6/17 : RUN       apk add --no-cache git &&      git clone https://github.com/minio/minio && cd minio &&      git checkout master && go install -v -ldflags"$(go run buildscripts/gen-ldflags.go)"

You are missing the point @RStapley I already explained that you need to fix your Dockerfile to build from master. It is not building from the master. 

Please join our https://slack.min.io to ask these questions and we can help you.

**Comment by harshavardhana** [comment]
To run your program just run it again https://play.min.io our public server.

**Comment by harshavardhana** [comment]
Here are the credentials

```
mc config host list play
play
  URL       : https://play.minio.io
  AccessKey : Q3AM3UQ867SPQQA43P2F
  SecretKey : zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  API       : s3v4
  Lookup    : auto
```

**Comment by RStapley** [comment]
Thank you @harshavardhana. 

I am still misunderstanding the Dockerfile change as it looks like step 6 already has git checkout master as part of the run steps. 

Thank you for your help, I will post in the slack channel tomorrow.

**Comment by harshavardhana** [comment]
@RStapley also we do not support versioning with single disk mode so most probably that is the issue here. Just run MinIO with multiple disks by using multiple directories like this and it shall work. 

```
$ docker run -p 9000:9000 c99f1cf65557 server /data{1...4}
```

**Comment by RStapley** [comment]
@harshavardhana Thank you so much! 

I'll give this a try and see how it goes. I'll start with Slack from now on as well.
