### ISSUE TITLE
Use http://host{xxx...xxx}/export{xxx...xxx} http://host{xxx...xxx}/export{xxx...xxx}  mode to Extended cluster

### ISSUE THREAD

**Issue by ZhangXuYangSKR** [minio/minio#9953]
first,i used server 100 101,
`./minio server --address :9010 http://10.20.31.{100...101}/data/prod{1...4}`
 and upload some files,then i stoped minio,changed scripts on 100 101 
`./minio server --address :9010 http://10.20.31.{100...101}/data/prod{1...4} http://10.20.31.{144...145}/data/prod{1...4}`
When i start the script,server100and101 would report an error:Unable to initial backend:1st/2nd disk is already used in anthor erasure deployment.(xxxxxxx16,butxxxxxxxx8 format.json).Then quit...
Why there is an error？Is it because of version of minio ?Or it is supported from beginning,1st version？

**Comment by nitisht** [comment]
Please use issue template to report issues. It is not clear what are you trying and what is not working. Closing this issue.
