### ISSUE TITLE
[not our bug] ERROR when I Expanding existing distributed setup

### ISSUE THREAD

**Issue by ZhangXuYangSKR** [minio/minio#9954]
when I do as https://docs.min.io/docs/distributed-minio-quickstart-guide.html to Expanding existing distributed setup , report an error
First config is
```
export MINIO_ACCESS_KEY=12345678
export MINIO_SECRET_KEY=12345678
./minio server --address :9010 http://10.20.31.{100...101}/home/data/prod{1...4}
```
New config is
```
export MINIO_ACCESS_KEY=12345678
export MINIO_SECRET_KEY=12345678
./minio server --address :9010 http://10.20.31.{100...101}/home/data/prod{1...4} http://10.20.31.{144...145}/home/data/prod{1...4}
``` 
When I stopped 10.20.31.100,10.20.31.101,and used new config to start 10.20.31.100/101,10.20.31.144/145,then server 100/101 report  errors:
`ERROR Unable to initialize backend: 1st disk is already being used in another erasure deployment. (Number of disks specified: 16 but the number of disks found in the 1st disk's format.json: 8)`
`ERROR Unable to initialize backend: 2nd disk is already being used in another erasure deployment. (Number of disks specified: 816but the number of disks found in the 2nd disk's format.json: 8)`

**Comment by ZhangXuYangSKR** [comment]
sorry,the error is
`ERROR Unable to initialize backend: 1st disk is already being used in another erasure deployment. (Number of disks specified: 16 but the number of disks found in the 1st disk's format.json: 8)`
`ERROR Unable to initialize backend: 2nd disk is already being used in another erasure deployment. (Number of disks specified: 16 but the number of disks found in the 2nd disk's format.json: 8)`

**Comment by ZhangXuYangSKR** [comment]
I had changed source code at storage-rest-common.go,add a new const parameter in last const parameters
`storageRESTLastRenameFile="lastRenameFile"`
And changed storage-rest-server.go at resisterStorageRESTHandler methed,

`subrouter.Metheds(http.MethedPost).Path(SlashSeparator+storageRESTRenameFile).HandlerFunc(httpTraceHdrs(server.RenameFileHandler)).Queries(restQueries(storageRESTSrcVolume,storageRESTSrcPath,storageRESTDstVolume,storageRESTDstPath,storageRESTLastRenameFile)...)`

when i call methed StorageAPI.Renamefile to remote disk server,i would add the new const parameter in http,and the remote disk server receive http ,i would get the const parameter.

I think this will not affect the server's start.

**Comment by harshavardhana** [comment]
> I had changed source code at storage-rest-common.go,add a new const parameter in last const parameters
> `storageRESTLastRenameFile="lastRenameFile"`
> And changed storage-rest-server.go at resisterStorageRESTHandler methed,
> 
> `subrouter.Metheds(http.MethedPost).Path(SlashSeparator+storageRESTRenameFile).HandlerFunc(httpTraceHdrs(server.RenameFileHandler)).Queries(restQueries(storageRESTSrcVolume,storageRESTSrcPath,storageRESTDstVolume,storageRESTDstPath,storageRESTLastRenameFile)...)`
> 
> when i call methed StorageAPI.Renamefile to remote disk server,i would add the new const parameter in http,and the remote disk server receive http ,i would get the const parameter.
> 
> I think this will not affect the server's start.

@ZhangXuYangSKR if you modify code then you are on your own. We can't help you here.

You haven't provided much details on which version you are and what are you really trying to achieve.

**Comment by ZhangXuYangSKR** [comment]
OK.Can you tell me its starting process?And what will happen to the cluster expansion?Only process,I will do it myself.Thanks!

**Comment by ZhangXuYangSKR** [comment]
> > I had changed source code at storage-rest-common.go,add a new const parameter in last const parameters
> > `storageRESTLastRenameFile="lastRenameFile"`
> > And changed storage-rest-server.go at resisterStorageRESTHandler methed,
> > `subrouter.Metheds(http.MethedPost).Path(SlashSeparator+storageRESTRenameFile).HandlerFunc(httpTraceHdrs(server.RenameFileHandler)).Queries(restQueries(storageRESTSrcVolume,storageRESTSrcPath,storageRESTDstVolume,storageRESTDstPath,storageRESTLastRenameFile)...)`
> > when i call methed StorageAPI.Renamefile to remote disk server,i would add the new const parameter in http,and the remote disk server receive http ,i would get the const parameter.
> > I think this will not affect the server's start.
> 
> @ZhangXuYangSKR if you modify code then you are on your own. We can't help you here.
> 
> You haven't provided much details on which version you are and what are you really trying to achieve.

Fine.Can you tell me its starting process and what will happen to the cluster expansion？Only process,I will work on my own.Thanks

**Comment by ZhangXuYangSKR** [comment]
> > I had changed source code at storage-rest-common.go,add a new const parameter in last const parameters
> > `storageRESTLastRenameFile="lastRenameFile"`
> > And changed storage-rest-server.go at resisterStorageRESTHandler methed,
> > `subrouter.Metheds(http.MethedPost).Path(SlashSeparator+storageRESTRenameFile).HandlerFunc(httpTraceHdrs(server.RenameFileHandler)).Queries(restQueries(storageRESTSrcVolume,storageRESTSrcPath,storageRESTDstVolume,storageRESTDstPath,storageRESTLastRenameFile)...)`
> > when i call methed StorageAPI.Renamefile to remote disk server,i would add the new const parameter in http,and the remote disk server receive http ,i would get the const parameter.
> > I think this will not affect the server's start.
> 
> @ZhangXuYangSKR if you modify code then you are on your own. We can't help you here.
> 
> You haven't provided much details on which version you are and what are you really trying to achieve.

Once I find the cause of the problem, I will reply to you

**Comment by harshavardhana** [comment]
> Once I find the cause of the problem, I will reply to you

Closing this until then.
