### ISSUE TITLE
Cannot create bucket with object lock enabled

### ISSUE THREAD

**Issue by tspoeri** [minio/minio#9962]
I try to create a bucket using mc with object lock enabled but it fails.

## Expected Behavior
Executing 
```
mc mb --with-lock dev/bucket-with-lock
```
should create the bucket `bucket-with-lock`.

## Current Behavior
Creation of the bucket fails:
```
mc mb --with-lock dev/bucket-with-lock
mc: <ERROR> Unable to make bucket `dev/bucket-with-lock`. A header you provided implies functionality that is not implemented
```

## Context
Creating a bucket with object lock enabled is a prerquisite for locking objects as described here: https://github.com/minio/minio/tree/master/docs/retention

## Your Environment
MinIO running as Docker container on Ubuntu 20.04 LTS

```
uname -a
Linux ubuntu-dev 5.4.0-39-generic #43-Ubuntu SMP Fri Jun 19 10:28:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

docker --version
Docker version 19.03.8, build afacb8b7f0

mc --version
mc version RELEASE.2020-06-26T19-56-55Z

mc admin info dev
●  localhost:9000
   Uptime: 2 hours 
   Version: 2020-07-02T00:15:09Z
   Network: 1/1 OK 

```

**Comment by kannappanr** [comment]
@tspoeri object locking is not supported in `fs` mode. You need to use erasure-coded mode to use the locking feature.

**Comment by tspoeri** [comment]
@kannappanr  I'm new to MinIO, is there a documentation which lists limitations depending on modes, etc? 
At first sight it's not clear to me why locks depend on erasure-coded mode.

**Comment by harshavardhana** [comment]
> @kannappanr I'm new to MinIO, is there a documentation which lists limitations depending on modes, etc?
> At first sight it's not clear to me why locks depend on erasure-coded mode.

FS mode think of it as minimal implementation, erasure coded is full fledged
