### ISSUE TITLE
memory consumption problem

### ISSUE THREAD

**Issue by Goatmaster** [minio/minio#9966]
Hey, 

I have a problem with MinIO. I run the MinIO version RELEASE.2020-06-22T03-12-50Z on a Debian10 virtual machine.

My problem ist that MinIO consumes all the memory of the virtual machine. I tried it with 32GB and 64GB of RAM but after 3-4 days the memory is completly used. Users than start to get problems. For example they can't reach the MinIO server or the buckets where not shown.

There is a swap partition on the virtual machine but it doesn't get used by MinIO. 

My idea was to use another distribution (CentOS) and see if I have the same problem there.

Is there any solution or fix for the problem or am I the only one with this behaviour?

## My Environment
- minio version: RELEASE.2020-06-22T03-12-50Z 
- debian10
- around 40 buckets (108GB used)
- it runs on a single minio instance
- nginx reverse proxy (v1.10.3) on another server (debian10)

**Comment by klauspost** [comment]
Once the server has gobbled up a good amount of RAM could you try to run a  `mc admin profile start --type=cpu,mem myminio` and shortly after a `mc admin profile stop myminio` and attach the downloaded zip file here?

**Comment by harshavardhana** [comment]
> Once the server has gobbled up a good amount of RAM could you try to run a `mc admin profile start --type=cpu,mem myminio` and shortly after a `mc admin profile stop myminio` and attach the downloaded zip file here?

Also explain your setup in a bit more detail @Goatmaster .  The entire issue template left out without any information regarding your application, operating system etc.

**Comment by Goatmaster** [comment]
> > Once the server has gobbled up a good amount of RAM could you try to run a `mc admin profile start --type=cpu,mem myminio` and shortly after a `mc admin profile stop myminio` and attach the downloaded zip file here?
> 
> Also explain your setup in a bit more detail @Goatmaster . The entire issue template left out without any information regarding your application, operating system etc.

There are informations about the setup in the issue. What more information do you need?

**Comment by klauspost** [comment]
@Goatmaster Number of disks, number of servers. Number of buckets, no of files in buckets would also help.

Please run the profile. Otherwise we will be unable to help.

**Comment by Goatmaster** [comment]
> @Goatmaster Number of disks, number of servers. Number of buckets, no of files in buckets would also help.
> 
> Please run the profile. Otherwise we will be unable to help.

Updated the details in the first post.

**Comment by harshavardhana** [comment]
> Updated the details in the first post.

We need the profile output @Goatmaster not provided yet. 

> * around 40 buckets (108GB used)

This doesn't make sense to run out of memory.

**Comment by klauspost** [comment]
@Goatmaster I don't see any profiles there?

@harshavardhana It is possible with a huge amount of objects not that deeply nested. I just want to confirm it.

**Comment by harshavardhana** [comment]
> @Goatmaster I don't see any profiles there?
> 
> @harshavardhana It is possible with a huge amount of objects not that deeply nested. I just want to confirm it.

@klauspost not really possible, we don't even know what operations were performed it's not mentioned in the issue.

**Comment by klauspost** [comment]
@harshavardhana The crawler makes that possible.

**Comment by harshavardhana** [comment]
> @harshavardhana The crawler makes that possible.

yeah but 104GiB? that's like if there were 1KiB files.

**Comment by klauspost** [comment]
Something like it. But either way a profile could tell us instead of having to guess. Can't do anything until we get a profile.

**Comment by yilezhu** [comment]
Hi,Friend, have you solved your problem? I also encountered the same problem, I used docker mode to run Minio, but Minio occupied too much memory!

**Comment by harshavardhana** [comment]
> Hi,Friend, have you solved your problem? I also encountered the same problem, I used docker mode to run Minio, but Minio occupied too much memory!

As mentioned help us help you profile us the memory profile @yilezhu

**Comment by yilezhu** [comment]
This may be due to the object caching mechanism of Minio. It seems that the configuration of object cache cannot be customized. There are good ways to solve this problem？ @harshavardhana 
![image](https://user-images.githubusercontent.com/18655233/87500131-5744be00-c68e-11ea-88eb-5b2dc459c54c.png)

**Comment by harshavardhana** [comment]
> This may be due to the object caching mechanism of Minio. It seems that the configuration of object cache cannot be customized. There are good ways to solve this problem？ @harshavardhana
> ![image](https://user-images.githubusercontent.com/18655233/87500131-5744be00-c68e-11ea-88eb-5b2dc459c54c.png)

please share the profile @yilezhu use `mc admin profile --type mem` - lets not speculate

**Comment by Goatmaster** [comment]
> 
> 
> @Goatmaster Number of disks, number of servers. Number of buckets, no of files in buckets would also help.
> 
> Please run the profile. Otherwise we will be unable to help.

The command is not working for me.

![minio](https://i.imgur.com/k0bxhvi.png)

I am using minio with the startup script.

```
https://raw.githubusercontent.com/minio/minio-service/master/linux-systemd/minio.service
```

**Comment by MikeGoltsov** [comment]
I have similar problem. On 4 node (6 disk per node) installation I was seen 90G memory consumption. I have try to do profiling, but in that period mem utilisation was around 9-12G. 
[profile.zip](https://github.com/minio/minio/files/4936668/profile.zip)
[profile2.zip](https://github.com/minio/minio/files/4936674/profile2.zip)

**Comment by MikeGoltsov** [comment]
@harshavardhana 
On newest release I still have this problem. On minio-2 node about 8G memory used.
minio-u+  697129  157  3.0 9178484 7999384 ?     Ssl  16:24  29:55 /opt/minio/minio server https://minio-{1...4}.ok.loc/data/minio/data{1...6}/minio
[profile.zip](https://github.com/minio/minio/files/4960324/profile.zip)

**Comment by creker** [comment]
Looking at all profiles we've captured recently they all look the same - all the memory is being consumed by different sync.Pool's. Maybe minio should switch to a different implementation that can be bounded? sync.Pool is unbounded and theoretically can grow as much as it wants. Coupled with general inability to bound Go's heap size this sometimes leads to Go consuming all memory starving everyone else and ultimately being killed by OOM.

**Comment by harshavardhana** [comment]
sync.Pool is automatically cleared when they are not used, the GC cycle is governed Go's runtime if you have lower memory but higher concurrency requirement then either use a system with higher RAM or use GC value to trigger GC faster. If the memory doesn't go down then we have a leak if it does with GC change then we know it's just a GC cycle issue and that your hardware config is not capable for the concurrency requirements that you have.

The original issue of memory consumption is fixed, which was related to some leaking goroutines in listing operation.

Any other memory related issue let's stick to opening newer issues and with proper reproducers.

Going to lock further discussion here.
