### ISSUE TITLE
Allow setting a config directory directly

### ISSUE THREAD

**Issue by fd0** [minio/minio#997]
It is not possible to specify a config directory, on Linux minio insists on using `.minio` in the current user's home directory. This fails when minio is run as user `nobody` on my system, because that user's home directory is `/` and minio is not allowed to create `/.minio`. Apart from abusing the workaround for docker images and setting `DOCKERIMAGE=1` so that minio uses the current working directory, I did not find a way to set the dir.

I think it would be very nice to be able to configure the configuration directory, e.g. by setting an environment variable (e.g. `MINIO_CONFIG_DIR`), and falling back to the current user's home directory if the environment variable is not set.

I do not understand why you're collecting lots of information on the current user in `userCurrent()`, but only ever access the `HomeDir` string of the returned struct. This could be nicely cleaned up and even replace the `DOCKERIMAGE` workaround.

In addition, the function `userCurrent` even exists twice: https://github.com/minio/minio/blob/master/pkg/fs/config.go#L33 and https://github.com/minio/minio/blob/master/utils.go#L63

Are you interested in a PR that cleans this up a bit?

**Comment by harshavardhana** [comment]
> In addition, the function userCurrent even exists twice: https://github.com/minio/minio/blob/master/pkg/fs/config.go#L33 and https://github.com/minio/minio/blob/master/utils.go#L63

This has to be cleaned up, the problem is fs and top level both needs to access `.minio` directory. 

> I think it would be very nice to be able to configure the configuration directory, e.g. by setting an environment variable (e.g. MINIO_CONFIG_DIR), and falling back to the current user's home directory if the environment variable is not set.

This is a nice idea but generally against config directories to be set this way, it is perhaps better to implement `--config-folder` 

> setting DOCKERIMAGE=1 so that minio uses the current working directory, I did not find a way to set the dir.

DOCKERIMAGE flag is still needed to know if the current user is 'root' - only in case of docker its allowed. 

> Are you interested in a PR that cleans this up a bit?

It gets little tricky, let me give you a proper solution.

**Comment by harshavardhana** [comment]
You can set new config-folder now with `minio --config-folder <your_new_folder>` - let me know if this works for you @fd0 

You have to download the master repo.

**Comment by fd0** [comment]
Thanks, I'll have a look.
