### ISSUE TITLE
MINIO + STS https://github.com/minio/minio/blob/master/docs/sts/web-identity.md Issue.

### ISSUE THREAD

**Issue by PSHREYASHOLLA** [minio/minio#9976]
## Current Behavior
Trying to implement MINIO + STS from https://github.com/minio/minio/blob/master/docs/sts/web-identity.md Issue,
https://accounts.google.com/.well-known/openid-configuration certificate is copied to \.minio\certs\CAs
Starting the server as,
set MINIO_ACCESS_KEY=minioadmin
set MINIO_SECRET_KEY=minioadmin
set MINIO_IDENTITY_OPENID_CONFIG_URL=https://accounts.google.com/.well-known/openid-configuration
set MINIO_IDENTITY_OPENID_CLIENT_ID=843351d4-1080-11ea-aa20-271ecba3924a
minio server E:\FilePath

But most of times server fails to connect to OpenID saying,
Error: Unable to initialize OpenID: Get https://accounts.google.com/.well-known/openid-configuration: x509: certificate signed by unknown authority

## Steps to Reproduce (for bugs)

1.Starting the server as,
set MINIO_ACCESS_KEY=minioadmin
set MINIO_SECRET_KEY=minioadmin
set MINIO_IDENTITY_OPENID_CONFIG_URL=https://accounts.google.com/.well-known/openid-configuration
set MINIO_IDENTITY_OPENID_CLIENT_ID=843351d4-1080-11ea-aa20-271ecba3924a
minio server E:\FilePath
2.
3.
4.

## Your Environment

* Version used (`minio version`):minio.RELEASE.2020-05-08T02-40-49Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):Windows 10
* Link to your project:

**Comment by klauspost** [comment]
@PSHREYASHOLLA  Please use the provided template and fill out the information requested there.

**Comment by PSHREYASHOLLA** [comment]
@klauspost 
Have updated the same, please let me know if you need more details.

**Comment by harshavardhana** [comment]
You need to trust the openid public cert

> But most of times server fails to connect to OpenID saying,
> Error: Unable to initialize OpenID: Get https://accounts.google.com/.well-known/openid-configuration: x509: certificate signed by unknown authority

All you need to do is put the public cert from the Google endpoint to `.minio/certs/CAs`  this simply shows that your Windows setup has outdated trusted public certs.

Alternatively use a Linux system or in containers which is comes with proper updated certs..

**Comment by kannappanr** [comment]
@PSHREYASHOLLA Closing this issue as answered. Please feel free to reach out to us if you still have issues.

**Comment by PSHREYASHOLLA** [comment]
@harshavardhana @kannappanr  As per comments I will try on Linux and get back. But What is the problem with Windows here? Can you elaborate bit? 
And as mentioned in issue description, I have already copied the certificates to .minio/certs/CAs

**Comment by PSHREYASHOLLA** [comment]
Windows?

**Comment by harshavardhana** [comment]
> https://accounts.google.com/.well-known/openid-configuration certificate is copied to .minio\certs\CAs

First of all, it shows that your windows to be pretty outdated because it is not even able to trust the `accounts.google.com` which is a public domain. So you have to resort to copying its public cert,  which should be in `--certs-dir`. 

So it may be that it's not correctly copied to the right location.

With this outdated nature, what is the point of using this operating system? either upgrade your Windows or Linux which will work always.

**Comment by PSHREYASHOLLA** [comment]
Hi Harshavardhana,

Let me answer your concerns on OS first, the system we are speaking about has windows 10 Enterprise which is the latest version of windows OS available, so there is no point of upgrade here. So can you please let me know why is minio failing to read certificate?

 And as I mentioned before the certificates are copied to  %%USERPROFILE%%\.minio\certs\CAs folder. Let me know if this if the location is not proper?

And as per your suggestion will test on linux machine as well and share the results.

**Comment by harshavardhana** [comment]
> Let me answer your concerns on OS first, the system we are speaking about has windows 10 Enterprise which is the latest version of windows OS available, so there is no point of upgrade here. So can you please let me know why is minio failing to read certificate?
> 
> And as I mentioned before the certificates are copied to %%USERPROFILE%%.minio\certs\CAs folder. Let me know if this if the location is not proper?

If you are using the latest Windows, then either the installation is broken or the certs are somehow not available for the user you are trying to run. 

> * Version used (`minio version`):minio.RELEASE.2020-05-08T02-40-49Z

Have you tried upgrading MinIO before opening this issue?

**Comment by PSHREYASHOLLA** [comment]
Yes tried with version: 2020-07-02T00:15:09Z. Logs below,

Attempting encryption of all config, IAM users and policies on MinIO backend

API: SYSTEM()
Time: 01:11:26 IST 07/08/2020
DeploymentID: bd96ac01-e399-4ff5-a6e7-c99960265cc9
Error: Unable to initialize OpenID: Get https://accounts.google.com/.well-known/openid-configuration: x509: certificate signed by unknown authority
       8: github.com\minio\minio@\cmd\config-current.go:431:cmd.lookupConfigs()
       7: github.com\minio\minio@\cmd\config-current.go:583:cmd.newSrvConfig()
       6: github.com\minio\minio@\cmd\config-migrate.go:2466:cmd.migrateConfigToMinioSys()
       5: github.com\minio\minio@\cmd\config.go:234:cmd.initConfig()
       4: github.com\minio\minio@\cmd\config.go:209:cmd.(*ConfigSys).Init()
       3: github.com\minio\minio@\cmd\server-main.go:319:cmd.initAllSubsystems()
       2: github.com\minio\minio@\cmd\server-main.go:244:cmd.initSafeMode()
       1: github.com\minio\minio@\cmd\server-main.go:512:cmd.serverMain()

API: SYSTEM()
Time: 01:11:27 IST 07/08/2020
DeploymentID: bd96ac01-e399-4ff5-a6e7-c99960265cc9
Error: Unable to initialize OpenID: Get https://accounts.google.com/.well-known/openid-configuration: x509: certificate signed by unknown authority
       7: github.com\minio\minio@\cmd\config-current.go:431:cmd.lookupConfigs()
       6: github.com\minio\minio@\cmd\config-current.go:607:cmd.loadConfig()
       5: github.com\minio\minio@\cmd\config.go:249:cmd.initConfig()
       4: github.com\minio\minio@\cmd\config.go:209:cmd.(*ConfigSys).Init()
       3: github.com\minio\minio@\cmd\server-main.go:319:cmd.initAllSubsystems()
       2: github.com\minio\minio@\cmd\server-main.go:244:cmd.initSafeMode()
       1: github.com\minio\minio@\cmd\server-main.go:512:cmd.serverMain()
Endpoint:  http://169.254.112.212:9000  http://192.168.1.149:9000  http://169.254.188.146:9000  http://127.0.0.1:9000
AccessKey: minioadmin
SecretKey: minioadmin

Browser Access:
   http://169.254.112.212:9000  http://192.168.1.149:9000  http://169.254.188.146:9000  http://127.0.0.1:9000

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc.exe config host add myminio http://169.254.112.212:9000 minioadmin minioadmin

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

**Comment by PSHREYASHOLLA** [comment]
@harshavardhana @klauspost , As mentioned earlier sometimes the server configuration with OpenID works and sometimes it gives un trusted certificate. But when the server connects, UI login with OpenID is working but post request mentioned in https://github.com/minio/minio/blob/master/docs/sts/web-identity.md, which is http://minio.cluster:9000?Action=AssumeRoleWithWebIdentity&DurationSeconds=3600&WebIdentityToken=eyJ4NXQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0RKaFpXSTRORE5sWkRVMU9HRmtOakZpTVEiLCJraWQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0RKaFpXSTRORE5sWkRVMU9HRmtOakZpTVEiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJQb0VnWFA2dVZPNDVJc0VOUm5nRFhqNUF1NVlhIiwiYXpwIjoiUG9FZ1hQNnVWTzQ1SXNFTlJuZ0RYajVBdTVZYSIsImlzcyI6Imh0dHBzOlwvXC9sb2NhbGhvc3Q6OTQ0M1wvb2F1dGgyXC90b2tlbiIsImV4cCI6MTU0MTgwOTU4MiwiaWF0IjoxNTQxODA1OTgyLCJqdGkiOiI2Y2YyMGIwZS1lNGZmLTQzZmQtYTdiYS1kYTc3YTE3YzM2MzYifQ.Jm29jPliRvrK6Os34nSK3rhzIYLFjE__zdVGNng3uGKXGKzP3We_i6NPnhA0szJXMOKglXzUF1UgSz8MctbaxFS8XDusQPVe4LkB_45hwBm6TmBxzui911nt-1RbBLN_jZIlvl2lPrbTUH5hSn9kEkph6seWanTNQpz9tNEoVa6R_OX3kpJqxe8tLQUWw453A1JTwFNhdHa6-f1K8_Q_eEZ_4gOYINQ9t_fhTibdbkXZkJQFLop-Jwoybi9s4nwQU_dATocgcufq5eCeNItQeleT-23lGxIz0X7CiJrJynYLdd-ER0F77SumqEb5iCxhxuf4H7dovwd1kAmyKzLxpw&Version=2011-06-15,
Gives below error,
```
<?xml version="1.0" encoding="UTF-8"?>
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
    <Error>
        <Type></Type>
        <Code>InvalidParameterValue</Code>
        <Message>crypto/rsa: verification error</Message>
    </Error>
    <RequestId>161FB922BCC96904</RequestId>
</ErrorResponse>
```

**Comment by PSHREYASHOLLA** [comment]
@kannappanr @klauspost @harshavardhana  SHould I raise a new issue for the above?
