### ISSUE TITLE
[wont fix] Push to docker registry fails when using minio azure gateway due to empty ListMultipartUploads

### ISSUE THREAD

**Issue by tpresa** [minio/minio#9978]
Push to docker registry fails when using minio azure gateway, apparently due to the empty ListMultipartUploads.

I'm creating this as an issue request because I'm aware that the empty ListMultipartUploads is [a design decision](https://github.com/minio/minio/issues/7632#issuecomment-490959779). Apparently that decision assumes that the only known applications use that endpoint. The [docker registry uses that endpoint](https://github.com/docker/distribution/blob/244d5246c2f193d50b2f8fd220784958a5e1318b/registry/storage/driver/s3-aws/s3.go#L578), which I think should prompt a review of the design decision.

Please let me know of details you might need, I have the failing setup configured, so I should be able to gather that quickly.

Reproduced using docker image 4b618ba3d1ab

**Comment by harshavardhana** [comment]
@tpresa it is advised that you use azure storage backend directly, we have no plans to implement ListMultipartUploads emulation for azure gateway.

**Comment by harshavardhana** [comment]
> @tpresa it is advised that you use azure storage backend directly, we have no plans to implement ListMultipartUploads emulation for azure gateway.

It is preferred that you use azure storage https://docs.docker.com/registry/storage-drivers/azure/ directly, there is no point using an S3 emulation of azure for docker registry.

Implementing ListMultipartUploads() will lead to complicated code, so we have purposefully left it blank - if you must feel free to send a PR yourself. But we won't be able to work on this in the near future.
