### ISSUE TITLE
CORS headers not sent (RELEASE.2020-07-02T00-15-09Z)

### ISSUE THREAD

**Issue by francisfontoura** [minio/minio#9979]
## Expected Behavior

PUT request to presigned URL started by fetch API (browser) from another origin working.

## Current Behavior

Request not working because CORS headers are absent.

## Possible Solution

I don't know.

## Steps to Reproduce (for bugs)

1. Generate presigned PUT URL for an object.
2. Try to upload a file from browser with fetch API.

## Context

Web application of mine that uses a presigned URL to upload a file to server.

## Regression

I don't know.

## Your Environment

* Version used (`minio version`): RELEASE.2020-07-02T00-15-09Z
* Environment name and version (e.g. nginx 1.9.1): Docker 19.03.12, Traefik 2.2.1
* Server type and version:
* Operating System and version (`uname -a`): Ubuntu 18.04.4 LTS Linux 4.15.0-106-generic x86_64
* Link to your project:

**Comment by harshavardhana** [comment]
@francisfontoura the issue exists because of from handler re-ordering.
