### ISSUE TITLE
[working as intended] JWT Support Group to Group mapping

### ISSUE THREAD

**Issue by JakeNeyer** [minio/minio#9985]
**Is your feature request related to a problem? Please describe.**
Having to extend JWTs to non-standard claims, using `policy` makes configuration of STS complicated.

**Describe the solution you'd like**
It would be nice to be able to have a group to group mapping of JWT `groups` to minio groups wherein policies can be created and attached to minio groups.

**Describe alternatives you've considered**
Extending (specifically Dex) to support non-standard claims is potentially an option.

**Comment by harshavardhana** [comment]
> Having to extend JWTs to non-standard claims, using `policy` makes configuration of STS complicated.

You can set that to whatever name you can with these configuration settings, I don't know if you looked at our documentation

```
~ mc admin config set play/ identity_openid --env
KEY:
identity_openid  enable OpenID SSO support

ARGS:
MINIO_IDENTITY_OPENID_CONFIG_URL*   (url)       openid discovery document e.g. "https://accounts.google.com/.well-known/openid-configuration"
MINIO_IDENTITY_OPENID_CLIENT_ID     (string)    unique public identifier for apps e.g. "292085223830.apps.googleusercontent.com"
MINIO_IDENTITY_OPENID_CLAIM_NAME    (string)    JWT canned policy claim name, defaults to "policy"
MINIO_IDENTITY_OPENID_CLAIM_PREFIX  (string)    JWT claim namespace prefix e.g. "customer1/"
MINIO_IDENTITY_OPENID_SCOPES        (csv)       Comma separated list of OpenID scopes for server, defaults to advertised scopes from discovery document e.g. "email,admin"
MINIO_IDENTITY_OPENID_COMMENT       (sentence)  optionally add a comment to this setting
```

One is you can set a custom name and another is to set a custom prefix

```
MINIO_IDENTITY_OPENID_CLAIM_NAME    (string)    JWT canned policy claim name, defaults to "policy"
MINIO_IDENTITY_OPENID_CLAIM_PREFIX  (string)    JWT claim namespace prefix e.g. "customer1/"
```

**Comment by harshavardhana** [comment]
> It would be nice to be able to have a group to group mapping of JWT `groups` to minio groups wherein policies can be created and attached to minio groups.

This won't workgroups have no permissions by default, permissions have to be implied using policies alone. Map your policies to groups if necessary but you shouldn't interfere with `mc admin group` with OpenID they are not meant to be of the same world.

**Comment by harshavardhana** [comment]
> Extending (specifically Dex) to support non-standard claims is potentially an option.

Almost all OpenID identity managers either support custom claims - it is even part of the standard OpenID specification so I am not sure why it is not implemented.

**Comment by harshavardhana** [comment]
From the current solution that we provide sufficiently addresses all required use cases, we have dozens of deployment already using the existing features with similar requirements such as using `roles` instead of `policy` as they keyName in JWT from Azure AD IDP. 

Will close this issue as its sufficiently fixed.

**Comment by UchihaYuki** [comment]
I'm using keycloak and minio now. I think supporting custom jwt claims is necessary.

The only way I can control user access is through policy claim, which means I have to assign different policies to different users. For customer-facing applications, the state of users might change, for example, if a user buys a vip membership for a month, the user will get more access to minio then get less after a month. I can achieve this easily by use a custom jwt claims, jwt:vip=time-when-vip-expires, without it I have to traverse through user database to update policy for them daily, even hourly if I'd like to get more accurate control.
