### ISSUE TITLE
Sync/mutex maxClients [Crash]

### ISSUE THREAD

**Issue by FirKys** [minio/minio#9991]
Error: timed out. some connections are still active. doing abnormal shutdown. goroutines written to
Error description here: https://pastebin.com/fFMKBqCv

## Expected Behavior
The server continues to work at high load, but does not crash (just not save a file)

## Current Behavior
Server freezes, further requests do not work

## Steps to Reproduce (for bugs)

1. Start minio server in docker 
2. Use +10 processes on different hosts
3. Just copy pictures via s3hs (2-6 pic every 2-6 sec)
4. Get Crash

## Context

I have about 5 hosts, on each 3-4 containers that use s3fs. 
After a while I get an error, everything stops working.

What should I do next, start new minio server (two server minio)?
Using the restrictions from the minio documentation, the server continues to fall..

## Your Environment

* Version used (`minio version`): https://hub.docker.com/layers/minio/minio/latest/images/sha256-843af0cdb0fc90ad3f0cf40023f187cfc8dde5022dc355cbd3cd85c92f074516?context=explore
* Operating System and version (`uname -a`): Linux TestHostDelta007 4.4.0-185-generic #215-Ubuntu SMP Mon Jun 8 21:53:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
Thanks for the report! 

I have found a potential race in the affected code.
