### ISSUE TITLE
minIO returns an Error for OPTIONS request

### ISSUE THREAD

**Issue by FreeG** [minio/minio#9993]
when sending an HTTP OPTIONS request to minio for a given resource, XMinioUnknownAPIRequest is returned.

## Expected Behavior
when sending the very same request to Amazon S3 HTTP200 with the requested data is returned:
Example here:

------------- REQUEST S3 -------------
OPTIONS http://SomeBucket.SomeRegion.amazonaws.com/some/path/to/my/file.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200708T105201Z&X-Amz-SignedHeaders=content-md5%3Bhost&X-Amz-Expires=300&X-Amz-Credential=Some_Credentials%2FSomeRegion%2Fs3%2Faws4_request&X-Amz-Signature=SomeSignatur HTTP/1.1
Host: SomeBucket.SomeRegion.amazonaws.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
Accept: */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Access-Control-Request-Method: PUT
Access-Control-Request-Headers: content-md5,content-type,x-csrf-token
Referer: http://localhost:8080/SomePath
Origin: http://localhost:8080
Connection: keep-alive

------------- RESPONSE S3 -------------
#HTTP/1.1 200 OK
x-amz-id-2: SomeAmazonId
x-amz-request-id: SomeRequestId
Date: Wed, 08 Jul 2020 10:52:03 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, PUT, POST
Access-Control-Allow-Headers: content-md5, content-type, x-csrf-token
Vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method
Content-Length: 0
Server: AmazonS3

## Current Behavior
But minio returns an error.
Example here:

OPTIONS http://localhost:9000/some/path/to/my/file.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200708T110556Z&X-Amz-SignedHeaders=content-md5%3Bhost&X-Amz-Expires=300&X-Amz-Credential=Some_Credential%2FSomeRegion%2Fs3%2Faws4_request&X-Amz-Signature=SomeSignatur HTTP/1.1
Host: localhost:9000
Connection: keep-alive
Accept: */*
Access-Control-Request-Method: PUT
Access-Control-Request-Headers: content-md5,content-type,x-csrf-token
Origin: http://localhost:8080
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-Fetch-Dest: empty
Referer: http://localhost:8080/SomePath
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7

------------- RESPONSE MINIO -------------

HTTP/1.1 400 Bad Request
Accept-Ranges: bytes
Content-Length: 387
Content-Type: application/xml
Server: MinIO/RELEASE.2020-07-02T00-15-09Z
Date: Wed, 08 Jul 2020 11:05:56 GMT

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioUnknownAPIRequest</Code><Message>Unknown API request at /some/path/to/my/file.jpeg</Message><Resource>/some/path/to/my/file.jpeg</Resource><RequestId></RequestId><HostId>SomeHostId</HostId></Error>

## Steps to Reproduce (for bugs)
See Current Behaviour

## Context
Due to this issue it is no longer possible to upload data to minio within our software. We are using uppy and it seems like it is depends on the OPTIONS requests

## Your Environment
minio via console
* Version used (`RELEASE.2020-07-02`):
* Operating System and version (`Windows 10`):

**Comment by klauspost** [comment]
API: https://docs.aws.amazon.com/AmazonS3/latest/API/RESTOPTIONSobject.html

**Comment by flashspys** [comment]
The last update of minio bricked our uploading, too. We're using presigned put request, so the browser can upload sth in minio, and the preflight for the PUT request is failing.

@klauspost could you please add some more information to your answer, if this is meant as a solution to this problem?

**Comment by FreeG** [comment]
i noticed the following error message in the browsers log 

Access to XMLHttpRequest at 'http://localhost:9000/path/to/my/file?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200708T133819Z&X-Amz-SignedHeaders=content-md5%3Bhost&X-Amz-Expires=300&X-Amz-Credential=SomeCredential%2FSomeRegion%2Fs3%2Faws4_request&X-Amz-Signature=SomeSignature' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by klauspost** [comment]
@flashspys 

That doesn't seem related to the issue. If I read the issue correct this call has never been supported and as such is a feature request as far as I can tell. 

@FreeG What relation does that have to the issue?

**Comment by flashspys** [comment]
No, this is one single issue. In minio/minio:RELEASE.2020-07-02T00-15-09Z the cors response of presigned-PUT requests is broken. This worked at least until minio/minio:RELEASE.2020-06-22T03-12-50Z ! 

As @FreeG stated correctly: The CORS handling of AWS S3  works correctly, Minio's doesn't. As a result of the broken cors response, the browser does not send the file to minio, as shown in this error message.

**Comment by harshavardhana** [comment]
This is fixed in #9980 , will be available in next release.
