### ISSUE TITLE
[not our bug] sts.AssumeRoleWithWebIdentity - Do not have enough permissions to access this resource on Minio Brwoser

### ISSUE THREAD

**Issue by widdix123** [minio/minio#9998]
I am able to login to the browser using OIDC . The page gets displayed however the buckets that are created does not show up in the list 

![image](https://user-images.githubusercontent.com/38529736/87012836-62f43880-c1e7-11ea-90e9-7ed9b6e0c74a.png)

## Expected Behavior

I should be able to see the buckets , run upload file, create bucket etc 

![image](https://user-images.githubusercontent.com/38529736/87013081-c1211b80-c1e7-11ea-89e9-6517d72503e5.png)

The group Id in JWT should allow be to have a readonly /readwrite  from JWT token

## Current Behavior

**With accessKey and secretKey**

![image](https://user-images.githubusercontent.com/38529736/87013081-c1211b80-c1e7-11ea-89e9-6517d72503e5.png)

## Steps to Reproduce (for bugs)

1. deploy minio on EKS 1.6
2. port-forwarding of service to access the minio browser on localhost:9000

## Your Environment

* Version used (`minio version`):  RELEASE.2020-07-02T00-15-09Z 
* Environment name and version (e.g. nginx 1.9.1): - EKS 1.6
* Server type and version: - Kubernetes
* Operating System and version (`uname -a`): Amazon Linux
* Link to your project:

**Comment by widdix123** [comment]
I am able to see 200 stautus but no buckets are displayed to it . This needs to be on prod , can you please check this urgently 


07:37:10.620 [200 OK] sts.AssumeRoleWithWebIdentity localhost:9000/?Action=AssumeRoleWithWebIdentity&Version=2011-06-15&WebIdentityToken=eyJhbGciOiJSUzI1NiIsImtpZCI6ImFmNzJiYjk0ZThlMzk2NGViZmQwNGE2OTkxN2E1ODI3Y2FkZWIzMWYifQ.asdfsdfsfsafsafsadfsd.T0dsjdaPGCUbCQwtnuEO1SXw_prsL_s0vm2qW5tjgjLAtPGRK0svrg0A8iUiflzZEyl8LUQLhWSqAGwtUO6tXc0RnJG6tARphYfM8UCCNU21nROpbrCQ25bGtrtGH_SXyKnEVI9aQ_jg6Ew5KtANSBxwrp-sfsadfsfsdsadfsadfasd  127.0.0.1         188.917ms    ↑ 31 B ↓ 1.8 KiB

**Comment by widdix123** [comment]
@harshavardhana  - Can you please suggest ?

**Comment by harshavardhana** [comment]
> Go to Clients -> Client on account -> Mappers -> Create, Name can be any text, Mapper Type is User Attribute, User Attribute is policy, Token Claim Name is policy, Claim JSON Type is string, then Save.

First, you need to make sure you have added the policy as part of the custom JWT claim have you done that? @widdix123 without a policy there is no access granted by default. 

> I am able to see 200 stautus but no buckets are displayed to it . This needs to be on prod , can you please check this urgently

If this is in production and if you need production support with SLA - please look at our subscription for more information https://min.io/pricing

**Comment by widdix123** [comment]
@harshavardhana  - Thanks but is there something for Dex ? We currently are using Dex and not KeyClock .

I will bring up with my management for the SLA. Thanks for letting me know we definitely would want to explore it too :)

**Comment by harshavardhana** [comment]
> @harshavardhana - Thanks but is there something for Dex ? We currently are using Dex and not KeyClock .

Dex need to support custom claims for JWT @widdix123

**Comment by harshavardhana** [comment]
@widdix123 you can use  https://github.com/dexidp/dex/blob/master/Documentation/custom-scopes-claims-clients.md

You can set `groups` as your policy claim name for MinIO

```
mc admin config set play/ identity_openid --env
KEY:
identity_openid  enable OpenID SSO support

ARGS:
MINIO_IDENTITY_OPENID_CONFIG_URL*   (url)       openid discovery document e.g. "https://accounts.google.com/.well-known/openid-configuration"
MINIO_IDENTITY_OPENID_CLIENT_ID     (string)    unique public identifier for apps e.g. "292085223830.apps.googleusercontent.com"
MINIO_IDENTITY_OPENID_CLAIM_NAME    (string)    JWT canned policy claim name, defaults to "policy"
MINIO_IDENTITY_OPENID_CLAIM_PREFIX  (string)    JWT claim namespace prefix e.g. "customer1/"
MINIO_IDENTITY_OPENID_SCOPES        (csv)       Comma separated list of OpenID scopes for server, defaults to advertised scopes from discovery document e.g. "email,admin"
MINIO_IDENTITY_OPENID_COMMENT       (sentence)  optionally add a comment to this setting
```

From their sample JWT
```
{
  "iss": "http://127.0.0.1:5556/dex",
  "sub": "CgcyMzQyNzQ5EgZnaXRodWI",
  "aud": "example-app",
  "exp": 1492882042,
  "iat": 1492795642,
  "at_hash": "bi96gOXZShvlWYtal9Eqiw",
  "email": "jane.doe@coreos.com",
  "email_verified": true,
  "groups": [
    "admins",
    "developers"
  ],
  "name": "Jane Doe"
}
```

**Comment by harshavardhana** [comment]
Closing this issue as this is already supported

**Comment by widdix123** [comment]
@harshavardhana  -  Still it is not clear as to what needs to be done 

Not sure what needs to be done below

> First, you need to make sure you have added the policy as part of the custom JWT claim have you done that? @widdix123 without a policy there is no access granted by default.

The env inside pods

```
/ # env|grep MINIO
MINIO_PORT_9000_TCP=tcp://172.20.188.91:9000
MINIO_SERVICE_PORT=9000
MINIO_PORT=tcp://172.20.188.91:9000
MINIO_ACCESS_KEY_FILE=access_key
MINIO_KMS_MASTER_KEY_FILE=kms_master_key
MINIO_SSE_MASTER_KEY_FILE=sse_master_key
MINIO_ACCESS_KEY=xxxxxxxxxxx
MINIO_UPDATE=off
MINIO_IDENTITY_OPENID_CLIENT_ID=xxxxx-app
MINIO_SECRET_KEY_FILE=secret_key
MINIO_PORT_9000_TCP_ADDR=172.20.188.91
MINIO_SERVICE_PORT_HTTP=9000
MINIO_IDENTITY_OPENID_SCOPES=openid,profile,email,groups
MINIO_SECRET_KEY=xxxxxxxx
MINIO_PORT_9000_TCP_PORT=9000
MINIO_IDENTITY_OPENID_CONFIG_URL=https://dex.v5.xxxxx.com/dex/.well-known/openid-configuration
MINIO_PORT_9000_TCP_PROTO=tcp
MINIO_SERVICE_HOST=172.20.188.91
MINIO_IDENTITY_OPENID_CLAIM_NAME=groups
/ #

```

The documents are still not clear as to what policy is required for OIDC groups ? My jwt is similar to sample

**Comment by harshavardhana** [comment]
> The documents are still not clear as to what policy is required for OIDC groups ? My jwt is similar to sample

policy needs to map to the policy created on MinIO using `mc admin policy` MinIO expects that your JWT presents the policy 

### 4. JWT Claims
The access token received is a signed JSON Web Token (JWT). Use a JWT decoder to decode the access token to access the payload of the token that includes following JWT claims:

|Claim Name|Type|Claim Value|
|:--:|:--:|:--:|
|iss| _string_ | The issuer of the JWT. The '> Identity Provider Entity Id ' value of the OAuth2/OpenID Connect Inbound Authentication configuration of the Resident Identity Provider is returned here. |
|aud| _string array_ | The token audience list. The client identifier of the OAuth clients that the JWT is intended for, is sent herewith. |
|azp| _string_ | The authorized party for which the token is issued to. The client identifier of the OAuth client that the token is issued for, is sent herewith. |
|iat| _integer_ |	The token issue time. |
|exp| _integer_ |	The token expiration time. |
|jti| _string_ | Unique identifier for the JWT token. |
|policy| _string_ | Canned policy name to be applied for STS credentials. (Recommended) | 

--> this can be changed using `MINIO_IDENTITY_OPENID_CLAIM_NAME    (string)    JWT canned policy claim name, defaults to "policy"`

**Comment by widdix123** [comment]
@harshavardhana  - I still get this error while creating the jwt policy. Not sure what i am doing wrong here 

_**mc admin policy add v5 listbucketsonly minio.json --json**_

**Policy from jwt**
```
{
  "iss": "https://dex.xxxxx.xxxxx.com/dex",
  "sub": "asdasdfsadfsad",
  "aud": "appp",
  "exp": 1594364798,
  "iat": 1594361198,
  "nonce": "asdfsadfsdfs",
  "at_hash": "2D-asdfsadfsd",
  "email": "agupta@xxxxx.com",
  "email_verified": true,
  "groups": [
    "safdssdfsdf-c74f-4f37-adcb-dc18fd7d2c18",
    "asdfsadfs-801e-4ba0-a369-1a656e67fe41",
    "asdfsadf-2434-49f6-83b3-971f389fbda6",
  ],
  "name": "abhi@xxxxx.com"
}
```

****Error**:**
```
{
 "status": "error",
 "error": {
  "message": "Cannot add new policy",
  "cause": {
   "message": "Policy has invalid resource.",
   "error": {
    "Code": "MalformedPolicy",
    "Message": "Policy has invalid resource.",
    "BucketName": "",
    "Key": "",
    "RequestID": "16204F89CF532747",
    "HostID": "fb434cc7-d0d4-4ccf-b98b-318daf75dc15",
    "Region": ""
   }
  },
  "type": "fatal",
  "sysinfo": {
   "host.arch": "amd64",
   "host.cpus": "4",
   "host.lang": "go1.13.8",
   "host.name": "Abhisheks-MacBook-Pro.local",
   "host.os": "darwin",
   "mem.heap.total": "66 MB",
   "mem.heap.used": "1.3 MB",
   "mem.total": "72 MB",
   "mem.used": "1.3 MB"
  }
 }
}
```

**Comment by harshavardhana** [comment]
@widdix123 this is just a configuration issue, join our slack https://slack.minio.io - these questions are beyond the scope of a github issue
